import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Airport situation expansion (2026-08): raises A1-B2 coverage to 20 dialogues per level.
export const AIRPORT_EXPANSION: Dialogue[] = [
  {
    id: "airport-a1x-cart",
    situationKey: "airport",
    level: "A1",
    title: "Getting a luggage cart",
    lines: [
      { speaker: "여행객", kr: "카트는 어디에 있어요?", en: "Where are the luggage carts?" },
      { speaker: "직원", kr: "저기 기둥 옆에 있어요.", en: "They're over there next to the pillar." },
      { speaker: "여행객", kr: "무료예요?", en: "Are they free?" },
      { speaker: "직원", kr: "네, 무료예요.", en: "Yes, they're free." },
    ],
  },
  {
    id: "airport-a1x-scale",
    situationKey: "airport",
    level: "A1",
    title: "Where to weigh bags",
    lines: [
      { speaker: "여행객", kr: "가방을 어디서 달아요?", en: "Where do I weigh my bag?" },
      { speaker: "직원", kr: "저 저울 위에 올려 주세요.", en: "Please put it on that scale." },
      { speaker: "여행객", kr: "네, 알겠어요.", en: "Okay, got it." },
      { speaker: "직원", kr: "십오 킬로예요. 괜찮아요.", en: "It's 15 kilos. That's fine." },
    ],
  },
  {
    id: "airport-a1x-reprint",
    situationKey: "airport",
    level: "A1",
    title: "Reprinting a boarding pass",
    lines: [
      { speaker: "여행객", kr: "탑승권을 다시 뽑고 싶어요.", en: "I'd like to print my boarding pass again." },
      { speaker: "직원", kr: "여권 좀 보여 주세요.", en: "Please show me your passport." },
      { speaker: "여행객", kr: "여기 있어요.", en: "Here it is." },
      { speaker: "직원", kr: "네, 새로 뽑아 드릴게요.", en: "Okay, I'll print you a new one." },
    ],
  },
  {
    id: "airport-a1x-exchange",
    situationKey: "airport",
    level: "A1",
    title: "Exchanging money",
    lines: [
      { speaker: "여행객", kr: "환전소가 어디예요?", en: "Where's the currency exchange?" },
      { speaker: "직원", kr: "이 층에 있어요.", en: "It's on this floor." },
      { speaker: "여행객", kr: "고마워요.", en: "Thank you." },
      { speaker: "직원", kr: "네, 좋은 여행 되세요.", en: "You're welcome, have a good trip." },
    ],
  },
  {
    id: "airport-a1x-wheelchair",
    situationKey: "airport",
    level: "A1",
    title: "Requesting a wheelchair",
    lines: [
      { speaker: "여행객", kr: "휠체어가 필요해요.", en: "I need a wheelchair." },
      { speaker: "직원", kr: "네, 여기서 기다려 주세요.", en: "Okay, please wait here." },
      { speaker: "여행객", kr: "얼마나 걸려요?", en: "How long will it take?" },
      { speaker: "직원", kr: "오 분쯤 걸려요.", en: "About 5 minutes." },
    ],
  },
  {
    id: "airport-a1x-pet",
    situationKey: "airport",
    level: "A1",
    title: "Traveling with a pet",
    lines: [
      { speaker: "여행객", kr: "강아지랑 같이 타요.", en: "I'm traveling with my dog." },
      { speaker: "직원", kr: "이동장이 있어요?", en: "Do you have a carrier?" },
      { speaker: "여행객", kr: "네, 여기요.", en: "Yes, here it is." },
      { speaker: "직원", kr: "좋아요. 크기가 맞아요.", en: "Good. The size is fine." },
    ],
  },
  {
    id: "airport-a1x-fragile",
    situationKey: "airport",
    level: "A1",
    title: "Fragile sticker on a bag",
    lines: [
      { speaker: "여행객", kr: "이 가방은 깨지기 쉬워요.", en: "This bag has fragile items." },
      { speaker: "직원", kr: "스티커를 붙여 드릴게요.", en: "I'll put a fragile sticker on it." },
      { speaker: "여행객", kr: "감사해요.", en: "Thank you." },
      { speaker: "직원", kr: "조심히 다룰게요.", en: "We'll handle it carefully." },
    ],
  },
  {
    id: "airport-a1x-lounge",
    situationKey: "airport",
    level: "A1",
    title: "Asking about lounge access",
    lines: [
      { speaker: "여행객", kr: "라운지는 어디예요?", en: "Where's the lounge?" },
      { speaker: "직원", kr: "삼 층에 있어요.", en: "It's on the third floor." },
      { speaker: "여행객", kr: "표가 필요해요?", en: "Do I need a ticket?" },
      { speaker: "직원", kr: "네, 탑승권을 보여 주세요.", en: "Yes, please show your boarding pass." },
    ],
  },
  {
    id: "airport-a1x-meal",
    situationKey: "airport",
    level: "A1",
    title: "Choosing a meal on board",
    lines: [
      { speaker: "승무원", kr: "식사는 닭고기와 생선이 있어요.", en: "For the meal, we have chicken or fish." },
      { speaker: "승객", kr: "닭고기 주세요.", en: "I'll have the chicken, please." },
      { speaker: "승무원", kr: "음료는 뭐 드릴까요?", en: "What would you like to drink?" },
      { speaker: "승객", kr: "물 주세요.", en: "Water, please." },
    ],
  },
  {
    id: "airport-a1x-lostpass",
    situationKey: "airport",
    level: "A1",
    title: "Lost boarding pass",
    lines: [
      { speaker: "여행객", kr: "탑승권을 잃어버렸어요.", en: "I lost my boarding pass." },
      { speaker: "직원", kr: "여권 있어요?", en: "Do you have your passport?" },
      { speaker: "여행객", kr: "네, 여기요.", en: "Yes, here it is." },
      { speaker: "직원", kr: "다시 만들어 드릴게요.", en: "I'll make you a new one." },
    ],
  },
  {
    id: "airport-a1x-arrival",
    situationKey: "airport",
    level: "A1",
    title: "Finding the pickup point",
    lines: [
      { speaker: "여행객", kr: "픽업 장소가 어디예요?", en: "Where's the pickup point?" },
      { speaker: "직원", kr: "일 번 출구예요.", en: "It's exit number 1." },
      { speaker: "여행객", kr: "여기서 멀어요?", en: "Is it far from here?" },
      { speaker: "직원", kr: "아니요, 가까워요.", en: "No, it's close." },
    ],
  },
  {
    id: "airport-a1x-taxfree",
    situationKey: "airport",
    level: "A1",
    title: "Finding the tax refund counter",
    lines: [
      { speaker: "여행객", kr: "환급 창구가 어디예요?", en: "Where's the tax refund counter?" },
      { speaker: "직원", kr: "저쪽 이십 번 창구예요.", en: "It's counter 20 over there." },
      { speaker: "여행객", kr: "줄이 길어요?", en: "Is the line long?" },
      { speaker: "직원", kr: "지금은 짧아요.", en: "It's short right now." },
    ],
  },
  {
    id: "airport-a1x-charge",
    situationKey: "airport",
    level: "A1",
    title: "Finding a phone charger",
    lines: [
      { speaker: "여행객", kr: "충전기 있어요?", en: "Do you have a phone charger?" },
      { speaker: "직원", kr: "저기 의자 옆에 있어요.", en: "There's one next to the chairs over there." },
      { speaker: "여행객", kr: "고마워요.", en: "Thank you." },
      { speaker: "직원", kr: "네, 편히 쓰세요.", en: "You're welcome, feel free to use it." },
    ],
  },
  {
    id: "airport-a1x-elevator",
    situationKey: "airport",
    level: "A1",
    title: "Finding the elevator",
    lines: [
      { speaker: "여행객", kr: "엘리베이터가 어디예요?", en: "Where's the elevator?" },
      { speaker: "직원", kr: "왼쪽으로 가세요.", en: "Go to the left." },
      { speaker: "여행객", kr: "네, 알겠어요.", en: "Okay, got it." },
      { speaker: "직원", kr: "금방 보여요.", en: "You'll see it right away." },
    ],
  },
  {
    id: "airport-a1x-luggage-tag",
    situationKey: "airport",
    level: "A1",
    title: "Getting a luggage tag",
    lines: [
      { speaker: "여행객", kr: "짐표를 받고 싶어요.", en: "I'd like a luggage tag." },
      { speaker: "직원", kr: "가방 이름을 써 주세요.", en: "Please write your name on the bag." },
      { speaker: "여행객", kr: "여기 썼어요.", en: "I wrote it here." },
      { speaker: "직원", kr: "네, 태그 붙였어요.", en: "Okay, the tag is attached." },
    ],
  },
  {
    id: "airport-a2x-scale-heavy",
    situationKey: "airport",
    level: "A2",
    title: "Bag is over the weight limit",
    lines: [
      { speaker: "직원", kr: "가방이 이십삼 킬로가 넘었어요.", en: "Your bag is over 23 kilos." },
      { speaker: "여행객", kr: "얼마나 넘었어요?", en: "How much over is it?" },
      { speaker: "직원", kr: "삼 킬로 넘었어요.", en: "It's 3 kilos over." },
      { speaker: "여행객", kr: "가방에서 좀 뺄게요.", en: "I'll take some things out of the bag." },
      { speaker: "직원", kr: "네, 여기서 빼셔도 돼요.", en: "Yes, you can take them out here." },
    ],
  },
  {
    id: "airport-a2x-lounge-buy",
    situationKey: "airport",
    level: "A2",
    title: "Buying a day pass for the lounge",
    lines: [
      { speaker: "여행객", kr: "라운지 일일권을 사고 싶어요.", en: "I'd like to buy a day pass for the lounge." },
      { speaker: "직원", kr: "카드로 결제할 거예요?", en: "Will you pay by card?" },
      { speaker: "여행객", kr: "네, 카드로 할게요.", en: "Yes, I'll pay by card." },
      { speaker: "직원", kr: "가격은 삼만 원이에요.", en: "The price is 30,000 won." },
      { speaker: "여행객", kr: "알겠어요, 결제할게요.", en: "Okay, I'll pay." },
    ],
  },
  {
    id: "airport-a2x-minor",
    situationKey: "airport",
    level: "A2",
    title: "Unaccompanied minor service",
    lines: [
      { speaker: "직원", kr: "아이 혼자 타는 거 맞죠?", en: "Your child is flying alone, right?" },
      { speaker: "학부모", kr: "네, 맞아요.", en: "Yes, that's right." },
      { speaker: "직원", kr: "서류를 작성해 주세요.", en: "Please fill out this form." },
      { speaker: "학부모", kr: "누가 아이를 데려다줘요?", en: "Who will take my child there?" },
      { speaker: "직원", kr: "저희 직원이 게이트까지 데려다줘요.", en: "Our staff will take her to the gate." },
    ],
  },
  {
    id: "airport-a2x-pet-cabin",
    situationKey: "airport",
    level: "A2",
    title: "Pet in the cabin",
    lines: [
      { speaker: "여행객", kr: "고양이를 기내에 데려가고 싶어요.", en: "I'd like to bring my cat into the cabin." },
      { speaker: "직원", kr: "예약할 때 신청하셨어요?", en: "Did you apply when you booked?" },
      { speaker: "여행객", kr: "네, 신청했어요.", en: "Yes, I applied." },
      { speaker: "직원", kr: "그럼 이동장을 확인할게요.", en: "Then I'll check the carrier." },
      { speaker: "여행객", kr: "여기 있어요.", en: "Here it is." },
    ],
  },
  {
    id: "airport-a2x-exchange-rate",
    situationKey: "airport",
    level: "A2",
    title: "Asking about the exchange rate",
    lines: [
      { speaker: "여행객", kr: "오늘 환율이 얼마예요?", en: "What's today's exchange rate?" },
      { speaker: "직원", kr: "천삼백 원이에요.", en: "It's 1,300 won." },
      { speaker: "여행객", kr: "백 달러 바꿀게요.", en: "I'll exchange 100 dollars." },
      { speaker: "직원", kr: "수수료가 좀 있어요.", en: "There's a small fee." },
      { speaker: "여행객", kr: "괜찮아요, 바꿔 주세요.", en: "That's fine, please exchange it." },
    ],
  },
  {
    id: "airport-a2x-gate-question",
    situationKey: "airport",
    level: "A2",
    title: "Asking about a gate change",
    lines: [
      { speaker: "여행객", kr: "방금 게이트가 바뀌었어요?", en: "Did the gate just change?" },
      { speaker: "직원", kr: "네, 삼십오 번으로 바뀌었어요.", en: "Yes, it changed to gate 35." },
      { speaker: "여행객", kr: "여기서 멀어요?", en: "Is it far from here?" },
      { speaker: "직원", kr: "네, 조금 걸어야 해요.", en: "Yes, you'll need to walk a bit." },
      { speaker: "여행객", kr: "빨리 가야겠네요.", en: "I should hurry then." },
    ],
  },
  {
    id: "airport-a2x-rebook",
    situationKey: "airport",
    level: "A2",
    title: "Rebooking after a cancellation",
    lines: [
      { speaker: "여행객", kr: "제 비행기가 취소됐어요.", en: "My flight got canceled." },
      { speaker: "직원", kr: "확인했어요. 다음 편으로 바꿔 드릴게요.", en: "I see. I'll change you to the next flight." },
      { speaker: "여행객", kr: "언제 출발해요?", en: "When does it leave?" },
      { speaker: "직원", kr: "오후 세 시에 출발해요.", en: "It leaves at 3 p.m." },
      { speaker: "여행객", kr: "네, 그걸로 할게요.", en: "Okay, I'll take that one." },
    ],
  },
  {
    id: "airport-a2x-fragile-fee",
    situationKey: "airport",
    level: "A2",
    title: "Extra fee for fragile handling",
    lines: [
      { speaker: "직원", kr: "이 가방은 특수 포장이 필요해요.", en: "This bag needs special packaging." },
      { speaker: "여행객", kr: "돈이 더 들어요?", en: "Does that cost extra?" },
      { speaker: "직원", kr: "네, 오천 원 정도 들어요.", en: "Yes, it costs about 5,000 won." },
      { speaker: "여행객", kr: "그럼 포장해 주세요.", en: "Then please pack it." },
      { speaker: "직원", kr: "네, 지금 해 드릴게요.", en: "Okay, I'll do it now." },
    ],
  },
  {
    id: "airport-a2x-arrival-sign",
    situationKey: "airport",
    level: "A2",
    title: "Making a pickup sign",
    lines: [
      { speaker: "여행객", kr: "친구를 마중 나왔어요.", en: "I'm here to pick up a friend." },
      { speaker: "직원", kr: "이름을 쓴 팻말이 있어요?", en: "Do you have a sign with the name?" },
      { speaker: "여행객", kr: "아니요, 아직 안 만들었어요.", en: "No, I haven't made one yet." },
      { speaker: "직원", kr: "저쪽 매점에서 종이를 팔아요.", en: "The kiosk over there sells paper." },
      { speaker: "여행객", kr: "고마워요, 가 볼게요.", en: "Thanks, I'll go check." },
    ],
  },
  {
    id: "airport-a2x-charger-borrow",
    situationKey: "airport",
    level: "A2",
    title: "Borrowing a portable charger",
    lines: [
      { speaker: "여행객", kr: "보조 배터리를 빌릴 수 있어요?", en: "Can I borrow a portable charger?" },
      { speaker: "직원", kr: "네, 카드를 등록하면 빌려드려요.", en: "Yes, if you register a card, we'll lend one." },
      { speaker: "여행객", kr: "언제까지 반납해요?", en: "When do I need to return it?" },
      { speaker: "직원", kr: "탑승 전까지 반납해 주세요.", en: "Please return it before boarding." },
      { speaker: "여행객", kr: "알겠어요, 감사해요.", en: "Got it, thank you." },
    ],
  },
  {
    id: "airport-a2x-meal-special",
    situationKey: "airport",
    level: "A2",
    title: "Special meal request",
    lines: [
      { speaker: "여행객", kr: "채식 식사를 신청하고 싶어요.", en: "I'd like to request a vegetarian meal." },
      { speaker: "직원", kr: "언제 탑승하세요?", en: "When are you flying?" },
      { speaker: "여행객", kr: "내일 오전 열 시요.", en: "Tomorrow at 10 a.m." },
      { speaker: "직원", kr: "지금 신청하면 준비될 거예요.", en: "If you request now, it'll be ready." },
      { speaker: "여행객", kr: "네, 신청해 주세요.", en: "Yes, please request it." },
    ],
  },
  {
    id: "airport-a2x-lostpass-reissue",
    situationKey: "airport",
    level: "A2",
    title: "Reissuing a lost boarding pass at the gate",
    lines: [
      { speaker: "여행객", kr: "탑승권을 잃어버려서 게이트를 못 찾겠어요.", en: "I lost my boarding pass and can't find my gate." },
      { speaker: "직원", kr: "성함이랑 항공편을 말해 주세요.", en: "Please tell me your name and flight number." },
      { speaker: "여행객", kr: "김민수이고, 케이이백일 편이에요.", en: "Kim Minsu, flight KE201." },
      { speaker: "직원", kr: "찾았어요. 새로 뽑아 드릴게요.", en: "Found it. I'll print you a new one." },
      { speaker: "여행객", kr: "정말 감사해요.", en: "Thank you so much." },
    ],
  },
  {
    id: "airport-a2x-wheelchair-time",
    situationKey: "airport",
    level: "A2",
    title: "Scheduling wheelchair assistance",
    lines: [
      { speaker: "여행객", kr: "어머니께 휠체어가 필요해요.", en: "My mother needs a wheelchair." },
      { speaker: "직원", kr: "몇 시 비행기세요?", en: "What time is her flight?" },
      { speaker: "여행객", kr: "오후 두 시예요.", en: "2 p.m." },
      { speaker: "직원", kr: "한 시간 전에 여기로 다시 오세요.", en: "Please come back here an hour before." },
      { speaker: "여행객", kr: "네, 그렇게 할게요.", en: "Okay, I'll do that." },
    ],
  },
  {
    id: "airport-a2x-cart-return",
    situationKey: "airport",
    level: "A2",
    title: "Returning a luggage cart",
    lines: [
      { speaker: "여행객", kr: "이 카트는 어디에 반납해요?", en: "Where do I return this cart?" },
      { speaker: "직원", kr: "저쪽 카트 보관소에 놓으시면 돼요.", en: "You can leave it at the cart area over there." },
      { speaker: "여행객", kr: "동전을 다시 받을 수 있어요?", en: "Can I get my coin back?" },
      { speaker: "직원", kr: "네, 반납하면 자동으로 나와요.", en: "Yes, it comes out automatically when you return it." },
      { speaker: "여행객", kr: "알겠어요, 고마워요.", en: "Got it, thank you." },
    ],
  },
  {
    id: "airport-a2x-taxfree-form",
    situationKey: "airport",
    level: "A2",
    title: "Filling out a tax refund form",
    lines: [
      { speaker: "여행객", kr: "환급 서류를 어떻게 써요?", en: "How do I fill out the refund form?" },
      { speaker: "직원", kr: "여권 번호랑 카드 번호를 적어 주세요.", en: "Please write your passport number and card number." },
      { speaker: "여행객", kr: "이렇게 쓰면 돼요?", en: "Is this how I write it?" },
      { speaker: "직원", kr: "네, 맞아요. 서명도 해 주세요.", en: "Yes, that's right. Please sign it too." },
      { speaker: "여행객", kr: "다 됐어요.", en: "All done." },
    ],
  },
  {
    id: "airport-b1x-taxfree-negotiate",
    situationKey: "airport",
    level: "B1",
    title: "Overweight baggage fee negotiation",
    lines: [
      { speaker: "직원", kr: "가방이 오 킬로 초과돼서 추가 요금이 나와요.", en: "Your bag is 5 kilos over, so there's an extra fee." },
      { speaker: "여행객", kr: "얼마나 나와요?", en: "How much is it?" },
      { speaker: "직원", kr: "육만 원 정도예요.", en: "It's about 60,000 won." },
      { speaker: "여행객", kr: "너무 비싸네요. 짐을 좀 옮기면 안 될까요?", en: "That's too expensive. Can I move some items around?" },
      { speaker: "직원", kr: "다른 가방이 있으면 나눠서 넣으셔도 돼요.", en: "If you have another bag, you can split them up." },
      { speaker: "여행객", kr: "네, 잠깐 정리해 볼게요.", en: "Okay, let me sort it out for a moment." },
      { speaker: "직원", kr: "천천히 하세요, 시간 있어요.", en: "Take your time, there's time." },
    ],
  },
  {
    id: "airport-b1x-lounge-guest",
    situationKey: "airport",
    level: "B1",
    title: "Bringing a guest into the lounge",
    lines: [
      { speaker: "여행객", kr: "일행이랑 같이 라운지에 들어가고 싶은데요.", en: "I'd like to bring a companion into the lounge." },
      { speaker: "직원", kr: "동반 이용 조건이 있는지 확인해 볼게요.", en: "Let me check if there's a guest privilege." },
      { speaker: "여행객", kr: "제 카드는 프리미엄 카드예요.", en: "My card is a premium card." },
      { speaker: "직원", kr: "그러면 한 분까지 무료로 동반 가능해요.", en: "In that case, you can bring one guest for free." },
      { speaker: "여행객", kr: "다행이네요. 감사합니다.", en: "That's a relief. Thank you." },
      { speaker: "직원", kr: "카드랑 탑승권 보여 주세요.", en: "Please show me your card and boarding pass." },
      { speaker: "여행객", kr: "여기 있어요.", en: "Here you go." },
    ],
  },
  {
    id: "airport-b1x-minor-pickup",
    situationKey: "airport",
    level: "B1",
    title: "Confirming who will pick up a minor",
    lines: [
      { speaker: "직원", kr: "도착지에서 누가 아이를 데리러 오세요?", en: "Who is picking up your child at the arrival airport?" },
      { speaker: "학부모", kr: "아이 삼촌이 데리러 올 거예요.", en: "The child's uncle will be picking her up." },
      { speaker: "직원", kr: "그분 신분증 사본이 필요해요.", en: "We'll need a copy of his ID." },
      { speaker: "학부모", kr: "미리 이메일로 보냈는데 확인해 주시겠어요?", en: "I sent it by email in advance—could you check?" },
      { speaker: "직원", kr: "네, 잠시만요. 확인됐어요.", en: "Yes, one moment. It's confirmed." },
      { speaker: "학부모", kr: "다행이네요. 아이가 걱정이 많아서요.", en: "That's a relief. My daughter is quite worried." },
      { speaker: "직원", kr: "저희 직원이 끝까지 함께할 거예요.", en: "Our staff will be with her the whole way." },
    ],
  },
  {
    id: "airport-b1x-pet-vaccine",
    situationKey: "airport",
    level: "B1",
    title: "Missing pet vaccination record",
    lines: [
      { speaker: "직원", kr: "예방 접종 증명서를 가지고 계세요?", en: "Do you have the vaccination certificate?" },
      { speaker: "여행객", kr: "아, 집에 두고 온 것 같아요.", en: "Oh, I think I left it at home." },
      { speaker: "직원", kr: "그럼 반려동물을 태울 수 없어요.", en: "Then we can't board your pet." },
      { speaker: "여행객", kr: "휴대폰에 사진이 있는데 이걸로 안 될까요?", en: "I have a photo on my phone—would that work?" },
      { speaker: "직원", kr: "잠시 확인해 볼게요. 사진 보내 주세요.", en: "Let me check for a moment. Please send the photo." },
      { speaker: "여행객", kr: "지금 보냈어요.", en: "I just sent it." },
      { speaker: "직원", kr: "확인됐어요. 이번에는 통과해 드릴게요.", en: "It's confirmed. We'll let it pass this time." },
    ],
  },
  {
    id: "airport-b1x-exchange-large",
    situationKey: "airport",
    level: "B1",
    title: "Exchanging a large amount of cash",
    lines: [
      { speaker: "여행객", kr: "이천 달러를 원화로 바꾸고 싶어요.", en: "I'd like to exchange 2,000 dollars for won." },
      { speaker: "직원", kr: "큰 금액이라 신분증이 필요해요.", en: "Since it's a large amount, we'll need ID." },
      { speaker: "여행객", kr: "여권으로 되나요?", en: "Will a passport work?" },
      { speaker: "직원", kr: "네, 여권이면 충분해요.", en: "Yes, a passport is enough." },
      { speaker: "여행객", kr: "수수료는 얼마나 돼요?", en: "How much is the fee?" },
      { speaker: "직원", kr: "이 프로 정도 붙어요.", en: "It's about 2 percent." },
      { speaker: "여행객", kr: "알겠어요, 바꿔 주세요.", en: "Okay, please exchange it." },
    ],
  },
  {
    id: "airport-b1x-rebook-hotel",
    situationKey: "airport",
    level: "B1",
    title: "Rebooking and asking about a hotel voucher",
    lines: [
      { speaker: "여행객", kr: "제 항공편이 취소돼서 다음 날 아침 편으로 바뀌었어요.", en: "My flight got canceled and moved to the next morning." },
      { speaker: "직원", kr: "네, 확인했습니다. 불편을 드려 죄송해요.", en: "Yes, I see it. Sorry for the inconvenience." },
      { speaker: "여행객", kr: "그럼 오늘 밤 호텔은 어떻게 해요?", en: "Then what about tonight's hotel?" },
      { speaker: "직원", kr: "저희가 호텔 바우처를 드릴 수 있어요.", en: "We can give you a hotel voucher." },
      { speaker: "여행객", kr: "공항에서 가까운 곳인가요?", en: "Is it close to the airport?" },
      { speaker: "직원", kr: "네, 셔틀버스로 십 분 거리예요.", en: "Yes, it's a 10-minute shuttle ride away." },
      { speaker: "여행객", kr: "좋아요, 그걸로 부탁해요.", en: "Great, I'll take that, please." },
    ],
  },
  {
    id: "airport-b1x-lost-belt",
    situationKey: "airport",
    level: "B1",
    title: "Item left at the security tray",
    lines: [
      { speaker: "여행객", kr: "검색대에 벨트를 두고 온 것 같아요.", en: "I think I left my belt at the security tray." },
      { speaker: "직원", kr: "언제쯤 지나셨어요?", en: "About when did you go through?" },
      { speaker: "여행객", kr: "십 분 전쯤이요.", en: "About 10 minutes ago." },
      { speaker: "직원", kr: "잠깐만요, 무전으로 확인해 볼게요.", en: "One moment, I'll check by radio." },
      { speaker: "여행객", kr: "네, 부탁드려요.", en: "Yes, please." },
      { speaker: "직원", kr: "찾았대요. 다시 검색대로 가시면 돼요.", en: "They found it. You can go back to the checkpoint." },
      { speaker: "여행객", kr: "정말 다행이에요, 감사해요.", en: "What a relief, thank you." },
    ],
  },
  {
    id: "airport-b1x-arrival-late",
    situationKey: "airport",
    level: "B1",
    title: "Pickup driver running late",
    lines: [
      { speaker: "여행객", kr: "저를 데리러 올 기사님이 안 보여요.", en: "The driver who's supposed to pick me up isn't here." },
      { speaker: "직원", kr: "예약 확인서가 있으세요?", en: "Do you have your booking confirmation?" },
      { speaker: "여행객", kr: "네, 휴대폰에 있어요.", en: "Yes, it's on my phone." },
      { speaker: "직원", kr: "회사에 전화해서 확인해 볼게요.", en: "I'll call the company to check." },
      { speaker: "여행객", kr: "네, 부탁드려요.", en: "Yes, please." },
      { speaker: "직원", kr: "십 분 뒤에 도착한대요.", en: "They say the driver will arrive in 10 minutes." },
      { speaker: "여행객", kr: "알겠어요, 여기서 기다릴게요.", en: "Okay, I'll wait here." },
    ],
  },
  {
    id: "airport-b1x-gate-far",
    situationKey: "airport",
    level: "B1",
    title: "Gate changed to a far terminal",
    lines: [
      { speaker: "여행객", kr: "방송에서 게이트가 바뀌었다고 들었는데 맞아요?", en: "I heard on the announcement that the gate changed—is that right?" },
      { speaker: "직원", kr: "네, 다른 터미널로 옮겨졌어요.", en: "Yes, it's been moved to a different terminal." },
      { speaker: "여행객", kr: "거기까지 얼마나 걸려요?", en: "How long does it take to get there?" },
      { speaker: "직원", kr: "셔틀 타면 십오 분 정도 걸려요.", en: "By shuttle, it takes about 15 minutes." },
      { speaker: "여행객", kr: "지금 바로 가야겠네요.", en: "I should go right now." },
      { speaker: "직원", kr: "네, 셔틀은 저쪽에서 타요.", en: "Yes, you catch the shuttle over there." },
      { speaker: "여행객", kr: "감사해요, 서둘러야겠어요.", en: "Thanks, I'd better hurry." },
    ],
  },
  {
    id: "airport-b1x-fragile-refuse",
    situationKey: "airport",
    level: "B1",
    title: "Fragile item the airline won't check",
    lines: [
      { speaker: "직원", kr: "이 도자기는 위탁 수하물로 못 받아요.", en: "We can't accept this pottery as checked baggage." },
      { speaker: "여행객", kr: "왜 안 되는 거예요?", en: "Why not?" },
      { speaker: "직원", kr: "너무 깨지기 쉬워서 저희 규정에 안 맞아요.", en: "It's too fragile and doesn't meet our policy." },
      { speaker: "여행객", kr: "그럼 기내에 들고 타도 될까요?", en: "Then can I carry it on board?" },
      { speaker: "직원", kr: "크기가 맞으면 가능해요.", en: "If the size fits, yes." },
      { speaker: "여행객", kr: "확인해 볼게요.", en: "Let me check the size." },
      { speaker: "직원", kr: "저기 사이즈 틀에 넣어 보세요.", en: "Try putting it in the sizer over there." },
    ],
  },
  {
    id: "airport-b1x-meal-allergy",
    situationKey: "airport",
    level: "B1",
    title: "Meal allergy request at check-in",
    lines: [
      { speaker: "여행객", kr: "땅콩 알레르기가 있는데 기내식에 반영될까요?", en: "I have a peanut allergy—will that be reflected in the meal?" },
      { speaker: "직원", kr: "예약할 때 신청 안 하셨어요?", en: "Didn't you request it when booking?" },
      { speaker: "여행객", kr: "깜빡했어요. 지금이라도 될까요?", en: "I forgot. Is it possible even now?" },
      { speaker: "직원", kr: "출발까지 두 시간 남아서 가능할 것 같아요.", en: "There's 2 hours until departure, so it should be possible." },
      { speaker: "여행객", kr: "정말요? 다행이에요.", en: "Really? What a relief." },
      { speaker: "직원", kr: "지금 바로 요청 넣어 드릴게요.", en: "I'll put in the request right now." },
      { speaker: "여행객", kr: "감사해요, 정말로.", en: "Thank you so much." },
    ],
  },
  {
    id: "airport-b1x-lounge-full",
    situationKey: "airport",
    level: "B1",
    title: "Lounge is full",
    lines: [
      { speaker: "여행객", kr: "라운지에 들어가고 싶은데요.", en: "I'd like to go into the lounge." },
      { speaker: "직원", kr: "죄송하지만 지금 자리가 다 찼어요.", en: "I'm sorry, but it's full right now." },
      { speaker: "여행객", kr: "얼마나 기다려야 해요?", en: "How long do I need to wait?" },
      { speaker: "직원", kr: "보통 이십 분 정도 걸려요.", en: "It usually takes about 20 minutes." },
      { speaker: "여행객", kr: "그럼 기다렸다가 다시 올게요.", en: "Then I'll wait and come back." },
      { speaker: "직원", kr: "번호표를 드릴게요.", en: "I'll give you a number ticket." },
      { speaker: "여행객", kr: "네, 감사해요.", en: "Okay, thank you." },
    ],
  },
  {
    id: "airport-b1x-cart-crowded",
    situationKey: "airport",
    level: "B1",
    title: "No carts left at check-in",
    lines: [
      { speaker: "여행객", kr: "카트가 하나도 안 보이는데 다 나갔나요?", en: "I don't see any carts—are they all taken?" },
      { speaker: "직원", kr: "네, 아침에 사람이 많아서 지금 부족해요.", en: "Yes, it's been busy this morning so we're short right now." },
      { speaker: "여행객", kr: "짐이 많아서 카트 없이는 힘든데요.", en: "I have a lot of luggage, so it's hard without one." },
      { speaker: "여행객", kr: "언제쯤 더 들어와요?", en: "When will more come in?" },
      { speaker: "직원", kr: "직원이 지금 회수하러 나갔으니 곧 올 거예요.", en: "A staff member just went out to collect them, so they'll be here soon." },
      { speaker: "여행객", kr: "그럼 여기서 좀 기다려 볼게요.", en: "Then I'll wait here for a bit." },
      { speaker: "직원", kr: "보이는 대로 바로 가져다드릴게요.", en: "I'll bring one to you as soon as I see one." },
    ],
  },
  {
    id: "airport-b1x-lounge-time",
    situationKey: "airport",
    level: "B1",
    title: "How long can you stay in the lounge",
    lines: [
      { speaker: "여행객", kr: "라운지는 얼마나 오래 있을 수 있어요?", en: "How long can I stay in the lounge?" },
      { speaker: "직원", kr: "탑승 시작 전까지는 자유롭게 계셔도 돼요.", en: "You're free to stay until boarding begins." },
      { speaker: "여행객", kr: "제 비행기가 세 시간 뒤라서 오래 있을 것 같아요.", en: "My flight is in 3 hours, so I'll probably be here a while." },
      { speaker: "직원", kr: "괜찮아요, 시간 제한은 없어요.", en: "That's fine, there's no time limit." },
      { speaker: "여행객", kr: "그럼 샤워실도 이용할 수 있어요?", en: "Then can I also use the shower room?" },
      { speaker: "직원", kr: "네, 예약만 하시면 이용 가능해요.", en: "Yes, you can use it if you just make a reservation." },
      { speaker: "여행객", kr: "좋네요, 지금 예약할게요.", en: "That's great, I'll reserve one now." },
    ],
  },
  {
    id: "airport-b1x-meal-vegetarian-limited",
    situationKey: "airport",
    level: "B1",
    title: "Vegetarian meal already ran out",
    lines: [
      { speaker: "승무원", kr: "죄송하지만 채식 식사가 다 나갔어요.", en: "I'm sorry, but the vegetarian meal has run out." },
      { speaker: "승객", kr: "네? 미리 신청했는데요.", en: "What? I requested it in advance." },
      { speaker: "승무원", kr: "예약 내역을 확인해 볼게요, 잠시만요.", en: "Let me check the reservation record, one moment." },
      { speaker: "승객", kr: "네, 확인 부탁드려요.", en: "Yes, please check." },
      { speaker: "승무원", kr: "죄송해요, 시스템에 반영이 안 됐네요.", en: "I'm sorry, it wasn't reflected in the system." },
      { speaker: "승객", kr: "그럼 지금 먹을 수 있는 게 있어요?", en: "Then is there anything I can eat now?" },
      { speaker: "승무원", kr: "과일이랑 샐러드는 드릴 수 있어요.", en: "I can give you fruit and salad." },
    ],
  },
  {
    id: "airport-b1x-exchange-closed",
    situationKey: "airport",
    level: "B1",
    title: "Exchange counter closing soon",
    lines: [
      { speaker: "여행객", kr: "환전소가 몇 시까지 열어요?", en: "Until what time is the exchange counter open?" },
      { speaker: "직원", kr: "저녁 여덟 시까지예요. 이제 이십 분 남았어요.", en: "Until 8 p.m. There's only 20 minutes left now." },
      { speaker: "여행객", kr: "그럼 빨리 처리할 수 있어요?", en: "Then can we do this quickly?" },
      { speaker: "직원", kr: "네, 얼마나 바꾸실 거예요?", en: "Yes, how much would you like to exchange?" },
      { speaker: "여행객", kr: "삼백 달러요.", en: "300 dollars." },
      { speaker: "직원", kr: "네, 지금 바로 처리해 드릴게요.", en: "Okay, I'll process it right away." },
      { speaker: "여행객", kr: "감사해요, 시간 맞춰서 다행이에요.", en: "Thank you, I'm glad I made it in time." },
    ],
  },
  {
    id: "airport-b2x-cart-broken",
    situationKey: "airport",
    level: "B2",
    title: "Broken luggage cart at check-in",
    lines: [
      { speaker: "여행객", kr: "카트 바퀴가 하나 빠진 것 같아요. 계속 한쪽으로 쏠려요.", en: "One of the cart wheels seems to have come off. It keeps pulling to one side." },
      { speaker: "직원", kr: "아, 죄송해요. 새 카트로 바꿔 드릴게요.", en: "Oh, I'm sorry. I'll get you a new cart." },
      { speaker: "여행객", kr: "짐을 다시 옮겨야 하는데 좀 도와주실 수 있어요?", en: "I need to move my luggage again—could you help?" },
      { speaker: "직원", kr: "네, 제가 옮겨 드릴게요.", en: "Yes, I'll move it for you." },
      { speaker: "여행객", kr: "감사해요. 시간이 별로 없어서 걱정이었어요.", en: "Thank you. I was worried since I don't have much time." },
      { speaker: "직원", kr: "체크인까지 아직 시간 여유 있으니 걱정 마세요.", en: "There's still plenty of time before check-in closes, so don't worry." },
      { speaker: "여행객", kr: "그럼 좀 안심이 되네요.", en: "That's a bit of a relief, then." },
    ],
  },
  {
    id: "airport-b2x-taxfree-deadline",
    situationKey: "airport",
    level: "B2",
    title: "Tax refund deadline dispute",
    lines: [
      { speaker: "여행객", kr: "이 영수증도 환급 받을 수 있나요? 산 지 좀 됐는데요.", en: "Can I get a refund on this receipt too? It's been a while since I bought it." },
      { speaker: "직원", kr: "언제 구매하셨어요?", en: "When did you purchase it?" },
      { speaker: "여행객", kr: "삼 주 전이요. 날짜가 좀 애매하네요.", en: "Three weeks ago. The timing is a bit borderline." },
      { speaker: "직원", kr: "저희 규정은 구매 후 삼 개월 이내까지예요.", en: "Our policy is within 3 months of purchase." },
      { speaker: "여행객", kr: "아, 그럼 아직 괜찮은 거네요.", en: "Oh, then it should still be fine." },
      { speaker: "직원", kr: "네, 여권이랑 영수증 원본만 주시면 돼요.", en: "Yes, just give me your passport and the original receipt." },
      { speaker: "여행객", kr: "여기 있어요. 확인해 주세요.", en: "Here you go. Please check them." },
    ],
  },
  {
    id: "airport-b2x-pet-weather",
    situationKey: "airport",
    level: "B2",
    title: "Pet cargo restricted due to weather",
    lines: [
      { speaker: "직원", kr: "오늘 날씨 때문에 화물칸 반려동물 운송이 제한될 수 있어요.", en: "Because of today's weather, pet cargo transport may be restricted." },
      { speaker: "여행객", kr: "그게 무슨 말이에요? 못 태운다는 거예요?", en: "What does that mean—that my pet can't fly?" },
      { speaker: "직원", kr: "기온이 너무 높아서 안전 문제로 재검토 중이에요.", en: "The temperature is too high, so it's under review for safety reasons." },
      { speaker: "여행객", kr: "언제쯤 결정이 나요? 저는 곧 탑승해야 하는데요.", en: "When will they decide? I need to board soon." },
      { speaker: "직원", kr: "탑승 삼십 분 전까지는 알려 드릴게요.", en: "We'll let you know by 30 minutes before boarding." },
      { speaker: "여행객", kr: "만약 안 되면 어떻게 해야 하죠?", en: "If it's not allowed, what should I do?" },
      { speaker: "직원", kr: "그럴 경우 다음 편으로 무료 변경해 드릴게요.", en: "In that case, we'll change you to the next flight for free." },
    ],
  },
  {
    id: "airport-b2x-exchange-fake",
    situationKey: "airport",
    level: "B2",
    title: "Suspected counterfeit bill at exchange",
    lines: [
      { speaker: "직원", kr: "죄송한데 이 지폐는 저희 기계에서 인식이 안 돼요.", en: "I'm sorry, but this bill isn't being recognized by our machine." },
      { speaker: "여행객", kr: "정말요? 은행에서 받은 건데 이상하네요.", en: "Really? That's strange—I got it from a bank." },
      { speaker: "직원", kr: "다른 지폐로 바꿔 주실 수 있으세요?", en: "Could you exchange it for a different bill?" },
      { speaker: "여행객", kr: "지금은 이것밖에 없어요. 어떻게 해야 하죠?", en: "This is all I have right now. What should I do?" },
      { speaker: "직원", kr: "일단 이 지폐는 빼고 나머지 금액만 환전해 드릴게요.", en: "For now, I'll exclude this bill and exchange only the rest." },
      { speaker: "여행객", kr: "그럼 이 지폐는 어떻게 하죠?", en: "Then what do I do with this bill?" },
      { speaker: "직원", kr: "은행 창구에서 다시 확인해 보시는 게 좋을 거예요.", en: "It would be best to check it again at a bank counter." },
    ],
  },
  {
    id: "airport-b2x-rebook-connection",
    situationKey: "airport",
    level: "B2",
    title: "Rebooking that breaks a hotel reservation",
    lines: [
      { speaker: "여행객", kr: "다음 편으로 바꿔 주신다고 했는데 그럼 밤늦게 도착하잖아요.", en: "You said you'd change me to the next flight, but that means arriving very late at night." },
      { speaker: "직원", kr: "네, 죄송하지만 오늘은 그 편밖에 자리가 없어요.", en: "Yes, I'm sorry, but that's the only seat available today." },
      { speaker: "여행객", kr: "호텔 체크인 시간이 지나 버릴 것 같아서 걱정이에요.", en: "I'm worried the hotel check-in time will have passed by then." },
      { speaker: "직원", kr: "저희가 호텔 측에 연락해서 늦은 체크인을 요청해 드릴 수 있어요.", en: "We can contact the hotel to request a late check-in on your behalf." },
      { speaker: "여행객", kr: "정말 그렇게 해 주실 수 있어요?", en: "Can you really do that for me?" },
      { speaker: "직원", kr: "네, 예약 확인서 좀 보여 주시겠어요?", en: "Yes, could you show me your reservation confirmation?" },
      { speaker: "여행객", kr: "여기요, 부탁드릴게요.", en: "Here you go, I'd appreciate it." },
    ],
  },
  {
    id: "airport-b2x-lostbelt-claim",
    situationKey: "airport",
    level: "B2",
    title: "Filing a claim for an item lost at security",
    lines: [
      { speaker: "여행객", kr: "검색대에서 시계를 잃어버린 것 같은데 아무리 찾아도 없어요.", en: "I think I lost my watch at security, but I can't find it anywhere." },
      { speaker: "직원", kr: "언제, 어느 검색대였는지 기억나세요?", en: "Do you remember when and which checkpoint it was?" },
      { speaker: "여행객", kr: "한 시간 전쯤, 삼 번 검색대였던 것 같아요.", en: "About an hour ago, I think it was checkpoint 3." },
      { speaker: "직원", kr: "그럼 분실물 신고서를 작성해 주셔야 해요.", en: "Then you'll need to fill out a lost item report." },
      { speaker: "여행객", kr: "찾으면 어떻게 연락받을 수 있어요?", en: "If it's found, how will I be contacted?" },
      { speaker: "직원", kr: "연락처를 남기시면 찾는 대로 전화드려요.", en: "If you leave your contact info, we'll call as soon as it's found." },
      { speaker: "여행객", kr: "네, 여기 제 번호 적어 놓을게요.", en: "Okay, I'll write my number down here." },
    ],
  },
  {
    id: "airport-b2x-minor-late-pickup",
    situationKey: "airport",
    level: "B2",
    title: "Guardian late to pick up an unaccompanied minor",
    lines: [
      { speaker: "직원", kr: "아이를 데리러 오시기로 한 분이 아직 안 오셨어요.", en: "The person who was supposed to pick up your child hasn't arrived yet." },
      { speaker: "보호자", kr: "네? 저희는 계속 여기서 기다리고 있었는데요.", en: "What? We've been waiting here the whole time." },
      { speaker: "직원", kr: "죄송해요, 다시 확인해 볼게요. 성함이 어떻게 되세요?", en: "I'm sorry, let me check again. What's the name?" },
      { speaker: "보호자", kr: "박지훈이에요. 아이 삼촌이요.", en: "Park Jihoon. The child's uncle." },
      { speaker: "직원", kr: "아, 확인됐어요. 신분증만 보여 주시면 바로 인계해 드릴게요.", en: "Ah, confirmed. Just show your ID and I'll hand her over right away." },
      { speaker: "보호자", kr: "여기 있어요. 정말 걱정했어요.", en: "Here it is. I was really worried." },
      { speaker: "직원", kr: "번거롭게 해 드려 죄송합니다.", en: "I'm sorry for the trouble." },
    ],
  },
  {
    id: "airport-b2x-gate-shuttle-miss",
    situationKey: "airport",
    level: "B2",
    title: "Missed the shuttle to a changed gate",
    lines: [
      { speaker: "여행객", kr: "셔틀을 놓쳐서 게이트에 늦을 것 같아요.", en: "I missed the shuttle and I think I'll be late for the gate." },
      { speaker: "직원", kr: "몇 번 게이트로 가세요?", en: "Which gate are you headed to?" },
      { speaker: "여행객", kr: "사십이 번이요. 방금 바뀌었대요.", en: "Gate 42. I heard it just changed." },
      { speaker: "직원", kr: "다음 셔틀은 오 분 뒤에 와요.", en: "The next shuttle comes in 5 minutes." },
      { speaker: "여행객", kr: "그럼 탑승 시간에 못 맞출 것 같은데요.", en: "Then I don't think I'll make it in time for boarding." },
      { speaker: "직원", kr: "게이트에 미리 연락해서 상황을 알려 드릴게요.", en: "I'll contact the gate ahead of time to let them know." },
      { speaker: "여행객", kr: "정말 감사해요, 서둘러 볼게요.", en: "Thank you so much, I'll hurry." },
    ],
  },
  {
    id: "airport-b2x-fragile-damaged",
    situationKey: "airport",
    level: "B2",
    title: "Fragile item arrived damaged",
    lines: [
      { speaker: "여행객", kr: "깨지기 쉬운 스티커까지 붙였는데 도착해서 열어 보니 깨져 있었어요.", en: "I even put a fragile sticker on it, but when I opened it after arrival, it was broken." },
      { speaker: "직원", kr: "정말 죄송합니다. 언제 어디서 확인하셨어요?", en: "I'm truly sorry. When and where did you notice this?" },
      { speaker: "여행객", kr: "방금 수하물 찾는 곳에서 열어 봤어요.", en: "I just opened it at the baggage claim." },
      { speaker: "직원", kr: "파손 신고서를 작성해 주시면 보상 절차를 도와드릴게요.", en: "If you fill out a damage report, we'll help you with the compensation process." },
      { speaker: "여행객", kr: "영수증이 필요한가요? 안에 있는 물건 영수증이요.", en: "Do I need a receipt—for the item inside?" },
      { speaker: "직원", kr: "네, 가능하면 가져와 주시고, 없으면 사진이라도 도움이 돼요.", en: "Yes, if possible bring it, but a photo helps too if you don't have it." },
      { speaker: "여행객", kr: "알겠어요, 지금 신고서 작성할게요.", en: "Okay, I'll fill out the report now." },
    ],
  },
  {
    id: "airport-b2x-taxfree-electronics",
    situationKey: "airport",
    level: "B2",
    title: "Tax refund on electronics needs inspection",
    lines: [
      { speaker: "직원", kr: "전자 제품은 환급 전에 실물 확인이 필요해요.", en: "Electronics need a physical inspection before the refund." },
      { speaker: "여행객", kr: "아, 그럼 지금 짐에서 꺼내야 해요?", en: "Oh, so I need to take it out of my luggage now?" },
      { speaker: "직원", kr: "네, 위탁 수하물에 넣기 전에 확인받으셔야 해요.", en: "Yes, you need to have it checked before checking in your luggage." },
      { speaker: "여행객", kr: "이미 체크인하고 왔는데 어떡하죠?", en: "I already checked in—what should I do?" },
      { speaker: "직원", kr: "그럼 저쪽 세관 확인 창구로 먼저 가 보세요.", en: "Then please go to the customs verification counter over there first." },
      { speaker: "여행객", kr: "거기서도 확인이 가능한 거죠?", en: "Can they verify it there too?" },
      { speaker: "직원", kr: "네, 그쪽에서 도장을 받으시면 저희가 처리해 드려요.", en: "Yes, once you get the stamp there, we'll process it." },
    ],
  },
  {
    id: "airport-b2x-scale-dispute",
    situationKey: "airport",
    level: "B2",
    title: "Disputing a scale reading",
    lines: [
      { speaker: "여행객", kr: "집에서 잰 거랑 여기 저울 숫자가 너무 달라요.", en: "The number on this scale is very different from what I measured at home." },
      { speaker: "직원", kr: "저희 저울은 매일 아침 점검해요. 오차가 크진 않을 거예요.", en: "Our scale is checked every morning. There shouldn't be much error." },
      { speaker: "여행객", kr: "그래도 이 킬로그램 차이는 좀 이상해서요.", en: "Still, a 2-kilogram difference seems strange." },
      { speaker: "직원", kr: "원하시면 다른 저울로 다시 재 드릴게요.", en: "If you'd like, I can weigh it again on another scale." },
      { speaker: "여행객", kr: "네, 그렇게 해 주시면 좋겠어요.", en: "Yes, I'd appreciate that." },
      { speaker: "직원", kr: "이쪽으로 옮겨서 다시 확인해 볼게요.", en: "Let's move it over here and check again." },
      { speaker: "여행객", kr: "똑같이 나오면 그냥 초과 요금 낼게요.", en: "If it's the same, I'll just pay the excess fee." },
    ],
  },
  {
    id: "airport-b2x-arrival-nowifi",
    situationKey: "airport",
    level: "B2",
    title: "Can't reach pickup driver without wifi",
    lines: [
      { speaker: "여행객", kr: "와이파이가 안 잡혀서 기사님한테 연락을 못 하고 있어요.", en: "I can't get wifi, so I can't reach the driver." },
      { speaker: "직원", kr: "무료 와이파이 존은 저쪽 안내 데스크 근처예요.", en: "The free wifi zone is over near the information desk." },
      { speaker: "여행객", kr: "거기까지 좀 먼데, 혹시 여기 전화 좀 빌릴 수 있을까요?", en: "That's a bit far—could I possibly borrow a phone here?" },
      { speaker: "직원", kr: "네, 잠깐 쓰셔도 돼요. 번호가 어떻게 되세요?", en: "Yes, you can use it for a moment. What's the number?" },
      { speaker: "여행객", kr: "제가 불러 드릴게요, 감사합니다.", en: "I'll tell you the number, thank you." },
      { speaker: "직원", kr: "연결됐어요, 통화하세요.", en: "It's connected, go ahead and talk." },
      { speaker: "여행객", kr: "정말 큰 도움이 됐어요.", en: "This was a huge help." },
    ],
  },
  {
    id: "airport-b2x-charger-not-returned",
    situationKey: "airport",
    level: "B2",
    title: "Forgot to return the borrowed charger",
    lines: [
      { speaker: "직원", kr: "빌리신 보조 배터리를 아직 반납 안 하셨네요.", en: "You haven't returned the portable charger you borrowed yet." },
      { speaker: "여행객", kr: "아, 죄송해요. 가방 안에 있는 걸 깜빡했어요.", en: "Oh, sorry. I forgot it was in my bag." },
      { speaker: "직원", kr: "지금 탑승 시작했는데, 반납 안 하시면 요금이 청구돼요.", en: "Boarding has already started, and if it's not returned there's a charge." },
      { speaker: "여행객", kr: "지금 바로 꺼낼게요, 잠깐만요.", en: "I'll take it out right now, one moment." },
      { speaker: "여행객", kr: "여기요, 정말 죄송합니다.", en: "Here it is, I'm really sorry." },
      { speaker: "직원", kr: "괜찮아요, 확인했으니 요금은 안 나가요.", en: "It's fine, I've confirmed it so there won't be a charge." },
      { speaker: "여행객", kr: "다행이네요, 빨리 탑승할게요.", en: "What a relief, I'll board quickly." },
    ],
  },
  {
    id: "airport-b2x-lounge-noshow",
    situationKey: "airport",
    level: "B2",
    title: "Lounge access denied due to system error",
    lines: [
      { speaker: "여행객", kr: "제 카드로 라운지 이용이 된다고 들었는데 안 된다고 나오네요.", en: "I was told my card gives lounge access, but it's showing as not valid." },
      { speaker: "직원", kr: "카드 뒷면 번호를 다시 한번 스캔해 볼게요.", en: "Let me scan the number on the back of the card again." },
      { speaker: "여행객", kr: "여기요. 예전에는 문제없이 됐었어요.", en: "Here. It worked without any issue before." },
      { speaker: "직원", kr: "저희 쪽 시스템 오류인 것 같아요, 잠시만요.", en: "It seems to be an error on our system's side, one moment." },
      { speaker: "여행객", kr: "얼마나 걸릴까요? 비행기 시간이 얼마 안 남았어요.", en: "How long will it take? I don't have much time before my flight." },
      { speaker: "직원", kr: "본사에 확인 요청했으니 오 분 안에 해결될 거예요.", en: "I've requested a check with headquarters, so it should be resolved within 5 minutes." },
      { speaker: "여행객", kr: "알겠어요, 여기서 기다릴게요.", en: "Okay, I'll wait here." },
    ],
  },
  {
    id: "airport-b2x-wheelchair-mismatch",
    situationKey: "airport",
    level: "B2",
    title: "Wheelchair request wasn't logged properly",
    lines: [
      { speaker: "여행객", kr: "저희 아버지 휠체어를 예약할 때 신청했는데 여기 기록이 없대요.", en: "I requested a wheelchair for my father when booking, but there's no record here." },
      { speaker: "직원", kr: "죄송합니다, 시스템에서 확인이 안 되네요.", en: "I'm sorry, I can't find it in the system." },
      { speaker: "여행객", kr: "확인 메일도 받았는데 이상하네요.", en: "That's strange, I even got a confirmation email." },
      { speaker: "직원", kr: "메일을 보여 주시면 도움이 될 것 같아요.", en: "If you show me the email, that would help." },
      { speaker: "여행객", kr: "여기요, 확인해 보세요.", en: "Here, please check." },
      { speaker: "직원", kr: "확인했습니다. 지금 바로 휠체어를 준비해 드릴게요.", en: "Confirmed. I'll get a wheelchair ready for you right now." },
      { speaker: "여행객", kr: "감사해요, 오래 서 계시기 힘드실까 봐 걱정했어요.", en: "Thank you, I was worried he'd have a hard time standing for long." },
    ],
  },
  {
    id: "airport-b2x-pet-carrier-size",
    situationKey: "airport",
    level: "B2",
    title: "Pet carrier is slightly oversized",
    lines: [
      { speaker: "직원", kr: "이동장이 저희 기준보다 이 센티미터 커요.", en: "The carrier is 2 centimeters bigger than our standard." },
      { speaker: "여행객", kr: "네? 예약할 때 확인받은 규격인데요.", en: "What? This is the size I confirmed when I booked." },
      { speaker: "직원", kr: "죄송한데 저희 기내 규정은 좀 더 엄격해요.", en: "I'm sorry, but our in-cabin policy is a bit stricter." },
      { speaker: "여행객", kr: "그럼 어떻게 해야 하죠? 다른 이동장이 없는데요.", en: "Then what should I do? I don't have another carrier." },
      { speaker: "직원", kr: "매점에서 맞는 이동장을 파는지 확인해 볼게요.", en: "Let me check if the shop sells a carrier that fits." },
      { speaker: "여행객", kr: "시간이 별로 없는데 빨리 확인해 주실 수 있어요?", en: "I don't have much time—could you check quickly?" },
      { speaker: "직원", kr: "네, 지금 바로 연락해 볼게요.", en: "Yes, I'll contact them right now." },
    ],
  },
];

export const AIRPORT_QUIZZES: Record<string, DialogueQuiz> = {
  "airport-a1x-cart": {
    q: "Where are the luggage carts?",
    opts: ["Near the entrance", "Next to the pillar", "By the elevator", "At the check-in desk"],
    ans: 1,
  },
  "airport-a1x-scale": {
    q: "How much does the traveler's bag weigh?",
    opts: ["10 kilos", "12 kilos", "15 kilos", "20 kilos"],
    ans: 2,
  },
  "airport-a1x-reprint": {
    q: "What does the staff member ask to see first?",
    opts: ["A boarding pass", "A passport", "A credit card", "A ticket receipt"],
    ans: 1,
  },
  "airport-a1x-exchange": {
    q: "Where is the currency exchange?",
    opts: ["On this floor", "Downstairs", "Near the gate", "Outside the airport"],
    ans: 0,
  },
  "airport-a1x-wheelchair": {
    q: "How long will the wheelchair take to arrive?",
    opts: ["1 minute", "5 minutes", "10 minutes", "30 minutes"],
    ans: 1,
  },
  "airport-a1x-pet": {
    q: "What does the staff member check?",
    opts: ["The dog's vaccination", "The carrier size", "The flight ticket", "The dog's weight"],
    ans: 1,
  },
  "airport-a1x-fragile": {
    q: "What does the staff member do for the bag?",
    opts: ["Weighs it again", "Puts a fragile sticker on it", "Opens it to inspect", "Refuses to check it"],
    ans: 1,
  },
  "airport-a1x-lounge": {
    q: "What floor is the lounge on?",
    opts: ["First floor", "Second floor", "Third floor", "Fourth floor"],
    ans: 2,
  },
  "airport-a1x-meal": {
    q: "What does the passenger choose to drink?",
    opts: ["Juice", "Coffee", "Water", "Tea"],
    ans: 2,
  },
  "airport-a1x-lostpass": {
    q: "What does the traveler show instead of the boarding pass?",
    opts: ["A passport", "A credit card", "An ID card", "A phone screenshot"],
    ans: 0,
  },
  "airport-a1x-arrival": {
    q: "Which exit is the pickup point?",
    opts: ["Exit 1", "Exit 2", "Exit 3", "Exit 5"],
    ans: 0,
  },
  "airport-a1x-taxfree": {
    q: "What counter number is the tax refund desk?",
    opts: ["Counter 10", "Counter 15", "Counter 20", "Counter 25"],
    ans: 2,
  },
  "airport-a1x-charge": {
    q: "Where is the phone charger located?",
    opts: ["Next to the chairs", "By the entrance", "Near the restroom", "At the food court"],
    ans: 0,
  },
  "airport-a1x-elevator": {
    q: "Which direction is the elevator?",
    opts: ["Straight ahead", "To the right", "To the left", "Downstairs"],
    ans: 2,
  },
  "airport-a1x-luggage-tag": {
    q: "What does the traveler write on the bag?",
    opts: ["Phone number", "Flight number", "Their name", "Address"],
    ans: 2,
  },
  "airport-a2x-scale-heavy": {
    q: "How many kilos over the limit is the bag?",
    opts: ["1 kilo", "2 kilos", "3 kilos", "5 kilos"],
    ans: 2,
  },
  "airport-a2x-lounge-buy": {
    q: "How much is the lounge day pass?",
    opts: ["10,000 won", "20,000 won", "30,000 won", "50,000 won"],
    ans: 2,
  },
  "airport-a2x-minor": {
    q: "Who will take the child to the gate?",
    opts: ["The parent", "Airline staff", "A security guard", "The pilot"],
    ans: 1,
  },
  "airport-a2x-pet-cabin": {
    q: "What does the staff check for the cat?",
    opts: ["Vaccination record", "The carrier", "The ticket", "The cat's age"],
    ans: 1,
  },
  "airport-a2x-exchange-rate": {
    q: "How much does the traveler exchange?",
    opts: ["50 dollars", "100 dollars", "200 dollars", "300 dollars"],
    ans: 1,
  },
  "airport-a2x-gate-question": {
    q: "What gate did it change to?",
    opts: ["Gate 15", "Gate 25", "Gate 35", "Gate 45"],
    ans: 2,
  },
  "airport-a2x-rebook": {
    q: "When does the new flight leave?",
    opts: ["Morning", "Noon", "3 p.m.", "Evening"],
    ans: 2,
  },
  "airport-a2x-fragile-fee": {
    q: "How much does special packaging cost?",
    opts: ["About 2,000 won", "About 5,000 won", "About 10,000 won", "It's free"],
    ans: 1,
  },
  "airport-a2x-arrival-sign": {
    q: "Where can the traveler get paper for a sign?",
    opts: ["The information desk", "A kiosk", "The lounge", "The exchange counter"],
    ans: 1,
  },
  "airport-a2x-charger-borrow": {
    q: "When should the charger be returned?",
    opts: ["Within an hour", "Before boarding", "After landing", "The next day"],
    ans: 1,
  },
  "airport-a2x-meal-special": {
    q: "What meal does the traveler request?",
    opts: ["Vegetarian", "Kosher", "Gluten-free", "Low-sodium"],
    ans: 0,
  },
  "airport-a2x-lostpass-reissue": {
    q: "What flight number does the traveler give?",
    opts: ["KE101", "KE201", "KE301", "KE501"],
    ans: 1,
  },
  "airport-a2x-wheelchair-time": {
    q: "How early should they return for the wheelchair?",
    opts: ["30 minutes before", "1 hour before", "2 hours before", "Right at boarding"],
    ans: 1,
  },
  "airport-a2x-cart-return": {
    q: "What does the traveler get back when returning the cart?",
    opts: ["Nothing", "A coin", "A receipt", "A ticket"],
    ans: 1,
  },
  "airport-a2x-taxfree-form": {
    q: "What two things does the traveler write on the form?",
    opts: ["Name and address", "Passport number and card number", "Flight number and date", "Phone number and email"],
    ans: 1,
  },
  "airport-b1x-taxfree-negotiate": {
    q: "How does the traveler try to avoid the extra fee?",
    opts: ["Paying by card", "Splitting items into another bag", "Leaving items behind", "Arguing with staff"],
    ans: 1,
  },
  "airport-b1x-lounge-guest": {
    q: "How many guests can the premium card holder bring free?",
    opts: ["None", "One", "Two", "Unlimited"],
    ans: 1,
  },
  "airport-b1x-minor-pickup": {
    q: "Who is picking up the child at the destination?",
    opts: ["Her mother", "Her grandmother", "Her uncle", "A family friend"],
    ans: 2,
  },
  "airport-b1x-pet-vaccine": {
    q: "What does the traveler show as proof instead of the paper certificate?",
    opts: ["A printed copy", "A photo on their phone", "An email", "Nothing"],
    ans: 1,
  },
  "airport-b1x-exchange-large": {
    q: "How much is the exchange fee?",
    opts: ["About 1 percent", "About 2 percent", "About 5 percent", "There's no fee"],
    ans: 1,
  },
  "airport-b1x-rebook-hotel": {
    q: "How far is the hotel from the airport?",
    opts: ["Walking distance", "10-minute shuttle ride", "30-minute drive", "It's downtown"],
    ans: 1,
  },
  "airport-b1x-lost-belt": {
    q: "Where did the traveler lose the belt?",
    opts: ["At the gate", "In the lounge", "At the security tray", "At check-in"],
    ans: 2,
  },
  "airport-b1x-arrival-late": {
    q: "How soon does the driver arrive?",
    opts: ["5 minutes", "10 minutes", "20 minutes", "30 minutes"],
    ans: 1,
  },
  "airport-b1x-gate-far": {
    q: "How does the traveler get to the new gate?",
    opts: ["Walking", "By shuttle", "By taxi", "By train"],
    ans: 1,
  },
  "airport-b1x-fragile-refuse": {
    q: "Why won't the airline check the pottery as baggage?",
    opts: ["It's too heavy", "It's too fragile for their policy", "It's oversized", "It's not allowed at all"],
    ans: 1,
  },
  "airport-b1x-meal-allergy": {
    q: "What allergy does the traveler have?",
    opts: ["Shellfish", "Dairy", "Peanut", "Gluten"],
    ans: 2,
  },
  "airport-b1x-lounge-full": {
    q: "How long is the estimated wait for the lounge?",
    opts: ["5 minutes", "10 minutes", "20 minutes", "1 hour"],
    ans: 2,
  },
  "airport-b1x-cart-crowded": {
    q: "Why are there no carts available?",
    opts: ["They are all broken", "It's been busy this morning", "The airport ran out of carts", "They're being repaired"],
    ans: 1,
  },
  "airport-b1x-lounge-time": {
    q: "What can the traveler reserve in the lounge?",
    opts: ["A private room", "A shower room", "A meeting room", "A nap pod"],
    ans: 1,
  },
  "airport-b1x-meal-vegetarian-limited": {
    q: "What does the flight attendant offer instead?",
    opts: ["Chicken and rice", "Fruit and salad", "Bread and soup", "Nothing at all"],
    ans: 1,
  },
  "airport-b1x-exchange-closed": {
    q: "How much does the traveler exchange?",
    opts: ["100 dollars", "200 dollars", "300 dollars", "500 dollars"],
    ans: 2,
  },
  "airport-b2x-cart-broken": {
    q: "What's wrong with the cart?",
    opts: ["It's too small", "A wheel is broken", "It's missing a handle", "It's already in use"],
    ans: 1,
  },
  "airport-b2x-taxfree-deadline": {
    q: "What is the tax refund time limit after purchase?",
    opts: ["1 month", "6 weeks", "3 months", "6 months"],
    ans: 2,
  },
  "airport-b2x-pet-weather": {
    q: "Why might the pet not be allowed to fly today?",
    opts: ["Missing paperwork", "The carrier is too small", "High temperature safety concern", "The pet is too large"],
    ans: 2,
  },
  "airport-b2x-exchange-fake": {
    q: "What does the staff member do with the unrecognized bill?",
    opts: ["Exchanges it anyway", "Excludes it and exchanges the rest", "Refuses the entire transaction", "Calls the police"],
    ans: 1,
  },
  "airport-b2x-rebook-connection": {
    q: "What does the staff offer to help with the hotel?",
    opts: ["A refund", "Contacting the hotel for late check-in", "A free hotel room", "Nothing, it's not their problem"],
    ans: 1,
  },
  "airport-b2x-lostbelt-claim": {
    q: "Which checkpoint does the traveler think they lost the watch at?",
    opts: ["Checkpoint 1", "Checkpoint 2", "Checkpoint 3", "Checkpoint 4"],
    ans: 2,
  },
  "airport-b2x-minor-late-pickup": {
    q: "What is the guardian's relationship to the child?",
    opts: ["Father", "Uncle", "Grandfather", "Family friend"],
    ans: 1,
  },
  "airport-b2x-gate-shuttle-miss": {
    q: "How does the staff help the traveler who missed the shuttle?",
    opts: ["Calls a taxi", "Contacts the gate in advance", "Gives a refund", "Rebooks the flight"],
    ans: 1,
  },
  "airport-b2x-fragile-damaged": {
    q: "What does the staff ask the traveler to do?",
    opts: ["Buy a new item", "File a damage report", "Contact the airline later", "Nothing can be done"],
    ans: 1,
  },
  "airport-b2x-taxfree-electronics": {
    q: "Why does the traveler need to visit the customs counter?",
    opts: ["To pay a tax", "For a physical inspection of electronics", "To get a new receipt", "To recheck luggage"],
    ans: 1,
  },
  "airport-b2x-scale-dispute": {
    q: "What does the staff offer to resolve the dispute?",
    opts: ["A discount on the fee", "Weighing it on another scale", "Ignoring the difference", "Calling a manager"],
    ans: 1,
  },
  "airport-b2x-arrival-nowifi": {
    q: "What does the staff member offer the traveler?",
    opts: ["Free wifi password", "To borrow a phone", "To call the driver themselves", "Directions to the wifi zone only"],
    ans: 1,
  },
  "airport-b2x-lounge-noshow": {
    q: "What does the staff member say is causing the problem?",
    opts: ["An expired card", "A system error on their side", "The lounge is closed", "The card was reported lost"],
    ans: 1,
  },
  "airport-b2x-wheelchair-mismatch": {
    q: "What does the traveler show to prove the request was made?",
    opts: ["A phone call log", "A confirmation email", "A printed receipt", "A booking reference number"],
    ans: 1,
  },
  "airport-b2x-pet-carrier-size": {
    q: "By how much is the carrier oversized?",
    opts: ["1 centimeter", "2 centimeters", "5 centimeters", "10 centimeters"],
    ans: 1,
  },
  "airport-b2x-charger-not-returned": {
    q: "Where was the portable charger the whole time?",
    opts: ["Lost", "In the traveler's bag", "Left at the counter", "Given to another passenger"],
    ans: 1,
  },
};
