import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Airport situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const AIRPORT_C_EXPANSION: Dialogue[] = [
  {
    id: "airport-c1y-budget",
    situationKey: "airport",
    level: "C1",
    title: { en: "Debating budget airlines", ja: "格安航空会社について議論する", zh: "关于廉价航空公司的争论", vi: "Tranh luận về hàng không giá rẻ" },
    lines: [
      { speaker: "수진", kr: "저가 항공사는 확실히 싸긴 한데, 서비스 질이 예전만 못한 것 같지 않아?", en: "Budget airlines are definitely cheap, but doesn't the service quality feel worse than it used to be?", ja: "格安航空会社は間違いなく安いですが、サービス品質は以前よりも悪く感じませんか？", zh: "经济型航空公司肯定很便宜，但服务质量难道不比以前差吗？", vi: "Hàng không giá rẻ chắc chắn rẻ thật, nhưng chẳng phải chất lượng dịch vụ có cảm giác tệ hơn trước sao?" },
      { speaker: "재훈", kr: "글쎄, 난 오히려 그게 합리적인 거래라고 봐. 필요한 만큼만 돈을 내는 거잖아.", en: "I actually think of it as a rational trade-off. You only pay for what you need.", ja: "私は実際にそれを合理的なトレードオフと考えています。必要な分だけお支払いください。", zh: "我实际上认为这是一种理性的权衡。您只需支付所需的费用。", vi: "Tôi thực ra coi đó là một sự đánh đổi hợp lý. Anh chỉ trả tiền cho những gì anh cần." },
      { speaker: "수진", kr: "그래도 좌석 간격을 계속 줄이고, 수하물 요금은 갈수록 비싸지고. 결국 소비자가 손해 보는 거 아닐까?", en: "Still, they keep shrinking seat pitch and baggage fees keep climbing. Doesn't the consumer end up losing out?", ja: "それでも、座席ピッチは縮小し続け、手荷物料金は上昇し続けています。消費者は損をするのではないでしょうか？", zh: "尽管如此，他们的座椅间距不断缩小，行李费也不断攀升。消费者最终会不会输？", vi: "Dù vậy, họ vẫn tiếp tục thu hẹp khoảng cách ghế và phí hành lý cứ tăng dần. Chẳng phải người tiêu dùng cuối cùng bị thiệt sao?" },
      { speaker: "재훈", kr: "손해라기보다는 선택의 폭이 넓어진 거지. 짐 없이 가벼운 여행객한테는 오히려 이득이야.", en: "I'd call it expanded choice rather than a loss. For a light traveler with no baggage, it's actually a benefit.", ja: "私はそれを損失ではなく、選択肢の拡大と呼んでいます。手荷物のない軽い旅行者にとっては、実際にはメリットがあります。", zh: "我称之为扩展选择，而不是损失。对于没有行李的轻型旅行者来说，这实际上是一个好处。", vi: "Tôi thà gọi đó là mở rộng lựa chọn hơn là thiệt hại. Với người đi nhẹ không hành lý, đó thực ra là một lợi ích." },
      { speaker: "수진", kr: "이론상으론 그런데, 실제로는 숨겨진 수수료가 워낙 많아서 나중에 비교해 보면 대형 항공사랑 큰 차이 없을 때도 있더라.", en: "In theory, sure, but in practice there are so many hidden fees that sometimes when you compare it later there's not much difference from a full-service carrier.", ja: "理論的にはもちろんですが、実際には非常に多くの隠れた料金があるため、後で比較すると、フルサービスのキャリアとあまり違いがないことがあります。", zh: "从理论上讲，当然，但实际上隐藏的费用太多了，有时当您稍后进行比较时，与全方位服务的运营商没有太大区别。", vi: "Về lý thuyết thì đúng vậy, nhưng trên thực tế có quá nhiều phí ẩn nên đôi khi so sánh lại thì chẳng khác mấy so với hãng bay dịch vụ đầy đủ." },
      { speaker: "재훈", kr: "그건 인정해. 투명성 문제는 규제가 좀 더 촘촘해져야 할 부분이라고 봐.", en: "I'll grant you that. Transparency is an area where regulation probably needs to be tightened.", ja: "それはお任せします。透明性は、規制を強化する必要がある分野です。", zh: "我答应你。透明度是一个可能需要加强监管的领域。", vi: "Tôi công nhận điều đó. Tính minh bạch là một lĩnh vực mà quy định có lẽ cần được siết chặt hơn." },
      { speaker: "수진", kr: "안전 관리나 정비 주기도 원가 절감 압박 때문에 소홀해지는 거 아니냐는 우려도 있잖아.", en: "There's also the concern that safety management and maintenance cycles get neglected because of cost-cutting pressure.", ja: "また、コスト削減の圧力のために安全管理とメンテナンスサイクルが無視されるという懸念もあります。", zh: "还有人担心，由于成本削减压力，安全管理和维护周期会被忽视。", vi: "Cũng có mối lo là việc quản lý an toàn và chu kỳ bảo trì bị xao nhãng vì áp lực cắt giảm chi phí." },
      { speaker: "재훈", kr: "그 부분은 항공 당국 인증만 통과하면 법적 기준은 동일하게 적용되니까 근거 없는 불안이라고 생각해.", en: "On that point, as long as they pass aviation authority certification, the same legal standards apply, so I think that fear is unfounded.", ja: "その点では、航空局の認証を通過している限り、同じ法的基準が適用されるので、その恐れは根拠がないと思います。", zh: "在这一点上，只要他们通过航空当局认证，同样的法律标准适用，所以我认为恐惧是没有根据的。", vi: "Về điểm đó, miễn là họ vượt qua chứng nhận của cơ quan hàng không, cùng tiêu chuẩn pháp lý sẽ được áp dụng, nên tôi nghĩ nỗi lo đó không có cơ sở." },
      { speaker: "수진", kr: "결국은 각자 여행 목적에 따라 저울질할 문제겠지. 이번엔 나도 짐 가볍게 가니까 한번 타 볼까 해.", en: "In the end it's a matter of weighing it against your own travel purpose. Since I'm traveling light this time, I think I'll give one a try.", ja: "結局のところ、それはあなた自身の旅行目的と比較して重量を量る問題です。今回は光の旅なので、一度試してみようと思います。", zh: "归根结底，这是一个权衡自己的旅行目的的问题。既然这次旅行很轻松，我想我会试一试。", vi: "Cuối cùng đó là việc cân nhắc dựa trên mục đích chuyến đi của mỗi người. Vì lần này tôi đi nhẹ, tôi nghĩ tôi sẽ thử một chuyến." },
    ],
  },
  {
    id: "airport-c1y-pr",
    situationKey: "airport",
    level: "C1",
    title: { en: "Airline exec facing a PR crisis", ja: "広報危機に直面する航空会社役員", zh: "面临公关危机的航空公司高管", vi: "Giám đốc hãng bay đối mặt khủng hoảng truyền thông" },
    lines: [
      { speaker: "기자", kr: "지난주 발생한 승객 강제 하기 사건에 대해 회사 측 입장을 듣고 싶습니다.", en: "I'd like to hear the company's position on last week's forced passenger removal incident.", ja: "先週の乗客強制移動事件についての会社の立場を聞きたい。", zh: "我想听听公司对上周强迫乘客搬迁事件的立场。", vi: "Tôi muốn nghe lập trường của công ty về sự cố buộc hành khách rời máy bay tuần trước." },
      { speaker: "임원", kr: "먼저 해당 승객분과 함께 계셨던 모든 분들께 깊이 사과드립니다. 저희 대응이 미흡했음을 인정합니다.", en: "First, I offer my deepest apologies to that passenger and everyone who was present. We acknowledge our response fell short.", ja: "まず、その乗客と出席されたすべての方々に心からお詫び申し上げます。回答が不十分であったことを確認いたしました。", zh: "首先，我向那位乘客和所有在场的人致以最深切的歉意。我们承认我们的回复不足。", vi: "Trước hết, tôi xin gửi lời xin lỗi sâu sắc nhất đến hành khách đó và tất cả những người có mặt. Chúng tôi thừa nhận phản ứng của mình chưa thỏa đáng." },
      { speaker: "기자", kr: "미흡했다는 표현만으로는 부족해 보입니다. 규정을 자의적으로 해석했다는 비판이 나오고 있는데요.", en: "'Fell short' seems like an understatement. There's criticism that the rules were interpreted arbitrarily.", ja: "「足りなかった」というのは控えめな表現のように思えます。規則が恣意的に解釈されたという批判があります。", zh: "“做空”似乎有点轻描淡写。有人批评这些规则是任意解释的。", vi: "'Chưa thỏa đáng' nghe có vẻ là cách nói giảm nhẹ. Có chỉ trích rằng quy định đã bị diễn giải một cách tùy tiện." },
      { speaker: "임원", kr: "규정 자체는 존재했지만, 현장 직원의 재량 판단 과정에서 승객 배려가 충분히 반영되지 못했습니다.", en: "The rule itself existed, but in the frontline staff's discretionary judgment, sufficient consideration for the passenger wasn't reflected.", ja: "ルール自体は存在していたが、現場スタッフの裁量判断では、乗客への十分な配慮が反映されていなかった。", zh: "规则本身就存在，但在一线工作人员的酌情判断中，对乘客的充分考虑没有得到反映。", vi: "Bản thân quy định đã tồn tại, nhưng trong đánh giá tùy nghi của nhân viên tuyến đầu, sự cân nhắc đầy đủ cho hành khách đã không được phản ánh." },
      { speaker: "기자", kr: "그렇다면 재발 방지책은 무엇입니까? 말로만 그치는 사과가 아니길 바랍니다.", en: "So what are the preventive measures going forward? I hope this isn't just an apology in words.", ja: "それでは、今後の予防措置はどのようなものでしょうか？これが単なる言葉での謝罪ではないことを願っています。", zh: "那么，未来有哪些预防措施？我希望这不仅仅是口头上的道歉。", vi: "Vậy các biện pháp phòng ngừa sắp tới là gì? Tôi hy vọng đây không chỉ là lời xin lỗi suông." },
      { speaker: "임원", kr: "전 직원 대상 승객 응대 재교육을 실시하고, 초과 예약 시 자발적 하기 보상 한도를 대폭 상향할 계획입니다.", en: "We plan to retrain all staff on passenger handling, and to substantially raise the compensation cap for voluntary bumping in overbooking situations.", ja: "乗客の取り扱いについてすべてのスタッフを再教育し、オーバーブッキング状況での自発的な衝突に対する補償上限を大幅に引き上げる予定です。", zh: "我们计划对所有员工进行乘客处理方面的再培训，并大幅提高超额预订情况下自愿碰撞的补偿上限。", vi: "Chúng tôi dự định đào tạo lại toàn bộ nhân viên về cách xử lý hành khách, và nâng đáng kể mức trần bồi thường cho việc tự nguyện nhường chỗ trong tình huống đặt vé quá tải." },
      { speaker: "기자", kr: "보상 한도 상향이 근본적인 해결책이 될 수 있을지 의문입니다. 애초에 초과 예약 관행 자체를 재검토할 계획은 없으신가요?", en: "It's questionable whether raising compensation is a fundamental fix. Is there no plan to reconsider the overbooking practice itself?", ja: "報酬を引き上げることが根本的な修正であるかどうかは疑問です。オーバーブッキングの慣行自体を再検討する計画はありませんか？", zh: "提高薪酬是否是一项根本性的解决办法值得怀疑。没有计划重新考虑超额预订做法本身吗？", vi: "Việc tăng mức bồi thường có phải là giải pháp căn cơ hay không vẫn là điều đáng nghi ngờ. Có kế hoạch nào để xem xét lại chính thức việc đặt vé quá tải hay không?" },
      { speaker: "임원", kr: "초과 예약은 업계 전반의 수익 구조와 맞물려 있어서 즉각 폐지는 어렵지만, 알고리즘 정확도를 높여 발생 빈도를 낮추겠습니다.", en: "Overbooking is tied to the profit structure across the whole industry, so immediate abolition is difficult, but we'll improve algorithm accuracy to lower how often it occurs.", ja: "オーバーブッキングは業界全体の利益構造に結びついているため、直ちに廃止することは困難ですが、アルゴリズムの精度を向上させて、発生頻度を低くします。", zh: "超额预订与整个行业的利润结构有关，因此很难立即取消，但我们将提高算法的准确性，以降低超额预订的频率。", vi: "Đặt vé quá tải gắn liền với cơ cấu lợi nhuận của toàn ngành, nên việc xóa bỏ ngay lập tức là khó khăn, nhưng chúng tôi sẽ cải thiện độ chính xác của thuật toán để giảm tần suất xảy ra." },
      { speaker: "기자", kr: "이번 사태로 실추된 신뢰를 회복하기까지 상당한 시간이 걸릴 것 같습니다.", en: "It seems it will take considerable time to restore the trust lost in this incident.", ja: "今回の事件で失われた信頼を取り戻すには、かなりの時間がかかると思われます。", zh: "恢复在这次事件中失去的信任似乎需要相当长的时间。", vi: "Có vẻ sẽ mất khá nhiều thời gian để khôi phục lòng tin đã mất trong sự cố này." },
      { speaker: "임원", kr: "저희도 그 점을 무겁게 받아들이고 있습니다. 행동으로 증명하는 수밖에 없다고 생각합니다.", en: "We take that very seriously as well. I believe we have no choice but to prove it through our actions.", ja: "私たちもそれを非常に真剣に受け止めています。私たちの行動でそれを証明する以外に選択の余地はないと思います。", zh: "我们也非常重视这一点。我相信我们别无选择，只能通过我们的行动来证明这一点。", vi: "Chúng tôi cũng coi đó là vấn đề rất nghiêm túc. Tôi tin rằng chúng tôi không còn cách nào khác ngoài việc chứng minh điều đó bằng hành động." },
    ],
  },
  {
    id: "airport-c1y-loyalty",
    situationKey: "airport",
    level: "C1",
    title: { en: "Frequent flyers on loyalty program devaluation", ja: "マイレージ制度の価値低下を語る常連客", zh: "常旅客谈里程计划贬值", vi: "Khách bay thường xuyên bàn về việc giảm giá trị chương trình khách hàng thân thiết" },
    lines: [
      { speaker: "민호", kr: "이번에 마일리지 개편안 봤어? 좌석당 필요 마일이 거의 두 배로 뛰었더라.", en: "Did you see the mileage program overhaul? The miles needed per seat almost doubled.", ja: "走行距離プログラムのオーバーホールを見ましたか？座席あたりの走行距離はほぼ倍増しました。", zh: "你看到里程计划大修了吗？每个座位所需的里程几乎翻了一番。", vi: "Anh có thấy việc đại tu chương trình dặm bay chưa? Số dặm cần cho một chỗ ngồi gần như tăng gấp đôi." },
      { speaker: "은영", kr: "봤어. 십 년 넘게 모아 온 게 하루아침에 반토막 난 셈이니 배신감이 들 만도 하지.", en: "I saw it. Ten-plus years of accumulation effectively cut in half overnight — no wonder people feel betrayed.", ja: "私はそれを見ました。10年以上の蓄積は一晩で効果的に半分にカットされました。人々が裏切られたと感じるのも不思議ではありません。", zh: "我看到了，十年多的积累在一夜之间有效地减半，难怪人们觉得被背叛了。", vi: "Tôi thấy rồi. Hơn mười năm tích lũy bị cắt giảm gần một nửa chỉ trong một đêm — chẳng trách người ta cảm thấy bị phản bội." },
      { speaker: "민호", kr: "항공사 입장에서는 좌석 공급이 한정돼 있으니 수요에 맞춰 조정한 거라고 하겠지만, 소비자 신뢰는 생각 안 하나 싶어.", en: "From the airline's perspective they'll say it's adjusting to demand given limited seat supply, but I wonder if they even consider consumer trust.", ja: "航空会社の立場では座席供給が限られているから需要に合わせて調整したと言うだろうけど、消費者の信頼は考えていないんじゃないかと思う。", zh: "站在航空公司的角度，他们会说座位供给有限，是按需求做的调整，但我怀疑他们有没有考虑过消费者的信任。", vi: "Từ góc độ hãng bay, họ sẽ nói đó là điều chỉnh theo nhu cầu với nguồn cung ghế hạn chế, nhưng tôi tự hỏi liệu họ có cân nhắc đến lòng tin của người tiêu dùng hay không." },
      { speaker: "은영", kr: "게다가 예고 기간도 짧았잖아. 기존 회원들한테는 유예 기간 정도는 줬어야지.", en: "On top of that, the notice period was short. They should've at least given existing members a grace period.", ja: "しかも予告期間も短かったじゃない。既存会員には猶予期間くらいは与えるべきだったよ。", zh: "而且预告期也很短，至少应该给老会员一个宽限期吧。", vi: "Thêm vào đó, thời gian thông báo quá ngắn. Ít nhất họ nên cho các thành viên hiện tại một khoảng thời gian ân hạn." },
      { speaker: "민호", kr: "결국 이게 다른 항공사들도 따라갈 흐름이라는 게 더 씁쓸해. 업계 전체가 담합한 것도 아닌데 비슷한 시기에 다 개편하잖아.", en: "What's more bitter is that this is a trend other airlines will follow too. It's not like the industry colluded, but they all overhaul around the same time.", ja: "結局これが他の航空会社も追随する流れだというのがもっと苦い。業界全体が談合したわけでもないのに似た時期に一斉に改編するじゃない。", zh: "更让人心寒的是，这会成为其他航空公司也跟风的趋势。又不是整个行业串通好的，却都在差不多的时间集体改版。", vi: "Điều cay đắng hơn là đây là xu hướng mà các hãng bay khác cũng sẽ theo. Không phải cả ngành thông đồng, nhưng họ đều đại tu cùng khoảng thời gian." },
      { speaker: "은영", kr: "그러니까 이제는 마일리지를 자산이 아니라 언제든 가치가 깎일 수 있는 쿠폰 정도로 생각해야 할 것 같아.", en: "So I think we should stop thinking of miles as an asset and treat them more like a coupon whose value can be cut at any time.", ja: "だからもうマイレージを資産としてではなく、いつでも価値が下がりうるクーポン程度に考えるべきだと思う。", zh: "所以现在应该不再把里程当资产，而是当成随时可能贬值的优惠券来看待了。", vi: "Vì vậy tôi nghĩ chúng ta nên ngừng coi dặm bay là một tài sản mà xem nó giống như một phiếu giảm giá có thể bị cắt giá trị bất cứ lúc nào." },
      { speaker: "민호", kr: "동의해. 나도 이번 기회에 무리하게 좌석 등급 올리지 말고, 모이는 대로 바로바로 소진하는 쪽으로 전략을 바꾸려고.", en: "Agreed. I'm going to change my strategy this time too — instead of pushing for a higher cabin class, I'll just redeem miles as soon as they accumulate.", ja: "同意する。私もこの機会に無理に座席クラスを上げようとせず、貯まったらすぐに使い切る方向に戦略を変えるつもり。", zh: "同意。我这次也打算改变策略，不再硬要升舱，而是攒够了就马上兑换掉。", vi: "Đồng ý. Lần này tôi cũng sẽ thay đổi chiến lược — thay vì cố nâng hạng ghế, tôi sẽ đổi dặm ngay khi vừa tích lũy đủ." },
      { speaker: "은영", kr: "현명한 선택인 것 같아. 회원 등급 유지 조건도 갈수록 까다로워지니 이제는 충성도에 대한 보상이 아니라 부담처럼 느껴져.", en: "That sounds like a wise choice. The conditions for maintaining elite status also keep getting stricter, so it feels less like a reward for loyalty and more like a burden now.", ja: "賢い選択だと思う。会員ランクの維持条件もますます厳しくなっているから、もう忠誠心への報酬ではなく負担のように感じられる。", zh: "听起来是明智的选择。会员等级的维持条件也越来越苛刻，现在感觉不像是对忠诚度的回报，反倒像是一种负担。", vi: "Nghe có vẻ là lựa chọn khôn ngoan. Điều kiện duy trì hạng thành viên ưu tiên cũng ngày càng khắt khe hơn, nên giờ nó có cảm giác giống gánh nặng hơn là phần thưởng cho sự trung thành." },
    ],
  },
  {
    id: "airport-c1y-strike",
    situationKey: "airport",
    level: "C1",
    title: { en: "Overhearing a ground crew labor dispute", ja: "地上職員の労働争議を耳にする", zh: "偶然听到地勤人员的劳资纠纷", vi: "Nghe lỏm tranh chấp lao động của nhân viên mặt đất" },
    lines: [
      { speaker: "직원 A", kr: "노조 쪽에서 오늘 오후에 태업 들어간다는 얘기 들었어? 수하물 처리 속도가 눈에 띄게 느려질 거래.", en: "Did you hear the union is starting a slowdown this afternoon? Baggage handling speed is going to noticeably drop.", ja: "組合側が今日の午後から怠業に入るという話、聞いた？手荷物処理速度が目に見えて遅くなるらしいよ。", zh: "听说工会今天下午要开始怠工吗？据说行李处理速度会明显变慢。", vi: "Anh có nghe nói công đoàn sẽ bắt đầu làm việc chậm chiều nay không? Tốc độ xử lý hành lý sẽ giảm rõ rệt." },
      { speaker: "직원 B", kr: "들었지. 임금 인상안이 물가 상승률에도 못 미친다고 하니 현장 사람들 불만이 이만저만 아니야.", en: "I heard. The wage increase proposal doesn't even keep up with inflation, so the frontline staff's frustration is no small thing.", ja: "聞いたよ。賃上げ案が物価上昇率にも及ばないというから、現場の人たちの不満は並大抵じゃない。", zh: "听说了。加薪方案连物价上涨幅度都赶不上，现场员工的不满可不小。", vi: "Tôi nghe rồi. Đề xuất tăng lương thậm chí không theo kịp lạm phát, nên sự bất mãn của nhân viên tuyến đầu không phải là nhỏ." },
      { speaker: "직원 A", kr: "경영진은 항공 수요가 아직 완전히 회복되지 않았다는 핑계를 대던데, 그 말도 이젠 안 먹히는 것 같아.", en: "Management keeps giving the excuse that air travel demand hasn't fully recovered yet, but that line doesn't seem to work anymore.", ja: "経営陣は航空需要がまだ完全に回復していないという言い訳をしているけど、その話ももう通じないみたい。", zh: "管理层一直找借口说航空需求还没完全恢复，但这套说辞现在好像也不管用了。", vi: "Ban quản lý cứ đưa ra lý do rằng nhu cầu đi máy bay chưa hồi phục hoàn toàn, nhưng lý lẽ đó có vẻ không còn hiệu quả nữa." },
      { speaker: "직원 B", kr: "수요는 이미 예전 수준을 넘어섰잖아. 인력만 그대로 부족한 채로 놔두고 있으니 우리만 갈려 나가는 거지.", en: "Demand has already surpassed pre-pandemic levels. They just keep leaving staffing understaffed, so we're the ones getting worn down.", ja: "需要はすでに以前の水準を超えているじゃない。人員だけそのまま不足させておくから私たちだけがすり減っていくんだよ。", zh: "需求早就超过以前的水平了。人手却一直不足，最后受累的只有我们。", vi: "Nhu cầu đã vượt mức trước đại dịch rồi. Họ chỉ tiếp tục để nhân sự thiếu hụt, nên chính chúng tôi là người bị vắt kiệt sức." },
      { speaker: "직원 A", kr: "이러다 승객들 불편이 커지면 여론도 우리 편은 아닐 것 같은데 걱정이야.", en: "I'm worried that if passenger inconvenience grows from this, public opinion won't be on our side either.", ja: "こんな調子で乗客の不便が大きくなったら世論も私たちの味方じゃなさそうで心配だよ。", zh: "我担心这样下去乘客的不便加剧了，舆论也不会站在我们这边。", vi: "Tôi lo là nếu sự bất tiện của hành khách tăng lên vì việc này, dư luận cũng sẽ không đứng về phía chúng ta." },
      { speaker: "직원 B", kr: "그래서 노조도 전면 파업 대신 단계적 압박을 택한 거야. 여론 눈치를 아예 안 볼 수는 없으니까.", en: "That's why the union chose gradual pressure instead of a full strike. They can't completely ignore public opinion either.", ja: "だから組合も全面ストではなく段階的な圧力を選んだんだよ。世論を全く気にしないわけにはいかないから。", zh: "所以工会才选择了逐步施压，而不是全面罢工。毕竟不能完全不顾舆论。", vi: "Đó là lý do công đoàn chọn gây áp lực dần dần thay vì đình công toàn diện. Họ cũng không thể hoàn toàn phớt lờ dư luận." },
      { speaker: "직원 A", kr: "협상이 다음 주까지 타결 안 되면 상황이 더 악화될 텐데, 사측이 이번엔 진지하게 나올까?", en: "If negotiations aren't settled by next week, the situation will worsen — do you think management will finally take it seriously this time?", ja: "交渉が来週までにまとまらなければ状況はさらに悪化するだろうけど、会社側は今回は真剣に出てくるかな？", zh: "如果谈判到下周还没达成协议，情况会更糟——你觉得资方这次会认真对待吗？", vi: "Nếu đàm phán không được giải quyết trước tuần sau, tình hình sẽ xấu đi — anh nghĩ lần này ban quản lý có cuối cùng nghiêm túc xem xét không?" },
      { speaker: "직원 B", kr: "글쎄, 지난번에도 벼랑 끝까지 가서야 겨우 합의했잖아. 이번에도 크게 다르지 않을 것 같아.", en: "Well, last time too they only reached a deal after going right up to the brink. I doubt it'll be much different this time.", ja: "さあ、前回も土壇場まで行ってようやく合意したじゃない。今回もそんなに変わらないと思う。", zh: "谁知道呢，上次也是拖到最后关头才勉强达成协议。这次估计也不会有太大不同。", vi: "Ừm, lần trước cũng vậy, họ chỉ đạt thỏa thuận sau khi đi đến sát bờ vực. Tôi ngờ là lần này sẽ khác nhiều." },
    ],
  },
  {
    id: "airport-c1y-expansion",
    situationKey: "airport",
    level: "C1",
    title: { en: "A journalist covers airport expansion backlash", ja: "空港拡張への反発を取材する記者", zh: "记者报道机场扩建引发的反弹", vi: "Nhà báo đưa tin về phản ứng dữ dội với việc mở rộng sân bay" },
    lines: [
      { speaker: "기자", kr: "이번 활주로 증설 계획에 대해 인근 주민분들 반발이 상당하다고 들었는데, 구체적으로 어떤 점이 문제인가요?", en: "I've heard there's considerable backlash from nearby residents over this runway expansion plan. What specifically is the problem?", ja: "今回の滑走路増設計画について近隣住民の反発がかなり大きいと聞きましたが、具体的にどんな点が問題なのでしょうか？", zh: "听说附近居民对这次跑道扩建计划反弹很大，具体是哪些方面的问题呢？", vi: "Tôi nghe nói có sự phản đối đáng kể từ cư dân xung quanh về kế hoạch mở rộng đường băng này. Vấn đề cụ thể là gì?" },
      { speaker: "주민", kr: "가장 큰 건 소음이죠. 지금도 새벽 비행이 있는 날엔 잠을 설치는데, 증설되면 이착륙 횟수가 지금의 두 배 가까이 늘어난대요.", en: "The biggest issue is noise. Even now, on days with early morning flights we lose sleep, and with the expansion, takeoffs and landings will nearly double.", ja: "一番大きいのは騒音です。今でも早朝便がある日は眠れないのに、増設されると離着陸回数が今の倍近くに増えるそうです。", zh: "最大的问题是噪音。现在只要有凌晨航班的日子就睡不好，扩建以后起降次数据说会增加将近一倍。", vi: "Vấn đề lớn nhất là tiếng ồn. Ngay cả bây giờ, những ngày có chuyến bay sớm chúng tôi đã mất ngủ, và với việc mở rộng, số lượt cất hạ cánh sẽ gần như tăng gấp đôi." },
      { speaker: "기자", kr: "공항 측은 방음 시설 지원과 이주 보상안을 마련했다고 밝혔는데, 그걸로 충분하지 않다고 보시는 건가요?", en: "The airport authority has said it prepared soundproofing support and relocation compensation — do you think that's not enough?", ja: "空港側は防音施設支援と移住補償案を用意したと明らかにしましたが、それでは十分でないとお考えなのですか？", zh: "机场方面表示已经准备了隔音设施支持和搬迁补偿方案，您觉得这些还不够吗？", vi: "Cơ quan quản lý sân bay nói rằng họ đã chuẩn bị hỗ trợ cách âm và bồi thường di dời — anh nghĩ điều đó chưa đủ sao?" },
      { speaker: "주민", kr: "보상금 액수도 문제지만, 우리가 여기서 몇 대째 살아온 삶의 터전을 돈으로만 환산할 수 있는 건 아니잖아요.", en: "The compensation amount is one issue, but our home, where our family has lived for generations, isn't something you can simply convert into money.", ja: "補償金の額も問題ですが、私たちがここで何代も暮らしてきた生活の場をお金だけで換算できるわけではないでしょう。", zh: "赔偿金额是一回事，但我们在这里世世代代生活的家园，也不是光靠钱就能衡量的吧。", vi: "Số tiền bồi thường là một chuyện, nhưng ngôi nhà nơi gia đình chúng tôi đã sống qua nhiều thế hệ không phải thứ có thể đơn giản quy đổi thành tiền." },
      { speaker: "기자", kr: "공항 측은 지역 경제 활성화와 일자리 창출 효과를 강조하고 있는데, 이 부분은 어떻게 생각하십니까?", en: "The airport authority emphasizes the effect on local economic revitalization and job creation. What do you think about that aspect?", ja: "空港側は地域経済の活性化と雇用創出効果を強調していますが、この点についてはどうお考えですか？", zh: "机场方面强调了对地区经济活跃和创造就业的效果，您对这方面怎么看？", vi: "Cơ quan quản lý sân bay nhấn mạnh tác động đến việc phục hồi kinh tế địa phương và tạo việc làm. Anh nghĩ sao về khía cạnh đó?" },
      { speaker: "주민", kr: "일자리가 늘어나는 건 반가운 일이지만, 그 혜택이 정작 소음 피해를 직접 감내하는 저희 동네까지 오는지는 의문이에요.", en: "More jobs is welcome, but I doubt whether those benefits actually reach our neighborhood, which directly bears the noise damage.", ja: "雇用が増えるのは嬉しいことですが、その恩恵が実際に騒音被害を直接受ける私たちの町にまで来るのかは疑問です。", zh: "增加就业当然是好事，但我怀疑这些好处能不能真正惠及直接承受噪音之苦的我们这个社区。", vi: "Có thêm việc làm thì tôi hoan nghênh, nhưng tôi hoài nghi liệu những lợi ích đó có thực sự đến được khu dân cư của chúng tôi, nơi trực tiếp gánh chịu thiệt hại tiếng ồn hay không." },
      { speaker: "기자", kr: "주민 대책위 측은 향후 환경영향평가 재실시를 요구할 계획이라고 들었습니다. 실현 가능성은 어떻게 보시나요?", en: "I've heard the residents' committee plans to demand a redo of the environmental impact assessment. How feasible do you think that is?", ja: "住民対策委員会は今後、環境影響評価の再実施を求める計画だと聞きました。実現可能性はどう見ていますか？", zh: "听说居民对策委员会打算要求重新进行环境影响评估，您觉得这有多大可能性实现？", vi: "Tôi nghe nói ủy ban cư dân dự định yêu cầu làm lại đánh giá tác động môi trường. Anh nghĩ điều đó khả thi đến mức nào?" },
      { speaker: "주민", kr: "쉽지 않겠지만, 우리가 목소리를 내지 않으면 이 문제는 조용히 묻힐 게 뻔하니까 끝까지 요구할 생각입니다.", en: "It won't be easy, but if we don't raise our voices this issue will clearly get quietly buried, so we plan to keep pushing to the end.", ja: "簡単ではないでしょうが、私たちが声を上げなければこの問題は静かに埋もれるのが目に見えているので、最後まで要求し続けるつもりです。", zh: "不会容易，但如果我们不发声，这个问题肯定会被悄悄压下去，所以我们打算坚持到底。", vi: "Sẽ không dễ dàng, nhưng nếu chúng tôi không lên tiếng, vấn đề này rõ ràng sẽ bị âm thầm chôn vùi, nên chúng tôi dự định tiếp tục đấu tranh đến cùng." },
    ],
  },
  {
    id: "airport-c1y-carbon",
    situationKey: "airport",
    level: "C1",
    title: { en: "The environmental cost of flying, over a delay", ja: "遅延の中で語る飛行機の環境コスト", zh: "延误中谈飞行的环境代价", vi: "Chi phí môi trường của việc bay, nhân chuyện chuyến bay trễ" },
    lines: [
      { speaker: "지우", kr: "또 삼십 분 지연이래. 이럴 때마다 비행이 환경에 미치는 영향을 생각하게 돼.", en: "Another thirty-minute delay, apparently. Every time this happens, I end up thinking about the environmental impact of flying.", ja: "また30分遅延だって。こういう時、飛行機が環境に与える影響を考えてしまうよ。", zh: "又晚点三十分钟。每次这种时候，我都会想到飞行对环境的影响。", vi: "Lại trễ thêm ba mươi phút nữa rồi. Mỗi lần chuyện này xảy ra, tôi lại nghĩ đến tác động môi trường của việc bay." },
      { speaker: "현석", kr: "맞아, 사실 단거리 노선은 탄소 배출량이 기차보다 훨씬 크다는 연구 결과도 있잖아.", en: "Right, there's actually research showing short-haul flights emit far more carbon than trains.", ja: "そうだね、実際に短距離路線は列車よりも炭素排出量がずっと多いという研究結果もあるし。", zh: "对啊，其实有研究表明短途航线的碳排放量远高于火车。", vi: "Đúng vậy, thực ra có nghiên cứu cho thấy các chuyến bay ngắn thải ra lượng carbon nhiều hơn hẳn so với tàu hỏa." },
      { speaker: "지우", kr: "그런데도 가격이랑 시간 때문에 결국 비행기를 선택하게 되니까, 개인의 선택만으로 해결될 문제는 아닌 것 같아.", en: "And yet because of price and time we end up choosing planes anyway, so it doesn't seem like something individual choice alone can solve.", ja: "それでも価格と時間のせいで結局飛行機を選ぶことになるから、個人の選択だけで解決できる問題ではない気がする。", zh: "尽管如此，因为价格和时间的关系我们最后还是会选飞机，所以这似乎不是靠个人选择就能解决的问题。", vi: "Vậy mà vì giá cả và thời gian chúng ta vẫn chọn máy bay, nên có vẻ đây không phải điều mà chỉ riêng lựa chọn cá nhân có thể giải quyết được." },
      { speaker: "현석", kr: "탄소 상쇄 프로그램에 가입하는 것도 방법이긴 한데, 실효성에 대한 의문도 꾸준히 제기되잖아.", en: "Signing up for a carbon offset program is one option, but questions about its actual effectiveness keep being raised too.", ja: "カーボンオフセットプログラムに加入するのも一つの方法だけど、実効性についての疑問も絶えず提起されているよね。", zh: "加入碳抵消项目也是一种办法，但对其实际效果的质疑也不断被提出。", vi: "Đăng ký chương trình bù trừ carbon là một lựa chọn, nhưng câu hỏi về hiệu quả thực tế của nó vẫn liên tục được đặt ra." },
      { speaker: "지우", kr: "결국은 항공사들이 지속 가능 항공유 도입을 앞당기고, 정부가 탄소세 같은 정책적 장치를 마련해야 근본적으로 바뀔 것 같아.", en: "In the end, I think it'll take airlines accelerating the adoption of sustainable aviation fuel and governments creating policy mechanisms like carbon taxes to fundamentally change things.", ja: "結局は航空会社が持続可能な航空燃料の導入を前倒しし、政府が炭素税のような政策的装置を用意してこそ根本的に変わると思う。", zh: "归根结底，只有航空公司加快引入可持续航空燃料，政府建立碳税之类的政策机制，才能从根本上改变现状。", vi: "Cuối cùng, tôi nghĩ cần các hãng bay đẩy nhanh việc áp dụng nhiên liệu hàng không bền vững và chính phủ tạo ra các cơ chế chính sách như thuế carbon để thay đổi tận gốc." },
      { speaker: "현석", kr: "그런 정책이 도입되면 항공권 가격이 오를 텐데, 그럼 여행이 다시 소수의 특권으로 돌아가는 거 아닐까 걱정도 돼.", en: "If such policies are adopted, ticket prices will rise, and I worry that travel might revert to being a privilege for a select few again.", ja: "そういう政策が導入されると航空券の価格が上がるだろうから、旅行がまた少数の特権に戻るんじゃないかと心配にもなる。", zh: "如果引入这类政策，机票价格会上涨，我也担心旅行会不会又变回少数人的特权。", vi: "Nếu những chính sách đó được áp dụng, giá vé sẽ tăng, và tôi lo rằng du lịch có thể quay lại thành đặc quyền của một số ít người." },
      { speaker: "지우", kr: "그 딜레마는 나도 인정해. 그래도 지금처럼 환경 비용을 아무도 지불하지 않는 구조보다는 낫지 않을까.", en: "I recognize that dilemma too. Still, wouldn't that be better than the current structure where nobody pays the environmental cost at all?", ja: "そのジレンマは私も認めるよ。それでも今のように誰も環境コストを払わない構造よりはましじゃないかな。", zh: "这个两难我也认同。但总比现在这种谁都不为环境成本买单的结构要好一点吧。", vi: "Tôi cũng nhận ra nghịch lý đó. Dù vậy, chẳng phải điều đó vẫn tốt hơn cơ cấu hiện tại nơi không ai phải trả cho chi phí môi trường sao?" },
      { speaker: "현석", kr: "일리 있는 말이야. 최소한 우리라도 다음 여행부턴 직항을 우선으로 고려해 보자.", en: "That makes sense. At the very least, let's try to prioritize direct flights starting with our next trip.", ja: "一理ある話だね。少なくとも私たちだけでも次の旅行からは直行便を優先に考えてみよう。", zh: "有道理。至少我们从下次旅行开始优先考虑直飞航班吧。", vi: "Có lý. Ít nhất, hãy thử ưu tiên các chuyến bay thẳng bắt đầu từ chuyến đi tiếp theo của chúng ta." },
    ],
  },
  {
    id: "airport-c1y-reentry",
    situationKey: "airport",
    level: "C1",
    title: { en: "Immigration officer and a returning expat", ja: "出入国審査官と帰国する在外国民", zh: "入境官员与归国侨民", vi: "Nhân viên xuất nhập cảnh và một kiều bào trở về" },
    lines: [
      { speaker: "출입국 직원", kr: "재외국민 재입국 신고서 작성하셨나요? 해외 체류 기간이 오 년이 넘으시네요.", en: "Have you filled out the overseas Korean re-entry declaration? I see you've been residing abroad for over five years.", ja: "在外国民再入国申告書は記入されましたか？海外滞在期間が5年を超えていますね。", zh: "海外国民再入境申报表填写了吗？您在海外居住已经超过五年了呢。", vi: "Anh đã điền tờ khai tái nhập cảnh dành cho kiều bào chưa? Tôi thấy anh đã cư trú ở nước ngoài hơn năm năm rồi." },
      { speaker: "귀국자", kr: "네, 작성했습니다. 최근 정책이 바뀌었다고 들었는데, 저한테 해당되는 사항이 있을까요?", en: "Yes, I've filled it out. I heard the policy recently changed — is there anything that applies to me?", ja: "はい、記入しました。最近政策が変わったと聞いたのですが、私に該当する事項がありますか？", zh: "是的，已经填好了。听说最近政策有变化，有什么和我相关的地方吗？", vi: "Vâng, tôi đã điền rồi. Tôi nghe nói chính sách gần đây thay đổi — có gì áp dụng cho tôi không?" },
      { speaker: "출입국 직원", kr: "장기 체류 후 귀국하시는 분들은 건강보험 재가입 유예 조건이 예전보다 까다로워졌어요.", en: "For people returning after long-term residence abroad, the conditions for the health insurance re-enrollment grace period have become stricter than before.", ja: "長期滞在後に帰国される方は、健康保険の再加入猶予条件が以前より厳しくなりました。", zh: "对于长期海外居住后回国的人，健康保险重新加入的宽限条件比以前更严格了。", vi: "Đối với những người trở về sau thời gian cư trú dài hạn ở nước ngoài, điều kiện của thời gian ân hạn tái đăng ký bảo hiểm y tế đã trở nên khắt khe hơn trước." },
      { speaker: "귀국자", kr: "그렇군요. 그럼 관련 서류는 여기서 받을 수 있나요, 아니면 별도 기관을 방문해야 하나요?", en: "I see. Can I get the related documents here, or do I need to visit a separate agency?", ja: "そうなんですね。では関連書類はここで受け取れますか、それとも別の機関を訪問しなければなりませんか？", zh: "原来如此。那相关文件可以在这里领取吗，还是需要去另一个机构办理？", vi: "Tôi hiểu rồi. Tôi có thể lấy các giấy tờ liên quan ở đây, hay phải đến một cơ quan riêng?" },
      { speaker: "출입국 직원", kr: "일단 여기서 안내문은 드릴 수 있지만, 실제 접수는 관할 구청에 직접 하셔야 합니다.", en: "I can give you the informational notice here, but the actual submission needs to be done directly at your district office.", ja: "とりあえずここで案内文はお渡しできますが、実際の受付は管轄の区役所で直接行う必要があります。", zh: "我这里可以给您说明材料，但实际受理需要您本人前往管辖区厅办理。", vi: "Tôi có thể đưa cho anh thông báo thông tin ở đây, nhưng việc nộp thực tế cần thực hiện trực tiếp tại văn phòng quận của anh." },
      { speaker: "귀국자", kr: "혹시 세금 관련해서도 달라진 게 있는지 여쭤봐도 될까요? 해외 소득 신고 때문에 걱정이 좀 되어서요.", en: "May I also ask if anything has changed regarding taxes? I'm a bit worried about reporting overseas income.", ja: "もしかして税金関連でも変わったことがあるか伺ってもいいですか？海外所得申告のことでちょっと心配になりまして。", zh: "请问税务方面是不是也有变化？我对海外收入申报有点担心。", vi: "Tôi cũng có thể hỏi liệu có gì thay đổi về thuế không? Tôi hơi lo về việc khai báo thu nhập ở nước ngoài." },
      { speaker: "출입국 직원", kr: "세무 관련은 저희 소관이 아니라 국세청 상담 창구로 문의하시는 게 정확할 겁니다.", en: "Tax matters aren't within our jurisdiction, so it would be more accurate to inquire at the National Tax Service consultation window.", ja: "税務関連は私どもの所管ではないので、国税庁の相談窓口にお問い合わせいただくのが正確だと思います。", zh: "税务方面不属于我们的管辖范围，建议您咨询国税厅的咨询窗口会更准确。", vi: "Vấn đề thuế không thuộc thẩm quyền của chúng tôi, nên chính xác hơn là anh nên hỏi tại quầy tư vấn của Cơ quan Thuế Quốc gia." },
      { speaker: "귀국자", kr: "알겠습니다. 오랜만에 돌아오니 절차가 많이 바뀌어서 낯서네요. 안내 감사합니다.", en: "Understood. Coming back after so long, the procedures have changed a lot and feel unfamiliar. Thanks for the guidance.", ja: "分かりました。久しぶりに帰ってきたら手続きがだいぶ変わっていて戸惑いますね。案内ありがとうございます。", zh: "明白了。好久没回来，手续变了很多，感觉挺陌生的。谢谢您的说明。", vi: "Tôi hiểu rồi. Trở về sau bao lâu, thủ tục đã thay đổi nhiều và cảm thấy lạ lẫm. Cảm ơn anh đã hướng dẫn." },
      { speaker: "출입국 직원", kr: "귀국을 환영합니다. 궁금한 사항은 공항 안내 데스크에서도 도와드릴 수 있으니 참고하세요.", en: "Welcome back. If you have further questions, the airport information desk can also help, so keep that in mind.", ja: "帰国を歓迎します。ご不明な点は空港の案内デスクでもお手伝いできますので参考にしてください。", zh: "欢迎回国。如果还有其他疑问，机场问讯处也可以提供帮助，请多加利用。", vi: "Chào mừng anh trở về. Nếu có thêm câu hỏi, quầy thông tin sân bay cũng có thể giúp, nên anh cứ nhớ điều đó." },
    ],
  },
  {
    id: "airport-c1y-securitytheater",
    situationKey: "airport",
    level: "C1",
    title: { en: "Security theater versus real security", ja: "見せかけの保安対策と実質的な安全", zh: "安检表演与真正的安全", vi: "Sân khấu an ninh so với an ninh thực sự" },
    lines: [
      { speaker: "정우", kr: "이 긴 줄 좀 봐. 신발까지 벗기는 게 실제로 효과가 있는 조치인지 의문이야.", en: "Look at this long line. I doubt whether even making people take off their shoes actually does anything effective.", ja: "この長い列を見て。靴まで脱がせるのが本当に効果のある措置なのか疑問だよ。", zh: "你看这条长队。让人连鞋都脱掉，我都怀疑这真的有效果吗。", vi: "Nhìn hàng dài này xem. Tôi hoài nghi liệu việc bắt mọi người cởi giày ra có thực sự hiệu quả hay không." },
      { speaker: "혜리", kr: "그거 신발 폭탄 시도 이후에 생긴 절차잖아. 상징적인 의미도 있다고 봐.", en: "That procedure started after the shoe bomb attempt. I think it also has a symbolic meaning.", ja: "それって靴爆弾未遂の後にできた手続きじゃない。象徴的な意味もあると思う。", zh: "那是鞋子炸弹未遂事件之后才有的程序，我觉得也有象征意义。", vi: "Quy trình đó bắt đầu sau vụ mưu toan đánh bom trong giày. Tôi nghĩ nó cũng mang ý nghĩa biểu tượng." },
      { speaker: "정우", kr: "상징적인 거랑 실질적인 위협 대응은 다르지. 이게 소위 말하는 보안 연극 아닐까 싶어.", en: "Symbolic and actually addressing a real threat are different things. I wonder if this is what's called security theater.", ja: "象徴的なことと実質的な脅威対応は別物でしょ。これがいわゆるセキュリティ演劇じゃないかと思う。", zh: "象征意义和真正应对威胁是两回事吧。我觉得这就是所谓的“安检表演”。", vi: "Mang tính biểu tượng và thực sự đối phó với một mối đe dọa thực tế là hai chuyện khác nhau. Tôi tự hỏi đây có phải là cái gọi là 'sân khấu an ninh' hay không." },
      { speaker: "혜리", kr: "완전히 틀린 말은 아닌데, 그래도 승객들한테 심리적 안정감을 준다는 순기능은 있지 않을까?", en: "That's not entirely wrong, but doesn't it still serve the positive function of giving passengers psychological reassurance?", ja: "全く間違った話ではないけど、それでも乗客に心理的な安心感を与えるという良い機能はあるんじゃない？", zh: "这话也不完全错，但它多少还是能给乘客带来心理上的安全感吧？", vi: "Điều đó không hoàn toàn sai, nhưng chẳng phải nó vẫn phục vụ chức năng tích cực là mang lại sự yên tâm về mặt tâm lý cho hành khách sao?" },
      { speaker: "정우", kr: "심리적 안정감을 위해 실질적인 위험 요소보다 확률이 낮은 시나리오에 자원을 쏟는 건 비효율적이라고 생각해.", en: "I think pouring resources into low-probability scenarios for the sake of psychological reassurance, at the expense of more realistic risks, is inefficient.", ja: "心理的安心感のために、実質的な危険要素より確率の低いシナリオに資源を注ぐのは非効率的だと思う。", zh: "为了心理安全感，把资源投入到概率更低的场景，而不是更现实的风险上，我觉得这是低效的。", vi: "Tôi nghĩ việc đổ nguồn lực vào những kịch bản xác suất thấp vì lợi ích yên tâm tâm lý, trong khi bỏ qua những rủi ro thực tế hơn, là không hiệu quả." },
      { speaker: "혜리", kr: "그럼 어떤 방식이 더 효율적이라고 봐? 무작위 검사나 행동 분석 쪽이 나을까?", en: "Then what approach do you think would be more efficient? Random checks, or behavioral analysis?", ja: "じゃあどんな方式がもっと効率的だと思う？無作為検査や行動分析の方がいいのかな？", zh: "那你觉得哪种方式更有效？随机抽查还是行为分析比较好？", vi: "Vậy anh nghĩ cách tiếp cận nào sẽ hiệu quả hơn? Kiểm tra ngẫu nhiên, hay phân tích hành vi?" },
      { speaker: "정우", kr: "개인적으로는 데이터 기반 위험 평가를 강화하는 게 낫다고 봐. 모두를 똑같이 검사하는 것보다는.", en: "Personally I think strengthening data-driven risk assessment is better than checking everyone the same way.", ja: "個人的にはデータに基づくリスク評価を強化する方がいいと思う。みんなを同じように検査するよりは。", zh: "我个人认为加强基于数据的风险评估更好，而不是对所有人一视同仁地检查。", vi: "Cá nhân tôi nghĩ việc tăng cường đánh giá rủi ro dựa trên dữ liệu tốt hơn là kiểm tra mọi người theo cùng một cách." },
      { speaker: "혜리", kr: "그건 인종이나 국적 프로파일링으로 흐를 위험도 있잖아. 그 부작용은 어떻게 보완할 건데?", en: "But that risks sliding into racial or nationality profiling. How would you address that side effect?", ja: "それは人種や国籍プロファイリングに流れる危険もあるじゃない。その副作用はどう補うつもり？", zh: "但那也有滑向种族或国籍画像的风险吧？这个副作用你打算怎么弥补？", vi: "Nhưng điều đó có nguy cơ trượt sang việc phân biệt chủng tộc hoặc quốc tịch. Anh sẽ giải quyết mặt tác dụng phụ đó thế nào?" },
      { speaker: "정우", kr: "맞는 지적이야. 완벽한 해법은 없겠지만, 적어도 효과성에 대한 검증 없이 관행을 유지하는 건 재고해야 한다고 봐.", en: "That's a fair point. There's no perfect solution, but at the very least I think we should reconsider maintaining practices without verifying their effectiveness.", ja: "その通りの指摘だね。完璧な解決策はないだろうけど、少なくとも効果性の検証なしに慣行を維持するのは再考すべきだと思う。", zh: "你说得对。虽然没有完美的解决方案，但至少我认为不该在没有验证有效性的情况下继续维持这种惯例。", vi: "Đó là một điểm hợp lý. Không có giải pháp hoàn hảo, nhưng ít nhất tôi nghĩ chúng ta nên xem xét lại việc duy trì các thực hành mà không kiểm chứng hiệu quả của chúng." },
    ],
  },
  {
    id: "airport-c1y-liminal",
    situationKey: "airport",
    level: "C1",
    title: { en: "Strangers on the liminal nature of airports", ja: "空港という中間地帯について語る見知らぬ者同士", zh: "陌生人谈论机场的阈限特质", vi: "Người lạ bàn về bản chất trung gian của sân bay" },
    lines: [
      { speaker: "여행자 A", kr: "실례지만, 공항이라는 공간이 참 묘하지 않아요? 어디에도 속하지 않은 느낌이랄까요.", en: "Excuse me, but isn't this place, the airport, kind of strange? It feels like it belongs nowhere.", ja: "失礼ですが、空港というこの空間、なんだか不思議じゃないですか？どこにも属していない感じというか。", zh: "不好意思，机场这个地方是不是挺奇妙的？有种不属于任何地方的感觉。", vi: "Xin lỗi, nhưng chẳng phải nơi này, sân bay, hơi kỳ lạ sao? Nó có cảm giác như không thuộc về đâu cả." },
      { speaker: "여행자 B", kr: "저도 늘 그렇게 느꼈어요. 출국 심사를 지나는 순간부터 이미 이 나라를 떠난 것도, 아직 안 떠난 것도 아닌 상태가 되잖아요.", en: "I've always felt that way too. The moment you pass through departure inspection, you're neither still in this country nor yet gone.", ja: "私もいつもそう感じていました。出国審査を通過した瞬間から、もうこの国を離れたわけでも、まだ離れていないわけでもない状態になりますよね。", zh: "我也一直有这种感觉。一过出境审查，就变成既不算还在这个国家、也不算已经离开的状态了。", vi: "Tôi luôn cảm thấy như vậy. Khoảnh khắc anh đi qua khu kiểm tra xuất cảnh, anh không còn ở đất nước này nữa mà cũng chưa thực sự rời đi." },
      { speaker: "여행자 A", kr: "그래서인지 여기서는 사람들이 평소랑 다르게 행동하는 것 같아요. 낯선 사람한테도 쉽게 말을 걸고요.", en: "Maybe that's why people seem to act differently here. They start conversations with strangers more easily too.", ja: "だからか、ここでは人が普段と違う行動をする気がします。見知らぬ人にも気軽に話しかけたりして。", zh: "也许正因如此，在这里人们的举止好像和平时不一样，也更容易主动和陌生人搭话。", vi: "Có lẽ đó là lý do người ta có vẻ hành xử khác ở đây. Họ cũng dễ dàng bắt chuyện với người lạ hơn." },
      { speaker: "여행자 B", kr: "일상의 규칙이 잠시 유예되는 공간이라서 그런 게 아닐까요. 다시 만날 일이 없다는 걸 아니까요.", en: "Maybe it's because it's a space where the rules of daily life are temporarily suspended. You know you'll probably never meet again.", ja: "日常の規則が一時的に猶予される空間だからではないでしょうか。二度と会うことがないと分かっているから。", zh: "也许是因为这里是日常规则暂时被搁置的空间吧，毕竟大家都知道以后不会再见了。", vi: "Có lẽ vì đây là không gian mà quy tắc của đời sống thường nhật tạm thời bị đình chỉ. Anh biết rằng có lẽ mình sẽ không bao giờ gặp lại họ nữa." },
      { speaker: "여행자 A", kr: "인류학자들이 이런 공간을 '리미널 스페이스'라고 부른다고 들었어요. 통과의례 사이에 낀 중간 지대라는 뜻이라던데요.", en: "I heard anthropologists call this kind of space a 'liminal space' — meaning an in-between zone caught between rites of passage.", ja: "人類学者はこういう空間を「リミナル・スペース」と呼ぶそうです。通過儀礼の間に挟まれた中間地帯という意味らしいです。", zh: "我听说人类学家把这种空间称为“阈限空间”，意思是夹在通过仪式之间的中间地带。", vi: "Tôi nghe nói các nhà nhân học gọi loại không gian này là 'không gian ngưỡng' — nghĩa là một vùng trung gian bị kẹt giữa các nghi thức chuyển tiếp." },
      { speaker: "여행자 B", kr: "듣고 보니 정말 그러네요. 여기 있는 동안은 과거의 나도, 도착지에서의 나도 아닌 것 같아요.", en: "Now that you mention it, that's really true. While I'm here, I feel like neither my past self nor the self I'll be at the destination.", ja: "言われてみると本当にそうですね。ここにいる間は過去の自分でも、到着地での自分でもない気がします。", zh: "听你这么一说确实是这样。待在这里的时候，感觉自己既不是过去的自己，也不是到达目的地后的自己。", vi: "Anh nhắc mới nhớ, đúng là như vậy thật. Trong lúc ở đây, tôi cảm thấy mình không còn là con người trước đây, cũng chưa phải con người tôi sẽ trở thành ở điểm đến." },
      { speaker: "여행자 A", kr: "그런 불확실함이 불안하기도 하지만, 동시에 묘한 해방감을 주기도 하는 것 같아요.", en: "That uncertainty is a little unsettling, but at the same time it seems to give a strange sense of freedom.", ja: "そういう不確実さが不安でもありますが、同時に不思議な解放感を与えてくれる気もします。", zh: "这种不确定感虽然让人有点不安，但同时似乎也带来一种奇妙的解放感。", vi: "Sự bất định đó hơi khiến người ta bất an, nhưng đồng thời có vẻ mang lại một cảm giác tự do kỳ lạ." },
      { speaker: "여행자 B", kr: "맞아요. 어쩌면 그래서 사람들이 공항에서 낯선 이한테 속마음을 더 쉽게 털어놓는 걸지도 모르겠네요.", en: "Right. Maybe that's exactly why people find it easier to open up to strangers at airports.", ja: "そうですね。もしかしたらだから人は空港で見知らぬ人に本音を打ち明けやすいのかもしれませんね。", zh: "对啊。也许正因如此，人们在机场更容易向陌生人敞开心扉吧。", vi: "Đúng vậy. Có lẽ chính vì thế mà người ta thấy dễ dàng cởi mở với người lạ ở sân bay hơn." },
    ],
  },
  {
    id: "airport-c2y-atc",
    situationKey: "airport",
    level: "C2",
    title: { en: "Air traffic controllers' union negotiation snippet", ja: "航空管制官労組の交渉の一場面", zh: "空管人员工会谈判片段", vi: "Trích đoạn đàm phán công đoàn kiểm soát viên không lưu" },
    lines: [
      { speaker: "노조 대표", kr: "관제 인력 부족 문제는 이미 여러 차례 경고해 왔습니다. 이번 협상에서 인력 충원 없이는 합의가 불가능합니다.", en: "We've already warned about the controller staffing shortage on multiple occasions. Without a staffing increase in this negotiation, an agreement is impossible.", ja: "管制人員不足の問題はすでに何度も警告してきました。今回の交渉で人員補充がなければ合意は不可能です。", zh: "关于管制人员不足的问题我们已经多次警告过。这次谈判如果不增加人员，就不可能达成协议。", vi: "Chúng tôi đã nhiều lần cảnh báo về tình trạng thiếu nhân viên kiểm soát không lưu. Nếu đàm phán lần này không có việc tăng nhân sự, thỏa thuận sẽ là điều không thể." },
      { speaker: "당국 대표", kr: "예산 편성 절차상 즉각적인 충원은 현실적으로 어렵습니다. 다만 단계적 확대 방안은 검토할 수 있습니다.", en: "Given the budget allocation process, immediate hiring is realistically difficult. However, a phased expansion plan could be considered.", ja: "予算編成手続き上、即座の補充は現実的に難しいです。ただし段階的拡大案は検討できます。", zh: "由于预算编列程序的关系，立即增员在现实中很困难，不过可以考虑分阶段扩编的方案。", vi: "Xét theo quy trình phân bổ ngân sách, việc tuyển dụng ngay lập tức trên thực tế là khó khăn. Tuy nhiên, có thể xem xét một kế hoạch mở rộng theo giai đoạn." },
      { speaker: "노조 대표", kr: "단계적이라는 말이 결국 몇 년씩 미뤄지는 걸 저희는 이미 경험했습니다. 현장 관제사들은 이미 초과 근무로 번아웃 상태예요.", en: "We've already experienced how 'phased' ends up meaning delays of several years. Frontline controllers are already burned out from overtime.", ja: "「段階的」という言葉が結局何年も先送りされることを私たちはすでに経験しています。現場の管制官はすでに超過勤務でバーンアウト状態です。", zh: "我们已经亲身经历过“分阶段”最后拖延好几年是什么意思。一线管制员已经因为超时工作而精疲力竭了。", vi: "Chúng tôi đã từng trải qua việc 'theo giai đoạn' rốt cuộc có nghĩa là trì hoãn nhiều năm. Các kiểm soát viên tuyến đầu đã kiệt sức vì làm thêm giờ rồi." },
      { speaker: "당국 대표", kr: "그 우려는 이해합니다만, 신규 채용 인력이 실제 독립 관제까지 갖추려면 최소 이 년 이상의 훈련 기간이 필요한 게 현실입니다.", en: "I understand that concern, but the reality is that newly hired staff need at least two years of training before they can reach independent controller status.", ja: "その懸念は理解しますが、新規採用人員が実際に単独管制ができるようになるには最低2年以上の訓練期間が必要なのが現実です。", zh: "我理解这个担忧，但现实是新招聘的人员要具备独立管制能力，至少需要两年以上的培训期。", vi: "Tôi hiểu mối lo đó, nhưng thực tế là nhân viên mới tuyển cần ít nhất hai năm đào tạo trước khi đạt được vị trí kiểm soát viên độc lập." },
      { speaker: "노조 대표", kr: "그래서 지금 당장 시작해야 한다는 겁니다. 훈련 기간이 길수록 결정을 미룰 이유가 아니라 서두를 이유가 되어야죠.", en: "That's exactly why we need to start right now. A longer training period should be a reason to hurry, not a reason to delay the decision.", ja: "だから今すぐ始めるべきだということです。訓練期間が長いほど決定を先送りする理由ではなく、急ぐ理由になるべきです。", zh: "所以我们才需要现在马上开始。培训期越长，越应该是加快决策的理由，而不是拖延的理由。", vi: "Chính vì thế mà chúng ta cần bắt đầu ngay bây giờ. Thời gian đào tạo dài hơn nên là lý do để gấp rút, chứ không phải lý do để trì hoãn quyết định." },
      { speaker: "당국 대표", kr: "일리 있는 지적입니다. 다만 관제사 근무 시간 상한 조정과 충원 규모를 연계해서 다뤄야 예산 부처를 설득할 수 있을 것 같습니다.", en: "That's a fair point. However, we'll likely need to link the adjustment of controller working-hour caps with the staffing scale to persuade the budget authorities.", ja: "一理ある指摘です。ただ、管制官の勤務時間上限調整と補充規模を連携して扱ってこそ、予算部署を説得できると思います。", zh: "这个说法有道理。不过恐怕要把管制员工时上限的调整和增员规模挂钩来处理，才能说服预算部门。", vi: "Đó là một điểm hợp lý. Tuy nhiên, chúng tôi có lẽ sẽ cần liên kết việc điều chỉnh giới hạn giờ làm việc của kiểm soát viên với quy mô nhân sự để thuyết phục cơ quan ngân sách." },
      { speaker: "노조 대표", kr: "근무 시간 상한 조정에는 동의하지만, 그게 충원 지연의 명분으로 악용되어서는 안 됩니다. 서면으로 시한을 못박아 주시죠.", en: "We agree to adjusting working-hour caps, but that must not be exploited as a pretext for delaying staffing. Please put a deadline in writing.", ja: "勤務時間上限の調整には同意しますが、それが補充遅延の口実に悪用されてはいけません。書面で期限を明記してください。", zh: "我们同意调整工时上限，但这不能被拿来当作拖延增员的借口。请书面明确期限。", vi: "Chúng tôi đồng ý điều chỉnh giới hạn giờ làm việc, nhưng điều đó không được lợi dụng làm cái cớ để trì hoãn việc tuyển dụng. Xin hãy ghi rõ thời hạn bằng văn bản." },
      { speaker: "당국 대표", kr: "구체적인 시한 명시는 상부 승인이 필요한 사안이라 이 자리에서 즉답은 어렵지만, 최대한 반영하도록 노력하겠습니다.", en: "Specifying a concrete deadline requires higher-level approval, so I can't give an immediate answer here, but I'll try to reflect it as much as possible.", ja: "具体的な期限の明記は上層部の承認が必要な事案なので、この場で即答は難しいですが、できる限り反映するよう努力します。", zh: "明确具体期限需要上级批准，我现在没法当场答复，但会尽量争取反映您的要求。", vi: "Việc quy định thời hạn cụ thể cần được phê duyệt cấp cao hơn, nên tôi không thể trả lời ngay tại đây, nhưng tôi sẽ cố gắng phản ánh điều đó nhiều nhất có thể." },
      { speaker: "노조 대표", kr: "노력이라는 말만으로는 조합원들을 설득할 수 없습니다. 다음 협상까지 구체적인 시한 초안을 준비해 오시기 바랍니다.", en: "The word 'try' alone won't persuade our members. Please come to the next negotiation with a concrete draft deadline prepared.", ja: "努力という言葉だけでは組合員を説得できません。次の交渉までに具体的な期限案を準備してきてください。", zh: "光说“尽量”是说服不了工会成员的。请在下次谈判前准备好具体的期限草案。", vi: "Chỉ riêng từ 'cố gắng' sẽ không thuyết phục được các thành viên của chúng tôi. Xin hãy chuẩn bị một bản dự thảo thời hạn cụ thể cho cuộc đàm phán tiếp theo." },
    ],
  },
  {
    id: "airport-c2y-hub",
    situationKey: "airport",
    level: "C2",
    title: { en: "Debating whether the airport should be a mega-hub", ja: "空港を巨大ハブにすべきかを議論する", zh: "争论机场是否应打造成超级枢纽", vi: "Tranh luận liệu sân bay có nên trở thành trung tâm hàng không lớn" },
    lines: [
      { speaker: "평론가", kr: "정부가 이 공항을 동북아 허브로 키우겠다는 청사진을 내놨는데, 저는 이 전략 자체가 시대착오적이라고 봅니다.", en: "The government has put forward a blueprint to grow this airport into a Northeast Asian hub, but I think the strategy itself is anachronistic.", ja: "政府がこの空港を東北アジアのハブに育てるという青写真を出しましたが、私はこの戦略自体が時代錯誤だと思います。", zh: "政府提出了要把这个机场打造成东北亚枢纽的蓝图，但我认为这个战略本身就已经过时了。", vi: "Chính phủ đã đưa ra kế hoạch phát triển sân bay này thành trung tâm hàng không khu vực Đông Bắc Á, nhưng tôi nghĩ bản thân chiến lược này đã lỗi thời." },
      { speaker: "학자", kr: "동의하기 어렵네요. 환승 수요를 흡수하지 못하면 주변국 허브 공항들에 우리 항공 산업의 부가가치를 다 내주는 셈이 됩니다.", en: "I find that hard to agree with. If we fail to capture transfer demand, we'll effectively hand over all the added value of our aviation industry to neighboring hub airports.", ja: "同意しかねます。乗り継ぎ需要を吸収できなければ、周辺国のハブ空港に我が国の航空産業の付加価値をすべて渡してしまうことになります。", zh: "这我很难认同。如果不能吸收中转需求，我们航空产业的附加值就会全部拱手让给周边国家的枢纽机场。", vi: "Tôi thấy khó đồng ý với điều đó. Nếu chúng ta không thu hút được nhu cầu trung chuyển, chúng ta sẽ thực chất trao toàn bộ giá trị gia tăng của ngành hàng không cho các sân bay trung tâm lân cận." },
      { speaker: "평론가", kr: "부가가치를 논하기 전에, 대규모 확장이 초래할 환경 비용과 지역 사회 갈등부터 따져 봐야 하지 않을까요.", en: "Before discussing added value, shouldn't we first weigh the environmental cost and community conflict that large-scale expansion will bring?", ja: "付加価値を論じる前に、大規模拡張がもたらす環境コストと地域社会の葛藤からまず検討すべきではないでしょうか。", zh: "在讨论附加值之前，是不是应该先权衡大规模扩建带来的环境成本和社区矛盾？", vi: "Trước khi bàn về giá trị gia tăng, chẳng phải chúng ta nên cân nhắc trước chi phí môi trường và xung đột cộng đồng mà việc mở rộng quy mô lớn sẽ mang lại sao?" },
      { speaker: "학자", kr: "물론 그 비용을 간과해서는 안 되지만, 허브 지위를 상실했을 때 발생할 일자리와 관광 수입의 장기적 손실도 함께 계산에 넣어야 공정한 논의가 됩니다.", en: "Of course those costs shouldn't be overlooked, but for a fair discussion we must also factor in the long-term loss of jobs and tourism revenue if hub status is lost.", ja: "もちろんそのコストを見過ごしてはいけませんが、ハブの地位を失った場合に生じる雇用と観光収入の長期的損失も一緒に計算に入れてこそ公正な議論になります。", zh: "当然不能忽视那些成本，但如果失去枢纽地位所带来的就业和旅游收入的长期损失也一并计入，才算是公平的讨论。", vi: "Tất nhiên những chi phí đó không nên bị bỏ qua, nhưng để có một cuộc thảo luận công bằng, chúng ta cũng phải tính đến việc mất việc làm và doanh thu du lịch dài hạn nếu để mất vị thế trung tâm." },
      { speaker: "평론가", kr: "장기적 손실이라는 가정 자체가 항공 수요 예측이라는 불확실한 전제 위에 서 있다는 걸 지적하고 싶습니다. 팬데믹 이후 수요 패턴이 근본적으로 바뀌었잖아요.", en: "I'd point out that the assumption of long-term loss itself rests on the uncertain premise of aviation demand forecasting. Demand patterns have fundamentally shifted since the pandemic.", ja: "長期的損失という仮定自体が、航空需要予測という不確実な前提の上に立っていることを指摘したいです。パンデミック以降、需要パターンが根本的に変わったじゃないですか。", zh: "我想指出，长期损失这个假设本身就建立在航空需求预测这个不确定的前提之上。疫情之后需求模式已经发生了根本性变化。", vi: "Tôi muốn chỉ ra rằng giả định về thiệt hại dài hạn tự nó dựa trên tiền đề bất định của dự báo nhu cầu hàng không. Xu hướng nhu cầu đã thay đổi căn bản kể từ đại dịch." },
      { speaker: "학자", kr: "패턴이 바뀐 건 맞지만, 오히려 화물 운송과 비즈니스 수요는 회복세를 넘어 성장하고 있다는 지표도 있습니다.", en: "It's true the pattern has changed, but there are also indicators showing cargo transport and business demand have not just recovered but are growing.", ja: "パターンが変わったのは事実ですが、むしろ貨物輸送とビジネス需要は回復を超えて成長しているという指標もあります。", zh: "模式确实变了，但也有指标显示货运和商务需求不仅恢复了，还在增长。", vi: "Đúng là xu hướng đã thay đổi, nhưng cũng có những chỉ số cho thấy vận tải hàng hóa và nhu cầu công tác không chỉ hồi phục mà còn đang tăng trưởng." },
      { speaker: "평론가", kr: "결국 이 논쟁은 성장 지상주의와 지속 가능성 사이의 오래된 긴장의 재현일 뿐이라고 생각합니다.", en: "In the end, I think this debate is simply a rehash of the old tension between growth-at-all-costs thinking and sustainability.", ja: "結局この論争は成長至上主義と持続可能性の間の古い緊張の再現に過ぎないと思います。", zh: "归根结底，我认为这场争论不过是增长至上主义和可持续性之间那种老矛盾的重演罢了。", vi: "Cuối cùng, tôi nghĩ cuộc tranh luận này chỉ là sự lặp lại của căng thẳng cũ giữa tư duy tăng trưởng bằng mọi giá và tính bền vững." },
      { speaker: "학자", kr: "그 긴장을 인정하더라도, 정책 결정은 결국 구체적인 수치와 시나리오 분석에 기반해야지 이념적 대립으로 환원될 문제는 아니라고 봅니다.", en: "Even granting that tension, I believe policy decisions ultimately need to be based on concrete figures and scenario analysis, not reduced to an ideological clash.", ja: "その緊張を認めるとしても、政策決定は結局具体的な数値とシナリオ分析に基づくべきで、理念的対立に還元される問題ではないと思います。", zh: "即便承认这种矛盾，我认为政策决策终究应该基于具体数据和情景分析，而不能简化成意识形态的对立。", vi: "Ngay cả khi thừa nhận căng thẳng đó, tôi tin rằng các quyết định chính sách cuối cùng cần dựa trên số liệu cụ thể và phân tích kịch bản, chứ không nên bị giản lược thành xung đột ý thức hệ." },
      { speaker: "평론가", kr: "그 점에는 동의합니다. 다만 그 수치를 누가 산출하고 누구의 이해관계가 반영되는지도 함께 검증해야겠죠.", en: "I agree on that point. But we also need to verify who produces those figures and whose interests are reflected in them.", ja: "その点には同意します。ただ、その数値を誰が算出し、誰の利害関係が反映されているのかも一緒に検証すべきでしょう。", zh: "这一点我同意。但也需要一并核实这些数据是谁算出来的、又反映了谁的利益。", vi: "Tôi đồng ý với điểm đó. Nhưng chúng ta cũng cần xác minh ai là người tạo ra những số liệu đó và lợi ích của ai được phản ánh trong đó." },
    ],
  },
  {
    id: "airport-c2y-biometric",
    situationKey: "airport",
    level: "C2",
    title: { en: "Journalistic commentary on biometric boarding", ja: "生体認証搭乗についての報道解説", zh: "关于生物识别登机的新闻评论", vi: "Bình luận báo chí về lên máy bay bằng sinh trắc học" },
    lines: [
      { speaker: "진행자", kr: "이제 여권 없이 얼굴 인식만으로 탑승하는 시대가 왔다고 하는데요, 오늘은 이 생체 인증 탑승 시스템의 명암을 짚어 보겠습니다.", en: "It seems we've now entered an era where you can board with just facial recognition, no passport needed. Today we'll examine the light and shadow of this biometric boarding system.", ja: "今やパスポートなしで顔認証だけで搭乗できる時代になったそうですが、今日はこの生体認証搭乗システムの光と影を見ていきます。", zh: "现在已经进入无需护照、只靠人脸识别就能登机的时代了，今天我们来探讨一下这种生物识别登机系统的利与弊。", vi: "Có vẻ chúng ta đã bước vào thời đại mà chỉ cần nhận diện khuôn mặt là có thể lên máy bay, không cần hộ chiếu. Hôm nay chúng ta sẽ xem xét cả mặt sáng lẫn mặt tối của hệ thống lên máy bay bằng sinh trắc học này." },
      { speaker: "전문가", kr: "속도 면에서는 확실히 혁신적입니다. 게이트 통과 시간이 기존 대비 삼분의 일로 줄었다는 통계도 있고요.", en: "In terms of speed, it's certainly innovative. There are statistics showing gate transit time dropped to a third of what it used to be.", ja: "スピードの面では確かに革新的です。ゲート通過時間が従来の三分の一に減ったという統計もあります。", zh: "在速度方面确实具有革新性。有统计数据显示，登机口通过时间缩短到了以前的三分之一。", vi: "Về mặt tốc độ, đây chắc chắn là một đổi mới. Có thống kê cho thấy thời gian qua cửa lên máy bay đã giảm xuống còn một phần ba so với trước." },
      { speaker: "진행자", kr: "다만 개인 정보 보호 측면에서는 우려의 목소리도 만만치 않습니다. 이 데이터가 어디까지 활용될 수 있는지가 관건 아닐까요.", en: "However, concerns over privacy protection are no small matter either. Isn't the key question how far this data could be used?", ja: "ただ、個人情報保護の面では懸念の声も小さくありません。このデータがどこまで活用されうるのかが鍵ではないでしょうか。", zh: "不过在个人信息保护方面的担忧声音也不小。这些数据能被利用到什么程度，才是关键问题吧？", vi: "Tuy nhiên, mối lo về bảo vệ quyền riêng tư cũng không hề nhỏ. Chẳng phải câu hỏi then chốt là dữ liệu này có thể được sử dụng đến đâu sao?" },
      { speaker: "전문가", kr: "맞습니다. 항공사는 탑승 목적으로만 쓴다고 하지만, 제삼자 제공이나 장기 보관 여부에 대한 투명한 공시가 부족한 게 현실이죠.", en: "Right. Airlines say it's used only for boarding purposes, but the reality is there's a lack of transparent disclosure about third-party sharing or long-term retention.", ja: "そうです。航空会社は搭乗目的にのみ使うと言いますが、第三者提供や長期保管の有無についての透明な公示が不足しているのが現実です。", zh: "没错。航空公司说只用于登机目的，但现实是关于是否提供给第三方或长期保存，缺乏透明的公开说明。", vi: "Đúng vậy. Các hãng bay nói rằng nó chỉ được dùng cho mục đích lên máy bay, nhưng thực tế là thiếu sự công khai minh bạch về việc chia sẻ với bên thứ ba hoặc lưu trữ dài hạn." },
      { speaker: "진행자", kr: "일각에서는 이런 기술이 편의라는 명목으로 감시 사회를 정당화하는 발판이 될 수 있다는 비판도 제기합니다.", en: "Some critics also raise the point that such technology, under the guise of convenience, could become a stepping stone to legitimizing a surveillance society.", ja: "一部ではこうした技術が利便性の名の下に監視社会を正当化する足場になりうるという批判も提起されています。", zh: "也有批评指出，这种技术打着便利的名义，可能成为让监控社会合理化的跳板。", vi: "Một số nhà phê bình cũng chỉ ra rằng công nghệ như vậy, dưới vỏ bọc tiện lợi, có thể trở thành bước đệm để hợp thức hóa một xã hội giám sát." },
      { speaker: "전문가", kr: "그 비판이 과장만은 아니라고 봅니다. 공항이라는 통제된 공간에서 시작된 생체 인증이 다른 공공 영역으로 확산될 가능성을 배제할 수 없거든요.", en: "I don't think that criticism is mere exaggeration. We can't rule out the possibility that biometric authentication, starting in the controlled space of the airport, could spread to other public domains.", ja: "その批判が誇張だけとは思いません。空港という統制された空間で始まった生体認証が、他の公共領域に拡散する可能性を排除できないからです。", zh: "我认为这种批评并非夸大其词。从机场这种受控空间开始的生物识别，不能排除会扩散到其他公共领域的可能性。", vi: "Tôi không nghĩ chỉ trích đó chỉ là phóng đại. Chúng ta không thể loại trừ khả năng xác thực sinh trắc học, bắt đầu từ không gian được kiểm soát của sân bay, sẽ lan sang các lĩnh vực công cộng khác." },
      { speaker: "진행자", kr: "그렇다면 소비자로서는 이 기술을 거부할 권리를 어떻게 보장받아야 할까요.", en: "So how should consumers be guaranteed the right to opt out of this technology?", ja: "それなら消費者としては、この技術を拒否する権利をどう保障してもらうべきでしょうか。", zh: "那么作为消费者，应该如何保障拒绝使用这项技术的权利呢？", vi: "Vậy làm sao để đảm bảo quyền từ chối sử dụng công nghệ này cho người tiêu dùng?" },
      { speaker: "전문가", kr: "적어도 생체 인증을 거부해도 동일한 대기 시간 안에 탑승할 수 있는 대안 절차가 명시적으로 보장되어야 한다고 봅니다.", en: "At the very least, I believe there needs to be an explicitly guaranteed alternative procedure that allows boarding within the same waiting time even if you opt out of biometric authentication.", ja: "少なくとも生体認証を拒否しても同じ待ち時間内に搭乗できる代替手続きが明示的に保障されるべきだと思います。", zh: "至少应该明确保障即便拒绝生物识别，也能在相同等待时间内登机的替代程序。", vi: "Ít nhất, tôi tin cần có một quy trình thay thế được đảm bảo rõ ràng, cho phép lên máy bay trong cùng thời gian chờ ngay cả khi từ chối xác thực sinh trắc học." },
      { speaker: "진행자", kr: "결국 기술의 편의성과 개인의 자기 결정권 사이에서 균형을 어떻게 찾느냐가 앞으로의 과제겠네요.", en: "In the end, how to strike a balance between technological convenience and individual self-determination will be the challenge going forward.", ja: "結局、技術の利便性と個人の自己決定権の間でどうバランスを取るかが今後の課題ですね。", zh: "归根结底，如何在技术便利性和个人自主决定权之间找到平衡，将是今后的课题。", vi: "Cuối cùng, cách cân bằng giữa sự tiện lợi công nghệ và quyền tự quyết cá nhân sẽ là thách thức trong thời gian tới." },
    ],
  },
  {
    id: "airport-c2y-slots",
    situationKey: "airport",
    level: "C2",
    title: { en: "Debating the fairness of slot allocation", ja: "発着枠配分の公正性を議論する", zh: "争论时段分配的公平性", vi: "Tranh luận về tính công bằng của phân bổ khe cất hạ cánh" },
    lines: [
      { speaker: "경제학자", kr: "혼잡 공항의 이착륙 슬롯을 지금처럼 관행적 배정 방식으로 유지하는 건 시장 효율성 측면에서 명백한 왜곡이라고 봅니다.", en: "Maintaining slot allocation at congested airports through the current customary system is, from a market efficiency standpoint, a clear distortion.", ja: "混雑空港の発着枠を今のように慣行的な配分方式で維持するのは、市場効率性の面で明白な歪みだと思います。", zh: "对于拥挤机场的起降时段，如果继续维持现在这种惯例分配方式，从市场效率角度来看是明显的扭曲。", vi: "Việc duy trì phân bổ khe cất/hạ cánh tại các sân bay đông đúc theo hệ thống thông lệ hiện tại, xét từ góc độ hiệu quả thị trường, rõ ràng là một sự méo mó." },
      { speaker: "항공사 관계자", kr: "왜곡이라기보다는 신생 항공사와 기존 항공사 간의 균형을 맞추기 위한 최소한의 안전판이라고 봐야 하지 않을까요.", en: "Rather than calling it a distortion, shouldn't we see it as a minimal safeguard for balancing between new entrants and incumbent carriers?", ja: "歪みというより、新興航空会社と既存航空会社の間のバランスを取るための最小限の安全弁と見るべきではないでしょうか。", zh: "与其说是扭曲，不如说这是平衡新兴航空公司和老牌航空公司之间关系的最低限度的安全阀吧？", vi: "Thay vì gọi đó là méo mó, chẳng phải chúng ta nên xem đó là một biện pháp bảo vệ tối thiểu để cân bằng giữa các hãng mới gia nhập và các hãng đã hoạt động sao?" },
      { speaker: "경제학자", kr: "안전판이라는 명목 아래 이미 슬롯을 선점한 대형 항공사들의 기득권이 고착화되는 부작용은 어떻게 설명하시겠습니까.", en: "How would you explain the side effect that, under the name of a safeguard, the vested interests of major carriers who already secured slots become entrenched?", ja: "安全弁という名目の下、すでに枠を先取りした大手航空会社の既得権が固定化される副作用はどう説明されますか。", zh: "在安全阀的名义下，已经抢占时段的大型航空公司既得利益被固化，这个副作用您怎么解释？", vi: "Anh sẽ giải thích thế nào về tác dụng phụ rằng, dưới danh nghĩa bảo vệ, lợi ích đã có sẵn của các hãng lớn đã giữ được khe cất/hạ cánh trở nên cố định?" },
      { speaker: "항공사 관계자", kr: "경매 방식으로 전환하면 자본력이 있는 항공사만 살아남고, 지방 노선처럼 수익성이 낮은 구간은 아예 사라질 위험이 있습니다.", en: "If we switch to an auction system, there's a risk that only well-capitalized airlines survive, and low-profit routes like regional connections could disappear entirely.", ja: "オークション方式に転換すると資本力のある航空会社だけが生き残り、地方路線のような収益性の低い区間は完全に消える危険があります。", zh: "如果改成拍卖方式，只有资本雄厚的航空公司才能生存，像地方航线这种盈利性低的航线有可能彻底消失。", vi: "Nếu chúng ta chuyển sang hệ thống đấu giá, có nguy cơ chỉ những hãng bay có vốn mạnh mới tồn tại được, và các tuyến ít lợi nhuận như kết nối khu vực có thể biến mất hoàn toàn." },
      { speaker: "경제학자", kr: "그 위험을 인정하더라도, 공익 노선에 한해 별도의 보조금이나 의무 배정을 병행하면 시장 효율성과 공공성을 동시에 확보할 수 있지 않을까요.", en: "Even granting that risk, couldn't we secure both market efficiency and public interest simultaneously by pairing it with separate subsidies or mandatory allocation for public-service routes?", ja: "その危険を認めるとしても、公益路線に限って別途の補助金や義務配分を並行すれば、市場効率性と公共性を同時に確保できるのではないでしょうか。", zh: "即便承认这个风险，如果针对公益航线单独设立补贴或强制分配，不就能同时确保市场效率和公共性吗？", vi: "Ngay cả khi thừa nhận rủi ro đó, chẳng phải chúng ta có thể đảm bảo cả hiệu quả thị trường lẫn lợi ích công cộng cùng lúc bằng cách kết hợp với trợ cấp riêng hoặc phân bổ bắt buộc cho các tuyến dịch vụ công?" },
      { speaker: "항공사 관계자", kr: "이론적으로는 그럴듯하지만, 실제 정책 설계 단계에서 그 경계선을 어디에 긋느냐를 두고 끝없는 로비와 갈등이 생길 겁니다.", en: "That sounds plausible in theory, but at the actual policy design stage, endless lobbying and conflict will arise over where exactly to draw that line.", ja: "理論的にはもっともらしいですが、実際の政策設計段階でその境界線をどこに引くかをめぐって果てしないロビー活動と葛藤が生じるでしょう。", zh: "理论上听起来不错，但在实际的政策设计阶段，围绕这条线该划在哪里，会引发无休止的游说和冲突。", vi: "Nghe có vẻ hợp lý về lý thuyết, nhưng ở giai đoạn thiết kế chính sách thực tế, sẽ nảy sinh vận động hành lang và xung đột không hồi kết về việc vạch ranh giới đó chính xác ở đâu." },
      { speaker: "경제학자", kr: "정치적 갈등이 예상된다는 이유로 비효율적인 현행 제도를 계속 방치하는 것도 정당화되기는 어렵다고 생각합니다.", en: "I also think it's hard to justify simply leaving the current inefficient system in place just because political conflict is anticipated.", ja: "政治的葛藤が予想されるという理由で非効率な現行制度を放置し続けることも正当化するのは難しいと思います。", zh: "以预见到政治冲突为由，继续放任现行低效制度不变，我认为也很难说得过去。", vi: "Tôi cũng nghĩ khó có thể biện minh cho việc đơn giản giữ nguyên hệ thống kém hiệu quả hiện tại chỉ vì dự đoán trước xung đột chính trị." },
      { speaker: "항공사 관계자", kr: "결국 전면적 개혁보다는 일부 슬롯부터 시범적으로 경매제를 도입해 데이터를 축적하는 점진적 접근이 현실적이지 않을까 싶습니다.", en: "In the end, rather than sweeping reform, I think a gradual approach — piloting an auction system on a portion of slots first to accumulate data — might be more realistic.", ja: "結局全面的改革よりは一部の枠から試験的にオークション制を導入してデータを蓄積する漸進的アプローチが現実的ではないかと思います。", zh: "归根结底，与其全面改革，不如先在部分时段试点拍卖制、积累数据，这种循序渐进的方式或许更现实。", vi: "Cuối cùng, thay vì cải cách triệt để, tôi nghĩ một cách tiếp cận dần dần — thí điểm hệ thống đấu giá trên một phần khe cất/hạ cánh trước để tích lũy dữ liệu — có thể thực tế hơn." },
      { speaker: "경제학자", kr: "점진적 접근에는 동의하지만, 시범 사업에 명확한 평가 지표와 종료 시점을 못박지 않으면 또 흐지부지될 우려가 있습니다.", en: "I agree with a gradual approach, but unless clear evaluation metrics and an end date are fixed for the pilot program, there's a risk it will fizzle out again.", ja: "漸進的アプローチには同意しますが、試験事業に明確な評価指標と終了時点を明記しなければ、また有耶無耶になる恐れがあります。", zh: "循序渐进的方式我同意，但如果不为试点项目明确评估指标和结束时间，恐怕又会不了了之。", vi: "Tôi đồng ý với cách tiếp cận dần dần, nhưng trừ khi các chỉ số đánh giá rõ ràng và ngày kết thúc được ấn định cho chương trình thí điểm, có nguy cơ nó sẽ lại chìm xuồng." },
    ],
  },
  {
    id: "airport-c2y-outsourcing",
    situationKey: "airport",
    level: "C2",
    title: { en: "Debate over outsourcing airport security", ja: "空港保安業務の民間委託をめぐる議論", zh: "关于机场安检外包的争论", vi: "Tranh luận về việc thuê ngoài an ninh sân bay" },
    lines: [
      { speaker: "칼럼니스트", kr: "공항 보안 업무를 민간 위탁으로 전환한 이후 인력 이직률이 급증했다는 통계가 나왔습니다. 이걸 어떻게 진단하십니까.", en: "Statistics show staff turnover has surged since airport security work was outsourced to private contractors. How do you diagnose this?", ja: "空港保安業務を民間委託に転換して以降、人材の離職率が急増したという統計が出ました。これをどう診断されますか。", zh: "有统计显示，机场安检业务转为民间外包后，人员离职率大幅上升。您怎么看这个问题？", vi: "Thống kê cho thấy tỷ lệ nghỉ việc của nhân viên đã tăng vọt kể từ khi công việc an ninh sân bay được thuê ngoài cho các nhà thầu tư nhân. Anh chẩn đoán điều này thế nào?" },
      { speaker: "노동 연구자", kr: "위탁 업체 간 저가 입찰 경쟁이 결국 인건비 압박으로 이어지고, 그게 근로 조건 악화와 이직률 상승으로 나타난 전형적인 구조입니다.", en: "This is the textbook structure where low-bid competition among contractors ultimately leads to wage pressure, which then manifests as worsening working conditions and rising turnover.", ja: "委託業者間の低価格入札競争が結局人件費圧迫につながり、それが労働条件の悪化と離職率の上昇として現れる典型的な構造です。", zh: "外包公司之间的低价竞标最终导致人力成本被压缩，进而表现为劳动条件恶化和离职率上升，这是一种典型的结构性问题。", vi: "Đây là cấu trúc sách giáo khoa nơi cạnh tranh đấu thầu giá thấp giữa các nhà thầu cuối cùng dẫn đến áp lực lương, sau đó biểu hiện thành điều kiện làm việc xấu đi và tỷ lệ nghỉ việc tăng." },
      { speaker: "칼럼니스트", kr: "그렇다면 보안이라는 국가 안전과 직결된 업무를 민간에 맡기는 것 자체가 애초에 잘못된 설계였다고 보시는 건가요.", en: "So do you see it as a flawed design from the outset to entrust a task directly tied to national security, like security screening, to the private sector at all?", ja: "それでは保安という国家の安全に直結する業務を民間に任せること自体が、そもそも間違った設計だったとお考えですか。", zh: "那么您认为，把安检这种直接关系国家安全的业务交给民间，本身从一开始就是设计上的错误吗？", vi: "Vậy anh có xem đây là một thiết kế sai lầm ngay từ đầu khi giao một công việc gắn liền trực tiếp với an ninh quốc gia, như sàng lọc an ninh, cho khu vực tư nhân không?" },
      { speaker: "노동 연구자", kr: "민간 위탁 자체를 전면 부정하기보다는, 최소 입찰가가 아니라 숙련도와 근속 연수를 평가 기준에 반영하는 방식으로 제도를 손봐야 한다고 봅니다.", en: "Rather than outright rejecting private outsourcing itself, I think the system needs to be reformed so that evaluation criteria reflect skill and tenure rather than just the lowest bid.", ja: "民間委託自体を全面否定するよりは、最低入札価格ではなく熟練度と勤続年数を評価基準に反映する方式に制度を手直しすべきだと思います。", zh: "与其全盘否定民间外包本身，不如把评价标准从最低报价改为反映熟练程度和工龄，从而改良这个制度。", vi: "Thay vì hoàn toàn bác bỏ việc thuê ngoài tư nhân, tôi nghĩ hệ thống cần được cải cách để tiêu chí đánh giá phản ánh kỹ năng và thâm niên thay vì chỉ giá thầu thấp nhất." },
      { speaker: "칼럼니스트", kr: "숙련도를 어떻게 객관적으로 측정할 수 있을지도 논쟁거리가 될 것 같은데요.", en: "How to objectively measure skill would itself seem to become a point of contention.", ja: "熟練度をどう客観的に測定できるかも論争の的になりそうですね。", zh: "如何客观衡量熟练程度，这本身似乎也会成为争议点。", vi: "Cách đo lường kỹ năng một cách khách quan tự nó có vẻ sẽ trở thành điểm gây tranh cãi." },
      { speaker: "노동 연구자", kr: "완벽한 지표는 없겠지만, 최소한 과거 사고 이력이나 재교육 이수율 같은 정량적 데이터를 반영하는 것부터 시작할 수 있다고 봅니다.", en: "There's no perfect metric, but at the very least I think we could start by reflecting quantitative data such as past incident history or retraining completion rates.", ja: "完璧な指標はないでしょうが、少なくとも過去の事故履歴や再教育履修率のような定量的データを反映することから始められると思います。", zh: "没有完美的指标，但至少可以从反映过去事故记录、再培训完成率等量化数据开始。", vi: "Không có thước đo hoàn hảo, nhưng ít nhất tôi nghĩ chúng ta có thể bắt đầu bằng cách phản ánh dữ liệu định lượng như lịch sử sự cố trong quá khứ hoặc tỷ lệ hoàn thành đào tạo lại." },
      { speaker: "칼럼니스트", kr: "일각에서는 아예 보안 업무를 공공 부문으로 재편입시켜야 한다는 주장도 있는데, 이 부분은 어떻게 보십니까.", en: "Some argue that security work should be fully reintegrated into the public sector. What's your view on that?", ja: "一部では保安業務を完全に公共部門に再編入すべきだという主張もありますが、この点についてはどうお考えですか。", zh: "也有人主张干脆把安检业务重新收归公共部门，您怎么看这个观点？", vi: "Một số người lập luận rằng công việc an ninh nên được tái tích hợp hoàn toàn vào khu vực công. Anh nghĩ sao về điều đó?" },
      { speaker: "노동 연구자", kr: "재정적으로나 행정적으로 단기간에 실현되기는 어려운 방안이지만, 장기적인 목표로 설정해 둘 가치는 충분하다고 생각합니다.", en: "It's a difficult plan to realize in the short term, both financially and administratively, but I think it's well worth setting as a long-term goal.", ja: "財政的にも行政的にも短期間で実現するのは難しい案ですが、長期的な目標として設定しておく価値は十分あると思います。", zh: "从财政和行政角度看，短期内很难实现，但作为长期目标来设定是完全值得的。", vi: "Đó là một kế hoạch khó thực hiện trong ngắn hạn, cả về tài chính lẫn hành chính, nhưng tôi nghĩ nó rất đáng để đặt làm mục tiêu dài hạn." },
      { speaker: "칼럼니스트", kr: "결국 이 문제도 비용 절감과 공공 안전이라는 가치 사이에서 사회가 어디에 우선순위를 둘 것인지의 문제로 귀결되는군요.", en: "In the end, this issue too comes down to where society places its priority between cost reduction and the value of public safety.", ja: "結局この問題もコスト削減と公共安全という価値の間で社会がどこに優先順位を置くかという問題に帰結しますね。", zh: "归根结底，这个问题也归结为社会在削减成本和公共安全这两种价值之间，究竟把优先级放在哪一边。", vi: "Cuối cùng, vấn đề này cũng quy về việc xã hội đặt ưu tiên ở đâu giữa cắt giảm chi phí và giá trị của an toàn công cộng." },
    ],
  },
  {
    id: "airport-c2y-noise",
    situationKey: "airport",
    level: "C2",
    title: { en: "Op-ed style commentary on night flight curfews", ja: "夜間飛行制限に関する論説風解説", zh: "关于夜航宵禁的评论性解说", vi: "Bình luận kiểu xã luận về lệnh giới nghiêm chuyến bay đêm" },
    lines: [
      { speaker: "해설자", kr: "야간 운항 제한 완화를 둘러싼 논쟁이 다시 불거지고 있습니다. 오늘은 이 사안을 다각도로 살펴보겠습니다.", en: "The debate over relaxing night flight curfews has flared up again. Today we'll examine this issue from multiple angles.", ja: "夜間運航制限緩和をめぐる論争が再び浮上しています。今日はこの問題を多角的に見ていきます。", zh: "围绕放宽夜间航班限制的争论再次浮出水面，今天我们将从多个角度审视这个问题。", vi: "Cuộc tranh luận về việc nới lỏng lệnh giới nghiêm chuyến bay đêm lại bùng lên. Hôm nay chúng ta sẽ xem xét vấn đề này từ nhiều góc độ." },
      { speaker: "패널", kr: "물류 업계 입장에서는 시차를 활용한 야간 화물 운송이 국제 경쟁력의 핵심입니다. 제한을 유지하면 화물 허브로서의 입지가 흔들릴 수 있습니다.", en: "From the logistics industry's standpoint, night cargo transport that leverages time zone differences is central to international competitiveness. Keeping the curfew could destabilize the airport's position as a cargo hub.", ja: "物流業界の立場では時差を活用した夜間貨物輸送が国際競争力の核心です。制限を維持すれば貨物ハブとしての地位が揺らぐ可能性があります。", zh: "从物流行业的角度看，利用时差进行的夜间货运是国际竞争力的核心。如果继续维持限制，可能会动摇作为货运枢纽的地位。", vi: "Từ góc độ ngành logistics, vận chuyển hàng hóa ban đêm tận dụng chênh lệch múi giờ là trung tâm của khả năng cạnh tranh quốc tế. Duy trì lệnh giới nghiêm có thể làm lung lay vị thế trung tâm vận chuyển hàng hóa của sân bay." },
      { speaker: "해설자", kr: "반면 인근 주민들에게는 수면권 침해라는 훨씬 직접적이고 즉각적인 피해로 다가오지 않겠습니까.", en: "On the other hand, wouldn't this arrive for nearby residents as a much more direct and immediate harm — an infringement of their right to sleep?", ja: "一方で近隣住民には睡眠権侵害という、はるかに直接的で即座の被害として迫るのではないでしょうか。", zh: "但另一方面，对附近居民来说，这不就是侵犯睡眠权这种更直接、更即时的伤害吗？", vi: "Mặt khác, chẳng phải điều này sẽ đến với cư dân xung quanh như một thiệt hại trực tiếp và tức thời hơn nhiều — sự xâm phạm quyền được ngủ của họ sao?" },
      { speaker: "패널", kr: "그 지적에 반박할 생각은 없습니다. 다만 소음 저감 항공기 도입을 조건으로 제한적 완화를 시범 운영해 보는 절충안도 고려할 만하다고 봅니다.", en: "I have no intention of disputing that point. However, I think a compromise worth considering is piloting a limited relaxation on the condition that noise-reducing aircraft are introduced.", ja: "その指摘に反論するつもりはありません。ただ、騒音低減機の導入を条件に限定的な緩和を試験運営してみる妥協案も検討する価値があると思います。", zh: "我不打算反驳这一点。不过我认为，以引进降噪飞机为条件，试点实施有限度的放宽，也是一个值得考虑的折中方案。", vi: "Tôi không có ý định tranh cãi điểm đó. Tuy nhiên, tôi nghĩ một thỏa hiệp đáng cân nhắc là thí điểm nới lỏng có giới hạn với điều kiện đưa vào sử dụng máy bay giảm tiếng ồn." },
      { speaker: "해설자", kr: "소음 저감 항공기라는 기술적 해법이 정책적 완화를 정당화할 만큼 충분히 검증되었다고 보십니까.", en: "Do you consider the technical solution of noise-reducing aircraft to be sufficiently proven to justify policy relaxation?", ja: "騒音低減機という技術的解決策が政策的緩和を正当化するほど十分に検証されているとお考えですか。", zh: "您认为降噪飞机这种技术方案，已经得到了足以为政策放宽提供正当性的充分验证吗？", vi: "Anh có cho rằng giải pháp kỹ thuật máy bay giảm tiếng ồn đã được chứng minh đủ để biện minh cho việc nới lỏng chính sách không?" },
      { speaker: "패널", kr: "완전한 해결책은 아니지만, 기존 기종 대비 체감 소음이 상당히 줄어든다는 실증 데이터는 이미 축적되어 있습니다.", en: "It's not a complete solution, but empirical data has already accumulated showing perceived noise is substantially reduced compared to older aircraft models.", ja: "完全な解決策ではありませんが、従来機種に比べて体感騒音がかなり減るという実証データはすでに蓄積されています。", zh: "虽然不是完全的解决方案，但已经积累了实证数据，显示与旧机型相比感知噪音大幅降低。", vi: "Đó không phải là giải pháp hoàn chỉnh, nhưng dữ liệu thực nghiệm đã tích lũy cho thấy tiếng ồn cảm nhận được giảm đáng kể so với các mẫu máy bay cũ." },
      { speaker: "해설자", kr: "그렇다 해도 주민들 입장에서는 소음이 줄어든다는 것과 아예 없어지는 것 사이의 간극을 받아들이기 쉽지 않을 텐데요.", en: "Even so, for residents, the gap between reduced noise and no noise at all wouldn't be easy to accept.", ja: "そうだとしても住民の立場では、騒音が減るということと完全になくなることの間の隔たりを受け入れるのは容易ではないでしょう。", zh: "即便如此，对居民来说，噪音减少和噪音完全消失之间的差距，恐怕也不容易接受。", vi: "Dù vậy, đối với cư dân, khoảng cách giữa tiếng ồn giảm và không có tiếng ồn hoàn toàn sẽ không dễ chấp nhận." },
      { speaker: "패널", kr: "그래서 저는 이 사안을 순수하게 기술이나 경제 논리로만 풀 수 없고, 결국 보상과 신뢰 구축이라는 사회적 합의 과정이 병행되어야 한다고 봅니다.", en: "That's why I believe this issue can't be resolved purely through technical or economic logic, and ultimately a social consensus process involving compensation and trust-building must proceed in parallel.", ja: "だから私はこの問題を純粋に技術や経済論理だけでは解決できず、結局補償と信頼構築という社会的合意プロセスが並行されるべきだと思います。", zh: "所以我认为这个问题不能单靠技术或经济逻辑来解决，最终还需要并行推进补偿与建立信任的社会共识过程。", vi: "Đó là lý do tôi tin vấn đề này không thể giải quyết thuần túy bằng logic kỹ thuật hay kinh tế, và cuối cùng một quá trình đồng thuận xã hội bao gồm bồi thường và xây dựng lòng tin phải tiến hành song song." },
      { speaker: "해설자", kr: "결국 완화와 제한 사이의 이분법이 아니라, 그 중간 지대를 어떻게 설계하느냐가 관건이라는 말씀이시군요.", en: "So in the end, rather than a binary between relaxation and restriction, the key is how we design the middle ground between them.", ja: "結局緩和と制限の二分法ではなく、その中間地帯をどう設計するかが鍵だというお話ですね。", zh: "也就是说，问题的关键不在于放宽与限制的二选一，而在于如何设计两者之间的中间地带。", vi: "Vậy cuối cùng, thay vì lựa chọn nhị phân giữa nới lỏng và hạn chế, mấu chốt là cách chúng ta thiết kế vùng trung gian giữa hai điều đó." },
    ],
  },
  {
    id: "airport-c2y-privatization",
    situationKey: "airport",
    level: "C2",
    title: { en: "Debate over airport privatization", ja: "空港民営化をめぐる議論", zh: "关于机场私有化的争论", vi: "Tranh luận về tư nhân hóa sân bay" },
    lines: [
      { speaker: "정치인", kr: "공항 지분을 민간 자본에 매각하면 만성적인 재정 적자를 해소하고 운영 효율성도 개선될 것이라고 봅니다.", en: "If we sell airport equity to private capital, I believe it will resolve the chronic budget deficit and also improve operational efficiency.", ja: "空港の持分を民間資本に売却すれば慢性的な財政赤字を解消し、運営効率も改善されると思います。", zh: "如果把机场股权出售给民间资本，我认为可以解决长期的财政赤字，也能提高运营效率。", vi: "Nếu chúng ta bán cổ phần sân bay cho tư nhân, tôi tin điều đó sẽ giải quyết thâm hụt ngân sách kinh niên và cũng cải thiện hiệu quả vận hành." },
      { speaker: "시민단체 대표", kr: "효율성이라는 말이 결국 요금 인상과 서비스 축소로 귀결된 해외 사례가 이미 여러 건 보고되지 않았습니까.", en: "Hasn't 'efficiency' already been reported to translate into fee hikes and reduced services in multiple overseas cases?", ja: "効率性という言葉が結局料金引き上げとサービス縮小に帰結した海外事例がすでに複数報告されているじゃないですか。", zh: "“效率”这个说法最终导致收费上涨、服务缩水的海外案例，不是已经有很多报告了吗？", vi: "Chẳng phải 'hiệu quả' đã được báo cáo là dẫn đến tăng phí và giảm dịch vụ trong nhiều trường hợp ở nước ngoài sao?" },
      { speaker: "정치인", kr: "물론 그런 부작용을 우려할 수 있지만, 매각 계약서에 요금 상한선과 서비스 최저 기준을 명시하면 방지할 수 있는 문제라고 생각합니다.", en: "Of course that side effect can be a concern, but I believe it's a problem that can be prevented by specifying fee caps and minimum service standards in the sale contract.", ja: "もちろんそういう副作用は懸念されますが、売却契約書に料金上限と最低サービス基準を明記すれば防げる問題だと思います。", zh: "当然可以担心这种副作用，但我认为只要在出售合同中明确收费上限和最低服务标准，就能防止这个问题。", vi: "Tất nhiên tác dụng phụ đó có thể là mối lo, nhưng tôi tin đó là vấn đề có thể ngăn ngừa bằng cách quy định rõ mức trần phí và tiêu chuẩn dịch vụ tối thiểu trong hợp đồng bán." },
      { speaker: "시민단체 대표", kr: "계약서상의 조항이 아무리 정교해도, 국가 기간 시설을 이윤 추구가 목적인 민간에 넘기는 순간 통제력을 상당 부분 잃게 되는 건 부정할 수 없는 사실입니다.", en: "No matter how elaborate the contract clauses are, it's undeniable that once you hand a critical national infrastructure to profit-seeking private entities, you lose a considerable degree of control.", ja: "契約書上の条項がどんなに精巧でも、国家基幹施設を利潤追求が目的の民間に渡す瞬間、統制力をかなり失うことは否定できない事実です。", zh: "无论合同条款写得多么周密，一旦把国家基础设施交给以盈利为目的的民间机构，就会在很大程度上失去控制力，这是不可否认的事实。", vi: "Dù các điều khoản hợp đồng có tinh vi đến đâu, không thể phủ nhận rằng một khi giao cơ sở hạ tầng quốc gia quan trọng cho các thực thể tư nhân theo đuổi lợi nhuận, anh sẽ mất một mức độ kiểm soát đáng kể." },
      { speaker: "정치인", kr: "통제력 상실이라는 표현은 다소 과장된 측면이 있습니다. 지분 매각이지 전면적인 경영권 이양은 아니니까요.", en: "The expression 'loss of control' seems somewhat exaggerated. It's an equity sale, not a full transfer of management rights.", ja: "統制力喪失という表現はやや誇張された面があります。持分売却であって全面的な経営権移譲ではありませんから。", zh: "“失去控制力”这种说法有点夸张，因为这只是股权出售，不是全面移交经营权。", vi: "Cụm từ 'mất kiểm soát' có vẻ hơi phóng đại. Đây là bán cổ phần, không phải chuyển giao toàn bộ quyền quản lý." },
      { speaker: "시민단체 대표", kr: "지분 구조상 실질적 의사 결정권이 민간 대주주에게 넘어가는 사례를 우리는 이미 여러 산업에서 목격했습니다.", en: "We've already witnessed, in multiple industries, cases where actual decision-making power shifts to private majority shareholders based on the equity structure.", ja: "持分構造上、実質的な意思決定権が民間大株主に渡る事例を私たちはすでに複数の産業で目撃してきました。", zh: "我们已经在多个行业中见过，由于股权结构的原因，实际决策权最终落到民间大股东手中的案例。", vi: "Chúng ta đã chứng kiến, trong nhiều ngành, những trường hợp quyền quyết định thực tế chuyển sang cổ đông đa số tư nhân dựa trên cơ cấu vốn cổ phần." },
      { speaker: "정치인", kr: "재정 적자를 방치하는 것도 결국 국민 세금으로 메워야 하는 문제인데, 그 대안은 무엇이라고 보십니까.", en: "Leaving the budget deficit unaddressed is also ultimately a problem that must be plugged with taxpayer money — what alternative do you propose?", ja: "財政赤字を放置することも結局国民の税金で埋めなければならない問題ですが、その代案は何だとお考えですか。", zh: "放任财政赤字不管，最终也得靠国民纳税来填补，那您认为有什么替代方案？", vi: "Để thâm hụt ngân sách không được giải quyết cũng cuối cùng là vấn đề phải bù đắp bằng tiền thuế của người dân — anh đề xuất giải pháp thay thế nào?" },
      { speaker: "시민단체 대표", kr: "민영화가 아니라 공공 운영 체계 안에서 비핵심 부대사업을 다변화하는 방식으로도 충분히 수익 구조를 개선할 여지가 있다고 봅니다.", en: "Rather than privatization, I believe there's ample room to improve the revenue structure by diversifying non-core ancillary businesses within a public operating framework.", ja: "民営化ではなく、公共運営体系の中で非中核付帯事業を多角化する方式でも十分に収益構造を改善する余地があると思います。", zh: "我认为不需要私有化，只需在公共运营体系内多元化非核心附属业务，就有足够空间改善盈利结构。", vi: "Thay vì tư nhân hóa, tôi tin có nhiều dư địa để cải thiện cơ cấu doanh thu bằng cách đa dạng hóa các mảng kinh doanh phụ trợ không cốt lõi trong khuôn khổ vận hành công." },
      { speaker: "정치인", kr: "그 방식이 단기간에 재정 적자를 상쇄할 만큼 충분한 규모를 만들어 낼 수 있을지는 여전히 의문입니다.", en: "Whether that approach can generate a scale sufficient to offset the deficit in the short term is still a question in my mind.", ja: "その方式が短期間に財政赤字を相殺できるほど十分な規模を作り出せるかは依然として疑問です。", zh: "这种方式能否在短期内产生足以抵消财政赤字的规模，我仍然存疑。", vi: "Liệu cách tiếp cận đó có thể tạo ra quy mô đủ để bù đắp thâm hụt trong ngắn hạn vẫn còn là một câu hỏi trong đầu tôi." },
    ],
  },
  {
    id: "airport-c2y-language",
    situationKey: "airport",
    level: "C2",
    title: { en: "Literary reflection on airport announcements", ja: "空港アナウンスについての文学的考察", zh: "对机场广播的文学性思考", vi: "Suy ngẫm văn học về các thông báo tại sân bay" },
    lines: [
      { speaker: "작가", kr: "공항 안내 방송의 언어를 유심히 들어 보면, 그 안에 담긴 정중함이 오히려 어떤 소외감을 자아낸다는 생각이 들 때가 있습니다.", en: "When I listen carefully to the language of airport announcements, there are times I feel that the politeness embedded in it actually produces a kind of alienation.", ja: "空港アナウンスの言葉を注意深く聞いてみると、そこに込められた丁寧さがかえって何か疎外感を生み出していると感じることがあります。", zh: "仔细聆听机场广播的措辞时，我有时会觉得其中蕴含的礼貌反而产生了一种疏离感。", vi: "Khi tôi lắng nghe kỹ ngôn ngữ của các thông báo tại sân bay, có những lúc tôi cảm thấy sự lịch sự được gắn trong đó thực ra tạo ra một kiểu xa lạ hóa." },
      { speaker: "청자", kr: "흥미로운 관점이네요. 저는 오히려 그 정형화된 표현들이 안정감을 준다고 느꼈거든요.", en: "That's an interesting perspective. I actually felt those formulaic expressions gave a sense of stability.", ja: "興味深い観点ですね。私はむしろその定型化された表現が安定感を与えると感じていました。", zh: "这个观点很有意思。我倒是觉得那些程式化的表达反而给人一种安定感。", vi: "Đó là một góc nhìn thú vị. Tôi thực ra cảm thấy những cách diễn đạt khuôn mẫu đó mang lại cảm giác ổn định." },
      { speaker: "작가", kr: "안정감을 주는 동시에, 승객 개개인의 사연은 지워지고 모두가 동일한 절차 속 익명의 존재로 환원되는 느낌도 있지 않나요.", en: "While giving that stability, isn't there also a sense that each passenger's individual story gets erased, and everyone is reduced to an anonymous presence within the same procedure?", ja: "安定感を与えると同時に、乗客一人ひとりの物語は消され、みんなが同じ手続きの中で匿名の存在に還元される感じもあるのではないでしょうか。", zh: "在带来安定感的同时，是不是也让人觉得每位乘客各自的故事被抹去了，所有人都被简化成同一套程序中的匿名存在？", vi: "Trong khi mang lại sự ổn định đó, chẳng phải cũng có cảm giác rằng câu chuyện cá nhân của từng hành khách bị xóa bỏ, và mọi người bị giản lược thành một sự hiện diện vô danh trong cùng một quy trình sao?" },
      { speaker: "청자", kr: "그렇게 보니 '탑승을 시작하겠습니다'라는 문장 하나에도 어떤 관료적 리듬이 있는 것 같네요.", en: "Looking at it that way, there does seem to be a kind of bureaucratic rhythm even in a single sentence like 'We will now begin boarding.'", ja: "そう考えると「搭乗を開始します」という一文にも何か官僚的なリズムがある気がしますね。", zh: "这么一说，感觉连“现在开始登机”这一句话里都带着某种官僚式的节奏呢。", vi: "Nhìn theo cách đó, dường như có một loại nhịp điệu quan liêu ngay cả trong một câu đơn giản như 'Chúng tôi sẽ bắt đầu cho hành khách lên máy bay.'" },
      { speaker: "작가", kr: "저는 그 리듬을 소설에서 종종 인용해요. 개인의 서사와 제도의 언어가 충돌하는 지점을 보여주고 싶어서요.", en: "I often quote that rhythm in my novels. I want to show the point where an individual's narrative collides with institutional language.", ja: "私はそのリズムを小説でよく引用します。個人の物語と制度の言葉が衝突する地点を見せたいからです。", zh: "我经常在小说里引用这种节奏，因为我想呈现个人叙事与体制语言相碰撞的那个点。", vi: "Tôi thường trích dẫn nhịp điệu đó trong tiểu thuyết của mình. Tôi muốn cho thấy điểm mà câu chuyện cá nhân va chạm với ngôn ngữ thể chế." },
      { speaker: "청자", kr: "그런데 한편으로는 그 몰개성적인 언어가 위기 상황에서는 오히려 필수적이지 않을까 싶기도 해요. 감정이 개입되면 안 되는 순간들이 있으니까요.", en: "On the other hand though, I wonder if that impersonal language is actually essential in crisis situations. There are moments when emotion shouldn't factor in.", ja: "でも一方で、その没個性的な言葉が危機状況ではむしろ必須なのではとも思います。感情が介入してはいけない瞬間もありますから。", zh: "不过另一方面，我也在想，那种缺乏个性的语言在紧急状况下会不会反而是必要的呢？毕竟有些时刻不能掺入情感。", vi: "Nhưng mặt khác, tôi tự hỏi liệu ngôn ngữ phi cá nhân đó có thực sự cần thiết trong các tình huống khủng hoảng hay không. Có những khoảnh khắc mà cảm xúc không nên xen vào." },
      { speaker: "작가", kr: "맞는 말씀이에요. 그래서 저는 이 언어를 비판하기보다는, 그 이중성 자체를 글의 소재로 삼고 싶은 거예요.", en: "That's a fair point. That's why, rather than criticizing this language, I want to make that very duality the subject matter of my writing.", ja: "その通りだと思います。だから私はこの言葉を批判するよりも、その二重性自体を作品の題材にしたいんです。", zh: "您说得对。所以比起批判这种语言，我更想把这种双重性本身当作写作的素材。", vi: "Đó là một điểm hợp lý. Đó là lý do, thay vì chỉ trích ngôn ngữ này, tôi muốn biến chính sự lưỡng phân đó thành đề tài trong tác phẩm của mình." },
      { speaker: "청자", kr: "다음 소설에서는 공항을 배경으로 한 이야기를 다뤄 보실 생각이 있으신가요?", en: "Do you have plans to write a story set at an airport for your next novel?", ja: "次の小説では空港を舞台にした物語を扱われるご予定はありますか？", zh: "您下一部小说有没有打算写一个以机场为背景的故事？", vi: "Chị có kế hoạch viết một câu chuyện lấy bối cảnh sân bay cho tiểu thuyết tiếp theo không?" },
      { speaker: "작가", kr: "네, 사실 지금 구상 중이에요. 탑승구 앞에서 우연히 마주친 인물들의 서로 다른 시간대를 교차시켜 보려고요.", en: "Yes, actually I'm working on the idea right now. I want to interweave the different timelines of characters who happen to cross paths in front of a boarding gate.", ja: "はい、実は今構想中です。搭乗口の前で偶然出会った人物たちの異なる時間軸を交差させてみようと思っています。", zh: "有的，其实我正在构思。我想把在登机口偶然相遇的几个人物各自不同的时间线交织在一起。", vi: "Có, thực ra tôi đang phát triển ý tưởng đó ngay bây giờ. Tôi muốn đan xen các dòng thời gian khác nhau của những nhân vật tình cờ gặp nhau trước cửa lên máy bay." },
    ],
  },
  {
    id: "airport-c2y-drones",
    situationKey: "airport",
    level: "C2",
    title: { en: "Debate over drone incursions grounding flights", ja: "ドローン侵入による欠航をめぐる議論", zh: "关于无人机入侵导致停飞的争论", vi: "Tranh luận về việc drone xâm nhập khiến chuyến bay bị hoãn" },
    lines: [
      { speaker: "보도자", kr: "어젯밤 인근 상공에서 포착된 드론 때문에 세 시간 넘게 활주로가 폐쇄됐습니다. 이런 사태가 반복되는 이유를 짚어 보겠습니다.", en: "Last night the runway was closed for over three hours because of a drone spotted in the nearby airspace. We'll examine why this keeps recurring.", ja: "昨夜、近隣上空で捕捉されたドローンのため三時間以上滑走路が閉鎖されました。このような事態が繰り返される理由を見ていきます。", zh: "昨晚由于附近上空发现无人机，跑道关闭了三个多小时。我们来探讨一下这类事件反复发生的原因。", vi: "Đêm qua đường băng đã bị đóng hơn ba tiếng vì phát hiện một chiếc drone trong không phận gần đó. Chúng ta sẽ xem xét tại sao chuyện này cứ tái diễn." },
      { speaker: "보안 전문가", kr: "현재 대응 체계가 탐지 위주로 설계되어 있고, 실제 무력화 수단은 법적 근거가 미비해서 발이 묶여 있는 상황입니다.", en: "The current response system is designed mainly around detection, and actual neutralization measures are held back due to insufficient legal grounds.", ja: "現在の対応体系は探知中心に設計されており、実際の無力化手段は法的根拠が不十分で足止めされている状況です。", zh: "目前的应对体系主要以探测为核心设计，实际的反制手段则因法律依据不足而受到限制。", vi: "Hệ thống ứng phó hiện tại chủ yếu được thiết kế xoay quanh việc phát hiện, còn các biện pháp vô hiệu hóa thực tế bị hạn chế do thiếu cơ sở pháp lý đầy đủ." },
      { speaker: "보도자", kr: "무력화라고 하면 격추 같은 물리적 조치를 말씀하시는 건가요? 그건 오히려 더 위험하지 않을까요.", en: "By neutralization, do you mean physical measures like shooting it down? Wouldn't that actually be more dangerous?", ja: "無力化というと撃墜のような物理的措置をおっしゃっているのですか？それはむしろもっと危険ではないでしょうか。", zh: "反制的意思是指击落这类物理手段吗？那样做会不会反而更危险？", vi: "Vô hiệu hóa ở đây có nghĩa là các biện pháp vật lý như bắn hạ không? Chẳng phải điều đó thực ra nguy hiểm hơn sao?" },
      { speaker: "보안 전문가", kr: "물리적 격추보다는 전파 교란이나 신호 탈취 방식이 일반적입니다. 다만 이 역시 민간 통신망에 미칠 영향 때문에 규제가 엄격한 편이죠.", en: "It's usually signal jamming or signal hijacking rather than physical shootdown. But that too is fairly strictly regulated because of the potential impact on civilian communication networks.", ja: "物理的撃墜より電波妨害や信号奪取方式が一般的です。ただこれも民間通信網への影響のため規制が厳しい方です。", zh: "通常不是物理击落，而是使用信号干扰或信号劫持的方式。不过这种方式因为可能影响民用通信网络，监管也相当严格。", vi: "Thường là gây nhiễu tín hiệu hoặc chiếm quyền tín hiệu chứ không phải bắn hạ vật lý. Nhưng điều đó cũng bị quản lý khá chặt chẽ vì tác động tiềm tàng đến mạng lưới thông tin liên lạc dân sự." },
      { speaker: "보도자", kr: "그렇다면 근본적으로는 드론 소유자를 식별하고 처벌하는 사후 대응에 그칠 수밖에 없다는 말씀이신가요.", en: "So are you saying that fundamentally we're left with only after-the-fact responses like identifying and punishing the drone owner?", ja: "それでは根本的にはドローンの所有者を特定して処罰する事後対応にとどまるしかないということでしょうか。", zh: "那么从根本上说，只能停留在识别并处罚无人机主人这种事后应对措施吗？", vi: "Vậy anh đang nói rằng về cơ bản chúng ta chỉ còn lại các phản ứng sau sự việc như xác định và trừng phạt chủ sở hữu drone thôi sao?" },
      { speaker: "보안 전문가", kr: "사후 대응만으로는 재발을 막을 수 없다는 게 문제죠. 예방적 차원에서 공항 반경 내 드론 등록제와 실시간 위치 공유 의무화가 필요하다고 봅니다.", en: "The problem is that after-the-fact response alone can't prevent recurrence. From a preventive standpoint, I think we need mandatory drone registration and real-time location sharing within the airport's radius.", ja: "事後対応だけでは再発を防げないのが問題です。予防的な次元で空港半径内のドローン登録制とリアルタイム位置共有の義務化が必要だと思います。", zh: "问题在于仅靠事后应对无法防止再次发生。从预防角度来看，我认为有必要在机场半径范围内实行无人机登记制，并强制要求实时位置共享。", vi: "Vấn đề là chỉ phản ứng sau sự việc không thể ngăn tái diễn. Từ góc độ phòng ngừa, tôi nghĩ chúng ta cần đăng ký bắt buộc drone và chia sẻ vị trí thời gian thực trong bán kính sân bay." },
      { speaker: "보도자", kr: "그런 제도가 실제로 악의적인 조종자에게는 별 구속력이 없지 않을까요. 애초에 신고 안 하고 몰래 띄우면 그만이니까요.", en: "Wouldn't such a system have little binding power over a genuinely malicious operator anyway? They could just fly it secretly without registering in the first place.", ja: "そうした制度が実際に悪意ある操縦者にはあまり拘束力がないのではないでしょうか。そもそも申告せずこっそり飛ばせばそれまでですから。", zh: "这种制度对真正心怀恶意的操作者恐怕没什么约束力吧？毕竟他们一开始就可以不申报、偷偷放飞。", vi: "Chẳng phải một hệ thống như vậy sẽ có ít sức ràng buộc đối với một người điều khiển thực sự có ác ý đằng nào? Họ có thể chỉ bay lén mà không đăng ký ngay từ đầu." },
      { speaker: "보안 전문가", kr: "맞는 말씀입니다. 그래서 등록제와 병행해서 탐지 센서망을 촘촘히 구축하는 이중 전략이 필요하다는 겁니다.", en: "That's correct. That's exactly why I'm saying we need a dual strategy of building a dense detection sensor network alongside the registration system.", ja: "その通りです。だから登録制と並行して探知センサー網を緻密に構築する二重戦略が必要だということです。", zh: "您说得对。所以我才说需要在登记制的同时，密集建设探测传感器网络，采取双重战略。", vi: "Đúng vậy. Đó chính xác là lý do tại sao tôi nói chúng ta cần một chiến lược kép là xây dựng mạng lưới cảm biến phát hiện dày đặc song song với hệ thống đăng ký." },
      { speaker: "보도자", kr: "결국 기술과 제도가 동시에 따라가지 못하면 이런 지연 사태는 계속될 수밖에 없겠군요.", en: "So in the end, unless technology and institutions keep pace together, these kinds of delay incidents are bound to continue.", ja: "結局、技術と制度が同時に追いつかなければ、こういう遅延事態は続くしかないでしょうね。", zh: "看来最终如果技术和制度不能同步跟进，这类延误事件恐怕还会持续发生。", vi: "Vậy cuối cùng, trừ khi công nghệ và thể chế cùng tiến bước, những sự cố trì hoãn kiểu này chắc chắn sẽ tiếp diễn." },
    ],
  },
];

export const AIRPORT_C_QUIZZES: Record<string, DialogueQuiz> = {
  "airport-c1y-budget": {
    q: "What does Jaehun ultimately concede to Sujin?",
    opts: [
      "That budget airlines are unsafe",
      "That transparency around hidden fees needs stricter regulation",
      "That he will stop using budget airlines",
      "That seat pitch reductions are illegal",
    ],
    ans: 1,
  },
  "airport-c1y-pr": {
    q: "What corrective measure does the executive commit to regarding overbooking itself?",
    opts: [
      "Immediately abolishing overbooking",
      "Improving algorithm accuracy to reduce how often it happens",
      "Doubling the compensation cap only",
      "Refusing to discuss the topic further",
    ],
    ans: 1,
  },
  "airport-c1y-loyalty": {
    q: "What strategy does Minho say he will adopt after the devaluation?",
    opts: [
      "Stop flying entirely",
      "Switch to a rival airline's program",
      "Redeem miles as soon as they accumulate instead of saving for upgrades",
      "File a formal complaint with regulators",
    ],
    ans: 2,
  },
  "airport-c1y-strike": {
    q: "Why did the union choose a slowdown instead of a full strike?",
    opts: [
      "They lack legal grounds for a strike",
      "Management threatened mass layoffs",
      "They can't fully disregard public opinion",
      "The slowdown was mandated by the government",
    ],
    ans: 2,
  },
  "airport-c1y-expansion": {
    q: "What is the resident's main objection to the compensation package?",
    opts: [
      "The compensation amount is too high",
      "It doesn't address that their home and community can't simply be reduced to money",
      "It only applies to new residents",
      "It was never formally offered",
    ],
    ans: 1,
  },
  "airport-c1y-carbon": {
    q: "What does Jiwoo propose as the fundamental fix for aviation's environmental cost?",
    opts: [
      "Banning short-haul flights entirely",
      "Relying solely on individual carbon offset purchases",
      "Airlines adopting sustainable fuel sooner and governments introducing policy tools like carbon taxes",
      "Switching all flights to trains",
    ],
    ans: 2,
  },
  "airport-c1y-reentry": {
    q: "Where does the immigration officer direct the returnee for tax-related questions?",
    opts: [
      "The airport information desk",
      "The district office",
      "The National Tax Service consultation window",
      "The airline's customer service",
    ],
    ans: 2,
  },
  "airport-c1y-securitytheater": {
    q: "What alternative approach does Jungwoo personally favor over uniform screening?",
    opts: [
      "Eliminating all security screening",
      "Strengthening data-driven risk assessment",
      "Random behavioral analysis only",
      "Outsourcing security to private firms",
    ],
    ans: 1,
  },
  "airport-c1y-liminal": {
    q: "What term does traveler A mention that anthropologists use for spaces like airports?",
    opts: [
      "Non-place",
      "Liminal space",
      "Transit zone",
      "Threshold territory",
    ],
    ans: 1,
  },
  "airport-c2y-atc": {
    q: "What is the union representative's core demand in the negotiation?",
    opts: [
      "Immediate wage doubling",
      "Staffing increases without indefinite delay, backed by a written deadline",
      "Reducing controller training time",
      "Ending overtime pay entirely",
    ],
    ans: 1,
  },
  "airport-c2y-hub": {
    q: "What does the scholar argue would be lost if the airport fails to capture transfer demand?",
    opts: [
      "Nothing significant",
      "Jobs and tourism revenue tied to hub status",
      "Only cargo revenue",
      "The airport's environmental rating",
    ],
    ans: 1,
  },
  "airport-c2y-biometric": {
    q: "What does the expert say consumers should be guaranteed if they opt out of biometric boarding?",
    opts: [
      "A discounted ticket",
      "An alternative procedure with the same waiting time",
      "Priority boarding as compensation",
      "No guarantee is proposed",
    ],
    ans: 1,
  },
  "airport-c2y-slots": {
    q: "What compromise approach does the airline representative ultimately suggest?",
    opts: [
      "Full immediate auction of all slots",
      "Keeping the current system unchanged forever",
      "A gradual pilot auction on some slots to gather data before wider reform",
      "Abolishing slot allocation altogether",
    ],
    ans: 2,
  },
  "airport-c2y-outsourcing": {
    q: "What does the labor researcher propose as a reform to the outsourcing bidding process?",
    opts: [
      "Banning private outsourcing outright",
      "Weighting evaluation criteria toward skill and tenure instead of lowest bid",
      "Increasing the number of competing contractors",
      "Removing all government oversight",
    ],
    ans: 1,
  },
  "airport-c2y-noise": {
    q: "What compromise does the panelist propose regarding night flight curfews?",
    opts: [
      "Permanently keeping the full curfew",
      "Removing the curfew entirely with no conditions",
      "A conditional, limited relaxation tied to adopting noise-reducing aircraft",
      "Relocating the airport instead",
    ],
    ans: 2,
  },
  "airport-c2y-privatization": {
    q: "What alternative to privatization does the civic group representative propose?",
    opts: [
      "Raising landing fees sharply",
      "Diversifying non-core ancillary businesses within public operation",
      "Selling the airport to a foreign government",
      "Eliminating all airport services",
    ],
    ans: 1,
  },
  "airport-c2y-language": {
    q: "What tension does the writer say she wants to explore in her fiction about airport announcements?",
    opts: [
      "The high cost of airport tickets",
      "The collision between individual narrative and institutional language",
      "The accuracy of translated announcements",
      "The history of aviation regulation",
    ],
    ans: 1,
  },
  "airport-c2y-drones": {
    q: "What dual strategy does the security expert recommend against drone incursions?",
    opts: [
      "Only physical shootdown of drones",
      "Only after-the-fact punishment of owners",
      "A drone registration system combined with a dense detection sensor network",
      "Closing the airport permanently at night",
    ],
    ans: 2,
  },
};
