import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Airport situation expansion (2026-08): raises A1-B2 coverage to 20 dialogues per level.
export const AIRPORT_EXPANSION: Dialogue[] = [
  {
    id: "airport-a1x-cart",
    situationKey: "airport",
    level: "A1",
    title: { en: "Getting a luggage cart", ja: "手荷物カートを借りる", zh: "取行李推车" },
    lines: [
      { speaker: "여행객", kr: "카트는 어디에 있어요?", en: "Where are the luggage carts?", ja: "カートはどこにありますか？", zh: "推车在哪里？" },
      { speaker: "직원", kr: "저기 기둥 옆에 있어요.", en: "They're over there next to the pillar.", ja: "あそこの柱の横にあります。", zh: "在那边柱子旁边。" },
      { speaker: "여행객", kr: "무료예요?", en: "Are they free?", ja: "無料ですか？", zh: "免费吗？" },
      { speaker: "직원", kr: "네, 무료예요.", en: "Yes, they're free.", ja: "はい、無料です。", zh: "是的，免费。" },
    ],
  },
  {
    id: "airport-a1x-scale",
    situationKey: "airport",
    level: "A1",
    title: { en: "Where to weigh bags", ja: "荷物の重さを量る場所", zh: "在哪里称行李" },
    lines: [
      { speaker: "여행객", kr: "가방을 어디서 달아요?", en: "Where do I weigh my bag?", ja: "かばんはどこで量りますか？", zh: "行李在哪里称重？" },
      { speaker: "직원", kr: "저 저울 위에 올려 주세요.", en: "Please put it on that scale.", ja: "あの秤の上に乗せてください。", zh: "请放在那台秤上。" },
      { speaker: "여행객", kr: "네, 알겠어요.", en: "Okay, got it.", ja: "はい、分かりました。", zh: "好的，明白了。" },
      { speaker: "직원", kr: "십오 킬로예요. 괜찮아요.", en: "It's 15 kilos. That's fine.", ja: "十五キロです。大丈夫です。", zh: "十五公斤，没问题。" },
    ],
  },
  {
    id: "airport-a1x-reprint",
    situationKey: "airport",
    level: "A1",
    title: { en: "Reprinting a boarding pass", ja: "搭乗券を再発行する", zh: "重新打印登机牌" },
    lines: [
      { speaker: "여행객", kr: "탑승권을 다시 뽑고 싶어요.", en: "I'd like to print my boarding pass again.", ja: "搭乗券をもう一度発行してほしいです。", zh: "我想重新打印一下登机牌。" },
      { speaker: "직원", kr: "여권 좀 보여 주세요.", en: "Please show me your passport.", ja: "パスポートを見せてください。", zh: "请出示您的护照。" },
      { speaker: "여행객", kr: "여기 있어요.", en: "Here it is.", ja: "こちらです。", zh: "在这里。" },
      { speaker: "직원", kr: "네, 새로 뽑아 드릴게요.", en: "Okay, I'll print you a new one.", ja: "はい、新しく発行いたします。", zh: "好的，我给您重新打印一张。" },
    ],
  },
  {
    id: "airport-a1x-exchange",
    situationKey: "airport",
    level: "A1",
    title: { en: "Exchanging money", ja: "両替をする", zh: "兑换货币" },
    lines: [
      { speaker: "여행객", kr: "환전소가 어디예요?", en: "Where's the currency exchange?", ja: "両替所はどこですか？", zh: "换汇处在哪里？" },
      { speaker: "직원", kr: "이 층에 있어요.", en: "It's on this floor.", ja: "この階にあります。", zh: "就在这一层。" },
      { speaker: "여행객", kr: "고마워요.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
      { speaker: "직원", kr: "네, 좋은 여행 되세요.", en: "You're welcome, have a good trip.", ja: "どういたしまして、良い旅を。", zh: "不客气，祝您旅途愉快。" },
    ],
  },
  {
    id: "airport-a1x-wheelchair",
    situationKey: "airport",
    level: "A1",
    title: { en: "Requesting a wheelchair", ja: "車椅子をお願いする", zh: "申请轮椅" },
    lines: [
      { speaker: "여행객", kr: "휠체어가 필요해요.", en: "I need a wheelchair.", ja: "車椅子が必要です。", zh: "我需要一辆轮椅。" },
      { speaker: "직원", kr: "네, 여기서 기다려 주세요.", en: "Okay, please wait here.", ja: "はい、ここでお待ちください。", zh: "好的，请在这里等一下。" },
      { speaker: "여행객", kr: "얼마나 걸려요?", en: "How long will it take?", ja: "どれくらいかかりますか？", zh: "要多久？" },
      { speaker: "직원", kr: "오 분쯤 걸려요.", en: "About 5 minutes.", ja: "五分くらいかかります。", zh: "大约五分钟。" },
    ],
  },
  {
    id: "airport-a1x-pet",
    situationKey: "airport",
    level: "A1",
    title: { en: "Traveling with a pet", ja: "ペットと一緒に搭乗する", zh: "带宠物一起出行" },
    lines: [
      { speaker: "여행객", kr: "강아지랑 같이 타요.", en: "I'm traveling with my dog.", ja: "犬と一緒に乗ります。", zh: "我和我的狗一起坐飞机。" },
      { speaker: "직원", kr: "이동장이 있어요?", en: "Do you have a carrier?", ja: "キャリーはお持ちですか？", zh: "有宠物笼吗？" },
      { speaker: "여행객", kr: "네, 여기요.", en: "Yes, here it is.", ja: "はい、こちらです。", zh: "有的，在这里。" },
      { speaker: "직원", kr: "좋아요. 크기가 맞아요.", en: "Good. The size is fine.", ja: "いいですね。サイズも大丈夫です。", zh: "很好，大小合适。" },
    ],
  },
  {
    id: "airport-a1x-fragile",
    situationKey: "airport",
    level: "A1",
    title: { en: "Fragile sticker on a bag", ja: "かばんに割れ物ステッカーを貼る", zh: "在行李上贴易碎标签" },
    lines: [
      { speaker: "여행객", kr: "이 가방은 깨지기 쉬워요.", en: "This bag has fragile items.", ja: "このかばんは壊れやすいものが入っています。", zh: "这个包里装的是易碎物品。" },
      { speaker: "직원", kr: "스티커를 붙여 드릴게요.", en: "I'll put a fragile sticker on it.", ja: "割れ物ステッカーを貼っておきます。", zh: "我给您贴上易碎标签。" },
      { speaker: "여행객", kr: "감사해요.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
      { speaker: "직원", kr: "조심히 다룰게요.", en: "We'll handle it carefully.", ja: "丁寧に扱います。", zh: "我们会小心处理的。" },
    ],
  },
  {
    id: "airport-a1x-lounge",
    situationKey: "airport",
    level: "A1",
    title: { en: "Asking about lounge access", ja: "ラウンジの利用について尋ねる", zh: "询问贵宾室的使用方法" },
    lines: [
      { speaker: "여행객", kr: "라운지는 어디예요?", en: "Where's the lounge?", ja: "ラウンジはどこですか？", zh: "贵宾室在哪里？" },
      { speaker: "직원", kr: "삼 층에 있어요.", en: "It's on the third floor.", ja: "三階にあります。", zh: "在三楼。" },
      { speaker: "여행객", kr: "표가 필요해요?", en: "Do I need a ticket?", ja: "チケットが必要ですか？", zh: "需要票吗？" },
      { speaker: "직원", kr: "네, 탑승권을 보여 주세요.", en: "Yes, please show your boarding pass.", ja: "はい、搭乗券を見せてください。", zh: "需要，请出示登机牌。" },
    ],
  },
  {
    id: "airport-a1x-meal",
    situationKey: "airport",
    level: "A1",
    title: { en: "Choosing a meal on board", ja: "機内食を選ぶ", zh: "选择机上餐食" },
    lines: [
      { speaker: "승무원", kr: "식사는 닭고기와 생선이 있어요.", en: "For the meal, we have chicken or fish.", ja: "お食事は鶏肉と魚がございます。", zh: "餐食有鸡肉和鱼肉可选。" },
      { speaker: "승객", kr: "닭고기 주세요.", en: "I'll have the chicken, please.", ja: "鶏肉をお願いします。", zh: "请给我鸡肉。" },
      { speaker: "승무원", kr: "음료는 뭐 드릴까요?", en: "What would you like to drink?", ja: "お飲み物は何になさいますか？", zh: "饮料要点什么？" },
      { speaker: "승객", kr: "물 주세요.", en: "Water, please.", ja: "水をお願いします。", zh: "请给我水。" },
    ],
  },
  {
    id: "airport-a1x-lostpass",
    situationKey: "airport",
    level: "A1",
    title: { en: "Lost boarding pass", ja: "搭乗券をなくした", zh: "登机牌丢了" },
    lines: [
      { speaker: "여행객", kr: "탑승권을 잃어버렸어요.", en: "I lost my boarding pass.", ja: "搭乗券をなくしてしまいました。", zh: "我的登机牌弄丢了。" },
      { speaker: "직원", kr: "여권 있어요?", en: "Do you have your passport?", ja: "パスポートはお持ちですか？", zh: "有护照吗？" },
      { speaker: "여행객", kr: "네, 여기요.", en: "Yes, here it is.", ja: "はい、こちらです。", zh: "有，在这里。" },
      { speaker: "직원", kr: "다시 만들어 드릴게요.", en: "I'll make you a new one.", ja: "新しく作ります。", zh: "我给您重新办一张。" },
    ],
  },
  {
    id: "airport-a1x-arrival",
    situationKey: "airport",
    level: "A1",
    title: { en: "Finding the pickup point", ja: "送迎場所を探す", zh: "寻找接机点" },
    lines: [
      { speaker: "여행객", kr: "픽업 장소가 어디예요?", en: "Where's the pickup point?", ja: "送迎場所はどこですか？", zh: "接机地点在哪里？" },
      { speaker: "직원", kr: "일 번 출구예요.", en: "It's exit number 1.", ja: "一番出口です。", zh: "在一号出口。" },
      { speaker: "여행객", kr: "여기서 멀어요?", en: "Is it far from here?", ja: "ここから遠いですか？", zh: "离这儿远吗？" },
      { speaker: "직원", kr: "아니요, 가까워요.", en: "No, it's close.", ja: "いいえ、近いです。", zh: "不远，很近。" },
    ],
  },
  {
    id: "airport-a1x-taxfree",
    situationKey: "airport",
    level: "A1",
    title: { en: "Finding the tax refund counter", ja: "免税還付カウンターを探す", zh: "寻找退税柜台" },
    lines: [
      { speaker: "여행객", kr: "환급 창구가 어디예요?", en: "Where's the tax refund counter?", ja: "還付カウンターはどこですか？", zh: "退税柜台在哪里？" },
      { speaker: "직원", kr: "저쪽 이십 번 창구예요.", en: "It's counter 20 over there.", ja: "あちらの二十番窓口です。", zh: "在那边的二十号窗口。" },
      { speaker: "여행객", kr: "줄이 길어요?", en: "Is the line long?", ja: "列は長いですか？", zh: "排队的人多吗？" },
      { speaker: "직원", kr: "지금은 짧아요.", en: "It's short right now.", ja: "今は短いです。", zh: "现在不多。" },
    ],
  },
  {
    id: "airport-a1x-charge",
    situationKey: "airport",
    level: "A1",
    title: { en: "Finding a phone charger", ja: "携帯の充電器を探す", zh: "寻找手机充电器" },
    lines: [
      { speaker: "여행객", kr: "충전기 있어요?", en: "Do you have a phone charger?", ja: "充電器はありますか？", zh: "有手机充电器吗？" },
      { speaker: "직원", kr: "저기 의자 옆에 있어요.", en: "There's one next to the chairs over there.", ja: "あそこの椅子の横にあります。", zh: "在那边椅子旁边有一个。" },
      { speaker: "여행객", kr: "고마워요.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
      { speaker: "직원", kr: "네, 편히 쓰세요.", en: "You're welcome, feel free to use it.", ja: "どういたしまして、ご自由にお使いください。", zh: "不客气，请随意使用。" },
    ],
  },
  {
    id: "airport-a1x-elevator",
    situationKey: "airport",
    level: "A1",
    title: { en: "Finding the elevator", ja: "エレベーターを探す", zh: "寻找电梯" },
    lines: [
      { speaker: "여행객", kr: "엘리베이터가 어디예요?", en: "Where's the elevator?", ja: "エレベーターはどこですか？", zh: "电梯在哪里？" },
      { speaker: "직원", kr: "왼쪽으로 가세요.", en: "Go to the left.", ja: "左に行ってください。", zh: "往左走。" },
      { speaker: "여행객", kr: "네, 알겠어요.", en: "Okay, got it.", ja: "はい、分かりました。", zh: "好的，明白了。" },
      { speaker: "직원", kr: "금방 보여요.", en: "You'll see it right away.", ja: "すぐ見えます。", zh: "很快就能看到。" },
    ],
  },
  {
    id: "airport-a1x-luggage-tag",
    situationKey: "airport",
    level: "A1",
    title: { en: "Getting a luggage tag", ja: "荷物タグをもらう", zh: "领取行李牌" },
    lines: [
      { speaker: "여행객", kr: "짐표를 받고 싶어요.", en: "I'd like a luggage tag.", ja: "荷物タグをいただきたいです。", zh: "我想要一个行李牌。" },
      { speaker: "직원", kr: "가방 이름을 써 주세요.", en: "Please write your name on the bag.", ja: "かばんに名前を書いてください。", zh: "请在行李上写上您的名字。" },
      { speaker: "여행객", kr: "여기 썼어요.", en: "I wrote it here.", ja: "ここに書きました。", zh: "我写在这里了。" },
      { speaker: "직원", kr: "네, 태그 붙였어요.", en: "Okay, the tag is attached.", ja: "はい、タグを付けました。", zh: "好了，牌子已经系上了。" },
    ],
  },
  {
    id: "airport-a2x-scale-heavy",
    situationKey: "airport",
    level: "A2",
    title: { en: "Bag is over the weight limit", ja: "荷物が重量制限を超えている", zh: "行李超重了" },
    lines: [
      { speaker: "직원", kr: "가방이 이십삼 킬로가 넘었어요.", en: "Your bag is over 23 kilos.", ja: "かばんが二十三キロを超えています。", zh: "您的行李超过了二十三公斤。" },
      { speaker: "여행객", kr: "얼마나 넘었어요?", en: "How much over is it?", ja: "どれくらい超えていますか？", zh: "超了多少？" },
      { speaker: "직원", kr: "삼 킬로 넘었어요.", en: "It's 3 kilos over.", ja: "三キロ超えています。", zh: "超了三公斤。" },
      { speaker: "여행객", kr: "가방에서 좀 뺄게요.", en: "I'll take some things out of the bag.", ja: "かばんから少し出します。", zh: "我从包里拿出一些东西。" },
      { speaker: "직원", kr: "네, 여기서 빼셔도 돼요.", en: "Yes, you can take them out here.", ja: "はい、ここで出していただいて大丈夫です。", zh: "可以，您可以在这里拿出来。" },
    ],
  },
  {
    id: "airport-a2x-lounge-buy",
    situationKey: "airport",
    level: "A2",
    title: { en: "Buying a day pass for the lounge", ja: "ラウンジの一日券を購入する", zh: "购买贵宾室一日通行证" },
    lines: [
      { speaker: "여행객", kr: "라운지 일일권을 사고 싶어요.", en: "I'd like to buy a day pass for the lounge.", ja: "ラウンジの一日券を買いたいです。", zh: "我想买贵宾室的一日票。" },
      { speaker: "직원", kr: "카드로 결제할 거예요?", en: "Will you pay by card?", ja: "カードでお支払いになりますか？", zh: "用卡支付吗？" },
      { speaker: "여행객", kr: "네, 카드로 할게요.", en: "Yes, I'll pay by card.", ja: "はい、カードで払います。", zh: "对，用卡付。" },
      { speaker: "직원", kr: "가격은 삼만 원이에요.", en: "The price is 30,000 won.", ja: "価格は三万ウォンです。", zh: "价格是30000韩元。" },
      { speaker: "여행객", kr: "알겠어요, 결제할게요.", en: "Okay, I'll pay.", ja: "分かりました、支払います。", zh: "好的，我付款。" },
    ],
  },
  {
    id: "airport-a2x-minor",
    situationKey: "airport",
    level: "A2",
    title: { en: "Unaccompanied minor service", ja: "非同伴児童サービス", zh: "无成人陪伴儿童服务" },
    lines: [
      { speaker: "직원", kr: "아이 혼자 타는 거 맞죠?", en: "Your child is flying alone, right?", ja: "お子さんは一人で搭乗されるんですよね？", zh: "孩子是一个人乘机吧？" },
      { speaker: "학부모", kr: "네, 맞아요.", en: "Yes, that's right.", ja: "はい、そうです。", zh: "对，是的。" },
      { speaker: "직원", kr: "서류를 작성해 주세요.", en: "Please fill out this form.", ja: "書類を記入してください。", zh: "请填写一下这份表格。" },
      { speaker: "학부모", kr: "누가 아이를 데려다줘요?", en: "Who will take my child there?", ja: "誰が子供を連れて行ってくれますか？", zh: "谁会带孩子过去呢？" },
      { speaker: "직원", kr: "저희 직원이 게이트까지 데려다줘요.", en: "Our staff will take her to the gate.", ja: "私どものスタッフがゲートまでお連れします。", zh: "我们的工作人员会带她到登机口。" },
    ],
  },
  {
    id: "airport-a2x-pet-cabin",
    situationKey: "airport",
    level: "A2",
    title: { en: "Pet in the cabin", ja: "ペットを機内に持ち込む", zh: "宠物随机舱内携带" },
    lines: [
      { speaker: "여행객", kr: "고양이를 기내에 데려가고 싶어요.", en: "I'd like to bring my cat into the cabin.", ja: "猫を機内に連れて行きたいです。", zh: "我想带猫咪一起进机舱。" },
      { speaker: "직원", kr: "예약할 때 신청하셨어요?", en: "Did you apply when you booked?", ja: "予約の時に申請されましたか？", zh: "预订的时候申请过吗？" },
      { speaker: "여행객", kr: "네, 신청했어요.", en: "Yes, I applied.", ja: "はい、申請しました。", zh: "申请过了。" },
      { speaker: "직원", kr: "그럼 이동장을 확인할게요.", en: "Then I'll check the carrier.", ja: "では、キャリーを確認いたします。", zh: "那我看一下宠物笼。" },
      { speaker: "여행객", kr: "여기 있어요.", en: "Here it is.", ja: "こちらです。", zh: "在这里。" },
    ],
  },
  {
    id: "airport-a2x-exchange-rate",
    situationKey: "airport",
    level: "A2",
    title: { en: "Asking about the exchange rate", ja: "為替レートについて尋ねる", zh: "询问汇率" },
    lines: [
      { speaker: "여행객", kr: "오늘 환율이 얼마예요?", en: "What's today's exchange rate?", ja: "今日の為替レートはいくらですか？", zh: "今天的汇率是多少？" },
      { speaker: "직원", kr: "천삼백 원이에요.", en: "It's 1,300 won.", ja: "千三百ウォンです。", zh: "是1300韩元。" },
      { speaker: "여행객", kr: "백 달러 바꿀게요.", en: "I'll exchange 100 dollars.", ja: "百ドル両替します。", zh: "我要兑换100美元。" },
      { speaker: "직원", kr: "수수료가 좀 있어요.", en: "There's a small fee.", ja: "手数料が少しかかります。", zh: "会有一点手续费。" },
      { speaker: "여행객", kr: "괜찮아요, 바꿔 주세요.", en: "That's fine, please exchange it.", ja: "大丈夫です、両替してください。", zh: "没关系，请帮我兑换。" },
    ],
  },
  {
    id: "airport-a2x-gate-question",
    situationKey: "airport",
    level: "A2",
    title: { en: "Asking about a gate change", ja: "ゲート変更について尋ねる", zh: "询问登机口变更" },
    lines: [
      { speaker: "여행객", kr: "방금 게이트가 바뀌었어요?", en: "Did the gate just change?", ja: "たった今ゲートが変わりましたか？", zh: "刚才登机口改了吗？" },
      { speaker: "직원", kr: "네, 삼십오 번으로 바뀌었어요.", en: "Yes, it changed to gate 35.", ja: "はい、三十五番に変わりました。", zh: "对，改成了35号。" },
      { speaker: "여행객", kr: "여기서 멀어요?", en: "Is it far from here?", ja: "ここから遠いですか？", zh: "离这儿远吗？" },
      { speaker: "직원", kr: "네, 조금 걸어야 해요.", en: "Yes, you'll need to walk a bit.", ja: "はい、少し歩く必要があります。", zh: "有点远，需要走一段路。" },
      { speaker: "여행객", kr: "빨리 가야겠네요.", en: "I should hurry then.", ja: "急いで行かないといけませんね。", zh: "那我得快点过去了。" },
    ],
  },
  {
    id: "airport-a2x-rebook",
    situationKey: "airport",
    level: "A2",
    title: { en: "Rebooking after a cancellation", ja: "欠航後の予約変更", zh: "航班取消后重新订票" },
    lines: [
      { speaker: "여행객", kr: "제 비행기가 취소됐어요.", en: "My flight got canceled.", ja: "私の飛行機が欠航になりました。", zh: "我的航班取消了。" },
      { speaker: "직원", kr: "확인했어요. 다음 편으로 바꿔 드릴게요.", en: "I see. I'll change you to the next flight.", ja: "確認しました。次の便に変更いたします。", zh: "我确认过了，帮您改到下一班。" },
      { speaker: "여행객", kr: "언제 출발해요?", en: "When does it leave?", ja: "いつ出発しますか？", zh: "什么时候起飞？" },
      { speaker: "직원", kr: "오후 세 시에 출발해요.", en: "It leaves at 3 p.m.", ja: "午後三時に出発します。", zh: "下午三点起飞。" },
      { speaker: "여행객", kr: "네, 그걸로 할게요.", en: "Okay, I'll take that one.", ja: "はい、それにします。", zh: "好的，就那个吧。" },
    ],
  },
  {
    id: "airport-a2x-fragile-fee",
    situationKey: "airport",
    level: "A2",
    title: { en: "Extra fee for fragile handling", ja: "割れ物取り扱いの追加料金", zh: "易碎物品处理的额外费用" },
    lines: [
      { speaker: "직원", kr: "이 가방은 특수 포장이 필요해요.", en: "This bag needs special packaging.", ja: "このかばんは特殊梱包が必要です。", zh: "这个包需要特殊包装。" },
      { speaker: "여행객", kr: "돈이 더 들어요?", en: "Does that cost extra?", ja: "追加料金がかかりますか？", zh: "要多花钱吗？" },
      { speaker: "직원", kr: "네, 오천 원 정도 들어요.", en: "Yes, it costs about 5,000 won.", ja: "はい、五千ウォンほどかかります。", zh: "是的，大概要5000韩元。" },
      { speaker: "여행객", kr: "그럼 포장해 주세요.", en: "Then please pack it.", ja: "では、梱包してください。", zh: "那请帮我包装一下。" },
      { speaker: "직원", kr: "네, 지금 해 드릴게요.", en: "Okay, I'll do it now.", ja: "はい、今すぐいたします。", zh: "好的，我现在就帮您处理。" },
    ],
  },
  {
    id: "airport-a2x-arrival-sign",
    situationKey: "airport",
    level: "A2",
    title: { en: "Making a pickup sign", ja: "出迎え用の名前ボードを作る", zh: "制作接机牌" },
    lines: [
      { speaker: "여행객", kr: "친구를 마중 나왔어요.", en: "I'm here to pick up a friend.", ja: "友達を出迎えに来ました。", zh: "我来接朋友。" },
      { speaker: "직원", kr: "이름을 쓴 팻말이 있어요?", en: "Do you have a sign with the name?", ja: "名前を書いた札はありますか？", zh: "有写名字的牌子吗？" },
      { speaker: "여행객", kr: "아니요, 아직 안 만들었어요.", en: "No, I haven't made one yet.", ja: "いいえ、まだ作っていません。", zh: "没有，还没做。" },
      { speaker: "직원", kr: "저쪽 매점에서 종이를 팔아요.", en: "The kiosk over there sells paper.", ja: "あちらの売店で紙を売っています。", zh: "那边的小卖部有卖纸。" },
      { speaker: "여행객", kr: "고마워요, 가 볼게요.", en: "Thanks, I'll go check.", ja: "ありがとうございます、行ってみます。", zh: "谢谢，我去看看。" },
    ],
  },
  {
    id: "airport-a2x-charger-borrow",
    situationKey: "airport",
    level: "A2",
    title: { en: "Borrowing a portable charger", ja: "モバイルバッテリーを借りる", zh: "借充电宝" },
    lines: [
      { speaker: "여행객", kr: "보조 배터리를 빌릴 수 있어요?", en: "Can I borrow a portable charger?", ja: "モバイルバッテリーを借りられますか？", zh: "可以借一下充电宝吗？" },
      { speaker: "직원", kr: "네, 카드를 등록하면 빌려드려요.", en: "Yes, if you register a card, we'll lend one.", ja: "はい、カードを登録すればお貸しします。", zh: "可以，登记一下卡就可以借。" },
      { speaker: "여행객", kr: "언제까지 반납해요?", en: "When do I need to return it?", ja: "いつまでに返却しますか？", zh: "什么时候要还？" },
      { speaker: "직원", kr: "탑승 전까지 반납해 주세요.", en: "Please return it before boarding.", ja: "搭乗前に返却してください。", zh: "请在登机前归还。" },
      { speaker: "여행객", kr: "알겠어요, 감사해요.", en: "Got it, thank you.", ja: "分かりました、ありがとうございます。", zh: "明白了，谢谢。" },
    ],
  },
  {
    id: "airport-a2x-meal-special",
    situationKey: "airport",
    level: "A2",
    title: { en: "Special meal request", ja: "特別食のリクエスト", zh: "申请特殊餐食" },
    lines: [
      { speaker: "여행객", kr: "채식 식사를 신청하고 싶어요.", en: "I'd like to request a vegetarian meal.", ja: "ベジタリアン食を申請したいです。", zh: "我想申请素食餐。" },
      { speaker: "직원", kr: "언제 탑승하세요?", en: "When are you flying?", ja: "いつ搭乗されますか？", zh: "什么时候乘机？" },
      { speaker: "여행객", kr: "내일 오전 열 시요.", en: "Tomorrow at 10 a.m.", ja: "明日の午前十時です。", zh: "明天上午十点。" },
      { speaker: "직원", kr: "지금 신청하면 준비될 거예요.", en: "If you request now, it'll be ready.", ja: "今申請すれば準備できます。", zh: "现在申请的话应该来得及准备。" },
      { speaker: "여행객", kr: "네, 신청해 주세요.", en: "Yes, please request it.", ja: "はい、申請してください。", zh: "好的，请帮我申请。" },
    ],
  },
  {
    id: "airport-a2x-lostpass-reissue",
    situationKey: "airport",
    level: "A2",
    title: { en: "Reissuing a lost boarding pass at the gate", ja: "ゲートで搭乗券を再発行する", zh: "在登机口补办丢失的登机牌" },
    lines: [
      { speaker: "여행객", kr: "탑승권을 잃어버려서 게이트를 못 찾겠어요.", en: "I lost my boarding pass and can't find my gate.", ja: "搭乗券をなくして、ゲートが分かりません。", zh: "登机牌丢了，找不到登机口。" },
      { speaker: "직원", kr: "성함이랑 항공편을 말해 주세요.", en: "Please tell me your name and flight number.", ja: "お名前と便名を教えてください。", zh: "请告诉我您的姓名和航班号。" },
      { speaker: "여행객", kr: "김민수이고, 케이이백일 편이에요.", en: "Kim Minsu, flight KE201.", ja: "キム・ミンスで、KE201便です。", zh: "我叫金民秀，KE201航班。" },
      { speaker: "직원", kr: "찾았어요. 새로 뽑아 드릴게요.", en: "Found it. I'll print you a new one.", ja: "見つかりました。新しく発行いたします。", zh: "找到了，我给您重新打印一张。" },
      { speaker: "여행객", kr: "정말 감사해요.", en: "Thank you so much.", ja: "本当にありがとうございます。", zh: "太感谢了。" },
    ],
  },
  {
    id: "airport-a2x-wheelchair-time",
    situationKey: "airport",
    level: "A2",
    title: { en: "Scheduling wheelchair assistance", ja: "車椅子サービスの時間を調整する", zh: "预约轮椅协助时间" },
    lines: [
      { speaker: "여행객", kr: "어머니께 휠체어가 필요해요.", en: "My mother needs a wheelchair.", ja: "母に車椅子が必要です。", zh: "我母亲需要一辆轮椅。" },
      { speaker: "직원", kr: "몇 시 비행기세요?", en: "What time is her flight?", ja: "何時の飛行機ですか？", zh: "是几点的飞机？" },
      { speaker: "여행객", kr: "오후 두 시예요.", en: "2 p.m.", ja: "午後二時です。", zh: "下午两点。" },
      { speaker: "직원", kr: "한 시간 전에 여기로 다시 오세요.", en: "Please come back here an hour before.", ja: "一時間前にまたここに来てください。", zh: "请提前一小时再来这里。" },
      { speaker: "여행객", kr: "네, 그렇게 할게요.", en: "Okay, I'll do that.", ja: "はい、そうします。", zh: "好的，我会的。" },
    ],
  },
  {
    id: "airport-a2x-cart-return",
    situationKey: "airport",
    level: "A2",
    title: { en: "Returning a luggage cart", ja: "カートを返却する", zh: "归还行李推车" },
    lines: [
      { speaker: "여행객", kr: "이 카트는 어디에 반납해요?", en: "Where do I return this cart?", ja: "このカートはどこに返却しますか？", zh: "这个推车要还到哪里？" },
      { speaker: "직원", kr: "저쪽 카트 보관소에 놓으시면 돼요.", en: "You can leave it at the cart area over there.", ja: "あちらのカート置き場に置けば大丈夫です。", zh: "放在那边的推车存放处就可以了。" },
      { speaker: "여행객", kr: "동전을 다시 받을 수 있어요?", en: "Can I get my coin back?", ja: "コインは戻ってきますか？", zh: "硬币能取回来吗？" },
      { speaker: "직원", kr: "네, 반납하면 자동으로 나와요.", en: "Yes, it comes out automatically when you return it.", ja: "はい、返却すると自動的に出てきます。", zh: "可以，还车的时候会自动退出来。" },
      { speaker: "여행객", kr: "알겠어요, 고마워요.", en: "Got it, thank you.", ja: "分かりました、ありがとうございます。", zh: "明白了，谢谢。" },
    ],
  },
  {
    id: "airport-a2x-taxfree-form",
    situationKey: "airport",
    level: "A2",
    title: { en: "Filling out a tax refund form", ja: "免税還付書類を記入する", zh: "填写退税表格" },
    lines: [
      { speaker: "여행객", kr: "환급 서류를 어떻게 써요?", en: "How do I fill out the refund form?", ja: "還付書類はどう書きますか？", zh: "退税表格要怎么填？" },
      { speaker: "직원", kr: "여권 번호랑 카드 번호를 적어 주세요.", en: "Please write your passport number and card number.", ja: "パスポート番号とカード番号を書いてください。", zh: "请填写护照号码和卡号。" },
      { speaker: "여행객", kr: "이렇게 쓰면 돼요?", en: "Is this how I write it?", ja: "こう書けばいいですか？", zh: "这样写对吗？" },
      { speaker: "직원", kr: "네, 맞아요. 서명도 해 주세요.", en: "Yes, that's right. Please sign it too.", ja: "はい、正しいです。サインもお願いします。", zh: "对，没错。请再签个名。" },
      { speaker: "여행객", kr: "다 됐어요.", en: "All done.", ja: "できました。", zh: "都填好了。" },
    ],
  },
  {
    id: "airport-b1x-taxfree-negotiate",
    situationKey: "airport",
    level: "B1",
    title: { en: "Overweight baggage fee negotiation", ja: "超過手荷物料金の交渉", zh: "商议超重行李费" },
    lines: [
      { speaker: "직원", kr: "가방이 오 킬로 초과돼서 추가 요금이 나와요.", en: "Your bag is 5 kilos over, so there's an extra fee.", ja: "かばんが五キロ超過しているので、追加料金がかかります。", zh: "行李超重五公斤，需要收取额外费用。" },
      { speaker: "여행객", kr: "얼마나 나와요?", en: "How much is it?", ja: "いくらかかりますか？", zh: "要多少钱？" },
      { speaker: "직원", kr: "육만 원 정도예요.", en: "It's about 60,000 won.", ja: "六万ウォンくらいです。", zh: "大约60000韩元。" },
      { speaker: "여행객", kr: "너무 비싸네요. 짐을 좀 옮기면 안 될까요?", en: "That's too expensive. Can I move some items around?", ja: "高すぎますね。荷物を少し移してもいいですか？", zh: "太贵了。可以把一些东西挪出来吗？" },
      { speaker: "직원", kr: "다른 가방이 있으면 나눠서 넣으셔도 돼요.", en: "If you have another bag, you can split them up.", ja: "他のかばんがあれば分けて入れても大丈夫です。", zh: "如果有其他包，可以分开装。" },
      { speaker: "여행객", kr: "네, 잠깐 정리해 볼게요.", en: "Okay, let me sort it out for a moment.", ja: "はい、少し整理してみます。", zh: "好的，我整理一下。" },
      { speaker: "직원", kr: "천천히 하세요, 시간 있어요.", en: "Take your time, there's time.", ja: "ゆっくりどうぞ、時間はあります。", zh: "不着急，还有时间。" },
    ],
  },
  {
    id: "airport-b1x-lounge-guest",
    situationKey: "airport",
    level: "B1",
    title: { en: "Bringing a guest into the lounge", ja: "同伴者をラウンジに連れて入る", zh: "带同伴进入贵宾室" },
    lines: [
      { speaker: "여행객", kr: "일행이랑 같이 라운지에 들어가고 싶은데요.", en: "I'd like to bring a companion into the lounge.", ja: "同行者と一緒にラウンジに入りたいのですが。", zh: "我想和同伴一起进贵宾室。" },
      { speaker: "직원", kr: "동반 이용 조건이 있는지 확인해 볼게요.", en: "Let me check if there's a guest privilege.", ja: "同伴利用の条件があるか確認します。", zh: "我确认一下有没有同伴使用的资格。" },
      { speaker: "여행객", kr: "제 카드는 프리미엄 카드예요.", en: "My card is a premium card.", ja: "私のカードはプレミアムカードです。", zh: "我的卡是高级卡。" },
      { speaker: "직원", kr: "그러면 한 분까지 무료로 동반 가능해요.", en: "In that case, you can bring one guest for free.", ja: "それでしたら、お一人まで無料で同伴できます。", zh: "那样的话，可以免费带一位同伴进入。" },
      { speaker: "여행객", kr: "다행이네요. 감사합니다.", en: "That's a relief. Thank you.", ja: "よかったです。ありがとうございます。", zh: "太好了，谢谢。" },
      { speaker: "직원", kr: "카드랑 탑승권 보여 주세요.", en: "Please show me your card and boarding pass.", ja: "カードと搭乗券を見せてください。", zh: "请出示您的卡和登机牌。" },
      { speaker: "여행객", kr: "여기 있어요.", en: "Here you go.", ja: "こちらです。", zh: "在这里。" },
    ],
  },
  {
    id: "airport-b1x-minor-pickup",
    situationKey: "airport",
    level: "B1",
    title: { en: "Confirming who will pick up a minor", ja: "子供を迎えに来る人を確認する", zh: "确认由谁来接未成年人" },
    lines: [
      { speaker: "직원", kr: "도착지에서 누가 아이를 데리러 오세요?", en: "Who is picking up your child at the arrival airport?", ja: "到着地では誰がお子さんを迎えに来ますか？", zh: "在到达机场谁来接孩子呢？" },
      { speaker: "학부모", kr: "아이 삼촌이 데리러 올 거예요.", en: "The child's uncle will be picking her up.", ja: "子供の叔父が迎えに来ます。", zh: "孩子的舅舅会来接。" },
      { speaker: "직원", kr: "그분 신분증 사본이 필요해요.", en: "We'll need a copy of his ID.", ja: "その方の身分証のコピーが必要です。", zh: "我们需要他的身份证复印件。" },
      { speaker: "학부모", kr: "미리 이메일로 보냈는데 확인해 주시겠어요?", en: "I sent it by email in advance—could you check?", ja: "事前にメールで送ったのですが、確認していただけますか？", zh: "我提前用邮件发过去了，可以帮我确认一下吗？" },
      { speaker: "직원", kr: "네, 잠시만요. 확인됐어요.", en: "Yes, one moment. It's confirmed.", ja: "はい、少々お待ちください。確認できました。", zh: "好的，稍等。已经确认了。" },
      { speaker: "학부모", kr: "다행이네요. 아이가 걱정이 많아서요.", en: "That's a relief. My daughter is quite worried.", ja: "よかったです。子供がとても心配していたので。", zh: "太好了。孩子一直很担心。" },
      { speaker: "직원", kr: "저희 직원이 끝까지 함께할 거예요.", en: "Our staff will be with her the whole way.", ja: "私どものスタッフが最後まで付き添います。", zh: "我们的工作人员会一直陪着她。" },
    ],
  },
  {
    id: "airport-b1x-pet-vaccine",
    situationKey: "airport",
    level: "B1",
    title: { en: "Missing pet vaccination record", ja: "ペットの予防接種証明書がない", zh: "宠物疫苗证明缺失" },
    lines: [
      { speaker: "직원", kr: "예방 접종 증명서를 가지고 계세요?", en: "Do you have the vaccination certificate?", ja: "予防接種証明書はお持ちですか？", zh: "您带疫苗证明了吗？" },
      { speaker: "여행객", kr: "아, 집에 두고 온 것 같아요.", en: "Oh, I think I left it at home.", ja: "あ、家に置いてきたようです。", zh: "啊，好像忘在家里了。" },
      { speaker: "직원", kr: "그럼 반려동물을 태울 수 없어요.", en: "Then we can't board your pet.", ja: "それでは、ペットを搭乗させることができません。", zh: "那就不能带宠物登机了。" },
      { speaker: "여행객", kr: "휴대폰에 사진이 있는데 이걸로 안 될까요?", en: "I have a photo on my phone—would that work?", ja: "携帯に写真があるんですが、これではだめですか？", zh: "手机里有照片，这个可以吗？" },
      { speaker: "직원", kr: "잠시 확인해 볼게요. 사진 보내 주세요.", en: "Let me check for a moment. Please send the photo.", ja: "少し確認してみます。写真を送ってください。", zh: "我确认一下，请把照片发过来。" },
      { speaker: "여행객", kr: "지금 보냈어요.", en: "I just sent it.", ja: "今送りました。", zh: "刚发过去了。" },
      { speaker: "직원", kr: "확인됐어요. 이번에는 통과해 드릴게요.", en: "It's confirmed. We'll let it pass this time.", ja: "確認できました。今回は通します。", zh: "确认了，这次就放行。" },
    ],
  },
  {
    id: "airport-b1x-exchange-large",
    situationKey: "airport",
    level: "B1",
    title: { en: "Exchanging a large amount of cash", ja: "多額の現金を両替する", zh: "兑换大额现金" },
    lines: [
      { speaker: "여행객", kr: "이천 달러를 원화로 바꾸고 싶어요.", en: "I'd like to exchange 2,000 dollars for won.", ja: "二千ドルをウォンに両替したいです。", zh: "我想把2000美元换成韩元。" },
      { speaker: "직원", kr: "큰 금액이라 신분증이 필요해요.", en: "Since it's a large amount, we'll need ID.", ja: "大きな金額なので身分証が必要です。", zh: "因为金额较大，需要身份证件。" },
      { speaker: "여행객", kr: "여권으로 되나요?", en: "Will a passport work?", ja: "パスポートで大丈夫ですか？", zh: "护照可以吗？" },
      { speaker: "직원", kr: "네, 여권이면 충분해요.", en: "Yes, a passport is enough.", ja: "はい、パスポートで十分です。", zh: "可以，护照就够了。" },
      { speaker: "여행객", kr: "수수료는 얼마나 돼요?", en: "How much is the fee?", ja: "手数料はいくらですか？", zh: "手续费是多少？" },
      { speaker: "직원", kr: "이 프로 정도 붙어요.", en: "It's about 2 percent.", ja: "二パーセントほどかかります。", zh: "大概是百分之二。" },
      { speaker: "여행객", kr: "알겠어요, 바꿔 주세요.", en: "Okay, please exchange it.", ja: "分かりました、両替してください。", zh: "好的，请帮我兑换。" },
    ],
  },
  {
    id: "airport-b1x-rebook-hotel",
    situationKey: "airport",
    level: "B1",
    title: { en: "Rebooking and asking about a hotel voucher", ja: "予約変更とホテルバウチャーについて尋ねる", zh: "改签并询问酒店代金券" },
    lines: [
      { speaker: "여행객", kr: "제 항공편이 취소돼서 다음 날 아침 편으로 바뀌었어요.", en: "My flight got canceled and moved to the next morning.", ja: "私の便が欠航になり、翌朝の便に変更されました。", zh: "我的航班取消了，改到了第二天早上。" },
      { speaker: "직원", kr: "네, 확인했습니다. 불편을 드려 죄송해요.", en: "Yes, I see it. Sorry for the inconvenience.", ja: "はい、確認しました。ご不便をおかけして申し訳ございません。", zh: "好的，我确认过了。给您带来不便，非常抱歉。" },
      { speaker: "여행객", kr: "그럼 오늘 밤 호텔은 어떻게 해요?", en: "Then what about tonight's hotel?", ja: "では今夜のホテルはどうなりますか？", zh: "那今晚的住宿怎么办？" },
      { speaker: "직원", kr: "저희가 호텔 바우처를 드릴 수 있어요.", en: "We can give you a hotel voucher.", ja: "私どもがホテルバウチャーを差し上げられます。", zh: "我们可以给您一张酒店代金券。" },
      { speaker: "여행객", kr: "공항에서 가까운 곳인가요?", en: "Is it close to the airport?", ja: "空港から近い場所ですか？", zh: "离机场近吗？" },
      { speaker: "직원", kr: "네, 셔틀버스로 십 분 거리예요.", en: "Yes, it's a 10-minute shuttle ride away.", ja: "はい、シャトルバスで十分の距離です。", zh: "近，坐接驳车十分钟就到。" },
      { speaker: "여행객", kr: "좋아요, 그걸로 부탁해요.", en: "Great, I'll take that, please.", ja: "いいですね、それでお願いします。", zh: "好，那就麻烦您了。" },
    ],
  },
  {
    id: "airport-b1x-lost-belt",
    situationKey: "airport",
    level: "B1",
    title: { en: "Item left at the security tray", ja: "保安検査のトレイに忘れ物", zh: "东西落在安检托盘里" },
    lines: [
      { speaker: "여행객", kr: "검색대에 벨트를 두고 온 것 같아요.", en: "I think I left my belt at the security tray.", ja: "保安検査のところにベルトを忘れてきたようです。", zh: "我好像把腰带落在安检那里了。" },
      { speaker: "직원", kr: "언제쯤 지나셨어요?", en: "About when did you go through?", ja: "いつ頃通られましたか？", zh: "大概是什么时候过安检的？" },
      { speaker: "여행객", kr: "십 분 전쯤이요.", en: "About 10 minutes ago.", ja: "十分くらい前です。", zh: "大概十分钟前。" },
      { speaker: "직원", kr: "잠깐만요, 무전으로 확인해 볼게요.", en: "One moment, I'll check by radio.", ja: "少々お待ちください、無線で確認します。", zh: "请稍等，我用对讲机确认一下。" },
      { speaker: "여행객", kr: "네, 부탁드려요.", en: "Yes, please.", ja: "はい、お願いします。", zh: "好的，麻烦您了。" },
      { speaker: "직원", kr: "찾았대요. 다시 검색대로 가시면 돼요.", en: "They found it. You can go back to the checkpoint.", ja: "見つかったそうです。もう一度検査場に戻ってください。", zh: "找到了，您再回安检口就可以了。" },
      { speaker: "여행객", kr: "정말 다행이에요, 감사해요.", en: "What a relief, thank you.", ja: "本当によかったです、ありがとうございます。", zh: "太好了，谢谢。" },
    ],
  },
  {
    id: "airport-b1x-arrival-late",
    situationKey: "airport",
    level: "B1",
    title: { en: "Pickup driver running late", ja: "送迎の運転手が遅れている", zh: "接机司机迟到" },
    lines: [
      { speaker: "여행객", kr: "저를 데리러 올 기사님이 안 보여요.", en: "The driver who's supposed to pick me up isn't here.", ja: "迎えに来るはずの運転手さんが見当たりません。", zh: "来接我的司机没看到人。" },
      { speaker: "직원", kr: "예약 확인서가 있으세요?", en: "Do you have your booking confirmation?", ja: "予約確認書はお持ちですか？", zh: "有预约确认单吗？" },
      { speaker: "여행객", kr: "네, 휴대폰에 있어요.", en: "Yes, it's on my phone.", ja: "はい、携帯にあります。", zh: "有，在我手机里。" },
      { speaker: "직원", kr: "회사에 전화해서 확인해 볼게요.", en: "I'll call the company to check.", ja: "会社に電話して確認します。", zh: "我打电话给公司确认一下。" },
      { speaker: "여행객", kr: "네, 부탁드려요.", en: "Yes, please.", ja: "はい、お願いします。", zh: "好的，麻烦您了。" },
      { speaker: "직원", kr: "십 분 뒤에 도착한대요.", en: "They say the driver will arrive in 10 minutes.", ja: "十分後に到着するそうです。", zh: "说是十分钟后到。" },
      { speaker: "여행객", kr: "알겠어요, 여기서 기다릴게요.", en: "Okay, I'll wait here.", ja: "分かりました、ここで待ちます。", zh: "好的，我在这里等。" },
    ],
  },
  {
    id: "airport-b1x-gate-far",
    situationKey: "airport",
    level: "B1",
    title: { en: "Gate changed to a far terminal", ja: "ゲートが遠いターミナルに変更", zh: "登机口改到了较远的航站楼" },
    lines: [
      { speaker: "여행객", kr: "방송에서 게이트가 바뀌었다고 들었는데 맞아요?", en: "I heard on the announcement that the gate changed—is that right?", ja: "アナウンスでゲートが変わったと聞いたんですが、本当ですか？", zh: "广播里说登机口改了，是真的吗？" },
      { speaker: "직원", kr: "네, 다른 터미널로 옮겨졌어요.", en: "Yes, it's been moved to a different terminal.", ja: "はい、別のターミナルに移りました。", zh: "对，改到了另一个航站楼。" },
      { speaker: "여행객", kr: "거기까지 얼마나 걸려요?", en: "How long does it take to get there?", ja: "そこまでどれくらいかかりますか？", zh: "到那里要多久？" },
      { speaker: "직원", kr: "셔틀 타면 십오 분 정도 걸려요.", en: "By shuttle, it takes about 15 minutes.", ja: "シャトルに乗れば十五分くらいかかります。", zh: "坐接驳车大概要十五分钟。" },
      { speaker: "여행객", kr: "지금 바로 가야겠네요.", en: "I should go right now.", ja: "今すぐ行かないといけませんね。", zh: "那我得马上出发了。" },
      { speaker: "직원", kr: "네, 셔틀은 저쪽에서 타요.", en: "Yes, you catch the shuttle over there.", ja: "はい、シャトルはあちらから乗ります。", zh: "对，接驳车在那边坐。" },
      { speaker: "여행객", kr: "감사해요, 서둘러야겠어요.", en: "Thanks, I'd better hurry.", ja: "ありがとうございます、急がないと。", zh: "谢谢，我得赶紧了。" },
    ],
  },
  {
    id: "airport-b1x-fragile-refuse",
    situationKey: "airport",
    level: "B1",
    title: { en: "Fragile item the airline won't check", ja: "航空会社が預かれない割れ物", zh: "航空公司不接受托运的易碎品" },
    lines: [
      { speaker: "직원", kr: "이 도자기는 위탁 수하물로 못 받아요.", en: "We can't accept this pottery as checked baggage.", ja: "この陶磁器は預け荷物としてお預かりできません。", zh: "这件陶瓷不能作为托运行李收下。" },
      { speaker: "여행객", kr: "왜 안 되는 거예요?", en: "Why not?", ja: "どうしてだめなんですか？", zh: "为什么不行呢？" },
      { speaker: "직원", kr: "너무 깨지기 쉬워서 저희 규정에 안 맞아요.", en: "It's too fragile and doesn't meet our policy.", ja: "壊れやすすぎて弊社の規定に合いません。", zh: "太容易碎了，不符合我们的规定。" },
      { speaker: "여행객", kr: "그럼 기내에 들고 타도 될까요?", en: "Then can I carry it on board?", ja: "では機内に持ち込んでもいいですか？", zh: "那可以带上机吗？" },
      { speaker: "직원", kr: "크기가 맞으면 가능해요.", en: "If the size fits, yes.", ja: "サイズが合えば可能です。", zh: "大小合适的话可以。" },
      { speaker: "여행객", kr: "확인해 볼게요.", en: "Let me check the size.", ja: "確認してみます。", zh: "我确认一下大小。" },
      { speaker: "직원", kr: "저기 사이즈 틀에 넣어 보세요.", en: "Try putting it in the sizer over there.", ja: "あちらのサイズ枠に入れてみてください。", zh: "请试着放进那边的尺寸框里。" },
    ],
  },
  {
    id: "airport-b1x-meal-allergy",
    situationKey: "airport",
    level: "B1",
    title: { en: "Meal allergy request at check-in", ja: "チェックインで機内食アレルギーを申請する", zh: "在值机时申请餐食过敏事项" },
    lines: [
      { speaker: "여행객", kr: "땅콩 알레르기가 있는데 기내식에 반영될까요?", en: "I have a peanut allergy—will that be reflected in the meal?", ja: "ピーナッツアレルギーがあるんですが、機内食に反映されますか？", zh: "我对花生过敏，机上餐食能反映这一点吗？" },
      { speaker: "직원", kr: "예약할 때 신청 안 하셨어요?", en: "Didn't you request it when booking?", ja: "予約の時に申請されませんでしたか？", zh: "预订的时候没有申请吗？" },
      { speaker: "여행객", kr: "깜빡했어요. 지금이라도 될까요?", en: "I forgot. Is it possible even now?", ja: "忘れていました。今からでも可能ですか？", zh: "忘了。现在还能申请吗？" },
      { speaker: "직원", kr: "출발까지 두 시간 남아서 가능할 것 같아요.", en: "There's 2 hours until departure, so it should be possible.", ja: "出発まで二時間あるので可能だと思います。", zh: "距离起飞还有两小时，应该可以。" },
      { speaker: "여행객", kr: "정말요? 다행이에요.", en: "Really? What a relief.", ja: "本当ですか？よかったです。", zh: "真的吗？太好了。" },
      { speaker: "직원", kr: "지금 바로 요청 넣어 드릴게요.", en: "I'll put in the request right now.", ja: "今すぐリクエストを入れます。", zh: "我现在就帮您提交申请。" },
      { speaker: "여행객", kr: "감사해요, 정말로.", en: "Thank you so much.", ja: "本当にありがとうございます。", zh: "真的太谢谢您了。" },
    ],
  },
  {
    id: "airport-b1x-lounge-full",
    situationKey: "airport",
    level: "B1",
    title: { en: "Lounge is full", ja: "ラウンジが満席", zh: "贵宾室已满" },
    lines: [
      { speaker: "여행객", kr: "라운지에 들어가고 싶은데요.", en: "I'd like to go into the lounge.", ja: "ラウンジに入りたいのですが。", zh: "我想进贵宾室。" },
      { speaker: "직원", kr: "죄송하지만 지금 자리가 다 찼어요.", en: "I'm sorry, but it's full right now.", ja: "申し訳ございませんが、今は満席です。", zh: "不好意思，现在座位都满了。" },
      { speaker: "여행객", kr: "얼마나 기다려야 해요?", en: "How long do I need to wait?", ja: "どれくらい待たなければなりませんか？", zh: "要等多久？" },
      { speaker: "직원", kr: "보통 이십 분 정도 걸려요.", en: "It usually takes about 20 minutes.", ja: "通常二十分くらいかかります。", zh: "通常要二十分钟左右。" },
      { speaker: "여행객", kr: "그럼 기다렸다가 다시 올게요.", en: "Then I'll wait and come back.", ja: "では待ってからまた来ます。", zh: "那我等会儿再过来。" },
      { speaker: "직원", kr: "번호표를 드릴게요.", en: "I'll give you a number ticket.", ja: "番号札をお渡しします。", zh: "我给您一张号码牌。" },
      { speaker: "여행객", kr: "네, 감사해요.", en: "Okay, thank you.", ja: "はい、ありがとうございます。", zh: "好的，谢谢。" },
    ],
  },
  {
    id: "airport-b1x-cart-crowded",
    situationKey: "airport",
    level: "B1",
    title: { en: "No carts left at check-in", ja: "チェックインでカートが足りない", zh: "值机处推车用完了" },
    lines: [
      { speaker: "여행객", kr: "카트가 하나도 안 보이는데 다 나갔나요?", en: "I don't see any carts—are they all taken?", ja: "カートが一台も見当たりませんが、全部出てしまいましたか？", zh: "我一辆推车都没看到，都被拿走了吗？" },
      { speaker: "직원", kr: "네, 아침에 사람이 많아서 지금 부족해요.", en: "Yes, it's been busy this morning so we're short right now.", ja: "はい、朝人が多くて今不足しています。", zh: "是的，早上人多，现在不太够。" },
      { speaker: "여행객", kr: "짐이 많아서 카트 없이는 힘든데요.", en: "I have a lot of luggage, so it's hard without one.", ja: "荷物が多いのでカートなしでは大変です。", zh: "我行李很多，没有推车不方便。" },
      { speaker: "여행객", kr: "언제쯤 더 들어와요?", en: "When will more come in?", ja: "いつ頃また入ってきますか？", zh: "什么时候还会有新的推车？" },
      { speaker: "직원", kr: "직원이 지금 회수하러 나갔으니 곧 올 거예요.", en: "A staff member just went out to collect them, so they'll be here soon.", ja: "スタッフが今回収に出ているので、すぐ戻ります。", zh: "员工现在正去回收推车，很快就会有。" },
      { speaker: "여행객", kr: "그럼 여기서 좀 기다려 볼게요.", en: "Then I'll wait here for a bit.", ja: "では、ここで少し待ってみます。", zh: "那我在这里等一下。" },
      { speaker: "직원", kr: "보이는 대로 바로 가져다드릴게요.", en: "I'll bring one to you as soon as I see one.", ja: "見つかり次第すぐお持ちします。", zh: "一有推车我就马上给您送过来。" },
    ],
  },
  {
    id: "airport-b1x-lounge-time",
    situationKey: "airport",
    level: "B1",
    title: { en: "How long can you stay in the lounge", ja: "ラウンジにどれくらい滞在できるか", zh: "贵宾室能待多久" },
    lines: [
      { speaker: "여행객", kr: "라운지는 얼마나 오래 있을 수 있어요?", en: "How long can I stay in the lounge?", ja: "ラウンジにはどれくらい長く滞在できますか？", zh: "贵宾室能待多长时间？" },
      { speaker: "직원", kr: "탑승 시작 전까지는 자유롭게 계셔도 돼요.", en: "You're free to stay until boarding begins.", ja: "搭乗開始まで自由に滞在いただけます。", zh: "登机开始之前都可以自由停留。" },
      { speaker: "여행객", kr: "제 비행기가 세 시간 뒤라서 오래 있을 것 같아요.", en: "My flight is in 3 hours, so I'll probably be here a while.", ja: "私の飛行機は三時間後なので、長くいそうです。", zh: "我的飞机三小时后起飞，可能会待挺久。" },
      { speaker: "직원", kr: "괜찮아요, 시간 제한은 없어요.", en: "That's fine, there's no time limit.", ja: "大丈夫です、時間制限はありません。", zh: "没关系，没有时间限制。" },
      { speaker: "여행객", kr: "그럼 샤워실도 이용할 수 있어요?", en: "Then can I also use the shower room?", ja: "ではシャワールームも利用できますか？", zh: "那淋浴室也能用吗？" },
      { speaker: "직원", kr: "네, 예약만 하시면 이용 가능해요.", en: "Yes, you can use it if you just make a reservation.", ja: "はい、予約さえすればご利用いただけます。", zh: "可以，预约一下就能用。" },
      { speaker: "여행객", kr: "좋네요, 지금 예약할게요.", en: "That's great, I'll reserve one now.", ja: "いいですね、今予約します。", zh: "太好了，我现在就预约。" },
    ],
  },
  {
    id: "airport-b1x-meal-vegetarian-limited",
    situationKey: "airport",
    level: "B1",
    title: { en: "Vegetarian meal already ran out", ja: "ベジタリアン食がすでになくなった", zh: "素食餐已经用完了" },
    lines: [
      { speaker: "승무원", kr: "죄송하지만 채식 식사가 다 나갔어요.", en: "I'm sorry, but the vegetarian meal has run out.", ja: "申し訳ございませんが、ベジタリアン食がなくなりました。", zh: "不好意思，素食餐已经发完了。" },
      { speaker: "승객", kr: "네? 미리 신청했는데요.", en: "What? I requested it in advance.", ja: "え？事前に申請したんですが。", zh: "什么？我提前申请过的。" },
      { speaker: "승무원", kr: "예약 내역을 확인해 볼게요, 잠시만요.", en: "Let me check the reservation record, one moment.", ja: "予約履歴を確認します、少々お待ちください。", zh: "我确认一下预订记录，请稍等。" },
      { speaker: "승객", kr: "네, 확인 부탁드려요.", en: "Yes, please check.", ja: "はい、確認をお願いします。", zh: "好的，麻烦您确认一下。" },
      { speaker: "승무원", kr: "죄송해요, 시스템에 반영이 안 됐네요.", en: "I'm sorry, it wasn't reflected in the system.", ja: "申し訳ございません、システムに反映されていませんでした。", zh: "不好意思，系统里没有反映出来。" },
      { speaker: "승객", kr: "그럼 지금 먹을 수 있는 게 있어요?", en: "Then is there anything I can eat now?", ja: "では今食べられるものはありますか？", zh: "那现在有什么能吃的吗？" },
      { speaker: "승무원", kr: "과일이랑 샐러드는 드릴 수 있어요.", en: "I can give you fruit and salad.", ja: "果物とサラダならお渡しできます。", zh: "可以给您水果和沙拉。" },
    ],
  },
  {
    id: "airport-b1x-exchange-closed",
    situationKey: "airport",
    level: "B1",
    title: { en: "Exchange counter closing soon", ja: "両替所がまもなく閉まる", zh: "换汇柜台快要关门了" },
    lines: [
      { speaker: "여행객", kr: "환전소가 몇 시까지 열어요?", en: "Until what time is the exchange counter open?", ja: "両替所は何時まで開いていますか？", zh: "换汇处开到几点？" },
      { speaker: "직원", kr: "저녁 여덟 시까지예요. 이제 이십 분 남았어요.", en: "Until 8 p.m. There's only 20 minutes left now.", ja: "夜八時までです。あと二十分しかありません。", zh: "到晚上八点。现在只剩二十分钟了。" },
      { speaker: "여행객", kr: "그럼 빨리 처리할 수 있어요?", en: "Then can we do this quickly?", ja: "では急いで処理できますか？", zh: "那能快点办吗？" },
      { speaker: "직원", kr: "네, 얼마나 바꾸실 거예요?", en: "Yes, how much would you like to exchange?", ja: "はい、いくら両替されますか？", zh: "可以，您要兑换多少？" },
      { speaker: "여행객", kr: "삼백 달러요.", en: "300 dollars.", ja: "三百ドルです。", zh: "300美元。" },
      { speaker: "직원", kr: "네, 지금 바로 처리해 드릴게요.", en: "Okay, I'll process it right away.", ja: "はい、今すぐ処理いたします。", zh: "好的，我马上给您办理。" },
      { speaker: "여행객", kr: "감사해요, 시간 맞춰서 다행이에요.", en: "Thank you, I'm glad I made it in time.", ja: "ありがとうございます、間に合ってよかったです。", zh: "谢谢，还好赶上了。" },
    ],
  },
  {
    id: "airport-b2x-cart-broken",
    situationKey: "airport",
    level: "B2",
    title: { en: "Broken luggage cart at check-in", ja: "チェックインで壊れたカート", zh: "值机处的推车坏了" },
    lines: [
      { speaker: "여행객", kr: "카트 바퀴가 하나 빠진 것 같아요. 계속 한쪽으로 쏠려요.", en: "One of the cart wheels seems to have come off. It keeps pulling to one side.", ja: "カートの車輪が一つ外れているようです。ずっと片方に傾きます。", zh: "推车好像掉了一个轮子，一直往一边偏。" },
      { speaker: "직원", kr: "아, 죄송해요. 새 카트로 바꿔 드릴게요.", en: "Oh, I'm sorry. I'll get you a new cart.", ja: "あ、申し訳ございません。新しいカートに交換いたします。", zh: "啊，不好意思。我给您换一辆新的。" },
      { speaker: "여행객", kr: "짐을 다시 옮겨야 하는데 좀 도와주실 수 있어요?", en: "I need to move my luggage again—could you help?", ja: "荷物をまた移さなければならないんですが、手伝っていただけますか？", zh: "我得重新搬一次行李，能帮个忙吗？" },
      { speaker: "직원", kr: "네, 제가 옮겨 드릴게요.", en: "Yes, I'll move it for you.", ja: "はい、私が移します。", zh: "可以，我来帮您搬。" },
      { speaker: "여행객", kr: "감사해요. 시간이 별로 없어서 걱정이었어요.", en: "Thank you. I was worried since I don't have much time.", ja: "ありがとうございます。あまり時間がなくて心配していました。", zh: "谢谢。时间不多我还挺担心的。" },
      { speaker: "직원", kr: "체크인까지 아직 시간 여유 있으니 걱정 마세요.", en: "There's still plenty of time before check-in closes, so don't worry.", ja: "チェックインまでまだ時間に余裕がありますのでご心配なく。", zh: "距离值机截止还有充裕的时间，请别担心。" },
      { speaker: "여행객", kr: "그럼 좀 안심이 되네요.", en: "That's a bit of a relief, then.", ja: "それなら少し安心です。", zh: "那样的话就放心多了。" },
    ],
  },
  {
    id: "airport-b2x-taxfree-deadline",
    situationKey: "airport",
    level: "B2",
    title: { en: "Tax refund deadline dispute", ja: "免税還付の期限をめぐるやり取り", zh: "关于退税期限的争议" },
    lines: [
      { speaker: "여행객", kr: "이 영수증도 환급 받을 수 있나요? 산 지 좀 됐는데요.", en: "Can I get a refund on this receipt too? It's been a while since I bought it.", ja: "このレシートも還付を受けられますか？買ってから少し経っているんですが。", zh: "这张收据也能退税吗？买了有一阵子了。" },
      { speaker: "직원", kr: "언제 구매하셨어요?", en: "When did you purchase it?", ja: "いつ購入されましたか？", zh: "什么时候买的？" },
      { speaker: "여행객", kr: "삼 주 전이요. 날짜가 좀 애매하네요.", en: "Three weeks ago. The timing is a bit borderline.", ja: "三週間前です。日付が少し微妙ですね。", zh: "三周前。日期有点模糊。" },
      { speaker: "직원", kr: "저희 규정은 구매 후 삼 개월 이내까지예요.", en: "Our policy is within 3 months of purchase.", ja: "私どもの規定は購入後三ヶ月以内です。", zh: "我们的规定是购买后三个月内。" },
      { speaker: "여행객", kr: "아, 그럼 아직 괜찮은 거네요.", en: "Oh, then it should still be fine.", ja: "あ、それならまだ大丈夫ですね。", zh: "啊，那还来得及。" },
      { speaker: "직원", kr: "네, 여권이랑 영수증 원본만 주시면 돼요.", en: "Yes, just give me your passport and the original receipt.", ja: "はい、パスポートと領収書の原本をいただければ大丈夫です。", zh: "对，只要给我护照和收据原件就可以。" },
      { speaker: "여행객", kr: "여기 있어요. 확인해 주세요.", en: "Here you go. Please check them.", ja: "こちらです。確認してください。", zh: "在这里，请帮我看一下。" },
    ],
  },
  {
    id: "airport-b2x-pet-weather",
    situationKey: "airport",
    level: "B2",
    title: { en: "Pet cargo restricted due to weather", ja: "天候によりペット貨物輸送が制限される", zh: "因天气原因宠物货运受限" },
    lines: [
      { speaker: "직원", kr: "오늘 날씨 때문에 화물칸 반려동물 운송이 제한될 수 있어요.", en: "Because of today's weather, pet cargo transport may be restricted.", ja: "今日の天気のため、貨物室でのペット輸送が制限される可能性があります。", zh: "由于今天的天气，货舱宠物运输可能会受到限制。" },
      { speaker: "여행객", kr: "그게 무슨 말이에요? 못 태운다는 거예요?", en: "What does that mean—that my pet can't fly?", ja: "それはどういうことですか？乗せられないということですか？", zh: "这是什么意思？是说不能带上飞机吗？" },
      { speaker: "직원", kr: "기온이 너무 높아서 안전 문제로 재검토 중이에요.", en: "The temperature is too high, so it's under review for safety reasons.", ja: "気温が高すぎるため、安全上の理由で再検討中です。", zh: "因为气温太高，出于安全考虑正在重新评估。" },
      { speaker: "여행객", kr: "언제쯤 결정이 나요? 저는 곧 탑승해야 하는데요.", en: "When will they decide? I need to board soon.", ja: "いつ頃決定が出ますか？私はもうすぐ搭乗しなければならないんですが。", zh: "什么时候能决定？我马上就要登机了。" },
      { speaker: "직원", kr: "탑승 삼십 분 전까지는 알려 드릴게요.", en: "We'll let you know by 30 minutes before boarding.", ja: "搭乗三十分前までにはお知らせします。", zh: "登机前三十分钟会告诉您。" },
      { speaker: "여행객", kr: "만약 안 되면 어떻게 해야 하죠?", en: "If it's not allowed, what should I do?", ja: "もしだめだったらどうすればいいですか？", zh: "如果不行的话该怎么办？" },
      { speaker: "직원", kr: "그럴 경우 다음 편으로 무료 변경해 드릴게요.", en: "In that case, we'll change you to the next flight for free.", ja: "その場合は次の便に無料で変更いたします。", zh: "那种情况我们会免费帮您改签下一班。" },
    ],
  },
  {
    id: "airport-b2x-exchange-fake",
    situationKey: "airport",
    level: "B2",
    title: { en: "Suspected counterfeit bill at exchange", ja: "両替で偽札の疑い", zh: "换汇时疑似遇到假钞" },
    lines: [
      { speaker: "직원", kr: "죄송한데 이 지폐는 저희 기계에서 인식이 안 돼요.", en: "I'm sorry, but this bill isn't being recognized by our machine.", ja: "申し訳ございませんが、この紙幣は弊社の機械で認識されません。", zh: "不好意思，这张钞票我们的机器识别不出来。" },
      { speaker: "여행객", kr: "정말요? 은행에서 받은 건데 이상하네요.", en: "Really? That's strange—I got it from a bank.", ja: "本当ですか？銀行でもらったものなのでおかしいですね。", zh: "真的吗？这是从银行拿到的，很奇怪啊。" },
      { speaker: "직원", kr: "다른 지폐로 바꿔 주실 수 있으세요?", en: "Could you exchange it for a different bill?", ja: "別の紙幣に替えていただけますか？", zh: "能换一张别的钞票吗？" },
      { speaker: "여행객", kr: "지금은 이것밖에 없어요. 어떻게 해야 하죠?", en: "This is all I have right now. What should I do?", ja: "今はこれしかありません。どうすればいいですか？", zh: "我现在只有这一张。该怎么办呢？" },
      { speaker: "직원", kr: "일단 이 지폐는 빼고 나머지 금액만 환전해 드릴게요.", en: "For now, I'll exclude this bill and exchange only the rest.", ja: "とりあえずこの紙幣は除いて、残りの金額だけ両替いたします。", zh: "先把这张钞票排除，只帮您兑换剩下的金额。" },
      { speaker: "여행객", kr: "그럼 이 지폐는 어떻게 하죠?", en: "Then what do I do with this bill?", ja: "ではこの紙幣はどうしますか？", zh: "那这张钞票怎么办？" },
      { speaker: "직원", kr: "은행 창구에서 다시 확인해 보시는 게 좋을 거예요.", en: "It would be best to check it again at a bank counter.", ja: "銀行の窓口でもう一度確認されるのがいいと思います。", zh: "最好去银行柜台再确认一下。" },
    ],
  },
  {
    id: "airport-b2x-rebook-connection",
    situationKey: "airport",
    level: "B2",
    title: { en: "Rebooking that breaks a hotel reservation", ja: "ホテル予約に影響する予約変更", zh: "改签影响到酒店预订" },
    lines: [
      { speaker: "여행객", kr: "다음 편으로 바꿔 주신다고 했는데 그럼 밤늦게 도착하잖아요.", en: "You said you'd change me to the next flight, but that means arriving very late at night.", ja: "次の便に変更してくださると言いましたが、それだと夜遅く到着してしまいます。", zh: "您说帮我改到下一班，可那样的话晚上很晚才能到。" },
      { speaker: "직원", kr: "네, 죄송하지만 오늘은 그 편밖에 자리가 없어요.", en: "Yes, I'm sorry, but that's the only seat available today.", ja: "はい、申し訳ございませんが、今日はその便しか席がありません。", zh: "是的，不好意思，今天只有那趟航班有位子。" },
      { speaker: "여행객", kr: "호텔 체크인 시간이 지나 버릴 것 같아서 걱정이에요.", en: "I'm worried the hotel check-in time will have passed by then.", ja: "ホテルのチェックイン時間が過ぎてしまいそうで心配です。", zh: "我担心到时候酒店入住时间已经过了。" },
      { speaker: "직원", kr: "저희가 호텔 측에 연락해서 늦은 체크인을 요청해 드릴 수 있어요.", en: "We can contact the hotel to request a late check-in on your behalf.", ja: "私どもがホテル側に連絡して、遅いチェックインをリクエストできます。", zh: "我们可以联系酒店，帮您申请延迟入住。" },
      { speaker: "여행객", kr: "정말 그렇게 해 주실 수 있어요?", en: "Can you really do that for me?", ja: "本当にそうしていただけますか？", zh: "真的能帮我这样做吗？" },
      { speaker: "직원", kr: "네, 예약 확인서 좀 보여 주시겠어요?", en: "Yes, could you show me your reservation confirmation?", ja: "はい、予約確認書を見せていただけますか？", zh: "可以，能给我看一下预订确认单吗？" },
      { speaker: "여행객", kr: "여기요, 부탁드릴게요.", en: "Here you go, I'd appreciate it.", ja: "こちらです、よろしくお願いします。", zh: "在这里，麻烦您了。" },
    ],
  },
  {
    id: "airport-b2x-lostbelt-claim",
    situationKey: "airport",
    level: "B2",
    title: { en: "Filing a claim for an item lost at security", ja: "保安検査場での紛失物届を出す", zh: "为安检丢失的物品报案" },
    lines: [
      { speaker: "여행객", kr: "검색대에서 시계를 잃어버린 것 같은데 아무리 찾아도 없어요.", en: "I think I lost my watch at security, but I can't find it anywhere.", ja: "保安検査場で時計をなくしたようなんですが、どんなに探しても見つかりません。", zh: "我好像把手表落在安检了，怎么找都找不到。" },
      { speaker: "직원", kr: "언제, 어느 검색대였는지 기억나세요?", en: "Do you remember when and which checkpoint it was?", ja: "いつ、どの検査場だったか覚えていますか？", zh: "记得是什么时候、哪个安检口吗？" },
      { speaker: "여행객", kr: "한 시간 전쯤, 삼 번 검색대였던 것 같아요.", en: "About an hour ago, I think it was checkpoint 3.", ja: "一時間前くらい、三番検査場だったと思います。", zh: "大概一小时前，好像是三号安检口。" },
      { speaker: "직원", kr: "그럼 분실물 신고서를 작성해 주셔야 해요.", en: "Then you'll need to fill out a lost item report.", ja: "それでは紛失物届を記入していただく必要があります。", zh: "那需要您填写一份失物申报单。" },
      { speaker: "여행객", kr: "찾으면 어떻게 연락받을 수 있어요?", en: "If it's found, how will I be contacted?", ja: "見つかったらどうやって連絡をもらえますか？", zh: "找到了怎么联系我呢？" },
      { speaker: "직원", kr: "연락처를 남기시면 찾는 대로 전화드려요.", en: "If you leave your contact info, we'll call as soon as it's found.", ja: "連絡先を残していただければ、見つかり次第お電話します。", zh: "留下联系方式，一找到我们就会打电话给您。" },
      { speaker: "여행객", kr: "네, 여기 제 번호 적어 놓을게요.", en: "Okay, I'll write my number down here.", ja: "はい、ここに電話番号を書いておきます。", zh: "好的，我把号码写在这里。" },
    ],
  },
  {
    id: "airport-b2x-minor-late-pickup",
    situationKey: "airport",
    level: "B2",
    title: { en: "Guardian late to pick up an unaccompanied minor", ja: "保護者が非同伴児童の迎えに遅れる", zh: "监护人接无成人陪伴儿童迟到" },
    lines: [
      { speaker: "직원", kr: "아이를 데리러 오시기로 한 분이 아직 안 오셨어요.", en: "The person who was supposed to pick up your child hasn't arrived yet.", ja: "お子さんを迎えに来る予定の方がまだいらしていません。", zh: "预定来接孩子的人还没到。" },
      { speaker: "보호자", kr: "네? 저희는 계속 여기서 기다리고 있었는데요.", en: "What? We've been waiting here the whole time.", ja: "え？私たちはずっとここで待っていたんですが。", zh: "什么？我们一直在这里等着呢。" },
      { speaker: "직원", kr: "죄송해요, 다시 확인해 볼게요. 성함이 어떻게 되세요?", en: "I'm sorry, let me check again. What's the name?", ja: "申し訳ございません、もう一度確認します。お名前は？", zh: "不好意思，我再确认一下。请问贵姓？" },
      { speaker: "보호자", kr: "박지훈이에요. 아이 삼촌이요.", en: "Park Jihoon. The child's uncle.", ja: "パク・ジフンです。子供の叔父です。", zh: "我叫朴智勋，是孩子的舅舅。" },
      { speaker: "직원", kr: "아, 확인됐어요. 신분증만 보여 주시면 바로 인계해 드릴게요.", en: "Ah, confirmed. Just show your ID and I'll hand her over right away.", ja: "あ、確認できました。身分証を見せていただければすぐお引き渡しします。", zh: "啊，确认了。出示一下身份证，我马上把她交给您。" },
      { speaker: "보호자", kr: "여기 있어요. 정말 걱정했어요.", en: "Here it is. I was really worried.", ja: "こちらです。本当に心配しました。", zh: "在这里。真的挺担心的。" },
      { speaker: "직원", kr: "번거롭게 해 드려 죄송합니다.", en: "I'm sorry for the trouble.", ja: "お手数をおかけして申し訳ございません。", zh: "给您添麻烦了，非常抱歉。" },
    ],
  },
  {
    id: "airport-b2x-gate-shuttle-miss",
    situationKey: "airport",
    level: "B2",
    title: { en: "Missed the shuttle to a changed gate", ja: "変更されたゲート行きのシャトルに乗り遅れる", zh: "错过了去新登机口的接驳车" },
    lines: [
      { speaker: "여행객", kr: "셔틀을 놓쳐서 게이트에 늦을 것 같아요.", en: "I missed the shuttle and I think I'll be late for the gate.", ja: "シャトルに乗り遅れて、ゲートに遅れそうです。", zh: "错过了接驳车，恐怕会赶不上登机口的时间。" },
      { speaker: "직원", kr: "몇 번 게이트로 가세요?", en: "Which gate are you headed to?", ja: "何番ゲートに行かれますか？", zh: "您要去几号登机口？" },
      { speaker: "여행객", kr: "사십이 번이요. 방금 바뀌었대요.", en: "Gate 42. I heard it just changed.", ja: "四十二番です。たった今変わったそうです。", zh: "42号。听说刚刚改的。" },
      { speaker: "직원", kr: "다음 셔틀은 오 분 뒤에 와요.", en: "The next shuttle comes in 5 minutes.", ja: "次のシャトルは五分後に来ます。", zh: "下一班接驳车五分钟后到。" },
      { speaker: "여행객", kr: "그럼 탑승 시간에 못 맞출 것 같은데요.", en: "Then I don't think I'll make it in time for boarding.", ja: "それでは搭乗時間に間に合わないと思うんですが。", zh: "那我恐怕赶不上登机时间了。" },
      { speaker: "직원", kr: "게이트에 미리 연락해서 상황을 알려 드릴게요.", en: "I'll contact the gate ahead of time to let them know.", ja: "ゲートに前もって連絡して状況をお知らせします。", zh: "我提前联系登机口，把情况告诉他们。" },
      { speaker: "여행객", kr: "정말 감사해요, 서둘러 볼게요.", en: "Thank you so much, I'll hurry.", ja: "本当にありがとうございます、急いでみます。", zh: "太感谢了，我尽快赶过去。" },
    ],
  },
  {
    id: "airport-b2x-fragile-damaged",
    situationKey: "airport",
    level: "B2",
    title: { en: "Fragile item arrived damaged", ja: "割れ物が破損して到着した", zh: "易碎品到达时已损坏" },
    lines: [
      { speaker: "여행객", kr: "깨지기 쉬운 스티커까지 붙였는데 도착해서 열어 보니 깨져 있었어요.", en: "I even put a fragile sticker on it, but when I opened it after arrival, it was broken.", ja: "割れ物ステッカーまで貼ったのに、到着して開けてみたら割れていました。", zh: "都贴了易碎标签，可到了打开一看还是碎了。" },
      { speaker: "직원", kr: "정말 죄송합니다. 언제 어디서 확인하셨어요?", en: "I'm truly sorry. When and where did you notice this?", ja: "本当に申し訳ございません。いつ、どこで確認されましたか？", zh: "真的很抱歉。您是什么时候、在哪里发现的？" },
      { speaker: "여행객", kr: "방금 수하물 찾는 곳에서 열어 봤어요.", en: "I just opened it at the baggage claim.", ja: "たった今手荷物受取所で開けてみました。", zh: "刚才在行李领取处打开看的。" },
      { speaker: "직원", kr: "파손 신고서를 작성해 주시면 보상 절차를 도와드릴게요.", en: "If you fill out a damage report, we'll help you with the compensation process.", ja: "破損届を記入していただければ、補償手続きをお手伝いします。", zh: "填写一份损坏报告，我们会协助您办理赔偿。" },
      { speaker: "여행객", kr: "영수증이 필요한가요? 안에 있는 물건 영수증이요.", en: "Do I need a receipt—for the item inside?", ja: "領収書は必要ですか？中の物の領収書です。", zh: "需要收据吗？就是里面那个物品的收据。" },
      { speaker: "직원", kr: "네, 가능하면 가져와 주시고, 없으면 사진이라도 도움이 돼요.", en: "Yes, if possible bring it, but a photo helps too if you don't have it.", ja: "はい、可能であれば持ってきていただき、なければ写真でも役立ちます。", zh: "对，可以的话请带来，没有的话照片也可以。" },
      { speaker: "여행객", kr: "알겠어요, 지금 신고서 작성할게요.", en: "Okay, I'll fill out the report now.", ja: "分かりました、今届を記入します。", zh: "好的，我现在就填写报告。" },
    ],
  },
  {
    id: "airport-b2x-taxfree-electronics",
    situationKey: "airport",
    level: "B2",
    title: { en: "Tax refund on electronics needs inspection", ja: "電子製品の免税還付には現物確認が必要", zh: "电子产品退税需要实物检查" },
    lines: [
      { speaker: "직원", kr: "전자 제품은 환급 전에 실물 확인이 필요해요.", en: "Electronics need a physical inspection before the refund.", ja: "電子製品は還付前に現物確認が必要です。", zh: "电子产品退税前需要出示实物检查。" },
      { speaker: "여행객", kr: "아, 그럼 지금 짐에서 꺼내야 해요?", en: "Oh, so I need to take it out of my luggage now?", ja: "あ、では今荷物から出さないといけませんか？", zh: "啊，那我现在得从行李里拿出来吗？" },
      { speaker: "직원", kr: "네, 위탁 수하물에 넣기 전에 확인받으셔야 해요.", en: "Yes, you need to have it checked before checking in your luggage.", ja: "はい、預け荷物に入れる前に確認を受ける必要があります。", zh: "对，托运之前需要先经过检查。" },
      { speaker: "여행객", kr: "이미 체크인하고 왔는데 어떡하죠?", en: "I already checked in—what should I do?", ja: "もうチェックインしてきたんですが、どうすればいいですか？", zh: "我已经办完值机了，该怎么办？" },
      { speaker: "직원", kr: "그럼 저쪽 세관 확인 창구로 먼저 가 보세요.", en: "Then please go to the customs verification counter over there first.", ja: "それではあちらの税関確認窓口に先に行ってみてください。", zh: "那请先去那边的海关核验窗口。" },
      { speaker: "여행객", kr: "거기서도 확인이 가능한 거죠?", en: "Can they verify it there too?", ja: "そこでも確認できるんですよね？", zh: "那里也能核验对吧？" },
      { speaker: "직원", kr: "네, 그쪽에서 도장을 받으시면 저희가 처리해 드려요.", en: "Yes, once you get the stamp there, we'll process it.", ja: "はい、そちらでスタンプをもらえば私どもが処理いたします。", zh: "对，在那边盖了章之后我们就能给您处理。" },
    ],
  },
  {
    id: "airport-b2x-scale-dispute",
    situationKey: "airport",
    level: "B2",
    title: { en: "Disputing a scale reading", ja: "秤の数値をめぐる異議", zh: "对秤重结果提出异议" },
    lines: [
      { speaker: "여행객", kr: "집에서 잰 거랑 여기 저울 숫자가 너무 달라요.", en: "The number on this scale is very different from what I measured at home.", ja: "家で計ったのとここの秤の数値がかなり違います。", zh: "在家称的重量和这里秤上的数字差太多了。" },
      { speaker: "직원", kr: "저희 저울은 매일 아침 점검해요. 오차가 크진 않을 거예요.", en: "Our scale is checked every morning. There shouldn't be much error.", ja: "私どもの秤は毎朝点検しています。誤差は大きくないはずです。", zh: "我们的秤每天早上都会检查，误差应该不会太大。" },
      { speaker: "여행객", kr: "그래도 이 킬로그램 차이는 좀 이상해서요.", en: "Still, a 2-kilogram difference seems strange.", ja: "それでも二キログラムの差はちょっとおかしいと思います。", zh: "但两公斤的差距还是有点奇怪。" },
      { speaker: "직원", kr: "원하시면 다른 저울로 다시 재 드릴게요.", en: "If you'd like, I can weigh it again on another scale.", ja: "ご希望であれば、別の秤でもう一度計り直します。", zh: "如果您愿意，可以换一台秤再称一次。" },
      { speaker: "여행객", kr: "네, 그렇게 해 주시면 좋겠어요.", en: "Yes, I'd appreciate that.", ja: "はい、そうしていただけると助かります。", zh: "好，那就麻烦您了。" },
      { speaker: "직원", kr: "이쪽으로 옮겨서 다시 확인해 볼게요.", en: "Let's move it over here and check again.", ja: "こちらに移して再確認します。", zh: "我们把它挪到这边再确认一下。" },
      { speaker: "여행객", kr: "똑같이 나오면 그냥 초과 요금 낼게요.", en: "If it's the same, I'll just pay the excess fee.", ja: "同じ結果なら、そのまま超過料金を払います。", zh: "如果结果一样，那我就付超重费好了。" },
    ],
  },
  {
    id: "airport-b2x-arrival-nowifi",
    situationKey: "airport",
    level: "B2",
    title: { en: "Can't reach pickup driver without wifi", ja: "Wi-Fiがなくて送迎の運転手に連絡できない", zh: "没有Wi-Fi联系不上接机司机" },
    lines: [
      { speaker: "여행객", kr: "와이파이가 안 잡혀서 기사님한테 연락을 못 하고 있어요.", en: "I can't get wifi, so I can't reach the driver.", ja: "Wi-Fiがつながらなくて運転手さんに連絡できません。", zh: "连不上Wi-Fi，联系不上司机。" },
      { speaker: "직원", kr: "무료 와이파이 존은 저쪽 안내 데스크 근처예요.", en: "The free wifi zone is over near the information desk.", ja: "無料Wi-Fiゾーンはあちらの案内デスクの近くです。", zh: "免费Wi-Fi区域在那边的问询处附近。" },
      { speaker: "여행객", kr: "거기까지 좀 먼데, 혹시 여기 전화 좀 빌릴 수 있을까요?", en: "That's a bit far—could I possibly borrow a phone here?", ja: "そこまでちょっと遠いんですが、こちらの電話を借りられますか？", zh: "那边有点远，能不能借用一下这里的电话？" },
      { speaker: "직원", kr: "네, 잠깐 쓰셔도 돼요. 번호가 어떻게 되세요?", en: "Yes, you can use it for a moment. What's the number?", ja: "はい、少しなら使っていただいて大丈夫です。番号は何番ですか？", zh: "可以，用一下没问题。号码是多少？" },
      { speaker: "여행객", kr: "제가 불러 드릴게요, 감사합니다.", en: "I'll tell you the number, thank you.", ja: "番号を言いますね、ありがとうございます。", zh: "我告诉您号码，谢谢。" },
      { speaker: "직원", kr: "연결됐어요, 통화하세요.", en: "It's connected, go ahead and talk.", ja: "つながりました、どうぞお話しください。", zh: "接通了，您说话吧。" },
      { speaker: "여행객", kr: "정말 큰 도움이 됐어요.", en: "This was a huge help.", ja: "本当に助かりました。", zh: "真是帮了大忙。" },
    ],
  },
  {
    id: "airport-b2x-charger-not-returned",
    situationKey: "airport",
    level: "B2",
    title: { en: "Forgot to return the borrowed charger", ja: "借りた充電器の返却を忘れる", zh: "忘了归还借来的充电器" },
    lines: [
      { speaker: "직원", kr: "빌리신 보조 배터리를 아직 반납 안 하셨네요.", en: "You haven't returned the portable charger you borrowed yet.", ja: "お借りになったモバイルバッテリー、まだ返却されていませんね。", zh: "您借的充电宝还没有归还呢。" },
      { speaker: "여행객", kr: "아, 죄송해요. 가방 안에 있는 걸 깜빡했어요.", en: "Oh, sorry. I forgot it was in my bag.", ja: "あ、すみません。かばんの中にあるのを忘れていました。", zh: "啊，不好意思。忘了它在包里了。" },
      { speaker: "직원", kr: "지금 탑승 시작했는데, 반납 안 하시면 요금이 청구돼요.", en: "Boarding has already started, and if it's not returned there's a charge.", ja: "今搭乗が始まっていますが、返却されないと料金が請求されます。", zh: "现在已经开始登机了，不归还的话会收取费用。" },
      { speaker: "여행객", kr: "지금 바로 꺼낼게요, 잠깐만요.", en: "I'll take it out right now, one moment.", ja: "今すぐ出します、少々お待ちください。", zh: "我现在马上拿出来，稍等。" },
      { speaker: "여행객", kr: "여기요, 정말 죄송합니다.", en: "Here it is, I'm really sorry.", ja: "こちらです、本当に申し訳ございません。", zh: "在这里，真的很抱歉。" },
      { speaker: "직원", kr: "괜찮아요, 확인했으니 요금은 안 나가요.", en: "It's fine, I've confirmed it so there won't be a charge.", ja: "大丈夫です、確認できたので料金はかかりません。", zh: "没关系，确认好了就不会收费了。" },
      { speaker: "여행객", kr: "다행이네요, 빨리 탑승할게요.", en: "What a relief, I'll board quickly.", ja: "よかったです、急いで搭乗します。", zh: "太好了，我赶紧去登机。" },
    ],
  },
  {
    id: "airport-b2x-lounge-noshow",
    situationKey: "airport",
    level: "B2",
    title: { en: "Lounge access denied due to system error", ja: "システムエラーでラウンジに入れない", zh: "因系统错误无法进入贵宾室" },
    lines: [
      { speaker: "여행객", kr: "제 카드로 라운지 이용이 된다고 들었는데 안 된다고 나오네요.", en: "I was told my card gives lounge access, but it's showing as not valid.", ja: "私のカードでラウンジが利用できると聞いたのですが、だめだと表示されます。", zh: "听说我的卡可以用来进贵宾室，但系统显示不行。" },
      { speaker: "직원", kr: "카드 뒷면 번호를 다시 한번 스캔해 볼게요.", en: "Let me scan the number on the back of the card again.", ja: "カード裏の番号をもう一度スキャンしてみます。", zh: "我再扫一下卡背面的号码。" },
      { speaker: "여행객", kr: "여기요. 예전에는 문제없이 됐었어요.", en: "Here. It worked without any issue before.", ja: "こちらです。以前は問題なく使えていました。", zh: "在这里。以前用起来没问题的。" },
      { speaker: "직원", kr: "저희 쪽 시스템 오류인 것 같아요, 잠시만요.", en: "It seems to be an error on our system's side, one moment.", ja: "こちらのシステムエラーのようです、少々お待ちください。", zh: "好像是我们系统的问题，请稍等。" },
      { speaker: "여행객", kr: "얼마나 걸릴까요? 비행기 시간이 얼마 안 남았어요.", en: "How long will it take? I don't have much time before my flight.", ja: "どれくらいかかりますか？飛行機の時間があまり残っていません。", zh: "要多久？我的飞机时间不多了。" },
      { speaker: "직원", kr: "본사에 확인 요청했으니 오 분 안에 해결될 거예요.", en: "I've requested a check with headquarters, so it should be resolved within 5 minutes.", ja: "本社に確認を依頼しましたので、五分以内に解決すると思います。", zh: "已经请求总部确认了，五分钟内应该能解决。" },
      { speaker: "여행객", kr: "알겠어요, 여기서 기다릴게요.", en: "Okay, I'll wait here.", ja: "分かりました、ここで待ちます。", zh: "好的，我在这里等。" },
    ],
  },
  {
    id: "airport-b2x-wheelchair-mismatch",
    situationKey: "airport",
    level: "B2",
    title: { en: "Wheelchair request wasn't logged properly", ja: "車椅子のリクエストが正しく記録されていない", zh: "轮椅申请没有被正确记录" },
    lines: [
      { speaker: "여행객", kr: "저희 아버지 휠체어를 예약할 때 신청했는데 여기 기록이 없대요.", en: "I requested a wheelchair for my father when booking, but there's no record here.", ja: "父の車椅子を予約の時に申請したんですが、ここに記録がないそうです。", zh: "预订的时候给我父亲申请了轮椅，但这里没有记录。" },
      { speaker: "직원", kr: "죄송합니다, 시스템에서 확인이 안 되네요.", en: "I'm sorry, I can't find it in the system.", ja: "申し訳ございません、システムで確認できません。", zh: "不好意思，系统里查不到。" },
      { speaker: "여행객", kr: "확인 메일도 받았는데 이상하네요.", en: "That's strange, I even got a confirmation email.", ja: "確認メールももらったのにおかしいですね。", zh: "我还收到过确认邮件，很奇怪啊。" },
      { speaker: "직원", kr: "메일을 보여 주시면 도움이 될 것 같아요.", en: "If you show me the email, that would help.", ja: "メールを見せていただければ助かります。", zh: "能给我看看那封邮件的话就好办了。" },
      { speaker: "여행객", kr: "여기요, 확인해 보세요.", en: "Here, please check.", ja: "こちらです、確認してください。", zh: "在这里，请看一下。" },
      { speaker: "직원", kr: "확인했습니다. 지금 바로 휠체어를 준비해 드릴게요.", en: "Confirmed. I'll get a wheelchair ready for you right now.", ja: "確認できました。今すぐ車椅子をご用意します。", zh: "确认了。我马上给您准备轮椅。" },
      { speaker: "여행객", kr: "감사해요, 오래 서 계시기 힘드실까 봐 걱정했어요.", en: "Thank you, I was worried he'd have a hard time standing for long.", ja: "ありがとうございます、長く立っているのが大変だろうと心配していました。", zh: "谢谢，我担心他站太久会吃不消。" },
    ],
  },
  {
    id: "airport-b2x-pet-carrier-size",
    situationKey: "airport",
    level: "B2",
    title: { en: "Pet carrier is slightly oversized", ja: "ペットキャリーがわずかに規定サイズを超えている", zh: "宠物笼稍微超过了规定尺寸" },
    lines: [
      { speaker: "직원", kr: "이동장이 저희 기준보다 이 센티미터 커요.", en: "The carrier is 2 centimeters bigger than our standard.", ja: "キャリーが弊社の基準より二センチ大きいです。", zh: "宠物笼比我们的标准大了两厘米。" },
      { speaker: "여행객", kr: "네? 예약할 때 확인받은 규격인데요.", en: "What? This is the size I confirmed when I booked.", ja: "え？予約の時に確認された規格なんですが。", zh: "什么？这是预订时确认过的尺寸啊。" },
      { speaker: "직원", kr: "죄송한데 저희 기내 규정은 좀 더 엄격해요.", en: "I'm sorry, but our in-cabin policy is a bit stricter.", ja: "申し訳ございませんが、機内規定はもう少し厳しいんです。", zh: "不好意思，我们客舱的规定更严格一些。" },
      { speaker: "여행객", kr: "그럼 어떻게 해야 하죠? 다른 이동장이 없는데요.", en: "Then what should I do? I don't have another carrier.", ja: "では、どうすればいいですか？他のキャリーがないんですが。", zh: "那该怎么办？我没有别的宠物笼。" },
      { speaker: "직원", kr: "매점에서 맞는 이동장을 파는지 확인해 볼게요.", en: "Let me check if the shop sells a carrier that fits.", ja: "売店で合うキャリーを売っているか確認してみます。", zh: "我看看小卖部有没有合适的宠物笼。" },
      { speaker: "여행객", kr: "시간이 별로 없는데 빨리 확인해 주실 수 있어요?", en: "I don't have much time—could you check quickly?", ja: "あまり時間がないんですが、急いで確認していただけますか？", zh: "时间不太够了，能快点确认一下吗？" },
      { speaker: "직원", kr: "네, 지금 바로 연락해 볼게요.", en: "Yes, I'll contact them right now.", ja: "はい、今すぐ連絡してみます。", zh: "好的，我现在马上联系。" },
    ],
  },
];

export const AIRPORT_QUIZZES: Record<string, DialogueQuiz> = {
  "airport-a1x-cart": {
    q: "Where are the luggage carts?",
    opts: ["Near the entrance", "Next to the pillar", "By the elevator", "At the check-in desk"],
    ans: 1,
  },
  "airport-a1x-scale": {
    q: "How much does the traveler's bag weigh?",
    opts: ["10 kilos", "12 kilos", "15 kilos", "20 kilos"],
    ans: 2,
  },
  "airport-a1x-reprint": {
    q: "What does the staff member ask to see first?",
    opts: ["A boarding pass", "A passport", "A credit card", "A ticket receipt"],
    ans: 1,
  },
  "airport-a1x-exchange": {
    q: "Where is the currency exchange?",
    opts: ["On this floor", "Downstairs", "Near the gate", "Outside the airport"],
    ans: 0,
  },
  "airport-a1x-wheelchair": {
    q: "How long will the wheelchair take to arrive?",
    opts: ["1 minute", "5 minutes", "10 minutes", "30 minutes"],
    ans: 1,
  },
  "airport-a1x-pet": {
    q: "What does the staff member check?",
    opts: ["The dog's vaccination", "The carrier size", "The flight ticket", "The dog's weight"],
    ans: 1,
  },
  "airport-a1x-fragile": {
    q: "What does the staff member do for the bag?",
    opts: ["Weighs it again", "Puts a fragile sticker on it", "Opens it to inspect", "Refuses to check it"],
    ans: 1,
  },
  "airport-a1x-lounge": {
    q: "What floor is the lounge on?",
    opts: ["First floor", "Second floor", "Third floor", "Fourth floor"],
    ans: 2,
  },
  "airport-a1x-meal": {
    q: "What does the passenger choose to drink?",
    opts: ["Juice", "Coffee", "Water", "Tea"],
    ans: 2,
  },
  "airport-a1x-lostpass": {
    q: "What does the traveler show instead of the boarding pass?",
    opts: ["A passport", "A credit card", "An ID card", "A phone screenshot"],
    ans: 0,
  },
  "airport-a1x-arrival": {
    q: "Which exit is the pickup point?",
    opts: ["Exit 1", "Exit 2", "Exit 3", "Exit 5"],
    ans: 0,
  },
  "airport-a1x-taxfree": {
    q: "What counter number is the tax refund desk?",
    opts: ["Counter 10", "Counter 15", "Counter 20", "Counter 25"],
    ans: 2,
  },
  "airport-a1x-charge": {
    q: "Where is the phone charger located?",
    opts: ["Next to the chairs", "By the entrance", "Near the restroom", "At the food court"],
    ans: 0,
  },
  "airport-a1x-elevator": {
    q: "Which direction is the elevator?",
    opts: ["Straight ahead", "To the right", "To the left", "Downstairs"],
    ans: 2,
  },
  "airport-a1x-luggage-tag": {
    q: "What does the traveler write on the bag?",
    opts: ["Phone number", "Flight number", "Their name", "Address"],
    ans: 2,
  },
  "airport-a2x-scale-heavy": {
    q: "How many kilos over the limit is the bag?",
    opts: ["1 kilo", "2 kilos", "3 kilos", "5 kilos"],
    ans: 2,
  },
  "airport-a2x-lounge-buy": {
    q: "How much is the lounge day pass?",
    opts: ["10,000 won", "20,000 won", "30,000 won", "50,000 won"],
    ans: 2,
  },
  "airport-a2x-minor": {
    q: "Who will take the child to the gate?",
    opts: ["The parent", "Airline staff", "A security guard", "The pilot"],
    ans: 1,
  },
  "airport-a2x-pet-cabin": {
    q: "What does the staff check for the cat?",
    opts: ["Vaccination record", "The carrier", "The ticket", "The cat's age"],
    ans: 1,
  },
  "airport-a2x-exchange-rate": {
    q: "How much does the traveler exchange?",
    opts: ["50 dollars", "100 dollars", "200 dollars", "300 dollars"],
    ans: 1,
  },
  "airport-a2x-gate-question": {
    q: "What gate did it change to?",
    opts: ["Gate 15", "Gate 25", "Gate 35", "Gate 45"],
    ans: 2,
  },
  "airport-a2x-rebook": {
    q: "When does the new flight leave?",
    opts: ["Morning", "Noon", "3 p.m.", "Evening"],
    ans: 2,
  },
  "airport-a2x-fragile-fee": {
    q: "How much does special packaging cost?",
    opts: ["About 2,000 won", "About 5,000 won", "About 10,000 won", "It's free"],
    ans: 1,
  },
  "airport-a2x-arrival-sign": {
    q: "Where can the traveler get paper for a sign?",
    opts: ["The information desk", "A kiosk", "The lounge", "The exchange counter"],
    ans: 1,
  },
  "airport-a2x-charger-borrow": {
    q: "When should the charger be returned?",
    opts: ["Within an hour", "Before boarding", "After landing", "The next day"],
    ans: 1,
  },
  "airport-a2x-meal-special": {
    q: "What meal does the traveler request?",
    opts: ["Vegetarian", "Kosher", "Gluten-free", "Low-sodium"],
    ans: 0,
  },
  "airport-a2x-lostpass-reissue": {
    q: "What flight number does the traveler give?",
    opts: ["KE101", "KE201", "KE301", "KE501"],
    ans: 1,
  },
  "airport-a2x-wheelchair-time": {
    q: "How early should they return for the wheelchair?",
    opts: ["30 minutes before", "1 hour before", "2 hours before", "Right at boarding"],
    ans: 1,
  },
  "airport-a2x-cart-return": {
    q: "What does the traveler get back when returning the cart?",
    opts: ["Nothing", "A coin", "A receipt", "A ticket"],
    ans: 1,
  },
  "airport-a2x-taxfree-form": {
    q: "What two things does the traveler write on the form?",
    opts: ["Name and address", "Passport number and card number", "Flight number and date", "Phone number and email"],
    ans: 1,
  },
  "airport-b1x-taxfree-negotiate": {
    q: "How does the traveler try to avoid the extra fee?",
    opts: ["Paying by card", "Splitting items into another bag", "Leaving items behind", "Arguing with staff"],
    ans: 1,
  },
  "airport-b1x-lounge-guest": {
    q: "How many guests can the premium card holder bring free?",
    opts: ["None", "One", "Two", "Unlimited"],
    ans: 1,
  },
  "airport-b1x-minor-pickup": {
    q: "Who is picking up the child at the destination?",
    opts: ["Her mother", "Her grandmother", "Her uncle", "A family friend"],
    ans: 2,
  },
  "airport-b1x-pet-vaccine": {
    q: "What does the traveler show as proof instead of the paper certificate?",
    opts: ["A printed copy", "A photo on their phone", "An email", "Nothing"],
    ans: 1,
  },
  "airport-b1x-exchange-large": {
    q: "How much is the exchange fee?",
    opts: ["About 1 percent", "About 2 percent", "About 5 percent", "There's no fee"],
    ans: 1,
  },
  "airport-b1x-rebook-hotel": {
    q: "How far is the hotel from the airport?",
    opts: ["Walking distance", "10-minute shuttle ride", "30-minute drive", "It's downtown"],
    ans: 1,
  },
  "airport-b1x-lost-belt": {
    q: "Where did the traveler lose the belt?",
    opts: ["At the gate", "In the lounge", "At the security tray", "At check-in"],
    ans: 2,
  },
  "airport-b1x-arrival-late": {
    q: "How soon does the driver arrive?",
    opts: ["5 minutes", "10 minutes", "20 minutes", "30 minutes"],
    ans: 1,
  },
  "airport-b1x-gate-far": {
    q: "How does the traveler get to the new gate?",
    opts: ["Walking", "By shuttle", "By taxi", "By train"],
    ans: 1,
  },
  "airport-b1x-fragile-refuse": {
    q: "Why won't the airline check the pottery as baggage?",
    opts: ["It's too heavy", "It's too fragile for their policy", "It's oversized", "It's not allowed at all"],
    ans: 1,
  },
  "airport-b1x-meal-allergy": {
    q: "What allergy does the traveler have?",
    opts: ["Shellfish", "Dairy", "Peanut", "Gluten"],
    ans: 2,
  },
  "airport-b1x-lounge-full": {
    q: "How long is the estimated wait for the lounge?",
    opts: ["5 minutes", "10 minutes", "20 minutes", "1 hour"],
    ans: 2,
  },
  "airport-b1x-cart-crowded": {
    q: "Why are there no carts available?",
    opts: ["They are all broken", "It's been busy this morning", "The airport ran out of carts", "They're being repaired"],
    ans: 1,
  },
  "airport-b1x-lounge-time": {
    q: "What can the traveler reserve in the lounge?",
    opts: ["A private room", "A shower room", "A meeting room", "A nap pod"],
    ans: 1,
  },
  "airport-b1x-meal-vegetarian-limited": {
    q: "What does the flight attendant offer instead?",
    opts: ["Chicken and rice", "Fruit and salad", "Bread and soup", "Nothing at all"],
    ans: 1,
  },
  "airport-b1x-exchange-closed": {
    q: "How much does the traveler exchange?",
    opts: ["100 dollars", "200 dollars", "300 dollars", "500 dollars"],
    ans: 2,
  },
  "airport-b2x-cart-broken": {
    q: "What's wrong with the cart?",
    opts: ["It's too small", "A wheel is broken", "It's missing a handle", "It's already in use"],
    ans: 1,
  },
  "airport-b2x-taxfree-deadline": {
    q: "What is the tax refund time limit after purchase?",
    opts: ["1 month", "6 weeks", "3 months", "6 months"],
    ans: 2,
  },
  "airport-b2x-pet-weather": {
    q: "Why might the pet not be allowed to fly today?",
    opts: ["Missing paperwork", "The carrier is too small", "High temperature safety concern", "The pet is too large"],
    ans: 2,
  },
  "airport-b2x-exchange-fake": {
    q: "What does the staff member do with the unrecognized bill?",
    opts: ["Exchanges it anyway", "Excludes it and exchanges the rest", "Refuses the entire transaction", "Calls the police"],
    ans: 1,
  },
  "airport-b2x-rebook-connection": {
    q: "What does the staff offer to help with the hotel?",
    opts: ["A refund", "Contacting the hotel for late check-in", "A free hotel room", "Nothing, it's not their problem"],
    ans: 1,
  },
  "airport-b2x-lostbelt-claim": {
    q: "Which checkpoint does the traveler think they lost the watch at?",
    opts: ["Checkpoint 1", "Checkpoint 2", "Checkpoint 3", "Checkpoint 4"],
    ans: 2,
  },
  "airport-b2x-minor-late-pickup": {
    q: "What is the guardian's relationship to the child?",
    opts: ["Father", "Uncle", "Grandfather", "Family friend"],
    ans: 1,
  },
  "airport-b2x-gate-shuttle-miss": {
    q: "How does the staff help the traveler who missed the shuttle?",
    opts: ["Calls a taxi", "Contacts the gate in advance", "Gives a refund", "Rebooks the flight"],
    ans: 1,
  },
  "airport-b2x-fragile-damaged": {
    q: "What does the staff ask the traveler to do?",
    opts: ["Buy a new item", "File a damage report", "Contact the airline later", "Nothing can be done"],
    ans: 1,
  },
  "airport-b2x-taxfree-electronics": {
    q: "Why does the traveler need to visit the customs counter?",
    opts: ["To pay a tax", "For a physical inspection of electronics", "To get a new receipt", "To recheck luggage"],
    ans: 1,
  },
  "airport-b2x-scale-dispute": {
    q: "What does the staff offer to resolve the dispute?",
    opts: ["A discount on the fee", "Weighing it on another scale", "Ignoring the difference", "Calling a manager"],
    ans: 1,
  },
  "airport-b2x-arrival-nowifi": {
    q: "What does the staff member offer the traveler?",
    opts: ["Free wifi password", "To borrow a phone", "To call the driver themselves", "Directions to the wifi zone only"],
    ans: 1,
  },
  "airport-b2x-lounge-noshow": {
    q: "What does the staff member say is causing the problem?",
    opts: ["An expired card", "A system error on their side", "The lounge is closed", "The card was reported lost"],
    ans: 1,
  },
  "airport-b2x-wheelchair-mismatch": {
    q: "What does the traveler show to prove the request was made?",
    opts: ["A phone call log", "A confirmation email", "A printed receipt", "A booking reference number"],
    ans: 1,
  },
  "airport-b2x-pet-carrier-size": {
    q: "By how much is the carrier oversized?",
    opts: ["1 centimeter", "2 centimeters", "5 centimeters", "10 centimeters"],
    ans: 1,
  },
  "airport-b2x-charger-not-returned": {
    q: "Where was the portable charger the whole time?",
    opts: ["Lost", "In the traveler's bag", "Left at the counter", "Given to another passenger"],
    ans: 1,
  },
};
