import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Airport situation C1/C2 expansion round 2 (2026-08): completes advanced coverage to 20/level.
export const AIRPORT_C2_EXPANSION: Dialogue[] = [
  {
    id: "airport-c1z-offset",
    situationKey: "airport",
    level: "C1",
    title: "Debating carbon offset credibility",
    lines: [
      { speaker: "민주", kr: "체크인할 때 탄소 상쇄 옵션 봤어? 요즘 항공사마다 다 붙어 있더라.", en: "Did you see the carbon offset option at check-in? Every airline seems to have it now." },
      { speaker: "태석", kr: "봤는데 결제는 안 했어. 솔직히 그 돈이 어디로 가는지 믿음이 안 가서.", en: "I saw it but didn't pay. Honestly I don't trust where that money actually goes." },
      { speaker: "민주", kr: "나무 심기나 재생에너지 사업에 투자한다고는 하던데, 왜 못 미더워?", en: "They say it goes to tree planting or renewable energy projects — why don't you trust it?" },
      { speaker: "태석", kr: "이미 심어질 예정이었던 나무를 자기네 상쇄 실적으로 둔갑시키는 사례가 여럿 보고됐잖아. 이른바 '추가성' 문제.", en: "There have been several reported cases of trees that were already going to be planted anyway getting rebranded as their offset results. The so-called 'additionality' problem." },
      { speaker: "민주", kr: "그건 나도 들었어. 그래도 아예 안 하는 것보단 나은 거 아닐까?", en: "I've heard of that too. But isn't doing something better than nothing at all?" },
      { speaker: "태석", kr: "오히려 역효과일 수도 있어. 돈만 내면 죄책감이 사라지니까 항공 수요 자체를 줄이려는 압박이 약해지는 거지.", en: "It could actually backfire. Once you pay and the guilt disappears, the pressure to actually reduce air travel demand weakens." },
      { speaker: "민주", kr: "그럼 대안은 뭔데? 아예 비행기를 안 탈 수도 없잖아.", en: "So what's the alternative then? It's not like we can just stop flying entirely." },
      { speaker: "태석", kr: "제3자 검증 기관이 인증한 상쇄 프로그램을 골라서 쓰거나, 아니면 항공사가 아니라 직접 검증된 환경 단체에 기부하는 게 낫다고 봐.", en: "I think it's better to choose offset programs certified by third-party verification bodies, or donate directly to a vetted environmental group instead of through the airline." },
      { speaker: "민주", kr: "결국 소비자가 일일이 검증해야 한다는 거네. 피곤하긴 하다.", en: "So in the end the consumer has to verify everything themselves. That's exhausting." },
    ],
  },
  {
    id: "airport-c1z-biophilic",
    situationKey: "airport",
    level: "C1",
    title: "An airport designer on biophilic trends",
    lines: [
      { speaker: "기자", kr: "최근 지은 터미널들을 보면 실내에 나무와 폭포까지 있던데, 이런 설계 흐름은 왜 생긴 건가요?", en: "Recent terminals even have indoor trees and waterfalls — why has this design trend emerged?" },
      { speaker: "건축가", kr: "이용객들이 공항에서 느끼는 스트레스 지수가 상당히 높다는 연구 결과 때문입니다. 자연 요소가 그 수치를 낮춘다는 게 입증됐거든요.", en: "It's because of research showing that travelers' stress levels at airports are quite high. It's been demonstrated that natural elements lower those numbers." },
      { speaker: "기자", kr: "단순히 보기 좋으라고 넣는 게 아니라 심리적 효과를 노린 거군요.", en: "So it's not just for looks, it's aimed at a psychological effect." },
      { speaker: "건축가", kr: "맞습니다. 천장 채광부터 실내 식물까지, 이걸 '생체 친화적 설계'라고 부르는데 대기 시간의 체감을 실제보다 짧게 만드는 효과가 있어요.", en: "Exactly. From skylights to indoor plants, we call this 'biophilic design,' and it has the effect of making waiting time feel shorter than it actually is." },
      { speaker: "기자", kr: "하지만 유지비가 만만치 않을 것 같은데요. 그 비용은 결국 이용료에 반영되는 거 아닌가요?", en: "But maintenance costs must be considerable. Doesn't that cost ultimately get reflected in usage fees?" },
      { speaker: "건축가", kr: "초기 투자는 크지만, 승객 체류 시간이 늘면서 상업 시설 매출이 함께 오르기 때문에 장기적으로는 상쇄된다는 분석이 많습니다.", en: "The initial investment is large, but many analyses show it's offset in the long run because as passenger dwell time increases, retail revenue rises along with it." },
      { speaker: "기자", kr: "결국 미학과 상업성이 맞물려 있는 설계라는 거네요.", en: "So it's a design where aesthetics and commercial interest are intertwined." },
      { speaker: "건축가", kr: "부정할 수는 없죠. 다만 그 결과로 승객이 실제로 덜 불안하고 덜 지친 상태로 비행기에 오른다면, 저는 의미 있는 설계라고 생각합니다.", en: "I can't deny that. But if the result is that passengers actually board their flight less anxious and less exhausted, I think it's meaningful design." },
    ],
  },
  {
    id: "airport-c1z-flightshame",
    situationKey: "airport",
    level: "C1",
    title: "Two academics debating 'flight shame'",
    lines: [
      { speaker: "교수A", kr: "'플라이트 셰임' 운동이 유럽에서 시작해서 한국까지 번지고 있는데, 실제로 항공 수요를 줄이는 효과가 있다고 보세요?", en: "The 'flight shame' movement started in Europe and has spread to Korea — do you think it's actually reducing air travel demand?" },
      { speaker: "교수B", kr: "일부 국가에서는 단거리 노선 이용률이 눈에 띄게 줄었다는 통계가 있긴 합니다. 다만 그게 죄책감 때문인지 철도 대안이 좋아져서인지는 분리해서 봐야 해요.", en: "There are statistics showing a noticeable drop in short-haul route usage in some countries. But we need to separate whether that's due to guilt or because rail alternatives improved." },
      { speaker: "교수A", kr: "저는 개인의 도덕적 선택에 호소하는 방식 자체에 회의적입니다. 항공업 배출량 대부분은 개인 여가 여행이 아니라 화물이나 비즈니스 수요에서 나오잖아요.", en: "I'm skeptical of the approach itself of appealing to individual moral choice. Most aviation emissions come from cargo or business demand, not personal leisure travel." },
      { speaker: "교수B", kr: "그건 통계상 논쟁의 여지가 있어요. 국제선 여객 수요가 배출량 증가의 주된 축이라는 IATA 자료도 있습니다.", en: "That's statistically debatable. There's also IATA data showing that international passenger demand is the main driver of the emissions increase." },
      { speaker: "교수A", kr: "설령 그렇다 해도, 개인에게 죄책감을 지우는 담론은 구조적 문제, 그러니까 연료세 면제나 보조금 같은 걸 가리는 부작용이 있다고 봐요.", en: "Even if that's true, I think discourse that places guilt on the individual has the side effect of obscuring structural issues — like fuel tax exemptions or subsidies." },
      { speaker: "교수B", kr: "동의합니다. 다만 대중의 인식 전환이 결국 정책 압박으로 이어진다는 점에서 완전히 무의미한 운동은 아니라고 봐요.", en: "I agree. Still, I don't think it's a completely meaningless movement, since shifting public awareness eventually translates into policy pressure." },
      { speaker: "교수A", kr: "결국 개인의 선택과 제도적 개혁이 같이 가야 한다는 결론이네요.", en: "So the conclusion is that individual choice and institutional reform need to go hand in hand." },
      { speaker: "교수B", kr: "네, 어느 한쪽만으로는 배출량 문제를 해결할 수 없다고 봅니다.", en: "Right, I don't think either one alone can solve the emissions problem." },
    ],
  },
  {
    id: "airport-c1z-pilotunion",
    situationKey: "airport",
    level: "C1",
    title: "Pilots' union and management negotiation snippet",
    lines: [
      { speaker: "노조대표", kr: "이번 교섭에서 저희가 요구하는 핵심은 피로 누적을 막기 위한 최소 휴식 시간 확대입니다.", en: "The core demand we're making in this negotiation is expanding the minimum rest time to prevent fatigue buildup." },
      { speaker: "인사임원", kr: "휴식 시간을 늘리면 운항 편수가 줄어들고, 그건 곧 인력 추가 채용 없이는 불가능한 요구입니다.", en: "Extending rest time reduces the number of flights operated, and that's a demand that's impossible without additional hiring." },
      { speaker: "노조대표", kr: "그럼 인력을 늘리면 될 일 아닙니까. 지금 기장들의 월평균 비행 시간이 법정 상한선에 근접해 있는 상태예요.", en: "Then just hire more people. Right now captains' average monthly flight hours are close to the legal upper limit." },
      { speaker: "인사임원", kr: "인건비 증가는 결국 항공권 가격 인상으로 이어질 수밖에 없습니다. 소비자 부담도 고려해야죠.", en: "An increase in labor costs will inevitably lead to higher ticket prices. We have to consider the burden on consumers too." },
      { speaker: "노조대표", kr: "피로한 조종사가 조종석에 앉는 것과 항공권이 몇천 원 오르는 것, 어느 쪽이 더 중대한 문제인지 되묻고 싶습니다.", en: "I'd like to ask which is the more serious problem — a fatigued pilot sitting in the cockpit, or ticket prices rising by a few thousand won." },
      { speaker: "인사임원", kr: "안전을 경시하는 게 아닙니다. 다만 경영 지속 가능성도 함께 고려해야 한다는 겁니다.", en: "We're not dismissing safety. It's just that we also need to consider the sustainability of the business." },
      { speaker: "노조대표", kr: "저희는 시뮬레이션 데이터를 근거로 제시했습니다. 이번 주 안에 구체적인 안을 받고 싶습니다.", en: "We've presented simulation data as evidence. We'd like to receive a concrete proposal within this week." },
      { speaker: "인사임원", kr: "검토해서 다음 교섭 자리에서 수정안을 가져오겠습니다.", en: "We'll review it and bring a revised proposal to the next negotiation session." },
    ],
  },
  {
    id: "airport-c1z-baggagescandal",
    situationKey: "airport",
    level: "C1",
    title: "A journalist exposing a baggage-handling scandal",
    lines: [
      { speaker: "기자", kr: "수하물 파손율이 업계 평균의 세 배에 달한다는 내부 문서를 입수했습니다. 이에 대해 어떻게 설명하시겠습니까?", en: "We've obtained internal documents showing your baggage damage rate is three times the industry average. How do you explain this?" },
      { speaker: "홍보팀장", kr: "그 문서의 출처와 표본 기간을 먼저 확인해야 할 것 같습니다. 저희 공식 통계와는 상당히 차이가 있어서요.", en: "I think we first need to verify the source and sampling period of that document. It differs considerably from our official statistics." },
      { speaker: "기자", kr: "출처는 밝힐 수 없지만, 최근 6개월간 접수된 파손 신고 건수를 다룬 자료입니다. 통계를 축소 보고한 정황이 있다는 제보도 있었고요.", en: "I can't disclose the source, but it's data covering damage reports filed over the past six months. There was also a tip suggesting statistics were underreported." },
      { speaker: "홍보팀장", kr: "저희는 모든 신고 건을 규정에 따라 접수하고 처리하고 있습니다. 축소 보고라는 주장은 근거가 확인되지 않았습니다.", en: "We accept and process every reported case according to regulations. The claim of underreporting hasn't been verified." },
      { speaker: "기자", kr: "그렇다면 자체 감사를 통해 공개 검증을 받을 의향이 있으신가요?", en: "Then are you willing to undergo public verification through an internal audit?" },
      { speaker: "홍보팀장", kr: "감사 결과 공개 여부는 법무팀과 협의해야 할 사안입니다. 지금 이 자리에서 확답드리기는 어렵습니다.", en: "Whether to disclose audit results is a matter that needs to be discussed with the legal team. I can't give a definite answer here right now." },
      { speaker: "기자", kr: "협의는 언제까지 마무리될 예정입니까? 소비자들은 지금 당장 답을 원하고 있습니다.", en: "By when will that discussion be concluded? Consumers want an answer right now." },
      { speaker: "홍보팀장", kr: "이번 주 안으로 공식 입장을 정리해서 다시 연락드리겠습니다.", en: "We'll put together an official position within this week and get back to you." },
      { speaker: "기자", kr: "그 답변, 반드시 기사로 남기겠습니다.", en: "I will make sure that response goes on the record." },
    ],
  },
  {
    id: "airport-c1z-visadiplomacy",
    situationKey: "airport",
    level: "C1",
    title: "Debating visa-free reciprocity diplomacy",
    lines: [
      { speaker: "연구원A", kr: "이번에 우리 정부가 그 나라와 무비자 협정을 체결했잖아요. 관광 활성화 측면에서는 긍정적이지 않나요?", en: "Our government just signed a visa-waiver agreement with that country. Isn't it positive from a tourism standpoint?" },
      { speaker: "연구원B", kr: "숫자로만 보면 그렇죠. 그런데 상대국이 자국민 대비 우리 국민에게만 혜택을 주는 비대칭 협정이라 상호주의 원칙에 어긋난다는 지적도 있어요.", en: "In terms of numbers, sure. But there's criticism that it's an asymmetric agreement benefiting only our citizens relative to the other country's own, which violates the principle of reciprocity." },
      { speaker: "연구원A", kr: "완전한 상호주의를 고집하면 협상 자체가 성사되기 어려운 경우도 많잖아요. 단계적 접근이 현실적이지 않을까요?", en: "Insisting on full reciprocity often makes it hard to even reach an agreement in the first place. Wouldn't a phased approach be more realistic?" },
      { speaker: "연구원B", kr: "문제는 그 '단계적'이라는 말이 무기한 유예로 이어지는 사례가 많다는 거예요. 국내 여론도 형평성 문제로 비판적이고요.", en: "The problem is that 'phased' often turns into an indefinite postponement in practice. Domestic public opinion is also critical over the fairness issue." },
      { speaker: "연구원A", kr: "그래도 외교적으로는 선제적 개방이 협상력을 높이는 카드가 될 수 있다는 시각도 있습니다.", en: "Still, there's also a view that diplomatically, preemptive openness can be a card that increases bargaining power." },
      { speaker: "연구원B", kr: "그 카드가 실제로 상대국의 상응 조치를 끌어냈는지 검증할 필요가 있어요. 지난 사례들을 보면 흐지부지된 경우가 적지 않았거든요.", en: "We need to verify whether that card has actually drawn out reciprocal measures from the other country. Looking at past cases, many ended up fizzling out." },
      { speaker: "연구원A", kr: "결국 정량적 평가 지표를 만들어서 일정 기간 뒤 재검토하는 조항이 필요하다는 거네요.", en: "So in the end we need a clause that creates quantitative evaluation metrics and mandates a review after a set period." },
      { speaker: "연구원B", kr: "네, 그런 안전장치 없이는 이런 협정이 정치적 상징에 그칠 위험이 커요.", en: "Right, without such a safeguard, there's a high risk these agreements amount to nothing more than political symbolism." },
    ],
  },
  {
    id: "airport-c1z-hiddencity",
    situationKey: "airport",
    level: "C1",
    title: "Travelers debating 'hidden city' ticketing ethics",
    lines: [
      { speaker: "지훈", kr: "이번에 나 인천에서 도쿄 경유해서 서울 오는 표를 샀는데, 도쿄에서 내리고 서울행은 안 탈 거야. 그게 더 싸더라고.", en: "This time I bought a ticket from Incheon connecting through Tokyo to Seoul, but I'm getting off at Tokyo and not taking the Seoul leg. It was cheaper that way." },
      { speaker: "은서", kr: "그거 '히든 시티 티케팅'이잖아. 나도 들어봤는데, 그게 항공사 약관 위반 아니야?", en: "That's 'hidden city ticketing,' right? I've heard of it — isn't that a violation of the airline's terms?" },
      { speaker: "지훈", kr: "약관 위반이긴 한데, 소비자가 정당하게 지불한 가격 안에서 선택하는 거라 도덕적으로 문제될 건 없다고 봐.", en: "It does violate the terms, but I think it's morally fine since it's a choice made within the price the consumer legitimately paid." },
      { speaker: "은서", kr: "그래도 그 좌석 하나 때문에 다른 승객이 대기자 명단에서 못 타는 경우도 생기잖아. 완전히 무해한 건 아니지.", en: "But that seat can end up meaning another passenger on the waitlist can't get on. It's not entirely harmless." },
      { speaker: "지훈", kr: "그건 항공사가 초과 예약을 상습적으로 하니까 생기는 문제지, 내 개인의 선택 탓으로 돌리긴 어렵지 않을까.", en: "That's a problem caused by the airline habitually overbooking — I don't think it's fair to blame it on my individual choice." },
      { speaker: "은서", kr: "위탁 수하물을 못 부친다는 것도 단점이잖아. 걸리면 마일리지 계정 정지될 수도 있고.", en: "Not being able to check baggage is also a downside. And if you get caught, your mileage account could get suspended." },
      { speaker: "지훈", kr: "위험을 감수하는 것도 결국 내 몫이니까, 그 정도는 감안하고 하는 거야.", en: "Taking on that risk is ultimately my own responsibility, so I factor that in when I do it." },
      { speaker: "은서", kr: "논리는 이해하는데, 나라면 걸렸을 때의 리스크가 너무 커서 안 할 것 같아.", en: "I understand the logic, but personally the risk if I got caught feels too big, so I don't think I'd do it." },
    ],
  },
  {
    id: "airport-c1z-chaplain",
    situationKey: "airport",
    level: "C1",
    title: "An airport chaplain reflecting on grief and farewells",
    lines: [
      { speaker: "기자", kr: "공항에 상주하는 목사님이라니 특이한 직업 같습니다. 주로 어떤 분들을 만나시나요?", en: "A chaplain stationed at the airport seems like an unusual job. What kind of people do you mostly meet?" },
      { speaker: "목사", kr: "장거리 비행 전 갑자기 불안 발작을 겪는 분들, 가족의 부고를 듣고 급히 출국하려는 분들, 정말 다양합니다.", en: "People who suddenly have anxiety attacks before a long flight, people rushing to leave the country after hearing of a family member's death — it's really varied." },
      { speaker: "기자", kr: "슬픔이 응축되는 공간이라는 생각이 드네요. 특별히 기억에 남는 순간이 있으신가요?", en: "It feels like a space where grief becomes concentrated. Is there a particular moment that stays with you?" },
      { speaker: "목사", kr: "부친상 소식을 듣고 탑승구 앞에서 주저앉으신 분이 계셨어요. 그저 옆에 앉아 손을 잡아드린 것밖에 못 했는데, 나중에 편지를 보내주셨죠.", en: "There was a person who collapsed in front of the gate after hearing news of their father's death. All I could do was sit beside them and hold their hand, but later they sent me a letter." },
      { speaker: "기자", kr: "공항이라는 공간이 왜 그런 감정을 유독 증폭시키는 걸까요?", en: "Why do you think a place like the airport particularly amplifies emotions like that?" },
      { speaker: "목사", kr: "이별과 재회가 동시에 일어나는 유일한 장소니까요. 시간이 촉박하고, 다시 만날 기약이 불확실하다는 점도 크고요.", en: "Because it's the one place where farewells and reunions happen simultaneously. The fact that time is short and there's uncertainty about when you'll meet again also matters a lot." },
      { speaker: "기자", kr: "종교가 다른 분들께도 도움을 주시는지 궁금합니다.", en: "I'm curious whether you also help people of different religions." },
      { speaker: "목사", kr: "물론입니다. 제가 하는 일은 특정 교리를 전하는 게 아니라 그 순간 곁에 있어 드리는 것뿐이에요.", en: "Of course. What I do isn't to preach a particular doctrine, but simply to be present beside someone in that moment." },
    ],
  },
  {
    id: "airport-c1z-biometricprivacy",
    situationKey: "airport",
    level: "C1",
    title: "A tech ethicist on biometric data privacy",
    lines: [
      { speaker: "진행자", kr: "공항에서 안면 인식으로 탑승 수속을 끝내는 시대가 왔는데, 이게 프라이버시 측면에서는 어떤 문제가 있을까요?", en: "We've reached an era where boarding can be completed through facial recognition at the airport — what are the privacy issues with this?" },
      { speaker: "윤리학자", kr: "가장 큰 문제는 그 생체 정보가 얼마나 오래 보관되고, 누구와 공유되는지 승객이 정확히 알기 어렵다는 겁니다.", en: "The biggest problem is that it's hard for passengers to know exactly how long that biometric data is stored and who it's shared with." },
      { speaker: "진행자", kr: "항공사는 보안과 편의를 위해서라고 설명하는데, 그 명분만으로 충분한가요?", en: "Airlines explain it's for security and convenience — is that justification alone sufficient?" },
      { speaker: "윤리학자", kr: "명분 자체는 타당합니다. 다만 편의와 안전을 이유로 동의 절차가 형식적으로 흐르는 경향이 있다는 게 문제예요.", en: "The justification itself is valid. The problem is that the consent process tends to become a mere formality in the name of convenience and safety." },
      { speaker: "진행자", kr: "안면 인식을 거부할 수 있는 선택권이 실제로 보장되나요?", en: "Is the option to opt out of facial recognition actually guaranteed in practice?" },
      { speaker: "윤리학자", kr: "이론적으로는 있지만, 거부하면 줄이 훨씬 길어지고 절차가 번거로워지니 사실상 압박이 되는 경우가 많습니다.", en: "Theoretically it exists, but if you opt out the line becomes much longer and the process more cumbersome, so it effectively becomes a pressure in many cases." },
      { speaker: "진행자", kr: "제도적으로 어떤 보완이 필요하다고 보십니까?", en: "What institutional supplements do you think are needed?" },
      { speaker: "윤리학자", kr: "수집된 데이터의 삭제 시점을 명문화하고, 제3자 제공 여부를 정기적으로 감사받는 독립 기구가 필요하다고 봅니다.", en: "I think we need to codify the deletion timeline for collected data, and have an independent body that regularly audits whether it's shared with third parties." },
    ],
  },
  {
    id: "airport-c2z-hubidentity",
    situationKey: "airport",
    level: "C2",
    title: "A historian on how an airport shaped a city",
    lines: [
      { speaker: "진행자", kr: "이 도시가 지금의 국제적 위상을 갖게 된 데에 공항이 결정적 역할을 했다고 하셨는데, 구체적으로 어떤 계기였나요?", en: "You've said the airport played a decisive role in this city gaining its current international standing — what specifically was the turning point?" },
      { speaker: "역사학자", kr: "1960년대 말 정기 국제선이 취항하면서 도시가 단순한 지역 거점에서 국제 물류와 인적 교류의 관문으로 재편되기 시작했습니다.", en: "When regular international routes began service in the late 1960s, the city started being reorganized from a mere regional hub into a gateway for international logistics and human exchange." },
      { speaker: "진행자", kr: "당시 시민들은 그 변화를 긍정적으로만 받아들였나요?", en: "Did the citizens at the time embrace that change entirely positively?" },
      { speaker: "역사학자", kr: "그렇지만은 않았습니다. 공항 확장으로 인근 마을이 통째로 이주해야 했고, 소음 공해에 대한 반발도 상당했어요. 발전의 이면에는 늘 희생이 있었죠.", en: "Not entirely. The airport expansion required entire neighboring villages to relocate, and there was considerable backlash over noise pollution. Behind every advance, there was always a sacrifice." },
      { speaker: "진행자", kr: "그럼에도 결과적으로는 도시 정체성 자체가 그 공항을 중심으로 재구성됐다고 보시는 거군요.", en: "Even so, you see the city's identity itself as ultimately having been reconstructed around that airport." },
      { speaker: "역사학자", kr: "네, 관광, 무역, 심지어 시민들의 자기 인식까지도 '세계와 연결된 도시'라는 서사에 맞춰졌습니다. 공항이 단순한 시설을 넘어 도시의 상징이 된 겁니다.", en: "Yes, tourism, trade, and even the citizens' own self-perception came to align with the narrative of being 'a city connected to the world.' The airport became more than mere infrastructure — it became the city's symbol." },
      { speaker: "진행자", kr: "요즘 신공항 건설을 두고도 비슷한 논쟁이 반복되는 걸 보면, 역사가 되풀이되는 느낌이네요.", en: "Watching similar debates recur around new airport construction these days, it feels like history repeating itself." },
      { speaker: "역사학자", kr: "정확한 지적입니다. 다만 이번에는 환경 영향평가나 주민 참여 절차가 그때보다 훨씬 정교해졌다는 차이가 있죠.", en: "That's a precise observation. Though this time there's a difference in that environmental impact assessments and resident participation procedures have become far more sophisticated than back then." },
      { speaker: "진행자", kr: "결국 개발과 보존, 편의와 희생 사이에서 균형을 찾는 게 도시의 영원한 숙제인 것 같습니다.", en: "In the end, finding balance between development and preservation, convenience and sacrifice, seems to be a city's eternal task." },
    ],
  },
  {
    id: "airport-c2z-nightcurfew",
    situationKey: "airport",
    level: "C2",
    title: "Residents and an official debating runway noise",
    lines: [
      { speaker: "주민대표", kr: "저희 마을은 활주로 바로 아래에 있어서 이착륙 소음으로 밤잠을 설치는 날이 부지기수입니다. 방음창 지원만으로는 부족합니다.", en: "Our village is right under the runway, and there are countless nights we lose sleep to takeoff and landing noise. Soundproof window support alone isn't enough." },
      { speaker: "공항관계자", kr: "심야 운항 편수를 이미 15퍼센트 줄였고, 소음 저감 절차도 도입했습니다. 완전한 통제는 물류와 여객 수요 때문에 현실적으로 어렵습니다.", en: "We've already reduced late-night flight operations by 15 percent and introduced noise abatement procedures. Complete control is realistically difficult due to cargo and passenger demand." },
      { speaker: "주민대표", kr: "15퍼센트로 체감이 될 것 같습니까? 저희가 요구하는 건 자정부터 새벽 5시까지 완전한 운항 금지입니다.", en: "Do you think 15 percent is noticeable? What we're demanding is a complete flight ban from midnight to 5am." },
      { speaker: "공항관계자", kr: "그 시간대는 화물 노선의 절반 이상이 몰려 있는 시간입니다. 전면 금지하면 물류 업계 전체가 타격을 받습니다.", en: "That time slot is when over half of cargo routes are concentrated. A total ban would strike the entire logistics industry." },
      { speaker: "주민대표", kr: "화물기 노선은 다른 시간대로 조정할 수 있는 여지가 있지 않습니까. 사람의 건강권보다 물류 효율이 우선이라는 겁니까?", en: "Isn't there room to shift cargo routes to other time slots? Are you saying logistics efficiency takes priority over people's right to health?" },
      { speaker: "공항관계자", kr: "그런 뜻은 아닙니다. 다만 전면 조정에는 항공 슬롯 재배치와 물류사와의 계약 재협상까지 얽혀 있어 시간이 걸린다는 말씀을 드리는 겁니다.", en: "That's not what I mean. I'm just saying a full adjustment involves slot reallocation and renegotiating contracts with logistics companies, which takes time." },
      { speaker: "주민대표", kr: "저희는 이미 10년째 같은 답변을 듣고 있습니다. 이번에는 구체적인 이행 일정을 문서로 받고 싶습니다.", en: "We've been hearing the same answer for ten years now. This time we want a concrete implementation schedule in writing." },
      { speaker: "공항관계자", kr: "다음 달 지역 협의체 회의에서 단계적 감축안을 문서로 제출하겠습니다.", en: "We'll submit a phased reduction plan in writing at next month's regional consultative committee meeting." },
      { speaker: "주민대표", kr: "이번에는 지켜지길 바랍니다. 저희도 더는 물러설 곳이 없습니다.", en: "I hope it's honored this time. We have no more room left to give in either." },
    ],
  },
  {
    id: "airport-c2z-slotresale",
    situationKey: "airport",
    level: "C2",
    title: "Analysts on gray-market slot resale",
    lines: [
      { speaker: "분석가A", kr: "일부 항공사가 배정받은 슬롯을 실제로는 거의 안 쓰고, 형식적인 최소 운항만 채운 뒤 나머지 시간대를 암암리에 넘긴다는 이야기가 있던데요.", en: "There's talk that some airlines barely use their allocated slots, only meet the formal minimum operation requirement, and then quietly transfer the remaining time slots." },
      { speaker: "분석가B", kr: "이른바 '고스트 비행'이죠. 승객도 화물도 거의 없이 슬롯 유지만을 위해 띄우는 편명들이 실제로 존재합니다.", en: "The so-called 'ghost flights.' There really are flight numbers that get flown almost empty of passengers and cargo, purely to hold onto the slot." },
      { speaker: "분석가A", kr: "그게 규정상 허점을 이용한 거잖아요. 슬롯 사용률 기준을 충족만 시키면 되니까, 공정성 측면에서 심각한 문제 아닌가요?", en: "That's exploiting a loophole in the regulations. Since they just need to meet the slot usage threshold, isn't this a serious fairness issue?" },
      { speaker: "분석가B", kr: "심각하죠. 특히 탄소 배출까지 고려하면, 텅 빈 비행기를 띄우는 관행은 환경적으로도 정당화가 안 됩니다.", en: "Very serious. Especially considering carbon emissions, the practice of flying empty planes can't be justified environmentally either." },
      { speaker: "분석가A", kr: "규제 당국은 사용률 기준을 상향하거나 예외 승인 절차를 강화하는 방향으로 움직이고 있다고 들었습니다.", en: "I've heard regulatory authorities are moving toward either raising the usage threshold or tightening the exception approval process." },
      { speaker: "분석가B", kr: "다만 기준을 너무 엄격하게 하면, 신규 항공사나 소규모 노선의 진입 장벽이 오히려 높아질 수 있다는 반론도 있어요.", en: "But there's also a counterargument that if the threshold is made too strict, it could actually raise entry barriers for new airlines or small routes." },
      { speaker: "분석가A", kr: "결국 대형 항공사의 편법 사용을 막으면서도 신규 사업자를 보호하는 이중 기준이 필요하다는 거네요.", en: "So in the end, a dual standard is needed that blocks major carriers' loophole exploitation while still protecting new entrants." },
      { speaker: "분석가B", kr: "말은 쉬운데 실제로 그 경계선을 어디에 그을지가 규제 설계의 핵심 난제죠.", en: "Easy to say, but where exactly to draw that line is the core challenge in designing the regulation." },
      { speaker: "분석가A", kr: "당분간은 계속 지켜봐야 할 사안 같습니다.", en: "It seems like an issue we'll need to keep watching for the time being." },
    ],
  },
  {
    id: "airport-c2z-antitrafficking",
    situationKey: "airport",
    level: "C2",
    title: "Border officer training on trafficking indicators",
    lines: [
      { speaker: "신입직원", kr: "선배님, 인신매매 의심 징후를 판별하는 게 생각보다 훨씬 어려운 것 같습니다. 겉보기엔 그냥 가족 여행 같기도 하고요.", en: "Senior, distinguishing suspected trafficking indicators seems far harder than I expected. On the surface it can look just like a family trip." },
      { speaker: "선배직원", kr: "맞아, 그래서 단일 징후만으로 판단하면 안 돼. 동반자가 대신 대답하려 한다거나, 아이가 여권을 처음 본 듯한 반응을 보인다거나, 여러 정황을 종합해야 해.", en: "Right, that's why you can't judge based on a single indicator alone. You have to weigh multiple circumstances together — like a companion trying to answer on someone's behalf, or a child reacting as if seeing their passport for the first time." },
      { speaker: "신입직원", kr: "그런데 그런 질문을 던졌다가 실제로는 아무 문제 없는 가족한테 불쾌감을 줄 수도 있잖아요. 그 균형을 어떻게 잡으시나요?", en: "But asking those questions could end up offending a family that actually has no issue at all. How do you strike that balance?" },
      { speaker: "선배직원", kr: "질문의 태도가 중요해. 추궁하듯이 묻지 않고, 통상적인 절차의 일부인 것처럼 자연스럽게 여러 사람에게 동일한 질문을 던지는 게 핵심이야.", en: "The manner of asking matters. The key is asking the same question naturally to multiple people, as if it's a routine part of the process, rather than interrogating." },
      { speaker: "신입직원", kr: "만약 의심이 확신으로 바뀌면 그다음 절차는 어떻게 되나요?", en: "If suspicion turns into conviction, what's the next procedure?" },
      { speaker: "선배직원", kr: "즉시 체포하는 게 아니라, 별도 공간으로 안내해서 전담 상담 인력과 통역사를 배치하고 피해자 보호 절차부터 시작하는 게 원칙이야.", en: "The principle isn't immediate arrest — you guide them to a separate space, arrange dedicated counseling staff and an interpreter, and start with victim protection procedures first." },
      { speaker: "신입직원", kr: "피해자로 확인되기 전까지는 잠재적 범죄자가 아니라 보호 대상으로 접근한다는 거군요.", en: "So until confirmed as a victim, the approach treats them as someone to protect, not a potential criminal." },
      { speaker: "선배직원", kr: "그게 이 업무에서 가장 중요한 원칙이야. 판단이 틀렸을 때의 대가가 너무 크니까.", en: "That's the single most important principle in this job. Because the cost of getting the judgment wrong is far too great." },
    ],
  },
  {
    id: "airport-c2z-lostgeneration",
    situationKey: "airport",
    level: "C2",
    title: "A retired flight attendant reflecting on the golden age",
    lines: [
      { speaker: "후배", kr: "선배님은 항공사 초창기부터 근무하셨잖아요. 그때랑 지금이랑 가장 크게 달라진 게 뭐라고 느끼세요?", en: "You've worked at the airline since its early days — what do you feel is the biggest difference between then and now?" },
      { speaker: "은퇴승무원", kr: "그때는 비행 자체가 특별한 사건이었어. 승객들도 정장을 갖춰 입고 탑승했고, 승무원도 격식 있는 서비스를 제공하는 게 자부심이었지.", en: "Back then, the flight itself was a special occasion. Passengers boarded in formal attire, and it was a point of pride for crew to provide formal, dignified service." },
      { speaker: "후배", kr: "지금은 워낙 대중화됐으니 그런 특별함이 많이 사라졌겠네요.", en: "Now that it's become so mass-market, a lot of that specialness must have disappeared." },
      { speaker: "은퇴승무원", kr: "대중화 자체는 나쁘지 않다고 봐. 문제는 서비스의 본질이 '환대'에서 '효율'로 완전히 옮겨갔다는 거지. 승객 수는 늘었는데 인력은 오히려 줄었으니까.", en: "Mass-market access itself isn't a bad thing. The problem is that the essence of the service has shifted entirely from 'hospitality' to 'efficiency.' Passenger numbers grew while staffing actually decreased." },
      { speaker: "후배", kr: "그럼 요즘 승무원들은 그때보다 훨씬 더 힘든 조건에서 일하는 셈이네요.", en: "So today's crew are effectively working under far harder conditions than back then." },
      { speaker: "은퇴승무원", kr: "체력적으로도, 감정노동 측면에서도 그렇지. 다만 그 시절을 무조건 미화하고 싶진 않아. 여성 승무원에 대한 차별적 규정도 심했으니까.", en: "Both physically and in terms of emotional labor, yes. But I don't want to romanticize that era unconditionally either — discriminatory regulations against female flight attendants were severe back then too." },
      { speaker: "후배", kr: "그렇게 보면 단순히 좋았다 나빴다로 나눌 수 있는 문제는 아니네요.", en: "Looking at it that way, it's not something that can simply be divided into 'better' or 'worse.'" },
      { speaker: "은퇴승무원", kr: "맞아. 얻은 것도 있고 잃은 것도 있는 거지. 다만 승객을 하나의 인격체로 대하는 태도만큼은 시대가 바뀌어도 지켜졌으면 하는 바람이야.", en: "Exactly. Something was gained and something was lost. But my one wish is that the attitude of treating passengers as full human beings holds true no matter how the era changes." },
      { speaker: "후배", kr: "좋은 말씀 감사합니다. 저도 그 마음가짐 잊지 않고 일하겠습니다.", en: "Thank you for those words. I'll keep that mindset in mind as I work too." },
    ],
  },
  {
    id: "airport-c2z-migrationroute",
    situationKey: "airport",
    level: "C2",
    title: "Sociologists debating diaspora travel patterns",
    lines: [
      { speaker: "연구자A", kr: "명절마다 이 공항이 마비 수준으로 붐비는 걸 보면, 이주민들에게 고국행 항공권이 단순한 이동 수단 이상의 의미를 갖는 것 같아요.", en: "Seeing this airport get jam-packed to a standstill every holiday, it seems like a ticket home means more than mere transportation for migrants." },
      { speaker: "연구자B", kr: "맞습니다. 저는 그걸 '정체성 재확인 의례'라고 부르는데요, 고국을 떠난 지 오래될수록 오히려 그 상징적 무게가 커지는 경향이 있어요.", en: "Right. I call it a 'ritual of identity reaffirmation' — and the longer someone has been away from their home country, the heavier that symbolic weight tends to become." },
      { speaker: "연구자A", kr: "그런데 항공료 부담 때문에 격년으로만 가거나, 아예 포기하는 이주 노동자층도 상당하잖아요. 그 계층에게도 같은 논리가 적용될까요?", en: "But there's also a considerable class of migrant workers who can only afford to go every other year, or give it up entirely, because of airfare costs. Does the same logic apply to them?" },
      { speaker: "연구자B", kr: "오히려 더 강하게 적용됩니다. 못 가는 해에 느끼는 상실감이나 죄책감이 다음 방문을 더 필사적으로 만드는 동력이 되거든요.", en: "It applies even more strongly. The sense of loss or guilt felt in a year they can't go becomes a driving force that makes the next visit feel more desperate." },
      { speaker: "연구자A", kr: "그렇다면 저가 항공사의 확장이 이 계층의 이동권 확보에 실질적으로 기여했다고 볼 수 있을까요?", en: "Then could we say the expansion of budget airlines has substantively contributed to securing this group's mobility rights?" },
      { speaker: "연구자B", kr: "부분적으로는요. 다만 저가 항공은 대개 직항 노선을 제공하지 않아서, 시간 비용이라는 또 다른 형태의 비용이 발생한다는 한계가 있습니다.", en: "Partially. But budget airlines generally don't offer direct routes, so there's a limitation in that a different form of cost — time cost — arises instead." },
      { speaker: "연구자A", kr: "결국 경제적 접근성이 나아져도, 시간적 여유가 없는 계층에게는 여전히 장벽이 남는다는 거네요.", en: "So even as economic accessibility improves, a barrier still remains for people who don't have the luxury of time." },
      { speaker: "연구자B", kr: "네, 이동의 권리를 온전히 보장하려면 비용뿐 아니라 노동 조건까지 함께 논의돼야 한다고 봅니다.", en: "Right, I think fully guaranteeing the right to mobility requires discussing not just cost but labor conditions as well." },
      { speaker: "연구자A", kr: "다음 연구에서는 그 부분을 좀 더 파고들어야겠네요.", en: "We should dig into that part more in our next research then." },
    ],
  },
  {
    id: "airport-c2z-wildlifestrike",
    situationKey: "airport",
    level: "C2",
    title: "Wildlife management debate near a coastal runway",
    lines: [
      { speaker: "환경단체", kr: "이 활주로 인근이 철새 이동 경로와 겹치는데, 조류 충돌 방지를 이유로 서식지 자체를 훼손하는 방식은 재고돼야 합니다.", en: "This runway's vicinity overlaps with a migratory bird route, and the approach of destroying the habitat itself in the name of preventing bird strikes needs to be reconsidered." },
      { speaker: "공항안전팀", kr: "저희도 서식지를 없애자는 게 아닙니다. 다만 활주로 반경 내 조류 밀도를 낮추지 않으면 실제 사고로 이어질 위험이 있어서요.", en: "We're not trying to eliminate the habitat either. But if we don't reduce bird density within the runway radius, there's a real risk it leads to an actual accident." },
      { speaker: "환경단체", kr: "음파 퇴치기나 맹금류를 활용한 비살상 방식도 있는데, 왜 서식지 매립 같은 극단적 조치부터 검토하시는 거죠?", en: "There are non-lethal methods like sonic deterrents or falconry — why is habitat landfilling being considered as an extreme first measure?" },
      { speaker: "공항안전팀", kr: "비살상 방식은 이미 병행하고 있습니다. 그런데 번식기에는 그 효과가 현저히 떨어진다는 게 저희 데이터로 확인됐어요.", en: "We're already running non-lethal methods in parallel. But our data confirms their effectiveness drops significantly during breeding season." },
      { speaker: "환경단체", kr: "그렇다고 서식지를 훼손하면 다른 지역으로 이동한 새들이 또 다른 항로와 충돌할 위험을 그냥 옮기는 것 아닙니까?", en: "Even so, if you destroy the habitat, aren't you just shifting the risk — birds displaced to another area will collide with a different flight path instead?" },
      { speaker: "공항안전팀", kr: "일리 있는 지적입니다. 그래서 저희도 완전 매립이 아니라 서식 밀도를 분산시키는 대체 습지 조성안을 검토 중입니다.", en: "That's a fair point. That's why we're also reviewing a plan to create alternative wetlands that disperse habitat density, rather than complete landfilling." },
      { speaker: "환경단체", kr: "그 대체 습지 조성이 실제 새들에게 유효한 대안이 될지는 독립적인 생태 조사로 검증받아야 한다고 봅니다.", en: "Whether that alternative wetland creation will actually be a valid alternative for the birds needs to be verified through an independent ecological survey, I believe." },
      { speaker: "공항안전팀", kr: "동의합니다. 다음 달 제3기관 조사 결과가 나오면 그걸 토대로 다시 논의하시죠.", en: "Agreed. Once the third-party institution's survey results come out next month, let's discuss again based on that." },
      { speaker: "환경단체", kr: "그 결과가 나올 때까지 매립 관련 절차는 잠정 중단해 주시길 요청드립니다.", en: "We request that landfilling-related procedures be provisionally suspended until those results come out." },
    ],
  },
  {
    id: "airport-c2z-fuelhedging",
    situationKey: "airport",
    level: "C2",
    title: "Finance analysts on jet fuel hedging strategy",
    lines: [
      { speaker: "분석가A", kr: "지난 분기 실적을 보면 유류비 헤지 전략이 오히려 손실 요인으로 작용했더라고요. 이게 전략의 실패인가요, 아니면 시장 변동성 탓인가요?", en: "Looking at last quarter's results, the fuel hedging strategy actually functioned as a loss factor. Is this a strategic failure, or just market volatility?" },
      { speaker: "분석가B", kr: "둘 다 맞물려 있다고 봐야죠. 유가가 예상보다 급락하면서 헤지 계약이 오히려 시장가보다 비싼 가격에 묶여버린 겁니다.", en: "I think both are intertwined. As oil prices fell more sharply than expected, the hedge contracts ended up locked into prices higher than the market rate." },
      { speaker: "분석가A", kr: "그럼 애초에 헤지 비율을 그렇게 높게 잡은 것 자체가 판단 미스 아니었을까요?", en: "Then wasn't setting the hedge ratio that high in the first place itself a misjudgment?" },
      { speaker: "분석가B", kr: "위험 관리 측면에서는 합리적인 선택이었어요. 유가 급등 시나리오에 대비한 보험 성격이니까, 결과만 보고 비판하는 건 사후 확증 편향일 수 있습니다.", en: "From a risk management standpoint, it was a rational choice. It's insurance-like protection against a scenario of sharp oil price spikes, so criticizing it purely based on the outcome could be hindsight bias." },
      { speaker: "분석가A", kr: "그건 인정하지만, 헤지 비율을 시장 상황에 따라 좀 더 유연하게 조정할 여지는 없었을까요?", en: "I grant that, but wasn't there room to adjust the hedge ratio more flexibly according to market conditions?" },
      { speaker: "분석가B", kr: "이론적으로는 가능하지만, 잦은 조정은 오히려 거래 비용과 심리적 노이즈를 키워서 장기 전략의 일관성을 해칠 수 있어요.", en: "Theoretically possible, but frequent adjustments can instead increase transaction costs and psychological noise, undermining the consistency of the long-term strategy." },
      { speaker: "분석가A", kr: "결국 투자자들에게는 이 손실을 단기 실적 악화가 아니라 장기 리스크 관리 비용으로 설명해야겠네요.", en: "In the end, this loss needs to be explained to investors not as short-term performance deterioration but as a long-term risk management cost." },
      { speaker: "분석가B", kr: "맞습니다. 다만 그 설명이 매 분기 반복되면 설득력을 잃는다는 것도 염두에 둬야죠.", en: "Right. But we also need to keep in mind that if that explanation repeats every quarter, it loses persuasive power." },
    ],
  },
  {
    id: "airport-c2z-dynamicpricing",
    situationKey: "airport",
    level: "C2",
    title: "Economists debating dynamic airfare pricing",
    lines: [
      { speaker: "경제학자A", kr: "요즘 항공권 가격이 검색할 때마다 다르게 뜨는 걸 두고 소비자들 불만이 큰데, 이게 단순한 수요 공급 반영인가요, 아니면 가격 차별에 가까운가요?", en: "There's a lot of consumer complaint about airfares showing different prices every time you search — is this simply reflecting supply and demand, or is it closer to price discrimination?" },
      { speaker: "경제학자B", kr: "엄밀히 말하면 둘 다예요. 좌석 점유율에 따른 동적 가격 책정이 기본이지만, 최근에는 검색 기록이나 기기 정보까지 반영한다는 의혹이 있습니다.", en: "Strictly speaking, it's both. Dynamic pricing based on seat occupancy is the baseline, but recently there are suspicions it also factors in search history or device information." },
      { speaker: "경제학자A", kr: "개인별로 다른 가격을 제시하는 거라면 그건 명백한 차별 아닌가요? 같은 좌석인데 누구는 더 비싸게 사는 셈이잖아요.", en: "If it's presenting different prices to different individuals, isn't that clearly discrimination? For the same seat, some people end up paying more." },
      { speaker: "경제학자B", kr: "법적으로는 '차별'보다 '세분화된 가격 책정'이라는 용어를 쓰죠. 문제는 그 세분화 기준이 투명하게 공개되지 않는다는 데 있습니다.", en: "Legally, the term used is 'segmented pricing' rather than 'discrimination.' The problem is that the criteria for that segmentation aren't transparently disclosed." },
      { speaker: "경제학자A", kr: "그렇다면 소비자가 가격을 낮추기 위해 시크릿 모드로 검색하거나 쿠키를 지우는 것도 일종의 대응 전략이 되는 거네요.", en: "Then consumers searching in incognito mode or clearing cookies to lower prices becomes a kind of counter-strategy as well." },
      { speaker: "경제학자B", kr: "그렇죠. 다만 그런 요령이 통한다는 것 자체가 이 시스템의 불투명성을 방증하는 셈이에요. 정보 비대칭이 소비자에게 불리하게 작용하고 있으니까요.", en: "Right. But the very fact that such tricks work is itself evidence of the system's opacity. The information asymmetry is working against consumers." },
      { speaker: "경제학자A", kr: "규제 당국이 개입할 여지는 없나요? 가격 책정 알고리즘 공개를 의무화한다든지요.", en: "Is there no room for regulators to intervene — mandating disclosure of the pricing algorithm, for instance?" },
      { speaker: "경제학자B", kr: "일부 국가에서 논의가 시작됐지만, 영업 기밀 보호와 충돌한다는 항공사 측 반발이 만만치 않아서 진전이 더딥니다.", en: "Discussions have begun in some countries, but progress is slow because of considerable pushback from airlines that it conflicts with trade secret protection." },
      { speaker: "경제학자A", kr: "결국 완전한 공개보다는, 개인 식별 정보를 가격에 반영하는 관행만이라도 금지하는 절충안이 현실적이겠네요.", en: "In the end, rather than full disclosure, a compromise banning at least the practice of factoring personally identifiable information into pricing seems more realistic." },
      { speaker: "경제학자B", kr: "네, 그게 소비자 보호와 기업의 가격 책정 자율성 사이에서 찾을 수 있는 가장 현실적인 지점이라고 봅니다.", en: "Yes, I think that's the most realistic middle ground achievable between consumer protection and a company's pricing autonomy." },
    ],
  },
];

export const AIRPORT_C2_QUIZZES: Record<string, DialogueQuiz> = {
  "airport-c1z-offset": {
    q: "Which reason does Taeseok NOT give for being skeptical of paying for the airline's carbon offset?",
    opts: ["Cases of trees that were already going to be planted being rebranded as offset results", "The risk that disappearing guilt weakens pressure to cut actual demand", "The ticket price itself being far too expensive", "The idea that third-party verification or direct donation is a better alternative"],
    ans: 2,
  },
  "airport-c1z-biophilic": {
    q: "What effect of biophilic design does the architect describe?",
    opts: ["It lowers ticket prices", "It makes waiting time feel shorter than it actually is", "It reduces the rate of lost baggage", "It shortens boarding procedure time"],
    ans: 1,
  },
  "airport-c1z-flightshame": {
    q: "What is Professor A's core reason for being skeptical of the 'flight shame' discourse?",
    opts: ["Short-haul route usage statistics were fabricated", "Placing guilt on the individual can obscure structural problems", "Airlines are already sufficiently eco-friendly", "Rail alternatives are already fully developed"],
    ans: 1,
  },
  "airport-c1z-pilotunion": {
    q: "What is the core demand the union representative makes?",
    opts: ["A base salary increase", "Expanding the minimum rest time to prevent fatigue buildup", "Extending the retirement age", "Increasing welfare benefit points"],
    ans: 1,
  },
  "airport-c1z-baggagescandal": {
    q: "What does the internal document the journalist obtained reveal?",
    opts: ["Executive salary details", "A baggage damage rate three times the industry average", "A plan to expand new routes", "Evidence of hiring corruption"],
    ans: 1,
  },
  "airport-c1z-visadiplomacy": {
    q: "What does Researcher B worry about regarding the visa-waiver agreement?",
    opts: ["That tourist numbers will increase excessively", "The risk that an asymmetric agreement violating the reciprocity principle is left unaddressed", "That signing the agreement itself is illegal", "That the other country will reject the agreement"],
    ans: 1,
  },
  "airport-c1z-hiddencity": {
    q: "Which of the following is NOT a concern Eunseo raises about hidden city ticketing?",
    opts: ["That another passenger on the waitlist could be harmed", "That checked baggage can't be used", "That a mileage account could be suspended if caught", "That the ticket price ends up being more expensive instead"],
    ans: 3,
  },
  "airport-c1z-chaplain": {
    q: "How does the chaplain describe his own role?",
    opts: ["Spreading a particular religious doctrine", "Being present beside someone in that moment", "Issuing psychological counseling certifications", "Handling compensation procedures on behalf of the airline"],
    ans: 1,
  },
  "airport-c1z-biometricprivacy": {
    q: "What problem does the ethicist point out about facial-recognition boarding?",
    opts: ["That it is technically inaccurate", "That the consent process tends to become a mere formality", "That it is far too inexpensive", "That it has already been banned in every country"],
    ans: 1,
  },
  "airport-c2z-hubidentity": {
    q: "What downside of the airport's expansion does the historian describe?",
    opts: ["Citizen satisfaction was always high", "Nearby villages had to relocate and there was backlash over noise pollution", "There were never any international routes", "It had nothing to do with the city's identity"],
    ans: 1,
  },
  "airport-c2z-nightcurfew": {
    q: "Why does the airport official balk at a complete late-night flight ban?",
    opts: ["Because the noise problem has already been resolved", "Because over half of cargo routes are concentrated in that late-night window", "Because the residents' demand has no basis", "Because there is no budget at all"],
    ans: 1,
  },
  "airport-c2z-slotresale": {
    q: "What do the analysts mean by 'ghost flights'?",
    opts: ["Flights that don't actually exist at all", "Flight numbers flown nearly empty purely to hold onto a slot", "Cargo-only flights that operate at night only", "Cancelled flights that were never refunded"],
    ans: 1,
  },
  "airport-c2z-antitrafficking": {
    q: "What is the most important principle the senior officer emphasizes for handling trafficking cases?",
    opts: ["Arresting the suspect immediately", "Treating the person as someone to protect, not a potential criminal, until confirmed", "Never asking any questions at all", "Processing quickly without an interpreter"],
    ans: 1,
  },
  "airport-c2z-lostgeneration": {
    q: "What reason does the retired flight attendant give for not romanticizing the past unconditionally?",
    opts: ["Ticket prices back then were far too expensive", "Discriminatory regulations against female flight attendants were severe", "There were far more passengers than there are now", "The quality of in-flight meals was low"],
    ans: 1,
  },
  "airport-c2z-migrationroute": {
    q: "What limitation of budget airline expansion does Researcher B mention?",
    opts: ["That prices actually became more expensive", "That the lack of direct routes creates a time cost", "That migrants don't use them at all", "That safety standards are low"],
    ans: 1,
  },
  "airport-c2z-wildlifestrike": {
    q: "What concern does the environmental group raise about habitat landfilling?",
    opts: ["That it costs far too much", "That it may just shift the risk of collision to another flight path as displaced birds relocate elsewhere", "That the birds are not actually an endangered species", "That it is unrelated to airport safety"],
    ans: 1,
  },
  "airport-c2z-fuelhedging": {
    q: "What is Analyst B's view on the jet fuel hedging loss?",
    opts: ["That it was entirely a misjudgment by management", "That since it's insurance-like protection against an oil price spike, judging it purely on the outcome could be hindsight bias", "That the hedging strategy should be abolished altogether", "That there was no loss at all"],
    ans: 1,
  },
  "airport-c2z-dynamicpricing": {
    q: "What problem does Economist B point out about dynamic airfare pricing?",
    opts: ["That ticket prices always stay exactly the same", "That the criteria for segmentation aren't transparently disclosed", "That the government directly controls prices", "That every airline offers the same price"],
    ans: 1,
  },
};
