import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Directions situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const DIRECTIONS_C_EXPANSION: Dialogue[] = [
  {
    id: "directions-c1y-subway-hearing",
    situationKey: "directions",
    level: "C1",
    title: "Public hearing on a new subway route",
    lines: [
      { speaker: "공무원", kr: "오늘 공청회는 신설 9호선 연장 구간의 노선안을 설명드리기 위해 마련했습니다.", en: "Today's hearing is to explain the proposed route for the new Line 9 extension." },
      { speaker: "주민", kr: "저희 동네를 완전히 우회해서 지나가던데, 애초에 수요 조사는 제대로 하신 겁니까?", en: "It completely bypasses our neighborhood — was the demand survey even done properly?" },
      { speaker: "공무원", kr: "지반 조건상 직선 구간을 확보하기 어려워서 부득이하게 우회 노선을 택할 수밖에 없었습니다.", en: "Given the ground conditions, securing a straight section was difficult, so we had no choice but to opt for a detour route." },
      { speaker: "주민", kr: "그 말씀은 결국 저희 동네 주민들이 불편을 감수해야 한다는 뜻 아닙니까.", en: "So what you're saying is that our residents just have to put up with the inconvenience." },
      { speaker: "공무원", kr: "대신 환승 셔틀버스를 신설역까지 무료로 운행할 계획입니다.", en: "Instead, we plan to run a free shuttle bus to the new station." },
      { speaker: "주민", kr: "셔틀버스로는 배차 간격이 벌어지면 오히려 지금보다 더 돌아가는 셈이 됩니다.", en: "If the shuttle's intervals are spread out, it'll actually end up being more roundabout than now." },
      { speaker: "공무원", kr: "배차 간격은 출퇴근 시간대에 한해 십 분 이내로 못 박아 운영하겠습니다.", en: "We'll fix the interval at under ten minutes specifically during rush hour." },
      { speaker: "주민", kr: "그 약속을 문서로 남겨 주실 수 있습니까? 구두 약속은 번번이 흐지부지됐으니까요.", en: "Can you put that promise in writing? Verbal promises have fizzled out time and again." },
      { speaker: "공무원", kr: "네, 오늘 논의 사항을 정리해서 다음 회차 공청회 전까지 공문으로 배부하겠습니다.", en: "Yes, we'll compile today's discussion and distribute it as an official document before the next round of hearings." },
    ],
  },
  {
    id: "directions-c1y-gentrification",
    situationKey: "directions",
    level: "C1",
    title: "Debating displacement with a longtime resident",
    lines: [
      { speaker: "기자", kr: "이 골목이 젠트리피케이션으로 유명해지면서 오히려 원주민들이 밀려났다는 얘기가 많던데요.", en: "There's a lot of talk that this alley, once it got famous through gentrification, ended up pushing out the original residents." },
      { speaker: "주민", kr: "말도 마세요. 삼십 년 살던 골목인데 이제는 방향 감각조차 안 잡혀요.", en: "Don't even get me started. I've lived in this alley for thirty years, and now I can't even get my bearings." },
      { speaker: "기자", kr: "구체적으로 어떤 부분이 가장 낯설게 느껴지세요?", en: "Specifically, what feels most unfamiliar to you?" },
      { speaker: "주민", kr: "골목 이름 대신 카페 이름으로 길을 설명해야 하는 게 씁쓸하죠.", en: "It's bitter having to give directions using cafe names instead of the alley names." },
      { speaker: "기자", kr: "그럼 예전 지명이나 표지판은 아예 사라진 겁니까?", en: "So have the old place names or signs disappeared entirely?" },
      { speaker: "주민", kr: "구청에서 표지판은 남겨 뒀지만 정작 사람들은 지도 앱만 보고 다니니 무용지물이에요.", en: "The district office left the signs up, but people only follow map apps, so they're useless." },
      { speaker: "기자", kr: "지역 정체성을 지키자는 목소리도 있던데, 실효성이 있을까요?", en: "There's a call to preserve local identity — do you think that'll actually be effective?" },
      { speaker: "주민", kr: "상권이 이미 바뀐 마당에 표지판 몇 개로 정체성이 돌아올 리 없죠.", en: "With the commercial district already transformed, a few signs aren't going to bring back the identity." },
    ],
  },
  {
    id: "directions-c1y-15min-city",
    situationKey: "directions",
    level: "C1",
    title: "Explaining the 15-minute city to skeptical citizens",
    lines: [
      { speaker: "도시계획가", kr: "십오 분 도시란 도보나 자전거로 십오 분 안에 생활에 필요한 시설을 이용할 수 있게 재편하는 개념입니다.", en: "The 15-minute city is a concept where you restructure things so all daily necessities are reachable within fifteen minutes on foot or by bike." },
      { speaker: "주민", kr: "듣기엔 좋은데, 결국 차량 진입을 막겠다는 얘기 아닙니까?", en: "It sounds nice, but isn't it ultimately about blocking car access?" },
      { speaker: "도시계획가", kr: "전면 통제가 아니라 필수 이동은 허용하되 통과 교통만 우회시키는 방식입니다.", en: "It's not a total ban — essential travel is allowed, but only through-traffic is rerouted." },
      { speaker: "주민", kr: "그럼 저희처럼 외곽에서 출퇴근하는 사람들은 어떻게 되는 겁니까?", en: "Then what happens to people like us who commute from the outskirts?" },
      { speaker: "도시계획가", kr: "환승 거점을 늘려서 외곽 주민도 대중교통으로 십오 분 권역에 진입할 수 있게 설계했습니다.", en: "We've designed more transfer hubs so residents from the outskirts can also enter the fifteen-minute zone via public transit." },
      { speaker: "주민", kr: "설계는 그럴듯한데, 상점 배치까지 강제로 바꾸실 겁니까?", en: "The design sounds plausible, but will you also forcibly change the layout of shops?" },
      { speaker: "도시계획가", kr: "강제가 아니라 세제 혜택으로 생활 밀착형 업종의 입점을 유도하는 방향입니다.", en: "Not by force — we're inducing daily-essential businesses to move in through tax incentives." },
      { speaker: "주민", kr: "그렇다면 시간을 두고 지켜볼 만은 하겠네요.", en: "In that case, it might be worth watching over time." },
    ],
  },
  {
    id: "directions-c1y-wayfinding-blind",
    situationKey: "directions",
    level: "C1",
    title: "Wayfinding design for the visually impaired",
    lines: [
      { speaker: "기자", kr: "이번 역사 리모델링에서 시각장애인을 위한 동선 설계가 화제라고 들었습니다.", en: "I heard the wayfinding design for the visually impaired in this station's remodeling is drawing attention." },
      { speaker: "설계자", kr: "네, 점자 블록만으로는 부족해서 촉지도와 음성 안내를 결합했습니다.", en: "Yes, tactile paving alone wasn't enough, so we combined tactile maps with voice guidance." },
      { speaker: "기자", kr: "기존 점자 블록의 어떤 점이 부족하다고 판단하신 겁니까?", en: "What did you find lacking about the existing tactile paving?" },
      { speaker: "설계자", kr: "환승 구간처럼 동선이 갈라지는 지점에서 방향을 오인하기 쉽더라고요.", en: "At points where the path branches, like transfer sections, it was easy to misjudge direction." },
      { speaker: "기자", kr: "음성 안내는 구체적으로 어떻게 작동합니까?", en: "How exactly does the voice guidance work?" },
      { speaker: "설계자", kr: "스마트폰 앱과 연동해서 사용자가 접근하면 갈림길마다 방향을 안내해 줍니다.", en: "It links with a smartphone app and announces directions at every branching point as the user approaches." },
      { speaker: "기자", kr: "그래도 앱을 못 쓰시는 어르신들은 소외될 수 있지 않을까요?", en: "Still, wouldn't elderly users who can't use the app end be left out?" },
      { speaker: "설계자", kr: "그래서 음성 유도등을 병행 설치해 앱 없이도 소리를 따라올 수 있게 했습니다.", en: "That's why we also installed audible beacons in parallel, so people can follow the sound without the app." },
      { speaker: "기자", kr: "결국 이중 삼중의 안전장치를 마련하신 셈이군요.", en: "So you've essentially built in double and triple safeguards." },
    ],
  },
  {
    id: "directions-c1y-walking-tour",
    situationKey: "directions",
    level: "C1",
    title: "An urban historian's walking-tour lecture",
    lines: [
      { speaker: "역사가", kr: "지금 서 계신 이 사거리가 조선 시대에는 성문 밖 첫 번째 갈림길이었습니다.", en: "This very intersection you're standing at was the first fork just outside the city gate during the Joseon dynasty." },
      { speaker: "관광객", kr: "그럼 지금 저 큰 도로가 원래는 성벽이 있던 자리인가요?", en: "So does that big road over there used to be where the fortress wall stood?" },
      { speaker: "역사가", kr: "정확히는 성벽 바로 안쪽 순찰로였고, 성벽 자체는 저 언덕 능선을 따라 이어져 있었습니다.", en: "To be precise, it was the patrol path just inside the wall, and the wall itself ran along the ridge of that hill." },
      { speaker: "관광객", kr: "지형을 보면 지금 걸어온 길이 원래 물길이었을 것 같기도 한데요.", en: "Looking at the terrain, the path we just walked seems like it might have been a waterway originally." },
      { speaker: "역사가", kr: "정확히 보셨습니다. 지금은 복개되어 도로가 됐지만 원래는 개천이었지요.", en: "You've observed correctly. It's been covered over and turned into a road now, but it used to be a stream." },
      { speaker: "관광객", kr: "그렇다면 옛 물길을 따라가면 자연스럽게 시내 중심부로 이어지겠군요.", en: "Then following the old waterway would naturally lead into the heart of downtown, wouldn't it." },
      { speaker: "역사가", kr: "맞습니다. 실제로 옛 지도를 보면 상권이 모두 그 물길을 따라 형성돼 있습니다.", en: "That's right. In fact, old maps show that the commercial district all formed along that waterway." },
    ],
  },
  {
    id: "directions-c1y-self-driving-streets",
    situationKey: "directions",
    level: "C1",
    title: "Do self-driving cars need different streets?",
    lines: [
      { speaker: "기자", kr: "자율주행차가 늘어나면 지금 도로 체계로는 부족하다는 의견이 있던데요.", en: "There's an opinion that as autonomous vehicles increase, the current road system will fall short." },
      { speaker: "전문가", kr: "표지판이나 차선은 인간 운전자를 전제로 설계된 거라 인식 오류가 종종 발생합니다.", en: "Signs and lane markings were designed on the premise of human drivers, so recognition errors often occur." },
      { speaker: "기자", kr: "구체적으로 어떤 상황에서 오류가 잦습니까?", en: "In what specific situations do errors occur most often?" },
      { speaker: "전문가", kr: "눈이나 낙엽으로 차선이 가려지면 센서가 도로 경계를 제대로 못 잡는 경우가 있습니다.", en: "When lane markings are covered by snow or fallen leaves, sensors sometimes fail to properly detect the road boundary." },
      { speaker: "기자", kr: "그럼 별도의 전용 차선을 새로 만들어야 한다는 뜻인가요?", en: "So does that mean dedicated lanes need to be built separately?" },
      { speaker: "전문가", kr: "전용 차선보다는 도로 하부에 유도선을 매설하는 방안이 더 현실적이라는 논의가 있습니다.", en: "Rather than dedicated lanes, there's discussion that burying guidance lines under the road surface is more realistic." },
      { speaker: "기자", kr: "그렇게 되면 기존 보행자 동선과의 충돌은 어떻게 조율합니까?", en: "In that case, how would conflicts with existing pedestrian paths be coordinated?" },
      { speaker: "전문가", kr: "교차로마다 보행 우선 신호 체계를 강화해서 자율주행차가 자동으로 양보하도록 설계하고 있습니다.", en: "At every intersection, they're strengthening a pedestrian-priority signal system so autonomous cars are designed to yield automatically." },
    ],
  },
  {
    id: "directions-c1y-street-closure-town-hall",
    situationKey: "directions",
    level: "C1",
    title: "A heated town hall on closing a street to cars",
    lines: [
      { speaker: "주민", kr: "이 거리를 차 없는 거리로 만들면 저희 가게는 물건도 못 나릅니다.", en: "If you turn this street into a car-free zone, our shop won't even be able to bring in goods." },
      { speaker: "공무원", kr: "새벽 시간대에는 배송 차량 진입을 허용하는 방안을 검토 중입니다.", en: "We're reviewing a plan to allow delivery vehicles in during the early morning hours." },
      { speaker: "주민", kr: "새벽에만 허용하면 낮 시간 긴급 배송은 어떻게 하라는 겁니까?", en: "If it's only allowed at dawn, what are we supposed to do about urgent daytime deliveries?" },
      { speaker: "공무원", kr: "긴급 상황에 한해서는 별도 통행증을 발급해 예외를 두려고 합니다.", en: "For emergency cases only, we plan to issue separate permits to allow exceptions." },
      { speaker: "주민", kr: "통행증 발급 절차가 복잡하면 결국 유명무실해질 게 뻔합니다.", en: "If the permit process is complicated, it's bound to become meaningless in the end." },
      { speaker: "공무원", kr: "온라인 신청으로 즉시 발급되도록 시스템을 손질하겠습니다.", en: "We'll adjust the system so permits are issued instantly through online applications." },
      { speaker: "주민", kr: "보행자 늘어나는 건 반갑지만 저희 생계도 함께 고려해 주셔야죠.", en: "I welcome more pedestrians, but you also need to consider our livelihood." },
      { speaker: "공무원", kr: "말씀하신 부분을 시범 운영 기간 동안 집중적으로 모니터링하겠습니다.", en: "We'll intensively monitor that exact point during the pilot operation period." },
    ],
  },
  {
    id: "directions-c1y-layout-behavior",
    situationKey: "directions",
    level: "C1",
    title: "How city layout shapes social behavior",
    lines: [
      { speaker: "건축가", kr: "골목이 좁고 굽어 있는 동네일수록 이웃 간 마주칠 확률이 높아진다는 연구가 있습니다.", en: "There's research showing that in neighborhoods with narrow, winding alleys, the odds of neighbors bumping into each other rise." },
      { speaker: "기자", kr: "직선 대로 위주의 신도시와는 어떤 차이가 있는 겁니까?", en: "What's the difference compared to new towns built around straight boulevards?" },
      { speaker: "건축가", kr: "직선 대로는 이동 효율은 높지만 우연한 만남을 만들어내는 구조는 아니죠.", en: "Straight boulevards are efficient for movement, but they aren't a structure that generates chance encounters." },
      { speaker: "기자", kr: "그렇다면 의도적으로 굽은 골목을 설계하는 사례도 있나요?", en: "Then are there cases where winding alleys are deliberately designed?" },
      { speaker: "건축가", kr: "네, 최근 공동주택 단지들은 동선을 일부러 살짝 꺾어서 커뮤니티 공간을 지나게 합니다.", en: "Yes, recent apartment complexes deliberately bend the pathways slightly so they pass through community spaces." },
      { speaker: "기자", kr: "주민들이 오히려 불편하게 느끼지는 않습니까?", en: "Don't the residents find that inconvenient instead?" },
      { speaker: "건축가", kr: "초반에는 그런 불만이 있지만 시간이 지나면 그 지점이 만남의 장소로 자리 잡더군요.", en: "There are complaints like that at first, but over time that spot tends to settle in as a meeting place." },
    ],
  },
  {
    id: "directions-c1y-congestion-pricing-coffee",
    situationKey: "directions",
    level: "C1",
    title: "Discussing congestion pricing over coffee",
    lines: [
      { speaker: "친구1", kr: "다음 달부터 도심 진입할 때 혼잡 통행료 내야 한다며?", en: "I heard starting next month you have to pay a congestion charge to enter downtown?" },
      { speaker: "친구2", kr: "응, 출퇴근 시간대에 자가용으로 들어오면 요금이 부과된대.", en: "Yeah, they say a fee will be charged if you drive in during rush hour." },
      { speaker: "친구1", kr: "그럼 우회로로 다니는 사람이 늘어서 오히려 다른 도로가 막히지 않을까?", en: "Then won't more people take detours, and end up clogging the other roads instead?" },
      { speaker: "친구2", kr: "그럴 가능성 때문에 우회로 쪽에도 순차적으로 요금을 확대할 계획이래.", en: "Because of that possibility, they plan to gradually extend the charge to the detour roads too." },
      { speaker: "친구1", kr: "결국 어디로 가든 돈을 내야 한다는 소리네.", en: "So basically wherever you go, you'll have to pay." },
      { speaker: "친구2", kr: "대신 걷히는 요금은 전액 대중교통 확충에 쓴다고 하더라.", en: "Instead, they say all the collected fees go toward expanding public transit." },
      { speaker: "친구1", kr: "그 말을 믿어도 될지는 두고 봐야 알겠지.", en: "Whether that promise can be trusted is something we'll have to wait and see." },
    ],
  },
  {
    id: "directions-c2y-heritage-vs-redevelop",
    situationKey: "directions",
    level: "C2",
    title: "Debating heritage preservation versus street redevelopment",
    lines: [
      { speaker: "기자", kr: "이 골목을 근대 문화유산으로 지정하자는 움직임과 재개발을 밀어붙이자는 목소리가 첨예하게 맞서고 있습니다.", en: "There's a sharp standoff between a movement to designate this alley as modern cultural heritage and voices pushing for redevelopment." },
      { speaker: "학자", kr: "이 미로 같은 골목 자체가 근대 상업사를 증언하는 살아있는 지도라고 봐야 합니다.", en: "This maze-like alley itself should be seen as a living map bearing witness to modern commercial history." },
      { speaker: "주민", kr: "증언이니 지도니 말씀은 좋습니다만, 소방차 한 대 못 들어오는 골목에서 화재라도 나면 누가 책임집니까.", en: "Talk of testimony and living maps is fine, but if there's a fire in an alley where not even a single fire truck can enter, who takes responsibility?" },
      { speaker: "학자", kr: "안전 문제는 골목의 골격을 유지하면서도 소방 도로를 부분적으로 확보하는 절충안으로 해결이 가능합니다.", en: "The safety issue can be resolved with a compromise that partially secures a fire access road while preserving the alley's skeleton." },
      { speaker: "주민", kr: "부분 확보라는 게 결국 어느 집 앞마당을 헐겠다는 얘기 아닙니까.", en: "'Partially securing' just means tearing down someone's front yard, doesn't it." },
      { speaker: "학자", kr: "보상과 이주 대책을 병행한다면 일방적인 희생이라 부를 수는 없을 겁니다.", en: "If compensation and relocation measures are carried out in parallel, it can't be called a one-sided sacrifice." },
      { speaker: "기자", kr: "결국 두 분 말씀을 들어 보면 골목의 물리적 형태를 어디까지 지킬 것이냐가 관건이군요.", en: "Listening to both of you, it seems the crux is how much of the alley's physical form should be preserved." },
      { speaker: "학자", kr: "형태를 지키지 못하면 기억도 함께 지워진다는 게 제 우려입니다.", en: "My concern is that if the form isn't preserved, the memory is erased along with it." },
      { speaker: "주민", kr: "기억은 사람이 안전하게 살아남아야 이어갈 수 있는 것 아니겠습니까.", en: "But memory can only be carried on if the people survive safely, wouldn't you say." },
    ],
  },
  {
    id: "directions-c2y-algorithmic-navigation",
    situationKey: "directions",
    level: "C2",
    title: "Debating algorithmic route optimization and social cost",
    lines: [
      { speaker: "칼럼니스트", kr: "내비게이션 알고리즘이 이면도로로 차량을 몰아넣으면서 주택가 골목이 사실상 우회 간선도로가 되어 버렸다는 지적이 나옵니다.", en: "There's criticism that navigation algorithms are funneling cars into side streets, effectively turning residential alleys into de facto arterial bypasses." },
      { speaker: "개발자", kr: "저희 알고리즘은 통행 시간을 최소화하도록 설계됐을 뿐, 특정 도로를 겨냥해 유도하는 건 아닙니다.", en: "Our algorithm is simply designed to minimize travel time — it's not deliberately targeting or funneling into any particular street." },
      { speaker: "칼럼니스트", kr: "의도가 없었다는 게 결과에 대한 책임까지 면제해 준다고 보기는 어렵지 않습니까.", en: "It's hard to say the absence of intent absolves you of responsibility for the outcome, isn't it." },
      { speaker: "개발자", kr: "주거 밀집 구간에 가중치를 부여해서 우회 유입을 억제하는 업데이트를 이미 검토 중입니다.", en: "We're already reviewing an update that assigns weighting to dense residential sections to suppress the diversion inflow." },
      { speaker: "칼럼니스트", kr: "그런 조정이 결국 지자체의 도로 정책보다 알고리즘 설계자의 재량에 더 좌우된다는 게 아이러니 아닐까요.", en: "Isn't it ironic that such adjustments end up being governed more by the algorithm designer's discretion than by the municipality's own road policy?" },
      { speaker: "개발자", kr: "저희로서는 지자체와 데이터를 공유해서 정책적 판단을 함께 반영하려 노력하고 있습니다.", en: "For our part, we're trying to share data with municipalities to jointly reflect their policy judgments." },
      { speaker: "칼럼니스트", kr: "공유된 데이터가 실제 정책 결정에 얼마나 반영되는지는 검증할 방법이 마땅치 않습니다.", en: "There's no adequate way to verify how much the shared data actually gets reflected in real policy decisions." },
      { speaker: "개발자", kr: "투명성 보고서를 정기적으로 공개하는 방향으로 개선해 나갈 계획입니다.", en: "We plan to improve this by regularly publishing transparency reports." },
      { speaker: "칼럼니스트", kr: "결국 신뢰의 문제로 귀결되는군요. 보고서가 그 신뢰를 회복할 수 있을지 지켜봐야겠습니다.", en: "So it ultimately comes down to a question of trust. We'll have to see whether the reports can restore that trust." },
    ],
  },
  {
    id: "directions-c2y-desire-lines",
    situationKey: "directions",
    level: "C2",
    title: "A design critic on desire lines and official planning",
    lines: [
      { speaker: "평론가", kr: "잔디밭을 가로질러 생긴 저 흙길, 흔히 '욕망의 길'이라 부르는데 설계자의 의도를 배반하는 증거물이죠.", en: "That dirt path cutting across the lawn is what's often called a 'desire line' — it's evidence that betrays the designer's original intent." },
      { speaker: "설계자", kr: "배반이라기보다는 설계 단계에서 미처 포착하지 못한 실제 동선을 뒤늦게 드러낸 거라고 봐야죠.", en: "Rather than betrayal, I'd say it's a belated revelation of the actual foot traffic that the design phase failed to capture." },
      { speaker: "평론가", kr: "결국 보행자들이 설계도보다 더 정직한 지도를 몸으로 그려낸 셈 아닙니까.", en: "So in the end, the pedestrians have drawn a more honest map with their bodies than the blueprint did, haven't they." },
      { speaker: "설계자", kr: "저희도 최근에는 개장 후 일정 기간 관찰해서 욕망의 길을 정식 보행로로 편입하는 방식을 씁니다.", en: "Recently we've also started observing for a set period after opening and incorporating those desire lines as official walkways." },
      { speaker: "평론가", kr: "그렇다면 애초에 완벽한 설계란 존재할 수 없고, 설계는 사후 수정을 전제해야 한다는 뜻이 되는군요.", en: "That would mean a perfect design can't exist from the outset, and design must presuppose post-hoc revision." },
      { speaker: "설계자", kr: "정확히 그렇습니다. 저희는 이제 첫 도면을 최종안이 아니라 가설로 취급합니다.", en: "Exactly. We now treat the first blueprint not as a final plan but as a hypothesis." },
      { speaker: "평론가", kr: "가설이라는 표현이 흥미롭네요. 그렇다면 이용자야말로 진짜 공동 설계자인 셈이고요.", en: "The word 'hypothesis' is interesting. That would make the users the true co-designers, then." },
      { speaker: "설계자", kr: "저는 그 표현에 전적으로 동의합니다. 다만 예산과 안전 기준이라는 현실적 제약은 여전히 남아 있죠.", en: "I fully agree with that framing. Though practical constraints like budget and safety standards still remain." },
      { speaker: "평론가", kr: "결국 이상과 현실 사이에서 매번 새로운 타협점을 찾아야 한다는 얘기네요.", en: "So it comes down to having to find a new compromise between ideal and reality every time." },
    ],
  },
  {
    id: "directions-c2y-toponym-erasure",
    situationKey: "directions",
    level: "C2",
    title: "A journalist on the erasure of old place names",
    lines: [
      { speaker: "기자", kr: "행정구역 통폐합 이후로 옛 지명들이 지도에서 하나둘 사라지고 있다는 우려가 커지고 있습니다.", en: "There's growing concern that, since the administrative district mergers, old place names are disappearing from maps one by one." },
      { speaker: "지명학자", kr: "지명은 단순한 표지가 아니라 그 땅의 역사와 지형 정보를 압축해 담고 있는 언어 유산입니다.", en: "A place name isn't just a marker — it's a linguistic heritage that compresses the land's history and topographical information." },
      { speaker: "기자", kr: "구체적으로 어떤 정보가 지명 안에 담겨 있다는 말씀이신가요?", en: "Specifically, what kind of information do you mean is embedded in a place name?" },
      { speaker: "지명학자", kr: "예를 들어 '갈현동' 같은 이름은 예전에 그곳에 갈대가 우거진 고개가 있었다는 지형 정보를 담고 있죠.", en: "For instance, a name like 'Galhyeon-dong' carries topographical information that there used to be a reed-covered hill pass there." },
      { speaker: "기자", kr: "그런데 새 행정명은 대개 번호나 방위로만 구성되어 있잖습니까.", en: "But new administrative names are mostly composed of just numbers or compass directions, aren't they." },
      { speaker: "지명학자", kr: "그렇습니다. 효율성만 앞세우다 보니 땅이 품고 있던 서사가 통째로 지워지는 셈이죠.", en: "That's right. Prioritizing efficiency alone ends up erasing the entire narrative the land once held." },
      { speaker: "기자", kr: "이런 흐름을 막을 현실적인 대안이 있을까요?", en: "Is there a realistic alternative to stem this trend?" },
      { speaker: "지명학자", kr: "행정명과 별개로 옛 지명을 병기하는 표지판만 세워도 상당 부분 복원이 가능하다고 봅니다.", en: "I believe even just installing signs that co-list the old place names alongside the administrative ones could restore a significant part of it." },
      { speaker: "기자", kr: "결국 작은 표지판 하나가 지역의 기억을 지탱하는 마지막 보루인 셈이군요.", en: "So in the end, one small sign becomes the last bastion holding up a region's memory." },
    ],
  },
  {
    id: "directions-c2y-superblock-debate",
    situationKey: "directions",
    level: "C2",
    title: "A debate over superblocks and local commerce",
    lines: [
      { speaker: "패널1", kr: "슈퍼블록 정책으로 내부 도로 통행이 제한되면서 상권이 침체됐다는 상인들의 반발이 거셉니다.", en: "There's fierce backlash from merchants claiming that restricting internal road traffic under the superblock policy has depressed local commerce." },
      { speaker: "패널2", kr: "단기 통계만 보면 그렇게 보일 수 있지만, 보행자 유입량 자체는 오히려 증가했습니다.", en: "Looking only at short-term statistics might make it seem that way, but foot traffic itself has actually increased." },
      { speaker: "패널1", kr: "보행자가 늘었다는 게 곧 매출로 이어졌다는 증거는 아니지 않습니까.", en: "But an increase in pedestrians isn't proof that it translated into sales, is it." },
      { speaker: "패널2", kr: "초기 육 개월 자료를 보면 소규모 카페와 서점 매출은 뚜렷하게 상승했습니다.", en: "Looking at the initial six-month data, sales at small cafes and bookstores rose distinctly." },
      { speaker: "패널1", kr: "반면 대형 매장은 배송 차량 진입이 막히면서 물류비가 급증했다는 하소연이 잇따릅니다.", en: "On the other hand, large stores have been complaining one after another that logistics costs have surged as delivery vehicles are blocked." },
      { speaker: "패널2", kr: "그 부분은 인정합니다. 배송 전용 시간대를 확대하는 보완책이 필요하다고 봅니다.", en: "I acknowledge that point. I think a supplementary measure expanding dedicated delivery time slots is needed." },
      { speaker: "패널1", kr: "결국 업종 규모에 따라 정책의 명암이 극명하게 갈린다는 뜻이군요.", en: "So it means the policy's light and shadow are starkly divided depending on the scale of the business." },
      { speaker: "패널2", kr: "맞습니다. 다만 그 명암을 이유로 정책 자체를 폐기하기보다는 세분화된 예외 조항으로 보완해야겠죠.", en: "That's right. But rather than scrapping the policy itself because of that divide, we should supplement it with more finely tuned exception clauses." },
      { speaker: "패널1", kr: "그 세분화 작업이 얼마나 신속하게 이뤄지느냐가 정책의 성패를 가르겠네요.", en: "How quickly that fine-tuning is carried out will likely determine whether the policy succeeds or fails." },
    ],
  },
  {
    id: "directions-c2y-ferry-terminal-signage",
    situationKey: "directions",
    level: "C2",
    title: "Journalists dissecting confusing multilingual signage",
    lines: [
      { speaker: "기자1", kr: "이번 여객터미널 오픈 이후로 다국어 표지판이 오히려 혼란을 키운다는 민원이 폭주하고 있다는데요.", en: "Since this passenger terminal opened, complaints are pouring in that the multilingual signage is actually increasing confusion." },
      { speaker: "기자2", kr: "직접 가 보니 한 표지판에 네 개 언어가 다 들어가 있어서 정작 눈에 잘 안 들어오더라고요.", en: "I went and saw it myself — with four languages crammed onto a single sign, it actually didn't stand out at all." },
      { speaker: "기자1", kr: "정보 과잉이 오히려 가독성을 해친다는 전형적인 사례군요.", en: "That's a textbook case of information overload actually harming readability." },
      { speaker: "기자2", kr: "게다가 언어별 우선순위도 뒤죽박죽이라 외국인 관광객이 자기 언어를 찾는 데도 시간이 걸리더군요.", en: "On top of that, the priority order between languages was jumbled, so foreign tourists took time even finding their own language." },
      { speaker: "기자1", kr: "픽토그램 위주로 단순화하자는 제안도 있던데 그건 어떻습니까?", en: "There's also a proposal to simplify things by relying mainly on pictograms — what about that?" },
      { speaker: "기자2", kr: "픽토그램만으로는 세부 방향, 그러니까 몇 번 게이트인지까지는 전달하기 어렵다는 한계가 있죠.", en: "The limitation is that pictograms alone struggle to convey detailed direction — like exactly which gate number." },
      { speaker: "기자1", kr: "결국 언어와 픽토그램을 어떻게 위계적으로 배치하느냐가 관건이겠네요.", en: "So it comes down to how you hierarchically arrange language and pictograms." },
      { speaker: "기자2", kr: "터미널 측은 다음 분기까지 시야각과 색상 대비를 재조정한 시범 표지판을 시험한다고 밝혔습니다.", en: "The terminal authority stated they'll test pilot signage with readjusted viewing angles and color contrast by next quarter." },
      { speaker: "기자1", kr: "적어도 문제의식은 제대로 짚었으니 결과가 기대되긴 하네요.", en: "At least they've correctly identified the problem, so the outcome is worth looking forward to." },
    ],
  },
  {
    id: "directions-c2y-street-vendor-informal-map",
    situationKey: "directions",
    level: "C2",
    title: "Informal vendor networks versus the official street map",
    lines: [
      { speaker: "연구자", kr: "노점상들이 자체적으로 공유하는 골목 지도가 공식 지도보다 더 정교하다는 사실이 흥미롭습니다.", en: "It's fascinating that the alley maps street vendors informally share among themselves are more sophisticated than the official map." },
      { speaker: "상인", kr: "저희는 단속반이 어느 골목으로 들어오는지, 어디가 막다른 길인지까지 다 꿰고 있죠.", en: "We know down to which alley the enforcement team enters from, even which ones are dead ends." },
      { speaker: "연구자", kr: "그런 정보가 세대를 거쳐 구전으로 전승된다는 게 맞습니까?", en: "Is it accurate to say that information gets passed down orally across generations?" },
      { speaker: "상인", kr: "네, 저도 어머니한테 물려받았고 지금은 후배 상인들한테 알려 주고 있어요.", en: "Yes, I inherited it from my mother, and now I'm passing it on to junior vendors." },
      { speaker: "연구자", kr: "공식 지도에는 그런 이면 동선이 전혀 반영되어 있지 않죠.", en: "The official map doesn't reflect any of that behind-the-scenes routing at all." },
      { speaker: "상인", kr: "당연하죠. 저희 지도는 생존을 위한 지도지, 관광객용이 아니니까요.", en: "Of course. Our map is a map for survival, not one for tourists." },
      { speaker: "연구자", kr: "그렇다면 도시 정책 입안자들이 이런 비공식 지식을 제도권으로 끌어들일 필요가 있지 않을까요?", en: "Then shouldn't urban policymakers need to bring this informal knowledge into the institutional fold?" },
      { speaker: "상인", kr: "저희 입장에서는 그게 오히려 단속을 더 정교하게 만들까 봐 걱정도 됩니다.", en: "From our position, we're also worried that could end up making enforcement more sophisticated instead." },
      { speaker: "연구자", kr: "결국 지식 공유와 생계 보호 사이에서 균형을 찾는 게 숙제로 남는군요.", en: "So finding a balance between sharing knowledge and protecting livelihoods remains the homework left to do." },
    ],
  },
  {
    id: "directions-c2y-flood-evacuation-route",
    situationKey: "directions",
    level: "C2",
    title: "Reassessing evacuation routes after a flood",
    lines: [
      { speaker: "공무원", kr: "이번 폭우로 기존 대피 경로 상당수가 실제로는 무용지물이었다는 점이 드러났습니다.", en: "This heavy rain revealed that a significant portion of the existing evacuation routes were, in practice, useless." },
      { speaker: "전문가", kr: "지도상 최단 경로가 실제로는 저지대를 통과해서 오히려 침수 위험을 키웠던 거죠.", en: "The shortest route on the map actually passed through low-lying areas, which ended up increasing the flood risk instead." },
      { speaker: "공무원", kr: "그럼 경로를 다시 짜는 데 가장 우선적으로 고려해야 할 요소가 무엇입니까?", en: "So what factor should be the top priority in redesigning the routes?" },
      { speaker: "전문가", kr: "고도 데이터를 기반으로 반드시 오르막 방향으로만 대피로를 지정해야 합니다.", en: "Based on elevation data, evacuation routes must be designated strictly in the uphill direction." },
      { speaker: "공무원", kr: "주민들이 익숙한 지름길을 버리고 낯선 경로를 따를지 의문입니다.", en: "I doubt residents will abandon the shortcuts they're familiar with and follow an unfamiliar route." },
      { speaker: "전문가", kr: "그래서 평상시에도 정기적인 대피 훈련으로 새 경로를 몸에 익히게 하는 게 관건입니다.", en: "That's why the key is to have regular evacuation drills even in ordinary times, so the new route becomes second nature." },
      { speaker: "공무원", kr: "예산상 훈련 횟수를 늘리기는 쉽지 않은데 대안이 있을까요?", en: "Increasing the number of drills isn't easy given the budget — is there an alternative?" },
      { speaker: "전문가", kr: "실제 훈련 대신 증강현실 앱으로 가상 대피 시뮬레이션을 제공하는 방안도 검토할 만합니다.", en: "Instead of live drills, providing a virtual evacuation simulation through an augmented reality app is also worth considering." },
      { speaker: "공무원", kr: "우선은 고지대 경로부터 표지판을 재정비하고 그다음 단계로 넘어가겠습니다.", en: "First we'll overhaul the signage for the high-ground routes, then move on to the next stage." },
    ],
  },
];

export const DIRECTIONS_C_QUIZZES: Record<string, DialogueQuiz> = {
  "directions-c1y-subway-hearing": {
    q: "What does the resident ask the official to do at the end of the hearing?",
    opts: [
      "Cancel the extension entirely",
      "Move the new station closer to the neighborhood",
      "Put the shuttle bus promise in writing",
      "Reduce the fare for the new line",
    ],
    ans: 2,
  },
  "directions-c1y-gentrification": {
    q: "According to the resident, what is bittersweet about giving directions now?",
    opts: [
      "Having to use English instead of Korean",
      "Having to pay a toll to enter the alley",
      "Having to describe the route using cafe names instead of the alley's old name",
      "Having to walk further because roads were closed",
    ],
    ans: 2,
  },
  "directions-c1y-15min-city": {
    q: "How does the planner say outlying commuters will reach the 15-minute zone?",
    opts: [
      "By being banned from driving entirely",
      "By paying a special congestion fee",
      "By walking the entire distance",
      "Through expanded transfer hubs connecting to public transit",
    ],
    ans: 3,
  },
  "directions-c1y-wayfinding-blind": {
    q: "What backup solution does the designer mention for elderly users who cannot use the app?",
    opts: [
      "Larger tactile paving blocks",
      "Free staff guides at every station",
      "Audible beacons that can be followed without the app",
      "Braille-only signage",
    ],
    ans: 2,
  },
  "directions-c1y-walking-tour": {
    q: "What does the historian reveal about the road the tourists just walked on?",
    opts: [
      "It was the original fortress wall",
      "It was reserved only for soldiers",
      "It was the site of the old royal palace",
      "It was a covered-over stream that once was a waterway",
    ],
    ans: 3,
  },
  "directions-c1y-self-driving-streets": {
    q: "What solution does the expert mention as more realistic than dedicated lanes for autonomous vehicles?",
    opts: [
      "Banning human drivers from the road",
      "Installing more traffic cameras",
      "Widening every existing lane",
      "Burying guidance lines beneath the road surface",
    ],
    ans: 3,
  },
  "directions-c1y-street-closure-town-hall": {
    q: "What exception does the official propose for urgent daytime deliveries?",
    opts: [
      "No exceptions will be allowed at all",
      "Deliveries must wait until the pilot period ends",
      "A separate permit issued instantly through online application",
      "Only bicycle deliveries will be permitted",
    ],
    ans: 2,
  },
  "directions-c1y-layout-behavior": {
    q: "According to the architect, what do recent apartment complexes deliberately do with pathways?",
    opts: [
      "Make them perfectly straight for efficiency",
      "Remove all pedestrian paths",
      "Widen them to fit more traffic",
      "Bend them slightly so they pass through community spaces",
    ],
    ans: 3,
  },
  "directions-c1y-congestion-pricing-coffee": {
    q: "What does friend 2 say the congestion pricing revenue will be used for?",
    opts: [
      "Building new highways",
      "Subsidizing gas prices",
      "Expanding public transit",
      "Funding city hall renovations",
    ],
    ans: 2,
  },
  "directions-c2y-heritage-vs-redevelop": {
    q: "What safety concern does the resident raise about preserving the alley?",
    opts: [
      "The alley floods every year",
      "The alley has no streetlights",
      "A fire truck cannot enter the alley in an emergency",
      "The alley is too far from the subway",
    ],
    ans: 2,
  },
  "directions-c2y-algorithmic-navigation": {
    q: "What is the columnist's main criticism of the developer's explanation?",
    opts: [
      "The algorithm is too slow to compute routes",
      "The app charges too much money",
      "Lack of intent doesn't remove responsibility for the social outcome",
      "The app doesn't work in rural areas",
    ],
    ans: 2,
  },
  "directions-c2y-desire-lines": {
    q: "How does the designer say their firm now treats the first blueprint?",
    opts: [
      "As a legally binding final document",
      "As something to be discarded immediately",
      "As a template to be reused everywhere",
      "As a hypothesis subject to post-opening revision",
    ],
    ans: 3,
  },
  "directions-c2y-toponym-erasure": {
    q: "What example does the toponymist give of information embedded in an old place name?",
    opts: [
      "A number indicating population size",
      "The name of a former mayor",
      "Topographical information about a reed-covered hill pass",
      "A reference to a nearby river's width",
    ],
    ans: 2,
  },
  "directions-c2y-superblock-debate": {
    q: "What complaint does panel 1 raise about large stores under the superblock policy?",
    opts: [
      "Their rent has increased sharply",
      "They have lost all their customers",
      "They are being forced to relocate",
      "Their logistics costs surged due to blocked delivery vehicle access",
    ],
    ans: 3,
  },
  "directions-c2y-ferry-terminal-signage": {
    q: "What limitation does journalist 2 note about relying only on pictograms?",
    opts: [
      "They are too expensive to install",
      "They cannot be seen in low light",
      "They are illegal under international regulations",
      "They struggle to convey detailed direction like a specific gate number",
    ],
    ans: 3,
  },
  "directions-c2y-street-vendor-informal-map": {
    q: "How does the vendor describe the nature of their informally shared map?",
    opts: [
      "A tourist attraction map",
      "A map for survival, not for tourists",
      "An official government document",
      "A map used only for advertising",
    ],
    ans: 1,
  },
  "directions-c2y-flood-evacuation-route": {
    q: "Why were the existing evacuation routes found ineffective after the flood?",
    opts: [
      "They were too long to walk quickly",
      "The shortest routes passed through low-lying, flood-prone areas",
      "They were blocked by construction",
      "They had no signage at all",
    ],
    ans: 1,
  },
};
