import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Directions situation expansion (2026-08): raises A1-B2 coverage to 20 dialogues per level.
export const DIRECTIONS_EXPANSION: Dialogue[] = [
  // ---------- A1 (15) ----------
  {
    id: "directions-a1x-bank",
    situationKey: "directions",
    level: "A1",
    title: { en: "Where's the nearest bank?", ja: "一番近い銀行はどこ？", zh: "最近的银行在哪里？" },
    lines: [
      { speaker: "행인", kr: "저기요, 은행이 어디에 있어요?", en: "Excuse me, where's the bank?", ja: "すみません、銀行はどこですか？", zh: "请问，银行在哪里？" },
      { speaker: "주민", kr: "저기 편의점 옆에 있어요.", en: "It's next to the convenience store over there.", ja: "あそこのコンビニの隣にあります。", zh: "在那边便利店旁边。" },
      { speaker: "행인", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
      { speaker: "주민", kr: "네, 안녕히 가세요.", en: "You're welcome, take care.", ja: "はい、お気をつけて。", zh: "不客气，慢走。" },
    ],
  },
  {
    id: "directions-a1x-atm",
    situationKey: "directions",
    level: "A1",
    title: { en: "Finding an ATM", ja: "ATMを探す", zh: "寻找取款机" },
    lines: [
      { speaker: "행인", kr: "여기 근처에 현금인출기가 있어요?", en: "Is there an ATM near here?", ja: "この近くにATMがありますか？", zh: "这附近有取款机吗？" },
      { speaker: "주민", kr: "네, 이 건물 안에 있어요.", en: "Yes, it's inside this building.", ja: "はい、この建物の中にあります。", zh: "有，就在这栋楼里。" },
      { speaker: "행인", kr: "몇 층이에요?", en: "What floor?", ja: "何階ですか？", zh: "在几楼？" },
      { speaker: "주민", kr: "1층이에요.", en: "The first floor.", ja: "一階です。", zh: "一楼。" },
    ],
  },
  {
    id: "directions-a1x-pharmacy-closed",
    situationKey: "directions",
    level: "A1",
    title: { en: "Pharmacy after hours", ja: "営業時間外の薬局", zh: "药店打烊后" },
    lines: [
      { speaker: "행인", kr: "약국이 문을 닫았어요.", en: "The pharmacy is closed.", ja: "薬局が閉まっています。", zh: "药店关门了。" },
      { speaker: "주민", kr: "다른 약국은 저기 있어요.", en: "There's another pharmacy over there.", ja: "別の薬局があそこにあります。", zh: "那边还有一家药店。" },
      { speaker: "행인", kr: "멀어요?", en: "Is it far?", ja: "遠いですか？", zh: "远吗？" },
      { speaker: "주민", kr: "아니요, 가까워요.", en: "No, it's close.", ja: "いいえ、近いです。", zh: "不远，很近。" },
    ],
  },
  {
    id: "directions-a1x-crosswalk",
    situationKey: "directions",
    level: "A1",
    title: { en: "Crossing to the bus stop", ja: "バス停まで横断する", zh: "过马路去公交站" },
    lines: [
      { speaker: "행인", kr: "버스 정류장이 길 건너에 있어요?", en: "Is the bus stop across the street?", ja: "バス停は道の向こう側にありますか？", zh: "公交站在马路对面吗？" },
      { speaker: "주민", kr: "네, 저기 횡단보도로 건너세요.", en: "Yes, cross at that crosswalk.", ja: "はい、あの横断歩道を渡ってください。", zh: "是的，从那个人行横道过去。" },
      { speaker: "행인", kr: "알겠습니다, 감사해요.", en: "Got it, thanks.", ja: "わかりました、ありがとうございます。", zh: "明白了，谢谢。" },
      { speaker: "주민", kr: "조심히 가세요.", en: "Take care crossing.", ja: "気をつけて渡ってください。", zh: "过马路小心点。" },
    ],
  },
  {
    id: "directions-a1x-airport-platform",
    situationKey: "directions",
    level: "A1",
    title: { en: "Platform for the airport train", ja: "空港鉄道のホーム", zh: "机场铁路站台" },
    lines: [
      { speaker: "행인", kr: "공항철도는 몇 번 승강장이에요?", en: "Which platform is the airport train?", ja: "空港鉄道は何番ホームですか？", zh: "机场铁路是几号站台？" },
      { speaker: "역무원", kr: "3번 승강장이에요.", en: "Platform 3.", ja: "3番ホームです。", zh: "三号站台。", vi: "(Platform 3.)" },
      { speaker: "행인", kr: "이쪽이 맞아요?", en: "Is it this way?", ja: "こっちで合っていますか？", zh: "是这边吗？" },
      { speaker: "역무원", kr: "네, 맞아요.", en: "Yes, that's right.", ja: "はい、そうです。", zh: "对，没错。", vi: "có that's đúng" },
    ],
  },
  {
    id: "directions-a1x-elevator",
    situationKey: "directions",
    level: "A1",
    title: { en: "Elevator or stairs", ja: "エレベーターか階段か", zh: "坐电梯还是走楼梯" },
    lines: [
      { speaker: "행인", kr: "엘리베이터가 어디에 있어요?", en: "Where's the elevator?", ja: "エレベーターはどこですか？", zh: "电梯在哪里？" },
      { speaker: "역무원", kr: "계단 옆에 있어요.", en: "It's next to the stairs.", ja: "階段の隣にあります。", zh: "在楼梯旁边。" },
      { speaker: "행인", kr: "계단으로 가도 돼요?", en: "Can I take the stairs too?", ja: "階段で行ってもいいですか？", zh: "可以走楼梯吗？" },
      { speaker: "역무원", kr: "네, 둘 다 괜찮아요.", en: "Yes, either is fine.", ja: "はい、どちらでも大丈夫です。", zh: "可以，两个都行。" },
    ],
  },
  {
    id: "directions-a1x-last-train",
    situationKey: "directions",
    level: "A1",
    title: { en: "Last train time", ja: "最終電車の時間", zh: "末班车时间" },
    lines: [
      { speaker: "행인", kr: "막차가 몇 시예요?", en: "What time is the last train?", ja: "最終電車は何時ですか？", zh: "末班车是几点？" },
      { speaker: "역무원", kr: "밤 12시예요.", en: "It's midnight.", ja: "夜の十二時です。", zh: "是凌晨十二点。" },
      { speaker: "행인", kr: "아직 시간이 있네요.", en: "There's still time.", ja: "まだ時間がありますね。", zh: "那还有时间。" },
      { speaker: "역무원", kr: "네, 서두르세요.", en: "Yes, but hurry.", ja: "はい、でも急いでください。", zh: "有，不过要抓紧。" },
    ],
  },
  {
    id: "directions-a1x-card-tap",
    situationKey: "directions",
    level: "A1",
    title: { en: "Where to tap the transit card", ja: "交通カードをかざす場所", zh: "交通卡刷卡位置" },
    lines: [
      { speaker: "행인", kr: "카드를 어디에 대요?", en: "Where do I tap my card?", ja: "カードはどこにかざしますか？", zh: "卡要刷在哪里？" },
      { speaker: "역무원", kr: "여기 초록색 부분이에요.", en: "Here, on the green part.", ja: "ここの緑色の部分です。", zh: "就在这个绿色的地方。" },
      { speaker: "행인", kr: "이렇게요?", en: "Like this?", ja: "こうですか？", zh: "这样吗？", vi: "thích this?" },
      { speaker: "역무원", kr: "네, 맞아요.", en: "Yes, that's right.", ja: "はい、そうです。", zh: "对，没错。", vi: "có that's đúng" },
    ],
  },
  {
    id: "directions-a1x-parking-entrance",
    situationKey: "directions",
    level: "A1",
    title: { en: "Parking lot entrance", ja: "駐車場の入口", zh: "停车场入口" },
    lines: [
      { speaker: "기사", kr: "주차장 입구가 어디예요?", en: "Where's the parking lot entrance?", ja: "駐車場の入口はどこですか？", zh: "停车场入口在哪里？" },
      { speaker: "안내원", kr: "건물 뒤쪽에 있어요.", en: "It's behind the building.", ja: "建物の裏側にあります。", zh: "在大楼后面。" },
      { speaker: "기사", kr: "차로 가면 돼요?", en: "Can I drive there?", ja: "車で行けますか？", zh: "可以开车过去吗？" },
      { speaker: "안내원", kr: "네, 바로 가세요.", en: "Yes, go straight there.", ja: "はい、まっすぐ行ってください。", zh: "可以，直接开过去就行。" },
    ],
  },
  {
    id: "directions-a1x-plaza-meet",
    situationKey: "directions",
    level: "A1",
    title: { en: "Meeting point at the plaza", ja: "広場での待ち合わせ場所", zh: "广场集合地点" },
    lines: [
      { speaker: "행인", kr: "광장 어디에서 만나요?", en: "Where in the plaza should we meet?", ja: "広場のどこで会いましょうか？", zh: "在广场哪里见面？" },
      { speaker: "주민", kr: "분수대 앞에서 만나요.", en: "Let's meet in front of the fountain.", ja: "噴水の前で会いましょう。", zh: "我们在喷泉前见吧。" },
      { speaker: "행인", kr: "네, 좋아요.", en: "Okay, sounds good.", ja: "はい、いいですね。", zh: "好，没问题。" },
      { speaker: "주민", kr: "이따 봐요.", en: "See you then.", ja: "それじゃまた後で。", zh: "那到时候见。" },
    ],
  },
  {
    id: "directions-a1x-cafe-restroom-code",
    situationKey: "directions",
    level: "A1",
    title: { en: "Cafe restroom code", ja: "カフェのトイレの暗証番号", zh: "咖啡厅洗手间密码" },
    lines: [
      { speaker: "손님", kr: "화장실 비밀번호가 뭐예요?", en: "What's the restroom code?", ja: "トイレの暗証番号は何ですか？", zh: "洗手间的密码是多少？" },
      { speaker: "직원", kr: "영수증에 있어요.", en: "It's on the receipt.", ja: "レシートに書いてあります。", zh: "在小票上。" },
      { speaker: "손님", kr: "아, 여기 있네요.", en: "Oh, here it is.", ja: "あ、ここにありますね。", zh: "哦，在这里。" },
      { speaker: "직원", kr: "네, 맞아요.", en: "Yes, that's it.", ja: "はい、それです。", zh: "对，就是那个。" },
    ],
  },
  {
    id: "directions-a1x-exit-number",
    situationKey: "directions",
    level: "A1",
    title: { en: "Which exit number", ja: "何番出口か", zh: "是几号出口" },
    lines: [
      { speaker: "행인", kr: "몇 번 출구예요?", en: "Which exit number?", ja: "何番出口ですか？", zh: "是几号出口？" },
      { speaker: "주민", kr: "5번 출구예요.", en: "Exit 5.", ja: "5番出口です。", zh: "五号出口。", vi: "(Exit 5.)" },
      { speaker: "행인", kr: "여기서 멀어요?", en: "Is it far from here?", ja: "ここから遠いですか？", zh: "离这里远吗？" },
      { speaker: "주민", kr: "아니요, 바로 앞이에요.", en: "No, it's right there.", ja: "いいえ、すぐそこです。", zh: "不远，就在那边。" },
    ],
  },
  {
    id: "directions-a1x-post-office",
    situationKey: "directions",
    level: "A1",
    title: { en: "Finding the post office", ja: "郵便局を探す", zh: "寻找邮局" },
    lines: [
      { speaker: "행인", kr: "우체국이 어디예요?", en: "Where's the post office?", ja: "郵便局はどこですか？", zh: "邮局在哪里？" },
      { speaker: "주민", kr: "사거리에서 왼쪽이에요.", en: "It's on the left at the intersection.", ja: "交差点を左に行ったところです。", zh: "在十字路口的左边。" },
      { speaker: "행인", kr: "걸어서 가까워요?", en: "Is it close to walk?", ja: "歩いて近いですか？", zh: "走路近吗？" },
      { speaker: "주민", kr: "네, 5분이면 돼요.", en: "Yes, five minutes is enough.", ja: "はい、五分で着きます。", zh: "近，走五分钟就到。" },
    ],
  },
  {
    id: "directions-a1x-taxi-stand",
    situationKey: "directions",
    level: "A1",
    title: { en: "Taxi stand location", ja: "タクシー乗り場の場所", zh: "出租车站位置" },
    lines: [
      { speaker: "행인", kr: "택시 타는 곳이 어디예요?", en: "Where do I catch a taxi?", ja: "タクシー乗り場はどこですか？", zh: "打车的地方在哪里？" },
      { speaker: "안내원", kr: "정문 밖에 있어요.", en: "It's outside the main gate.", ja: "正門の外にあります。", zh: "在正门外面。" },
      { speaker: "행인", kr: "줄이 길어요?", en: "Is the line long?", ja: "列は長いですか？", zh: "队排得长吗？", vi: "là the dòng dài" },
      { speaker: "안내원", kr: "지금은 짧아요.", en: "It's short right now.", ja: "今は短いです。", zh: "现在不长。" },
    ],
  },
  {
    id: "directions-a1x-park-entrance",
    situationKey: "directions",
    level: "A1",
    title: { en: "Park entrance", ja: "公園の入口", zh: "公园入口" },
    lines: [
      { speaker: "행인", kr: "공원 입구가 어디예요?", en: "Where's the park entrance?", ja: "公園の入口はどこですか？", zh: "公园入口在哪里？" },
      { speaker: "주민", kr: "다리를 건너면 있어요.", en: "It's after you cross the bridge.", ja: "橋を渡ったところにあります。", zh: "过了桥就是。" },
      { speaker: "행인", kr: "고맙습니다.", en: "Thanks.", ja: "ありがとうございます。", zh: "谢谢。", vi: "(Thanks.)" },
      { speaker: "주민", kr: "천천히 가세요.", en: "Take your time getting there.", ja: "ゆっくり行ってください。", zh: "慢慢走过去就行。" },
    ],
  },
  // ---------- A2 (15) ----------
  {
    id: "directions-a2x-lost-card",
    situationKey: "directions",
    level: "A2",
    title: { en: "Lost transit card gate", ja: "交通カードでゲートが開かない", zh: "交通卡卡在闸机口" },
    lines: [
      { speaker: "행인", kr: "교통카드를 찍었는데 문이 안 열렸어요.", en: "I tapped my transit card but the gate didn't open.", ja: "交通カードをタッチしたのにゲートが開きませんでした。", zh: "我刷了交通卡，但闸机没开。" },
      { speaker: "역무원", kr: "카드에 잔액이 있었어요?", en: "Did the card have enough balance?", ja: "カードの残高はありましたか？", zh: "卡里余额够吗？" },
      { speaker: "행인", kr: "아까 충전했는데 이상하네요.", en: "I topped it up earlier, that's strange.", ja: "さっきチャージしたんですが、おかしいですね。", zh: "我刚才充值了，很奇怪。" },
      { speaker: "역무원", kr: "여기 다시 찍어 보세요.", en: "Try tapping again here.", ja: "ここでもう一度タッチしてみてください。", zh: "在这里再刷一次试试。" },
      { speaker: "행인", kr: "아, 이제 열렸어요.", en: "Oh, it opened now.", ja: "あ、今度は開きました。", zh: "哦，这次开了。" },
    ],
  },
  {
    id: "directions-a2x-bank-hours",
    situationKey: "directions",
    level: "A2",
    title: { en: "Bank closing soon", ja: "もうすぐ閉まる銀行", zh: "银行快关门了" },
    lines: [
      { speaker: "행인", kr: "은행이 몇 시까지 열어요?", en: "Until what time is the bank open?", ja: "銀行は何時まで開いていますか？", zh: "银行开到几点？" },
      { speaker: "주민", kr: "4시까지였는데 지금 3시 50분이에요.", en: "It was until 4, and it's 3:50 now.", ja: "四時までだったんですが、今三時五十分です。", zh: "本来到四点，现在是三点五十分。" },
      { speaker: "행인", kr: "그럼 빨리 가야겠어요.", en: "Then I should hurry.", ja: "それでは急がないと。", zh: "那我得快点了。" },
      { speaker: "주민", kr: "뛰어가면 늦지 않을 거예요.", en: "If you run, you won't be late.", ja: "走れば間に合いますよ。", zh: "跑过去就不会迟。" },
      { speaker: "행인", kr: "네, 가 볼게요!", en: "Okay, I'll go now!", ja: "はい、行ってきます！", zh: "好，我这就去！" },
    ],
  },
  {
    id: "directions-a2x-pharmacy-night",
    situationKey: "directions",
    level: "A2",
    title: { en: "24-hour pharmacy", ja: "24時間営業の薬局", zh: "24小时药店" },
    lines: [
      { speaker: "행인", kr: "밤에도 여는 약국이 있어요?", en: "Is there a pharmacy open at night?", ja: "夜も開いている薬局はありますか？", zh: "有晚上也营业的药店吗？" },
      { speaker: "주민", kr: "네, 역 앞에 24시간 약국이 있어요.", en: "Yes, there's a 24-hour pharmacy in front of the station.", ja: "はい、駅前に二十四時間営業の薬局があります。", zh: "有，车站前有一家二十四小时药店。" },
      { speaker: "행인", kr: "거기까지 얼마나 걸려요?", en: "How long does it take to get there?", ja: "そこまでどのくらいかかりますか？", zh: "到那里要多久？" },
      { speaker: "주민", kr: "걸어서 십 분쯤 걸릴 거예요.", en: "It'll take about ten minutes on foot.", ja: "歩いて十分くらいかかります。", zh: "走路大概十分钟。" },
      { speaker: "행인", kr: "알겠어요, 가 볼게요.", en: "Okay, I'll go check it out.", ja: "わかりました、行ってみます。", zh: "好，我去看看。" },
    ],
  },
  {
    id: "directions-a2x-bus-stop-side",
    situationKey: "directions",
    level: "A2",
    title: { en: "Wrong side of the street", ja: "道の反対側だった", zh: "站错了马路对面" },
    lines: [
      { speaker: "행인", kr: "이 정류장에서 시청 가는 버스 타요?", en: "Do I catch the City Hall bus from this stop?", ja: "このバス停から市庁舎行きのバスに乗れますか？", zh: "在这个站能坐到市政厅的车吗？" },
      { speaker: "주민", kr: "아니요, 그건 반대쪽 정류장이에요.", en: "No, that's on the stop across the street.", ja: "いいえ、それは道の反対側のバス停です。", zh: "不行，那趟车要在马路对面坐。" },
      { speaker: "행인", kr: "그럼 어떻게 건너가요?", en: "Then how do I cross over?", ja: "それではどうやって渡ればいいですか？", zh: "那要怎么过去？" },
      { speaker: "주민", kr: "저 육교로 건너면 돼요.", en: "You can cross using that overpass.", ja: "あの歩道橋で渡れます。", zh: "可以走那座天桥过去。" },
      { speaker: "행인", kr: "네, 감사합니다.", en: "Okay, thank you.", ja: "はい、ありがとうございます。", zh: "好的，谢谢。" },
    ],
  },
  {
    id: "directions-a2x-airport-checkin",
    situationKey: "directions",
    level: "A2",
    title: { en: "Airport train check-in counter", ja: "空港鉄道のチェックインカウンター", zh: "机场铁路值机柜台" },
    lines: [
      { speaker: "행인", kr: "공항철도에서 수하물을 미리 부칠 수 있어요?", en: "Can I check my luggage in advance on the airport train?", ja: "空港鉄道で荷物を事前に預けられますか？", zh: "在机场铁路可以提前托运行李吗？" },
      { speaker: "역무원", kr: "네, 도심공항터미널에서 가능해요.", en: "Yes, it's possible at the city air terminal.", ja: "はい、都心空港ターミナルで可能です。", zh: "可以，在市区机场航站楼就能办。" },
      { speaker: "행인", kr: "그게 어디에 있어요?", en: "Where is that?", ja: "それはどこにありますか？", zh: "那个在哪里？" },
      { speaker: "역무원", kr: "2번 출구로 나가면 바로 보여요.", en: "Go out exit 2 and you'll see it right away.", ja: "二番出口を出るとすぐ見えます。", zh: "出二号口就能马上看到。" },
      { speaker: "행인", kr: "좋아요, 가 볼게요.", en: "Great, I'll head there.", ja: "いいですね、行ってみます。", zh: "好，我去那边看看。" },
    ],
  },
  {
    id: "directions-a2x-elevator-broken",
    situationKey: "directions",
    level: "A2",
    title: { en: "Elevator out of order", ja: "故障中のエレベーター", zh: "电梯故障" },
    lines: [
      { speaker: "행인", kr: "엘리베이터가 고장 났어요.", en: "The elevator is broken.", ja: "エレベーターが故障しています。", zh: "电梯坏了。" },
      { speaker: "역무원", kr: "네, 오늘 오전부터 수리 중이에요.", en: "Yes, it's been under repair since this morning.", ja: "はい、今日の午前から修理中です。", zh: "是的，从今天上午开始就在维修。" },
      { speaker: "행인", kr: "그럼 짐을 들고 계단으로 가야 해요?", en: "So I have to carry my luggage on the stairs?", ja: "それじゃあ荷物を持って階段で行かなきゃいけないんですか？", zh: "那我得拿着行李走楼梯了？" },
      { speaker: "역무원", kr: "휠체어 리프트를 쓰실 수 있어요.", en: "You can use the wheelchair lift instead.", ja: "車椅子用リフトを使えますよ。", zh: "可以用轮椅升降梯代替。" },
      { speaker: "행인", kr: "아, 다행이네요.", en: "Oh, that's a relief.", ja: "ああ、よかったです。", zh: "哦，那就好。" },
    ],
  },
  {
    id: "directions-a2x-parking-full",
    situationKey: "directions",
    level: "A2",
    title: { en: "Parking lot full", ja: "満車の駐車場", zh: "停车场已满" },
    lines: [
      { speaker: "기사", kr: "여기 주차장이 다 찼어요.", en: "This parking lot is full.", ja: "ここの駐車場は満車です。", zh: "这里的停车场满了。" },
      { speaker: "안내원", kr: "네, 뒤쪽에 다른 주차장이 있어요.", en: "Yes, there's another lot behind here.", ja: "はい、この裏にもう一つ駐車場があります。", zh: "是的，后面还有一个停车场。" },
      { speaker: "기사", kr: "거기는 자리가 있어요?", en: "Are there spots there?", ja: "そこは空きがありますか？", zh: "那边有空位吗？" },
      { speaker: "안내원", kr: "방금 확인했는데 몇 자리 남았어요.", en: "I just checked, and a few spots are left.", ja: "さっき確認したんですが、いくつか空きがあります。", zh: "刚查过，还剩几个位置。" },
      { speaker: "기사", kr: "그럼 그쪽으로 갈게요.", en: "Then I'll head over there.", ja: "それではそちらに行きます。", zh: "那我去那边。" },
    ],
  },
  {
    id: "directions-a2x-plaza-crowded",
    situationKey: "directions",
    level: "A2",
    title: { en: "Finding a friend in a crowded plaza", ja: "混雑した広場で友達を探す", zh: "在拥挤的广场找朋友" },
    lines: [
      { speaker: "행인", kr: "광장에 사람이 너무 많아서 못 찾겠어요.", en: "There are too many people in the plaza, I can't find them.", ja: "広場に人が多すぎて見つけられません。", zh: "广场上人太多，我找不到人了。" },
      { speaker: "주민", kr: "무슨 색 옷을 입었어요?", en: "What color clothes are they wearing?", ja: "何色の服を着ていますか？", zh: "对方穿什么颜色的衣服？" },
      { speaker: "행인", kr: "빨간 재킷을 입었어요.", en: "They're wearing a red jacket.", ja: "赤いジャケットを着ています。", zh: "穿着一件红色外套。" },
      { speaker: "주민", kr: "저기 시계탑 근처에 있는 것 같아요.", en: "I think they're near the clock tower over there.", ja: "あそこの時計塔の近くにいると思います。", zh: "我猜他们在那边的钟楼附近。" },
      { speaker: "행인", kr: "아, 찾았어요, 고마워요!", en: "Oh, I found them, thanks!", ja: "あ、見つけました、ありがとうございます！", zh: "哦，找到了，谢谢！" },
    ],
  },
  {
    id: "directions-a2x-cafe-code-changed",
    situationKey: "directions",
    level: "A2",
    title: { en: "Restroom code changed", ja: "トイレの暗証番号が変わった", zh: "洗手间密码变了" },
    lines: [
      { speaker: "손님", kr: "비밀번호를 눌렀는데 안 열려요.", en: "I entered the code but it won't open.", ja: "暗証番号を押したのに開きません。", zh: "我输了密码，但门没开。" },
      { speaker: "직원", kr: "어제 비밀번호가 바뀌었어요.", en: "The code changed yesterday.", ja: "昨日暗証番号が変わりました。", zh: "密码昨天改了。" },
      { speaker: "손님", kr: "새 비밀번호가 뭐예요?", en: "What's the new code?", ja: "新しい暗証番号は何ですか？", zh: "新密码是多少？" },
      { speaker: "직원", kr: "여기 영수증 아래에 적혀 있어요.", en: "It's written at the bottom of the receipt here.", ja: "ここのレシートの下に書いてあります。", zh: "写在这张小票的下面。" },
      { speaker: "손님", kr: "아, 찾았어요.", en: "Oh, found it.", ja: "あ、見つけました。", zh: "哦，找到了。" },
    ],
  },
  {
    id: "directions-a2x-market-entrance",
    situationKey: "directions",
    level: "A2",
    title: { en: "Market entrance blocked", ja: "市場の入口が塞がれている", zh: "市场入口被封" },
    lines: [
      { speaker: "행인", kr: "시장 정문이 공사 중이에요.", en: "The market's main entrance is under construction.", ja: "市場の正門が工事中です。", zh: "市场的正门在施工。" },
      { speaker: "주민", kr: "그럼 옆문으로 들어가야 해요.", en: "Then you have to go in through the side door.", ja: "それでは横のドアから入らないといけませんね。", zh: "那得从旁边的门进去了。" },
      { speaker: "행인", kr: "옆문은 어디에 있어요?", en: "Where's the side door?", ja: "横のドアはどこですか？", zh: "旁边的门在哪里？" },
      { speaker: "주민", kr: "저 골목 끝에 있어요.", en: "It's at the end of that alley.", ja: "あの路地の突き当たりにあります。", zh: "在那条巷子尽头。" },
      { speaker: "행인", kr: "알겠어요, 감사합니다.", en: "Got it, thank you.", ja: "わかりました、ありがとうございます。", zh: "明白了，谢谢。" },
    ],
  },
  {
    id: "directions-a2x-hospital-wing",
    situationKey: "directions",
    level: "A2",
    title: { en: "Which hospital wing", ja: "病院のどの棟か", zh: "医院哪一栋" },
    lines: [
      { speaker: "행인", kr: "응급실은 어느 쪽이에요?", en: "Which way is the emergency room?", ja: "救急室はどちらですか？", zh: "急诊室在哪边？" },
      { speaker: "안내원", kr: "본관 말고 별관에 있어요.", en: "It's in the annex, not the main building.", ja: "本館ではなく別館にあります。", zh: "不在主楼，在别馆。" },
      { speaker: "행인", kr: "별관은 어떻게 가요?", en: "How do I get to the annex?", ja: "別館へはどう行けばいいですか？", zh: "怎么去别馆？" },
      { speaker: "안내원", kr: "밖으로 나가서 오른쪽으로 가세요.", en: "Go outside and head to the right.", ja: "外に出て右に進んでください。", zh: "出去以后往右走。" },
      { speaker: "행인", kr: "네, 빨리 가 볼게요.", en: "Okay, I'll hurry over.", ja: "はい、急いで行きます。", zh: "好，我赶紧过去。" },
    ],
  },
  {
    id: "directions-a2x-luggage-locker",
    situationKey: "directions",
    level: "A2",
    title: { en: "Finding a luggage locker", ja: "荷物用ロッカーを探す", zh: "寻找行李寄存柜" },
    lines: [
      { speaker: "행인", kr: "짐 보관함이 이 근처에 있어요?", en: "Is there a luggage locker near here?", ja: "この近くに荷物用のロッカーはありますか？", zh: "这附近有行李寄存柜吗？" },
      { speaker: "역무원", kr: "네, 개찰구를 지나면 바로 있어요.", en: "Yes, right after you pass the ticket gate.", ja: "はい、改札を出てすぐのところにあります。", zh: "有，一过检票口就是。" },
      { speaker: "행인", kr: "요금은 얼마예요?", en: "How much does it cost?", ja: "料金はいくらですか？", zh: "多少钱？" },
      { speaker: "역무원", kr: "크기에 따라 다른데 보통 삼천 원이에요.", en: "It depends on the size, but it's usually 3,000 won.", ja: "3,000ウォン", zh: "3,000韩元", vi: "3,000 won" },
      { speaker: "행인", kr: "좋아요, 써 볼게요.", en: "Great, I'll use it.", ja: "いいですね、使ってみます。", zh: "好，我用一下。" },
    ],
  },
  {
    id: "directions-a2x-stadium-gate",
    situationKey: "directions",
    level: "A2",
    title: { en: "Which gate at the stadium", ja: "競技場の何番ゲートか", zh: "体育场的几号门" },
    lines: [
      { speaker: "행인", kr: "제 자리가 몇 번 게이트예요?", en: "What gate is my seat at?", ja: "私の席は何番ゲートですか？", zh: "我的座位是几号门？" },
      { speaker: "안내원", kr: "표를 보여 주시겠어요?", en: "Could you show me your ticket?", ja: "チケットを見せていただけますか？", zh: "能给我看一下票吗？" },
      { speaker: "행인", kr: "여기요.", en: "Here it is.", ja: "これです。", zh: "在这里。" },
      { speaker: "안내원", kr: "7번 게이트로 가시면 돼요.", en: "You should go to gate 7.", ja: "七番ゲートへ行ってください。", zh: "您去七号门就行。" },
      { speaker: "행인", kr: "감사합니다, 찾아볼게요.", en: "Thanks, I'll head there.", ja: "ありがとうございます、行ってみます。", zh: "谢谢，我这就去。" },
    ],
  },
  {
    id: "directions-a2x-school-visitor",
    situationKey: "directions",
    level: "A2",
    title: { en: "Visitor entrance at a school", ja: "学校の来訪者用入口", zh: "学校访客入口" },
    lines: [
      { speaker: "행인", kr: "방문객은 어디로 들어가요?", en: "Where do visitors enter?", ja: "来訪者はどこから入りますか？", zh: "访客从哪里进？" },
      { speaker: "안내원", kr: "정문이 아니라 후문으로 오셔야 해요.", en: "You need to come through the back gate, not the front.", ja: "正門ではなく裏門から来てください。", zh: "不是正门，得从后门进。" },
      { speaker: "행인", kr: "후문은 여기서 멀어요?", en: "Is the back gate far from here?", ja: "裏門はここから遠いですか？", zh: "后门离这里远吗？" },
      { speaker: "안내원", kr: "차로 이 분 정도 걸려요.", en: "It takes about two minutes by car.", ja: "車で二分くらいかかります。", zh: "开车大概两分钟。" },
      { speaker: "행인", kr: "네, 이동할게요.", en: "Okay, I'll head over.", ja: "はい、移動します。", zh: "好，我这就过去。" },
    ],
  },
  {
    id: "directions-a2x-gym-floor",
    situationKey: "directions",
    level: "A2",
    title: { en: "Which floor for the gym", ja: "ジムは何階か", zh: "健身房在几楼" },
    lines: [
      { speaker: "행인", kr: "헬스장이 몇 층이에요?", en: "What floor is the gym on?", ja: "ジムは何階にありますか？", zh: "健身房在几楼？" },
      { speaker: "안내원", kr: "지하 1층이에요.", en: "It's on basement floor 1.", ja: "地下一階です。", zh: "在地下一楼。" },
      { speaker: "행인", kr: "엘리베이터로 가면 돼요?", en: "Can I take the elevator?", ja: "エレベーターで行けますか？", zh: "可以坐电梯吗？" },
      { speaker: "안내원", kr: "네, B1 버튼을 누르시면 돼요.", en: "Yes, just press the B1 button.", ja: "はい、B1のボタンを押してください。", zh: "可以，按B1的按钮就行。" },
      { speaker: "행인", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
    ],
  },
  // ---------- B1 (16) ----------
  {
    id: "directions-b1x-one-way-confusion",
    situationKey: "directions",
    level: "B1",
    title: { en: "Confused by a one-way street", ja: "一方通行の道に戸惑う", zh: "被单行道搞糊涂了" },
    lines: [
      { speaker: "기사", kr: "여기가 일방통행인 줄 몰랐어요.", en: "I didn't realize this was a one-way street.", ja: "ここが一方通行だとは知りませんでした。", zh: "我没意识到这里是单行道。" },
      { speaker: "경찰", kr: "네, 표지판을 못 보신 것 같네요.", en: "Right, it seems you missed the sign.", ja: "ええ、標識を見落とされたようですね。", zh: "对，您好像没看到标志。" },
      { speaker: "기사", kr: "그럼 이제 어떻게 나가야 해요?", en: "So how do I get out now?", ja: "それじゃあ今どうやって出ればいいですか？", zh: "那我现在该怎么出去？" },
      { speaker: "경찰", kr: "앞으로 쭉 가시다가 다음 골목에서 우회전하세요.", en: "Go straight ahead and turn right at the next alley.", ja: "このまままっすぐ行って、次の路地で右に曲がってください。", zh: "一直往前开，在下个巷口右转。" },
      { speaker: "기사", kr: "거기서 큰길로 나갈 수 있나요?", en: "Can I get to the main road from there?", ja: "そこから大通りに出られますか？", zh: "从那里能到大路上吗？" },
      { speaker: "경찰", kr: "네, 바로 연결돼요.", en: "Yes, it connects directly.", ja: "はい、直接つながっています。", zh: "可以，直接就连着。" },
    ],
  },
  {
    id: "directions-b1x-bike-path-rules",
    situationKey: "directions",
    level: "B1",
    title: { en: "Bike path rules explained", ja: "自転車専用道路のルール説明", zh: "解释自行车道规则" },
    lines: [
      { speaker: "행인", kr: "이 길은 자전거만 다닐 수 있어요?", en: "Is this path only for bicycles?", ja: "この道は自転車専用ですか？", zh: "这条路只能骑自行车吗？" },
      { speaker: "주민", kr: "네, 걸어 다니는 구간은 따로 표시돼 있어요.", en: "Yes, the walking section is marked separately.", ja: "はい、歩行者用の区間は別に表示されています。", zh: "对，步行区域是单独标出来的。" },
      { speaker: "행인", kr: "저는 어디로 걸어야 하죠?", en: "Where should I walk, then?", ja: "それでは私はどこを歩けばいいですか？", zh: "那我该走哪里？" },
      { speaker: "주민", kr: "바닥에 초록색 선이 보행로예요.", en: "The green line on the ground is the walking path.", ja: "地面の緑色の線が歩道です。", zh: "地上的绿线就是人行道。" },
      { speaker: "행인", kr: "아, 표시가 있는지 몰랐어요.", en: "Oh, I didn't notice the marking.", ja: "あ、表示に気づきませんでした。", zh: "哦，我没注意到标线。" },
      { speaker: "주민", kr: "처음 오시면 헷갈리실 수 있어요.", en: "It can be confusing the first time you come here.", ja: "初めて来ると戸惑うかもしれません。", zh: "第一次来这里可能会搞混。" },
    ],
  },
  {
    id: "directions-b1x-night-bus",
    situationKey: "directions",
    level: "B1",
    title: { en: "Asking about the night bus", ja: "深夜バスについて尋ねる", zh: "询问夜班车" },
    lines: [
      { speaker: "행인", kr: "심야버스가 이 근처에서도 다녀요?", en: "Does the night bus run near here too?", ja: "深夜バスはこの近くも通っていますか？", zh: "夜班车也经过这附近吗？" },
      { speaker: "주민", kr: "네, 근데 노선이 낮 버스랑 좀 달라요.", en: "Yes, but the route is a bit different from the daytime bus.", ja: "はい、でも路線が昼のバスとは少し違います。", zh: "是的，不过路线和白天的车有点不一样。" },
      { speaker: "행인", kr: "그럼 정류장 위치도 다른가요?", en: "So is the stop location different too?", ja: "それではバス停の場所も違うんですか？", zh: "那站牌位置也不一样吗？" },
      { speaker: "주민", kr: "이 정류장은 같이 써요.", en: "This stop is shared for both.", ja: "このバス停はどちらも共用しています。", zh: "这个站两班车共用。" },
      { speaker: "행인", kr: "다행이네요, 헤맬 뻔했어요.", en: "That's a relief, I almost got confused.", ja: "よかった、危うく混乱するところでした。", zh: "太好了，差点搞混了。" },
      { speaker: "주민", kr: "배차 간격이 기니까 시간 확인하세요.", en: "The interval is long, so check the schedule.", ja: "運行間隔が長いので時刻を確認してください。", zh: "发车间隔比较长，请确认好时刻表。" },
    ],
  },
  {
    id: "directions-b1x-rooftop-viewpoint",
    situationKey: "directions",
    level: "B1",
    title: { en: "Finding a rooftop viewpoint", ja: "屋上の展望スポットを探す", zh: "寻找屋顶观景点" },
    lines: [
      { speaker: "행인", kr: "여기서 야경 보기 좋은 곳 있어요?", en: "Is there a good spot to see the night view from here?", ja: "ここから夜景がよく見える場所はありますか？", zh: "这附近有看夜景的好地方吗？" },
      { speaker: "주민", kr: "저 건물 옥상에 전망대가 있어요.", en: "There's an observation deck on the roof of that building.", ja: "あのビルの屋上に展望台があります。", zh: "那栋楼的天台上有个观景台。" },
      { speaker: "행인", kr: "일반인도 올라갈 수 있어요?", en: "Can regular visitors go up there too?", ja: "一般の人も上がれますか？", zh: "普通游客也能上去吗？" },
      { speaker: "주민", kr: "네, 근데 저녁 여덟 시까지만 개방해요.", en: "Yes, but it's only open until 8 PM.", ja: "はい、でも夜八時までしか開いていません。", zh: "可以，不过只开到晚上八点。" },
      { speaker: "행인", kr: "지금 가면 시간 맞겠네요.", en: "If I go now, I should make it in time.", ja: "今行けば間に合いますね。", zh: "现在去应该来得及。" },
      { speaker: "주민", kr: "엘리베이터가 좀 느리니까 서두르세요.", en: "The elevator is a bit slow, so hurry.", ja: "エレベーターが少し遅いので急いでください。", zh: "电梯有点慢，请抓紧时间。" },
    ],
  },
  {
    id: "directions-b1x-palace-shortcut",
    situationKey: "directions",
    level: "B1",
    title: { en: "Shortcut vs scenic route to the palace", ja: "宮殿への近道と景色の良い道", zh: "去宫殿的近路和风景路线" },
    lines: [
      { speaker: "행인", kr: "궁궐까지 빠른 길이랑 예쁜 길 중에 뭐가 나아요?", en: "Between the fast way and the scenic way to the palace, which is better?", ja: "宮殿まで、早い道ときれいな道とどちらがいいですか？", zh: "去宫殿，走近路还是走风景好的路更好？" },
      { speaker: "주민", kr: "빠른 길은 큰길을 따라가면 십 분이에요.", en: "The fast way is ten minutes along the main road.", ja: "早い道は大通り沿いで十分です。", zh: "近路沿大路走，十分钟。" },
      { speaker: "행인", kr: "예쁜 길은 얼마나 더 걸려요?", en: "How much longer is the scenic way?", ja: "きれいな道はどのくらい余分にかかりますか？", zh: "风景路要多花多长时间？" },
      { speaker: "주민", kr: "한옥 골목을 지나가서 이십 분쯤 걸려요.", en: "It goes through the hanok alleys, so about twenty minutes.", ja: "韓屋の路地を通るので、二十分くらいかかります。", zh: "要穿过韩屋巷子，大概二十分钟。" },
      { speaker: "행인", kr: "시간 여유가 있으니까 예쁜 길로 갈게요.", en: "Since I have time, I'll take the scenic route.", ja: "時間の余裕があるので、きれいな道で行きます。", zh: "反正有时间，我走风景路吧。" },
      { speaker: "주민", kr: "사진 찍기 좋은 곳이 많을 거예요.", en: "There will be lots of good photo spots.", ja: "写真を撮るのにいい場所がたくさんありますよ。", zh: "会有很多适合拍照的地方。" },
    ],
  },
  {
    id: "directions-b1x-delivery-phone",
    situationKey: "directions",
    level: "B1",
    title: { en: "Directing a delivery driver by phone", ja: "電話で配達員に道案内する", zh: "打电话给外卖员指路" },
    lines: [
      { speaker: "기사", kr: "고객님, 입구를 못 찾겠어요.", en: "Sir/Ma'am, I can't find the entrance.", ja: "お客様、入口が見つかりません。", zh: "客人，我找不到入口。" },
      { speaker: "손님", kr: "편의점 지나서 오셨어요?", en: "Did you pass the convenience store?", ja: "コンビニは通り過ぎましたか？", zh: "您过了便利店了吗？" },
      { speaker: "기사", kr: "네, 지금 그 앞이에요.", en: "Yes, I'm in front of it now.", ja: "はい、今その前にいます。", zh: "过了，我现在就在它前面。" },
      { speaker: "손님", kr: "거기서 왼쪽 골목으로 들어오세요.", en: "Turn into the alley on the left there.", ja: "そこから左の路地に入ってください。", zh: "从那里往左拐进巷子。" },
      { speaker: "기사", kr: "아, 이제 보여요, 감사합니다.", en: "Oh, I see it now, thank you.", ja: "あ、見えました、ありがとうございます。", zh: "哦，看到了，谢谢。" },
      { speaker: "손님", kr: "3층 초인종 눌러 주세요.", en: "Please ring the buzzer on the third floor.", ja: "三階のインターホンを押してください。", zh: "请按三楼的门铃。" },
    ],
  },
  {
    id: "directions-b1x-market-stall-number",
    situationKey: "directions",
    level: "B1",
    title: { en: "Finding a specific market stall", ja: "特定の市場の屋台を探す", zh: "寻找市场里的特定摊位" },
    lines: [
      { speaker: "행인", kr: "떡볶이로 유명한 가게가 몇 번 골목에 있어요?", en: "Which alley number is the tteokbokki place famous around here?", ja: "辻トッポッキで有名な店は何番の路地にありますか？", zh: "这附近有名的炒年糕店在几号巷？" },
      { speaker: "주민", kr: "정확한 번호는 모르는데 중앙 통로 근처예요.", en: "I don't know the exact number, but it's near the central aisle.", ja: "正確な番号は分かりませんが、中央通路の近くです。", zh: "具体号数不清楚，但在中央通道附近。" },
      { speaker: "행인", kr: "중앙 통로는 어느 방향이에요?", en: "Which direction is the central aisle?", ja: "中央通路はどちらの方向ですか？", zh: "中央通道往哪个方向？" },
      { speaker: "주민", kr: "입구에서 곧장 들어가면 나와요.", en: "Go straight in from the entrance and you'll find it.", ja: "入口からまっすぐ入ると出てきます。", zh: "从入口直走进去就能看到。" },
      { speaker: "행인", kr: "냄새로도 찾을 수 있을 것 같네요.", en: "I think I could find it by smell too.", ja: "匂いでも見つけられそうです。", zh: "我感觉靠味道也能找到。" },
      { speaker: "주민", kr: "맞아요, 줄 서 있는 곳이 거기예요.", en: "Right, the place with the line is it.", ja: "そうです、行列ができているところがそこです。", zh: "对，排队的那家就是。" },
    ],
  },
  {
    id: "directions-b1x-hospital-shuttle",
    situationKey: "directions",
    level: "B1",
    title: { en: "Hospital shuttle bus stop", ja: "病院のシャトルバス乗り場", zh: "医院班车站" },
    lines: [
      { speaker: "행인", kr: "본관까지 가는 셔틀버스가 있다고 들었어요.", en: "I heard there's a shuttle bus to the main building.", ja: "本館まで行くシャトルバスがあると聞きました。", zh: "听说有到主楼的班车。" },
      { speaker: "안내원", kr: "네, 정문 밖 셔틀 정류장에서 타시면 돼요.", en: "Yes, you can catch it at the shuttle stop outside the main gate.", ja: "はい、正門の外のシャトル乗り場から乗れます。", zh: "对，可以在正门外的班车站坐。" },
      { speaker: "행인", kr: "배차 간격이 얼마나 돼요?", en: "How often does it run?", ja: "運行間隔はどのくらいですか？", zh: "多久一趟？" },
      { speaker: "안내원", kr: "십오 분마다 한 대씩 와요.", en: "One comes every fifteen minutes.", ja: "十五分おきに一台来ます。", zh: "每十五分钟一趟。" },
      { speaker: "행인", kr: "걸어가는 게 더 빠를 수도 있겠네요.", en: "Walking might actually be faster.", ja: "歩いた方が実は早いかもしれませんね。", zh: "走路可能其实更快。" },
      { speaker: "안내원", kr: "짐이 없으시면 그럴 수도 있어요.", en: "That could be true if you don't have luggage.", ja: "荷物がなければそうかもしれません。", zh: "如果没有行李的话，确实可能这样。" },
    ],
  },
  {
    id: "directions-b1x-festival-crowd-control",
    situationKey: "directions",
    level: "B1",
    title: { en: "Festival crowd control detour", ja: "祭りの混雑規制による迂回", zh: "节庆人流管制导致绕行" },
    lines: [
      { speaker: "행인", kr: "축제 때문에 이 길이 통제됐네요.", en: "This street is closed off because of the festival.", ja: "祭りのためこの通りが通行止めになっていますね。", zh: "因为节庆这条路封了。" },
      { speaker: "경찰", kr: "네, 우회로를 이용해 주세요.", en: "Yes, please use the detour route.", ja: "はい、迂回路をご利用ください。", zh: "是的，请走迂回道。" },
      { speaker: "행인", kr: "그럼 시청 쪽으로 어떻게 가요?", en: "Then how do I get to City Hall?", ja: "それでは市庁舎へはどう行けばいいですか？", zh: "那要怎么去市政厅？" },
      { speaker: "경찰", kr: "저쪽 골목으로 돌아서 가시면 돼요.", en: "Go around through that alley over there.", ja: "あの路地を回って行ってください。", zh: "绕过那条巷子过去。" },
      { speaker: "행인", kr: "시간이 얼마나 더 걸릴까요?", en: "How much longer will it take?", ja: "どのくらい余分に時間がかかりますか？", zh: "会多花多长时间？" },
      { speaker: "경찰", kr: "한 십 분 정도 더 걸리실 거예요.", en: "It'll take about ten extra minutes.", ja: "十分くらい余分にかかります。", zh: "大概会多花十分钟。" },
    ],
  },
  {
    id: "directions-b1x-university-building-numbering",
    situationKey: "directions",
    level: "B1",
    title: { en: "Confusing building numbers on campus", ja: "キャンパスの紛らわしい建物番号", zh: "校园里令人困惑的楼号" },
    lines: [
      { speaker: "행인", kr: "건물 번호가 순서대로가 아니네요.", en: "The building numbers aren't in order.", ja: "建物の番号が順番通りじゃないですね。", zh: "楼号不是按顺序排的。" },
      { speaker: "주민", kr: "맞아요, 신축 건물이 나중에 번호를 받아서 그래요.", en: "Right, that's because new buildings got their numbers later.", ja: "そうです、新しい建物は後から番号がついたのでそうなっています。", zh: "对，因为新楼是后来才编号的。" },
      { speaker: "행인", kr: "그럼 공학관은 몇 번이에요?", en: "So what number is the engineering building?", ja: "それでは工学館は何号ですか？", zh: "那工学馆是几号楼？" },
      { speaker: "주민", kr: "7호관인데 정문에서 제일 멀어요.", en: "Building 7, and it's the farthest from the main gate.", ja: "七号館で、正門から一番遠いです。", zh: "七号楼，离正门最远。" },
      { speaker: "행인", kr: "지도 앱을 보는 게 낫겠어요.", en: "I'd better look at a map app.", ja: "地図アプリを見た方がよさそうです。", zh: "我最好看看地图App。" },
      { speaker: "주민", kr: "네, 캠퍼스 앱이 더 정확해요.", en: "Yes, the campus app is more accurate.", ja: "はい、キャンパスアプリの方が正確です。", zh: "对，校园App更准确。" },
    ],
  },
  {
    id: "directions-b1x-ferry-terminal-gate",
    situationKey: "directions",
    level: "B1",
    title: { en: "Wrong gate at the ferry terminal", ja: "フェリーターミナルで違うゲート", zh: "渡轮码头走错了登船口" },
    lines: [
      { speaker: "행인", kr: "제주도행 배는 어느 게이트예요?", en: "Which gate is the ferry to Jeju Island?", ja: "済州島行きの船は何番ゲートですか？", zh: "去济州岛的船在几号门？" },
      { speaker: "안내원", kr: "표를 보니 2번 게이트가 아니라 5번이네요.", en: "Looking at your ticket, it's gate 5, not gate 2.", ja: "チケットを見ると、二番ゲートじゃなくて五番ですね。", zh: "看您的票，不是二号门，是五号门。" },
      { speaker: "행인", kr: "5번 게이트는 어디로 가요?", en: "Where's gate 5?", ja: "五番ゲートはどこですか？", zh: "五号门在哪里？" },
      { speaker: "안내원", kr: "이 통로 끝까지 가시면 나와요.", en: "Go all the way to the end of this corridor.", ja: "この通路を突き当たりまで行ってください。", zh: "沿这条通道一直走到尽头。" },
      { speaker: "행인", kr: "시간이 촉박한데 뛰어야겠어요.", en: "I'm running short on time, I should run.", ja: "時間があまりないので走らないと。", zh: "时间不太够了，我得跑了。" },
      { speaker: "안내원", kr: "탑승 마감까지 아직 여유 있어요.", en: "There's still time before boarding closes.", ja: "搭乗締め切りまでまだ余裕があります。", zh: "离登船截止还有时间。" },
    ],
  },
  {
    id: "directions-b1x-mountain-cable-car",
    situationKey: "directions",
    level: "B1",
    title: { en: "Cable car station directions", ja: "ケーブルカー乗り場までの道案内", zh: "缆车站的路线指引" },
    lines: [
      { speaker: "행인", kr: "케이블카 타는 곳까지 걸어갈 수 있어요?", en: "Can I walk to where the cable car departs?", ja: "ケーブルカー乗り場まで歩いて行けますか？", zh: "能走路去缆车站吗？" },
      { speaker: "주민", kr: "네, 근데 경사가 좀 있어서 힘들 수 있어요.", en: "Yes, but it's a bit steep so it might be tough.", ja: "はい、でも坂が少しきついので大変かもしれません。", zh: "可以，不过有点陡，可能会有点吃力。" },
      { speaker: "행인", kr: "셔틀버스는 없어요?", en: "Isn't there a shuttle bus?", ja: "シャトルバスはないんですか？", zh: "没有班车吗？" },
      { speaker: "주민", kr: "있는데 주말에만 운행해요.", en: "There is, but it only runs on weekends.", ja: "あるんですが、週末しか運行しません。", zh: "有，不过只在周末运营。" },
      { speaker: "행인", kr: "오늘은 평일이라 걸어야겠네요.", en: "Since it's a weekday today, I'll have to walk.", ja: "今日は平日なので歩かないといけませんね。", zh: "今天是工作日，那我只能走路了。" },
      { speaker: "주민", kr: "천천히 가시면 이십 분이면 돼요.", en: "If you go slowly, twenty minutes is enough.", ja: "ゆっくり行けば二十分で十分です。", zh: "慢慢走的话，二十分钟就够了。" },
    ],
  },
  {
    id: "directions-b1x-office-building-security",
    situationKey: "directions",
    level: "B1",
    title: { en: "Security desk directions in an office building", ja: "オフィスビルの受付での道案内", zh: "写字楼前台的路线指引" },
    lines: [
      { speaker: "행인", kr: "3층 회의실을 찾고 있는데요.", en: "I'm looking for the meeting room on the third floor.", ja: "三階の会議室を探しているんですが。", zh: "我在找三楼的会议室。" },
      { speaker: "안내원", kr: "방문증부터 받으셔야 해요.", en: "You'll need to get a visitor pass first.", ja: "まず訪問証を受け取っていただく必要があります。", zh: "您得先领一张访客证。" },
      { speaker: "행인", kr: "그건 어디서 받아요?", en: "Where do I get that?", ja: "それはどこでもらえますか？", zh: "在哪里领？" },
      { speaker: "안내원", kr: "이 데스크에서 신분증 주시면 발급해 드려요.", en: "Give me your ID at this desk and I'll issue one.", ja: "こちらのデスクで身分証をいただければ発行いたします。", zh: "在这个台子给我身份证，我就给您办。" },
      { speaker: "행인", kr: "여기 있습니다.", en: "Here you go.", ja: "どうぞ。", zh: "给您。" },
      { speaker: "안내원", kr: "엘리베이터 왼쪽 첫 번째가 3층 버튼이에요.", en: "The first button on the left of the elevator is for the third floor.", ja: "エレベーターの左側の一番上のボタンが三階です。", zh: "电梯左边第一个按钮就是三楼。" },
    ],
  },
  {
    id: "directions-b1x-riverside-bike-rental",
    situationKey: "directions",
    level: "B1",
    title: { en: "Riverside bike rental spot", ja: "川沿いのレンタサイクル場所", zh: "江边自行车租赁点" },
    lines: [
      { speaker: "행인", kr: "따릉이 대여소가 이 근처에 몇 개나 있어요?", en: "How many bike rental stations are near here?", ja: "この近くにレンタサイクルの貸出所はいくつありますか？", zh: "这附近有几个共享单车租赁点？" },
      { speaker: "주민", kr: "강변을 따라 세 개 정도 있어요.", en: "There are about three along the riverside.", ja: "川沿いに三か所くらいあります。", zh: "沿江边大概有三个。" },
      { speaker: "행인", kr: "제일 가까운 곳은 어디예요?", en: "Which one is closest?", ja: "一番近いのはどこですか？", zh: "最近的在哪里？" },
      { speaker: "주민", kr: "다리 밑에 하나 있는데 자전거가 자주 없어요.", en: "There's one under the bridge, but bikes are often unavailable.", ja: "橋の下に一つありますが、よく自転車がありません。", zh: "桥下有一个，但经常没车。" },
      { speaker: "행인", kr: "그럼 다른 곳으로 가야겠네요.", en: "Then I should go to another one.", ja: "それじゃあ別のところに行った方がいいですね。", zh: "那我该去别的地方了。" },
      { speaker: "주민", kr: "공원 입구 쪽이 재고가 더 많아요.", en: "The one by the park entrance usually has more available.", ja: "公園の入口の方が在庫が多いです。", zh: "公园入口那个通常车更多。" },
    ],
  },
  {
    id: "directions-b1x-airport-transfer-desk",
    situationKey: "directions",
    level: "B1",
    title: { en: "Transfer desk at the airport", ja: "空港の乗り継ぎデスク", zh: "机场转机柜台" },
    lines: [
      { speaker: "행인", kr: "환승하는데 어디로 가야 해요?", en: "Where do I go for a connecting flight?", ja: "乗り継ぎはどこへ行けばいいですか？", zh: "转机应该去哪里？" },
      { speaker: "안내원", kr: "환승 안내 데스크가 이쪽에 있어요.", en: "The transfer information desk is this way.", ja: "乗り継ぎ案内デスクはこちらです。", zh: "转机咨询台在这边。" },
      { speaker: "행인", kr: "거기서 짐도 다시 부쳐야 해요?", en: "Do I need to recheck my luggage there too?", ja: "そこで荷物も預け直す必要がありますか？", zh: "在那边还需要重新托运行李吗？" },
      { speaker: "안내원", kr: "직항 연결편이면 안 하셔도 돼요.", en: "If it's a direct connecting flight, you don't have to.", ja: "直行の乗り継ぎ便なら必要ありません。", zh: "如果是直连航班，就不用。" },
      { speaker: "행인", kr: "다행이네요, 시간이 별로 없었거든요.", en: "That's a relief, I didn't have much time.", ja: "よかった、あまり時間がなかったので。", zh: "太好了，我时间不多。" },
      { speaker: "안내원", kr: "그래도 서두르시는 게 좋아요.", en: "Still, it's best to hurry.", ja: "それでも急がれた方がいいです。", zh: "不过还是尽快比较好。" },
    ],
  },
  {
    id: "directions-b1x-apartment-visitor-parking",
    situationKey: "directions",
    level: "B1",
    title: { en: "Visitor parking at an apartment complex", ja: "マンションの来訪者用駐車場", zh: "小区访客停车位" },
    lines: [
      { speaker: "기사", kr: "방문 차량은 어디에 주차해요?", en: "Where do visitor cars park?", ja: "来訪車はどこに駐車しますか？", zh: "访客车辆停在哪里？" },
      { speaker: "경비원", kr: "정문 옆에 방문자 구역이 있어요.", en: "There's a visitor zone next to the main gate.", ja: "正門の隣に来訪者エリアがあります。", zh: "正门旁边有访客停车区。" },
      { speaker: "기사", kr: "거기 자리가 있을까요?", en: "Would there be a spot there?", ja: "そこは空きがありますか？", zh: "那边会有空位吗？" },
      { speaker: "경비원", kr: "지금 시간엔 보통 여유가 있어요.", en: "There's usually space at this time.", ja: "この時間帯は普通空きがあります。", zh: "这个时间点通常有空位。" },
      { speaker: "기사", kr: "몇 동으로 가면 되는지도 알려 주시겠어요?", en: "Could you also tell me which building to go to?", ja: "何号棟へ行けばいいかも教えていただけますか？", zh: "能告诉我应该去几栋吗？" },
      { speaker: "경비원", kr: "101동은 저쪽 오른편이에요.", en: "Building 101 is over there on the right.", ja: "101棟はあちらの右側です。", zh: "101栋在那边右侧。" },
    ],
  },
  // ---------- B2 (16) ----------
  {
    id: "directions-b2x-underground-mall-maze",
    situationKey: "directions",
    level: "B2",
    title: { en: "Getting lost in an underground shopping mall", ja: "地下商店街で迷子になる", zh: "在地下商场迷路" },
    lines: [
      { speaker: "행인", kr: "지하상가가 이렇게 복잡한 줄 몰랐어요, 완전히 헤맸어요.", en: "I had no idea the underground mall was this complicated, I got completely lost.", ja: "地下商店街がこんなに複雑だとは思わず、完全に迷ってしまいました。", zh: "没想到地下商场这么复杂，我完全迷路了。" },
      { speaker: "주민", kr: "처음 오시는 분들은 다 그러세요, 구역별로 색깔이 달라서 그걸 기준으로 삼으시면 돼요.", en: "First-timers always do, but each section is color-coded so you can use that as a reference.", ja: "初めて来られる方はみんなそうなります、区域ごとに色が違うのでそれを目印にすればいいですよ。", zh: "第一次来的人都会这样，各个区域颜色不一样，可以用颜色当参考。" },
      { speaker: "행인", kr: "아, 그러고 보니 바닥 색이 다르긴 하네요.", en: "Oh, now that you mention it, the floor colors are different.", ja: "あ、言われてみれば床の色が違いますね。", zh: "哦，您这么一说，地板颜色确实不一样。" },
      { speaker: "주민", kr: "빨간 구역이 의류고, 파란 구역이 잡화예요.", en: "The red zone is clothing, and the blue zone is general goods.", ja: "赤い区域が衣類で、青い区域が雑貨です。", zh: "红色区是服装，蓝色区是日用杂货。" },
      { speaker: "행인", kr: "그럼 제가 찾는 신발 가게는 어느 쪽이에요?", en: "So which side is the shoe store I'm looking for?", ja: "それじゃあ私が探している靴屋はどちらですか？", zh: "那我要找的鞋店在哪一边？" },
      { speaker: "주민", kr: "신발은 파란 구역 끝쪽에 몰려 있어요.", en: "Shoe stores are clustered at the far end of the blue zone.", ja: "靴屋は青い区域の一番奥に集まっています。", zh: "鞋店都聚集在蓝色区的最里面。" },
      { speaker: "행인", kr: "덕분에 이제 방향이 좀 잡히네요, 감사해요.", en: "Thanks to you I finally have a sense of direction, thank you.", ja: "おかげでようやく方向がつかめました、ありがとうございます。", zh: "多亏了您，我总算有了点方向感，谢谢。" },
    ],
  },
  {
    id: "directions-b2x-toll-gate-lane",
    situationKey: "directions",
    level: "B2",
    title: { en: "Picking the wrong toll gate lane", ja: "料金所の車線を間違える", zh: "选错了收费站车道" },
    lines: [
      { speaker: "기사", kr: "하이패스 차선인 줄 모르고 들어왔는데 어떡하죠?", en: "I didn't realize this was a Hi-pass-only lane, what should I do?", ja: "ハイパス専用車線だと知らずに入ってしまったんですが、どうすればいいですか？", zh: "我不知道这是Hi-pass专用车道就开进来了，该怎么办？" },
      { speaker: "경찰", kr: "일단 속도를 줄이시고 그대로 통과하시면 나중에 문자로 요금이 청구돼요.", en: "Slow down for now and pass through as is, the toll will be billed to you by text later.", ja: "とりあえず速度を落としてそのまま通過してください、料金は後で文字メッセージで請求されます。", zh: "先减速直接通过就行，通行费之后会通过短信通知扣款。" },
      { speaker: "기사", kr: "벌금은 안 나오나요?", en: "Won't I get a fine?", ja: "罰金は取られませんか？", zh: "不会被罚款吗？" },
      { speaker: "경찰", kr: "실수로 들어간 경우엔 요금만 부과되니까 걱정 안 하셔도 돼요.", en: "For accidental entries, only the toll is charged, so you don't need to worry.", ja: "誤って入った場合は料金だけ請求されるので、心配しなくて大丈夫です。", zh: "误入的话只收通行费，不用担心。" },
      { speaker: "기사", kr: "다음부터는 표지판을 더 잘 봐야겠네요.", en: "I'll have to watch the signs more carefully next time.", ja: "次からは標識をもっとよく見ないといけませんね。", zh: "下次得更仔细看标志了。" },
      { speaker: "경찰", kr: "일반 차선은 항상 오른쪽에 몰려 있으니 참고하세요.", en: "The regular lanes are always clustered on the right, keep that in mind.", ja: "一般車線はいつも右側に固まっているので参考にしてください。", zh: "普通车道通常都集中在右侧，请留意。" },
    ],
  },
  {
    id: "directions-b2x-hiking-map-inconsistency",
    situationKey: "directions",
    level: "B2",
    title: { en: "Trail map doesn't match reality", ja: "登山地図が実際と違う", zh: "登山地图与实际不符" },
    lines: [
      { speaker: "행인", kr: "지도에는 여기서 갈림길이 두 개인데 실제로는 세 개네요.", en: "The map shows two forks here, but there are actually three.", ja: "地図ではここに分かれ道が二つですが、実際は三つありますね。", zh: "地图上这里显示两个岔路，实际上有三个。" },
      { speaker: "주민", kr: "아, 그거 작년에 새로 낸 샛길일 거예요, 지도가 아직 업데이트가 안 됐어요.", en: "Ah, that's probably a new side trail from last year, the map hasn't been updated yet.", ja: "ああ、それはたぶん去年新しくできた脇道です、地図がまだ更新されていないんです。", zh: "啊，那大概是去年新开的一条小路，地图还没更新。" },
      { speaker: "행인", kr: "그럼 어느 길이 원래 정상으로 가는 길이에요?", en: "So which one is the original route to the summit?", ja: "それでは元々頂上へ行く道はどれですか？", zh: "那原本通往山顶的路是哪条？" },
      { speaker: "주민", kr: "가운데 길이 정상 길이고, 왼쪽은 전망대로 빠지는 샛길이에요.", en: "The middle path is the summit route, and the left one branches off to a viewpoint.", ja: "真ん中の道が頂上への道で、左は展望台へ分かれる脇道です。", zh: "中间那条是通往山顶的路，左边那条是通往观景台的岔路。" },
      { speaker: "행인", kr: "전망대 쪽도 궁금한데 시간이 얼마나 더 걸릴까요?", en: "I'm curious about the viewpoint too, how much longer would it add?", ja: "展望台の方も気になるんですが、どのくらい余分に時間がかかりますか？", zh: "我对观景台也挺好奇，会多花多长时间？" },
      { speaker: "주민", kr: "왕복으로 한 삼십 분 정도 더 걸릴 거예요.", en: "It would add about thirty minutes round trip.", ja: "往復で三十分くらい余分にかかります。", zh: "往返大概会多花三十分钟。" },
      { speaker: "행인", kr: "그럼 정상 먼저 갔다가 내려오면서 들를게요.", en: "Then I'll go to the summit first and stop by on the way down.", ja: "それじゃあ頂上に先に行って、下りながら寄ります。", zh: "那我先去山顶，下山的路上再顺路过去看看。" },
    ],
  },
  {
    id: "directions-b2x-delivery-address-mismatch",
    situationKey: "directions",
    level: "B2",
    title: { en: "Delivery address doesn't match the building", ja: "配達先住所と建物名が違う", zh: "配送地址与楼名不符" },
    lines: [
      { speaker: "기사", kr: "주소지에 왔는데 건물 이름이 앱이랑 다르게 붙어 있어요.", en: "I've arrived at the address, but the building name posted here doesn't match the app.", ja: "住所地に着いたんですが、建物の名前がアプリと違って表示されています。", zh: "我到地址了，但这里贴的楼名和App上不一样。" },
      { speaker: "손님", kr: "아, 저희 건물이 최근에 이름을 바꿨는데 등록이 안 됐나 봐요.", en: "Oh, our building recently changed its name, it seems the registration wasn't updated.", ja: "あ、うちの建物が最近名前を変えたんですが、登録が更新されていないみたいですね。", zh: "哦，我们大楼最近改了名字，好像信息还没更新。" },
      { speaker: "기사", kr: "그럼 예전 이름이 뭐였는지 알 수 있을까요, 확인하고 싶어서요.", en: "Could you tell me the old name then, I want to double-check.", ja: "それでは以前の名前を教えていただけますか、確認したいので。", zh: "那能告诉我以前的名字吗，我想确认一下。" },
      { speaker: "손님", kr: "한빛빌딩이었어요, 간판은 아직 그대로 붙어 있을 거예요.", en: "It was Hanbit Building, the sign is probably still up as is.", ja: "ハンビッビルでした、看板はまだそのままだと思います。", zh: "以前叫韩碧大厦，招牌应该还没换。" },
      { speaker: "기사", kr: "아, 맞네요, 찾았습니다.", en: "Ah, that's right, I found it.", ja: "あ、そうですね、見つかりました。", zh: "啊，没错，我找到了。" },
      { speaker: "손님", kr: "정문 말고 후문으로 오시면 더 가까워요.", en: "It's closer if you come through the back door instead of the front.", ja: "正門ではなく裏門から来ていただいた方が近いです。", zh: "从后门进来会更近，不用走正门。" },
      { speaker: "기사", kr: "네, 후문으로 돌아갈게요.", en: "Okay, I'll go around to the back door.", ja: "はい、裏門の方に回ります。", zh: "好，我绕到后门去。" },
    ],
  },
  {
    id: "directions-b2x-subway-construction-detour",
    situationKey: "directions",
    level: "B2",
    title: { en: "Station renovation forces a longer walk", ja: "駅の改修工事で遠回りに", zh: "车站施工被迫绕远路" },
    lines: [
      { speaker: "행인", kr: "3번 출구가 공사 때문에 막혀 있던데 다른 길이 있나요?", en: "Exit 3 is blocked because of construction, is there another way?", ja: "三番出口が工事で塞がれているんですが、他の道はありますか？", zh: "三号出口因为施工封闭了，有别的路吗？" },
      { speaker: "역무원", kr: "네, 대신 1번 출구로 나가셔서 크게 돌아가셔야 해요.", en: "Yes, you'll need to exit through gate 1 and go a longer way around instead.", ja: "はい、代わりに一番出口から出て大きく回っていただく必要があります。", zh: "有，得从一号出口出去，绕一大圈。" },
      { speaker: "행인", kr: "그럼 원래보다 시간이 얼마나 더 걸려요?", en: "So how much longer than usual would that take?", ja: "それじゃあ普段よりどのくらい余分に時間がかかりますか？", zh: "那比平时要多花多长时间？" },
      { speaker: "역무원", kr: "체감상 한 오 분에서 십 분 정도 더 걸리실 거예요.", en: "It would feel like about five to ten minutes longer.", ja: "体感で五分から十分くらい余分にかかると思います。", zh: "感觉上大概会多花五到十分钟。" },
      { speaker: "행인", kr: "공사가 언제까지 계속되는지 아세요?", en: "Do you know how long the construction will continue?", ja: "工事がいつまで続くかご存知ですか？", zh: "知道施工要持续到什么时候吗？" },
      { speaker: "역무원", kr: "다음 달 말까지라고 안내판에 쓰여 있더라고요.", en: "The sign says it's until the end of next month.", ja: "案内板には来月末までと書いてありました。", zh: "告示牌上写着到下个月底。" },
      { speaker: "행인", kr: "그때까지는 어쩔 수 없이 돌아가야겠네요.", en: "Until then I guess I'll just have to take the long way.", ja: "それまでは仕方なく遠回りしないといけませんね。", zh: "那在那之前只能绕远路了。" },
    ],
  },
  {
    id: "directions-b2x-shared-office-floor-plan",
    situationKey: "directions",
    level: "B2",
    title: { en: "Confusing floor plan at a shared office", ja: "シェアオフィスの分かりにくい間取り", zh: "共享办公室令人困惑的平面图" },
    lines: [
      { speaker: "행인", kr: "회의실 이름이 다 비슷해서 헷갈리는데 정확히 어디예요?", en: "The meeting room names are all similar and confusing, where exactly is it?", ja: "会議室の名前がどれも似ていて紛らわしいんですが、正確にはどこですか？", zh: "会议室名字都长得很像，容易搞混，具体在哪里？" },
      { speaker: "안내원", kr: "'해오름'실은 A동이고 '해오름 2'는 B동에 있어서 다들 처음엔 헷갈려 하세요.", en: "'Haeoreum' room is in Building A, and 'Haeoreum 2' is in Building B, everyone gets confused at first.", ja: "「ヘオルム」室はA棟で、「ヘオルム2」はB棟にあるので、みんな最初は戸惑います。", zh: "“海乌姆”会议室在A栋，“海乌姆2”在B栋，大家一开始都会搞混。" },
      { speaker: "행인", kr: "제가 예약한 건 그냥 '해오름'인데 그럼 A동 맞죠?", en: "The one I booked is just 'Haeoreum', so that's Building A, right?", ja: "私が予約したのはただの「ヘオルム」なので、それならA棟で合っていますよね？", zh: "我订的就是普通的“海乌姆”，那应该是A栋对吧？" },
      { speaker: "안내원", kr: "네 맞아요, 로비에서 왼쪽 복도로 쭉 가시면 나와요.", en: "Yes, that's right, go straight down the left hallway from the lobby.", ja: "はい、その通りです、ロビーから左の廊下をまっすぐ行ってください。", zh: "对，没错，从大堂沿左边走廊一直走。" },
      { speaker: "행인", kr: "혹시 표지판이 따로 붙어 있나요, 아니면 그냥 번호만 있어요?", en: "Is there a separate sign, or just room numbers?", ja: "別に案内板がありますか、それとも番号だけですか？", zh: "有单独的指示牌吗，还是只有房间号？" },
      { speaker: "안내원", kr: "문 앞에 이름표가 붙어 있는데 조명이 어두워서 잘 안 보일 수도 있어요.", en: "There's a nameplate on the door, but the lighting is dim so it might be hard to see.", ja: "ドアに名札が付いていますが、照明が暗くて見えにくいかもしれません。", zh: "门上有名牌，不过灯光比较暗，可能不太好看清。" },
      { speaker: "행인", kr: "그럼 조심해서 찾아볼게요, 감사합니다.", en: "Then I'll look carefully, thank you.", ja: "それでは気をつけて探します、ありがとうございます。", zh: "那我仔细找找，谢谢。" },
    ],
  },
  {
    id: "directions-b2x-riverside-run-route",
    situationKey: "directions",
    level: "B2",
    title: { en: "Choosing a running route along the river", ja: "川沿いのランニングコースを選ぶ", zh: "选择沿江跑步路线" },
    lines: [
      { speaker: "행인", kr: "아침에 뛸 만한 코스 좀 추천해 주실 수 있어요?", en: "Could you recommend a good route for a morning run?", ja: "朝走るのにいいコースを勧めていただけますか？", zh: "能推荐一条适合晨跑的路线吗？" },
      { speaker: "주민", kr: "강변 코스가 평평해서 좋은데 이 시간엔 자전거랑 겹쳐서 좀 복잡해요.", en: "The riverside route is flat and nice, but at this hour it overlaps with cyclists so it gets a bit crowded.", ja: "川沿いのコースは平坦でいいんですが、この時間は自転車と重なって少し混みます。", zh: "沿江路线很平坦，不错，但这个时段和骑车的人重叠，会有点拥挤。" },
      { speaker: "행인", kr: "그럼 사람이 덜 몰리는 다른 코스는 없어요?", en: "Then is there another route that's less crowded?", ja: "それじゃあ人が少ない別のコースはありませんか？", zh: "那有没有人少一点的别的路线？" },
      { speaker: "주민", kr: "공원 안쪽으로 도는 코스가 있는데 대신 약간 오르막이에요.", en: "There's a route that loops through the inside of the park, but it has a slight uphill.", ja: "公園の内側を回るコースがありますが、少し上り坂です。", zh: "有一条绕公园内部的路线，不过有点上坡。" },
      { speaker: "행인", kr: "오르막이면 거리도 더 짧아지나요?", en: "If it has an uphill, is the distance shorter too?", ja: "上り坂だと距離も短くなりますか？", zh: "上坡的话距离会短一些吗？" },
      { speaker: "주민", kr: "아니요, 거리는 비슷한데 체감 난이도가 좀 더 있어요.", en: "No, the distance is similar, but it feels a bit more challenging.", ja: "いいえ、距離は同じくらいですが、体感的にはもう少しきついです。", zh: "不会，距离差不多，但感觉会更累一些。" },
      { speaker: "행인", kr: "그럼 오늘은 공원 코스로 한번 뛰어 볼게요.", en: "Then I'll try the park route today.", ja: "それでは今日は公園コースを走ってみます。", zh: "那我今天就试试公园路线。" },
    ],
  },
  {
    id: "directions-b2x-night-market-alley-numbers",
    situationKey: "directions",
    level: "B2",
    title: { en: "Finding a stall by unofficial alley numbers", ja: "非公式の路地番号で屋台を探す", zh: "凭非官方的巷号找摊位" },
    lines: [
      { speaker: "행인", kr: "여기 골목마다 이름이 없어서 위치를 설명하기가 힘드네요.", en: "None of these alleys have names, so it's hard to explain the location.", ja: "ここの路地には名前が一つもなくて、場所を説明するのが大変です。", zh: "这里的巷子都没有名字，很难说明位置。" },
      { speaker: "주민", kr: "상인들끼리는 그냥 번호로 불러요, 저기가 3번 골목이에요.", en: "Vendors just call them by numbers among themselves, that one over there is alley 3.", ja: "商人たちは番号で呼んでいます、あそこは三番路地です。", zh: "商贩之间就用编号来叫，那边那条是三号巷。" },
      { speaker: "행인", kr: "그럼 지도 앱에는 왜 하나도 안 나와요?", en: "Then why doesn't the map app show any of this?", ja: "それじゃあ地図アプリにはなぜ何も出てこないんですか？", zh: "那为什么地图App上一点都不显示？" },
      { speaker: "주민", kr: "비공식 명칭이라 등록이 안 돼 있거든요.", en: "They're unofficial names, so they're not registered.", ja: "非公式な名称なので登録されていないんです。", zh: "因为是非正式名称，没有登记。" },
      { speaker: "행인", kr: "그럼 친구한테는 어떻게 설명해야 하죠?", en: "So how should I explain it to a friend, then?", ja: "それじゃあ友達にはどう説明すればいいですか？", zh: "那我该怎么跟朋友说明呢？" },
      { speaker: "주민", kr: "입구 사진을 찍어서 보내는 게 제일 정확해요.", en: "Taking a photo of the entrance and sending it is the most accurate way.", ja: "入口の写真を撮って送るのが一番正確です。", zh: "拍一张入口的照片发过去最准确。" },
      { speaker: "행인", kr: "좋은 방법이네요, 그렇게 할게요.", en: "That's a good idea, I'll do that.", ja: "いい方法ですね、そうします。", zh: "这个办法不错，我就这么做。" },
    ],
  },
  {
    id: "directions-b2x-cruise-terminal-shuttle-lines",
    situationKey: "directions",
    level: "B2",
    title: { en: "Two shuttle lines at the cruise terminal", ja: "クルーズターミナルの2つのシャトル路線", zh: "邮轮码头的两条班车线路" },
    lines: [
      { speaker: "행인", kr: "셔틀버스가 두 종류인데 뭘 타야 시내로 가요?", en: "There are two kinds of shuttle buses, which one goes downtown?", ja: "シャトルバスが二種類あるんですが、どちらが市内に行きますか？", zh: "有两种班车，哪个去市区？" },
      { speaker: "안내원", kr: "파란색 버스는 시내로 가고 노란색은 근처 아울렛으로 가요.", en: "The blue bus goes downtown, and the yellow one goes to a nearby outlet mall.", ja: "青いバスが市内に行き、黄色いバスは近くのアウトレットに行きます。", zh: "蓝色车去市区，黄色车去附近的奥特莱斯。" },
      { speaker: "행인", kr: "시내까지 얼마나 걸려요?", en: "How long does it take to get downtown?", ja: "市内までどのくらいかかりますか？", zh: "到市区要多久？" },
      { speaker: "안내원", kr: "정체가 없으면 사십 분, 있으면 한 시간 넘게 걸릴 수도 있어요.", en: "It's forty minutes without traffic, but could take over an hour with it.", ja: "渋滞がなければ四十分ですが、あれば一時間以上かかることもあります。", zh: "不堵车四十分钟，堵车的话可能要超过一小时。" },
      { speaker: "행인", kr: "지금 시간대는 어때요?", en: "How is it at this time of day?", ja: "今の時間帯はどうですか？", zh: "现在这个时段怎么样？" },
      { speaker: "안내원", kr: "오후라 좀 막힐 수 있으니 여유 있게 나오세요.", en: "It's the afternoon so it might be congested, so leave with some buffer time.", ja: "午後なので少し混むかもしれません、余裕を持って出発してください。", zh: "现在是下午，可能会有点堵，请提早一些出发。" },
      { speaker: "행인", kr: "알겠어요, 서두를게요.", en: "Got it, I'll get moving.", ja: "わかりました、急いで出ます。", zh: "知道了，我这就出发。" },
    ],
  },
  {
    id: "directions-b2x-embassy-security-entrance",
    situationKey: "directions",
    level: "B2",
    title: { en: "Finding the correct entrance at an embassy", ja: "大使館の正しい入口を探す", zh: "寻找大使馆正确的入口" },
    lines: [
      { speaker: "행인", kr: "여권 신청하러 왔는데 정문에서 안 받아 주시네요.", en: "I came to apply for a passport, but they wouldn't accept me at the main entrance.", ja: "パスポートを申請しに来たんですが、正門で受け付けてもらえませんでした。", zh: "我是来办护照的，但正门不给受理。" },
      { speaker: "경찰", kr: "민원인은 옆 건물 지하 입구로 들어가셔야 해요.", en: "Visitors with civil affairs need to enter through the basement entrance of the building next door.", ja: "民願の方は隣の建物の地下入口から入っていただく必要があります。", zh: "办理民生事务的人得从隔壁大楼的地下入口进。" },
      { speaker: "행인", kr: "지하 입구는 어디로 돌아가야 나와요?", en: "Which way do I go around to reach the basement entrance?", ja: "地下入口はどう回れば行けますか？", zh: "地下入口该怎么绕过去？" },
      { speaker: "경찰", kr: "이 담장을 따라 오른쪽으로 백 미터쯤 가시면 계단이 보여요.", en: "Go right along this wall for about a hundred meters and you'll see stairs.", ja: "この塀に沿って右に百メートルほど行くと階段が見えます。", zh: "沿这堵墙往右走大约一百米就能看到楼梯。" },
      { speaker: "행인", kr: "신분증도 미리 준비해야 하나요?", en: "Should I have my ID ready in advance too?", ja: "身分証も前もって用意しておくべきですか？", zh: "身份证也要提前准备好吗？" },
      { speaker: "경찰", kr: "네, 입구에서 검사하니까 미리 꺼내 두세요.", en: "Yes, they check it at the entrance, so have it out beforehand.", ja: "はい、入口で確認しますので前もって出しておいてください。", zh: "对，入口会检查，请提前准备好拿出来。" },
      { speaker: "행인", kr: "알겠습니다, 감사해요.", en: "Understood, thank you.", ja: "わかりました、ありがとうございます。", zh: "明白了，谢谢。" },
    ],
  },
  {
    id: "directions-b2x-camp-site-numbering",
    situationKey: "directions",
    level: "B2",
    title: { en: "Campsite numbering doesn't match the reservation", ja: "キャンプ場の番号が予約と違う", zh: "露营地编号与预订不符" },
    lines: [
      { speaker: "행인", kr: "예약한 자리 번호랑 팻말에 붙은 번호가 안 맞는 것 같아요.", en: "The reserved site number doesn't seem to match the number on the sign.", ja: "予約した区画番号と看板の番号が合わないようです。", zh: "预订的位置编号好像和牌子上的号码不一样。" },
      { speaker: "안내원", kr: "작년에 구역을 재배치하면서 번호가 좀 바뀌었어요.", en: "The numbers changed a bit when the zones were rearranged last year.", ja: "去年区域を再配置した時に番号が少し変わりました。", zh: "去年重新划分区域时，编号有些改动。" },
      { speaker: "행인", kr: "그럼 예약 시스템은 업데이트가 안 된 거예요?", en: "So the reservation system wasn't updated then?", ja: "それでは予約システムは更新されていないんですね。", zh: "那预订系统没有更新吗？" },
      { speaker: "안내원", kr: "네, 죄송해요, 현장 번호 기준으로 다시 안내해 드릴게요.", en: "Yes, sorry about that, let me guide you again based on the on-site numbering.", ja: "はい、申し訳ございません、現地の番号に基づいて改めてご案内します。", zh: "是的，非常抱歉，我按现场编号重新给您指引。" },
      { speaker: "행인", kr: "저희는 강 쪽 자리를 원했는데 그건 어디예요?", en: "We wanted a spot by the river, where's that?", ja: "私たちは川沿いの区画を希望していたんですが、それはどこですか？", zh: "我们想要靠河边的位置，那在哪里？" },
      { speaker: "안내원", kr: "강변 구역은 이제 A로 시작하는 번호예요, 저쪽으로 가시면 돼요.", en: "The riverside zone now starts with the letter A, you can head that way.", ja: "川沿いの区域は今Aで始まる番号です、そちらへ行ってください。", zh: "河边区域现在编号以A开头，您往那边走就行。" },
      { speaker: "행인", kr: "네, 그쪽으로 가 볼게요.", en: "Okay, I'll head over there.", ja: "はい、そちらへ行きます。", zh: "好，我这就过去。" },
    ],
  },
  {
    id: "directions-b2x-elevator-restricted-floor",
    situationKey: "directions",
    level: "B2",
    title: { en: "Elevator won't go to a restricted floor", ja: "エレベーターが制限フロアに行かない", zh: "电梯无法到达受限楼层" },
    lines: [
      { speaker: "행인", kr: "12층 버튼을 눌렀는데 불이 안 들어와요.", en: "I pressed the button for floor 12 but it's not lighting up.", ja: "十二階のボタンを押したんですが、明かりがつきません。", zh: "我按了十二楼的按钮，但灯没亮。" },
      { speaker: "안내원", kr: "그 층은 카드 인증을 해야 올라가요, 방문증 있으세요?", en: "That floor requires a card authentication to go up, do you have a visitor pass?", ja: "その階はカード認証が必要です、訪問証はお持ちですか？", zh: "那层楼需要刷卡才能上去，您有访客证吗？" },
      { speaker: "행인", kr: "아직 못 받았는데 어디서 받아요?", en: "I haven't gotten one yet, where do I get it?", ja: "まだもらっていないんですが、どこでもらえますか？", zh: "我还没拿到，在哪里能领？" },
      { speaker: "안내원", kr: "1층 로비 데스크에서 발급받으시면 돼요.", en: "You can get one issued at the lobby desk on the first floor.", ja: "一階のロビーデスクで発行できます。", zh: "在一楼大堂前台可以办理。" },
      { speaker: "행인", kr: "다시 내려가야 하는 거네요.", en: "So I have to go back down.", ja: "それでは一度下に戻らないといけませんね。", zh: "那我得先下去一趟了。" },
      { speaker: "안내원", kr: "네, 근데 발급이 빨라서 오래 안 걸리실 거예요.", en: "Yes, but issuing is quick so it won't take long.", ja: "はい、でも発行はすぐなのであまり時間はかかりません。", zh: "是的，不过办理很快，不会花太久。" },
      { speaker: "행인", kr: "알겠습니다, 금방 다녀올게요.", en: "Okay, I'll be back quickly.", ja: "わかりました、すぐ戻ります。", zh: "好，我马上回来。" },
    ],
  },
  {
    id: "directions-b2x-airport-rental-car-shuttle",
    situationKey: "directions",
    level: "B2",
    title: { en: "Rental car shuttle pickup point moved", ja: "レンタカーのシャトル乗り場が移動した", zh: "租车班车上车点搬迁了" },
    lines: [
      { speaker: "행인", kr: "렌터카 셔틀 타는 곳이 여기 맞아요? 안내판이랑 위치가 다른 것 같아서요.", en: "Is this the right spot for the rental car shuttle? The signage seems to not match the location.", ja: "ここがレンタカーのシャトル乗り場で合っていますか？案内板と場所が違うようなので。", zh: "这里是租车班车的上车点吗？标牌和实际位置好像对不上。" },
      { speaker: "안내원", kr: "아, 지난주부터 탑승 위치가 3번 출구 쪽으로 옮겨졌어요.", en: "Ah, the pickup location moved to near exit 3 starting last week.", ja: "あ、先週から乗車場所が三番出口の方に移動しました。", zh: "啊，从上周开始上车点已经移到三号出口附近了。" },
      { speaker: "행인", kr: "그럼 여기서 얼마나 걸어가야 해요?", en: "How far do I need to walk from here, then?", ja: "それではここからどのくらい歩かないといけませんか？", zh: "那我从这里要走多远？" },
      { speaker: "안내원", kr: "짐이 있으시면 한 오 분 정도 걸리실 거예요.", en: "With luggage, it'll take about five minutes.", ja: "荷物があると五分くらいかかると思います。", zh: "带着行李的话，大概要走五分钟。" },
      { speaker: "행인", kr: "표지판을 새로 세워야 하는 거 아니에요?", en: "Shouldn't they put up new signs?", ja: "新しい標識を立てるべきじゃないですか？", zh: "是不是应该立个新标牌？" },
      { speaker: "안내원", kr: "맞아요, 저희도 계속 건의하고 있어요.", en: "You're right, we keep raising that too.", ja: "おっしゃる通りです、私たちもずっと要望しています。", zh: "您说得对，我们也一直在反映这个问题。" },
      { speaker: "행인", kr: "그럼 얼른 3번 출구로 가 볼게요.", en: "Then I'll head to exit 3 right away.", ja: "それではすぐに三番出口へ向かいます。", zh: "那我马上去三号出口。" },
    ],
  },
  {
    id: "directions-b2x-temple-visitor-route",
    situationKey: "directions",
    level: "B2",
    title: { en: "Temple has a separate route for visitors during a ceremony", ja: "儀式中は参拝者用に別のルートがあるお寺", zh: "法事期间寺庙为游客设了另一条路线" },
    lines: [
      { speaker: "행인", kr: "법당 쪽으로 가려고 하는데 스님들이 지나가시라고 막으시네요.", en: "I was heading toward the main hall, but the monks are stopping people from passing.", ja: "法堂の方に行こうとしたら、お坊さんたちに通行を止められました。", zh: "我正要去大殿，被僧人拦下不让过去。" },
      { speaker: "주민", kr: "지금 의식 중이라 방문객은 옆길로 돌아가셔야 해요.", en: "There's a ceremony going on right now, so visitors have to go around the side path.", ja: "今儀式中なので、参拝者は横道を回っていただく必要があります。", zh: "现在正在举行法事，游客得绕小路走。" },
      { speaker: "행인", kr: "옆길로 가면 법당을 아예 못 보나요?", en: "If I take the side path, will I not be able to see the main hall at all?", ja: "横道を行くと法堂は全く見えなくなりますか？", zh: "走小路的话，就完全看不到大殿了吗？" },
      { speaker: "주민", kr: "아니요, 조금 멀리서 보이긴 하는데 가까이는 못 가요.", en: "No, you can see it from a bit farther away, you just can't get close.", ja: "いいえ、少し離れたところから見えますが、近くには行けません。", zh: "不会，能从稍远的地方看到，只是不能靠近。" },
      { speaker: "행인", kr: "의식은 언제쯤 끝나요?", en: "About when does the ceremony end?", ja: "儀式はだいたいいつ終わりますか？", zh: "法事大概什么时候结束？" },
      { speaker: "주민", kr: "보통 한 시간쯤 걸리니까 그때 다시 오시면 돼요.", en: "It usually takes about an hour, so you could come back then.", ja: "普通一時間くらいかかるので、その頃また来ていただければ大丈夫です。", zh: "一般要一个小时左右，到时候再来就行。" },
      { speaker: "행인", kr: "그럼 다른 곳부터 둘러보고 다시 올게요.", en: "Then I'll look around elsewhere first and come back.", ja: "それではまず他のところを見て、また戻ってきます。", zh: "那我先去别的地方转转，再回来。" },
    ],
  },
  {
    id: "directions-b2x-warehouse-loading-dock",
    situationKey: "directions",
    level: "B2",
    title: { en: "Truck driver directed to the wrong loading dock", ja: "違う荷降ろし場に案内されたトラック運転手", zh: "被指错卸货区的卡车司机" },
    lines: [
      { speaker: "기사", kr: "3번 하역장으로 오라고 하셨는데 여기는 5번이라고 쓰여 있는데요.", en: "You told me to come to loading dock 3, but this one is marked 5.", ja: "三番の荷降ろし場に来るように言われたんですが、ここは五番と書いてあります。", zh: "您让我来三号卸货区，但这里写的是五号。" },
      { speaker: "안내원", kr: "죄송해요, 번호판이 옛날 거라 안 바뀌었어요.", en: "Sorry, the sign plate is old and hasn't been updated.", ja: "すみません、看板が古いままで更新されていないんです。", zh: "对不起，指示牌是旧的，还没更新。" },
      { speaker: "기사", kr: "그럼 실제 3번은 어디예요?", en: "So where's the actual number 3?", ja: "それでは本当の三番はどこですか？", zh: "那真正的三号在哪里？" },
      { speaker: "안내원", kr: "여기서 두 번째 건물이 진짜 3번이에요.", en: "The second building from here is the real number 3.", ja: "ここから二つ目の建物が本当の三番です。", zh: "从这里数第二栋楼才是真正的三号。" },
      { speaker: "기사", kr: "차를 돌려서 가야 하는데 공간이 좁네요.", en: "I need to turn the truck around, but the space is tight.", ja: "トラックを転回させないといけないんですが、スペースが狭いですね。", zh: "我得把车调头，但地方太窄了。" },
      { speaker: "안내원", kr: "제가 나가서 후진하시는 거 봐 드릴게요.", en: "I'll go out and guide you while you back up.", ja: "私が外に出てバックするのを見ておきますね。", zh: "我出去给您指挥倒车。" },
      { speaker: "기사", kr: "감사합니다, 도움이 많이 되네요.", en: "Thanks, that's a big help.", ja: "ありがとうございます、とても助かります。", zh: "谢谢，帮了大忙。" },
    ],
  },
  {
    id: "directions-b2x-flea-market-vendor-map",
    situationKey: "directions",
    level: "B2",
    title: { en: "Vendor map doesn't match the actual flea market layout", ja: "フリーマーケットの出店マップが実際と違う", zh: "跳蚤市场的商贩地图与实际布局不符" },
    lines: [
      { speaker: "행인", kr: "안내소에서 받은 지도랑 실제 배치가 다른 것 같아요.", en: "The map I got from the information booth doesn't seem to match the actual layout.", ja: "案内所でもらった地図と実際の配置が違うようです。", zh: "我从问讯处拿的地图和实际布局好像不一样。" },
      { speaker: "주민", kr: "네, 매달 판매자들 위치가 추첨으로 바뀌어서 지도가 자주 틀려요.", en: "Right, the vendor positions are decided by lottery every month, so the map is often wrong.", ja: "はい、毎月出店者の位置が抽選で変わるので、地図がよく間違っているんです。", zh: "是的，每个月商贩的位置都是抽签决定的，所以地图经常不准。" },
      { speaker: "행인", kr: "그럼 원하는 가게를 어떻게 찾아요?", en: "Then how do I find the shop I'm looking for?", ja: "それでは探している店をどうやって見つければいいですか？", zh: "那我该怎么找到我要找的店？" },
      { speaker: "주민", kr: "구역 번호는 안 바뀌니까 그걸로 물어보시면 돼요.", en: "The section numbers don't change, so you can ask using those.", ja: "区画番号は変わらないので、それで聞いていただければ大丈夫です。", zh: "区域号是不变的，用那个来问就行。" },
      { speaker: "행인", kr: "제가 찾는 가게는 3구역이라고 들었어요.", en: "I heard the shop I'm looking for is in section 3.", ja: "私が探している店は三区画にあると聞きました。", zh: "我听说我要找的店在三区。" },
      { speaker: "주민", kr: "3구역은 저 천막들 지나서 왼쪽이에요.", en: "Section 3 is on the left past those tents.", ja: "三区画はあのテントを過ぎて左側です。", zh: "三区在过了那些帐篷之后的左边。" },
      { speaker: "행인", kr: "네, 구역 번호로 다시 찾아볼게요, 감사합니다.", en: "Okay, I'll look again using the section number, thank you.", ja: "はい、区画番号でもう一度探してみます、ありがとうございます。", zh: "好，我用区域号再找找，谢谢。" },
    ],
  },
];

export const DIRECTIONS_QUIZZES: Record<string, DialogueQuiz> = {
  "directions-a1x-bank": {
    q: "Where is the bank located?",
    opts: ["Next to the pharmacy", "Next to the convenience store", "Across from the station", "Inside the mall"],
    ans: 1,
  },
  "directions-a1x-atm": {
    q: "Where is the ATM?",
    opts: ["Outside the building", "On the second floor", "Inside the building, first floor", "Next door"],
    ans: 2,
  },
  "directions-a1x-pharmacy-closed": {
    q: "Why does the pedestrian need another pharmacy?",
    opts: ["It's too expensive", "The first one is closed", "It's out of medicine", "It moved away"],
    ans: 1,
  },
  "directions-a1x-crosswalk": {
    q: "How should the pedestrian get to the bus stop?",
    opts: ["Take an underpass", "Use the crosswalk", "Take a taxi", "Wait for a shuttle"],
    ans: 1,
  },
  "directions-a1x-airport-platform": {
    q: "Which platform is the airport train?",
    opts: ["Platform 1", "Platform 2", "Platform 3", "Platform 4"],
    ans: 2,
  },
  "directions-a1x-elevator": {
    q: "Where is the elevator?",
    opts: ["Near the entrance", "Next to the stairs", "On the second floor", "Behind the ticket gate"],
    ans: 1,
  },
  "directions-a1x-last-train": {
    q: "What time is the last train?",
    opts: ["10 PM", "11 PM", "Midnight", "1 AM"],
    ans: 2,
  },
  "directions-a1x-card-tap": {
    q: "Where does the person tap their card?",
    opts: ["The red part", "The blue part", "The green part", "The yellow part"],
    ans: 2,
  },
  "directions-a1x-parking-entrance": {
    q: "Where is the parking lot entrance?",
    opts: ["In front of the building", "Behind the building", "Underground", "Next to the elevator"],
    ans: 1,
  },
  "directions-a1x-plaza-meet": {
    q: "Where will they meet in the plaza?",
    opts: ["By the entrance gate", "By the clock tower", "In front of the fountain", "Near the parking lot"],
    ans: 2,
  },
  "directions-a1x-cafe-restroom-code": {
    q: "Where can the restroom code be found?",
    opts: ["On the menu", "On the door", "On the receipt", "On the wall"],
    ans: 2,
  },
  "directions-a1x-exit-number": {
    q: "Which exit is being discussed?",
    opts: ["Exit 3", "Exit 4", "Exit 5", "Exit 6"],
    ans: 2,
  },
  "directions-a1x-post-office": {
    q: "How do you get to the post office?",
    opts: ["Turn right at the intersection", "Turn left at the intersection", "Go straight past the bank", "Take the bus"],
    ans: 1,
  },
  "directions-a1x-taxi-stand": {
    q: "Where is the taxi stand?",
    opts: ["Inside the building", "Behind the building", "Outside the main gate", "Near the elevator"],
    ans: 2,
  },
  "directions-a1x-park-entrance": {
    q: "How do you reach the park entrance?",
    opts: ["Turn left at the sign", "Cross the bridge", "Take the stairs down", "Walk through the alley"],
    ans: 1,
  },
  "directions-a2x-lost-card": {
    q: "What was the likely problem with the gate?",
    opts: ["The card was expired", "It just needed to be tapped again", "The gate was broken", "The card had no balance"],
    ans: 1,
  },
  "directions-a2x-bank-hours": {
    q: "Why does the pedestrian need to hurry?",
    opts: ["The bank is far away", "The bank closes soon", "The line is long", "It's about to rain"],
    ans: 1,
  },
  "directions-a2x-pharmacy-night": {
    q: "Where is the 24-hour pharmacy located?",
    opts: ["Near the park", "In front of the station", "Next to the bank", "Behind the market"],
    ans: 1,
  },
  "directions-a2x-bus-stop-side": {
    q: "How does the pedestrian cross to the correct bus stop?",
    opts: ["Wait for a green light", "Use the overpass", "Ask a driver for a ride", "Take a different bus"],
    ans: 1,
  },
  "directions-a2x-airport-checkin": {
    q: "Where can luggage be checked in advance?",
    opts: ["At the airport gate", "At the city air terminal", "At the train station office", "Online only"],
    ans: 1,
  },
  "directions-a2x-elevator-broken": {
    q: "What alternative does the station worker suggest?",
    opts: ["Wait for repairs", "Use the wheelchair lift", "Take a taxi instead", "Use a different station"],
    ans: 1,
  },
  "directions-a2x-parking-full": {
    q: "What does the driver decide to do?",
    opts: ["Wait for a spot to open", "Go to the lot behind this one", "Park illegally", "Turn back home"],
    ans: 1,
  },
  "directions-a2x-plaza-crowded": {
    q: "How does the pedestrian find their friend?",
    opts: ["By calling out their name", "By the color of their jacket", "By waiting at the entrance", "By checking a map app"],
    ans: 1,
  },
  "directions-a2x-cafe-code-changed": {
    q: "Why didn't the old restroom code work?",
    opts: ["The customer misread it", "The code changed yesterday", "The door was locked", "It was never valid"],
    ans: 1,
  },
  "directions-a2x-market-entrance": {
    q: "Why does the pedestrian need to use the side door?",
    opts: ["The market is closed", "The main entrance is under construction", "The side door is faster", "It's a members-only entrance"],
    ans: 1,
  },
  "directions-a2x-hospital-wing": {
    q: "Where is the emergency room?",
    opts: ["In the main building", "In the annex", "On the second floor", "Near the parking lot"],
    ans: 1,
  },
  "directions-a2x-luggage-locker": {
    q: "Where is the luggage locker located?",
    opts: ["Before the ticket gate", "Right after the ticket gate", "Outside the station", "On the platform"],
    ans: 1,
  },
  "directions-a2x-stadium-gate": {
    q: "Which gate should the visitor go to?",
    opts: ["Gate 5", "Gate 6", "Gate 7", "Gate 8"],
    ans: 2,
  },
  "directions-a2x-school-visitor": {
    q: "Which entrance should visitors use?",
    opts: ["The front gate", "The back gate", "The side gate", "The staff entrance"],
    ans: 1,
  },
  "directions-a2x-gym-floor": {
    q: "What floor is the gym on?",
    opts: ["First floor", "Second floor", "Basement floor 1", "Basement floor 2"],
    ans: 2,
  },
  "directions-b1x-one-way-confusion": {
    q: "What should the driver do to get out?",
    opts: ["Turn around immediately", "Go straight, then turn right at the next alley", "Park and wait", "Ask a passerby to guide the car"],
    ans: 1,
  },
  "directions-b1x-bike-path-rules": {
    q: "How is the walking path marked?",
    opts: ["With a red line", "With a blue line", "With a green line", "With a yellow line"],
    ans: 2,
  },
  "directions-b1x-night-bus": {
    q: "What's true about the night bus stop?",
    opts: ["It uses a different stop from the day bus", "It shares the same stop as the day bus", "It has no fixed stop", "It only stops at the terminal"],
    ans: 1,
  },
  "directions-b1x-rooftop-viewpoint": {
    q: "Until when is the rooftop observation deck open?",
    opts: ["7 PM", "8 PM", "9 PM", "10 PM"],
    ans: 1,
  },
  "directions-b1x-palace-shortcut": {
    q: "Which route does the pedestrian choose?",
    opts: ["The fast route along the main road", "The scenic route through the hanok alleys", "Neither, they take a taxi", "They ask for a third option"],
    ans: 1,
  },
  "directions-b1x-delivery-phone": {
    q: "Where should the driver ring the buzzer?",
    opts: ["First floor", "Second floor", "Third floor", "Fourth floor"],
    ans: 2,
  },
  "directions-b1x-market-stall-number": {
    q: "How does the resident suggest finding the tteokbokki stall?",
    opts: ["By its exact stall number", "By following the smell and the line", "By asking a security guard", "By checking a map board"],
    ans: 1,
  },
  "directions-b1x-hospital-shuttle": {
    q: "How often does the shuttle bus run?",
    opts: ["Every 5 minutes", "Every 10 minutes", "Every 15 minutes", "Every 30 minutes"],
    ans: 2,
  },
  "directions-b1x-festival-crowd-control": {
    q: "Why is the street closed?",
    opts: ["Road construction", "A festival", "A car accident", "A protest"],
    ans: 1,
  },
  "directions-b1x-university-building-numbering": {
    q: "Why are the building numbers confusing?",
    opts: ["They were never assigned properly", "New buildings got numbers later, out of order", "The signs were removed", "Numbers change every semester"],
    ans: 1,
  },
  "directions-b1x-ferry-terminal-gate": {
    q: "What mistake did the pedestrian almost make?",
    opts: ["Going to the wrong terminal", "Going to gate 2 instead of gate 5", "Missing the boarding time entirely", "Taking the wrong ferry"],
    ans: 1,
  },
  "directions-b1x-mountain-cable-car": {
    q: "Why does the pedestrian have to walk instead of taking a shuttle?",
    opts: ["The shuttle is broken", "The shuttle only runs on weekends", "The shuttle is too expensive", "There is no shuttle at all"],
    ans: 1,
  },
  "directions-b1x-office-building-security": {
    q: "What must the visitor do before going up?",
    opts: ["Call ahead", "Get a visitor pass at the desk", "Wait for an escort", "Sign a form online"],
    ans: 1,
  },
  "directions-b1x-riverside-bike-rental": {
    q: "Which rental spot does the resident recommend?",
    opts: ["The one under the bridge", "The one by the park entrance", "The one near the dam", "None, better to walk"],
    ans: 1,
  },
  "directions-b1x-airport-transfer-desk": {
    q: "Does the passenger need to recheck luggage?",
    opts: ["Yes, always", "No, since it's a direct connecting flight", "Only for international flights", "Only if bags are overweight"],
    ans: 1,
  },
  "directions-b1x-apartment-visitor-parking": {
    q: "Where is the visitor parking zone?",
    opts: ["Behind building 101", "Next to the main gate", "Underground", "Near the playground"],
    ans: 1,
  },
  "directions-b2x-underground-mall-maze": {
    q: "How can visitors navigate the underground mall's sections?",
    opts: ["By floor number", "By color-coded zones", "By store directory kiosks", "By asking staff at each entrance"],
    ans: 1,
  },
  "directions-b2x-toll-gate-lane": {
    q: "What happens after accidentally entering the Hi-pass lane?",
    opts: ["A fine is issued immediately", "Only the toll is billed by text later", "The car must be towed", "Nothing happens at all"],
    ans: 1,
  },
  "directions-b2x-hiking-map-inconsistency": {
    q: "What does the middle path lead to?",
    opts: ["A viewpoint", "The summit", "A parking lot", "A rest area"],
    ans: 1,
  },
  "directions-b2x-delivery-address-mismatch": {
    q: "What was the building's old name?",
    opts: ["Hanbit Building", "Haneul Tower", "Bitna Plaza", "Sarang Building"],
    ans: 0,
  },
  "directions-b2x-subway-construction-detour": {
    q: "How much longer does the detour add to the trip?",
    opts: ["1-2 minutes", "5-10 minutes", "15-20 minutes", "30 minutes"],
    ans: 1,
  },
  "directions-b2x-shared-office-floor-plan": {
    q: "Where is the room the pedestrian booked?",
    opts: ["Building A", "Building B", "Building C", "It's unclear"],
    ans: 0,
  },
  "directions-b2x-riverside-run-route": {
    q: "Why is the park route more challenging than the riverside route?",
    opts: ["It's much longer", "It has a slight uphill", "It's poorly lit", "It's crowded with cyclists"],
    ans: 1,
  },
  "directions-b2x-night-market-alley-numbers": {
    q: "Why doesn't the map app show the alley numbers?",
    opts: ["The app is outdated", "They are unofficial, unregistered names", "The market asked to hide them", "GPS doesn't work underground"],
    ans: 1,
  },
  "directions-b2x-cruise-terminal-shuttle-lines": {
    q: "Which shuttle bus goes downtown?",
    opts: ["The yellow bus", "The blue bus", "Both buses", "Neither, a taxi is needed"],
    ans: 1,
  },
  "directions-b2x-embassy-security-entrance": {
    q: "Where must visitors with civil affairs enter?",
    opts: ["The embassy's main entrance", "A side gate with security", "The basement entrance of the building next door", "A separate visitor building across the street"],
    ans: 2,
  },
  "directions-b2x-camp-site-numbering": {
    q: "Why doesn't the reserved site number match the sign?",
    opts: ["A printing error", "The zones were rearranged last year and the system wasn't updated", "The visitor misread the confirmation", "Sites are renumbered daily"],
    ans: 1,
  },
  "directions-b2x-elevator-restricted-floor": {
    q: "What does the visitor need to reach floor 12?",
    opts: ["A key from security", "A card-authenticated visitor pass", "An appointment confirmation", "Permission from the tenant"],
    ans: 1,
  },
  "directions-b2x-airport-rental-car-shuttle": {
    q: "Where did the rental car shuttle pickup point move to?",
    opts: ["Near exit 1", "Near exit 2", "Near exit 3", "Near the parking garage"],
    ans: 2,
  },
  "directions-b2x-temple-visitor-route": {
    q: "Why can't the visitor go directly to the main hall?",
    opts: ["It's closed for repairs", "A ceremony is in progress", "It's past visiting hours", "Only monks are allowed today"],
    ans: 1,
  },
  "directions-b2x-warehouse-loading-dock": {
    q: "Why did the driver go to the wrong loading dock?",
    opts: ["He misread the directions", "The sign plate was outdated", "GPS gave wrong coordinates", "He arrived too early"],
    ans: 1,
  },
  "directions-b2x-flea-market-vendor-map": {
    q: "Why is the vendor map often inaccurate?",
    opts: ["It's never updated", "Vendor spots change monthly by lottery", "The market moves locations", "Vendors don't register with the booth"],
    ans: 1,
  },
};
