import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Directions situation expansion (2026-08): raises A1-B2 coverage to 20 dialogues per level.
export const DIRECTIONS_EXPANSION: Dialogue[] = [
  // ---------- A1 (15) ----------
  {
    id: "directions-a1x-bank",
    situationKey: "directions",
    level: "A1",
    title: "Where's the nearest bank?",
    lines: [
      { speaker: "행인", kr: "저기요, 은행이 어디에 있어요?", en: "Excuse me, where's the bank?" },
      { speaker: "주민", kr: "저기 편의점 옆에 있어요.", en: "It's next to the convenience store over there." },
      { speaker: "행인", kr: "감사합니다.", en: "Thank you." },
      { speaker: "주민", kr: "네, 안녕히 가세요.", en: "You're welcome, take care." },
    ],
  },
  {
    id: "directions-a1x-atm",
    situationKey: "directions",
    level: "A1",
    title: "Finding an ATM",
    lines: [
      { speaker: "행인", kr: "여기 근처에 현금인출기가 있어요?", en: "Is there an ATM near here?" },
      { speaker: "주민", kr: "네, 이 건물 안에 있어요.", en: "Yes, it's inside this building." },
      { speaker: "행인", kr: "몇 층이에요?", en: "What floor?" },
      { speaker: "주민", kr: "1층이에요.", en: "The first floor." },
    ],
  },
  {
    id: "directions-a1x-pharmacy-closed",
    situationKey: "directions",
    level: "A1",
    title: "Pharmacy after hours",
    lines: [
      { speaker: "행인", kr: "약국이 문을 닫았어요.", en: "The pharmacy is closed." },
      { speaker: "주민", kr: "다른 약국은 저기 있어요.", en: "There's another pharmacy over there." },
      { speaker: "행인", kr: "멀어요?", en: "Is it far?" },
      { speaker: "주민", kr: "아니요, 가까워요.", en: "No, it's close." },
    ],
  },
  {
    id: "directions-a1x-crosswalk",
    situationKey: "directions",
    level: "A1",
    title: "Crossing to the bus stop",
    lines: [
      { speaker: "행인", kr: "버스 정류장이 길 건너에 있어요?", en: "Is the bus stop across the street?" },
      { speaker: "주민", kr: "네, 저기 횡단보도로 건너세요.", en: "Yes, cross at that crosswalk." },
      { speaker: "행인", kr: "알겠습니다, 감사해요.", en: "Got it, thanks." },
      { speaker: "주민", kr: "조심히 가세요.", en: "Take care crossing." },
    ],
  },
  {
    id: "directions-a1x-airport-platform",
    situationKey: "directions",
    level: "A1",
    title: "Platform for the airport train",
    lines: [
      { speaker: "행인", kr: "공항철도는 몇 번 승강장이에요?", en: "Which platform is the airport train?" },
      { speaker: "역무원", kr: "3번 승강장이에요.", en: "Platform 3." },
      { speaker: "행인", kr: "이쪽이 맞아요?", en: "Is it this way?" },
      { speaker: "역무원", kr: "네, 맞아요.", en: "Yes, that's right." },
    ],
  },
  {
    id: "directions-a1x-elevator",
    situationKey: "directions",
    level: "A1",
    title: "Elevator or stairs",
    lines: [
      { speaker: "행인", kr: "엘리베이터가 어디에 있어요?", en: "Where's the elevator?" },
      { speaker: "역무원", kr: "계단 옆에 있어요.", en: "It's next to the stairs." },
      { speaker: "행인", kr: "계단으로 가도 돼요?", en: "Can I take the stairs too?" },
      { speaker: "역무원", kr: "네, 둘 다 괜찮아요.", en: "Yes, either is fine." },
    ],
  },
  {
    id: "directions-a1x-last-train",
    situationKey: "directions",
    level: "A1",
    title: "Last train time",
    lines: [
      { speaker: "행인", kr: "막차가 몇 시예요?", en: "What time is the last train?" },
      { speaker: "역무원", kr: "밤 12시예요.", en: "It's midnight." },
      { speaker: "행인", kr: "아직 시간이 있네요.", en: "There's still time." },
      { speaker: "역무원", kr: "네, 서두르세요.", en: "Yes, but hurry." },
    ],
  },
  {
    id: "directions-a1x-card-tap",
    situationKey: "directions",
    level: "A1",
    title: "Where to tap the transit card",
    lines: [
      { speaker: "행인", kr: "카드를 어디에 대요?", en: "Where do I tap my card?" },
      { speaker: "역무원", kr: "여기 초록색 부분이에요.", en: "Here, on the green part." },
      { speaker: "행인", kr: "이렇게요?", en: "Like this?" },
      { speaker: "역무원", kr: "네, 맞아요.", en: "Yes, that's right." },
    ],
  },
  {
    id: "directions-a1x-parking-entrance",
    situationKey: "directions",
    level: "A1",
    title: "Parking lot entrance",
    lines: [
      { speaker: "기사", kr: "주차장 입구가 어디예요?", en: "Where's the parking lot entrance?" },
      { speaker: "안내원", kr: "건물 뒤쪽에 있어요.", en: "It's behind the building." },
      { speaker: "기사", kr: "차로 가면 돼요?", en: "Can I drive there?" },
      { speaker: "안내원", kr: "네, 바로 가세요.", en: "Yes, go straight there." },
    ],
  },
  {
    id: "directions-a1x-plaza-meet",
    situationKey: "directions",
    level: "A1",
    title: "Meeting point at the plaza",
    lines: [
      { speaker: "행인", kr: "광장 어디에서 만나요?", en: "Where in the plaza should we meet?" },
      { speaker: "주민", kr: "분수대 앞에서 만나요.", en: "Let's meet in front of the fountain." },
      { speaker: "행인", kr: "네, 좋아요.", en: "Okay, sounds good." },
      { speaker: "주민", kr: "이따 봐요.", en: "See you then." },
    ],
  },
  {
    id: "directions-a1x-cafe-restroom-code",
    situationKey: "directions",
    level: "A1",
    title: "Cafe restroom code",
    lines: [
      { speaker: "손님", kr: "화장실 비밀번호가 뭐예요?", en: "What's the restroom code?" },
      { speaker: "직원", kr: "영수증에 있어요.", en: "It's on the receipt." },
      { speaker: "손님", kr: "아, 여기 있네요.", en: "Oh, here it is." },
      { speaker: "직원", kr: "네, 맞아요.", en: "Yes, that's it." },
    ],
  },
  {
    id: "directions-a1x-exit-number",
    situationKey: "directions",
    level: "A1",
    title: "Which exit number",
    lines: [
      { speaker: "행인", kr: "몇 번 출구예요?", en: "Which exit number?" },
      { speaker: "주민", kr: "5번 출구예요.", en: "Exit 5." },
      { speaker: "행인", kr: "여기서 멀어요?", en: "Is it far from here?" },
      { speaker: "주민", kr: "아니요, 바로 앞이에요.", en: "No, it's right there." },
    ],
  },
  {
    id: "directions-a1x-post-office",
    situationKey: "directions",
    level: "A1",
    title: "Finding the post office",
    lines: [
      { speaker: "행인", kr: "우체국이 어디예요?", en: "Where's the post office?" },
      { speaker: "주민", kr: "사거리에서 왼쪽이에요.", en: "It's on the left at the intersection." },
      { speaker: "행인", kr: "걸어서 가까워요?", en: "Is it close to walk?" },
      { speaker: "주민", kr: "네, 5분이면 돼요.", en: "Yes, five minutes is enough." },
    ],
  },
  {
    id: "directions-a1x-taxi-stand",
    situationKey: "directions",
    level: "A1",
    title: "Taxi stand location",
    lines: [
      { speaker: "행인", kr: "택시 타는 곳이 어디예요?", en: "Where do I catch a taxi?" },
      { speaker: "안내원", kr: "정문 밖에 있어요.", en: "It's outside the main gate." },
      { speaker: "행인", kr: "줄이 길어요?", en: "Is the line long?" },
      { speaker: "안내원", kr: "지금은 짧아요.", en: "It's short right now." },
    ],
  },
  {
    id: "directions-a1x-park-entrance",
    situationKey: "directions",
    level: "A1",
    title: "Park entrance",
    lines: [
      { speaker: "행인", kr: "공원 입구가 어디예요?", en: "Where's the park entrance?" },
      { speaker: "주민", kr: "다리를 건너면 있어요.", en: "It's after you cross the bridge." },
      { speaker: "행인", kr: "고맙습니다.", en: "Thanks." },
      { speaker: "주민", kr: "천천히 가세요.", en: "Take your time getting there." },
    ],
  },
  // ---------- A2 (15) ----------
  {
    id: "directions-a2x-lost-card",
    situationKey: "directions",
    level: "A2",
    title: "Lost transit card gate",
    lines: [
      { speaker: "행인", kr: "교통카드를 찍었는데 문이 안 열렸어요.", en: "I tapped my transit card but the gate didn't open." },
      { speaker: "역무원", kr: "카드에 잔액이 있었어요?", en: "Did the card have enough balance?" },
      { speaker: "행인", kr: "아까 충전했는데 이상하네요.", en: "I topped it up earlier, that's strange." },
      { speaker: "역무원", kr: "여기 다시 찍어 보세요.", en: "Try tapping again here." },
      { speaker: "행인", kr: "아, 이제 열렸어요.", en: "Oh, it opened now." },
    ],
  },
  {
    id: "directions-a2x-bank-hours",
    situationKey: "directions",
    level: "A2",
    title: "Bank closing soon",
    lines: [
      { speaker: "행인", kr: "은행이 몇 시까지 열어요?", en: "Until what time is the bank open?" },
      { speaker: "주민", kr: "4시까지였는데 지금 3시 50분이에요.", en: "It was until 4, and it's 3:50 now." },
      { speaker: "행인", kr: "그럼 빨리 가야겠어요.", en: "Then I should hurry." },
      { speaker: "주민", kr: "뛰어가면 늦지 않을 거예요.", en: "If you run, you won't be late." },
      { speaker: "행인", kr: "네, 가 볼게요!", en: "Okay, I'll go now!" },
    ],
  },
  {
    id: "directions-a2x-pharmacy-night",
    situationKey: "directions",
    level: "A2",
    title: "24-hour pharmacy",
    lines: [
      { speaker: "행인", kr: "밤에도 여는 약국이 있어요?", en: "Is there a pharmacy open at night?" },
      { speaker: "주민", kr: "네, 역 앞에 24시간 약국이 있어요.", en: "Yes, there's a 24-hour pharmacy in front of the station." },
      { speaker: "행인", kr: "거기까지 얼마나 걸려요?", en: "How long does it take to get there?" },
      { speaker: "주민", kr: "걸어서 십 분쯤 걸릴 거예요.", en: "It'll take about ten minutes on foot." },
      { speaker: "행인", kr: "알겠어요, 가 볼게요.", en: "Okay, I'll go check it out." },
    ],
  },
  {
    id: "directions-a2x-bus-stop-side",
    situationKey: "directions",
    level: "A2",
    title: "Wrong side of the street",
    lines: [
      { speaker: "행인", kr: "이 정류장에서 시청 가는 버스 타요?", en: "Do I catch the City Hall bus from this stop?" },
      { speaker: "주민", kr: "아니요, 그건 반대쪽 정류장이에요.", en: "No, that's on the stop across the street." },
      { speaker: "행인", kr: "그럼 어떻게 건너가요?", en: "Then how do I cross over?" },
      { speaker: "주민", kr: "저 육교로 건너면 돼요.", en: "You can cross using that overpass." },
      { speaker: "행인", kr: "네, 감사합니다.", en: "Okay, thank you." },
    ],
  },
  {
    id: "directions-a2x-airport-checkin",
    situationKey: "directions",
    level: "A2",
    title: "Airport train check-in counter",
    lines: [
      { speaker: "행인", kr: "공항철도에서 수하물을 미리 부칠 수 있어요?", en: "Can I check my luggage in advance on the airport train?" },
      { speaker: "역무원", kr: "네, 도심공항터미널에서 가능해요.", en: "Yes, it's possible at the city air terminal." },
      { speaker: "행인", kr: "그게 어디에 있어요?", en: "Where is that?" },
      { speaker: "역무원", kr: "2번 출구로 나가면 바로 보여요.", en: "Go out exit 2 and you'll see it right away." },
      { speaker: "행인", kr: "좋아요, 가 볼게요.", en: "Great, I'll head there." },
    ],
  },
  {
    id: "directions-a2x-elevator-broken",
    situationKey: "directions",
    level: "A2",
    title: "Elevator out of order",
    lines: [
      { speaker: "행인", kr: "엘리베이터가 고장 났어요.", en: "The elevator is broken." },
      { speaker: "역무원", kr: "네, 오늘 오전부터 수리 중이에요.", en: "Yes, it's been under repair since this morning." },
      { speaker: "행인", kr: "그럼 짐을 들고 계단으로 가야 해요?", en: "So I have to carry my luggage on the stairs?" },
      { speaker: "역무원", kr: "휠체어 리프트를 쓰실 수 있어요.", en: "You can use the wheelchair lift instead." },
      { speaker: "행인", kr: "아, 다행이네요.", en: "Oh, that's a relief." },
    ],
  },
  {
    id: "directions-a2x-parking-full",
    situationKey: "directions",
    level: "A2",
    title: "Parking lot full",
    lines: [
      { speaker: "기사", kr: "여기 주차장이 다 찼어요.", en: "This parking lot is full." },
      { speaker: "안내원", kr: "네, 뒤쪽에 다른 주차장이 있어요.", en: "Yes, there's another lot behind here." },
      { speaker: "기사", kr: "거기는 자리가 있어요?", en: "Are there spots there?" },
      { speaker: "안내원", kr: "방금 확인했는데 몇 자리 남았어요.", en: "I just checked, and a few spots are left." },
      { speaker: "기사", kr: "그럼 그쪽으로 갈게요.", en: "Then I'll head over there." },
    ],
  },
  {
    id: "directions-a2x-plaza-crowded",
    situationKey: "directions",
    level: "A2",
    title: "Finding a friend in a crowded plaza",
    lines: [
      { speaker: "행인", kr: "광장에 사람이 너무 많아서 못 찾겠어요.", en: "There are too many people in the plaza, I can't find them." },
      { speaker: "주민", kr: "무슨 색 옷을 입었어요?", en: "What color clothes are they wearing?" },
      { speaker: "행인", kr: "빨간 재킷을 입었어요.", en: "They're wearing a red jacket." },
      { speaker: "주민", kr: "저기 시계탑 근처에 있는 것 같아요.", en: "I think they're near the clock tower over there." },
      { speaker: "행인", kr: "아, 찾았어요, 고마워요!", en: "Oh, I found them, thanks!" },
    ],
  },
  {
    id: "directions-a2x-cafe-code-changed",
    situationKey: "directions",
    level: "A2",
    title: "Restroom code changed",
    lines: [
      { speaker: "손님", kr: "비밀번호를 눌렀는데 안 열려요.", en: "I entered the code but it won't open." },
      { speaker: "직원", kr: "어제 비밀번호가 바뀌었어요.", en: "The code changed yesterday." },
      { speaker: "손님", kr: "새 비밀번호가 뭐예요?", en: "What's the new code?" },
      { speaker: "직원", kr: "여기 영수증 아래에 적혀 있어요.", en: "It's written at the bottom of the receipt here." },
      { speaker: "손님", kr: "아, 찾았어요.", en: "Oh, found it." },
    ],
  },
  {
    id: "directions-a2x-market-entrance",
    situationKey: "directions",
    level: "A2",
    title: "Market entrance blocked",
    lines: [
      { speaker: "행인", kr: "시장 정문이 공사 중이에요.", en: "The market's main entrance is under construction." },
      { speaker: "주민", kr: "그럼 옆문으로 들어가야 해요.", en: "Then you have to go in through the side door." },
      { speaker: "행인", kr: "옆문은 어디에 있어요?", en: "Where's the side door?" },
      { speaker: "주민", kr: "저 골목 끝에 있어요.", en: "It's at the end of that alley." },
      { speaker: "행인", kr: "알겠어요, 감사합니다.", en: "Got it, thank you." },
    ],
  },
  {
    id: "directions-a2x-hospital-wing",
    situationKey: "directions",
    level: "A2",
    title: "Which hospital wing",
    lines: [
      { speaker: "행인", kr: "응급실은 어느 쪽이에요?", en: "Which way is the emergency room?" },
      { speaker: "안내원", kr: "본관 말고 별관에 있어요.", en: "It's in the annex, not the main building." },
      { speaker: "행인", kr: "별관은 어떻게 가요?", en: "How do I get to the annex?" },
      { speaker: "안내원", kr: "밖으로 나가서 오른쪽으로 가세요.", en: "Go outside and head to the right." },
      { speaker: "행인", kr: "네, 빨리 가 볼게요.", en: "Okay, I'll hurry over." },
    ],
  },
  {
    id: "directions-a2x-luggage-locker",
    situationKey: "directions",
    level: "A2",
    title: "Finding a luggage locker",
    lines: [
      { speaker: "행인", kr: "짐 보관함이 이 근처에 있어요?", en: "Is there a luggage locker near here?" },
      { speaker: "역무원", kr: "네, 개찰구를 지나면 바로 있어요.", en: "Yes, right after you pass the ticket gate." },
      { speaker: "행인", kr: "요금은 얼마예요?", en: "How much does it cost?" },
      { speaker: "역무원", kr: "크기에 따라 다른데 보통 삼천 원이에요.", en: "It depends on the size, but it's usually 3,000 won." },
      { speaker: "행인", kr: "좋아요, 써 볼게요.", en: "Great, I'll use it." },
    ],
  },
  {
    id: "directions-a2x-stadium-gate",
    situationKey: "directions",
    level: "A2",
    title: "Which gate at the stadium",
    lines: [
      { speaker: "행인", kr: "제 자리가 몇 번 게이트예요?", en: "What gate is my seat at?" },
      { speaker: "안내원", kr: "표를 보여 주시겠어요?", en: "Could you show me your ticket?" },
      { speaker: "행인", kr: "여기요.", en: "Here it is." },
      { speaker: "안내원", kr: "7번 게이트로 가시면 돼요.", en: "You should go to gate 7." },
      { speaker: "행인", kr: "감사합니다, 찾아볼게요.", en: "Thanks, I'll head there." },
    ],
  },
  {
    id: "directions-a2x-school-visitor",
    situationKey: "directions",
    level: "A2",
    title: "Visitor entrance at a school",
    lines: [
      { speaker: "행인", kr: "방문객은 어디로 들어가요?", en: "Where do visitors enter?" },
      { speaker: "안내원", kr: "정문이 아니라 후문으로 오셔야 해요.", en: "You need to come through the back gate, not the front." },
      { speaker: "행인", kr: "후문은 여기서 멀어요?", en: "Is the back gate far from here?" },
      { speaker: "안내원", kr: "차로 이 분 정도 걸려요.", en: "It takes about two minutes by car." },
      { speaker: "행인", kr: "네, 이동할게요.", en: "Okay, I'll head over." },
    ],
  },
  {
    id: "directions-a2x-gym-floor",
    situationKey: "directions",
    level: "A2",
    title: "Which floor for the gym",
    lines: [
      { speaker: "행인", kr: "헬스장이 몇 층이에요?", en: "What floor is the gym on?" },
      { speaker: "안내원", kr: "지하 1층이에요.", en: "It's on basement floor 1." },
      { speaker: "행인", kr: "엘리베이터로 가면 돼요?", en: "Can I take the elevator?" },
      { speaker: "안내원", kr: "네, B1 버튼을 누르시면 돼요.", en: "Yes, just press the B1 button." },
      { speaker: "행인", kr: "감사합니다.", en: "Thank you." },
    ],
  },
  // ---------- B1 (16) ----------
  {
    id: "directions-b1x-one-way-confusion",
    situationKey: "directions",
    level: "B1",
    title: "Confused by a one-way street",
    lines: [
      { speaker: "기사", kr: "여기가 일방통행인 줄 몰랐어요.", en: "I didn't realize this was a one-way street." },
      { speaker: "경찰", kr: "네, 표지판을 못 보신 것 같네요.", en: "Right, it seems you missed the sign." },
      { speaker: "기사", kr: "그럼 이제 어떻게 나가야 해요?", en: "So how do I get out now?" },
      { speaker: "경찰", kr: "앞으로 쭉 가시다가 다음 골목에서 우회전하세요.", en: "Go straight ahead and turn right at the next alley." },
      { speaker: "기사", kr: "거기서 큰길로 나갈 수 있나요?", en: "Can I get to the main road from there?" },
      { speaker: "경찰", kr: "네, 바로 연결돼요.", en: "Yes, it connects directly." },
    ],
  },
  {
    id: "directions-b1x-bike-path-rules",
    situationKey: "directions",
    level: "B1",
    title: "Bike path rules explained",
    lines: [
      { speaker: "행인", kr: "이 길은 자전거만 다닐 수 있어요?", en: "Is this path only for bicycles?" },
      { speaker: "주민", kr: "네, 걸어 다니는 구간은 따로 표시돼 있어요.", en: "Yes, the walking section is marked separately." },
      { speaker: "행인", kr: "저는 어디로 걸어야 하죠?", en: "Where should I walk, then?" },
      { speaker: "주민", kr: "바닥에 초록색 선이 보행로예요.", en: "The green line on the ground is the walking path." },
      { speaker: "행인", kr: "아, 표시가 있는지 몰랐어요.", en: "Oh, I didn't notice the marking." },
      { speaker: "주민", kr: "처음 오시면 헷갈리실 수 있어요.", en: "It can be confusing the first time you come here." },
    ],
  },
  {
    id: "directions-b1x-night-bus",
    situationKey: "directions",
    level: "B1",
    title: "Asking about the night bus",
    lines: [
      { speaker: "행인", kr: "심야버스가 이 근처에서도 다녀요?", en: "Does the night bus run near here too?" },
      { speaker: "주민", kr: "네, 근데 노선이 낮 버스랑 좀 달라요.", en: "Yes, but the route is a bit different from the daytime bus." },
      { speaker: "행인", kr: "그럼 정류장 위치도 다른가요?", en: "So is the stop location different too?" },
      { speaker: "주민", kr: "이 정류장은 같이 써요.", en: "This stop is shared for both." },
      { speaker: "행인", kr: "다행이네요, 헤맬 뻔했어요.", en: "That's a relief, I almost got confused." },
      { speaker: "주민", kr: "배차 간격이 기니까 시간 확인하세요.", en: "The interval is long, so check the schedule." },
    ],
  },
  {
    id: "directions-b1x-rooftop-viewpoint",
    situationKey: "directions",
    level: "B1",
    title: "Finding a rooftop viewpoint",
    lines: [
      { speaker: "행인", kr: "여기서 야경 보기 좋은 곳 있어요?", en: "Is there a good spot to see the night view from here?" },
      { speaker: "주민", kr: "저 건물 옥상에 전망대가 있어요.", en: "There's an observation deck on the roof of that building." },
      { speaker: "행인", kr: "일반인도 올라갈 수 있어요?", en: "Can regular visitors go up there too?" },
      { speaker: "주민", kr: "네, 근데 저녁 여덟 시까지만 개방해요.", en: "Yes, but it's only open until 8 PM." },
      { speaker: "행인", kr: "지금 가면 시간 맞겠네요.", en: "If I go now, I should make it in time." },
      { speaker: "주민", kr: "엘리베이터가 좀 느리니까 서두르세요.", en: "The elevator is a bit slow, so hurry." },
    ],
  },
  {
    id: "directions-b1x-palace-shortcut",
    situationKey: "directions",
    level: "B1",
    title: "Shortcut vs scenic route to the palace",
    lines: [
      { speaker: "행인", kr: "궁궐까지 빠른 길이랑 예쁜 길 중에 뭐가 나아요?", en: "Between the fast way and the scenic way to the palace, which is better?" },
      { speaker: "주민", kr: "빠른 길은 큰길을 따라가면 십 분이에요.", en: "The fast way is ten minutes along the main road." },
      { speaker: "행인", kr: "예쁜 길은 얼마나 더 걸려요?", en: "How much longer is the scenic way?" },
      { speaker: "주민", kr: "한옥 골목을 지나가서 이십 분쯤 걸려요.", en: "It goes through the hanok alleys, so about twenty minutes." },
      { speaker: "행인", kr: "시간 여유가 있으니까 예쁜 길로 갈게요.", en: "Since I have time, I'll take the scenic route." },
      { speaker: "주민", kr: "사진 찍기 좋은 곳이 많을 거예요.", en: "There will be lots of good photo spots." },
    ],
  },
  {
    id: "directions-b1x-delivery-phone",
    situationKey: "directions",
    level: "B1",
    title: "Directing a delivery driver by phone",
    lines: [
      { speaker: "기사", kr: "고객님, 입구를 못 찾겠어요.", en: "Sir/Ma'am, I can't find the entrance." },
      { speaker: "손님", kr: "편의점 지나서 오셨어요?", en: "Did you pass the convenience store?" },
      { speaker: "기사", kr: "네, 지금 그 앞이에요.", en: "Yes, I'm in front of it now." },
      { speaker: "손님", kr: "거기서 왼쪽 골목으로 들어오세요.", en: "Turn into the alley on the left there." },
      { speaker: "기사", kr: "아, 이제 보여요, 감사합니다.", en: "Oh, I see it now, thank you." },
      { speaker: "손님", kr: "3층 초인종 눌러 주세요.", en: "Please ring the buzzer on the third floor." },
    ],
  },
  {
    id: "directions-b1x-market-stall-number",
    situationKey: "directions",
    level: "B1",
    title: "Finding a specific market stall",
    lines: [
      { speaker: "행인", kr: "떡볶이로 유명한 가게가 몇 번 골목에 있어요?", en: "Which alley number is the tteokbokki place famous around here?" },
      { speaker: "주민", kr: "정확한 번호는 모르는데 중앙 통로 근처예요.", en: "I don't know the exact number, but it's near the central aisle." },
      { speaker: "행인", kr: "중앙 통로는 어느 방향이에요?", en: "Which direction is the central aisle?" },
      { speaker: "주민", kr: "입구에서 곧장 들어가면 나와요.", en: "Go straight in from the entrance and you'll find it." },
      { speaker: "행인", kr: "냄새로도 찾을 수 있을 것 같네요.", en: "I think I could find it by smell too." },
      { speaker: "주민", kr: "맞아요, 줄 서 있는 곳이 거기예요.", en: "Right, the place with the line is it." },
    ],
  },
  {
    id: "directions-b1x-hospital-shuttle",
    situationKey: "directions",
    level: "B1",
    title: "Hospital shuttle bus stop",
    lines: [
      { speaker: "행인", kr: "본관까지 가는 셔틀버스가 있다고 들었어요.", en: "I heard there's a shuttle bus to the main building." },
      { speaker: "안내원", kr: "네, 정문 밖 셔틀 정류장에서 타시면 돼요.", en: "Yes, you can catch it at the shuttle stop outside the main gate." },
      { speaker: "행인", kr: "배차 간격이 얼마나 돼요?", en: "How often does it run?" },
      { speaker: "안내원", kr: "십오 분마다 한 대씩 와요.", en: "One comes every fifteen minutes." },
      { speaker: "행인", kr: "걸어가는 게 더 빠를 수도 있겠네요.", en: "Walking might actually be faster." },
      { speaker: "안내원", kr: "짐이 없으시면 그럴 수도 있어요.", en: "That could be true if you don't have luggage." },
    ],
  },
  {
    id: "directions-b1x-festival-crowd-control",
    situationKey: "directions",
    level: "B1",
    title: "Festival crowd control detour",
    lines: [
      { speaker: "행인", kr: "축제 때문에 이 길이 통제됐네요.", en: "This street is closed off because of the festival." },
      { speaker: "경찰", kr: "네, 우회로를 이용해 주세요.", en: "Yes, please use the detour route." },
      { speaker: "행인", kr: "그럼 시청 쪽으로 어떻게 가요?", en: "Then how do I get to City Hall?" },
      { speaker: "경찰", kr: "저쪽 골목으로 돌아서 가시면 돼요.", en: "Go around through that alley over there." },
      { speaker: "행인", kr: "시간이 얼마나 더 걸릴까요?", en: "How much longer will it take?" },
      { speaker: "경찰", kr: "한 십 분 정도 더 걸리실 거예요.", en: "It'll take about ten extra minutes." },
    ],
  },
  {
    id: "directions-b1x-university-building-numbering",
    situationKey: "directions",
    level: "B1",
    title: "Confusing building numbers on campus",
    lines: [
      { speaker: "행인", kr: "건물 번호가 순서대로가 아니네요.", en: "The building numbers aren't in order." },
      { speaker: "주민", kr: "맞아요, 신축 건물이 나중에 번호를 받아서 그래요.", en: "Right, that's because new buildings got their numbers later." },
      { speaker: "행인", kr: "그럼 공학관은 몇 번이에요?", en: "So what number is the engineering building?" },
      { speaker: "주민", kr: "7호관인데 정문에서 제일 멀어요.", en: "Building 7, and it's the farthest from the main gate." },
      { speaker: "행인", kr: "지도 앱을 보는 게 낫겠어요.", en: "I'd better look at a map app." },
      { speaker: "주민", kr: "네, 캠퍼스 앱이 더 정확해요.", en: "Yes, the campus app is more accurate." },
    ],
  },
  {
    id: "directions-b1x-ferry-terminal-gate",
    situationKey: "directions",
    level: "B1",
    title: "Wrong gate at the ferry terminal",
    lines: [
      { speaker: "행인", kr: "제주도행 배는 어느 게이트예요?", en: "Which gate is the ferry to Jeju Island?" },
      { speaker: "안내원", kr: "표를 보니 2번 게이트가 아니라 5번이네요.", en: "Looking at your ticket, it's gate 5, not gate 2." },
      { speaker: "행인", kr: "5번 게이트는 어디로 가요?", en: "Where's gate 5?" },
      { speaker: "안내원", kr: "이 통로 끝까지 가시면 나와요.", en: "Go all the way to the end of this corridor." },
      { speaker: "행인", kr: "시간이 촉박한데 뛰어야겠어요.", en: "I'm running short on time, I should run." },
      { speaker: "안내원", kr: "탑승 마감까지 아직 여유 있어요.", en: "There's still time before boarding closes." },
    ],
  },
  {
    id: "directions-b1x-mountain-cable-car",
    situationKey: "directions",
    level: "B1",
    title: "Cable car station directions",
    lines: [
      { speaker: "행인", kr: "케이블카 타는 곳까지 걸어갈 수 있어요?", en: "Can I walk to where the cable car departs?" },
      { speaker: "주민", kr: "네, 근데 경사가 좀 있어서 힘들 수 있어요.", en: "Yes, but it's a bit steep so it might be tough." },
      { speaker: "행인", kr: "셔틀버스는 없어요?", en: "Isn't there a shuttle bus?" },
      { speaker: "주민", kr: "있는데 주말에만 운행해요.", en: "There is, but it only runs on weekends." },
      { speaker: "행인", kr: "오늘은 평일이라 걸어야겠네요.", en: "Since it's a weekday today, I'll have to walk." },
      { speaker: "주민", kr: "천천히 가시면 이십 분이면 돼요.", en: "If you go slowly, twenty minutes is enough." },
    ],
  },
  {
    id: "directions-b1x-office-building-security",
    situationKey: "directions",
    level: "B1",
    title: "Security desk directions in an office building",
    lines: [
      { speaker: "행인", kr: "3층 회의실을 찾고 있는데요.", en: "I'm looking for the meeting room on the third floor." },
      { speaker: "안내원", kr: "방문증부터 받으셔야 해요.", en: "You'll need to get a visitor pass first." },
      { speaker: "행인", kr: "그건 어디서 받아요?", en: "Where do I get that?" },
      { speaker: "안내원", kr: "이 데스크에서 신분증 주시면 발급해 드려요.", en: "Give me your ID at this desk and I'll issue one." },
      { speaker: "행인", kr: "여기 있습니다.", en: "Here you go." },
      { speaker: "안내원", kr: "엘리베이터 왼쪽 첫 번째가 3층 버튼이에요.", en: "The first button on the left of the elevator is for the third floor." },
    ],
  },
  {
    id: "directions-b1x-riverside-bike-rental",
    situationKey: "directions",
    level: "B1",
    title: "Riverside bike rental spot",
    lines: [
      { speaker: "행인", kr: "따릉이 대여소가 이 근처에 몇 개나 있어요?", en: "How many bike rental stations are near here?" },
      { speaker: "주민", kr: "강변을 따라 세 개 정도 있어요.", en: "There are about three along the riverside." },
      { speaker: "행인", kr: "제일 가까운 곳은 어디예요?", en: "Which one is closest?" },
      { speaker: "주민", kr: "다리 밑에 하나 있는데 자전거가 자주 없어요.", en: "There's one under the bridge, but bikes are often unavailable." },
      { speaker: "행인", kr: "그럼 다른 곳으로 가야겠네요.", en: "Then I should go to another one." },
      { speaker: "주민", kr: "공원 입구 쪽이 재고가 더 많아요.", en: "The one by the park entrance usually has more available." },
    ],
  },
  {
    id: "directions-b1x-airport-transfer-desk",
    situationKey: "directions",
    level: "B1",
    title: "Transfer desk at the airport",
    lines: [
      { speaker: "행인", kr: "환승하는데 어디로 가야 해요?", en: "Where do I go for a connecting flight?" },
      { speaker: "안내원", kr: "환승 안내 데스크가 이쪽에 있어요.", en: "The transfer information desk is this way." },
      { speaker: "행인", kr: "거기서 짐도 다시 부쳐야 해요?", en: "Do I need to recheck my luggage there too?" },
      { speaker: "안내원", kr: "직항 연결편이면 안 하셔도 돼요.", en: "If it's a direct connecting flight, you don't have to." },
      { speaker: "행인", kr: "다행이네요, 시간이 별로 없었거든요.", en: "That's a relief, I didn't have much time." },
      { speaker: "안내원", kr: "그래도 서두르시는 게 좋아요.", en: "Still, it's best to hurry." },
    ],
  },
  {
    id: "directions-b1x-apartment-visitor-parking",
    situationKey: "directions",
    level: "B1",
    title: "Visitor parking at an apartment complex",
    lines: [
      { speaker: "기사", kr: "방문 차량은 어디에 주차해요?", en: "Where do visitor cars park?" },
      { speaker: "경비원", kr: "정문 옆에 방문자 구역이 있어요.", en: "There's a visitor zone next to the main gate." },
      { speaker: "기사", kr: "거기 자리가 있을까요?", en: "Would there be a spot there?" },
      { speaker: "경비원", kr: "지금 시간엔 보통 여유가 있어요.", en: "There's usually space at this time." },
      { speaker: "기사", kr: "몇 동으로 가면 되는지도 알려 주시겠어요?", en: "Could you also tell me which building to go to?" },
      { speaker: "경비원", kr: "101동은 저쪽 오른편이에요.", en: "Building 101 is over there on the right." },
    ],
  },
  // ---------- B2 (16) ----------
  {
    id: "directions-b2x-underground-mall-maze",
    situationKey: "directions",
    level: "B2",
    title: "Getting lost in an underground shopping mall",
    lines: [
      { speaker: "행인", kr: "지하상가가 이렇게 복잡한 줄 몰랐어요, 완전히 헤맸어요.", en: "I had no idea the underground mall was this complicated, I got completely lost." },
      { speaker: "주민", kr: "처음 오시는 분들은 다 그러세요, 구역별로 색깔이 달라서 그걸 기준으로 삼으시면 돼요.", en: "First-timers always do, but each section is color-coded so you can use that as a reference." },
      { speaker: "행인", kr: "아, 그러고 보니 바닥 색이 다르긴 하네요.", en: "Oh, now that you mention it, the floor colors are different." },
      { speaker: "주민", kr: "빨간 구역이 의류고, 파란 구역이 잡화예요.", en: "The red zone is clothing, and the blue zone is general goods." },
      { speaker: "행인", kr: "그럼 제가 찾는 신발 가게는 어느 쪽이에요?", en: "So which side is the shoe store I'm looking for?" },
      { speaker: "주민", kr: "신발은 파란 구역 끝쪽에 몰려 있어요.", en: "Shoe stores are clustered at the far end of the blue zone." },
      { speaker: "행인", kr: "덕분에 이제 방향이 좀 잡히네요, 감사해요.", en: "Thanks to you I finally have a sense of direction, thank you." },
    ],
  },
  {
    id: "directions-b2x-toll-gate-lane",
    situationKey: "directions",
    level: "B2",
    title: "Picking the wrong toll gate lane",
    lines: [
      { speaker: "기사", kr: "하이패스 차선인 줄 모르고 들어왔는데 어떡하죠?", en: "I didn't realize this was a Hi-pass-only lane, what should I do?" },
      { speaker: "경찰", kr: "일단 속도를 줄이시고 그대로 통과하시면 나중에 문자로 요금이 청구돼요.", en: "Slow down for now and pass through as is, the toll will be billed to you by text later." },
      { speaker: "기사", kr: "벌금은 안 나오나요?", en: "Won't I get a fine?" },
      { speaker: "경찰", kr: "실수로 들어간 경우엔 요금만 부과되니까 걱정 안 하셔도 돼요.", en: "For accidental entries, only the toll is charged, so you don't need to worry." },
      { speaker: "기사", kr: "다음부터는 표지판을 더 잘 봐야겠네요.", en: "I'll have to watch the signs more carefully next time." },
      { speaker: "경찰", kr: "일반 차선은 항상 오른쪽에 몰려 있으니 참고하세요.", en: "The regular lanes are always clustered on the right, keep that in mind." },
    ],
  },
  {
    id: "directions-b2x-hiking-map-inconsistency",
    situationKey: "directions",
    level: "B2",
    title: "Trail map doesn't match reality",
    lines: [
      { speaker: "행인", kr: "지도에는 여기서 갈림길이 두 개인데 실제로는 세 개네요.", en: "The map shows two forks here, but there are actually three." },
      { speaker: "주민", kr: "아, 그거 작년에 새로 낸 샛길일 거예요, 지도가 아직 업데이트가 안 됐어요.", en: "Ah, that's probably a new side trail from last year, the map hasn't been updated yet." },
      { speaker: "행인", kr: "그럼 어느 길이 원래 정상으로 가는 길이에요?", en: "So which one is the original route to the summit?" },
      { speaker: "주민", kr: "가운데 길이 정상 길이고, 왼쪽은 전망대로 빠지는 샛길이에요.", en: "The middle path is the summit route, and the left one branches off to a viewpoint." },
      { speaker: "행인", kr: "전망대 쪽도 궁금한데 시간이 얼마나 더 걸릴까요?", en: "I'm curious about the viewpoint too, how much longer would it add?" },
      { speaker: "주민", kr: "왕복으로 한 삼십 분 정도 더 걸릴 거예요.", en: "It would add about thirty minutes round trip." },
      { speaker: "행인", kr: "그럼 정상 먼저 갔다가 내려오면서 들를게요.", en: "Then I'll go to the summit first and stop by on the way down." },
    ],
  },
  {
    id: "directions-b2x-delivery-address-mismatch",
    situationKey: "directions",
    level: "B2",
    title: "Delivery address doesn't match the building",
    lines: [
      { speaker: "기사", kr: "주소지에 왔는데 건물 이름이 앱이랑 다르게 붙어 있어요.", en: "I've arrived at the address, but the building name posted here doesn't match the app." },
      { speaker: "손님", kr: "아, 저희 건물이 최근에 이름을 바꿨는데 등록이 안 됐나 봐요.", en: "Oh, our building recently changed its name, it seems the registration wasn't updated." },
      { speaker: "기사", kr: "그럼 예전 이름이 뭐였는지 알 수 있을까요, 확인하고 싶어서요.", en: "Could you tell me the old name then, I want to double-check." },
      { speaker: "손님", kr: "한빛빌딩이었어요, 간판은 아직 그대로 붙어 있을 거예요.", en: "It was Hanbit Building, the sign is probably still up as is." },
      { speaker: "기사", kr: "아, 맞네요, 찾았습니다.", en: "Ah, that's right, I found it." },
      { speaker: "손님", kr: "정문 말고 후문으로 오시면 더 가까워요.", en: "It's closer if you come through the back door instead of the front." },
      { speaker: "기사", kr: "네, 후문으로 돌아갈게요.", en: "Okay, I'll go around to the back door." },
    ],
  },
  {
    id: "directions-b2x-subway-construction-detour",
    situationKey: "directions",
    level: "B2",
    title: "Station renovation forces a longer walk",
    lines: [
      { speaker: "행인", kr: "3번 출구가 공사 때문에 막혀 있던데 다른 길이 있나요?", en: "Exit 3 is blocked because of construction, is there another way?" },
      { speaker: "역무원", kr: "네, 대신 1번 출구로 나가셔서 크게 돌아가셔야 해요.", en: "Yes, you'll need to exit through gate 1 and go a longer way around instead." },
      { speaker: "행인", kr: "그럼 원래보다 시간이 얼마나 더 걸려요?", en: "So how much longer than usual would that take?" },
      { speaker: "역무원", kr: "체감상 한 오 분에서 십 분 정도 더 걸리실 거예요.", en: "It would feel like about five to ten minutes longer." },
      { speaker: "행인", kr: "공사가 언제까지 계속되는지 아세요?", en: "Do you know how long the construction will continue?" },
      { speaker: "역무원", kr: "다음 달 말까지라고 안내판에 쓰여 있더라고요.", en: "The sign says it's until the end of next month." },
      { speaker: "행인", kr: "그때까지는 어쩔 수 없이 돌아가야겠네요.", en: "Until then I guess I'll just have to take the long way." },
    ],
  },
  {
    id: "directions-b2x-shared-office-floor-plan",
    situationKey: "directions",
    level: "B2",
    title: "Confusing floor plan at a shared office",
    lines: [
      { speaker: "행인", kr: "회의실 이름이 다 비슷해서 헷갈리는데 정확히 어디예요?", en: "The meeting room names are all similar and confusing, where exactly is it?" },
      { speaker: "안내원", kr: "'해오름'실은 A동이고 '해오름 2'는 B동에 있어서 다들 처음엔 헷갈려 하세요.", en: "'Haeoreum' room is in Building A, and 'Haeoreum 2' is in Building B, everyone gets confused at first." },
      { speaker: "행인", kr: "제가 예약한 건 그냥 '해오름'인데 그럼 A동 맞죠?", en: "The one I booked is just 'Haeoreum', so that's Building A, right?" },
      { speaker: "안내원", kr: "네 맞아요, 로비에서 왼쪽 복도로 쭉 가시면 나와요.", en: "Yes, that's right, go straight down the left hallway from the lobby." },
      { speaker: "행인", kr: "혹시 표지판이 따로 붙어 있나요, 아니면 그냥 번호만 있어요?", en: "Is there a separate sign, or just room numbers?" },
      { speaker: "안내원", kr: "문 앞에 이름표가 붙어 있는데 조명이 어두워서 잘 안 보일 수도 있어요.", en: "There's a nameplate on the door, but the lighting is dim so it might be hard to see." },
      { speaker: "행인", kr: "그럼 조심해서 찾아볼게요, 감사합니다.", en: "Then I'll look carefully, thank you." },
    ],
  },
  {
    id: "directions-b2x-riverside-run-route",
    situationKey: "directions",
    level: "B2",
    title: "Choosing a running route along the river",
    lines: [
      { speaker: "행인", kr: "아침에 뛸 만한 코스 좀 추천해 주실 수 있어요?", en: "Could you recommend a good route for a morning run?" },
      { speaker: "주민", kr: "강변 코스가 평평해서 좋은데 이 시간엔 자전거랑 겹쳐서 좀 복잡해요.", en: "The riverside route is flat and nice, but at this hour it overlaps with cyclists so it gets a bit crowded." },
      { speaker: "행인", kr: "그럼 사람이 덜 몰리는 다른 코스는 없어요?", en: "Then is there another route that's less crowded?" },
      { speaker: "주민", kr: "공원 안쪽으로 도는 코스가 있는데 대신 약간 오르막이에요.", en: "There's a route that loops through the inside of the park, but it has a slight uphill." },
      { speaker: "행인", kr: "오르막이면 거리도 더 짧아지나요?", en: "If it has an uphill, is the distance shorter too?" },
      { speaker: "주민", kr: "아니요, 거리는 비슷한데 체감 난이도가 좀 더 있어요.", en: "No, the distance is similar, but it feels a bit more challenging." },
      { speaker: "행인", kr: "그럼 오늘은 공원 코스로 한번 뛰어 볼게요.", en: "Then I'll try the park route today." },
    ],
  },
  {
    id: "directions-b2x-night-market-alley-numbers",
    situationKey: "directions",
    level: "B2",
    title: "Finding a stall by unofficial alley numbers",
    lines: [
      { speaker: "행인", kr: "여기 골목마다 이름이 없어서 위치를 설명하기가 힘드네요.", en: "None of these alleys have names, so it's hard to explain the location." },
      { speaker: "주민", kr: "상인들끼리는 그냥 번호로 불러요, 저기가 3번 골목이에요.", en: "Vendors just call them by numbers among themselves, that one over there is alley 3." },
      { speaker: "행인", kr: "그럼 지도 앱에는 왜 하나도 안 나와요?", en: "Then why doesn't the map app show any of this?" },
      { speaker: "주민", kr: "비공식 명칭이라 등록이 안 돼 있거든요.", en: "They're unofficial names, so they're not registered." },
      { speaker: "행인", kr: "그럼 친구한테는 어떻게 설명해야 하죠?", en: "So how should I explain it to a friend, then?" },
      { speaker: "주민", kr: "입구 사진을 찍어서 보내는 게 제일 정확해요.", en: "Taking a photo of the entrance and sending it is the most accurate way." },
      { speaker: "행인", kr: "좋은 방법이네요, 그렇게 할게요.", en: "That's a good idea, I'll do that." },
    ],
  },
  {
    id: "directions-b2x-cruise-terminal-shuttle-lines",
    situationKey: "directions",
    level: "B2",
    title: "Two shuttle lines at the cruise terminal",
    lines: [
      { speaker: "행인", kr: "셔틀버스가 두 종류인데 뭘 타야 시내로 가요?", en: "There are two kinds of shuttle buses, which one goes downtown?" },
      { speaker: "안내원", kr: "파란색 버스는 시내로 가고 노란색은 근처 아울렛으로 가요.", en: "The blue bus goes downtown, and the yellow one goes to a nearby outlet mall." },
      { speaker: "행인", kr: "시내까지 얼마나 걸려요?", en: "How long does it take to get downtown?" },
      { speaker: "안내원", kr: "정체가 없으면 사십 분, 있으면 한 시간 넘게 걸릴 수도 있어요.", en: "It's forty minutes without traffic, but could take over an hour with it." },
      { speaker: "행인", kr: "지금 시간대는 어때요?", en: "How is it at this time of day?" },
      { speaker: "안내원", kr: "오후라 좀 막힐 수 있으니 여유 있게 나오세요.", en: "It's the afternoon so it might be congested, so leave with some buffer time." },
      { speaker: "행인", kr: "알겠어요, 서두를게요.", en: "Got it, I'll get moving." },
    ],
  },
  {
    id: "directions-b2x-embassy-security-entrance",
    situationKey: "directions",
    level: "B2",
    title: "Finding the correct entrance at an embassy",
    lines: [
      { speaker: "행인", kr: "여권 신청하러 왔는데 정문에서 안 받아 주시네요.", en: "I came to apply for a passport, but they wouldn't accept me at the main entrance." },
      { speaker: "경찰", kr: "민원인은 옆 건물 지하 입구로 들어가셔야 해요.", en: "Visitors with civil affairs need to enter through the basement entrance of the building next door." },
      { speaker: "행인", kr: "지하 입구는 어디로 돌아가야 나와요?", en: "Which way do I go around to reach the basement entrance?" },
      { speaker: "경찰", kr: "이 담장을 따라 오른쪽으로 백 미터쯤 가시면 계단이 보여요.", en: "Go right along this wall for about a hundred meters and you'll see stairs." },
      { speaker: "행인", kr: "신분증도 미리 준비해야 하나요?", en: "Should I have my ID ready in advance too?" },
      { speaker: "경찰", kr: "네, 입구에서 검사하니까 미리 꺼내 두세요.", en: "Yes, they check it at the entrance, so have it out beforehand." },
      { speaker: "행인", kr: "알겠습니다, 감사해요.", en: "Understood, thank you." },
    ],
  },
  {
    id: "directions-b2x-camp-site-numbering",
    situationKey: "directions",
    level: "B2",
    title: "Campsite numbering doesn't match the reservation",
    lines: [
      { speaker: "행인", kr: "예약한 자리 번호랑 팻말에 붙은 번호가 안 맞는 것 같아요.", en: "The reserved site number doesn't seem to match the number on the sign." },
      { speaker: "안내원", kr: "작년에 구역을 재배치하면서 번호가 좀 바뀌었어요.", en: "The numbers changed a bit when the zones were rearranged last year." },
      { speaker: "행인", kr: "그럼 예약 시스템은 업데이트가 안 된 거예요?", en: "So the reservation system wasn't updated then?" },
      { speaker: "안내원", kr: "네, 죄송해요, 현장 번호 기준으로 다시 안내해 드릴게요.", en: "Yes, sorry about that, let me guide you again based on the on-site numbering." },
      { speaker: "행인", kr: "저희는 강 쪽 자리를 원했는데 그건 어디예요?", en: "We wanted a spot by the river, where's that?" },
      { speaker: "안내원", kr: "강변 구역은 이제 A로 시작하는 번호예요, 저쪽으로 가시면 돼요.", en: "The riverside zone now starts with the letter A, you can head that way." },
      { speaker: "행인", kr: "네, 그쪽으로 가 볼게요.", en: "Okay, I'll head over there." },
    ],
  },
  {
    id: "directions-b2x-elevator-restricted-floor",
    situationKey: "directions",
    level: "B2",
    title: "Elevator won't go to a restricted floor",
    lines: [
      { speaker: "행인", kr: "12층 버튼을 눌렀는데 불이 안 들어와요.", en: "I pressed the button for floor 12 but it's not lighting up." },
      { speaker: "안내원", kr: "그 층은 카드 인증을 해야 올라가요, 방문증 있으세요?", en: "That floor requires a card authentication to go up, do you have a visitor pass?" },
      { speaker: "행인", kr: "아직 못 받았는데 어디서 받아요?", en: "I haven't gotten one yet, where do I get it?" },
      { speaker: "안내원", kr: "1층 로비 데스크에서 발급받으시면 돼요.", en: "You can get one issued at the lobby desk on the first floor." },
      { speaker: "행인", kr: "다시 내려가야 하는 거네요.", en: "So I have to go back down." },
      { speaker: "안내원", kr: "네, 근데 발급이 빨라서 오래 안 걸리실 거예요.", en: "Yes, but issuing is quick so it won't take long." },
      { speaker: "행인", kr: "알겠습니다, 금방 다녀올게요.", en: "Okay, I'll be back quickly." },
    ],
  },
  {
    id: "directions-b2x-airport-rental-car-shuttle",
    situationKey: "directions",
    level: "B2",
    title: "Rental car shuttle pickup point moved",
    lines: [
      { speaker: "행인", kr: "렌터카 셔틀 타는 곳이 여기 맞아요? 안내판이랑 위치가 다른 것 같아서요.", en: "Is this the right spot for the rental car shuttle? The signage seems to not match the location." },
      { speaker: "안내원", kr: "아, 지난주부터 탑승 위치가 3번 출구 쪽으로 옮겨졌어요.", en: "Ah, the pickup location moved to near exit 3 starting last week." },
      { speaker: "행인", kr: "그럼 여기서 얼마나 걸어가야 해요?", en: "How far do I need to walk from here, then?" },
      { speaker: "안내원", kr: "짐이 있으시면 한 오 분 정도 걸리실 거예요.", en: "With luggage, it'll take about five minutes." },
      { speaker: "행인", kr: "표지판을 새로 세워야 하는 거 아니에요?", en: "Shouldn't they put up new signs?" },
      { speaker: "안내원", kr: "맞아요, 저희도 계속 건의하고 있어요.", en: "You're right, we keep raising that too." },
      { speaker: "행인", kr: "그럼 얼른 3번 출구로 가 볼게요.", en: "Then I'll head to exit 3 right away." },
    ],
  },
  {
    id: "directions-b2x-temple-visitor-route",
    situationKey: "directions",
    level: "B2",
    title: "Temple has a separate route for visitors during a ceremony",
    lines: [
      { speaker: "행인", kr: "법당 쪽으로 가려고 하는데 스님들이 지나가시라고 막으시네요.", en: "I was heading toward the main hall, but the monks are stopping people from passing." },
      { speaker: "주민", kr: "지금 의식 중이라 방문객은 옆길로 돌아가셔야 해요.", en: "There's a ceremony going on right now, so visitors have to go around the side path." },
      { speaker: "행인", kr: "옆길로 가면 법당을 아예 못 보나요?", en: "If I take the side path, will I not be able to see the main hall at all?" },
      { speaker: "주민", kr: "아니요, 조금 멀리서 보이긴 하는데 가까이는 못 가요.", en: "No, you can see it from a bit farther away, you just can't get close." },
      { speaker: "행인", kr: "의식은 언제쯤 끝나요?", en: "About when does the ceremony end?" },
      { speaker: "주민", kr: "보통 한 시간쯤 걸리니까 그때 다시 오시면 돼요.", en: "It usually takes about an hour, so you could come back then." },
      { speaker: "행인", kr: "그럼 다른 곳부터 둘러보고 다시 올게요.", en: "Then I'll look around elsewhere first and come back." },
    ],
  },
  {
    id: "directions-b2x-warehouse-loading-dock",
    situationKey: "directions",
    level: "B2",
    title: "Truck driver directed to the wrong loading dock",
    lines: [
      { speaker: "기사", kr: "3번 하역장으로 오라고 하셨는데 여기는 5번이라고 쓰여 있는데요.", en: "You told me to come to loading dock 3, but this one is marked 5." },
      { speaker: "안내원", kr: "죄송해요, 번호판이 옛날 거라 안 바뀌었어요.", en: "Sorry, the sign plate is old and hasn't been updated." },
      { speaker: "기사", kr: "그럼 실제 3번은 어디예요?", en: "So where's the actual number 3?" },
      { speaker: "안내원", kr: "여기서 두 번째 건물이 진짜 3번이에요.", en: "The second building from here is the real number 3." },
      { speaker: "기사", kr: "차를 돌려서 가야 하는데 공간이 좁네요.", en: "I need to turn the truck around, but the space is tight." },
      { speaker: "안내원", kr: "제가 나가서 후진하시는 거 봐 드릴게요.", en: "I'll go out and guide you while you back up." },
      { speaker: "기사", kr: "감사합니다, 도움이 많이 되네요.", en: "Thanks, that's a big help." },
    ],
  },
  {
    id: "directions-b2x-flea-market-vendor-map",
    situationKey: "directions",
    level: "B2",
    title: "Vendor map doesn't match the actual flea market layout",
    lines: [
      { speaker: "행인", kr: "안내소에서 받은 지도랑 실제 배치가 다른 것 같아요.", en: "The map I got from the information booth doesn't seem to match the actual layout." },
      { speaker: "주민", kr: "네, 매달 판매자들 위치가 추첨으로 바뀌어서 지도가 자주 틀려요.", en: "Right, the vendor positions are decided by lottery every month, so the map is often wrong." },
      { speaker: "행인", kr: "그럼 원하는 가게를 어떻게 찾아요?", en: "Then how do I find the shop I'm looking for?" },
      { speaker: "주민", kr: "구역 번호는 안 바뀌니까 그걸로 물어보시면 돼요.", en: "The section numbers don't change, so you can ask using those." },
      { speaker: "행인", kr: "제가 찾는 가게는 3구역이라고 들었어요.", en: "I heard the shop I'm looking for is in section 3." },
      { speaker: "주민", kr: "3구역은 저 천막들 지나서 왼쪽이에요.", en: "Section 3 is on the left past those tents." },
      { speaker: "행인", kr: "네, 구역 번호로 다시 찾아볼게요, 감사합니다.", en: "Okay, I'll look again using the section number, thank you." },
    ],
  },
];

export const DIRECTIONS_QUIZZES: Record<string, DialogueQuiz> = {
  "directions-a1x-bank": {
    q: "Where is the bank located?",
    opts: ["Next to the pharmacy", "Next to the convenience store", "Across from the station", "Inside the mall"],
    ans: 1,
  },
  "directions-a1x-atm": {
    q: "Where is the ATM?",
    opts: ["Outside the building", "On the second floor", "Inside the building, first floor", "Next door"],
    ans: 2,
  },
  "directions-a1x-pharmacy-closed": {
    q: "Why does the pedestrian need another pharmacy?",
    opts: ["It's too expensive", "The first one is closed", "It's out of medicine", "It moved away"],
    ans: 1,
  },
  "directions-a1x-crosswalk": {
    q: "How should the pedestrian get to the bus stop?",
    opts: ["Take an underpass", "Use the crosswalk", "Take a taxi", "Wait for a shuttle"],
    ans: 1,
  },
  "directions-a1x-airport-platform": {
    q: "Which platform is the airport train?",
    opts: ["Platform 1", "Platform 2", "Platform 3", "Platform 4"],
    ans: 2,
  },
  "directions-a1x-elevator": {
    q: "Where is the elevator?",
    opts: ["Near the entrance", "Next to the stairs", "On the second floor", "Behind the ticket gate"],
    ans: 1,
  },
  "directions-a1x-last-train": {
    q: "What time is the last train?",
    opts: ["10 PM", "11 PM", "Midnight", "1 AM"],
    ans: 2,
  },
  "directions-a1x-card-tap": {
    q: "Where does the person tap their card?",
    opts: ["The red part", "The blue part", "The green part", "The yellow part"],
    ans: 2,
  },
  "directions-a1x-parking-entrance": {
    q: "Where is the parking lot entrance?",
    opts: ["In front of the building", "Behind the building", "Underground", "Next to the elevator"],
    ans: 1,
  },
  "directions-a1x-plaza-meet": {
    q: "Where will they meet in the plaza?",
    opts: ["By the entrance gate", "By the clock tower", "In front of the fountain", "Near the parking lot"],
    ans: 2,
  },
  "directions-a1x-cafe-restroom-code": {
    q: "Where can the restroom code be found?",
    opts: ["On the menu", "On the door", "On the receipt", "On the wall"],
    ans: 2,
  },
  "directions-a1x-exit-number": {
    q: "Which exit is being discussed?",
    opts: ["Exit 3", "Exit 4", "Exit 5", "Exit 6"],
    ans: 2,
  },
  "directions-a1x-post-office": {
    q: "How do you get to the post office?",
    opts: ["Turn right at the intersection", "Turn left at the intersection", "Go straight past the bank", "Take the bus"],
    ans: 1,
  },
  "directions-a1x-taxi-stand": {
    q: "Where is the taxi stand?",
    opts: ["Inside the building", "Behind the building", "Outside the main gate", "Near the elevator"],
    ans: 2,
  },
  "directions-a1x-park-entrance": {
    q: "How do you reach the park entrance?",
    opts: ["Turn left at the sign", "Cross the bridge", "Take the stairs down", "Walk through the alley"],
    ans: 1,
  },
  "directions-a2x-lost-card": {
    q: "What was the likely problem with the gate?",
    opts: ["The card was expired", "It just needed to be tapped again", "The gate was broken", "The card had no balance"],
    ans: 1,
  },
  "directions-a2x-bank-hours": {
    q: "Why does the pedestrian need to hurry?",
    opts: ["The bank is far away", "The bank closes soon", "The line is long", "It's about to rain"],
    ans: 1,
  },
  "directions-a2x-pharmacy-night": {
    q: "Where is the 24-hour pharmacy located?",
    opts: ["Near the park", "In front of the station", "Next to the bank", "Behind the market"],
    ans: 1,
  },
  "directions-a2x-bus-stop-side": {
    q: "How does the pedestrian cross to the correct bus stop?",
    opts: ["Wait for a green light", "Use the overpass", "Ask a driver for a ride", "Take a different bus"],
    ans: 1,
  },
  "directions-a2x-airport-checkin": {
    q: "Where can luggage be checked in advance?",
    opts: ["At the airport gate", "At the city air terminal", "At the train station office", "Online only"],
    ans: 1,
  },
  "directions-a2x-elevator-broken": {
    q: "What alternative does the station worker suggest?",
    opts: ["Wait for repairs", "Use the wheelchair lift", "Take a taxi instead", "Use a different station"],
    ans: 1,
  },
  "directions-a2x-parking-full": {
    q: "What does the driver decide to do?",
    opts: ["Wait for a spot to open", "Go to the lot behind this one", "Park illegally", "Turn back home"],
    ans: 1,
  },
  "directions-a2x-plaza-crowded": {
    q: "How does the pedestrian find their friend?",
    opts: ["By calling out their name", "By the color of their jacket", "By waiting at the entrance", "By checking a map app"],
    ans: 1,
  },
  "directions-a2x-cafe-code-changed": {
    q: "Why didn't the old restroom code work?",
    opts: ["The customer misread it", "The code changed yesterday", "The door was locked", "It was never valid"],
    ans: 1,
  },
  "directions-a2x-market-entrance": {
    q: "Why does the pedestrian need to use the side door?",
    opts: ["The market is closed", "The main entrance is under construction", "The side door is faster", "It's a members-only entrance"],
    ans: 1,
  },
  "directions-a2x-hospital-wing": {
    q: "Where is the emergency room?",
    opts: ["In the main building", "In the annex", "On the second floor", "Near the parking lot"],
    ans: 1,
  },
  "directions-a2x-luggage-locker": {
    q: "Where is the luggage locker located?",
    opts: ["Before the ticket gate", "Right after the ticket gate", "Outside the station", "On the platform"],
    ans: 1,
  },
  "directions-a2x-stadium-gate": {
    q: "Which gate should the visitor go to?",
    opts: ["Gate 5", "Gate 6", "Gate 7", "Gate 8"],
    ans: 2,
  },
  "directions-a2x-school-visitor": {
    q: "Which entrance should visitors use?",
    opts: ["The front gate", "The back gate", "The side gate", "The staff entrance"],
    ans: 1,
  },
  "directions-a2x-gym-floor": {
    q: "What floor is the gym on?",
    opts: ["First floor", "Second floor", "Basement floor 1", "Basement floor 2"],
    ans: 2,
  },
  "directions-b1x-one-way-confusion": {
    q: "What should the driver do to get out?",
    opts: ["Turn around immediately", "Go straight, then turn right at the next alley", "Park and wait", "Ask a passerby to guide the car"],
    ans: 1,
  },
  "directions-b1x-bike-path-rules": {
    q: "How is the walking path marked?",
    opts: ["With a red line", "With a blue line", "With a green line", "With a yellow line"],
    ans: 2,
  },
  "directions-b1x-night-bus": {
    q: "What's true about the night bus stop?",
    opts: ["It uses a different stop from the day bus", "It shares the same stop as the day bus", "It has no fixed stop", "It only stops at the terminal"],
    ans: 1,
  },
  "directions-b1x-rooftop-viewpoint": {
    q: "Until when is the rooftop observation deck open?",
    opts: ["7 PM", "8 PM", "9 PM", "10 PM"],
    ans: 1,
  },
  "directions-b1x-palace-shortcut": {
    q: "Which route does the pedestrian choose?",
    opts: ["The fast route along the main road", "The scenic route through the hanok alleys", "Neither, they take a taxi", "They ask for a third option"],
    ans: 1,
  },
  "directions-b1x-delivery-phone": {
    q: "Where should the driver ring the buzzer?",
    opts: ["First floor", "Second floor", "Third floor", "Fourth floor"],
    ans: 2,
  },
  "directions-b1x-market-stall-number": {
    q: "How does the resident suggest finding the tteokbokki stall?",
    opts: ["By its exact stall number", "By following the smell and the line", "By asking a security guard", "By checking a map board"],
    ans: 1,
  },
  "directions-b1x-hospital-shuttle": {
    q: "How often does the shuttle bus run?",
    opts: ["Every 5 minutes", "Every 10 minutes", "Every 15 minutes", "Every 30 minutes"],
    ans: 2,
  },
  "directions-b1x-festival-crowd-control": {
    q: "Why is the street closed?",
    opts: ["Road construction", "A festival", "A car accident", "A protest"],
    ans: 1,
  },
  "directions-b1x-university-building-numbering": {
    q: "Why are the building numbers confusing?",
    opts: ["They were never assigned properly", "New buildings got numbers later, out of order", "The signs were removed", "Numbers change every semester"],
    ans: 1,
  },
  "directions-b1x-ferry-terminal-gate": {
    q: "What mistake did the pedestrian almost make?",
    opts: ["Going to the wrong terminal", "Going to gate 2 instead of gate 5", "Missing the boarding time entirely", "Taking the wrong ferry"],
    ans: 1,
  },
  "directions-b1x-mountain-cable-car": {
    q: "Why does the pedestrian have to walk instead of taking a shuttle?",
    opts: ["The shuttle is broken", "The shuttle only runs on weekends", "The shuttle is too expensive", "There is no shuttle at all"],
    ans: 1,
  },
  "directions-b1x-office-building-security": {
    q: "What must the visitor do before going up?",
    opts: ["Call ahead", "Get a visitor pass at the desk", "Wait for an escort", "Sign a form online"],
    ans: 1,
  },
  "directions-b1x-riverside-bike-rental": {
    q: "Which rental spot does the resident recommend?",
    opts: ["The one under the bridge", "The one by the park entrance", "The one near the dam", "None, better to walk"],
    ans: 1,
  },
  "directions-b1x-airport-transfer-desk": {
    q: "Does the passenger need to recheck luggage?",
    opts: ["Yes, always", "No, since it's a direct connecting flight", "Only for international flights", "Only if bags are overweight"],
    ans: 1,
  },
  "directions-b1x-apartment-visitor-parking": {
    q: "Where is the visitor parking zone?",
    opts: ["Behind building 101", "Next to the main gate", "Underground", "Near the playground"],
    ans: 1,
  },
  "directions-b2x-underground-mall-maze": {
    q: "How can visitors navigate the underground mall's sections?",
    opts: ["By floor number", "By color-coded zones", "By store directory kiosks", "By asking staff at each entrance"],
    ans: 1,
  },
  "directions-b2x-toll-gate-lane": {
    q: "What happens after accidentally entering the Hi-pass lane?",
    opts: ["A fine is issued immediately", "Only the toll is billed by text later", "The car must be towed", "Nothing happens at all"],
    ans: 1,
  },
  "directions-b2x-hiking-map-inconsistency": {
    q: "What does the middle path lead to?",
    opts: ["A viewpoint", "The summit", "A parking lot", "A rest area"],
    ans: 1,
  },
  "directions-b2x-delivery-address-mismatch": {
    q: "What was the building's old name?",
    opts: ["Hanbit Building", "Haneul Tower", "Bitna Plaza", "Sarang Building"],
    ans: 0,
  },
  "directions-b2x-subway-construction-detour": {
    q: "How much longer does the detour add to the trip?",
    opts: ["1-2 minutes", "5-10 minutes", "15-20 minutes", "30 minutes"],
    ans: 1,
  },
  "directions-b2x-shared-office-floor-plan": {
    q: "Where is the room the pedestrian booked?",
    opts: ["Building A", "Building B", "Building C", "It's unclear"],
    ans: 0,
  },
  "directions-b2x-riverside-run-route": {
    q: "Why is the park route more challenging than the riverside route?",
    opts: ["It's much longer", "It has a slight uphill", "It's poorly lit", "It's crowded with cyclists"],
    ans: 1,
  },
  "directions-b2x-night-market-alley-numbers": {
    q: "Why doesn't the map app show the alley numbers?",
    opts: ["The app is outdated", "They are unofficial, unregistered names", "The market asked to hide them", "GPS doesn't work underground"],
    ans: 1,
  },
  "directions-b2x-cruise-terminal-shuttle-lines": {
    q: "Which shuttle bus goes downtown?",
    opts: ["The yellow bus", "The blue bus", "Both buses", "Neither, a taxi is needed"],
    ans: 1,
  },
  "directions-b2x-embassy-security-entrance": {
    q: "Where must visitors with civil affairs enter?",
    opts: ["The embassy's main entrance", "A side gate with security", "The basement entrance of the building next door", "A separate visitor building across the street"],
    ans: 2,
  },
  "directions-b2x-camp-site-numbering": {
    q: "Why doesn't the reserved site number match the sign?",
    opts: ["A printing error", "The zones were rearranged last year and the system wasn't updated", "The visitor misread the confirmation", "Sites are renumbered daily"],
    ans: 1,
  },
  "directions-b2x-elevator-restricted-floor": {
    q: "What does the visitor need to reach floor 12?",
    opts: ["A key from security", "A card-authenticated visitor pass", "An appointment confirmation", "Permission from the tenant"],
    ans: 1,
  },
  "directions-b2x-airport-rental-car-shuttle": {
    q: "Where did the rental car shuttle pickup point move to?",
    opts: ["Near exit 1", "Near exit 2", "Near exit 3", "Near the parking garage"],
    ans: 2,
  },
  "directions-b2x-temple-visitor-route": {
    q: "Why can't the visitor go directly to the main hall?",
    opts: ["It's closed for repairs", "A ceremony is in progress", "It's past visiting hours", "Only monks are allowed today"],
    ans: 1,
  },
  "directions-b2x-warehouse-loading-dock": {
    q: "Why did the driver go to the wrong loading dock?",
    opts: ["He misread the directions", "The sign plate was outdated", "GPS gave wrong coordinates", "He arrived too early"],
    ans: 1,
  },
  "directions-b2x-flea-market-vendor-map": {
    q: "Why is the vendor map often inaccurate?",
    opts: ["It's never updated", "Vendor spots change monthly by lottery", "The market moves locations", "Vendors don't register with the booth"],
    ans: 1,
  },
};
