import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Hospital situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const HOSPITAL_C_EXPANSION: Dialogue[] = [
  {
    id: "hospital-c1y-reform",
    situationKey: "hospital",
    level: "C1",
    title: "Colleagues debate healthcare reform",
    lines: [
      { speaker: "의사1", kr: "이번에 발표된 의료 개혁안 보셨어요? 필수 진료과에 대한 수가를 대폭 인상한다고 하던데요.", en: "Did you see the healthcare reform plan they announced? Apparently they're drastically raising reimbursement rates for essential specialties." },
      { speaker: "의사2", kr: "저도 봤는데, 취지는 공감하지만 재원을 어디서 마련할지가 관건인 것 같아요.", en: "I saw it too. I agree with the intent, but where the funding will come from seems to be the crux of it." },
      { speaker: "의사1", kr: "건강보험료 인상만으로는 한계가 있을 텐데, 정부 재정을 더 투입하지 않으면 지속되기 어렵지 않을까요.", en: "Raising health insurance premiums alone will only go so far—without more government funding, I don't think it'll be sustainable." },
      { speaker: "의사2", kr: "맞아요. 게다가 필수과 기피 현상이 단순히 수가 문제만은 아니잖아요. 소송 부담이나 근무 강도도 무시할 수 없죠.", en: "Right. And the avoidance of essential specialties isn't purely a reimbursement issue either. The malpractice-litigation burden and workload intensity can't be ignored." },
      { speaker: "의사1", kr: "결국 종합적인 접근이 필요한데, 이번 안은 재정 대책이 다소 미흡해 보여서 실효성에 의문이 들어요.", en: "In the end a comprehensive approach is needed, but this plan's financial measures seem somewhat lacking, which makes me doubt its effectiveness." },
      { speaker: "의사2", kr: "그래도 논의 자체가 시작됐다는 데 의의를 두고 싶어요. 의료계 목소리가 이번엔 어느 정도 반영된 것 같기도 하고요.", en: "Still, I want to find significance in the fact that the discussion has started. It also seems like the medical community's voice was reflected to some degree this time." },
      { speaker: "의사1", kr: "공청회 일정이 잡히면 저희 병원에서도 의견서를 제출하는 게 좋겠어요.", en: "Once the public hearing schedule is set, I think our hospital should submit an opinion paper." },
      { speaker: "의사2", kr: "동의합니다. 현장의 목소리가 빠지면 또 탁상행정이 될 수밖에 없으니까요.", en: "I agree. If the voices from the field are left out, it'll inevitably become another case of desk-bound policymaking." },
    ],
  },
  {
    id: "hospital-c1y-hedging",
    situationKey: "hospital",
    level: "C1",
    title: "Explaining a difficult diagnosis with care",
    lines: [
      { speaker: "의사", kr: "검사 결과를 말씀드리기 전에, 아직 확진은 아니고 추가 조직 검사가 필요한 단계라는 점을 먼저 말씀드리고 싶습니다.", en: "Before I share the test results, I want to first say that this isn't a confirmed diagnosis yet—we're at the stage where an additional biopsy is needed." },
      { speaker: "환자", kr: "네... 그래도 대략적으로라도 어떤 가능성이 있는지 알고 싶어요.", en: "Okay... but I'd still like to know, even roughly, what the possibilities are." },
      { speaker: "의사", kr: "영상에서 이형성이 의심되는 부위가 발견됐습니다. 악성일 가능성을 완전히 배제할 수는 없지만, 양성 소견과도 겹치는 부분이 있어요.", en: "The imaging revealed an area suspected of dysplasia. We can't completely rule out malignancy, but there's also overlap with benign findings." },
      { speaker: "환자", kr: "만약 안 좋은 쪽으로 나오면 어떻게 되는 건가요.", en: "If it comes back as the bad outcome, what happens then?" },
      { speaker: "의사", kr: "그 경우엔 병기를 판단하기 위한 추가 검사가 이어지고, 치료 방침도 그에 따라 결정됩니다. 다만 지금 단정 짓기보다는 결과를 기다려 보시는 게 맞습니다.", en: "In that case, further tests to determine the stage would follow, and the treatment plan would be decided accordingly. But rather than jumping to conclusions now, it's right to wait for the results." },
      { speaker: "환자", kr: "불안한 마음은 어쩔 수 없네요.", en: "I can't help feeling anxious." },
      { speaker: "의사", kr: "충분히 이해합니다. 조직 검사 결과는 일주일 정도 걸릴 예정이고, 그 사이 궁금한 점이 있으시면 언제든 연락 주셔도 됩니다.", en: "That's completely understandable. The biopsy results will take about a week, and if you have any questions in the meantime, please feel free to contact us anytime." },
      { speaker: "환자", kr: "감사합니다. 최악의 경우도 준비는 해 둬야겠죠.", en: "Thank you. I suppose I should prepare myself for the worst case too." },
      { speaker: "의사", kr: "준비하시는 것도 좋지만, 확률상 양성일 가능성도 낮지 않다는 점은 기억해 주셨으면 합니다.", en: "Preparing is fine, but I'd like you to keep in mind that statistically, the chance of a benign result isn't low either." },
    ],
  },
  {
    id: "hospital-c1y-burnout",
    situationKey: "hospital",
    level: "C1",
    title: "A resident opens up about burnout",
    lines: [
      { speaker: "전공의", kr: "선생님, 요즘 제가 뭘 위해 이 일을 하고 있는지 모르겠다는 생각이 자꾸 들어요.", en: "Doctor, lately I keep thinking I don't know what I'm doing this work for anymore." },
      { speaker: "선배 의사", kr: "당직 스케줄이 워낙 빡빡했으니 그런 생각이 드는 것도 무리는 아니에요.", en: "Given how packed the on-call schedule's been, it's no wonder you'd feel that way." },
      { speaker: "전공의", kr: "환자를 봐도 예전처럼 마음이 움직이지 않고, 그냥 기계적으로 처방만 내리고 있는 것 같아서 스스로도 놀랐어요.", en: "When I see patients, I don't feel moved the way I used to—I'm just mechanically writing prescriptions, and it surprised even me." },
      { speaker: "선배 의사", kr: "그건 소진 증후군의 전형적인 신호예요. 감정적으로 무뎌지는 걸 방치하면 결국 진료의 질에도 영향을 줘요.", en: "That's a textbook sign of burnout. If you leave that emotional numbness unaddressed, it eventually affects the quality of care too." },
      { speaker: "전공의", kr: "그래도 다들 이렇게 버티는데 저만 힘들다고 하기가 눈치 보여요.", en: "But since everyone else is enduring it like this, I feel self-conscious about being the only one struggling." },
      { speaker: "선배 의사", kr: "다들 버틴다고 해서 그게 정상이라는 뜻은 아니에요. 정신건강의학과 상담이든 휴가든, 필요한 조치를 취하는 게 오히려 책임 있는 태도예요.", en: "Just because everyone endures it doesn't mean it's normal. Whether it's psychiatric counseling or taking leave, taking the necessary measures is actually the more responsible attitude." },
      { speaker: "전공의", kr: "솔직히 상담을 받는다는 것 자체가 약점처럼 느껴지기도 해요.", en: "Honestly, the very idea of getting counseling feels like admitting a weakness." },
      { speaker: "선배 의사", kr: "저도 레지던트 때 그랬어요. 하지만 돌아보면 그때 도움을 청했던 게 지금까지 이 일을 할 수 있게 해 준 이유였어요.", en: "I felt the same way during my residency. But looking back, asking for help back then is exactly why I've been able to keep doing this work." },
    ],
  },
  {
    id: "hospital-c1y-budgetcuts",
    situationKey: "hospital",
    level: "C1",
    title: "An administrator justifies budget cuts",
    lines: [
      { speaker: "행정팀장", kr: "다음 분기부터 각 부서 소모품 예산이 십 퍼센트 삭감될 예정입니다.", en: "Starting next quarter, each department's supply budget will be cut by ten percent." },
      { speaker: "과장", kr: "환자 안전과 직결되는 물품까지 포함되는 건가요?", en: "Does that include supplies directly tied to patient safety?" },
      { speaker: "행정팀장", kr: "필수 의료용품은 제외되고, 사무용품이나 소모성 비품 위주로 조정될 계획입니다.", en: "Essential medical supplies are excluded—the adjustment is planned mainly around office supplies and consumable equipment." },
      { speaker: "과장", kr: "그렇다면 다행이긴 한데, 병원 전체 재정이 그렇게 안 좋은가요?", en: "That's a relief, but is the hospital's overall finances really that bad?" },
      { speaker: "행정팀장", kr: "코로나 이후 병상 가동률이 완전히 회복되지 않은 데다, 인건비 상승분이 예상보다 컸습니다.", en: "Bed occupancy hasn't fully recovered since the pandemic, and the rise in labor costs was larger than expected." },
      { speaker: "과장", kr: "현장에서는 예산이 줄면 곧바로 인력 충원도 미뤄질 거라고 우려하고 있어요.", en: "Staff on the ground are worried that if the budget shrinks, hiring will be postponed right away too." },
      { speaker: "행정팀장", kr: "인력 충원 계획 자체는 유지하되, 승인 절차가 다소 신중해질 수는 있습니다.", en: "The hiring plan itself will remain in place, but the approval process may become somewhat more cautious." },
      { speaker: "과장", kr: "그 부분은 부서장들에게 명확히 공지해 주셨으면 합니다. 소문만 무성하면 사기가 떨어지니까요.", en: "I'd ask that you communicate that clearly to department heads. If it's left to rumor, morale will suffer." },
      { speaker: "행정팀장", kr: "다음 주 부서장 회의에서 상세 자료를 배포하겠습니다.", en: "I'll distribute the detailed materials at next week's department heads meeting." },
    ],
  },
  {
    id: "hospital-c1y-bioethics",
    situationKey: "hospital",
    level: "C1",
    title: "Medical students debate a bioethics case",
    lines: [
      { speaker: "학생1", kr: "이번 사례 연구, 환자가 종교적 이유로 수혈을 거부한 경우잖아요. 의료진은 어디까지 존중해야 할까요.", en: "This case study is about a patient refusing a blood transfusion for religious reasons. To what extent should medical staff respect that?" },
      { speaker: "학생2", kr: "환자의 자기결정권은 원칙적으로 존중되어야 한다고 생각해요. 성인이고 판단 능력에 문제가 없다면요.", en: "I think patient autonomy should be respected in principle, as long as they're an adult with no impairment of judgment." },
      { speaker: "학생1", kr: "그런데 그 결정이 생명과 직결될 정도로 위중한 상황이라면 어떻게 되죠? 의료진의 윤리적 책임은요?", en: "But what if the decision is critical enough to directly determine life or death? What about the medical staff's ethical responsibility?" },
      { speaker: "학생2", kr: "설득은 최대한 해야겠지만, 최종적으로는 환자의 의사를 뒤집을 권한이 의료진에게 없다고 봐요.", en: "They should try their best to persuade the patient, but ultimately I don't think medical staff have the authority to override the patient's wishes." },
      { speaker: "학생1", kr: "그렇다면 미성년 자녀의 경우는 어떤가요. 부모가 수혈을 거부하면요.", en: "Then what about a minor child's case—if the parents refuse the transfusion?" },
      { speaker: "학생2", kr: "그건 완전히 다른 문제죠. 판례상 법원이 개입해서 아동의 생명권을 우선시한 사례들이 있잖아요.", en: "That's a completely different issue. There are precedents where courts intervened and prioritized the child's right to life." },
      { speaker: "학생1", kr: "결국 자기결정권과 생명 보호 사이의 경계가 상황마다 다르게 그어진다는 거네요.", en: "So in the end, the line between autonomy and the protection of life gets drawn differently depending on the situation." },
      { speaker: "학생2", kr: "맞아요. 그래서 이런 사례들이 정답이 없는 대신 판단의 틀을 훈련시켜 주는 거고요.", en: "Exactly. That's why these cases don't have a single correct answer—instead, they train us in a framework for judgment." },
    ],
  },
  {
    id: "hospital-c1y-billingprobe",
    situationKey: "hospital",
    level: "C1",
    title: "A reporter probes hospital billing",
    lines: [
      { speaker: "기자", kr: "환자들이 비급여 항목 안내를 제대로 받지 못했다는 민원이 계속 접수되고 있는데, 병원 측 입장은 어떻습니까.", en: "Complaints keep coming in that patients weren't properly informed about non-covered items—what's the hospital's position?" },
      { speaker: "원무과장", kr: "사전 설명 절차는 규정대로 진행하고 있습니다만, 일부 항목에서 안내가 미흡했던 사례가 있었던 건 사실입니다.", en: "We follow the required prior-explanation procedure, but it's true there were cases where the explanation for some items fell short." },
      { speaker: "기자", kr: "구체적으로 어떤 항목에서 문제가 발생한 겁니까?", en: "Specifically which items did the problems occur with?" },
      { speaker: "원무과장", kr: "주로 검사 추가나 특수 재료 사용 시 실시간으로 동의를 받지 못한 경우들이었습니다.", en: "They were mostly cases where real-time consent wasn't obtained when additional tests or special materials were used." },
      { speaker: "기자", kr: "그렇다면 재발 방지 대책은 마련되어 있나요.", en: "So do you have measures in place to prevent recurrence?" },
      { speaker: "원무과장", kr: "전자 동의 시스템을 도입해서 항목이 추가될 때마다 환자에게 실시간 고지가 가도록 개선할 예정입니다.", en: "We plan to introduce an electronic consent system so that patients are notified in real time whenever an item is added." },
      { speaker: "기자", kr: "도입 시기는 언제쯤으로 보십니까.", en: "When do you expect that system to be introduced?" },
      { speaker: "원무과장", kr: "내부 검토가 끝나는 대로 다음 분기 안에 시행할 계획입니다.", en: "Once the internal review is complete, we plan to implement it within the next quarter." },
    ],
  },
  {
    id: "hospital-c1y-mentalhealthgap",
    situationKey: "hospital",
    level: "C1",
    title: "Generational views on mental health treatment",
    lines: [
      { speaker: "환자", kr: "어머니는 제가 상담받으러 다닌다고 하니까 그냥 마음을 굳게 먹으면 되는 거 아니냐고 하시더라고요.", en: "When I told my mother I was going to therapy, she just said, 'Can't you simply toughen your resolve?'" },
      { speaker: "의사", kr: "이전 세대에서는 정신과 진료를 받는다는 것 자체를 낙인처럼 여기는 경우가 많았으니까요.", en: "In the previous generation, receiving psychiatric care itself was often seen as something stigmatizing." },
      { speaker: "환자", kr: "저도 처음엔 약을 먹는다는 게 뭔가 패배를 인정하는 것 같아서 망설였어요.", en: "At first, I hesitated too, because taking medication felt like admitting some kind of defeat." },
      { speaker: "의사", kr: "많은 분들이 그렇게 느끼시죠. 하지만 우울증이나 불안장애도 다른 만성 질환처럼 생물학적 요인이 있는 질환이에요.", en: "Many people feel that way. But depression and anxiety disorders are conditions with biological factors, just like any other chronic illness." },
      { speaker: "환자", kr: "그 말씀을 들으니 조금은 마음이 편해지네요. 어머니께 어떻게 설명드려야 할지 여전히 막막하지만요.", en: "Hearing that puts my mind a bit more at ease, though I'm still at a loss for how to explain it to my mother." },
      { speaker: "의사", kr: "원하시면 다음 진료 때 어머님과 함께 오셔서 제가 직접 설명드릴 수도 있어요.", en: "If you'd like, you could bring your mother to the next appointment, and I could explain it to her directly." },
      { speaker: "환자", kr: "그러면 정말 도움이 될 것 같아요. 전문가 말씀이면 조금은 다르게 받아들이실 수도 있으니까요.", en: "That would really help. Coming from a specialist, she might accept it a bit differently." },
    ],
  },
  {
    id: "hospital-c1y-fundingpitch",
    situationKey: "hospital",
    level: "C1",
    title: "Negotiating funding for a clinical trial",
    lines: [
      { speaker: "연구원", kr: "이번 임상시험 2상 결과가 긍정적으로 나와서 3상 진입을 위한 추가 지원을 요청드리려 합니다.", en: "The phase 2 results for this clinical trial came back positive, so I'd like to request additional support to move into phase 3." },
      { speaker: "재단 관계자", kr: "긍정적인 결과라니 반갑네요. 다만 3상은 규모가 훨씬 커질 텐데, 예상 소요 비용이 어느 정도인가요.", en: "Glad to hear the positive results. But phase 3 will be much larger in scale—what's the estimated cost?" },
      { speaker: "연구원", kr: "다기관 임상으로 확대되면서 이전 대비 약 세 배 정도의 예산이 필요할 것으로 추산됩니다.", en: "Since it'll expand into a multi-center trial, we estimate roughly three times the budget compared to before." },
      { speaker: "재단 관계자", kr: "이사회를 설득하려면 좀 더 구체적인 근거가 필요할 것 같아요. 다른 재원 확보 계획은 있으신가요.", en: "To persuade the board, we'll likely need more concrete grounds. Do you have plans to secure other sources of funding?" },
      { speaker: "연구원", kr: "정부 연구비 공모에도 별도로 지원해 둔 상태고, 결과는 다음 달 발표됩니다.", en: "We've also separately applied for a government research grant, and the results will be announced next month." },
      { speaker: "재단 관계자", kr: "그렇다면 정부 지원 결과가 나온 뒤에 저희 쪽 지원 규모를 확정하는 게 안전할 것 같습니다.", en: "In that case, it seems safer to finalize our support amount after the government funding results come out." },
      { speaker: "연구원", kr: "이해합니다. 다만 3상 준비 자체는 시간이 걸리니, 예비 검토만이라도 지금부터 시작해 주실 수 있을까요.", en: "I understand. But since preparing for phase 3 itself takes time, could you at least start a preliminary review from now?" },
      { speaker: "재단 관계자", kr: "네, 예비 검토는 바로 착수하겠습니다.", en: "Yes, we'll go ahead and begin the preliminary review right away." },
    ],
  },
  {
    id: "hospital-c1y-understaffing",
    situationKey: "hospital",
    level: "C1",
    title: "Nurses discuss understaffing risks",
    lines: [
      { speaker: "간호사1", kr: "오늘 야간 근무에 저 혼자 병동 스물두 명을 봐야 하는데, 이게 정말 안전한 건지 모르겠어요.", en: "I have to cover twenty-two patients on the ward alone during tonight's shift—I'm not sure this is really safe." },
      { speaker: "간호사2", kr: "저도 지난주에 비슷한 상황이었는데, 투약 시간을 지키는 것만도 벅찼어요.", en: "I was in a similar situation last week too—it was already a struggle just to keep up with medication times." },
      { speaker: "간호사1", kr: "이러다가 투약 오류라도 나면 결국 책임은 저희한테 돌아오는 거잖아요.", en: "If a medication error happens because of this, the responsibility will ultimately fall on us." },
      { speaker: "간호사2", kr: "맞아요. 인력 배치 기준 자체가 현실과 너무 동떨어져 있는 것 같아요.", en: "Right. The staffing standards themselves seem far too disconnected from reality." },
      { speaker: "간호사1", kr: "노조를 통해서든 뭐든 이 문제를 공식적으로 제기해야 할 것 같아요. 더 이상 개인이 감당할 수준이 아니에요.", en: "I think we need to formally raise this issue, whether through the union or otherwise. It's no longer something individuals can bear." },
      { speaker: "간호사2", kr: "저도 동의해요. 다음 부서 회의 때 근무 인원 현황 자료를 정리해서 제출하는 게 어떨까요.", en: "I agree. How about we compile the staffing data and submit it at the next department meeting?" },
      { speaker: "간호사1", kr: "좋아요. 숫자로 보여주면 위에서도 무시하기는 어려울 거예요.", en: "Good idea. If we show it with numbers, it'll be harder for management to ignore." },
      { speaker: "간호사2", kr: "이번엔 흐지부지되지 않게 끝까지 챙겨봐요.", en: "Let's make sure this doesn't fizzle out this time—let's see it through." },
    ],
  },
  {
    id: "hospital-c2y-triagedebate",
    situationKey: "hospital",
    level: "C2",
    title: "Debating triage priorities during a surge",
    lines: [
      { speaker: "응급의학과장", kr: "환자 급증 시 중증도 분류 기준을 어떻게 조정할지에 대해 부서 간 이견이 좁혀지지 않고 있습니다.", en: "There's a persistent disagreement between departments over how to adjust triage criteria during a surge in patients." },
      { speaker: "내과과장", kr: "만성질환 악화 환자를 우선순위에서 지나치게 낮추면, 결국 골든타임을 놓치는 사례가 늘어날 겁니다.", en: "If we lower the priority of patients with worsening chronic conditions too much, we'll end up seeing more cases where the golden hour is missed." },
      { speaker: "응급의학과장", kr: "이해는 하지만, 자원이 한정된 상황에서는 즉각적인 생명 위협이 있는 환자를 최우선으로 둘 수밖에 없다는 게 국제 기준이기도 합니다.", en: "I understand, but under conditions of limited resources, prioritizing patients with immediate life-threatening conditions is also the international standard." },
      { speaker: "내과과장", kr: "그 기준이 재난 상황을 전제로 만들어진 건데, 평시 과밀화까지 동일하게 적용하는 게 과연 타당한지 의문입니다.", en: "That standard was designed with disaster scenarios in mind, so I question whether it's really valid to apply it identically to routine overcrowding as well." },
      { speaker: "응급의학과장", kr: "그렇다면 현재의 과밀화를 재난에 준하는 상황으로 볼 것인지부터가 논쟁의 핵심이겠네요.", en: "Then whether we regard the current overcrowding as tantamount to a disaster is itself the crux of this debate, isn't it." },
      { speaker: "내과과장", kr: "정확합니다. 그리고 그 판단에 따라 병원 전체의 자원 배분 철학이 달라질 수밖에 없고요.", en: "Exactly. And depending on that judgment, the entire hospital's philosophy of resource allocation is bound to change." },
      { speaker: "응급의학과장", kr: "일단 이번 주 내로 위원회를 소집해서 잠정 기준안을 마련하는 게 급선무일 것 같습니다.", en: "For now, I think the urgent priority is to convene a committee within this week and draft a provisional set of criteria." },
      { speaker: "내과과장", kr: "동의합니다. 다만 최종 기준이 나오기 전까지는 현장 재량을 존중해 주셨으면 합니다.", en: "I agree. But until the final criteria come out, I'd ask that clinical discretion in the field be respected." },
      { speaker: "응급의학과장", kr: "물론이죠. 이건 규정으로 현장을 옥죄자는 취지가 아니라 오히려 보호하자는 취지니까요.", en: "Of course. This isn't meant to constrain frontline staff with regulations—it's meant to protect them, if anything." },
    ],
  },
  {
    id: "hospital-c2y-epidemiology",
    situationKey: "hospital",
    level: "C2",
    title: "A public health official presents an epidemiological report",
    lines: [
      { speaker: "보건 당국자", kr: "이번 집단 감염 사례에 대한 역학조사 결과를 말씀드리겠습니다. 최초 감염 경로는 아직 완전히 특정되지 않았습니다.", en: "I'll present the epidemiological investigation results for this cluster outbreak. The initial route of transmission has not yet been fully identified." },
      { speaker: "기자", kr:"확산 속도가 예상보다 빨랐다는 지적이 있는데, 초기 대응에 문제가 있었던 건 아닙니까.", en: "There have been claims that the spread was faster than expected—wasn't there a problem with the initial response?" },
      { speaker: "보건 당국자", kr: "잠복기가 예상보다 짧게 관찰된 것이 확산 속도에 영향을 미쳤을 가능성이 있고, 초기 접촉자 추적은 지침에 따라 이루어졌습니다.", en: "It's possible that the incubation period, which was observed to be shorter than expected, affected the speed of spread, and the initial contact tracing was carried out according to protocol." },
      { speaker: "기자", kr: "그렇다면 지침 자체를 개정할 계획은 없으십니까.", en: "Then do you have no plans to revise the protocol itself?" },
      { speaker: "보건 당국자", kr: "이번 사례를 반영해서 접촉자 범위를 확대하는 방향으로 지침 개정을 검토 중입니다. 다음 달 전문가 자문회의를 거칠 예정입니다.", en: "We're reviewing a revision to expand the scope of contact tracing based on this case, and it will go through an expert advisory meeting next month." },
      { speaker: "기자", kr: "지역사회 감염으로 확대될 가능성은 어느 정도로 보십니까.", en: "How likely do you think it is that this will spread into community transmission?" },
      { speaker: "보건 당국자", kr: "현재까지 확인된 감염원은 특정 시설 내로 국한되어 있지만, 안심할 단계는 아니라고 판단하고 있습니다.", en: "As of now, the confirmed sources of infection are confined within a specific facility, but we don't judge it to be a stage where we can be complacent." },
      { speaker: "기자", kr: "시민들이 특별히 주의해야 할 점이 있다면 말씀해 주시죠.", en: "If there's anything citizens should be particularly careful about, please tell us." },
      { speaker: "보건 당국자", kr: "해당 시설을 방문하신 분들은 증상 유무와 관계없이 보건소에 신고해 주시고, 밀접 접촉자로 분류되신 분들은 자가격리 지침을 준수해 주시기 바랍니다.", en: "We ask that anyone who visited the facility report to the public health center regardless of symptoms, and that those classified as close contacts comply with the self-quarantine guidelines." },
    ],
  },
  {
    id: "hospital-c2y-mediaethics",
    situationKey: "hospital",
    level: "C2",
    title: "Editorial debate on covering a medical error",
    lines: [
      { speaker: "기자", kr: "이번 의료사고 보도, 병원 측 실명을 공개하는 게 맞을까요? 아직 조사 결과가 확정된 것도 아닌데요.", en: "For this medical-error story, is it right to disclose the hospital's name? The investigation results aren't even finalized yet." },
      { speaker: "데스크", kr: "공익성을 고려하면 시민들의 알 권리가 우선이지만, 확정되지 않은 사안을 단정적으로 다루면 명예훼손 소지도 있어요.", en: "Considering the public interest, citizens' right to know takes priority, but if we treat an unconfirmed matter as settled fact, there's also a risk of defamation." },
      { speaker: "기자", kr: "그렇다고 익명 처리를 하면 이 사건이 갖는 경각심 자체가 희석될 수 있잖아요.", en: "But if we anonymize it, the sense of alarm this incident is meant to raise could itself get diluted." },
      { speaker: "데스크", kr: "맞는 말이지만, 저희 보도로 인해 무고한 의료진까지 여론재판을 받게 되는 부작용도 고려해야 해요.", en: "That's true, but we also have to consider the side effect that our reporting could subject even innocent medical staff to trial by public opinion." },
      { speaker: "기자", kr: "그러면 병원 실명은 밝히되, 담당 의료진 개인 신상은 비공개로 하는 절충안은 어떨까요.", en: "Then how about a compromise—disclose the hospital's name but keep the individual staff members' personal information private?" },
      { speaker: "데스크", kr: "그게 현실적인 균형점 같네요. 다만 조사 결과가 나오기 전까지는 '의혹'이라는 표현을 일관되게 써 주세요.", en: "That seems like a realistic balance. But until the investigation results come out, please consistently use the term 'allegation.'" },
      { speaker: "기자", kr: "네, 그리고 병원 측 반론도 같은 비중으로 실어야겠죠.", en: "Understood, and we should also give the hospital's rebuttal equal weight." },
      { speaker: "데스크", kr: "물론이죠. 균형을 잃는 순간 이 보도의 신뢰성 자체가 흔들리니까요.", en: "Of course. The moment we lose balance, the credibility of the report itself will be shaken." },
      { speaker: "기자", kr: "알겠습니다. 병원 측 공식 입장부터 다시 요청해 보겠습니다.", en: "Understood. I'll go ahead and request the hospital's official statement again first." },
    ],
  },
  {
    id: "hospital-c2y-airesearch",
    situationKey: "hospital",
    level: "C2",
    title: "Debating AI diagnostic tools in practice",
    lines: [
      { speaker: "의사1", kr: "인공지능 판독 보조 시스템 도입안, 결국 이사회에서 통과됐다고 하더라고요.", en: "I heard the proposal to introduce the AI-assisted reading system finally passed at the board level." },
      { speaker: "의사2", kr: "저는 여전히 우려가 커요. 알고리즘의 판단 근거가 완전히 투명하지 않은 상태에서 최종 책임만 임상의에게 지우는 구조잖아요.", en: "I'm still quite concerned. It's a structure where the algorithm's reasoning isn't fully transparent, yet the final responsibility rests entirely on the clinician." },
      { speaker: "의사1", kr: "그 점은 저도 동의하지만, 판독 정확도 자체는 여러 논문에서 숙련의 수준에 근접했다는 결과가 나왔잖아요.", en: "I agree on that point, but multiple papers have shown the reading accuracy itself approaches the level of experienced specialists." },
      { speaker: "의사2", kr: "정확도가 높다고 해서 오진의 책임 소재 문제가 해결되는 건 아니죠. 시스템 오류로 놓친 소견을 누가 책임질지 아직 불분명해요.", en: "High accuracy doesn't resolve the question of liability for misdiagnosis. It's still unclear who's responsible for a finding missed due to a system error." },
      { speaker: "의사1", kr: "결국 이중 판독 체계로 운영하면서 인공지능은 보조 수단으로만 활용하는 게 현실적인 절충안 아닐까요.", en: "In the end, isn't operating a dual-reading system, where AI is used only as an auxiliary tool, the realistic compromise?" },
      { speaker: "의사2", kr: "저도 그 방향에는 공감해요. 다만 시간이 지나면서 의존도가 서서히 높아지는 게 진짜 위험 요소라고 봐요.", en: "I agree with that direction too. But I think the real risk factor is that dependence will gradually increase over time." },
      { speaker: "의사1", kr: "그래서 정기적으로 오류 사례를 검토하고 피드백하는 체계가 병행되어야 할 것 같아요.", en: "That's why I think a system for regularly reviewing error cases and feeding back the findings needs to run in parallel." },
      { speaker: "의사2", kr: "동의합니다. 기술을 배척할 게 아니라 통제할 수 있는 틀을 먼저 갖추는 게 순서겠죠.", en: "I agree. Rather than rejecting the technology outright, establishing a framework to control it should come first." },
      { speaker: "의사1", kr: "도입 후 첫 6개월간의 성과 지표를 별도로 추적해서 공유하는 것도 제안해 봐야겠어요.", en: "I should also propose separately tracking and sharing performance metrics for the first six months after implementation." },
    ],
  },
  {
    id: "hospital-c2y-rareconsent",
    situationKey: "hospital",
    level: "C2",
    title: "Debating consent for an experimental therapy",
    lines: [
      { speaker: "주치의", kr: "표준 치료로는 더 이상 반응을 기대하기 어려운 상황이라, 실험적 치료를 제안드리려 합니다.", en: "Since we can no longer reasonably expect a response from standard treatment, I'd like to propose an experimental therapy." },
      { speaker: "보호자", kr: "그 치료법의 안전성은 어느 정도 검증된 건가요? 임상 사례가 많지 않다고 들었어요.", en: "To what extent has that therapy's safety been verified? I've heard there aren't many clinical cases." },
      { speaker: "주치의", kr: "소규모 임상에서 유의미한 반응률이 보고되긴 했지만, 장기적인 부작용에 대해서는 아직 축적된 데이터가 충분하지 않습니다.", en: "A meaningful response rate has been reported in small-scale trials, but there isn't yet sufficient accumulated data on long-term side effects." },
      { speaker: "보호자", kr: "만약 부작용이 심각하게 나타나면 되돌릴 방법이 있나요.", en: "If severe side effects occur, is there a way to reverse them?" },
      { speaker: "주치의", kr: "투여를 즉시 중단하고 대증 치료로 전환할 수는 있지만, 완전히 원상 복구된다는 보장은 드리기 어렵습니다.", en: "We can stop administration immediately and switch to symptomatic treatment, but I can't guarantee a full return to the original condition." },
      { speaker: "보호자", kr: "환자 본인은 어떤 입장이신지 여쭤봐도 될까요.", en: "May I ask what the patient herself thinks about this?" },
      { speaker: "주치의", kr: "환자분께서는 남은 가능성에 걸어보고 싶다는 의사를 이미 밝히셨습니다. 다만 최종 동의는 가족분들과 충분히 논의하신 뒤에 받고자 합니다.", en: "The patient has already expressed a wish to take a chance on the remaining possibility. However, we'd like to obtain final consent only after you've had a thorough discussion with the family." },
      { speaker: "보호자", kr: "저희끼리 상의할 시간을 며칠 주실 수 있을까요.", en: "Could you give us a few days to discuss it among ourselves?" },
      { speaker: "주치의", kr: "물론입니다. 다만 치료 효과는 병기 진행 전에 시작할수록 높아지니, 일주일 이내로 결정해 주시면 감사하겠습니다.", en: "Of course. But since the treatment's efficacy is higher the earlier it starts before the disease progresses, I'd appreciate a decision within a week." },
    ],
  },
  {
    id: "hospital-c2y-priorityfunding",
    situationKey: "hospital",
    level: "C2",
    title: "Journalist and official spar over research priorities",
    lines: [
      { speaker: "기자", kr: "희귀질환 연구 예산이 매년 삭감되는 반면, 특정 대기업이 후원하는 연구에는 예산이 몰리고 있다는 지적이 있습니다.", en: "There's criticism that funding for rare disease research is cut every year, while research sponsored by certain large corporations is receiving concentrated investment." },
      { speaker: "보건 당국자", kr: "예산 배분은 환자 수와 사회적 부담을 종합적으로 고려한 결과이지, 특정 기업의 이해관계가 반영된 게 아닙니다.", en: "Budget allocation is the result of comprehensively considering patient numbers and social burden—it doesn't reflect any particular company's interests." },
      { speaker: "기자", kr: "그렇지만 희귀질환은 환자 수가 적다는 이유로 늘 후순위로 밀리는 구조 아닙니까.", en: "But isn't the structure such that rare diseases are always pushed to lower priority precisely because of their small patient numbers?" },
      { speaker: "보건 당국자", kr: "그 점을 보완하기 위해 별도의 희귀질환 전용 기금을 운영하고 있고, 올해 지원 규모도 소폭 확대되었습니다.", en: "To make up for that, we operate a separate fund dedicated to rare diseases, and this year's support was also modestly expanded." },
      { speaker: "기자", kr: "소폭 확대라고 하셨는데, 물가상승률을 감안하면 실질적으로는 동결에 가깝지 않습니까.", en: "You said 'modestly expanded,' but accounting for inflation, isn't that effectively close to a freeze?" },
      { speaker: "보건 당국자", kr: "그 지적에는 일부 타당한 측면이 있습니다. 내년도 예산안에서 실질 증액을 반영하도록 관련 부서와 협의 중입니다.", en: "There's some validity to that point. We're consulting with the relevant departments to reflect a real increase in next year's budget proposal." },
      { speaker: "기자", kr: "구체적인 증액 규모나 시기를 지금 말씀해 주실 수 있나요.", en: "Can you tell us the specific scale or timing of the increase right now?" },
      { speaker: "보건 당국자", kr: "아직 확정 전이라 구체적인 수치를 말씀드리기는 조심스럽습니다만, 국회 예산 심의 전까지는 방향을 확정할 예정입니다.", en: "Since it hasn't been finalized, I'm cautious about giving specific figures, but we plan to finalize the direction before the National Assembly's budget review." },
      { speaker: "기자", kr: "환자 단체들이 계속 지켜보고 있다는 점, 참고해 주시길 바랍니다.", en: "I hope you'll keep in mind that patient advocacy groups are continuing to watch this closely." },
    ],
  },
  {
    id: "hospital-c2y-overdiagnosis",
    situationKey: "hospital",
    level: "C2",
    title: "Debating overdiagnosis in screening programs",
    lines: [
      { speaker: "역학전문가", kr: "국가 건강검진 프로그램이 확대되면서 과잉진단 문제도 함께 논의될 필요가 있다고 봅니다.", en: "As the national health screening program expands, I think the issue of overdiagnosis needs to be discussed alongside it." },
      { speaker: "임상의", kr: "조기 발견이 생존율을 높인다는 건 확립된 사실 아닌가요? 과잉진단을 지나치게 강조하면 검진 자체를 꺼리게 만들 위험이 있어요.", en: "Isn't it an established fact that early detection improves survival rates? Overemphasizing overdiagnosis risks discouraging screening altogether." },
      { speaker: "역학전문가", kr: "생존율 향상이 반드시 조기 발견 덕분만은 아니라는 게 문제예요. 진행하지 않았을 병변까지 발견해서 치료로 이어지는 경우가 상당수 보고되고 있거든요.", en: "The problem is that improved survival isn't necessarily due to early detection alone. A considerable number of cases are reported where lesions that would never have progressed are detected and lead to unnecessary treatment." },
      { speaker: "임상의", kr: "그렇다고 해도 개별 의사가 어떤 병변이 진행할지 안 할지를 사전에 구별할 방법이 마땅치 않잖아요.", en: "Even so, there's no reliable way for an individual physician to distinguish beforehand which lesions will progress and which won't." },
      { speaker: "역학전문가", kr: "그래서 저는 획일적인 전수 검진보다 위험군에 따른 차등 검진 전략이 더 합리적이라고 주장하는 겁니다.", en: "That's exactly why I'm arguing that a risk-stratified screening strategy makes more sense than a uniform, blanket screening approach." },
      { speaker: "임상의", kr: "이론적으로는 그럴듯하지만, 현장에서 위험군을 정교하게 나누는 게 현실적으로 가능할지 의문이에요.", en: "It sounds plausible in theory, but I question whether finely stratifying risk groups is realistically feasible in the field." },
      { speaker: "역학전문가", kr: "완벽한 모델은 없겠지만, 적어도 현재의 획일적 접근보다는 개선의 여지가 크다고 봅니다.", en: "There's no perfect model, but I believe there's considerably more room for improvement than the current uniform approach." },
      { speaker: "임상의", kr: "결국 이 논쟁도 근거 자료가 충분히 쌓이기 전까지는 평행선을 달릴 수밖에 없겠네요.", en: "In the end, this debate too is bound to remain at an impasse until enough evidence accumulates." },
      { speaker: "역학전문가", kr: "그래서 저희 연구팀이 장기 추적 코호트 연구를 제안하려고 준비 중입니다.", en: "That's why our research team is preparing to propose a long-term follow-up cohort study." },
    ],
  },
  {
    id: "hospital-c2y-disclosurecrisis",
    situationKey: "hospital",
    level: "C2",
    title: "Crisis meeting after disclosing a systemic error",
    lines: [
      { speaker: "병원장", kr: "이번 투약 오류 사건이 단순 실수가 아니라 시스템상의 구조적 결함에서 비롯됐다는 내부 조사 결과가 나왔습니다.", en: "The internal investigation found that this medication-error incident stemmed not from a simple mistake, but from a structural flaw in the system." },
      { speaker: "품질관리팀장", kr: "전자처방 시스템에서 유사 약품명이 함께 뜨는 인터페이스 문제가 핵심 원인으로 지목되었습니다.", en: "The core cause was identified as an interface issue in the electronic prescribing system, where similarly named drugs appear together." },
      { speaker: "병원장", kr: "그렇다면 이건 담당 간호사 개인의 과실로만 몰아갈 사안이 아니라는 거군요.", en: "Then this isn't something that can simply be blamed entirely on the individual nurse's fault." },
      { speaker: "품질관리팀장", kr: "그렇습니다. 다만 이 부분을 공개적으로 인정하면 병원의 법적 책임 범위도 함께 커질 수 있다는 우려가 있습니다.", en: "That's right. However, there's a concern that publicly acknowledging this could also broaden the scope of the hospital's legal liability." },
      { speaker: "병원장", kr: "책임을 회피하려다가 신뢰를 완전히 잃는 것보다는, 구조적 결함을 인정하고 재발 방지책을 함께 발표하는 게 맞다고 봅니다.", en: "Rather than trying to avoid responsibility and losing trust entirely, I believe it's right to acknowledge the structural flaw and announce prevention measures together." },
      { speaker: "품질관리팀장", kr: "동의합니다. 다만 법무팀과 사전에 표현 수위를 조율해서, 사실관계와 책임 인정의 경계를 명확히 해야 할 것 같습니다.", en: "I agree. But I think we need to coordinate the wording with the legal team beforehand, to clearly separate the factual record from the acknowledgment of responsibility." },
      { speaker: "병원장", kr: "환자 가족에게는 언론 발표 이전에 저희가 먼저 직접 설명드리는 게 도리라고 생각합니다.", en: "I think it's only right that we personally explain this to the patient's family ourselves before the press announcement." },
      { speaker: "품질관리팀장", kr: "오늘 중으로 면담 일정을 잡고, 재발 방지 대책의 구체적인 초안도 함께 준비하겠습니다.", en: "I'll arrange a meeting with them today and also prepare a concrete draft of the recurrence-prevention plan." },
      { speaker: "병원장", kr: "이번 일을 계기로 시스템 전반을 재점검하는 계기로 삼읍시다.", en: "Let's use this incident as an opportunity to thoroughly re-examine the system as a whole." },
    ],
  },
  {
    id: "hospital-c2y-consentwithdrawal",
    situationKey: "hospital",
    level: "C2",
    title: "Debate after a research subject withdraws consent",
    lines: [
      { speaker: "연구책임자", kr: "3상 시험 도중에 피험자 한 분이 돌연 동의를 철회하겠다는 의사를 밝혀 왔습니다.", en: "In the middle of the phase 3 trial, one subject has suddenly expressed intent to withdraw consent." },
      { speaker: "임상연구간호사", kr: "사유를 여쭤봤더니, 부작용 자체보다는 언론에 보도된 다른 임상시험 사고 소식에 불안감을 느꼈다고 하시더라고요.", en: "When I asked the reason, she said it wasn't the side effects themselves, but rather anxiety triggered by news coverage of a different clinical trial incident." },
      { speaker: "연구책임자", kr: "이해는 가지만, 이 시점에서 이탈하시면 통계적 검정력에 영향을 줄 수 있어서 걱정이네요.", en: "I understand, but if she withdraws at this point, it could affect the statistical power, which is concerning." },
      { speaker: "임상연구간호사", kr: "그래도 동의 철회는 절대적인 권리이니, 저희가 통계적 부담을 이유로 설득을 강요할 수는 없는 거잖아요.", en: "Still, withdrawal of consent is an absolute right, so we can't pressure her to stay just because of our statistical concerns." },
      { speaker: "연구책임자", kr: "물론입니다. 다만 우려하시는 부분에 대해 정확한 정보를 다시 안내해 드리는 것까지는 괜찮겠죠.", en: "Of course. But it should still be fine to give her accurate information again regarding what she's worried about." },
      { speaker: "임상연구간호사", kr: "그 정도는 필요하다고 봐요. 다만 최종 결정은 전적으로 본인 의사에 맡겨야 하고요.", en: "I think that much is necessary. But the final decision has to be left entirely up to her." },
      { speaker: "연구책임자", kr: "이번 이탈이 다른 피험자들에게도 영향을 줄 수 있으니, 전체 공지 방식도 신중하게 정해야겠어요.", en: "Since this withdrawal could also affect other subjects, we'll need to carefully decide how to communicate it more broadly as well." },
      { speaker: "임상연구간호사", kr: "개별 정보는 철저히 비밀로 하고, 전체적인 안전성 지표만 요약해서 공유하는 게 좋을 것 같아요.", en: "I think it would be best to keep individual information strictly confidential and share only a summary of the overall safety indicators." },
      { speaker: "연구책임자", kr: "동의합니다. IRB에도 이번 사례를 보고해서 절차상 문제가 없었는지 확인받아야겠어요.", en: "I agree. We should also report this case to the IRB to confirm there was no issue with the procedure." },
    ],
  },
  {
    id: "hospital-c2y-culturaltaboo",
    situationKey: "hospital",
    level: "C2",
    title: "Commentary on cultural taboos around terminal illness",
    lines: [
      { speaker: "완화의료 전문의", kr: "우리 사회에서는 여전히 말기 진단을 환자 본인에게 직접 알리기를 꺼리는 경향이 뿌리 깊게 남아 있습니다.", en: "In our society, there's still a deeply rooted tendency to hesitate about directly informing the patient of a terminal diagnosis." },
      { speaker: "사회복지사", kr: "가족들은 대체로 환자가 희망을 잃을까 봐 진실을 숨기려고 하시더라고요. 저도 그 마음이 이해가 안 되는 건 아니에요.", en: "Families generally try to hide the truth for fear the patient will lose hope. I don't fail to understand that impulse either." },
      { speaker: "완화의료 전문의", kr: "문제는 그 선의가 오히려 환자에게서 남은 시간을 스스로 계획할 기회를 빼앗는다는 데 있어요.", en: "The problem is that this good intention actually deprives the patient of the opportunity to plan their own remaining time." },
      { speaker: "사회복지사", kr: "맞아요. 실제로 뒤늦게 진실을 알게 된 환자분들이 배신감을 토로하시는 경우도 적지 않았고요.", en: "That's true. There have been quite a few cases where patients, upon belatedly learning the truth, expressed a sense of betrayal." },
      { speaker: "완화의료 전문의", kr: "그래서 저희는 가족 면담을 먼저 진행하되, 결국 고지 여부는 환자 본인의 의사를 우선하도록 설득하는 방향으로 접근하고 있어요.", en: "That's why our approach is to first hold a family meeting, but ultimately persuade them to prioritize the patient's own wishes on whether to disclose." },
      { speaker: "사회복지사", kr: "다만 문화적 맥락을 완전히 무시할 수도 없잖아요. 특히 연세 드신 어르신들은 침묵 속에서 존엄을 지킨다고 여기시는 경우도 있으니까요.", en: "Still, we can't entirely ignore the cultural context either. Especially for elderly patients, some feel that preserving dignity means maintaining silence." },
      { speaker: "완화의료 전문의", kr: "그 지점이 참 어려워요. 서구식 자기결정권 모델을 그대로 이식하는 게 능사는 아니라는 거죠.", en: "That's exactly the difficult part. Simply transplanting the Western model of autonomy wholesale isn't necessarily the right answer." },
      { speaker: "사회복지사", kr: "결국 각 가정의 문화와 환자 개인의 성향을 함께 고려하는 균형점을 찾아야겠네요.", en: "In the end, we need to find a balance that takes into account both each family's culture and the individual patient's disposition." },
      { speaker: "완화의료 전문의", kr: "그래서 저희 병원도 획일적인 매뉴얼 대신 사례별 상담 체계를 강화하는 쪽으로 방향을 잡았어요.", en: "That's why our hospital has also decided to strengthen a case-by-case counseling system instead of relying on a one-size-fits-all manual." },
    ],
  },
];

export const HOSPITAL_C_QUIZZES: Record<string, DialogueQuiz> = {
  "hospital-c1y-reform": {
    q: "According to Doctor 2, what factor beyond reimbursement rates contributes to doctors avoiding essential specialties?",
    opts: ["Lack of hospital beds", "Malpractice-litigation burden and workload intensity", "Insufficient medical school seats", "Poor public transportation to hospitals"],
    ans: 1,
  },
  "hospital-c1y-hedging": {
    q: "What does the doctor say cannot yet be determined about the imaging findings?",
    opts: ["The patient's blood type", "Whether the finding is malignant or benign", "The cost of treatment", "Which hospital department will treat the patient"],
    ans: 1,
  },
  "hospital-c1y-burnout": {
    q: "What does the senior doctor identify as a classic sign of burnout in the resident?",
    opts: ["Frequent tardiness", "Emotional numbness while treating patients", "Refusing night shifts", "Arguing with nurses"],
    ans: 1,
  },
  "hospital-c1y-budgetcuts": {
    q: "According to the administrator, what is excluded from the ten percent budget cut?",
    opts: ["Office supplies", "Essential medical supplies", "Consumable equipment", "Staff training budgets"],
    ans: 1,
  },
  "hospital-c1y-bioethics": {
    q: "What distinction does Student 2 draw between an adult refusing a transfusion and a minor's parents refusing one?",
    opts: ["There is no meaningful difference between the two", "Courts have intervened to prioritize a child's right to life in the minor's case", "Minors always have final say over their own treatment", "Religious objections apply only to adults"],
    ans: 1,
  },
  "hospital-c1y-billingprobe": {
    q: "What solution does the billing office manager describe to prevent future non-covered-item complaints?",
    opts: ["Removing all non-covered items from services", "An electronic consent system with real-time notification", "Hiring more billing staff", "Printing paper brochures for patients"],
    ans: 1,
  },
  "hospital-c1y-mentalhealthgap": {
    q: "What does the doctor offer to do to help the patient's mother understand the treatment?",
    opts: ["Write a formal letter to her", "Explain it directly if she comes to the next appointment", "Refer her to a different specialist", "Send her printed research articles"],
    ans: 1,
  },
  "hospital-c1y-fundingpitch": {
    q: "Why does the foundation representative want to wait before finalizing their funding amount?",
    opts: ["They doubt the phase 2 results", "They want to see the results of the government research grant application first", "The researcher hasn't submitted a proposal yet", "The foundation's board has been dissolved"],
    ans: 1,
  },
  "hospital-c1y-understaffing": {
    q: "What do the nurses decide to do about the understaffing problem?",
    opts: ["Quit their jobs immediately", "Compile staffing data to present at the next department meeting", "Ignore it since nothing can be done", "File individual complaints only"],
    ans: 1,
  },
  "hospital-c2y-triagedebate": {
    q: "What is the central point of contention between the two department heads?",
    opts: ["Whether to hire more emergency staff", "Whether current overcrowding should be treated as equivalent to a disaster scenario for triage purposes", "Whether to close the emergency department", "Whether patients should pay higher fees"],
    ans: 1,
  },
  "hospital-c2y-epidemiology": {
    q: "What does the health official say may have contributed to the outbreak spreading faster than expected?",
    opts: ["A shorter-than-expected incubation period", "A vaccine shortage", "Public non-compliance with masks", "A delay in laboratory testing equipment"],
    ans: 0,
  },
  "hospital-c2y-mediaethics": {
    q: "What compromise do the reporter and editor agree on regarding the story?",
    opts: ["Withhold the story entirely", "Disclose the hospital's name but keep individual staff identities private", "Publish only anonymous sources", "Name both the hospital and the individual staff involved"],
    ans: 1,
  },
  "hospital-c2y-airesearch": {
    q: "What compromise approach do the two doctors converge on regarding the AI diagnostic system?",
    opts: ["Reject the AI system entirely", "Use AI as an auxiliary tool within a dual-reading system, with regular error review", "Replace all radiologists with AI immediately", "Use AI only for administrative scheduling"],
    ans: 1,
  },
  "hospital-c2y-rareconsent": {
    q: "What does the physician say about reversing the experimental treatment if severe side effects occur?",
    opts: ["Full recovery is guaranteed", "Administration can be stopped and switched to symptomatic treatment, but full reversal isn't guaranteed", "There is no way to stop the treatment once started", "The hospital will not treat any resulting side effects"],
    ans: 1,
  },
  "hospital-c2y-priorityfunding": {
    q: "How does the health official ultimately respond to the claim that rare-disease funding is effectively frozen after accounting for inflation?",
    opts: ["Denies there is any validity to the claim", "Admits partial validity and says they're consulting on a real increase for next year's budget", "Refuses to comment further", "Blames patient advocacy groups for the shortfall"],
    ans: 1,
  },
  "hospital-c2y-overdiagnosis": {
    q: "What alternative to uniform blanket screening does the epidemiologist propose?",
    opts: ["Eliminating all screening programs", "A risk-stratified screening strategy based on risk groups", "Screening only patients over 65", "Doubling the frequency of current screenings for everyone"],
    ans: 1,
  },
  "hospital-c2y-disclosurecrisis": {
    q: "What did the internal investigation identify as the core cause of the medication error?",
    opts: ["A single nurse's personal negligence", "An interface issue in the electronic prescribing system showing similarly named drugs together", "A shortage of medication stock", "Patient noncompliance"],
    ans: 1,
  },
  "hospital-c2y-consentwithdrawal": {
    q: "Why did the trial subject want to withdraw consent?",
    opts: ["She experienced severe side effects from the drug", "News coverage of a different clinical trial incident made her anxious", "She moved to another city", "She was never given informed consent originally"],
    ans: 1,
  },
  "hospital-c2y-culturaltaboo": {
    q: "What is the palliative care specialist's main concern about withholding a terminal diagnosis from the patient?",
    opts: ["It violates hospital billing codes", "It deprives the patient of the chance to plan their remaining time themselves", "It is illegal in all cases", "It increases hospital costs"],
    ans: 1,
  },
};
