import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Hospital situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const HOSPITAL_C_EXPANSION: Dialogue[] = [
  {
    id: "hospital-c1y-reform",
    situationKey: "hospital",
    level: "C1",
    title: { en: "Colleagues debate healthcare reform", ja: "同僚同士が医療改革について議論する", zh: "同事们就医疗改革展开讨论" },
    lines: [
      { speaker: "의사1", kr: "이번에 발표된 의료 개혁안 보셨어요? 필수 진료과에 대한 수가를 대폭 인상한다고 하던데요.", en: "Did you see the healthcare reform plan they announced? Apparently they're drastically raising reimbursement rates for essential specialties.", ja: "今回発表された医療改革案、見ましたか？必須診療科の診療報酬を大幅に引き上げるらしいですよ。", zh: "你看到这次公布的医疗改革方案了吗？听说要大幅上调必要科室的诊疗费。" },
      { speaker: "의사2", kr: "저도 봤는데, 취지는 공감하지만 재원을 어디서 마련할지가 관건인 것 같아요.", en: "I saw it too. I agree with the intent, but where the funding will come from seems to be the crux of it.", ja: "私も見ました。趣旨には共感しますが、財源をどこから確保するかが鍵だと思います。", zh: "我也看到了。我认同这个初衷，但关键在于财源从哪里来。" },
      { speaker: "의사1", kr: "건강보험료 인상만으로는 한계가 있을 텐데, 정부 재정을 더 투입하지 않으면 지속되기 어렵지 않을까요.", en: "Raising health insurance premiums alone will only go so far—without more government funding, I don't think it'll be sustainable.", ja: "健康保険料の引き上げだけでは限界があるでしょうし、政府財政をもっと投入しなければ持続しにくいのではないでしょうか。", zh: "光靠上调医保费用是有限的，如果不增加政府财政投入，恐怕难以持续下去。" },
      { speaker: "의사2", kr: "맞아요. 게다가 필수과 기피 현상이 단순히 수가 문제만은 아니잖아요. 소송 부담이나 근무 강도도 무시할 수 없죠.", en: "Right. And the avoidance of essential specialties isn't purely a reimbursement issue either. The malpractice-litigation burden and workload intensity can't be ignored.", ja: "そうですね。それに必須科目の忌避現象は単に診療報酬だけの問題でもないですし。訴訟の負担や勤務強度も無視できません。", zh: "对，而且大家回避必要科室的现象也不单是诊疗费的问题。诉讼压力和工作强度也不容忽视。" },
      { speaker: "의사1", kr: "결국 종합적인 접근이 필요한데, 이번 안은 재정 대책이 다소 미흡해 보여서 실효성에 의문이 들어요.", en: "In the end a comprehensive approach is needed, but this plan's financial measures seem somewhat lacking, which makes me doubt its effectiveness.", ja: "結局は総合的なアプローチが必要ですが、今回の案は財政対策がやや不十分に見えて、実効性に疑問が残ります。", zh: "归根结底需要综合施策，但这次方案的财政对策似乎有些不足，让人怀疑实际效果。" },
      { speaker: "의사2", kr: "그래도 논의 자체가 시작됐다는 데 의의를 두고 싶어요. 의료계 목소리가 이번엔 어느 정도 반영된 것 같기도 하고요.", en: "Still, I want to find significance in the fact that the discussion has started. It also seems like the medical community's voice was reflected to some degree this time.", ja: "それでも議論自体が始まったことに意義を見出したいです。医療界の声も今回はある程度反映されたようですし。", zh: "不过我还是想肯定讨论已经开始这一点。这次医疗界的声音好像也在一定程度上被采纳了。" },
      { speaker: "의사1", kr: "공청회 일정이 잡히면 저희 병원에서도 의견서를 제출하는 게 좋겠어요.", en: "Once the public hearing schedule is set, I think our hospital should submit an opinion paper.", ja: "公聴会の日程が決まったら、うちの病院からも意見書を提出した方がいいですね。", zh: "等听证会日程定下来，我们医院也应该提交一份意见书。" },
      { speaker: "의사2", kr: "동의합니다. 현장의 목소리가 빠지면 또 탁상행정이 될 수밖에 없으니까요.", en: "I agree. If the voices from the field are left out, it'll inevitably become another case of desk-bound policymaking.", ja: "同感です。現場の声が抜けたら、また机上の空論になってしまいますから。", zh: "我同意。如果缺少一线的声音，就又会变成纸上谈兵的政策了。" },
    ],
  },
  {
    id: "hospital-c1y-hedging",
    situationKey: "hospital",
    level: "C1",
    title: { en: "Explaining a difficult diagnosis with care", ja: "難しい診断結果を慎重に説明する", zh: "谨慎地说明一个棘手的诊断" },
    lines: [
      { speaker: "의사", kr: "검사 결과를 말씀드리기 전에, 아직 확진은 아니고 추가 조직 검사가 필요한 단계라는 점을 먼저 말씀드리고 싶습니다.", en: "Before I share the test results, I want to first say that this isn't a confirmed diagnosis yet—we're at the stage where an additional biopsy is needed.", ja: "検査結果をお伝えする前に、まだ確定診断ではなく、追加の組織検査が必要な段階だということを先にお話ししたいと思います。", zh: "在告诉您检查结果之前，我想先说明这还不是确诊，目前处于需要进一步做组织检查的阶段。" },
      { speaker: "환자", kr: "네... 그래도 대략적으로라도 어떤 가능성이 있는지 알고 싶어요.", en: "Okay... but I'd still like to know, even roughly, what the possibilities are.", ja: "はい…それでも大まかにでもどんな可能性があるのか知りたいです。", zh: "好的……不过我还是想大概了解一下有哪些可能性。" },
      { speaker: "의사", kr: "영상에서 이형성이 의심되는 부위가 발견됐습니다. 악성일 가능성을 완전히 배제할 수는 없지만, 양성 소견과도 겹치는 부분이 있어요.", en: "The imaging revealed an area suspected of dysplasia. We can't completely rule out malignancy, but there's also overlap with benign findings.", ja: "画像で異形成が疑われる部位が見つかりました。悪性の可能性を完全には排除できませんが、良性の所見と重なる部分もあります。", zh: "影像检查发现了一处疑似异型增生的部位。虽然不能完全排除恶性的可能，但也有一些地方和良性表现重叠。" },
      { speaker: "환자", kr: "만약 안 좋은 쪽으로 나오면 어떻게 되는 건가요.", en: "If it comes back as the bad outcome, what happens then?", ja: "もし悪い方の結果が出たら、どうなるんですか。", zh: "如果结果不好的话，接下来会怎么样呢？" },
      { speaker: "의사", kr: "그 경우엔 병기를 판단하기 위한 추가 검사가 이어지고, 치료 방침도 그에 따라 결정됩니다. 다만 지금 단정 짓기보다는 결과를 기다려 보시는 게 맞습니다.", en: "In that case, further tests to determine the stage would follow, and the treatment plan would be decided accordingly. But rather than jumping to conclusions now, it's right to wait for the results.", ja: "その場合は病期を判断するための追加検査が続き、治療方針もそれに従って決まります。ただ今断定するより、結果を待たれる方が正しいです。", zh: "那样的话，会接着做进一步检查来判断分期，治疗方案也会据此决定。不过与其现在下定论，还是应该耐心等待结果。" },
      { speaker: "환자", kr: "불안한 마음은 어쩔 수 없네요.", en: "I can't help feeling anxious.", ja: "不安な気持ちはどうしようもないですね。", zh: "心里的不安还是没办法消除呢。" },
      { speaker: "의사", kr: "충분히 이해합니다. 조직 검사 결과는 일주일 정도 걸릴 예정이고, 그 사이 궁금한 점이 있으시면 언제든 연락 주셔도 됩니다.", en: "That's completely understandable. The biopsy results will take about a week, and if you have any questions in the meantime, please feel free to contact us anytime.", ja: "十分理解できます。組織検査の結果は一週間ほどかかる予定で、その間気になることがあればいつでもご連絡ください。", zh: "完全能理解。组织检查结果大约需要一周时间，这期间如果有任何疑问，随时可以联系我们。" },
      { speaker: "환자", kr: "감사합니다. 최악의 경우도 준비는 해 둬야겠죠.", en: "Thank you. I suppose I should prepare myself for the worst case too.", ja: "ありがとうございます。最悪の場合にも備えておかないといけませんね。", zh: "谢谢您。我想也应该为最坏的情况做好准备吧。" },
      { speaker: "의사", kr: "준비하시는 것도 좋지만, 확률상 양성일 가능성도 낮지 않다는 점은 기억해 주셨으면 합니다.", en: "Preparing is fine, but I'd like you to keep in mind that statistically, the chance of a benign result isn't low either.", ja: "備えることも大切ですが、確率的には良性である可能性も低くないという点も覚えておいてください。", zh: "做好准备当然好，但也希望您记住，从概率上看，结果为良性的可能性也不低。" },
    ],
  },
  {
    id: "hospital-c1y-burnout",
    situationKey: "hospital",
    level: "C1",
    title: { en: "A resident opens up about burnout", ja: "研修医が燃え尽き症候群について打ち明ける", zh: "住院医生坦承职业倦怠" },
    lines: [
      { speaker: "전공의", kr: "선생님, 요즘 제가 뭘 위해 이 일을 하고 있는지 모르겠다는 생각이 자꾸 들어요.", en: "Doctor, lately I keep thinking I don't know what I'm doing this work for anymore.", ja: "先生、最近自分が何のためにこの仕事をしているのか分からなくなることがよくあります。", zh: "老师，最近我总是觉得，不知道自己到底是为了什么在做这份工作。" },
      { speaker: "선배 의사", kr: "당직 스케줄이 워낙 빡빡했으니 그런 생각이 드는 것도 무리는 아니에요.", en: "Given how packed the on-call schedule's been, it's no wonder you'd feel that way.", ja: "当直のスケジュールがかなりきつかったので、そう思うのも無理はないですよ。", zh: "值班安排本来就那么紧张，会有这种想法也不奇怪。" },
      { speaker: "전공의", kr: "환자를 봐도 예전처럼 마음이 움직이지 않고, 그냥 기계적으로 처방만 내리고 있는 것 같아서 스스로도 놀랐어요.", en: "When I see patients, I don't feel moved the way I used to—I'm just mechanically writing prescriptions, and it surprised even me.", ja: "患者さんを見ても以前のように心が動かなくて、ただ機械的に処方を出しているだけのような気がして、自分でも驚きました。", zh: "看病人的时候也不像以前那样有感触了，感觉自己只是机械地开处方，这让我自己都吓了一跳。" },
      { speaker: "선배 의사", kr: "그건 소진 증후군의 전형적인 신호예요. 감정적으로 무뎌지는 걸 방치하면 결국 진료의 질에도 영향을 줘요.", en: "That's a textbook sign of burnout. If you leave that emotional numbness unaddressed, it eventually affects the quality of care too.", ja: "それは燃え尽き症候群の典型的な兆候です。感情が鈍くなるのを放っておくと、結局診療の質にも影響します。", zh: "那是职业倦怠的典型信号。如果放任这种情感麻木不管，最终会影响到诊疗质量。" },
      { speaker: "전공의", kr: "그래도 다들 이렇게 버티는데 저만 힘들다고 하기가 눈치 보여요.", en: "But since everyone else is enduring it like this, I feel self-conscious about being the only one struggling.", ja: "でもみんなこうして耐えているのに、自分だけつらいと言うのは気が引けます。", zh: "可是大家都这样撑着，只有我说自己撑不住，总觉得不太好意思。" },
      { speaker: "선배 의사", kr: "다들 버틴다고 해서 그게 정상이라는 뜻은 아니에요. 정신건강의학과 상담이든 휴가든, 필요한 조치를 취하는 게 오히려 책임 있는 태도예요.", en: "Just because everyone endures it doesn't mean it's normal. Whether it's psychiatric counseling or taking leave, taking the necessary measures is actually the more responsible attitude.", ja: "みんなが耐えているからといって、それが正常だという意味ではありません。精神科の相談でも休暇でも、必要な措置を取ることこそ責任ある態度です。", zh: "大家都在忍耐并不代表那就是正常的。不管是去看精神科咨询还是请假，采取必要的措施才是更负责任的态度。" },
      { speaker: "전공의", kr: "솔직히 상담을 받는다는 것 자체가 약점처럼 느껴지기도 해요.", en: "Honestly, the very idea of getting counseling feels like admitting a weakness.", ja: "正直、相談を受けること自体が弱みのように感じることもあります。", zh: "说实话，接受咨询这件事本身有时也让我觉得像是承认自己软弱。" },
      { speaker: "선배 의사", kr: "저도 레지던트 때 그랬어요. 하지만 돌아보면 그때 도움을 청했던 게 지금까지 이 일을 할 수 있게 해 준 이유였어요.", en: "I felt the same way during my residency. But looking back, asking for help back then is exactly why I've been able to keep doing this work.", ja: "私もレジデントの時そうでした。でも振り返ってみると、あの時助けを求めたことが今までこの仕事を続けられている理由でした。", zh: "我做住院医生的时候也是这样想的。但回过头看，正是那时候寻求了帮助，我才能坚持做这份工作到现在。" },
    ],
  },
  {
    id: "hospital-c1y-budgetcuts",
    situationKey: "hospital",
    level: "C1",
    title: { en: "An administrator justifies budget cuts", ja: "行政担当者が予算削減について説明する", zh: "行政人员为预算削减作解释" },
    lines: [
      { speaker: "행정팀장", kr: "다음 분기부터 각 부서 소모품 예산이 십 퍼센트 삭감될 예정입니다.", en: "Starting next quarter, each department's supply budget will be cut by ten percent.", ja: "来四半期から各部署の消耗品予算が十パーセント削減される予定です。", zh: "从下一季度起，各部门的耗材预算将削减百分之十。" },
      { speaker: "과장", kr: "환자 안전과 직결되는 물품까지 포함되는 건가요?", en: "Does that include supplies directly tied to patient safety?", ja: "患者の安全に直結する物品まで含まれるんですか？", zh: "包括直接关系到患者安全的物品吗？" },
      { speaker: "행정팀장", kr: "필수 의료용품은 제외되고, 사무용품이나 소모성 비품 위주로 조정될 계획입니다.", en: "Essential medical supplies are excluded—the adjustment is planned mainly around office supplies and consumable equipment.", ja: "必須医療用品は除外され、事務用品や消耗性備品中心に調整される予定です。", zh: "必要的医疗用品会排除在外，主要调整办公用品和消耗性设备。" },
      { speaker: "과장", kr: "그렇다면 다행이긴 한데, 병원 전체 재정이 그렇게 안 좋은가요?", en: "That's a relief, but is the hospital's overall finances really that bad?", ja: "それなら少し安心ですが、病院全体の財政がそんなに悪いんですか？", zh: "那样的话还算好，不过医院整体财务状况有那么糟糕吗？" },
      { speaker: "행정팀장", kr: "코로나 이후 병상 가동률이 완전히 회복되지 않은 데다, 인건비 상승분이 예상보다 컸습니다.", en: "Bed occupancy hasn't fully recovered since the pandemic, and the rise in labor costs was larger than expected.", ja: "コロナ以降病床稼働率が完全に回復していない上に、人件費の上昇分が予想より大きかったんです。", zh: "疫情之后床位使用率一直没有完全恢复，加上人力成本上涨幅度比预期更大。" },
      { speaker: "과장", kr: "현장에서는 예산이 줄면 곧바로 인력 충원도 미뤄질 거라고 우려하고 있어요.", en: "Staff on the ground are worried that if the budget shrinks, hiring will be postponed right away too.", ja: "現場では予算が減ればすぐに人員補充も先送りになるのではと懸念しています。", zh: "一线员工担心，预算一减少，人员招聘也会马上被推迟。" },
      { speaker: "행정팀장", kr: "인력 충원 계획 자체는 유지하되, 승인 절차가 다소 신중해질 수는 있습니다.", en: "The hiring plan itself will remain in place, but the approval process may become somewhat more cautious.", ja: "人員補充計画自体は維持しますが、承認手続きが多少慎重になる可能性はあります。", zh: "招聘计划本身会维持不变，但审批流程可能会变得稍微谨慎一些。" },
      { speaker: "과장", kr: "그 부분은 부서장들에게 명확히 공지해 주셨으면 합니다. 소문만 무성하면 사기가 떨어지니까요.", en: "I'd ask that you communicate that clearly to department heads. If it's left to rumor, morale will suffer.", ja: "その部分は部署長にはっきり通知していただきたいです。噂ばかり広がると士気が落ちますから。", zh: "希望能把这一点明确通知给各部门主管。要是只靠传言，会打击士气的。" },
      { speaker: "행정팀장", kr: "다음 주 부서장 회의에서 상세 자료를 배포하겠습니다.", en: "I'll distribute the detailed materials at next week's department heads meeting.", ja: "来週の部署長会議で詳細な資料を配布します。", zh: "我会在下周的部门主管会议上分发详细资料。" },
    ],
  },
  {
    id: "hospital-c1y-bioethics",
    situationKey: "hospital",
    level: "C1",
    title: { en: "Medical students debate a bioethics case", ja: "医学生が生命倫理の事例について議論する", zh: "医学生辩论一个生命伦理案例" },
    lines: [
      { speaker: "학생1", kr: "이번 사례 연구, 환자가 종교적 이유로 수혈을 거부한 경우잖아요. 의료진은 어디까지 존중해야 할까요.", en: "This case study is about a patient refusing a blood transfusion for religious reasons. To what extent should medical staff respect that?", ja: "今回のケーススタディ、患者が宗教的理由で輸血を拒否した場合ですよね。医療スタッフはどこまで尊重すべきでしょうか。", zh: "这次的案例研究是患者出于宗教原因拒绝输血的情况。医护人员应该尊重到什么程度呢？" },
      { speaker: "학생2", kr: "환자의 자기결정권은 원칙적으로 존중되어야 한다고 생각해요. 성인이고 판단 능력에 문제가 없다면요.", en: "I think patient autonomy should be respected in principle, as long as they're an adult with no impairment of judgment.", ja: "患者の自己決定権は原則として尊重されるべきだと思います。成人で判断能力に問題がなければ。", zh: "我认为原则上应该尊重患者的自主决定权，只要是成年人且判断能力没有问题。" },
      { speaker: "학생1", kr: "그런데 그 결정이 생명과 직결될 정도로 위중한 상황이라면 어떻게 되죠? 의료진의 윤리적 책임은요?", en: "But what if the decision is critical enough to directly determine life or death? What about the medical staff's ethical responsibility?", ja: "でもその決定が命に直結するほど重篤な状況ならどうなりますか？医療スタッフの倫理的責任は？", zh: "但如果这个决定严重到直接关乎生死，那该怎么办呢？医护人员的伦理责任又如何？" },
      { speaker: "학생2", kr: "설득은 최대한 해야겠지만, 최종적으로는 환자의 의사를 뒤집을 권한이 의료진에게 없다고 봐요.", en: "They should try their best to persuade the patient, but ultimately I don't think medical staff have the authority to override the patient's wishes.", ja: "説得は最大限すべきですが、最終的には患者の意思を覆す権限は医療スタッフにはないと思います。", zh: "应该尽最大努力去说服，但最终我认为医护人员没有权力推翻患者本人的意愿。" },
      { speaker: "학생1", kr: "그렇다면 미성년 자녀의 경우는 어떤가요. 부모가 수혈을 거부하면요.", en: "Then what about a minor child's case—if the parents refuse the transfusion?", ja: "それでは未成年の子供の場合はどうですか。親が輸血を拒否したら？", zh: "那未成年子女的情况呢？如果是父母拒绝输血。" },
      { speaker: "학생2", kr: "그건 완전히 다른 문제죠. 판례상 법원이 개입해서 아동의 생명권을 우선시한 사례들이 있잖아요.", en: "That's a completely different issue. There are precedents where courts intervened and prioritized the child's right to life.", ja: "それは全く別の問題です。判例上、裁判所が介入して子供の生命権を優先した事例がありますよね。", zh: "那完全是另一回事。判例中有法院介入并优先保障孩子生命权的案例。" },
      { speaker: "학생1", kr: "결국 자기결정권과 생명 보호 사이의 경계가 상황마다 다르게 그어진다는 거네요.", en: "So in the end, the line between autonomy and the protection of life gets drawn differently depending on the situation.", ja: "結局、自己決定権と生命保護の間の境界線は状況によって違って引かれるということですね。", zh: "所以说，自主决定权和保护生命之间的界线，会随情况的不同而有所变化。" },
      { speaker: "학생2", kr: "맞아요. 그래서 이런 사례들이 정답이 없는 대신 판단의 틀을 훈련시켜 주는 거고요.", en: "Exactly. That's why these cases don't have a single correct answer—instead, they train us in a framework for judgment.", ja: "そうです。だからこういう事例は正解がない代わりに、判断の枠組みを訓練させてくれるんです。", zh: "没错。所以这类案例没有标准答案，而是用来训练我们判断的思维框架。" },
    ],
  },
  {
    id: "hospital-c1y-billingprobe",
    situationKey: "hospital",
    level: "C1",
    title: { en: "A reporter probes hospital billing", ja: "記者が病院の請求問題を追及する", zh: "记者调查医院账单问题" },
    lines: [
      { speaker: "기자", kr: "환자들이 비급여 항목 안내를 제대로 받지 못했다는 민원이 계속 접수되고 있는데, 병원 측 입장은 어떻습니까.", en: "Complaints keep coming in that patients weren't properly informed about non-covered items—what's the hospital's position?", ja: "患者が非給付項目の案内を十分に受けられなかったという苦情が続いて寄せられていますが、病院側の立場はどうですか。", zh: "不断有投诉说患者没有得到关于自费项目的充分说明，医院方面对此有什么立场？" },
      { speaker: "원무과장", kr: "사전 설명 절차는 규정대로 진행하고 있습니다만, 일부 항목에서 안내가 미흡했던 사례가 있었던 건 사실입니다.", en: "We follow the required prior-explanation procedure, but it's true there were cases where the explanation for some items fell short.", ja: "事前説明の手続きは規定通り行っておりますが、一部項目で案内が不十分だった事例があったのは事実です。", zh: "事前说明流程是按规定进行的，但确实存在部分项目说明不到位的情况。" },
      { speaker: "기자", kr: "구체적으로 어떤 항목에서 문제가 발생한 겁니까?", en: "Specifically which items did the problems occur with?", ja: "具体的にどの項目で問題が発生したんですか？", zh: "具体是哪些项目出现了问题？" },
      { speaker: "원무과장", kr: "주로 검사 추가나 특수 재료 사용 시 실시간으로 동의를 받지 못한 경우들이었습니다.", en: "They were mostly cases where real-time consent wasn't obtained when additional tests or special materials were used.", ja: "主に検査追加や特殊材料使用時にリアルタイムで同意を得られなかったケースでした。", zh: "主要是在增加检查项目或使用特殊材料时，没能及时获得患者同意的情况。" },
      { speaker: "기자", kr: "그렇다면 재발 방지 대책은 마련되어 있나요.", en: "So do you have measures in place to prevent recurrence?", ja: "それでは再発防止策は用意されていますか。", zh: "那么有没有制定防止再次发生的对策？" },
      { speaker: "원무과장", kr: "전자 동의 시스템을 도입해서 항목이 추가될 때마다 환자에게 실시간 고지가 가도록 개선할 예정입니다.", en: "We plan to introduce an electronic consent system so that patients are notified in real time whenever an item is added.", ja: "電子同意システムを導入して、項目が追加されるたびに患者にリアルタイムで通知が行くよう改善する予定です。", zh: "我们计划引入电子同意系统，每次增加项目时都会实时通知患者。" },
      { speaker: "기자", kr: "도입 시기는 언제쯤으로 보십니까.", en: "When do you expect that system to be introduced?", ja: "導入時期はいつ頃と見ていますか。", zh: "预计什么时候能引入这个系统？" },
      { speaker: "원무과장", kr: "내부 검토가 끝나는 대로 다음 분기 안에 시행할 계획입니다.", en: "Once the internal review is complete, we plan to implement it within the next quarter.", ja: "内部検討が終わり次第、来四半期以内に実施する計画です。", zh: "内部审核结束后，计划在下一季度内实施。" },
    ],
  },
  {
    id: "hospital-c1y-mentalhealthgap",
    situationKey: "hospital",
    level: "C1",
    title: { en: "Generational views on mental health treatment", ja: "精神科治療をめぐる世代間の見解の違い", zh: "两代人对精神健康治疗的不同看法" },
    lines: [
      { speaker: "환자", kr: "어머니는 제가 상담받으러 다닌다고 하니까 그냥 마음을 굳게 먹으면 되는 거 아니냐고 하시더라고요.", en: "When I told my mother I was going to therapy, she just said, 'Can't you simply toughen your resolve?'", ja: "母は私がカウンセリングに通っていると言ったら、ただ気を強く持てばいいんじゃないかと言うんです。", zh: "我告诉妈妈我在看心理咨询，她就说，你就不能咬咬牙挺过去吗。" },
      { speaker: "의사", kr: "이전 세대에서는 정신과 진료를 받는다는 것 자체를 낙인처럼 여기는 경우가 많았으니까요.", en: "In the previous generation, receiving psychiatric care itself was often seen as something stigmatizing.", ja: "以前の世代では精神科の診療を受けること自体を汚名のように考えることが多かったですからね。", zh: "上一代人往往把接受精神科治疗本身看作一种耻辱标签。" },
      { speaker: "환자", kr: "저도 처음엔 약을 먹는다는 게 뭔가 패배를 인정하는 것 같아서 망설였어요.", en: "At first, I hesitated too, because taking medication felt like admitting some kind of defeat.", ja: "私も最初は薬を飲むことが何か敗北を認めるようで躊躇しました。", zh: "我一开始也犹豫过，觉得吃药好像是在承认某种失败。" },
      { speaker: "의사", kr: "많은 분들이 그렇게 느끼시죠. 하지만 우울증이나 불안장애도 다른 만성 질환처럼 생물학적 요인이 있는 질환이에요.", en: "Many people feel that way. But depression and anxiety disorders are conditions with biological factors, just like any other chronic illness.", ja: "多くの方がそう感じます。しかしうつ病や不安障害も、他の慢性疾患と同じように生物学的要因のある病気です。", zh: "很多人都有这种感觉。但抑郁症和焦虑障碍和其他慢性病一样，都是有生物学因素的疾病。" },
      { speaker: "환자", kr: "그 말씀을 들으니 조금은 마음이 편해지네요. 어머니께 어떻게 설명드려야 할지 여전히 막막하지만요.", en: "Hearing that puts my mind a bit more at ease, though I'm still at a loss for how to explain it to my mother.", ja: "そのお話を聞くと少し気が楽になります。母にどう説明すればいいのか、まだ途方に暮れていますが。", zh: "听您这么说，我心里稍微轻松了一些。不过要怎么跟妈妈解释，我还是没有头绪。" },
      { speaker: "의사", kr: "원하시면 다음 진료 때 어머님과 함께 오셔서 제가 직접 설명드릴 수도 있어요.", en: "If you'd like, you could bring your mother to the next appointment, and I could explain it to her directly.", ja: "ご希望であれば、次の診療の時にお母様と一緒に来られて、私が直接説明することもできます。", zh: "如果您愿意的话，下次看诊时可以带妈妈一起来，我可以直接向她说明。" },
      { speaker: "환자", kr: "그러면 정말 도움이 될 것 같아요. 전문가 말씀이면 조금은 다르게 받아들이실 수도 있으니까요.", en: "That would really help. Coming from a specialist, she might accept it a bit differently.", ja: "それは本当に助かります。専門家の言葉なら少し違った受け止め方をしてくれるかもしれませんから。", zh: "那真的会有帮助。如果是专家说的话，她或许会有不一样的接受方式。" },
    ],
  },
  {
    id: "hospital-c1y-fundingpitch",
    situationKey: "hospital",
    level: "C1",
    title: { en: "Negotiating funding for a clinical trial", ja: "臨床試験の資金交渉", zh: "为临床试验争取资金" },
    lines: [
      { speaker: "연구원", kr: "이번 임상시험 2상 결과가 긍정적으로 나와서 3상 진입을 위한 추가 지원을 요청드리려 합니다.", en: "The phase 2 results for this clinical trial came back positive, so I'd like to request additional support to move into phase 3.", ja: "今回の臨床試験フェーズ2の結果が良好だったので、フェーズ3進出のための追加支援をお願いしたいと思います。", zh: "这次临床试验二期结果良好，所以想请您为进入三期提供追加支持。" },
      { speaker: "재단 관계자", kr: "긍정적인 결과라니 반갑네요. 다만 3상은 규모가 훨씬 커질 텐데, 예상 소요 비용이 어느 정도인가요.", en: "Glad to hear the positive results. But phase 3 will be much larger in scale—what's the estimated cost?", ja: "良好な結果とは嬉しいですね。ただフェーズ3ははるかに規模が大きくなるでしょうが、予想される費用はどのくらいですか。", zh: "听到好结果我很高兴。不过三期规模会大得多，预计需要多少费用呢？" },
      { speaker: "연구원", kr: "다기관 임상으로 확대되면서 이전 대비 약 세 배 정도의 예산이 필요할 것으로 추산됩니다.", en: "Since it'll expand into a multi-center trial, we estimate roughly three times the budget compared to before.", ja: "多機関臨床に拡大するので、以前に比べて約三倍程度の予算が必要になると推算されます。", zh: "由于会扩展成多中心临床试验，估计需要之前大约三倍的预算。" },
      { speaker: "재단 관계자", kr: "이사회를 설득하려면 좀 더 구체적인 근거가 필요할 것 같아요. 다른 재원 확보 계획은 있으신가요.", en: "To persuade the board, we'll likely need more concrete grounds. Do you have plans to secure other sources of funding?", ja: "理事会を説得するには、もう少し具体的な根拠が必要だと思います。他の財源確保の計画はありますか。", zh: "要说服理事会，恐怕需要更具体的依据。有没有其他筹措资金的计划？" },
      { speaker: "연구원", kr: "정부 연구비 공모에도 별도로 지원해 둔 상태고, 결과는 다음 달 발표됩니다.", en: "We've also separately applied for a government research grant, and the results will be announced next month.", ja: "政府の研究費公募にも別途応募している状態で、結果は来月発表されます。", zh: "我们也另外申请了政府的研究经费，结果下个月公布。" },
      { speaker: "재단 관계자", kr: "그렇다면 정부 지원 결과가 나온 뒤에 저희 쪽 지원 규모를 확정하는 게 안전할 것 같습니다.", en: "In that case, it seems safer to finalize our support amount after the government funding results come out.", ja: "それなら政府の支援結果が出た後で、私たちの支援規模を確定する方が安全だと思います。", zh: "那样的话，等政府支持结果出来之后再确定我们这边的支持规模，会比较稳妥。" },
      { speaker: "연구원", kr: "이해합니다. 다만 3상 준비 자체는 시간이 걸리니, 예비 검토만이라도 지금부터 시작해 주실 수 있을까요.", en: "I understand. But since preparing for phase 3 itself takes time, could you at least start a preliminary review from now?", ja: "理解しました。ただフェーズ3の準備自体に時間がかかるので、予備検討だけでも今から始めていただけますか。", zh: "我理解。不过三期的准备本身就需要时间，能不能至少从现在开始做初步审查？" },
      { speaker: "재단 관계자", kr: "네, 예비 검토는 바로 착수하겠습니다.", en: "Yes, we'll go ahead and begin the preliminary review right away.", ja: "はい、予備検討はすぐに着手します。", zh: "好的，我们马上开始初步审查。" },
    ],
  },
  {
    id: "hospital-c1y-understaffing",
    situationKey: "hospital",
    level: "C1",
    title: { en: "Nurses discuss understaffing risks", ja: "看護師たちが人員不足のリスクについて話し合う", zh: "护士们讨论人手不足的风险" },
    lines: [
      { speaker: "간호사1", kr: "오늘 야간 근무에 저 혼자 병동 스물두 명을 봐야 하는데, 이게 정말 안전한 건지 모르겠어요.", en: "I have to cover twenty-two patients on the ward alone during tonight's shift—I'm not sure this is really safe.", ja: "今日の夜勤で私一人で病棟二十二人を見なければならないんですが、これが本当に安全なのか分かりません。", zh: "今晚夜班要我一个人负责病房里二十二个病人，我真不知道这样是不是安全。" },
      { speaker: "간호사2", kr: "저도 지난주에 비슷한 상황이었는데, 투약 시간을 지키는 것만도 벅찼어요.", en: "I was in a similar situation last week too—it was already a struggle just to keep up with medication times.", ja: "私も先週似たような状況で、投薬時間を守るだけでも精一杯でした。", zh: "我上周也遇到过类似情况，光是按时给药就已经忙不过来了。" },
      { speaker: "간호사1", kr: "이러다가 투약 오류라도 나면 결국 책임은 저희한테 돌아오는 거잖아요.", en: "If a medication error happens because of this, the responsibility will ultimately fall on us.", ja: "こんなことで投薬ミスでも起きたら、結局責任は私たちに来るじゃないですか。", zh: "要是因为这样出了给药差错，责任最终还是会落在我们头上。" },
      { speaker: "간호사2", kr: "맞아요. 인력 배치 기준 자체가 현실과 너무 동떨어져 있는 것 같아요.", en: "Right. The staffing standards themselves seem far too disconnected from reality.", ja: "そうです。人員配置基準自体が現実とあまりにかけ離れている気がします。", zh: "没错。人力配置标准本身好像和现实脱节太远了。" },
      { speaker: "간호사1", kr: "노조를 통해서든 뭐든 이 문제를 공식적으로 제기해야 할 것 같아요. 더 이상 개인이 감당할 수준이 아니에요.", en: "I think we need to formally raise this issue, whether through the union or otherwise. It's no longer something individuals can bear.", ja: "労働組合を通じてでも何でも、この問題を正式に提起すべきだと思います。もう個人が耐えられるレベルではありません。", zh: "不管是通过工会还是别的途径，我觉得应该正式提出这个问题。这已经不是个人能承受的程度了。" },
      { speaker: "간호사2", kr: "저도 동의해요. 다음 부서 회의 때 근무 인원 현황 자료를 정리해서 제출하는 게 어떨까요.", en: "I agree. How about we compile the staffing data and submit it at the next department meeting?", ja: "私も同感です。次の部署会議で勤務人員の現況資料をまとめて提出するのはどうでしょうか。", zh: "我也同意。下次部门会议时，我们整理一份排班人数现状资料提交上去怎么样？" },
      { speaker: "간호사1", kr: "좋아요. 숫자로 보여주면 위에서도 무시하기는 어려울 거예요.", en: "Good idea. If we show it with numbers, it'll be harder for management to ignore.", ja: "いいですね。数字で見せれば上層部も無視しにくいでしょう。", zh: "好主意。用数字摆出来，上面也很难视而不见。" },
      { speaker: "간호사2", kr: "이번엔 흐지부지되지 않게 끝까지 챙겨봐요.", en: "Let's make sure this doesn't fizzle out this time—let's see it through.", ja: "今回はうやむやにならないように最後まで見届けましょう。", zh: "这次一定要盯到底，别不了了之。" },
    ],
  },
  {
    id: "hospital-c2y-triagedebate",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Debating triage priorities during a surge", ja: "急増時のトリアージ優先順位をめぐる議論", zh: "关于患者激增时分诊优先级的辩论" },
    lines: [
      { speaker: "응급의학과장", kr: "환자 급증 시 중증도 분류 기준을 어떻게 조정할지에 대해 부서 간 이견이 좁혀지지 않고 있습니다.", en: "There's a persistent disagreement between departments over how to adjust triage criteria during a surge in patients.", ja: "患者急増時の重症度分類基準をどう調整するかについて、部署間の意見の相違が縮まっていません。", zh: "关于患者激增时如何调整重症分级标准，各科室之间的分歧一直没能缩小。" },
      { speaker: "내과과장", kr: "만성질환 악화 환자를 우선순위에서 지나치게 낮추면, 결국 골든타임을 놓치는 사례가 늘어날 겁니다.", en: "If we lower the priority of patients with worsening chronic conditions too much, we'll end up seeing more cases where the golden hour is missed.", ja: "慢性疾患悪化患者の優先順位をあまりに下げると、結局ゴールデンタイムを逃す事例が増えるでしょう。", zh: "如果把慢性病恶化的患者优先级降得太低，最终会有更多病例错过黄金抢救时间。" },
      { speaker: "응급의학과장", kr: "이해는 하지만, 자원이 한정된 상황에서는 즉각적인 생명 위협이 있는 환자를 최우선으로 둘 수밖에 없다는 게 국제 기준이기도 합니다.", en: "I understand, but under conditions of limited resources, prioritizing patients with immediate life-threatening conditions is also the international standard.", ja: "理解はしますが、資源が限られた状況では即座に生命の危険がある患者を最優先にせざるを得ないというのが国際基準でもあります。", zh: "我理解，但在资源有限的情况下，把有即时生命危险的患者放在最优先，这也是国际通行标准。" },
      { speaker: "내과과장", kr: "그 기준이 재난 상황을 전제로 만들어진 건데, 평시 과밀화까지 동일하게 적용하는 게 과연 타당한지 의문입니다.", en: "That standard was designed with disaster scenarios in mind, so I question whether it's really valid to apply it identically to routine overcrowding as well.", ja: "その基準は災害状況を前提に作られたものなのに、平時の過密化にまで同じように適用するのが果たして妥当なのか疑問です。", zh: "那个标准是以灾难场景为前提制定的，把它同样套用在日常的过度拥挤上，是否合适，我持怀疑态度。" },
      { speaker: "응급의학과장", kr: "그렇다면 현재의 과밀화를 재난에 준하는 상황으로 볼 것인지부터가 논쟁의 핵심이겠네요.", en: "Then whether we regard the current overcrowding as tantamount to a disaster is itself the crux of this debate, isn't it.", ja: "それなら現在の過密化を災害に準じる状況と見るかどうかが、まさに論争の核心ですね。", zh: "那么当前的过度拥挤是否应视为等同于灾难的状况，这本身就是争论的核心了。" },
      { speaker: "내과과장", kr: "정확합니다. 그리고 그 판단에 따라 병원 전체의 자원 배분 철학이 달라질 수밖에 없고요.", en: "Exactly. And depending on that judgment, the entire hospital's philosophy of resource allocation is bound to change.", ja: "その通りです。そしてその判断次第で病院全体の資源配分の理念も変わらざるを得ません。", zh: "正是如此。而且根据这个判断的不同，整个医院资源分配的理念也必然会随之改变。" },
      { speaker: "응급의학과장", kr: "일단 이번 주 내로 위원회를 소집해서 잠정 기준안을 마련하는 게 급선무일 것 같습니다.", en: "For now, I think the urgent priority is to convene a committee within this week and draft a provisional set of criteria.", ja: "とりあえず今週中に委員会を招集して、暫定基準案を用意することが急務だと思います。", zh: "眼下当务之急，我认为是在本周内召集委员会，拟定一份暂定标准草案。" },
      { speaker: "내과과장", kr: "동의합니다. 다만 최종 기준이 나오기 전까지는 현장 재량을 존중해 주셨으면 합니다.", en: "I agree. But until the final criteria come out, I'd ask that clinical discretion in the field be respected.", ja: "同意します。ただ最終基準が出るまでは現場の裁量を尊重してほしいです。", zh: "我同意。不过在最终标准出台之前，希望能尊重一线的临床裁量权。" },
      { speaker: "응급의학과장", kr: "물론이죠. 이건 규정으로 현장을 옥죄자는 취지가 아니라 오히려 보호하자는 취지니까요.", en: "Of course. This isn't meant to constrain frontline staff with regulations—it's meant to protect them, if anything.", ja: "もちろんです。これは規定で現場を縛ろうという趣旨ではなく、むしろ守ろうという趣旨ですから。", zh: "那是当然。这不是要用规定束缚一线人员，反而是为了保护他们。" },
    ],
  },
  {
    id: "hospital-c2y-epidemiology",
    situationKey: "hospital",
    level: "C2",
    title: { en: "A public health official presents an epidemiological report", ja: "保健当局者が疫学調査の結果を発表する", zh: "公共卫生官员发布流行病学报告" },
    lines: [
      { speaker: "보건 당국자", kr: "이번 집단 감염 사례에 대한 역학조사 결과를 말씀드리겠습니다. 최초 감염 경로는 아직 완전히 특정되지 않았습니다.", en: "I'll present the epidemiological investigation results for this cluster outbreak. The initial route of transmission has not yet been fully identified.", ja: "今回の集団感染事例に関する疫学調査の結果をご報告します。最初の感染経路はまだ完全には特定されていません。", zh: "我来报告这次集群感染事件的流行病学调查结果。最初的感染途径目前尚未完全查明。" },
      { speaker: "기자", kr:"확산 속도가 예상보다 빨랐다는 지적이 있는데, 초기 대응에 문제가 있었던 건 아닙니까.", en: "There have been claims that the spread was faster than expected—wasn't there a problem with the initial response?", ja: "拡散速度が予想より速かったという指摘がありますが、初期対応に問題があったのではないですか。", zh: "有人指出扩散速度比预期快，是不是初期应对存在问题？" },
      { speaker: "보건 당국자", kr: "잠복기가 예상보다 짧게 관찰된 것이 확산 속도에 영향을 미쳤을 가능성이 있고, 초기 접촉자 추적은 지침에 따라 이루어졌습니다.", en: "It's possible that the incubation period, which was observed to be shorter than expected, affected the speed of spread, and the initial contact tracing was carried out according to protocol.", ja: "潜伏期間が予想より短く観察されたことが拡散速度に影響した可能性があり、初期の接触者追跡は指針に従って行われました。", zh: "潜伏期观察到比预期更短，这可能影响了扩散速度，而初期的密接追踪是按照指南进行的。" },
      { speaker: "기자", kr: "그렇다면 지침 자체를 개정할 계획은 없으십니까.", en: "Then do you have no plans to revise the protocol itself?", ja: "それなら指針自体を改定する計画はないんですか。", zh: "那么有没有计划修改指南本身呢？" },
      { speaker: "보건 당국자", kr: "이번 사례를 반영해서 접촉자 범위를 확대하는 방향으로 지침 개정을 검토 중입니다. 다음 달 전문가 자문회의를 거칠 예정입니다.", en: "We're reviewing a revision to expand the scope of contact tracing based on this case, and it will go through an expert advisory meeting next month.", ja: "今回の事例を反映して接触者範囲を拡大する方向で指針改定を検討中です。来月専門家諮問会議を経る予定です。", zh: "我们正在考虑根据这次事件扩大密接者的追踪范围，修订指南，下个月将召开专家咨询会议。" },
      { speaker: "기자", kr: "지역사회 감염으로 확대될 가능성은 어느 정도로 보십니까.", en: "How likely do you think it is that this will spread into community transmission?", ja: "地域社会感染に拡大する可能性はどの程度と見ていますか。", zh: "您认为扩散成社区传播的可能性有多大？" },
      { speaker: "보건 당국자", kr: "현재까지 확인된 감염원은 특정 시설 내로 국한되어 있지만, 안심할 단계는 아니라고 판단하고 있습니다.", en: "As of now, the confirmed sources of infection are confined within a specific facility, but we don't judge it to be a stage where we can be complacent.", ja: "現在まで確認された感染源は特定施設内に限定されていますが、安心できる段階ではないと判断しています。", zh: "目前确认的感染源仅限于特定设施内，但我们判断现在还不是可以掉以轻心的阶段。" },
      { speaker: "기자", kr: "시민들이 특별히 주의해야 할 점이 있다면 말씀해 주시죠.", en: "If there's anything citizens should be particularly careful about, please tell us.", ja: "市民が特に注意すべき点があれば教えてください。", zh: "如果有市民需要特别注意的地方，请告诉我们。" },
      { speaker: "보건 당국자", kr: "해당 시설을 방문하신 분들은 증상 유무와 관계없이 보건소에 신고해 주시고, 밀접 접촉자로 분류되신 분들은 자가격리 지침을 준수해 주시기 바랍니다.", en: "We ask that anyone who visited the facility report to the public health center regardless of symptoms, and that those classified as close contacts comply with the self-quarantine guidelines.", ja: "当該施設を訪問された方は症状の有無にかかわらず保健所に届け出てください。濃厚接触者に分類された方は自宅隔離指針を守ってください。", zh: "去过该设施的人，无论有无症状，都请向保健所报告；被列为密切接触者的人，请遵守居家隔离指南。" },
    ],
  },
  {
    id: "hospital-c2y-mediaethics",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Editorial debate on covering a medical error", ja: "医療事故報道をめぐる編集会議の議論", zh: "关于报道医疗事故的编辑室辩论" },
    lines: [
      { speaker: "기자", kr: "이번 의료사고 보도, 병원 측 실명을 공개하는 게 맞을까요? 아직 조사 결과가 확정된 것도 아닌데요.", en: "For this medical-error story, is it right to disclose the hospital's name? The investigation results aren't even finalized yet.", ja: "今回の医療事故報道、病院側の実名を公開するのが正しいでしょうか？まだ調査結果が確定したわけでもないのに。", zh: "这次医疗事故的报道，公开医院的真实名称合适吗？调查结果都还没有定论呢。" },
      { speaker: "데스크", kr: "공익성을 고려하면 시민들의 알 권리가 우선이지만, 확정되지 않은 사안을 단정적으로 다루면 명예훼손 소지도 있어요.", en: "Considering the public interest, citizens' right to know takes priority, but if we treat an unconfirmed matter as settled fact, there's also a risk of defamation.", ja: "公益性を考えれば市民の知る権利が優先ですが、確定していない事案を断定的に扱うと名誉毀損の恐れもあります。", zh: "考虑到公共利益，市民的知情权应该优先，但如果把尚未确认的事情当作定论来报道，也有诽谤的风险。" },
      { speaker: "기자", kr: "그렇다고 익명 처리를 하면 이 사건이 갖는 경각심 자체가 희석될 수 있잖아요.", en: "But if we anonymize it, the sense of alarm this incident is meant to raise could itself get diluted.", ja: "だからといって匿名にすれば、この事件が持つ警鐘の意味自体が薄れかねません。", zh: "但如果匿名处理，这起事件本应带来的警示作用也可能被削弱。" },
      { speaker: "데스크", kr: "맞는 말이지만, 저희 보도로 인해 무고한 의료진까지 여론재판을 받게 되는 부작용도 고려해야 해요.", en: "That's true, but we also have to consider the side effect that our reporting could subject even innocent medical staff to trial by public opinion.", ja: "その通りですが、私たちの報道によって無実の医療スタッフまで世論裁判を受ける副作用も考慮しなければなりません。", zh: "这话没错，但也要考虑到我们的报道可能会让无辜的医护人员也遭到舆论审判的副作用。" },
      { speaker: "기자", kr: "그러면 병원 실명은 밝히되, 담당 의료진 개인 신상은 비공개로 하는 절충안은 어떨까요.", en: "Then how about a compromise—disclose the hospital's name but keep the individual staff members' personal information private?", ja: "それでは病院の実名は明かすが、担当医療スタッフ個人の身元は非公開にする折衷案はどうでしょうか。", zh: "那公开医院真名，但对当事医护人员的个人身份保密，这样的折中方案怎么样？" },
      { speaker: "데스크", kr: "그게 현실적인 균형점 같네요. 다만 조사 결과가 나오기 전까지는 '의혹'이라는 표현을 일관되게 써 주세요.", en: "That seems like a realistic balance. But until the investigation results come out, please consistently use the term 'allegation.'", ja: "それが現実的なバランス点のようですね。ただ調査結果が出るまでは「疑惑」という表現を一貫して使ってください。", zh: "这看起来是个比较现实的平衡点。不过在调查结果出来之前，请统一使用「疑似」这样的措辞。" },
      { speaker: "기자", kr: "네, 그리고 병원 측 반론도 같은 비중으로 실어야겠죠.", en: "Understood, and we should also give the hospital's rebuttal equal weight.", ja: "はい、それと病院側の反論も同じ比重で載せるべきですね。", zh: "好的，而且医院方面的反驳意见也应该给予同等篇幅。" },
      { speaker: "데스크", kr: "물론이죠. 균형을 잃는 순간 이 보도의 신뢰성 자체가 흔들리니까요.", en: "Of course. The moment we lose balance, the credibility of the report itself will be shaken.", ja: "もちろんです。バランスを失った瞬間、この報道の信頼性自体が揺らぎますから。", zh: "那是当然。一旦失去平衡，这篇报道本身的可信度就会动摇。" },
      { speaker: "기자", kr: "알겠습니다. 병원 측 공식 입장부터 다시 요청해 보겠습니다.", en: "Understood. I'll go ahead and request the hospital's official statement again first.", ja: "分かりました。病院側の公式立場からもう一度依頼してみます。", zh: "明白了。我先重新去索要一份医院的正式声明。" },
    ],
  },
  {
    id: "hospital-c2y-airesearch",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Debating AI diagnostic tools in practice", ja: "AI診断ツールの実運用をめぐる議論", zh: "关于AI诊断工具实际应用的辩论" },
    lines: [
      { speaker: "의사1", kr: "인공지능 판독 보조 시스템 도입안, 결국 이사회에서 통과됐다고 하더라고요.", en: "I heard the proposal to introduce the AI-assisted reading system finally passed at the board level.", ja: "人工知能読影補助システムの導入案、結局理事会で可決されたそうですよ。", zh: "听说人工智能辅助读片系统的引进方案最终在理事会通过了。" },
      { speaker: "의사2", kr: "저는 여전히 우려가 커요. 알고리즘의 판단 근거가 완전히 투명하지 않은 상태에서 최종 책임만 임상의에게 지우는 구조잖아요.", en: "I'm still quite concerned. It's a structure where the algorithm's reasoning isn't fully transparent, yet the final responsibility rests entirely on the clinician.", ja: "私は依然として懸念が大きいです。アルゴリズムの判断根拠が完全に透明でない状態で、最終責任だけ臨床医に負わせる構造じゃないですか。", zh: "我还是很担心。这是一种算法判断依据不完全透明，却把最终责任全都压在临床医生身上的结构。" },
      { speaker: "의사1", kr: "그 점은 저도 동의하지만, 판독 정확도 자체는 여러 논문에서 숙련의 수준에 근접했다는 결과가 나왔잖아요.", en: "I agree on that point, but multiple papers have shown the reading accuracy itself approaches the level of experienced specialists.", ja: "その点は私も同意しますが、読影精度自体は複数の論文で熟練医のレベルに近づいたという結果が出ていますよね。", zh: "这一点我也同意，但读片准确度本身，已经有多篇论文显示接近资深专科医生的水平了。" },
      { speaker: "의사2", kr: "정확도가 높다고 해서 오진의 책임 소재 문제가 해결되는 건 아니죠. 시스템 오류로 놓친 소견을 누가 책임질지 아직 불분명해요.", en: "High accuracy doesn't resolve the question of liability for misdiagnosis. It's still unclear who's responsible for a finding missed due to a system error.", ja: "精度が高いからといって誤診の責任所在の問題が解決されるわけではありません。システムエラーで見落とした所見を誰が責任を負うのかまだ不明です。", zh: "准确度高并不能解决误诊责任归属的问题。因系统错误而漏诊的责任由谁来承担，目前还不明确。" },
      { speaker: "의사1", kr: "결국 이중 판독 체계로 운영하면서 인공지능은 보조 수단으로만 활용하는 게 현실적인 절충안 아닐까요.", en: "In the end, isn't operating a dual-reading system, where AI is used only as an auxiliary tool, the realistic compromise?", ja: "結局二重読影体制で運用しながら、人工知能は補助手段としてのみ活用するのが現実的な折衷案じゃないでしょうか。", zh: "说到底，采用双重读片制度、把人工智能仅作为辅助手段来使用，会不会才是现实的折中方案？" },
      { speaker: "의사2", kr: "저도 그 방향에는 공감해요. 다만 시간이 지나면서 의존도가 서서히 높아지는 게 진짜 위험 요소라고 봐요.", en: "I agree with that direction too. But I think the real risk factor is that dependence will gradually increase over time.", ja: "私もその方向には共感します。ただ時間が経つにつれ依存度が徐々に高まることが本当のリスク要因だと思います。", zh: "这个方向我也认同。不过我认为，随着时间推移依赖程度逐渐加深，这才是真正的风险因素。" },
      { speaker: "의사1", kr: "그래서 정기적으로 오류 사례를 검토하고 피드백하는 체계가 병행되어야 할 것 같아요.", en: "That's why I think a system for regularly reviewing error cases and feeding back the findings needs to run in parallel.", ja: "だから定期的にエラー事例を検討しフィードバックする体制を並行させる必要があると思います。", zh: "所以我觉得需要同时建立一套定期检讨错误案例并反馈的机制。" },
      { speaker: "의사2", kr: "동의합니다. 기술을 배척할 게 아니라 통제할 수 있는 틀을 먼저 갖추는 게 순서겠죠.", en: "I agree. Rather than rejecting the technology outright, establishing a framework to control it should come first.", ja: "同意します。技術を排斥するのではなく、統制できる枠組みを先に整えるのが順序でしょう。", zh: "我同意。与其排斥技术，不如先建立能够加以管控的框架，这才是正确的顺序。" },
      { speaker: "의사1", kr: "도입 후 첫 6개월간의 성과 지표를 별도로 추적해서 공유하는 것도 제안해 봐야겠어요.", en: "I should also propose separately tracking and sharing performance metrics for the first six months after implementation.", ja: "導入後最初の六ヶ月間の成果指標を別途追跡して共有することも提案してみます。", zh: "我也应该提议，单独追踪并分享引进后前六个月的绩效指标。" },
    ],
  },
  {
    id: "hospital-c2y-rareconsent",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Debating consent for an experimental therapy", ja: "実験的治療への同意をめぐる話し合い", zh: "关于实验性疗法同意书的讨论" },
    lines: [
      { speaker: "주치의", kr: "표준 치료로는 더 이상 반응을 기대하기 어려운 상황이라, 실험적 치료를 제안드리려 합니다.", en: "Since we can no longer reasonably expect a response from standard treatment, I'd like to propose an experimental therapy.", ja: "標準治療ではもうこれ以上反応が期待しにくい状況なので、実験的治療をご提案したいと思います。", zh: "由于标准治疗已经很难再期待出现反应，我想向您提议尝试实验性疗法。" },
      { speaker: "보호자", kr: "그 치료법의 안전성은 어느 정도 검증된 건가요? 임상 사례가 많지 않다고 들었어요.", en: "To what extent has that therapy's safety been verified? I've heard there aren't many clinical cases.", ja: "その治療法の安全性はどの程度検証されているんですか？臨床事例が多くないと聞きました。", zh: "这种疗法的安全性经过多大程度的验证呢？听说临床案例并不多。" },
      { speaker: "주치의", kr: "소규모 임상에서 유의미한 반응률이 보고되긴 했지만, 장기적인 부작용에 대해서는 아직 축적된 데이터가 충분하지 않습니다.", en: "A meaningful response rate has been reported in small-scale trials, but there isn't yet sufficient accumulated data on long-term side effects.", ja: "小規模臨床では有意な反応率が報告されていますが、長期的な副作用についてはまだ十分なデータが蓄積されていません。", zh: "小规模临床试验中确实报告了有意义的反应率，但关于长期副作用的数据积累还不够充分。" },
      { speaker: "보호자", kr: "만약 부작용이 심각하게 나타나면 되돌릴 방법이 있나요.", en: "If severe side effects occur, is there a way to reverse them?", ja: "もし副作用が深刻に現れたら、元に戻す方法はありますか。", zh: "如果出现严重的副作用，有办法逆转吗？" },
      { speaker: "주치의", kr: "투여를 즉시 중단하고 대증 치료로 전환할 수는 있지만, 완전히 원상 복구된다는 보장은 드리기 어렵습니다.", en: "We can stop administration immediately and switch to symptomatic treatment, but I can't guarantee a full return to the original condition.", ja: "投与をすぐに中止して対症療法に切り替えることはできますが、完全に元通りになる保証は難しいです。", zh: "可以立即停止用药并转为对症治疗，但很难保证能完全恢复原状。" },
      { speaker: "보호자", kr: "환자 본인은 어떤 입장이신지 여쭤봐도 될까요.", en: "May I ask what the patient herself thinks about this?", ja: "患者ご本人はどのようなお考えなのか伺ってもいいですか。", zh: "可以问一下患者本人是什么想法吗？" },
      { speaker: "주치의", kr: "환자분께서는 남은 가능성에 걸어보고 싶다는 의사를 이미 밝히셨습니다. 다만 최종 동의는 가족분들과 충분히 논의하신 뒤에 받고자 합니다.", en: "The patient has already expressed a wish to take a chance on the remaining possibility. However, we'd like to obtain final consent only after you've had a thorough discussion with the family.", ja: "患者様はすでに残された可能性に賭けてみたいという意思を示されています。ただ最終同意はご家族と十分に話し合われた後にいただきたいと思います。", zh: "患者本人已经表示想赌一把剩下的可能性。不过最终的同意，我们希望是在您与家人充分商量之后再确认。" },
      { speaker: "보호자", kr: "저희끼리 상의할 시간을 며칠 주실 수 있을까요.", en: "Could you give us a few days to discuss it among ourselves?", ja: "私たちだけで相談する時間を数日いただけますか。", zh: "能不能给我们几天时间自己商量一下？" },
      { speaker: "주치의", kr: "물론입니다. 다만 치료 효과는 병기 진행 전에 시작할수록 높아지니, 일주일 이내로 결정해 주시면 감사하겠습니다.", en: "Of course. But since the treatment's efficacy is higher the earlier it starts before the disease progresses, I'd appreciate a decision within a week.", ja: "もちろんです。ただ治療効果は病期進行前に始めるほど高くなるので、一週間以内に決めていただけると助かります。", zh: "当然可以。不过治疗效果是越早在病情进展之前开始越好，所以希望您能在一周之内做出决定。" },
    ],
  },
  {
    id: "hospital-c2y-priorityfunding",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Journalist and official spar over research priorities", ja: "記者と当局者が研究優先順位をめぐって応酬する", zh: "记者与官员就研究优先事项展开交锋" },
    lines: [
      { speaker: "기자", kr: "희귀질환 연구 예산이 매년 삭감되는 반면, 특정 대기업이 후원하는 연구에는 예산이 몰리고 있다는 지적이 있습니다.", en: "There's criticism that funding for rare disease research is cut every year, while research sponsored by certain large corporations is receiving concentrated investment.", ja: "希少疾患研究予算が毎年削減される一方、特定の大企業が後援する研究には予算が集中しているという指摘があります。", zh: "有批评指出，罕见病研究预算逐年削减，而某些大企业赞助的研究却预算集中投入。" },
      { speaker: "보건 당국자", kr: "예산 배분은 환자 수와 사회적 부담을 종합적으로 고려한 결과이지, 특정 기업의 이해관계가 반영된 게 아닙니다.", en: "Budget allocation is the result of comprehensively considering patient numbers and social burden—it doesn't reflect any particular company's interests.", ja: "予算配分は患者数と社会的負担を総合的に考慮した結果であり、特定企業の利害関係が反映されたものではありません。", zh: "预算分配是综合考虑患者人数和社会负担之后的结果，并没有反映特定企业的利益。" },
      { speaker: "기자", kr: "그렇지만 희귀질환은 환자 수가 적다는 이유로 늘 후순위로 밀리는 구조 아닙니까.", en: "But isn't the structure such that rare diseases are always pushed to lower priority precisely because of their small patient numbers?", ja: "しかし希少疾患は患者数が少ないという理由で常に後回しにされる構造ではないですか。", zh: "但罕见病不是总因为患者数量少而一直被排在次要地位吗？" },
      { speaker: "보건 당국자", kr: "그 점을 보완하기 위해 별도의 희귀질환 전용 기금을 운영하고 있고, 올해 지원 규모도 소폭 확대되었습니다.", en: "To make up for that, we operate a separate fund dedicated to rare diseases, and this year's support was also modestly expanded.", ja: "その点を補うために別途希少疾患専用基金を運営していて、今年の支援規模も小幅ながら拡大されました。", zh: "为了弥补这一点，我们运营着专门的罕见病基金，今年的支持规模也略有扩大。" },
      { speaker: "기자", kr: "소폭 확대라고 하셨는데, 물가상승률을 감안하면 실질적으로는 동결에 가깝지 않습니까.", en: "You said 'modestly expanded,' but accounting for inflation, isn't that effectively close to a freeze?", ja: "小幅拡大とおっしゃいましたが、物価上昇率を考慮すれば実質的には凍結に近いのではないですか。", zh: "您说是小幅扩大，但考虑到通货膨胀率，实际上不是接近冻结吗？" },
      { speaker: "보건 당국자", kr: "그 지적에는 일부 타당한 측면이 있습니다. 내년도 예산안에서 실질 증액을 반영하도록 관련 부서와 협의 중입니다.", en: "There's some validity to that point. We're consulting with the relevant departments to reflect a real increase in next year's budget proposal.", ja: "その指摘には一部妥当な面があります。来年度予算案で実質増額を反映するよう関連部署と協議中です。", zh: "这个指出有一定的道理。我们正在与相关部门协商，力求在明年的预算方案中体现实质性增加。" },
      { speaker: "기자", kr: "구체적인 증액 규모나 시기를 지금 말씀해 주실 수 있나요.", en: "Can you tell us the specific scale or timing of the increase right now?", ja: "具体的な増額規模や時期を今お話しいただけますか。", zh: "能否现在告诉我们具体的增加幅度或时间？" },
      { speaker: "보건 당국자", kr: "아직 확정 전이라 구체적인 수치를 말씀드리기는 조심스럽습니다만, 국회 예산 심의 전까지는 방향을 확정할 예정입니다.", en: "Since it hasn't been finalized, I'm cautious about giving specific figures, but we plan to finalize the direction before the National Assembly's budget review.", ja: "まだ確定前なので具体的な数値を申し上げるのは慎重にならざるを得ませんが、国会予算審議前までには方向性を確定する予定です。", zh: "由于还未最终确定，具体数字方面我不便贸然透露，但计划在国会预算审议之前确定方向。" },
      { speaker: "기자", kr: "환자 단체들이 계속 지켜보고 있다는 점, 참고해 주시길 바랍니다.", en: "I hope you'll keep in mind that patient advocacy groups are continuing to watch this closely.", ja: "患者団体がずっと見守っているという点、参考にしていただければと思います。", zh: "希望您能记住，患者团体一直在密切关注此事。" },
    ],
  },
  {
    id: "hospital-c2y-overdiagnosis",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Debating overdiagnosis in screening programs", ja: "検診プログラムにおける過剰診断をめぐる議論", zh: "关于筛查项目中过度诊断的辩论" },
    lines: [
      { speaker: "역학전문가", kr: "국가 건강검진 프로그램이 확대되면서 과잉진단 문제도 함께 논의될 필요가 있다고 봅니다.", en: "As the national health screening program expands, I think the issue of overdiagnosis needs to be discussed alongside it.", ja: "国家健康診断プログラムが拡大するにつれ、過剰診断の問題も一緒に議論される必要があると思います。", zh: "随着国家健康体检项目的扩大，我认为也需要一并讨论过度诊断的问题。" },
      { speaker: "임상의", kr: "조기 발견이 생존율을 높인다는 건 확립된 사실 아닌가요? 과잉진단을 지나치게 강조하면 검진 자체를 꺼리게 만들 위험이 있어요.", en: "Isn't it an established fact that early detection improves survival rates? Overemphasizing overdiagnosis risks discouraging screening altogether.", ja: "早期発見が生存率を高めるというのは確立された事実じゃないですか？過剰診断をあまり強調すると検診自体を敬遠させる危険があります。", zh: "早期发现能提高生存率不是已经确定的事实吗？过分强调过度诊断，有可能让人干脆回避体检本身。" },
      { speaker: "역학전문가", kr: "생존율 향상이 반드시 조기 발견 덕분만은 아니라는 게 문제예요. 진행하지 않았을 병변까지 발견해서 치료로 이어지는 경우가 상당수 보고되고 있거든요.", en: "The problem is that improved survival isn't necessarily due to early detection alone. A considerable number of cases are reported where lesions that would never have progressed are detected and lead to unnecessary treatment.", ja: "生存率向上が必ずしも早期発見のおかげだけではないというのが問題です。進行しなかったはずの病変まで発見して治療につながるケースがかなり報告されているんです。", zh: "问题在于，生存率的提高并不一定完全归功于早期发现。相当多的病例报告显示，那些原本不会恶化的病变也被发现并进行了治疗。" },
      { speaker: "임상의", kr: "그렇다고 해도 개별 의사가 어떤 병변이 진행할지 안 할지를 사전에 구별할 방법이 마땅치 않잖아요.", en: "Even so, there's no reliable way for an individual physician to distinguish beforehand which lesions will progress and which won't.", ja: "だとしても個々の医師がどの病変が進行するかしないかを事前に見分ける方法がないじゃないですか。", zh: "即便如此，单个医生也没有可靠的方法事先判断哪些病变会恶化、哪些不会。" },
      { speaker: "역학전문가", kr: "그래서 저는 획일적인 전수 검진보다 위험군에 따른 차등 검진 전략이 더 합리적이라고 주장하는 겁니다.", en: "That's exactly why I'm arguing that a risk-stratified screening strategy makes more sense than a uniform, blanket screening approach.", ja: "だから私は画一的な全数検診より、リスク群に応じた差等検診戦略の方が合理的だと主張しているんです。", zh: "所以我才主张，比起一刀切的全员筛查，按风险人群分级的差异化筛查策略更合理。" },
      { speaker: "임상의", kr: "이론적으로는 그럴듯하지만, 현장에서 위험군을 정교하게 나누는 게 현실적으로 가능할지 의문이에요.", en: "It sounds plausible in theory, but I question whether finely stratifying risk groups is realistically feasible in the field.", ja: "理論的にはもっともらしいですが、現場でリスク群を精密に分けることが現実的に可能なのか疑問です。", zh: "理论上听起来有道理，但我怀疑在实际操作中能否精确划分风险人群。" },
      { speaker: "역학전문가", kr: "완벽한 모델은 없겠지만, 적어도 현재의 획일적 접근보다는 개선의 여지가 크다고 봅니다.", en: "There's no perfect model, but I believe there's considerably more room for improvement than the current uniform approach.", ja: "完璧なモデルはないでしょうが、少なくとも現在の画一的なアプローチよりは改善の余地が大きいと思います。", zh: "不会有完美的模型，但至少比现在这种一刀切的方式，改善的空间要大得多。" },
      { speaker: "임상의", kr: "결국 이 논쟁도 근거 자료가 충분히 쌓이기 전까지는 평행선을 달릴 수밖에 없겠네요.", en: "In the end, this debate too is bound to remain at an impasse until enough evidence accumulates.", ja: "結局この論争も根拠資料が十分に蓄積されるまでは平行線をたどるしかなさそうですね。", zh: "看来这场争论也只能在证据充分积累之前，一直各说各话了。" },
      { speaker: "역학전문가", kr: "그래서 저희 연구팀이 장기 추적 코호트 연구를 제안하려고 준비 중입니다.", en: "That's why our research team is preparing to propose a long-term follow-up cohort study.", ja: "だから私たちの研究チームは長期追跡コホート研究を提案しようと準備中です。", zh: "所以我们研究团队正在准备提议开展一项长期随访队列研究。" },
    ],
  },
  {
    id: "hospital-c2y-disclosurecrisis",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Crisis meeting after disclosing a systemic error", ja: "システム上の欠陥公表後の緊急会議", zh: "披露系统性错误后的危机会议" },
    lines: [
      { speaker: "병원장", kr: "이번 투약 오류 사건이 단순 실수가 아니라 시스템상의 구조적 결함에서 비롯됐다는 내부 조사 결과가 나왔습니다.", en: "The internal investigation found that this medication-error incident stemmed not from a simple mistake, but from a structural flaw in the system.", ja: "今回の投薬ミス事件が単純な過失ではなく、システム上の構造的欠陥から生じたという内部調査結果が出ました。", zh: "内部调查结果显示，这次给药错误事件并非单纯的失误，而是源于系统上的结构性缺陷。" },
      { speaker: "품질관리팀장", kr: "전자처방 시스템에서 유사 약품명이 함께 뜨는 인터페이스 문제가 핵심 원인으로 지목되었습니다.", en: "The core cause was identified as an interface issue in the electronic prescribing system, where similarly named drugs appear together.", ja: "電子処方システムで類似薬品名が一緒に表示されるインターフェースの問題が核心原因として指摘されました。", zh: "核心原因被指认为电子处方系统的界面问题——相似药名会一起显示出来。" },
      { speaker: "병원장", kr: "그렇다면 이건 담당 간호사 개인의 과실로만 몰아갈 사안이 아니라는 거군요.", en: "Then this isn't something that can simply be blamed entirely on the individual nurse's fault.", ja: "それならこれは担当看護師個人の過失だけに押し付ける問題ではないということですね。", zh: "那这就不是可以单纯归咎于当班护士个人过失的事情了。" },
      { speaker: "품질관리팀장", kr: "그렇습니다. 다만 이 부분을 공개적으로 인정하면 병원의 법적 책임 범위도 함께 커질 수 있다는 우려가 있습니다.", en: "That's right. However, there's a concern that publicly acknowledging this could also broaden the scope of the hospital's legal liability.", ja: "そうです。ただこの部分を公に認めれば、病院の法的責任範囲も一緒に広がる恐れがあります。", zh: "是的。不过也有人担心，如果公开承认这一点，医院的法律责任范围可能也会随之扩大。" },
      { speaker: "병원장", kr: "책임을 회피하려다가 신뢰를 완전히 잃는 것보다는, 구조적 결함을 인정하고 재발 방지책을 함께 발표하는 게 맞다고 봅니다.", en: "Rather than trying to avoid responsibility and losing trust entirely, I believe it's right to acknowledge the structural flaw and announce prevention measures together.", ja: "責任を回避しようとして信頼を完全に失うより、構造的欠陥を認めて再発防止策を一緒に発表するのが正しいと思います。", zh: "与其想逃避责任却彻底失去信任，我认为承认结构性缺陷、同时公布防止再发生的对策才是正确做法。" },
      { speaker: "품질관리팀장", kr: "동의합니다. 다만 법무팀과 사전에 표현 수위를 조율해서, 사실관계와 책임 인정의 경계를 명확히 해야 할 것 같습니다.", en: "I agree. But I think we need to coordinate the wording with the legal team beforehand, to clearly separate the factual record from the acknowledgment of responsibility.", ja: "同意します。ただ法務チームと事前に表現のレベルを調整して、事実関係と責任認定の境界を明確にする必要があると思います。", zh: "我同意。不过需要事先和法务团队协调好措辞尺度，明确划清事实陈述和责任认定之间的界限。" },
      { speaker: "병원장", kr: "환자 가족에게는 언론 발표 이전에 저희가 먼저 직접 설명드리는 게 도리라고 생각합니다.", en: "I think it's only right that we personally explain this to the patient's family ourselves before the press announcement.", ja: "患者ご家族には報道発表の前に私たちが先に直接説明するのが筋だと思います。", zh: "我认为，在向媒体公布之前，我们应该先亲自向患者家属做出说明，这才合乎道理。" },
      { speaker: "품질관리팀장", kr: "오늘 중으로 면담 일정을 잡고, 재발 방지 대책의 구체적인 초안도 함께 준비하겠습니다.", en: "I'll arrange a meeting with them today and also prepare a concrete draft of the recurrence-prevention plan.", ja: "今日中に面談の日程を組み、再発防止策の具体的な草案も一緒に準備します。", zh: "我今天之内会安排好会面时间，同时准备好防止再发生对策的具体草案。" },
      { speaker: "병원장", kr: "이번 일을 계기로 시스템 전반을 재점검하는 계기로 삼읍시다.", en: "Let's use this incident as an opportunity to thoroughly re-examine the system as a whole.", ja: "今回のことを機に、システム全般を再点検する契機にしましょう。", zh: "就以这次事件为契机，全面重新审视整个系统吧。" },
    ],
  },
  {
    id: "hospital-c2y-consentwithdrawal",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Debate after a research subject withdraws consent", ja: "被験者の同意撤回をめぐる話し合い", zh: "研究受试者撤回同意后的讨论" },
    lines: [
      { speaker: "연구책임자", kr: "3상 시험 도중에 피험자 한 분이 돌연 동의를 철회하겠다는 의사를 밝혀 왔습니다.", en: "In the middle of the phase 3 trial, one subject has suddenly expressed intent to withdraw consent.", ja: "フェーズ3の試験の途中で、被験者お一人が突然同意を撤回する意向を示してきました。", zh: "在三期试验进行到一半时，一位受试者突然表示要撤回同意。" },
      { speaker: "임상연구간호사", kr: "사유를 여쭤봤더니, 부작용 자체보다는 언론에 보도된 다른 임상시험 사고 소식에 불안감을 느꼈다고 하시더라고요.", en: "When I asked the reason, she said it wasn't the side effects themselves, but rather anxiety triggered by news coverage of a different clinical trial incident.", ja: "理由を伺ったところ、副作用自体よりも報道された別の臨床試験事故のニュースに不安を感じたそうです。", zh: "问了原因，她说与其说是不良反应本身，不如说是因为看到媒体报道的另一起临床试验事故新闻而感到不安。" },
      { speaker: "연구책임자", kr: "이해는 가지만, 이 시점에서 이탈하시면 통계적 검정력에 영향을 줄 수 있어서 걱정이네요.", en: "I understand, but if she withdraws at this point, it could affect the statistical power, which is concerning.", ja: "理解はできますが、この時点で離脱されると統計的検出力に影響が出る恐れがあって心配です。", zh: "我能理解，但这个时候退出的话，可能会影响到统计检验效力，这让人担心。" },
      { speaker: "임상연구간호사", kr: "그래도 동의 철회는 절대적인 권리이니, 저희가 통계적 부담을 이유로 설득을 강요할 수는 없는 거잖아요.", en: "Still, withdrawal of consent is an absolute right, so we can't pressure her to stay just because of our statistical concerns.", ja: "それでも同意撤回は絶対的な権利なので、統計的な負担を理由に説得を強要することはできませんよね。", zh: "但撤回同意是绝对的权利，我们不能以统计负担为由强行说服她留下。" },
      { speaker: "연구책임자", kr: "물론입니다. 다만 우려하시는 부분에 대해 정확한 정보를 다시 안내해 드리는 것까지는 괜찮겠죠.", en: "Of course. But it should still be fine to give her accurate information again regarding what she's worried about.", ja: "もちろんです。ただ心配されている部分について正確な情報を改めてご案内することまでは問題ないでしょう。", zh: "当然。不过针对她担心的部分，再次向她提供准确信息应该没问题吧。" },
      { speaker: "임상연구간호사", kr: "그 정도는 필요하다고 봐요. 다만 최종 결정은 전적으로 본인 의사에 맡겨야 하고요.", en: "I think that much is necessary. But the final decision has to be left entirely up to her.", ja: "その程度は必要だと思います。ただ最終決定は完全にご本人の意思に委ねるべきです。", zh: "我觉得这个程度是必要的。不过最终决定还是必须完全交由她本人决定。" },
      { speaker: "연구책임자", kr: "이번 이탈이 다른 피험자들에게도 영향을 줄 수 있으니, 전체 공지 방식도 신중하게 정해야겠어요.", en: "Since this withdrawal could also affect other subjects, we'll need to carefully decide how to communicate it more broadly as well.", ja: "今回の離脱が他の被験者にも影響を与える可能性があるので、全体への通知方法も慎重に決める必要がありますね。", zh: "这次退出可能会影响到其他受试者，所以整体的通知方式也需要慎重决定。" },
      { speaker: "임상연구간호사", kr: "개별 정보는 철저히 비밀로 하고, 전체적인 안전성 지표만 요약해서 공유하는 게 좋을 것 같아요.", en: "I think it would be best to keep individual information strictly confidential and share only a summary of the overall safety indicators.", ja: "個別情報は徹底的に秘密にし、全体的な安全性指標だけを要約して共有するのがいいと思います。", zh: "我觉得最好把个人信息严格保密，只对整体安全性指标进行汇总分享。" },
      { speaker: "연구책임자", kr: "동의합니다. IRB에도 이번 사례를 보고해서 절차상 문제가 없었는지 확인받아야겠어요.", en: "I agree. We should also report this case to the IRB to confirm there was no issue with the procedure.", ja: "同意します。IRBにも今回の事例を報告して、手続き上問題がなかったか確認を受けなければなりません。", zh: "我同意。也应该把这个案例报告给IRB，确认程序上是否存在问题。" },
    ],
  },
  {
    id: "hospital-c2y-culturaltaboo",
    situationKey: "hospital",
    level: "C2",
    title: { en: "Commentary on cultural taboos around terminal illness", ja: "末期疾患をめぐる文化的タブーについての考察", zh: "关于晚期疾病文化禁忌的评论" },
    lines: [
      { speaker: "완화의료 전문의", kr: "우리 사회에서는 여전히 말기 진단을 환자 본인에게 직접 알리기를 꺼리는 경향이 뿌리 깊게 남아 있습니다.", en: "In our society, there's still a deeply rooted tendency to hesitate about directly informing the patient of a terminal diagnosis.", ja: "私たちの社会では、いまだに末期診断を患者本人に直接伝えることをためらう傾向が根深く残っています。", zh: "在我们的社会里，依然根深蒂固地存在着不愿直接告知患者本人晚期诊断结果的倾向。" },
      { speaker: "사회복지사", kr: "가족들은 대체로 환자가 희망을 잃을까 봐 진실을 숨기려고 하시더라고요. 저도 그 마음이 이해가 안 되는 건 아니에요.", en: "Families generally try to hide the truth for fear the patient will lose hope. I don't fail to understand that impulse either.", ja: "ご家族は大体患者が希望を失うのを恐れて真実を隠そうとされますね。私もその気持ちが分からないわけではありません。", zh: "家属大多是担心患者失去希望，才想隐瞒真相。这种心情我也不是不能理解。" },
      { speaker: "완화의료 전문의", kr: "문제는 그 선의가 오히려 환자에게서 남은 시간을 스스로 계획할 기회를 빼앗는다는 데 있어요.", en: "The problem is that this good intention actually deprives the patient of the opportunity to plan their own remaining time.", ja: "問題はその善意が、かえって患者から残された時間を自ら計画する機会を奪うということにあります。", zh: "问题在于，这种善意反而剥夺了患者自己规划所剩时间的机会。" },
      { speaker: "사회복지사", kr: "맞아요. 실제로 뒤늦게 진실을 알게 된 환자분들이 배신감을 토로하시는 경우도 적지 않았고요.", en: "That's true. There have been quite a few cases where patients, upon belatedly learning the truth, expressed a sense of betrayal.", ja: "そうですね。実際に遅れて真実を知った患者さんが裏切られた気持ちを訴えるケースも少なくありませんでした。", zh: "确实。实际上有不少患者是事后才得知真相，倾诉过被背叛的感觉。" },
      { speaker: "완화의료 전문의", kr: "그래서 저희는 가족 면담을 먼저 진행하되, 결국 고지 여부는 환자 본인의 의사를 우선하도록 설득하는 방향으로 접근하고 있어요.", en: "That's why our approach is to first hold a family meeting, but ultimately persuade them to prioritize the patient's own wishes on whether to disclose.", ja: "だから私たちは家族面談を先に行いつつ、結局告知の可否は患者本人の意思を優先するよう説得する方向でアプローチしています。", zh: "所以我们的做法是先进行家庭会谈，但最终会朝着说服家属尊重患者本人意愿的方向来处理是否告知的问题。" },
      { speaker: "사회복지사", kr: "다만 문화적 맥락을 완전히 무시할 수도 없잖아요. 특히 연세 드신 어르신들은 침묵 속에서 존엄을 지킨다고 여기시는 경우도 있으니까요.", en: "Still, we can't entirely ignore the cultural context either. Especially for elderly patients, some feel that preserving dignity means maintaining silence.", ja: "ただ文化的背景を完全に無視することもできませんよね。特にご高齢の方は沈黙の中で尊厳を守ると考えられる場合もありますから。", zh: "不过也不能完全无视文化背景。尤其是高龄的长辈，有些人认为在沉默中才是守护尊严的方式。" },
      { speaker: "완화의료 전문의", kr: "그 지점이 참 어려워요. 서구식 자기결정권 모델을 그대로 이식하는 게 능사는 아니라는 거죠.", en: "That's exactly the difficult part. Simply transplanting the Western model of autonomy wholesale isn't necessarily the right answer.", ja: "その点が本当に難しいです。西洋式の自己決定権モデルをそのまま移植することが万能ではないということです。", zh: "这一点确实很难。把西方式的自主决定权模式原封不动地照搬过来，并不一定是万全之策。" },
      { speaker: "사회복지사", kr: "결국 각 가정의 문화와 환자 개인의 성향을 함께 고려하는 균형점을 찾아야겠네요.", en: "In the end, we need to find a balance that takes into account both each family's culture and the individual patient's disposition.", ja: "結局それぞれの家庭の文化と患者個人の性向を共に考慮するバランス点を見つけなければなりませんね。", zh: "看来最终需要找到一个平衡点，同时考虑每个家庭的文化和患者个人的性格倾向。" },
      { speaker: "완화의료 전문의", kr: "그래서 저희 병원도 획일적인 매뉴얼 대신 사례별 상담 체계를 강화하는 쪽으로 방향을 잡았어요.", en: "That's why our hospital has also decided to strengthen a case-by-case counseling system instead of relying on a one-size-fits-all manual.", ja: "だから私たちの病院も画一的なマニュアルの代わりに、事例別相談体制を強化する方向に舵を切りました。", zh: "所以我们医院也决定，与其依赖一刀切的手册，不如朝着加强个案化咨询体系的方向努力。" },
    ],
  },
];

export const HOSPITAL_C_QUIZZES: Record<string, DialogueQuiz> = {
  "hospital-c1y-reform": {
    q: "According to Doctor 2, what factor beyond reimbursement rates contributes to doctors avoiding essential specialties?",
    opts: ["Lack of hospital beds", "Malpractice-litigation burden and workload intensity", "Insufficient medical school seats", "Poor public transportation to hospitals"],
    ans: 1,
  },
  "hospital-c1y-hedging": {
    q: "What does the doctor say cannot yet be determined about the imaging findings?",
    opts: ["The patient's blood type", "Whether the finding is malignant or benign", "The cost of treatment", "Which hospital department will treat the patient"],
    ans: 1,
  },
  "hospital-c1y-burnout": {
    q: "What does the senior doctor identify as a classic sign of burnout in the resident?",
    opts: ["Frequent tardiness", "Emotional numbness while treating patients", "Refusing night shifts", "Arguing with nurses"],
    ans: 1,
  },
  "hospital-c1y-budgetcuts": {
    q: "According to the administrator, what is excluded from the ten percent budget cut?",
    opts: ["Office supplies", "Essential medical supplies", "Consumable equipment", "Staff training budgets"],
    ans: 1,
  },
  "hospital-c1y-bioethics": {
    q: "What distinction does Student 2 draw between an adult refusing a transfusion and a minor's parents refusing one?",
    opts: ["There is no meaningful difference between the two", "Courts have intervened to prioritize a child's right to life in the minor's case", "Minors always have final say over their own treatment", "Religious objections apply only to adults"],
    ans: 1,
  },
  "hospital-c1y-billingprobe": {
    q: "What solution does the billing office manager describe to prevent future non-covered-item complaints?",
    opts: ["Removing all non-covered items from services", "An electronic consent system with real-time notification", "Hiring more billing staff", "Printing paper brochures for patients"],
    ans: 1,
  },
  "hospital-c1y-mentalhealthgap": {
    q: "What does the doctor offer to do to help the patient's mother understand the treatment?",
    opts: ["Write a formal letter to her", "Explain it directly if she comes to the next appointment", "Refer her to a different specialist", "Send her printed research articles"],
    ans: 1,
  },
  "hospital-c1y-fundingpitch": {
    q: "Why does the foundation representative want to wait before finalizing their funding amount?",
    opts: ["They doubt the phase 2 results", "They want to see the results of the government research grant application first", "The researcher hasn't submitted a proposal yet", "The foundation's board has been dissolved"],
    ans: 1,
  },
  "hospital-c1y-understaffing": {
    q: "What do the nurses decide to do about the understaffing problem?",
    opts: ["Quit their jobs immediately", "Compile staffing data to present at the next department meeting", "Ignore it since nothing can be done", "File individual complaints only"],
    ans: 1,
  },
  "hospital-c2y-triagedebate": {
    q: "What is the central point of contention between the two department heads?",
    opts: ["Whether to hire more emergency staff", "Whether current overcrowding should be treated as equivalent to a disaster scenario for triage purposes", "Whether to close the emergency department", "Whether patients should pay higher fees"],
    ans: 1,
  },
  "hospital-c2y-epidemiology": {
    q: "What does the health official say may have contributed to the outbreak spreading faster than expected?",
    opts: ["A shorter-than-expected incubation period", "A vaccine shortage", "Public non-compliance with masks", "A delay in laboratory testing equipment"],
    ans: 0,
  },
  "hospital-c2y-mediaethics": {
    q: "What compromise do the reporter and editor agree on regarding the story?",
    opts: ["Withhold the story entirely", "Disclose the hospital's name but keep individual staff identities private", "Publish only anonymous sources", "Name both the hospital and the individual staff involved"],
    ans: 1,
  },
  "hospital-c2y-airesearch": {
    q: "What compromise approach do the two doctors converge on regarding the AI diagnostic system?",
    opts: ["Reject the AI system entirely", "Use AI as an auxiliary tool within a dual-reading system, with regular error review", "Replace all radiologists with AI immediately", "Use AI only for administrative scheduling"],
    ans: 1,
  },
  "hospital-c2y-rareconsent": {
    q: "What does the physician say about reversing the experimental treatment if severe side effects occur?",
    opts: ["Full recovery is guaranteed", "Administration can be stopped and switched to symptomatic treatment, but full reversal isn't guaranteed", "There is no way to stop the treatment once started", "The hospital will not treat any resulting side effects"],
    ans: 1,
  },
  "hospital-c2y-priorityfunding": {
    q: "How does the health official ultimately respond to the claim that rare-disease funding is effectively frozen after accounting for inflation?",
    opts: ["Denies there is any validity to the claim", "Admits partial validity and says they're consulting on a real increase for next year's budget", "Refuses to comment further", "Blames patient advocacy groups for the shortfall"],
    ans: 1,
  },
  "hospital-c2y-overdiagnosis": {
    q: "What alternative to uniform blanket screening does the epidemiologist propose?",
    opts: ["Eliminating all screening programs", "A risk-stratified screening strategy based on risk groups", "Screening only patients over 65", "Doubling the frequency of current screenings for everyone"],
    ans: 1,
  },
  "hospital-c2y-disclosurecrisis": {
    q: "What did the internal investigation identify as the core cause of the medication error?",
    opts: ["A single nurse's personal negligence", "An interface issue in the electronic prescribing system showing similarly named drugs together", "A shortage of medication stock", "Patient noncompliance"],
    ans: 1,
  },
  "hospital-c2y-consentwithdrawal": {
    q: "Why did the trial subject want to withdraw consent?",
    opts: ["She experienced severe side effects from the drug", "News coverage of a different clinical trial incident made her anxious", "She moved to another city", "She was never given informed consent originally"],
    ans: 1,
  },
  "hospital-c2y-culturaltaboo": {
    q: "What is the palliative care specialist's main concern about withholding a terminal diagnosis from the patient?",
    opts: ["It violates hospital billing codes", "It deprives the patient of the chance to plan their remaining time themselves", "It is illegal in all cases", "It increases hospital costs"],
    ans: 1,
  },
};
