import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Hotel situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const HOTEL_C_EXPANSION: Dialogue[] = [
  {
    id: "hotel-c1y-viral",
    situationKey: "hotel",
    level: "C1",
    title: "Handling a viral complaint",
    lines: [
      { speaker: "총지배인", kr: "어제 올라온 게시물이 벌써 조회수 십만을 넘었다고요?", en: "The post that went up yesterday has already crossed a hundred thousand views?" },
      { speaker: "홍보팀장", kr: "네, 객실 위생 문제를 지적한 영상인데 반응이 예상보다 훨씬 격해요.", en: "Yes, it's a video pointing out a room hygiene issue, and the reaction is far more intense than expected." },
      { speaker: "총지배인", kr: "일단 사실 관계부터 확인해야겠네요. 해당 객실 청소 기록 좀 뽑아 주시겠어요?", en: "We need to verify the facts first. Could you pull the cleaning log for that room?" },
      { speaker: "홍보팀장", kr: "이미 확인했는데, 담당 직원이 실수로 체크리스트 항목 하나를 빠뜨린 게 맞더라고요.", en: "I already checked, and it turns out the staff member did miss one item on the checklist by mistake." },
      { speaker: "총지배인", kr: "그렇다면 변명보다는 인정하고 사과하는 쪽으로 가야겠죠. 재발 방지 대책도 함께 발표하고요.", en: "Then rather than making excuses, we should acknowledge it and apologize, and announce prevention measures at the same time." },
      { speaker: "홍보팀장", kr: "손님께는 개별적으로 연락드려서 숙박료 환불과 함께 진심 어린 사과를 전하겠습니다.", en: "I'll contact the guest individually to offer a refund along with a sincere apology." },
      { speaker: "총지배인", kr: "댓글 반응도 계속 모니터링해 주시고, 필요하면 청소 프로세스 전체를 재점검합시다.", en: "Please keep monitoring the comments too, and if needed, let's review the entire cleaning process." },
      { speaker: "홍보팀장", kr: "네, 이번 일을 계기로 체크리스트를 이중 확인 체계로 바꾸는 게 어떨까 싶습니다.", en: "Yes, I think this incident is a good opportunity to switch the checklist to a double-verification system." },
      { speaker: "총지배인", kr: "좋은 생각이에요. 위기를 개선의 기회로 삼는 게 결국 신뢰 회복의 지름길이니까요.", en: "Good idea. Turning a crisis into an opportunity for improvement is ultimately the shortcut to rebuilding trust." },
    ],
  },
  {
    id: "hotel-c1y-dynamicpricing",
    situationKey: "hotel",
    level: "C1",
    title: "Debating dynamic pricing",
    lines: [
      { speaker: "수익관리팀장", kr: "성수기 요금을 실시간 수요에 맞춰 올리는 게 업계 표준이 된 지 오래예요.", en: "Raising rates in real time to match demand during peak season has long been the industry standard." },
      { speaker: "지배인", kr: "이해는 하지만, 예약 직후에 가격이 두 배로 뛰는 걸 본 손님 입장에서는 배신감을 느낄 수밖에 없죠.", en: "I understand, but from a guest's perspective who sees the price double right after booking, they can't help but feel betrayed." },
      { speaker: "수익관리팀장", kr: "그건 오해예요. 이미 확정된 예약의 요금이 바뀌는 게 아니라, 남은 객실에만 적용되는 거니까요.", en: "That's a misunderstanding. It's not that the rate of an already confirmed booking changes; it only applies to the remaining rooms." },
      { speaker: "지배인", kr: "그렇다 해도 소비자 입장에서는 그 구조를 정확히 이해하기 어려워요. 투명성이 부족하다는 비판이 나올 만하죠.", en: "Even so, it's hard for consumers to understand that structure precisely. It's understandable that criticism about lack of transparency arises." },
      { speaker: "수익관리팀장", kr: "그럼 요금 변동 폭에 상한선을 두고, 예약 화면에 안내 문구를 명시하는 방향은 어떨까요?", en: "Then how about capping the range of the rate fluctuation and clearly stating a notice on the booking page?" },
      { speaker: "지배인", kr: "그 정도 타협이면 손님들도 납득할 수 있을 것 같아요. 다만 지역 축제 기간처럼 극단적인 경우는 예외를 둬야겠죠.", en: "With that level of compromise, I think guests could accept it. Though we should make an exception for extreme cases like local festival periods." },
      { speaker: "수익관리팀장", kr: "맞아요. 결국 수익과 신뢰 사이에서 균형점을 찾는 게 관건이니까요.", en: "Right. In the end, finding the balance point between revenue and trust is the key issue." },
      { speaker: "지배인", kr: "이번 안을 경영진에 제안해 보죠. 장기적으로는 이게 더 지속 가능한 전략일 겁니다.", en: "Let's propose this plan to management. In the long run, this will be the more sustainable strategy." },
    ],
  },
  {
    id: "hotel-c1y-anonymouscritic",
    situationKey: "hotel",
    level: "C1",
    title: "The anonymous critic's review",
    lines: [
      { speaker: "지배인", kr: "그 평론가가 우리 호텔에 묵었다는 걸 나중에야 알았다는 게 좀 씁쓸하네요.", en: "It's a bit bitter that we only found out afterward that critic had stayed at our hotel." },
      { speaker: "프런트팀장", kr: "익명으로 예약했으니 알아챌 방법이 없었죠. 그런데 리뷰 내용이 생각보다 날카롭더라고요.", en: "Since they booked anonymously, there was no way to notice. But the review content was sharper than expected." },
      { speaker: "지배인", kr: "체크인 대기 시간이 길었다는 지적은 뼈아프네요. 실제로 그날 프런트 인력이 부족했잖아요.", en: "The point about the long check-in wait time really stings. We actually were short-staffed at the front desk that day." },
      { speaker: "프런트팀장", kr: "맞아요. 다만 조식 메뉴 구성에 대한 칭찬은 저희에게 힘이 되는 부분이었어요.", en: "True. Though the praise for the breakfast menu composition was encouraging for us." },
      { speaker: "지배인", kr: "비판을 방어적으로만 받아들이지 말고, 인력 배치 시스템을 근본적으로 재검토해 봅시다.", en: "Instead of just taking the criticism defensively, let's fundamentally review the staffing system." },
      { speaker: "프런트팀장", kr: "성수기 피크 시간대에 임시 인력을 투입하는 방안을 검토해 보겠습니다.", en: "I'll look into deploying temporary staff during peak hours in busy season." },
      { speaker: "지배인", kr: "그리고 이 리뷰를 팀 전체와 공유해서, 불편함을 데이터로 바꾸는 계기로 삼읍시다.", en: "And let's share this review with the whole team, turning discomfort into data as a learning opportunity." },
      { speaker: "프런트팀장", kr: "동의합니다. 익명의 평가라도 진심 어린 관찰이라면 겸허히 받아들여야죠.", en: "Agreed. Even an anonymous evaluation should be humbly accepted if it's a sincere observation." },
    ],
  },
  {
    id: "hotel-c1y-corporatecontract",
    situationKey: "hotel",
    level: "C1",
    title: "Negotiating a corporate rate contract",
    lines: [
      { speaker: "영업팀장", kr: "귀사 직원들의 연간 숙박 건수를 고려하면, 저희 쪽에서 상당한 할인율을 제시할 수 있습니다.", en: "Considering your employees' annual stay volume, we can offer a considerable discount rate." },
      { speaker: "구매담당자", kr: "구체적으로 어느 정도까지 가능할까요? 다른 체인에서는 이미 이십 퍼센트를 제안받았거든요.", en: "How much specifically would be possible? We've already been offered twenty percent by another chain." },
      { speaker: "영업팀장", kr: "저희도 그 수준까지는 맞출 수 있습니다만, 대신 연간 최소 예약 건수를 보장해 주셔야 합니다.", en: "We can match that level too, but in exchange you'd need to guarantee a minimum number of annual bookings." },
      { speaker: "구매담당자", kr: "최소 건수를 채우지 못할 경우 위약금이 발생하는 조항이라면 신중하게 검토해야겠네요.", en: "If there's a penalty clause for failing to meet the minimum count, we'd need to review it carefully." },
      { speaker: "영업팀장", kr: "위약금보다는 다음 해 할인율을 소폭 조정하는 방식으로 유연하게 운영하고 있습니다.", en: "Rather than a penalty, we operate flexibly by slightly adjusting the following year's discount rate." },
      { speaker: "구매담당자", kr: "그렇다면 부담이 훨씬 덜하겠네요. 대신 취소 수수료 면제 조항도 포함해 주실 수 있나요?", en: "That would be much less burdensome. In exchange, could you include a clause waiving cancellation fees?" },
      { speaker: "영업팀장", kr: "예약 하루 전 취소까지는 면제해 드리겠습니다. 초안 계약서를 다음 주까지 보내드리죠.", en: "We'll waive it for cancellations up to a day before. I'll send you a draft contract by next week." },
      { speaker: "구매담당자", kr: "좋습니다. 법무팀 검토를 거쳐 최종 서명 일정을 잡도록 하죠.", en: "Good. We'll go through legal review and set a schedule for the final signing." },
    ],
  },
  {
    id: "hotel-c1y-housekeepinglabor",
    situationKey: "hotel",
    level: "C1",
    title: "Labor conditions for housekeeping",
    lines: [
      { speaker: "노조대표", kr: "객실 정비 인원이 하루에 처리하는 객실 수가 업계 평균보다 많다는 통계가 나왔습니다.", en: "Statistics show the number of rooms each housekeeping staff processes per day exceeds the industry average." },
      { speaker: "인사팀장", kr: "저희도 그 자료를 검토했습니다. 다만 다른 호텔 대비 시급이 더 높다는 점도 고려해야 하지 않을까요?", en: "We've reviewed that data too. But shouldn't we also consider that our hourly wage is higher than other hotels?" },
      { speaker: "노조대표", kr: "임금이 높은 건 감사하지만, 신체적 부담이 누적되면 결국 장기 근속에 악영향을 줍니다.", en: "We're grateful the wage is higher, but if physical strain accumulates, it ultimately hurts long-term retention." },
      { speaker: "인사팀장", kr: "일리 있는 말씀이에요. 객실당 배정 시간을 늘리는 대신 인력을 추가 채용하는 방안을 검토해 보겠습니다.", en: "That's a fair point. We'll consider hiring additional staff instead of just extending the allotted time per room." },
      { speaker: "노조대표", kr: "채용도 좋지만, 무거운 침구를 다루는 작업에는 보조 장비 도입도 함께 논의됐으면 합니다.", en: "Hiring is good, but I'd like the introduction of assistive equipment for handling heavy bedding to be discussed too." },
      { speaker: "인사팀장", kr: "타당한 제안입니다. 다음 분기 예산에 관련 장비 도입 비용을 반영해 보죠.", en: "That's a reasonable proposal. Let's try to reflect the cost of introducing that equipment in next quarter's budget." },
      { speaker: "노조대표", kr: "그리고 이런 논의가 일회성으로 끝나지 않도록 정기 협의체를 구성했으면 합니다.", en: "And I'd like a regular consultation body to be formed so this discussion doesn't end as a one-off." },
      { speaker: "인사팀장", kr: "동의합니다. 매달 노사 간담회를 여는 걸로 정리하겠습니다.", en: "Agreed. Let's arrange to hold a monthly labor-management meeting." },
    ],
  },
  {
    id: "hotel-c1y-designphilosophy",
    situationKey: "hotel",
    level: "C1",
    title: "Explaining a design philosophy",
    lines: [
      { speaker: "기자", kr: "이 부티크 호텔을 설계하실 때 가장 신경 쓰신 부분이 무엇인지 여쭤봐도 될까요?", en: "May I ask what you focused on the most when designing this boutique hotel?" },
      { speaker: "오너", kr: "지역 전통 가옥의 구조를 현대적으로 재해석하는 데 가장 공을 들였습니다.", en: "I put the most effort into modernly reinterpreting the structure of traditional local houses." },
      { speaker: "기자", kr: "구체적으로 어떤 요소를 차용하셨는지 궁금합니다.", en: "I'm curious specifically which elements you borrowed." },
      { speaker: "오너", kr: "마당을 중심으로 방들이 배치되는 구조를 살려서, 손님들이 자연스럽게 공용 공간에서 마주치게 했어요.", en: "I preserved the structure where rooms are arranged around a central courtyard, so guests naturally encounter each other in the shared space." },
      { speaker: "기자", kr: "요즘 호텔들은 프라이버시를 극대화하는 추세인데, 오히려 반대 방향을 택하신 거네요.", en: "These days hotels tend to maximize privacy, so you've actually chosen the opposite direction." },
      { speaker: "오너", kr: "맞습니다. 저는 여행이 낯선 이들과의 우연한 교류에서 더 풍성해진다고 믿거든요.", en: "That's right. I believe travel becomes richer through unexpected exchanges with strangers." },
      { speaker: "기자", kr: "가구나 조명 선택에도 그런 철학이 반영되었나요?", en: "Was that philosophy reflected in the choice of furniture and lighting as well?" },
      { speaker: "오너", kr: "네, 지역 장인들과 협업해서 대량 생산품 대신 손으로 만든 조명을 곳곳에 배치했습니다.", en: "Yes, I collaborated with local artisans and placed handmade lighting throughout instead of mass-produced items." },
      { speaker: "기자", kr: "결국 이 호텔 자체가 지역 문화를 담는 그릇인 셈이군요.", en: "So in the end, this hotel itself is a vessel containing the local culture." },
      { speaker: "오너", kr: "정확합니다. 손님들이 떠날 때 이 지역을 조금이라도 이해하고 가셨으면 하는 바람입니다.", en: "Exactly. My hope is that guests leave having understood this region even a little." },
    ],
  },
  {
    id: "hotel-c1y-aiconcierge",
    situationKey: "hotel",
    level: "C1",
    title: "AI concierge changing the job",
    lines: [
      { speaker: "선임 컨시어지", kr: "요즘 도입된 인공지능 챗봇이 단순 문의는 거의 다 처리하고 있어요.", en: "The AI chatbot introduced recently is handling almost all the simple inquiries." },
      { speaker: "신입 컨시어지", kr: "그럼 저희가 할 일이 줄어드는 거 아닌가요? 조금 걱정되기도 해요.", en: "Then doesn't that mean our work is decreasing? I'm a bit worried too." },
      { speaker: "선임 컨시어지", kr: "저도 처음엔 그렇게 생각했는데, 오히려 복잡하고 미묘한 요청에 집중할 시간이 늘었더라고요.", en: "I thought so at first too, but it turns out I actually have more time to focus on complex and nuanced requests." },
      { speaker: "신입 컨시어지", kr: "예를 들면 어떤 요청이요?", en: "Like what kind of requests, for example?" },
      { speaker: "선임 컨시어지", kr: "가령 프러포즈를 준비하는 손님한테 그 사람 취향에 딱 맞는 레스토랑을 추천하는 일 같은 거요. 챗봇은 그런 섬세함까지는 못 읽거든요.", en: "For instance, recommending a restaurant tailored exactly to the taste of a guest preparing a proposal. A chatbot can't read that kind of subtlety." },
      { speaker: "신입 컨시어지", kr: "듣고 보니 오히려 우리 역할이 더 전문화되는 셈이네요.", en: "Now that I hear it, our role is actually becoming more specialized." },
      { speaker: "선임 컨시어지", kr: "맞아요. 반복 업무는 기계에 맡기고, 우리는 공감과 판단이 필요한 일에 집중하는 거죠.", en: "Right. We leave repetitive tasks to the machine and focus on work that requires empathy and judgment." },
      { speaker: "신입 컨시어지", kr: "그렇다면 두려워할 게 아니라 오히려 기회로 받아들여야겠네요.", en: "Then it's not something to fear but rather something to embrace as an opportunity." },
    ],
  },
  {
    id: "hotel-c1y-franchisedispute",
    situationKey: "hotel",
    level: "C1",
    title: "A franchise dispute unfolds",
    lines: [
      { speaker: "지점 오너", kr: "본사에서 리뉴얼 기준을 이렇게 갑자기 강제하는 건 계약 위반 소지가 있다고 봅니다.", en: "I think headquarters suddenly forcing these renovation standards this way may constitute a breach of contract." },
      { speaker: "본사 담당자", kr: "계약서 조항에 브랜드 이미지 유지를 위한 정기 리뉴얼 의무가 명시되어 있습니다.", en: "The contract clause explicitly states the obligation for periodic renovation to maintain brand image." },
      { speaker: "지점 오너", kr: "그 조항은 인정하지만, 비용 규모나 시행 시기에 대한 협의 절차가 전혀 없었잖아요.", en: "I acknowledge that clause, but there was no consultation process at all regarding the cost scale or timing of implementation." },
      { speaker: "본사 담당자", kr: "일방적으로 통보한 점은 저희도 아쉽게 생각합니다. 다만 경쟁 브랜드 대비 노후화가 심각한 상황이라서요.", en: "We also regret that it was a one-sided notice. But the deterioration compared to competing brands is quite serious." },
      { speaker: "지점 오너", kr: "그렇다면 최소한 비용 일부를 본사에서 분담하거나, 시행 기간을 유예해 주셔야 합니다.", en: "Then at the very least, headquarters should share part of the cost or give a grace period for implementation." },
      { speaker: "본사 담당자", kr: "비용 분담은 어렵지만, 시행 기간을 육 개월 유예하는 안은 검토해 볼 수 있을 것 같습니다.", en: "Cost-sharing is difficult, but I think we could review a proposal to grant a six-month grace period." },
      { speaker: "지점 오너", kr: "그 정도면 저희도 자금 계획을 다시 세울 여유가 생기겠네요.", en: "With that much, we'd have room to re-plan our funding as well." },
      { speaker: "본사 담당자", kr: "이번 사안을 계기로 앞으로는 정책 변경 전에 가맹점 협의체를 반드시 거치도록 하겠습니다.", en: "Taking this matter as an opportunity, we'll make sure to always go through the franchisee consultation body before any policy change from now on." },
    ],
  },
  {
    id: "hotel-c1y-diplomaticvip",
    situationKey: "hotel",
    level: "C1",
    title: "Mentoring through a VIP incident",
    lines: [
      { speaker: "신입 매니저", kr: "그 회원님이 예약된 스위트룸이 아니라며 크게 화를 내셨는데, 어떻게 대응해야 할지 몰라서 진땀을 뺐어요.", en: "That member got furious saying it wasn't the suite he'd booked, and I broke into a cold sweat not knowing how to respond." },
      { speaker: "선배 매니저", kr: "일단 잘 버텼어요. 그런 순간엔 사실 규명보다 감정을 먼저 인정해 주는 게 우선이에요.", en: "You held up well overall. In moments like that, acknowledging the emotion comes before establishing the facts." },
      { speaker: "신입 매니저", kr: "저는 예약 시스템 오류라는 걸 먼저 설명하려고 했는데, 오히려 역효과가 났던 것 같아요.", en: "I tried to explain the reservation system error first, but it seems to have had the opposite effect." },
      { speaker: "선배 매니저", kr: "맞아요. 설명은 감정이 가라앉은 다음에 해도 늦지 않아요. \"불편을 드려 죄송합니다\"부터 시작하는 게 좋았을 거예요.", en: "Right. Explanation isn't too late once the emotion has settled. It would've been better to start with 'I'm sorry for the inconvenience.'" },
      { speaker: "신입 매니저", kr: "그럼 이후에 업그레이드를 제안했던 건 적절한 대응이었나요?", en: "Then was offering an upgrade afterward an appropriate response?" },
      { speaker: "선배 매니저", kr: "타이밍은 좋았는데, 다음번엔 지배인 승인 없이 즉석에서 약속하지 않는 게 안전해요.", en: "The timing was good, but next time it's safer not to make an on-the-spot promise without the manager's approval." },
      { speaker: "신입 매니저", kr: "명심하겠습니다. 그런데 이런 손님들은 결국 어떻게 마음을 돌리시던가요?", en: "I'll keep that in mind. But how do guests like that end up changing their minds in the end?" },
      { speaker: "선배 매니저", kr: "진심이 느껴지는 대응을 받으면 대부분 누그러져요. 결국 사람 대 사람의 문제니까요.", en: "Most soften up when they receive a response where sincerity comes through. In the end, it's a person-to-person issue." },
    ],
  },
  {
    id: "hotel-c2y-viraldebate",
    situationKey: "hotel",
    level: "C2",
    title: "The ethics of viral outrage",
    lines: [
      { speaker: "기자", kr: "이번 사태를 보면서 소셜 미디어가 기업의 위기 대응 방식 자체를 근본적으로 바꿔놓았다는 생각이 듭니다.", en: "Watching this incident unfold, I find myself thinking that social media has fundamentally transformed how companies respond to crises." },
      { speaker: "총지배인", kr: "동의합니다. 예전 같으면 내부적으로 조용히 해결했을 사안이 이제는 몇 시간 만에 여론 재판대에 오르니까요.", en: "I agree. What used to be resolved quietly internally now ends up on the court of public opinion within hours." },
      { speaker: "기자", kr: "그런데 일각에서는 그런 즉각적인 공론화가 오히려 사실 확인보다 감정적 단죄를 부추긴다고 비판하기도 하죠.", en: "Some, however, criticize that such instant public discourse actually incites emotional condemnation rather than fact-checking." },
      { speaker: "총지배인", kr: "일리 있는 지적이에요. 저희도 이번에 진위를 채 파악하기도 전에 이미 여론의 판결이 내려진 상태였으니까요.", en: "That's a fair point. In our case too, public verdict had already been rendered before we could even establish the facts." },
      { speaker: "기자", kr: "그럼에도 불구하고 이런 압박이 결과적으로 기업의 투명성을 높이는 순기능도 있다고 보시나요?", en: "Nevertheless, do you think such pressure ultimately has a positive function of increasing corporate transparency?" },
      { speaker: "총지배인", kr: "역설적이게도 그렇습니다. 숨길 수 없다는 전제가 오히려 내부 관리를 더 철저하게 만들거든요.", en: "Ironically, yes. The premise that nothing can be hidden actually makes internal management more thorough." },
      { speaker: "기자", kr: "그렇다면 앞으로 호텔 업계 전반의 위기 관리 매뉴얼도 이런 흐름에 맞춰 재편되어야겠군요.", en: "Then going forward, the entire hotel industry's crisis management manuals should probably be restructured to fit this trend." },
      { speaker: "총지배인", kr: "맞습니다. 저희는 이미 실시간 모니터링 체계를 상시화하는 방향으로 조직을 개편하고 있습니다.", en: "That's right. We're already restructuring our organization to institutionalize a real-time monitoring system." },
      { speaker: "기자", kr: "결국 신뢰는 위기 이전이 아니라 위기를 다루는 방식에서 판가름 나는 셈이네요.", en: "In the end, trust is decided not before a crisis but in how the crisis is handled." },
    ],
  },
  {
    id: "hotel-c2y-pricingdebate",
    situationKey: "hotel",
    level: "C2",
    title: "The moral hazard of surge pricing",
    lines: [
      { speaker: "칼럼니스트", kr: "재난 상황에서조차 숙박 요금이 몇 배씩 뛰는 현상을 두고 시장 논리의 필연적 결과라고만 볼 수 있을까요?", en: "Even amid disaster situations, can the phenomenon of lodging rates spiking several times over be seen merely as an inevitable outcome of market logic?" },
      { speaker: "경제학자", kr: "수요와 공급의 원리로 보면 자연스러운 현상이지만, 재난이라는 특수성이 그 원리의 정당성을 흔든다고 봅니다.", en: "From the principle of supply and demand it's a natural phenomenon, but I think the special circumstance of disaster undermines the legitimacy of that principle." },
      { speaker: "칼럼니스트", kr: "그렇다면 평시의 성수기 요금 변동과 재난 시의 폭리는 어떻게 구분해야 할까요?", en: "Then how should we distinguish ordinary peak-season rate fluctuations from price gouging during disasters?" },
      { speaker: "경제학자", kr: "저는 소비자에게 선택의 여지가 있는지를 기준으로 삼아야 한다고 생각합니다. 대피처가 없는 상황이라면 그건 착취에 가깝죠.", en: "I think whether the consumer has any alternative should be the criterion. If there's no other shelter available, that's closer to exploitation." },
      { speaker: "칼럼니스트", kr: "업계에서는 인건비와 응급 대응 비용 상승을 근거로 요금 인상을 정당화하기도 하던데요.", en: "The industry sometimes justifies the rate hikes citing rising labor and emergency response costs, though." },
      { speaker: "경제학자", kr: "그 논리가 완전히 틀린 건 아니지만, 상한선 없는 가격 책정과는 별개의 문제로 다뤄야 합니다.", en: "That logic isn't entirely wrong, but it should be treated as a separate issue from pricing without any ceiling." },
      { speaker: "칼럼니스트", kr: "결국 법적 규제와 업계 자율 윤리 사이 어디쯤에서 균형점을 찾아야 한다는 말씀이시군요.", en: "So you're saying the balance must ultimately be found somewhere between legal regulation and industry self-imposed ethics." },
      { speaker: "경제학자", kr: "맞습니다. 시장의 효율성과 인간의 존엄성이 충돌할 때, 후자에 조금 더 무게를 두는 사회가 성숙한 사회라고 봅니다.", en: "Exactly. When market efficiency and human dignity collide, I believe a society that weighs the latter a bit more heavily is a mature one." },
      { speaker: "칼럼니스트", kr: "귀한 말씀 감사합니다. 이 논쟁은 앞으로도 계속될 것 같네요.", en: "Thank you for the valuable insight. It seems this debate will continue on." },
    ],
  },
  {
    id: "hotel-c2y-criticreflection",
    situationKey: "hotel",
    level: "C2",
    title: "The critic and the staff, after the review",
    lines: [
      { speaker: "평론가", kr: "익명성을 포기하고 이렇게 직접 뵙자고 한 건, 리뷰가 단순한 비판으로만 읽히지 않기를 바라서였습니다.", en: "The reason I gave up anonymity and asked to meet you directly like this was because I hoped the review wouldn't be read as mere criticism." },
      { speaker: "지배인", kr: "솔직히 처음 읽었을 때는 방어적인 감정이 앞섰습니다만, 다시 읽어보니 애정이 느껴지더라고요.", en: "Honestly, my first reaction when reading it was defensive, but reading it again, I could feel the affection behind it." },
      { speaker: "평론가", kr: "정확히 짚어주셨네요. 저는 문제를 지적하지 않는 리뷰는 결국 독자에게도, 업계에도 도움이 안 된다고 믿습니다.", en: "You've pinpointed it exactly. I believe a review that doesn't point out problems ultimately doesn't help either the reader or the industry." },
      { speaker: "지배인", kr: "다만 익명 평론이라는 형식 자체에 대한 논쟁도 있잖아요. 책임 소재가 불분명하다는 비판이요.", en: "Though there's also debate about the format of anonymous reviewing itself, criticism that accountability becomes unclear." },
      { speaker: "평론가", kr: "그 비판을 부정하진 않습니다. 다만 익명성이 있어야 업체의 눈치를 보지 않고 있는 그대로 경험할 수 있거든요.", en: "I don't deny that criticism. But anonymity is what allows me to experience things as they are without worrying about how the business will react." },
      { speaker: "지배인", kr: "이해합니다. 그런데 오늘처럼 직접 대화를 나누고 나니, 비판이 훨씬 건설적으로 다가오네요.", en: "I understand. But having had a direct conversation like today, the criticism feels far more constructive now." },
      { speaker: "평론가", kr: "저 역시 현장에서 직접 이야기를 들으니, 글로만 접했을 때보다 훨씬 입체적으로 상황을 이해하게 됐습니다.", en: "I too, having heard the story directly on-site, came to understand the situation much more three-dimensionally than through text alone." },
      { speaker: "지배인", kr: "다음번엔 익명이 아니라 이렇게 대화의 형태로 피드백을 주고받는 자리를 정기적으로 마련해보고 싶네요.", en: "Next time, rather than anonymously, I'd like to regularly arrange occasions to exchange feedback in this conversational form." },
      { speaker: "평론가", kr: "좋은 생각입니다. 다만 그 자리가 리뷰의 객관성을 해치지 않도록 경계는 유지해야겠죠.", en: "That's a good idea. Though we'll need to maintain boundaries so that such occasions don't compromise the review's objectivity." },
    ],
  },
  {
    id: "hotel-c2y-contractnegotiationtension",
    situationKey: "hotel",
    level: "C2",
    title: "Where corporate contracts get contentious",
    lines: [
      { speaker: "법무 자문", kr: "이 조항대로라면 귀사가 예약 건수를 채우지 못했을 때 사실상 일방적으로 불리한 위치에 놓이게 됩니다.", en: "Under this clause as written, your company would effectively be placed in a one-sidedly disadvantageous position if you fail to meet the booking count." },
      { speaker: "구매담당자", kr: "저도 그 부분이 걸립니다. 다만 할인율 자체는 매력적이라서 완전히 거절하기도 아쉬워요.", en: "I'm concerned about that part too. But the discount rate itself is attractive, so it's a shame to reject it entirely." },
      { speaker: "법무 자문", kr: "위약금 조항을 삭제하는 대신, 목표 미달 시 다음 해 할인율만 조정하는 안으로 역제안해 보시죠.", en: "Instead of a penalty clause, let's counter-propose an arrangement where only next year's discount rate is adjusted if the target isn't met." },
      { speaker: "구매담당자", kr: "그게 훨씬 합리적이네요. 그런데 호텔 측에서 그 제안을 순순히 받아들일까요?", en: "That's far more reasonable. But will the hotel side readily accept that proposal?" },
      { speaker: "법무 자문", kr: "받아들이지 않는다면, 그건 이 계약이 상호 이익보다 일방적 통제에 방점을 찍고 있다는 방증이겠죠.", en: "If they don't accept it, that would be evidence that this contract emphasizes one-sided control rather than mutual benefit." },
      { speaker: "구매담당자", kr: "날카로운 지적이네요. 그런 태도라면 다른 체인과의 협상 카드로도 활용할 수 있겠고요.", en: "That's a sharp point. With that attitude, we could also use it as leverage in negotiations with other chains." },
      { speaker: "법무 자문", kr: "협상이란 게 결국 어느 쪽이 아쉬운 소리를 덜 하느냐의 싸움이니까요.", en: "Negotiation, after all, is ultimately a battle over which side has to concede less." },
      { speaker: "구매담당자", kr: "말씀 감사합니다. 이 방향으로 수정안을 준비해서 다시 협상 테이블에 앉아보죠.", en: "Thank you. Let's prepare a revised proposal in this direction and sit at the negotiation table again." },
      { speaker: "법무 자문", kr: "네, 다만 최종 서명 전에는 반드시 저희 검토를 다시 거치시기 바랍니다.", en: "Yes, but please make sure to go through our review again before the final signing." },
    ],
  },
  {
    id: "hotel-c2y-laborstructural",
    situationKey: "hotel",
    level: "C2",
    title: "Structural roots of housekeeping strain",
    lines: [
      { speaker: "사회학자", kr: "호텔 청소 노동의 강도 문제는 단순히 개별 사업장의 처우 개선만으로는 해결되지 않는다고 봅니다.", en: "I don't think the problem of hotel housekeeping labor intensity can be resolved merely by individual workplaces improving conditions." },
      { speaker: "노조대표", kr: "구조적인 문제라는 말씀이시군요. 어떤 지점에서 그렇게 보시는 건가요?", en: "You mean it's a structural problem. On what basis do you see it that way?" },
      { speaker: "사회학자", kr: "온라인 예약 플랫폼의 수수료 구조가 호텔의 인건비 여력 자체를 압박하고 있거든요.", en: "The fee structure of online booking platforms itself is squeezing the room hotels have for labor costs." },
      { speaker: "노조대표", kr: "저희도 체감하는 부분입니다. 플랫폼 수수료가 오를 때마다 결국 그 부담이 현장 인력에게 전가되니까요.", en: "That's something we feel too. Every time platform fees rise, the burden ultimately gets passed down to the on-site workforce." },
      { speaker: "사회학자", kr: "그렇다면 정책적으로는 플랫폼 수수료 상한제와 최저 배정 시간 보장을 함께 논의해야 하지 않을까요?", en: "Then shouldn't policy discussions address a platform fee cap alongside a guaranteed minimum allotted time together?" },
      { speaker: "노조대표", kr: "동의합니다. 다만 업계에서는 그런 규제가 결국 소비자 요금 인상으로 이어질 거라고 반발할 텐데요.", en: "I agree. Though the industry will likely push back, arguing such regulation would ultimately lead to higher consumer rates." },
      { speaker: "사회학자", kr: "그 반발도 이해는 되지만, 노동자의 신체를 갈아 넣어 유지되는 저가 구조가 지속 가능하다고 보긴 어렵죠.", en: "I understand that pushback too, but it's hard to see a low-price structure sustained by grinding down workers' bodies as sustainable." },
      { speaker: "노조대표", kr: "결국 소비자, 노동자, 플랫폼 삼자가 비용을 나눠 지는 구조로 재설계되어야겠네요.", en: "In the end, it needs to be redesigned into a structure where consumers, workers, and platforms share the cost three ways." },
      { speaker: "사회학자", kr: "정확합니다. 그런 재설계 없이는 이번 논의도 또 한 번의 미봉책에 그칠 겁니다.", en: "Exactly. Without such a redesign, this discussion too will end up as just another stopgap measure." },
    ],
  },
  {
    id: "hotel-c2y-designjournalism",
    situationKey: "hotel",
    level: "C2",
    title: "Design philosophy under journalistic scrutiny",
    lines: [
      { speaker: "기자", kr: "지역 문화를 담는다는 취지는 아름답지만, 일각에서는 그것이 상업적 소비를 미화하는 포장에 불과하다고 지적합니다.", en: "The intent of embodying local culture is beautiful, but some point out it's merely packaging that beautifies commercial consumption." },
      { speaker: "오너", kr: "날카로운 지적이네요. 저 역시 그 경계가 늘 조심스럽습니다. 그래서 장인들과의 수익 배분 구조를 투명하게 공개하고 있어요.", en: "That's a sharp point. I too am always cautious about that boundary. That's why I openly disclose the revenue-sharing structure with the artisans." },
      { speaker: "기자", kr: "구체적으로 어떤 방식으로 배분하시나요?", en: "How exactly do you distribute it?" },
      { speaker: "오너", kr: "조명이나 가구가 판매될 때마다 일정 로열티가 제작자에게 돌아가도록 계약서에 명시해 두었습니다.", en: "I've specified in the contract that a certain royalty goes back to the maker each time a light fixture or piece of furniture is sold." },
      { speaker: "기자", kr: "그렇다면 이 공간은 전시라기보다는 지속적인 협업의 결과물에 가깝다고 봐도 될까요?", en: "Then could this space be seen as closer to the result of ongoing collaboration rather than an exhibition?" },
      { speaker: "오너", kr: "정확히 그렇습니다. 저는 이 호텔을 완성된 작품이 아니라 계속 진화하는 프로젝트로 여기고 있어요.", en: "Exactly right. I regard this hotel not as a finished work but as an ever-evolving project." },
      { speaker: "기자", kr: "그런 철학이 결국 손님들에게도 전달될까요, 아니면 그저 오너 개인의 만족에 그칠까요?", en: "Does that philosophy ultimately get conveyed to guests too, or does it end up as merely the owner's personal satisfaction?" },
      { speaker: "오너", kr: "전달되지 않는다면 실패한 겁니다. 다행히 많은 손님들이 체크아웃할 때 그 장인의 이름을 물어보시더라고요.", en: "If it isn't conveyed, then it's a failure. Fortunately, many guests ask for the artisan's name when checking out." },
      { speaker: "기자", kr: "그 질문 하나가 결국 이 공간이 제대로 작동하고 있다는 증거겠네요.", en: "That single question is ultimately proof that this space is working as intended." },
    ],
  },
  {
    id: "hotel-c2y-aijobdebate",
    situationKey: "hotel",
    level: "C2",
    title: "Will AI hollow out hospitality careers?",
    lines: [
      { speaker: "노동경제학자", kr: "호텔업계에서 인공지능 도입이 단순 업무를 대체하는 걸 넘어, 결국 신입 채용 자체를 줄이고 있다는 우려가 나옵니다.", en: "There are concerns that AI adoption in the hotel industry is going beyond replacing simple tasks and ultimately reducing entry-level hiring itself." },
      { speaker: "호텔 경영자", kr: "저희 경험으로는 오히려 반대입니다. 단순 응대를 기계가 맡으면서 직원들이 더 전문적인 역할로 이동하고 있어요.", en: "In our experience it's actually the opposite. As machines take over simple responses, staff are moving into more specialized roles." },
      { speaker: "노동경제학자", kr: "그건 이미 숙련된 인력에게는 맞는 이야기일 수 있지만, 애초에 그 경력을 쌓을 입구 자체가 좁아진다는 게 문제 아닐까요?", en: "That may hold true for already skilled staff, but isn't the problem that the entry point to build that experience in the first place is narrowing?" },
      { speaker: "호텔 경영자", kr: "일리 있는 지적입니다. 다만 저희는 신입을 단순 업무가 아니라 처음부터 손님 응대 훈련에 투입하는 쪽으로 방향을 틀었어요.", en: "That's a fair point. But we've shifted direction to put new hires into guest-service training from the start, rather than simple tasks." },
      { speaker: "노동경제학자", kr: "그렇다면 훈련 비용이 예전보다 훨씬 늘어났을 텐데, 그게 업계 전체로 확산될 수 있을까요?", en: "Then the training cost must have increased far more than before—can that spread across the industry as a whole?" },
      { speaker: "호텔 경영자", kr: "쉽지 않을 겁니다. 자본이 넉넉한 대형 체인이 아니라면 그런 전환이 부담스러울 수밖에 없죠.", en: "It won't be easy. Unless you're a large chain with ample capital, such a transition is bound to be burdensome." },
      { speaker: "노동경제학자", kr: "결국 기술 도입의 혜택이 대형 브랜드에 집중되고, 중소 숙박업은 도태될 위험이 있다는 말씀이시군요.", en: "So you're saying the benefits of technology adoption end up concentrated in large brands, while small and mid-sized lodging businesses risk being weeded out." },
      { speaker: "호텔 경영자", kr: "안타깝지만 그 가능성을 배제할 수 없습니다. 정책적으로 중소업체의 디지털 전환을 지원할 필요가 있어 보여요.", en: "Regrettably, that possibility can't be ruled out. It seems policy support is needed for the digital transition of smaller businesses." },
      { speaker: "노동경제학자", kr: "기술이 일자리를 없애느냐 바꾸느냐의 논쟁은 결국 누가 그 전환 비용을 감당하느냐의 문제로 귀결되는군요.", en: "The debate over whether technology eliminates or transforms jobs ultimately comes down to who bears the cost of that transition." },
    ],
  },
  {
    id: "hotel-c2y-franchisepower",
    situationKey: "hotel",
    level: "C2",
    title: "Power asymmetry in franchise disputes",
    lines: [
      { speaker: "산업 전문가", kr: "이번 리뉴얼 강제 사태는 프랜차이즈 계약 구조가 본질적으로 본사에 유리하게 설계돼 있다는 걸 보여주는 사례입니다.", en: "This forced-renovation incident is a case showing that franchise contract structures are inherently designed to favor headquarters." },
      { speaker: "가맹점 협회장", kr: "정확한 지적입니다. 계약 초기에는 매력적인 조건처럼 보이지만, 갱신 시점마다 가맹점의 협상력은 점점 약해지거든요.", en: "That's a precise observation. At the outset the terms look attractive, but the franchisee's bargaining power weakens with each renewal point." },
      { speaker: "산업 전문가", kr: "왜 그런 비대칭이 심화된다고 보시나요?", en: "Why do you think that asymmetry deepens?" },
      { speaker: "가맹점 협회장", kr: "브랜드를 이탈하면 그동안 쌓은 고객 데이터와 인지도를 전부 잃게 되니, 가맹점은 사실상 이탈이 불가능한 인질 상태가 됩니다.", en: "If you leave the brand, you lose all the customer data and recognition built up over time, so the franchisee ends up in a virtually hostage state, unable to leave." },
      { speaker: "산업 전문가", kr: "그렇다면 이 문제를 해결할 제도적 장치로 무엇을 제안하시겠습니까?", en: "Then what institutional mechanism would you propose to resolve this problem?" },
      { speaker: "가맹점 협회장", kr: "정책 변경 시 가맹점 과반 동의를 의무화하는 법 조항이 있어야 한다고 봅니다.", en: "I believe there needs to be a legal provision requiring majority franchisee consent for policy changes." },
      { speaker: "산업 전문가", kr: "본사 측에서는 그런 조항이 브랜드의 신속한 의사결정을 저해한다고 반발할 텐데요.", en: "Headquarters would likely push back, arguing such a clause hampers the brand's swift decision-making." },
      { speaker: "가맹점 협회장", kr: "신속함이 항상 정당성을 담보하지는 않습니다. 오히려 그 신속함이 누구의 희생 위에 세워졌는지를 물어야죠.", en: "Speed doesn't always guarantee legitimacy. Rather, we should ask whose sacrifice that speed was built upon." },
      { speaker: "산업 전문가", kr: "결국 이 논쟁은 계약의 자유와 구조적 불균형 사이의 오래된 긴장을 다시 보여주는 셈이군요.", en: "In the end, this debate is once again revealing the old tension between freedom of contract and structural imbalance." },
    ],
  },
  {
    id: "hotel-c2y-overtourismculture",
    situationKey: "hotel",
    level: "C2",
    title: "Overtourism and the erosion of place",
    lines: [
      { speaker: "문화인류학자", kr: "이 지역이 관광지로 뜨면서 정작 이곳을 지탱해 온 생활 문화 자체가 사라지고 있다는 게 아이러니합니다.", en: "It's ironic that as this area rises as a tourist spot, the very living culture that sustained it is disappearing." },
      { speaker: "숙박업 조합장", kr: "저희도 그 딜레마를 잘 압니다. 관광객이 오지 않으면 지역 경제가 무너지고, 오면 원래의 정체성이 흐려지니까요.", en: "We know that dilemma well too. If tourists don't come, the local economy collapses; if they do, the original identity blurs." },
      { speaker: "문화인류학자", kr: "그렇다면 숙박업계는 이 딜레마에 어떤 책임을 지고 있다고 보십니까?", en: "Then what responsibility do you think the lodging industry bears in this dilemma?" },
      { speaker: "숙박업 조합장", kr: "저희가 이 골목의 임대료 상승을 부추긴 측면은 부인할 수 없습니다. 그 점은 겸허히 인정해야죠.", en: "We can't deny that we've contributed to driving up rents in this alley. That's something we need to humbly acknowledge." },
      { speaker: "문화인류학자", kr: "인정을 넘어서 실질적인 대응이 필요할 텐데요. 예를 들면 어떤 방안이 가능할까요?", en: "Beyond acknowledgment, practical responses would be needed. What measures might be possible, for example?" },
      { speaker: "숙박업 조합장", kr: "숙박세 일부를 원주민 주거 지원 기금으로 돌리는 방안을 조합 차원에서 논의 중입니다.", en: "We're discussing at the association level a plan to redirect part of the lodging tax into a fund supporting original residents' housing." },
      { speaker: "문화인류학자", kr: "고무적인 시도네요. 다만 그런 기금이 실제로 원주민에게 도달하기까지는 행정적 신뢰가 관건일 겁니다.", en: "That's an encouraging attempt. Though administrative trust will be key to whether such a fund actually reaches original residents." },
      { speaker: "숙박업 조합장", kr: "맞습니다. 그래서 주민 대표가 직접 기금 운용에 참여하는 구조를 만들려고 합니다.", en: "Right. That's why we're trying to create a structure where resident representatives directly participate in fund management." },
      { speaker: "문화인류학자", kr: "결국 관광 산업이 지역을 잠식하는 게 아니라 함께 지탱하는 방식으로 진화할 수 있을지가 시험대에 오른 셈이군요.", en: "In the end, it's a test of whether the tourism industry can evolve to sustain the region together rather than encroach upon it." },
    ],
  },
];

export const HOTEL_C_QUIZZES: Record<string, DialogueQuiz> = {
  "hotel-c1y-viral": {
    q: "What did the hotel staff decide to do about the viral complaint?",
    opts: [
      "Deny the claim publicly and demand the video be removed",
      "Acknowledge the mistake, apologize, refund the guest, and improve the checklist",
      "Ignore the post since it would fade on its own",
      "Offer the guest a free upgrade without addressing the hygiene issue",
    ],
    ans: 1,
  },
  "hotel-c1y-dynamicpricing": {
    q: "What compromise did the manager propose regarding dynamic pricing?",
    opts: [
      "Eliminating dynamic pricing entirely",
      "Applying it only to loyalty members",
      "Capping the rate fluctuation and disclosing it clearly on the booking page",
      "Doubling prices only during local festivals",
    ],
    ans: 2,
  },
  "hotel-c1y-anonymouscritic": {
    q: "What specific criticism from the anonymous critic's review stung the manager the most?",
    opts: [
      "The breakfast menu was poor",
      "The check-in wait time was long due to understaffing",
      "The rooms were too small",
      "The staff were rude to guests",
    ],
    ans: 1,
  },
  "hotel-c1y-corporatecontract": {
    q: "What did the sales manager require in exchange for matching the twenty percent discount?",
    opts: [
      "A guarantee of a minimum number of annual bookings",
      "Payment of the full year upfront",
      "Exclusive use of only one hotel brand",
      "A non-negotiable five-year contract",
    ],
    ans: 0,
  },
  "hotel-c1y-housekeepinglabor": {
    q: "What did the HR manager agree to consider instead of simply extending time per room?",
    opts: [
      "Cutting wages to fund more staff",
      "Hiring additional staff and introducing assistive equipment",
      "Reducing the number of rooms cleaned per day without adding staff",
      "Outsourcing housekeeping entirely",
    ],
    ans: 1,
  },
  "hotel-c1y-designphilosophy": {
    q: "According to the owner, why are rooms arranged around a central courtyard?",
    opts: [
      "To maximize privacy for guests",
      "To reduce construction costs",
      "To let guests naturally encounter each other in shared space, unlike privacy-focused modern hotels",
      "Because it was required by local building codes",
    ],
    ans: 2,
  },
  "hotel-c1y-aiconcierge": {
    q: "How does the senior concierge say the AI chatbot has changed their role?",
    opts: [
      "It has made their job obsolete",
      "It handles simple inquiries, freeing them to focus on complex, nuanced requests",
      "It has increased their workload with technical troubleshooting",
      "It only assists guests who speak English",
    ],
    ans: 1,
  },
  "hotel-c1y-franchisedispute": {
    q: "What compromise did headquarters offer the franchise owner?",
    opts: [
      "Full cost-sharing for the renovation",
      "Cancellation of the renovation requirement",
      "A six-month grace period for the renovation timeline",
      "A permanent exemption from all future renewal standards",
    ],
    ans: 2,
  },
  "hotel-c1y-diplomaticvip": {
    q: "What lesson does the senior manager give about handling the angry VIP guest?",
    opts: [
      "Explain the technical error first before anything else",
      "Acknowledge the guest's emotion before explaining facts, and get approval before promising upgrades",
      "Always call security immediately",
      "Offer a full refund without discussion",
    ],
    ans: 1,
  },
  "hotel-c2y-viraldebate": {
    q: "According to the general manager, what paradoxical positive effect can social media pressure have?",
    opts: [
      "It reduces the need for internal audits",
      "It makes internal management more thorough because nothing can be hidden",
      "It eliminates the need for PR staff",
      "It guarantees guests will forgive mistakes faster",
    ],
    ans: 1,
  },
  "hotel-c2y-pricingdebate": {
    q: "What criterion does the economist propose for distinguishing acceptable pricing from exploitation?",
    opts: [
      "Whether the hotel is a large chain or independent",
      "Whether the consumer has any alternative choice available",
      "Whether the price increase happens during a weekend",
      "Whether the government has approved the rate beforehand",
    ],
    ans: 1,
  },
  "hotel-c2y-criticreflection": {
    q: "Why did the critic say anonymity matters in reviewing, despite giving it up for this meeting?",
    opts: [
      "It allows businesses to know they are being watched",
      "It lets the reviewer experience things authentically without the business adjusting behavior out of awareness",
      "It protects the critic from legal liability",
      "It is required by the publication's editorial policy",
    ],
    ans: 1,
  },
  "hotel-c2y-contractnegotiationtension": {
    q: "What counter-proposal does the legal advisor suggest instead of the penalty clause?",
    opts: [
      "Terminate the contract negotiation entirely",
      "Adjust only the following year's discount rate if the booking target is missed",
      "Demand a higher discount rate from the hotel",
      "Sign the contract as originally written",
    ],
    ans: 1,
  },
  "hotel-c2y-laborstructural": {
    q: "What does the sociologist identify as a structural root cause of housekeeping strain?",
    opts: [
      "Individual hotels' poor management choices alone",
      "Guests demanding excessive services",
      "Online booking platform fee structures squeezing hotels' labor cost capacity",
      "A shortage of interested workers in the labor market",
    ],
    ans: 2,
  },
  "hotel-c2y-designjournalism": {
    q: "How does the owner respond to the criticism that the design philosophy commercializes local culture?",
    opts: [
      "By denying any commercial motive exists",
      "By disclosing a transparent royalty structure for local artisans and viewing the hotel as an evolving collaborative project",
      "By refusing to comment on the criticism",
      "By stating the design will be replaced with a mass-produced style",
    ],
    ans: 1,
  },
  "hotel-c2y-aijobdebate": {
    q: "What concern does the labor economist raise about AI's effect on hospitality careers?",
    opts: [
      "AI will completely eliminate all hospitality jobs within a decade",
      "AI adoption is narrowing the entry point for building career experience even as it helps skilled staff",
      "AI cannot be trained to handle guest inquiries at all",
      "AI adoption is illegal in most countries",
    ],
    ans: 1,
  },
  "hotel-c2y-franchisepower": {
    q: "Why does the franchise association president say franchisees are effectively 'hostages' to the brand?",
    opts: [
      "Because contracts are illegal to terminate under any circumstance",
      "Because leaving the brand means losing all accumulated customer data and brand recognition",
      "Because franchisees are legally required to stay for life",
      "Because headquarters physically controls the property deeds",
    ],
    ans: 1,
  },
  "hotel-c2y-overtourismculture": {
    q: "What practical measure is the lodging association considering to address the impact on original residents?",
    opts: [
      "Banning tourists from the district entirely",
      "Redirecting part of the lodging tax into a fund supporting original residents' housing, with resident participation in its management",
      "Relocating all guesthouses outside the district",
      "Increasing marketing spend to attract more tourists",
    ],
    ans: 1,
  },
};
