import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Phone situation C1/C2 expansion round 2 (2026-08): completes advanced coverage to 20/level.
export const PHONE_C2_EXPANSION: Dialogue[] = [
  {
    id: "phone-c1z-hotline-intake",
    situationKey: "phone",
    level: "C1",
    title: "A whistleblower hotline intake call about workplace safety",
    lines: [
      { speaker: "상담원", kr: "네, 익명 신고 접수 센터입니다. 제보 내용을 말씀해 주시면 기록하겠습니다.", en: "Hello, this is the anonymous reporting intake center. Please tell me the details and I'll record them." },
      { speaker: "제보자", kr: "저희 현장에서 안전 점검 결과를 조작해서 상부에 보고하고 있다는 걸 알게 됐습니다.", en: "I found out that our site has been falsifying safety inspection results before reporting them to management." },
      { speaker: "상담원", kr: "구체적으로 어떤 항목이 조작됐는지 말씀해 주실 수 있으신가요?", en: "Could you tell me specifically which items were falsified?" },
      { speaker: "제보자", kr: "환기 장치 수치가 기준 미달인데도 정상으로 기재된 걸 여러 번 봤습니다.", en: "I've seen ventilation readings that were below standard being recorded as normal, multiple times." },
      { speaker: "상담원", kr: "언제부터 이런 일이 있었는지, 그리고 관련된 인원이 있는지도 확인이 필요합니다.", en: "We'll also need to know since when this has been happening, and whether specific people were involved." },
      { speaker: "제보자", kr: "적어도 반년은 됐고, 현장 소장이 지시했다는 얘기를 동료한테 들은 적도 있습니다.", en: "It's been at least six months, and I've also heard from a coworker that the site manager gave the instruction." },
      { speaker: "상담원", kr: "신원은 철저히 비공개로 처리되며, 접수 후 별도 조사팀이 현장 확인에 나설 예정입니다.", en: "Your identity will be kept strictly confidential, and after intake a separate investigation team will go verify the site." },
      { speaker: "제보자", kr: "혹시 조사 중에 제가 보복성 인사 조치를 당하면 어떻게 되나요?", en: "What happens if I face retaliatory personnel action while the investigation is underway?" },
      { speaker: "상담원", kr: "내부고발자 보호 규정에 따라 그런 조치는 별도로 제재 대상이 되니 즉시 다시 신고해 주시면 됩니다.", en: "Under whistleblower protection rules, such action is itself subject to separate sanctions, so please report it again immediately if it happens." },
    ],
  },
  {
    id: "phone-c1z-book-deal",
    situationKey: "phone",
    level: "C1",
    title: "Negotiating a book deal with a literary agent",
    lines: [
      { speaker: "에이전트", kr: "출판사 쪽에서 제안서를 보내왔는데, 선인세 조건이 처음 얘기했던 것보다 낮게 잡혔어요.", en: "The publisher sent over a proposal, but the advance is set lower than what was originally discussed." },
      { speaker: "작가", kr: "얼마나 차이가 나는데요? 저는 최소한 지난번 계약 수준은 맞춰줘야 한다고 생각했거든요.", en: "How much of a difference is it? I thought they'd at least match the level of the last contract." },
      { speaker: "에이전트", kr: "20퍼센트 정도 낮아요. 대신 인세율을 조금 올려주겠다는 조건을 붙였더라고요.", en: "It's about 20 percent lower. In exchange, they've attached a condition to raise the royalty rate slightly." },
      { speaker: "작가", kr: "장기적으로는 그게 나을 수도 있겠네요. 근데 초판 부수가 어느 정도로 잡혀 있나요?", en: "That might be better in the long run. But what's the first-print run set at?" },
      { speaker: "에이전트", kr: "5천 부로 시작하는데, 이건 시장 상황을 좀 더 반영해서 협상해 볼 수 있을 것 같아요.", en: "It starts at five thousand copies, but I think we can negotiate that further based on market conditions." },
      { speaker: "작가", kr: "그럼 선인세는 원래 수준으로 밀어붙이되, 안 되면 인세율 인상 폭이라도 더 확보해 주세요.", en: "Then push for the original advance level, and if that fails, at least secure a bigger increase in the royalty rate." },
      { speaker: "에이전트", kr: "알겠습니다. 그리고 전자책과 오디오북 권리는 별도 계약으로 분리하자고 제안해 볼게요.", en: "Understood. I'll also propose separating e-book and audiobook rights into a separate contract." },
      { speaker: "작가", kr: "좋아요. 그 부분은 이전 계약에서 손해를 좀 봤던 기억이 있어서 이번엔 신경 써 주세요.", en: "Good. I remember losing out on that in a previous contract, so please pay close attention to it this time." },
      { speaker: "에이전트", kr: "네, 수정 제안서 받는 대로 바로 공유드리겠습니다.", en: "Sure, I'll share the revised proposal as soon as I receive it." },
    ],
  },
  {
    id: "phone-c1z-crisis-line",
    situationKey: "phone",
    level: "C1",
    title: "A crisis-line volunteer handling a difficult call calmly",
    lines: [
      { speaker: "상담원", kr: "여기는 24시간 상담 전화입니다. 지금 많이 힘드신 것 같은데, 어떤 일이 있으셨는지 천천히 말씀해 주세요.", en: "This is the 24-hour helpline. It sounds like you're going through a lot right now—please take your time and tell me what happened." },
      { speaker: "내담자", kr: "그냥... 아무것도 의미가 없는 것 같아요. 며칠째 잠도 못 자고 있고요.", en: "It's just... nothing feels like it means anything anymore. I haven't been able to sleep for days." },
      { speaker: "상담원", kr: "그런 마음이 드신 지는 얼마나 되셨어요? 특별히 계기가 된 일이 있었나요?", en: "How long have you been feeling this way? Was there something specific that triggered it?" },
      { speaker: "내담자", kr: "한 달 전에 실직하고 나서부터 계속 이래요. 가족한테도 말을 못 하겠고요.", en: "It's been like this ever since I lost my job a month ago. I can't even bring myself to tell my family." },
      { speaker: "상담원", kr: "혼자 감당하기 힘드셨겠어요. 지금 이 순간 스스로를 해치고 싶은 생각이 드시나요?", en: "That must have been hard to carry alone. Right now, are you having thoughts of hurting yourself?" },
      { speaker: "내담자", kr: "가끔 그런 생각이 들긴 하는데, 실제로 뭘 하지는 않았어요.", en: "Sometimes those thoughts come up, but I haven't actually done anything." },
      { speaker: "상담원", kr: "솔직하게 말씀해 주셔서 감사해요. 지금 곁에 계신 분이 있으신가요, 아니면 혼자 계세요?", en: "Thank you for being honest with me. Is there someone with you right now, or are you alone?" },
      { speaker: "내담자", kr: "혼자 있어요. 그런데 이렇게 말하고 나니까 조금은 숨통이 트이는 것 같아요.", en: "I'm alone. But now that I've said this out loud, I feel a little like I can breathe again." },
      { speaker: "상담원", kr: "다행이에요. 내일 오전에 상담센터 연계해 드릴 테니, 오늘 밤은 저와 조금 더 이야기 나누실까요?", en: "I'm glad to hear that. I'll connect you to a counseling center tomorrow morning—shall we keep talking a bit more tonight?" },
    ],
  },
  {
    id: "phone-c1z-old-friends",
    situationKey: "phone",
    level: "C1",
    title: "Two old friends reconnecting after a falling-out",
    lines: [
      { speaker: "지훈", kr: "여보세요... 나야, 지훈이. 오랜만이다, 연락해도 될지 한참 고민했어.", en: "Hello... it's me, Ji-hoon. It's been a while—I went back and forth for a long time on whether to call." },
      { speaker: "민서", kr: "어, 진짜 오랜만이네. 나도 사실 몇 번 연락하려다 말았어.", en: "Wow, it really has been a while. Honestly, I tried to reach out a few times too and stopped." },
      { speaker: "지훈", kr: "그때 내가 한 말은 진심이 아니었는데, 화가 나서 심하게 말했던 것 같아. 계속 마음에 걸렸어.", en: "What I said back then wasn't what I really meant—I think I said it too harshly out of anger. It's been weighing on me ever since." },
      { speaker: "민서", kr: "나도 그날 좀 예민하게 굴었던 것 같아. 근데 솔직히 그것보다는 그 뒤로 아무 연락도 없었던 게 더 서운했어.", en: "I think I was also being a bit too sensitive that day. But honestly, what hurt more was the silence afterward." },
      { speaker: "지훈", kr: "맞아, 그게 더 잘못한 거지. 자존심 세우느라 먼저 연락도 못 하고.", en: "You're right, that was the bigger mistake—I let my pride get in the way and couldn't reach out first." },
      { speaker: "민서", kr: "그래도 이렇게 전화해 준 거 고마워. 나도 그동안 너 생각 많이 났어.", en: "Still, I'm grateful you called like this. I thought about you a lot during that time too." },
      { speaker: "지훈", kr: "다음 주에 시간 되면 얼굴 보고 얘기하자. 밀린 얘기가 너무 많아.", en: "If you're free next week, let's meet up and talk in person. There's so much catching up to do." },
      { speaker: "민서", kr: "좋아, 나도 마침 그 근처에 갈 일이 있어. 장소는 내가 찾아볼게.", en: "Sounds good, I actually have something to do around there anyway. I'll look for a place." },
    ],
  },
  {
    id: "phone-c1z-mediator-spouse",
    situationKey: "phone",
    level: "C1",
    title: "A divorce mediator on a preliminary call with one spouse",
    lines: [
      { speaker: "조정관", kr: "안녕하세요, 이번 조정 절차를 맡게 된 조정관입니다. 오늘은 전체 진행 방식을 안내해 드리려고 연락드렸어요.", en: "Hello, I'm the mediator handling this proceeding. I'm calling today to walk you through how the whole process will go." },
      { speaker: "의뢰인", kr: "네, 사실 저는 이게 재판까지 갈 필요는 없다고 생각하는데, 상대방 입장은 아직 모르겠어요.", en: "Sure. Honestly I don't think this needs to go to trial, but I don't know the other side's position yet." },
      { speaker: "조정관", kr: "조정은 양측이 합의점을 찾도록 돕는 절차라 강제성은 없어요. 다만 재산 분할과 양육권 두 가지가 핵심 쟁점이 될 것 같습니다.", en: "Mediation is a non-binding process meant to help both sides find common ground. That said, property division and custody will likely be the two key issues." },
      { speaker: "의뢰인", kr: "양육권 부분이 제일 걱정이에요. 아이 학교 때문에 지금 사는 곳에서 벗어나고 싶지 않거든요.", en: "The custody part worries me the most. I don't want to move away from where we live now because of the kids' school." },
      { speaker: "조정관", kr: "그 부분은 상대방과의 첫 공동 회의에서 다룰 거예요. 그전에 원하시는 조건을 정리해서 보내주시면 도움이 됩니다.", en: "That will be addressed at the first joint session with the other party. It would help if you sent me your desired terms organized beforehand." },
      { speaker: "의뢰인", kr: "재산 쪽은 사실 크게 다툴 게 없긴 한데, 감정이 격해지면 얘기가 복잡해질까 봐 걱정이에요.", en: "There's not really much to fight over on the property side, but I'm worried things will get complicated if emotions run high." },
      { speaker: "조정관", kr: "그런 경우를 대비해서 각자 따로 만나는 개별 회기도 준비해 뒀으니 너무 걱정하지 않으셔도 돼요.", en: "We've prepared separate individual sessions to prepare for that kind of situation, so you don't need to worry too much." },
      { speaker: "의뢰인", kr: "알겠습니다. 첫 회의 전에 조건 정리해서 이메일로 보내드릴게요.", en: "Understood. I'll organize my terms and send them by email before the first session." },
      { speaker: "조정관", kr: "네, 받는 대로 검토하고 일정 잡아서 다시 연락드리겠습니다.", en: "Great, I'll review it as soon as it arrives and follow up to set a date." },
    ],
  },
  {
    id: "phone-c1z-escalated-complaint",
    situationKey: "phone",
    level: "C1",
    title: "A call center supervisor debriefing an escalated complaint",
    lines: [
      { speaker: "팀장", kr: "아까 3번 상담사한테 넘어온 그 고객 건, 어떻게 마무리됐는지 궁금해서 전화했어요.", en: "I'm calling to find out how that customer case handed off to agent number three earlier ended up." },
      { speaker: "상담사", kr: "네, 결제가 두 번 중복돼서 화가 많이 나신 상태였는데, 환불 처리하고 사과드렸습니다.", en: "Yes, they were very upset because they were charged twice—I processed the refund and apologized." },
      { speaker: "팀장", kr: "고객이 보상 얘기도 했다고 들었는데, 그 부분은 어떻게 안내했어요?", en: "I heard the customer also brought up compensation—how did you handle that?" },
      { speaker: "상담사", kr: "제 권한으로는 쿠폰 정도만 드릴 수 있어서, 추가 보상은 상급자 검토가 필요하다고 안내했습니다.", en: "Since a coupon was the most I could authorize, I told them additional compensation would need supervisor review." },
      { speaker: "팀장", kr: "잘했어요. 근데 통화 중에 고객이 계속 언성을 높였다고 하던데, 대응하기 힘들지 않았어요?", en: "Good call. But I heard the customer kept raising their voice during the call—wasn't it hard to handle?" },
      { speaker: "상담사", kr: "솔직히 좀 힘들긴 했는데, 매뉴얼대로 침착하게 응대하려고 했습니다.", en: "Honestly it was a bit tough, but I tried to stay calm and follow the manual." },
      { speaker: "팀장", kr: "고생 많았어요. 이 건은 제가 직접 다시 연락드려서 보상안을 안내할게요.", en: "You did well. I'll personally follow up with the customer directly to walk them through a compensation offer." },
      { speaker: "상담사", kr: "네, 고객 연락처랑 통화 기록은 시스템에 다 남겨뒀습니다.", en: "Okay, I've left the customer's contact info and the call log in the system." },
      { speaker: "팀장", kr: "확인할게요. 이런 케이스는 앞으로 초반에 바로 저한테 에스컬레이션해도 괜찮아요.", en: "I'll check it. For cases like this, it's fine to escalate to me right away in the future." },
    ],
  },
  {
    id: "phone-c1z-persuasion-call",
    situationKey: "phone",
    level: "C1",
    title: "A political campaign volunteer making a persuasion call",
    lines: [
      { speaker: "자원봉사자", kr: "안녕하세요, 지역 유권자분들께 연락드리고 있는 자원봉사자입니다. 잠깐 통화 가능하실까요?", en: "Hello, I'm a volunteer reaching out to local voters. Do you have a moment to talk?" },
      { speaker: "유권자", kr: "네, 뭐 짧게라면요. 근데 저는 이번 선거에 별로 관심이 없어서요.", en: "Sure, if it's brief. But I'm not really interested in this election." },
      { speaker: "자원봉사자", kr: "이해합니다. 혹시 평소에 가장 걱정되시는 지역 현안이 있으신가요?", en: "I understand. Is there a local issue that tends to concern you the most?" },
      { speaker: "유권자", kr: "글쎄요, 요즘 버스 노선이 자꾸 줄어서 불편하긴 해요.", en: "Well, bus routes keep getting cut lately, which has been inconvenient." },
      { speaker: "자원봉사자", kr: "저희 후보가 바로 그 대중교통 확충을 공약으로 내세우고 있어요. 관련 정책 자료를 보내드려도 될까요?", en: "Our candidate is actually campaigning on exactly that—expanding public transit. May I send you the relevant policy materials?" },
      { speaker: "유권자", kr: "음, 나쁘지 않네요. 근데 공약이 실제로 지켜질지는 잘 모르겠어요.", en: "Hmm, that's not bad. But I'm not sure the pledge would actually be kept." },
      { speaker: "자원봉사자", kr: "말씀하신 우려 충분히 이해합니다. 이전 시의원 시절 실행하신 정책 사례도 같이 보내드릴게요.", en: "I fully understand that concern. I'll also send you examples of policies actually implemented during the candidate's time as a city council member." },
      { speaker: "유권자", kr: "그럼 자료 한번 보고 판단해 볼게요.", en: "Alright, I'll take a look at the materials and make up my mind." },
      { speaker: "자원봉사자", kr: "감사합니다. 투표일 전에 다시 한번 연락드려도 괜찮을까요?", en: "Thank you. Would it be all right if I reached out once more before election day?" },
      { speaker: "유권자", kr: "네, 그건 괜찮아요.", en: "Yes, that's fine." },
    ],
  },
  {
    id: "phone-c1z-debt-collector",
    situationKey: "phone",
    level: "C1",
    title: "A debt collector call handled assertively by the debtor",
    lines: [
      { speaker: "추심원", kr: "안녕하세요, 미납된 카드 대금 관련해서 연락드렸습니다. 이번 달까지 처리가 안 되면 신용에 영향이 갈 수 있습니다.", en: "Hello, I'm calling regarding your outstanding credit card balance. If it's not resolved by the end of this month, it could affect your credit." },
      { speaker: "채무자", kr: "네, 상황은 알고 있습니다. 근데 이렇게 협박조로 말씀하시는 건 좀 불편하네요.", en: "Yes, I'm aware of the situation. But I find it uncomfortable that you're speaking in such a threatening tone." },
      { speaker: "추심원", kr: "협박이 아니라 사실을 안내드리는 겁니다. 전액 상환이 어려우시면 언제 가능하신지 말씀해 주세요.", en: "This isn't a threat, just informing you of the facts. If a full repayment is difficult, please tell me when it would be possible." },
      { speaker: "채무자", kr: "지금은 형편이 어려워서 분할로 갚고 싶은데, 이 부분은 조정 가능한가요?", en: "My finances are tight right now, so I'd like to pay in installments—is that negotiable?" },
      { speaker: "추심원", kr: "가능은 합니다만 매월 최소 30만 원 이상 납부하셔야 승인이 됩니다.", en: "It's possible, but you'd need to pay at least 300,000 won a month for it to be approved." },
      { speaker: "채무자", kr: "지금 제 상황으로는 20만 원이 최대입니다. 이 조건으로 서면 합의서를 받고 싶습니다.", en: "200,000 won is the most I can manage given my current situation. I'd like a written agreement on these terms." },
      { speaker: "추심원", kr: "확인해 보겠지만 규정상 조율이 어려울 수도 있습니다.", en: "I'll check, but under our policy that adjustment may be difficult." },
      { speaker: "채무자", kr: "그럼 상급자와 통화하고 싶습니다. 그리고 오늘 통화는 녹음하고 있다는 점 알려드립니다.", en: "Then I'd like to speak with your supervisor. And I'll let you know I'm recording today's call." },
      { speaker: "추심원", kr: "알겠습니다. 상급자에게 연결해 드리고, 조건은 서면으로 다시 안내해 드리겠습니다.", en: "Understood. I'll transfer you to a supervisor and send the terms in writing again." },
    ],
  },
  {
    id: "phone-c1z-parking-ticket",
    situationKey: "phone",
    level: "C1",
    title: "Calling to contest a parking ticket with a bureaucratic office",
    lines: [
      { speaker: "민원인", kr: "안녕하세요, 지난주에 부과된 주차 위반 과태료 이의 신청 관련해서 연락드렸습니다.", en: "Hello, I'm calling regarding an objection to the parking violation fine issued last week." },
      { speaker: "담당자", kr: "네, 접수 번호 알려주시겠어요? 사진 자료랑 같이 확인해 드리겠습니다.", en: "Sure, could you give me the case number? I'll check it along with the photo evidence." },
      { speaker: "민원인", kr: "2384번인데요, 사실 그 자리는 표지판이 나뭇가지에 가려져서 안 보였습니다. 사진도 찍어뒀어요.", en: "It's 2384. Actually the sign there was hidden behind tree branches and wasn't visible—I took a photo of it." },
      { speaker: "담당자", kr: "그 사진을 이의 신청서와 함께 제출해 주시면 현장 확인 후 재심사에 들어갑니다.", en: "If you submit that photo along with the objection form, we'll conduct a site check and start a re-review." },
      { speaker: "민원인", kr: "재심사에는 보통 얼마나 걸리나요? 급하게 처리해야 할 사정이 있어서요.", en: "How long does the re-review usually take? I have circumstances that require this to be handled quickly." },
      { speaker: "담당자", kr: "통상 2주 정도 걸리는데, 급하신 경우 온라인으로 우선 접수하시면 조금 단축될 수 있습니다.", en: "It usually takes about two weeks, but if it's urgent, submitting online first may shorten it a bit." },
      { speaker: "민원인", kr: "알겠습니다. 그런데 재심사 결과가 나올 때까지 과태료 납부는 유예되나요?", en: "Understood. But is payment of the fine deferred until the re-review result comes out?" },
      { speaker: "담당자", kr: "네, 이의 신청이 접수되면 결과 통보 전까지는 납부가 유예됩니다.", en: "Yes, once the objection is filed, payment is deferred until you're notified of the result." },
      { speaker: "민원인", kr: "다행이네요. 서류는 오늘 중으로 온라인 제출하겠습니다.", en: "That's a relief. I'll submit the documents online today." },
    ],
  },
  {
    id: "phone-c2z-study-findings",
    situationKey: "phone",
    level: "C2",
    title: "A scientist explaining a study's findings to a science journalist",
    lines: [
      { speaker: "기자", kr: "이번에 발표하신 논문 관련해서 몇 가지 여쭤봐도 될까요? 일반 독자도 이해할 수 있게 풀어서 설명해 주시면 좋겠습니다.", en: "Could I ask a few questions about the paper you just published? I'd love it explained in a way general readers can follow." },
      { speaker: "연구자", kr: "네, 물론이죠. 핵심은 특정 장내 미생물이 만성 염증 반응을 조절하는 데 관여한다는 걸 확인한 겁니다.", en: "Of course. The core finding is that we confirmed a specific gut microbe is involved in regulating chronic inflammatory responses." },
      { speaker: "기자", kr: "그러면 이게 실제로 특정 질환 치료에 응용될 수 있다는 뜻인가요?", en: "Does that mean this could actually be applied to treating a specific disease?" },
      { speaker: "연구자", kr: "가능성은 있지만 아직은 동물 실험 단계라 단정적으로 말씀드리기는 이릅니다. 임상 적용까지는 최소 몇 년은 걸릴 겁니다.", en: "There's potential, but since we're still at the animal-model stage, it's too early to say anything definitive. Clinical application would take at least a few years." },
      { speaker: "기자", kr: "혹시 보도자료 제목처럼 '치료제 개발 임박'이라고 써도 무리가 없을까요?", en: "Would it be fine to write something like the press release title, 'treatment breakthrough imminent'?" },
      { speaker: "연구자", kr: "그건 과장이 심하다고 봅니다. 오해를 살 수 있으니 '가능성을 시사한다' 정도로 표현해 주셨으면 합니다.", en: "I think that's a significant overstatement. It could mislead readers, so I'd prefer something like 'suggests a possibility.'" },
      { speaker: "기자", kr: "알겠습니다. 그럼 이 연구가 기존 이론과 어떻게 다른지도 짚어주실 수 있을까요?", en: "Understood. Then could you also clarify how this study differs from existing theories?" },
      { speaker: "연구자", kr: "기존에는 염증이 면역세포 단독 작용이라고 봤는데, 저희는 미생물과의 상호작용까지 포함해야 한다는 걸 보인 겁니다.", en: "Previous views treated inflammation as driven solely by immune cells, but we showed that microbial interaction needs to be included as well." },
      { speaker: "기자", kr: "표현 수위는 신중하게 조정해서 기사를 작성하겠습니다. 인용문 확인은 게재 전에 다시 드릴게요.", en: "I'll be careful to calibrate the language when writing the article. I'll send you the quotes to confirm before publication." },
      { speaker: "연구자", kr: "감사합니다. 정확한 전달이 저한테는 제일 중요해서요.", en: "Thank you. Accurate communication matters most to me." },
    ],
  },
  {
    id: "phone-c2z-art-appraisal",
    situationKey: "phone",
    level: "C2",
    title: "An art appraiser disputes a forged authentication claim",
    lines: [
      { speaker: "감정사", kr: "말씀하신 작품 감정 결과를 다시 검토해 봤는데, 안타깝지만 위작 가능성이 매우 높다는 결론입니다.", en: "I reviewed the appraisal of the piece again, and unfortunately my conclusion is that it's very likely a forgery." },
      { speaker: "소장자", kr: "그럴 리가요. 지난번 다른 기관에서는 진품이라고 확인해 줬는데요.", en: "That can't be right. Another institution confirmed it as authentic last time." },
      { speaker: "감정사", kr: "그 감정서도 검토했습니다만, 안료 성분 분석이 빠져 있더군요. 저희는 그 부분에서 시대와 맞지 않는 합성 안료를 발견했습니다.", en: "I reviewed that certificate too, but it lacked pigment composition analysis. We found synthetic pigments that don't match the claimed period." },
      { speaker: "소장자", kr: "구체적으로 어떤 안료가 문제가 됐다는 건가요?", en: "Which pigment specifically is the issue?" },
      { speaker: "감정사", kr: "티타늄화이트가 검출됐는데, 이건 20세기 중반 이후에나 상용화된 안료라 작품 연대와 모순됩니다.", en: "Titanium white was detected, and since that pigment wasn't commercially available until the mid-20th century, it contradicts the claimed date of the work." },
      { speaker: "소장자", kr: "그렇다면 이전 감정 기관의 실수라는 건가요? 이건 보험 처리나 재판매에도 영향이 큰 문제인데요.", en: "So are you saying the earlier institution made a mistake? This has major implications for insurance and resale." },
      { speaker: "감정사", kr: "단정하기보다는, 두 기관의 분석 방식 차이라고 보는 게 맞을 겁니다. 저희는 원자 흡광 분광법까지 사용했거든요.", en: "Rather than being definitive, I'd say it comes down to a difference in analytical methods—we used atomic absorption spectroscopy as well." },
      { speaker: "소장자", kr: "제3의 독립 기관에 재감정을 의뢰하고 싶은데, 추천해 주실 만한 곳이 있을까요?", en: "I'd like to request a re-appraisal from a third, independent institution—could you recommend one?" },
      { speaker: "감정사", kr: "네, 국제적으로 공신력 있는 두 곳을 안내해 드리겠습니다. 다만 결과는 저희와 크게 다르지 않을 가능성이 높습니다.", en: "Sure, I'll give you two internationally credible options. That said, the results are likely to be largely similar to ours." },
      { speaker: "소장자", kr: "알겠습니다. 일단 재감정부터 진행해 보겠습니다.", en: "Understood. I'll proceed with the re-appraisal first." },
    ],
  },
  {
    id: "phone-c2z-adoption-agency",
    situationKey: "phone",
    level: "C2",
    title: "A prospective parent discusses the adoption process with an agency counselor",
    lines: [
      { speaker: "상담사", kr: "지난번 상담 이후로 서류는 잘 준비되고 계신가요? 오늘은 절차 전반을 좀 더 구체적으로 안내해 드리려고요.", en: "How are the documents coming along since our last consultation? Today I'd like to go over the whole process in more detail." },
      { speaker: "신청자", kr: "네, 대부분 준비됐는데 가정환경 조사는 어떤 방식으로 진행되는지 궁금해요.", en: "Yes, most of it is ready, but I'm curious how the home study is actually conducted." },
      { speaker: "상담사", kr: "사회복지사가 두 차례 방문해서 주거 환경과 양육 계획, 지지 체계를 종합적으로 평가합니다.", en: "A social worker will visit twice to comprehensively assess your living environment, parenting plan, and support system." },
      { speaker: "신청자", kr: "혹시 평가 기준에서 걸림돌이 될 만한 부분이 있으면 미리 알려주실 수 있나요?", en: "Could you let me know in advance if there's anything in the criteria that might be a sticking point?" },
      { speaker: "상담사", kr: "지금 맞벌이시라고 하셨는데, 아이 돌봄 계획이 구체적으로 마련돼 있는지가 중요하게 볼 부분입니다.", en: "You mentioned both partners work, so how concrete your childcare plan is will be an important factor they look at." },
      { speaker: "신청자", kr: "저희는 조부모님이 근처에 계셔서 초기엔 도움을 받을 계획이에요. 이런 것도 서류에 포함해야 하나요?", en: "We have grandparents nearby who plan to help in the early stages—should that be included in the documents too?" },
      { speaker: "상담사", kr: "네, 구체적인 지지 체계로 포함해 주시면 평가에 긍정적으로 반영됩니다.", en: "Yes, including that as a concrete part of your support system will reflect positively in the evaluation." },
      { speaker: "신청자", kr: "그럼 아이와의 결연은 보통 어느 시점에 이루어지나요? 심리적으로 준비가 필요할 것 같아서요.", en: "Then at what point does the actual matching with a child typically happen? I feel like I need to prepare myself emotionally." },
      { speaker: "상담사", kr: "가정환경 조사가 승인되고 나면 통상 두세 달 안에 결연 후보가 제시됩니다. 그 사이에 예비 부모 교육도 함께 진행돼요.", en: "Once the home study is approved, a matching candidate is usually presented within two to three months. Prospective-parent education runs alongside that period." },
      { speaker: "신청자", kr: "알겠습니다. 교육 일정도 함께 안내해 주시면 감사하겠습니다.", en: "Understood. I'd appreciate it if you could also send me the education schedule." },
      { speaker: "상담사", kr: "네, 다음 주 초에 전체 일정표를 이메일로 보내드릴게요.", en: "Sure, I'll email you the full schedule early next week." },
    ],
  },
  {
    id: "phone-c2z-archaeology-permit",
    situationKey: "phone",
    level: "C2",
    title: "An archaeologist negotiates excavation access with a landowner",
    lines: [
      { speaker: "고고학자", kr: "선생님 소유 토지에서 지표 조사 중에 유물로 추정되는 파편이 발견돼서 연락드렸습니다.", en: "I'm calling because during a surface survey on your property we found fragments believed to be artifacts." },
      { speaker: "토지주", kr: "네? 그거 발견되면 제 땅 개발 계획에 문제가 생기는 거 아닌가요?", en: "What? Wouldn't that create a problem for my development plans for the land?" },
      { speaker: "고고학자", kr: "정밀 발굴 조사가 필요한 건 맞지만, 결과에 따라 개발이 완전히 막히는 건 아닙니다. 범위가 제한적일 수도 있고요.", en: "A detailed excavation survey is indeed needed, but development isn't necessarily blocked entirely depending on the results—the scope could also be limited." },
      { speaker: "토지주", kr: "그럼 조사 기간은 얼마나 걸리고, 비용은 누가 부담하게 되나요?", en: "Then how long would the survey take, and who bears the cost?" },
      { speaker: "고고학자", kr: "규모에 따라 다르지만 통상 두 달 정도이고, 비용은 문화재청 지원과 저희 연구소가 일부 분담합니다.", en: "It varies by scale, but typically about two months, and the cost is partly covered by Cultural Heritage Administration funding and our research institute." },
      { speaker: "토지주", kr: "제 입장에서는 개발이 지연되는 게 제일 큰 손해인데, 보상 절차는 따로 있나요?", en: "From my perspective, the delay to development is the biggest loss—is there a separate compensation process?" },
      { speaker: "고고학자", kr: "네, 조사로 인한 지연 기간에 대해서는 관련 법령에 따라 보상 신청이 가능합니다. 저희가 서류 작성도 도와드릴 수 있어요.", en: "Yes, you can apply for compensation for the delay period caused by the survey under the relevant regulations. We can also help with the paperwork." },
      { speaker: "토지주", kr: "만약 정말 중요한 유적이 나오면 그땐 어떻게 되는 건가요?", en: "And if something truly significant turns out to be there, what happens then?" },
      { speaker: "고고학자", kr: "그럴 경우 보존 조치가 우선되고 토지 수용이나 매입 협의가 진행될 수 있는데, 이 경우도 정당한 보상이 원칙입니다.", en: "In that case, preservation would take priority and land expropriation or purchase negotiations could proceed, but fair compensation is the principle even then." },
      { speaker: "토지주", kr: "알겠습니다. 일단 정밀 조사부터 진행해 주시고, 보상 관련 서류도 같이 준비해 주세요.", en: "Understood. Please go ahead with the detailed survey first, and prepare the compensation documents alongside it." },
    ],
  },
  {
    id: "phone-c2z-esports-contract",
    situationKey: "phone",
    level: "C2",
    title: "A talent manager disputes a sponsorship clause with a brand rep",
    lines: [
      { speaker: "매니저", kr: "보내주신 스폰서십 계약서 검토했는데, 독점 조항 범위가 너무 넓게 잡혀 있네요.", en: "I reviewed the sponsorship contract you sent, but the exclusivity clause is set far too broadly." },
      { speaker: "브랜드 담당자", kr: "저희 입장에서는 경쟁사 노출을 막는 게 핵심이라서요. 어느 부분이 문제라고 보시나요?", en: "From our side, preventing exposure to competitors is the whole point. Which part do you see as an issue?" },
      { speaker: "매니저", kr: "게임 주변기기뿐 아니라 음료, 의류까지 전 카테고리를 묶어놨는데, 이건 선수 개인 활동을 지나치게 제약합니다.", en: "It bundles not just gaming peripherals but beverages and apparel into the entire category, which excessively restricts the player's individual activities." },
      { speaker: "브랜드 담당자", kr: "저희로서는 브랜드 이미지 통일성이 중요해서 넓게 잡을 수밖에 없었습니다.", en: "For us, brand image consistency matters, so we had no choice but to set it broadly." },
      { speaker: "매니저", kr: "이해는 하지만, 최소한 직접 경쟁 카테고리로만 한정해 주셨으면 합니다. 그렇지 않으면 선수 개인 스폰서 기회가 다 막힙니다.", en: "I understand, but I'd like it limited to at least directly competing categories only. Otherwise, it blocks all of the player's individual sponsorship opportunities." },
      { speaker: "브랜드 담당자", kr: "내부적으로 조율해 보겠습니다. 대신 노출 조항 쪽에서 저희가 요구하는 방송 횟수는 유지해 주셨으면 해요.", en: "We'll try to coordinate internally. In exchange, we'd like the required number of broadcast appearances in the exposure clause to remain as is." },
      { speaker: "매니저", kr: "그 부분은 큰 이견 없습니다. 다만 위약금 조항이 과도하게 설정돼 있어서 이것도 재검토가 필요합니다.", en: "We don't have a major disagreement on that. But the penalty clause is set excessively high, so that also needs re-review." },
      { speaker: "브랜드 담당자", kr: "위약금은 계약 위반 방지 차원이라 완전히 없애기는 어렵지만, 금액 수준은 논의해 볼 수 있습니다.", en: "The penalty is there to deter breach of contract, so we can't remove it entirely, but we can discuss the amount." },
      { speaker: "매니저", kr: "좋습니다. 독점 조항 범위 축소와 위약금 조정, 이 두 가지를 우선순위로 수정안 부탁드립니다.", en: "Good. Please prioritize those two points—narrowing the exclusivity scope and adjusting the penalty—in the revised draft." },
    ],
  },
  {
    id: "phone-c2z-museum-repatriation",
    situationKey: "phone",
    level: "C2",
    title: "A museum curator discusses repatriation of a contested artifact",
    lines: [
      { speaker: "정부 대표", kr: "저희 정부에서 요청드린 유물 반환 건에 대해 박물관 측 입장을 듣고 싶어서 연락드렸습니다.", en: "I'm calling to hear the museum's position on the artifact repatriation request our government made." },
      { speaker: "큐레이터", kr: "네, 내부 위원회에서 검토했습니다. 다만 취득 경위에 대한 추가 자료가 필요하다는 의견이 있었습니다.", en: "Yes, our internal committee reviewed it. However, there was a view that additional documentation on the acquisition circumstances is needed." },
      { speaker: "정부 대표", kr: "저희 쪽 기록으로는 식민 시기에 불법적으로 반출된 정황이 명확한데, 어떤 자료가 더 필요하신 건가요?", en: "According to our records, the circumstances of illegal removal during the colonial period are clear—what additional documentation do you need?" },
      { speaker: "큐레이터", kr: "물론 그 정황은 저희도 인지하고 있습니다. 다만 소장 경위를 법적으로 명확히 하기 위해 원 소유권 입증 자료가 필요하다는 겁니다.", en: "Of course we're aware of that context too. But to legally clarify the circumstances of possession, we need documentation proving original ownership." },
      { speaker: "정부 대표", kr: "이건 법적 소유권보다 도덕적, 역사적 정의의 문제로 봐야 하지 않을까요?", en: "Shouldn't this be seen as a matter of moral and historical justice rather than legal ownership?" },
      { speaker: "큐레이터", kr: "저 개인적으로는 동의합니다. 다만 이사회를 설득하려면 법적 근거가 뒷받침돼야 실질적인 결정이 가능합니다.", en: "Personally, I agree. But to persuade the board, a legal basis needs to back it up for an actual decision to be made." },
      { speaker: "정부 대표", kr: "그렇다면 저희가 국가기록원 자료와 당시 정황을 정리한 보고서를 다시 보내드리겠습니다.", en: "In that case, we'll send you the national archive materials and a report summarizing the circumstances at the time again." },
      { speaker: "큐레이터", kr: "감사합니다. 그 자료를 받으면 다음 이사회 안건으로 정식 상정하겠습니다.", en: "Thank you. Once we receive that, I'll formally put it on the agenda for the next board meeting." },
      { speaker: "정부 대표", kr: "시간이 얼마나 더 걸릴지 예상하시나요? 저희도 계속 진행 상황을 대중에게 설명해야 하는 입장이라서요.", en: "How much longer do you expect this to take? We're in a position where we also need to keep explaining the progress to the public." },
      { speaker: "큐레이터", kr: "다음 이사회가 두 달 뒤라, 그때 결론이 나올 가능성이 높습니다. 진행 상황은 계속 공유드리겠습니다.", en: "The next board meeting is in two months, so a conclusion is likely to come then. I'll keep sharing progress with you in the meantime." },
    ],
  },
  {
    id: "phone-c2z-vaccine-hesitancy",
    situationKey: "phone",
    level: "C2",
    title: "A public health official addresses a caller's vaccine hesitancy on air",
    lines: [
      { speaker: "진행자", kr: "오늘은 보건 당국 관계자분을 모시고 백신 관련 청취자 질문을 받아보겠습니다. 첫 번째 청취자분, 말씀해 주세요.", en: "Today we have a public health official with us to take listener questions about vaccines. First caller, go ahead." },
      { speaker: "청취자", kr: "제가 인터넷에서 보니까 이번 백신이 임상 시험 기간이 너무 짧았다고 하던데, 안전성이 정말 검증된 건가요?", en: "I read online that the clinical trial period for this vaccine was too short—has its safety really been verified?" },
      { speaker: "관계자", kr: "충분히 나올 수 있는 우려입니다. 다만 임상 3상까지 통상적인 규모의 참여자로 진행됐고, 승인 이후에도 지속적인 안전성 모니터링이 이뤄지고 있습니다.", en: "That's a very understandable concern. But phase-three trials were conducted with a typical scale of participants, and continuous safety monitoring has continued even after approval." },
      { speaker: "청취자", kr: "그럼 부작용 사례는 왜 이렇게 많이 보도되는 거죠? 은폐하다가 뒤늦게 나온 거 아닌가요?", en: "Then why are so many adverse-event cases being reported? Isn't it that they were covered up and only came out later?" },
      { speaker: "관계자", kr: "은폐가 아니라, 이상 반응 신고 체계 자체가 공개적으로 운영되기 때문에 보고된 사례가 투명하게 드러나는 겁니다. 다만 인과관계가 확인된 경우와 아닌 경우를 구분해서 봐야 합니다.", en: "It's not a cover-up—since the adverse-event reporting system itself operates transparently, reported cases become visible in the open. But you need to distinguish between cases where causality has been confirmed and those where it hasn't." },
      { speaker: "청취자", kr: "그 구분이 일반인 입장에서는 어렵잖아요. 신뢰하기 힘든 이유가 바로 그거예요.", en: "That distinction is hard for ordinary people to make. That's exactly why it's hard to trust." },
      { speaker: "관계자", kr: "맞는 지적입니다. 그래서 저희가 매달 공개 보고서를 통해 인과관계 평가 결과를 구체적으로 설명하려고 하고 있습니다.", en: "That's a fair point. That's why we're trying to explain the causality assessment results in detail through a public monthly report." },
      { speaker: "청취자", kr: "그 보고서, 저 같은 사람도 이해할 수 있게 되어 있나요?", en: "Is that report written in a way someone like me could actually understand?" },
      { speaker: "관계자", kr: "일반인 대상 요약본도 함께 제공하고 있으니 한번 확인해 보시면 좋겠습니다. 관련 링크는 방송 후에 안내해 드리겠습니다.", en: "We also provide a summary version for the general public, so I'd encourage you to take a look. We'll share the relevant link after the broadcast." },
      { speaker: "진행자", kr: "네, 좋은 질문 감사합니다. 다음 청취자분 연결하겠습니다.", en: "Thank you for the great question. Let's move to the next caller." },
    ],
  },
  {
    id: "phone-c2z-linguist-endangered",
    situationKey: "phone",
    level: "C2",
    title: "A linguist explains urgency to a foundation reviewing a documentation grant",
    lines: [
      { speaker: "재단 심사위원", kr: "제출하신 소멸 위기 언어 기록화 사업 계획서 검토했는데, 예산 규모가 예년보다 상당히 커졌더라고요.", en: "I reviewed your proposal for the endangered-language documentation project, and the budget has grown quite a bit compared to previous years." },
      { speaker: "언어학자", kr: "네, 이번엔 화자 수가 급격히 줄어든 지역이라 현지 체류 기간을 늘릴 수밖에 없었습니다.", en: "Yes, this time the speaker population has declined so sharply in the region that we had no choice but to extend the fieldwork period." },
      { speaker: "재단 심사위원", kr: "구체적으로 화자가 몇 분이나 남아 계신가요? 시급성을 판단할 근거가 필요해서요.", en: "Specifically, how many speakers are left? We need grounds to judge the urgency." },
      { speaker: "언어학자", kr: "유창하게 구사하시는 분이 이제 세 분뿐이고, 모두 팔십 대 후반이십니다. 한 분은 최근 건강이 많이 안 좋아지셨고요.", en: "Only three fluent speakers remain, all in their late eighties. One of them has recently had a significant decline in health." },
      { speaker: "재단 심사위원", kr: "상황이 정말 급하네요. 그런데 녹음만으로는 부족하다고 판단하신 이유는 뭔가요?", en: "That's genuinely urgent. But why did you decide that audio recording alone wouldn't be enough?" },
      { speaker: "언어학자", kr: "구술 서사나 의례 언어는 몸짓과 맥락이 같이 있어야 의미가 온전히 전달돼서, 영상 기록과 현지 공동 작업이 꼭 필요합니다.", en: "For oral narratives and ritual language, gestures and context need to accompany them for the meaning to come through fully, so video documentation and community collaboration are essential." },
      { speaker: "재단 심사위원", kr: "그럼 예산 중 상당 부분이 현지 공동체 참여자 인건비로 잡혀 있는 것도 그런 이유겠네요.", en: "Then I suppose that's also why a significant portion of the budget is allocated to compensation for local community collaborators." },
      { speaker: "언어학자", kr: "맞습니다. 저희만의 작업이 아니라 공동체가 자료를 소유하고 활용할 수 있도록 하는 게 이 사업의 원칙이에요.", en: "Exactly. It's not our work alone—the principle of this project is to make sure the community owns and can use the materials themselves." },
      { speaker: "재단 심사위원", kr: "취지는 충분히 설득력 있습니다. 다만 예산 증액분에 대한 세부 내역서를 다시 제출해 주셔야 이사회 승인이 가능할 것 같아요.", en: "The rationale is quite convincing. But you'll need to resubmit an itemized breakdown of the budget increase for board approval to go through." },
      { speaker: "언어학자", kr: "네, 이번 주 안으로 세부 내역서 정리해서 보내드리겠습니다.", en: "Understood, I'll put together the itemized breakdown and send it within this week." },
    ],
  },
  {
    id: "phone-c2z-diplomat-hostage",
    situationKey: "phone",
    level: "C2",
    title: "A consular officer briefs an anxious family during a hostage negotiation",
    lines: [
      { speaker: "영사", kr: "어젯밤 이후 상황에 진전이 있어서 연락드렸습니다. 다만 아직 확정된 건 아니라는 점 미리 말씀드립니다.", en: "I'm calling because there's been progress since last night. That said, I want to be upfront that nothing is confirmed yet." },
      { speaker: "가족", kr: "네, 어떤 진전인가요? 밤새 한숨도 못 잤어요.", en: "Yes, what kind of progress? I haven't slept a wink all night." },
      { speaker: "영사", kr: "현지 협상팀이 억류자 측과 세 번째 접촉에 성공했고, 안전은 확인됐다고 합니다.", en: "The local negotiation team succeeded in a third contact with the captors' side, and safety has been confirmed." },
      { speaker: "가족", kr: "정말 다행이네요... 그럼 석방 시점은 언제쯤으로 보고 있나요?", en: "That's such a relief... so when do you expect the release to happen?" },
      { speaker: "영사", kr: "그 부분은 아직 협상 중이라 확답을 드리기 어렵습니다. 요구 조건에 대해 상부와 조율이 필요한 상황이에요.", en: "That part is still under negotiation, so I can't give a definite answer. Coordination with higher authorities is needed regarding the demands." },
      { speaker: "가족", kr: "혹시 저희가 언론에 이 내용을 알리는 게 협상에 도움이 될까요, 방해가 될까요?", en: "Would it help or hurt the negotiation if we made this public through the media?" },
      { speaker: "영사", kr: "현재로서는 비공개로 진행하는 게 협상팀 판단으로는 더 안전합니다. 언론 대응은 저희와 먼저 상의해 주셨으면 합니다.", en: "At this stage, the negotiation team's judgment is that keeping it private is safer. We'd ask that you consult with us first before any media response." },
      { speaker: "가족", kr: "알겠습니다. 그런데 저희가 직접 몸값 협상에 나서겠다는 사람들도 있어서 걱정이에요.", en: "Understood. But I'm worried because there are people who want to step in and negotiate a ransom directly." },
      { speaker: "영사", kr: "그건 절대 권해드리지 않습니다. 비공식 접촉은 오히려 협상팀의 공식 채널을 위태롭게 할 수 있어요.", en: "We strongly advise against that. Unofficial contact could actually jeopardize the negotiation team's official channel." },
      { speaker: "가족", kr: "네, 그 부분은 가족들끼리 다시 얘기해서 자제하도록 하겠습니다.", en: "Okay, we'll talk it over among the family and make sure to hold back on that." },
      { speaker: "영사", kr: "감사합니다. 진전이 있을 때마다 하루 두 차례, 오전과 오후로 정기 연락드리겠습니다.", en: "Thank you. I'll give you regular updates twice a day, morning and afternoon, whenever there's progress." },
    ],
  },
];

export const PHONE_C2_QUIZZES: Record<string, DialogueQuiz> = {
  "phone-c1z-hotline-intake": {
    q: "What falsification did the whistleblower report?",
    opts: ["Unpaid wage records", "Ventilation system safety inspection readings", "Falsified work hours", "Forged hiring documents"],
    ans: 1,
  },
  "phone-c1z-book-deal": {
    q: "What did the publisher's proposal lower?",
    opts: ["The royalty rate", "The first-print run", "The advance", "The e-book rights"],
    ans: 2,
  },
  "phone-c1z-crisis-line": {
    q: "What triggered the caller's distress?",
    opts: ["A divorce", "Losing their job", "Moving house", "A health problem"],
    ans: 1,
  },
  "phone-c1z-old-friends": {
    q: "Why did Min-seo say she was more hurt?",
    opts: ["Because of the harsh words", "Because of the lack of contact afterward", "Because a promise was broken", "Because of money problems"],
    ans: 1,
  },
  "phone-c1z-mediator-spouse": {
    q: "What does the client worry about most regarding custody?",
    opts: ["The amount of child support", "Visitation rights", "Having to move because of the kids' school", "The timing of the custody decision"],
    ans: 2,
  },
  "phone-c1z-escalated-complaint": {
    q: "What compensation could the agent offer the customer directly?",
    opts: ["A full refund", "A coupon", "Free shipping", "A transfer to a supervisor's call"],
    ans: 1,
  },
  "phone-c1z-persuasion-call": {
    q: "What local issue does the voter usually worry about?",
    opts: ["Bus routes being cut", "Public safety", "Waste disposal", "Lack of parking"],
    ans: 0,
  },
  "phone-c1z-debt-collector": {
    q: "How much did the debtor request to pay per month?",
    opts: ["100,000 won", "200,000 won", "300,000 won", "500,000 won"],
    ans: 1,
  },
  "phone-c1z-parking-ticket": {
    q: "What reason did the caller give for the objection?",
    opts: ["An error in the fine amount", "The sign was hidden by tree branches", "The license plate was misread", "An error in the violation time"],
    ans: 1,
  },
  "phone-c2z-study-findings": {
    q: "How did the researcher react to the press release title?",
    opts: ["Agreed it was appropriate", "Said it was a significant overstatement", "Asked for stronger wording", "Rewrote the title herself"],
    ans: 1,
  },
  "phone-c2z-art-appraisal": {
    q: "What was the decisive evidence the appraiser cited for the forgery?",
    opts: ["A mismatched signature", "A problem with the canvas material", "Synthetic pigment that doesn't match the period", "The year the frame was made"],
    ans: 2,
  },
  "phone-c2z-adoption-agency": {
    q: "What is the applicant worried about regarding the home study?",
    opts: ["Their income level", "Their childcare plan given both partners work", "The size of their home", "An age limit"],
    ans: 1,
  },
  "phone-c2z-archaeology-permit": {
    q: "What is the landowner most worried about?",
    opts: ["Whether the artifacts are genuine", "The loss from a delay to development", "The size of the survey team", "Noise from excavation equipment"],
    ans: 1,
  },
  "phone-c2z-esports-contract": {
    q: "What clause did the manager flag as a problem?",
    opts: ["The broadcast-appearance requirement", "The excessively broad exclusivity clause", "The contract length", "The scope of image-rights use"],
    ans: 1,
  },
  "phone-c2z-museum-repatriation": {
    q: "What did the curator say was needed to decide on repatriation?",
    opts: ["Results of a public opinion poll", "Documentation proving original ownership", "Precedents from other museums", "An estimate of restoration costs"],
    ans: 1,
  },
  "phone-c2z-vaccine-hesitancy": {
    q: "What reason did the official give for so many adverse-event reports?",
    opts: ["A flaw in the vaccine itself", "The adverse-event reporting system operates openly", "Exaggerated media coverage", "Failed clinical trials"],
    ans: 1,
  },
  "phone-c2z-linguist-endangered": {
    q: "Why did the linguist say video documentation is essential?",
    opts: ["Recording equipment is scarce", "Gestures and context must accompany the language for meaning to come through fully", "The speakers wanted to be filmed", "It helps with budget review"],
    ans: 1,
  },
  "phone-c2z-diplomat-hostage": {
    q: "What did the consular officer ask the family to refrain from?",
    opts: ["Requesting media interviews", "Negotiating a ransom directly themselves", "Visiting the location", "Protesting to the government"],
    ans: 1,
  },
};
