import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Restaurant situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const RESTAURANT_C_EXPANSION: Dialogue[] = [
  {
    id: "restaurant-c1y-menu-change",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "Defending a menu overhaul to a regular", ja: "常連客にメニュー刷新を説明する", zh: "向老顾客解释菜单大改", vi: "Giải thích việc đại tu thực đơn cho khách quen" },
    lines: [
      { speaker: "단골", kr: "예전 메뉴판이 훨씬 정겨웠는데, 왜 갑자기 다 바꾸신 거예요?", en: "The old menu felt so much more familiar — why change everything so suddenly?", ja: "前のメニュー表の方がずっと親しみがあったのに、どうして急に全部変えたんですか？", zh: "以前的菜单更有亲切感，怎么突然全都改了呢？", vi: "Thực đơn cũ nghe quen thuộc hơn nhiều — sao lại đổi hết đột ngột như vậy?" },
      { speaker: "셰프", kr: "정겨움도 좋지만, 재료 수급이 불안정해지면서 어쩔 수 없이 손을 댈 수밖에 없었습니다.", en: "Familiarity matters, but sourcing got unstable, so I had no choice but to make changes.", ja: "親しみも大事ですが、食材の仕入れが不安定になって、やむを得ず手を加えるしかなかったんです。", zh: "亲切感固然重要，但食材供应变得不稳定，我不得不做出调整。", vi: "Sự quen thuộc quan trọng thật, nhưng nguồn nguyên liệu trở nên bất ổn nên tôi không còn lựa chọn nào khác ngoài việc thay đổi." },
      { speaker: "단골", kr: "그래도 제가 십 년 넘게 먹던 육개장이 사라진 건 좀 서운하네요.", en: "Still, it's a bit disappointing that the yukgaejang I've eaten for over ten years is gone.", ja: "それでも私が十年以上食べていたユッケジャンがなくなったのは少し寂しいですね。", zh: "不过我吃了十几年的辣牛肉汤没了，还是有点失落。", vi: "Dù vậy, cũng hơi tiếc khi món yukgaejang tôi ăn suốt hơn mười năm nay không còn nữa." },
      { speaker: "셰프", kr: "그 마음 충분히 이해합니다. 대신 같은 뿌리에서 나온 얼큰한 국물 요리를 새로 준비했으니 한번 드셔보시겠어요?", en: "I completely understand that feeling. Instead, I've prepared a new spicy soup dish rooted in the same tradition — would you like to try it?", ja: "そのお気持ち、よく分かります。代わりに同じ系統の辛いスープ料理を新しく用意しましたので、一度お試しになりますか？", zh: "我完全理解这种心情。我准备了一道源自同一传统的辣汤新菜，要不要尝尝看？", vi: "Tôi hoàn toàn hiểu cảm giác đó. Thay vào đó, tôi đã chuẩn bị một món canh cay mới nhưng vẫn bắt nguồn từ truyền thống cũ — anh/chị muốn thử không?" },
      { speaker: "단골", kr: "음, 낯설긴 한데 향은 비슷하네요.", en: "Hmm, it's unfamiliar but the aroma is similar.", ja: "うーん、見慣れないですが香りは似ていますね。", zh: "嗯，虽然陌生但香气挺相似的。", vi: "Ừm, lạ miệng thật nhưng mùi hương thì khá giống." },
      { speaker: "셰프", kr: "익숙함을 완전히 버리는 게 아니라, 그 위에 새로운 걸 얹는다고 생각해 주시면 좋겠습니다.", en: "I'd like you to think of it not as abandoning familiarity, but as building something new on top of it.", ja: "慣れ親しんだものを完全に捨てるのではなく、その上に新しいものを重ねると考えていただければと思います。", zh: "希望您不要把这看作抛弃熟悉的味道，而是在此基础上添上新的东西。", vi: "Tôi mong anh/chị nghĩ về nó không phải là từ bỏ sự quen thuộc, mà là xây dựng thêm cái mới trên nền tảng đó." },
      { speaker: "단골", kr: "말씀은 그럴듯한데, 결국 손님들 반응이 관건이겠죠.", en: "That sounds reasonable in theory, but ultimately it'll come down to how customers react.", ja: "お話はもっともらしいですが、結局はお客さんの反応次第でしょうね。", zh: "话说得挺有道理，但最终还是要看顾客的反应吧。", vi: "Nghe có lý về mặt lý thuyết, nhưng cuối cùng vẫn phải xem khách hàng phản ứng thế nào." },
      { speaker: "셰프", kr: "맞습니다. 그래서 한 달간 시식 기간을 두고 의견을 계속 반영할 생각입니다.", en: "Exactly. That's why I'm running a month-long tasting period and plan to keep incorporating feedback.", ja: "その通りです。だから一ヶ月間試食期間を設けて、意見を反映し続けるつもりです。", zh: "没错。所以我打算设一个月的试吃期，不断吸收顾客的意见。", vi: "Chính xác. Vì vậy tôi đang chạy thử nghiệm nếm thử trong một tháng và sẽ tiếp tục tiếp thu phản hồi." },
      { speaker: "단골", kr: "그 정성이면 믿어볼 만하네요.", en: "With that much effort, I suppose it's worth trusting.", ja: "その心遣いなら信頼できそうですね。", zh: "有这份诚意，倒是值得信任。", vi: "Bỏ công sức đến thế thì cũng đáng để tin tưởng." },
    ],
  },
  {
    id: "restaurant-c1y-tipping-culture",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "Debating whether to import tipping culture", ja: "チップ文化を導入すべきか議論する", zh: "讨论要不要引进小费文化", vi: "Tranh luận có nên du nhập văn hóa tiền boa" },
    lines: [
      { speaker: "사장", kr: "요즘 젊은 직원들이 미국식 팁 문화를 도입하면 어떻겠냐고 자꾸 묻더라고요.", en: "Lately the younger staff keep asking whether we should introduce American-style tipping.", ja: "最近若いスタッフがアメリカ式のチップ文化を導入したらどうかとよく聞いてくるんです。", zh: "最近年轻员工老是问要不要引入美式小费文化。", vi: "Dạo này nhân viên trẻ cứ hỏi liệu chúng ta có nên đưa văn hóa boa kiểu Mỹ vào không." },
      { speaker: "매니저", kr: "솔직히 저는 회의적이에요. 서비스료를 이미 받고 있는데 이중으로 받는 셈이잖아요.", en: "Honestly I'm skeptical. We already charge a service fee, so it'd essentially be double-charging.", ja: "正直私は懐疑的です。もうサービス料をいただいているのに、二重に取ることになりますから。", zh: "老实说我持怀疑态度。我们已经收服务费了，这样等于重复收费。", vi: "Thành thật mà nói tôi khá hoài nghi. Chúng ta đã thu phí dịch vụ rồi, nên về bản chất đó là tính tiền hai lần." },
      { speaker: "사장", kr: "그렇긴 한데, 숙련된 직원을 붙잡아 두려면 인센티브가 필요하다는 논리도 일리가 있어요.", en: "That's true, but there's also a point to the argument that we need incentives to retain skilled staff.", ja: "確かにそうですが、熟練したスタッフを引き止めるにはインセンティブが必要だという論理も一理あります。", zh: "确实如此，但为了留住熟练员工需要激励机制，这个说法也有道理。", vi: "Đúng vậy, nhưng cũng có lý khi lập luận rằng cần có động lực để giữ chân nhân viên giỏi." },
      { speaker: "매니저", kr: "인센티브라면 팁보다는 성과급 체계를 정비하는 게 낫지 않을까요? 팁은 손님한테 부담을 떠넘기는 거잖아요.", en: "If it's about incentives, wouldn't restructuring a performance-pay system be better than tips? Tipping just shifts the burden onto customers.", ja: "インセンティブなら、チップより成果給制度を整備する方がいいのではないでしょうか？チップはお客さんに負担を押し付けるだけですから。", zh: "如果是激励的话,与其用小费不如完善绩效工资体系？小费只是把负担转嫁给顾客而已。", vi: "Nếu là vấn đề động lực, chẳng phải tái cấu trúc hệ thống lương theo hiệu suất sẽ tốt hơn tiền boa sao? Tiền boa chỉ đơn thuần đẩy gánh nặng sang khách hàng." },
      { speaker: "사장", kr: "부담을 떠넘긴다는 지적은 맞는데, 요즘 외국인 손님들은 오히려 팁이 없어서 어색해하더라고요.", en: "That criticism about shifting the burden is fair, but lately foreign customers actually seem awkward about the absence of tipping.", ja: "負担を押し付けているという指摘は正しいですが、最近外国人のお客さんはむしろチップがないことに戸惑っているようです。", zh: "转嫁负担这个说法没错，但最近外国顾客反而对没有小费感到不习惯。", vi: "Chỉ trích về việc đẩy gánh nặng thì đúng, nhưng dạo này khách nước ngoài có vẻ thật sự thấy ngại vì không có tục lệ boa." },
      { speaker: "매니저", kr: "그건 문화가 다른 거지, 우리가 굳이 맞춰줄 필요는 없다고 봐요.", en: "That's just a cultural difference — I don't think we need to accommodate it.", ja: "それは文化の違いであって、私たちが無理に合わせる必要はないと思います。", zh: "那只是文化差异,我觉得我们没必要非得迁就。", vi: "Đó chỉ là khác biệt văn hóa thôi — tôi nghĩ chúng ta không cần phải chiều theo." },
      { speaker: "사장", kr: "일리 있는 말이에요. 일단은 성과급 체계부터 손보고, 팁 도입은 조금 더 지켜보죠.", en: "That makes sense. Let's start by fixing the performance-pay system and hold off on tipping a bit longer.", ja: "一理ありますね。とりあえず成果給制度から整備して、チップ導入はもう少し様子を見ましょう。", zh: "有道理。先从完善绩效工资体系入手，小费的事再观察一阵子吧。", vi: "Nghe có lý. Vậy hãy bắt đầu bằng việc sửa lại hệ thống lương theo hiệu suất và tạm hoãn chuyện tiền boa thêm một thời gian nữa." },
    ],
  },
  {
    id: "restaurant-c1y-sommelier-pairing",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "A sommelier explains a pairing philosophy", ja: "ソムリエがペアリングの哲学を説明する", zh: "侍酒师讲解配餐理念", vi: "Người quản lý rượu giải thích triết lý kết hợp món ăn" },
    lines: [
      { speaker: "손님", kr: "이 생선 요리에 왜 레드 와인을 추천하시는 거예요? 상식과는 좀 반대되는 것 같은데요.", en: "Why are you recommending a red wine with this fish dish? That seems counterintuitive.", ja: "この魚料理にどうして赤ワインを勧めるんですか？常識とは反対のように思えますが。", zh: "为什么给这道鱼推荐红酒呢？这好像和常识相反。", vi: "Sao lại đề xuất rượu vang đỏ với món cá này? Nghe có vẻ trái ngược thông thường." },
      { speaker: "소믈리에", kr: "일반적인 통념과는 다르지만, 이 요리는 간장 베이스 소스라 타닌이 부드러운 레드와 오히려 잘 어울립니다.", en: "It goes against conventional wisdom, but this dish has a soy-based sauce, so a soft-tannin red actually pairs well.", ja: "一般的な通念とは違いますが、この料理は醤油ベースのソースなので、タンニンが柔らかい赤ワインの方がむしろよく合うんです。", zh: "这确实和常识不同，但这道菜是酱油底的酱汁，单宁柔和的红酒反而更搭。", vi: "Nó đi ngược lại lẽ thường, nhưng món này có nước sốt nền đậu tương, nên loại vang đỏ có tannin mềm thực ra lại rất hợp." },
      { speaker: "손님", kr: "타닌이 생선 비린내를 더 부각시키지는 않나요?", en: "Doesn't tannin tend to amplify the fishy taste?", ja: "タンニンが魚の生臭さをより際立たせるのではないですか？", zh: "单宁不会让鱼腥味更明显吗？", vi: "Chẳng phải tannin thường làm tăng vị tanh sao?" },
      { speaker: "소믈리에", kr: "타닌과 지방이 만나면 그런 문제가 생기죠. 하지만 이 생선은 지방이 적고 소스의 감칠맛이 강해서 균형이 맞습니다.", en: "That happens when tannin meets fat. But this fish is low in fat, and the sauce's umami is strong enough to balance it out.", ja: "タンニンと脂肪が出会うとそういう問題が起きます。ですがこの魚は脂肪が少なく、ソースの旨味が強いのでバランスが取れるんです。", zh: "单宁遇上脂肪才会有那种问题。但这条鱼脂肪含量低，酱汁的鲜味很浓，能达到平衡。", vi: "Điều đó xảy ra khi tannin gặp chất béo. Nhưng con cá này ít béo, và vị umami của nước sốt đủ mạnh để cân bằng lại." },
      { speaker: "손님", kr: "듣고 보니 논리적이긴 한데, 그래도 안전하게 화이트로 갈까 싶기도 하네요.", en: "Now that I hear it, it does sound logical, but part of me still wants to play it safe with white.", ja: "聞いてみると理にかなってはいますが、それでも安全に白にしようかとも思いますね。", zh: "听起来是挺有道理，不过我心里还是想稳妥点选白酒。", vi: "Nghe vậy thì thấy có lý đấy, nhưng trong lòng tôi vẫn muốn chọn an toàn với vang trắng." },
      { speaker: "소믈리에", kr: "물론 화이트도 무난한 선택입니다. 다만 오늘은 손님께 조금 더 대담한 경험을 권해드리고 싶었어요.", en: "White is certainly a safe choice too. I just wanted to offer you a bolder experience today.", ja: "もちろん白も無難な選択です。ただ今日はお客様にもう少し大胆な経験をお勧めしたかったんです。", zh: "白酒当然也是稳妥的选择。只是今天想为您推荐一次更大胆的体验。", vi: "Vang trắng chắc chắn cũng là lựa chọn an toàn. Tôi chỉ muốn mang đến cho anh/chị một trải nghiệm táo bạo hơn hôm nay thôi." },
      { speaker: "손님", kr: "좋아요, 모험 한번 해보죠. 대신 별로면 솔직히 말할게요.", en: "All right, let's take the adventure. But I'll be honest if it doesn't work.", ja: "いいでしょう、冒険してみます。ただ、いまいちだったら正直に言いますね。", zh: "好，那就冒险一次吧。不过如果不好吃我会直说的。", vi: "Được rồi, hãy thử mạo hiểm xem sao. Nhưng nếu không hợp tôi sẽ nói thẳng." },
      { speaker: "소믈리에", kr: "환영합니다. 저희도 그런 피드백이 메뉴를 발전시키는 원동력이라고 생각해요.", en: "I welcome that. We believe that kind of feedback is what drives the menu forward.", ja: "歓迎します。私たちもそういうフィードバックがメニューを発展させる原動力だと思っています。", zh: "非常欢迎。我们也认为这样的反馈正是推动菜单进步的动力。", vi: "Tôi rất hoan nghênh điều đó. Chúng tôi tin rằng chính những phản hồi như vậy mới giúp thực đơn tiến bộ." },
    ],
  },
  {
    id: "restaurant-c1y-authenticity-debate",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "Two food writers argue over fusion authenticity", ja: "二人のフードライターがフュージョン料理の正統性を論じる", zh: "两位美食作家争论融合菜的正宗性", vi: "Hai nhà văn ẩm thực tranh cãi về tính chính thống của món fusion" },
    lines: [
      { speaker: "기자A", kr: "이 퓨전 김치 타코, 솔직히 정체성이 애매하지 않아요? 이도 저도 아닌 느낌이에요.", en: "This fusion kimchi taco — doesn't it feel ambiguously identity-less? Neither one thing nor the other.", ja: "このフュージョンキムチタコス、正直アイデンティティが曖昧じゃないですか？どっちつかずな感じがします。", zh: "这道融合泡菜卷饼，说实话不觉得身份很模糊吗？感觉两不像。", vi: "Món taco kimchi fusion này — chẳng phải nó có cảm giác mơ hồ, không rõ bản sắc sao? Chẳng phải cái này cũng chẳng phải cái kia." },
      { speaker: "기자B", kr: "저는 반대예요. 오히려 두 전통이 만나서 새로운 문법을 만든 거라고 봐요.", en: "I disagree. I see it as two traditions meeting to create a new grammar altogether.", ja: "私は反対です。むしろ二つの伝統が出会って新しい文法を作ったと見ています。", zh: "我不这么认为。我觉得这是两种传统相遇创造出了新的语法。", vi: "Tôi không đồng ý. Tôi coi đó là sự gặp gỡ của hai truyền thống để tạo ra một ngữ pháp hoàn toàn mới." },
      { speaker: "기자A", kr: "그 새로운 문법이라는 게, 결국 원조의 맥락을 지워버리는 거 아닌가요?", en: "But doesn't that 'new grammar' end up erasing the original context?", ja: "その新しい文法というものが、結局本家の文脈を消してしまうんじゃないですか？", zh: "但那种“新语法”不是最终抹去了原始的语境吗？", vi: "Nhưng chẳng phải 'ngữ pháp mới' đó cuối cùng lại xóa bỏ bối cảnh gốc sao?" },
      { speaker: "기자B", kr: "맥락을 지운다기보다는 확장한다고 표현하고 싶은데요. 김치의 발효 원리는 그대로 살아 있잖아요.", en: "I'd rather say it expands the context rather than erasing it. The fermentation principle of kimchi is still intact.", ja: "文脈を消すというより拡張すると表現したいですね。キムチの発酵原理はそのまま生きていますから。", zh: "我更愿意说是扩展语境而不是抹去。泡菜的发酵原理还是完整保留的。", vi: "Tôi thà nói rằng nó mở rộng bối cảnh chứ không xóa bỏ nó. Nguyên lý lên men của kimchi vẫn còn nguyên vẹn." },
      { speaker: "기자A", kr: "발효 원리가 살아 있다고 해서 정통성이 보장되는 건 아니죠. 결국 소비자가 원조를 오해하게 될 수도 있어요.", en: "Just because the fermentation principle survives doesn't guarantee authenticity. Consumers might end up misunderstanding the original.", ja: "発酵原理が生きているからといって正統性が保証されるわけではありません。結局消費者が本家を誤解することにもなり得ます。", zh: "发酵原理保留下来并不代表正宗性得到了保证。消费者最终可能会误解正宗的原型。", vi: "Chỉ vì nguyên lý lên men còn tồn tại không có nghĩa là đảm bảo được tính chính thống. Người tiêu dùng có thể sẽ hiểu sai về bản gốc." },
      { speaker: "기자B", kr: "그건 오해라기보다 재해석의 여지를 주는 거 아닐까요. 모든 요리는 결국 어딘가에서 변형되어 왔잖아요.", en: "Isn't that leaving room for reinterpretation rather than misunderstanding? Every cuisine has ultimately been transformed somewhere along the way.", ja: "それは誤解というより再解釈の余地を与えるものではないでしょうか。あらゆる料理は結局どこかで変形されてきたわけですから。", zh: "那与其说是误解，不如说是留出了重新诠释的空间吧。所有菜系归根结底都是在某处经历过变形的。", vi: "Chẳng phải đó là để lại chỗ cho sự tái diễn giải chứ không phải là hiểu sai sao? Suy cho cùng mọi nền ẩm thực đều đã biến đổi ở đâu đó trên hành trình của nó." },
      { speaker: "기자A", kr: "그 말도 맞지만, 변형의 속도가 너무 빠르면 뿌리를 잃어버릴 위험도 있죠.", en: "That's fair, but if the pace of transformation is too fast, there's also a risk of losing one's roots.", ja: "その言葉も正しいですが、変形の速度が速すぎるとルーツを失う危険もありますよね。", zh: "这话也没错，但变化速度太快也有失去根基的风险。", vi: "Điều đó đúng, nhưng nếu tốc độ biến đổi quá nhanh, cũng có nguy cơ đánh mất gốc rễ." },
      { speaker: "기자B", kr: "결국 우리 둘 다 같은 걱정을 하고 있는 거네요. 속도와 존중의 균형이요.", en: "In the end we're both worried about the same thing — the balance between speed and respect.", ja: "結局私たち二人とも同じ心配をしているんですね。速度と敬意のバランスというものを。", zh: "看来我们俩担心的其实是同一件事——速度与尊重之间的平衡。", vi: "Cuối cùng cả hai chúng ta đều lo lắng về cùng một điều — sự cân bằng giữa tốc độ và sự tôn trọng." },
    ],
  },
  {
    id: "restaurant-c1y-labor-costs",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "Discussing labor costs with a journalist", ja: "記者と人件費について語る", zh: "与记者谈论人工成本", vi: "Bàn luận chi phí nhân công với một nhà báo" },
    lines: [
      { speaker: "기자", kr: "최저임금이 오르면서 식당 운영에 실질적으로 어떤 부담이 있으신가요?", en: "With the minimum wage rising, what practical burdens has that placed on running the restaurant?", ja: "最低賃金が上がって、飲食店経営に実際どんな負担がありますか？", zh: "最低工资上涨后，对餐厅经营带来了哪些实际的负担？", vi: "Với việc lương tối thiểu tăng, điều đó tạo ra gánh nặng thực tế nào cho việc vận hành nhà hàng?" },
      { speaker: "사장", kr: "인건비 비중이 매출의 삼십 퍼센트를 넘어서면서, 메뉴 가격을 올리지 않으면 버티기 힘든 구조가 됐어요.", en: "With labor costs exceeding thirty percent of revenue, it's become a structure where we can't survive without raising menu prices.", ja: "人件費の割合が売上の三十パーセントを超えて、メニューの値段を上げないとやっていけない構造になりました。", zh: "人工成本占营业额超过三成，变成了不涨价就很难维持的结构。", vi: "Khi chi phí nhân công vượt quá ba mươi phần trăm doanh thu, đó trở thành một cơ cấu mà chúng tôi không thể tồn tại nếu không tăng giá thực đơn." },
      { speaker: "기자", kr: "그렇다고 가격을 올리면 손님이 줄어들 위험도 있잖아요.", en: "But raising prices also risks losing customers, doesn't it?", ja: "だからといって値段を上げたらお客さんが減るリスクもありますよね。", zh: "但涨价的话也有顾客减少的风险吧。", vi: "Nhưng tăng giá cũng có nguy cơ mất khách, phải không?" },
      { speaker: "사장", kr: "맞아요. 그래서 저희는 가격 인상 대신 메뉴 구성을 단순화해서 조리 인력을 효율적으로 배치하는 쪽을 택했습니다.", en: "Right. So instead of raising prices, we chose to simplify the menu and deploy kitchen staff more efficiently.", ja: "そうなんです。だから私たちは値上げの代わりに、メニュー構成を単純化して調理人員を効率的に配置する方を選びました。", zh: "对。所以我们选择了不涨价，而是简化菜单、更高效地安排厨房人手。", vi: "Đúng vậy. Vì thế thay vì tăng giá, chúng tôi chọn cách đơn giản hóa thực đơn và bố trí nhân viên bếp hiệu quả hơn." },
      { speaker: "기자", kr: "직원들 입장에서는 업무 강도가 세지는 건 아닐까요?", en: "From the employees' perspective, wouldn't that intensify their workload?", ja: "スタッフの立場からすると、業務の強度が強くなるのではないでしょうか？", zh: "从员工的角度来看，工作强度不会因此加大吗？", vi: "Từ góc độ nhân viên, chẳng phải điều đó sẽ làm tăng khối lượng công việc của họ sao?" },
      { speaker: "사장", kr: "그 우려도 있어서, 대신 근무 시간을 유연하게 조정하고 성과에 따른 보너스를 신설했어요.", en: "That concern is real, so instead we made work hours more flexible and introduced performance-based bonuses.", ja: "その懸念もあったので、代わりに勤務時間を柔軟に調整して、成果に応じたボーナスを新設しました。", zh: "这种担忧也是有的，所以我们把工作时间调整得更灵活，还新增了绩效奖金。", vi: "Mối lo đó là có thật, nên thay vào đó chúng tôi đã linh hoạt hóa giờ làm việc và đưa vào tiền thưởng theo hiệu suất." },
      { speaker: "기자", kr: "결국 최저임금 인상이 오히려 조직 운영 방식을 바꾸는 계기가 된 셈이네요.", en: "So in the end, the minimum wage increase became an occasion to change how the whole operation runs.", ja: "結局最低賃金の引き上げが、むしろ組織運営の方式を変えるきっかけになったわけですね。", zh: "所以说到底，最低工资的上涨反而成了改变整个经营方式的契机。", vi: "Vậy cuối cùng, việc tăng lương tối thiểu đã trở thành cơ hội để thay đổi cách toàn bộ hoạt động vận hành." },
      { speaker: "사장", kr: "정확히 보셨어요. 부담이었지만, 돌이켜보면 체질 개선의 계기이기도 했습니다.", en: "You've put it exactly right. It was a burden, but in hindsight it was also a chance to improve our fundamentals.", ja: "まさにその通りです。負担ではありましたが、振り返ってみれば体質改善のきっかけでもありました。", zh: "您说得很准确。虽然是负担，但回过头看也是一次体质改善的契机。", vi: "Anh/chị nói đúng lắm. Đó là một gánh nặng, nhưng nhìn lại thì cũng là cơ hội để cải thiện nền tảng của chúng tôi." },
    ],
  },
  {
    id: "restaurant-c1y-vip-complaint",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "Mentoring a new server on a VIP complaint", ja: "新人にVIP客のクレーム対応を指導する", zh: "指导新员工应对贵宾客诉", vi: "Hướng dẫn nhân viên mới xử lý khiếu nại của khách VIP" },
    lines: [
      { speaker: "신입", kr: "방금 그 손님, 예약 시간보다 이십 분이나 늦게 자리를 드렸다고 화를 내셨는데 어떻게 대응해야 할지 모르겠어요.", en: "That customer just now got angry because we seated them twenty minutes past their reservation, and I don't know how to respond.", ja: "さっきのお客様、予約時間より二十分も遅く席に案内したと怒っていらしたんですが、どう対応すればいいか分かりません。", zh: "刚才那位客人，因为比预约时间晚了二十分钟才安排入座生气了，我不知道该怎么处理。", vi: "Vị khách vừa rồi nổi giận vì chúng ta xếp chỗ trễ hai mươi phút so với giờ đặt, tôi không biết phải xử lý thế nào." },
      { speaker: "선배", kr: "일단 변명부터 하지 않는 게 중요해. 이유를 설명하기 전에 먼저 불편을 끼친 것에 대해 확실히 사과부터 해야 돼.", en: "First, it's important not to start with excuses. Before explaining the reason, you have to clearly apologize for the inconvenience first.", ja: "まず言い訳から入らないことが大事だよ。理由を説明する前に、まず不便をかけたことについてしっかり謝らないと。", zh: "首先，重要的是不要先找借口。在解释原因之前，一定要先为造成的不便明确道歉。", vi: "Trước hết, điều quan trọng là không được bắt đầu bằng lời bào chữa. Trước khi giải thích lý do, phải xin lỗi rõ ràng về sự bất tiện trước đã." },
      { speaker: "신입", kr: "사과만 하면 손님이 더 화내지 않을까요? 이유를 알고 싶어 하실 것 같은데요.", en: "Won't the customer get angrier if I just apologize? I feel like they'd want to know the reason.", ja: "謝るだけだとお客様がもっと怒るんじゃないですか？理由を知りたがっていると思うんですが。", zh: "只道歉的话客人会不会更生气呢？感觉他们会想知道原因。", vi: "Nếu chỉ xin lỗi thôi thì khách sẽ không càng giận hơn sao? Tôi có cảm giác họ sẽ muốn biết lý do." },
      { speaker: "선배", kr: "사과 다음에 이유를 짧게 설명하고, 대신 뭘 해드릴 수 있는지를 제안하는 순서가 중요해. 예를 들어 웰컴 디저트를 서비스로 드린다든가.", en: "The order matters — apologize, briefly explain the reason, then offer what you can do to make up for it. For example, offering a complimentary welcome dessert.", ja: "謝罪の後に理由を簡潔に説明して、代わりに何ができるかを提案する順番が大事だよ。例えばウェルカムデザートをサービスするとかね。", zh: "顺序很重要——先道歉，然后简短说明原因，再提出能做些什么来补偿，比如免费送一份欢迎甜点。", vi: "Thứ tự rất quan trọng — xin lỗi, giải thích ngắn gọn lý do, rồi đề xuất những gì có thể làm để bù đắp. Ví dụ, mời một món tráng miệng chào mừng miễn phí." },
      { speaker: "신입", kr: "만약 그래도 손님이 안 풀리면요?", en: "And if the customer still isn't satisfied even after that?", ja: "それでもお客様の気が収まらなかったらどうしますか？", zh: "如果那样客人还是不消气怎么办？", vi: "Còn nếu khách vẫn không hài lòng dù đã làm như vậy thì sao?" },
      { speaker: "선배", kr: "그럴 땐 매니저를 불러서 권한을 넘기는 게 맞아. 신입이 혼자 감당하려다가 상황이 더 커지는 경우가 많거든.", en: "In that case, the right move is to call the manager and hand off the authority. New staff often make things worse by trying to handle it alone.", ja: "そういう時はマネージャーを呼んで権限を渡すのが正しいよ。新人が一人で抱え込もうとして状況が大きくなることが多いから。", zh: "那种情况下应该叫来经理，把权限移交给他。新员工独自硬撑往往会让情况更严重。", vi: "Trong trường hợp đó, cách đúng đắn là gọi quản lý và chuyển giao thẩm quyền. Nhân viên mới thường làm mọi thứ tệ hơn khi cố tự mình xử lý." },
      { speaker: "신입", kr: "알겠습니다. 사과, 설명, 제안, 그리고 필요하면 매니저 호출이군요.", en: "Got it — apologize, explain, offer, and call the manager if needed.", ja: "分かりました。謝罪、説明、提案、そして必要ならマネージャーを呼ぶんですね。", zh: "明白了。道歉、解释、提议，必要时叫经理。", vi: "Em hiểu rồi — xin lỗi, giải thích, đề xuất, và gọi quản lý nếu cần." },
      { speaker: "선배", kr: "정확해. 그 순서만 지켜도 대부분의 컴플레인은 부드럽게 넘어가.", en: "Exactly. Just following that order resolves most complaints smoothly.", ja: "その通り。その順番さえ守れば、ほとんどのクレームはスムーズに解決するよ。", zh: "没错。只要照这个顺序来，大部分投诉都能平稳解决。", vi: "Chính xác. Chỉ cần theo đúng thứ tự đó thì phần lớn khiếu nại sẽ được giải quyết suôn sẻ." },
    ],
  },
  {
    id: "restaurant-c1y-neighborhood-decline",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "The decline of a neighborhood's dining culture", ja: "地域の食文化の衰退", zh: "社区餐饮文化的衰落", vi: "Sự suy tàn của văn hóa ẩm thực khu phố" },
    lines: [
      { speaker: "주민A", kr: "이 골목도 예전엔 저녁마다 사람들로 북적였는데, 요즘은 문 닫은 가게가 절반이 넘네요.", en: "This alley used to be packed with people every evening, but these days more than half the shops have closed.", ja: "この路地も昔は毎晩人でにぎわっていたのに、最近は閉店した店が半分を超えていますね。", zh: "这条巷子以前每天晚上都人来人往，现在关门的店都超过一半了。", vi: "Con hẻm này ngày trước tối nào cũng đông nghịt người, nhưng dạo này hơn phân nửa cửa hàng đã đóng cửa." },
      { speaker: "주민B", kr: "임대료가 워낙 올라서 오래된 가게들이 버티질 못했죠. 대신 프랜차이즈만 들어오고요.", en: "Rent went up so much that the old shops couldn't hold on. Instead, only franchises moved in.", ja: "家賃があまりに上がって、古い店は持ちこたえられませんでした。代わりにチェーン店ばかり入ってきて。", zh: "租金涨得太厉害，老店都撑不下去了。取而代之的都是连锁店。", vi: "Tiền thuê tăng quá cao khiến các cửa hàng cũ không trụ nổi. Thay vào đó, chỉ có các chuỗi nhượng quyền chuyển vào." },
      { speaker: "주민A", kr: "프랜차이즈가 나쁘다는 건 아니지만, 골목만의 색깔이 사라지는 게 아쉬워요.", en: "I'm not saying franchises are bad, but it's a shame the alley's unique character is disappearing.", ja: "チェーン店が悪いというわけではありませんが、この路地ならではの色が消えていくのが残念です。", zh: "我不是说连锁店不好，只是这条巷子独有的味道正在消失，挺可惜的。", vi: "Tôi không nói chuỗi nhượng quyền là xấu, nhưng thật đáng tiếc khi bản sắc riêng của con hẻm đang biến mất." },
      { speaker: "주민B", kr: "저도 그렇게 생각해요. 근데 젊은 세대는 오히려 익숙하고 깔끔한 프랜차이즈를 더 편하게 느끼더라고요.", en: "I feel the same way. But the younger generation actually seems to find familiar, tidy franchises more comfortable.", ja: "私もそう思います。でも若い世代はむしろ慣れていて清潔なチェーン店の方が居心地いいと感じているようです。", zh: "我也这么想。不过年轻一代反而觉得熟悉又整洁的连锁店更让人自在。", vi: "Tôi cũng cảm thấy vậy. Nhưng thế hệ trẻ có vẻ thực sự thấy thoải mái hơn với những chuỗi quen thuộc, gọn gàng." },
      { speaker: "주민A", kr: "편함과 정겨움은 다른 문제인데, 그 둘을 다 잡기가 쉽지 않은 모양이에요.", en: "Comfort and warmth are different things — it seems hard to hold onto both.", ja: "快適さと親しみやすさは別の問題なのに、その両方をつかむのは簡単ではないようです。", zh: "舒适和亲切感是两码事，看来很难两者兼得。", vi: "Sự thoải mái và hơi ấm là hai điều khác nhau — có vẻ khó giữ được cả hai cùng lúc." },
      { speaker: "주민B", kr: "구청에서 골목 상권 지원 사업을 한다고는 하던데, 실효성이 있을지는 지켜봐야죠.", en: "I heard the district office is running a support program for the alley's commercial district, but we'll have to see if it's actually effective.", ja: "区役所が路地商圏支援事業をやるとは聞きましたが、実効性があるかは見守るしかないですね。", zh: "听说区政府在搞巷弄商圈扶持项目，不过是否真的有效还得观察观察。", vi: "Tôi nghe nói ủy ban quận đang chạy chương trình hỗ trợ khu thương mại của con hẻm, nhưng phải xem liệu nó có thực sự hiệu quả hay không." },
      { speaker: "주민A", kr: "지원금만으로는 부족할 것 같고, 결국 사람들이 다시 찾아올 이유를 만들어야 할 텐데요.", en: "Subsidies alone probably won't be enough — ultimately we need to create reasons for people to come back.", ja: "支援金だけでは足りないと思いますし、結局人々がまた訪れる理由を作らないといけないでしょうね。", zh: "光靠补贴恐怕不够，归根结底还是要创造让人们重新回来的理由。", vi: "Chỉ trợ cấp thôi có lẽ không đủ — cuối cùng chúng ta cần tạo ra lý do để mọi người quay lại." },
    ],
  },
  {
    id: "restaurant-c1y-catering-negotiation",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "Negotiating a corporate catering contract", ja: "企業ケータリング契約の交渉", zh: "洽谈企业餐饮合同", vi: "Đàm phán hợp đồng catering doanh nghiệp" },
    lines: [
      { speaker: "담당자", kr: "저희 회사는 매달 세 번 정도 팀 회식을 케이터링으로 진행하려고 하는데, 정기 계약이 가능할까요?", en: "Our company plans to run team dinners via catering about three times a month — would a regular contract be possible?", ja: "うちの会社は毎月三回ほどチーム会食をケータリングでやろうと思っているんですが、定期契約は可能でしょうか？", zh: "我们公司打算每月大约三次用餐饮服务办团队聚餐，可以签定期合同吗？", vi: "Công ty chúng tôi dự định tổ chức tiệc ăn tối cho nhóm qua dịch vụ catering khoảng ba lần một tháng — có thể ký hợp đồng thường xuyên không?" },
      { speaker: "사장", kr: "가능합니다. 다만 정기 계약이면 메뉴 다양성을 어느 정도 유지할지 미리 정해두는 게 좋아요.", en: "That's possible. But for a regular contract, it's better to decide in advance how much menu variety to maintain.", ja: "可能です。ただ定期契約なら、メニューの多様性をどの程度維持するか事前に決めておく方がいいです。", zh: "可以的。不过定期合同的话，最好提前定好菜单要保持多大程度的多样性。", vi: "Có thể được ạ. Nhưng với hợp đồng thường xuyên, tốt hơn là nên quyết định trước mức độ đa dạng thực đơn cần duy trì." },
      { speaker: "담당자", kr: "매번 다른 메뉴를 원하는데, 그럼 단가가 많이 올라가나요?", en: "We'd like a different menu each time — would that raise the unit price significantly?", ja: "毎回違うメニューを希望しているんですが、それだと単価がかなり上がりますか？", zh: "我们希望每次都换菜单，那样的话单价会涨很多吗？", vi: "Chúng tôi muốn mỗi lần có thực đơn khác nhau — điều đó có làm tăng đáng kể đơn giá không?" },
      { speaker: "사장", kr: "완전히 다른 메뉴보다는, 기본 구성은 유지하되 두세 가지 요리만 순환시키는 방식을 추천드려요. 그러면 단가 변동도 줄어들고요.", en: "Rather than a completely different menu each time, I'd recommend keeping a base composition and rotating just two or three dishes — that also reduces price fluctuation.", ja: "完全に違うメニューにするより、基本構成は維持しつつ二、三品だけ入れ替える方式をお勧めします。そうすれば単価変動も減ります。", zh: "与其每次都完全不同，不如建议保留基本组合、只轮换两三道菜，这样单价波动也会小一些。", vi: "Thay vì thay đổi hoàn toàn thực đơn mỗi lần, tôi khuyên nên giữ một cơ cấu cơ bản và luân phiên chỉ hai ba món — cách đó cũng giảm được biến động giá." },
      { speaker: "담당자", kr: "알레르기가 있는 직원들도 있는데, 개별 대응이 되나요?", en: "We have staff with allergies — can you accommodate that individually?", ja: "アレルギーのある社員もいるんですが、個別対応は可能ですか？", zh: "我们有些员工有过敏，可以个别处理吗？", vi: "Chúng tôi có nhân viên bị dị ứng — anh/chị có thể xử lý riêng cho từng người không?" },
      { speaker: "사장", kr: "명단만 미리 주시면 별도 표시를 해서 준비해 드립니다. 오히려 그 부분을 미리 알려주시는 게 저희에게도 편해요.", en: "If you just give us the list in advance, we'll mark those dishes separately. That kind of advance notice actually makes things easier for us too.", ja: "名簿さえ事前にいただければ、別途表示して準備します。むしろその部分を事前に教えていただく方が私たちも助かります。", zh: "只要提前给我们名单，我们会单独标注准备。提前告知反而对我们也更方便。", vi: "Chỉ cần cho chúng tôi danh sách trước, chúng tôi sẽ đánh dấu riêng những món đó. Việc báo trước như vậy thực ra cũng giúp chúng tôi thuận tiện hơn." },
      { speaker: "담당자", kr: "좋네요. 그럼 시범적으로 한 달만 먼저 진행해 보고 계약 조건을 다시 논의하는 건 어떨까요?", en: "Sounds good. Then how about running it on a trial basis for one month first and discussing the contract terms again after?", ja: "いいですね。では試験的に一ヶ月だけ先に進めてみて、契約条件をまた話し合うのはどうでしょう？", zh: "不错。那先试运行一个月，之后再讨论合同条款怎么样？", vi: "Nghe ổn đấy. Vậy sao không thử chạy trong một tháng trước rồi bàn lại điều khoản hợp đồng sau?" },
      { speaker: "사장", kr: "합리적인 제안이라고 생각합니다. 그렇게 진행하시죠.", en: "I think that's a reasonable proposal. Let's proceed that way.", ja: "合理的な提案だと思います。そのように進めましょう。", zh: "我觉得这个提议很合理。那就这样进行吧。", vi: "Tôi nghĩ đó là một đề xuất hợp lý. Hãy tiến hành theo cách đó." },
    ],
  },
  {
    id: "restaurant-c1y-inspector-reveal",
    situationKey: "restaurant",
    level: "C1",
    title: { en: "A Michelin inspector's visit revealed after the fact", ja: "後から分かったミシュラン調査員の来店", zh: "事后才知道米其林调查员来过", vi: "Chuyến thăm của thanh tra viên Michelin được tiết lộ sau đó" },
    lines: [
      { speaker: "셰프", kr: "지난주 화요일에 조용히 앉아서 코스 요리를 다 드시고 가신 분, 알고 보니 미쉐린 심사위원이었대요.", en: "That person who quietly sat and ate through our whole tasting course last Tuesday — turns out they were a Michelin inspector.", ja: "先週の火曜日に静かに座ってコース料理を全部召し上がって帰った方、実はミシュランの審査員だったそうです。", zh: "上周二安静地坐着吃完整套菜的那位客人，原来是米其林评审员。", vi: "Người ngồi lặng lẽ ăn hết cả suất tasting của chúng ta hôm thứ Ba tuần trước — hóa ra là thanh tra viên Michelin." },
      { speaker: "부주방장", kr: "정말요? 그날 딱히 특별한 서비스도 안 했는데, 오히려 다행이네요.", en: "Really? We didn't do anything particularly special that day — actually that's a relief.", ja: "本当ですか？あの日特に特別なサービスもしなかったのに、むしろよかったです。", zh: "真的吗？那天也没做什么特别的服务，反倒是好事。", vi: "Thật sao? Hôm đó chúng ta không làm gì đặc biệt cả — thực ra thế lại là điều đáng mừng." },
      { speaker: "셰프", kr: "그러니까요. 미리 알았으면 오히려 긴장해서 실수했을 것 같아요.", en: "Exactly. If we'd known in advance, we probably would've gotten nervous and made mistakes.", ja: "そうなんです。事前に知っていたら、むしろ緊張してミスしていたと思います。", zh: "就是啊。要是提前知道，恐怕反而会紧张出错。", vi: "Đúng vậy. Nếu biết trước, có lẽ chúng ta đã lo lắng và mắc sai sót." },
      { speaker: "부주방장", kr: "그래도 평소처럼 했다는 게 결국 저희 기본기가 흔들리지 않았다는 뜻이잖아요.", en: "Still, doing it as usual ultimately means our fundamentals didn't waver.", ja: "それでもいつも通りにできたということは、結局私たちの基本がぶれなかったということですよね。", zh: "不过按平时的水平来做，也说明我们的基本功没有动摇。", vi: "Dù sao thì làm như bình thường cuối cùng cũng có nghĩa là nền tảng của chúng ta không hề dao động." },
      { speaker: "셰프", kr: "맞아요. 평가라는 게 결국 특별한 날이 아니라 일상을 보는 거니까요.", en: "Right. Evaluation is ultimately about looking at the everyday, not a special occasion.", ja: "その通りです。評価というのは結局特別な日ではなく、日常を見るものですから。", zh: "对。评价说到底看的是日常，而不是特殊的某一天。", vi: "Đúng. Đánh giá suy cho cùng là nhìn vào cái thường ngày, chứ không phải một dịp đặc biệt." },
      { speaker: "부주방장", kr: "그럼 이번에 별을 받을 수도 있는 거예요?", en: "So does that mean we might actually get a star this time?", ja: "では今回星を取れる可能性もあるということですか？", zh: "那这次是不是有可能拿到星星？", vi: "Vậy có nghĩa là lần này chúng ta có thể thực sự nhận được một sao không?" },
      { speaker: "셰프", kr: "아직 발표 전이라 장담은 못 하지만, 적어도 부끄럽지 않은 하루였다는 건 확실해요.", en: "It hasn't been announced yet so I can't be sure, but at the very least it was a day we have nothing to be ashamed of.", ja: "まだ発表前なので断言はできませんが、少なくとも恥ずかしくない一日だったのは確かです。", zh: "还没公布，我不敢保证，但至少那天我们问心无愧，这一点是确定的。", vi: "Vẫn chưa được công bố nên tôi không thể chắc chắn, nhưng ít nhất đó là một ngày mà chúng ta chẳng có gì phải xấu hổ." },
    ],
  },
  {
    id: "restaurant-c2y-succession",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "A daughter debates taking over the family restaurant", ja: "娘が家業のレストランを継ぐか悩む", zh: "女儿纠结是否接手家族餐厅", vi: "Người con gái phân vân có nên tiếp quản nhà hàng gia đình" },
    lines: [
      { speaker: "딸", kr: "아버지, 저 이 식당을 물려받는 게 맞는 건지 요즘 계속 고민이 돼요. 제가 원해서라기보다는 떠밀리는 느낌이라서요.", en: "Dad, I keep wondering lately whether taking over this restaurant is really right for me. It feels less like something I want and more like I'm being pushed into it.", ja: "お父さん、私がこの店を継ぐのが正しいのか、最近ずっと悩んでいるの。自分が望んでいるというより、押し付けられている感じがして。", zh: "爸，最近我一直在想，接手这家店到底对不对。与其说是我自己想要的，不如说感觉是被推着走的。", vi: "Bố, dạo này con cứ tự hỏi liệu việc tiếp quản nhà hàng này có thực sự đúng với con không. Nó có cảm giác giống như bị đẩy vào chứ không phải điều con thực sự muốn." },
      { speaker: "아버지", kr: "떠민 적은 없다고 생각했는데, 네가 그렇게 느꼈다면 내가 부지불식간에 부담을 준 거겠지.", en: "I didn't think I'd pushed you, but if that's how you felt, then I must have unknowingly put pressure on you.", ja: "押し付けたつもりはなかったが、お前がそう感じたなら、私が知らず知らずのうちにプレッシャーをかけていたんだろうな。", zh: "我以为没逼过你，但既然你有这种感觉，那一定是我不知不觉中给了你压力。", vi: "Bố không nghĩ mình đã ép con, nhưng nếu con cảm thấy như vậy, thì chắc bố đã vô tình tạo áp lực cho con rồi." },
      { speaker: "딸", kr: "부담이라기보다는, 삼십 년 넘게 쌓아 오신 걸 제가 망치면 어떡하나 하는 두려움이 더 커요.", en: "It's less about pressure and more about the fear of what happens if I ruin what you've built over thirty-some years.", ja: "プレッシャーというより、三十年以上積み上げてきたものを私が壊してしまったらどうしようという恐れの方が大きいの。", zh: "与其说是压力，我更害怕的是万一把您三十多年积累的东西搞砸了怎么办。", vi: "Không hẳn là áp lực, mà là nỗi sợ nếu con làm hỏng những gì bố đã xây dựng suốt hơn ba mươi năm thì sao." },
      { speaker: "아버지", kr: "그 두려움 자체가 어쩌면 네가 이 일을 진지하게 생각하고 있다는 증거일지도 몰라. 무관심했다면 두렵지도 않았을 테니까.", en: "That very fear might be evidence that you're taking this seriously. If you were indifferent, you wouldn't be afraid at all.", ja: "その恐れ自体が、もしかしたらお前がこの仕事を真剣に考えている証拠かもしれない。無関心だったら怖くもなかっただろうから。", zh: "这种害怕本身，或许正说明你是认真在考虑这件事。如果你根本不在乎，就不会害怕了。", vi: "Chính nỗi sợ đó có thể là bằng chứng cho thấy con đang nghiêm túc với việc này. Nếu con thờ ơ thì con đã chẳng sợ chút nào rồi." },
      { speaker: "딸", kr: "그렇게 말씀해 주시니 조금은 위안이 되는데, 그래도 완전히 똑같이 이어받아야 한다는 압박감은 여전해요.", en: "Hearing you say that is somewhat comforting, but the pressure to carry it on exactly the same way still lingers.", ja: "そう言ってもらえると少し慰めになるけど、それでも完全に同じように引き継がなきゃという圧迫感は消えないの。", zh: "您这么说我稍微安心一点，但那种必须原样传承下去的压力还是在的。", vi: "Nghe bố nói vậy con cũng thấy an ủi phần nào, nhưng áp lực phải tiếp nối y hệt như cũ vẫn còn đó." },
      { speaker: "아버지", kr: "누가 똑같이 이어받으라고 했니. 나도 내 아버지 방식을 그대로 따르지 않았고, 시대가 바뀌면 방식도 바뀌어야지.", en: "Who said you have to carry it on exactly the same? I didn't follow my own father's methods exactly either — as times change, methods should change too.", ja: "誰が全く同じに継げと言った？私も自分の父のやり方をそのまま踏襲したわけじゃないし、時代が変われば方法も変わらないと。", zh: "谁说非要一模一样传下去了？我也没有完全照搬我父亲的方式，时代变了方法也该跟着变。", vi: "Ai bảo con phải tiếp nối y hệt như cũ? Bố cũng đâu có làm theo đúng cách của ông nội — thời thế thay đổi thì cách làm cũng nên thay đổi." },
      { speaker: "딸", kr: "그럼 제가 메뉴를 좀 손대거나 인테리어를 바꿔도 서운해하지 않으실 거예요?", en: "Then would you not be hurt if I changed the menu somewhat or renovated the interior?", ja: "じゃあ私がメニューを少しいじったり、内装を変えても寂しく思わない？", zh: "那如果我改改菜单或者装修，您不会觉得难受吗？", vi: "Vậy nếu con thay đổi thực đơn phần nào hoặc sửa lại nội thất, bố sẽ không thấy tổn thương chứ?" },
      { speaker: "아버지", kr: "서운함보다는 궁금함이 앞설 것 같구나. 네가 만들어갈 다음 삼십 년이 어떤 모습일지.", en: "Curiosity would come before any hurt feelings, I think — I'd be curious what shape the next thirty years you build will take.", ja: "寂しさより好奇心の方が先に来ると思うよ。お前が作っていく次の三十年がどんな姿になるのか。", zh: "比起难受，我更多的会是好奇——想看看你接下来创造的三十年会是什么样子。", vi: "Bố nghĩ sự tò mò sẽ đến trước cả cảm giác tổn thương — bố sẽ tò mò xem ba mươi năm tiếp theo mà con xây dựng sẽ có hình dáng ra sao." },
      { speaker: "딸", kr: "그 말씀 들으니 오히려 용기가 나네요. 한번 진지하게 준비해 볼게요.", en: "Hearing that actually gives me courage. I'll seriously start preparing for it.", ja: "その言葉を聞いたら、むしろ勇気が出るわ。一度真剣に準備してみる。", zh: "听您这么说，我反而有勇气了。我会认真准备的。", vi: "Nghe bố nói vậy con thấy có thêm can đảm rồi. Con sẽ bắt đầu chuẩn bị nghiêm túc cho việc đó." },
    ],
  },
  {
    id: "restaurant-c2y-review-fallout",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "The fallout from a scathing online review", ja: "辛辣なオンラインレビューの余波", zh: "一篇尖锐网评引发的风波", vi: "Hậu quả từ một bài đánh giá trực tuyến gay gắt" },
    lines: [
      { speaker: "사장", kr: "그 리뷰 보셨어요? '가격만 비싸고 정성은 없다'는 표현이 이렇게까지 퍼질 줄은 몰랐네요.", en: "Did you see that review? I never expected the phrase 'overpriced with no real effort' to spread this far.", ja: "あのレビュー見ましたか？「値段だけ高くて心がこもっていない」という表現がここまで広がるとは思いませんでした。", zh: "看到那条评论了吗？没想到“价格贵却毫无用心”这句话会传得这么广。", vi: "Anh xem bài đánh giá đó chưa? Tôi không ngờ câu 'đắt đỏ mà chẳng có nỗ lực gì thực sự' lại lan rộng đến thế." },
      { speaker: "홍보팀장", kr: "저도 놀랐어요. 근데 댓글을 자세히 읽어 보면, 그날 유독 예약이 몰려서 대응이 늦었던 게 화근인 것 같아요.", en: "I was surprised too. But if you read the comments closely, it seems the real trigger was that reservations were unusually backed up that day, delaying our response.", ja: "私も驚きました。でもコメントをよく読むと、あの日特に予約が集中して対応が遅れたのが火種だったようです。", zh: "我也很意外。不过仔细看留言，那天预约特别多导致响应不及时，好像是导火索。", vi: "Tôi cũng bất ngờ. Nhưng nếu đọc kỹ các bình luận, có vẻ nguyên nhân thực sự là hôm đó lượng đặt bàn dồn lại bất thường, khiến chúng ta phản hồi chậm." },
      { speaker: "사장", kr: "이유야 어쨌든, 손님 입장에서는 변명으로밖에 안 들릴 거예요. 일단 공개 사과문부터 올려야 할까요?", en: "Whatever the reason, from the customer's perspective it'll only sound like an excuse. Should we post a public apology first?", ja: "理由がどうであれ、お客様の立場からすれば言い訳にしか聞こえないでしょう。とりあえず公開謝罪文から出すべきでしょうか？", zh: "不管原因是什么，从顾客角度看只会觉得是借口。要不要先发个公开道歉声明？", vi: "Dù lý do gì đi nữa, từ góc nhìn của khách hàng thì cũng chỉ nghe như lời bào chữa thôi. Chúng ta có nên đăng lời xin lỗi công khai trước không?" },
      { speaker: "홍보팀장", kr: "성급하게 사과문부터 올리면 오히려 불난 집에 부채질하는 격이 될 수도 있어요. 먼저 그 손님께 개인적으로 연락드려서 상황을 파악하는 게 순서일 것 같아요.", en: "Rushing to post an apology first could actually fan the flames. I think reaching out to that customer personally first to understand the situation is the right order of operations.", ja: "急いで謝罪文から出すと、むしろ火に油を注ぐことになりかねません。まずその客様に個人的に連絡して状況を把握するのが順序だと思います。", zh: "急着先发道歉声明反而可能火上浇油。我觉得应该先私下联系那位客人，了解情况，这才是正确的顺序。", vi: "Vội vàng đăng lời xin lỗi trước có thể thực ra lại thổi bùng ngọn lửa. Tôi nghĩ liên hệ trực tiếp với vị khách đó trước để hiểu tình huống mới là thứ tự đúng." },
      { speaker: "사장", kr: "일리 있네요. 근데 이미 캡처가 퍼진 상태라 침묵도 부정적으로 비칠까 봐 걱정돼요.", en: "That makes sense. But since screenshots have already spread, I'm worried silence might also be perceived negatively.", ja: "一理ありますね。でも既にスクリーンショットが広まっている状態なので、沈黙も悪く映るんじゃないかと心配です。", zh: "有道理。不过截图已经传开了，我担心沉默也会被解读成负面信号。", vi: "Nghe có lý. Nhưng vì ảnh chụp màn hình đã lan truyền rồi, tôi lo im lặng cũng có thể bị hiểu theo hướng tiêu cực." },
      { speaker: "홍보팀장", kr: "그래서 짧게라도 '확인 중이며 곧 답변드리겠다'는 안내는 남기고, 실제 사과는 사실관계를 파악한 후에 하는 게 낫습니다.", en: "That's why we should leave at least a brief note saying we're looking into it and will respond soon, and issue the actual apology only after we've confirmed the facts.", ja: "だから短くても「確認中で、まもなくご回答します」という案内は残して、実際の謝罪は事実関係を把握した後にする方がいいです。", zh: "所以哪怕简短，也应该留言说“正在核实，会尽快回复”，实际的道歉要等确认了事实关系之后再做。", vi: "Vì vậy chúng ta nên để lại ít nhất một dòng ngắn nói rằng chúng ta đang xem xét và sẽ phản hồi sớm, còn lời xin lỗi chính thức thì chỉ đưa ra sau khi đã xác nhận sự việc." },
      { speaker: "사장", kr: "알겠어요. 감정적으로 대응하지 않고 순서대로 밟아가 보죠.", en: "Understood. Let's proceed step by step without reacting emotionally.", ja: "分かりました。感情的に対応せず、順番通りに進めていきましょう。", zh: "明白了。不要情绪化应对，按步骤来吧。", vi: "Hiểu rồi. Hãy tiến hành từng bước một, không phản ứng theo cảm xúc." },
      { speaker: "홍보팀장", kr: "이번 일을 계기로 바쁜 시간대 응대 매뉴얼도 다시 점검해야 할 것 같고요.", en: "This incident should also be a chance to review our response manual for busy hours.", ja: "この件をきっかけに、忙しい時間帯の対応マニュアルも見直すべきだと思います。", zh: "借这次事件，我们也应该重新检视一下高峰时段的应对手册。", vi: "Sự việc lần này cũng nên là dịp để chúng ta rà soát lại quy trình xử lý vào giờ cao điểm." },
      { speaker: "사장", kr: "맞아요. 위기가 곧 점검의 기회라는 말이 이럴 때 쓰는 거겠죠.", en: "True. This must be exactly the situation the saying 'a crisis is also a chance to review' was made for.", ja: "そうですね。「危機はすなわち見直しの機会」という言葉はこういう時に使うんでしょうね。", zh: "对啊。“危机也是复盘的机会”这句话大概就是用在这种时候的。", vi: "Đúng vậy. Đây hẳn chính là tình huống mà câu nói 'khủng hoảng cũng là cơ hội để nhìn lại' được sinh ra." },
    ],
  },
  {
    id: "restaurant-c2y-critic-anonymity",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "A literary essay on the vanishing anonymous critic", ja: "消えゆく匿名批評家をめぐる文芸エッセイ", zh: "一篇关于消失的匿名评论家的散文", vi: "Một bài tiểu luận văn học về nhà phê bình ẩn danh đang biến mất" },
    lines: [
      { speaker: "작가A", kr: "요즘 맛집 리뷰라는 게 결국 팔로워 수와 협찬 여부로 좌우되는 것 같아서, 익명 비평가의 순수성이라는 게 이제 신화에 가깝다는 생각이 들어요.", en: "These days restaurant reviews seem entirely governed by follower counts and sponsorships, so the purity of the anonymous critic feels almost like a myth now.", ja: "最近のグルメレビューは結局フォロワー数とスポンサーの有無で左右されているようで、匿名批評家の純粋性というものはもう神話に近いと思うんです。", zh: "现在的美食评论似乎完全由粉丝数和赞助与否决定，匿名评论家的纯粹性感觉已经近乎神话了。", vi: "Dạo này các bài đánh giá nhà hàng có vẻ hoàn toàn bị chi phối bởi số lượng người theo dõi và tài trợ, nên sự trong sạch của nhà phê bình ẩn danh gần như trở thành một huyền thoại rồi." },
      { speaker: "작가B", kr: "신화라기보다는, 그 역할이 다른 방식으로 분산됐다고 보는 게 더 정확하지 않을까요. 누구나 카메라를 들 수 있는 시대니까요.", en: "Rather than a myth, wouldn't it be more accurate to say that role has simply been redistributed in a different form? After all, anyone can hold a camera now.", ja: "神話というより、その役割が別の形で分散したと見る方が正確じゃないでしょうか。誰でもカメラを持てる時代ですから。", zh: "与其说是神话，不如说是那种角色以别的方式被分散了，这样说是不是更准确？毕竟现在人人都能拿起相机。", vi: "Thay vì gọi là huyền thoại, chẳng phải chính xác hơn nếu nói rằng vai trò đó chỉ đơn giản là được phân bổ lại dưới một hình thức khác sao? Suy cho cùng bây giờ ai cũng có thể cầm máy quay." },
      { speaker: "작가A", kr: "분산됐다는 말도 맞지만, 그만큼 책임 소재도 흐려졌어요. 예전엔 한 사람의 서명이 신뢰를 담보했는데, 지금은 익명의 파도 속에서 누구도 책임지지 않죠.", en: "'Redistributed' is fair, but accountability has blurred just as much. In the past, one person's byline guaranteed trust; now, within a wave of anonymity, no one is accountable.", ja: "分散したという言葉も正しいですが、それだけ責任の所在も曖昧になりました。昔は一人の署名が信頼を担保していましたが、今は匿名の波の中で誰も責任を負いません。", zh: "分散这个说法没错，但责任归属也因此变得模糊了。以前一个人的署名就能担保信任，现在在匿名的浪潮里谁都不用负责。", vi: "'Phân bổ lại' thì đúng, nhưng trách nhiệm giải trình cũng mờ nhạt đi tương ứng. Trước đây, tên tuổi của một người đảm bảo sự tin cậy; giờ đây, trong làn sóng ẩn danh, không ai chịu trách nhiệm cả." },
      { speaker: "작가B", kr: "그 지적은 뼈아프네요. 다만 저는 오히려 다수의 목소리가 한 사람의 권위보다 왜곡을 줄일 수도 있다고 봐요.", en: "That's a painful point. Still, I'd say multiple voices might actually reduce distortion more than a single person's authority.", ja: "その指摘は痛いですね。ただ私はむしろ多数の声の方が、一人の権威より歪みを減らせるかもしれないと思っています。", zh: "这一点戳得挺痛。不过我觉得众多声音反而可能比一个人的权威更能减少扭曲。", vi: "Đó là một điểm đau đấy. Dù vậy, tôi cho rằng nhiều tiếng nói có khi lại làm giảm sự sai lệch hơn là quyền uy của một cá nhân." },
      { speaker: "작가A", kr: "다수라는 것도 결국 알고리즘이 선별한 다수일 뿐이라는 게 함정이죠. 진짜 다양성이 아니라 증폭된 편향일 수도 있고요.", en: "The trap is that 'multiple voices' is ultimately just a multitude curated by an algorithm. It could be amplified bias rather than genuine diversity.", ja: "多数というものも結局アルゴリズムが選別した多数に過ぎないというのが罠ですね。本当の多様性ではなく、増幅された偏りかもしれません。", zh: "问题在于，所谓“众多声音”说到底也只是算法筛选出来的多数罢了。这可能不是真正的多样性，而是被放大的偏见。", vi: "Cái bẫy ở chỗ 'nhiều tiếng nói' cuối cùng cũng chỉ là số đông được thuật toán chọn lọc. Đó có thể là thiên kiến được khuếch đại chứ không phải sự đa dạng thực sự." },
      { speaker: "작가B", kr: "그렇다면 우리가 향수를 느끼는 대상은 익명성 자체가 아니라, 그 익명성을 지탱했던 편집자의 신뢰 체계인 셈이네요.", en: "Then what we're nostalgic for isn't anonymity itself, but the editorial system of trust that once sustained that anonymity.", ja: "そうだとすれば、私たちが郷愁を感じる対象は匿名性そのものではなく、その匿名性を支えていた編集者の信頼体系というわけですね。", zh: "那么我们怀念的其实不是匿名本身，而是曾经支撑那种匿名性的编辑信任体系。", vi: "Vậy thì điều chúng ta đang hoài niệm không phải là bản thân sự ẩn danh, mà là hệ thống biên tập đáng tin cậy từng nâng đỡ sự ẩn danh đó." },
      { speaker: "작가A", kr: "정확히 짚으셨어요. 결국 문제는 익명이냐 아니냐가 아니라, 누가 그 목소리에 책임을 지느냐인 거죠.", en: "You've hit it exactly. In the end the question isn't anonymity or not, but who takes responsibility for that voice.", ja: "まさにその通りです。結局問題は匿名かどうかではなく、誰がその声に責任を負うかということですね。", zh: "您说到点子上了。归根结底问题不在于匿名与否，而在于谁来为那种声音负责。", vi: "Anh nói trúng phóc. Cuối cùng câu hỏi không phải là ẩn danh hay không, mà là ai chịu trách nhiệm cho tiếng nói đó." },
      { speaker: "작가B", kr: "이 논의를 칼럼으로 정리해 보면 어떨까요. 제목은 '사라진 비평가, 흩어진 책임' 정도로요.", en: "Why don't we write this discussion up as a column? Maybe titled something like 'The Vanished Critic, Scattered Accountability.'", ja: "この議論をコラムにまとめてみませんか？タイトルは「消えた批評家、散った責任」くらいで。", zh: "要不我们把这次讨论整理成一篇专栏文章吧？标题就叫《消失的评论家，散落的责任》怎么样。", vi: "Sao chúng ta không viết cuộc thảo luận này thành một bài chuyên mục nhỉ? Có thể đặt tựa đề đại loại 'Nhà phê bình đã biến mất, trách nhiệm bị phân tán'." },
      { speaker: "작가A", kr: "좋아요. 다만 결론은 냉소로 끝내지 말고, 새로운 신뢰 체계의 가능성을 열어두는 쪽으로 갑시다.", en: "I like that. But let's not end the conclusion on cynicism — let's leave it open to the possibility of a new system of trust.", ja: "いいですね。ただ結論は皮肉で終わらせず、新しい信頼体系の可能性を開いておく方向にしましょう。", zh: "好啊。不过结论不要以冷嘲收尾，留一个新信任体系的可能性给读者吧。", vi: "Tôi thích ý đó. Nhưng đừng kết thúc bằng sự hoài nghi — hãy để ngỏ khả năng cho một hệ thống tin cậy mới." },
    ],
  },
  {
    id: "restaurant-c2y-generational-palate",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "Debating whether younger palates are losing depth", ja: "若い世代の味覚が浅くなっているのか議論する", zh: "争论年轻一代的味觉是否变浅了", vi: "Tranh luận liệu vị giác của thế hệ trẻ có đang mất chiều sâu" },
    lines: [
      { speaker: "노셰프", kr: "요즘 젊은 손님들은 자극적인 맛에만 반응하고, 은근한 감칠맛이나 여운은 잘 못 느끼는 것 같아 안타까워요.", en: "It's a shame that young customers these days only seem to respond to intense flavors and don't really pick up on subtle umami or lingering aftertaste.", ja: "最近の若いお客さんは刺激的な味にしか反応せず、微妙な旨味や余韻をあまり感じられないようで残念です。", zh: "最近的年轻顾客好像只对刺激的味道有反应，很难感受到细腻的鲜味或余韵，挺可惜的。", vi: "Thật đáng tiếc khi khách hàng trẻ dạo này có vẻ chỉ phản ứng với hương vị đậm đà, và không thực sự cảm nhận được vị umami tinh tế hay dư vị kéo dài." },
      { speaker: "젊은셰프", kr: "저는 조금 다르게 봐요. 못 느끼는 게 아니라, 접해 볼 기회 자체가 적었던 게 아닐까요.", en: "I see it a bit differently. Maybe it's not that they can't sense it, but that they simply haven't had many opportunities to encounter it.", ja: "私は少し違う見方をします。感じられないのではなく、単に触れる機会自体が少なかったのではないでしょうか。", zh: "我的看法有点不一样。不是感受不到，而是他们本来接触这种味道的机会就少。", vi: "Tôi nhìn nhận hơi khác một chút. Có lẽ không phải họ không cảm nhận được, mà đơn giản là họ chưa có nhiều cơ hội để tiếp xúc với nó." },
      { speaker: "노셰프", kr: "기회가 없었다는 건 결국 우리 세대가 그 감각을 제대로 물려주지 못했다는 뜻이겠네요.", en: "If they haven't had the opportunity, that ultimately means our generation failed to properly pass down that sensibility.", ja: "機会がなかったというのは、結局私たちの世代がその感覚をきちんと伝えられなかったということですね。", zh: "没有机会，说到底就是我们这一代没能好好把那种感觉传承下去。", vi: "Nếu họ chưa có cơ hội, thì cuối cùng điều đó có nghĩa là thế hệ chúng ta đã không truyền tải được cảm quan đó một cách đúng đắn." },
      { speaker: "젊은셰프", kr: "물려주지 못했다기보다는, 전달 방식이 달라져야 했던 거죠. 긴 설명보다는 경험을 통해 스며들게 하는 방식이요.", en: "It's less that it wasn't passed down and more that the method of transmission needed to change — letting it seep in through experience rather than long explanations.", ja: "伝えられなかったというより、伝え方が変わるべきだったんです。長い説明よりも経験を通してしみ込ませる方法がいいんです。", zh: "与其说没传下去，不如说传递方式需要改变——比起长篇解释,通过体验去慢慢渗透更好。", vi: "Không hẳn là không được truyền lại, mà là cách truyền tải cần thay đổi — để nó thấm dần qua trải nghiệm thay vì giải thích dài dòng." },
      { speaker: "노셰프", kr: "그 말도 일리는 있지만, 결국 미각도 훈련인데 자극적인 맛에만 길들면 섬세한 맛을 구분하는 능력 자체가 퇴화하지 않을까요.", en: "That has a point, but taste is ultimately trained too — if people only get accustomed to intense flavors, wouldn't the ability to distinguish subtle flavors itself atrophy?", ja: "その言葉も一理ありますが、結局味覚も訓練であって、刺激的な味だけに慣れたら繊細な味を区別する能力自体が退化しないでしょうか。", zh: "这话也有道理，但味觉终究也是训练出来的，只习惯刺激的味道，分辨细腻味道的能力不会退化吗？", vi: "Điều đó có lý, nhưng vị giác suy cho cùng cũng được huấn luyện — nếu chỉ quen với hương vị đậm đà, chẳng phải khả năng phân biệt hương vị tinh tế cũng sẽ dần thoái hóa sao?" },
      { speaker: "젊은셰프", kr: "퇴화라기보다는 취향의 이동이라고 보고 싶어요. 다만 선생님 말씀처럼 그 안에서도 깊이를 잃지 않도록 저희가 신경 써야겠죠.", en: "I'd rather call it a shift in taste rather than atrophy. Though as you say, we do need to make sure not to lose depth within that shift.", ja: "退化というより好みの移動と見たいです。ただ先生のおっしゃる通り、その中でも深みを失わないよう私たちが気を配らないといけませんね。", zh: "与其说是退化，我更愿意称之为口味的迁移。不过正如您说的，在这个过程中我们也得留心不能失去深度。", vi: "Tôi thà gọi đó là sự dịch chuyển khẩu vị hơn là thoái hóa. Dù đúng như anh nói, chúng ta cũng cần đảm bảo không đánh mất chiều sâu trong sự dịch chuyển đó." },
      { speaker: "노셰프", kr: "결국 우리가 할 일은 판단이 아니라 다리를 놓는 거겠지. 자극과 섬세함 사이의.", en: "In the end, what we should do isn't judge but build a bridge — between intensity and subtlety.", ja: "結局私たちがすべきことは判断ではなく、橋をかけることだろうね。刺激と繊細さの間の。", zh: "说到底我们要做的不是评判，而是架桥——在刺激和细腻之间架一座桥。", vi: "Cuối cùng, điều chúng ta nên làm không phải là phán xét mà là xây một cây cầu — giữa sự đậm đà và sự tinh tế." },
      { speaker: "젊은셰프", kr: "동의해요. 오늘 코스에 그 다리 하나 놓아볼게요. 처음은 자극적으로, 마지막은 여운으로 마무리하는 구성으로요.", en: "Agreed. Let me build that bridge into today's course — starting bold and finishing on a lingering note.", ja: "同意です。今日のコースにその橋を一つかけてみます。最初は刺激的に、最後は余韻で締めくくる構成で。", zh: "我同意。今天的套餐我就来架一座这样的桥——开头刺激，结尾以余韵收束。", vi: "Đồng ý. Để tôi đưa cây cầu đó vào suất ăn hôm nay — bắt đầu táo bạo và kết thúc bằng dư vị lắng đọng." },
      { speaker: "노셰프", kr: "기대되는구나. 그 구성, 나도 한 접시 먹어보고 싶다.", en: "That's something to look forward to. I'd like to have a plate of that composition myself.", ja: "楽しみだね。その構成、私も一皿食べてみたいよ。", zh: "真让人期待。这样的组合，我也想尝一盘。", vi: "Đó là điều đáng mong chờ đấy. Tôi cũng muốn tự mình thưởng thức một đĩa như thế." },
    ],
  },
  {
    id: "restaurant-c2y-labor-dispute",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "A tense negotiation over service-charge distribution", ja: "サービス料分配をめぐる緊迫した交渉", zh: "关于服务费分配的紧张谈判", vi: "Cuộc đàm phán căng thẳng về phân chia phí dịch vụ" },
    lines: [
      { speaker: "노조대표", kr: "서비스료가 매출의 십 퍼센트나 되는데, 그중 절반 이상이 관리직에게 돌아간다는 건 형평성에 어긋난다고 봅니다.", en: "Service charges amount to ten percent of revenue, and the fact that more than half of that goes to management strikes us as fundamentally inequitable.", ja: "サービス料が売上の十パーセントにもなるのに、その半分以上が管理職に回るというのは公平性に反すると思います。", zh: "服务费占营业额的百分之十，其中一半以上却分给管理层，我们认为这明显有失公平。", vi: "Phí dịch vụ chiếm mười phần trăm doanh thu, và việc hơn một nửa số đó đi vào tay ban quản lý khiến chúng tôi thấy về cơ bản là bất công." },
      { speaker: "사장", kr: "관리직도 결국 서비스 품질을 유지하기 위해 뒤에서 조율하는 역할을 하고 있어서, 완전히 배제하기는 어렵습니다.", en: "Management also plays a coordinating role behind the scenes to maintain service quality, so completely excluding them is difficult.", ja: "管理職も結局サービスの質を維持するために裏で調整する役割をしているので、完全に除外するのは難しいです。", zh: "管理层为了维持服务质量，也在幕后承担协调的角色，完全排除他们很困难。", vi: "Ban quản lý cũng đóng vai trò điều phối phía sau hậu trường để duy trì chất lượng dịch vụ, nên việc loại trừ hoàn toàn họ là điều khó khăn." },
      { speaker: "노조대표", kr: "조율의 가치를 부정하는 게 아니라, 손님과 직접 접촉하며 팁의 근거를 만드는 건 결국 홀 직원과 주방 직원이라는 겁니다.", en: "We're not denying the value of coordination — but ultimately it's the floor staff and kitchen staff who directly interact with customers and generate the basis for that service charge.", ja: "調整の価値を否定しているわけではなく、お客様と直接接してチップの根拠を作るのは結局ホールスタッフと厨房スタッフだということです。", zh: "我们不是否定协调的价值，而是说直接接触顾客、创造服务费依据的终究是前厅和厨房员工。", vi: "Chúng tôi không phủ nhận giá trị của việc điều phối — nhưng cuối cùng chính nhân viên phục vụ và bếp là những người trực tiếp tiếp xúc với khách hàng và tạo ra nền tảng cho phí dịch vụ đó." },
      { speaker: "사장", kr: "그 지적은 타당합니다. 다만 분배 비율을 급격히 바꾸면 관리직의 이탈로 이어질 수 있다는 우려도 이해해 주셨으면 합니다.", en: "That point is valid. But I'd ask you to also understand the concern that a sudden change in the distribution ratio could lead to management turnover.", ja: "その指摘は妥当です。ただ分配比率を急激に変えると管理職の離職につながりかねないという懸念も理解していただきたいです。", zh: "这个说法是合理的。但也希望您能理解，如果分配比例骤然改变，可能会导致管理层流失，这一点我们也担心。", vi: "Điểm đó là hợp lý. Nhưng tôi muốn anh/chị hiểu thêm mối lo rằng thay đổi tỷ lệ phân chia đột ngột có thể dẫn đến việc quản lý nghỉ việc hàng loạt." },
      { speaker: "노조대표", kr: "이탈이 걱정되신다면, 급여 체계 자체를 분리해서 서비스료는 온전히 현장 직원에게, 관리직은 기본급 인상으로 보완하는 방안은 어떻습니까.", en: "If turnover is the concern, how about separating the pay structures entirely — the service charge goes fully to front-line staff, while management is compensated through a base-salary increase instead?", ja: "離職が心配なら、給与体系自体を分離して、サービス料は完全に現場スタッフに、管理職は基本給の引き上げで補う案はどうですか。", zh: "如果担心流失，不如把薪资体系彻底分开——服务费全归一线员工，管理层则通过提高底薪来补偿，这个方案如何？", vi: "Nếu mối lo là việc nghỉ việc, sao không tách hoàn toàn cơ cấu lương — phí dịch vụ chuyển hết cho nhân viên tuyến đầu, còn ban quản lý được bù đắp bằng cách tăng lương cơ bản?" },
      { speaker: "사장", kr: "흥미로운 제안이네요. 다만 그렇게 하면 인건비 총액 자체가 늘어날 텐데, 그 부분은 어떻게 감당할지 논의가 필요합니다.", en: "That's an interesting proposal. But that would increase the total labor cost, so we'd need to discuss how to absorb that.", ja: "興味深い提案ですね。ただそうすると人件費の総額自体が増えるはずで、その部分をどう負担するか議論が必要です。", zh: "这个提议很有意思。但那样的话人工成本总额会增加，这部分怎么承担还需要讨论。", vi: "Đó là một đề xuất thú vị. Nhưng điều đó sẽ làm tăng tổng chi phí nhân công, nên chúng ta cần bàn cách hấp thụ khoản đó." },
      { speaker: "노조대표", kr: "그 논의, 저희도 함께 하고 싶습니다. 일방적인 통보가 아니라 공동으로 방안을 짜는 게 이번 갈등의 진짜 해법이라고 봅니다.", en: "We'd like to be part of that discussion too. We believe the real solution to this conflict is jointly designing the plan, not a one-sided announcement.", ja: "その議論、私たちも一緒にしたいです。一方的な通告ではなく、共同で方策を練るのが今回の対立の本当の解決策だと思います。", zh: "这个讨论，我们也想一起参与。我们认为共同制定方案，而不是单方面宣布，才是解决这次矛盾的真正办法。", vi: "Chúng tôi cũng muốn tham gia vào cuộc thảo luận đó. Chúng tôi tin rằng giải pháp thực sự cho xung đột này là cùng nhau thiết kế kế hoạch, chứ không phải một thông báo đơn phương." },
      { speaker: "사장", kr: "동의합니다. 다음 주에 재무 자료를 공유하고 함께 시뮬레이션을 돌려보죠.", en: "Agreed. Let's share the financial data next week and run the simulations together.", ja: "同意します。来週財務資料を共有して一緒にシミュレーションをしてみましょう。", zh: "同意。下周我们共享财务数据，一起做模拟测算吧。", vi: "Đồng ý. Tuần sau hãy chia sẻ dữ liệu tài chính và cùng nhau chạy các mô phỏng." },
      { speaker: "노조대표", kr: "감사합니다. 이렇게 마주 앉아 논의할 수 있다는 것 자체가 이미 큰 진전이라고 생각합니다.", en: "Thank you. The fact that we can sit down and discuss this face to face is itself already significant progress.", ja: "ありがとうございます。こうして向き合って議論できること自体が、すでに大きな進展だと思います。", zh: "谢谢您。能这样面对面坐下来讨论，本身就已经是很大的进步了。", vi: "Cảm ơn. Việc chúng ta có thể ngồi lại và thảo luận trực tiếp thế này tự nó đã là một bước tiến đáng kể rồi." },
    ],
  },
  {
    id: "restaurant-c2y-closing-legacy",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "An owner reflects on closing a forty-year restaurant", ja: "四十年続いた店の閉店を振り返るオーナー", zh: "老板回顾结束四十年餐厅经营", vi: "Chủ nhà hàng suy ngẫm về việc đóng cửa nhà hàng bốn mươi năm" },
    lines: [
      { speaker: "기자", kr: "사십 년 동안 운영해 오신 식당을 이번 달에 정리하신다고 들었는데, 소회가 남다르실 것 같습니다.", en: "I heard you're closing the restaurant you've run for forty years this month — I imagine your feelings must be quite complex.", ja: "四十年間運営されてきたお店を今月閉められると聞きましたが、感慨もひとしおでしょうね。", zh: "听说您经营了四十年的餐厅这个月要结束了，想必心情很复杂吧。", vi: "Tôi nghe nói tháng này anh/chị đóng cửa nhà hàng đã vận hành suốt bốn mươi năm — chắc cảm xúc của anh/chị phải khá phức tạp." },
      { speaker: "사장", kr: "솔직히 말씀드리면, 슬픔보다는 안도감이 먼저 밀려오더라고요. 그게 오히려 저 스스로도 놀랐습니다.", en: "Honestly, relief washed over me before sadness did. That surprised even me.", ja: "正直に申しますと、悲しみより安堵感が先に押し寄せてきました。それが自分でも驚きでした。", zh: "老实说，比起悲伤，先涌上来的是一种安心感。这连我自己都感到意外。", vi: "Thành thật mà nói, cảm giác nhẹ nhõm ập đến trước cả nỗi buồn. Điều đó khiến chính tôi cũng bất ngờ." },
      { speaker: "기자", kr: "안도감이라니 뜻밖이네요. 보통은 애착 때문에 정리가 더 어려울 거라고 생각했는데요.", en: "Relief is unexpected. I would have thought attachment would make closing it even harder.", ja: "安堵感とは意外ですね。普通は愛着があるから閉めるのがもっと難しいと思っていました。", zh: "安心感真是出乎意料。一般会觉得因为有感情，收摊会更难才对。", vi: "Nhẹ nhõm thì thật bất ngờ. Tôi cứ nghĩ sự gắn bó sẽ khiến việc đóng cửa càng khó khăn hơn." },
      { speaker: "사장", kr: "애착이 없다는 게 아니라, 이 애착을 짐처럼 짊어지고 억지로 이어가는 게 오히려 이 공간에 대한 모독이라는 생각이 들었어요.", en: "It's not that I lack attachment — it's that carrying this attachment like a burden and forcing it to continue felt like an insult to the place itself.", ja: "愛着がないというわけではなく、この愛着を重荷のように背負って無理に続けることが、むしろこの場所への冒涜だという考えに至ったんです。", zh: "不是没有感情，而是觉得把这份感情当作负担硬撑下去，反而是对这个地方的一种亵渎。", vi: "Không phải là tôi thiếu sự gắn bó — mà là việc cứ mang sự gắn bó đó như một gánh nặng rồi ép nó tiếp tục cảm giác như một sự xúc phạm đối với chính nơi này." },
      { speaker: "기자", kr: "모독이라는 표현이 인상적이네요. 조금 더 설명해 주실 수 있을까요.", en: "That word 'insult' is striking. Could you elaborate a bit more?", ja: "冒涜という表現が印象的ですね。もう少し説明していただけますか。", zh: "亵渎这个说法很有冲击力。可以再详细说说吗？", vi: "Từ 'xúc phạm' nghe khá ấn tượng. Anh/chị có thể nói rõ hơn một chút không?" },
      { speaker: "사장", kr: "이 자리가 저에게 준 건 생계 이상의 의미였는데, 체력도 예전 같지 않고 열정도 예전만큼 뜨겁지 않은 채로 간판만 유지하는 건 그 세월을 배신하는 것 같았습니다.", en: "This place gave me something beyond just a livelihood — and keeping the sign up while my stamina isn't what it used to be and my passion isn't as fiery felt like a betrayal of those years.", ja: "この場所が私に与えてくれたのは生計以上の意味でした。体力も以前のようではなく、情熱も昔ほど熱くないまま看板だけ維持するのは、あの歳月への裏切りのように感じたんです。", zh: "这个地方给我的意义不只是生计。体力已不如从前，热情也没有当年那么炽热，光是保留招牌苦撑，感觉像是背叛了那段岁月。", vi: "Nơi này đã cho tôi nhiều hơn cả một kế sinh nhai — và việc treo biển hiệu lên trong khi sức khỏe không còn như xưa và đam mê không còn cháy bỏng nữa có cảm giác như phản bội những năm tháng đó." },
      { speaker: "기자", kr: "그럼 폐업 이후에는 어떤 계획이 있으신가요.", en: "So what plans do you have after closing?", ja: "では閉店後はどんな計画がありますか。", zh: "那结业之后有什么打算吗？", vi: "Vậy anh/chị có kế hoạch gì sau khi đóng cửa không?" },
      { speaker: "사장", kr: "당장은 계획이랄 게 없어요. 다만 이 자리를 완전히 지우기보다는, 단골 손님들과의 마지막 저녁을 기록으로 남기고 싶습니다.", en: "I don't really have a plan for right now. But rather than erasing this place entirely, I'd like to leave a record of the final dinners with regular customers.", ja: "今すぐの計画というのはありません。ただこの場所を完全に消すというより、常連のお客様との最後の夕食を記録として残したいです。", zh: "眼下没什么具体计划。只是与其把这里彻底抹去，我更想把和老顾客们最后的晚餐留下记录。", vi: "Tôi thực sự chưa có kế hoạch cụ thể ngay bây giờ. Nhưng thay vì xóa bỏ hoàn toàn nơi này, tôi muốn để lại một ghi chép về những bữa tối cuối cùng với các khách quen." },
      { speaker: "기자", kr: "그 기록이 나중에 어떤 형태로든 이 식당의 유산이 되겠네요.", en: "That record will likely become this restaurant's legacy in some form down the line.", ja: "その記録が後にどんな形であれ、この店の遺産になるでしょうね。", zh: "那份记录以后无论以什么形式，都会成为这家餐厅的遗产吧。", vi: "Ghi chép đó có lẽ sẽ trở thành di sản của nhà hàng này dưới một hình thức nào đó sau này." },
      { speaker: "사장", kr: "그렇게 남아준다면 더 바랄 게 없겠습니다.", en: "If it can remain that way, I couldn't ask for anything more.", ja: "そうやって残ってくれるなら、これ以上望むことはありません。", zh: "如果能这样留下来，我就没什么可奢求的了。", vi: "Nếu nó có thể tồn tại theo cách đó, tôi không mong gì hơn thế." },
    ],
  },
  {
    id: "restaurant-c2y-food-media-ethics",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "A panel debates paid placements in food media", ja: "パネルディスカッション：グルメメディアの有料掲載", zh: "小组讨论美食媒体的付费植入", vi: "Một hội thảo bàn về quảng cáo trả phí trong truyền thông ẩm thực" },
    lines: [
      { speaker: "진행자", kr: "오늘 주제는 맛집 콘텐츠의 유료 광고 표기 문제입니다. 먼저 이 문제를 어떻게 보시는지 여쭙고 싶습니다.", en: "Today's topic is the issue of paid-ad disclosure in restaurant content. First, I'd like to ask how you view this problem.", ja: "今日のテーマはグルメコンテンツの有料広告表記の問題です。まずこの問題をどう見ていらっしゃるか伺いたいです。", zh: "今天的主题是美食内容的有偿广告标注问题。首先想请教两位怎么看待这个问题。", vi: "Chủ đề hôm nay là vấn đề công bố quảng cáo trả phí trong nội dung nhà hàng. Trước tiên, tôi muốn hỏi anh/chị nhìn nhận vấn đề này thế nào." },
      { speaker: "평론가", kr: "표기 자체는 법적으로 의무화됐지만, 실제로는 협찬 여부와 별개로 평가의 진정성이 훼손되는 경우가 더 문제라고 봅니다.", en: "Disclosure itself is now legally mandatory, but I think the bigger problem is that the sincerity of the evaluation is compromised regardless of whether it's labeled.", ja: "表記自体は法的に義務化されていますが、実際には協賛の有無とは別に評価の真正性が損なわれるケースの方が問題だと思います。", zh: "标注本身在法律上已经是义务了，但我认为问题更大的是，不管有没有标注，评价的真实性都可能受损。", vi: "Việc công bố giờ đây đã là bắt buộc theo pháp luật, nhưng tôi nghĩ vấn đề lớn hơn là sự chân thành của đánh giá bị ảnh hưởng bất kể có gắn nhãn hay không." },
      { speaker: "마케터", kr: "저는 조금 다르게 생각합니다. 광고라고 명시했다면 소비자도 그걸 감안하고 걸러서 받아들일 수 있는 판단력이 있다고 봐요.", en: "I see it a bit differently. If it's clearly labeled as an ad, I believe consumers have the judgment to factor that in and filter accordingly.", ja: "私は少し違う考えです。広告と明示すれば、消費者もそれを考慮してフィルターをかけて受け止める判断力があると思います。", zh: "我的看法有点不同。只要明确标注是广告，我相信消费者有能力权衡并加以过滤。", vi: "Tôi nhìn nhận hơi khác một chút. Nếu được gắn nhãn rõ ràng là quảng cáo, tôi tin rằng người tiêu dùng có đủ khả năng phán đoán để cân nhắc và lọc thông tin phù hợp." },
      { speaker: "평론가", kr: "이론적으로는 그렇지만, 실제로는 표기가 작고 눈에 잘 안 띄게 처리되는 경우가 대부분이라 실효성이 떨어져요.", en: "Theoretically, yes, but in practice the disclosure is usually made small and hard to notice, so it loses its practical effect.", ja: "理論的にはそうですが、実際には表記が小さく目立たないように処理されるケースがほとんどで、実効性に欠けます。", zh: "理论上是这样，但实际上标注大多做得很小、不显眼，实际效果大打折扣。", vi: "Về lý thuyết thì đúng vậy, nhưng trên thực tế thông báo thường được ghi nhỏ và khó nhận thấy, nên mất đi hiệu quả thực tiễn." },
      { speaker: "마케터", kr: "그건 표기 방식의 문제지, 협찬 콘텐츠 자체의 문제는 아니지 않나요. 규제를 강화하면 해결될 문제 같은데요.", en: "Isn't that a problem with how the disclosure is displayed, not with sponsored content itself? That seems like something stronger regulation could fix.", ja: "それは表記方式の問題であって、協賛コンテンツ自体の問題ではないのではないですか。規制を強化すれば解決する問題だと思いますが。", zh: "那是标注方式的问题，而不是赞助内容本身的问题吧？加强监管应该就能解决。", vi: "Chẳng phải đó là vấn đề về cách hiển thị thông báo, chứ không phải bản thân nội dung được tài trợ sao? Đó có vẻ là điều mà quy định chặt chẽ hơn có thể khắc phục." },
      { speaker: "평론가", kr: "규제 강화도 필요하지만, 근본적으로는 크리에이터 스스로가 신뢰를 자산으로 여기는 문화가 자리 잡아야 한다고 생각합니다.", en: "Stronger regulation is needed too, but fundamentally I think a culture needs to take root where creators themselves treat trust as an asset.", ja: "規制強化も必要ですが、根本的にはクリエイター自身が信頼を資産と考える文化が根付くべきだと思います。", zh: "加强监管也是必要的，但根本上还是需要建立一种文化，让创作者自己把信任当作资产来珍视。", vi: "Cần có quy định chặt chẽ hơn thật, nhưng về cơ bản tôi nghĩ cần hình thành một văn hóa mà chính các nhà sáng tạo coi sự tin cậy là một tài sản." },
      { speaker: "마케터", kr: "그 말씀에는 동의해요. 다만 신뢰를 자산으로 여기라는 요구가 생계와 충돌하는 순간, 현실적으로 지켜지기 어려운 게 사실이죠.", en: "I agree with that. But the moment the demand to treat trust as an asset collides with making a living, it's realistically hard to uphold, and that's the truth.", ja: "そのお言葉には同意します。ただ信頼を資産と見なせという要求が生計と衝突する瞬間、現実的に守るのが難しいのは事実です。", zh: "这一点我同意。但当“把信任当资产”这种要求与生计发生冲突时，现实中确实很难坚持。", vi: "Tôi đồng ý với điều đó. Nhưng ngay khi yêu cầu coi sự tin cậy là tài sản va chạm với việc kiếm sống, thì trên thực tế rất khó giữ vững, và đó là sự thật." },
      { speaker: "진행자", kr: "결국 규제와 자율, 그리고 생계라는 세 축이 균형을 이뤄야 한다는 말씀으로 정리해도 될까요.", en: "Can we sum this up as saying that regulation, self-restraint, and livelihood all need to find balance, in the end?", ja: "結局規制と自律、そして生計という三つの軸がバランスを取らなければならないという話にまとめてもよろしいでしょうか。", zh: "可以总结为，监管、自律和生计这三者最终需要找到平衡，这样理解可以吗？", vi: "Chúng ta có thể tóm tắt rằng cuối cùng quy định, tự kiềm chế và sinh kế đều cần tìm được sự cân bằng không?" },
      { speaker: "평론가", kr: "정확한 정리라고 생각합니다.", en: "I think that's an accurate summary.", ja: "正確なまとめだと思います。", zh: "我觉得这个总结很准确。", vi: "Tôi nghĩ đó là một bản tóm tắt chính xác." },
      { speaker: "마케터", kr: "저도 동의합니다. 오늘 논의가 그 균형점을 찾는 데 작은 실마리가 됐으면 좋겠네요.", en: "I agree as well. I hope today's discussion becomes a small clue toward finding that balance.", ja: "私も同意します。今日の議論がそのバランス点を見つける小さな手がかりになればと思います。", zh: "我也同意。希望今天的讨论能成为寻找那个平衡点的一点线索。", vi: "Tôi cũng đồng ý. Tôi hy vọng cuộc thảo luận hôm nay sẽ trở thành một manh mối nhỏ để tìm ra sự cân bằng đó." },
    ],
  },
  {
    id: "restaurant-c2y-ai-kiosk-depth",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "Two regulars debate whether kiosks erode dining as ritual", ja: "常連客二人がキオスクが食事の儀礼性を損なうか議論する", zh: "两位常客争论自助点餐机是否消解了用餐的仪式感", vi: "Hai khách quen tranh luận liệu máy tự order có xói mòn nghi thức ăn uống" },
    lines: [
      { speaker: "손님A", kr: "저는 이 키오스크가 편하긴 한데, 주문이라는 행위 자체가 하나의 의례였다는 걸 요즘 부쩍 실감해요. 그게 사라진 느낌이랄까요.", en: "This kiosk is convenient, but lately I keenly feel that ordering itself used to be a kind of ritual. It feels as if that's disappeared.", ja: "このキオスクは便利ではありますが、注文という行為自体が一つの儀式だったと最近やたら実感します。それが消えた感じというか。", zh: "这个自助点餐机确实方便，但最近我越来越感觉到，点单这个行为本身曾经是一种仪式。感觉那种东西消失了。", vi: "Máy tự order này tiện thật, nhưng dạo này tôi cảm nhận sâu sắc rằng việc gọi món từng là một loại nghi thức. Có cảm giác như điều đó đã biến mất rồi." },
      { speaker: "손님B", kr: "의례라고까지 표현하시니 조금 거창하게 들리는데, 결국 주문은 정보 전달의 수단 아니었나요. 수단이 효율화된 것뿐이라고 봐요.", en: "Calling it a ritual sounds a bit grandiose to me — wasn't ordering ultimately just a means of conveying information? I see it as simply the means becoming more efficient.", ja: "儀式とまで表現すると少し大げさに聞こえますが、結局注文は情報伝達の手段じゃなかったですか。手段が効率化されただけだと思います。", zh: "说成仪式听起来有点夸张了，点单说到底不就是传递信息的手段吗？我觉得只是手段变得更高效了而已。", vi: "Gọi đó là nghi thức nghe hơi quá lời với tôi — chẳng phải gọi món suy cho cùng chỉ là một phương tiện truyền đạt thông tin sao? Tôi coi đó đơn giản là phương tiện trở nên hiệu quả hơn thôi." },
      { speaker: "손님A", kr: "수단이라는 말에는 동의하지만, 그 수단 안에 눈빛을 교환하고 취향을 설명하는 과정 자체가 관계를 만드는 요소였다고 생각해요.", en: "I agree it's a means, but the process within that means — exchanging glances, explaining preferences — was itself an element that built a relationship.", ja: "手段という言葉には同意しますが、その手段の中で視線を交わし、好みを説明する過程自体が関係を作る要素だったと思います。", zh: "手段这个说法我同意，但在那个手段中，眼神交流、说明自己喜好的过程本身就是建立关系的元素。", vi: "Tôi đồng ý đó là một phương tiện, nhưng quá trình bên trong phương tiện đó — trao đổi ánh mắt, giải thích sở thích — tự nó là một yếu tố xây dựng nên mối quan hệ." },
      { speaker: "손님B", kr: "관계라는 것도 결국 낯선 사람과의 짧은 접촉일 뿐인데, 그걸 잃었다고 아쉬워하는 게 오히려 낭만화 아닐까요.", en: "But that 'relationship' was ultimately just a brief contact with a stranger — isn't lamenting its loss actually a romanticization?", ja: "関係というものも結局見知らぬ人との短い接触にすぎないのに、それを失ったと惜しむのはむしろロマンチック化ではないでしょうか。", zh: "所谓“关系”终究只是和陌生人的短暂接触，为失去它而惋惜，会不会反而是一种浪漫化？", vi: "Nhưng 'mối quan hệ' đó cuối cùng cũng chỉ là một tiếp xúc ngắn ngủi với người lạ — chẳng phải việc than tiếc mất nó thực ra là một sự lãng mạn hóa sao?" },
      { speaker: "손님A", kr: "낭만화라는 지적을 부정하진 않겠어요. 다만 사소한 접촉들이 쌓여서 결국 동네라는 공동체 감각을 만든다고 믿는 편이에요.", en: "I won't deny that charge of romanticization. Still, I tend to believe that small contacts accumulate to eventually form the sense of community that makes a neighborhood.", ja: "ロマンチック化という指摘を否定はしません。ただ些細な接触が積み重なって、結局街という共同体感覚を作ると信じている方です。", zh: "浪漫化这个说法我不否认。不过我倾向于相信，那些细小的接触积累起来，最终会形成一种社区归属感。", vi: "Tôi không phủ nhận cáo buộc lãng mạn hóa đó. Dù vậy, tôi vẫn có xu hướng tin rằng những tiếp xúc nhỏ tích lũy lại cuối cùng sẽ tạo nên cảm giác cộng đồng làm nên một khu phố." },
      { speaker: "손님B", kr: "그 믿음 자체는 존중하지만, 데이터로 보면 키오스크 도입 이후 오히려 재방문율이 높아진 가게도 많아요. 효율이 곧 냉담함을 뜻하진 않는다는 거죠.", en: "I respect that belief, but the data shows many places have actually seen higher repeat-visit rates after adopting kiosks. Efficiency doesn't necessarily mean coldness.", ja: "その信念自体は尊重しますが、データで見るとキオスク導入以降むしろ再訪問率が高くなった店も多いです。効率が即冷淡さを意味するわけではないということです。", zh: "这种信念本身我尊重，但从数据看，很多店引入自助机后回头客率反而提高了。效率并不等于冷漠。", vi: "Tôi tôn trọng niềm tin đó, nhưng dữ liệu cho thấy nhiều nơi thực ra đã có tỷ lệ khách quay lại cao hơn sau khi áp dụng máy tự order. Hiệu quả không nhất thiết đồng nghĩa với lạnh lùng." },
      { speaker: "손님A", kr: "재방문율이 는다고 해서 그 방문의 질까지 담보되는 건 아니겠지만, 말씀을 들으니 제가 너무 한쪽 감상에만 치우쳤나 싶기도 하네요.", en: "A higher repeat-visit rate doesn't necessarily guarantee the quality of those visits, but hearing you, I do wonder if I've leaned too heavily into one-sided sentiment.", ja: "再訪問率が上がったからといって、その訪問の質まで担保されるわけではないでしょうが、お話を聞くと私が一方的な感傷に偏りすぎたのかとも思いますね。", zh: "回头客率上升不代表访问的质量也有保证，不过听您这么说，我也在想自己是不是太偏向一种感伤情绪了。", vi: "Tỷ lệ khách quay lại cao hơn không nhất thiết đảm bảo chất lượng của những lần ghé thăm đó, nhưng nghe anh nói vậy, tôi cũng tự hỏi liệu mình có nghiêng quá nhiều về cảm tính một chiều không." },
      { speaker: "손님B", kr: "치우쳤다기보다는, 서로 다른 걸 가치 있게 여기는 거죠. 저는 효율에서 안도감을 느끼고, 당신은 접촉에서 온기를 느끼는 거고요.", en: "I wouldn't say leaned so much as that we simply value different things. You find warmth in contact, and I find reassurance in efficiency.", ja: "偏っているというより、お互い違うものに価値を見出しているんです。私は効率に安堵感を感じ、あなたは接触に温かさを感じている。", zh: "与其说偏，不如说我们看重的东西不同。您在接触中感受到温暖，我在效率中感受到安心。", vi: "Tôi sẽ không nói là nghiêng, mà đơn giản là chúng ta coi trọng những thứ khác nhau. Anh tìm thấy hơi ấm trong sự tiếp xúc, còn tôi tìm thấy sự yên tâm trong hiệu quả." },
      { speaker: "손님A", kr: "그렇게 정리해 주시니 이 논쟁이 승패의 문제가 아니라는 게 명확해지네요. 그래도 저는 가끔은 굳이 직원분께 말을 걸어볼 것 같아요.", en: "Framing it that way makes clear this debate isn't about winning or losing. Still, I think I'll occasionally go out of my way to chat with the staff anyway.", ja: "そうまとめていただくと、この論争が勝ち負けの問題ではないことがはっきりしますね。それでも私は時々あえて店員さんに話しかけてみると思います。", zh: "这样一说，就更清楚这场争论不是输赢的问题。不过我想我还是会偶尔特意找店员聊两句吧。", vi: "Đặt vấn đề như vậy thì rõ ràng cuộc tranh luận này không phải là chuyện thắng thua. Dù vậy, tôi nghĩ thỉnh thoảng tôi vẫn sẽ cố tình bắt chuyện với nhân viên." },
    ],
  },
  {
    id: "restaurant-c2y-critics-notebook",
    situationKey: "restaurant",
    level: "C2",
    title: { en: "A veteran critic reflects on the ethics of a scathing verdict", ja: "ベテラン評論家が辛口評価の倫理を振り返る", zh: "资深评论家反思尖锐评价的伦理", vi: "Nhà phê bình kỳ cựu suy ngẫm về đạo đức của một lời phán xét gay gắt" },
    lines: [
      { speaker: "후배 평론가", kr: "선배님, 이번 리뷰 정말 신랄하시던데요. 그 식당 이번 시즌에 폐업한다는 소문까지 도는데, 마음이 편치 않으실 것 같아요.", en: "Senior, that review of yours was really scathing. There are even rumors the restaurant might close this season — I imagine that must weigh on you.", ja: "先輩、今回のレビュー本当に辛辣でしたね。あの店が今シーズン閉店するという噂まで出ていて、心中穏やかではないと思います。", zh: "前辈，您这次的评论真的很尖锐。据说那家店这个季度可能要关门，您心里应该也不好受吧。", vi: "Đàn anh, bài đánh giá của anh thật sự gay gắt. Thậm chí có tin đồn nhà hàng có thể đóng cửa vào mùa này — tôi hình dung điều đó chắc hẳn đè nặng lên anh." },
      { speaker: "선배 평론가", kr: "마음이 편할 리가 있나. 근데 신랄함이 개인적인 원한에서 나온 게 아니라 요리에 대한 존중에서 나왔다는 걸 나 자신은 알고 있어.", en: "How could it be easy? But I know for myself that the harshness didn't come from personal grudge — it came from respect for the cooking itself.", ja: "心中穏やかなわけがないさ。だけど辛辣さが個人的な恨みからではなく、料理への敬意から出たものだということは自分自身が分かっている。", zh: "心里怎么可能好受。但我自己清楚，那种尖锐并非出于个人恩怨，而是出于对料理的尊重。", vi: "Sao có thể dễ dàng được? Nhưng tôi tự biết rằng sự gay gắt đó không xuất phát từ ác cảm cá nhân — nó xuất phát từ sự tôn trọng đối với chính món ăn." },
      { speaker: "후배 평론가", kr: "존중에서 나왔다는 말씀은 이해가 되는데, 그래도 한 문장이 한 가게의 생계를 좌우할 수도 있다는 무게는 어떻게 감당하세요?", en: "I understand what you mean about respect, but how do you carry the weight of knowing one sentence could determine a restaurant's survival?", ja: "敬意から出たというお話は理解できますが、それでも一文が一つの店の生計を左右し得るという重みをどう抱えていらっしゃるんですか？", zh: "尊重出发这一点我理解，但一句话可能左右一家店的生计，这份重量您是怎么承受的？", vi: "Em hiểu ý anh về sự tôn trọng, nhưng làm sao anh mang được sức nặng khi biết rằng một câu văn có thể quyết định sự sống còn của một nhà hàng?" },
      { speaker: "선배 평론가", kr: "그 무게를 가볍게 여긴 적은 단 한 번도 없어. 다만 침묵도 결국 하나의 평가라는 걸 잊으면 안 돼. 나쁜 요리를 눈감아 주는 것도 누군가에게는 폭력이 될 수 있으니까.", en: "I've never once taken that weight lightly. But you mustn't forget that silence is itself a form of judgment too. Turning a blind eye to bad cooking can be its own kind of violence to someone else.", ja: "その重みを軽く見たことは一度もない。ただ沈黙も結局一つの評価だということを忘れてはいけない。悪い料理に目をつぶることも、誰かにとっては暴力になり得るから。", zh: "这份重量我从来没有轻视过。但也不能忘记，沉默本身也是一种评价。对糟糕的料理睁一只眼闭一只眼，对某些人来说也可能是一种暴力。", vi: "Tôi chưa bao giờ xem nhẹ sức nặng đó dù chỉ một lần. Nhưng em đừng quên rằng im lặng tự nó cũng là một hình thức phán xét. Nhắm mắt làm ngơ trước món ăn tồi có thể là một dạng bạo lực đối với người khác." },
      { speaker: "후배 평론가", kr: "누군가에게는 폭력이라니, 무슨 뜻이신지 조금 더 설명해 주시겠어요?", en: "Violence to someone else — could you explain that a bit more?", ja: "誰かにとっては暴力だなんて、どういう意味かもう少し説明していただけますか？", zh: "对某些人来说是暴力，这是什么意思，可以再解释一下吗？", vi: "Bạo lực đối với người khác — anh có thể giải thích rõ hơn một chút không?" },
      { speaker: "선배 평론가", kr: "부실한 음식에 대한 침묵은 결국 다음 손님이 똑같은 실망을 반복하게 만들어. 정직한 평가가 오히려 그 식당이 스스로를 돌아볼 마지막 기회일 수도 있고.", en: "Silence about a poorly made dish just means the next customer repeats the same disappointment. An honest review might actually be the restaurant's last chance to reflect on itself.", ja: "不十分な料理への沈黙は、結局次のお客さんが同じ失望を繰り返すことになる。正直な評価がむしろその店が自らを振り返る最後の機会かもしれない。", zh: "对劣质食物保持沉默，结果只会让下一位顾客重复同样的失望。诚实的评价，反而可能是那家店审视自己的最后机会。", vi: "Im lặng về một món ăn dở chỉ có nghĩa là vị khách tiếp theo lặp lại cùng một sự thất vọng đó. Một bài đánh giá trung thực thực ra có thể là cơ hội cuối cùng để nhà hàng tự nhìn lại mình." },
      { speaker: "후배 평론가", kr: "그렇게 들으니 신랄함이 오히려 애정의 다른 얼굴일 수도 있겠네요. 그래도 저는 아직 그 정도 확신을 갖고 글을 쓸 자신은 없어요.", en: "Hearing that, harshness might actually be another face of care. Still, I don't yet have the confidence to write with that level of conviction.", ja: "そう聞くと、辛辣さがむしろ愛情の別の顔なのかもしれませんね。それでも私はまだそこまでの確信を持って文章を書く自信がありません。", zh: "听您这么说，尖锐或许也是关爱的另一副面孔。不过我还没有那种程度的信心去写这样的文字。", vi: "Nghe vậy, sự gay gắt có lẽ thực ra là một khuôn mặt khác của sự quan tâm. Dù vậy, em vẫn chưa có đủ tự tin để viết với mức độ xác tín như thế." },
      { speaker: "선배 평론가", kr: "확신은 하루아침에 생기지 않아. 다만 매번 문장을 쓰기 전에 스스로에게 물어봐. 이게 요리를 향한 정직함인지, 아니면 그저 재치를 뽐내려는 욕심인지.", en: "Conviction doesn't form overnight. Just ask yourself before every sentence you write — is this honesty toward the cooking, or just a desire to show off cleverness?", ja: "確信は一朝一夕にはできない。ただ毎回文章を書く前に自分自身に問いかけてみなさい。これが料理への正直さなのか、それとも単に機知を誇示したい欲なのか。", zh: "信心不是一朝一夕就能有的。只是每次落笔之前问问自己——这是对料理的诚实，还是只是想炫耀文笔的欲望。", vi: "Sự xác tín không hình thành trong một sớm một chiều. Chỉ cần tự hỏi mình trước mỗi câu em viết — đây là sự trung thực đối với món ăn, hay chỉ là mong muốn thể hiện sự khôn khéo?" },
      { speaker: "후배 평론가", kr: "그 질문, 이제부터 제 글쓰기의 기준으로 삼아볼게요.", en: "I'll make that question my standard for writing from now on.", ja: "その問い、これから私の文章の基準にしてみます。", zh: "这个问题，我从今以后就把它当作自己写作的标准吧。", vi: "Từ nay em sẽ lấy câu hỏi đó làm chuẩn mực khi viết." },
    ],
  },
];

export const RESTAURANT_C_QUIZZES: Record<string, DialogueQuiz> = {
  "restaurant-c1y-menu-change": {
    q: "Why did the chef change the menu?",
    opts: [
      "To follow a trendy diet fad",
      "Because ingredient sourcing became unstable",
      "Because the regular customer demanded it",
      "To cut costs during a recession",
    ],
    ans: 1,
  },
  "restaurant-c1y-tipping-culture": {
    q: "What did the owner and manager agree to do first?",
    opts: [
      "Introduce tipping immediately",
      "Ask foreign customers for their opinion",
      "Fix the performance-pay system before considering tips",
      "Raise the service charge instead",
    ],
    ans: 2,
  },
  "restaurant-c1y-sommelier-pairing": {
    q: "Why does the sommelier say the red wine works with the fish?",
    opts: [
      "The fish is very fatty, which balances tannin",
      "The soy-based sauce and low fat content balance the tannin",
      "Red wine is always safer than white with fish",
      "The customer specifically requested red wine",
    ],
    ans: 1,
  },
  "restaurant-c1y-authenticity-debate": {
    q: "What do both writers ultimately agree they share concern about?",
    opts: [
      "Whether the taco tastes good",
      "The price of the dish",
      "The balance between speed of change and respect for tradition",
      "Which restaurant serves the better version",
    ],
    ans: 2,
  },
  "restaurant-c1y-labor-costs": {
    q: "What did the owner do instead of raising menu prices?",
    opts: [
      "Laid off staff to cut costs",
      "Simplified the menu and made staffing more efficient",
      "Reduced business hours",
      "Switched to lower-quality ingredients",
    ],
    ans: 1,
  },
  "restaurant-c1y-vip-complaint": {
    q: "According to the senior server, what should happen first when handling a complaint?",
    opts: [
      "Explain the reason for the delay",
      "Call the manager immediately",
      "Apologize before explaining anything",
      "Offer a discount on the bill",
    ],
    ans: 2,
  },
  "restaurant-c1y-neighborhood-decline": {
    q: "What do the two residents identify as the main cause of old shops closing?",
    opts: [
      "Poor food quality",
      "Rising rent prices",
      "Lack of parking",
      "Declining population in the area",
    ],
    ans: 1,
  },
  "restaurant-c1y-catering-negotiation": {
    q: "What compromise does the owner suggest for menu variety in the catering contract?",
    opts: [
      "A completely different menu every single time",
      "The exact same fixed menu every time",
      "Keeping a base composition while rotating two or three dishes",
      "Letting the client cook their own food",
    ],
    ans: 2,
  },
  "restaurant-c1y-inspector-reveal": {
    q: "Why is the chef relieved not to have known about the inspector in advance?",
    opts: [
      "They would have closed early that day",
      "They might have gotten nervous and made mistakes",
      "They didn't have enough ingredients that day",
      "They would have overcharged the inspector",
    ],
    ans: 1,
  },
  "restaurant-c2y-succession": {
    q: "What reassurance does the father give his daughter about taking over the restaurant?",
    opts: [
      "She must run it exactly as he did",
      "She should sell it instead",
      "She doesn't need to replicate his methods exactly, since times change",
      "She should wait another ten years",
    ],
    ans: 2,
  },
  "restaurant-c2y-review-fallout": {
    q: "What does the PR manager recommend doing before issuing a full apology?",
    opts: [
      "Ignore the review completely",
      "Post a public apology immediately",
      "Contact the customer personally and confirm the facts first",
      "Delete all references to the review online",
    ],
    ans: 2,
  },
  "restaurant-c2y-critic-anonymity": {
    q: "What do the two writers conclude the real issue is, beyond anonymity itself?",
    opts: [
      "Whether reviewers get paid enough",
      "Who takes responsibility for the review's voice",
      "Whether restaurants should ban photography",
      "How many followers a reviewer has",
    ],
    ans: 1,
  },
  "restaurant-c2y-generational-palate": {
    q: "How does the younger chef reframe the perceived decline in young diners' palates?",
    opts: [
      "As a permanent loss of ability",
      "As a shift in taste due to fewer opportunities to experience subtlety",
      "As proof that older diners are wrong",
      "As something impossible to address",
    ],
    ans: 1,
  },
  "restaurant-c2y-labor-dispute": {
    q: "What alternative plan does the union representative propose?",
    opts: [
      "Eliminate the service charge entirely",
      "Give all service charge to management",
      "Separate pay structures: service charge to floor/kitchen staff, base-salary raise for management",
      "Reduce everyone's pay equally",
    ],
    ans: 2,
  },
  "restaurant-c2y-closing-legacy": {
    q: "Why does the owner feel relief rather than only sadness about closing?",
    opts: [
      "He never liked running the restaurant",
      "Forcing it to continue without the same stamina and passion felt like a betrayal of its years",
      "He is retiring to travel the world",
      "The restaurant was losing money for years",
    ],
    ans: 1,
  },
  "restaurant-c2y-food-media-ethics": {
    q: "What do the panelists agree needs to be balanced regarding paid food content?",
    opts: [
      "Only government regulation matters",
      "Regulation, creator self-restraint, and livelihood needs",
      "Only consumer awareness matters",
      "Advertising should be banned outright",
    ],
    ans: 1,
  },
  "restaurant-c2y-ai-kiosk-depth": {
    q: "How do the two customers ultimately frame their disagreement about kiosks?",
    opts: [
      "As a factual dispute that has one correct answer",
      "As a difference in what each of them personally values, not a win-or-lose debate",
      "As proof that kiosks should be banned",
      "As evidence that human staff are obsolete",
    ],
    ans: 1,
  },
  "restaurant-c2y-critics-notebook": {
    q: "How does the senior critic justify writing harsh reviews?",
    opts: [
      "Harsh reviews get more readers and clicks",
      "Silence about bad food is itself a judgment that lets disappointment repeat, so honesty can be an act of care",
      "It doesn't matter if restaurants close from bad reviews",
      "Younger critics should always copy the senior's style",
    ],
    ans: 1,
  },
};
