import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Restaurant situation expansion (2026-08): raises A1-B2 coverage to 20 dialogues per level.
export const RESTAURANT_EXPANSION: Dialogue[] = [
  {
    id: "restaurant-a1x-window",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Asking for a window seat", ja: "窓側の席をお願いする", zh: "请求靠窗的座位" },
    lines: [
      { speaker: "손님", kr: "창가 자리 있어요?", en: "Do you have a table by the window?", ja: "窓側の席はありますか？", zh: "有靠窗的桌子吗？", vi: "Bạn có bàn cạnh cửa sổ không?" },
      { speaker: "직원", kr: "네, 이쪽으로 오세요.", en: "Yes, this way please.", ja: "はい、こちらへどうぞ。", zh: "好的，请这边走。", vi: "Vâng, xin mời này." },
      { speaker: "손님", kr: "여기 좋네요. 감사합니다.", en: "This is nice. Thank you.", ja: "ここはいいですね。ありがとうございます。", zh: "这里很不错。谢谢。", vi: "Chỗ này rất tốt. Cảm ơn bạn." },
      { speaker: "직원", kr: "메뉴판 드릴게요.", en: "Here's the menu.", ja: "メニューです。", zh: "这是菜单。", vi: "Đây là thực đơn." },
    ],
  },
  {
    id: "restaurant-a1x-barleytea",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "More barley tea, please", ja: "麦茶のおかわりをお願いする", zh: "请再来点大麦茶" },
    lines: [
      { speaker: "손님", kr: "저기요, 보리차 좀 더 주세요.", en: "Excuse me, more barley tea please.", ja: "すみません、麦茶をもっと下さい。", zh: "请问，麦茶再来一杯。", vi: "Xin lỗi, cho tôi thêm trà lúa mì." },
      { speaker: "직원", kr: "네, 잠시만요.", en: "Sure, one moment.", ja: "かしこまりました。少々お待ち下さい。", zh: "好的，请稍等。", vi: "Vâng, chờ một chút." },
      { speaker: "직원", kr: "여기 있습니다.", en: "Here you go.", ja: "お待たせしました。", zh: "给您。", vi: "Đây là đồ uống của bạn." },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。", vi: "Cảm ơn bạn." },
    ],
  },
  {
    id: "restaurant-a1x-bell",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Calling staff with the bell", ja: "ベルでスタッフを呼ぶ", zh: "用铃铛叫服务员" },
    lines: [
      { speaker: "손님", kr: "벨이 있네요. 눌러도 돼요?", en: "There's a bell. Can I press it?", ja: "ベルがありますね。押してもいいですか？", zh: "有个铃。我可以按吗？", vi: "Có cái chuông. Tôi có thể bấm không?" },
      { speaker: "직원", kr: "네, 필요하시면 누르세요.", en: "Yes, press it whenever you need us.", ja: "はい、必要な時にいつでも押して下さい。", zh: "可以，需要的时候按。", vi: "Vâng, bạn cần thì bấm." },
      { speaker: "손님", kr: "알겠습니다. 지금 물 좀 주세요.", en: "Okay. Water please, right now.", ja: "分かりました。今、水をください。", zh: "好的。现在请给我水。", vi: "Được. Xin cho tôi nước ngay." },
      { speaker: "직원", kr: "바로 갖다드릴게요.", en: "I'll bring it right away.", ja: "すぐに持ってきます。", zh: "马上就来。", vi: "Tôi sẽ mang ngay." },
    ],
  },
  {
    id: "restaurant-a1x-rice",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Extra rice", ja: "ご飯のおかわり", zh: "加一碗米饭" },
    lines: [
      { speaker: "손님", kr: "공기밥 하나 더 주세요.", en: "One more bowl of rice, please.", ja: "ご飯をもう一つください。", zh: "请再给我一碗米饭。" },
      { speaker: "직원", kr: "네, 얼마예요?", en: "Sure — did you mean the price?", ja: "はい、値段のことですか？", zh: "好的，您是问价格吗？" },
      { speaker: "직원", kr: "천 원입니다.", en: "It's one thousand won.", ja: "千ウォンです。", zh: "1000韩元。" },
      { speaker: "손님", kr: "네, 주세요.", en: "Yes, please bring it.", ja: "はい、お願いします。", zh: "好的，请给我吧。" },
    ],
  },
  {
    id: "restaurant-a1x-fork",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "A fork instead of chopsticks", ja: "箸の代わりにフォークを", zh: "用叉子代替筷子" },
    lines: [
      { speaker: "손님", kr: "젓가락 말고 포크 있어요?", en: "Do you have a fork instead of chopsticks?", ja: "箸ではなくフォークはありますか？", zh: "有叉子吗？不要筷子。" },
      { speaker: "직원", kr: "네, 가져다드릴게요.", en: "Yes, I'll bring you one.", ja: "はい、お持ちします。", zh: "有的，我拿给您。" },
      { speaker: "손님", kr: "감사해요.", en: "Thanks.", ja: "ありがとうございます。", zh: "谢谢。", vi: "(Thanks.)" },
      { speaker: "직원", kr: "여기 포크요.", en: "Here's your fork.", ja: "こちらフォークです。", zh: "这是您的叉子。" },
    ],
  },
  {
    id: "restaurant-a1x-togo",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Dine-in or to go", ja: "店内か持ち帰りか", zh: "堂食还是打包" },
    lines: [
      { speaker: "직원", kr: "여기서 드세요, 포장이세요?", en: "For here, or to go?", ja: "こちらで召し上がりますか、お持ち帰りですか？", zh: "在这里吃还是打包？" },
      { speaker: "손님", kr: "포장이요.", en: "To go, please.", ja: "持ち帰りでお願いします。", zh: "打包，谢谢。" },
      { speaker: "직원", kr: "네, 봉투에 담아 드릴게요.", en: "Okay, I'll put it in a bag.", ja: "はい、袋に入れますね。", zh: "好的，我给您装袋。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
    ],
  },
  {
    id: "restaurant-a1x-restroom",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Where's the restroom", ja: "お手洗いはどこ", zh: "洗手间在哪里" },
    lines: [
      { speaker: "손님", kr: "화장실이 어디예요?", en: "Where's the restroom?", ja: "お手洗いはどこですか？", zh: "洗手间在哪里？" },
      { speaker: "직원", kr: "저쪽 끝에 있어요.", en: "It's at the far end there.", ja: "あちらの奥にあります。", zh: "在那边最里面。" },
      { speaker: "손님", kr: "네, 감사합니다.", en: "Okay, thank you.", ja: "はい、ありがとうございます。", zh: "好的，谢谢。" },
      { speaker: "직원", kr: "천만에요.", en: "You're welcome.", ja: "どういたしまして。", zh: "不客气。" },
    ],
  },
  {
    id: "restaurant-a1x-napkin",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "More napkins", ja: "紙ナプキンをもっと", zh: "多要点纸巾" },
    lines: [
      { speaker: "손님", kr: "휴지 좀 더 주세요.", en: "Could I get more tissues?", ja: "ティッシュをもっといただけますか？", zh: "可以再给我点纸巾吗？" },
      { speaker: "직원", kr: "네, 여기 있어요.", en: "Sure, here you go.", ja: "はい、どうぞ。", zh: "好的，给您。" },
      { speaker: "손님", kr: "고맙습니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
      { speaker: "직원", kr: "필요하면 또 말씀하세요.", en: "Let me know if you need more.", ja: "必要でしたらまたおっしゃってください。", zh: "需要的话请再告诉我。" },
    ],
  },
  {
    id: "restaurant-a1x-cardonly",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Card only, no cash", ja: "カードのみ、現金不可", zh: "只收卡不收现金" },
    lines: [
      { speaker: "손님", kr: "현금도 받아요?", en: "Do you take cash too?", ja: "現金も使えますか？", zh: "可以用现金吗？" },
      { speaker: "직원", kr: "아니요, 카드만 받아요.", en: "No, card only.", ja: "いいえ、カードのみです。", zh: "不行，只收卡。" },
      { speaker: "손님", kr: "아, 알겠어요.", en: "Ah, okay.", ja: "あ、分かりました。", zh: "啊，好的。" },
      { speaker: "직원", kr: "죄송합니다.", en: "Sorry about that.", ja: "申し訳ございません。", zh: "不好意思。" },
    ],
  },
  {
    id: "restaurant-a1x-veggie",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Asking about vegetarian food", ja: "ベジタリアン料理について尋ねる", zh: "询问素食" },
    lines: [
      { speaker: "손님", kr: "채식 메뉴 있어요?", en: "Do you have vegetarian food?", ja: "ベジタリアンメニューはありますか？", zh: "有素食菜单吗？" },
      { speaker: "직원", kr: "네, 비빔밥은 고기 빼고 돼요.", en: "Yes, we can make the bibimbap without meat.", ja: "はい、ビビンバは肉抜きで作れます。", zh: "有的，拌饭可以不放肉。" },
      { speaker: "손님", kr: "좋아요, 그걸로 주세요.", en: "Great, I'll have that.", ja: "いいですね、それでお願いします。", zh: "好，那就要那个吧。" },
      { speaker: "직원", kr: "네, 알겠습니다.", en: "Okay, got it.", ja: "はい、かしこまりました。", zh: "好的，明白了。" },
    ],
  },
  {
    id: "restaurant-a1x-wifi",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Asking for the wifi password", ja: "Wi-Fiのパスワードを尋ねる", zh: "询问Wi-Fi密码" },
    lines: [
      { speaker: "손님", kr: "와이파이 비밀번호가 뭐예요?", en: "What's the wifi password?", ja: "Wi-Fiのパスワードは何ですか？", zh: "Wi-Fi密码是什么？" },
      { speaker: "직원", kr: "영수증에 적혀 있어요.", en: "It's written on the receipt.", ja: "レシートに書いてあります。", zh: "写在收据上。" },
      { speaker: "손님", kr: "아, 감사합니다.", en: "Ah, thank you.", ja: "あ、ありがとうございます。", zh: "啊，谢谢。" },
      { speaker: "직원", kr: "네, 편하게 쓰세요.", en: "Sure, feel free to use it.", ja: "はい、ご自由にお使いください。", zh: "好的，请随意使用。" },
    ],
  },
  {
    id: "restaurant-a1x-water2",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Still or sparkling water", ja: "普通の水か炭酸水か", zh: "普通水还是气泡水" },
    lines: [
      { speaker: "직원", kr: "물은 일반 물, 탄산수 중에 뭐로 드릴까요?", en: "Would you like still water or sparkling water?", ja: "お水は普通の水と炭酸水、どちらになさいますか？", zh: "水您要普通水还是气泡水？" },
      { speaker: "손님", kr: "탄산수 주세요.", en: "Sparkling water, please.", ja: "炭酸水をお願いします。", zh: "请给我气泡水。" },
      { speaker: "직원", kr: "네, 바로 드릴게요.", en: "Sure, I'll bring it right away.", ja: "はい、すぐお持ちします。", zh: "好的，马上给您送来。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thanks.", ja: "ありがとうございます。", zh: "谢谢。", vi: "(Thanks.)" },
    ],
  },
  {
    id: "restaurant-a1x-bartable",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Bar seat, please", ja: "バー席をお願いします", zh: "请给我吧台座位" },
    lines: [
      { speaker: "손님", kr: "저 혼자인데 바 자리 있어요?", en: "I'm alone — is there a bar seat?", ja: "一人なんですが、バー席はありますか？", zh: "我一个人，有吧台座位吗？" },
      { speaker: "직원", kr: "네, 저기 앉으세요.", en: "Yes, please sit over there.", ja: "はい、あちらにお座りください。", zh: "有的，请坐那边。" },
      { speaker: "손님", kr: "네, 감사합니다.", en: "Okay, thank you.", ja: "はい、ありがとうございます。", zh: "好的，谢谢。" },
      { speaker: "직원", kr: "메뉴 보여드릴게요.", en: "I'll show you the menu.", ja: "メニューをお見せします。", zh: "我给您看看菜单。" },
    ],
  },
  {
    id: "restaurant-a1x-kidsmenu",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "Is there a kids menu", ja: "キッズメニューはある？", zh: "有儿童菜单吗" },
    lines: [
      { speaker: "손님", kr: "어린이 메뉴 있어요?", en: "Is there a kids menu?", ja: "キッズメニューはありますか？", zh: "有儿童菜单吗？" },
      { speaker: "직원", kr: "네, 돈가스랑 오므라이스 있어요.", en: "Yes, we have pork cutlet and omurice.", ja: "はい、とんかつとオムライスがあります。", zh: "有的，有炸猪排和蛋包饭。" },
      { speaker: "손님", kr: "오므라이스로 주세요.", en: "Omurice, please.", ja: "オムライスでお願いします。", zh: "请给我蛋包饭。" },
      { speaker: "직원", kr: "네, 알겠습니다.", en: "Okay, got it.", ja: "はい、かしこまりました。", zh: "好的，明白了。" },
    ],
  },
  {
    id: "restaurant-a1x-quiet",
    situationKey: "restaurant",
    level: "A1",
    title: { en: "A quieter table", ja: "もっと静かな席", zh: "更安静的座位" },
    lines: [
      { speaker: "손님", kr: "여기는 좀 시끄러워요. 조용한 자리 있어요?", en: "It's a bit loud here. Is there a quieter table?", ja: "ここは少しうるさいです。静かな席はありますか？", zh: "这里有点吵。有安静一点的座位吗？" },
      { speaker: "직원", kr: "네, 안쪽 자리로 옮겨 드릴게요.", en: "Yes, I'll move you to a table in the back.", ja: "はい、奥の席に移していただきますね。", zh: "有的，我给您换到里面的座位。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
      { speaker: "직원", kr: "이쪽으로 오세요.", en: "This way, please.", ja: "こちらへどうぞ。", zh: "这边请。" },
    ],
  },
  {
    id: "restaurant-a2x-allergy",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "No onions, please", ja: "玉ねぎ抜きでお願いします", zh: "请不要放洋葱" },
    lines: [
      { speaker: "손님", kr: "제가 양파 알레르기가 있어서요. 양파 빼고 주실 수 있어요?", en: "I have an onion allergy — could you make it without onions?", ja: "私、玉ねぎアレルギーがあるんです。玉ねぎを抜いていただけますか？", zh: "我对洋葱过敏。可以不放洋葱吗？" },
      { speaker: "직원", kr: "네, 주방에 말씀드릴게요.", en: "Yes, I'll let the kitchen know.", ja: "はい、厨房に伝えますね。", zh: "好的，我会告诉厨房。" },
      { speaker: "손님", kr: "감사해요. 마늘은 괜찮아요.", en: "Thanks. Garlic is fine, though.", ja: "ありがとうございます。ニンニクは大丈夫です。", zh: "谢谢。大蒜没关系。" },
      { speaker: "직원", kr: "네, 양파만 빼서 만들어 드릴게요.", en: "Got it, we'll leave out just the onions.", ja: "分かりました、玉ねぎだけ抜いて作ります。", zh: "明白了，只去掉洋葱。" },
      { speaker: "손님", kr: "혹시 늦게 나올까요?", en: "Will it take a bit longer to come out?", ja: "少し遅く出てきますか？", zh: "会不会晚一点上菜？" },
      { speaker: "직원", kr: "조금만 더 기다리시면 돼요.", en: "You'll only have to wait a little longer.", ja: "もう少しお待ちいただくだけで大丈夫です。", zh: "只需要多等一点点就好。" },
    ],
  },
  {
    id: "restaurant-a2x-grill",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "How to grill the meat", ja: "お肉の焼き方", zh: "怎么烤肉" },
    lines: [
      { speaker: "손님", kr: "고기를 처음 구워 봐서요. 어떻게 구울지 알려 주실 수 있어요?", en: "This is my first time grilling meat here. Could you show me how?", ja: "お肉を焼くのが初めてで。どう焼けばいいか教えていただけますか？", zh: "我是第一次烤这种肉。可以教我怎么烤吗？" },
      { speaker: "직원", kr: "네, 제가 구워 드릴게요.", en: "Sure, I'll grill it for you.", ja: "はい、私が焼いて差し上げます。", zh: "好的，我来帮您烤。" },
      { speaker: "직원", kr: "한 번만 뒤집으시면 돼요.", en: "You only need to flip it once.", ja: "一回だけひっくり返せば大丈夫です。", zh: "只要翻一次面就可以。" },
      { speaker: "손님", kr: "언제 뒤집어야 돼요?", en: "When should I flip it?", ja: "いつひっくり返せばいいですか？", zh: "什么时候该翻面？" },
      { speaker: "직원", kr: "이렇게 색이 변하면 뒤집으세요.", en: "Flip it once the color changes like this.", ja: "こうやって色が変わったらひっくり返してください。", zh: "颜色变成这样的时候翻面。" },
      { speaker: "손님", kr: "알겠어요, 감사합니다.", en: "Got it, thank you.", ja: "分かりました、ありがとうございます。", zh: "明白了，谢谢。" },
    ],
  },
  {
    id: "restaurant-a2x-ssam",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Wrapping a ssam", ja: "サムの包み方", zh: "怎么包生菜包肉" },
    lines: [
      { speaker: "손님", kr: "쌈을 어떻게 싸는지 몰라서요.", en: "I don't know how to wrap a ssam.", ja: "サムの包み方が分からなくて。", zh: "我不知道怎么包生菜包肉。" },
      { speaker: "직원", kr: "상추에 고기랑 쌈장을 올리고 싸시면 돼요.", en: "Put the meat and ssamjang on the lettuce, then wrap it up.", ja: "サンチュに肉とサムジャンを乗せて包めばいいですよ。", zh: "把肉和包饭酱放在生菜上包起来就行。" },
      { speaker: "손님", kr: "마늘도 같이 넣어요?", en: "Do I put garlic in too?", ja: "ニンニクも一緒に入れますか？", zh: "大蒜也一起放吗？" },
      { speaker: "직원", kr: "네, 원하시면 넣으세요.", en: "Yes, add it if you'd like.", ja: "はい、お好みで入れてください。", zh: "对，喜欢的话可以放。" },
      { speaker: "손님", kr: "한번 해 볼게요.", en: "I'll give it a try.", ja: "一度やってみます。", zh: "我试试看。" },
      { speaker: "직원", kr: "잘하시네요!", en: "You're doing great!", ja: "お上手ですね！", zh: "您做得很好！" },
    ],
  },
  {
    id: "restaurant-a2x-setmenu",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Asking about the set menu", ja: "セットメニューについて尋ねる", zh: "询问套餐内容" },
    lines: [
      { speaker: "손님", kr: "세트 메뉴는 뭐가 나와요?", en: "What comes with the set menu?", ja: "セットメニューには何が付きますか？", zh: "套餐里都有什么？" },
      { speaker: "직원", kr: "스프, 샐러드, 메인 요리, 커피가 나와요.", en: "You get soup, salad, a main dish, and coffee.", ja: "スープ、サラダ、メイン料理、コーヒーが付きます。", zh: "有汤、沙拉、主菜和咖啡。" },
      { speaker: "손님", kr: "메인은 고를 수 있어요?", en: "Can I choose the main dish?", ja: "メインは選べますか？", zh: "主菜可以选吗？" },
      { speaker: "직원", kr: "네, 스테이크나 파스타 중에 고르시면 돼요.", en: "Yes, you can choose between steak or pasta.", ja: "はい、ステーキかパスタからお選びいただけます。", zh: "可以，可以在牛排和意面中选一个。" },
      { speaker: "손님", kr: "그럼 스테이크로 할게요.", en: "Then I'll go with the steak.", ja: "では、ステーキにします。", zh: "那就要牛排吧。" },
      { speaker: "직원", kr: "네, 주문 도와드릴게요.", en: "Great, I'll get that order started.", ja: "はい、ご注文を承ります。", zh: "好的，我马上帮您下单。" },
    ],
  },
  {
    id: "restaurant-a2x-splitdish",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Splitting one dish two ways", ja: "一品を二人で分ける", zh: "两人分吃一份菜" },
    lines: [
      { speaker: "손님", kr: "저희 둘이 하나만 시켜서 나눠 먹을 건데 괜찮아요?", en: "The two of us are going to order just one and share it — is that okay?", ja: "私たち二人で一つだけ注文して分けて食べようと思うんですが、大丈夫ですか？", zh: "我们两个人只点一份分着吃，可以吗？" },
      { speaker: "직원", kr: "네, 괜찮아요. 접시 하나 더 드릴까요?", en: "Yes, that's fine. Would you like an extra plate?", ja: "はい、大丈夫です。お皿をもう一枚お持ちしましょうか？", zh: "可以的。需要再给您一个盘子吗？" },
      { speaker: "손님", kr: "네, 부탁드려요.", en: "Yes, please.", ja: "はい、お願いします。", zh: "好的，麻烦您了。", vi: "có please." },
      { speaker: "직원", kr: "알겠습니다, 곧 갖다드릴게요.", en: "Okay, I'll bring it shortly.", ja: "かしこまりました、すぐお持ちします。", zh: "好的，马上给您送来。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
    ],
  },
  {
    id: "restaurant-a2x-forgot",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "The order hasn't come yet", ja: "注文がまだ来ない", zh: "点的菜还没上" },
    lines: [
      { speaker: "손님", kr: "저희 주문한 지 이십 분 됐는데 아직 안 나왔어요.", en: "It's been twenty minutes since we ordered and it still hasn't come.", ja: "注文してから二十分経ったんですが、まだ来ていません。", zh: "我们点单已经二十分钟了，还没上菜。" },
      { speaker: "직원", kr: "정말 죄송해요, 바로 확인해 볼게요.", en: "I'm so sorry, let me check right away.", ja: "本当に申し訳ございません、すぐに確認いたします。", zh: "非常抱歉，我马上去确认一下。" },
      { speaker: "직원", kr: "주문이 빠졌던 것 같아요.", en: "It looks like your order got missed.", ja: "注文が抜けていたようです。", zh: "看起来漏了您的订单。" },
      { speaker: "손님", kr: "그럼 얼마나 더 기다려야 돼요?", en: "So how much longer do we have to wait?", ja: "では、あとどれくらい待てばいいですか？", zh: "那还要等多久？" },
      { speaker: "직원", kr: "오 분이면 됩니다, 죄송합니다.", en: "Just five minutes — I'm really sorry.", ja: "五分あれば大丈夫です、申し訳ございません。", zh: "五分钟就好，真的很抱歉。" },
      { speaker: "손님", kr: "네, 알겠어요.", en: "Okay, understood.", ja: "はい、分かりました。", zh: "好的，明白了。" },
    ],
  },
  {
    id: "restaurant-a2x-aircon",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "It's too cold in here", ja: "ここは寒すぎます", zh: "这里太冷了" },
    lines: [
      { speaker: "손님", kr: "여기 에어컨이 너무 세서 추워요.", en: "The air conditioning is really strong here — it's cold.", ja: "ここのエアコンが強すぎて寒いです。", zh: "这里的空调太强了，好冷。" },
      { speaker: "직원", kr: "죄송해요, 온도 좀 올려 드릴게요.", en: "Sorry about that, I'll turn up the temperature.", ja: "申し訳ございません、温度を上げますね。", zh: "不好意思，我把温度调高一点。" },
      { speaker: "손님", kr: "감사해요. 담요 같은 것도 있어요?", en: "Thanks. Do you have a blanket or something too?", ja: "ありがとうございます。ブランケットのようなものもありますか？", zh: "谢谢。有毯子之类的东西吗？" },
      { speaker: "직원", kr: "네, 하나 가져다드릴게요.", en: "Yes, I'll bring you one.", ja: "はい、一枚お持ちします。", zh: "有的，我拿一条给您。" },
      { speaker: "손님", kr: "정말 감사합니다.", en: "Thank you so much.", ja: "本当にありがとうございます。", zh: "真的非常感谢。" },
    ],
  },
  {
    id: "restaurant-a2x-parking",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Parking validation", ja: "駐車券の確認", zh: "停车券盖章" },
    lines: [
      { speaker: "손님", kr: "주차하고 왔는데 여기서 도장 받을 수 있어요?", en: "I parked outside — can I get my ticket stamped here?", ja: "駐車してきたんですが、ここでハンコをもらえますか？", zh: "我在外面停了车，可以在这里盖章吗？" },
      { speaker: "직원", kr: "네, 영수증이랑 주차권 주세요.", en: "Yes, please give me your receipt and parking ticket.", ja: "はい、レシートと駐車券をください。", zh: "可以，请给我收据和停车券。" },
      { speaker: "손님", kr: "여기 있어요.", en: "Here you go.", ja: "こちらです。", zh: "给您。" },
      { speaker: "직원", kr: "한 시간 무료로 찍어 드렸어요.", en: "I've stamped you for one hour free.", ja: "一時間分の無料スタンプを押しました。", zh: "已经给您盖了一小时免费停车。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
    ],
  },
  {
    id: "restaurant-a2x-lastorder",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "When is last order", ja: "ラストオーダーはいつ", zh: "最后点餐时间是几点" },
    lines: [
      { speaker: "손님", kr: "라스트 오더가 몇 시예요?", en: "What time is last order?", ja: "ラストオーダーは何時ですか？", zh: "最后点餐是几点？" },
      { speaker: "직원", kr: "아홉 시 삼십 분까지예요.", en: "It's until nine thirty.", ja: "九時三十分までです。", zh: "到九点半为止。" },
      { speaker: "손님", kr: "지금 아홉 시 이십 분인데 시킬 수 있어요?", en: "It's nine twenty now — can I still order?", ja: "今九時二十分ですが、注文できますか？", zh: "现在是九点二十，还能点吗？" },
      { speaker: "직원", kr: "네, 아직 괜찮아요.", en: "Yes, you're still fine.", ja: "はい、まだ大丈夫です。", zh: "可以，还来得及。" },
      { speaker: "손님", kr: "다행이네요.", en: "That's a relief.", ja: "よかったです。", zh: "太好了。" },
    ],
  },
  {
    id: "restaurant-a2x-delivery",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Delivery or dine-in at the counter", ja: "配達か店内利用か", zh: "外送还是堂食" },
    lines: [
      { speaker: "손님", kr: "여기서도 주문하고 배달도 시킬 수 있어요?", en: "Can I order here and also get delivery?", ja: "ここで注文して配達もお願いできますか？", zh: "在这里点单也能叫外送吗？" },
      { speaker: "직원", kr: "지금은 매장에서 드시는 것만 돼요.", en: "Right now we only do dine-in orders.", ja: "今は店内でのお食事のみとなっております。", zh: "现在只能堂食。" },
      { speaker: "손님", kr: "아, 그럼 여기서 먹을게요.", en: "Ah, then I'll eat here.", ja: "あ、では、ここで食べます。", zh: "啊，那我就在这里吃吧。" },
      { speaker: "직원", kr: "네, 자리는 어디로 드릴까요?", en: "Okay, where would you like to sit?", ja: "はい、お席はどちらになさいますか？", zh: "好的，您想坐哪里？" },
      { speaker: "손님", kr: "창가 쪽으로 주세요.", en: "By the window, please.", ja: "窓側でお願いします。", zh: "请给我靠窗的座位。" },
    ],
  },
  {
    id: "restaurant-a2x-lostcard",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Lost my card at the till", ja: "レジにカードを忘れた", zh: "把卡忘在收银台了" },
    lines: [
      { speaker: "손님", kr: "제 카드를 못 찾겠어요. 계산대에 두고 갔나 봐요.", en: "I can't find my card. I think I left it at the register.", ja: "カードが見つかりません。レジに置いてきたみたいです。", zh: "我找不到我的卡了。可能忘在收银台了。" },
      { speaker: "직원", kr: "잠시만요, 확인해 볼게요.", en: "One moment, let me check.", ja: "少々お待ちください、確認します。", zh: "请稍等，我去确认一下。" },
      { speaker: "직원", kr: "여기 있네요, 저희가 보관하고 있었어요.", en: "Here it is — we had it kept safe.", ja: "ありました、こちらでお預かりしていました。", zh: "在这里，我们帮您保管着呢。" },
      { speaker: "손님", kr: "정말 감사합니다, 다행이에요.", en: "Thank you so much, what a relief.", ja: "本当にありがとうございます、よかったです。", zh: "太感谢了，真是万幸。" },
      { speaker: "직원", kr: "다음엔 조심하세요.", en: "Please be more careful next time.", ja: "次は気をつけてくださいね。", zh: "下次请小心一点。" },
    ],
  },
  {
    id: "restaurant-a2x-lesssalt",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Less salty, please", ja: "塩分控えめでお願いします", zh: "请少放点盐" },
    lines: [
      { speaker: "손님", kr: "짜지 않게 해 주실 수 있어요?", en: "Could you make it less salty?", ja: "塩辛くならないようにしていただけますか？", zh: "可以做得不那么咸吗？" },
      { speaker: "직원", kr: "네, 소금 적게 넣어 달라고 전할게요.", en: "Sure, I'll tell them to use less salt.", ja: "はい、塩を少なめにするよう伝えます。", zh: "好的，我会告诉他们少放盐。" },
      { speaker: "손님", kr: "설탕도 조금만 넣어 주세요.", en: "A little less sugar too, please.", ja: "砂糖も少しだけ入れてください。", zh: "糖也请少放一点。" },
      { speaker: "직원", kr: "네, 둘 다 전달할게요.", en: "Okay, I'll pass both along.", ja: "はい、両方お伝えします。", zh: "好的，两个都会转达。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
    ],
  },
  {
    id: "restaurant-a2x-music",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Turning down the music", ja: "音楽の音量を下げる", zh: "把音乐声调小" },
    lines: [
      { speaker: "손님", kr: "음악 소리를 좀 줄여 주실 수 있어요?", en: "Could you turn the music down a bit?", ja: "音楽の音量を少し下げていただけますか？", zh: "可以把音乐声调小一点吗？" },
      { speaker: "직원", kr: "네, 줄여 드릴게요.", en: "Sure, I'll turn it down.", ja: "はい、下げますね。", zh: "好的，我调小一点。" },
      { speaker: "손님", kr: "대화하기가 힘들어서요.", en: "It's hard to have a conversation.", ja: "会話がしづらくて。", zh: "因为不太方便聊天。" },
      { speaker: "직원", kr: "이해해요, 바로 조정할게요.", en: "I understand, I'll adjust it right away.", ja: "分かります、すぐに調整します。", zh: "理解，我马上调整。" },
      { speaker: "손님", kr: "감사합니다.", en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。" },
    ],
  },
  {
    id: "restaurant-a2x-dessertspoon",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "An extra spoon for dessert", ja: "デザート用のスプーンを追加", zh: "再要一个吃甜点的勺子" },
    lines: [
      { speaker: "손님", kr: "디저트 하나 시켰는데 숟가락 하나 더 주실 수 있어요?", en: "We ordered one dessert — could we get an extra spoon?", ja: "デザートを一つ頼んだんですが、スプーンをもう一本いただけますか？", zh: "我们点了一份甜点，可以再给一个勺子吗？" },
      { speaker: "직원", kr: "네, 몇 개 드릴까요?", en: "Sure, how many would you like?", ja: "はい、何本お持ちしましょうか？", zh: "好的，需要几个？" },
      { speaker: "손님", kr: "두 개 더 주세요.", en: "Two more, please.", ja: "もう二本お願いします。", zh: "请再给两个。" },
      { speaker: "직원", kr: "알겠습니다, 곧 가져다드릴게요.", en: "Got it, I'll bring them shortly.", ja: "かしこまりました、すぐお持ちします。", zh: "好的，马上给您送来。" },
      { speaker: "손님", kr: "고맙습니다.", en: "Thanks.", ja: "ありがとうございます。", zh: "谢谢。", vi: "(Thanks.)" },
    ],
  },
  {
    id: "restaurant-a2x-birthdaynoodle",
    situationKey: "restaurant",
    level: "A2",
    title: { en: "Birthday noodles", ja: "誕生日の麺料理", zh: "生日面条" },
    lines: [
      { speaker: "손님", kr: "오늘 제 생일이라서 국수를 먹으려고요.", en: "It's my birthday today, so I wanted to have noodles.", ja: "今日は私の誕生日なので、麺を食べようと思って。", zh: "今天是我生日，所以想吃面条。" },
      { speaker: "직원", kr: "아, 생일 축하드려요! 국수는 장수를 뜻해요.", en: "Oh, happy birthday! Noodles are supposed to mean a long life.", ja: "あ、お誕生日おめでとうございます！麺は長寿を意味するんですよ。", zh: "啊，生日快乐！面条象征长寿呢。" },
      { speaker: "손님", kr: "맞아요, 그래서 매년 먹어요.", en: "That's right, so I eat them every year.", ja: "そうなんです、だから毎年食べています。", zh: "对啊，所以每年都会吃。" },
      { speaker: "직원", kr: "그럼 특별히 많이 드릴게요.", en: "Then I'll give you an extra big portion.", ja: "では、特別にたくさん差し上げますね。", zh: "那我特意多给您一些。" },
      { speaker: "손님", kr: "감사합니다!", en: "Thank you!", ja: "ありがとうございます！", zh: "谢谢！" },
    ],
  },
  {
    id: "restaurant-b1x-discount",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Asking about a discount", ja: "割引について尋ねる", zh: "询问折扣" },
    lines: [
      { speaker: "손님", kr: "혹시 이 쿠폰 아직 쓸 수 있어요? 유효기간이 지난 것 같기도 해서요.", en: "Can I still use this coupon? It looks like it might be expired.", ja: "このクーポン、まだ使えますか？期限が過ぎているような気もして。", zh: "请问这张优惠券还能用吗？看起来好像已经过期了。" },
      { speaker: "직원", kr: "한번 볼게요. 어제까지였네요.", en: "Let me take a look. It expired yesterday.", ja: "確認しますね。昨日までだったようです。", zh: "我看看。截止日期是昨天。" },
      { speaker: "손님", kr: "아, 그래요? 하루 차이인데 좀 봐주실 수 있어요?", en: "Oh really? It's only a day off — could you make an exception?", ja: "あ、そうですか？たった一日の差なんですが、大目に見ていただけますか？", zh: "啊，是吗？就差一天，可以通融一下吗？" },
      { speaker: "직원", kr: "원래는 안 되는데, 이번만 해 드릴게요.", en: "It's not usually allowed, but I'll do it just this once.", ja: "本来はできないんですが、今回だけ特別にいたします。", zh: "本来是不行的，这次就破例一次吧。" },
      { speaker: "손님", kr: "정말 감사합니다, 다음엔 미리 챙길게요.", en: "Thank you so much — I'll keep track of the date next time.", ja: "本当にありがとうございます、次は前もって気をつけますね。", zh: "太感谢了，下次我会提前留意日期的。" },
      { speaker: "직원", kr: "네, 좋은 하루 되세요.", en: "Sure, have a great day.", ja: "はい、良い一日をお過ごしください。", zh: "好的，祝您今天愉快。" },
    ],
  },
  {
    id: "restaurant-b1x-noshow",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "A no-show reservation", ja: "無断キャンセルの予約", zh: "预约却没来" },
    lines: [
      { speaker: "직원", kr: "예약하셨던 시간이 지났는데 연락이 안 되셔서요.", en: "Your reservation time has passed and we couldn't reach you.", ja: "ご予約のお時間が過ぎたのですが、ご連絡が取れませんでした。", zh: "您预约的时间已经过了，我们联系不上您。" },
      { speaker: "손님", kr: "죄송해요, 차가 너무 막혀서 늦었어요.", en: "I'm sorry, traffic was really bad so I'm late.", ja: "すみません、道が渋滞していて遅れました。", zh: "对不起，路上太堵了所以迟到了。" },
      { speaker: "직원", kr: "저희가 자리를 다른 손님께 드릴 수밖에 없었어요.", en: "We had no choice but to give the table to another guest.", ja: "他のお客様にお席をお譲りするしかありませんでした。", zh: "我们没办法只好把桌子让给了别的客人。" },
      { speaker: "손님", kr: "아, 그럼 지금은 자리가 전혀 없어요?", en: "Oh, so there's absolutely no table available now?", ja: "あ、では今は席が全くないんですか？", zh: "啊，那现在完全没有位置了吗？" },
      { speaker: "직원", kr: "바 자리는 남아 있어요, 괜찮으시면요.", en: "There's a bar seat left, if that works for you.", ja: "バー席なら空いています、よろしければ。", zh: "吧台还有位置，如果您不介意的话。" },
      { speaker: "손님", kr: "네, 그거라도 앉을게요.", en: "Yes, I'll take that.", ja: "はい、それでも座ります。", zh: "好的，那我就坐那里吧。" },
    ],
  },
  {
    id: "restaurant-b1x-corkage",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Bringing your own wine", ja: "ワインの持ち込み", zh: "自带葡萄酒" },
    lines: [
      { speaker: "손님", kr: "저희가 와인을 가져왔는데 여기서 마셔도 돼요?", en: "We brought our own wine — is it okay to drink it here?", ja: "ワインを持ってきたんですが、ここで飲んでもいいですか？", zh: "我们带了葡萄酒，可以在这里喝吗？" },
      { speaker: "직원", kr: "네, 되긴 하는데 콜키지 비용이 있어요.", en: "Yes, that's fine, but there's a corkage fee.", ja: "はい、大丈夫ですが、コルク料がかかります。", zh: "可以的，但要收开瓶费。" },
      { speaker: "손님", kr: "얼마예요?", en: "How much is it?", ja: "いくらですか？", zh: "多少钱？" },
      { speaker: "직원", kr: "한 병에 만 오천 원이에요.", en: "It's fifteen thousand won per bottle.", ja: "一本一万五千ウォンです。", zh: "一瓶15000韩元。" },
      { speaker: "손님", kr: "괜찮아요, 잔이랑 오프너도 주실 수 있어요?", en: "That's fine — could we also get glasses and an opener?", ja: "大丈夫です、グラスとオープナーもいただけますか？", zh: "没问题，可以给我们杯子和开瓶器吗？" },
      { speaker: "직원", kr: "네, 바로 준비해 드릴게요.", en: "Sure, I'll get those ready right away.", ja: "はい、すぐご用意いたします。", zh: "好的，马上给您准备。" },
    ],
  },
  {
    id: "restaurant-b1x-combo",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "A combo for two", ja: "二人分のコンボ", zh: "两人套餐" },
    lines: [
      { speaker: "손님", kr: "저희 둘이 먹을 건데 뭘 시키면 좋을지 추천해 주실 수 있어요?", en: "There are two of us — could you recommend what to order?", ja: "二人で食べるんですが、何を頼めばいいかおすすめしていただけますか？", zh: "我们两个人吃，可以推荐一下点什么吗？" },
      { speaker: "직원", kr: "이인 세트가 있는데, 그걸 드시면 양이 딱 맞아요.", en: "We have a two-person set — the portion would be just right.", ja: "二人セットがありまして、それなら量がちょうどいいです。", zh: "有二人套餐，分量正合适。" },
      { speaker: "손님", kr: "그 세트에는 뭐가 포함돼 있어요?", en: "What's included in that set?", ja: "そのセットには何が含まれていますか？", zh: "那个套餐里包含什么？" },
      { speaker: "직원", kr: "고기 두 종류랑 찌개, 밥이 나와요.", en: "You get two types of meat, a stew, and rice.", ja: "肉二種類とチゲ、ご飯が付きます。", zh: "有两种肉、汤和米饭。" },
      { speaker: "손님", kr: "좋네요, 그걸로 할게요.", en: "That sounds good, we'll go with that.", ja: "いいですね、それにします。", zh: "不错，就要那个吧。" },
      { speaker: "직원", kr: "네, 바로 준비해 드릴게요.", en: "Great, I'll get it started right away.", ja: "はい、すぐご用意いたします。", zh: "好的，马上给您准备。" },
    ],
  },
  {
    id: "restaurant-b1x-buffet",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Buffet refill etiquette", ja: "ビュッフェのおかわりマナー", zh: "自助餐取餐礼仪" },
    lines: [
      { speaker: "손님", kr: "뷔페 처음이라서요, 접시 하나로 계속 다시 담아도 돼요?", en: "This is my first time at a buffet — can I keep refilling the same plate?", ja: "ビュッフェが初めてなんですが、同じお皿に何度も盛ってもいいですか？", zh: "第一次吃自助餐，可以一直用同一个盘子装吗？" },
      { speaker: "직원", kr: "네, 다만 남기지 않는 게 좋아요.", en: "Yes, though it's best not to leave leftovers.", ja: "はい、ただ残さない方がいいですよ。", zh: "可以，不过最好不要剩下食物。" },
      { speaker: "손님", kr: "혹시 남기면 어떻게 돼요?", en: "What happens if I do leave food?", ja: "もし残したらどうなりますか？", zh: "如果剩下了会怎么样？" },
      { speaker: "직원", kr: "일정 양 이상 남기시면 추가 요금이 있어요.", en: "If you leave more than a certain amount, there's an extra charge.", ja: "一定量以上残すと追加料金がかかります。", zh: "剩下超过一定量的话要收额外费用。" },
      { speaker: "손님", kr: "아, 그럼 조금씩만 담을게요.", en: "Ah, then I'll just take small portions.", ja: "あ、では少しずつ盛りますね。", zh: "啊，那我就少量多次拿吧。" },
      { speaker: "직원", kr: "네, 그게 좋아요.", en: "Yes, that's a good approach.", ja: "はい、その方がいいです。", zh: "对，那样比较好。" },
    ],
  },
  {
    id: "restaurant-b1x-cooktime",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "How long does it take to cook", ja: "調理にどれくらいかかる", zh: "做这道菜要多久" },
    lines: [
      { speaker: "손님", kr: "이 갈비찜은 나오는 데 얼마나 걸려요?", en: "How long does this braised short rib dish take to come out?", ja: "このカルビチムはどれくらいで出てきますか？", zh: "这个炖排骨要多久才能上桌？" },
      { speaker: "직원", kr: "삼십 분 정도 걸려요, 미리 조리해서요.", en: "About thirty minutes — it's cooked to order.", ja: "三十分ほどかかります、注文を受けてから調理しますので。", zh: "大概要三十分钟，是现点现做的。" },
      { speaker: "손님", kr: "좀 오래 걸리네요, 다른 걸로 먼저 시켜도 돼요?", en: "That's a bit long — can we order something else first?", ja: "少し時間がかかりますね、他のものを先に注文してもいいですか？", zh: "有点久呢，可以先点别的吗？" },
      { speaker: "직원", kr: "네, 전이랑 같이 준비해 드릴까요?", en: "Sure, shall I get you some pajeon while you wait?", ja: "はい、チヂミも一緒にご用意しましょうか？", zh: "可以，要不要顺便给您准备一份煎饼？" },
      { speaker: "손님", kr: "네, 좋아요.", en: "Yes, that sounds good.", ja: "はい、いいですね。", zh: "好，那挺好的。" },
      { speaker: "직원", kr: "알겠습니다.", en: "Understood.", ja: "かしこまりました。", zh: "明白了。", vi: "(Understood.)" },
    ],
  },
  {
    id: "restaurant-b1x-meeting",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "A quiet corner for a meeting", ja: "打ち合わせ用の静かな席", zh: "为开会找安静的角落" },
    lines: [
      { speaker: "손님", kr: "업무 미팅이라서 좀 조용한 자리로 부탁드려도 될까요?", en: "This is a work meeting — could we get a quieter table, please?", ja: "仕事の打ち合わせなので、静かな席をお願いできますか？", zh: "是工作会议，可以给我们安排安静一点的座位吗？" },
      { speaker: "직원", kr: "네, 안쪽 룸이 하나 비어 있어요.", en: "Yes, there's a private room available in the back.", ja: "はい、奥の個室が一つ空いています。", zh: "可以，里面有一个包间是空的。" },
      { speaker: "손님", kr: "그럼 거기로 부탁드려요. 콘센트도 있어요?", en: "Then we'll take that, please. Is there an outlet too?", ja: "では、そちらでお願いします。コンセントもありますか？", zh: "那就要那间吧。有插座吗？" },
      { speaker: "직원", kr: "네, 벽 쪽에 있어요.", en: "Yes, there's one by the wall.", ja: "はい、壁際にあります。", zh: "有的，在墙边。" },
      { speaker: "손님", kr: "완벽하네요, 감사합니다.", en: "That's perfect, thank you.", ja: "完璧です、ありがとうございます。", zh: "太好了，谢谢。" },
      { speaker: "직원", kr: "이쪽으로 안내해 드릴게요.", en: "I'll show you the way.", ja: "こちらへご案内します。", zh: "我带您过去。" },
    ],
  },
  {
    id: "restaurant-b1x-photo",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Asking staff to take a photo", ja: "スタッフに写真をお願いする", zh: "请服务员帮忙拍照" },
    lines: [
      { speaker: "손님", kr: "죄송한데 저희 사진 한 장만 찍어 주실 수 있어요?", en: "Sorry to ask, but could you take one photo of us?", ja: "すみません、私たちの写真を一枚撮っていただけますか？", zh: "不好意思，可以帮我们拍一张照吗？" },
      { speaker: "직원", kr: "네, 그럼요. 어떻게 찍어 드릴까요?", en: "Of course. How would you like it taken?", ja: "はい、もちろんです。どのように撮りましょうか？", zh: "当然可以。您想怎么拍？" },
      { speaker: "손님", kr: "테이블이랑 저희 다 나오게 찍어 주세요.", en: "Please get both the table and all of us in the shot.", ja: "テーブルと私たち全員が写るように撮ってください。", zh: "请把桌子和我们都拍进去。" },
      { speaker: "직원", kr: "네, 하나, 둘, 셋.", en: "Okay, one, two, three.", ja: "はい、いち、に、さん。", zh: "好的，一，二，三。" },
      { speaker: "손님", kr: "감사합니다, 잘 나왔어요.", en: "Thank you, it came out great.", ja: "ありがとうございます、いい感じに撮れました。", zh: "谢谢，拍得很好。" },
      { speaker: "직원", kr: "즐거운 시간 되세요.", en: "Enjoy the rest of your meal.", ja: "楽しい時間をお過ごしください。", zh: "祝您用餐愉快。" },
    ],
  },
  {
    id: "restaurant-b1x-halal",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Asking about halal food", ja: "ハラル料理について尋ねる", zh: "询问清真食品" },
    lines: [
      { speaker: "손님", kr: "제가 할랄 음식만 먹는데 여기 가능한 메뉴 있어요?", en: "I only eat halal food — do you have any menu items that work?", ja: "私はハラル料理しか食べないんですが、こちらで対応できるメニューはありますか？", zh: "我只吃清真食品，这里有适合我的菜单吗？" },
      { speaker: "직원", kr: "돼지고기가 들어간 메뉴가 많아서 확인이 필요해요.", en: "Many of our dishes have pork, so let me check.", ja: "豚肉が入っているメニューが多いので、確認が必要です。", zh: "很多菜里都有猪肉，我需要确认一下。" },
      { speaker: "직원", kr: "생선 요리랑 채소 메뉴는 괜찮으실 거예요.", en: "The fish dishes and vegetable menu should work for you.", ja: "魚料理と野菜メニューなら大丈夫だと思います。", zh: "鱼类和蔬菜类菜品应该没问题。" },
      { speaker: "손님", kr: "그럼 생선구이로 주세요.", en: "Then I'll have the grilled fish, please.", ja: "では、焼き魚をお願いします。", zh: "那就来一份烤鱼吧。" },
      { speaker: "직원", kr: "네, 조리할 때도 따로 확인할게요.", en: "Sure, I'll also make sure it's handled separately in the kitchen.", ja: "はい、調理の際も別に確認いたします。", zh: "好的，做菜时我也会特别注意确认。" },
      { speaker: "손님", kr: "정말 감사합니다.", en: "Thank you so much.", ja: "本当にありがとうございます。", zh: "真的非常感谢。" },
    ],
  },
  {
    id: "restaurant-b1x-gochujang",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Extra gochujang", ja: "コチュジャンを追加", zh: "多加点辣椒酱" },
    lines: [
      { speaker: "손님", kr: "저는 매운 걸 좋아해서 고추장을 더 주실 수 있어요?", en: "I like spicy food — could I get some extra gochujang?", ja: "辛いものが好きなので、コチュジャンをもっといただけますか？", zh: "我喜欢吃辣，可以多给我一点辣椒酱吗？" },
      { speaker: "직원", kr: "네, 그런데 이 요리는 이미 매운 편이에요.", en: "Sure, though this dish is already quite spicy.", ja: "はい、ただこの料理はもともとかなり辛い方です。", zh: "可以，不过这道菜本身已经挺辣的了。" },
      { speaker: "손님", kr: "그래도 더 맵게 먹고 싶어서요.", en: "Even so, I'd like it spicier.", ja: "それでももっと辛くして食べたいんです。", zh: "不过我还是想吃更辣一点的。" },
      { speaker: "직원", kr: "알겠습니다, 조금만 드릴까요 아니면 많이 드릴까요?", en: "Understood — a little or a lot?", ja: "かしこまりました、少しにしますか、それとも多めにしますか？", zh: "明白了，要少加一点还是多加一点？" },
      { speaker: "손님", kr: "많이 주세요.", en: "A lot, please.", ja: "たくさんお願いします。", zh: "请多加一点。" },
      { speaker: "직원", kr: "네, 바로 가져다드릴게요.", en: "Okay, I'll bring it right away.", ja: "はい、すぐお持ちします。", zh: "好的，马上给您送来。" },
    ],
  },
  {
    id: "restaurant-b1x-festival",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Asking about a food festival discount", ja: "フードフェスティバルの割引について", zh: "询问美食节折扣" },
    lines: [
      { speaker: "손님", kr: "지금 축제 기간이라 할인된다고 들었는데 맞아요?", en: "I heard there's a discount during this festival period — is that right?", ja: "今フェスティバル期間で割引があると聞いたんですが、本当ですか？", zh: "听说现在是节庆期间有折扣，是真的吗？" },
      { speaker: "직원", kr: "네, 맞아요. 전체 이십 퍼센트 할인이에요.", en: "Yes, that's correct. There's a twenty percent discount on everything.", ja: "はい、そうです。全品二十パーセント割引です。", zh: "是的，没错。所有商品打八折。" },
      { speaker: "손님", kr: "따로 신청해야 돼요, 아니면 자동으로 적용돼요?", en: "Do I need to sign up separately, or is it applied automatically?", ja: "別途申し込みが必要ですか、それとも自動的に適用されますか？", zh: "需要另外申请吗，还是自动适用？" },
      { speaker: "직원", kr: "계산할 때 자동으로 빠져요.", en: "It's taken off automatically at checkout.", ja: "お会計の際に自動的に引かれます。", zh: "结账的时候会自动扣除。" },
      { speaker: "손님", kr: "잘됐네요, 감사합니다.", en: "That's great, thank you.", ja: "よかったです、ありがとうございます。", zh: "太好了，谢谢。" },
      { speaker: "직원", kr: "네, 맛있게 드세요.", en: "You're welcome — enjoy your meal.", ja: "はい、どうぞ美味しく召し上がってください。", zh: "不客气，祝您用餐愉快。" },
    ],
  },
  {
    id: "restaurant-b1x-sidechange",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Switching a side dish", ja: "副菜を変更する", zh: "更换配菜" },
    lines: [
      { speaker: "손님", kr: "여기 깍두기 대신 김치로 바꿔 주실 수 있어요?", en: "Could you swap the radish kimchi for regular kimchi?", ja: "カクテキの代わりにキムチに変えていただけますか？", zh: "可以把萝卜泡菜换成白菜泡菜吗？" },
      { speaker: "직원", kr: "네, 그런데 이 세트는 깍두기가 기본이라 추가 요금이 있어요.", en: "Sure, but this set comes with radish kimchi by default, so there's an extra charge.", ja: "はい、ただこのセットはカクテキが基本なので追加料金がかかります。", zh: "可以，但这个套餐默认配萝卜泡菜，换的话要收费。" },
      { speaker: "손님", kr: "얼마나 더 내야 돼요?", en: "How much more do I have to pay?", ja: "いくら追加になりますか？", zh: "要多付多少钱？" },
      { speaker: "직원", kr: "오백 원 정도예요.", en: "About five hundred won.", ja: "五百ウォンくらいです。", zh: "大概500韩元。" },
      { speaker: "손님", kr: "그 정도면 괜찮아요, 바꿔 주세요.", en: "That's fine — please make the swap.", ja: "その程度なら大丈夫です、変えてください。", zh: "那没问题，请帮我换吧。" },
      { speaker: "직원", kr: "네, 알겠습니다.", en: "Sure, got it.", ja: "はい、かしこまりました。", zh: "好的，明白了。" },
    ],
  },
  {
    id: "restaurant-b1x-splitcards",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Splitting the bill on two cards", ja: "会計を二枚のカードで分ける", zh: "用两张卡分开结账" },
    lines: [
      { speaker: "손님", kr: "계산을 카드 두 장으로 나눠서 할 수 있어요?", en: "Can we split the payment across two cards?", ja: "会計をカード二枚に分けて支払えますか？", zh: "结账可以用两张卡分开付吗？" },
      { speaker: "직원", kr: "네, 가능해요. 반씩 나눠 드릴까요?", en: "Yes, that's possible. Shall I split it evenly?", ja: "はい、可能です。半分ずつに分けましょうか？", zh: "可以的。要平均分开吗？" },
      { speaker: "손님", kr: "아니요, 제가 삼만 원, 친구가 나머지 낼게요.", en: "No — I'll pay thirty thousand won, and my friend will pay the rest.", ja: "いいえ、私が三万ウォン、友達が残りを払います。", zh: "不，我付30000韩元，剩下的朋友付。" },
      { speaker: "직원", kr: "알겠습니다, 카드 순서대로 주세요.", en: "Understood, please give me the cards in order.", ja: "かしこまりました、カードを順番にお願いします。", zh: "明白了，请按顺序给我卡。" },
      { speaker: "손님", kr: "여기요.", en: "Here you go.", ja: "こちらです。", zh: "给您。" },
      { speaker: "직원", kr: "결제 완료됐습니다.", en: "The payment is complete.", ja: "決済が完了しました。", zh: "结账完成了。" },
    ],
  },
  {
    id: "restaurant-b1x-holiday",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Closing time on a holiday", ja: "祝日の閉店時間", zh: "假期的打烊时间" },
    lines: [
      { speaker: "손님", kr: "이번 주 월요일이 공휴일인데 그날도 영업해요?", en: "This Monday is a public holiday — are you open that day?", ja: "今週の月曜日は祝日ですが、その日も営業していますか？", zh: "这周一是公休日，那天也营业吗？" },
      { speaker: "직원", kr: "네, 영업하는데 오후 여섯 시까지만 해요.", en: "Yes, we're open, but only until six in the evening.", ja: "はい、営業していますが、午後六時までです。", zh: "营业，但只营业到晚上六点。" },
      { speaker: "손님", kr: "평소보다 일찍 닫네요.", en: "That's earlier than usual.", ja: "いつもより早く閉まりますね。", zh: "比平时打烊得早呢。" },
      { speaker: "직원", kr: "네, 직원들도 좀 쉬어야 해서요.", en: "Right, the staff need some rest too.", ja: "はい、スタッフも少し休む必要がありまして。", zh: "对，员工也需要休息一下。" },
      { speaker: "손님", kr: "그럼 저녁 다섯 시쯤 갈게요.", en: "Then I'll come around five in the evening.", ja: "では、夕方五時頃に行きます。", zh: "那我大概晚上五点去。" },
      { speaker: "직원", kr: "네, 기다리고 있을게요.", en: "Sure, we'll be expecting you.", ja: "はい、お待ちしております。", zh: "好的，我们等您。" },
    ],
  },
  {
    id: "restaurant-b1x-privateroom",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Asking about a private room", ja: "個室について尋ねる", zh: "询问包间" },
    lines: [
      { speaker: "손님", kr: "여덟 명이 모이는데 룸으로 예약할 수 있어요?", en: "There will be eight of us — can we book a private room?", ja: "八人集まるんですが、個室を予約できますか？", zh: "我们有八个人，可以预约包间吗？" },
      { speaker: "직원", kr: "네, 있어요. 최소 인원이 여섯 명이라 딱 맞으세요.", en: "Yes, we have one. The minimum is six people, so you'd fit perfectly.", ja: "はい、あります。最低人数が六名なので、ちょうど合いますね。", zh: "有的。最少要六人，正好合适。" },
      { speaker: "손님", kr: "룸 이용료가 따로 있어요?", en: "Is there a separate fee for using the room?", ja: "個室の利用料は別にありますか？", zh: "使用包间要另外收费吗？" },
      { speaker: "직원", kr: "아니요, 음식만 주문하시면 무료예요.", en: "No, it's free as long as you order food.", ja: "いいえ、お料理を注文いただければ無料です。", zh: "不用，只要点菜就免费。" },
      { speaker: "손님", kr: "잘됐네요, 예약할게요.", en: "That's great, I'll book it.", ja: "よかったです、予約します。", zh: "太好了，那我预约吧。" },
      { speaker: "직원", kr: "네, 성함이랑 시간 알려 주세요.", en: "Sure, please give me your name and time.", ja: "はい、お名前とお時間を教えてください。", zh: "好的，请告诉我您的姓名和时间。" },
    ],
  },
  {
    id: "restaurant-b1x-reheat",
    situationKey: "restaurant",
    level: "B1",
    title: { en: "Asking for a dish to be reheated", ja: "料理を温め直してもらう", zh: "请求把菜重新加热" },
    lines: [
      { speaker: "손님", kr: "이야기하다 보니 국이 다 식었어요. 다시 데워 주실 수 있어요?", en: "We were talking and the soup got cold. Could you reheat it?", ja: "話しているうちにスープが冷めてしまいました。もう一度温めていただけますか？", zh: "我们聊着聊着汤都凉了。可以帮忙重新加热一下吗？" },
      { speaker: "직원", kr: "네, 그릇째 가져가서 데워 올게요.", en: "Sure, I'll take the whole bowl and heat it up.", ja: "はい、器ごと持って行って温めてきます。", zh: "可以，我把整碗端去加热一下。" },
      { speaker: "손님", kr: "감사해요, 오래 걸릴까요?", en: "Thanks — will it take long?", ja: "ありがとうございます、時間はかかりますか？", zh: "谢谢，会花很久吗？" },
      { speaker: "직원", kr: "아니요, 금방 됩니다.", en: "No, it'll be quick.", ja: "いいえ、すぐです。", zh: "不会，很快就好。" },
      { speaker: "직원", kr: "여기 다시 데워온 국이요.", en: "Here's your soup, reheated.", ja: "こちら、温め直したスープです。", zh: "这是重新加热好的汤。" },
      { speaker: "손님", kr: "따뜻하네요, 감사합니다.", en: "It's nice and warm, thank you.", ja: "温かいですね、ありがとうございます。", zh: "很热乎，谢谢。" },
    ],
  },
  {
    id: "restaurant-b2x-buffetmixup",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Mixed up plates at the buffet counter", ja: "ビュッフェの取り違え", zh: "自助餐台的餐盘弄混了" },
    lines: [
      { speaker: "손님", kr: "저기요, 제가 픽업대에 놓은 접시가 없어졌어요.", en: "Excuse me, the plate I left at the pickup counter is gone.", ja: "すみません、受け取りカウンターに置いた私のお皿がなくなりました。", zh: "打扰一下，我放在取餐台的盘子不见了。" },
      { speaker: "직원", kr: "죄송해요, 다른 손님이 잘못 가져가신 것 같아요.", en: "I'm sorry — it looks like another guest took it by mistake.", ja: "申し訳ございません、他のお客様が間違えてお持ちになったようです。", zh: "不好意思，好像是别的客人拿错了。" },
      { speaker: "손님", kr: "거기에 제가 주문한 스테이크가 있었는데요.", en: "The steak I ordered was on that plate.", ja: "そこに私が注文したステーキが載っていたんですが。", zh: "那上面有我点的牛排。" },
      { speaker: "직원", kr: "정말 죄송합니다, 바로 새로 구워 드릴게요.", en: "I'm truly sorry — I'll have a new one grilled right away.", ja: "本当に申し訳ございません、すぐに新しく焼かせていただきます。", zh: "真的很抱歉，我马上重新给您烤一份。" },
      { speaker: "손님", kr: "기다리는 동안 다른 걸 좀 챙겨 주실 수 있어요?", en: "While I wait, could you bring me something else in the meantime?", ja: "待っている間、何か他のものを持ってきていただけますか？", zh: "等待期间可以先给我准备点别的吗？" },
      { speaker: "직원", kr: "네, 샐러드라도 먼저 갖다드릴게요.", en: "Of course, I'll bring you a salad first at least.", ja: "はい、サラダだけでも先にお持ちします。", zh: "好的，我先给您上一份沙拉。" },
      { speaker: "손님", kr: "그렇게 해 주시면 감사하죠.", en: "That would be much appreciated.", ja: "そうしていただけると助かります。", zh: "那样的话就太感谢了。" },
    ],
  },
  {
    id: "restaurant-b2x-appissue",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "The reservation app didn't go through", ja: "予約アプリが通っていなかった", zh: "预约软件没有成功" },
    lines: [
      { speaker: "손님", kr: "어제 앱으로 예약했는데 확인 문자를 못 받았어요.", en: "I made a reservation through the app yesterday, but I never got a confirmation text.", ja: "昨日アプリで予約したんですが、確認のメッセージが来ませんでした。", zh: "我昨天用软件预约了，但没收到确认短信。" },
      { speaker: "직원", kr: "성함이랑 시간을 말씀해 주시겠어요?", en: "Could you tell me your name and the time?", ja: "お名前とお時間を教えていただけますか？", zh: "可以告诉我您的姓名和时间吗？" },
      { speaker: "손님", kr: "김서연이고 일곱 시로 했어요.", en: "It's under Kim Seoyeon, for seven o'clock.", ja: "キム・ソヨンで、七時にしました。", zh: "我是金瑞妍，预约的是七点。" },
      { speaker: "직원", kr: "확인해 보니 예약이 들어와 있지 않네요.", en: "Looking it up, the reservation didn't actually go through.", ja: "確認したところ、予約が入っていないようです。", zh: "查了一下，其实预约没有成功。" },
      { speaker: "손님", kr: "이상하네요, 확정 화면까지 봤는데요.", en: "That's strange — I even saw a confirmation screen.", ja: "おかしいですね、確定画面まで見たのに。", zh: "很奇怪，我明明看到确认画面了。" },
      { speaker: "직원", kr: "저희 시스템 오류였을 수도 있어요, 지금 자리 마련해 드릴게요.", en: "It might have been a system error on our end — let me get you a table right now.", ja: "こちらのシステムエラーかもしれません、今すぐお席をご用意します。", zh: "可能是我们系统出错了，我现在马上给您安排位子。" },
      { speaker: "손님", kr: "감사합니다, 다음엔 전화로 다시 확인할게요.", en: "Thank you — next time I'll follow up with a phone call to be sure.", ja: "ありがとうございます、次は電話でも確認します。", zh: "谢谢，下次我会再打电话确认一下。" },
    ],
  },
  {
    id: "restaurant-b2x-latecall",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Calling ahead about a late arrival", ja: "遅れる旨を電話で伝える", zh: "打电话告知会晚到" },
    lines: [
      { speaker: "손님", kr: "여보세요, 저희 일곱 시 예약인데 차가 막혀서 십오 분 정도 늦을 것 같아요.", en: "Hello, we have a seven o'clock reservation, but traffic means we'll probably be about fifteen minutes late.", ja: "もしもし、七時の予約なんですが、渋滞で十五分ほど遅れそうです。", zh: "喂，我们预约的是七点，但堵车了，大概会晚到十五分钟左右。" },
      { speaker: "직원", kr: "네, 알려 주셔서 감사해요. 자리는 잡아 둘게요.", en: "Thank you for letting us know. I'll hold the table for you.", ja: "はい、お知らせいただきありがとうございます。お席は確保しておきますね。", zh: "好的，谢谢您告知我们。我会给您留好位置的。" },
      { speaker: "손님", kr: "혹시 십오 분보다 더 늦어지면 어떻게 될까요?", en: "What happens if we end up more than fifteen minutes late?", ja: "もし十五分より遅れたらどうなりますか？", zh: "如果比十五分钟还晚会怎么样呢？" },
      { speaker: "직원", kr: "이십 분까지는 괜찮은데 그 이상이면 다시 연락 주셔야 해요.", en: "Up to twenty minutes is fine, but past that you'd need to call us again.", ja: "二十分までなら大丈夫ですが、それ以上でしたらまたご連絡ください。", zh: "二十分钟以内没问题，超过的话请再联系我们一下。" },
      { speaker: "손님", kr: "알겠습니다, 최대한 서두를게요.", en: "Understood, we'll try to hurry as much as we can.", ja: "分かりました、できるだけ急ぎます。", zh: "明白了，我们尽量赶快。" },
      { speaker: "직원", kr: "네, 조심히 오세요.", en: "Okay, drive safely.", ja: "はい、お気をつけていらしてください。", zh: "好的，路上小心。" },
    ],
  },
  {
    id: "restaurant-b2x-servicecharge",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Is the service charge included", ja: "サービス料は含まれている？", zh: "服务费包含在内吗" },
    lines: [
      { speaker: "손님", kr: "영수증 보니까 서비스 차지가 따로 붙어 있던데, 팁이랑 다른 거예요?", en: "I noticed a separate service charge on the receipt — is that different from a tip?", ja: "レシートを見たら別にサービス料がついていましたが、チップとは違うんですか？", zh: "看收据上另外加了服务费，这和小费不一样吗？" },
      { speaker: "직원", kr: "네, 저희는 서비스 차지가 자동으로 십 퍼센트 붙어요.", en: "Yes, we automatically add a ten percent service charge.", ja: "はい、うちはサービス料が自動的に十パーセントつきます。", zh: "对，我们会自动加收百分之十的服务费。" },
      { speaker: "손님", kr: "그럼 따로 팁을 더 낼 필요는 없는 거죠?", en: "So I don't need to leave an additional tip on top of that?", ja: "では、別途チップを払う必要はないんですね？", zh: "那就不需要另外再给小费了吧？" },
      { speaker: "직원", kr: "네, 그걸로 충분해요.", en: "That's right, that covers it.", ja: "はい、それで十分です。", zh: "对，那就够了。" },
      { speaker: "손님", kr: "미리 말씀해 주셨으면 좋았을 텐데요.", en: "It would have been nice if that had been mentioned earlier.", ja: "事前に教えていただけたらよかったんですが。", zh: "要是提前告诉我就好了。" },
      { speaker: "직원", kr: "죄송해요, 메뉴판에는 작게 적혀 있어요. 다음엔 미리 안내할게요.", en: "I'm sorry — it's noted in small print on the menu. We'll mention it upfront next time.", ja: "申し訳ございません、メニューには小さく書いてあります。次は事前にご案内します。", zh: "不好意思，菜单上写得比较小。下次会提前说明的。" },
      { speaker: "손님", kr: "네, 그렇게 해 주세요.", en: "Yes, please do that.", ja: "はい、そうしてください。", zh: "好的，请那样做吧。" },
    ],
  },
  {
    id: "restaurant-b2x-cancelpart",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Canceling part of an order", ja: "注文の一部をキャンセルする", zh: "取消部分点单" },
    lines: [
      { speaker: "손님", kr: "저희가 방금 시킨 것 중에 튀김 하나는 취소할 수 있을까요?", en: "Of what we just ordered, could we cancel one of the fried dishes?", ja: "さっき注文したものの中で、揚げ物一つをキャンセルできますか？", zh: "我们刚点的东西里，可以取消一份炸物吗？" },
      { speaker: "직원", kr: "확인해 볼게요, 조리가 이미 시작됐을 수도 있어서요.", en: "Let me check — the kitchen may have already started on it.", ja: "確認します、もう調理が始まっているかもしれないので。", zh: "我确认一下，可能已经开始做了。" },
      { speaker: "직원", kr: "죄송한데 이미 튀기고 있대요.", en: "I'm sorry, they say it's already frying.", ja: "申し訳ないんですが、もう揚げているそうです。", zh: "不好意思，说是已经在炸了。" },
      { speaker: "손님", kr: "아, 그럼 어쩔 수 없죠. 대신 포장해서 가져가도 돼요?", en: "Ah, then I guess there's no helping it. Can we take it to go instead?", ja: "あ、それなら仕方ないですね。代わりに持ち帰りにしてもいいですか？", zh: "啊，那也没办法了。可以改成打包带走吗？" },
      { speaker: "직원", kr: "네, 그렇게 해 드릴게요.", en: "Yes, we can do that for you.", ja: "はい、そのようにいたします。", zh: "可以，那就给您打包。" },
      { speaker: "손님", kr: "감사합니다, 그럼 그렇게 해 주세요.", en: "Thank you, let's go with that then.", ja: "ありがとうございます、ではそうしてください。", zh: "谢谢，那就麻烦您了。" },
      { speaker: "직원", kr: "네, 계산할 때 포장 용기 값이 조금 붙어요.", en: "Sure — just note there's a small container fee added at checkout.", ja: "はい、お会計の際に容器代が少し追加されます。", zh: "好的，结账时会加收一点包装容器费。" },
    ],
  },
  {
    id: "restaurant-b2x-togobox",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "A fee for the to-go container", ja: "持ち帰り容器の料金", zh: "打包盒收费" },
    lines: [
      { speaker: "손님", kr: "영수증에 포장 용기비가 있던데 원래 이렇게 받아요?", en: "I see a container fee on the receipt — is that normally charged?", ja: "レシートに容器代がありましたが、通常こうやって取るんですか？", zh: "收据上有个包装容器费，一直都是这样收费的吗？" },
      { speaker: "직원", kr: "네, 저희 매장은 용기값이 따로 있어요, 죄송해요.", en: "Yes, our restaurant charges for containers separately — sorry about that.", ja: "はい、当店は容器代が別にかかります、申し訳ございません。", zh: "对，我们店的容器费是另外收的，不好意思。" },
      { speaker: "손님", kr: "다른 데는 보통 무료던데 좀 놀랐어요.", en: "It's usually free elsewhere, so I was a bit surprised.", ja: "他の店では大体無料なので、ちょっと驚きました。", zh: "别的地方一般都是免费的，我有点惊讶。" },
      { speaker: "직원", kr: "저도 알아요, 손님들이 종종 말씀하세요.", en: "I know — guests mention that fairly often.", ja: "私も分かります、お客様からよく言われます。", zh: "我知道，客人经常这么说。" },
      { speaker: "손님", kr: "그럼 다음엔 미리 안내판이라도 있으면 좋겠어요.", en: "It would help if there were a sign about it in advance next time.", ja: "では次は事前に案内板でもあるといいですね。", zh: "那下次要是能提前放个告示牌就好了。" },
      { speaker: "직원", kr: "좋은 의견 감사해요, 건의해 볼게요.", en: "Thanks for the feedback, I'll pass that suggestion along.", ja: "貴重なご意見ありがとうございます、提案してみます。", zh: "谢谢您的建议，我会反映上去的。" },
      { speaker: "손님", kr: "네, 부탁드릴게요.", en: "Yes, please do.", ja: "はい、お願いします。", zh: "好的，拜托了。", vi: "có please làm" },
    ],
  },
  {
    id: "restaurant-b2x-recipehint",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Asking for a hint about the recipe", ja: "レシピのヒントを尋ねる", zh: "打听配方线索" },
    lines: [
      { speaker: "손님", kr: "이 소스가 진짜 맛있는데 혹시 어떤 재료가 들어가는지 알려 주실 수 있어요?", en: "This sauce is really delicious — could you tell me what ingredients go into it?", ja: "このソース、本当に美味しいんですが、どんな材料が入っているか教えていただけますか？", zh: "这个酱汁真的很好吃，可以告诉我里面放了什么材料吗？" },
      { speaker: "직원", kr: "정확한 레시피는 저도 몰라요, 사장님만 아세요.", en: "I don't actually know the exact recipe — only the owner does.", ja: "正確なレシピは私も知りません、店長だけが知っています。", zh: "确切的配方我也不清楚，只有老板知道。" },
      { speaker: "손님", kr: "아쉽네요, 그럼 대략적인 재료라도요.", en: "That's a shame — could you give me a rough idea, at least?", ja: "残念ですね、では大体の材料だけでも。", zh: "有点可惜，那大概的材料也可以告诉我吗？" },
      { speaker: "직원", kr: "간장이랑 마늘, 배즙이 들어간다고 들었어요.", en: "I've heard it has soy sauce, garlic, and pear juice in it.", ja: "醤油とニンニク、梨のジュースが入っていると聞きました。", zh: "听说里面放了酱油、大蒜和梨汁。" },
      { speaker: "손님", kr: "그렇군요, 집에서 한번 만들어 볼게요.", en: "I see — I'll try making it at home sometime.", ja: "そうなんですね、家で一度作ってみます。", zh: "原来如此，我在家试着做做看。" },
      { speaker: "직원", kr: "완전히 똑같지는 않겠지만 비슷하게 나올 거예요.", en: "It won't be exactly the same, but it should come out close.", ja: "全く同じにはならないでしょうが、近い味にはなると思います。", zh: "可能不会完全一样，但味道应该会很接近。" },
      { speaker: "손님", kr: "감사합니다, 재밌겠네요.", en: "Thanks, that sounds fun.", ja: "ありがとうございます、楽しそうですね。", zh: "谢谢，听起来挺有意思的。" },
    ],
  },
  {
    id: "restaurant-b2x-noisecomplaint",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Requesting a quieter table due to noise", ja: "騒音で席の変更をお願いする", zh: "因为吵闹要求换座位" },
    lines: [
      { speaker: "손님", kr: "죄송한데 옆 테이블이 너무 시끄러워서 대화가 안 돼요.", en: "Sorry, but the table next to us is so loud we can't have a conversation.", ja: "すみませんが、隣の席がうるさすぎて会話ができません。", zh: "不好意思，隔壁桌太吵了，我们没法聊天。" },
      { speaker: "직원", kr: "죄송합니다, 확인해 보겠습니다.", en: "I'm sorry — let me check on that.", ja: "申し訳ございません、確認いたします。", zh: "非常抱歉，我去确认一下。" },
      { speaker: "직원", kr: "혹시 다른 자리로 옮겨 드려도 될까요?", en: "Would it be all right if we moved you to a different table?", ja: "もしよろしければ、別のお席に移していただいてもよろしいですか？", zh: "如果可以的话，能给您换个座位吗？" },
      { speaker: "손님", kr: "네, 옮길 수 있으면 그게 낫겠어요.", en: "Yes, moving would be better if that's possible.", ja: "はい、移動できるならその方がいいです。", zh: "好的，能换的话那样更好。" },
      { speaker: "직원", kr: "안쪽에 조용한 자리가 있어요, 이쪽으로 오세요.", en: "There's a quiet table further in — this way, please.", ja: "奥に静かな席がございます、こちらへどうぞ。", zh: "里面有安静的位置，这边请。" },
      { speaker: "손님", kr: "훨씬 낫네요, 감사합니다.", en: "This is much better, thank you.", ja: "だいぶ良くなりました、ありがとうございます。", zh: "好多了，谢谢。" },
      { speaker: "직원", kr: "불편을 드려서 죄송했습니다.", en: "I'm sorry for the inconvenience.", ja: "ご不便をおかけして申し訳ございませんでした。", zh: "给您添麻烦了，非常抱歉。" },
    ],
  },
  {
    id: "restaurant-b2x-foreigncurrency",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Paying in a foreign currency", ja: "外貨で支払う", zh: "用外币付款" },
    lines: [
      { speaker: "손님", kr: "혹시 달러로 계산할 수 있어요? 원화가 부족해서요.", en: "Could I possibly pay in dollars? I'm short on Korean won.", ja: "ドルで支払うことはできますか？ウォンが足りなくて。", zh: "可以用美元结账吗？韩元不太够。" },
      { speaker: "직원", kr: "죄송한데 저희는 원화나 카드로만 받아요.", en: "I'm sorry, but we only accept won or card payment.", ja: "申し訳ございませんが、当店はウォンかカードのみとなります。", zh: "不好意思，我们只收韩元或刷卡。" },
      { speaker: "손님", kr: "그럼 카드로 할게요, 영어로 된 영수증도 받을 수 있어요?", en: "Then I'll pay by card — can I also get a receipt in English?", ja: "では、カードにします、英語のレシートもいただけますか？", zh: "那我刷卡吧，可以给我英文收据吗？" },
      { speaker: "직원", kr: "네, 영어 영수증도 출력할 수 있어요.", en: "Yes, we can print an English receipt too.", ja: "はい、英語のレシートも発行できます。", zh: "可以，我们也能打印英文收据。" },
      { speaker: "손님", kr: "잘됐네요, 부탁드려요.", en: "That's great, please do.", ja: "よかったです、お願いします。", zh: "太好了，麻烦您了。" },
      { speaker: "직원", kr: "카드 넣어 주세요.", en: "Please insert your card.", ja: "カードを挿入してください。", zh: "请插入卡片。" },
      { speaker: "손님", kr: "여기요, 감사합니다.", en: "Here you go, thank you.", ja: "どうぞ、ありがとうございます。", zh: "给您，谢谢。" },
    ],
  },
  {
    id: "restaurant-b2x-proposal",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Setting up a candle for a proposal", ja: "プロポーズ用のキャンドルを準備する", zh: "为求婚布置蜡烛" },
    lines: [
      { speaker: "손님", kr: "제가 오늘 여자친구한테 프러포즈를 하려고 하는데 도와주실 수 있어요?", en: "I'm planning to propose to my girlfriend today — could you help me set something up?", ja: "今日彼女にプロポーズしようと思っているんですが、手伝っていただけますか？", zh: "我今天打算向女朋友求婚，可以帮我准备一下吗？" },
      { speaker: "직원", kr: "와, 축하드려요! 어떻게 도와드릴까요?", en: "Wow, congratulations! How can we help?", ja: "わあ、おめでとうございます！どのようにお手伝いしましょうか？", zh: "哇，恭喜您！我们能怎么帮忙呢？" },
      { speaker: "손님", kr: "디저트 나올 때 촛불이랑 꽃잎을 좀 놓아 주실 수 있을까요?", en: "Could you set out a candle and some flower petals when the dessert comes out?", ja: "デザートが出るときにキャンドルと花びらを置いていただけますか？", zh: "甜点上桌时可以放上蜡烛和花瓣吗？" },
      { speaker: "직원", kr: "네, 가능해요. 반지는 어떻게 전달할지도 정해 두셨어요?", en: "Yes, we can do that. Have you also decided how you'll present the ring?", ja: "はい、可能です。指輪はどうやって渡すか決めていますか？", zh: "可以的。戒指打算怎么拿出来，您决定好了吗？" },
      { speaker: "손님", kr: "접시 밑에 숨겨 주시면 좋을 것 같아요.", en: "I think hiding it under the plate would be nice.", ja: "お皿の下に隠していただけるといいと思います。", zh: "我想藏在盘子底下会比较好。" },
      { speaker: "직원", kr: "좋은 생각이에요, 저희가 조심히 준비해 드릴게요.", en: "That's a great idea — we'll set it up carefully for you.", ja: "いいアイデアですね、こちらで丁寧にご用意します。", zh: "这个主意很好，我们会小心准备的。" },
      { speaker: "손님", kr: "정말 감사합니다, 긴장되네요.", en: "Thank you so much — I'm really nervous.", ja: "本当にありがとうございます、緊張しますね。", zh: "真的太感谢了，我好紧张。" },
    ],
  },
  {
    id: "restaurant-b2x-kidsfree",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Kids eat free promotion", ja: "子供無料キャンペーン", zh: "儿童免费用餐活动" },
    lines: [
      { speaker: "손님", kr: "저희 아이가 다섯 살인데 어린이 무료 행사 대상이 되나요?", en: "My child is five years old — does that qualify for the kids-eat-free promotion?", ja: "うちの子は五歳なんですが、子供無料キャンペーンの対象になりますか？", zh: "我孩子五岁，符合儿童免费活动的条件吗？" },
      { speaker: "직원", kr: "네, 여섯 살 이하는 성인 메뉴 하나당 한 명 무료예요.", en: "Yes, kids six and under get one free meal per adult entrée ordered.", ja: "はい、六歳以下は大人メニュー一つにつき一人無料です。", zh: "对，六岁以下的孩子每点一份成人套餐可以免费一位。" },
      { speaker: "손님", kr: "저희는 성인 메뉴 두 개를 시켰는데, 그럼 애가 둘이어도 다 무료예요?", en: "We ordered two adult entrées — so would both of our kids be free then?", ja: "私たちは大人メニューを二つ頼んだんですが、子供が二人でも両方無料ですか？", zh: "我们点了两份成人套餐，那两个孩子都能免费吗？" },
      { speaker: "직원", kr: "네, 성인 메뉴 개수만큼 적용돼서 두 명 다 무료예요.", en: "Yes, it applies per adult entrée ordered, so both kids would be free.", ja: "はい、大人メニューの数だけ適用されるので、二人とも無料です。", zh: "对，是按成人套餐数量算的，所以两个孩子都免费。" },
      { speaker: "손님", kr: "잘됐네요, 그럼 아이들 메뉴도 시킬게요.", en: "That's great — we'll order the kids' meals then.", ja: "よかったです、では子供メニューも注文します。", zh: "太好了，那我们也点儿童套餐吧。" },
      { speaker: "직원", kr: "네, 어떤 메뉴로 하시겠어요?", en: "Sure, which items would you like for them?", ja: "はい、どのメニューになさいますか？", zh: "好的，要点哪些菜？" },
      { speaker: "손님", kr: "돈가스 두 개 주세요.", en: "Two pork cutlets, please.", ja: "とんかつを二つお願いします。", zh: "请给我两份炸猪排。" },
    ],
  },
  {
    id: "restaurant-b2x-seasonal",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Debating the seasonal special", ja: "季節限定メニューを迷う", zh: "纠结要不要点季节限定菜" },
    lines: [
      { speaker: "직원", kr: "이번 주 계절 특선은 전복 리조또인데 한번 드셔 보시겠어요?", en: "This week's seasonal special is abalone risotto — would you like to try it?", ja: "今週の季節限定メニューはアワビのリゾットですが、一度お試しになりますか？", zh: "这周的季节限定菜是鲍鱼烩饭，要不要尝试一下？" },
      { speaker: "손님", kr: "궁금하긴 한데, 평소에 먹던 파스타랑 많이 다른가요?", en: "I'm curious, but is it very different from the pasta I usually get?", ja: "気にはなりますが、普段食べているパスタとかなり違いますか？", zh: "有点好奇，跟我平时吃的意面差别大吗？" },
      { speaker: "직원", kr: "크림 베이스라서 좀 더 진한 편이고, 전복이 많이 들어가 있어요.", en: "It's cream-based, so it's richer, and it has a generous amount of abalone in it.", ja: "クリームベースなので濃厚な方で、アワビがたっぷり入っています。", zh: "是奶油底的，味道更浓一些,而且放了很多鲍鱼。" },
      { speaker: "손님", kr: "가격도 더 비싸겠죠?", en: "It's probably more expensive too, right?", ja: "値段も高いですよね？", zh: "价格应该也更贵吧？" },
      { speaker: "직원", kr: "네, 파스타보다 오천 원 정도 더 비싸요.", en: "Yes, it's about five thousand won more than the pasta.", ja: "はい、パスタより五千ウォンほど高いです。", zh: "对，比意面贵大概5000韩元。" },
      { speaker: "손님", kr: "그럼 이번엔 모험 삼아 그걸로 해 볼게요.", en: "Then I'll take a chance and try that this time.", ja: "では今回は冒険してそれにしてみます。", zh: "那我这次就冒险试试那个吧。" },
      { speaker: "직원", kr: "좋은 선택이실 거예요, 바로 준비해 드릴게요.", en: "I think you'll be pleased — I'll get it started right away.", ja: "いい選択だと思います、すぐご用意いたします。", zh: "我觉得您会喜欢的，马上给您准备。" },
    ],
  },
  {
    id: "restaurant-b2x-nutallergy",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "A detailed nut allergy discussion", ja: "ナッツアレルギーについて詳しく相談する", zh: "详细讨论坚果过敏问题" },
    lines: [
      { speaker: "손님", kr: "제가 견과류 알레르기가 심한 편이라서 조리 과정도 좀 여쭤봐도 될까요?", en: "I have a fairly severe nut allergy — could I ask about how the dish is prepared too?", ja: "私はナッツアレルギーがかなり重い方なので、調理過程についても伺ってもいいですか？", zh: "我对坚果过敏比较严重，可以问一下烹饪过程吗？" },
      { speaker: "직원", kr: "네, 물론이죠. 어떤 게 걱정되세요?", en: "Yes, of course. What are you concerned about?", ja: "はい、もちろんです。何がご心配ですか？", zh: "当然可以。您担心的是什么？" },
      { speaker: "손님", kr: "같은 팬에서 견과류가 들어간 요리를 같이 조리하나요?", en: "Do you cook dishes with nuts in the same pan?", ja: "同じフライパンでナッツ入りの料理も一緒に調理しますか？", zh: "含坚果的菜品是不是用同一个锅做的？" },
      { speaker: "직원", kr: "저희는 팬을 나눠서 쓰긴 하는데, 완전히 분리된 건 아니에요.", en: "We do use separate pans, but they're not entirely isolated from each other.", ja: "フライパンは分けて使っていますが、完全に分離されているわけではありません。", zh: "我们锅是分开用的，但不是完全隔离的。" },
      { speaker: "손님", kr: "그럼 완전히 안전하다고는 말씀 못 드리시는 거죠?", en: "So you can't say it's completely safe, then?", ja: "では、完全に安全だとは言えないということですね？", zh: "那就是说不能保证百分之百安全对吧？" },
      { speaker: "직원", kr: "네, 솔직히 백 퍼센트 보장은 어려워요. 주방장님께 따로 여쭤볼게요.", en: "Right, honestly we can't guarantee it's a hundred percent safe. Let me ask the chef separately.", ja: "はい、正直言って百パーセントの保証は難しいです。シェフに別途確認します。", zh: "对，说实话很难保证百分之百安全。我另外问一下主厨。" },
      { speaker: "손님", kr: "네, 확인해 주시면 정말 감사하겠습니다.", en: "Yes, I'd really appreciate you checking on that.", ja: "はい、確認していただけると本当に助かります。", zh: "好的，麻烦您确认一下，非常感谢。" },
    ],
  },
  {
    id: "restaurant-b2x-nomsg",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Requesting no MSG", ja: "化学調味料抜きをお願いする", zh: "要求不加味精" },
    lines: [
      { speaker: "손님", kr: "혹시 조미료 없이 만들어 주실 수 있어요? 먹으면 머리가 아파서요.", en: "Could you make it without MSG? It gives me headaches when I eat it.", ja: "化学調味料なしで作っていただけますか？食べると頭が痛くなるので。", zh: "可以不放味精吗？我吃了会头疼。" },
      { speaker: "직원", kr: "저희는 육수에 조미료가 조금 들어가긴 해요.", en: "Our broth does have a small amount of seasoning added.", ja: "うちのスープには少し調味料が入っています。", zh: "我们的汤底里确实放了一点调味料。" },
      { speaker: "손님", kr: "그럼 완전히 빼는 건 어려운 거죠?", en: "So it's difficult to leave it out entirely, then?", ja: "では、完全に抜くのは難しいんですね？", zh: "那完全去掉是不是很难？" },
      { speaker: "직원", kr: "다른 육수를 따로 준비할 수는 있는데, 시간이 좀 걸려요.", en: "We could prepare a separate broth, but it would take a bit longer.", ja: "別のスープを別途用意することはできますが、少し時間がかかります。", zh: "可以单独准备一份汤底，但会花点时间。" },
      { speaker: "손님", kr: "괜찮아요, 기다릴게요. 건강이 더 중요하니까요.", en: "That's fine, I'll wait — my health matters more.", ja: "大丈夫です、待ちます。健康の方が大事ですから。", zh: "没关系，我等着。健康更重要。" },
      { speaker: "직원", kr: "알겠습니다, 십오 분 정도 걸릴 것 같아요.", en: "Understood, it should take about fifteen minutes.", ja: "かしこまりました、十五分ほどかかりそうです。", zh: "明白了，大概要十五分钟左右。" },
      { speaker: "손님", kr: "네, 부탁드릴게요.", en: "Yes, please go ahead.", ja: "はい、お願いします。", zh: "好的，麻烦您了。" },
    ],
  },
  {
    id: "restaurant-b2x-wifidown",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "Wifi problems during a work meeting", ja: "仕事の会議中のWi-Fiトラブル", zh: "工作会议时Wi-Fi出问题" },
    lines: [
      { speaker: "손님", kr: "죄송한데 와이파이가 계속 끊겨서 화상 회의를 못 하겠어요.", en: "Sorry, but the wifi keeps dropping and I can't get through this video call.", ja: "すみませんが、Wi-Fiが何度も切れてビデオ会議ができません。", zh: "不好意思，Wi-Fi一直断，视频会议开不了。" },
      { speaker: "직원", kr: "죄송해요, 요즘 손님이 많아서 그런 것 같아요.", en: "I'm sorry — it's probably because we've had a lot of guests lately.", ja: "申し訳ございません、最近お客様が多いせいだと思います。", zh: "不好意思，最近客人比较多，可能是这个原因。" },
      { speaker: "손님", kr: "혹시 재부팅하면 나아질까요?", en: "Would restarting the router help, maybe?", ja: "もしかして再起動したら良くなりますか？", zh: "重新启动一下会不会好一点？" },
      { speaker: "직원", kr: "네, 지금 바로 라우터를 재시작해 볼게요.", en: "Yes, let me restart the router right now.", ja: "はい、今すぐルーターを再起動してみます。", zh: "好的，我马上重启一下路由器。" },
      { speaker: "직원", kr: "잠깐만 기다려 주시겠어요, 이 분 정도면 돼요.", en: "Could you wait just a moment — it should take about two minutes.", ja: "少々お待ちいただけますか、二分ほどで済みます。", zh: "请您稍等一下，大概两分钟就好。" },
      { speaker: "손님", kr: "알겠어요, 회의가 곧 시작돼서 걱정되긴 하네요.", en: "Okay — I'm a bit worried since my meeting is about to start.", ja: "分かりました、会議がもうすぐ始まるので少し心配ですね。", zh: "好的，会议马上就要开始了，有点担心。" },
      { speaker: "직원", kr: "최대한 서둘러 볼게요, 정말 죄송합니다.", en: "I'll hurry as much as I can — I'm really sorry about this.", ja: "できるだけ急ぎます、本当に申し訳ございません。", zh: "我尽量快点，真的很抱歉。" },
    ],
  },
  {
    id: "restaurant-b2x-coldseat",
    situationKey: "restaurant",
    level: "B2",
    title: { en: "A drafty seat near the door", ja: "ドア近くの隙間風が入る席", zh: "靠近门口通风的座位" },
    lines: [
      { speaker: "손님", kr: "저희 자리가 문 바로 옆이라 사람들 드나들 때마다 바람이 들어와요.", en: "Our table is right next to the door, so a draft comes in every time someone goes in and out.", ja: "私たちの席がドアのすぐ横で、人が出入りするたびに風が入ってきます。", zh: "我们的座位就在门边，每次有人进出都会有风吹进来。" },
      { speaker: "직원", kr: "아, 불편하셨겠어요. 다른 자리로 안내해 드릴까요?", en: "Ah, that must have been uncomfortable. Would you like to be seated somewhere else?", ja: "あ、それは不便でしたね。他のお席にご案内しましょうか？", zh: "啊，那一定很不舒服吧。要不要给您换个座位？" },
      { speaker: "손님", kr: "네, 가능하면 안쪽으로 옮기고 싶어요.", en: "Yes, if possible I'd like to move further inside.", ja: "はい、可能であれば奥の方に移りたいです。", zh: "好的，如果可以的话我想坐到里面去。" },
      { speaker: "직원", kr: "지금은 자리가 다 찼는데, 십 분 정도면 하나 빌 것 같아요.", en: "Everything's full right now, but a table should open up in about ten minutes.", ja: "今は席が全部埋まっていますが、十分ほどで一つ空きそうです。", zh: "现在座位都满了，大概十分钟后会空出一个。" },
      { speaker: "손님", kr: "그럼 그때까지는 어떻게 하죠? 너무 추워서요.", en: "Then what should we do until then? It's really cold.", ja: "では、それまでどうしましょうか？とても寒いので。", zh: "那在那之前该怎么办呢？真的很冷。" },
      { speaker: "직원", kr: "우선 담요를 갖다드릴게요, 자리 나면 바로 알려 드릴게요.", en: "I'll bring you a blanket for now, and let you know the moment a table opens.", ja: "まずブランケットをお持ちします、席が空いたらすぐお知らせします。", zh: "我先给您拿条毯子，位置一空出来我就通知您。" },
      { speaker: "손님", kr: "감사합니다, 그렇게 해 주세요.", en: "Thank you, please do that.", ja: "ありがとうございます、そうしてください。", zh: "谢谢，那就麻烦您了。" },
    ],
  },
];

export const RESTAURANT_QUIZZES: Record<string, DialogueQuiz> = {
  "restaurant-a1x-window": {
    q: "What does the customer ask for?",
    opts: ["A table by the window", "A table outside", "A booth", "A table by the kitchen"],
    ans: 0,
  },
  "restaurant-a1x-barleytea": {
    q: "What does the customer request more of?",
    opts: ["Water", "Barley tea", "Ice", "Soup"],
    ans: 1,
  },
  "restaurant-a1x-bell": {
    q: "What does the customer ask for first after pressing the bell?",
    opts: ["The menu", "The bill", "Water", "Chopsticks"],
    ans: 2,
  },
  "restaurant-a1x-rice": {
    q: "How much does the extra rice cost?",
    opts: ["500 won", "1,000 won", "1,500 won", "It's free"],
    ans: 1,
  },
  "restaurant-a1x-fork": {
    q: "What does the customer ask for instead of chopsticks?",
    opts: ["A spoon", "A fork", "A knife", "Nothing"],
    ans: 1,
  },
  "restaurant-a1x-togo": {
    q: "How is the customer taking their food?",
    opts: ["Eating in", "To go", "Delivery", "They didn't decide"],
    ans: 1,
  },
  "restaurant-a1x-restroom": {
    q: "Where does the staff say the restroom is?",
    opts: ["Near the entrance", "Upstairs", "At the far end", "Next to the kitchen"],
    ans: 2,
  },
  "restaurant-a1x-napkin": {
    q: "What did the customer ask for?",
    opts: ["More tissues", "A spoon", "The bill", "Water"],
    ans: 0,
  },
  "restaurant-a1x-cardonly": {
    q: "How can the customer pay?",
    opts: ["Cash only", "Card only", "Cash or card", "Mobile pay only"],
    ans: 1,
  },
  "restaurant-a1x-veggie": {
    q: "What does the customer end up ordering?",
    opts: ["Bibimbap without meat", "Grilled fish", "Salad", "Noodles"],
    ans: 0,
  },
  "restaurant-a1x-wifi": {
    q: "Where can the customer find the wifi password?",
    opts: ["On the wall", "On the receipt", "On the menu", "They have to ask again"],
    ans: 1,
  },
  "restaurant-a1x-water2": {
    q: "What kind of water does the customer choose?",
    opts: ["Still water", "Sparkling water", "Hot water", "No water"],
    ans: 1,
  },
  "restaurant-a1x-bartable": {
    q: "Why does the customer ask for a bar seat?",
    opts: ["They're with a group", "They're alone", "It's cheaper", "It's near the window"],
    ans: 1,
  },
  "restaurant-a1x-kidsmenu": {
    q: "What does the customer order from the kids menu?",
    opts: ["Pork cutlet", "Omurice", "Noodles", "Pizza"],
    ans: 1,
  },
  "restaurant-a1x-quiet": {
    q: "Why does the customer want to move tables?",
    opts: ["Too cold", "Too far from the door", "Too loud", "Too close to the kitchen"],
    ans: 2,
  },
  "restaurant-a2x-allergy": {
    q: "What is the customer allergic to?",
    opts: ["Garlic", "Onions", "Seafood", "Nuts"],
    ans: 1,
  },
  "restaurant-a2x-grill": {
    q: "How does the staff say to grill the meat?",
    opts: ["Flip it several times", "Flip it only once", "Don't flip it at all", "Cut it before grilling"],
    ans: 1,
  },
  "restaurant-a2x-ssam": {
    q: "What does the staff say to put on the lettuce first?",
    opts: ["Rice and kimchi", "Meat and ssamjang", "Garlic only", "Just meat"],
    ans: 1,
  },
  "restaurant-a2x-setmenu": {
    q: "What main dish does the customer choose?",
    opts: ["Pasta", "Steak", "Soup", "Salad"],
    ans: 1,
  },
  "restaurant-a2x-splitdish": {
    q: "What does the staff offer the two customers?",
    opts: ["A discount", "An extra plate", "A bigger portion", "A free drink"],
    ans: 1,
  },
  "restaurant-a2x-forgot": {
    q: "Why hadn't the food arrived?",
    opts: ["The kitchen was closed", "The order got missed", "They ran out of ingredients", "The customer ordered late"],
    ans: 1,
  },
  "restaurant-a2x-aircon": {
    q: "What does the staff bring the customer besides adjusting the temperature?",
    opts: ["A jacket", "A blanket", "Hot tea", "A heater"],
    ans: 1,
  },
  "restaurant-a2x-parking": {
    q: "How much free parking does the customer get?",
    opts: ["30 minutes", "1 hour", "2 hours", "No free parking"],
    ans: 1,
  },
  "restaurant-a2x-lastorder": {
    q: "What time is last order?",
    opts: ["9:00", "9:20", "9:30", "10:00"],
    ans: 2,
  },
  "restaurant-a2x-delivery": {
    q: "What service is currently available?",
    opts: ["Delivery only", "Dine-in only", "Both delivery and dine-in", "Neither"],
    ans: 1,
  },
  "restaurant-a2x-lostcard": {
    q: "Where was the customer's card found?",
    opts: ["On the floor", "At the register", "In their bag", "It was never found"],
    ans: 1,
  },
  "restaurant-a2x-lesssalt": {
    q: "What two things does the customer ask to reduce?",
    opts: ["Spice and salt", "Salt and sugar", "Oil and salt", "Sugar and spice"],
    ans: 1,
  },
  "restaurant-a2x-music": {
    q: "Why does the customer ask to lower the music?",
    opts: ["It's giving them a headache", "It's hard to have a conversation", "It's the wrong genre", "It's too late at night"],
    ans: 1,
  },
  "restaurant-a2x-dessertspoon": {
    q: "How many extra spoons does the customer ask for?",
    opts: ["One", "Two", "Three", "None"],
    ans: 1,
  },
  "restaurant-a2x-birthdaynoodle": {
    q: "What do noodles symbolize according to the staff?",
    opts: ["Good luck", "A long life", "Wealth", "Happiness"],
    ans: 1,
  },
  "restaurant-b1x-discount": {
    q: "What happens with the expired coupon?",
    opts: ["It's rejected completely", "The staff makes a one-time exception", "The customer gets a new coupon", "The manager is called"],
    ans: 1,
  },
  "restaurant-b1x-noshow": {
    q: "Why did the restaurant give away the customer's table?",
    opts: ["The customer canceled", "They couldn't reach the customer after the reservation time passed", "The customer never reserved", "It was a mistake by the app"],
    ans: 1,
  },
  "restaurant-b1x-corkage": {
    q: "How much is the corkage fee?",
    opts: ["10,000 won", "15,000 won", "20,000 won", "It's free"],
    ans: 1,
  },
  "restaurant-b1x-combo": {
    q: "What is included in the two-person set?",
    opts: ["Two meats, stew, and rice", "Salad and soup only", "Just meat", "Rice and side dishes only"],
    ans: 0,
  },
  "restaurant-b1x-buffet": {
    q: "What happens if a guest leaves too much food?",
    opts: ["Nothing happens", "There's an extra charge", "They get banned", "They must apologize to staff"],
    ans: 1,
  },
  "restaurant-b1x-cooktime": {
    q: "What does the customer order while waiting for the braised ribs?",
    opts: ["Salad", "Pajeon", "Soup", "Rice"],
    ans: 1,
  },
  "restaurant-b1x-meeting": {
    q: "Where does the staff seat the customer for their meeting?",
    opts: ["By the window", "At the bar", "In a private room", "Outside on the patio"],
    ans: 2,
  },
  "restaurant-b1x-photo": {
    q: "What does the customer ask the staff to do?",
    opts: ["Recommend a dish", "Take a photo", "Turn down the music", "Bring the check"],
    ans: 1,
  },
  "restaurant-b1x-halal": {
    q: "What does the customer end up ordering?",
    opts: ["Grilled fish", "Pork dish", "Bibimbap", "Steak"],
    ans: 0,
  },
  "restaurant-b1x-gochujang": {
    q: "How much extra gochujang does the customer request?",
    opts: ["A little", "A lot", "None, they change their mind", "Just enough for tasting"],
    ans: 1,
  },
  "restaurant-b1x-festival": {
    q: "How is the festival discount applied?",
    opts: ["Customers must ask for it", "It's applied automatically at checkout", "Only for drinks", "Only on weekends"],
    ans: 1,
  },
  "restaurant-b1x-sidechange": {
    q: "How much extra does it cost to swap the side dish?",
    opts: ["It's free", "500 won", "1,000 won", "2,000 won"],
    ans: 1,
  },
  "restaurant-b1x-splitcards": {
    q: "How do the customers want to split the payment?",
    opts: ["Evenly", "Unevenly, by a specific amount", "One person pays everything", "They use one card"],
    ans: 1,
  },
  "restaurant-b1x-holiday": {
    q: "Until what time is the restaurant open on the holiday?",
    opts: ["5 PM", "6 PM", "8 PM", "It's closed"],
    ans: 1,
  },
  "restaurant-b1x-privateroom": {
    q: "What is the minimum number of people for the private room?",
    opts: ["Four", "Six", "Eight", "Ten"],
    ans: 1,
  },
  "restaurant-b1x-reheat": {
    q: "Why did the soup need to be reheated?",
    opts: ["It was made too early", "It got cold while they were talking", "It was the wrong dish", "It was never hot"],
    ans: 1,
  },
  "restaurant-b2x-buffetmixup": {
    q: "What happened to the customer's plate?",
    opts: ["It fell on the floor", "Another guest took it by mistake", "The kitchen forgot to make it", "It was still cooking"],
    ans: 1,
  },
  "restaurant-b2x-appissue": {
    q: "What was the problem with the reservation?",
    opts: ["It was made for the wrong day", "It never actually went through despite the confirmation screen", "The customer canceled it", "The restaurant was closed"],
    ans: 1,
  },
  "restaurant-b2x-latecall": {
    q: "How late can the customer be without needing to call again?",
    opts: ["10 minutes", "15 minutes", "20 minutes", "30 minutes"],
    ans: 2,
  },
  "restaurant-b2x-servicecharge": {
    q: "What does the automatic service charge mean for the customer?",
    opts: ["They still need to leave a tip", "They don't need to leave an additional tip", "It's optional", "It only applies to large groups"],
    ans: 1,
  },
  "restaurant-b2x-cancelpart": {
    q: "Why couldn't the fried dish be canceled?",
    opts: ["It was already paid for", "It was already being cooked", "The kitchen was closed", "It was a group order rule"],
    ans: 1,
  },
  "restaurant-b2x-togobox": {
    q: "What does the customer suggest for next time?",
    opts: ["Lowering the fee", "Posting a sign about the fee in advance", "Removing the fee entirely", "Charging more"],
    ans: 1,
  },
  "restaurant-b2x-recipehint": {
    q: "Who actually knows the exact recipe?",
    opts: ["The server", "The owner", "No one", "A cookbook"],
    ans: 1,
  },
  "restaurant-b2x-noisecomplaint": {
    q: "What solution does the staff offer?",
    opts: ["Asking the other table to quiet down", "Moving the customer to a quieter table", "Giving a discount", "Nothing can be done"],
    ans: 1,
  },
  "restaurant-b2x-foreigncurrency": {
    q: "How does the customer end up paying?",
    opts: ["In dollars", "By card", "In won cash", "They can't pay"],
    ans: 1,
  },
  "restaurant-b2x-proposal": {
    q: "Where does the customer want to hide the ring?",
    opts: ["In a drink", "Under the plate", "In a napkin", "In a gift box"],
    ans: 1,
  },
  "restaurant-b2x-kidsfree": {
    q: "How many kids qualify for the free promotion in this case?",
    opts: ["None", "One", "Both", "It's unclear"],
    ans: 2,
  },
  "restaurant-b2x-seasonal": {
    q: "How much more expensive is the seasonal special?",
    opts: ["2,000 won", "5,000 won", "10,000 won", "It's the same price"],
    ans: 1,
  },
  "restaurant-b2x-nutallergy": {
    q: "Can the staff guarantee the food is completely safe from nuts?",
    opts: ["Yes, completely", "No, not one hundred percent", "Only for some dishes", "They refuse to answer"],
    ans: 1,
  },
  "restaurant-b2x-nomsg": {
    q: "What does making the broth without MSG require?",
    opts: ["Nothing extra", "A separate broth that takes longer", "A different dish entirely", "It's not possible at all"],
    ans: 1,
  },
  "restaurant-b2x-wifidown": {
    q: "What does the staff do to try to fix the wifi?",
    opts: ["Call a technician", "Restart the router", "Give the customer a new password", "Tell them to use mobile data"],
    ans: 1,
  },
  "restaurant-b2x-coldseat": {
    q: "What does the staff do while the customer waits for a new table?",
    opts: ["Nothing", "Bring a blanket", "Close the door", "Give a discount"],
    ans: 1,
  },
};
