import type { Dialogue, DialogueQuiz } from "@/lib/listening-dialogues";

// Shopping situation C1/C2 expansion (2026-08): raises advanced coverage to 20 dialogues per level.
export const SHOPPING_C_EXPANSION: Dialogue[] = [
  {
    id: "shopping-c1y-fastfashion",
    situationKey: "shopping",
    level: "C1",
    title: "Debating fast fashion with a friend",
    lines: [
      { speaker: "수진", kr: "이 브랜드 요즘 일주일마다 신상 쏟아내잖아. 솔직히 좀 심하지 않아?", en: "This brand drops new arrivals literally every week now. Honestly, isn't that a bit much?" },
      { speaker: "민호", kr: "가격만 보면 부담 없으니까 자꾸 손이 가긴 하지. 근데 나도 요즘 마음이 편치는 않더라.", en: "Since the prices are so low, it's tempting to keep buying. But lately I haven't felt great about it either." },
      { speaker: "수진", kr: "옷 수명이 짧아서 몇 번 입다 버려지는 게 태반이래. 그게 다 환경 부담으로 돌아오는 거지.", en: "Apparently most of it barely survives a few wears before being thrown out. That all comes back as an environmental burden." },
      { speaker: "민호", kr: "그렇다고 무작정 안 사는 것도 답은 아닌 것 같아. 대신 소재나 생산 방식을 따져보고 사는 건 어때?", en: "I don't think just refusing to buy anything is the answer either. What about checking the materials and production methods before buying?" },
      { speaker: "수진", kr: "그것도 결국 소비자가 발품 팔아야 하는 거잖아. 기업이 정보를 투명하게 공개해야 맞는 거 아니야?", en: "But that still puts the burden on the consumer to dig for it. Shouldn't companies be the ones disclosing that information transparently?" },
      { speaker: "민호", kr: "맞아, 라벨에 원산지랑 소재만 적혀 있지 노동 환경이나 탄소 배출량은 전혀 안 나오잖아.", en: "True, labels only show origin and material, nothing about labor conditions or carbon emissions." },
      { speaker: "수진", kr: "그래서 요즘은 리세일이나 수선 서비스 있는 브랜드 위주로 사려고 해. 오래 입을 수 있으면 그게 최선인 것 같아.", en: "That's why I've been leaning toward brands with resale or repair services. If I can wear something for a long time, that seems like the best I can do." },
      { speaker: "민호", kr: "듣고 보니 나도 옷장 정리부터 다시 해야겠다. 안 입는 거 팔고 진짜 필요한 것만 사야지.", en: "Hearing that, I think I need to sort out my closet first. I should sell what I don't wear and only buy what I actually need." },
      { speaker: "수진", kr: "그게 제일 확실한 방법이지. 소비 습관 하나 바꾸는 게 결국 제일 큰 변화를 만드는 것 같아.", en: "That's the surest way. Changing one consumption habit ends up making the biggest difference in the end." },
    ],
  },
  {
    id: "shopping-c1y-buyernegotiate",
    situationKey: "shopping",
    level: "C1",
    title: "A department store buyer negotiates with a designer",
    lines: [
      { speaker: "바이어", kr: "이번 시즌 컬렉션 반응이 좋아서 저희 매장에 정식으로 입점을 제안드리고 싶습니다.", en: "The response to this season's collection has been strong, so I'd like to formally propose bringing you into our store." },
      { speaker: "디자이너", kr: "제안은 감사한데, 저희는 소량 생산 방식이라 백화점 물량을 맞추기가 쉽지 않을 것 같아요.", en: "I appreciate the offer, but we run small-batch production, so it might be hard to meet a department store's volume." },
      { speaker: "바이어", kr: "처음부터 대량으로 시작할 필요는 없습니다. 시즌당 소량으로 시작해서 반응을 보며 늘려가는 방식도 가능해요.", en: "You don't have to start with a large volume. We can begin with a small quantity per season and scale based on response." },
      { speaker: "디자이너", kr: "그럼 수수료 구조는 어떻게 되나요? 저희 같은 작은 브랜드한테는 그게 가장 부담되는 부분이라서요.", en: "Then what would the commission structure look like? That's the part that weighs heaviest on a small brand like ours." },
      { speaker: "바이어", kr: "신진 디자이너 육성 프로그램으로 진행하면 초기 수수료율을 낮춰드릴 수 있고, 매대 위치도 우선 배정해 드립니다.", en: "If we run this under our emerging-designer program, we can lower the initial commission rate and give you priority placement as well." },
      { speaker: "디자이너", kr: "위치는 정말 중요하죠. 매대가 구석에 있으면 아무리 옷이 좋아도 눈에 안 띄니까요.", en: "Placement really matters. No matter how good the clothes are, they won't get noticed if the rack is tucked in a corner." },
      { speaker: "바이어", kr: "맞습니다. 대신 계약 기간은 6개월로 짧게 잡고, 성과에 따라 재계약 여부를 논의하는 방식을 제안드리고 싶어요.", en: "Exactly. In exchange, I'd like to propose a short six-month contract term, with renewal discussed based on performance." },
      { speaker: "디자이너", kr: "합리적이네요. 재고 반품 조건만 조금 더 명확히 해 주시면 저희 쪽에서도 긍정적으로 검토할 수 있을 것 같아요.", en: "That sounds reasonable. If you can just clarify the return conditions for unsold inventory, we could consider this positively on our end." },
      { speaker: "바이어", kr: "물론이죠. 계약서 초안 작성해서 이번 주 안으로 다시 연락드리겠습니다.", en: "Of course. We'll draft the contract and get back to you within the week." },
    ],
  },
  {
    id: "shopping-c1y-dynamicpricing",
    situationKey: "shopping",
    level: "C1",
    title: "Discussing algorithmic pricing and dynamic discounts",
    lines: [
      { speaker: "지훈", kr: "어제 봤던 항공권이 오늘 다시 들어가니까 가격이 올라 있더라. 이거 알고리즘이 사람 행동 패턴 읽는 거 아니야?", en: "The flight I looked at yesterday went up in price when I checked again today. Isn't this the algorithm reading people's behavior patterns?" },
      { speaker: "은영", kr: "맞아, 검색만 자주 해도 수요가 몰린다고 판단해서 가격을 올리는 방식이래. 재방문 자체가 신호가 되는 거지.", en: "Right, apparently just repeated searches signal high demand, so the price gets raised. The revisit itself becomes a signal." },
      { speaker: "지훈", kr: "그럼 소비자 입장에서는 검색 기록을 지우거나 시크릿 모드로 들어가야 하는 거야? 좀 불합리한 것 같은데.", en: "So from a consumer's perspective, do I have to clear my search history or use incognito mode? That seems a bit unreasonable." },
      { speaker: "은영", kr: "실제로 그렇게들 많이 해. 근데 문제는 이게 투명하게 공개된 정책이 아니라는 거야. 소비자는 자기가 왜 더 비싸게 사는지도 몰라.", en: "A lot of people actually do that. But the problem is this isn't a transparent, disclosed policy. Consumers don't even know why they're paying more." },
      { speaker: "지훈", kr: "동일한 상품인데 사람마다 다른 가격을 보는 거잖아. 이거 가격 차별 아니야?", en: "It's the same product, but different people see different prices. Isn't that just price discrimination?" },
      { speaker: "은영", kr: "법적으로는 아직 회색 지대야. 항공사나 이커머스 업체들은 수요 예측에 따른 정상적인 가격 책정이라고 주장하거든.", en: "Legally it's still a gray area. Airlines and e-commerce companies argue it's just normal demand-based pricing." },
      { speaker: "지훈", kr: "그래도 최소한 어떤 요소가 가격에 영향을 주는지는 공개해야 하는 거 아닐까? 그래야 소비자가 선택을 할 수 있지.", en: "Still, shouldn't they at least disclose what factors affect the price? Only then can consumers actually make an informed choice." },
      { speaker: "은영", kr: "동의해. 결국 알고리즘이 소비자를 위한 도구인지, 기업 이익을 극대화하는 도구인지 경계가 애매해지는 거지.", en: "Agreed. In the end, the line blurs between whether the algorithm serves the consumer or just maximizes company profit." },
    ],
  },
  {
    id: "shopping-c1y-classaction",
    situationKey: "shopping",
    level: "C1",
    title: "A consumer rights advocate explains a class-action case",
    lines: [
      { speaker: "진행자", kr: "오늘은 최근 화제가 된 화장품 집단 소송 건에 대해 소비자 단체 관계자분을 모셨습니다. 간단히 설명 부탁드릴까요?", en: "Today we have a representative from a consumer rights group to discuss the recent class-action lawsuit over cosmetics. Could you give us a brief explanation?" },
      { speaker: "관계자", kr: "네, 해당 업체가 자사 제품에 표기하지 않은 성분이 실제로는 포함돼 있다는 사실이 검사 결과로 드러났습니다.", en: "Yes, testing revealed that the company's products actually contained an ingredient that wasn't listed on the label." },
      { speaker: "진행자", kr: "성분 표기 오류가 소송으로까지 번진 건 이례적인데요, 소비자 피해가 구체적으로 어떻게 확인됐나요?", en: "It's unusual for a labeling error to escalate into a lawsuit. How exactly was consumer harm confirmed?" },
      { speaker: "관계자", kr: "피부 트러블을 호소한 소비자 신고가 수백 건 접수됐고, 그중 일부는 병원 진단서까지 첨부해서 제출했습니다.", en: "Hundreds of consumer complaints about skin irritation were filed, and some even included medical diagnoses as evidence." },
      { speaker: "진행자", kr: "그렇다면 이번 소송에서 소비자들이 실질적으로 받을 수 있는 배상은 어떤 형태인가요?", en: "So in this lawsuit, what form of compensation can consumers actually expect to receive?" },
      { speaker: "관계자", kr: "제품 구매가 환불은 물론이고, 치료비 영수증이 있는 경우에는 별도로 실비 배상을 청구할 수 있는 구조입니다.", en: "It covers a refund of the purchase price, and for those with medical treatment receipts, they can separately claim reimbursement for actual costs." },
      { speaker: "진행자", kr: "일반 소비자가 개별적으로 소송을 걸기는 현실적으로 어려운데, 집단 소송의 의의는 어디에 있다고 보시나요?", en: "It's practically difficult for an individual consumer to sue on their own. Where do you see the significance of a class action?" },
      { speaker: "관계자", kr: "비용과 시간 부담을 나눠서 지는 대신, 다수의 피해를 한 번에 입증할 수 있다는 점에서 실효성이 훨씬 높습니다.", en: "By sharing the cost and time burden, it becomes far more effective at proving widespread harm all at once." },
      { speaker: "진행자", kr: "소비자분들이 참여 의사가 있으시면 어떤 절차를 밟으셔야 할까요?", en: "If viewers wish to participate, what procedure should they follow?" },
      { speaker: "관계자", kr: "저희 단체 홈페이지에 피해 사례 접수 창구를 열어두었으니, 구매 영수증과 함께 신청해 주시면 됩니다.", en: "We've opened a case-submission channel on our organization's website, so please apply along with your purchase receipt." },
    ],
  },
  {
    id: "shopping-c1y-minimalism",
    situationKey: "shopping",
    level: "C1",
    title: "Colleagues debating minimalism versus consumerism",
    lines: [
      { speaker: "재현", kr: "요새 미니멀 라이프가 유행이라던데, 나는 솔직히 물건 사는 게 낙인 사람이라 잘 이해가 안 가.", en: "I hear minimalist living is trendy these days, but honestly, buying things is my one joy in life, so I don't quite get it." },
      { speaker: "소라", kr: "나도 처음엔 그랬어. 근데 물건이 많아질수록 오히려 정신이 산만해지더라고. 뭘 어디 뒀는지도 기억을 못 해.", en: "I felt the same at first. But the more stuff I had, the more scattered my mind felt. I couldn't even remember where I put things." },
      { speaker: "재현", kr: "그래도 쇼핑할 때 느끼는 그 만족감은 무시할 수 없잖아. 스트레스 풀리는 방법이기도 하고.", en: "Still, you can't ignore the satisfaction you feel when shopping. It's also a way to relieve stress." },
      { speaker: "소라", kr: "그 만족감이 얼마나 가는지가 문제인 것 같아. 나는 사고 나서 며칠만 지나면 흥미가 뚝 떨어지더라고.", en: "I think the question is how long that satisfaction lasts. For me, my interest just drops off a few days after buying something." },
      { speaker: "재현", kr: "그건 나도 인정. 근데 미니멀리즘도 결국 극단으로 가면 강박이 되는 거 아니야? 물건 하나 들일 때마다 죄책감 느끼는 것도 이상하잖아.", en: "I'll grant you that. But doesn't minimalism become its own obsession when taken to an extreme? Feeling guilty every time you bring in one object seems odd too." },
      { speaker: "소라", kr: "맞아, 나도 처음엔 그렇게 강박적으로 접근했다가 오히려 지쳤어. 지금은 그냥 '이게 나한테 진짜 필요한가'만 묻는 정도로 완화했지.", en: "Right, I approached it that obsessively at first too and it just wore me out. Now I've relaxed it to simply asking 'do I really need this.'" },
      { speaker: "재현", kr: "그 정도면 나도 시도해 볼 만하겠다. 극단적으로 다 버리는 게 아니라 소비 기준을 세우는 거네.", en: "That level sounds doable for me too. It's not about tossing everything out extremely, but about setting a standard for consumption." },
      { speaker: "소라", kr: "그렇지. 결국 물건 자체보다 왜 사는지에 대한 이유가 더 중요한 것 같아.", en: "Exactly. In the end, the reason behind why you buy seems to matter more than the object itself." },
    ],
  },
  {
    id: "shopping-c1y-livecommerce",
    situationKey: "shopping",
    level: "C1",
    title: "A live-commerce host and guest discuss influencer ethics",
    lines: [
      { speaker: "진행자", kr: "오늘 방송에 인플루언서 마케팅 전문가분을 모셨는데요, 요즘 라이브 커머스에서 논란이 되는 부분이 있다고요?", en: "Today's broadcast features an influencer marketing expert, and I hear there's a controversial issue in live commerce right now." },
      { speaker: "게스트", kr: "네, 협찬받은 제품인데도 마치 직접 구매해서 써 본 것처럼 소개하는 경우가 많아서 문제가 되고 있습니다.", en: "Yes, there are many cases where sponsored products are introduced as if the host bought and used them personally, and that's become a problem." },
      { speaker: "진행자", kr: "시청자 입장에서는 진짜 후기인지 광고인지 구분이 안 되겠네요.", en: "From the viewer's perspective, it must be hard to tell whether it's a genuine review or an advertisement." },
      { speaker: "게스트", kr: "맞습니다. 법적으로는 협찬 사실을 명확히 고지해야 하는데, 자막을 아주 작게 넣거나 순식간에 지나가게 처리하는 경우가 많아요.", en: "Exactly. Legally, the sponsorship must be clearly disclosed, but many hosts insert the caption in tiny text or flash it by in an instant." },
      { speaker: "진행자", kr: "그럼 시청자가 속아서 구매하는 경우도 실제로 많은가요?", en: "So are there actually many cases of viewers being deceived into purchasing?" },
      { speaker: "게스트", kr: "네, 특히 한정 수량이나 실시간 할인이라는 표현을 반복하면서 구매를 서두르게 만드는 방식이 문제로 지적됩니다.", en: "Yes, in particular, repeating phrases like 'limited quantity' or 'real-time discount' to rush purchases has been pointed out as problematic." },
      { speaker: "진행자", kr: "그렇다면 소비자들이 방송을 보면서 스스로 점검할 수 있는 기준이 있을까요?", en: "Then are there any standards viewers can use to check for themselves while watching a broadcast?" },
      { speaker: "게스트", kr: "일단 협찬 고지 자막이 있는지 확인하고, 지나치게 긴박감을 조성하는 멘트가 반복되면 한 번쯤 의심해 보시는 게 좋습니다.", en: "First, check whether there's a sponsorship disclosure caption, and if urgency-inducing remarks repeat excessively, it's worth being a bit suspicious." },
      { speaker: "진행자", kr: "결국 플랫폼 차원의 규제도 필요하겠네요.", en: "In the end, platform-level regulation would be necessary too." },
      { speaker: "게스트", kr: "그렇습니다. 자율 규제만으로는 한계가 있으니 최소한의 고지 기준을 강제하는 제도가 마련돼야 한다고 봅니다.", en: "That's right. Self-regulation alone has its limits, so I believe a system enforcing minimum disclosure standards needs to be established." },
    ],
  },
  {
    id: "shopping-c1y-distribution",
    situationKey: "shopping",
    level: "C1",
    title: "Negotiating exclusive distribution rights",
    lines: [
      { speaker: "담당자", kr: "저희 쪽에서는 이번 브랜드의 국내 독점 유통권을 확보하고 싶습니다. 조건을 좀 더 구체적으로 논의해 볼까요?", en: "On our end, we'd like to secure exclusive domestic distribution rights for this brand. Shall we discuss the terms in more detail?" },
      { speaker: "본사", kr: "독점권을 드리려면 최소 주문 물량과 연간 매출 목표를 먼저 합의해야 합니다. 저희로서는 리스크가 있는 부분이라서요.", en: "To grant exclusivity, we'd first need to agree on a minimum order quantity and annual sales target. It carries some risk on our side." },
      { speaker: "담당자", kr: "이해합니다. 다만 초도 물량을 너무 높게 잡으시면 저희 쪽 자금 부담이 커져서 시작 자체가 어려워질 수 있어요.", en: "I understand. However, if the initial volume is set too high, it would place a heavy financial burden on us, which could make it hard to even get started." },
      { speaker: "본사", kr: "그렇다면 첫해는 목표치를 낮추는 대신, 미달 시 독점권이 자동으로 해지되는 조항을 넣는 건 어떨까요?", en: "Then how about lowering the target for the first year, but including a clause where exclusivity automatically terminates if the target isn't met?" },
      { speaker: "담당자", kr: "합리적이네요. 대신 마케팅 비용은 공동으로 부담하는 조건을 넣어 주셨으면 합니다.", en: "That sounds fair. In return, I'd like a clause where marketing costs are shared jointly." },
      { speaker: "본사", kr: "마케팅 비용 분담 비율은 어느 정도를 생각하고 계신가요?", en: "What ratio are you thinking of for splitting the marketing costs?" },
      { speaker: "담당자", kr: "저희가 판매 채널을 직접 관리하니 6대 4 정도로, 저희가 더 부담하는 대신 데이터 접근권을 요청드리고 싶습니다.", en: "Since we manage the sales channels directly, around a 6-to-4 split with us covering more, in exchange for requesting data access rights." },
      { speaker: "본사", kr: "데이터 공유는 저희도 필요한 부분이니 문제없습니다. 계약 기간은 3년으로 하고 갱신 조항을 넣는 걸로 정리하죠.", en: "Data sharing is something we need too, so that's no problem. Let's finalize a three-year contract term with a renewal clause." },
      { speaker: "담당자", kr: "좋습니다. 세부 조항은 법무팀 검토 거쳐서 다음 주에 최종 계약서로 보내드리겠습니다.", en: "Sounds good. We'll have the detailed clauses reviewed by legal and send the final contract next week." },
    ],
  },
  {
    id: "shopping-c1y-deescalate",
    situationKey: "shopping",
    level: "C1",
    title: "A manager trains staff on de-escalating a demanding customer",
    lines: [
      { speaker: "매니저", kr: "오늘은 지난주에 있었던 컴플레인 상황을 바탕으로 대응 요령을 좀 짚어보려고 해요.", en: "Today I want to go over some response techniques based on the complaint situation we had last week." },
      { speaker: "직원", kr: "그 손님은 정말 처음부터 언성을 높이셔서 어떻게 대응해야 할지 당황스러웠어요.", en: "That customer raised their voice from the very start, so I was flustered about how to respond." },
      { speaker: "매니저", kr: "그럴 땐 일단 손님 말을 끊지 말고 끝까지 들어드리는 게 우선이에요. 화가 난 이유를 먼저 인정해 드려야 대화가 풀려요.", en: "In that case, the priority is to not interrupt and let them finish speaking. You need to first acknowledge the reason for their anger before the conversation can move forward." },
      { speaker: "직원", kr: "그런데 손님 요구가 규정상 들어드릴 수 없는 경우엔 어떻게 말씀드려야 하나요?", en: "But when the customer's request can't be granted under policy, how should I phrase that?" },
      { speaker: "매니저", kr: "'안 됩니다'라고 바로 말하기보다, 규정을 설명하고 대안을 함께 제시하는 방식이 훨씬 효과적이에요.", en: "Rather than saying 'that's not possible' outright, it's far more effective to explain the policy and offer an alternative at the same time." },
      { speaker: "직원", kr: "대안이 마땅치 않은 경우도 있잖아요. 그럴 땐 어떻게 하죠?", en: "But there are cases with no good alternative. What do we do then?" },
      { speaker: "매니저", kr: "그럴 땐 상급자에게 넘기겠다고 미리 안내하는 게 낫습니다. 직원 선에서 끝까지 감당하려다 상황이 더 악화되는 경우가 많거든요.", en: "In that case, it's better to inform them in advance that you'll escalate to a supervisor. Situations often worsen when staff try to handle everything alone to the end." },
      { speaker: "직원", kr: "감정적으로 대응하지 않는 게 제일 어려운 것 같아요. 저도 모르게 방어적으로 말하게 되더라고요.", en: "Not responding emotionally seems to be the hardest part. I catch myself speaking defensively without meaning to." },
      { speaker: "매니저", kr: "그건 훈련으로 나아져요. 오늘 배운 대로 역할극 몇 번 더 해보면 실전에서 훨씬 수월해질 거예요.", en: "That improves with practice. If we do a few more role-plays like today, it'll get much easier in real situations." },
    ],
  },
  {
    id: "shopping-c1y-counterfeit",
    situationKey: "shopping",
    level: "C1",
    title: "A casual chat about counterfeit goods and IP law",
    lines: [
      { speaker: "태윤", kr: "친구가 해외여행 갔다가 짝퉁 가방을 사 왔더라고. 본인도 알면서 산 거긴 한데, 그거 국내 반입도 괜찮은 거야?", en: "My friend came back from a trip abroad with a fake bag. She knew it was fake when she bought it, but is bringing that into the country even okay?" },
      { speaker: "혜린", kr: "개인이 자기가 쓰려고 소량 들여오는 건 세관에서 웬만하면 넘어가긴 하는데, 판매 목적이면 완전히 얘기가 달라져.", en: "Customs usually lets it slide when it's a small amount for personal use, but if it's meant for resale, that's a completely different story." },
      { speaker: "태윤", kr: "판매 목적이면 어떻게 되는데?", en: "What happens if it's for resale?" },
      { speaker: "혜린", kr: "상표법 위반으로 형사 처벌 대상이 될 수 있어. 벌금은 물론이고 재판까지 갈 수도 있다더라.", en: "It can become subject to criminal punishment for trademark infringement. Fines, of course, and it could even go to trial." },
      { speaker: "태윤", kr: "생각보다 심각하네. 근데 요즘 짝퉁도 워낙 정교해져서 눈으로 구분하기가 거의 불가능하잖아.", en: "That's more serious than I thought. But nowadays fakes are so sophisticated that they're almost impossible to tell apart by eye." },
      { speaker: "혜린", kr: "맞아, 그래서 브랜드들도 정품 인증 앱이나 시리얼 번호 조회 같은 걸 도입하고 있대.", en: "Right, that's why brands are introducing things like authentication apps or serial number lookups." },
      { speaker: "태윤", kr: "그래도 소비자 입장에서는 값싸게 비슷한 걸 가질 수 있으니까 유혹을 느끼는 거 아니겠어?", en: "Still, from a consumer's perspective, isn't the temptation there because you can get something similar for cheap?" },
      { speaker: "혜린", kr: "그 마음은 이해하는데, 결국 그런 소비가 정품 브랜드의 디자인 투자나 품질 관리를 갉아먹는 거니까 장기적으론 손해 아닐까.", en: "I get that impulse, but ultimately that kind of consumption eats away at the original brand's design investment and quality control, so isn't it a loss in the long run?" },
    ],
  },
  {
    id: "shopping-c2y-brickmortar",
    situationKey: "shopping",
    level: "C2",
    title: "An op-ed-style talk on the decline of brick-and-mortar retail",
    lines: [
      { speaker: "진행자", kr: "오늘은 도심 상권의 공실률이 계속 치솟고 있다는 기사를 놓고 두 분 전문가와 이야기 나눠보겠습니다.", en: "Today we'll be discussing an article on the continually rising vacancy rates in downtown commercial districts with two experts." },
      { speaker: "평론가A", kr: "온라인 쇼핑의 편의성이야 부정할 수 없지만, 저는 오프라인 매장의 몰락을 단순히 기술 발전의 결과로만 보는 시각에는 동의하기 어렵습니다.", en: "The convenience of online shopping is undeniable, but I find it hard to agree with the view that the decline of physical stores is simply a result of technological progress." },
      { speaker: "평론가B", kr: "저는 좀 다르게 봅니다. 배송 인프라와 결제 시스템이 고도화되면서 오프라인이 제공하던 즉시성이라는 장점 자체가 무의미해진 측면이 크죠.", en: "I see it a bit differently. As delivery infrastructure and payment systems have advanced, the very advantage of immediacy that physical stores offered has largely become meaningless." },
      { speaker: "평론가A", kr: "그렇지만 임대료 정책이나 상권 관리에 대한 지자체의 태도도 함께 짚어야 하지 않을까요. 공실이 늘면서 임대료가 오히려 오르는 역설적 현상도 있잖습니까.", en: "But shouldn't we also examine local governments' stances on rent policy and district management? There's even the paradoxical phenomenon of rents rising as vacancies increase." },
      { speaker: "평론가B", kr: "그 지점은 저도 동의합니다. 다만 근본적으로는 소비자가 매장에서 얻는 경험적 가치를 재정의하지 못한 게 더 크다고 봅니다.", en: "I agree with that point too. But fundamentally, I think the bigger issue is that stores haven't managed to redefine the experiential value consumers get from visiting." },
      { speaker: "진행자", kr: "경험적 가치라 하시면 구체적으로 어떤 걸 말씀하시는 건가요?", en: "When you say experiential value, what specifically do you mean?" },
      { speaker: "평론가B", kr: "단순히 물건을 진열해 놓고 파는 공간이 아니라, 그 브랜드의 세계관을 체험하게 만드는 공간으로 전환해야 한다는 겁니다.", en: "It means the space needs to shift from simply displaying and selling goods to letting customers experience the brand's worldview firsthand." },
      { speaker: "평론가A", kr: "일리는 있습니다만, 그런 체험형 매장은 결국 대기업 자본이 있어야 가능한 모델 아닙니까. 중소 상인들은 어떻게 살아남으라는 겁니까.", en: "That has some merit, but ultimately such experiential stores are only possible with large corporate capital, aren't they? How are small merchants supposed to survive?" },
      { speaker: "평론가B", kr: "그 부분은 지역 상권 단위의 협업이나 공공 지원 정책이 뒷받침돼야겠죠. 개별 상인 혼자 감당할 문제는 아니라고 봅니다.", en: "That part would need to be backed by cooperation at the district level or public support policy. I don't think it's a problem individual merchants can bear alone." },
      { speaker: "진행자", kr: "결국 오프라인 상권의 생존은 기술 대응만이 아니라 정책과 공간 기획이 함께 맞물려야 한다는 말씀이시군요.", en: "So the survival of brick-and-mortar districts requires not just adapting to technology, but policy and spatial planning working in tandem as well." },
    ],
  },
  {
    id: "shopping-c2y-luxuryresale",
    situationKey: "shopping",
    level: "C2",
    title: "A journalistic segment on the luxury resale market",
    lines: [
      { speaker: "기자", kr: "명품 리셀 시장 규모가 매년 두 자릿수 성장을 기록하고 있는데요, 이 현상을 어떻게 진단하십니까?", en: "The luxury resale market has been posting double-digit growth every year. How do you diagnose this phenomenon?" },
      { speaker: "전문가", kr: "희소성이 곧 가치라는 명품 산업의 오랜 공식이 오히려 리셀 시장을 키우는 역설적 구조를 만든 셈입니다.", en: "The long-standing formula of the luxury industry that scarcity equals value has, ironically, created the very structure that fuels the resale market." },
      { speaker: "기자", kr: "브랜드 입장에서는 자사 제품이 되팔리며 웃돈이 붙는 걸 마냥 반가워하지는 않을 것 같은데요.", en: "From the brand's perspective, they probably aren't entirely thrilled that their own products are being resold at a markup." },
      { speaker: "전문가", kr: "그렇습니다. 그래서 최근에는 아예 브랜드가 직접 리셀 플랫폼과 제휴하거나 자체 인증 서비스를 내놓는 방향으로 선회하고 있어요.", en: "Right. That's why brands have recently pivoted toward directly partnering with resale platforms or launching their own authentication services." },
      { speaker: "기자", kr: "일종의 통제 불가능한 시장을 제도권 안으로 끌어들이는 전략이라고 봐도 될까요?", en: "Could we call this a strategy of pulling an otherwise uncontrollable market into the formal system?" },
      { speaker: "전문가", kr: "정확한 지적입니다. 동시에 신제품 판매만으로는 확보하기 어려운 소비자 데이터를 리셀 거래를 통해 얻을 수 있다는 이점도 있죠.", en: "That's a precise observation. At the same time, there's also the benefit of gaining consumer data through resale transactions that would be hard to capture through new-product sales alone." },
      { speaker: "기자", kr: "소비자 입장에서 리셀 구매가 늘어나는 이유는 단순히 가격 때문만은 아닌 것 같은데, 어떻게 보십니까?", en: "From the consumer side, the rise in resale purchasing doesn't seem to be purely about price. What's your view?" },
      { speaker: "전문가", kr: "단종된 한정판이나 희귀 컬러를 소유하고 싶은 수집 욕구도 상당한 비중을 차지합니다. 투자 자산으로 접근하는 경우도 늘고 있고요.", en: "The collector's desire to own discontinued limited editions or rare colorways accounts for a considerable share as well. There's also a growing tendency to approach it as an investment asset." },
      { speaker: "기자", kr: "투자 자산이라는 표현이 흥미로운데요, 실제로 그런 수익률이 지속 가능하다고 보시나요?", en: "The phrase 'investment asset' is interesting. Do you think that kind of return is actually sustainable?" },
      { speaker: "전문가", kr: "제한적으로만 가능하다고 봅니다. 극소수 희귀 품목을 제외하면 결국 유행 주기에 따라 가치가 급락할 위험이 크거든요.", en: "I think it's only sustainable in a limited sense. Except for a tiny number of rare items, there's a significant risk that value will crash sharply according to trend cycles." },
    ],
  },
  {
    id: "shopping-c2y-greenwashing",
    situationKey: "shopping",
    level: "C2",
    title: "Debate on greenwashing in retail marketing",
    lines: [
      { speaker: "사회자", kr: "'친환경'이라는 표현이 상품 포장 어디에나 붙는 시대가 됐는데, 이게 실질적인 변화를 반영하는 걸까요, 아니면 마케팅에 불과할까요?", en: "We've reached an era where the label 'eco-friendly' appears on nearly every product's packaging. Does this reflect real change, or is it just marketing?" },
      { speaker: "연구원", kr: "냉정히 말하면 상당 부분은 후자에 가깝습니다. 재활용 소재 함량이 5퍼센트만 넘어도 '친환경 라인'이라는 이름을 붙이는 사례가 허다하니까요.", en: "Frankly, a substantial portion leans toward the latter. There are plenty of cases where a product is branded an 'eco-friendly line' with recycled content barely over five percent." },
      { speaker: "업계관계자", kr: "그건 다소 극단적인 사례를 일반화하신 것 같습니다. 기준이 아직 명확히 정립되지 않은 초기 시장이라 혼란이 있는 것뿐이에요.", en: "I think that's generalizing from a somewhat extreme case. It's just confusion arising from an early-stage market where standards haven't yet been clearly established." },
      { speaker: "연구원", kr: "기준이 없다는 걸 핑계로 삼기엔 이미 소비자를 오도하고 있다는 지적이 여러 차례 나왔습니다. 자율에 맡기기엔 이미 늦은 것 아닐까요.", en: "Using the absence of standards as an excuse seems inadequate when there have already been repeated claims that consumers are being misled. Isn't it already too late to leave this to self-regulation?" },
      { speaker: "업계관계자", kr: "저희 업계도 인증 마크 도입 등 자체적으로 신뢰를 쌓으려는 노력을 하고 있습니다. 규제로 일괄 묶기엔 산업별 편차가 너무 커요.", en: "Our industry is also making efforts to build trust on its own, such as introducing certification marks. Blanket regulation would be difficult given how much variation there is across industries." },
      { speaker: "연구원", kr: "산업별 편차가 크다는 점이야말로 통일된 법적 기준이 필요한 이유 아닌가요. 자율 규제로는 무임승차하는 기업을 막을 방법이 없습니다.", en: "Isn't the very fact that variation is large across industries the reason a unified legal standard is needed? Self-regulation offers no way to stop free-riding companies." },
      { speaker: "사회자", kr: "소비자 입장에서는 그럼 지금 당장 뭘 근거로 판단해야 할까요?", en: "So from the consumer's standpoint, what should they use as a basis for judgment right now?" },
      { speaker: "연구원", kr: "일단 제3자 인증 기관의 마크가 있는지 확인하시고, 모호한 문구만 있고 수치가 없는 제품은 일단 의심하시는 게 안전합니다.", en: "First, check whether there's a mark from a third-party certification body, and it's safer to be suspicious of products with vague wording but no actual figures." },
      { speaker: "업계관계자", kr: "그 조언에는 저도 동의합니다. 결국 신뢰할 수 있는 정보를 제공하는 게 업계 전체의 장기적 이익과도 맞닿아 있으니까요.", en: "I agree with that advice too. Ultimately, providing trustworthy information is also tied to the long-term interest of the entire industry." },
    ],
  },
  {
    id: "shopping-c2y-personaldata",
    situationKey: "shopping",
    level: "C2",
    title: "A panel on personal data use in personalized retail",
    lines: [
      { speaker: "사회자", kr: "맞춤형 추천 서비스가 소비자 편의를 높인다는 주장과, 사실상 감시에 가깝다는 비판이 팽팽히 맞서고 있는데요.", en: "There's a sharp divide between the claim that personalized recommendation services enhance consumer convenience, and the criticism that they amount to surveillance." },
      { speaker: "패널A", kr: "저는 개인화 기술 자체를 부정할 필요는 없다고 봅니다. 문제는 데이터가 수집되는 과정에서 동의 절차가 형식적으로 흘러간다는 데 있습니다.", en: "I don't think we need to reject personalization technology itself. The problem lies in how the consent process becomes a mere formality during data collection." },
      { speaker: "패널B", kr: "저는 좀 더 근본적인 문제를 제기하고 싶습니다. 동의 자체가 실질적 선택권이 될 수 없는 구조 아닌가요. 거부하면 서비스 이용 자체가 막히는데요.", en: "I'd like to raise a more fundamental issue. Isn't the structure such that consent itself can't function as a genuine choice? If you refuse, you're blocked from using the service at all." },
      { speaker: "패널A", kr: "그 지적도 타당합니다만, 그렇다고 개인화 서비스를 전면 금지하면 오히려 소비자 편익이 크게 줄어드는 부작용도 무시할 수 없죠.", en: "That point is valid too, but if we ban personalized services outright, we can't ignore the side effect of significantly reducing consumer benefit." },
      { speaker: "패널B", kr: "편익과 프라이버시를 저울질하는 방식 자체가 이미 기업 논리에 치우친 것 아닐까요. 최소한의 정보로도 서비스는 충분히 작동할 수 있습니다.", en: "Isn't the very framework of weighing benefit against privacy already skewed toward corporate logic? Services can function perfectly well with minimal information." },
      { speaker: "패널A", kr: "이론적으로는 그렇지만, 실제로 추천 정확도가 떨어지면 소비자 불만도 함께 늘어난다는 데이터가 있습니다. 균형점을 찾는 게 관건이겠죠.", en: "In theory, yes, but there's data showing that when recommendation accuracy drops, consumer complaints rise as well. Finding the balance point is what matters." },
      { speaker: "사회자", kr: "그렇다면 규제 당국이 취해야 할 가장 시급한 조치는 무엇이라고 보십니까?", en: "Then what do you see as the most urgent action regulators should take?" },
      { speaker: "패널B", kr: "동의 화면을 세분화해서 항목별로 선택할 수 있게 하고, 거부해도 핵심 서비스는 이용 가능하도록 강제하는 게 먼저입니다.", en: "First, consent screens should be broken down so users can choose item by item, and it should be mandated that core services remain usable even when a user declines." },
      { speaker: "패널A", kr: "그 방향에는 저도 동의합니다. 다만 전환 비용을 기업이 일방적으로 떠안지 않도록 유예 기간을 두는 것도 함께 고려해야 할 겁니다.", en: "I agree with that direction too. However, we should also consider a grace period so companies aren't left to shoulder the transition cost unilaterally." },
    ],
  },
  {
    id: "shopping-c2y-labormarket",
    situationKey: "shopping",
    level: "C2",
    title: "A commentary on retail automation and labor displacement",
    lines: [
      { speaker: "진행자", kr: "무인 매장이 빠르게 확산되면서 매장 노동자의 일자리가 사라지고 있다는 우려가 커지고 있습니다.", en: "As unmanned stores rapidly spread, concerns are growing that retail workers' jobs are disappearing." },
      { speaker: "경제학자", kr: "역사적으로 자동화는 늘 일부 직군을 대체해 왔습니다. 다만 이번엔 그 속도가 유례없이 빠르다는 점이 다릅니다.", en: "Historically, automation has always replaced certain job categories. What's different this time is the unprecedented speed at which it's happening." },
      { speaker: "노동단체대표", kr: "속도만의 문제가 아닙니다. 대체된 노동자들이 재교육을 받고 새로운 일자리로 이동할 시간적 여유조차 주어지지 않는다는 게 핵심이에요.", en: "It's not just about speed. The core issue is that displaced workers aren't even given time to retrain and move into new jobs." },
      { speaker: "경제학자", kr: "그 부분은 저도 동의합니다. 다만 기업 입장에서는 인건비 상승 압박 속에서 자동화가 불가피한 생존 전략이라는 점도 고려해야 하지 않을까요.", en: "I agree with that point too. But shouldn't we also consider that, from the company's perspective, automation is an unavoidable survival strategy amid rising labor cost pressures?" },
      { speaker: "노동단체대표", kr: "생존 전략이라는 말로 노동자에게 전가되는 비용을 정당화할 수는 없습니다. 이익은 기업이 취하고 부담은 노동자가 지는 구조니까요.", en: "The phrase 'survival strategy' can't justify shifting the cost onto workers. It's a structure where the company reaps the benefit and the worker bears the burden." },
      { speaker: "진행자", kr: "그렇다면 두 분 모두 동의하실 수 있는 대안이 있을까요?", en: "Then is there a middle ground both of you could agree on?" },
      { speaker: "경제학자", kr: "자동화로 절감된 비용의 일부를 재교육 기금으로 의무화하는 방안은 현실적으로 검토할 만하다고 봅니다.", en: "I think it's realistic to consider mandating that a portion of the cost savings from automation be allocated to a retraining fund." },
      { speaker: "노동단체대표", kr: "그 정도로는 부족하지만 출발점은 될 수 있겠네요. 최소한 전환 과정에서 노동자가 완전히 배제되지는 않아야 합니다.", en: "That alone falls short, but it could be a starting point. At the very least, workers shouldn't be completely excluded from the transition process." },
      { speaker: "진행자", kr: "결국 기술 도입의 속도와 사회적 안전망 구축의 속도가 함께 논의돼야 할 문제라는 말씀이시군요.", en: "So the point is that the pace of technology adoption and the pace of building a social safety net need to be discussed together." },
    ],
  },
  {
    id: "shopping-c2y-thirdplace",
    situationKey: "shopping",
    level: "C2",
    title: "Analyzing retail spaces as a cultural 'third place'",
    lines: [
      { speaker: "평론가", kr: "최근 매장들이 상품 판매보다 공간 경험 자체에 더 공을 들이는 경향이 뚜렷해지고 있어요. 일종의 '제3의 공간' 전략이라고 볼 수 있죠.", en: "Recently there's a clear trend of stores investing more effort in the spatial experience itself than in selling products. You could call it a 'third place' strategy." },
      { speaker: "건축가", kr: "저도 동의합니다. 다만 그 개념이 원래 공동체적 교류를 위한 공간이었다는 점을 생각하면, 상업 공간에 갖다 붙이는 게 다소 역설적이지 않나 싶어요.", en: "I agree. But when you consider that the concept originally referred to spaces for communal interaction, it seems somewhat paradoxical to graft it onto commercial spaces." },
      { speaker: "평론가", kr: "역설적이긴 하지만, 소비자들이 실제로 그런 정서적 유대감을 느끼고 재방문한다는 점에서는 전략적으로 유효한 것 같습니다.", en: "It is paradoxical, but given that consumers actually feel that emotional bond and return, it seems strategically effective." },
      { speaker: "건축가", kr: "문제는 그 유대감이 진짜 공동체 의식이 아니라 브랜드가 설계한 감정이라는 데 있죠. 소비자는 결국 소비를 통해서만 그 공간에 속할 수 있으니까요.", en: "The problem is that the bond isn't genuine community feeling but an emotion designed by the brand. Ultimately, consumers can only belong to that space through consumption." },
      { speaker: "평론가", kr: "일리 있는 지적입니다. 그렇다고 해도 도서관이나 공원 같은 전통적인 제3의 공간이 줄어드는 현실에서, 이런 상업적 대안이라도 필요한 게 아닐까요.", en: "That's a fair point. Even so, given the reality that traditional third places like libraries or parks are shrinking, isn't a commercial alternative like this still necessary?" },
      { speaker: "건축가", kr: "대안이 될 수는 있어도 대체는 될 수 없다고 봅니다. 결국 그 공간은 소비력이 없는 사람에게는 열려 있지 않으니까요.", en: "It can serve as an alternative, but I don't think it can be a replacement. In the end, that space isn't open to people without purchasing power." },
      { speaker: "평론가", kr: "맞는 말씀입니다. 접근성의 불평등이라는 측면에서 보면 상업적 제3의 공간의 한계가 명확해지네요.", en: "That's a fair point. From the angle of accessibility inequality, the limits of the commercial third place become clear." },
      { speaker: "건축가", kr: "그래서 저는 도시 계획 차원에서 공공 공간과 상업 공간이 상호 보완하는 방향으로 설계돼야 한다고 봅니다.", en: "That's why I believe, at the urban planning level, public and commercial spaces need to be designed in a way that complements each other." },
      { speaker: "평론가", kr: "결국 상업 공간의 역할을 인정하되, 공공성이 배제되지 않도록 균형을 맞추는 게 앞으로의 과제겠네요.", en: "So the task going forward is to acknowledge the role of commercial space while balancing it so that public value isn't excluded." },
    ],
  },
  {
    id: "shopping-c2y-subscription",
    situationKey: "shopping",
    level: "C2",
    title: "A critique of subscription-based retail models",
    lines: [
      { speaker: "칼럼니스트", kr: "구독형 소비 모델이 거의 모든 카테고리로 확산되고 있는데, 이게 소비자에게 정말 이득인지는 따져볼 필요가 있습니다.", en: "The subscription consumption model has spread into nearly every category, but whether it's truly beneficial for consumers deserves scrutiny." },
      { speaker: "업계전문가", kr: "편의성 측면에서는 확실히 이점이 있습니다. 매번 구매 결정을 내리는 인지적 부담을 줄여주니까요.", en: "In terms of convenience, there are clear benefits. It reduces the cognitive burden of making a purchase decision every time." },
      { speaker: "칼럼니스트", kr: "그 편의성이 오히려 불필요한 지출을 방치하게 만드는 것 아닐까요. 자동 결제라는 특성상 해지 시점을 놓치는 소비자가 상당히 많습니다.", en: "But doesn't that convenience end up letting unnecessary spending slide? Given the nature of automatic billing, quite a lot of consumers miss the point at which they should cancel." },
      { speaker: "업계전문가", kr: "해지 절차가 복잡하게 설계된 서비스가 있는 건 사실입니다. 다만 업계 전체를 그렇게 일반화하기는 조심스럽습니다.", en: "It's true that some services design a deliberately complicated cancellation process. But I'd be cautious about generalizing that across the whole industry." },
      { speaker: "칼럼니스트", kr: "그렇다면 해지 절차를 가입 절차만큼 간단하게 만들도록 법으로 강제하는 방안에는 동의하십니까?", en: "Then would you agree with legally mandating that the cancellation process be made as simple as the sign-up process?" },
      { speaker: "업계전문가", kr: "그 방향 자체에는 반대할 이유가 없습니다. 오히려 투명성을 높이는 게 장기적으로 업계 신뢰도에도 도움이 될 거라고 봅니다.", en: "There's no reason to oppose that direction itself. In fact, I think increasing transparency would help industry credibility in the long run too." },
      { speaker: "칼럼니스트", kr: "소비자 입장에서 구독 서비스를 현명하게 이용하려면 어떤 습관이 필요할까요?", en: "From the consumer's side, what habits are needed to use subscription services wisely?" },
      { speaker: "업계전문가", kr: "정기적으로 이용 내역을 점검하고, 실제 사용 빈도가 낮은 구독은 과감히 정리하는 습관이 가장 기본이라고 봅니다.", en: "Regularly reviewing your usage history and decisively cutting subscriptions with low actual use frequency is the most basic habit." },
      { speaker: "칼럼니스트", kr: "결국 편리함과 지속적인 관리 사이의 균형을 소비자 스스로 찾아야 한다는 결론이네요.", en: "So the conclusion is that consumers themselves need to find the balance between convenience and ongoing management." },
    ],
  },
  {
    id: "shopping-c2y-secondhandstigma",
    situationKey: "shopping",
    level: "C2",
    title: "Cultural commentary on the changing perception of secondhand goods",
    lines: [
      { speaker: "사회학자", kr: "불과 십 년 전만 해도 중고 거래는 궁핍함의 상징처럼 여겨졌는데, 지금은 오히려 안목 있는 소비로 받아들여지는 분위기죠.", en: "Just a decade ago, secondhand trading was viewed almost as a symbol of poverty, but now it's accepted as discerning consumption instead." },
      { speaker: "기자", kr: "그런 인식 변화의 배경에는 어떤 요인이 있다고 보십니까?", en: "What factors do you see behind that shift in perception?" },
      { speaker: "사회학자", kr: "일단 환경 문제에 대한 세대 전반의 인식 수준이 확실히 높아졌고요, 동시에 희소한 빈티지 아이템을 소유하는 것 자체가 하나의 취향 표현으로 자리 잡았습니다.", en: "For one, awareness of environmental issues has clearly risen across the generation as a whole, and at the same time, owning rare vintage items has itself become a form of taste expression." },
      { speaker: "기자", kr: "취향 표현이라는 말씀이 흥미로운데요, 예전에는 새 제품을 소유하는 게 곧 취향의 증명이었잖습니까.", en: "That phrase 'taste expression' is interesting. In the past, owning something new was itself proof of taste." },
      { speaker: "사회학자", kr: "맞습니다. 그런데 대량 생산 시대에 새 제품은 오히려 누구나 가질 수 있는 것이 됐고, 반대로 단종되거나 희귀한 중고 아이템이 차별화의 수단이 된 거죠.", en: "Exactly. But in an era of mass production, new products became something anyone could have, whereas rare or discontinued secondhand items became the means of differentiation instead." },
      { speaker: "기자", kr: "그럼에도 여전히 위생이나 품질에 대한 거부감을 가진 소비자층도 상당할 것 같은데요.", en: "Even so, there must still be a substantial group of consumers who feel resistance around hygiene or quality." },
      { speaker: "사회학자", kr: "물론입니다. 다만 최근에는 전문 세탁 및 검수 서비스를 갖춘 플랫폼이 늘면서 그런 심리적 장벽이 상당히 낮아진 것도 사실이고요.", en: "Of course. But it's also true that as platforms with professional cleaning and inspection services have grown, that psychological barrier has been considerably lowered as well." },
      { speaker: "기자", kr: "결국 중고 시장의 성장이 단순한 절약을 넘어서 소비 문화 자체를 재편하고 있다고 봐도 될까요?", en: "So could we say that the growth of the secondhand market goes beyond simple frugality and is reshaping consumer culture itself?" },
      { speaker: "사회학자", kr: "그렇습니다. 소유의 의미가 '새것'에서 '이야기가 있는 것'으로 옮겨가는 흐름을 보여주는 대표적인 사례라고 생각합니다.", en: "That's right. I think it's a representative example showing the shift in the meaning of ownership from 'something new' to 'something with a story.'" },
    ],
  },
  {
    id: "shopping-c2y-hyperconsumerism",
    situationKey: "shopping",
    level: "C2",
    title: "A literary-style monologue reflecting on hyperconsumerism",
    lines: [
      { speaker: "화자", kr: "쇼핑몰 조명 아래 서 있으면 시간관념 자체가 사라진다는 걸 아세요? 창문 하나 없이 설계된 공간이 우연이 아니더라고요.", en: "Do you know that standing under a shopping mall's lighting, your very sense of time disappears? A space designed without a single window turns out not to be an accident." },
      { speaker: "청자", kr: "그렇게까지 생각해 본 적은 없는데, 듣고 보니 확실히 설계된 무언가라는 느낌이 드네요.", en: "I've never thought about it quite that way, but hearing you put it like that, it does feel like something deliberately engineered." },
      { speaker: "화자", kr: "저는 예전에 백화점에서 일했었는데, 매출이 저조한 날엔 향과 음악부터 바꿨어요. 손님의 감각을 조율하는 게 판매 전략의 시작이었던 거죠.", en: "I used to work at a department store, and on slow sales days, the first thing we'd change was the scent and the music. Tuning the customer's senses was where the sales strategy began." },
      { speaker: "청자", kr: "소비자는 자기가 자유의지로 물건을 고른다고 믿지만, 사실은 이미 설계된 동선 안에서 움직이는 걸 수도 있겠네요.", en: "Consumers believe they're choosing things of their own free will, but in reality they might just be moving within an already engineered path." },
      { speaker: "화자", kr: "정확히 그거예요. 에스컬레이터를 한 층씩 갈아타게 만드는 구조도, 결국 손님이 매장을 한 바퀴 더 돌게 만들려는 의도니까요.", en: "That's exactly it. Even the layout forcing you to switch escalators floor by floor is, in the end, designed to make you circle the store one more time." },
      { speaker: "청자", kr: "그런 걸 알고 나면 오히려 소비 자체에 냉소적이 될 것 같은데, 선생님은 지금도 물건을 사시나요?", en: "Knowing all that, I'd think it would make you cynical about consumption itself. Do you still buy things now?" },
      { speaker: "화자", kr: "물론이죠. 다만 예전처럼 충동적으로 손이 가진 않아요. 살 때마다 스스로에게 묻거든요. 이게 정말 내 선택인지, 아니면 저 조명과 음악이 만든 착각인지.", en: "Of course. But I don't reach for things impulsively the way I used to. Every time I buy something, I ask myself whether it's really my own choice, or an illusion created by that lighting and music." },
      { speaker: "청자", kr: "그 질문 하나만으로도 소비 습관이 꽤 달라질 것 같네요.", en: "It sounds like that single question alone could change consumption habits quite a lot." },
      { speaker: "화자", kr: "적어도 후회는 훨씬 줄어들더라고요. 결국 소비란 것도 자기 자신을 얼마나 들여다보느냐의 문제인 것 같아요.", en: "At the very least, my regrets have dropped considerably. In the end, consumption seems to come down to how closely you examine yourself." },
    ],
  },
];

export const SHOPPING_C_QUIZZES: Record<string, DialogueQuiz> = {
  "shopping-c1y-fastfashion": {
    q: "What solution does 수진 say she has personally shifted toward regarding fast fashion?",
    opts: [
      "Buying only from brands with resale or repair services",
      "Boycotting all clothing purchases entirely",
      "Only buying secondhand from thrift stores",
      "Demanding refunds for old purchases",
    ],
    ans: 0,
  },
  "shopping-c1y-buyernegotiate": {
    q: "What does the buyer propose to lower the burden on the small designer brand?",
    opts: [
      "A permanent, unconditional five-year contract",
      "Immediate large-volume mass production",
      "A lower initial commission rate and priority shelf placement under an emerging-designer program",
      "Full ownership transfer of the brand's designs",
    ],
    ans: 2,
  },
  "shopping-c1y-dynamicpricing": {
    q: "According to 은영, what can trigger a price increase under dynamic/algorithmic pricing?",
    opts: [
      "Paying with a specific credit card",
      "Repeated searches signaling high demand",
      "Buying during a holiday sale",
      "Using a mobile app instead of a website",
    ],
    ans: 1,
  },
  "shopping-c1y-classaction": {
    q: "What triggered the class-action lawsuit discussed on the show?",
    opts: [
      "A price-fixing scandal among competitors",
      "An undisclosed ingredient found in the cosmetics that wasn't listed on the label",
      "Late delivery of online orders",
      "A data breach exposing customer information",
    ],
    ans: 1,
  },
  "shopping-c1y-minimalism": {
    q: "How did 소라 eventually moderate her approach to minimalism?",
    opts: [
      "By refusing to buy anything for a full year",
      "By donating all her belongings at once",
      "By simply asking herself if she truly needs an item before buying it",
      "By hiring a professional organizer",
    ],
    ans: 2,
  },
  "shopping-c1y-livecommerce": {
    q: "What problematic practice does the guest describe regarding live-commerce hosts?",
    opts: [
      "Selling only counterfeit goods",
      "Refusing to answer viewer questions",
      "Presenting sponsored products as if personally purchased, with disclosure captions made tiny or fleeting",
      "Charging viewers a subscription fee to watch",
    ],
    ans: 2,
  },
  "shopping-c1y-distribution": {
    q: "What compromise do the two sides reach regarding the first year's sales target?",
    opts: [
      "The target is removed entirely with no conditions",
      "The target is lowered, but exclusivity auto-terminates if it isn't met",
      "The target is doubled to secure exclusivity faster",
      "The distributor pays a penalty instead of meeting any target",
    ],
    ans: 1,
  },
  "shopping-c1y-deescalate": {
    q: "What does the manager recommend when a customer's request truly cannot be met and no alternative exists?",
    opts: [
      "Ending the conversation immediately without explanation",
      "Letting the customer speak with a supervisor instead of staff handling it alone to the end",
      "Offering a full refund regardless of policy",
      "Calling security right away",
    ],
    ans: 1,
  },
  "shopping-c1y-counterfeit": {
    q: "According to 혜린, what changes the legal consequences of bringing counterfeit goods into the country?",
    opts: [
      "Whether the goods are intended for personal use or resale",
      "The country the goods were purchased in",
      "The brand name printed on the item",
      "Whether the item was purchased online or in person",
    ],
    ans: 0,
  },
  "shopping-c2y-brickmortar": {
    q: "What does 평론가B argue is the deeper reason behind brick-and-mortar decline, beyond online convenience?",
    opts: [
      "Rising minimum wage for retail staff",
      "Stores failing to redefine the experiential value they offer",
      "A nationwide ban on physical advertising",
      "Excessive government subsidies for e-commerce",
    ],
    ans: 1,
  },
  "shopping-c2y-luxuryresale": {
    q: "Why are luxury brands increasingly partnering directly with resale platforms?",
    opts: [
      "To eliminate the resale market entirely",
      "To lower the price of new products",
      "To bring the market into the formal system and gain consumer data",
      "Because government regulation forces them to",
    ],
    ans: 2,
  },
  "shopping-c2y-greenwashing": {
    q: "What does the researcher suggest consumers check to avoid being misled by 'eco-friendly' claims?",
    opts: [
      "The color of the packaging",
      "Whether there is a third-party certification mark and concrete figures, not just vague wording",
      "The price of the product compared to competitors",
      "Whether the product is imported or domestic",
    ],
    ans: 1,
  },
  "shopping-c2y-personaldata": {
    q: "What does 패널B argue is the fundamental flaw in current consent processes for personalized retail?",
    opts: [
      "Consent forms are too short to read",
      "Consent isn't a real choice because refusing blocks access to the service entirely",
      "Companies never ask for consent at all",
      "Consent is only required for international customers",
    ],
    ans: 1,
  },
  "shopping-c2y-labormarket": {
    q: "What compromise do the economist and labor representative reach by the end of the discussion?",
    opts: [
      "A total ban on all retail automation",
      "Mandatory retraining funds from part of the cost savings automation generates",
      "Doubling wages for all remaining retail workers",
      "Delaying automation by exactly ten years",
    ],
    ans: 1,
  },
  "shopping-c2y-thirdplace": {
    q: "What limitation does the architect point out about commercial spaces as a 'third place'?",
    opts: [
      "They are always too small to be useful",
      "They require government approval to open",
      "They aren't open to people without purchasing power, unlike true public space",
      "They can only exist in large cities",
    ],
    ans: 2,
  },
  "shopping-c2y-subscription": {
    q: "What reform does the columnist propose regarding subscription cancellation?",
    opts: [
      "Banning subscriptions for anyone under 25",
      "Making cancellation legally as simple as signing up",
      "Requiring a phone call to sign up in the first place",
      "Charging a fee for every cancellation request",
    ],
    ans: 1,
  },
  "shopping-c2y-secondhandstigma": {
    q: "According to the sociologist, why has owning secondhand items become a form of 'taste expression'?",
    opts: [
      "Because new products became widely accessible, making rare secondhand items the new means of differentiation",
      "Because new products are now more expensive than vintage items",
      "Because secondhand stores now sell only counterfeit designer goods",
      "Because government subsidies make secondhand shopping mandatory",
    ],
    ans: 0,
  },
  "shopping-c2y-hyperconsumerism": {
    q: "What question does the speaker say she now asks herself before every purchase?",
    opts: [
      "Whether the item is the cheapest option available",
      "Whether it is really her own choice or an illusion created by the store's lighting and music",
      "Whether she has enough space at home for it",
      "Whether her friends would approve of the purchase",
    ],
    ans: 1,
  },
};
