import type { RawVocabWord } from "./types";

export const DAILY_LIFE_WORDS: RawVocabWord[] = [
  // A1
  { level: "A1", korean: "물", romanization: "mul", meaning_en: "water", example_kr: "저는 물을 마셔요.", example_en: "I drink water." },
  { level: "A1", korean: "밥", romanization: "bap", meaning_en: "rice / a meal", example_kr: "우리는 밥을 먹어요.", example_en: "We eat a meal." },
  { level: "A1", korean: "학교", romanization: "hakgyo", meaning_en: "school", example_kr: "저는 학교에 가요.", example_en: "I go to school." },
  { level: "A1", korean: "친구", romanization: "chingu", meaning_en: "friend", example_kr: "이 사람은 제 친구예요.", example_en: "This person is my friend." },
  { level: "A1", korean: "가족", romanization: "gajok", meaning_en: "family", example_kr: "우리 가족은 네 명이에요.", example_en: "My family has four people." },
  { level: "A1", korean: "이름", romanization: "ireum", meaning_en: "name", example_kr: "제 이름은 마리아예요.", example_en: "My name is Maria." },
  { level: "A1", korean: "오늘", romanization: "oneul", meaning_en: "today", example_kr: "오늘은 월요일이에요.", example_en: "Today is Monday." },
  { level: "A1", korean: "아침", romanization: "achim", meaning_en: "morning", example_kr: "저는 아침에 커피를 마셔요.", example_en: "I drink coffee in the morning." },
  { level: "A1", korean: "저녁", romanization: "jeonyeok", meaning_en: "evening", example_kr: "우리는 저녁에 만나요.", example_en: "We meet in the evening." },
  { level: "A1", korean: "사람", romanization: "saram", meaning_en: "person", example_kr: "저 사람은 누구예요?", example_en: "Who is that person?" },
  { level: "A1", korean: "집", romanization: "jip", meaning_en: "house", example_kr: "저는 집에 가요.", example_en: "I'm going home." },
  { level: "A1", korean: "시간", romanization: "sigan", meaning_en: "time", example_kr: "저는 시간이 없어요.", example_en: "I don't have time." },
  { level: "A1", korean: "돈", romanization: "don", meaning_en: "money", example_kr: "저는 돈이 없어요.", example_en: "I don't have money." },
  { level: "A1", korean: "전화", romanization: "jeonhwa", meaning_en: "phone", example_kr: "친구한테 전화를 해요.", example_en: "I call my friend." },
  { level: "A1", korean: "문", romanization: "mun", meaning_en: "door", example_kr: "문을 닫아 주세요.", example_en: "Please close the door." },
  { level: "A1", korean: "창문", romanization: "changmun", meaning_en: "window", example_kr: "창문을 열어요.", example_en: "I open the window." },
  { level: "A1", korean: "의자", romanization: "uija", meaning_en: "chair", example_kr: "의자에 앉으세요.", example_en: "Please sit on the chair." },

  // A2
  { level: "A2", korean: "날씨", romanization: "nalssi", meaning_en: "weather", example_kr: "오늘 날씨가 좋아요.", example_en: "The weather is nice today." },
  { level: "A2", korean: "계획", romanization: "gyehoek", meaning_en: "plan", example_kr: "주말 계획이 있어요?", example_en: "Do you have plans for the weekend?" },
  { level: "A2", korean: "약속", romanization: "yaksok", meaning_en: "appointment / promise", example_kr: "친구와 약속이 있어요.", example_en: "I have an appointment with a friend." },
  { level: "A2", korean: "회사", romanization: "hoesa", meaning_en: "company", example_kr: "저는 회사에 다녀요.", example_en: "I work at a company." },
  { level: "A2", korean: "근처", romanization: "geuncheo", meaning_en: "nearby / vicinity", example_kr: "근처에 카페가 있어요.", example_en: "There's a cafe nearby." },
  { level: "A2", korean: "편의점", romanization: "pyeonuijeom", meaning_en: "convenience store", example_kr: "편의점에서 물을 샀어요.", example_en: "I bought water at the convenience store." },
  { level: "A2", korean: "지하철", romanization: "jihacheol", meaning_en: "subway", example_kr: "지하철을 타고 가요.", example_en: "I go by subway." },
  { level: "A2", korean: "버스", romanization: "beoseu", meaning_en: "bus", example_kr: "버스가 늦게 왔어요.", example_en: "The bus came late." },
  { level: "A2", korean: "우산", romanization: "usan", meaning_en: "umbrella", example_kr: "비가 와서 우산을 썼어요.", example_en: "It rained so I used an umbrella." },
  { level: "A2", korean: "병원", romanization: "byeongwon", meaning_en: "hospital", example_kr: "병원에 가야 해요.", example_en: "I have to go to the hospital." },
  { level: "A2", korean: "약국", romanization: "yakguk", meaning_en: "pharmacy", example_kr: "약국에서 약을 샀어요.", example_en: "I bought medicine at the pharmacy." },
  { level: "A2", korean: "은행", romanization: "eunhaeng", meaning_en: "bank", example_kr: "은행에서 돈을 찾았어요.", example_en: "I withdrew money at the bank." },
  { level: "A2", korean: "서점", romanization: "seojeom", meaning_en: "bookstore", example_kr: "서점에서 책을 샀어요.", example_en: "I bought a book at the bookstore." },
  { level: "A2", korean: "식당", romanization: "sikdang", meaning_en: "restaurant", example_kr: "이 식당은 정말 맛있어요.", example_en: "This restaurant is really delicious." },
  { level: "A2", korean: "카페", romanization: "kape", meaning_en: "cafe", example_kr: "카페에서 커피를 마셔요.", example_en: "I drink coffee at a cafe." },
  { level: "A2", korean: "주말", romanization: "jumal", meaning_en: "weekend", example_kr: "주말에 뭐 해요?", example_en: "What do you do on weekends?" },
  { level: "A2", korean: "취미", romanization: "chwimi", meaning_en: "hobby", example_kr: "제 취미는 그림 그리기예요.", example_en: "My hobby is drawing." },

  // B1
  { level: "B1", korean: "습관", romanization: "seupgwan", meaning_en: "habit", example_kr: "좋은 습관을 만드는 게 중요해요.", example_en: "It's important to build good habits." },
  { level: "B1", korean: "경험", romanization: "gyeongheom", meaning_en: "experience", example_kr: "좋은 경험이었어요.", example_en: "It was a good experience." },
  { level: "B1", korean: "기회", romanization: "gihoe", meaning_en: "opportunity", example_kr: "좋은 기회를 놓쳤어요.", example_en: "I missed a good opportunity." },
  { level: "B1", korean: "상황", romanization: "sanghwang", meaning_en: "situation", example_kr: "지금 상황이 복잡해요.", example_en: "The situation is complicated right now." },
  { level: "B1", korean: "이유", romanization: "iyu", meaning_en: "reason", example_kr: "늦은 이유를 말해 주세요.", example_en: "Please tell me the reason you're late." },
  { level: "B1", korean: "방법", romanization: "bangbeop", meaning_en: "method", example_kr: "더 좋은 방법이 있을까요?", example_en: "Is there a better method?" },
  { level: "B1", korean: "관계", romanization: "gwan-gye", meaning_en: "relationship", example_kr: "두 사람의 관계가 좋아졌어요.", example_en: "The relationship between the two got better." },
  { level: "B1", korean: "성격", romanization: "seonggyeok", meaning_en: "personality", example_kr: "그는 성격이 좋아요.", example_en: "He has a good personality." },
  { level: "B1", korean: "감정", romanization: "gamjeong", meaning_en: "emotion", example_kr: "감정을 표현하는 게 어려워요.", example_en: "It's hard to express emotions.", root: "gam" },
  { level: "B1", korean: "스트레스", romanization: "seuteureseu", meaning_en: "stress", example_kr: "요즘 스트레스가 많아요.", example_en: "I have a lot of stress these days." },
  { level: "B1", korean: "여유", romanization: "yeoyu", meaning_en: "leisure / composure", example_kr: "요즘 마음의 여유가 없어요.", example_en: "I don't have peace of mind these days." },
  { level: "B1", korean: "걱정", romanization: "geokjeong", meaning_en: "worry", example_kr: "너무 걱정하지 마세요.", example_en: "Don't worry too much." },
  { level: "B1", korean: "자신감", romanization: "jasin-gam", meaning_en: "confidence", example_kr: "자신감을 가지세요.", example_en: "Have confidence." },
  { level: "B1", korean: "부담", romanization: "budam", meaning_en: "burden", example_kr: "너무 부담 갖지 마세요.", example_en: "Don't feel too burdened." },
  { level: "B1", korean: "결정", romanization: "gyeoljeong", meaning_en: "decision", example_kr: "중요한 결정을 내렸어요.", example_en: "I made an important decision." },
  { level: "B1", korean: "목표", romanization: "mokpyo", meaning_en: "goal", example_kr: "제 목표는 한국어를 잘하는 거예요.", example_en: "My goal is to be good at Korean." },
  { level: "B1", korean: "실수", romanization: "silsu", meaning_en: "mistake", example_kr: "누구나 실수를 해요.", example_en: "Everyone makes mistakes." },

  // B2
  { level: "B2", korean: "대인관계", romanization: "daein-gwan-gye", meaning_en: "interpersonal relationships", example_kr: "대인관계가 힘들 때가 있어요.", example_en: "There are times interpersonal relationships are hard." },
  { level: "B2", korean: "배려", romanization: "baeryeo", meaning_en: "consideration for others", example_kr: "서로 배려하는 게 중요해요.", example_en: "It's important to be considerate of each other." },
  { level: "B2", korean: "편견", romanization: "pyeon-gyeon", meaning_en: "prejudice", example_kr: "편견 없이 사람을 대해요.", example_en: "I treat people without prejudice.", root: "pyeon" },
  { level: "B2", korean: "갈등", romanization: "galdeung", meaning_en: "conflict", example_kr: "두 사람 사이에 갈등이 생겼어요.", example_en: "Conflict arose between the two people." },
  { level: "B2", korean: "타협", romanization: "tahyeop", meaning_en: "compromise", example_kr: "서로 타협을 했어요.", example_en: "We compromised with each other." },
  { level: "B2", korean: "신뢰", romanization: "silloe", meaning_en: "trust", example_kr: "신뢰를 쌓는 데 시간이 걸려요.", example_en: "Building trust takes time." },
  { level: "B2", korean: "책임감", romanization: "chaegim-gam", meaning_en: "sense of responsibility", example_kr: "그는 책임감이 강해요.", example_en: "He has a strong sense of responsibility.", root: "gam" },
  { level: "B2", korean: "자율성", romanization: "jayulseong", meaning_en: "autonomy", example_kr: "아이의 자율성을 존중해요.", example_en: "I respect the child's autonomy." },
  { level: "B2", korean: "효율성", romanization: "hyoyulseong", meaning_en: "efficiency", example_kr: "업무 효율성이 높아졌어요.", example_en: "Work efficiency has improved." },
  { level: "B2", korean: "유연성", romanization: "yuyeonseong", meaning_en: "flexibility", example_kr: "생각의 유연성이 필요해요.", example_en: "Flexibility of thought is needed." },
  { level: "B2", korean: "적응", romanization: "jeogeung", meaning_en: "adaptation", example_kr: "새 학교에 적응하고 있어요.", example_en: "I'm adapting to the new school." },
  { level: "B2", korean: "협력", romanization: "hyeomnyeok", meaning_en: "cooperation", example_kr: "두 회사가 협력하기로 했어요.", example_en: "The two companies decided to cooperate." },
  { level: "B2", korean: "소통", romanization: "sotong", meaning_en: "communication", example_kr: "소통이 잘 안 돼요.", example_en: "Communication isn't going well." },
  { level: "B2", korean: "공감", romanization: "gonggam", meaning_en: "empathy", example_kr: "그 말에 깊이 공감해요.", example_en: "I deeply empathize with that." },
  { level: "B2", korean: "성찰", romanization: "seongchal", meaning_en: "self-reflection", example_kr: "자기 성찰의 시간을 가져요.", example_en: "I take time for self-reflection." },
  { level: "B2", korean: "균형", romanization: "gyunhyeong", meaning_en: "balance", example_kr: "일과 삶의 균형이 중요해요.", example_en: "Work-life balance is important." },
  { level: "B2", korean: "우선순위", romanization: "useon-sunwi", meaning_en: "priority", example_kr: "우선순위를 정해야 해요.", example_en: "You need to set priorities." },

  // C1
  { level: "C1", korean: "통찰력", romanization: "tongchallyeok", meaning_en: "insight", example_kr: "그는 통찰력이 뛰어나요.", example_en: "He has excellent insight.", root: "ryeok" },
  { level: "C1", korean: "역설", romanization: "yeokseol", meaning_en: "paradox", example_kr: "이건 일종의 역설이에요.", example_en: "This is a kind of paradox." },
  { level: "C1", korean: "모순", romanization: "mosun", meaning_en: "contradiction", example_kr: "그의 말은 모순이 있어요.", example_en: "His words contain a contradiction." },
  { level: "C1", korean: "편향", romanization: "pyeonhyang", meaning_en: "bias", example_kr: "언론의 편향을 경계해야 해요.", example_en: "We should be wary of media bias.", root: "pyeon" },
  { level: "C1", korean: "타당성", romanization: "tadangseong", meaning_en: "validity", example_kr: "그 주장은 타당성이 부족해요.", example_en: "That argument lacks validity." },
  { level: "C1", korean: "객관성", romanization: "gaekgwanseong", meaning_en: "objectivity", example_kr: "기사는 객관성을 유지해야 해요.", example_en: "Articles should maintain objectivity." },
  { level: "C1", korean: "주관성", romanization: "jugwanseong", meaning_en: "subjectivity", example_kr: "이 평가는 주관성이 강해요.", example_en: "This evaluation is highly subjective." },
  { level: "C1", korean: "함의", romanization: "hamui", meaning_en: "implication", example_kr: "그 발언은 깊은 함의를 담고 있어요.", example_en: "That remark carries a deep implication." },
  { level: "C1", korean: "논란", romanization: "nollan", meaning_en: "controversy", example_kr: "그 정책은 논란이 되고 있어요.", example_en: "That policy is becoming controversial." },
  { level: "C1", korean: "쟁점", romanization: "jaengjeom", meaning_en: "point of contention", example_kr: "오늘 회의의 쟁점은 예산이에요.", example_en: "Today's meeting point of contention is the budget." },
  { level: "C1", korean: "담론", romanization: "damnon", meaning_en: "discourse", example_kr: "사회적 담론이 활발해요.", example_en: "Social discourse is active." },
  { level: "C1", korean: "여론", romanization: "yeoron", meaning_en: "public opinion", example_kr: "여론이 나빠지고 있어요.", example_en: "Public opinion is worsening." },
  { level: "C1", korean: "통념", romanization: "tongnyeom", meaning_en: "conventional wisdom", example_kr: "그건 잘못된 통념이에요.", example_en: "That's a mistaken conventional wisdom." },
  { level: "C1", korean: "고정관념", romanization: "gojeong-gwannyeom", meaning_en: "stereotype", example_kr: "고정관념을 깨야 해요.", example_en: "We need to break stereotypes." },
  { level: "C1", korean: "편협함", romanization: "pyeonhyeopham", meaning_en: "narrow-mindedness", example_kr: "그의 편협함이 문제예요.", example_en: "His narrow-mindedness is the problem." },
  { level: "C1", korean: "포용력", romanization: "poyongnyeok", meaning_en: "inclusiveness", example_kr: "그녀는 포용력이 넓어요.", example_en: "She has broad inclusiveness." },
  { level: "C1", korean: "함축", romanization: "hamchuk", meaning_en: "connotation", example_kr: "이 시는 많은 함축을 담고 있어요.", example_en: "This poem carries many connotations." },

  // C2
  { level: "C2", korean: "미봉책", romanization: "mibongchaek", meaning_en: "stopgap measure", example_kr: "이건 임시 미봉책일 뿐이에요.", example_en: "This is just a temporary stopgap measure." },
  { level: "C2", korean: "일사천리", romanization: "ilsacheolli", meaning_en: "smooth and swift progress", example_kr: "일이 일사천리로 진행됐어요.", example_en: "Things proceeded smoothly and swiftly." },
  { level: "C2", korean: "진퇴양난", romanization: "jintwoeyangnan", meaning_en: "dilemma", example_kr: "저는 진퇴양난에 빠졌어요.", example_en: "I'm caught in a dilemma." },
  { level: "C2", korean: "유비무환", romanization: "yubimuhwan", meaning_en: "being prepared avoids trouble", example_kr: "유비무환이라고 미리 준비했어요.", example_en: "As they say, \"prepare in advance,\" so I got ready early." },
  { level: "C2", korean: "새옹지마", romanization: "saeongjima", meaning_en: "blessing in disguise", example_kr: "인생은 새옹지마예요.", example_en: "Life is like a blessing in disguise." },
  { level: "C2", korean: "자업자득", romanization: "jaeopjadeuk", meaning_en: "reaping what you sow", example_kr: "그건 자업자득이에요.", example_en: "That's your own doing." },
  { level: "C2", korean: "이심전심", romanization: "isimjeonsim", meaning_en: "mutual understanding without words", example_kr: "우리는 이심전심으로 통했어요.", example_en: "We understood each other without words." },
  { level: "C2", korean: "온고지신", romanization: "ongojisin", meaning_en: "learning from the past", example_kr: "온고지신의 자세가 필요해요.", example_en: "We need the attitude of learning from the past." },
  { level: "C2", korean: "우여곡절", romanization: "uyeogokjeol", meaning_en: "twists and turns", example_kr: "우여곡절 끝에 성공했어요.", example_en: "After many twists and turns, I succeeded." },
  { level: "C2", korean: "학수고대", romanization: "haksugodae", meaning_en: "eagerly awaiting", example_kr: "그 소식을 학수고대하고 있어요.", example_en: "I'm eagerly awaiting that news." },
  { level: "C2", korean: "절체절명", romanization: "jeolchejeolmyeong", meaning_en: "critical, desperate situation", example_kr: "절체절명의 순간이었어요.", example_en: "It was a critical, desperate moment." },
  { level: "C2", korean: "고육지책", romanization: "goyukjichaek", meaning_en: "painful compromise measure", example_kr: "그건 고육지책이었어요.", example_en: "That was a painful compromise measure." },
  { level: "C2", korean: "시행착오", romanization: "sihaengchak-o", meaning_en: "trial and error", example_kr: "시행착오를 거쳐 배웠어요.", example_en: "I learned through trial and error." },
  { level: "C2", korean: "안목", romanization: "anmok", meaning_en: "discerning eye", example_kr: "그는 안목이 뛰어나요.", example_en: "He has an excellent eye." },
  { level: "C2", korean: "저력", romanization: "jeoryeok", meaning_en: "latent strength", example_kr: "이 팀은 저력이 있어요.", example_en: "This team has latent strength." },
  { level: "C2", korean: "통섭", romanization: "tongseop", meaning_en: "consilience", example_kr: "학문 간 통섭이 중요해요.", example_en: "Consilience between disciplines is important." },
  { level: "C2", korean: "백문불여일견", romanization: "baengmunburyeoilgyeon", meaning_en: "seeing is believing", example_kr: "백문불여일견이니 직접 가 보세요.", example_en: "Seeing is believing, so go see it yourself." },
];
