import type { RawPrompt } from "./types";

export const WRITING_A1_JOURNAL: RawPrompt[] = [
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 아침에 무엇을 먹었어요?",
    prompt_en: "What did you eat this morning?",
    prompt_ja: "今朝何を食べましたか？",
    example_kr: "저는 빵을 먹었어요.",
    example_en: "I ate bread.",
    example_ja: "私はパンを食べました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 날씨가 어땠어요?",
    prompt_en: "How was the weather yesterday?",
    prompt_ja: "昨日の天気はどうでしたか？",
    example_kr: "어제 비가 왔어요.",
    example_en: "It rained yesterday.",
    example_ja: "昨日雨が降りました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 기분이 어때요?",
    prompt_en: "How do you feel right now?",
    prompt_ja: "今の気分はどうですか？",
    example_kr: "저는 아주 기뻐요.",
    example_en: "I am very happy.",
    example_ja: "私はとてもうれしいです。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 무슨 운동을 해요?",
    prompt_en: "What exercise do you do today?",
    prompt_ja: "今日どんな運動をしますか？",
    example_kr: "저는 매일 걸어요.",
    example_en: "I walk every day.",
    example_ja: "私は毎日歩きます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 밤에 몇 시에 잤어요?",
    prompt_en: "What time did you sleep last night?",
    prompt_ja: "昨日の夜、何時に寝ましたか？",
    example_kr: "저는 일찍 잤어요.",
    example_en: "I slept early.",
    example_ja: "私は早く寝ました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 커피를 마셨어요?",
    prompt_en: "Did you drink coffee today?",
    prompt_ja: "今日コーヒーを飲みましたか？",
    example_kr: "저는 커피를 마셔요.",
    example_en: "I drink coffee.",
    example_ja: "私はコーヒーを飲みます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "주말에 무엇을 해요?",
    prompt_en: "What do you do on the weekend?",
    prompt_ja: "週末に何をしますか？",
    example_kr: "저는 집에서 쉬어요.",
    example_en: "I rest at home.",
    example_ja: "私は家で休みます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 음악을 들어요?",
    prompt_en: "What kind of music do you listen to today?",
    prompt_ja: "今日どんな音楽を聞きますか？",
    example_kr: "저는 팝송을 들어요.",
    example_en: "I listen to pop songs.",
    example_ja: "私はポップソングを聞きます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 친구를 만났어요?",
    prompt_en: "Did you meet a friend yesterday?",
    prompt_ja: "昨日友達に会いましたか？",
    example_kr: "저는 친구를 만났어요.",
    example_en: "I met a friend.",
    example_ja: "私は友達に会いました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 점심은 무엇을 먹어요?",
    prompt_en: "What are you eating for lunch today?",
    prompt_ja: "今日の昼ごはんは何を食べますか？",
    example_kr: "저는 라면을 먹어요.",
    example_en: "I eat ramen.",
    example_ja: "私はラーメンを食べます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 어디에 있어요?",
    prompt_en: "Where are you now?",
    prompt_ja: "今どこにいますか？",
    example_kr: "저는 카페에 있어요.",
    example_en: "I am at a cafe.",
    example_ja: "私はカフェにいます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 책을 읽었어요?",
    prompt_en: "Did you read a book yesterday?",
    prompt_ja: "昨日本を読みましたか？",
    example_kr: "저는 책을 읽었어요.",
    example_en: "I read a book.",
    example_ja: "私は本を読みました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 무슨 영화를 봐요?",
    prompt_en: "What movie are you watching today?",
    prompt_ja: "今日どんな映画を見ますか？",
    example_kr: "저는 코미디를 봐요.",
    example_en: "I watch comedy.",
    example_ja: "私はコメディを見ます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "가장 좋아하는 색은 무엇이에요?",
    prompt_en: "What is your favorite color?",
    prompt_ja: "一番好きな色は何ですか？",
    example_kr: "저는 파란색 좋아해요.",
    example_en: "I like blue.",
    example_ja: "私は青色が好きです。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 과일을 먹었어요?",
    prompt_en: "Did you eat fruit today?",
    prompt_ja: "今日果物を食べましたか？",
    example_kr: "저는 사과를 먹어요.",
    example_en: "I eat apples.",
    example_ja: "私はりんごを食べます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 쇼핑을 했어요?",
    prompt_en: "Did you go shopping yesterday?",
    prompt_ja: "昨日買い物をしましたか？",
    example_kr: "저는 옷을 샀어요.",
    example_en: "I bought clothes.",
    example_ja: "私は服を買いました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 공부하는 과목이 무엇이에요?",
    prompt_en: "What subject are you studying now?",
    prompt_ja: "今勉強している科目は何ですか？",
    example_kr: "저는 한국어를 배워요.",
    example_en: "I learn Korean.",
    example_ja: "私は韓国語を習います。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 동물을 보았어요?",
    prompt_en: "What kind of animal did you see today?",
    prompt_ja: "今日どんな動物を見ましたか？",
    example_kr: "저는 강아지 봤어요.",
    example_en: "I saw a puppy.",
    example_ja: "私は子犬を見ました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지난주에 여행을 갔어요?",
    prompt_en: "Did you go on a trip last week?",
    prompt_ja: "先週旅行に行きましたか？",
    example_kr: "저는 제주도 갔어요.",
    example_en: "I went to Jeju island.",
    example_ja: "私はチェジュ島に行きました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 차를 마셔요?",
    prompt_en: "What kind of tea do you drink today?",
    prompt_ja: "今日どんなお茶を飲みますか？",
    example_kr: "저는 녹차 마셔요.",
    example_en: "I drink green tea.",
    example_ja: "私は緑茶を飲みます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 사진을 찍었어요?",
    prompt_en: "Did you take a picture yesterday?",
    prompt_ja: "昨日写真を撮りましたか？",
    example_kr: "저는 풍경 찍었어요.",
    example_en: "I took a scenery picture.",
    example_ja: "私は風景を撮りました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 몇 시에 일어났어요?",
    prompt_en: "What time did you wake up today?",
    prompt_ja: "今日何時に起きましたか？",
    example_kr: "저는 일곱시 일어났어요.",
    example_en: "I woke up at seven.",
    example_ja: "私は七時に起きました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 방이 깨끗해요?",
    prompt_en: "Is your room clean now?",
    prompt_ja: "今部屋はきれいですか？",
    example_kr: "제 방이 깨끗해요.",
    example_en: "My room is clean.",
    example_ja: "私の部屋はきれいです。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 편지를 썼어요?",
    prompt_en: "Did you write a letter yesterday?",
    prompt_ja: "昨日手紙を書きましたか？",
    example_kr: "저는 편지 썼어요.",
    example_en: "I wrote a letter.",
    example_ja: "私は手紙を書きました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 음식을 좋아해요?",
    prompt_en: "What kind of food do you like today?",
    prompt_ja: "今日どんな食べ物が好きですか？",
    example_kr: "저는 한식 좋아해요.",
    example_en: "I like Korean food.",
    example_ja: "私は韓国料理が好きです。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 무슨 생각을 해요?",
    prompt_en: "What are you thinking about now?",
    prompt_ja: "今何を考えていますか？",
    example_kr: "저는 저녁 생각해요.",
    example_en: "I think about dinner.",
    example_ja: "私は夕食のことを考えています。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 선물을 받았어요?",
    prompt_en: "Did you receive a gift yesterday?",
    prompt_ja: "昨日プレゼントをもらいましたか？",
    example_kr: "저는 꽃을 받았어요.",
    example_en: "I received flowers.",
    example_ja: "私は花をもらいました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 계절을 좋아해요?",
    prompt_en: "Which season do you like today?",
    prompt_ja: "今日どんな季節が好きですか？",
    example_kr: "저는 봄을 좋아해요.",
    example_en: "I like spring.",
    example_ja: "私は春が好きです。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 노래를 불렀어요?",
    prompt_en: "Did you sing a song yesterday?",
    prompt_ja: "昨日歌を歌いましたか？",
    example_kr: "저는 노래 불렀어요.",
    example_en: "I sang a song.",
    example_ja: "私は歌を歌いました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 꽃을 좋아해요?",
    prompt_en: "What kind of flowers do you like today?",
    prompt_ja: "今日どんな花が好きですか？",
    example_kr: "저는 장미 좋아해요.",
    example_en: "I like roses.",
    example_ja: "私はバラが好きです。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 가방에 무엇이 있어요?",
    prompt_en: "What is in your bag now?",
    prompt_ja: "今かばんに何がありますか？",
    example_kr: "가방에 지갑 있어요.",
    example_en: "There is a wallet inside.",
    example_ja: "かばんに財布があります。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 요리를 했어요?",
    prompt_en: "Did you cook yesterday?",
    prompt_ja: "昨日料理をしましたか？",
    example_kr: "저는 카레 만들었어요.",
    example_en: "I made curry.",
    example_ja: "私はカレーを作りました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 무슨 게임을 해요?",
    prompt_en: "What game do you play today?",
    prompt_ja: "今日どんなゲームをしますか？",
    example_kr: "저는 체스 해요.",
    example_en: "I play chess.",
    example_ja: "私はチェスをします。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 컴퓨터를 썼어요?",
    prompt_en: "Did you use a computer yesterday?",
    prompt_ja: "昨日パソコンを使いましたか？",
    example_kr: "저는 노트북 썼어요.",
    example_en: "I used a laptop.",
    example_ja: "私はノートパソコンを使いました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 신발을 신어요?",
    prompt_en: "What shoes do you wear today?",
    prompt_ja: "今日どんな靴を履きますか？",
    example_kr: "저는 운동화 신어요.",
    example_en: "I wear sneakers.",
    example_ja: "私はスニーカーを履きます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 약속이 있었어요?",
    prompt_en: "Did you have an appointment yesterday?",
    prompt_ja: "昨日約束がありましたか？",
    example_kr: "저는 약속 있었어요.",
    example_en: "I had an appointment.",
    example_ja: "私は約束がありました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 과자를 먹어요?",
    prompt_en: "What snack do you eat today?",
    prompt_ja: "今日どんなお菓子を食べますか？",
    example_kr: "저는 쿠키 먹어요.",
    example_en: "I eat cookies.",
    example_ja: "私はクッキーを食べます。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 늦게 잤어요?",
    prompt_en: "Did you sleep late yesterday?",
    prompt_ja: "昨日遅く寝ましたか？",
    example_kr: "저는 늦게 잤어요.",
    example_en: "I slept late.",
    example_ja: "私は遅く寝ました。",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 음료를 마셔요?",
    prompt_en: "What drink do you have today?",
    prompt_ja: "今日どんな飲み物を飲みますか？",
    example_kr: "저는 주스 마셔요.",
    example_en: "I drink juice.",
    example_ja: "私はジュースを飲みます。",
  },
];
