import type { RawPrompt } from "./types";

export const WRITING_A1_JOURNAL: RawPrompt[] = [
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 아침에 무엇을 먹었어요?",
    prompt_en: "What did you eat this morning?",
    example_kr: "저는 빵을 먹었어요.",
    example_en: "I ate bread.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 날씨가 어땠어요?",
    prompt_en: "How was the weather yesterday?",
    example_kr: "어제 비가 왔어요.",
    example_en: "It rained yesterday.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 기분이 어때요?",
    prompt_en: "How do you feel right now?",
    example_kr: "저는 아주 기뻐요.",
    example_en: "I am very happy.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 무슨 운동을 해요?",
    prompt_en: "What exercise do you do today?",
    example_kr: "저는 매일 걸어요.",
    example_en: "I walk every day.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 밤에 몇 시에 잤어요?",
    prompt_en: "What time did you sleep last night?",
    example_kr: "저는 일찍 잤어요.",
    example_en: "I slept early.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 커피를 마셨어요?",
    prompt_en: "Did you drink coffee today?",
    example_kr: "저는 커피를 마셔요.",
    example_en: "I drink coffee.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "주말에 무엇을 해요?",
    prompt_en: "What do you do on the weekend?",
    example_kr: "저는 집에서 쉬어요.",
    example_en: "I rest at home.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 음악을 들어요?",
    prompt_en: "What kind of music do you listen to today?",
    example_kr: "저는 팝송을 들어요.",
    example_en: "I listen to pop songs.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 친구를 만났어요?",
    prompt_en: "Did you meet a friend yesterday?",
    example_kr: "저는 친구를 만났어요.",
    example_en: "I met a friend.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 점심은 무엇을 먹어요?",
    prompt_en: "What are you eating for lunch today?",
    example_kr: "저는 라면을 먹어요.",
    example_en: "I eat ramen.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 어디에 있어요?",
    prompt_en: "Where are you now?",
    example_kr: "저는 카페에 있어요.",
    example_en: "I am at a cafe.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 책을 읽었어요?",
    prompt_en: "Did you read a book yesterday?",
    example_kr: "저는 책을 읽었어요.",
    example_en: "I read a book.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 무슨 영화를 봐요?",
    prompt_en: "What movie are you watching today?",
    example_kr: "저는 코미디를 봐요.",
    example_en: "I watch comedy.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "가장 좋아하는 색은 무엇이에요?",
    prompt_en: "What is your favorite color?",
    example_kr: "저는 파란색 좋아해요.",
    example_en: "I like blue.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 과일을 먹었어요?",
    prompt_en: "Did you eat fruit today?",
    example_kr: "저는 사과를 먹어요.",
    example_en: "I eat apples.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 쇼핑을 했어요?",
    prompt_en: "Did you go shopping yesterday?",
    example_kr: "저는 옷을 샀어요.",
    example_en: "I bought clothes.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 공부하는 과목이 무엇이에요?",
    prompt_en: "What subject are you studying now?",
    example_kr: "저는 한국어를 배워요.",
    example_en: "I learn Korean.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 동물을 보았어요?",
    prompt_en: "What kind of animal did you see today?",
    example_kr: "저는 강아지 봤어요.",
    example_en: "I saw a puppy.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지난주에 여행을 갔어요?",
    prompt_en: "Did you go on a trip last week?",
    example_kr: "저는 제주도 갔어요.",
    example_en: "I went to Jeju island.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 차를 마셔요?",
    prompt_en: "What kind of tea do you drink today?",
    example_kr: "저는 녹차 마셔요.",
    example_en: "I drink green tea.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 사진을 찍었어요?",
    prompt_en: "Did you take a picture yesterday?",
    example_kr: "저는 풍경 찍었어요.",
    example_en: "I took a scenery picture.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 몇 시에 일어났어요?",
    prompt_en: "What time did you wake up today?",
    example_kr: "저는 일곱시 일어났어요.",
    example_en: "I woke up at seven.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 방이 깨끗해요?",
    prompt_en: "Is your room clean now?",
    example_kr: "제 방이 깨끗해요.",
    example_en: "My room is clean.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 편지를 썼어요?",
    prompt_en: "Did you write a letter yesterday?",
    example_kr: "저는 편지 썼어요.",
    example_en: "I wrote a letter.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 음식을 좋아해요?",
    prompt_en: "What kind of food do you like today?",
    example_kr: "저는 한식 좋아해요.",
    example_en: "I like Korean food.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 무슨 생각을 해요?",
    prompt_en: "What are you thinking about now?",
    example_kr: "저는 저녁 생각해요.",
    example_en: "I think about dinner.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 선물을 받았어요?",
    prompt_en: "Did you receive a gift yesterday?",
    example_kr: "저는 꽃을 받았어요.",
    example_en: "I received flowers.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 계절을 좋아해요?",
    prompt_en: "Which season do you like today?",
    example_kr: "저는 봄을 좋아해요.",
    example_en: "I like spring.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 노래를 불렀어요?",
    prompt_en: "Did you sing a song yesterday?",
    example_kr: "저는 노래 불렀어요.",
    example_en: "I sang a song.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 꽃을 좋아해요?",
    prompt_en: "What kind of flowers do you like today?",
    example_kr: "저는 장미 좋아해요.",
    example_en: "I like roses.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "지금 가방에 무엇이 있어요?",
    prompt_en: "What is in your bag now?",
    example_kr: "가방에 지갑 있어요.",
    example_en: "There is a wallet inside.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 요리를 했어요?",
    prompt_en: "Did you cook yesterday?",
    example_kr: "저는 카레 만들었어요.",
    example_en: "I made curry.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 무슨 게임을 해요?",
    prompt_en: "What game do you play today?",
    example_kr: "저는 체스 해요.",
    example_en: "I play chess.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 컴퓨터를 썼어요?",
    prompt_en: "Did you use a computer yesterday?",
    example_kr: "저는 노트북 썼어요.",
    example_en: "I used a laptop.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 신발을 신어요?",
    prompt_en: "What shoes do you wear today?",
    example_kr: "저는 운동화 신어요.",
    example_en: "I wear sneakers.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 약속이 있었어요?",
    prompt_en: "Did you have an appointment yesterday?",
    example_kr: "저는 약속 있었어요.",
    example_en: "I had an appointment.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 과자를 먹어요?",
    prompt_en: "What snack do you eat today?",
    example_kr: "저는 쿠키 먹어요.",
    example_en: "I eat cookies.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "어제 늦게 잤어요?",
    prompt_en: "Did you sleep late yesterday?",
    example_kr: "저는 늦게 잤어요.",
    example_en: "I slept late.",
  },
  {
    level: "A1",
    genre: "journal",
    prompt_kr: "오늘 어떤 음료를 마셔요?",
    prompt_en: "What drink do you have today?",
    example_kr: "저는 주스 마셔요.",
    example_en: "I drink juice.",
  },
];
