import type { RawPrompt } from "./types";

export const WRITING_A1_OPINION: RawPrompt[] = [
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 음식을 좋아해요?",
    prompt_en: "What food do you like?",
    prompt_ja: "どんな食べ物が好きですか？",
    prompt_zh: "你喜欢什么食物？",
    example_kr: "저는 밥을 좋아해요.",
    example_en: "I like rice.",
    example_ja: "私はご飯が好きです。",
    example_zh: "我喜欢米饭。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 과일을 좋아해요?",
    prompt_en: "What fruit do you like?",
    prompt_ja: "どんな果物が好きですか？",
    prompt_zh: "你喜欢什么水果？",
    example_kr: "저는 사과를 좋아해요.",
    example_en: "I like apples.",
    example_ja: "私はりんごが好きです。",
    example_zh: "我喜欢苹果。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 음료를 좋아해요?",
    prompt_en: "What beverage do you like?",
    prompt_ja: "どんな飲み物が好きですか？",
    prompt_zh: "你喜欢什么饮料？",
    example_kr: "저는 물을 마셔요.",
    example_en: "I drink water.",
    example_ja: "私は水を飲みます。",
    example_zh: "我喝水。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 계절을 좋아해요?",
    prompt_en: "What season do you like?",
    prompt_ja: "どんな季節が好きですか？",
    prompt_zh: "你喜欢哪个季节？",
    example_kr: "저는 봄을 좋아해요.",
    example_en: "I like spring.",
    example_ja: "私は春が好きです。",
    example_zh: "我喜欢春天。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 날씨를 좋아해요?",
    prompt_en: "What weather do you like?",
    prompt_ja: "どんな天気が好きですか？",
    prompt_zh: "你喜欢什么天气？",
    example_kr: "저는 비를 좋아해요.",
    example_en: "I like rain.",
    example_ja: "私は雨が好きです。",
    example_zh: "我喜欢下雨天。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 색을 좋아해요?",
    prompt_en: "What color do you like?",
    prompt_ja: "どんな色が好きですか？",
    prompt_zh: "你喜欢什么颜色？",
    example_kr: "저는 파란색을 좋아해요.",
    example_en: "I like blue.",
    example_ja: "私は青色が好きです。",
    example_zh: "我喜欢蓝色。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 동물을 좋아해요?",
    prompt_en: "What animal do you like?",
    prompt_ja: "どんな動物が好きですか？",
    prompt_zh: "你喜欢什么动物？",
    example_kr: "저는 고양이를 좋아해요.",
    example_en: "I like cats.",
    example_ja: "私は猫が好きです。",
    example_zh: "我喜欢猫。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 운동을 좋아해요?",
    prompt_en: "What exercise do you like?",
    prompt_ja: "どんな運動が好きですか？",
    prompt_zh: "你喜欢什么运动？",
    example_kr: "저는 축구를 좋아해요.",
    example_en: "I like soccer.",
    example_ja: "私はサッカーが好きです。",
    example_zh: "我喜欢足球。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 음악을 좋아해요?",
    prompt_en: "What music do you like?",
    prompt_ja: "どんな音楽が好きですか？",
    prompt_zh: "你喜欢什么音乐？",
    example_kr: "저는 팝송을 좋아해요.",
    example_en: "I like pop songs.",
    example_ja: "私はポップソングが好きです。",
    example_zh: "我喜欢流行歌曲。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 영화를 좋아해요?",
    prompt_en: "What movie do you like?",
    prompt_ja: "どんな映画が好きですか？",
    prompt_zh: "你喜欢什么电影？",
    example_kr: "저는 코미디를 좋아해요.",
    example_en: "I like comedies.",
    example_ja: "私はコメディが好きです。",
    example_zh: "我喜欢喜剧片。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 책을 좋아해요?",
    prompt_en: "What book do you like?",
    prompt_ja: "どんな本が好きですか？",
    prompt_zh: "你喜欢什么书？",
    example_kr: "저는 소설을 좋아해요.",
    example_en: "I like novels.",
    example_ja: "私は小説が好きです。",
    example_zh: "我喜欢小说。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 꽃을 좋아해요?",
    prompt_en: "What flower do you like?",
    prompt_ja: "どんな花が好きですか？",
    prompt_zh: "你喜欢什么花？",
    example_kr: "저는 장미를 좋아해요.",
    example_en: "I like roses.",
    example_ja: "私はバラが好きです。",
    example_zh: "我喜欢玫瑰。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 커피를 좋아해요?",
    prompt_en: "What coffee do you like?",
    prompt_ja: "どんなコーヒーが好きですか？",
    prompt_zh: "你喜欢什么咖啡？",
    example_kr: "저는 라떼를 좋아해요.",
    example_en: "I like lattes.",
    example_ja: "私はラテが好きです。",
    example_zh: "我喜欢拿铁。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 차를 좋아해요?",
    prompt_en: "What tea do you like?",
    prompt_ja: "どんなお茶が好きですか？",
    prompt_zh: "你喜欢什么茶？",
    example_kr: "저는 녹차를 좋아해요.",
    example_en: "I like green tea.",
    example_ja: "私は緑茶が好きです。",
    example_zh: "我喜欢绿茶。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 빵을 좋아해요?",
    prompt_en: "What bread do you like?",
    prompt_ja: "どんなパンが好きですか？",
    prompt_zh: "你喜欢什么面包？",
    example_kr: "저는 식빵을 좋아해요.",
    example_en: "I like white bread.",
    example_ja: "私は食パンが好きです。",
    example_zh: "我喜欢吐司。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 면 요리를 좋아해요?",
    prompt_en: "What noodle dish do you like?",
    prompt_ja: "どんな麺料理が好きですか？",
    prompt_zh: "你喜欢什么面食？",
    example_kr: "저는 라면을 좋아해요.",
    example_en: "I like ramen.",
    example_ja: "私はラーメンが好きです。",
    example_zh: "我喜欢拉面。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 고기를 좋아해요?",
    prompt_en: "What meat do you like?",
    prompt_ja: "どんな肉が好きですか？",
    prompt_zh: "你喜欢什么肉？",
    example_kr: "저는 소고기를 좋아해요.",
    example_en: "I like beef.",
    example_ja: "私は牛肉が好きです。",
    example_zh: "我喜欢牛肉。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 야채를 좋아해요?",
    prompt_en: "What vegetable do you like?",
    prompt_ja: "どんな野菜が好きですか？",
    prompt_zh: "你喜欢什么蔬菜？",
    example_kr: "저는 오이를 좋아해요.",
    example_en: "I like cucumbers.",
    example_ja: "私はきゅうりが好きです。",
    example_zh: "我喜欢黄瓜。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 간식을 좋아해요?",
    prompt_en: "What snack do you like?",
    prompt_ja: "どんなおやつが好きですか？",
    prompt_zh: "你喜欢什么零食？",
    example_kr: "저는 과자를 좋아해요.",
    example_en: "I like cookies.",
    example_ja: "私はお菓子が好きです。",
    example_zh: "我喜欢饼干。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 아이스크림을 좋아해요?",
    prompt_en: "What ice cream do you like?",
    prompt_ja: "どんなアイスクリームが好きですか？",
    prompt_zh: "你喜欢什么冰淇淋？",
    example_kr: "저는 바닐라를 좋아해요.",
    example_en: "I like vanilla.",
    example_ja: "私はバニラが好きです。",
    example_zh: "我喜欢香草味。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 요리를 좋아해요?",
    prompt_en: "What cooking do you like?",
    prompt_ja: "どんな料理が好きですか？",
    prompt_zh: "你喜欢什么料理？",
    example_kr: "저는 한식을 좋아해요.",
    example_en: "I like Korean food.",
    example_ja: "私は韓国料理が好きです。",
    example_zh: "我喜欢韩式料理。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 취미를 좋아해요?",
    prompt_en: "What hobby do you like?",
    prompt_ja: "どんな趣味が好きですか？",
    prompt_zh: "你喜欢什么兴趣爱好？",
    example_kr: "저는 독서를 좋아해요.",
    example_en: "I like reading.",
    example_ja: "私は読書が好きです。",
    example_zh: "我喜欢阅读。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 과목을 좋아해요?",
    prompt_en: "What subject do you like?",
    prompt_ja: "どんな科目が好きですか？",
    prompt_zh: "你喜欢什么科目？",
    example_kr: "저는 영어를 좋아해요.",
    example_en: "I like English.",
    example_ja: "私は英語が好きです。",
    example_zh: "我喜欢英语。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 언어를 좋아해요?",
    prompt_en: "What language do you like?",
    prompt_ja: "どんな言語が好きですか？",
    prompt_zh: "你喜欢什么语言？",
    example_kr: "저는 한국어를 좋아해요.",
    example_en: "I like Korean.",
    example_ja: "私は韓国語が好きです。",
    example_zh: "我喜欢韩语。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 가수를 좋아해요?",
    prompt_en: "What singer do you like?",
    prompt_ja: "どんな歌手が好きですか？",
    prompt_zh: "你喜欢哪个歌手？",
    example_kr: "저는 아이유를 좋아해요.",
    example_en: "I like IU.",
    example_ja: "私はIUが好きです。",
    example_zh: "我喜欢IU。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 배우를 좋아해요?",
    prompt_en: "What actor do you like?",
    prompt_ja: "どんな俳優が好きですか？",
    prompt_zh: "你喜欢哪个演员？",
    example_kr: "저는 공유를 좋아해요.",
    example_en: "I like Gong Yoo.",
    example_ja: "私はコン・ユが好きです。",
    example_zh: "我喜欢孔刘。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 장소를 좋아해요?",
    prompt_en: "What place do you like?",
    prompt_ja: "どんな場所が好きですか？",
    prompt_zh: "你喜欢什么地方？",
    example_kr: "저는 공원을 좋아해요.",
    example_en: "I like parks.",
    example_ja: "私は公園が好きです。",
    example_zh: "我喜欢公园。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 방을 좋아해요?",
    prompt_en: "What room do you like?",
    prompt_ja: "どんな部屋が好きですか？",
    prompt_zh: "你喜欢什么样的房间？",
    example_kr: "저는 내 방을 좋아해요.",
    example_en: "I like my room.",
    example_ja: "私は自分の部屋が好きです。",
    example_zh: "我喜欢我的房间。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 나라를 좋아해요?",
    prompt_en: "What country do you like?",
    prompt_ja: "どんな国が好きですか？",
    prompt_zh: "你喜欢哪个国家？",
    example_kr: "저는 한국을 좋아해요.",
    example_en: "I like Korea.",
    example_ja: "私は韓国が好きです。",
    example_zh: "我喜欢韩国。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 도시를 좋아해요?",
    prompt_en: "What city do you like?",
    prompt_ja: "どんな都市が好きですか？",
    prompt_zh: "你喜欢哪个城市？",
    example_kr: "저는 서울을 좋아해요.",
    example_en: "I like Seoul.",
    example_ja: "私はソウルが好きです。",
    example_zh: "我喜欢首尔。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 바다를 좋아해요?",
    prompt_en: "What sea do you like?",
    prompt_ja: "どんな海が好きですか？",
    prompt_zh: "你喜欢哪片海？",
    example_kr: "저는 동해를 좋아해요.",
    example_en: "I like the East Sea.",
    example_ja: "私は東海が好きです。",
    example_zh: "我喜欢东海。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 산을 좋아해요?",
    prompt_en: "What mountain do you like?",
    prompt_ja: "どんな山が好きですか？",
    prompt_zh: "你喜欢哪座山？",
    example_kr: "저는 한라산을 좋아해요.",
    example_en: "I like Hallasan.",
    example_ja: "私はハルラ山が好きです。",
    example_zh: "我喜欢汉拿山。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 하늘을 좋아해요?",
    prompt_en: "What sky do you like?",
    prompt_ja: "どんな空が好きですか？",
    prompt_zh: "你喜欢什么样的天空？",
    example_kr: "저는 맑음을 좋아해요.",
    example_en: "I like clear skies.",
    example_ja: "私は晴れが好きです。",
    example_zh: "我喜欢晴天。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 달을 좋아해요?",
    prompt_en: "What month do you like?",
    prompt_ja: "どんな月が好きですか？",
    prompt_zh: "你喜欢哪个月份？",
    example_kr: "저는 오월을 좋아해요.",
    example_en: "I like May.",
    example_ja: "私は五月が好きです。",
    example_zh: "我喜欢五月。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 요일을 좋아해요?",
    prompt_en: "What day of the week do you like?",
    prompt_ja: "どんな曜日が好きですか？",
    prompt_zh: "你喜欢星期几？",
    example_kr: "저는 금요일을 좋아해요.",
    example_en: "I like Fridays.",
    example_ja: "私は金曜日が好きです。",
    example_zh: "我喜欢星期五。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 시간을 좋아해요?",
    prompt_en: "What time do you like?",
    prompt_ja: "どんな時間が好きですか？",
    prompt_zh: "你喜欢什么时间？",
    example_kr: "저는 저녁을 좋아해요.",
    example_en: "I like evenings.",
    example_ja: "私は夕方が好きです。",
    example_zh: "我喜欢晚上。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 방학을 좋아해요?",
    prompt_en: "What vacation do you like?",
    prompt_ja: "どんな休みが好きですか？",
    prompt_zh: "你喜欢什么假期？",
    example_kr: "저는 여름을 좋아해요.",
    example_en: "I like summers.",
    example_ja: "私は夏が好きです。",
    example_zh: "我喜欢夏天。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 선물을 좋아해요?",
    prompt_en: "What gift do you like?",
    prompt_ja: "どんなプレゼントが好きですか？",
    prompt_zh: "你喜欢什么礼物？",
    example_kr: "저는 꽃을 좋아해요.",
    example_en: "I like flowers.",
    example_ja: "私は花が好きです。",
    example_zh: "我喜欢花。",
  },
  {
    level: "A1",
    genre: "opinion",
    prompt_kr: "어떤 옷을 좋아해요?",
    prompt_en: "What clothes do you like?",
    prompt_ja: "どんな服が好きですか？",
    prompt_zh: "你喜欢什么衣服？",
    example_kr: "저는 한복을 좋아해요.",
    example_en: "I like Hanbok.",
    example_ja: "私は韓服が好きです。",
    example_zh: "我喜欢韩服。",
  },
];
