import type { RawPrompt } from "./types";

export const WRITING_A1_REPLY: RawPrompt[] = [
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "지금 뭐 해요? 점심 먹어요?",
    stimulus_en: "What are you doing now? Are you eating lunch?",
    stimulus_ja: "今何してる？お昼食べた？",
    stimulus_zh: "你现在在做什么？在吃午饭吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 밥을 먹어요.",
    example_en: "I eat a meal.",
    example_ja: "私はご飯を食べます。",
    example_zh: "我在吃饭。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "휴일에 보통 뭐 해요?",
    stimulus_en: "What do you usually do on holidays?",
    stimulus_ja: "休みの日は普段何してる？",
    stimulus_zh: "假期你通常做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 음악을 들어요.",
    example_en: "I listen to music.",
    example_ja: "私は音楽を聞きます。",
    example_zh: "我听音乐。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 어떤 음료를 마셔요?",
    stimulus_en: "What kind of drink are you having today?",
    stimulus_ja: "今日はどんな飲み物飲んでる？",
    stimulus_zh: "你今天喝什么饮料？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 커피를 마셔요.",
    example_en: "I drink coffee.",
    example_ja: "私はコーヒーを飲みます。",
    example_zh: "我喝咖啡。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "방에서 지금 뭐 해요?",
    stimulus_en: "What are you doing in the room now?",
    stimulus_ja: "部屋で今何してる？",
    stimulus_zh: "你现在在房间里做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 책을 읽어요.",
    example_en: "I read a book.",
    example_ja: "私は本を読みます。",
    example_zh: "我在读书。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "요즘 학원에서 뭐 해요?",
    stimulus_en: "What do you do at the academy these days?",
    stimulus_ja: "最近塾で何してる？",
    stimulus_zh: "你最近在补习班做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 한국어를 배워요.",
    example_en: "I learn Korean.",
    example_ja: "私は韓国語を習います。",
    example_zh: "我在学韩语。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "주말에 보통 무엇을 해요?",
    stimulus_en: "What do you usually do on the weekend?",
    stimulus_ja: "週末は普段何してる？",
    stimulus_zh: "周末你通常做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 영화를 봐요.",
    example_en: "I watch a movie.",
    example_ja: "私は映画を見ます。",
    example_zh: "我看电影。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 누구를 봐요?",
    stimulus_en: "Who are you seeing this evening?",
    stimulus_ja: "今日の夕方誰に会う？",
    stimulus_zh: "你今晚见谁？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 친구를 만나요.",
    example_en: "I meet a friend.",
    example_ja: "私は友達に会います。",
    example_zh: "我见朋友。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "회사에서 지금 어디로 가요?",
    stimulus_en: "Where are you going now from the office?",
    stimulus_ja: "会社から今どこに行く？",
    stimulus_zh: "你现在从公司去哪里？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 집에 가요.",
    example_en: "I go home.",
    example_ja: "私は家に帰ります。",
    example_zh: "我回家。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "아침에 어디로 출발해요?",
    stimulus_en: "Where do you leave for in the morning?",
    stimulus_ja: "朝どこに出発する？",
    stimulus_zh: "你早上出发去哪里？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 회사에 가요.",
    example_en: "I go to work.",
    example_ja: "私は会社に行きます。",
    example_zh: "我去公司。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "지금 책상 앞에서 뭐 해요?",
    stimulus_en: "What are you doing in front of the desk now?",
    stimulus_ja: "今机の前で何してる？",
    stimulus_zh: "你现在在桌前做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 숙제를 해요.",
    example_en: "I do homework.",
    example_ja: "私は宿題をします。",
    example_zh: "我在做作业。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저녁에 공원에서 뭐 해요?",
    stimulus_en: "What do you do at the park in the evening?",
    stimulus_ja: "夕方公園で何してる？",
    stimulus_zh: "你晚上在公园做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 운동을 해요.",
    example_en: "I exercise.",
    example_ja: "私は運動をします。",
    example_zh: "我做运动。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "방이 왜 그렇게 바빠요?",
    stimulus_en: "Why are you so busy in your room?",
    stimulus_ja: "部屋どうしてそんなに忙しいの？",
    stimulus_zh: "你房间为什么那么忙？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 청소를 해요.",
    example_en: "I clean.",
    example_ja: "私は掃除をします。",
    example_zh: "我在打扫。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "주방에서 지금 뭐 해요?",
    stimulus_en: "What are you doing in the kitchen now?",
    stimulus_ja: "台所で今何してる？",
    stimulus_zh: "你现在在厨房做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 요리를 해요.",
    example_en: "I cook.",
    example_ja: "私は料理をします。",
    example_zh: "我在做饭。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "백화점에서 오늘 뭐 해요?",
    stimulus_en: "What are you doing at the department store today?",
    stimulus_ja: "デパートで今日何してる？",
    stimulus_zh: "你今天在百货商店做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 옷을 사요.",
    example_en: "I buy clothes.",
    example_ja: "私は服を買います。",
    example_zh: "我买衣服。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "베이커리에 왜 갔어요?",
    stimulus_en: "Why did you go to the bakery?",
    stimulus_ja: "パン屋にどうして行ったの？",
    stimulus_zh: "你为什么去面包店了？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 빵을 사요.",
    example_en: "I buy bread.",
    example_ja: "私はパンを買います。",
    example_zh: "我买面包。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "풍경 앞에서 뭐 해요?",
    stimulus_en: "What are you doing in front of the scenery?",
    stimulus_ja: "景色の前で何してる？",
    stimulus_zh: "你在风景前做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 사진을 찍어요.",
    example_en: "I take a picture.",
    example_ja: "私は写真を撮ります。",
    example_zh: "我拍照片。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "책상에 앉아서 뭐 해요?",
    stimulus_en: "What are you doing sitting at the desk?",
    stimulus_ja: "机に座って何してる？",
    stimulus_zh: "你坐在桌前做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 편지를 써요.",
    example_en: "I write a letter.",
    example_ja: "私は手紙を書きます。",
    example_zh: "我写信。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "노래방에서 지금 뭐 해요?",
    stimulus_en: "What are you doing at the karaoke now?",
    stimulus_ja: "カラオケで今何してる？",
    stimulus_zh: "你现在在KTV做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 노래를 부워요.",
    example_en: "I sing a song.",
    example_ja: "私は歌を歌います。",
    example_zh: "我在唱歌。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "운동장에서 오늘 뭐 해요?",
    stimulus_en: "What are you doing on the playground today?",
    stimulus_ja: "運動場で今日何してる？",
    stimulus_zh: "你今天在操场做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 축구를 해요.",
    example_en: "I play soccer.",
    example_ja: "私はサッカーをします。",
    example_zh: "我踢足球。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "풀장에서 지금 뭐 해요?",
    stimulus_en: "What are you doing at the pool now?",
    stimulus_ja: "プールで今何してる？",
    stimulus_zh: "你现在在泳池做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 수영을 해요.",
    example_en: "I swim.",
    example_ja: "私は水泳をします。",
    example_zh: "我在游泳。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "컴퓨터로 지금 뭐 해요?",
    stimulus_en: "What are you doing on the computer now?",
    stimulus_ja: "パソコンで今何してる？",
    stimulus_zh: "你现在用电脑做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 게임을 해요.",
    example_en: "I play a game.",
    example_ja: "私はゲームをします。",
    example_zh: "我在玩游戏。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "스마트폰으로 지금 뭐 해요?",
    stimulus_en: "What are you doing with your smartphone now?",
    stimulus_ja: "スマホで今何してる？",
    stimulus_zh: "你现在用智能手机做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 전화를 걸어요.",
    example_en: "I make a phone call.",
    example_ja: "私は電話をかけます。",
    example_zh: "我打电话。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "친구 생일에 무엇을 해요?",
    stimulus_en: "What do you do on your friend's birthday?",
    stimulus_ja: "友達の誕生日に何する？",
    stimulus_zh: "朋友生日你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 선물을 줘요.",
    example_en: "I give a gift.",
    example_ja: "私はプレゼントをあげます。",
    example_zh: "我送礼物。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "베란다에서 보통 뭐 해요?",
    stimulus_en: "What do you usually do on the veranda?",
    stimulus_ja: "ベランダで普段何してる？",
    stimulus_zh: "你通常在阳台做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 꽃을 키워요.",
    example_en: "I grow flowers.",
    example_ja: "私は花を育てます。",
    example_zh: "我养花。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "다리 위에서 지금 뭐 해요?",
    stimulus_en: "What are you doing on the bridge now?",
    stimulus_ja: "橋の上で今何してる？",
    stimulus_zh: "你现在在桥上做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 강을 건너요.",
    example_en: "I cross the river.",
    example_ja: "私は川を渡ります。",
    example_zh: "我在过江。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "카페에서 오늘 뭐 마셔요?",
    stimulus_en: "What are you drinking at the cafe today?",
    stimulus_ja: "カフェで今日何飲む？",
    stimulus_zh: "你今天在咖啡厅喝什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 차를 마셔요.",
    example_en: "I drink tea.",
    example_ja: "私はお茶を飲みます。",
    example_zh: "我喝茶。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "파티에서 지금 뭐 해요?",
    stimulus_en: "What are you doing at the party now?",
    stimulus_ja: "パーティーで今何してる？",
    stimulus_zh: "你现在在派对上做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 춤을 춰요.",
    example_en: "I dance.",
    example_ja: "私はダンスをします。",
    example_zh: "我在跳舞。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "길을 잃었을 때 뭐 해요?",
    stimulus_en: "What do you do when you get lost?",
    stimulus_ja: "道に迷ったら何する？",
    stimulus_zh: "迷路的时候你会做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지도를 봐요.",
    example_en: "I look at a map.",
    example_ja: "私は地図を見ます。",
    example_zh: "我看地图。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "은행에서 지금 뭐 해요?",
    stimulus_en: "What are you doing at the bank now?",
    stimulus_ja: "銀行で今何してる？",
    stimulus_zh: "你现在在银行做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 돈을 찾아요.",
    example_en: "I withdraw money.",
    example_ja: "私はお金をおろします。",
    example_zh: "我取钱。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "감기에 걸려서 뭐 해요?",
    stimulus_en: "What do you do since you caught a cold?",
    stimulus_ja: "風邪をひいて何する？",
    stimulus_zh: "感冒了你会做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 약을 먹어요.",
    example_en: "I take medicine.",
    example_ja: "私は薬を飲みます。",
    example_zh: "我吃药。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "화장실에서 지금 뭐 해요?",
    stimulus_en: "What are you doing in the bathroom now?",
    stimulus_ja: "トイレで今何してる？",
    stimulus_zh: "你现在在洗手间做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 이를 닦아요.",
    example_en: "I brush my teeth.",
    example_ja: "私は歯を磨きます。",
    example_zh: "我刷牙。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "아침에 일어나서 뭐 해요?",
    stimulus_en: "What do you do after waking up in the morning?",
    stimulus_ja: "朝起きて何する？",
    stimulus_zh: "早上起床后你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 세수를 해요.",
    example_en: "I wash my face.",
    example_ja: "私は顔を洗います。",
    example_zh: "我洗脸。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "샤워할 때 먼저 뭐 해요?",
    stimulus_en: "What do you do first when taking a shower?",
    stimulus_ja: "シャワーするとき最初に何する？",
    stimulus_zh: "洗澡时你先做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 머리를 감아요.",
    example_en: "I wash my hair.",
    example_ja: "私は髪を洗います。",
    example_zh: "我洗头。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "시장 구경에서 뭐 해요?",
    stimulus_en: "What do you do while looking around the market?",
    stimulus_ja: "市場見物で何してる？",
    stimulus_zh: "逛市场时你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 구경을 해요.",
    example_en: "I sightsee.",
    example_ja: "私は見物をします。",
    example_zh: "我逛一逛。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "피곤해서 지금 뭐 해요?",
    stimulus_en: "What are you doing now because you are tired?",
    stimulus_ja: "疲れて今何してる？",
    stimulus_zh: "因为累了你现在做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 휴식을 취해요.",
    example_en: "I take a rest.",
    example_ja: "私は休憩を取ります。",
    example_zh: "我在休息。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "수업 시간에 모르면 뭐 해요?",
    stimulus_en: "What do you do if you don't know during class?",
    stimulus_ja: "授業中わからなかったら何する？",
    stimulus_zh: "上课不懂的时候你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 질문을 해요.",
    example_en: "I ask a question.",
    example_ja: "私は質問をします。",
    example_zh: "我提问。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "선생님이 부르면 뭐 해요?",
    stimulus_en: "What do you do when the teacher calls you?",
    stimulus_ja: "先生が呼んだら何する？",
    stimulus_zh: "老师叫你时你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 대답을 해요.",
    example_en: "I give an answer.",
    example_ja: "私は答えます。",
    example_zh: "我回答。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "주말 계획으로 무엇을 해요?",
    stimulus_en: "What do you do for weekend plans?",
    stimulus_ja: "週末の計画で何する？",
    stimulus_zh: "周末计划你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 약속을 해요.",
    example_en: "I make a promise.",
    example_ja: "私は約束をします。",
    example_zh: "我安排见面。",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "외출하기 전에 뭐 해요?",
    stimulus_en: "What do you do before going out?",
    stimulus_ja: "外出する前に何する？",
    stimulus_zh: "出门前你做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 준비를 해요.",
    example_en: "I make preparations.",
    example_ja: "私は準備をします。",
    example_zh: "我做准备。",
  },
];
