import type { RawPrompt } from "./types";

export const WRITING_A1_REPLY: RawPrompt[] = [
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "안녕하세요! 이름이 뭐예요?",
    stimulus_en: "Hi! What is your name?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "안녕하세요! 제 이름은 민지예요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 같이 밥 먹을래요?",
    stimulus_en: "Do you want to eat dinner together this evening?",
    prompt_kr: "친구의 초대에 답장해 보세요.",
    prompt_en: "Reply to your friend's invitation.",
    example_kr: "네, 좋아요! 몇 시에 만날까요?",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "지금 뭐 해요?",
    stimulus_en: "What are you doing right now?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 지금 책을 읽고 있어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "내일 시간 있어요? 같이 영화 봐요.",
    stimulus_en: "Are you free tomorrow? Let's watch a movie together.",
    prompt_kr: "친구의 초대에 답장해 보세요.",
    prompt_en: "Reply to your friend's invitation.",
    example_kr: "네, 내일 시간 있어요. 몇 시에 볼까요?",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "생일 축하해요! 오늘 뭐 할 거예요?",
    stimulus_en: "Happy birthday! What are you going to do today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Reply to your friend's message.",
    example_kr: "고마워요! 오늘 가족과 저녁을 먹을 거예요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "어디에 살아요?",
    stimulus_en: "Where do you live?",
    prompt_kr: "새로운 친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to a new friend's question.",
    example_kr: "저는 서울에 살아요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "주말에 뭐 했어요?",
    stimulus_en: "What did you do this weekend?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 주말에 공원에 갔어요. 재미있었어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "매운 음식 좋아해요?",
    stimulus_en: "Do you like spicy food?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "네, 저는 매운 음식을 좋아해요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "오늘 날씨가 좋아요. 하늘이 맑아요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "이번 주 토요일에 제 생일 파티가 있어요. 올 수 있어요?",
    stimulus_en: "My birthday party is this Saturday. Can you come?",
    prompt_kr: "친구의 초대에 답장해 보세요.",
    prompt_en: "Reply to your friend's invitation.",
    example_kr: "네, 갈 수 있어요! 몇 시예요?",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "지금 밖에 비가 와요. 우산 있어요?",
    stimulus_en: "It's raining outside right now. Do you have an umbrella?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Reply to your friend's message.",
    example_kr: "네, 저는 우산이 있어요. 걱정하지 마세요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "커피 마시러 갈래요?",
    stimulus_en: "Do you want to go get coffee?",
    prompt_kr: "친구의 제안에 답장해 보세요.",
    prompt_en: "Reply to your friend's suggestion.",
    example_kr: "좋아요! 몇 시에 만날까요?",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "형제나 자매가 있어요?",
    stimulus_en: "Do you have any siblings?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "네, 저는 언니가 한 명 있어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "요즘 한국어 공부 어때요?",
    stimulus_en: "How's your Korean study going these days?",
    prompt_kr: "선생님의 질문에 대답해 보세요.",
    prompt_en: "Reply to your teacher's question.",
    example_kr: "재미있어요. 하지만 조금 어려워요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저 지금 도착했어요. 어디에 있어요?",
    stimulus_en: "I just arrived. Where are you?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Reply to your friend's message.",
    example_kr: "저는 카페 앞에 있어요. 여기로 오세요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 학교에 왜 안 왔어요? 괜찮아요?",
    stimulus_en: "Why didn't you come to school today? Are you okay?",
    prompt_kr: "친구의 걱정에 답장해 보세요.",
    prompt_en: "Reply to your friend's concern.",
    example_kr: "저는 조금 아팠어요. 지금은 괜찮아요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "무슨 음악 좋아해요?",
    stimulus_en: "What music do you like?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 케이팝을 좋아해요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "이번 여름에 어디 여행 가고 싶어요?",
    stimulus_en: "Where do you want to travel this summer?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 제주도에 가고 싶어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹을까요?",
    stimulus_en: "What should we eat for dinner?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "김밥 어때요? 저는 김밥을 좋아해요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "아니요, 아직 안 했어요. 지금 할 거예요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "요즘 바빠요?",
    stimulus_en: "Are you busy these days?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "네, 요즘 조금 바빠요. 일이 많아요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "내일 저랑 같이 운동할래요?",
    stimulus_en: "Do you want to exercise with me tomorrow?",
    prompt_kr: "친구의 제안에 답장해 보세요.",
    prompt_en: "Reply to your friend's suggestion.",
    example_kr: "네, 좋아요! 아침에 만나요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "몇 시에 일어나요?",
    stimulus_en: "What time do you wake up?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 보통 일곱 시에 일어나요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "새 옷 샀어요? 예뻐요!",
    stimulus_en: "Did you buy new clothes? They look pretty!",
    prompt_kr: "친구의 칭찬에 답장해 보세요.",
    prompt_en: "Reply to your friend's compliment.",
    example_kr: "고마워요! 어제 샀어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저는 지금 공원에 있어요. 같이 산책할래요?",
    stimulus_en: "I'm at the park right now. Do you want to walk together?",
    prompt_kr: "친구의 제안에 답장해 보세요.",
    prompt_en: "Reply to your friend's suggestion.",
    example_kr: "좋아요! 지금 갈게요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "가족이 몇 명이에요?",
    stimulus_en: "How many people are in your family?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "우리 가족은 네 명이에요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "지금 어디 가요?",
    stimulus_en: "Where are you going right now?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 지금 마트에 가요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 시험 어땠어요?",
    stimulus_en: "How was the test today?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "조금 어려웠어요. 하지만 괜찮았어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저 다음 주에 이사해요. 도와줄 수 있어요?",
    stimulus_en: "I'm moving next week. Can you help me?",
    prompt_kr: "친구의 부탁에 답장해 보세요.",
    prompt_en: "Reply to your friend's request.",
    example_kr: "네, 도와줄 수 있어요. 몇 시에 갈까요?",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "핸드폰 번호가 뭐예요?",
    stimulus_en: "What's your phone number?",
    prompt_kr: "새로운 친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to a new friend's question.",
    example_kr: "제 번호는 010-1234-5678이에요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 좀 피곤해 보여요. 괜찮아요?",
    stimulus_en: "You look a little tired today. Are you okay?",
    prompt_kr: "친구의 걱정에 답장해 보세요.",
    prompt_en: "Reply to your friend's concern.",
    example_kr: "네, 괜찮아요. 어제 늦게 잤어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "우리 다음 주에 다시 만날까요?",
    stimulus_en: "Should we meet again next week?",
    prompt_kr: "친구의 제안에 답장해 보세요.",
    prompt_en: "Reply to your friend's suggestion.",
    example_kr: "네, 좋아요. 화요일 어때요?",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "취미가 뭐예요?",
    stimulus_en: "What is your hobby?",
    prompt_kr: "새로운 친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to a new friend's question.",
    example_kr: "제 취미는 요리예요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저 오늘 시간이 없어요. 미안해요.",
    stimulus_en: "I don't have time today. Sorry.",
    prompt_kr: "친구의 사과에 답장해 보세요.",
    prompt_en: "Reply to your friend's apology.",
    example_kr: "괜찮아요. 다음에 만나요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "선물 정말 고마워요!",
    stimulus_en: "Thank you so much for the gift!",
    prompt_kr: "친구의 감사 인사에 답장해 보세요.",
    prompt_en: "Reply to your friend's thanks.",
    example_kr: "천만에요. 마음에 들었으면 좋겠어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 뭐 먹었어요?",
    stimulus_en: "What did you eat today?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 오늘 비빔밥을 먹었어요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "저 지금 길을 잃었어요. 도와줄 수 있어요?",
    stimulus_en: "I'm lost right now. Can you help me?",
    prompt_kr: "친구의 부탁에 답장해 보세요.",
    prompt_en: "Reply to your friend's request.",
    example_kr: "네, 지금 어디에 있어요? 제가 갈게요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "제일 좋아하는 계절이 뭐예요?",
    stimulus_en: "What is your favorite season?",
    prompt_kr: "친구의 질문에 대답해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "저는 봄을 제일 좋아해요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "우리 내일 몇 시에 만날까요?",
    stimulus_en: "What time should we meet tomorrow?",
    prompt_kr: "친구의 질문에 답장해 보세요.",
    prompt_en: "Reply to your friend's question.",
    example_kr: "오후 두 시에 만나요.",
  },
  {
    level: "A1",
    genre: "reply",
    stimulus_kr: "오늘 정말 즐거웠어요. 고마워요!",
    stimulus_en: "I had a really fun time today. Thank you!",
    prompt_kr: "친구의 인사에 답장해 보세요.",
    prompt_en: "Reply to your friend's message.",
    example_kr: "저도 즐거웠어요. 다음에 또 만나요.",
  },
];
