import type { RawPrompt } from "./types";

export const WRITING_A2_A: RawPrompt[] = [
  {
    level: "A2",
    prompt_kr: "버스를 잘못 타서 생긴 일에 대해 '-아서/어서'를 사용해서 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about a time you got on the wrong bus, using '-아서/어서' to explain cause and effect.",
    example_kr: "어제 버스 번호를 잘못 봐서 다른 방향으로 갔어요. 낯선 동네에 내려서 깜짝 놀랐어요. 지도를 보고 다시 버스를 타서 집에 왔어요. 다음부터는 번호를 두 번 확인할 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "아침에 늦잠을 잔 날 이야기를 '-지만'을 사용해서 쓰세요.",
    prompt_en: "Write about a day you overslept, using '-지만' to contrast what happened.",
    example_kr: "알람이 울렸지만 저는 계속 잤어요. 늦게 일어났지만 서둘러서 준비했어요. 택시를 탔지만 결국 회의에 늦었어요. 미안했지만 동료들이 이해해 줬어요.",
  },
  {
    level: "A2",
    prompt_kr: "산에 올라갔을 때 있었던 일을 '-을 때'를 사용해서 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about something that happened while you were hiking, using '-을 때'.",
    example_kr: "산 정상에 도착했을 때 안개가 가득했어요. 사진을 찍을 때 바람이 세게 불었어요. 내려올 때 다리가 많이 아팠어요. 하지만 경치를 볼 때 정말 행복했어요.",
  },
  {
    level: "A2",
    prompt_kr: "여행 가방을 싸기 전에 무엇을 확인하는지 '-기 전에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you check before packing a suitcase, using '-기 전에'.",
    example_kr: "여행 가방을 싸기 전에 날씨를 확인해요. 옷을 넣기 전에 목록을 만들어요. 공항에 가기 전에 여권을 다시 확인해요. 이렇게 준비하면 여행이 편해요.",
  },
  {
    level: "A2",
    prompt_kr: "저녁을 먹은 후에 무엇을 하는지 '-은 후에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about your habits after eating dinner, using '-은 후에'.",
    example_kr: "저녁을 먹은 후에 설거지를 해요. 설거지를 한 후에 산책을 나가요. 산책한 후에 책을 조금 읽어요. 그리고 일찍 잠자리에 들어요.",
  },
  {
    level: "A2",
    prompt_kr: "공항에서 비행기를 놓친 경험을 '-고 나서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a time you missed a flight, using '-고 나서'.",
    example_kr: "길이 막혀서 늦게 도착했어요. 체크인 카운터에 가고 나서 문이 이미 닫힌 것을 알았어요. 직원과 이야기하고 나서 다음 비행기를 예약했어요. 결국 몇 시간을 공항에서 기다렸어요.",
  },
  {
    level: "A2",
    prompt_kr: "낯선 음식을 처음 먹어 본 경험을 '-어 보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about the first time you tried an unusual food, using '-어 보다'.",
    example_kr: "저는 작년에 낫토를 처음 먹어 봤어요. 냄새가 강해서 조금 놀랐어요. 그래도 용기를 내서 먹어 봤어요. 생각보다 맛있어서 또 먹고 싶어졌어요.",
  },
  {
    level: "A2",
    prompt_kr: "휴대폰 없이 하루를 보낼 수 있는지 '-을 수 있어요/없어요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you can spend a day without your phone, using '-을 수 있어요/없어요'.",
    example_kr: "저는 하루 종일 휴대폰 없이 지낼 수 없어요. 하지만 지난주에 한번 시도해 봤어요. 처음에는 불안했지만 몇 시간은 견딜 수 있었어요. 완전히 끊는 것은 아직 할 수 없어요.",
  },
  {
    level: "A2",
    prompt_kr: "혼자 영화 보는 것을 좋아하는지 '-는 것을 좋아해요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you like watching movies alone, using '-는 것을 좋아해요'.",
    example_kr: "저는 혼자 영화 보는 것을 좋아해요. 팝콘을 사서 조용히 앉아 있는 것을 좋아해요. 지난 주말에도 극장에 혼자 갔어요. 다음에도 새 영화가 나오면 또 보러 갈 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "친구에게 즉흥적으로 여행 가자고 제안하는 상황을 '-을래요?'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about spontaneously suggesting a trip to a friend, using '-을래요?'.",
    example_kr: "저는 갑자기 바다가 보고 싶었어요. 친구에게 전화해서 '이번 주말에 같이 갈래요?'라고 물었어요. 친구가 좋다고 해서 바로 기차표를 예매했어요. 계획 없이 떠난 여행이 제일 재미있었어요.",
  },
  {
    level: "A2",
    prompt_kr: "예상보다 물건 값이 비쌌던 경험을 '-보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a time something cost more than expected, using '-보다'.",
    example_kr: "시장에서 가방을 봤는데 생각보다 비쌌어요. 온라인 가격보다 훨씬 높았어요. 그래도 품질이 좋아서 결국 샀어요. 나중에 후회는 안 했어요.",
  },
  {
    level: "A2",
    prompt_kr: "약속에 늦은 이유를 '-기 때문에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences explaining why you were late to an appointment, using '-기 때문에'.",
    example_kr: "어젯밤에 잠을 못 잤기 때문에 아침에 늦게 일어났어요. 지하철이 고장 났기 때문에 더 늦어졌어요. 친구가 화가 났기 때문에 저는 사과를 여러 번 했어요. 다음에는 일찍 나갈 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "비가 오면 계획이 어떻게 바뀌는지 '-으면/면'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about how your plans change if it rains, using '-으면/면'.",
    example_kr: "주말에 비가 오면 저는 집에 있어요. 날씨가 좋으면 자전거를 타러 나가요. 지난주에는 갑자기 비가 와서 계획을 바꿨어요. 대신 카페에서 책을 읽었어요.",
  },
  {
    level: "A2",
    prompt_kr: "지갑을 집에 두고 나와서 겪은 일을 '-아서/어서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a time you forgot your wallet at home, using '-아서/어서'.",
    example_kr: "아침에 서둘러서 지갑을 안 가지고 나왔어요. 편의점에서 계산할 때 알아서 당황했어요. 다행히 친구가 돈을 빌려줘서 문제가 해결됐어요. 그날 저녁에 바로 돈을 갚았어요.",
  },
  {
    level: "A2",
    prompt_kr: "예상과 다른 날씨를 만난 여행 경험을 '-지만'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a trip where the weather was unexpected, using '-지만'.",
    example_kr: "여행 전에는 날씨가 맑을 거라고 들었지만 도착하자마자 비가 왔어요. 우산이 없었지만 편의점에서 하나 샀어요. 비가 계속 왔지만 실내 관광지를 구경했어요. 아쉬웠지만 그래도 즐거운 여행이었어요.",
  },
  {
    level: "A2",
    prompt_kr: "새로운 취미를 시작했을 때 느낀 점을 '-을 때'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about how you felt when you started a new activity, using '-을 때'.",
    example_kr: "처음 수영을 배울 때 물이 무서웠어요. 강사님이 도와줄 때 조금 안심이 됐어요. 처음 혼자 헤엄칠 때 정말 뿌듯했어요. 지금도 수영장에 갈 때마다 그날이 생각나요.",
  },
  {
    level: "A2",
    prompt_kr: "설거지를 하기 전에 하는 습관을 '-기 전에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a habit you have before doing the dishes, using '-기 전에'.",
    example_kr: "설거지를 하기 전에 음악을 틀어요. 물을 틀기 전에 그릇을 정리해요. 시작하기 전에 고무장갑을 껴요. 이렇게 하면 설거지가 덜 힘들어요.",
  },
  {
    level: "A2",
    prompt_kr: "낯선 도시에서 길을 잃어버린 후에 한 일을 '-은 후에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you did after getting lost in an unfamiliar city, using '-은 후에'.",
    example_kr: "지도 앱이 갑자기 꺼진 후에 완전히 길을 잃었어요. 30분 동안 헤맨 후에 경찰서를 찾았어요. 경찰관에게 도움을 받은 후에 겨우 숙소로 돌아갔어요. 그 후에는 지도를 미리 저장해요.",
  },
  {
    level: "A2",
    prompt_kr: "친구와 크게 싸운 후에 화해한 이야기를 '-고 나서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about making up with a friend after a big argument, using '-고 나서'.",
    example_kr: "친구와 크게 싸우고 나서 며칠 동안 연락을 안 했어요. 마음이 진정되고 나서 먼저 문자를 보냈어요. 만나서 이야기하고 나서 오해가 풀렸어요. 지금은 예전보다 더 친해졌어요.",
  },
  {
    level: "A2",
    prompt_kr: "번지 점프나 스카이다이빙 같은 것을 해 본 경험을 '-어 보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about trying something extreme like bungee jumping, using '-어 보다'.",
    example_kr: "작년에 처음으로 번지 점프를 해 봤어요. 뛰기 전에는 다리가 떨렸어요. 막상 뛰어 보니까 무섭지만 정말 짜릿했어요. 다음에 다시 해 보고 싶어요.",
  },
  {
    level: "A2",
    prompt_kr: "새벽에 일찍 일어날 수 있는지 '-을 수 있어요/없어요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you can wake up early, using '-을 수 있어요/없어요'.",
    example_kr: "평소에는 새벽에 일어날 수 없어요. 하지만 여행을 갈 때는 일찍 일어날 수 있어요. 지난달에는 일출을 보려고 새벽 5시에 일어났어요. 힘들었지만 정말 아름다웠어요.",
  },
  {
    level: "A2",
    prompt_kr: "비 오는 날 창밖을 보는 것을 좋아하는지 '-는 것을 좋아해요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you like watching the rain from a window, using '-는 것을 좋아해요'.",
    example_kr: "저는 비 오는 날 창밖을 보는 것을 좋아해요. 따뜻한 차를 마시면서 보는 것을 좋아해요. 어제도 비가 와서 한 시간 동안 창가에 앉아 있었어요. 그런 시간이 저에게는 휴식이에요.",
  },
  {
    level: "A2",
    prompt_kr: "룸메이트에게 청소를 같이 하자고 제안하는 상황을 '-을래요?'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about suggesting to a roommate that you clean together, using '-을래요?'.",
    example_kr: "집이 너무 지저분해서 걱정이 됐어요. 룸메이트에게 '오늘 같이 청소할래요?'라고 물어봤어요. 룸메이트가 좋다고 해서 함께 청소를 시작했어요. 청소가 끝나니까 기분이 훨씬 좋아졌어요.",
  },
  {
    level: "A2",
    prompt_kr: "기대했던 것보다 재미없었던 영화 이야기를 '-보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a movie that was less fun than you expected, using '-보다'.",
    example_kr: "지난 주에 유명한 영화를 봤어요. 그런데 광고보다 재미없었어요. 친구의 기대보다도 실망스러웠어요. 그래도 팝콘은 맛있어서 괜찮았어요.",
  },
  {
    level: "A2",
    prompt_kr: "시험 전날 잠을 못 잔 이유를 '-기 때문에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about why you couldn't sleep before an exam, using '-기 때문에'.",
    example_kr: "다음 날 시험이 있었기 때문에 너무 긴장됐어요. 걱정이 많았기 때문에 계속 뒤척였어요. 결국 새벽 3시까지 못 잤기 때문에 아침에 매우 피곤했어요. 그래도 시험은 잘 봤어요.",
  },
  {
    level: "A2",
    prompt_kr: "일찍 자면 다음 날 어떻게 다른지 '-으면/면'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about how the next day is different if you sleep early, using '-으면/면'.",
    example_kr: "일찍 자면 아침에 기분이 좋아요. 늦게 자면 하루 종일 피곤해요. 어제는 일찍 자서 오늘 컨디션이 아주 좋아요. 앞으로도 일찍 자려고 노력할 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "엘리베이터에 갇혔던 경험을 '-아서/어서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a time you got stuck in an elevator, using '-아서/어서'.",
    example_kr: "정전이 나서 엘리베이터가 갑자기 멈췄어요. 너무 무서워서 소리를 질렀어요. 관리인이 빨리 와서 문을 열어 줬어요. 그 후로는 계단을 자주 이용해요.",
  },
  {
    level: "A2",
    prompt_kr: "가족 모임에서 있었던 재미있는 실수를 '-지만'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a funny mistake at a family gathering, using '-지만'.",
    example_kr: "설날에 삼촌 이름을 잘못 불렀지만 아무도 화내지 않았어요. 조금 창피했지만 다들 웃었어요. 처음에는 당황했지만 나중에는 저도 같이 웃었어요. 지금은 가족 모임 때마다 그 이야기를 해요.",
  },
  {
    level: "A2",
    prompt_kr: "처음 스키를 탔을 때 있었던 일을 '-을 때'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what happened the first time you went skiing, using '-을 때'.",
    example_kr: "처음 스키장에 갔을 때 어떻게 서는지도 몰랐어요. 슬로프를 내려갈 때 계속 넘어졌어요. 마지막에 조금 익숙해질 때 정말 신났어요. 다음 겨울에도 또 가고 싶어요.",
  },
  {
    level: "A2",
    prompt_kr: "면접을 보기 전에 준비하는 것을 '-기 전에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you prepare before an interview, using '-기 전에'.",
    example_kr: "면접을 보기 전에 회사에 대해 조사해요. 나가기 전에 옷을 미리 준비해요. 면접장에 들어가기 전에 심호흡을 해요. 이렇게 하면 긴장이 조금 풀려요.",
  },
  {
    level: "A2",
    prompt_kr: "이사를 온 후에 새 동네에서 겪은 일을 '-은 후에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what happened after moving to a new neighborhood, using '-은 후에'.",
    example_kr: "새 동네로 이사한 후에 길을 잘 몰라서 자주 헤맸어요. 며칠 지난 후에 조금씩 익숙해졌어요. 이웃과 인사를 나눈 후에 마음이 편해졌어요. 지금은 이 동네가 정말 좋아요.",
  },
  {
    level: "A2",
    prompt_kr: "발표를 끝내고 나서 느낀 점을 '-고 나서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about how you felt after finishing a presentation, using '-고 나서'.",
    example_kr: "발표를 하기 전에는 손이 떨렸어요. 발표를 끝내고 나서 온몸에 힘이 빠졌어요. 박수 소리를 듣고 나서 조금씩 안심이 됐어요. 발표가 끝나고 나서 동료들이 칭찬해 줬어요.",
  },
  {
    level: "A2",
    prompt_kr: "매운 음식에 도전해 본 경험을 '-어 보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about trying very spicy food, using '-어 보다'.",
    example_kr: "친구가 매운 라면을 먹어 보라고 했어요. 저는 용기를 내서 한 입 먹어 봤어요. 너무 매워서 눈물이 났어요. 그래도 재미있는 경험이어서 좋았어요.",
  },
  {
    level: "A2",
    prompt_kr: "혼자 캠핑을 갈 수 있는지 '-을 수 있어요/없어요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you can go camping alone, using '-을 수 있어요/없어요'.",
    example_kr: "저는 예전에는 혼자 캠핑을 갈 수 없었어요. 무섭기도 하고 자신이 없었어요. 하지만 이번 여름에는 혼자 갈 수 있었어요. 생각보다 편안하고 즐거운 시간이었어요.",
  },
  {
    level: "A2",
    prompt_kr: "일요일 아침에 늦게까지 침대에 있는 것을 좋아하는지 '-는 것을 좋아해요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you like staying in bed late on Sunday mornings, using '-는 것을 좋아해요'.",
    example_kr: "저는 일요일 아침에 늦게까지 침대에 있는 것을 좋아해요. 알람 없이 자연스럽게 일어나는 것을 좋아해요. 지난 일요일에도 정오까지 잤어요. 그런 여유로운 시간이 저에게 꼭 필요해요.",
  },
  {
    level: "A2",
    prompt_kr: "동료에게 점심을 같이 먹으러 나가자고 제안하는 상황을 '-을래요?'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about suggesting a colleague go out for lunch together, using '-을래요?'.",
    example_kr: "새로 온 동료가 계속 혼자 밥을 먹었어요. 그래서 제가 '같이 점심 먹을래요?'라고 물었어요. 동료가 기뻐하면서 좋다고 했어요. 그날부터 우리는 자주 같이 밥을 먹어요.",
  },
  {
    level: "A2",
    prompt_kr: "생각했던 것보다 오래 걸린 일에 대해 '-보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about something that took longer than you thought, using '-보다'.",
    example_kr: "이케아 가구를 조립하기로 했어요. 설명서를 봤지만 생각보다 훨씬 어려웠어요. 예상보다 세 시간이나 더 걸렸어요. 그래도 다 만들고 나니까 뿌듯했어요.",
  },
  {
    level: "A2",
    prompt_kr: "여행에서 사진을 많이 찍은 이유를 '-기 때문에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about why you took many photos on a trip, using '-기 때문에'.",
    example_kr: "풍경이 너무 아름다웠기 때문에 사진을 많이 찍었어요. 다시 오기 힘들기 때문에 순간을 기록하고 싶었어요. 친구들이 부러워했기 때문에 더 많이 공유했어요. 지금도 그 사진들을 자주 봐요.",
  },
  {
    level: "A2",
    prompt_kr: "일찍 도착하면 무엇을 하는지 '-으면/면'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you do if you arrive somewhere early, using '-으면/면'.",
    example_kr: "약속 장소에 일찍 도착하면 카페에서 기다려요. 시간이 많이 남으면 책을 읽어요. 지난주에도 일찍 도착해서 커피를 마셨어요. 이렇게 여유를 가지면 마음이 편해요.",
  },
  {
    level: "A2",
    prompt_kr: "택배를 잘못 받았던 경험을 '-아서/어서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about receiving the wrong package delivery, using '-아서/어서'.",
    example_kr: "주소를 착각해서 다른 사람의 택배를 받았어요. 상자를 열어서 깜짝 놀랐어요. 배송 회사에 연락해서 문제를 설명했어요. 결국 다음 날 제 택배가 제대로 도착했어요.",
  },
  {
    level: "A2",
    prompt_kr: "긴 줄을 서서 기다린 경험을 '-지만'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about waiting in a long line, using '-지만'.",
    example_kr: "유명한 빵집 앞에 줄이 길었지만 저는 기다리기로 했어요. 한 시간이나 걸렸지만 포기하지 않았어요. 다리가 아팠지만 결국 빵을 샀어요. 맛있었지만 다음에는 조금 더 일찍 갈 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "처음 운전면허 시험을 봤을 때 있었던 일을 '-을 때'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what happened when you first took a driving test, using '-을 때'.",
    example_kr: "처음 운전면허 시험을 볼 때 정말 긴장했어요. 주차할 때 손이 떨렸어요. 시험관이 합격이라고 말할 때 너무 기뻤어요. 그날 저녁에 가족과 함께 축하했어요.",
  },
  {
    level: "A2",
    prompt_kr: "긴 비행을 타기 전에 준비하는 것을 '-기 전에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you prepare before a long flight, using '-기 전에'.",
    example_kr: "긴 비행을 타기 전에 목베개를 챙겨요. 공항에 가기 전에 짐을 다시 확인해요. 비행기에 타기 전에 물을 사요. 이렇게 준비하면 비행이 편해요.",
  },
  {
    level: "A2",
    prompt_kr: "운동을 시작한 후에 몸이 어떻게 바뀌었는지 '-은 후에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about how your body changed after you started exercising, using '-은 후에'.",
    example_kr: "운동을 시작한 후에 몸이 조금 가벼워졌어요. 두 달이 지난 후에 체력이 많이 좋아졌어요. 꾸준히 한 후에 잠도 더 잘 자게 됐어요. 앞으로도 계속 운동할 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "짐을 다 풀고 나서 여행에서 아쉬웠던 점을 '-고 나서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you regretted about a trip after unpacking, using '-고 나서'.",
    example_kr: "여행에서 돌아와서 짐을 풀고 나서 기념품을 못 산 게 생각났어요. 사진을 정리하고 나서 더 많이 찍을 걸 후회했어요. 며칠 쉬고 나서 다시 여행 계획을 세우기 시작했어요. 다음에는 더 여유 있게 다닐 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "패러글라이딩이나 서핑 같은 새로운 스포츠를 해 본 경험을 '-어 보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about trying a new sport like paragliding or surfing, using '-어 보다'.",
    example_kr: "지난여름에 처음으로 서핑을 해 봤어요. 처음에는 계속 넘어져서 물을 많이 먹었어요. 강사님 도움으로 몇 번 파도를 타 봤어요. 다음 여름에도 꼭 다시 해 보고 싶어요.",
  },
  {
    level: "A2",
    prompt_kr: "휴일에 하루 종일 요리만 할 수 있는지 '-을 수 있어요/없어요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you can spend a whole holiday just cooking, using '-을 수 있어요/없어요'.",
    example_kr: "저는 요리를 좋아해서 하루 종일 부엌에 있을 수 있어요. 지난 공휴일에도 아침부터 저녁까지 요리만 했어요. 세 가지 다른 요리를 만들 수 있었어요. 친구들을 초대해서 같이 먹었어요.",
  },
  {
    level: "A2",
    prompt_kr: "손편지 쓰는 것을 좋아하는지 '-는 것을 좋아해요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you like writing handwritten letters, using '-는 것을 좋아해요'.",
    example_kr: "저는 손으로 편지를 쓰는 것을 좋아해요. 예쁜 편지지를 고르는 것도 좋아해요. 지난달에도 친구에게 긴 편지를 썼어요. 그 친구도 답장을 보내 줘서 정말 기뻤어요.",
  },
  {
    level: "A2",
    prompt_kr: "예상보다 사람이 많았던 축제 경험을 '-보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a festival that was more crowded than expected, using '-보다'.",
    example_kr: "지난달에 벚꽃 축제에 갔어요. 작년보다 사람이 훨씬 많았어요. 예상보다 줄이 길어서 표를 사는 데 오래 걸렸어요. 그래도 벚꽃이 아름다워서 만족했어요.",
  },
  {
    level: "A2",
    prompt_kr: "친구가 갑자기 방문하면 어떻게 하는지 '-으면/면'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you do if a friend visits suddenly, using '-으면/면'.",
    example_kr: "친구가 갑자기 오면 저는 집을 빨리 정리해요. 시간이 없으면 간단한 음식을 준비해요. 지난주에도 친구가 갑자기 와서 급하게 청소했어요. 그래도 함께 있는 시간이 즐거웠어요.",
  },
  {
    level: "A2",
    prompt_kr: "우산을 안 가져가서 비를 맞은 경험을 '-아서/어서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a time you got soaked because you forgot your umbrella, using '-아서/어서'.",
    example_kr: "일기예보를 안 봐서 우산을 안 챙겼어요. 갑자기 비가 와서 옷이 다 젖었어요. 편의점에서 우산을 사서 겨우 집에 왔어요. 그 후로는 항상 일기예보를 확인해요.",
  },
  {
    level: "A2",
    prompt_kr: "온라인으로 산 물건이 마음에 안 들었던 경험을 '-지만'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about ordering something online that you didn't like, using '-지만'.",
    example_kr: "사진은 예뻤지만 실제로 받아 보니 색이 달랐어요. 반품하고 싶었지만 절차가 복잡했어요. 조금 실망했지만 결국 그냥 쓰기로 했어요. 다음부터는 후기를 더 꼼꼼히 읽을 거예요.",
  },
  {
    level: "A2",
    prompt_kr: "처음 자전거를 배웠을 때 있었던 일을 '-을 때'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what happened when you first learned to ride a bike, using '-을 때'.",
    example_kr: "처음 자전거를 배울 때 아빠가 뒤에서 잡아 줬어요. 균형을 잡을 때 여러 번 넘어졌어요. 혼자 탈 때 너무 신났어요. 지금도 자전거를 탈 때마다 그 순간이 생각나요.",
  },
  {
    level: "A2",
    prompt_kr: "새 학기가 시작되기 전에 준비하는 것을 '-기 전에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you prepare before a new semester starts, using '-기 전에'.",
    example_kr: "학기가 시작되기 전에 교과서를 미리 사요. 수업이 시작하기 전에 시간표를 확인해요. 개학하기 전에 필요한 문구도 준비해요. 이렇게 준비하면 첫날이 덜 바빠요.",
  },
  {
    level: "A2",
    prompt_kr: "결혼식에 다녀온 후에 느낀 점을 '-은 후에'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about how you felt after attending a wedding, using '-은 후에'.",
    example_kr: "친구의 결혼식에 다녀온 후에 마음이 따뜻해졌어요. 축하 인사를 전한 후에 사진도 많이 찍었어요. 집에 돌아온 후에도 계속 그날 생각이 났어요. 저도 언젠가 결혼하고 싶어졌어요.",
  },
  {
    level: "A2",
    prompt_kr: "이사를 다 끝내고 나서 힘들었던 점을 '-고 나서'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what was hard after finishing a move, using '-고 나서'.",
    example_kr: "이사를 끝내고 나서 온몸이 아팠어요. 짐을 다 옮기고 나서 힘이 하나도 없었어요. 정리를 다 하고 나서 겨우 쉴 수 있었어요. 그래도 새집이 마음에 들어서 좋았어요.",
  },
  {
    level: "A2",
    prompt_kr: "밤에 별을 보는 것을 좋아하는지 '-는 것을 좋아해요'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about whether you like stargazing at night, using '-는 것을 좋아해요'.",
    example_kr: "저는 밤에 별을 보는 것을 좋아해요. 도시를 떠나서 캠핑장에서 보는 것을 좋아해요. 지난여름에도 친구들과 별을 보러 갔어요. 그날 본 별들을 아직도 잊을 수 없어요.",
  },
  {
    level: "A2",
    prompt_kr: "동생에게 같이 자전거를 타러 가자고 제안하는 상황을 '-을래요?'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about suggesting to a sibling that you go biking together, using '-을래요?'.",
    example_kr: "날씨가 너무 좋아서 밖에 나가고 싶었어요. 동생에게 '같이 자전거 탈래요?'라고 물었어요. 동생이 좋다고 해서 같이 공원에 갔어요. 오랜만에 동생과 좋은 시간을 보냈어요.",
  },
  {
    level: "A2",
    prompt_kr: "기대했던 것보다 즐거웠던 가족 여행을 '-보다'를 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about a family trip that was more fun than expected, using '-보다'.",
    example_kr: "사실 처음에는 이번 여행을 별로 기대하지 않았어요. 그런데 예상보다 훨씬 재미있었어요. 생각보다 숙소도 좋고 음식도 맛있었어요. 다음에 또 같은 곳에 가고 싶어졌어요.",
  },
  {
    level: "A2",
    prompt_kr: "여유 시간이 생기면 무엇을 하는지 '-으면/면'을 사용해서 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you do when you have free time, using '-으면/면'.",
    example_kr: "여유 시간이 생기면 저는 그림을 그려요. 시간이 많으면 긴 산책도 해요. 지난 휴일에 시간이 많이 남아서 하루 종일 그림을 그렸어요. 이런 취미가 마음을 편하게 해 줘요.",
  },
];
