import type { RawPrompt } from "./types";

export const WRITING_A2_DESCRIPTION: RawPrompt[] = [
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 어디에 갔어요?",
    prompt_en: "Where did you go yesterday?",
    prompt_ja: "昨日どこに行きましたか？",
    example_kr: "저는 어제 바다에 갔어요.",
    example_en: "I went to the sea yesterday.",
    example_ja: "私は昨日海に行きました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 무엇을 먹었어요?",
    prompt_en: "What did you eat last week?",
    prompt_ja: "先週何を食べましたか？",
    example_kr: "우리는 지난주에 빵을 먹었어요.",
    example_en: "We ate bread last week.",
    example_ja: "私たちは先週パンを食べました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "아침에 무엇을 마셨어요?",
    prompt_en: "What did you drink in the morning?",
    prompt_ja: "朝何を飲みましたか？",
    example_kr: "저는 아침에 차를 마셨어요.",
    example_en: "I drank tea in the morning.",
    example_ja: "私は朝お茶を飲みました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 누구를 만났어요?",
    prompt_en: "Who did you meet yesterday?",
    prompt_ja: "昨日誰に会いましたか？",
    example_kr: "나는 어제 친구를 만났어요.",
    example_en: "I met a friend yesterday.",
    example_ja: "私は昨日友達に会いました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "작년에 어디에서 살았어요?",
    prompt_en: "Where did you live last year?",
    prompt_ja: "去年どこに住んでいましたか？",
    example_kr: "저는 작년에 서울에 살았었어요.",
    example_en: "I lived in Seoul last year.",
    example_ja: "私は去年ソウルに住んでいました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 도서관에서 무엇을 했어요?",
    prompt_en: "What did you do at the library yesterday?",
    prompt_ja: "昨日図書館で何をしましたか？",
    example_kr: "저는 어제 책을 읽었어요.",
    example_en: "I read a book yesterday.",
    example_ja: "私は昨日本を読みました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 방에서 무엇을 했어요?",
    prompt_en: "What did you do in your room last week?",
    prompt_ja: "先週部屋で何をしましたか？",
    example_kr: "나는 지난주에 방을 청소했어요.",
    example_en: "I cleaned my room last week.",
    example_ja: "私は先週部屋を掃除しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 백화점에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the department store yesterday?",
    prompt_ja: "昨日デパートで何を買いましたか？",
    example_kr: "저는 어제 구두를 샀어요.",
    example_en: "I bought shoes yesterday.",
    example_ja: "私は昨日靴を買いました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 밤에 무엇을 보았어요?",
    prompt_en: "What did you watch last night?",
    prompt_ja: "昨日の夜何を見ましたか？",
    example_kr: "우리는 어제 영화를 보았어요.",
    example_en: "We watched a movie last night.",
    example_ja: "私たちは昨日映画を見ました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "아침에 공원에서 무엇을 했어요?",
    prompt_en: "What did you do in the park in the morning?",
    prompt_ja: "朝公園で何をしましたか？",
    example_kr: "저는 아침에 운동을 했어요.",
    example_en: "I exercised in the morning.",
    example_ja: "私は朝運動をしました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 저녁에 누구에게 전화를 걸었어요?",
    prompt_en: "Who did you call yesterday evening?",
    prompt_ja: "昨日の夕方誰に電話をかけましたか？",
    example_kr: "나는 어제 어머니께 전화했어요.",
    example_en: "I called my mother yesterday.",
    example_ja: "私は昨日母に電話しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 무엇을 배웠어요?",
    prompt_en: "What did you learn last week?",
    prompt_ja: "先週何を習いましたか？",
    example_kr: "저는 지난주에 한국어를 배웠어요.",
    example_en: "I learned Korean last week.",
    example_ja: "私は先週韓国語を習いました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 집에서 무엇을 만들었어요?",
    prompt_en: "What did you make at home yesterday?",
    prompt_ja: "昨日家で何を作りましたか？",
    example_kr: "나는 어제 요리를 만들었어요.",
    example_en: "I cooked food yesterday.",
    example_ja: "私は昨日料理を作りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 시장에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the market yesterday?",
    prompt_ja: "昨日市場で何を買いましたか？",
    example_kr: "우리는 어제 과일을 샀어요.",
    example_en: "We bought fruit yesterday.",
    example_ja: "私たちは昨日果物を買いました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 학교에서 누구를 가르쳤어요?",
    prompt_en: "Who did you teach at school yesterday?",
    prompt_ja: "昨日学校で誰を教えましたか？",
    example_kr: "나는 어제 아이를 가르쳤어요.",
    example_en: "I taught a child yesterday.",
    example_ja: "私は昨日子供を教えました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난달에 무엇을 공부했어요?",
    prompt_en: "What did you study last month?",
    prompt_ja: "先月何を勉強しましたか？",
    example_kr: "저는 지난달에 영어를 공부했어요.",
    example_en: "I studied English last month.",
    example_ja: "私は先月英語を勉強しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 밤에 음악을 들었어요?",
    prompt_en: "Did you listen to music last night?",
    prompt_ja: "昨日の夜音楽を聞きましたか？",
    example_kr: "저는 어제 음악을 들었어요.",
    example_en: "I listened to music yesterday.",
    example_ja: "私は昨日音楽を聞きました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 휴일에 무엇을 쉬었어요?",
    prompt_en: "What did you rest on your holiday yesterday?",
    prompt_ja: "昨日の休日はどうやって休みましたか？",
    example_kr: "나는 어제 집에서 쉬었어요.",
    example_en: "I rested at home yesterday.",
    example_ja: "私は昨日家で休みました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 식당에서 무엇을 주문했어요?",
    prompt_en: "What did you order at the restaurant yesterday?",
    prompt_ja: "昨日食堂で何を注文しましたか？",
    example_kr: "우리는 어제 김밥을 주문했어요.",
    example_en: "We ordered kimbap yesterday.",
    example_ja: "私たちは昨日キンパを注文しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 교실에서 무엇을 적었어요?",
    prompt_en: "What did you write in the classroom yesterday?",
    prompt_ja: "昨日教室で何を書きましたか？",
    example_kr: "나는 어제 편지를 적었어요.",
    example_en: "I wrote a letter yesterday.",
    example_ja: "私は昨日手紙を書きました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 미술관에서 무엇을 보았어요?",
    prompt_en: "What did you see at the art gallery last week?",
    prompt_ja: "先週美術館で何を見ましたか？",
    example_kr: "나는 지난주에 그림을 보았어요.",
    example_en: "I saw a painting last week.",
    example_ja: "私は先週絵を見ました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 우체국에서 무엇을 부쳤어요?",
    prompt_en: "What did you mail at the post office yesterday?",
    prompt_ja: "昨日郵便局で何を送りましたか？",
    example_kr: "나는 어제 소포를 부쳤어요.",
    example_en: "I mailed a parcel yesterday.",
    example_ja: "私は昨日小包を送りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 은행에서 무엇을 찾았어요?",
    prompt_en: "What did you withdraw at the bank yesterday?",
    prompt_ja: "昨日銀行で何を引き出しましたか？",
    example_kr: "저는 어제 돈을 찾았어요.",
    example_en: "I withdrew money yesterday.",
    example_ja: "私は昨日お金を引き出しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 카페에서 무엇을 주문했어요?",
    prompt_en: "What did you order at the cafe yesterday?",
    prompt_ja: "昨日カフェで何を注文しましたか？",
    example_kr: "나는 어제 커피를 주문했어요.",
    example_en: "I ordered coffee yesterday.",
    example_ja: "私は昨日コーヒーを注文しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 병원에서 무엇을 치료했어요?",
    prompt_en: "What did you treat at the hospital yesterday?",
    prompt_ja: "昨日病院で何を治療しましたか？",
    example_kr: "저는 어제 감기를 치료했어요.",
    example_en: "I treated a cold yesterday.",
    example_ja: "私は昨日風邪を治療しました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 약국에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the pharmacy yesterday?",
    prompt_ja: "昨日薬局で何を買いましたか？",
    example_kr: "나는 어제 약을 샀어요.",
    example_en: "I bought medicine yesterday.",
    example_ja: "私は昨日薬を買いました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 산에서 무엇을 했어요?",
    prompt_en: "What did you do on the mountain yesterday?",
    prompt_ja: "昨日山で何をしましたか？",
    example_kr: "우리는 어제 산을 올랐어요.",
    example_en: "We climbed the mountain yesterday.",
    example_ja: "私たちは昨日山に登りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 강가에서 무엇을 잡았어요?",
    prompt_en: "What did you catch by the river yesterday?",
    prompt_ja: "昨日川辺で何を捕まえましたか？",
    example_kr: "나는 어제 고기를 잡았어요.",
    example_en: "I caught fish yesterday.",
    example_ja: "私は昨日魚を捕まえました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 극장에서 무엇을 보았어요?",
    prompt_en: "What did you watch at the theater yesterday?",
    prompt_ja: "昨日劇場で何を見ましたか？",
    example_kr: "우리는 어제 연극을 보았어요.",
    example_en: "We watched a play yesterday.",
    example_ja: "私たちは昨日演劇を見ました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 콘서트에서 무엇을 불렀어요?",
    prompt_en: "What did you sing at the concert yesterday?",
    prompt_ja: "昨日コンサートで何を歌いましたか？",
    example_kr: "나는 어제 노래를 불렀어요.",
    example_en: "I sang a song yesterday.",
    example_ja: "私は昨日歌を歌いました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 운동장에서 무엇을 찼어요?",
    prompt_en: "What did you kick on the playground yesterday?",
    prompt_ja: "昨日運動場で何を蹴りましたか？",
    example_kr: "우리는 어제 공을 찼어요.",
    example_en: "We kicked a ball yesterday.",
    example_ja: "私たちは昨日ボールを蹴りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 수영장에서 무엇을 했어요?",
    prompt_en: "What did you do at the swimming pool yesterday?",
    prompt_ja: "昨日プールで何をしましたか？",
    example_kr: "나는 어제 수영을 했어요.",
    example_en: "I swam yesterday.",
    example_ja: "私は昨日水泳をしました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 놀이공원에서 무엇을 탔어요?",
    prompt_en: "What did you ride at the amusement park yesterday?",
    prompt_ja: "昨日遊園地で何に乗りましたか？",
    example_kr: "우리는 어제 버스를 탔어요.",
    example_en: "We rode a bus yesterday.",
    example_ja: "私たちは昨日バスに乗りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 동물원에서 무엇을 보았어요?",
    prompt_en: "What did you see at the zoo yesterday?",
    prompt_ja: "昨日動物園で何を見ましたか？",
    example_kr: "나는 어제 호랑이를 보았어요.",
    example_en: "I saw a tiger yesterday.",
    example_ja: "私は昨日トラを見ました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 사진관에서 무엇을 찍었어요?",
    prompt_en: "What did you take at the photo studio yesterday?",
    prompt_ja: "昨日写真館で何を撮りましたか？",
    example_kr: "나는 어제 사진을 찍었어요.",
    example_en: "I took a picture yesterday.",
    example_ja: "私は昨日写真を撮りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 미용실에서 무엇을 잘랐어요?",
    prompt_en: "What did you cut at the hair salon yesterday?",
    prompt_ja: "昨日美容室で何を切りましたか？",
    example_kr: "나는 어제 머리를 잘랐어요.",
    example_en: "I cut my hair yesterday.",
    example_ja: "私は昨日髪を切りました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 세탁소에서 무엇을 맡겼어요?",
    prompt_en: "What did you drop off at the laundry yesterday?",
    prompt_ja: "昨日クリーニング店で何を預けましたか？",
    example_kr: "나는 어제 옷을 맡겼어요.",
    example_en: "I dropped off clothes yesterday.",
    example_ja: "私は昨日服を預けました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 서점에서 무엇을 골랐어요?",
    prompt_en: "What did you pick at the bookstore yesterday?",
    prompt_ja: "昨日書店で何を選びましたか？",
    example_kr: "나는 어제 잡지를 골랐어요.",
    example_en: "I picked a magazine yesterday.",
    example_ja: "私は昨日雑誌を選びました。",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 주유소에서 무엇을 넣었어요?",
    prompt_en: "What did you put in at the gas station yesterday?",
    prompt_ja: "昨日ガソリンスタンドで何を入れましたか？",
    example_kr: "나는 어제 기름을 넣었어요.",
    example_en: "I put gas yesterday.",
    example_ja: "私は昨日ガソリンを入れました。",
  },
];
