import type { RawPrompt } from "./types";

export const WRITING_A2_DESCRIPTION: RawPrompt[] = [
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 어디에 갔어요?",
    prompt_en: "Where did you go yesterday?",
    example_kr: "저는 어제 바다에 갔어요.",
    example_en: "I went to the sea yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 무엇을 먹었어요?",
    prompt_en: "What did you eat last week?",
    example_kr: "우리는 지난주에 빵을 먹었어요.",
    example_en: "We ate bread last week.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "아침에 무엇을 마셨어요?",
    prompt_en: "What did you drink in the morning?",
    example_kr: "저는 아침에 차를 마셨어요.",
    example_en: "I drank tea in the morning.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 누구를 만났어요?",
    prompt_en: "Who did you meet yesterday?",
    example_kr: "나는 어제 친구를 만났어요.",
    example_en: "I met a friend yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "작년에 어디에서 살았어요?",
    prompt_en: "Where did you live last year?",
    example_kr: "저는 작년에 서울에 살았었어요.",
    example_en: "I lived in Seoul last year.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 도서관에서 무엇을 했어요?",
    prompt_en: "What did you do at the library yesterday?",
    example_kr: "저는 어제 책을 읽었어요.",
    example_en: "I read a book yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 방에서 무엇을 했어요?",
    prompt_en: "What did you do in your room last week?",
    example_kr: "나는 지난주에 방을 청소했어요.",
    example_en: "I cleaned my room last week.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 백화점에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the department store yesterday?",
    example_kr: "저는 어제 구두를 샀어요.",
    example_en: "I bought shoes yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 밤에 무엇을 보았어요?",
    prompt_en: "What did you watch last night?",
    example_kr: "우리는 어제 영화를 보았어요.",
    example_en: "We watched a movie last night.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "아침에 공원에서 무엇을 했어요?",
    prompt_en: "What did you do in the park in the morning?",
    example_kr: "저는 아침에 운동을 했어요.",
    example_en: "I exercised in the morning.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 저녁에 누구에게 전화를 걸었어요?",
    prompt_en: "Who did you call yesterday evening?",
    example_kr: "나는 어제 어머니께 전화했어요.",
    example_en: "I called my mother yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 무엇을 배웠어요?",
    prompt_en: "What did you learn last week?",
    example_kr: "저는 지난주에 한국어를 배웠어요.",
    example_en: "I learned Korean last week.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 집에서 무엇을 만들었어요?",
    prompt_en: "What did you make at home yesterday?",
    example_kr: "나는 어제 요리를 만들었어요.",
    example_en: "I cooked food yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 시장에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the market yesterday?",
    example_kr: "우리는 어제 과일을 샀어요.",
    example_en: "We bought fruit yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 학교에서 누구를 가르쳤어요?",
    prompt_en: "Who did you teach at school yesterday?",
    example_kr: "나는 어제 아이를 가르쳤어요.",
    example_en: "I taught a child yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난달에 무엇을 공부했어요?",
    prompt_en: "What did you study last month?",
    example_kr: "저는 지난달에 영어를 공부했어요.",
    example_en: "I studied English last month.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 밤에 음악을 들었어요?",
    prompt_en: "Did you listen to music last night?",
    example_kr: "저는 어제 음악을 들었어요.",
    example_en: "I listened to music yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 휴일에 무엇을 쉬었어요?",
    prompt_en: "What did you rest on your holiday yesterday?",
    example_kr: "나는 어제 집에서 쉬었어요.",
    example_en: "I rested at home yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 식당에서 무엇을 주문했어요?",
    prompt_en: "What did you order at the restaurant yesterday?",
    example_kr: "우리는 어제 김밥을 주문했어요.",
    example_en: "We ordered kimbap yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 교실에서 무엇을 적었어요?",
    prompt_en: "What did you write in the classroom yesterday?",
    example_kr: "나는 어제 편지를 적었어요.",
    example_en: "I wrote a letter yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "지난주에 미술관에서 무엇을 보았어요?",
    prompt_en: "What did you see at the art gallery last week?",
    example_kr: "나는 지난주에 그림을 보았어요.",
    example_en: "I saw a painting last week.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 우체국에서 무엇을 부쳤어요?",
    prompt_en: "What did you mail at the post office yesterday?",
    example_kr: "나는 어제 소포를 부쳤어요.",
    example_en: "I mailed a parcel yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 은행에서 무엇을 찾았어요?",
    prompt_en: "What did you withdraw at the bank yesterday?",
    example_kr: "저는 어제 돈을 찾았어요.",
    example_en: "I withdrew money yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 카페에서 무엇을 주문했어요?",
    prompt_en: "What did you order at the cafe yesterday?",
    example_kr: "나는 어제 커피를 주문했어요.",
    example_en: "I ordered coffee yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 병원에서 무엇을 치료했어요?",
    prompt_en: "What did you treat at the hospital yesterday?",
    example_kr: "저는 어제 감기를 치료했어요.",
    example_en: "I treated a cold yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 약국에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the pharmacy yesterday?",
    example_kr: "나는 어제 약을 샀어요.",
    example_en: "I bought medicine yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 산에서 무엇을 했어요?",
    prompt_en: "What did you do on the mountain yesterday?",
    example_kr: "우리는 어제 산을 올랐어요.",
    example_en: "We climbed the mountain yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 강가에서 무엇을 잡았어요?",
    prompt_en: "What did you catch by the river yesterday?",
    example_kr: "나는 어제 고기를 잡았어요.",
    example_en: "I caught fish yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 극장에서 무엇을 보았어요?",
    prompt_en: "What did you watch at the theater yesterday?",
    example_kr: "우리는 어제 연극을 보았어요.",
    example_en: "We watched a play yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 콘서트에서 무엇을 불렀어요?",
    prompt_en: "What did you sing at the concert yesterday?",
    example_kr: "나는 어제 노래를 불렀어요.",
    example_en: "I sang a song yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 운동장에서 무엇을 찼어요?",
    prompt_en: "What did you kick on the playground yesterday?",
    example_kr: "우리는 어제 공을 찼어요.",
    example_en: "We kicked a ball yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 수영장에서 무엇을 했어요?",
    prompt_en: "What did you do at the swimming pool yesterday?",
    example_kr: "나는 어제 수영을 했어요.",
    example_en: "I swam yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 놀이공원에서 무엇을 탔어요?",
    prompt_en: "What did you ride at the amusement park yesterday?",
    example_kr: "우리는 어제 버스를 탔어요.",
    example_en: "We rode a bus yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 동물원에서 무엇을 보았어요?",
    prompt_en: "What did you see at the zoo yesterday?",
    example_kr: "나는 어제 호랑이를 보았어요.",
    example_en: "I saw a tiger yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 사진관에서 무엇을 찍었어요?",
    prompt_en: "What did you take at the photo studio yesterday?",
    example_kr: "나는 어제 사진을 찍었어요.",
    example_en: "I took a picture yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 미용실에서 무엇을 잘랐어요?",
    prompt_en: "What did you cut at the hair salon yesterday?",
    example_kr: "나는 어제 머리를 잘랐어요.",
    example_en: "I cut my hair yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 세탁소에서 무엇을 맡겼어요?",
    prompt_en: "What did you drop off at the laundry yesterday?",
    example_kr: "나는 어제 옷을 맡겼어요.",
    example_en: "I dropped off clothes yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 서점에서 무엇을 골랐어요?",
    prompt_en: "What did you pick at the bookstore yesterday?",
    example_kr: "나는 어제 잡지를 골랐어요.",
    example_en: "I picked a magazine yesterday.",
  },
  {
    level: "A2",
    genre: "description",
    prompt_kr: "어제 주유소에서 무엇을 넣었어요?",
    prompt_en: "What did you put in at the gas station yesterday?",
    example_kr: "나는 어제 기름을 넣었어요.",
    example_en: "I put gas yesterday.",
  },
];
