import type { RawPrompt } from "./types";

export const WRITING_A2_JOURNAL: RawPrompt[] = [
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 아침에 있었던 일을 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about something that happened this morning.",
    example_kr: "오늘 아침에 늦게 일어나서 서둘렀어요. 아침을 못 먹고 집을 나왔어요. 다행히 버스는 늦지 않게 탔어요. 회사에 도착하니까 마음이 좀 놓였어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 주말 계획을 '-을 거예요'를 사용해서 쓰세요.",
    prompt_en: "Write about your plans for this weekend using '-을 거예요'.",
    example_kr: "이번 주말에는 오랜만에 등산을 갈 거예요. 아침 일찍 출발할 거예요. 산 정상에서 도시락을 먹을 거예요. 저녁에는 집에서 푹 쉴 거예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 새로 시작한 일을 '-기 시작했어요'를 사용해서 쓰세요.",
    prompt_en: "Write about something you started doing last month, using '-기 시작했어요'.",
    example_kr: "지난달부터 아침마다 조깅을 하기 시작했어요. 처음에는 십 분도 힘들었어요. 요즘은 삼십 분씩 뛰기 시작했어요. 몸이 조금씩 가벼워지는 것 같아요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 기분이 어땠는지 이유와 함께 '-아서/어서'를 사용해서 쓰세요.",
    prompt_en: "Write about how you felt today and why, using '-아서/어서'.",
    example_kr: "오늘은 회의가 잘 끝나서 기분이 좋았어요. 팀장님이 칭찬해 줘서 더 뿌듯했어요. 그런데 저녁에 비가 와서 조금 우울했어요. 그래도 전체적으로 좋은 하루였어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 자주 만나는 사람에 대해 쓰세요. 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about someone you've been seeing often lately.",
    example_kr: "요즘 회사 근처 카페에서 같은 직원을 자주 만나요. 서로 인사를 하다가 이제는 이야기도 나눠요. 그 사람은 항상 웃으면서 인사해요. 다음에는 이름도 물어보고 싶어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난 휴일에 집에서 무엇을 했는지 '-으면서'를 사용해서 쓰세요.",
    prompt_en: "Write about what you did at home last holiday, using '-으면서'.",
    example_kr: "지난 휴일에는 음악을 들으면서 방을 청소했어요. 청소하면서 오래된 사진도 정리했어요. 저녁에는 영화를 보면서 라면을 먹었어요. 조용하지만 편안한 하루였어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 걱정하는 일을 '-을까 봐'를 사용해서 쓰세요.",
    prompt_en: "Write about something you've been worried about, using '-을까 봐'.",
    example_kr: "요즘 시험을 못 볼까 봐 걱정이에요. 매일 늦게까지 공부해요. 그래도 잊어버릴까 봐 계속 복습해요. 시험이 끝나면 마음이 편해질 것 같아요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 달에 가장 즐거웠던 일을 쓰세요. '-어서 좋았어요'를 사용해서 3-5문장으로 쓰세요.",
    prompt_en: "Write about the most enjoyable thing that happened this month, using '-어서 좋았어요'.",
    example_kr: "이번 달에는 오랜만에 고향 친구를 만나서 정말 좋았어요. 같이 옛날 이야기를 해서 재미있었어요. 맛있는 음식도 많이 먹어서 행복했어요. 다음 달에도 또 만나고 싶어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 배운 새로운 것을 '-게 됐어요'를 사용해서 쓰세요.",
    prompt_en: "Write about something new you learned today, using '-게 됐어요'.",
    example_kr: "오늘 요리 수업에서 김치찌개 끓이는 법을 배우게 됐어요. 처음에는 순서가 헷갈렸어요. 선생님이 설명해 주셔서 알게 됐어요. 집에서도 한번 만들어 보고 싶어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 저녁 식사에 대해 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about what you had for dinner last night.",
    example_kr: "어제 저녁에는 집에서 볶음밥을 만들어 먹었어요. 냉장고에 있는 야채를 다 넣었어요. 생각보다 맛있어서 놀랐어요. 다음에도 또 만들어 먹을 거예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 주에 힘들었던 일을 '-는 게 힘들었어요'를 사용해서 쓰세요.",
    prompt_en: "Write about something difficult this week, using '-는 게 힘들었어요'.",
    example_kr: "이번 주에는 매일 야근하는 게 힘들었어요. 집에 늦게 가서 잠도 부족했어요. 그래도 프로젝트를 끝내는 게 힘들었지만 뿌듯했어요. 주말에는 푹 쉴 거예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 관심이 생긴 것을 '-에 관심이 생겼어요'를 사용해서 쓰세요.",
    prompt_en: "Write about something you've become interested in lately, using '-에 관심이 생겼어요'.",
    example_kr: "요즘 식물 키우기에 관심이 생겼어요. 친구 집에서 예쁜 화분을 보고 시작했어요. 매일 물을 주면서 관찰해요. 곧 꽃이 필 것 같아서 기대돼요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "다음 주 계획 중 기대되는 일을 '-을 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "Write about something you're looking forward to next week, using '-을 것 같아요'.",
    example_kr: "다음 주에 새로운 팀 프로젝트가 시작될 것 같아요. 조금 긴장되지만 재미있을 것 같아요. 새로운 동료들과도 친해질 것 같아요. 벌써 기대가 돼요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 저녁 산책에 대해 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about a walk you took this evening.",
    example_kr: "오늘 저녁에 동네를 한 바퀴 산책했어요. 바람이 시원해서 기분이 좋았어요. 공원에서 강아지들도 많이 봤어요. 산책 덕분에 하루의 피로가 풀렸어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 자주 듣는 노래에 대해 '-을 때마다'를 사용해서 쓰세요.",
    prompt_en: "Write about a song you listen to a lot these days, using '-을 때마다'.",
    example_kr: "요즘 한 노래를 자주 들어요. 그 노래를 들을 때마다 기분이 좋아져요. 출근할 때마다 이 노래로 하루를 시작해요. 친구에게도 추천해 줬어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 달 목표를 '-으려고 해요'를 사용해서 쓰세요.",
    prompt_en: "Write about a goal for this month, using '-으려고 해요'.",
    example_kr: "이번 달에는 책을 두 권 읽으려고 해요. 자기 전에 삼십 분씩 읽으려고 해요. 물도 더 많이 마시려고 해요. 작은 목표지만 꾸준히 지키고 싶어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 아침에 먹은 것을 '-으니까'를 사용해서 쓰세요.",
    prompt_en: "Write about what you ate this morning, using '-으니까' to explain a reason or result.",
    example_kr: "시간이 없으니까 오늘 아침은 토스트만 먹었어요. 배가 고프니까 커피도 같이 마셨어요. 간단히 먹으니까 준비가 빨랐어요. 그래도 든든한 느낌은 없었어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "최근에 산 물건에 대해 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about something you recently bought.",
    example_kr: "지난주에 새 운동화를 샀어요. 온라인으로 주문했는데 색이 마음에 들었어요. 신어 보니까 편해서 자주 신어요. 다음에는 운동복도 사고 싶어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 잠을 잘 자는지 '-는 편이에요'를 사용해서 쓰세요.",
    prompt_en: "Write about whether you're sleeping well these days, using '-는 편이에요'.",
    example_kr: "요즘 저는 잠을 잘 자는 편이에요. 일찍 자려고 노력하고 있어요. 가끔 늦게까지 휴대폰을 보긴 하지만 대부분 잘 자요. 앞으로도 좋은 습관을 지킬 거예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난 주말에 가족과 보낸 시간을 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about time you spent with family last weekend.",
    example_kr: "지난 주말에는 부모님 댁에 갔어요. 같이 저녁을 만들어 먹었어요. 오랜만에 다 같이 이야기를 많이 했어요. 다음 달에도 또 갈 계획이에요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 스트레스를 어떻게 푸는지 '-으로 스트레스를 풀어요'를 사용해서 쓰세요.",
    prompt_en: "Write about how you relieve stress these days, using '-으로 스트레스를 풀어요'.",
    example_kr: "저는 요즘 운동으로 스트레스를 풀어요. 특히 수영을 하면 기분이 좋아져요. 가끔 친구와 수다를 떨면서도 스트레스를 풀어요. 앞으로도 이 방법을 계속 쓸 거예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 주에 새로 알게 된 사람을 '-게 됐어요'를 사용해서 쓰세요.",
    prompt_en: "Write about someone you got to know this week, using '-게 됐어요'.",
    example_kr: "이번 주에 새로 이사 온 이웃과 인사하게 됐어요. 우연히 엘리베이터에서 만났어요. 이야기를 나누다가 친해지게 됐어요. 다음에 같이 커피를 마시기로 했어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 하루를 세 단어로 표현하고 이유를 설명해 보세요. 3-5문장으로 쓰세요.",
    prompt_en: "Describe your day in three words and explain why. Write 3-5 sentences.",
    example_kr: "오늘 하루는 바쁘고, 피곤하고, 뿌듯했어요. 아침부터 회의가 많아서 바빴어요. 저녁까지 일해서 피곤했어요. 그래도 일을 다 끝내서 뿌듯했어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 달에 후회한 일이 있는지 '-을 걸 그랬어요'를 사용해서 쓰세요.",
    prompt_en: "Write about something you regret this month, using '-을 걸 그랬어요'.",
    example_kr: "이번 달에는 운동을 더 열심히 할 걸 그랬어요. 계획만 세우고 실천을 못 했어요. 일찍 잘 걸 그랬어요. 다음 달에는 꼭 지킬 거예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난 여행에서 산 기념품에 대해 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about a souvenir you bought on a recent trip.",
    example_kr: "지난 여행에서 작은 열쇠고리를 샀어요. 시장에서 우연히 발견했어요. 여행지의 그림이 그려져 있어서 마음에 들었어요. 지금도 가방에 달고 다녀요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 자주 요리하는 음식에 대해 '-을 줄 알아요'를 사용해서 쓰세요.",
    prompt_en: "Write about a dish you often cook these days, using '-을 줄 알아요'.",
    example_kr: "요즘 된장찌개를 자주 만들어요. 저는 이제 된장찌개를 끓일 줄 알아요. 처음에는 간을 맞출 줄 몰랐어요. 이제는 자신 있게 만들 수 있어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 회사나 학교에서 있었던 재미있는 일을 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about something funny that happened at work or school today.",
    example_kr: "오늘 동료가 회의 중에 실수로 커피를 쏟았어요. 다들 웃으면서 같이 닦아 줬어요. 분위기가 갑자기 편해졌어요. 오늘 하루가 덜 지루하게 느껴졌어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 시간이 나면 무엇을 하는지 '-을 때마다'를 사용해서 쓰세요.",
    prompt_en: "Write about what you do whenever you have free time, using '-을 때마다'.",
    example_kr: "저는 시간이 날 때마다 그림을 그려요. 스트레스를 받을 때마다 그림이 도움이 돼요. 주말에 시간이 많을 때마다 두세 시간씩 그려요. 언젠가 전시회도 열고 싶어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 실수한 일과 거기서 배운 점을 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about a mistake you made last week and what you learned from it.",
    example_kr: "지난주에 회의 시간을 착각해서 늦게 갔어요. 팀원들에게 미안했어요. 그 후로는 일정을 항상 두 번 확인해요. 작은 실수였지만 좋은 습관이 생겼어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 건강을 위해 하는 일을 '-도록 노력해요'를 사용해서 쓰세요.",
    prompt_en: "Write about what you do for your health these days, using '-도록 노력해요'.",
    example_kr: "요즘 채소를 많이 먹도록 노력해요. 물도 하루에 여덟 잔 마시도록 노력해요. 밤에 늦게 자지 않도록 노력해요. 조금씩 습관이 자리 잡는 것 같아요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 주에 본 영화나 드라마에 대해 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about a movie or show you watched this week.",
    example_kr: "이번 주에 새로 나온 드라마를 봤어요. 이야기가 흥미로워서 밤새 봤어요. 배우들의 연기도 정말 좋았어요. 다음 편이 벌써 기다려져요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 누군가에게 고마웠던 순간을 '-어서 고마웠어요'를 사용해서 쓰세요.",
    prompt_en: "Write about a moment today you felt thankful to someone, using '-어서 고마웠어요'.",
    example_kr: "오늘 동료가 제 일을 도와줘서 고마웠어요. 바쁠 때 먼저 물어봐 줘서 더 고마웠어요. 저녁에 감사 인사를 문자로 보냈어요. 작은 도움이지만 큰 힘이 됐어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 달에 새로 알게 된 정보를 '-다는 걸 알게 됐어요'를 사용해서 쓰세요.",
    prompt_en: "Write about something new you learned this month, using '-다는 걸 알게 됐어요'.",
    example_kr: "이번 달에 근처에 새 도서관이 생겼다는 걸 알게 됐어요. 뉴스에서 보고 알게 됐어요. 조용해서 공부하기 좋다는 걸 알게 됐어요. 이번 주말에 가 보려고 해요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 날씨와 그에 따른 기분을 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about today's weather and how it affected your mood.",
    example_kr: "오늘은 하늘이 맑고 바람이 시원했어요. 그래서 아침부터 기분이 좋았어요. 점심에 밖에서 산책도 했어요. 이런 날씨가 계속되면 좋겠어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 자기 전에 하는 습관을 '-기 전에'를 사용해서 쓰세요.",
    prompt_en: "Write about a habit you have before going to sleep, using '-기 전에'.",
    example_kr: "저는 자기 전에 항상 일기를 써요. 불을 끄기 전에 창문도 닫아요. 눕기 전에 휴대폰을 멀리 둬요. 이렇게 하니까 더 잘 자는 것 같아요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 주에 새로 발견한 맛집에 대해 3-5문장으로 쓰세요.",
    prompt_en: "Write 3-5 sentences about a new restaurant you discovered this week.",
    example_kr: "이번 주에 회사 근처에서 작은 국밥집을 발견했어요. 우연히 지나가다가 들어가 봤어요. 국물이 진하고 맛있었어요. 앞으로 자주 갈 것 같아요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "요즘 가장 기다려지는 일을 '-이/가 기다려져요'를 사용해서 쓰세요.",
    prompt_en: "Write about what you're most looking forward to these days, using '-이/가 기다려져요'.",
    example_kr: "요즘 다음 달 여행이 정말 기다려져요. 비행기표는 이미 예매했어요. 친구와의 재회도 기다려져요. 남은 날짜를 매일 세고 있어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달과 비교해서 요즘 달라진 점을 '-보다'를 사용해서 쓰세요.",
    prompt_en: "Write about how things are different now compared to last month, using '-보다'.",
    example_kr: "지난달보다 요즘 일이 더 바빠졌어요. 그래도 지난달보다 운동은 더 규칙적으로 해요. 잠도 예전보다 조금 더 잘 자요. 전체적으로 나쁘지 않은 변화예요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "오늘 퇴근 후에 한 일을 '-고 나서'를 사용해서 3-5문장으로 쓰세요.",
    prompt_en: "Write about what you did after work today, using '-고 나서'.",
    example_kr: "오늘은 퇴근하고 나서 바로 집에 왔어요. 샤워를 하고 나서 간단하게 저녁을 만들었어요. 밥을 먹고 나서 친구하고 전화를 했어요. 조용하지만 편한 저녁이었어요.",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "이번 달에 돈을 아끼려고 한 일을 '-기 위해서'를 사용해서 3-5문장으로 쓰세요.",
    prompt_en: "Write about something you did this month to save money, using '-기 위해서'.",
    example_kr: "이번 달에는 돈을 아끼기 위해서 커피를 집에서 만들었어요. 점심도 도시락을 싸기 위해서 아침에 조금 일찍 일어났어요. 생각보다 돈이 많이 남아서 기분이 좋았어요. 다음 달에도 계속 해 볼 거예요.",
  },
];
