import type { RawPrompt } from "./types";

export const WRITING_A2_JOURNAL: RawPrompt[] = [
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 바다에 갔어요.",
    example_en: "I went to the beach last month.",
    example_ja: "私は先月海に行きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 시장에 갔어요.",
    example_en: "I went to the market last year.",
    example_ja: "私は去年市場に行きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 자전거를 탔어요.",
    example_en: "I rode a bike last week.",
    example_ja: "私は先週自転車に乗りました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 쇼핑을 했어요.",
    example_en: "I went shopping yesterday.",
    example_ja: "私は昨日買い物をしました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 음악을 들었어요.",
    example_en: "I listened to music a little while ago.",
    example_ja: "私はさっき音楽を聞きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 강아지를 산책시켰어요.",
    example_en: "I walked the dog last month.",
    example_ja: "私は先月犬を散歩させました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 산에 갔어요.",
    example_en: "I went to the mountain last year.",
    example_ja: "私は去年山に行きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 요리를 했어요.",
    example_en: "I cooked last week.",
    example_ja: "私は先週料理をしました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 늦게까지 일했어요.",
    example_en: "I worked late yesterday.",
    example_ja: "私は昨日遅くまで働きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 게임을 했어요.",
    example_en: "I played a game a little while ago.",
    example_ja: "私はさっきゲームをしました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 떡볶이를 먹었어요.",
    example_en: "I ate tteokbokki last month.",
    example_ja: "私は先月トッポギを食べました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 커피숍에 갔어요.",
    example_en: "I went to a coffee shop last year.",
    example_ja: "私は去年カフェに行きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 일찍 일어났어요.",
    example_en: "I woke up early last week.",
    example_ja: "私は先週早く起きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 책을 읽었어요.",
    example_en: "I read a book yesterday.",
    example_ja: "私は昨日本を読みました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 이메일을 보냈어요.",
    example_en: "I sent an email a little while ago.",
    example_ja: "私はさっきメールを送りました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 회의를 했어요.",
    example_en: "I had a meeting last month.",
    example_ja: "私は先月会議をしました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 청소를 했어요.",
    example_en: "I cleaned last year.",
    example_ja: "私は去年掃除をしました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 영화관에 갔어요.",
    example_en: "I went to the movie theater last week.",
    example_ja: "私は先週映画館に行きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 드라마를 봤어요.",
    example_en: "I watched a drama yesterday.",
    example_ja: "私は昨日ドラマを見ました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 빵을 먹었어요.",
    example_en: "I ate bread a little while ago.",
    example_ja: "私はさっきパンを食べました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 커피를 내렸어요.",
    example_en: "I brewed coffee last month.",
    example_ja: "私は先月コーヒーを淹れました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 사진을 찍었어요.",
    example_en: "I took photos last year.",
    example_ja: "私は去年写真を撮りました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 아이스크림을 먹었어요.",
    example_en: "I ate ice cream last week.",
    example_ja: "私は先週アイスクリームを食べました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 방을 정리했어요.",
    example_en: "I tidied my room yesterday.",
    example_ja: "私は昨日部屋を片付けました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 부모님과 통화했어요.",
    example_en: "I talked with my parents on the phone a little while ago.",
    example_ja: "私はさっき両親と電話しました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 김치찌개를 만들었어요.",
    example_en: "I made kimchi stew last month.",
    example_ja: "私は先月キムチチゲを作りました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 일찍 잤어요.",
    example_en: "I went to bed early last year.",
    example_ja: "私は去年早く寝ました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 과일을 샀어요.",
    example_en: "I bought fruit last week.",
    example_ja: "私は先週果物を買いました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 도서관에 갔어요.",
    example_en: "I went to the library yesterday.",
    example_ja: "私は昨日図書館に行きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 새 신발을 샀어요.",
    example_en: "I bought new shoes a little while ago.",
    example_ja: "私はさっき新しい靴を買いました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 고양이 밥을 줬어요.",
    example_en: "I fed the cat last month.",
    example_ja: "私は先月猫にご飯をあげました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 숙제를 했어요.",
    example_en: "I did homework last year.",
    example_ja: "私は去年宿題をしました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 삼겹살을 먹었어요.",
    example_en: "I ate samgyeopsal last week.",
    example_ja: "私は先週サムギョプサルを食べました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 빵을 구웠어요.",
    example_en: "I baked bread yesterday.",
    example_ja: "私は昨日パンを焼きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "아까 뭐 했어요?",
    prompt_en: "What did you do a little while ago?",
    prompt_ja: "さっき何をしましたか？",
    example_kr: "저는 아까 편지를 썼어요.",
    example_en: "I wrote a letter a little while ago.",
    example_ja: "私はさっき手紙を書きました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난달에 뭐 했어요?",
    prompt_en: "What did you do last month?",
    prompt_ja: "先月何をしましたか？",
    example_kr: "저는 지난달에 친구랑 통화했어요.",
    example_en: "I talked with a friend on the phone last month.",
    example_ja: "私は先月友達と電話しました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "작년에 뭐 했어요?",
    prompt_en: "What did you do last year?",
    prompt_ja: "去年何をしましたか？",
    example_kr: "저는 작년에 화분에 물을 줬어요.",
    example_en: "I watered the plants last year.",
    example_ja: "私は去年鉢植えに水をあげました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "지난주에 뭐 했어요?",
    prompt_en: "What did you do last week?",
    prompt_ja: "先週何をしましたか？",
    example_kr: "저는 지난주에 영화를 봤어요.",
    example_en: "I watched a movie last week.",
    example_ja: "私は先週映画を見ました。",
  },
  {
    level: "A2",
    genre: "journal",
    prompt_kr: "어제 뭐 했어요?",
    prompt_en: "What did you do yesterday?",
    prompt_ja: "昨日何をしましたか？",
    example_kr: "저는 어제 친구 집에 갔어요.",
    example_en: "I went to a friend's house yesterday.",
    example_ja: "私は昨日友達の家に行きました。",
  },
];
