import type { RawPrompt } from "./types";

export const WRITING_A2_OPINION: RawPrompt[] = [
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "커피와 차 중에서 무엇을 더 좋아해요? '-는 게 더 좋아요'를 사용해서 2-3문장으로 쓰세요.",
    prompt_en: "Which do you prefer, coffee or tea? Write 2-3 sentences using '-는 게 더 좋아요'.",
    example_kr: "저는 차를 마시는 게 더 좋아요. 커피는 마시면 밤에 잠을 잘 못 자요. 그래서 저녁에는 항상 차를 마셔요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "여름과 겨울 중에서 어느 계절이 더 좋아요? 이유를 '-기 때문에'로 설명해 보세요.",
    prompt_en: "Which season do you prefer, summer or winter? Explain your reason using '-기 때문에'.",
    example_kr: "저는 겨울이 더 좋아요. 눈을 볼 수 있기 때문이에요. 따뜻한 옷을 입는 것도 좋아하기 때문에 겨울을 기다려요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "혼자 여행하는 것과 같이 여행하는 것 중 무엇이 더 좋아요? 이유와 함께 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer traveling alone or with others? Give your reason in 2-3 sentences.",
    example_kr: "저는 같이 여행하는 것을 더 좋아해요. 혼자 가면 심심할 때가 많아요. 친구와 가면 더 재미있는 이야기를 나눌 수 있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "아침형 인간과 저녁형 인간 중 무엇이 더 좋아요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "Do you think it's better to be a morning person or a night person? Use '-은/는 것 같아요'.",
    example_kr: "저는 아침형 인간이 더 좋은 것 같아요. 아침에 일찍 일어나면 하루가 더 길게 느껴져요. 저녁에는 피곤해서 집중이 잘 안 되는 것 같아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "책과 영화 중에서 어느 것이 더 좋아요? 이유와 함께 2-3문장으로 쓰세요.",
    prompt_en: "Which do you prefer, books or movies? Give your reason in 2-3 sentences.",
    example_kr: "저는 영화를 더 좋아해요. 책보다 빨리 이야기를 즐길 수 있어요. 그리고 배우들의 연기를 보는 것도 재미있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "고양이와 강아지 중 어느 동물이 더 좋아요? '-는 게 좋아요'를 사용해서 쓰세요.",
    prompt_en: "Which do you prefer, cats or dogs? Use '-는 게 좋아요'.",
    example_kr: "저는 강아지를 키우는 게 좋아요. 강아지는 산책하는 것을 좋아해서 저도 같이 운동할 수 있어요. 고양이도 예쁘지만 저는 강아지가 더 좋아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "집에서 요리하는 것과 배달을 시키는 것 중 무엇이 더 좋아요? 이유와 함께 2-3문장으로 쓰세요.",
    prompt_en: "Which do you prefer, cooking at home or ordering delivery? Give your reason.",
    example_kr: "저는 집에서 요리하는 것을 더 좋아해요. 재료를 직접 고를 수 있어서 건강에 좋아요. 배달 음식은 편하지만 자주 먹으면 부담스러워요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "산과 바다 중 어디가 더 좋아요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "Do you prefer the mountains or the beach? Use '-은/는 것 같아요'.",
    example_kr: "저는 바다가 더 좋은 것 같아요. 파도 소리를 들으면 마음이 편해져요. 산도 아름답지만 저는 바다가 더 편안한 것 같아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "휴대폰으로 책을 읽는 것과 종이책을 읽는 것 중 무엇이 더 좋아요? 이유와 함께 쓰세요.",
    prompt_en: "Do you prefer reading books on your phone or paper books? Give your reason.",
    example_kr: "저는 종이책을 읽는 게 더 좋아요. 휴대폰으로 읽으면 눈이 쉽게 피곤해져요. 종이책은 종이 냄새도 좋고 집중이 더 잘돼요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "주말에 집에서 쉬는 것과 밖에 나가는 것 중 무엇을 더 좋아해요? 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer resting at home or going out on weekends? Write 2-3 sentences.",
    example_kr: "저는 집에서 쉬는 것을 더 좋아해요. 평일에 많이 피곤해서 주말에는 조용히 쉬고 싶어요. 가끔은 밖에 나가지만 대부분은 집에 있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "매운 음식과 단 음식 중 어느 것이 더 좋아요? '-는 게 좋아요'를 사용해서 쓰세요.",
    prompt_en: "Which do you like more, spicy food or sweet food? Use '-는 게 좋아요'.",
    example_kr: "저는 매운 음식을 먹는 게 더 좋아요. 매운맛을 느끼면 스트레스가 풀려요. 단 음식도 좋아하지만 매운 음식을 더 자주 먹어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "일찍 일어나는 것과 늦게까지 자는 것 중 무엇이 더 좋아요? 이유와 함께 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer waking up early or sleeping in? Give your reason.",
    example_kr: "저는 일찍 일어나는 게 더 좋아요. 아침에 조용한 시간을 보낼 수 있어요. 늦게까지 자면 오히려 하루가 짧게 느껴져요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "친구가 많은 것과 친한 친구가 적은 것 중 무엇이 더 좋다고 생각해요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "Do you think it's better to have many friends or a few close friends? Use '-은/는 것 같아요'.",
    example_kr: "저는 친한 친구가 적은 게 더 좋은 것 같아요. 깊은 이야기를 나눌 수 있어요. 친구가 많으면 오히려 시간이 부족한 것 같아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "운동을 혼자 하는 것과 같이 하는 것 중 무엇이 더 좋아요? 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer exercising alone or with others? Write 2-3 sentences.",
    example_kr: "저는 운동을 같이 하는 게 더 좋아요. 혼자 하면 쉽게 포기하게 돼요. 친구와 같이 하면 서로 응원해서 더 열심히 할 수 있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "전화 통화와 문자 중 무엇이 더 편해요? '-는 게 편해요'를 사용해서 쓰세요.",
    prompt_en: "Which is more comfortable for you, phone calls or texting? Use '-는 게 편해요'.",
    example_kr: "저는 문자로 이야기하는 게 더 편해요. 전화는 갑자기 하면 부담스러워요. 문자는 천천히 생각하고 답할 수 있어서 좋아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "도시 생활과 시골 생활 중 어느 것이 더 좋다고 생각해요? 이유와 함께 2-3문장으로 쓰세요.",
    prompt_en: "Do you think city life or countryside life is better? Give your reason.",
    example_kr: "저는 도시 생활이 더 편하다고 생각해요. 교통이 편리하고 편의시설이 많아요. 시골은 조용하지만 필요한 것을 사기가 불편해요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "혼자 밥 먹는 것과 같이 밥 먹는 것 중 무엇이 더 좋아요? '-는 게 좋아요'를 사용해서 쓰세요.",
    prompt_en: "Do you prefer eating alone or with others? Use '-는 게 좋아요'.",
    example_kr: "저는 가끔 혼자 밥 먹는 게 편해요. 시간에 얽매이지 않아서 좋아요. 하지만 대부분은 같이 먹는 게 더 즐거워요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "새 옷을 사는 것과 저축하는 것 중 무엇이 더 중요하다고 생각해요? 이유와 함께 쓰세요.",
    prompt_en: "Do you think buying new clothes or saving money is more important? Give your reason.",
    example_kr: "저는 저축하는 것이 더 중요하다고 생각해요. 미래를 위해 돈을 모아야 해요. 옷은 필요할 때만 사는 게 좋다고 생각해요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "지하철과 버스 중 어느 교통수단이 더 좋아요? '-는 게 좋아요'를 사용해서 2-3문장으로 쓰세요.",
    prompt_en: "Which do you prefer, the subway or the bus? Use '-는 게 좋아요'.",
    example_kr: "저는 지하철을 타는 게 더 좋아요. 시간이 정확해서 편해요. 버스는 길이 막히면 늦을 때가 많아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "온라인 쇼핑과 직접 가서 사는 것 중 무엇이 더 좋아요? 이유와 함께 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer online shopping or shopping in person? Give your reason.",
    example_kr: "저는 온라인 쇼핑이 더 편해요. 집에서 편하게 고를 수 있어요. 하지만 옷은 직접 입어 봐야 할 때도 있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "여행 갈 때 계획을 세우는 것과 즉흥적으로 다니는 것 중 무엇이 더 좋아요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "Do you prefer planning your trips or traveling spontaneously? Use '-은/는 것 같아요'.",
    example_kr: "저는 계획을 세우는 게 더 안전한 것 같아요. 시간을 아낄 수 있어요. 하지만 가끔은 즉흥적으로 다니는 것도 재미있는 것 같아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "사진 찍는 것과 그림 그리는 것 중 어느 것을 더 좋아해요? 2-3문장으로 쓰세요.",
    prompt_en: "Which do you like more, photography or drawing? Write 2-3 sentences.",
    example_kr: "저는 사진 찍는 것을 더 좋아해요. 순간을 빨리 담을 수 있어서 좋아요. 그림은 시간이 오래 걸려서 자주 못 그려요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "실내 운동과 야외 운동 중 무엇이 더 좋아요? '-기 때문에'를 사용해서 쓰세요.",
    prompt_en: "Which do you prefer, indoor exercise or outdoor exercise? Use '-기 때문에'.",
    example_kr: "저는 야외 운동이 더 좋아요. 신선한 공기를 마실 수 있기 때문이에요. 실내 운동도 편리하지만 답답하게 느껴질 때가 있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "생일 선물로 물건을 받는 것과 돈을 받는 것 중 무엇이 더 좋아요? 이유와 함께 쓰세요.",
    prompt_en: "For a birthday gift, do you prefer receiving an item or money? Give your reason.",
    example_kr: "저는 물건을 받는 게 더 좋아요. 그 사람이 고른 것에서 마음을 느낄 수 있어요. 돈은 편리하지만 조금 덜 특별하게 느껴져요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "평일에 쉬는 것과 주말에 쉬는 것 중 무엇이 더 좋아요? '-는 게 좋아요'를 사용해서 쓰세요.",
    prompt_en: "Do you prefer having a day off during the week or on weekends? Use '-는 게 좋아요'.",
    example_kr: "저는 평일에 쉬는 게 더 좋아요. 사람이 적어서 어디든 편하게 갈 수 있어요. 주말에는 사람이 많아서 불편할 때가 있어요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "집들이에 음식을 만들어 가는 것과 사서 가는 것 중 무엇이 더 좋아요? 2-3문장으로 쓰세요.",
    prompt_en: "For a housewarming, do you prefer bringing homemade food or store-bought food? Write 2-3 sentences.",
    example_kr: "저는 사서 가는 게 더 편해요. 시간이 없을 때가 많아요. 그래도 가끔은 직접 만들어 가면 더 정성스러워 보여요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "일찍 일어나서 공부하는 것과 밤에 늦게까지 공부하는 것 중 무엇이 더 효과적이에요? 이유와 함께 쓰세요.",
    prompt_en: "Is it more effective to study early in the morning or late at night? Give your reason.",
    example_kr: "저는 아침에 공부하는 게 더 효과적이라고 생각해요. 머리가 맑아서 집중이 잘돼요. 밤에는 피곤해서 오히려 실수가 많아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "새로운 곳으로 여행 가는 것과 좋아하는 곳에 또 가는 것 중 무엇이 더 좋아요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "Do you prefer traveling somewhere new or revisiting a favorite place? Use '-은/는 것 같아요'.",
    example_kr: "저는 새로운 곳에 가는 게 더 재미있는 것 같아요. 늘 새로운 경험을 할 수 있어요. 하지만 좋아하는 곳에 또 가는 것도 편안한 것 같아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "친구와 게임을 하는 것과 영화를 보는 것 중 무엇이 더 좋아요? 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer playing games or watching movies with friends? Write 2-3 sentences.",
    example_kr: "저는 친구와 게임을 하는 게 더 좋아요. 같이 이야기하면서 즐길 수 있어요. 영화는 조용히 봐야 해서 덜 활기차요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "휴가에 여행을 가는 것과 집에서 쉬는 것 중 무엇이 더 좋아요? '-기 때문에'를 사용해서 쓰세요.",
    prompt_en: "During a vacation, do you prefer traveling or resting at home? Use '-기 때문에'.",
    example_kr: "저는 여행을 가는 게 더 좋아요. 새로운 경험을 할 수 있기 때문이에요. 집에서 쉬는 것도 편하지만 여행이 더 기억에 남기 때문이에요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "손편지를 쓰는 것과 문자를 보내는 것 중 무엇이 더 좋다고 생각해요? 이유와 함께 쓰세요.",
    prompt_en: "Do you think writing a handwritten letter or texting is better? Give your reason.",
    example_kr: "저는 손편지를 쓰는 게 더 좋다고 생각해요. 정성이 많이 들어가요. 문자는 편리하지만 조금 덜 특별하게 느껴져요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "혼자 영화 보는 것과 극장에서 같이 보는 것 중 무엇이 더 좋아요? '-는 게 좋아요'를 사용해서 쓰세요.",
    prompt_en: "Do you prefer watching movies alone or at the theater with others? Use '-는 게 좋아요'.",
    example_kr: "저는 집에서 혼자 보는 게 더 편해요. 편한 옷을 입고 편하게 볼 수 있어요. 그래도 가끔은 극장에서 같이 보는 것도 좋아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "새 친구를 사귀는 것과 오래된 친구와 지내는 것 중 무엇이 더 좋아요? 2-3문장으로 쓰세요.",
    prompt_en: "Do you prefer making new friends or spending time with old friends? Write 2-3 sentences.",
    example_kr: "저는 오래된 친구와 지내는 게 더 편해요. 서로 잘 알아서 이야기하기 쉬워요. 새 친구를 사귀는 것도 재미있지만 시간이 필요해요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "일이 끝난 후에 바로 쉬는 것과 운동을 하는 것 중 무엇이 더 좋아요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "After work, do you prefer resting right away or exercising? Use '-은/는 것 같아요'.",
    example_kr: "저는 일이 끝난 후에 운동하는 게 더 좋은 것 같아요. 스트레스가 잘 풀려요. 바로 쉬면 오히려 몸이 더 무거워지는 것 같아요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "여러 가지 음식을 조금씩 먹는 것과 한 가지를 많이 먹는 것 중 무엇이 더 좋아요? 이유와 함께 쓰세요.",
    prompt_en: "Do you prefer eating a little of many dishes or a lot of one dish? Give your reason.",
    example_kr: "저는 여러 가지를 조금씩 먹는 게 더 좋아요. 다양한 맛을 즐길 수 있어요. 한 가지만 먹으면 금방 질려요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "아침을 먹는 것과 안 먹는 것 중 무엇이 더 좋다고 생각해요? '-기 때문에'를 사용해서 쓰세요.",
    prompt_en: "Do you think it's better to eat breakfast or skip it? Use '-기 때문에'.",
    example_kr: "저는 아침을 먹는 게 더 좋다고 생각해요. 하루를 힘차게 시작할 수 있기 때문이에요. 안 먹으면 점심때까지 배가 고프기 때문이에요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "휴대폰 게임과 보드게임 중 무엇이 더 좋아요? 2-3문장으로 쓰세요.",
    prompt_en: "Which do you prefer, phone games or board games? Write 2-3 sentences.",
    example_kr: "저는 보드게임을 하는 게 더 좋아요. 사람들과 얼굴을 보면서 놀 수 있어요. 휴대폰 게임은 편하지만 덜 재미있게 느껴져요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "월세로 사는 것과 집을 사는 것 중 무엇이 더 좋아요? '-는 게 더 좋아요'를 사용해서 쓰세요.",
    prompt_en: "Which do you prefer, renting or buying a home? Use '-는 게 더 좋아요'.",
    example_kr: "저는 지금은 월세로 사는 게 더 좋아요. 일 때문에 이사를 자주 하기 때문이에요. 집을 사면 큰돈이 필요해서 아직은 부담돼요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "새 언어를 배울 때 앱으로 혼자 공부하는 것과 선생님과 수업하는 것 중 무엇이 더 좋아요? 2-3문장으로 쓰세요.",
    prompt_en: "When learning a new language, do you prefer studying alone with an app or taking lessons with a teacher? Write 2-3 sentences.",
    example_kr: "저는 선생님과 수업하는 게 더 좋아요. 발음이 틀리면 바로 고쳐 주기 때문이에요. 앱은 편하지만 혼자 하면 금방 그만두게 돼요.",
  },
  {
    level: "A2",
    genre: "opinion",
    prompt_kr: "여행할 때 호텔과 에어비앤비 중 무엇이 더 좋아요? '-은/는 것 같아요'를 사용해서 쓰세요.",
    prompt_en: "When traveling, do you prefer hotels or Airbnb-style rentals? Use '-은/는 것 같아요'.",
    example_kr: "저는 에어비앤비가 더 좋은 것 같아요. 부엌이 있어서 아침을 직접 만들 수 있어요. 호텔보다 그 동네 사람처럼 살아 볼 수 있는 것 같아요.",
  },
];
