import type { RawPrompt } from "./types";

export const WRITING_A2_REPLY: RawPrompt[] = [
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 뭐 했어요？",
    stimulus_en: "",
    stimulus_ja: "昨日何しましたか？",
    stimulus_zh: "你昨天做了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 영화를 봤어요.",
    example_en: "I watched a movie yesterday.",
    example_ja: "私は昨日映画を見ました。",
    example_zh: "我昨天看了电影。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "지난주에 어디에 갔어요？",
    stimulus_en: "",
    stimulus_ja: "先週どこに行きましたか？",
    stimulus_zh: "你上周去哪里了？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난주에 바다에 갔어요.",
    example_en: "I went to the sea last week.",
    example_ja: "私は先週海に行きました。",
    example_zh: "我上周去了海边。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "아침에 뭘 먹었어요？",
    stimulus_en: "",
    stimulus_ja: "朝何を食べましたか？",
    stimulus_zh: "你早上吃了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 아침에 빵을 먹었어요.",
    example_en: "I ate bread in the morning.",
    example_ja: "私は朝パンを食べました。",
    example_zh: "我早上吃了面包。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 했어요？",
    stimulus_en: "",
    stimulus_ja: "夕方何しましたか？",
    stimulus_zh: "你晚上做了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 저녁에 책을 읽었어요.",
    example_en: "I read a book in the evening.",
    example_ja: "私は夕方本を読みました。",
    example_zh: "我晚上读了书。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 무엇을 공부했어요？",
    stimulus_en: "",
    stimulus_ja: "昨日何を勉強しましたか？",
    stimulus_zh: "你昨天学了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 한국어를 배웠어요.",
    example_en: "I learned Korean yesterday.",
    example_ja: "私は昨日韓国語を習いました。",
    example_zh: "我昨天学了韩语。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 집에서 쉬었어요？",
    stimulus_en: "",
    stimulus_ja: "昨日家で休みましたか？",
    stimulus_zh: "你昨天在家休息了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 집에서 쉬었어요.",
    example_en: "I rested at home yesterday.",
    example_ja: "私は昨日家で休みました。",
    example_zh: "我昨天在家休息了。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "언제 서울에 왔어요？",
    stimulus_en: "",
    stimulus_ja: "いつソウルに来ましたか？",
    stimulus_zh: "你什么时候来首尔的？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 작년에 서울에 왔어요.",
    example_en: "I came to Seoul last year.",
    example_ja: "私は去年ソウルに来ました。",
    example_zh: "我去年来了首尔。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 카페에서 뭐 마셨어요？",
    stimulus_en: "",
    stimulus_ja: "昨日カフェで何を飲みましたか？",
    stimulus_zh: "你昨天在咖啡厅喝了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 커피를 마셨어요.",
    example_en: "I drank coffee yesterday.",
    example_ja: "私は昨日コーヒーを飲みました。",
    example_zh: "我昨天喝了咖啡。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "오늘 아침에 운동했어요？",
    stimulus_en: "",
    stimulus_ja: "今朝運動しましたか？",
    stimulus_zh: "你今天早上运动了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 오늘 아침에 운동했어요.",
    example_en: "I exercised this morning.",
    example_ja: "私は今朝運動しました。",
    example_zh: "我今天早上运动了。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 무슨 노래를 들었어요？",
    stimulus_en: "",
    stimulus_ja: "昨日どんな歌を聞きましたか？",
    stimulus_zh: "你昨天听了什么歌？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 음악을 들었어요.",
    example_en: "I listened to music yesterday.",
    example_ja: "私は昨日音楽を聞きました。",
    example_zh: "我昨天听了音乐。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 누구를 만났어요？",
    stimulus_en: "",
    stimulus_ja: "昨日誰に会いましたか？",
    stimulus_zh: "你昨天见了谁？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 친구를 만났어요.",
    example_en: "I met a friend yesterday.",
    example_ja: "私は昨日友達に会いました。",
    example_zh: "我昨天见了朋友。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "언제 새 옷을 샀어요？",
    stimulus_en: "",
    stimulus_ja: "いつ新しい服を買いましたか？",
    stimulus_zh: "你什么时候买的新衣服？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난달에 옷을 샀어요.",
    example_en: "I bought clothes last month.",
    example_ja: "私は先月服を買いました。",
    example_zh: "我上个月买了衣服。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 저녁에 뭐 만들었어요？",
    stimulus_en: "",
    stimulus_ja: "昨日の夕食に何を作りましたか？",
    stimulus_zh: "你昨天晚上做了什么菜？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 피자를 만들었어요.",
    example_en: "I made pizza yesterday.",
    example_ja: "私は昨日ピザを作りました。",
    example_zh: "我昨天做了披萨。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 공원에서 뭐 했어요？",
    stimulus_en: "",
    stimulus_ja: "昨日公園で何しましたか？",
    stimulus_zh: "你昨天在公园做了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 사진을 찍었어요.",
    example_en: "I took a picture yesterday.",
    example_ja: "私は昨日写真を撮りました。",
    example_zh: "我昨天拍了照片。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "숙제 다 끝냈어요？",
    stimulus_en: "",
    stimulus_ja: "宿題は全部終わりましたか？",
    stimulus_zh: "作业都做完了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 숙제를 끝냈어요.",
    example_en: "I finished my homework yesterday.",
    example_ja: "私は昨日宿題を終えました。",
    example_zh: "我昨天做完了作业。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "오늘 어디에 아파서 갔어요？",
    stimulus_en: "",
    stimulus_ja: "今日どこが痛くて病院に行きましたか？",
    stimulus_zh: "你今天因为哪里不舒服去看病了？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 오늘 병원에 갔어요.",
    example_en: "I went to the hospital today.",
    example_ja: "私は今日病院に行きました。",
    example_zh: "我今天去了医院。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 과일 어디서 샀어요？",
    stimulus_en: "",
    stimulus_ja: "昨日果物をどこで買いましたか？",
    stimulus_zh: "你昨天在哪里买的水果？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 시장에 갔어요.",
    example_en: "I went to the market yesterday.",
    example_ja: "私は昨日市場に行きました。",
    example_zh: "我昨天去了市场。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "지난주 주말에 등산했어요？",
    stimulus_en: "",
    stimulus_ja: "先週末登山しましたか？",
    stimulus_zh: "你上周末爬山了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난주에 산에 갔어요.",
    example_en: "I went to the mountain last week.",
    example_ja: "私は先週山に行きました。",
    example_zh: "我上周去了山里。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 방 청소했어요？",
    stimulus_en: "",
    stimulus_ja: "昨日部屋を掃除しましたか？",
    stimulus_zh: "你昨天打扫房间了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 방을 청소했어요.",
    example_en: "I cleaned my room yesterday.",
    example_ja: "私は昨日部屋を掃除しました。",
    example_zh: "我昨天打扫了房间。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "생일에 선물 받았어요？",
    stimulus_en: "",
    stimulus_ja: "誕生日にプレゼントをもらいましたか？",
    stimulus_zh: "你生日收到礼物了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 선물을 받았어요.",
    example_en: "I received a gift yesterday.",
    example_ja: "私は昨日プレゼントをもらいました。",
    example_zh: "我昨天收到了礼物。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "아침에 커피 마셨어요？",
    stimulus_en: "",
    stimulus_ja: "朝コーヒーを飲みましたか？",
    stimulus_zh: "你早上喝咖啡了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 아침에 우유를 마셨어요.",
    example_en: "I drank milk in the morning.",
    example_ja: "私は朝牛乳を飲みました。",
    example_zh: "我早上喝了牛奶。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 누구한테 편지 썼어요？",
    stimulus_en: "",
    stimulus_ja: "昨日誰に手紙を書きましたか？",
    stimulus_zh: "你昨天给谁写信了？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 편지를 썼어요.",
    example_en: "I wrote a letter yesterday.",
    example_ja: "私は昨日手紙を書きました。",
    example_zh: "我昨天写了信。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 요리학원에 갔어요？",
    stimulus_en: "",
    stimulus_ja: "昨日料理教室に行きましたか？",
    stimulus_zh: "你昨天去烹饪班了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 요리를 배웠어요.",
    example_en: "I learned cooking yesterday.",
    example_ja: "私は昨日料理を習いました。",
    example_zh: "我昨天学了做饭。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "언제 운전면허 땄어요？",
    stimulus_en: "",
    stimulus_ja: "いつ運転免許を取りましたか？",
    stimulus_zh: "你什么时候考的驾照？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 작년에 차를 샀어요.",
    example_en: "I bought a car last year.",
    example_ja: "私は去年車を買いました。",
    example_zh: "我去年买了车。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 점심에 뭐 먹었어요？",
    stimulus_en: "",
    stimulus_ja: "昨日お昼に何を食べましたか？",
    stimulus_zh: "你昨天午饭吃了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 라면을 끓였어요.",
    example_en: "I boiled ramen yesterday.",
    example_ja: "私は昨日ラーメンを作りました。",
    example_zh: "我昨天煮了拉面。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 역사 박물관에 갔어요？",
    stimulus_en: "",
    stimulus_ja: "昨日歴史博物館に行きましたか？",
    stimulus_zh: "你昨天去历史博物馆了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 박물관에 갔어요.",
    example_en: "I went to the museum yesterday.",
    example_ja: "私は昨日博物館に行きました。",
    example_zh: "我昨天去了博物馆。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "과수원에 언제 갔어요？",
    stimulus_en: "",
    stimulus_ja: "果樹園にいつ行きましたか？",
    stimulus_zh: "你什么时候去的果园？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난주에 사과를 땄어요.",
    example_en: "I picked apples last week.",
    example_ja: "私は先週りんごを採りました。",
    example_zh: "我上周摘了苹果。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "오늘 아침에 일찍 일어났어요？",
    stimulus_en: "",
    stimulus_ja: "今日の朝早く起きましたか？",
    stimulus_zh: "你今天早上起得早吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 오늘 아침에 일찍 일어났어요.",
    example_en: "I woke up early this morning.",
    example_ja: "私は今日の朝早く起きました。",
    example_zh: "我今天早上起得很早。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 저녁에 산책했어요？",
    stimulus_en: "",
    stimulus_ja: "昨日の夕方散歩しましたか？",
    stimulus_zh: "你昨天晚上散步了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 공원에서 걸었어요.",
    example_en: "I walked in the park yesterday.",
    example_ja: "私は昨日公園で歩きました。",
    example_zh: "我昨天在公园散步了。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "언제 고향에 다녀왔어요？",
    stimulus_en: "",
    stimulus_ja: "いつ故郷に行ってきましたか？",
    stimulus_zh: "你什么时候回的老家？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난주에 고향에 갔어요.",
    example_en: "I went to my hometown last week.",
    example_ja: "私は先週故郷に行きました。",
    example_zh: "我上周回了老家。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 동생 숙제 도와줬어요？",
    stimulus_en: "",
    stimulus_ja: "昨日弟の宿題を手伝いましたか？",
    stimulus_zh: "你昨天帮弟弟做作业了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 동생을 도왔어요.",
    example_en: "I helped my younger sibling yesterday.",
    example_ja: "私は昨日弟を手伝いました。",
    example_zh: "我昨天帮了弟弟。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 라디오 들었어요？",
    stimulus_en: "",
    stimulus_ja: "昨日ラジオを聞きましたか？",
    stimulus_zh: "你昨天听广播了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 뉴스를 들었어요.",
    example_en: "I listened to the news yesterday.",
    example_ja: "私は昨日ニュースを聞きました。",
    example_zh: "我昨天听了新闻。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 한국 노래 번역했어요？",
    stimulus_en: "",
    stimulus_ja: "昨日韓国の歌を翻訳しましたか？",
    stimulus_zh: "你昨天翻译韩国歌了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 가사를 번역했어요.",
    example_en: "I translated song lyrics yesterday.",
    example_ja: "私は昨日歌詞を翻訳しました。",
    example_zh: "我昨天翻译了歌词。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "친구랑 언제 만나요？",
    stimulus_en: "",
    stimulus_ja: "友達といつ会いますか？",
    stimulus_zh: "你什么时候和朋友见面？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난주에 약속을 잡았어요.",
    example_en: "I made an appointment last week.",
    example_ja: "私は先週約束をしました。",
    example_zh: "我上周约好了见面。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "베란다 화분에 물 줬어요？",
    stimulus_en: "",
    stimulus_ja: "ベランダの鉢植えに水をあげましたか？",
    stimulus_zh: "你给阳台的花盆浇水了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 꽃에 물을 줬어요.",
    example_en: "I watered the flowers yesterday.",
    example_ja: "私は昨日花に水をあげました。",
    example_zh: "我昨天给花浇水了。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 무슨 일 있었어요？",
    stimulus_en: "",
    stimulus_ja: "昨日何かありましたか？",
    stimulus_zh: "你昨天发生什么事了？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 지갑을 잃어버렸어요.",
    example_en: "I lost my wallet yesterday.",
    example_ja: "私は昨日財布をなくしました。",
    example_zh: "我昨天丢了钱包。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "제주도 여행 언제 다녀왔어요？",
    stimulus_en: "",
    stimulus_ja: "済州島旅行はいつ行ってきましたか？",
    stimulus_zh: "你什么时候去的济州岛旅行？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 지난달에 제주도에 여행했어요.",
    example_en: "I traveled to Jeju Island last month.",
    example_ja: "私は先月済州島へ旅行しました。",
    example_zh: "我上个月去了济州岛旅行。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 도서관에서 뭐 빌렸어요？",
    stimulus_en: "",
    stimulus_ja: "昨日図書館で何を借りましたか？",
    stimulus_zh: "你昨天在图书馆借了什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 동화책을 읽었어요.",
    example_en: "I read a fairy tale book yesterday.",
    example_ja: "私は昨日童話の本を読みました。",
    example_zh: "我昨天读了童话书。",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "어제 밤하늘 봤어요？",
    stimulus_en: "",
    stimulus_ja: "昨日夜空を見ましたか？",
    stimulus_zh: "你昨晚看夜空了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "저는 어제 밤에 별을 봤어요.",
    example_en: "I saw stars at night yesterday.",
    example_ja: "私は昨日夜星を見ました。",
    example_zh: "我昨晚看了星星。",
  },
];
