import type { RawPrompt } from "./types";

export const WRITING_A2_REPLY: RawPrompt[] = [
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "이번 주 토요일에 같이 등산 갈래요? 날씨가 좋을 것 같아요.",
    stimulus_en: "Want to go hiking together this Saturday? The weather looks like it'll be nice.",
    prompt_kr: "친구의 초대를 거절하는 답장을 두세 문장으로 써 보세요. '-기 때문에'와 '-(으)ㄹ 거예요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply declining your friend's invitation. Use '-기 때문에' and '-(으)ㄹ 거예요'.",
    example_kr: "미안해요, 토요일에는 일이 있기 때문에 못 가요. 대신 다음 주에는 시간이 있을 거예요. 그때 같이 가요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "민준 씨, 내일 회의를 오전 열 시로 바꿔도 괜찮아요?",
    stimulus_en: "Min-jun, is it okay if we move tomorrow's meeting to 10 a.m.?",
    prompt_kr: "동료의 부탁을 받아들이는 답장을 두세 문장으로 써 보세요. '-(으)면'을 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply agreeing to your coworker's request. Use '-(으)면'.",
    example_kr: "네, 열 시면 괜찮아요. 회의 자료가 필요하면 오늘 저녁에 보내 드릴게요. 내일 봐요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "안녕하세요, 옆집이에요. 오늘 오후에 택배가 왔는데 제가 대신 받아 뒀어요.",
    stimulus_en: "Hi, it's your next-door neighbor. A package came this afternoon, so I took it in for you.",
    prompt_kr: "이웃의 메시지에 감사하는 답장을 두세 문장으로 써 보세요. '-(으)ㄹ게요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence thank-you reply to your neighbor. Use '-(으)ㄹ게요'.",
    example_kr: "정말 감사해요! 저는 일곱 시쯤 집에 도착해요. 그때 찾으러 갈게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 내일 오후 두 시 진료 예약을 확인해 주세요. 시간 변경이 필요하시면 답장 주세요.",
    stimulus_en: "Please confirm your appointment for tomorrow at 2 p.m. Reply if you need to change the time.",
    prompt_kr: "병원의 예약 확인 문자에 시간 변경을 요청하는 답장을 두세 문장으로 써 보세요. '-아/어야 해요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the clinic asking to change the time. Use '-아/어야 해요'.",
    example_kr: "안녕하세요, 내일 두 시에는 회의에 가야 해요. 혹시 네 시로 바꿀 수 있어요? 답장 기다릴게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "세입자님, 다음 주 수요일 오전에 보일러 점검이 있어요. 집에 계실 수 있어요?",
    stimulus_en: "Tenant, there's a boiler inspection next Wednesday morning. Will you be able to be home?",
    prompt_kr: "집주인의 메시지에 답장을 두세 문장으로 써 보세요. '-지만'을 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your landlord's message. Use '-지만'.",
    example_kr: "알려 주셔서 감사해요. 오전에는 출근해야 하지만 오후에는 집에 있어요. 오후에 오실 수 있어요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "한국 음식 중에서 뭐가 제일 좋아요? 저는 요즘 순두부찌개에 빠졌어요.",
    stimulus_en: "What's your favorite Korean food? I'm obsessed with sundubu-jjigae these days.",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-아/어 봤어요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-아/어 봤어요'.",
    example_kr: "저는 삼겹살을 제일 좋아해요. 순두부찌개는 아직 안 먹어 봤어요. 다음에 같이 먹으러 가요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 주문하신 안경이 준비됐어요. 언제 찾으러 오실 수 있어요?",
    stimulus_en: "Your glasses are ready. When can you come pick them up?",
    prompt_kr: "안경점의 문자에 방문 시간을 알리는 답장을 두세 문장으로 써 보세요. '-(으)ㄹ 수 있어요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the optician telling them when you can visit. Use '-(으)ㄹ 수 있어요'.",
    example_kr: "감사합니다! 저는 금요일 저녁 여섯 시쯤 갈 수 있어요. 그 시간에 가게가 열려 있어요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "역 근처에 새로 생긴 카페 가 봤어요? 케이크가 진짜 맛있대요.",
    stimulus_en: "Have you been to the new cafe near the station? I hear the cake is really good.",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-아/어 봤어요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-아/어 봤어요'.",
    example_kr: "네, 지난주에 가 봤어요. 커피는 좋았지만 케이크는 아직 안 먹어 봤어요. 이번 주말에 같이 가 볼까요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "오늘 점심 같이 먹을래요? 근처에 파스타 집이랑 국밥 집이 있어요.",
    stimulus_en: "Want to have lunch together today? There's a pasta place and a gukbap place nearby.",
    prompt_kr: "동료의 제안에 답장을 두세 문장으로 써 보세요. '-는 게 더 좋아요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your coworker's suggestion. Use '-는 게 더 좋아요'.",
    example_kr: "좋아요! 오늘은 날씨가 추워서 국밥을 먹는 게 더 좋아요. 열두 시에 로비에서 만나요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "이번 여름휴가는 어디로 가요? 아직 계획 없으면 같이 갈래요?",
    stimulus_en: "Where are you going for summer vacation? If you don't have plans yet, want to go together?",
    prompt_kr: "친구의 질문에 계획을 알리는 답장을 두세 문장으로 써 보세요. '-(으)려고 해요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply telling your friend your plans. Use '-(으)려고 해요'.",
    example_kr: "저는 팔월에 부산에 가려고 해요. 바다에서 며칠 쉬려고 해요. 같이 가면 정말 좋겠어요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "안녕하세요, 302호예요. 어젯밤에 제 자리에 차가 주차되어 있었어요. 혹시 그 차 주인이세요?",
    stimulus_en: "Hi, this is unit 302. Last night a car was parked in my spot. Is that your car by any chance?",
    prompt_kr: "이웃에게 사과하는 답장을 두세 문장으로 써 보세요. '-아/어서'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply apologizing to your neighbor. Use '-아/어서'.",
    example_kr: "네, 제 차예요. 어제 늦게 와서 자리를 잘못 봤어요. 정말 죄송해요, 다시는 안 그럴게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "저 다음 주 일요일에 이사해요. 혹시 오전에 시간 있으면 좀 도와줄 수 있어요?",
    stimulus_en: "I'm moving next Sunday. If you're free in the morning, could you help me out?",
    prompt_kr: "친구의 부탁을 받아들이는 답장을 두세 문장으로 써 보세요. '-(으)면'과 '-(으)ㄹ게요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply agreeing to help your friend. Use '-(으)면' and '-(으)ㄹ게요'.",
    example_kr: "물론이죠! 아홉 시에 가면 괜찮아요? 제 차도 가져갈게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "회원님, 내일 저녁 요가 수업이 취소됐어요. 다른 날로 바꿔 드릴까요?",
    stimulus_en: "Member, tomorrow evening's yoga class has been canceled. Shall we move you to another day?",
    prompt_kr: "헬스장의 안내 문자에 답장을 두세 문장으로 써 보세요. '-(으)ㄹ까요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the gym's notice. Use '-(으)ㄹ까요'.",
    example_kr: "알려 주셔서 감사해요. 목요일 저녁 수업으로 바꿀까요? 그날 자리가 있는지 알려 주세요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "요즘 뭐 재미있는 드라마 봐요? 주말에 볼 거 추천해 주세요!",
    stimulus_en: "Are you watching any good dramas lately? Recommend something for the weekend!",
    prompt_kr: "친구에게 추천하는 답장을 두세 문장으로 써 보세요. '-는 것 같아요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply recommending something to your friend. Use '-는 것 같아요'.",
    example_kr: "저는 요즘 '나의 아저씨'를 보고 있어요. 조금 슬프지만 정말 잘 만든 것 같아요. 주말에 한번 봐 보세요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "하늘 씨, 3층 프린터가 또 안 돼요. 어떻게 해야 해요?",
    stimulus_en: "Haneul, the 3rd-floor printer isn't working again. What should I do?",
    prompt_kr: "동료에게 방법을 알려 주는 답장을 두세 문장으로 써 보세요. '-아/어 보세요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply telling your coworker what to do. Use '-아/어 보세요'.",
    example_kr: "먼저 프린터를 껐다가 다시 켜 보세요. 그래도 안 되면 2층 프린터를 써 보세요. 제가 오후에 관리팀에 연락할게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요? 저는 하루 종일 집에서 잤어요.",
    stimulus_en: "Did you have a good weekend? I slept at home all day.",
    prompt_kr: "친구의 질문에 주말 이야기를 하는 답장을 두세 문장으로 써 보세요. '-고 나서'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply telling your friend about your weekend. Use '-고 나서'.",
    example_kr: "네, 잘 보냈어요. 토요일에 청소를 하고 나서 친구랑 한강에 갔어요. 일요일에는 저도 푹 쉬었어요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 처방하신 약은 하루 세 번, 식사 후에 드세요. 궁금한 점 있으세요?",
    stimulus_en: "Please take the prescribed medicine three times a day after meals. Do you have any questions?",
    prompt_kr: "약국의 안내 문자에 질문하는 답장을 두세 문장으로 써 보세요. '-기 전에'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the pharmacy asking a question. Use '-기 전에'.",
    example_kr: "안내 감사합니다. 자기 전에 먹어도 괜찮아요? 그리고 커피를 마시기 전에 약을 먹으면 안 돼요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "토요일에 우리 집에서 제 생일 파티 해요! 뭐 좀 가져올 수 있어요?",
    stimulus_en: "I'm having my birthday party at my place on Saturday! Could you bring something?",
    prompt_kr: "친구의 초대에 답장을 두세 문장으로 써 보세요. '-아/어 주세요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's invitation. Use '-아/어 주세요'.",
    example_kr: "생일 축하해요! 저는 와인이랑 치즈를 가져갈게요. 몇 시에 가면 되는지 알려 주세요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "안녕하세요, 이번 달 월세가 아직 안 들어왔어요. 확인 부탁드려요.",
    stimulus_en: "Hello, this month's rent hasn't come in yet. Please check.",
    prompt_kr: "집주인에게 사과하는 답장을 두세 문장으로 써 보세요. '-았/었어요'와 '-(으)ㄹ게요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply apologizing to your landlord. Use '-았/었어요' and '-(으)ㄹ게요'.",
    example_kr: "죄송해요, 이번 주에 너무 바빠서 깜빡했어요. 지금 바로 보낼게요. 확인 부탁드려요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "한국어 정말 많이 늘었네요! 평소에 어떻게 공부해요?",
    stimulus_en: "Your Korean has really improved! How do you usually study?",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-기 때문에'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-기 때문에'.",
    example_kr: "고마워요! 매일 출근길에 앱으로 공부해요. 시간이 별로 없기 때문에 짧게 자주 해요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "서연 씨는 재택근무 자주 해요? 저는 요즘 집에서 일하는 게 힘들어요.",
    stimulus_en: "Seo-yeon, do you work from home often? I'm finding it hard to work from home these days.",
    prompt_kr: "동료의 질문에 답장을 두세 문장으로 써 보세요. '-는 게 더 좋아요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your coworker's question. Use '-는 게 더 좋아요'.",
    example_kr: "저는 일주일에 두 번 재택해요. 집중이 잘 안 될 때는 사무실에서 일하는 게 더 좋아요. 카페에서 일해 봤어요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "내일 비가 많이 온대요. 그래도 야외 콘서트 갈 거예요?",
    stimulus_en: "They say it'll rain a lot tomorrow. Are you still going to the outdoor concert?",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-아/어도'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-아/어도'.",
    example_kr: "네, 비가 와도 갈 거예요. 표가 비쌌어요! 우비를 가져갈 거니까 걱정하지 마세요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "안녕하세요, 아래층이에요. 다음 주에 출장을 가는데 혹시 고양이 밥 좀 줄 수 있어요?",
    stimulus_en: "Hi, it's your downstairs neighbor. I'm going on a business trip next week — could you feed my cat?",
    prompt_kr: "이웃의 부탁을 받아들이는 답장을 두세 문장으로 써 보세요. '-(으)ㄹ 수 있어요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply agreeing to your neighbor's request. Use '-(으)ㄹ 수 있어요'.",
    example_kr: "네, 도와줄 수 있어요! 저는 저녁 일곱 시 이후에 갈 수 있어요. 열쇠는 언제 주실 거예요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 어제 저희 카페에 검은색 우산을 두고 가셨어요? 카운터에 있어요.",
    stimulus_en: "Did you leave a black umbrella at our cafe yesterday? It's at the counter.",
    prompt_kr: "카페의 메시지에 답장을 두세 문장으로 써 보세요. '-(으)ㄴ 것 같아요'와 '-(으)ㄹ게요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the cafe's message. Use '-(으)ㄴ 것 같아요' and '-(으)ㄹ게요'.",
    example_kr: "네, 제 우산인 것 같아요! 어제 창가 자리에 앉았어요. 오늘 퇴근 후에 찾으러 갈게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "요리 잘해요? 저는 라면밖에 못 끓여요.",
    stimulus_en: "Are you good at cooking? I can only make ramyeon.",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-(으)ㄹ 수 있어요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-(으)ㄹ 수 있어요'.",
    example_kr: "조금요. 저는 파스타랑 김치볶음밥을 만들 수 있어요. 다음에 우리 집에서 같이 만들어요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 치과 정기 검진 시기가 됐어요. 다음 달에 예약하시겠어요?",
    stimulus_en: "It's time for your regular dental checkup. Would you like to book for next month?",
    prompt_kr: "치과의 문자에 예약을 요청하는 답장을 두세 문장으로 써 보세요. '-(으)면 좋겠어요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the dentist requesting an appointment. Use '-(으)면 좋겠어요'.",
    example_kr: "네, 예약할게요. 다음 달 첫째 주 토요일 오전이면 좋겠어요. 가능한 시간을 알려 주세요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "지호 씨, 오늘 회식 몇 시에 끝나요? 저는 아홉 시에 집에 가야 해요.",
    stimulus_en: "Ji-ho, what time does the team dinner end today? I have to go home at nine.",
    prompt_kr: "동료의 질문에 답장을 두세 문장으로 써 보세요. '-아/어도 돼요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your coworker's question. Use '-아/어도 돼요'.",
    example_kr: "보통 열 시쯤 끝나요. 그런데 아홉 시에 먼저 가도 돼요. 팀장님께는 제가 말씀드릴게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "새 직장 어때요? 벌써 한 달 됐죠?",
    stimulus_en: "How's the new job? It's been a month already, right?",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-지만'을 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-지만'.",
    example_kr: "네, 벌써 한 달이에요. 일은 좀 많지만 동료들이 정말 친절해요. 출퇴근 시간이 짧아서 좋아요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "윗집이에요. 어제 저녁에 시끄러웠죠? 친구들이 와서 그랬어요. 정말 죄송해요.",
    stimulus_en: "This is the upstairs neighbor. It was noisy last night, wasn't it? I had friends over. I'm really sorry.",
    prompt_kr: "이웃의 사과에 답장을 두세 문장으로 써 보세요. '-(으)면'을 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your neighbor's apology. Use '-(으)면'.",
    example_kr: "괜찮아요, 말씀해 주셔서 감사해요. 열한 시 전에만 끝나면 저는 괜찮아요. 다음에도 미리 알려 주시면 좋겠어요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "요즘 운동해요? 저는 헬스장에 등록했는데 아직 한 번도 안 갔어요.",
    stimulus_en: "Are you exercising these days? I signed up for a gym but haven't gone once yet.",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-(으)ㄴ 후에'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-(으)ㄴ 후에'.",
    example_kr: "저는 퇴근한 후에 삼십 분씩 달려요. 처음에는 힘들었지만 지금은 재미있어요. 같이 헬스장에 갈까요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 현재 요금제보다 데이터가 두 배 많은 요금제가 나왔어요. 바꾸시겠어요?",
    stimulus_en: "A new plan with twice the data of your current plan is now available. Would you like to switch?",
    prompt_kr: "통신사의 문자에 답장을 두세 문장으로 써 보세요. '-(으)려고 해요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the phone carrier's message. Use '-(으)려고 해요'.",
    example_kr: "안내 감사합니다. 저는 데이터를 많이 안 써서 지금 요금제를 그대로 쓰려고 해요. 나중에 필요하면 다시 연락할게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "금요일 저녁에 우리 집에서 영화 볼래요? 몇 시가 좋아요?",
    stimulus_en: "Want to watch a movie at my place Friday evening? What time works for you?",
    prompt_kr: "친구의 제안에 답장을 두세 문장으로 써 보세요. '-(으)ㄹ까요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's suggestion. Use '-(으)ㄹ까요'.",
    example_kr: "좋아요! 일곱 시에 갈까요? 제가 피자를 사 갈까요, 아니면 팝콘이 더 좋아요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "유나 씨, 다음 주에 처음으로 부산 출장 가요. 뭘 준비해야 해요?",
    stimulus_en: "Yuna, I'm going on my first business trip to Busan next week. What should I prepare?",
    prompt_kr: "동료에게 알려 주는 답장을 두세 문장으로 써 보세요. '-아/어야 해요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply advising your coworker. Use '-아/어야 해요'.",
    example_kr: "먼저 기차표를 오늘 예약해야 해요. 금요일은 표가 빨리 없어져요. 그리고 영수증은 다 모아야 해요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "저 강아지 키우고 싶어요. 그런데 혼자 살아서 고민이에요. 어떻게 생각해요?",
    stimulus_en: "I want to get a dog. But I live alone, so I'm not sure. What do you think?",
    prompt_kr: "친구에게 의견을 말하는 답장을 두세 문장으로 써 보세요. '-기 때문에'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply giving your friend your opinion. Use '-기 때문에'.",
    example_kr: "저도 강아지를 좋아하지만 조금 걱정돼요. 강아지는 매일 산책이 필요하기 때문에 시간이 많이 들어요. 먼저 친구 강아지를 하루 돌봐 보는 건 어때요?",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 말씀하신 조건에 맞는 원룸이 나왔어요. 이번 주에 보러 오실 수 있어요?",
    stimulus_en: "A studio apartment matching your conditions just came up. Can you come see it this week?",
    prompt_kr: "부동산의 문자에 답장을 두세 문장으로 써 보세요. '-(으)ㄹ 거예요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the real estate agent. Use '-(으)ㄹ 거예요'.",
    example_kr: "연락 감사해요! 저는 목요일 오후에 갈 거예요. 월세랑 관리비도 미리 알려 주세요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "아침에 커피 마셔요, 차 마셔요? 저는 커피 없으면 하루를 못 시작해요.",
    stimulus_en: "Do you drink coffee or tea in the morning? I can't start my day without coffee.",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-는 게 더 좋아요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-는 게 더 좋아요'.",
    example_kr: "저는 아침에 차를 마시는 게 더 좋아요. 커피를 마시면 배가 아파요. 그래도 오후에는 가끔 라떼를 마셔요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "도윤 씨, 아까 보낸 파일이 잘못된 것 같아요. 다시 보내 줄 수 있어요?",
    stimulus_en: "Do-yoon, I think the file you sent earlier is the wrong one. Could you send it again?",
    prompt_kr: "동료에게 사과하는 답장을 두세 문장으로 써 보세요. '-네요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply apologizing to your coworker. Use '-네요'.",
    example_kr: "아, 정말 죄송해요. 지난달 파일을 보냈네요. 지금 바로 새 파일 보낼게요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "요즘 잠 잘 자요? 저는 새벽 세 시까지 잠이 안 와요.",
    stimulus_en: "Are you sleeping well these days? I can't fall asleep until 3 a.m.",
    prompt_kr: "친구의 질문에 답장을 두세 문장으로 써 보세요. '-아/어서'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to your friend's question. Use '-아/어서'.",
    example_kr: "저도 요즘 일이 많아서 늦게 자요. 그래도 자기 전에 핸드폰을 안 봐서 조금 나아졌어요. 한번 해 보세요!",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "고객님, 주문이 많아서 배달이 이십 분 정도 늦을 것 같아요. 죄송합니다.",
    stimulus_en: "Due to high order volume, your delivery will be about 20 minutes late. We apologize.",
    prompt_kr: "배달 지연 안내에 답장을 두세 문장으로 써 보세요. '-아/어 주세요'를 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to the delivery delay notice. Use '-아/어 주세요'.",
    example_kr: "괜찮아요, 천천히 오세요. 그런데 문 앞에 놓고 벨은 누르지 말아 주세요. 아기가 자고 있어요.",
  },
  {
    level: "A2",
    genre: "reply",
    stimulus_kr: "한국에 온 지 얼마나 됐어요? 처음에 뭐가 제일 힘들었어요?",
    stimulus_en: "How long have you been in Korea? What was hardest at first?",
    prompt_kr: "새로운 친구의 질문에 답장을 두세 문장으로 써 보세요. '-(으)ㄴ 지 ... 됐어요'와 '-지만'을 사용하세요.",
    prompt_en: "Write a two- or three-sentence reply to a new friend's question. Use '-(으)ㄴ 지 ... 됐어요' and '-지만'.",
    example_kr: "한국에 온 지 이 년 됐어요. 처음에는 은행 일이 제일 어려웠지만 지금은 괜찮아요. 이제 음식 주문도 혼자 할 수 있어요!",
  },
];
