import type { RawPrompt } from "./types";

export const WRITING_B1_DESCRIPTION: RawPrompt[] = [
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    prompt_ja: "私のかばんを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的包。",
    prompt_vi: "Hãy miêu tả chi tiết chiếc túi của tôi.",
    example_kr: "제 가방은 따뜻하고 예뻐요.",
    example_en: "My bag is warm and pretty.",
    example_ja: "私のかばんは暖かくてきれいです。",
    example_zh: "我的包很温暖又漂亮。",
    example_vi: "Chiếc túi của tôi ấm áp và đẹp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    prompt_ja: "このケーキを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这个蛋糕。",
    prompt_vi: "Hãy miêu tả chi tiết chiếc bánh này.",
    example_kr: "이 케이크는 복잡하고 멋있어요.",
    example_en: "This cake is crowded and cool.",
    example_ja: "このケーキは複雑でかっこいいです。",
    example_zh: "这个蛋糕很复杂又帅气。",
    example_vi: "Chiếc bánh này phức tạp và ngầu.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    prompt_ja: "私の町を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们的社区。",
    prompt_vi: "Hãy miêu tả chi tiết khu phố của tôi.",
    example_kr: "우리 동네는 복잡하고 조용해요.",
    example_en: "My neighborhood is crowded and quiet.",
    example_ja: "私の町は複雑で静かです。",
    example_zh: "我们的社区很复杂又安静。",
    example_vi: "Khu phố của tôi phức tạp và yên tĩnh.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    prompt_ja: "私の友達を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的朋友。",
    prompt_vi: "Hãy miêu tả chi tiết người bạn của tôi.",
    example_kr: "제 친구는 멋있고 귀여워요.",
    example_en: "My friend is cool and cute.",
    example_ja: "私の友達はかっこよくてかわいいです。",
    example_zh: "我的朋友很帅气又可爱。",
    example_vi: "Bạn của tôi ngầu và đáng yêu.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    prompt_ja: "私の部屋を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的房间。",
    prompt_vi: "Hãy miêu tả chi tiết căn phòng của tôi.",
    example_kr: "제 방은 친절하고 맛있어요.",
    example_en: "My room is kind and delicious.",
    example_ja: "私の部屋は親切でおいしいです。",
    example_zh: "我的房间很亲切又好吃。",
    example_vi: "Phòng của tôi thân thiện và ngon.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    prompt_ja: "この映画を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这部电影。",
    prompt_vi: "Hãy miêu tả chi tiết bộ phim này.",
    example_kr: "이 영화는 맛있고 커요.",
    example_en: "This movie is delicious and big.",
    example_ja: "この映画はおいしくて大きいです。",
    example_zh: "这部电影很好吃又大。",
    example_vi: "Bộ phim này ngon và to.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    prompt_ja: "うちの父を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我爸爸。",
    prompt_vi: "Hãy miêu tả chi tiết bố của tôi.",
    example_kr: "우리 아빠는 귀엽고 커요.",
    example_en: "My dad is cute and big.",
    example_ja: "うちの父はかわいくて大きいです。",
    example_zh: "我爸爸很可爱又大。",
    example_vi: "Bố tôi đáng yêu và to.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    prompt_ja: "うちの母を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我妈妈。",
    prompt_vi: "Hãy miêu tả chi tiết mẹ của tôi.",
    example_kr: "우리 엄마는 예쁘고 멋있어요.",
    example_en: "My mom is pretty and cool.",
    example_ja: "うちの母はきれいでかっこいいです。",
    example_zh: "我妈妈很漂亮又帅气。",
    example_vi: "Mẹ tôi đẹp và ngầu.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    prompt_ja: "私たちの先生を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们老师。",
    prompt_vi: "Hãy miêu tả chi tiết giáo viên của tôi.",
    example_kr: "우리 선생님은 복잡하고 친절해요.",
    example_en: "Our teacher is crowded and kind.",
    example_ja: "私たちの先生は複雑で親切です。",
    example_zh: "我们老师很复杂又亲切。",
    example_vi: "Giáo viên của tôi phức tạp và thân thiện.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    prompt_ja: "この歌を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这首歌。",
    prompt_vi: "Hãy miêu tả chi tiết bài hát này.",
    example_kr: "이 노래는 멋있고 맛있어요.",
    example_en: "This song is cool and delicious.",
    example_ja: "この歌はかっこよくておいしいです。",
    example_zh: "这首歌很帅气又好吃。",
    example_vi: "Bài hát này ngầu và ngon.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 고양이를 자세히 묘사해 보세요.",
    prompt_en: "Describe our cat in some detail.",
    prompt_ja: "うちの猫を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我家的猫。",
    prompt_vi: "Hãy miêu tả chi tiết con mèo nhà tôi.",
    example_kr: "우리 집 고양이는 친절하고 작아요.",
    example_en: "Our cat is kind and small.",
    example_ja: "うちの猫は親切で小さいです。",
    example_zh: "我家的猫很亲切又小。",
    example_vi: "Con mèo nhà tôi thân thiện và nhỏ.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    prompt_ja: "このカフェを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这家咖啡厅。",
    prompt_vi: "Hãy miêu tả chi tiết quán cà phê này.",
    example_kr: "이 카페는 귀엽고 편해요.",
    example_en: "This cafe is cute and comfortable.",
    example_ja: "このカフェはかわいくて楽です。",
    example_zh: "这家咖啡厅很可爱又舒适。",
    example_vi: "Quán cà phê này đáng yêu và thoải mái.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    prompt_ja: "ソウルを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下首尔。",
    prompt_vi: "Hãy miêu tả chi tiết Seoul.",
    example_kr: "서울은 친절하고 예뻐요.",
    example_en: "Seoul is kind and pretty.",
    example_ja: "ソウルは親切できれいです。",
    example_zh: "首尔很亲切又漂亮。",
    example_vi: "Seoul thân thiện và đẹp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 강아지를 자세히 묘사해 보세요.",
    prompt_en: "Describe our dog in some detail.",
    prompt_ja: "うちの犬を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我家的狗。",
    prompt_vi: "Hãy miêu tả chi tiết con chó nhà tôi.",
    example_kr: "우리 집 강아지는 유명하고 깨끗해요.",
    example_en: "Our dog is famous and clean.",
    example_ja: "うちの犬は有名で清潔です。",
    example_zh: "我家的狗很有名又干净。",
    example_vi: "Con chó nhà tôi nổi tiếng và sạch sẽ.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    prompt_ja: "私たちの学校を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们学校。",
    prompt_vi: "Hãy miêu tả chi tiết trường của tôi.",
    example_kr: "우리 학교는 조용하고 시끄러워요.",
    example_en: "My school is quiet and loud.",
    example_ja: "私たちの学校は静かでうるさいです。",
    example_zh: "我们学校很安静又吵闹。",
    example_vi: "Trường của tôi yên tĩnh và ồn ào.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    prompt_ja: "私のかばんを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的包。",
    prompt_vi: "Hãy miêu tả chi tiết chiếc túi của tôi.",
    example_kr: "제 가방은 시끄럽고 귀여워요.",
    example_en: "My bag is loud and cute.",
    example_ja: "私のかばんはうるさくてかわいいです。",
    example_zh: "我的包很吵闹又可爱。",
    example_vi: "Chiếc túi của tôi ồn ào và đáng yêu.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    prompt_ja: "このケーキを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这个蛋糕。",
    prompt_vi: "Hãy miêu tả chi tiết chiếc bánh này.",
    example_kr: "이 케이크는 복잡하고 편해요.",
    example_en: "This cake is crowded and comfortable.",
    example_ja: "このケーキは複雑で楽です。",
    example_zh: "这个蛋糕很复杂又舒适。",
    example_vi: "Chiếc bánh này phức tạp và thoải mái.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    prompt_ja: "私の町を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们的社区。",
    prompt_vi: "Hãy miêu tả chi tiết khu phố của tôi.",
    example_kr: "우리 동네는 예쁘고 유명해요.",
    example_en: "My neighborhood is pretty and famous.",
    example_ja: "私の町はきれいで有名です。",
    example_zh: "我们的社区很漂亮又有名。",
    example_vi: "Khu phố của tôi đẹp và nổi tiếng.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    prompt_ja: "私の友達を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的朋友。",
    prompt_vi: "Hãy miêu tả chi tiết người bạn của tôi.",
    example_kr: "제 친구는 귀엽고 복잡해요.",
    example_en: "My friend is cute and crowded.",
    example_ja: "私の友達はかわいくて複雑です。",
    example_zh: "我的朋友很可爱又复杂。",
    example_vi: "Bạn của tôi đáng yêu và phức tạp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    prompt_ja: "私の部屋を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的房间。",
    prompt_vi: "Hãy miêu tả chi tiết căn phòng của tôi.",
    example_kr: "제 방은 친절하고 유명해요.",
    example_en: "My room is kind and famous.",
    example_ja: "私の部屋は親切で有名です。",
    example_zh: "我的房间很亲切又有名。",
    example_vi: "Phòng của tôi thân thiện và nổi tiếng.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    prompt_ja: "この映画を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这部电影。",
    prompt_vi: "Hãy miêu tả chi tiết bộ phim này.",
    example_kr: "이 영화는 예쁘고 맛있어요.",
    example_en: "This movie is pretty and delicious.",
    example_ja: "この映画はきれいでおいしいです。",
    example_zh: "这部电影很漂亮又好吃。",
    example_vi: "Bộ phim này đẹp và ngon.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    prompt_ja: "うちの父を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我爸爸。",
    prompt_vi: "Hãy miêu tả chi tiết bố của tôi.",
    example_kr: "우리 아빠는 맛있고 아름다워요.",
    example_en: "My dad is delicious and beautiful.",
    example_ja: "うちの父はおいしくて美しいです。",
    example_zh: "我爸爸很好吃又美丽。",
    example_vi: "Bố tôi ngon và tuyệt đẹp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    prompt_ja: "うちの母を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我妈妈。",
    prompt_vi: "Hãy miêu tả chi tiết mẹ của tôi.",
    example_kr: "우리 엄마는 따뜻하고 깨끗해요.",
    example_en: "My mom is warm and clean.",
    example_ja: "うちの母は暖かくて清潔です。",
    example_zh: "我妈妈很温暖又干净。",
    example_vi: "Mẹ tôi ấm áp và sạch sẽ.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    prompt_ja: "私たちの先生を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们老师。",
    prompt_vi: "Hãy miêu tả chi tiết giáo viên của tôi.",
    example_kr: "우리 선생님은 맛있고 유명해요.",
    example_en: "Our teacher is delicious and famous.",
    example_ja: "私たちの先生はおいしくて有名です。",
    example_zh: "我们老师很好吃又有名。",
    example_vi: "Giáo viên của tôi ngon và nổi tiếng.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    prompt_ja: "この歌を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这首歌。",
    prompt_vi: "Hãy miêu tả chi tiết bài hát này.",
    example_kr: "이 노래는 편하고 아름다워요.",
    example_en: "This song is comfortable and beautiful.",
    example_ja: "この歌は楽で美しいです。",
    example_zh: "这首歌很舒适又美丽。",
    example_vi: "Bài hát này thoải mái và tuyệt đẹp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 고양이를 자세히 묘사해 보세요.",
    prompt_en: "Describe our cat in some detail.",
    prompt_ja: "うちの猫を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我家的猫。",
    prompt_vi: "Hãy miêu tả chi tiết con mèo nhà tôi.",
    example_kr: "우리 집 고양이는 조용하고 귀여워요.",
    example_en: "Our cat is quiet and cute.",
    example_ja: "うちの猫は静かでかわいいです。",
    example_zh: "我家的猫很安静又可爱。",
    example_vi: "Con mèo nhà tôi yên tĩnh và đáng yêu.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    prompt_ja: "このカフェを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这家咖啡厅。",
    prompt_vi: "Hãy miêu tả chi tiết quán cà phê này.",
    example_kr: "이 카페는 조용하고 커요.",
    example_en: "This cafe is quiet and big.",
    example_ja: "このカフェは静かで大きいです。",
    example_zh: "这家咖啡厅很安静又大。",
    example_vi: "Quán cà phê này yên tĩnh và to.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    prompt_ja: "ソウルを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下首尔。",
    prompt_vi: "Hãy miêu tả chi tiết Seoul.",
    example_kr: "서울은 작고 시끄러워요.",
    example_en: "Seoul is small and loud.",
    example_ja: "ソウルは小さくてうるさいです。",
    example_zh: "首尔很小又吵闹。",
    example_vi: "Seoul nhỏ và ồn ào.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 강아지를 자세히 묘사해 보세요.",
    prompt_en: "Describe our dog in some detail.",
    prompt_ja: "うちの犬を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我家的狗。",
    prompt_vi: "Hãy miêu tả chi tiết con chó nhà tôi.",
    example_kr: "우리 집 강아지는 아름답고 예뻐요.",
    example_en: "Our dog is beautiful and pretty.",
    example_ja: "うちの犬は美しくてきれいです。",
    example_zh: "我家的狗很美丽又漂亮。",
    example_vi: "Con chó nhà tôi tuyệt đẹp và xinh xắn.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    prompt_ja: "私たちの学校を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们学校。",
    prompt_vi: "Hãy miêu tả chi tiết trường của tôi.",
    example_kr: "우리 학교는 편하고 조용해요.",
    example_en: "My school is comfortable and quiet.",
    example_ja: "私たちの学校は楽で静かです。",
    example_zh: "我们学校很舒适又安静。",
    example_vi: "Trường của tôi thoải mái và yên tĩnh.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    prompt_ja: "私のかばんを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的包。",
    prompt_vi: "Hãy miêu tả chi tiết chiếc túi của tôi.",
    example_kr: "제 가방은 편하고 따뜻해요.",
    example_en: "My bag is comfortable and warm.",
    example_ja: "私のかばんは楽で暖かいです。",
    example_zh: "我的包很舒适又温暖。",
    example_vi: "Chiếc túi của tôi thoải mái và ấm áp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    prompt_ja: "このケーキを詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这个蛋糕。",
    prompt_vi: "Hãy miêu tả chi tiết chiếc bánh này.",
    example_kr: "이 케이크는 크고 친절해요.",
    example_en: "This cake is big and kind.",
    example_ja: "このケーキは大きくて親切です。",
    example_zh: "这个蛋糕很大又亲切。",
    example_vi: "Chiếc bánh này to và thân thiện.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    prompt_ja: "私の町を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们的社区。",
    prompt_vi: "Hãy miêu tả chi tiết khu phố của tôi.",
    example_kr: "우리 동네는 멋있고 편해요.",
    example_en: "My neighborhood is cool and comfortable.",
    example_ja: "私の町はかっこよくて楽です。",
    example_zh: "我们的社区很帅气又舒适。",
    example_vi: "Khu phố của tôi ngầu và thoải mái.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    prompt_ja: "私の友達を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的朋友。",
    prompt_vi: "Hãy miêu tả chi tiết người bạn của tôi.",
    example_kr: "제 친구는 작고 아름다워요.",
    example_en: "My friend is small and beautiful.",
    example_ja: "私の友達は小さくて美しいです。",
    example_zh: "我的朋友很小又美丽。",
    example_vi: "Bạn của tôi nhỏ và tuyệt đẹp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    prompt_ja: "私の部屋を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我的房间。",
    prompt_vi: "Hãy miêu tả chi tiết căn phòng của tôi.",
    example_kr: "제 방은 깨끗하고 시끄러워요.",
    example_en: "My room is clean and loud.",
    example_ja: "私の部屋は清潔でうるさいです。",
    example_zh: "我的房间很干净又吵闹。",
    example_vi: "Phòng của tôi sạch sẽ và ồn ào.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    prompt_ja: "この映画を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下这部电影。",
    prompt_vi: "Hãy miêu tả chi tiết bộ phim này.",
    example_kr: "이 영화는 작고 복잡해요.",
    example_en: "This movie is small and crowded.",
    example_ja: "この映画は小さくて複雑です。",
    example_zh: "这部电影很小又复杂。",
    example_vi: "Bộ phim này nhỏ và phức tạp.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    prompt_ja: "うちの父を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我爸爸。",
    prompt_vi: "Hãy miêu tả chi tiết bố của tôi.",
    example_kr: "우리 아빠는 복잡하고 커요.",
    example_en: "My dad is crowded and big.",
    example_ja: "うちの父は複雑で大きいです。",
    example_zh: "我爸爸很复杂又大。",
    example_vi: "Bố tôi phức tạp và to.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    prompt_ja: "うちの母を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我妈妈。",
    prompt_vi: "Hãy miêu tả chi tiết mẹ của tôi.",
    example_kr: "우리 엄마는 복잡하고 시끄러워요.",
    example_en: "My mom is crowded and loud.",
    example_ja: "うちの母は複雑でうるさいです。",
    example_zh: "我妈妈很复杂又吵闹。",
    example_vi: "Mẹ tôi phức tạp và ồn ào.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    prompt_ja: "私たちの先生を詳しく描写してみましょう。",
    prompt_zh: "请详细描述一下我们老师。",
    prompt_vi: "Hãy miêu tả chi tiết giáo viên của tôi.",
    example_kr: "우리 선생님은 유명하고 작아요.",
    example_en: "Our teacher is famous and small.",
    example_ja: "私たちの先生は有名で小さいです。",
    example_zh: "我们老师很有名又小。",
    example_vi: "Giáo viên của tôi nổi tiếng và nhỏ.",
  },
];
