import type { RawPrompt } from "./types";

export const WRITING_B1_DESCRIPTION: RawPrompt[] = [
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    example_kr: "제 가방은 따뜻하고 예뻐요.",
    example_en: "My bag is warm and pretty.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    example_kr: "이 케이크는 복잡하고 멋있어요.",
    example_en: "This cake is crowded and cool.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    example_kr: "우리 동네는 복잡하고 조용해요.",
    example_en: "My neighborhood is crowded and quiet.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    example_kr: "제 친구는 멋있고 귀여워요.",
    example_en: "My friend is cool and cute.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    example_kr: "제 방은 친절하고 맛있어요.",
    example_en: "My room is kind and delicious.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    example_kr: "이 영화는 맛있고 커요.",
    example_en: "This movie is delicious and big.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    example_kr: "우리 아빠는 귀엽고 커요.",
    example_en: "My dad is cute and big.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    example_kr: "우리 엄마는 예쁘고 멋있어요.",
    example_en: "My mom is pretty and cool.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    example_kr: "우리 선생님은 복잡하고 친절해요.",
    example_en: "Our teacher is crowded and kind.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    example_kr: "이 노래는 멋있고 맛있어요.",
    example_en: "This song is cool and delicious.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 고양이를 자세히 묘사해 보세요.",
    prompt_en: "Describe our cat in some detail.",
    example_kr: "우리 집 고양이는 친절하고 작아요.",
    example_en: "Our cat is kind and small.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    example_kr: "이 카페는 귀엽고 편해요.",
    example_en: "This cafe is cute and comfortable.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    example_kr: "서울은 친절하고 예뻐요.",
    example_en: "Seoul is kind and pretty.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 강아지를 자세히 묘사해 보세요.",
    prompt_en: "Describe our dog in some detail.",
    example_kr: "우리 집 강아지는 유명하고 깨끗해요.",
    example_en: "Our dog is famous and clean.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    example_kr: "우리 학교는 조용하고 시끄러워요.",
    example_en: "My school is quiet and loud.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    example_kr: "제 가방은 시끄럽고 귀여워요.",
    example_en: "My bag is loud and cute.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    example_kr: "이 케이크는 복잡하고 편해요.",
    example_en: "This cake is crowded and comfortable.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    example_kr: "우리 동네는 예쁘고 유명해요.",
    example_en: "My neighborhood is pretty and famous.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    example_kr: "제 친구는 귀엽고 복잡해요.",
    example_en: "My friend is cute and crowded.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    example_kr: "제 방은 친절하고 유명해요.",
    example_en: "My room is kind and famous.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    example_kr: "이 영화는 예쁘고 맛있어요.",
    example_en: "This movie is pretty and delicious.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    example_kr: "우리 아빠는 맛있고 아름다워요.",
    example_en: "My dad is delicious and beautiful.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    example_kr: "우리 엄마는 따뜻하고 깨끗해요.",
    example_en: "My mom is warm and clean.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    example_kr: "우리 선생님은 맛있고 유명해요.",
    example_en: "Our teacher is delicious and famous.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    example_kr: "이 노래는 편하고 아름다워요.",
    example_en: "This song is comfortable and beautiful.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 고양이를 자세히 묘사해 보세요.",
    prompt_en: "Describe our cat in some detail.",
    example_kr: "우리 집 고양이는 조용하고 귀여워요.",
    example_en: "Our cat is quiet and cute.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    example_kr: "이 카페는 조용하고 커요.",
    example_en: "This cafe is quiet and big.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    example_kr: "서울은 작고 시끄러워요.",
    example_en: "Seoul is small and loud.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 집 강아지를 자세히 묘사해 보세요.",
    prompt_en: "Describe our dog in some detail.",
    example_kr: "우리 집 강아지는 아름답고 예뻐요.",
    example_en: "Our dog is beautiful and pretty.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    example_kr: "우리 학교는 편하고 조용해요.",
    example_en: "My school is comfortable and quiet.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    example_kr: "제 가방은 편하고 따뜻해요.",
    example_en: "My bag is comfortable and warm.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    example_kr: "이 케이크는 크고 친절해요.",
    example_en: "This cake is big and kind.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    example_kr: "우리 동네는 멋있고 편해요.",
    example_en: "My neighborhood is cool and comfortable.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    example_kr: "제 친구는 작고 아름다워요.",
    example_en: "My friend is small and beautiful.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    example_kr: "제 방은 깨끗하고 시끄러워요.",
    example_en: "My room is clean and loud.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    example_kr: "이 영화는 작고 복잡해요.",
    example_en: "This movie is small and crowded.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    example_kr: "우리 아빠는 복잡하고 커요.",
    example_en: "My dad is crowded and big.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    example_kr: "우리 엄마는 복잡하고 시끄러워요.",
    example_en: "My mom is crowded and loud.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    example_kr: "우리 선생님은 유명하고 작아요.",
    example_en: "Our teacher is famous and small.",
  },
];
