import type { RawPrompt } from "./types";

export const WRITING_B1_DESCRIPTION: RawPrompt[] = [
  {
    level: "B1",
    genre: "description",
    prompt_kr: "기억에 남는 장소에 대해 다섯 문장으로 묘사해 보세요. '-는데'를 사용하세요.",
    prompt_en: "Write five sentences describing a memorable place. Use '-는데'.",
    example_kr: "제가 자주 가던 바닷가 마을이 있는데 지금도 눈을 감으면 떠올라요. 그곳은 작은 어촌 마을인데 사람들이 다 친절했어요. 바다가 코앞에 있는데 아침마다 파도 소리가 들렸어요. 골목마다 낡은 집이 있는데 그 모습이 오히려 정겨웠어요. 언젠가 꼭 다시 가 보고 싶은 곳이에요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "성격이 독특한 사람에 대해 다섯 문장으로 묘사해 보세요. '-는 반면에'를 사용하세요.",
    prompt_en: "Write five sentences describing someone with a distinctive personality. Use '-는 반면에'.",
    example_kr: "제 이모는 겉으로는 무뚝뚝한 반면에 속마음은 누구보다 따뜻해요. 말수는 적은 반면에 행동으로 마음을 표현하는 편이에요. 낯선 사람 앞에서는 어색해하는 반면에 가족 앞에서는 장난도 많이 쳐요. 계획을 잘 안 세우는 반면에 막상 일이 생기면 침착하게 처리해요. 그런 이모의 모습이 저에게는 늘 신기하고 존경스러워요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "요리하는 과정을 순서대로 다섯 문장으로 묘사해 보세요. '-은 후에'를 사용하세요.",
    prompt_en: "Write five sentences describing the process of cooking a dish, in order. Use '-은 후에'.",
    example_kr: "먼저 재료를 깨끗이 씻은 후에 알맞은 크기로 썰어요. 채소를 썬 후에 팬에 기름을 두르고 볶아요. 고기를 넣은 후에는 중불에서 충분히 익혀요. 양념을 넣은 후에 국물이 자작해질 때까지 끓여요. 마지막으로 불을 끈 후에 파를 조금 올리면 완성이에요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "어릴 적 살던 동네를 다섯 문장으로 묘사해 보세요. '-던'을 사용하세요.",
    prompt_en: "Write five sentences describing the neighborhood you grew up in. Use '-던'.",
    example_kr: "제가 어릴 때 살던 동네는 낮은 건물들이 모여 있는 조용한 곳이었어요. 매일 뛰어놀던 골목 끝에는 작은 슈퍼가 있었어요. 친구들과 자주 모이던 놀이터는 나무 그늘이 시원했어요. 자주 걷던 길가에는 오래된 담벼락이 이어져 있었어요. 지금도 그 풍경을 떠올리면 마음이 따뜻해져요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "존경하는 선생님이나 어른을 다섯 문장으로 묘사해 보세요. '-을 정도로'를 사용하세요.",
    prompt_en: "Write five sentences describing a teacher or elder you admire. Use '-을 정도로'.",
    example_kr: "제 담임 선생님은 학생 이름을 다 외울 정도로 세심하셨어요. 수업 준비를 밤늦게까지 하실 정도로 열정적이었어요. 학생들이 존경할 정도로 항상 공정하게 대해 주셨어요. 힘든 일이 있을 때는 밤새 상담해 주실 정도로 따뜻한 분이었어요. 지금도 가끔 그 선생님이 그리워요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "복잡한 도심의 풍경을 다섯 문장으로 묘사해 보세요. '-는 가운데'를 사용하세요.",
    prompt_en: "Write five sentences describing a bustling downtown scene. Use '-는 가운데'.",
    example_kr: "출근길 사람들이 바쁘게 걷는 가운데 거리는 활기로 가득해요. 자동차 소리가 시끄럽게 울리는 가운데 신호등마다 사람들이 모여 있어요. 건물마다 화려한 간판이 반짝이는 가운데 카페에서는 커피 향이 흘러나와요. 노점상들이 소리치는 가운데 지나가는 사람들은 발걸음을 재촉해요. 복잡하지만 그 안에서도 도시만의 활력이 느껴져요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "가장 편안하게 느끼는 사람의 성격을 다섯 문장으로 묘사해 보세요. '-는 편이에요'를 사용하세요.",
    prompt_en: "Write five sentences describing the personality of someone you feel most comfortable around. Use '-는 편이에요'.",
    example_kr: "제 친구는 남의 말을 끝까지 잘 들어주는 편이에요. 화를 잘 안 내고 늘 차분한 편이에요. 어떤 이야기를 해도 있는 그대로 받아 주는 편이라 편해요. 먼저 나서기보다는 뒤에서 조용히 챙겨 주는 편이에요. 그래서 그 친구 앞에서는 편하게 제 모습을 보여 줄 수 있어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "아침 출근길 풍경을 다섯 문장으로 묘사해 보세요. '-으면서'를 사용하세요.",
    prompt_en: "Write five sentences describing the scene during your morning commute. Use '-으면서'.",
    example_kr: "사람들은 커피를 마시면서 지하철을 기다려요. 저는 음악을 들으면서 계단을 내려가요. 사람들이 서로 부딪히면서도 무표정하게 걸어가요. 저는 스마트폰을 보면서도 발밑을 조심해요. 그렇게 정신없이 걸으면서 하루가 시작돼요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "특별한 날 입었던 옷차림을 다섯 문장으로 묘사해 보세요. '-은 채로'를 사용하세요.",
    prompt_en: "Write five sentences describing an outfit you wore on a special day. Use '-은 채로'.",
    example_kr: "그날은 오랜만에 정장을 갖춰 입은 채로 집을 나섰어요. 넥타이를 단정히 맨 채로 거울을 여러 번 확인했어요. 구두를 신은 채로 익숙하지 않은 걸음걸이가 어색했어요. 향수를 살짝 뿌린 채로 긴장한 마음을 감췄어요. 평소와 다른 모습이었지만 스스로도 만족스러웠어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "여러 감정이 섞인 표정을 짓던 사람에 대해 다섯 문장으로 묘사해 보세요. '-으면서도'를 사용하세요.",
    prompt_en: "Write five sentences describing someone whose expression mixed several emotions. Use '-으면서도'.",
    example_kr: "그분은 웃으면서도 눈에는 슬픔이 비쳤어요. 담담하게 말하면서도 목소리는 조금 떨렸어요. 씩씩한 척하면서도 손은 계속 만지작거리셨어요. 괜찮다고 하면서도 표정은 그렇지 않았어요. 그 복잡한 표정이 오래도록 기억에 남았어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "동네의 오래된 시장을 다섯 문장으로 묘사해 보세요. '-는 데다가'를 사용하세요.",
    prompt_en: "Write five sentences describing an old neighborhood market. Use '-는 데다가'.",
    example_kr: "동네 시장은 물건이 신선한 데다가 가격도 저렴해요. 상인들이 친절한 데다가 덤도 자주 얹어 줘요. 골목마다 활기가 넘치는 데다가 냄새도 구수해요. 오래된 가게가 많은 데다가 세월의 흔적이 그대로 남아 있어요. 그래서 저는 이 시장을 걸을 때마다 마음이 편안해져요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "성격이 정반대인 두 친구를 다섯 문장으로 묘사해 보세요. '-는 대신에'를 사용하세요.",
    prompt_en: "Write five sentences describing two friends with opposite personalities. Use '-는 대신에'.",
    example_kr: "한 친구는 말이 많은 대신에 늘 분위기를 밝게 만들어요. 다른 친구는 조용한 대신에 깊이 있는 이야기를 잘해요. 한 친구는 계획적인 대신에 가끔 융통성이 부족해요. 다른 친구는 즉흥적인 대신에 늘 새로운 아이디어를 내요. 성격은 다르지만 둘 다 저에게 소중한 친구예요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "비 오는 날의 거리 풍경을 다섯 문장으로 묘사해 보세요. '-을 때마다'를 사용하세요.",
    prompt_en: "Write five sentences describing a rainy street. Use '-을 때마다'.",
    example_kr: "비가 내릴 때마다 거리에는 우산들이 물결처럼 움직여요. 바람이 불 때마다 우산이 뒤집힐 듯 흔들려요. 자동차가 지나갈 때마다 물이 튀어서 사람들이 피해요. 빗방울이 창문을 두드릴 때마다 카페 안 사람들은 창밖을 바라봐요. 저는 이런 비 오는 거리 풍경을 왠지 좋아해요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "매일 반복되는 출퇴근 과정을 다섯 문장으로 묘사해 보세요. '-자마자'를 사용하세요.",
    prompt_en: "Write five sentences describing your daily commute routine step by step. Use '-자마자'.",
    example_kr: "알람이 울리자마자 저는 몸을 일으켜요. 씻고 나오자마자 커피를 한 잔 내려요. 집을 나서자마자 지하철역까지 빠르게 걸어요. 지하철에 타자마자 자리를 찾아 앉아요. 회사에 도착하자마자 하루 일정을 확인하고 업무를 시작해요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "낯선 도시에서 처음 본 풍경을 다섯 문장으로 묘사해 보세요. '-어 보니까'를 사용하세요.",
    prompt_en: "Write five sentences describing the first sights of an unfamiliar city. Use '-어 보니까'.",
    example_kr: "역에서 내려 보니까 낯선 언어의 간판들이 눈에 들어왔어요. 거리를 걸어 보니까 건물마다 색이 다양해서 신기했어요. 사람들을 지켜보니까 걸음이 유난히 빠르다는 걸 느꼈어요. 조금 더 돌아다녀 보니까 골목마다 작은 카페가 숨어 있었어요. 처음에는 낯설었지만 걸어 보니까 그 도시만의 매력이 보였어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "할머니나 할아버지의 손을 다섯 문장으로 묘사해 보세요. '-을 만큼'을 사용하세요.",
    prompt_en: "Write five sentences describing a grandparent's hands. Use '-을 만큼'.",
    example_kr: "할머니의 손은 세월이 느껴질 만큼 주름이 많았어요. 그 손은 평생 일하셨다는 걸 알 수 있을 만큼 거칠었어요. 그런데도 저를 만질 때는 놀랄 만큼 부드러웠어요. 손끝마다 온기가 남아 있을 만큼 따뜻했어요. 저는 그 손을 볼 때마다 할머니의 삶이 느껴졌어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "청소를 마친 후 방의 모습을 다섯 문장으로 묘사해 보세요. '-어 놓다'를 사용하세요.",
    prompt_en: "Write five sentences describing your room after cleaning it. Use '-어 놓다'.",
    example_kr: "책상 위 물건들을 다 정리해 놓았어요. 옷은 색깔별로 옷장에 걸어 놓았어요. 바닥에 있던 짐들도 상자에 담아 놓았어요. 창문을 활짝 열어 놓아서 방 안 공기가 상쾌해졌어요. 이렇게 깔끔하게 정리해 놓으니 마음까지 개운해졌어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "회사 사무실의 분위기를 다섯 문장으로 묘사해 보세요. '-는 편이에요'를 사용하세요.",
    prompt_en: "Write five sentences describing the atmosphere of your office. Use '-는 편이에요'.",
    example_kr: "저희 사무실은 비교적 조용한 편이에요. 다들 자기 일에 집중하는 편이라 잡담이 적어요. 상사들도 자유롭게 의견을 말하도록 배려하는 편이에요. 회의는 짧고 간결하게 진행되는 편이에요. 그래서 저는 이 분위기가 일하기에 편하다고 느껴요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "낮과 밤이 완전히 다른 동네를 다섯 문장으로 묘사해 보세요. '-는 반면에'를 사용하세요.",
    prompt_en: "Write five sentences describing a neighborhood that feels completely different by day and night. Use '-는 반면에'.",
    example_kr: "낮에는 거리가 한산한 반면에 밤이 되면 사람들로 붐벼요. 낮에는 상점 대부분이 조용한 반면에 밤에는 네온사인이 화려하게 켜져요. 낮에는 조용한 골목인 반면에 밤에는 음악 소리가 흘러나와요. 낮에는 사람들이 무표정한 반면에 밤에는 즐거운 표정이 많아요. 같은 동네인데도 시간에 따라 전혀 다른 얼굴을 가진 것 같아요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "친구가 좋아하는 것과 싫어하는 것을 다섯 문장으로 묘사해 보세요. '-는 것을 좋아해요'를 사용하세요.",
    prompt_en: "Write five sentences describing what a friend likes and dislikes. Use '-는 것을 좋아해요'.",
    example_kr: "제 친구는 새로운 음식을 시도하는 것을 좋아해요. 낯선 곳을 여행하는 것도 좋아해요. 반면에 계획 없이 움직이는 것은 싫어해요. 사람 많은 곳에서 오래 있는 것도 좋아하지 않아요. 그래서 여행을 갈 때마다 미리 일정을 꼼꼼히 짜는 편이에요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "직장 상사의 업무 스타일을 다섯 문장으로 묘사해 보세요. '-는 편이라서'를 사용하세요.",
    prompt_en: "Write five sentences describing your boss's working style. Use '-는 편이라서'.",
    example_kr: "저희 부장님은 결정을 빨리 내리는 편이라서 일이 늦어지지 않아요. 지시가 명확한 편이라서 오해가 생길 일이 적어요. 다만 세부 사항까지 챙기는 편이라서 가끔 부담스러울 때도 있어요. 그래도 팀원을 잘 챙기는 편이라서 믿음이 가요. 저는 이런 스타일 덕분에 오히려 배우는 게 많아요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "이른 새벽 시장의 풍경을 다섯 문장으로 묘사해 보세요. '-기 전에'를 사용하세요.",
    prompt_en: "Write five sentences describing an early morning market. Use '-기 전에'.",
    example_kr: "해가 뜨기 전에 상인들은 이미 자리를 정리하고 있어요. 손님이 오기 전에 채소를 진열해 놓아요. 첫 손님이 도착하기 전에 생선을 얼음 위에 가지런히 올려요. 시장이 붐비기 전에 조용한 새벽 공기가 흘러요. 하루가 시작되기 전에 이미 많은 사람들의 손길이 스쳐 지나가요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "친구의 웃는 모습을 다섯 문장으로 묘사해 보세요. '-을 때면'을 사용하세요.",
    prompt_en: "Write five sentences describing a friend's smile. Use '-을 때면'.",
    example_kr: "그 친구는 웃을 때면 눈이 반달 모양이 돼요. 크게 웃을 때면 주변까지 밝아지는 느낌이 들어요. 장난스럽게 웃을 때면 어린아이 같은 표정이 나와요. 진심으로 기뻐서 웃을 때면 얼굴 전체가 환해져요. 저는 친구의 그 웃는 모습을 볼 때면 저절로 기분이 좋아져요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "집 근처 공원의 사계절 모습을 다섯 문장으로 묘사해 보세요. '-어지다'를 사용하세요.",
    prompt_en: "Write five sentences describing how a nearby park changes through the seasons. Use '-어지다'.",
    example_kr: "봄이 되면 공원 벚꽃이 활짝 피어져요. 여름에는 나뭇잎이 짙어져서 그늘이 넓어져요. 가을에는 잔디가 노랗게 물들어져요. 겨울에는 나뭇가지가 앙상해지고 조용해져요. 계절마다 공원의 분위기가 완전히 달라져요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "새로 산 물건을 다섯 문장으로 묘사해 보세요. '-을 만하다'를 사용하세요.",
    prompt_en: "Write five sentences describing a newly bought item. Use '-을 만하다'.",
    example_kr: "새로 산 의자는 값을 지불할 만한 가치가 있었어요. 앉아 보니 등이 편할 만큼 디자인이 좋았어요. 오래 써도 흔들리지 않을 만큼 튼튼해 보여요. 색깔도 방 분위기와 잘 어울릴 만해서 만족스러워요. 주변 사람들에게도 추천할 만한 물건이라고 생각해요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "어색했던 첫 만남 상대의 인상을 다섯 문장으로 묘사해 보세요. '-어 보였어요'를 사용하세요.",
    prompt_en: "Write five sentences describing your first impression of someone you met awkwardly. Use '-어 보였어요'.",
    example_kr: "그 사람은 처음에 조금 차가워 보였어요. 말투는 딱딱해 보였지만 눈빛은 부드러워 보였어요. 표정이 긴장돼 보여서 저도 덩달아 어색했어요. 시간이 지나니 훨씬 편안해 보였어요. 나중에는 처음 인상과 다르게 다정해 보였어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "직장 동료의 책상을 다섯 문장으로 묘사해 보세요. '-어 두다'를 사용하세요.",
    prompt_en: "Write five sentences describing a coworker's desk. Use '-어 두다'.",
    example_kr: "그 동료는 서류를 항상 색깔별로 정리해 두어요. 필요한 자료는 가까운 곳에 놓아 두는 편이에요. 화분도 하나 키워서 책상 위에 올려 두었어요. 가족사진도 눈에 잘 보이는 자리에 붙여 두었어요. 그런 작은 정성이 책상 전체를 따뜻하게 만들어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "여행 중 묵었던 숙소를 다섯 문장으로 묘사해 보세요. '-치고는'을 사용하세요.",
    prompt_en: "Write five sentences describing the accommodation you stayed at during a trip. Use '-치고는'.",
    example_kr: "그 숙소는 저렴한 가격치고는 시설이 깨끗했어요. 작은 마을치고는 시설이 현대적이었어요. 숙박객이 많은 곳치고는 조용한 분위기였어요. 첫 방문객치고는 직원들이 세심하게 안내해 줬어요. 다음에 그 지역을 다시 가면 꼭 그 숙소에 묵고 싶어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "가장 좋아하는 계절의 냄새와 분위기를 다섯 문장으로 묘사해 보세요. '-는 냄새가 나요'를 사용하세요.",
    prompt_en: "Write five sentences describing the smell and mood of your favorite season. Use '-는 냄새가 나요'.",
    example_kr: "가을이 되면 거리에서 낙엽 타는 냄새가 나요. 아침 공기에서는 서늘한 냄새가 나요. 시장을 지나면 군고구마 익는 냄새가 나요. 카페 앞에서는 진한 커피 냄새가 나요. 그런 냄새를 맡으면 저는 가을이 왔다는 걸 실감해요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "오래된 가구가 있는 방을 다섯 문장으로 묘사해 보세요. '-은 지'를 사용하세요.",
    prompt_en: "Write five sentences describing a room with old furniture. Use '-은 지'.",
    example_kr: "그 나무 책상은 산 지 벌써 이십 년이 넘었어요. 낡은 지 오래됐지만 아직도 튼튼해요. 색이 바랜 지 오래돼서 처음 색깔이 잘 기억나지 않아요. 흔들거리기 시작한 지는 몇 년 됐지만 고쳐서 계속 쓰고 있어요. 그 가구를 볼 때마다 오랜 세월이 느껴져요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "직장에서 자주 마주치는 사람의 말투를 다섯 문장으로 묘사해 보세요. '-곤 하다'를 사용하세요.",
    prompt_en: "Write five sentences describing a coworker's characteristic way of speaking. Use '-곤 하다'.",
    example_kr: "그 동료는 말 끝에 늘 웃음을 곁들이곤 해요. 설명할 때 손짓을 크게 하곤 해요. 상대방 이름을 자주 불러 주곤 해요. 농담을 섞어 가며 분위기를 부드럽게 만들곤 해요. 그래서 그분과 이야기하면 저도 모르게 편해지곤 해요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "명절 음식이 준비되는 부엌 풍경을 다섯 문장으로 묘사해 보세요. '-으면서'를 사용하세요.",
    prompt_en: "Write five sentences describing a kitchen scene while holiday food is being prepared. Use '-으면서'.",
    example_kr: "엄마는 전을 부치면서 이런저런 이야기를 들려주세요. 이모는 나물을 무치면서 노래를 흥얼거려요. 저는 설거지를 도우면서 냄새를 맡아요. 아이들은 부엌을 기웃거리면서 간식을 몰래 집어 먹어요. 부엌 전체가 웃음소리와 음식 냄새로 가득해요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "새로 생긴 카페의 인테리어를 다섯 문장으로 묘사해 보세요. '-게 되어 있어요'를 사용하세요.",
    prompt_en: "Write five sentences describing the interior of a newly opened café. Use '-게 되어 있어요'.",
    example_kr: "그 카페는 창가 자리에서 밖이 잘 보이게 되어 있어요. 조명이 은은하게 비치게 되어 있어서 아늑한 느낌이에요. 테이블마다 콘센트가 있게 되어 있어서 편리해요. 음악이 너무 크지 않게 되어 있어서 대화하기 좋아요. 전체적으로 편안하게 머물 수 있게 되어 있는 공간이었어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "긴장한 발표자의 모습을 다섯 문장으로 묘사해 보세요. '-을 정도로'를 사용하세요.",
    prompt_en: "Write five sentences describing a nervous presenter. Use '-을 정도로'.",
    example_kr: "그 발표자는 손이 떨릴 정도로 긴장한 것처럼 보였어요. 목소리가 갈라질 정도로 떨었어요. 청중들이 눈치챌 정도로 표정이 굳어 있었어요. 그래도 끝까지 포기하지 않을 정도로 열심히 준비한 티가 났어요. 발표가 끝나자 안심할 정도로 표정이 밝아졌어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "친구의 방 분위기를 다섯 문장으로 묘사해 보세요. '-어 놓았어요'를 사용하세요.",
    prompt_en: "Write five sentences describing the mood of a friend's room. Use '-어 놓았어요'.",
    example_kr: "친구는 벽마다 좋아하는 사진들을 붙여 놓았어요. 책장에는 좋아하는 책들을 종류별로 꽂아 놓았어요. 창가에는 화분을 여러 개 놓아 놓았어요. 침대 옆에는 향초를 켜 놓아서 은은한 향이 났어요. 그 방에 들어가면 친구의 취향이 그대로 느껴졌어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "오래된 친구의 목소리를 다섯 문장으로 묘사해 보세요. '-을 때마다'를 사용하세요.",
    prompt_en: "Write five sentences describing an old friend's voice. Use '-을 때마다'.",
    example_kr: "그 친구는 반가울 때마다 목소리 톤이 확 올라가요. 웃을 때마다 목소리에 장난기가 섞여요. 진지한 이야기를 할 때마다 목소리가 낮아지고 차분해져요. 오랜만에 전화할 때마다 그 목소리만 들어도 안심이 돼요. 시간이 지나도 그 친구의 목소리는 하나도 변하지 않았어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "붐비는 지하철 안 풍경을 다섯 문장으로 묘사해 보세요. '-는 통에'를 사용하세요.",
    prompt_en: "Write five sentences describing a crowded subway scene. Use '-는 통에'.",
    example_kr: "사람들이 한꺼번에 밀려드는 통에 문 앞이 순식간에 붐볐어요. 서로 밀치는 통에 몸이 이리저리 흔들렸어요. 안내 방송이 잘 안 들리는 통에 몇몇 사람들은 당황했어요. 사람이 너무 많은 통에 숨쉬기조차 어려웠어요. 그래도 다들 익숙한 듯 조용히 견디고 있었어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "밤에 홀로 걷는 골목길 풍경을 다섯 문장으로 묘사해 보세요. '-는 듯했어요'를 사용하세요.",
    prompt_en: "Write five sentences describing an alley you walked alone at night. Use '-는 듯했어요'.",
    example_kr: "가로등 불빛이 유난히 흔들리는 듯했어요. 발걸음 소리가 골목 전체에 울리는 듯했어요. 창문마다 불이 꺼져서 마을 전체가 잠든 듯했어요. 고양이 한 마리가 저를 따라오는 듯했어요. 조용한 골목이 오히려 저에게 위로가 되는 듯했어요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "아이들이 뛰노는 놀이터 풍경을 다섯 문장으로 묘사해 보세요. '-는 대로'를 사용하세요.",
    prompt_en: "Write five sentences describing children playing in a playground. Use '-는 대로'.",
    example_kr: "아이들은 마음이 내키는 대로 이리저리 뛰어다녀요. 규칙이 필요하면 자기들끼리 정하는 대로 놀이를 바꿔요. 그네 순서가 오는 대로 서로 자연스럽게 바꿔 타요. 배가 고프면 부모가 부르는 대로 곧장 뛰어가요. 그렇게 자유롭게 노는 모습이 보기만 해도 즐거워요.",
  },
  {
    level: "B1",
    genre: "description",
    prompt_kr: "자주 가는 동네 빨래방의 풍경을 다섯 문장으로 묘사해 보세요. '-는 동안'을 사용하세요.",
    prompt_en: "Write five sentences describing the scene at a neighborhood laundromat. Use '-는 동안'.",
    example_kr: "동네 빨래방은 밤늦게까지 불이 켜져 있어요. 세탁기가 돌아가는 동안 사람들은 각자 휴대폰을 보거나 책을 읽어요. 건조기가 도는 동안 따뜻한 공기와 세제 냄새가 가게 안을 채워요. 기다리는 동안 옆자리 아저씨와 짧게 날씨 이야기를 나누기도 해요. 조용하지만 사람 사는 냄새가 나는 곳이에요.",
  },
];
