import type { RawPrompt } from "./types";

export const WRITING_B1_JOURNAL: RawPrompt[] = [
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 날씨가 어땠어요?",
    prompt_en: "How was the weather yesterday?",
    prompt_ja: "昨日、天気はどうでしたか？",
    prompt_zh: "昨天天气怎么样？",
    example_kr: "어제 비가 많이 와서 집에 있었어요.",
    example_en: "It rained a lot yesterday so I stayed at home.",
    example_ja: "昨日は雨がたくさん降ったので、家にいました。",
    example_zh: "昨天下了很大的雨，所以我待在家里。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 아침에 무엇을 먹었어요?",
    prompt_en: "What did you eat for breakfast yesterday?",
    prompt_ja: "昨日の朝、何を食べましたか？",
    prompt_zh: "你昨天早上吃了什么？",
    example_kr: "어제 아침에 빵을 먹고 커피를 마셨어요.",
    example_en: "I ate bread and drank coffee for breakfast yesterday.",
    example_ja: "昨日の朝はパンを食べて、コーヒーを飲みました。",
    example_zh: "昨天早上我吃了面包，喝了咖啡。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난 주말에 친구를 만났어요?",
    prompt_en: "Did you meet a friend last weekend?",
    prompt_ja: "先週末、友達に会いましたか？",
    prompt_zh: "上周末你见朋友了吗？",
    example_kr: "지난 주말에 친구를 만나서 영화를 봤어요.",
    example_en: "I met a friend and watched a movie last weekend.",
    example_ja: "先週末は友達に会って、映画を見ました。",
    example_zh: "上周末我见了朋友，一起看了电影。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 저녁에 어디에 갔어요?",
    prompt_en: "Where did you go yesterday evening?",
    prompt_ja: "昨日の夜、どこに行きましたか？",
    prompt_zh: "你昨天晚上去哪里了？",
    example_kr: "어제 저녁에 식당에 가서 국수를 먹었어요.",
    example_en: "I went to a restaurant and ate noodles yesterday evening.",
    example_ja: "昨日の夜は食堂に行って、麺を食べました。",
    example_zh: "昨天晚上我去了餐厅，吃了面条。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "오늘 회사에 어떻게 왔어요?",
    prompt_en: "How did you come to work today?",
    prompt_ja: "今日、会社にどうやって来ましたか？",
    prompt_zh: "你今天是怎么来公司的？",
    example_kr: "오늘 지하철을 타고 회사에 빨리 갔어요.",
    example_en: "I took the subway and went to work quickly today.",
    example_ja: "今日は地下鉄に乗って、会社に早く着きました。",
    example_zh: "我今天坐地铁很快就到公司了。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난번에 어떤 책을 읽었어요?",
    prompt_en: "What kind of book did you read last time?",
    prompt_ja: "この前、どんな本を読みましたか？",
    prompt_zh: "你上次读了什么书？",
    example_kr: "지난번에 재미있는 소설을 빌려서 읽었어요.",
    example_en: "I borrowed and read an interesting novel last time.",
    example_ja: "この前、面白い小説を借りて読みました。",
    example_zh: "上次我借了一本有趣的小说来读。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 저녁에 운동을 했어요?",
    prompt_en: "Did you exercise yesterday evening?",
    prompt_ja: "昨日の夜、運動しましたか？",
    prompt_zh: "你昨天晚上运动了吗？",
    example_kr: "어제 저녁에 공원에 가서 조깅을 했어요.",
    example_en: "I went to the park and jogged yesterday evening.",
    example_ja: "昨日の夜は公園に行って、ジョギングをしました。",
    example_zh: "昨天晚上我去公园慢跑了。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 점심에 무엇을 주문했어요?",
    prompt_en: "What did you order for lunch yesterday?",
    prompt_ja: "昨日のお昼、何を注文しましたか？",
    prompt_zh: "你昨天午饭点了什么？",
    example_kr: "어제 점심에 김밥을 시켜서 동료와 먹었어요.",
    example_en: "I ordered gimbap and ate it with a colleague for lunch yesterday.",
    example_ja: "昨日のお昼はキンパを頼んで、同僚と食べました。",
    example_zh: "昨天午饭我点了紫菜包饭，和同事一起吃了。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 부모님께 전화했어요?",
    prompt_en: "Did you call your parents last week?",
    prompt_ja: "先週、ご両親に電話しましたか？",
    prompt_zh: "你上周给父母打电话了吗？",
    example_kr: "지난주에 집에 전화해서 안부를 물었어요.",
    example_en: "I called home and asked about their well-being last week.",
    example_ja: "先週、実家に電話して近況を聞きました。",
    example_zh: "上周我给家里打了电话，问候了一下。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 마트에서 무엇을 샀어요?",
    prompt_en: "What did you buy at the supermarket yesterday?",
    prompt_ja: "昨日、スーパーで何を買いましたか？",
    prompt_zh: "你昨天在超市买了什么？",
    example_kr: "어제 마트에 가서 신선한 과일을 샀어요.",
    example_en: "I went to the supermarket and bought fresh fruit yesterday.",
    example_ja: "昨日はスーパーに行って、新鮮な果物を買いました。",
    example_zh: "昨天我去了超市，买了新鲜的水果。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 무슨 음악을 들었어요?",
    prompt_en: "What kind of music did you listen to yesterday?",
    prompt_ja: "昨日、どんな音楽を聴きましたか？",
    prompt_zh: "你昨天听了什么音乐？",
    example_kr: "어제 방에서 조용한 음악을 틀고 쉬었어요.",
    example_en: "I played quiet music in my room and rested yesterday.",
    example_ja: "昨日は部屋で静かな音楽をかけて休みました。",
    example_zh: "昨天我在房间里放了安静的音乐休息。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 어떤 영화를 봤어요?",
    prompt_en: "What movie did you watch last week?",
    prompt_ja: "先週、どんな映画を見ましたか？",
    prompt_zh: "你上周看了什么电影？",
    example_kr: "지난주에 극장에 가서 슬픈 영화를 봤어요.",
    example_en: "I went to the theater and watched a sad movie last week.",
    example_ja: "先週、映画館に行って悲しい映画を見ました。",
    example_zh: "上周我去电影院看了一部悲伤的电影。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 커피숍에서 누구를 만났어요?",
    prompt_en: "Who did you meet at the coffee shop yesterday?",
    prompt_ja: "昨日、コーヒーショップで誰に会いましたか？",
    prompt_zh: "你昨天在咖啡厅见了谁？",
    example_kr: "어제 카페에 가서 오랜 친구를 만났어요.",
    example_en: "I went to a cafe and met an old friend yesterday.",
    example_ja: "昨日はカフェに行って、久しぶりに友達に会いました。",
    example_zh: "昨天我去咖啡厅见了老朋友。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난 주말에 방청소를 했어요?",
    prompt_en: "Did you clean your room last weekend?",
    prompt_ja: "先週末、部屋の掃除をしましたか？",
    prompt_zh: "你上周末打扫房间了吗？",
    example_kr: "지난 주말에 방을 청소하고 옷을 정리했어요.",
    example_en: "I cleaned my room and organized my clothes last weekend.",
    example_ja: "先週末、部屋を掃除して服を整理しました。",
    example_zh: "上周末我打扫了房间，整理了衣服。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 백화점에 왜 갔어요?",
    prompt_en: "Why did you go to the department store yesterday?",
    prompt_ja: "昨日、どうしてデパートに行きましたか？",
    prompt_zh: "你昨天为什么去了百货商店？",
    example_kr: "어제 백화점에 가서 예쁜 옷을 구경했어요.",
    example_en: "I went to the department store and looked at pretty clothes yesterday.",
    example_ja: "昨日はデパートに行って、かわいい服を見て回りました。",
    example_zh: "昨天我去百货商店逛了漂亮的衣服。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 점심에 무슨 음식을 먹었어요?",
    prompt_en: "What food did you eat for lunch yesterday?",
    prompt_ja: "昨日のお昼、何の食べ物を食べましたか？",
    prompt_zh: "你昨天午饭吃了什么食物？",
    example_kr: "어제 점심에 한식당에 가서 찌개를 먹었어요.",
    example_en: "I went to a Korean restaurant and ate stew for lunch yesterday.",
    example_ja: "昨日のお昼は韓国料理店に行って、チゲを食べました。",
    example_zh: "昨天午饭我去韩式餐厅吃了汤。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난 휴일에 여행을 갔었어요?",
    prompt_en: "Did you go on a trip last holiday?",
    prompt_ja: "この前の休みに旅行に行きましたか？",
    prompt_zh: "上次假期你去旅行了吗？",
    example_kr: "지난 휴일에 바다에 가서 바람을 쐬었어요.",
    example_en: "I went to the sea and got some fresh air last holiday.",
    example_ja: "この前の休みに海に行って、風にあたりました。",
    example_zh: "上次假期我去了海边吹了吹风。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 집에 몇 시에 들어왔어요?",
    prompt_en: "What time did you come home yesterday?",
    prompt_ja: "昨日、何時に家に帰りましたか？",
    prompt_zh: "你昨天几点到家的？",
    example_kr: "어제 일이 늦어져서 밤에 집에 갔어요.",
    example_en: "My work ran late yesterday so I went home at night.",
    example_ja: "昨日は仕事が遅くなって、夜に家に帰りました。",
    example_zh: "昨天工作晚了，所以我很晚才到家。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 요리를 해 먹었어요?",
    prompt_en: "Did you cook and eat last week?",
    prompt_ja: "先週、料理を作って食べましたか？",
    prompt_zh: "你上周自己做饭吃了吗？",
    example_kr: "지난주에 주방에서 카레를 직접 만들었어요.",
    example_en: "I made curry myself in the kitchen last week.",
    example_ja: "先週、台所でカレーを自分で作りました。",
    example_zh: "上周我在厨房亲手做了咖喱。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 사진을 왜 찍었어요?",
    prompt_en: "Why did you take a picture yesterday?",
    prompt_ja: "昨日、どうして写真を撮りましたか？",
    prompt_zh: "你昨天为什么拍照了？",
    example_kr: "어제 예쁜 꽃을 보고 사진을 찍었어요.",
    example_en: "I saw a pretty flower and took a picture yesterday.",
    example_ja: "昨日、きれいな花を見て写真を撮りました。",
    example_zh: "昨天我看到漂亮的花就拍了照片。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 어떤 선물을 받았어요?",
    prompt_en: "What kind of gift did you receive last week?",
    prompt_ja: "先週、どんなプレゼントをもらいましたか？",
    prompt_zh: "你上周收到了什么礼物？",
    example_kr: "지난주에 생일이라서 친구에게 꽃을 받았어요.",
    example_en: "It was my birthday last week so I received flowers from a friend.",
    example_ja: "先週、誕生日だったので友達から花をもらいました。",
    example_zh: "上周是我生日，朋友送了我花。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 저녁에 텔레비전을 봤어요?",
    prompt_en: "Did you watch television yesterday evening?",
    prompt_ja: "昨日の夜、テレビを見ましたか？",
    prompt_zh: "你昨天晚上看电视了吗？",
    example_kr: "어제 거실에서 뉴스를 보며 밥을 먹었어요.",
    example_en: "I ate while watching the news in the living room yesterday.",
    example_ja: "昨日はリビングでニュースを見ながらご飯を食べました。",
    example_zh: "昨天我在客厅一边看新闻一边吃饭。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 도서관에 갔었어요?",
    prompt_en: "Did you go to the library last week?",
    prompt_ja: "先週、図書館に行きましたか？",
    prompt_zh: "你上周去图书馆了吗？",
    example_kr: "지난주에 도서관에 가서 시험 공부를 했어요.",
    example_en: "I went to the library and studied for the exam last week.",
    example_ja: "先週、図書館に行って試験勉強をしました。",
    example_zh: "上周我去图书馆学习准备考试了。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 오후에 커피를 마셨어요?",
    prompt_en: "Did you drink coffee yesterday afternoon?",
    prompt_ja: "昨日の午後、コーヒーを飲みましたか？",
    prompt_zh: "你昨天下午喝咖啡了吗？",
    example_kr: "어제 오후에 카페에 가서 라떼를 마셨어요.",
    example_en: "I went to a cafe and drank a latte yesterday afternoon.",
    example_ja: "昨日の午後、カフェに行ってラテを飲みました。",
    example_zh: "昨天下午我去咖啡厅喝了拿铁。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난 주말에 산에 갔었어요?",
    prompt_en: "Did you go to the mountain last weekend?",
    prompt_ja: "先週末、山に行きましたか？",
    prompt_zh: "你上周末去爬山了吗？",
    example_kr: "지난 주말에 높은 산에 올라가 풍경을 봤어요.",
    example_en: "I climbed a high mountain and saw the scenery last weekend.",
    example_ja: "先週末、高い山に登って景色を見ました。",
    example_zh: "上周末我爬上了高山，看了风景。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 어떤 뉴스를 들었어요?",
    prompt_en: "What news did you hear yesterday?",
    prompt_ja: "昨日、どんなニュースを聞きましたか？",
    prompt_zh: "你昨天听到了什么新闻？",
    example_kr: "어제 라디오를 듣다가 좋은 소식을 들었어요.",
    example_en: "I was listening to the radio yesterday and heard good news.",
    example_ja: "昨日、ラジオを聞いていて良いニュースを聞きました。",
    example_zh: "昨天我听广播时听到了好消息。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 편지를 썼어요?",
    prompt_en: "Did you write a letter last week?",
    prompt_ja: "先週、手紙を書きましたか？",
    prompt_zh: "你上周写信了吗？",
    example_kr: "지난주에 손편지를 써서 친구에게 보냈어요.",
    example_en: "I wrote a handwritten letter and sent it to a friend last week.",
    example_ja: "先週、手書きの手紙を書いて友達に送りました。",
    example_zh: "上周我写了一封手写信寄给了朋友。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 약국에 왜 들렀어요?",
    prompt_en: "Why did you stop by the pharmacy yesterday?",
    prompt_ja: "昨日、どうして薬局に寄りましたか？",
    prompt_zh: "你昨天为什么去了药店？",
    example_kr: "어제 머리가 아파서 약국에 가서 약을 샀어요.",
    example_en: "My head hurt yesterday so I went to the pharmacy and bought medicine.",
    example_ja: "昨日、頭が痛くて薬局に行って薬を買いました。",
    example_zh: "昨天我头疼，所以去药店买了药。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난번에 어떤 옷을 샀어요?",
    prompt_en: "What clothes did you buy last time?",
    prompt_ja: "この前、どんな服を買いましたか？",
    prompt_zh: "你上次买了什么衣服？",
    example_kr: "지난번에 가게에 가서 따뜻한 코트를 샀어요.",
    example_en: "I went to the shop and bought a warm coat last time.",
    example_ja: "この前、お店に行って暖かいコートを買いました。",
    example_zh: "上次我去商店买了一件暖和的外套。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 숙제를 다 끝냈어요?",
    prompt_en: "Did you finish all your homework yesterday?",
    prompt_ja: "昨日、宿題を全部終わらせましたか？",
    prompt_zh: "你昨天作业都做完了吗？",
    example_kr: "어제 밤늦게까지 숙제를 해서 다 끝냈어요.",
    example_en: "I did my homework until late last night and finished it all.",
    example_ja: "昨日は夜遅くまで宿題をして、全部終わらせました。",
    example_zh: "昨天我做作业到很晚，全部做完了。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 동물원에 갔었어요?",
    prompt_en: "Did you go to the zoo last week?",
    prompt_ja: "先週、動物園に行きましたか？",
    prompt_zh: "你上周去动物园了吗？",
    example_kr: "지난주에 동물원에 가서 귀여운 팬더를 봤어요.",
    example_en: "I went to the zoo and saw a cute panda last week.",
    example_ja: "先週、動物園に行ってかわいいパンダを見ました。",
    example_zh: "上周我去了动物园，看到了可爱的熊猫。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 아침에 일찍 일어났어요?",
    prompt_en: "Did you wake up early yesterday morning?",
    prompt_ja: "昨日の朝、早く起きましたか？",
    prompt_zh: "你昨天早上早起了吗？",
    example_kr: "어제 알람을 듣고 일찍 일어나서 준비했어요.",
    example_en: "I heard the alarm, woke up early, and got ready yesterday.",
    example_ja: "昨日はアラームを聞いて早く起きて、準備をしました。",
    example_zh: "昨天我听到闹钟早早起床做了准备。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 누굴 도와주었어요?",
    prompt_en: "Who did you help last week?",
    prompt_ja: "先週、誰を手伝いましたか？",
    prompt_zh: "你上周帮助了谁？",
    example_kr: "지난주에 무거운 가방을 든 할머니를 도왔어요.",
    example_en: "I helped a grandmother carrying a heavy bag last week.",
    example_ja: "先週、重いかばんを持ったおばあさんを手伝いました。",
    example_zh: "上周我帮助了一位拎着重包的老奶奶。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 저녁에 무엇을 만들었어요?",
    prompt_en: "What did you make yesterday evening?",
    prompt_ja: "昨日の夜、何を作りましたか？",
    prompt_zh: "你昨天晚上做了什么菜？",
    example_kr: "어제 저녁에 냉장고의 재료로 볶음밥을 만들었어요.",
    example_en: "I made fried rice with ingredients from the fridge yesterday evening.",
    example_ja: "昨日の夜は冷蔵庫の材料でチャーハンを作りました。",
    example_zh: "昨天晚上我用冰箱里的食材做了炒饭。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난번에 어떤 빵을 구웠어요?",
    prompt_en: "What kind of bread did you bake last time?",
    prompt_ja: "この前、どんなパンを焼きましたか？",
    prompt_zh: "你上次烤了什么面包？",
    example_kr: "지난번에 오븐을 써서 달콤한 케이크를 구웠어요.",
    example_en: "I used the oven and baked a sweet cake last time.",
    example_ja: "この前、オーブンを使って甘いケーキを焼きました。",
    example_zh: "上次我用烤箱烤了甜甜的蛋糕。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 컴퓨터로 무엇을 했어요?",
    prompt_en: "What did you do on the computer yesterday?",
    prompt_ja: "昨日、パソコンで何をしましたか？",
    prompt_zh: "你昨天用电脑做了什么？",
    example_kr: "어제 컴퓨터를 켜서 중요한 문서를 작성했어요.",
    example_en: "I turned on the computer and wrote an important document yesterday.",
    example_ja: "昨日はパソコンをつけて、大事な文書を作成しました。",
    example_zh: "昨天我打开电脑写了重要的文件。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난주에 꽃집에 왜 갔었어요?",
    prompt_en: "Why did you go to the flower shop last week?",
    prompt_ja: "先週、どうして花屋に行きましたか？",
    prompt_zh: "你上周为什么去了花店？",
    example_kr: "지난주에 꽃집에 가서 예쁜 장미를 골랐어요.",
    example_en: "I went to the flower shop and picked pretty roses last week.",
    example_ja: "先週、花屋に行って、きれいなバラを選びました。",
    example_zh: "上周我去花店挑选了漂亮的玫瑰。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "어제 미술관에 갔었어요?",
    prompt_en: "Did you go to the art museum yesterday?",
    prompt_ja: "昨日、美術館に行きましたか？",
    prompt_zh: "你昨天去美术馆了吗？",
    example_kr: "어제 미술관에 가서 멋진 그림을 감상했어요.",
    example_en: "I went to the art museum and appreciated wonderful paintings yesterday.",
    example_ja: "昨日、美術館に行って、すてきな絵を鑑賞しました。",
    example_zh: "昨天我去美术馆欣赏了精美的画作。",
  },
  {
    level: "B1",
    genre: "journal",
    prompt_kr: "지난 주말에 무엇을 타 봤어요?",
    prompt_en: "What did you try riding last weekend?",
    prompt_ja: "先週末、何に乗ってみましたか？",
    prompt_zh: "上周末你骑了什么？",
    example_kr: "지난 주말에 자전거를 빌려서 신나게 탔어요.",
    example_en: "I rented a bicycle and rode it excitedly last weekend.",
    example_ja: "先週末、自転車を借りて楽しく乗りました。",
    example_zh: "上周末我租了自行车，开心地骑了一圈。",
  },
];
