import type { RawPrompt } from "./types";

export const WRITING_B1_OPINION: RawPrompt[] = [
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "재택근무와 사무실 출근 중 어느 쪽이 더 좋다고 생각하는지 서너 문장으로 써 보세요. '-는 반면에'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether remote work or office work is better. Use '-는 반면에'.",
    example_kr: "저는 재택근무가 더 좋다고 생각해요. 출퇴근 시간이 절약되는 반면에 사무실에서는 그 시간이 그대로 낭비돼요. 물론 동료와의 소통은 사무실이 더 편한 반면에 집중력은 집에서 일할 때 더 높아요. 결국 저에게는 재택근무의 장점이 더 크다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "아이들에게 용돈을 정해진 날짜에 주는 것이 좋다고 생각하는지 서너 문장으로 써 보세요. '-어야 한다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether children should get allowance on a fixed schedule. Use '-어야 한다고 생각해요'.",
    example_kr: "저는 아이들에게 정해진 날짜에 용돈을 줘야 한다고 생각해요. 그래야 아이들이 계획적으로 돈을 쓰는 법을 배울 수 있어요. 필요할 때마다 그때그때 줘야 한다고 생각하면 오히려 돈의 가치를 모르게 될 수도 있어요. 그래서 저는 규칙적인 용돈이 더 교육적이라고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "대중교통 요금을 올리는 것에 찬성하는지 서너 문장으로 써 보세요. '-을 수밖에 없어요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether raising public transit fares is justified. Use '-을 수밖에 없어요'.",
    example_kr: "저는 대중교통 요금 인상에 찬성하는 편이에요. 유지 비용이 계속 오르면 요금도 함께 오를 수밖에 없어요. 요금이 너무 낮으면 서비스의 질이 떨어질 수밖에 없다고 생각해요. 다만 저소득층을 위한 할인 제도는 반드시 함께 마련되어야 한다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "직장에서 나이보다 실력이 중요하다고 생각하는지 서너 문장으로 써 보세요. '-다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether ability matters more than age at work. Use '-다고 생각해요'.",
    example_kr: "저는 직장에서는 나이보다 실력이 더 중요하다고 생각해요. 경험도 물론 중요하지만 결과를 내는 능력이 더 우선이라고 생각해요. 나이만 많다고 무조건 존중받아야 한다고는 생각하지 않아요. 그래서 승진이나 평가도 나이가 아니라 실력을 기준으로 이루어져야 한다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "학교에서 교복을 입는 것에 찬성하는지 서너 문장으로 써 보세요. '-는 편이 낫다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether schools should require uniforms. Use '-는 편이 낫다고 봐요'.",
    example_kr: "저는 교복을 입는 편이 낫다고 봐요. 매일 옷을 고민하지 않아도 되니 시간이 절약되기 때문이에요. 또한 경제적 차이가 옷차림으로 드러나지 않는 편이 낫다고 봐요. 물론 개성을 표현할 기회가 줄어드는 단점도 있지만 저는 장점이 더 크다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "반려동물을 키우기 전에 자격시험 같은 것이 필요하다고 생각하는지 서너 문장으로 써 보세요. '-을 필요가 있어요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether people should pass a test before owning a pet. Use '-을 필요가 있어요'.",
    example_kr: "저는 반려동물을 키우기 전에 최소한의 교육을 받을 필요가 있다고 생각해요. 준비 없이 키우다가 결국 포기하는 경우를 많이 봤기 때문이에요. 책임감을 확인할 방법이 있어야 유기 동물 문제도 줄일 필요가 있어요. 시험까지는 아니더라도 기본적인 교육 과정 정도는 필요하다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "온라인 수업이 오프라인 수업보다 효과적이라고 생각하는지 서너 문장으로 써 보세요. '-다고 보기는 어려워요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether online classes are more effective than in-person ones. Use '-다고 보기는 어려워요'.",
    example_kr: "저는 온라인 수업이 오프라인 수업보다 무조건 효과적이라고 보기는 어려워요. 시간과 장소의 제약이 적다는 장점은 있지만 집중력은 떨어지는 경우가 많아요. 특히 실습이 필요한 과목은 온라인만으로 충분하다고 보기는 어려워요. 그래서 두 방식을 적절히 병행하는 것이 가장 좋다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "결혼식에 많은 돈을 쓰는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-을 필요는 없다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on spending a lot of money on weddings. Use '-을 필요는 없다고 생각해요'.",
    example_kr: "저는 결혼식에 지나치게 많은 돈을 쓸 필요는 없다고 생각해요. 결혼식은 하루뿐이지만 결혼 생활은 평생 이어지기 때문이에요. 남에게 보여 주기 위해 무리할 필요는 없다고 생각해요. 저라면 그 돈을 신혼 생활을 준비하는 데 더 쓰고 싶어요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "회사에서 실수를 했을 때 즉시 보고해야 한다고 생각하는지 서너 문장으로 써 보세요. '-는 게 맞다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether workplace mistakes should be reported immediately. Use '-는 게 맞다고 생각해요'.",
    example_kr: "저는 실수를 했을 때는 바로 보고하는 게 맞다고 생각해요. 늦게 알리면 문제가 더 커질 수 있기 때문이에요. 혼날까 봐 숨기는 것보다 솔직하게 말하는 게 맞다고 생각해요. 결국 빠른 보고가 신뢰를 쌓는 데도 도움이 된다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "인터넷에 익명으로 글을 쓰는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 데 문제가 있다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on anonymous posting online. Use '-는 데 문제가 있다고 봐요'.",
    example_kr: "저는 완전한 익명으로 글을 쓰게 하는 데 문제가 있다고 봐요. 책임지지 않는 말이 늘어나서 상처받는 사람이 많기 때문이에요. 물론 익명이 필요한 경우도 있지만 무분별하게 허용하는 데 문제가 있다고 봐요. 그래서 최소한의 책임 장치는 필요하다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "돈보다 시간이 더 중요하다고 생각하는지 서너 문장으로 써 보세요. '-다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether time matters more than money. Use '-다고 봐요'.",
    example_kr: "저는 돈보다 시간이 더 중요하다고 봐요. 돈은 다시 벌 수 있지만 시간은 한번 지나가면 되돌릴 수 없다고 봐요. 물론 어느 정도의 돈이 있어야 시간을 자유롭게 쓸 수 있다는 점도 인정해요. 하지만 결국 삶의 만족은 시간을 어떻게 쓰느냐에 달려 있다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "직장에서 사적인 이야기를 나누는 것이 관계에 도움이 된다고 생각하는지 서너 문장으로 써 보세요. '-을 필요가 있다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether small talk at work helps relationships. Use '-을 필요가 있다고 봐요'.",
    example_kr: "저는 어느 정도 사적인 이야기를 나눌 필요가 있다고 봐요. 그래야 서로 편하게 협업할 수 있는 관계가 생기기 때문이에요. 물론 지나치게 개인적인 이야기는 조심할 필요가 있다고 봐요. 적절한 균형을 지킨다면 팀워크에도 긍정적인 영향을 준다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "학생들이 아르바이트를 하는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것도 나쁘지 않다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on students working part-time jobs. Use '-는 것도 나쁘지 않다고 봐요'.",
    example_kr: "저는 학생이 적당히 아르바이트를 하는 것도 나쁘지 않다고 봐요. 돈의 소중함을 몸으로 배울 수 있기 때문이에요. 다만 학업에 지장을 줄 정도로 많이 하는 것은 좋지 않다고 봐요. 균형만 잘 맞춘다면 아르바이트도 좋은 경험이 될 수 있다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "이웃과 자주 교류하는 것이 필요하다고 생각하는지 서너 문장으로 써 보세요. '-을수록 좋다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on the importance of interacting with neighbors. Use '-을수록 좋다고 생각해요'.",
    example_kr: "저는 이웃과의 교류는 많을수록 좋다고 생각해요. 위급한 상황이 생기면 가까운 이웃이 가장 먼저 도움을 줄 수 있기 때문이에요. 요즘은 다들 바빠서 교류가 줄어들었지만 그래도 조금씩 늘려 갈수록 좋다고 생각해요. 작은 인사부터 시작하면 충분히 가능한 일이라고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "회사에서 야근을 자주 하는 문화에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것은 바람직하지 않다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on a workplace culture with frequent overtime. Use '-는 것은 바람직하지 않다고 봐요'.",
    example_kr: "저는 야근이 일상이 되는 것은 바람직하지 않다고 봐요. 장기적으로 보면 직원의 건강과 효율성 모두 떨어지기 때문이에요. 급한 일이 있을 때 가끔 하는 것은 이해하지만 습관처럼 계속되는 것은 바람직하지 않다고 봐요. 오히려 근무 시간 안에 집중해서 일하는 문화가 더 필요하다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "채식 위주의 식습관이 건강에 더 좋다고 생각하는지 서너 문장으로 써 보세요. '-다고 단정할 수는 없어요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether a vegetarian diet is healthier. Use '-다고 단정할 수는 없어요'.",
    example_kr: "저는 채식이 무조건 건강에 더 좋다고 단정할 수는 없다고 생각해요. 사람마다 체질과 필요한 영양소가 다르기 때문이에요. 다만 채소를 많이 먹는 것이 도움이 된다는 점은 부정할 수 없어요. 결국 균형 잡힌 식습관이 더 중요하다고 단정할 수는 없어도 어느 정도는 사실이라고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "친구 사이에도 돈 문제는 확실히 해야 한다고 생각하는지 서너 문장으로 써 보세요. '-는 편이 좋다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on being clear about money matters even between friends. Use '-는 편이 좋다고 봐요'.",
    example_kr: "저는 친구 사이라도 돈 문제는 확실히 하는 편이 좋다고 봐요. 애매하게 넘어가면 나중에 오해가 생길 수 있기 때문이에요. 빌려주고 빌려 받을 때는 문서로 남기지는 않더라도 명확하게 말하는 편이 좋다고 봐요. 오히려 그래야 우정도 더 오래갈 수 있다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "소셜 미디어 사용 시간을 스스로 제한해야 한다고 생각하는지 서너 문장으로 써 보세요. '-어야 할 필요가 있어요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether people should limit their own social media use. Use '-어야 할 필요가 있어요'.",
    example_kr: "저는 스스로 사용 시간을 제한해야 할 필요가 있다고 생각해요. 무의식중에 시간을 너무 많이 쓰게 되기 때문이에요. 특히 잠들기 전에는 사용을 줄여야 할 필요가 있다고 봐요. 습관을 들이면 생활의 균형을 되찾는 데 큰 도움이 될 거예요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "부모가 자녀의 직업 선택에 개입하는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것은 지나치다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on parents influencing their children's career choices. Use '-는 것은 지나치다고 봐요'.",
    example_kr: "저는 부모가 자녀의 직업을 강제로 정하는 것은 지나치다고 봐요. 조언은 도움이 되지만 결정까지 대신하는 것은 지나치다고 생각해요. 자녀도 스스로 실패를 경험하며 배울 권리가 있다고 봐요. 그래서 부모의 역할은 지지하는 데 그쳐야 한다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "공공장소에서 큰 소리로 통화하는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것은 예의가 아니라고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on talking loudly on the phone in public. Use '-는 것은 예의가 아니라고 봐요'.",
    example_kr: "저는 공공장소에서 큰 소리로 통화하는 것은 예의가 아니라고 봐요. 주변 사람들에게 불편을 줄 수 있기 때문이에요. 급한 일이라도 목소리를 낮추는 배려가 필요하다고 봐요. 작은 배려가 모여야 공공장소가 모두에게 편안한 공간이 된다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "가족 여행보다 친구와의 여행이 더 좋다고 생각하는지 서너 문장으로 써 보세요. '-기 나름이라고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether trips with friends are better than family trips. Use '-기 나름이라고 봐요'.",
    example_kr: "저는 이 문제는 사람마다 마음가짐에 달려 있기 나름이라고 봐요. 가족 여행은 편안함이 크고 친구 여행은 자유로움이 크기 때문이에요. 결국 어느 쪽이 더 좋은지는 상황과 성향에 따라 달라지기 나름이라고 봐요. 저는 두 여행 모두 각자의 매력이 있다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "직업 선택에서 안정성과 흥미 중 무엇이 더 중요하다고 생각하는지 서너 문장으로 써 보세요. '-다고 생각하는 편이에요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether job stability or personal interest matters more. Use '-다고 생각하는 편이에요'.",
    example_kr: "저는 안정성보다 흥미가 더 중요하다고 생각하는 편이에요. 흥미가 있어야 오래 버틸 힘도 생기기 때문이에요. 물론 최소한의 안정성도 무시할 수는 없다고 생각하는 편이에요. 그래도 결국 매일 하는 일이니 흥미가 우선이라고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "아이들에게 스마트폰을 언제부터 줘도 된다고 생각하는지 서너 문장으로 써 보세요. '-는 것이 이르다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on when children should get a smartphone. Use '-는 것이 이르다고 봐요'.",
    example_kr: "저는 초등학교 저학년에게 스마트폰을 주는 것이 이르다고 봐요. 아직 자기 조절 능력이 충분하지 않기 때문이에요. 최소한 중학생 정도는 되어야 한다고 생각해요. 그전에 주는 것이 이르다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "회사에서 개인 SNS 사용을 제한하는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것은 과도하다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on companies restricting personal social media use. Use '-는 것은 과도하다고 봐요'.",
    example_kr: "저는 근무 시간에 개인 SNS를 완전히 금지하는 것은 과도하다고 봐요. 짧은 휴식 시간에 잠깐 보는 것까지 막을 필요는 없기 때문이에요. 다만 업무에 지장을 줄 정도라면 어느 정도 제한은 필요하다고 봐요. 전면 금지는 과도하다고 생각하지만 균형은 필요하다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "일회용품 사용을 법으로 규제해야 한다고 생각하는지 서너 문장으로 써 보세요. '-을 필요가 있다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether disposable products should be regulated by law. Use '-을 필요가 있다고 봐요'.",
    example_kr: "저는 일회용품 사용을 법으로 규제할 필요가 있다고 봐요. 자율에만 맡기면 실천이 잘 안 되는 경우가 많기 때문이에요. 물론 갑자기 강하게 규제하면 불편함도 클 수 있어요. 하지만 환경을 생각하면 단계적으로라도 규제할 필요가 있다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "친구가 잘못했을 때 바로 지적해야 한다고 생각하는지 서너 문장으로 써 보세요. '-는 게 옳다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether you should point out a friend's mistake immediately. Use '-는 게 옳다고 봐요'.",
    example_kr: "저는 친한 사이일수록 솔직하게 말해 주는 게 옳다고 봐요. 그냥 넘어가면 같은 실수를 계속 반복할 수 있기 때문이에요. 물론 말하는 방식은 조심스러워야 한다고 생각해요. 하지만 마음속으로만 담아 두는 것보다는 솔직하게 표현하는 게 옳다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "노후를 위해 젊을 때부터 저축을 많이 해야 한다고 생각하는지 서너 문장으로 써 보세요. '-는 것이 바람직하다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on saving for retirement from a young age. Use '-는 것이 바람직하다고 봐요'.",
    example_kr: "저는 젊을 때부터 조금씩이라도 저축하는 것이 바람직하다고 봐요. 시간이 지날수록 복리 효과가 커지기 때문이에요. 물론 현재의 삶을 지나치게 희생하면서까지 할 필요는 없다고 생각해요. 균형을 맞춰 꾸준히 저축하는 것이 바람직하다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "동물원이 필요하다고 생각하는지 서너 문장으로 써 보세요. '-다고 보기 어렵다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether zoos are necessary. Use '-다고 보기 어렵다고 생각해요'.",
    example_kr: "저는 오늘날 동물원이 반드시 필요하다고 보기 어렵다고 생각해요. 동물 복지 측면에서 문제가 많이 지적되기 때문이에요. 교육적인 목적은 다큐멘터리나 다른 방법으로도 충분히 채울 수 있다고 봐요. 그래서 저는 동물원의 형태를 근본적으로 바꿀 필요가 있다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "혼자 사는 것과 함께 사는 것 중 어느 쪽이 더 좋다고 생각하는지 서너 문장으로 써 보세요. '-기 나름이라고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether living alone or with others is better. Use '-기 나름이라고 봐요'.",
    example_kr: "저는 어느 쪽이 더 좋은지는 사람 성향에 따라 다르기 나름이라고 봐요. 혼자 살면 자유롭지만 외로울 수 있고 함께 살면 든든하지만 부딪힐 수도 있어요. 결국 자신에게 맞는 방식을 찾는 것이 중요하기 나름이라고 봐요. 저는 지금은 혼자 사는 게 저에게 더 맞는 것 같아요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "면접에서 첫인상이 실력보다 중요하다고 생각하는지 서너 문장으로 써 보세요. '-다고 보기는 힘들어요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether first impressions matter more than ability in interviews. Use '-다고 보기는 힘들어요'.",
    example_kr: "저는 첫인상이 실력보다 중요하다고 보기는 힘들어요. 짧은 시간에 받은 인상만으로 사람을 판단하는 것은 위험하기 때문이에요. 물론 어느 정도 영향을 준다는 것은 인정해요. 하지만 결국 결과를 만드는 건 실력이라고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "이웃 간 소음 문제는 대화로 해결해야 한다고 생각하는지 서너 문장으로 써 보세요. '-는 것이 먼저라고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on resolving neighbor noise disputes through conversation. Use '-는 것이 먼저라고 봐요'.",
    example_kr: "저는 이웃 문제는 신고보다 먼저 대화로 풀어 보는 것이 먼저라고 봐요. 갑자기 신고를 하면 관계가 더 나빠질 수 있기 때문이에요. 물론 대화가 통하지 않으면 다른 방법도 필요하다고 봐요. 하지만 처음에는 정중하게 이야기를 나누는 것이 먼저라고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "학교에서 시험 성적보다 협동 능력을 더 중요하게 평가해야 한다고 생각하는지 서너 문장으로 써 보세요. '-을 필요가 있다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether schools should value teamwork more than test scores. Use '-을 필요가 있다고 봐요'.",
    example_kr: "저는 학교가 시험 성적만큼 협동 능력도 중요하게 평가할 필요가 있다고 봐요. 사회에서는 혼자 일하는 경우보다 함께 일하는 경우가 훨씬 많기 때문이에요. 성적만으로는 사람의 능력을 다 알 수 없다고 봐요. 그래서 평가 방식을 다양화할 필요가 있다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "휴대폰 없이 하루를 보내는 것이 정신 건강에 좋다고 생각하는지 서너 문장으로 써 보세요. '-는 데 도움이 된다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether spending a day without a phone is good for mental health. Use '-는 데 도움이 된다고 봐요'.",
    example_kr: "저는 가끔 휴대폰 없이 하루를 보내는 것이 마음을 정리하는 데 도움이 된다고 봐요. 계속 확인하고 반응하다 보면 오히려 스트레스가 쌓이기 때문이에요. 처음에는 불안하지만 익숙해지면 여유를 찾는 데 도움이 된다고 봐요. 저는 한 달에 하루 정도는 꼭 시도해 보려고 해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "회사에서 정장 대신 편한 옷을 입도록 허용해야 한다고 생각하는지 서너 문장으로 써 보세요. '-는 것이 좋다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on allowing casual clothing instead of formal wear at work. Use '-는 것이 좋다고 봐요'.",
    example_kr: "저는 업무에 지장이 없다면 편한 옷을 입도록 허용하는 것이 좋다고 봐요. 옷차림이 편해야 업무 효율도 올라간다고 생각하기 때문이에요. 물론 고객을 직접 만나는 자리에서는 예외가 필요할 수 있다고 봐요. 전체적으로는 자율성을 넓히는 것이 좋다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "낯선 사람에게 먼저 도움을 청하는 것이 어렵지 않다고 생각하는지 서너 문장으로 써 보세요. '-는 게 부끄러운 일은 아니라고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether asking a stranger for help is difficult. Use '-는 게 부끄러운 일은 아니라고 봐요'.",
    example_kr: "저는 낯선 사람에게 도움을 청하는 게 부끄러운 일은 아니라고 봐요. 누구나 살면서 도움이 필요한 순간이 있기 때문이에요. 오히려 혼자 끙끙대는 것이 더 문제가 될 수 있다고 봐요. 그래서 필요할 때는 망설이지 않고 부탁하는 게 부끄러운 일은 아니라고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "회식 문화가 여전히 필요하다고 생각하는지 서너 문장으로 써 보세요. '-는 것도 이해가 돼요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether workplace group dinners are still necessary. Use '-는 것도 이해가 돼요'.",
    example_kr: "저는 요즘 젊은 세대가 회식을 부담스러워하는 것도 이해가 돼요. 개인 시간이 줄어들기 때문이에요. 다만 가끔은 서로를 알아가는 자리로서 필요하다는 것도 이해가 돼요. 그래서 강제성만 없다면 가끔의 회식은 나쁘지 않다고 생각해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "여행지에서 사진을 많이 찍는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것도 나름의 의미가 있다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on taking a lot of photos while traveling. Use '-는 것도 나름의 의미가 있다고 봐요'.",
    example_kr: "저는 여행지에서 사진을 많이 찍는 것도 나름의 의미가 있다고 봐요. 시간이 지나도 그 순간을 기억할 수 있게 해 주기 때문이에요. 물론 사진에만 신경 쓰다가 풍경을 놓치는 것은 아쉽다고 생각해요. 적당히 균형을 맞춘다면 사진을 남기는 것도 나름의 의미가 있다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "직장인이 점심시간에 혼자 밥을 먹는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-어도 상관없다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on eating lunch alone at work. Use '-어도 상관없다고 생각해요'.",
    example_kr: "저는 점심을 혼자 먹어도 상관없다고 생각해요. 짧은 시간이라도 온전히 쉴 수 있는 시간이 필요하기 때문이에요. 물론 동료와 함께 먹으면서 얻는 즐거움도 있다고 생각해요. 하지만 강제로 어울릴 필요는 없고 각자 편한 방식을 존중해 줘야 한다고 봐요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "식당에서 팁을 주는 문화가 꼭 필요한지에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-는 것이 더 낫다고 생각해요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on whether tipping at restaurants is necessary. Use '-는 것이 더 낫다고 생각해요'.",
    example_kr: "저는 팁 대신 직원 월급을 제대로 주는 것이 더 낫다고 생각해요. 손님이 계산할 때마다 고민하지 않아도 되기 때문이에요. 또 서비스가 좋든 나쁘든 직원의 수입이 안정적이어야 해요. 물론 좋은 서비스에 감사를 표현하고 싶은 마음도 이해해요.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "혼자 사는 사람이 반려동물을 키우는 것에 대해 어떻게 생각하는지 서너 문장으로 써 보세요. '-기 전에 -어야 한다고 봐요'를 사용하세요.",
    prompt_en: "Write 3-4 sentences giving your opinion on people who live alone keeping pets. Use '-기 전에 -어야 한다고 봐요'.",
    example_kr: "혼자 사는 사람도 충분히 반려동물을 키울 수 있다고 생각해요. 다만 데려오기 전에 자기 생활 패턴을 솔직하게 살펴봐야 한다고 봐요. 야근이 잦거나 출장이 많으면 동물이 하루 종일 혼자 있게 되기 때문이에요. 그런 점만 잘 준비한다면 서로에게 큰 위로가 될 거예요.",
  },
];
