import type { RawPrompt } from "./types";

export const WRITING_B1_OPINION: RawPrompt[] = [
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "음악 듣기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on listening to music.",
    prompt_ja: "音楽を聴くことについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对听音乐的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về nghe nhạc.",
    prompt_es: "Escribe en detalle tus pensamientos sobre escuchar música.",
    example_kr: "저는 음악 듣기를 좋아하는데 정말 편해요.",
    example_en: "I like listening to music, and I find it really comfortable.",
    example_ja: "私は音楽を聴くことが好きで、本当に楽です。",
    example_zh: "我喜欢听音乐，真的很舒服。",
    example_vi: "Tôi thích nghe nhạc, thật sự rất thoải mái.",
    example_es: "Me gusta escuchar música, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "겨울에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on winter.",
    prompt_ja: "冬についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对冬天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa đông.",
    prompt_es: "Escribe en detalle tus pensamientos sobre el invierno.",
    example_kr: "저는 겨울을 좋아하는데 정말 편해요.",
    example_en: "I like winter, and I find it really comfortable.",
    example_ja: "私は冬が好きで、本当に楽です。",
    example_zh: "我喜欢冬天，真的很舒服。",
    example_vi: "Tôi thích mùa đông, thật sự rất thoải mái.",
    example_es: "Me gusta el invierno, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "야식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on late-night snacks.",
    prompt_ja: "夜食についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对夜宵的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đồ ăn khuya.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la comida nocturna.",
    example_kr: "저는 야식을 좋아하는데 정말 편해요.",
    example_en: "I like late-night snacks, and I find it really comfortable.",
    example_ja: "私は夜食が好きで、本当に楽です。",
    example_zh: "我喜欢夜宵，真的很舒服。",
    example_vi: "Tôi thích đồ ăn khuya, thật sự rất thoải mái.",
    example_es: "Me gusta la comida nocturna, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "봄에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spring.",
    prompt_ja: "春についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对春天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa xuân.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la primavera.",
    example_kr: "저는 봄을 좋아하는데 정말 편해요.",
    example_en: "I like spring, and I find it really comfortable.",
    example_ja: "私は春が好きで、本当に楽です。",
    example_zh: "我喜欢春天，真的很舒服。",
    example_vi: "Tôi thích mùa xuân, thật sự rất thoải mái.",
    example_es: "Me gusta la primavera, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "고양이에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cats.",
    prompt_ja: "猫についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对猫的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mèo.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los gatos.",
    example_kr: "저는 고양이를 좋아하는데 정말 편해요.",
    example_en: "I like cats, and I find it really comfortable.",
    example_ja: "私は猫が好きで、本当に楽です。",
    example_zh: "我喜欢猫，真的很舒服。",
    example_vi: "Tôi thích mèo, thật sự rất thoải mái.",
    example_es: "Me gustan los gatos, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "디저트에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dessert.",
    prompt_ja: "デザートについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对甜点的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đồ tráng miệng.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los postres.",
    example_kr: "저는 디저트를 좋아하는데 정말 편해요.",
    example_en: "I like dessert, and I find it really comfortable.",
    example_ja: "私はデザートが好きで、本当に楽です。",
    example_zh: "我喜欢甜点，真的很舒服。",
    example_vi: "Tôi thích đồ tráng miệng, thật sự rất thoải mái.",
    example_es: "Me gustan los postres, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "강아지에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dogs.",
    prompt_ja: "犬についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对狗的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về chó con.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los perros.",
    example_kr: "저는 강아지를 좋아하는데 정말 편해요.",
    example_en: "I like dogs, and I find it really comfortable.",
    example_ja: "私は犬が好きで、本当に楽です。",
    example_zh: "我喜欢狗，真的很舒服。",
    example_vi: "Tôi thích chó con, thật sự rất thoải mái.",
    example_es: "Me gustan los perros, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "아침 운동에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on morning exercise.",
    prompt_ja: "朝の運動についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对晨练的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về tập thể dục buổi sáng.",
    prompt_es: "Escribe en detalle tus pensamientos sobre hacer ejercicio por la mañana.",
    example_kr: "저는 아침 운동을 좋아하는데 정말 편해요.",
    example_en: "I like morning exercise, and I find it really comfortable.",
    example_ja: "私は朝の運動が好きで、本当に楽です。",
    example_zh: "我喜欢晨练，真的很舒服。",
    example_vi: "Tôi thích tập thể dục buổi sáng, thật sự rất thoải mái.",
    example_es: "Me gusta hacer ejercicio por la mañana, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "일찍 일어나기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on waking up early.",
    prompt_ja: "早起きについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对早起的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về dậy sớm.",
    prompt_es: "Escribe en detalle tus pensamientos sobre despertarse temprano.",
    example_kr: "저는 일찍 일어나기를 좋아하는데 정말 편해요.",
    example_en: "I like waking up early, and I find it really comfortable.",
    example_ja: "私は早起きが好きで、本当に楽です。",
    example_zh: "我喜欢早起，真的很舒服。",
    example_vi: "Tôi thích dậy sớm, thật sự rất thoải mái.",
    example_es: "Me gusta despertarme temprano, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "등산에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hiking.",
    prompt_ja: "登山についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对爬山的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về leo núi.",
    prompt_es: "Escribe en detalle tus pensamientos sobre el senderismo.",
    example_kr: "저는 등산을 좋아하는데 정말 편해요.",
    example_en: "I like hiking, and I find it really comfortable.",
    example_ja: "私は登山が好きで、本当に楽です。",
    example_zh: "我喜欢爬山，真的很舒服。",
    example_vi: "Tôi thích leo núi, thật sự rất thoải mái.",
    example_es: "Me gusta el senderismo, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "비 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on rainy days.",
    prompt_ja: "雨の日についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对下雨天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ngày mưa.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los días lluviosos.",
    example_kr: "저는 비 오는 날을 좋아하는데 정말 편해요.",
    example_en: "I like rainy days, and I find it really comfortable.",
    example_ja: "私は雨の日が好きで、本当に楽です。",
    example_zh: "我喜欢下雨天，真的很舒服。",
    example_vi: "Tôi thích ngày mưa, thật sự rất thoải mái.",
    example_es: "Me gustan los días lluviosos, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "단체 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on group trips.",
    prompt_ja: "団体旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对团体旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch theo nhóm.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los viajes en grupo.",
    example_kr: "저는 단체 여행을 좋아하는데 정말 편해요.",
    example_en: "I like group trips, and I find it really comfortable.",
    example_ja: "私は団体旅行が好きで、本当に楽です。",
    example_zh: "我喜欢团体旅行，真的很舒服。",
    example_vi: "Tôi thích du lịch theo nhóm, thật sự rất thoải mái.",
    example_es: "Me gustan los viajes en grupo, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "한국 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on Korean food.",
    prompt_ja: "韓国料理についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对韩国料理的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về món ăn Hàn Quốc.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la comida coreana.",
    example_kr: "저는 한국 음식을 좋아하는데 정말 편해요.",
    example_en: "I like Korean food, and I find it really comfortable.",
    example_ja: "私は韓国料理が好きで、本当に楽です。",
    example_zh: "我喜欢韩国料理，真的很舒服。",
    example_vi: "Tôi thích món ăn Hàn Quốc, thật sự rất thoải mái.",
    example_es: "Me gusta la comida coreana, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "수영에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on swimming.",
    prompt_ja: "水泳についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对游泳的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về bơi lội.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la natación.",
    example_kr: "저는 수영을 좋아하는데 정말 편해요.",
    example_en: "I like swimming, and I find it really comfortable.",
    example_ja: "私は水泳が好きで、本当に楽です。",
    example_zh: "我喜欢游泳，真的很舒服。",
    example_vi: "Tôi thích bơi lội, thật sự rất thoải mái.",
    example_es: "Me gusta la natación, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "일찍 자기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on going to bed early.",
    prompt_ja: "早寝についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对早睡的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ngủ sớm.",
    prompt_es: "Escribe en detalle tus pensamientos sobre dormir temprano.",
    example_kr: "저는 일찍 자기를 좋아하는데 정말 편해요.",
    example_en: "I like going to bed early, and I find it really comfortable.",
    example_ja: "私は早寝が好きで、本当に楽です。",
    example_zh: "我喜欢早睡，真的很舒服。",
    example_vi: "Tôi thích ngủ sớm, thật sự rất thoải mái.",
    example_es: "Me gusta dormir temprano, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "도시 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on city life.",
    prompt_ja: "都市生活についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对城市生活的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cuộc sống thành phố.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la vida en la ciudad.",
    example_kr: "저는 도시 생활을 좋아하는데 정말 편해요.",
    example_en: "I like city life, and I find it really comfortable.",
    example_ja: "私は都市生活が好きで、本当に楽です。",
    example_zh: "我喜欢城市生活，真的很舒服。",
    example_vi: "Tôi thích cuộc sống thành phố, thật sự rất thoải mái.",
    example_es: "Me gusta la vida en la ciudad, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "빵 굽기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on baking bread.",
    prompt_ja: "パン作りについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对烤面包的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về nướng bánh mì.",
    prompt_es: "Escribe en detalle tus pensamientos sobre hornear pan.",
    example_kr: "저는 빵 굽기를 좋아하는데 정말 편해요.",
    example_en: "I like baking bread, and I find it really comfortable.",
    example_ja: "私はパン作りが好きで、本当に楽です。",
    example_zh: "我喜欢烤面包，真的很舒服。",
    example_vi: "Tôi thích nướng bánh mì, thật sự rất thoải mái.",
    example_es: "Me gusta hornear pan, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "여름에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on summer.",
    prompt_ja: "夏についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对夏天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa hè.",
    prompt_es: "Escribe en detalle tus pensamientos sobre el verano.",
    example_kr: "저는 여름을 좋아하는데 정말 편해요.",
    example_en: "I like summer, and I find it really comfortable.",
    example_ja: "私は夏が好きで、本当に楽です。",
    example_zh: "我喜欢夏天，真的很舒服。",
    example_vi: "Tôi thích mùa hè, thật sự rất thoải mái.",
    example_es: "Me gusta el verano, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "독서에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on reading.",
    prompt_ja: "読書についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对阅读的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đọc sách.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la lectura.",
    example_kr: "저는 독서를 좋아하는데 정말 편해요.",
    example_en: "I like reading, and I find it really comfortable.",
    example_ja: "私は読書が好きで、本当に楽です。",
    example_zh: "我喜欢阅读，真的很舒服。",
    example_vi: "Tôi thích đọc sách, thật sự rất thoải mái.",
    example_es: "Me gusta la lectura, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "긴 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on long trips.",
    prompt_ja: "長い旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对长途旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về chuyến du lịch dài ngày.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los viajes largos.",
    example_kr: "저는 긴 여행을 좋아하는데 정말 편해요.",
    example_en: "I like long trips, and I find it really comfortable.",
    example_ja: "私は長い旅行が好きで、本当に楽です。",
    example_zh: "我喜欢长途旅行，真的很舒服。",
    example_vi: "Tôi thích chuyến du lịch dài ngày, thật sự rất thoải mái.",
    example_es: "Me gustan los viajes largos, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "자전거 타기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cycling.",
    prompt_ja: "自転車に乗ることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对骑自行车的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đi xe đạp.",
    prompt_es: "Escribe en detalle tus pensamientos sobre andar en bicicleta.",
    example_kr: "저는 자전거 타기를 좋아하는데 정말 편해요.",
    example_en: "I like cycling, and I find it really comfortable.",
    example_ja: "私は自転車に乗ることが好きで、本当に楽です。",
    example_zh: "我喜欢骑自行车，真的很舒服。",
    example_vi: "Tôi thích đi xe đạp, thật sự rất thoải mái.",
    example_es: "Me gusta andar en bicicleta, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "영화 보기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on watching movies.",
    prompt_ja: "映画を見ることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对看电影的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về xem phim.",
    prompt_es: "Escribe en detalle tus pensamientos sobre ver películas.",
    example_kr: "저는 영화 보기를 좋아하는데 정말 편해요.",
    example_en: "I like watching movies, and I find it really comfortable.",
    example_ja: "私は映画を見ることが好きで、本当に楽です。",
    example_zh: "我喜欢看电影，真的很舒服。",
    example_vi: "Tôi thích xem phim, thật sự rất thoải mái.",
    example_es: "Me gusta ver películas, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "카페에서 공부하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on studying at a cafe.",
    prompt_ja: "カフェで勉強することについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对在咖啡厅学习的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về học ở quán cà phê.",
    prompt_es: "Escribe en detalle tus pensamientos sobre estudiar en un café.",
    example_kr: "저는 카페에서 공부하기를 좋아하는데 정말 편해요.",
    example_en: "I like studying at a cafe, and I find it really comfortable.",
    example_ja: "私はカフェで勉強することが好きで、本当に楽です。",
    example_zh: "我喜欢在咖啡厅学习，真的很舒服。",
    example_vi: "Tôi thích học ở quán cà phê, thật sự rất thoải mái.",
    example_es: "Me gusta estudiar en un café, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "휴가에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vacations.",
    prompt_ja: "休暇についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对假期的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về kỳ nghỉ.",
    prompt_es: "Escribe en detalle tus pensamientos sobre las vacaciones.",
    example_kr: "저는 휴가를 좋아하는데 정말 편해요.",
    example_en: "I like vacations, and I find it really comfortable.",
    example_ja: "私は休暇が好きで、本当に楽です。",
    example_zh: "我喜欢假期，真的很舒服。",
    example_vi: "Tôi thích kỳ nghỉ, thật sự rất thoải mái.",
    example_es: "Me gustan las vacaciones, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "혼밥에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on eating alone.",
    prompt_ja: "一人で食事をすることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对一个人吃饭的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ăn một mình.",
    prompt_es: "Escribe en detalle tus pensamientos sobre comer solo.",
    example_kr: "저는 혼밥을 좋아하는데 정말 편해요.",
    example_en: "I like eating alone, and I find it really comfortable.",
    example_ja: "私は一人で食事をすることが好きで、本当に楽です。",
    example_zh: "我喜欢一个人吃饭，真的很舒服。",
    example_vi: "Tôi thích ăn một mình, thật sự rất thoải mái.",
    example_es: "Me gusta comer solo, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "가을에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on fall.",
    prompt_ja: "秋についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对秋天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa thu.",
    prompt_es: "Escribe en detalle tus pensamientos sobre el otoño.",
    example_kr: "저는 가을을 좋아하는데 정말 편해요.",
    example_en: "I like fall, and I find it really comfortable.",
    example_ja: "私は秋が好きで、本当に楽です。",
    example_zh: "我喜欢秋天，真的很舒服。",
    example_vi: "Tôi thích mùa thu, thật sự rất thoải mái.",
    example_es: "Me gusta el otoño, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "매운 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spicy food.",
    prompt_ja: "辛い食べ物についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对辛辣食物的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đồ cay.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la comida picante.",
    example_kr: "저는 매운 음식을 좋아하는데 정말 편해요.",
    example_en: "I like spicy food, and I find it really comfortable.",
    example_ja: "私は辛い食べ物が好きで、本当に楽です。",
    example_zh: "我喜欢辛辣食物，真的很舒服。",
    example_vi: "Tôi thích đồ cay, thật sự rất thoải mái.",
    example_es: "Me gusta la comida picante, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "더운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hot weather.",
    prompt_ja: "暑い天気についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对炎热天气的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về thời tiết nóng.",
    prompt_es: "Escribe en detalle tus pensamientos sobre el clima caluroso.",
    example_kr: "저는 더운 날씨를 좋아하는데 정말 편해요.",
    example_en: "I like hot weather, and I find it really comfortable.",
    example_ja: "私は暑い天気が好きで、本当に楽です。",
    example_zh: "我喜欢炎热天气，真的很舒服。",
    example_vi: "Tôi thích thời tiết nóng, thật sự rất thoải mái.",
    example_es: "Me gusta el clima caluroso, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "아침형 인간에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on being a morning person.",
    prompt_ja: "朝型人間についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对晨型人的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về người dậy sớm.",
    prompt_es: "Escribe en detalle tus pensamientos sobre ser una persona madrugadora.",
    example_kr: "저는 아침형 인간을 좋아하는데 정말 편해요.",
    example_en: "I like being a morning person, and I find it really comfortable.",
    example_ja: "私は朝型人間が好きで、本当に楽です。",
    example_zh: "我喜欢做晨型人，真的很舒服。",
    example_vi: "Tôi thích người dậy sớm, thật sự rất thoải mái.",
    example_es: "Me gusta ser una persona madrugadora, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "추운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cold weather.",
    prompt_ja: "寒い天気についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对寒冷天气的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về thời tiết lạnh.",
    prompt_es: "Escribe en detalle tus pensamientos sobre el clima frío.",
    example_kr: "저는 추운 날씨를 좋아하는데 정말 편해요.",
    example_en: "I like cold weather, and I find it really comfortable.",
    example_ja: "私は寒い天気が好きで、本当に楽です。",
    example_zh: "我喜欢寒冷天气，真的很舒服。",
    example_vi: "Tôi thích thời tiết lạnh, thật sự rất thoải mái.",
    example_es: "Me gusta el clima frío, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "사진 찍기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on taking photos.",
    prompt_ja: "写真を撮ることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对拍照的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về chụp ảnh.",
    prompt_es: "Escribe en detalle tus pensamientos sobre tomar fotos.",
    example_kr: "저는 사진 찍기를 좋아하는데 정말 편해요.",
    example_en: "I like taking photos, and I find it really comfortable.",
    example_ja: "私は写真を撮ることが好きで、本当に楽です。",
    example_zh: "我喜欢拍照，真的很舒服。",
    example_vi: "Tôi thích chụp ảnh, thật sự rất thoải mái.",
    example_es: "Me gusta tomar fotos, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "시골 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on countryside life.",
    prompt_ja: "田舎暮らしについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对乡村生活的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cuộc sống nông thôn.",
    prompt_es: "Escribe en detalle tus pensamientos sobre la vida en el campo.",
    example_kr: "저는 시골 생활을 좋아하는데 정말 편해요.",
    example_en: "I like countryside life, and I find it really comfortable.",
    example_ja: "私は田舎暮らしが好きで、本当に楽です。",
    example_zh: "我喜欢乡村生活，真的很舒服。",
    example_vi: "Tôi thích cuộc sống nông thôn, thật sự rất thoải mái.",
    example_es: "Me gusta la vida en el campo, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "계획 세우기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on making plans.",
    prompt_ja: "計画を立てることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对制定计划的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về lập kế hoạch.",
    prompt_es: "Escribe en detalle tus pensamientos sobre hacer planes.",
    example_kr: "저는 계획 세우기를 좋아하는데 정말 편해요.",
    example_en: "I like making plans, and I find it really comfortable.",
    example_ja: "私は計画を立てることが好きで、本当に楽です。",
    example_zh: "我喜欢制定计划，真的很舒服。",
    example_vi: "Tôi thích lập kế hoạch, thật sự rất thoải mái.",
    example_es: "Me gusta hacer planes, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "혼자 여행하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling alone.",
    prompt_ja: "一人旅についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对独自旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch một mình.",
    prompt_es: "Escribe en detalle tus pensamientos sobre viajar solo.",
    example_kr: "저는 혼자 여행하기를 좋아하는데 정말 편해요.",
    example_en: "I like traveling alone, and I find it really comfortable.",
    example_ja: "私は一人旅が好きで、本当に楽です。",
    example_zh: "我喜欢独自旅行，真的很舒服。",
    example_vi: "Tôi thích du lịch một mình, thật sự rất thoải mái.",
    example_es: "Me gusta viajar solo, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "눈 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on snowy days.",
    prompt_ja: "雪の日についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对下雪天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ngày tuyết rơi.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los días de nieve.",
    example_kr: "저는 눈 오는 날을 좋아하는데 정말 편해요.",
    example_en: "I like snowy days, and I find it really comfortable.",
    example_ja: "私は雪の日が好きで、本当に楽です。",
    example_zh: "我喜欢下雪天，真的很舒服。",
    example_vi: "Tôi thích ngày tuyết rơi, thật sự rất thoải mái.",
    example_es: "Me gustan los días de nieve, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "요리하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cooking.",
    prompt_ja: "料理をすることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对做饭的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về nấu ăn.",
    prompt_es: "Escribe en detalle tus pensamientos sobre cocinar.",
    example_kr: "저는 요리하기를 좋아하는데 정말 편해요.",
    example_en: "I like cooking, and I find it really comfortable.",
    example_ja: "私は料理をすることが好きで、本当に楽です。",
    example_zh: "我喜欢做饭，真的很舒服。",
    example_vi: "Tôi thích nấu ăn, thật sự rất thoải mái.",
    example_es: "Me gusta cocinar, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "즉흥 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spontaneous trips.",
    prompt_ja: "思いつきの旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对说走就走的旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch bất chợt.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los viajes espontáneos.",
    example_kr: "저는 즉흥 여행을 좋아하는데 정말 편해요.",
    example_en: "I like spontaneous trips, and I find it really comfortable.",
    example_ja: "私は思いつきの旅行が好きで、本当に楽です。",
    example_zh: "我喜欢说走就走的旅行，真的很舒服。",
    example_vi: "Tôi thích du lịch bất chợt, thật sự rất thoải mái.",
    example_es: "Me gustan los viajes espontáneos, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "주말에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on weekends.",
    prompt_ja: "週末についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对周末的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cuối tuần.",
    prompt_es: "Escribe en detalle tus pensamientos sobre los fines de semana.",
    example_kr: "저는 주말을 좋아하는데 정말 편해요.",
    example_en: "I like weekends, and I find it really comfortable.",
    example_ja: "私は週末が好きで、本当に楽です。",
    example_zh: "我喜欢周末，真的很舒服。",
    example_vi: "Tôi thích cuối tuần, thật sự rất thoải mái.",
    example_es: "Me gustan los fines de semana, y me parece muy cómodo.",
  },
  {
    level: "B1",
    genre: "opinion",
    prompt_kr: "여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling.",
    prompt_ja: "旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch.",
    prompt_es: "Escribe en detalle tus pensamientos sobre viajar.",
    example_kr: "저는 여행을 좋아하는데 정말 편해요.",
    example_en: "I like traveling, and I find it really comfortable.",
    example_ja: "私は旅行が好きで、本当に楽です。",
    example_zh: "我喜欢旅行，真的很舒服。",
    example_vi: "Tôi thích du lịch, thật sự rất thoải mái.",
    example_es: "Me gusta viajar, y me parece muy cómodo.",
  },
];
