import type { RawPrompt } from "./types";

export const WRITING_B1_REPLY: RawPrompt[] = [
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지훈 씨, 다음 주 화요일 회의 자료 준비는 잘 되고 있어요? 혹시 도와드릴 부분이 있으면 말씀해 주세요.",
    stimulus_en: "Ji-hoon, how's the preparation for next Tuesday's meeting materials going? Let me know if there's anything I can help with.",
    prompt_kr: "동료의 메시지에 진행 상황을 알리고 도움을 요청하는 답장을 다섯 문장으로 써 보세요. '-고 있어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to your coworker updating them on your progress and asking for help. Use '-고 있어요'.",
    example_kr: "안녕하세요, 지금 자료를 절반 정도 준비하고 있어요. 자료 조사는 거의 끝냈고 지금은 발표 순서를 정리하고 있어요. 다만 지난달 판매 데이터를 아직 못 구해서 조금 헤매고 있어요. 혹시 그 자료를 어디서 받을 수 있는지 알려 주실 수 있을까요? 도와주신다면 정말 감사하겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "안녕하세요, 세입자님. 다음 주 화요일 오전에 배관 점검을 위해 방문하려고 하는데 시간이 괜찮으실까요?",
    stimulus_en: "Hello, tenant. I'd like to visit next Tuesday morning to check the plumbing. Would that time work for you?",
    prompt_kr: "집주인의 메시지에 방문 가능 여부를 답하는 답장을 다섯 문장으로 써 보세요. '-어도 될까요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to your landlord about whether the visit time works. Use '-어도 될까요'.",
    example_kr: "안녕하세요, 연락 주셔서 감사합니다. 화요일 오전에는 제가 출근을 해서 집에 없을 것 같습니다. 혹시 오후 시간으로 옮겨도 될까요? 아니면 제가 관리실에 열쇠를 맡겨 놓아도 될까요? 편하신 방법으로 알려 주시면 맞춰 보겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "민서야, 나 요즘 진로 때문에 너무 고민이 많아. 회사를 계속 다녀야 할지 대학원에 가야 할지 모르겠어. 넌 어떻게 생각해?",
    stimulus_en: "Min-seo, I've been really worried about my career path lately. I don't know whether to keep working or go to grad school. What do you think?",
    prompt_kr: "고민을 털어놓은 친구에게 조언하는 답장을 다섯 문장으로 써 보세요. '-어 보는 게 어때요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply giving advice to a friend who shared a career worry. Use '-어 보는 게 어때요'.",
    example_kr: "너무 고민 많았겠다, 이야기해 줘서 고마워. 먼저 지금 하는 일에서 뭐가 힘든지 정리해 보는 게 어때요? 그리고 대학원이 정말 필요한 이유가 뭔지도 한번 써 보는 게 어때요? 급하게 결정하지 말고 몇 사람한테 조언도 구해 보는 게 어때요? 어떤 선택을 하든 내가 옆에서 응원할게.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 주문하신 상품이 품절되어 배송이 지연되고 있습니다. 다음 주 화요일에 발송될 예정인데 괜찮으실까요?",
    stimulus_en: "Dear customer, the item you ordered is out of stock, causing a delay in shipping. It's expected to ship next Tuesday. Is that okay?",
    prompt_kr: "쇼핑몰의 지연 안내 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-어야 할 것 같아요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a store's delay notice. Use '-어야 할 것 같아요'.",
    example_kr: "안내해 주셔서 감사합니다. 화요일까지는 조금 더 기다려야 할 것 같아요. 다만 다음 주 주말에 여행을 가서 그전에 받아야 할 것 같아요. 혹시 조금 더 빠르게 받을 방법이 있는지 확인해 주실 수 있을까요? 어렵다면 취소를 고려해야 할 것 같습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여보, 이번 주말에 처가에 가기로 한 거 기억하지? 몇 시쯤 출발하면 좋을까?",
    stimulus_en: "Honey, you remember we're visiting my parents this weekend, right? What time should we leave?",
    prompt_kr: "배우자의 메시지에 일정을 조율하는 답장을 다섯 문장으로 써 보세요. '-는 게 어때요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply coordinating a schedule with your spouse. Use '-는 게 어때요'.",
    example_kr: "응, 기억하고 있어요. 토요일 아침 일찍 출발하는 게 어때요? 길이 막히기 전에 나가는 게 어때요? 대신 가는 길에 아침은 휴게소에서 먹는 게 어때요? 그렇게 하면 시간도 절약되고 여유롭게 도착할 수 있을 것 같아요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "선생님, 아이가 요즘 학교에서 친구 관계 때문에 힘들어하는 것 같아 상담을 요청드립니다. 시간 괜찮으신 날짜를 알려 주시겠어요?",
    stimulus_en: "Teacher, my child seems to be struggling with friend relationships at school lately, so I'd like to request a meeting. Could you let me know a day that works for you?",
    prompt_kr: "학부모의 상담 요청 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-어 드리겠습니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as a teacher responding to a parent's meeting request. Use '-어 드리겠습니다'.",
    example_kr: "안녕하세요, 어머니. 연락 주셔서 감사합니다. 이번 주 목요일 오후 세 시에 시간을 비워 드리겠습니다. 그 전에 아이의 최근 학교생활도 자세히 살펴봐 드리겠습니다. 상담할 때 궁금하신 점을 편하게 말씀해 주시면 자세히 설명해 드리겠습니다. 목요일에 뵙겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지원자님, 서류 전형에 합격하셨습니다. 다음 주 중 면접 가능한 날짜를 알려 주시겠어요?",
    stimulus_en: "Congratulations, you have passed the document screening. Could you let us know your available interview dates next week?",
    prompt_kr: "합격 및 면접 일정 안내 메일에 답하는 답장을 다섯 문장으로 써 보세요. '-도록 하겠습니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply responding to a pass notice and interview scheduling request. Use '-도록 하겠습니다'.",
    example_kr: "안녕하세요, 좋은 소식 전해 주셔서 감사합니다. 다음 주 수요일 오후에 시간을 맞추도록 하겠습니다. 필요한 서류는 미리 준비해서 가도록 하겠습니다. 면접 장소도 다시 한번 확인하도록 하겠습니다. 좋은 모습으로 뵐 수 있도록 준비하겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "옆집인데요, 밤늦게 발소리와 물건 떨어뜨리는 소리가 계속 들려서 불편합니다. 조금만 신경 써 주시면 감사하겠습니다.",
    stimulus_en: "Hi, this is your neighbor. I keep hearing footsteps and things being dropped late at night, and it's disturbing. I'd appreciate it if you could be more careful.",
    prompt_kr: "층간 소음에 대한 이웃의 불만에 사과하는 답장을 다섯 문장으로 써 보세요. '-도록 조심하겠습니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply apologizing to a neighbor about noise complaints. Use '-도록 조심하겠습니다'.",
    example_kr: "불편을 드려서 정말 죄송합니다. 요즘 이사 정리를 하느라 소음이 많았던 것 같습니다. 앞으로는 밤 열 시 이후에는 조용히 하도록 조심하겠습니다. 매트를 깔아서 발소리도 줄이도록 조심하겠습니다. 말씀해 주셔서 감사하고, 계속 불편하시면 언제든 다시 알려 주세요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "예은 씨, 다음 주 팀 회식 장소를 한식과 일식 중에서 정해야 하는데 어떤 게 좋을까요?",
    stimulus_en: "Ye-eun, we need to decide the team dinner venue between Korean and Japanese food. Which do you prefer?",
    prompt_kr: "회식 장소를 정하는 동료의 질문에 답하는 답장을 다섯 문장으로 써 보세요. '-는 게 나을 것 같아요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply answering a coworker's question about picking a dinner venue. Use '-는 게 나을 것 같아요'.",
    example_kr: "저는 이번에는 한식으로 가는 게 나을 것 같아요. 지난번에 일식을 먹었으니까 이번엔 다르게 가는 게 나을 것 같아요. 매운 음식을 못 먹는 팀원도 있으니까 순한 메뉴가 있는 곳으로 정하는 게 나을 것 같아요. 그리고 자리가 넓은 곳으로 예약하는 게 나을 것 같아요. 다른 팀원들 의견도 한번 물어볼까요?",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "손님, 예약하신 방은 준비가 다 됐습니다. 체크인은 오후 세 시부터 가능하신데 혹시 더 일찍 오실 예정이신가요?",
    stimulus_en: "Sir/Madam, your reserved room is ready. Check-in is available from 3pm — will you be arriving earlier than that?",
    prompt_kr: "숙소 체크인 안내 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-을 것 같아요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a hotel's check-in notice. Use '-을 것 같아요'.",
    example_kr: "안내해 주셔서 감사합니다. 저희는 오후 한 시쯤 도착할 것 같아요. 조금 이른 시간이라 짐만 먼저 맡겨야 할 것 같아요. 체크인이 늦어져도 괜찮으니 짐 보관만 부탁드릴 수 있을 것 같아요. 도착하면 다시 연락드릴 것 같아요, 잘 부탁드립니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "재훈 씨, 어제 보내 주신 보고서 잘 받았어요. 그런데 3페이지 수치가 조금 이상한 것 같은데 한번 확인해 주시겠어요?",
    stimulus_en: "Jae-hoon, I received the report you sent yesterday. But the numbers on page 3 seem a bit off — could you double-check them?",
    prompt_kr: "보고서 오류를 지적한 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-어 보겠습니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a message pointing out an error in your report. Use '-어 보겠습니다'.",
    example_kr: "확인해 주셔서 감사합니다. 지금 바로 3페이지 수치를 다시 확인해 보겠습니다. 원본 자료와 대조해 보겠습니다. 오류가 맞다면 오늘 안으로 수정해서 다시 보내 드려 보겠습니다. 불편을 드려 죄송하고 빠르게 처리해 보겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이모, 저 다음 달에 회사 그만두고 여행 좀 다녀오려고요. 갑자기 놀라시겠지만 응원해 주실 수 있으세요?",
    stimulus_en: "Auntie, I'm planning to quit my job next month and go traveling. This might come as a surprise, but could you support me?",
    prompt_kr: "조카의 갑작스러운 결심을 전하는 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-는 게 좋겠어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a niece/nephew's sudden decision to quit and travel. Use '-는 게 좋겠어요'.",
    example_kr: "많이 고민했겠구나, 솔직하게 말해 줘서 고마워. 이왕 결심했으면 미리 예산도 꼼꼼히 짜 보는 게 좋겠어요. 여행지의 안전 정보도 미리 알아보는 게 좋겠어요. 돌아온 후 계획도 조금은 생각해 두는 게 좋겠어요. 응원할 테니 좋은 경험 많이 하고 오렴.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여러분, 다음 주 목요일 워크숍에 필요한 자료를 이번 주 금요일까지 공유 폴더에 올려 주시기 바랍니다.",
    stimulus_en: "Everyone, please upload the materials needed for next Thursday's workshop to the shared folder by this Friday.",
    prompt_kr: "팀 공지에 진행 상황을 알리는 답장을 다섯 문장으로 써 보세요. '-을 예정이에요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a team announcement, giving your status update. Use '-을 예정이에요'.",
    example_kr: "안내해 주셔서 감사합니다. 저는 내일까지 초안을 완성할 예정이에요. 완성되는 대로 팀장님께 먼저 검토를 받을 예정이에요. 그 후에 목요일 아침까지는 최종본을 올릴 예정이에요. 혹시 늦어지면 미리 말씀드릴 예정이니 걱정하지 않으셔도 될 것 같아요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "저기, 저번에 빌려준 책 다 읽으셨어요? 이번 주에 시간 되시면 만나서 돌려받고 싶어서요.",
    stimulus_en: "Hey, have you finished the book I lent you? I'd like to meet up and get it back this week if you have time.",
    prompt_kr: "빌려준 물건을 돌려받고 싶어 하는 지인에게 답하는 답장을 다섯 문장으로 써 보세요. '-을게요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to an acquaintance who wants their lent item back. Use '-을게요'.",
    example_kr: "아, 맞다, 깜빡하고 있었어요, 미안해요. 이번 주 안에 다 읽고 돌려줄게요. 목요일 저녁에 시간 되시면 그때 만나서 드릴게요. 커피 한 잔도 살게요. 혹시 다른 시간이 편하시면 알려 주세요, 맞출게요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "사장님, 이번 달 매출이 지난달보다 많이 줄었습니다. 원인 분석과 대책이 필요할 것 같습니다.",
    stimulus_en: "Boss, this month's sales have dropped significantly compared to last month. We need to analyze the cause and come up with a plan.",
    prompt_kr: "매출 하락에 대한 직원의 보고에 답하는 답장을 다섯 문장으로 써 보세요. '-을 필요가 있어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as the boss responding to a report about declining sales. Use '-을 필요가 있어요'.",
    example_kr: "보고해 줘서 고마워요. 우선 원인을 정확히 파악할 필요가 있어요. 경쟁사 상황도 함께 살펴볼 필요가 있어요. 이번 주 안에 회의를 열어 대책을 논의할 필요가 있다고 생각해요. 자료를 준비해서 목요일까지 공유해 주면 좋겠어요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "엄마, 저 이번 명절에 시댁 먼저 갔다가 다음 날 친정 갈게요. 괜찮으시죠?",
    stimulus_en: "Mom, this holiday I'll go to my in-laws first and come to your place the next day. Is that okay?",
    prompt_kr: "명절 일정을 전하는 딸의 메시지에 답하는 부모의 답장을 다섯 문장으로 써 보세요. '-어도 괜찮아요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as a parent responding to a holiday schedule message. Use '-어도 괜찮아요'.",
    example_kr: "그렇게 정해도 괜찮아요, 너무 신경 쓰지 마. 순서는 상황에 맞게 조금 바뀌어도 괜찮아요. 늦게 와도 괜찮으니까 무리하지 말고 와. 몸 조심히 다녀와도 괜찮으니까 천천히 와도 괜찮아요. 도착하면 연락만 해 줘.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 문의하신 반품은 상품 수령 후 7일 이내에만 가능합니다. 현재 12일이 지나서 규정상 어려울 것 같습니다.",
    stimulus_en: "Dear customer, returns are only accepted within 7 days of receiving the item. Since 12 days have passed, it seems difficult per policy.",
    prompt_kr: "반품 불가 안내 메일에 재요청하는 답장을 다섯 문장으로 써 보세요. '-을 수 없을까요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply asking to reconsider a return-denial notice. Use '-을 수 없을까요'.",
    example_kr: "답변 감사합니다, 그런데 조금 아쉬운 마음에 다시 여쭤봅니다. 제가 해외 출장 때문에 확인이 늦어졌는데 예외로 처리해 주실 수 없을까요? 상품은 한 번도 사용하지 않은 상태인데 참고해 주실 수 없을까요? 어렵다면 교환이라도 가능한지 알고 싶습니다. 검토 부탁드립니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "형, 나 이번에 새로 이사한 집 집들이 하려고 하는데 토요일 저녁에 시간 돼?",
    stimulus_en: "Hey bro, I'm planning a housewarming for my new place — are you free Saturday evening?",
    prompt_kr: "집들이 초대에 답하는 답장을 다섯 문장으로 써 보세요. '-을게요' 또는 '-을 수 있을 것 같아요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a housewarming invitation. Use '-을게요' or '-을 수 있을 것 같아요'.",
    example_kr: "초대해 줘서 고마워, 당연히 갈게. 토요일 저녁에는 시간을 낼 수 있을 것 같아. 뭐 좀 사 갈까? 필요한 게 있으면 미리 말해 줘, 챙겨 갈게. 새집 구경할 생각에 벌써 기대돼.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 예약하신 미용실 시술은 두 시간 정도 소요될 예정입니다. 미리 알고 계시면 좋을 것 같아 안내드립니다.",
    stimulus_en: "Dear customer, your booked hair salon treatment is expected to take about two hours. Just letting you know in advance.",
    prompt_kr: "미용실의 시간 안내 문자에 답하는 답장을 다섯 문장으로 써 보세요. '-어야겠어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a salon's time estimate notice. Use '-어야겠어요'.",
    example_kr: "안내해 주셔서 감사합니다. 시간이 생각보다 오래 걸리니 다른 일정은 미뤄야겠어요. 점심도 미리 먹고 가야겠어요. 편한 책이라도 챙겨 가야겠어요. 시간 맞춰서 방문하겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여보세요, 저 아래층인데요. 세탁기 물이 저희 집 천장으로 새는 것 같아서 연락드렸어요.",
    stimulus_en: "Hello, this is your downstairs neighbor. It seems like water from your washing machine is leaking into our ceiling, so I'm reaching out.",
    prompt_kr: "누수 문제를 알려 온 아래층 이웃에게 답하는 답장을 다섯 문장으로 써 보세요. '-어 보겠습니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a downstairs neighbor who reported a water leak. Use '-어 보겠습니다'.",
    example_kr: "연락 주셔서 감사합니다, 정말 죄송합니다. 지금 바로 세탁기를 확인해 보겠습니다. 배관 상태도 함께 살펴보겠습니다. 문제를 찾으면 오늘 안으로 수리 기사님을 불러 보겠습니다. 피해가 있으시면 알려 주시면 제가 책임지고 처리해 보겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "선배님, 이번에 새로 온 팀에 아직 적응이 잘 안 되는데 조언 좀 해 주실 수 있으세요?",
    stimulus_en: "Senior, I'm still having trouble adjusting to my new team — could you give me some advice?",
    prompt_kr: "적응에 어려움을 토로한 후배에게 조언하는 답장을 다섯 문장으로 써 보세요. '-어 보세요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply giving advice to a junior colleague struggling to adjust. Use '-어 보세요'.",
    example_kr: "처음엔 다 그래요, 너무 걱정하지 마세요. 먼저 팀원들 이름과 업무 스타일을 파악해 보세요. 모르는 게 있으면 눈치 보지 말고 바로 물어보세요. 점심시간에 자연스럽게 대화도 나눠 보세요. 시간이 지나면 훨씬 편해질 거예요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여보, 오늘 저녁 뭐 먹을까요? 나는 아무거나 다 괜찮아요.",
    stimulus_en: "Honey, what should we eat tonight? I'm fine with anything.",
    prompt_kr: "저녁 메뉴를 정하는 배우자의 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-는 게 어때요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply deciding dinner with your spouse. Use '-는 게 어때요'.",
    example_kr: "그럼 오늘은 집에서 간단하게 만들어 먹는 게 어때요? 냉장고에 야채가 많으니까 볶음 요리를 해 보는 게 어때요? 아니면 요즘 날씨도 쌀쌀하니까 국을 끓이는 게 어때요? 당신이 좋아하는 걸로 정해도 좋아요. 퇴근하고 같이 준비하는 게 어때요?",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "저기요, 혹시 이 근처에 괜찮은 병원 아세요? 갑자기 몸이 안 좋아서 급하게 찾고 있어요.",
    stimulus_en: "Excuse me, do you know a decent clinic nearby? I suddenly feel unwell and I'm looking urgently.",
    prompt_kr: "길에서 도움을 요청한 낯선 사람에게 답하는 답장을 다섯 문장으로 써 보세요. '-어 보시는 게 어때요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply helping a stranger who asked for directions to a clinic. Use '-어 보시는 게 어때요'.",
    example_kr: "괜찮으세요? 저기 사거리 건너편 병원으로 가 보시는 게 어때요? 거기가 걸어서 오 분 정도밖에 안 걸려요. 혹시 걷기 힘드시면 택시를 불러 드릴까요? 급한 상황이면 응급실이 있는 큰 병원으로 가 보시는 게 어때요? 조심히 가세요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지영아, 다음 주에 있는 동창회 갈 거야? 오랜만에 얼굴도 볼 겸 같이 가면 좋을 것 같아서.",
    stimulus_en: "Ji-young, are you going to the reunion next week? I thought it'd be nice to go together and catch up.",
    prompt_kr: "동창회 참석을 묻는 친구의 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-을지 모르겠어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a friend's question about attending a reunion. Use '-을지 모르겠어요'.",
    example_kr: "연락 줘서 고마워, 나도 가고 싶긴 한데 그날 시간이 될지 모르겠어. 회사 일정이 아직 확정이 안 돼서 참석할 수 있을지 모르겠어. 확실해지면 이번 주 안에 알려 줄게. 만약 못 가게 되더라도 다음번엔 꼭 같이 가고 싶어. 조금만 기다려 줄 수 있어?",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 신청하신 헬스장 회원권은 3개월 이용 후 자동으로 연장됩니다. 계속 이용하시겠어요?",
    stimulus_en: "Dear customer, your gym membership will automatically renew after 3 months. Would you like to continue?",
    prompt_kr: "회원권 자동 연장 안내 문자에 답하는 답장을 다섯 문장으로 써 보세요. '-을까 해요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a gym's auto-renewal notice. Use '-을까 해요'.",
    example_kr: "안내해 주셔서 감사합니다. 지금까지는 꾸준히 다녀서 계속 연장할까 해요. 다만 요즘 시간이 부족해서 이용 횟수를 줄여 볼까 해요. 요금제를 조금 더 저렴한 걸로 바꿀까 해요. 상담이 가능하면 이번 주 안에 방문해 볼까 합니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "언니, 나 이번 시험 진짜 망친 것 같아. 너무 속상해서 어떻게 해야 할지 모르겠어.",
    stimulus_en: "Sis, I think I really messed up this exam. I'm so upset I don't know what to do.",
    prompt_kr: "시험을 망쳐서 속상해하는 동생을 위로하는 답장을 다섯 문장으로 써 보세요. '-을 수도 있어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply comforting a sibling upset about a failed exam. Use '-을 수도 있어요'.",
    example_kr: "많이 속상하겠다, 그래도 생각보다 결과가 괜찮을 수도 있어요. 시험은 한 번의 결과일 뿐이니까 다음 기회가 또 있을 수도 있어요. 지금은 힘들어도 시간이 지나면 별일 아닐 수도 있어요. 오늘은 푹 쉬고 나중에 다시 이야기해 보는 게 어때요. 언제든 나한테 전화해도 돼.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "부장님, 이번 프로젝트 마감일을 하루 정도 미뤄도 될까요? 예상보다 검토할 부분이 많습니다.",
    stimulus_en: "Sir, could we push the project deadline back by a day? There's more to review than expected.",
    prompt_kr: "마감 연기를 요청한 팀원에게 답하는 상사의 답장을 다섯 문장으로 써 보세요. '-도록 하죠'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as a manager responding to a request to extend a deadline. Use '-도록 하죠'.",
    example_kr: "상황을 이해했어요, 그럼 하루 정도 미루도록 하죠. 대신 그 사이에 진행 상황을 중간에 공유하도록 하죠. 다른 팀원들에게도 일정 변경을 알리도록 하죠. 다음부터는 이런 부분을 미리 확인하도록 하죠. 남은 기간 동안 꼼꼼하게 마무리해 주세요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "아빠, 저 이번에 회사에서 해외 파견 제안을 받았어요. 가야 할지 고민이 돼서 여쭤봐요.",
    stimulus_en: "Dad, I got offered an overseas posting at work. I'm not sure whether to go, so I wanted to ask you.",
    prompt_kr: "해외 발령을 고민하는 자녀에게 답하는 부모의 답장을 다섯 문장으로 써 보세요. '-는 게 좋을 것 같아요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as a parent responding to a child considering an overseas job posting. Use '-는 게 좋을 것 같아요'.",
    example_kr: "큰 결정이네, 먼저 조건을 자세히 알아보는 게 좋을 것 같아요. 얼마나 오래 있어야 하는지도 확인해 보는 게 좋을 것 같아요. 네가 정말 원하는 일인지 스스로에게 물어보는 게 좋을 것 같아요. 결정하기 전에 회사 동료들 의견도 들어 보는 게 좋을 것 같아요. 어떤 선택을 해도 우리는 널 응원해.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "안녕하세요, 다음 달 초에 이사 예정인데 정수기와 인터넷 해지 절차가 어떻게 되는지 문의드립니다.",
    stimulus_en: "Hello, I'm planning to move in early next month — could you tell me the process for canceling the water purifier and internet service?",
    prompt_kr: "이사 관련 문의에 답하는 상담원의 답장을 다섯 문장으로 써 보세요. '-어 드릴게요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as a customer service rep responding to a move-related cancellation inquiry. Use '-어 드릴게요'.",
    example_kr: "문의해 주셔서 감사합니다. 정수기 해지 절차부터 안내해 드릴게요. 이사 날짜를 알려 주시면 그날에 맞춰 방문 일정을 잡아 드릴게요. 인터넷은 별도로 해지 신청서를 보내 드릴게요. 궁금한 점이 더 있으시면 언제든 다시 연락 주시면 자세히 안내해 드릴게요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "야, 우리 동아리 다음 학기에도 계속할 거야? 회장 할 사람이 없어서 걱정이야.",
    stimulus_en: "Hey, are we keeping the club going next semester? We're worried since there's no one to be president.",
    prompt_kr: "동아리 운영에 대한 걱정을 나누는 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-을까 싶어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply responding to a friend's worry about the club's leadership. Use '-을까 싶어요'.",
    example_kr: "나도 그 얘기 듣고 좀 걱정이 됐어. 사실 나도 한번 해 볼까 싶어. 다만 시간이 부족할까 싶어서 망설여지기도 해. 부회장이랑 같이 나눠서 맡으면 괜찮지 않을까 싶어. 다음 모임 때 다 같이 논의해 보는 게 어때?",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 결제하신 항공권 일정에 변경이 생겨서 안내드립니다. 출발 시간이 두 시간 앞당겨졌습니다.",
    stimulus_en: "Dear customer, we're informing you of a change to your booked flight schedule. The departure time has been moved up two hours.",
    prompt_kr: "항공권 일정 변경 안내 메일에 답하는 답장을 다섯 문장으로 써 보세요. '-어야겠어요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a flight schedule change notice. Use '-어야겠어요'.",
    example_kr: "안내해 주셔서 감사합니다. 시간이 당겨졌으니 공항에 더 일찍 가야겠어요. 그날 일정도 다시 조정해야겠어요. 같이 가는 가족에게도 미리 알려야겠어요. 짐도 오늘 안에 미리 싸 놔야겠어요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "회장님, 이번 주 아파트 반상회에서 주차 문제를 안건으로 올리고 싶은데 괜찮을까요?",
    stimulus_en: "President, I'd like to add the parking issue to the agenda for this week's building meeting — would that be okay?",
    prompt_kr: "주민 대표에게 안건 상정을 요청받은 반장의 답장을 다섯 문장으로 써 보세요. '-도록 하겠습니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply as the building leader responding to an agenda-request from a resident. Use '-도록 하겠습니다'.",
    example_kr: "말씀해 주셔서 감사합니다. 이번 반상회 안건에 주차 문제를 포함하도록 하겠습니다. 관련 주민들 의견도 미리 모아 보도록 하겠습니다. 회의 자료에 관련 내용을 정리해서 공유하도록 하겠습니다. 좋은 방향으로 해결될 수 있도록 노력하겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여보세요, 저 옆집인데요. 혹시 이사 오시고 아직 정리가 안 되셨으면 반찬 좀 나눠 드리고 싶어서요.",
    stimulus_en: "Hello, this is your next-door neighbor. If you haven't fully settled in after moving, I'd like to share some side dishes with you.",
    prompt_kr: "친절한 이웃의 제안에 답하는 답장을 다섯 문장으로 써 보세요. '-어 주셔서 감사해요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply responding to a kind neighbor's offer. Use '-어 주셔서 감사해요'.",
    example_kr: "이렇게 먼저 챙겨 주셔서 감사해요. 아직 정리가 덜 돼서 정신이 없었는데 마음 써 주셔서 감사해요. 괜찮으시면 잠깐 들러 주셔도 좋을 것 같아요. 신경 써 주셔서 정말 감사해요, 저도 나중에 뭔가 보답하고 싶어요. 앞으로 잘 부탁드려요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여러분, 이번 프로젝트가 성공적으로 끝났습니다. 다들 정말 고생 많으셨습니다.",
    stimulus_en: "Everyone, this project has wrapped up successfully. Great work, everyone.",
    prompt_kr: "프로젝트 성공 소식에 감사를 전하는 답장을 다섯 문장으로 써 보세요. '-어 주셔서 감사합니다'를 사용하세요.",
    prompt_en: "Write a five-sentence reply expressing gratitude after a project's successful completion. Use '-어 주셔서 감사합니다'.",
    example_kr: "좋은 소식 전해 주셔서 감사합니다. 팀장님이 잘 이끌어 주셔서 감사합니다. 팀원 여러분도 끝까지 함께해 주셔서 감사합니다. 힘든 순간마다 도와주셔서 감사합니다. 다음 프로젝트도 이런 팀워크로 잘 해낼 수 있을 것 같아요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "얘, 너 요즘 살이 좀 빠진 것 같아. 밥은 잘 챙겨 먹고 다니는 거야?",
    stimulus_en: "Hey, you seem to have lost some weight lately. Are you eating well?",
    prompt_kr: "걱정해 주는 친구의 메시지에 답하는 답장을 다섯 문장으로 써 보세요. '-느라고'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a friend worried about your weight loss. Use '-느라고'.",
    example_kr: "걱정해 줘서 고마워, 요즘 일이 바빠서 그런지 살이 좀 빠졌나 봐. 마감을 맞추느라고 끼니를 자주 걸렀어. 야근하느라고 잠도 부족했고. 그래도 이번 주부터는 밥 잘 챙겨 먹으려고 노력하고 있어. 걱정 안 해도 될 정도로 금방 회복할게.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "안녕하세요, 한국어 스터디 모임 운영자 하늘입니다. 이번 달부터 모임 시간을 토요일 오전 10시에서 목요일 저녁 7시로 바꾸려고 하는데, 참석 가능하신지 알려 주세요.",
    stimulus_en: "Hello, this is Haneul, organizer of the Korean study group. Starting this month we're thinking of moving the meeting from Saturday 10 a.m. to Thursday 7 p.m. Please let me know if you can attend.",
    prompt_kr: "스터디 모임 시간 변경 안내에 답하는 답장을 다섯 문장으로 써 보세요. '-기는 하지만'을 사용하세요.",
    prompt_en: "Write a five-sentence reply to a study group's schedule-change notice. Use '-기는 하지만'.",
    example_kr: "안녕하세요, 안내해 주셔서 감사합니다. 목요일 저녁도 가능하기는 하지만 퇴근이 늦어지는 날이 가끔 있어요. 그래서 7시보다 7시 반이면 훨씬 안정적으로 참석할 수 있을 것 같아요. 다른 분들이 7시가 좋으시다면 저도 맞추기는 하겠지만 조금 늦을 수도 있습니다. 시간이 정해지면 다시 알려 주세요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 지난주에 방문하신 치과입니다. 다음 주 화요일 오후 2시 정기 검진 예약이 잡혀 있는데 하루 전에 확인 문자 드립니다. 변경이 필요하시면 회신 부탁드립니다.",
    stimulus_en: "This is the dental clinic you visited last week. You have a regular check-up booked for next Tuesday at 2 p.m.; this is a confirmation message. Please reply if you need to change it.",
    prompt_kr: "병원 예약 확인 문자에 답하며 시간을 바꾸는 답장을 다섯 문장으로 써 보세요. '-을 수 있을까요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a clinic's appointment confirmation, asking to change the time. Use '-을 수 있을까요'.",
    example_kr: "안녕하세요, 확인 문자 감사합니다. 죄송하지만 화요일 오후에 갑자기 회의가 잡혀서 그 시간에는 가기 어려울 것 같아요. 혹시 같은 날 오후 5시 이후로 바꿀 수 있을까요? 그날이 안 되면 수요일 오전도 괜찮습니다. 가능한 시간 알려 주시면 바로 확정하겠습니다.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "형, 저 지호예요. 다음 달에 서울로 이사하는데 이삿날 짐 옮기는 거 좀 도와줄 수 있어요? 점심은 제가 살게요!",
    stimulus_en: "Hey, it's Jiho. I'm moving to Seoul next month. Could you help me carry stuff on moving day? Lunch is on me!",
    prompt_kr: "이사를 도와 달라는 후배의 부탁에 답하는 답장을 다섯 문장으로 써 보세요. '-을 수 있으면'을 사용하세요.",
    prompt_en: "Write a five-sentence reply to a younger friend asking for help on moving day. Use '-을 수 있으면'.",
    example_kr: "지호야, 드디어 서울로 오는구나, 축하해. 이삿날이 주말이면 당연히 도와줄 수 있어. 평일이면 반차를 낼 수 있으면 갈게. 무거운 짐이 많으면 미리 알려 줘, 차를 빌릴 수 있으면 더 편할 것 같아. 점심은 네가 산다니까 기대할게.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "안녕하세요, 마케팅팀 서연입니다. 다음 주 목요일 오후에 신제품 관련해서 잠깐 인터뷰를 요청드리고 싶은데, 30분 정도 시간 내 주실 수 있을까요?",
    stimulus_en: "Hello, this is Seoyeon from the marketing team. I'd like to request a short interview about the new product next Thursday afternoon. Could you spare about 30 minutes?",
    prompt_kr: "다른 팀 동료의 인터뷰 요청에 조건을 붙여 수락하는 답장을 다섯 문장으로 써 보세요. '-는 대신에'를 사용하세요.",
    prompt_en: "Write a five-sentence reply accepting a coworker's interview request with a condition. Use '-는 대신에'.",
    example_kr: "안녕하세요, 서연 님. 목요일 오후는 괜찮은데 3시부터 4시 사이면 가능합니다. 대신에 질문지를 미리 보내 주시면 준비해서 더 정확하게 답변드릴 수 있을 것 같아요. 30분 안에 끝내는 대신에 필요한 자료는 제가 미리 정리해 두겠습니다. 시간 확정되면 회의실 예약 부탁드려요.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "고객님, 카드 명세서에 3월 12일 자로 결제된 59,000원 건에 대해 문의 주셨죠. 확인 결과 온라인 쇼핑몰 정기 결제로 보입니다. 취소를 원하시면 알려 주세요.",
    stimulus_en: "You asked about the 59,000 won charge dated March 12 on your card statement. It appears to be a recurring payment from an online shop. Let us know if you want it canceled.",
    prompt_kr: "카드사 상담원의 답변에 추가로 확인을 요청하는 답장을 다섯 문장으로 써 보세요. '-는지 확인해 주실 수 있을까요'를 사용하세요.",
    prompt_en: "Write a five-sentence reply to a card company's response, asking them to check something further. Use '-는지 확인해 주실 수 있을까요'.",
    example_kr: "확인해 주셔서 감사합니다. 그런데 저는 그 쇼핑몰에 정기 결제를 신청한 기억이 없어요. 혹시 언제부터 결제가 시작됐는지 확인해 주실 수 있을까요? 그리고 이전에도 같은 금액이 빠져나갔는지 확인해 주실 수 있을까요? 확인되면 바로 취소하고 싶습니다.",
  },
];
