import type { RawPrompt } from "./types";

export const WRITING_B1_REPLY: RawPrompt[] = [
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    stimulus_ja: "今日忙しいですか？",
    stimulus_zh: "你今天忙吗？",
    stimulus_vi: "Hôm nay bạn bận không?",
    stimulus_es: "¿Estás ocupado hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 드라마를 봐서 친구를 만났어요.",
    example_en: "Yes, I watched a drama and met a friend.",
    example_ja: "はい、私はドラマを見て、友達に会いました。",
    example_zh: "是的，我看了电视剧，所以见了朋友。",
    example_vi: "Vâng, tôi đã xem phim truyền hình rồi đi gặp bạn.",
    example_es: "Sí, vi un drama y quedé con un amigo.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    stimulus_ja: "今どこですか？",
    stimulus_zh: "你现在在哪里？",
    stimulus_vi: "Bây giờ bạn đang ở đâu?",
    stimulus_es: "¿Dónde estás ahora?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 영화를 봐서 빨래를 했어요.",
    example_en: "Yes, I watched a movie and did laundry.",
    example_ja: "はい、私は映画を見て、洗濯をしました。",
    example_zh: "是的，我看了电影，所以洗了衣服。",
    example_vi: "Vâng, tôi đã xem phim rồi giặt đồ.",
    example_es: "Sí, vi una película y lavé la ropa.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    stimulus_ja: "今日の天気はどうですか？",
    stimulus_zh: "今天天气怎么样？",
    stimulus_vi: "Hôm nay thời tiết thế nào?",
    stimulus_es: "¿Cómo está el clima hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 발표를 준비해서 요리를 했어요.",
    example_en: "Yes, I prepared a presentation and cooked.",
    example_ja: "はい、私は発表を準備して、料理をしました。",
    example_zh: "是的，我准备了演讲，所以做了饭。",
    example_vi: "Vâng, tôi đã chuẩn bị bài thuyết trình rồi nấu ăn.",
    example_es: "Sí, preparé una presentación y cociné.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    stimulus_ja: "一緒に映画を見ませんか？",
    stimulus_zh: "要一起看电影吗？",
    stimulus_vi: "Cùng xem phim không?",
    stimulus_es: "¿Quieres ver una película juntos?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 영화를 봐서 회의를 했어요.",
    example_en: "Yes, I watched a movie and had a meeting.",
    example_ja: "はい、私は映画を見て、会議をしました。",
    example_zh: "是的，我看了电影，所以开了会。",
    example_vi: "Vâng, tôi đã xem phim rồi họp.",
    example_es: "Sí, vi una película y tuve una reunión.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    stimulus_ja: "旅行はどうでしたか？",
    stimulus_zh: "旅行怎么样？",
    stimulus_vi: "Chuyến du lịch thế nào?",
    stimulus_es: "¿Qué tal el viaje?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 한국어를 공부해서 음악을 들었어요.",
    example_en: "Yes, I studied Korean and listened to music.",
    example_ja: "はい、私は韓国語を勉強して、音楽を聴きました。",
    example_zh: "是的，我学了韩语，所以听了音乐。",
    example_vi: "Vâng, tôi đã học tiếng Hàn rồi nghe nhạc.",
    example_es: "Sí, estudié coreano y escuché música.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    stimulus_ja: "宿題は全部終わりましたか？",
    stimulus_zh: "作业都做完了吗？",
    stimulus_vi: "Bạn làm xong bài tập chưa?",
    stimulus_es: "¿Terminaste toda la tarea?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 사진을 찍어서 요리를 했어요.",
    example_en: "Yes, I took photos and cooked.",
    example_ja: "はい、私は写真を撮って、料理をしました。",
    example_zh: "是的，我拍了照片，所以做了饭。",
    example_vi: "Vâng, tôi đã chụp ảnh rồi nấu ăn.",
    example_es: "Sí, tomé fotos y cociné.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    stimulus_ja: "この本、読んでみましたか？",
    stimulus_zh: "你读过这本书吗？",
    stimulus_vi: "Bạn đã đọc cuốn sách này chưa?",
    stimulus_es: "¿Has leído este libro?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 요리를 해서 과일을 샀어요.",
    example_en: "Yes, I cooked and bought fruit.",
    example_ja: "はい、私は料理をして、果物を買いました。",
    example_zh: "是的，我做了饭，所以买了水果。",
    example_vi: "Vâng, tôi đã nấu ăn rồi mua trái cây.",
    example_es: "Sí, cociné y compré fruta.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    stimulus_ja: "昨日どうして来なかったんですか？",
    stimulus_zh: "你昨天为什么没来？",
    stimulus_vi: "Sao hôm qua bạn không đến?",
    stimulus_es: "¿Por qué no viniste ayer?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 산에 가서 과일을 샀어요.",
    example_en: "Yes, I went to the mountain and bought fruit.",
    example_ja: "はい、私は山に行って、果物を買いました。",
    example_zh: "是的，我去了山里，所以买了水果。",
    example_vi: "Vâng, tôi đã đi núi rồi mua trái cây.",
    example_es: "Sí, fui a la montaña y compré fruta.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    stimulus_ja: "今週末、何をするつもりですか？",
    stimulus_zh: "这周末你打算做什么？",
    stimulus_vi: "Cuối tuần này bạn định làm gì?",
    stimulus_es: "¿Qué vas a hacer este fin de semana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 사진을 찍어서 회의를 했어요.",
    example_en: "Yes, I took photos and had a meeting.",
    example_ja: "はい、私は写真を撮って、会議をしました。",
    example_zh: "是的，我拍了照片，所以开了会。",
    example_vi: "Vâng, tôi đã chụp ảnh rồi họp.",
    example_es: "Sí, tomé fotos y tuve una reunión.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    stimulus_ja: "今日は何時に終わりますか？",
    stimulus_zh: "你今天几点结束？",
    stimulus_vi: "Hôm nay mấy giờ bạn xong việc?",
    stimulus_es: "¿A qué hora terminas hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 요리를 해서 일찍 일어났어요.",
    example_en: "Yes, I cooked and woke up early.",
    example_ja: "はい、私は料理をして、早く起きました。",
    example_zh: "是的，我做了饭，所以早起了。",
    example_vi: "Vâng, tôi đã nấu ăn rồi dậy sớm.",
    example_es: "Sí, cociné y me desperté temprano.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    stimulus_ja: "週末はよく過ごせましたか？",
    stimulus_zh: "周末过得好吗？",
    stimulus_vi: "Bạn đã có cuối tuần vui vẻ chứ?",
    stimulus_es: "¿Tuviste un buen fin de semana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 시장에 가서 산에 갔어요.",
    example_en: "Yes, I went to the market and went to the mountain.",
    example_ja: "はい、私は市場に行って、山に行きました。",
    example_zh: "是的，我去了市场，所以去了山里。",
    example_vi: "Vâng, tôi đã đi chợ rồi đi núi.",
    example_es: "Sí, fui al mercado y fui a la montaña.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    stimulus_ja: "夕食は何が食べたいですか？",
    stimulus_zh: "晚饭想吃什么？",
    stimulus_vi: "Tối nay bạn muốn ăn gì?",
    stimulus_es: "¿Qué quieres comer de cena?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 쇼핑을 해서 화분에 물을 줬어요.",
    example_en: "Yes, I went shopping and watered the plants.",
    example_ja: "はい、私は買い物をして、植木鉢に水をあげました。",
    example_zh: "是的，我购物了，所以给花盆浇了水。",
    example_vi: "Vâng, tôi đã đi mua sắm rồi tưới cây.",
    example_es: "Sí, fui de compras y regué las plantas.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    stimulus_ja: "今日の夕方は何をしますか？",
    stimulus_zh: "今天晚上做什么？",
    stimulus_vi: "Tối nay bạn làm gì?",
    stimulus_es: "¿Qué haces esta noche?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 커피를 마셔서 커피숍에 갔어요.",
    example_en: "Yes, I drank coffee and went to a coffee shop.",
    example_ja: "はい、私はコーヒーを飲んで、喫茶店に行きました。",
    example_zh: "是的，我喝了咖啡，所以去了咖啡厅。",
    example_vi: "Vâng, tôi đã uống cà phê rồi đến quán cà phê.",
    example_es: "Sí, tomé café y fui a una cafetería.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    stimulus_ja: "コーヒー一杯どうですか？",
    stimulus_zh: "要喝杯咖啡吗？",
    stimulus_vi: "Đi uống cà phê không?",
    stimulus_es: "¿Quieres tomar un café?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 일찍 자서 늦게까지 일했어요.",
    example_en: "Yes, I went to bed early and worked late.",
    example_ja: "はい、私は早く寝て、遅くまで働きました。",
    example_zh: "是的，我早睡了，所以工作到很晚。",
    example_vi: "Vâng, tôi đã ngủ sớm rồi làm việc đến khuya.",
    example_es: "Sí, me acosté temprano y trabajé hasta tarde.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    stimulus_ja: "誕生日おめでとう！",
    stimulus_zh: "生日快乐！",
    stimulus_vi: "Chúc mừng sinh nhật!",
    stimulus_es: "¡Feliz cumpleaños!",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 김치찌개를 만들어서 화분에 물을 줬어요.",
    example_en: "Yes, I made kimchi stew and watered the plants.",
    example_ja: "はい、私はキムチチゲを作って、植木鉢に水をあげました。",
    example_zh: "是的，我做了泡菜汤，所以给花盆浇了水。",
    example_vi: "Vâng, tôi đã nấu canh kimchi rồi tưới cây.",
    example_es: "Sí, preparé sopa de kimchi y regué las plantas.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    stimulus_ja: "週末、時間ありますか？",
    stimulus_zh: "周末有时间吗？",
    stimulus_vi: "Cuối tuần bạn có rảnh không?",
    stimulus_es: "¿Tienes tiempo el fin de semana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 도서관에 가서 드라마를 봤어요.",
    example_en: "Yes, I went to the library and watched a drama.",
    example_ja: "はい、私は図書館に行って、ドラマを見ました。",
    example_zh: "是的，我去了图书馆，所以看了电视剧。",
    example_vi: "Vâng, tôi đã đến thư viện rồi xem phim truyền hình.",
    example_es: "Sí, fui a la biblioteca y vi un drama.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    stimulus_ja: "昨日、よく眠れましたか？",
    stimulus_zh: "昨天睡得好吗？",
    stimulus_vi: "Hôm qua bạn ngủ ngon không?",
    stimulus_es: "¿Dormiste bien ayer?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 일찍 자서 친구 집에 갔어요.",
    example_en: "Yes, I went to bed early and went to a friend's house.",
    example_ja: "はい、私は早く寝て、友達の家に行きました。",
    example_zh: "是的，我早睡了，所以去了朋友家。",
    example_vi: "Vâng, tôi đã ngủ sớm rồi đến nhà bạn.",
    example_es: "Sí, me acosté temprano y fui a la casa de un amigo.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    stimulus_ja: "明日、時間は大丈夫ですか？",
    stimulus_zh: "明天有空吗？",
    stimulus_vi: "Ngày mai bạn rảnh không?",
    stimulus_es: "¿Tienes tiempo mañana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 운동을 해서 새 신발을 샀어요.",
    example_en: "Yes, I exercised and bought new shoes.",
    example_ja: "はい、私は運動をして、新しい靴を買いました。",
    example_zh: "是的，我运动了，所以买了新鞋。",
    example_vi: "Vâng, tôi đã tập thể dục rồi mua giày mới.",
    example_es: "Sí, hice ejercicio y compré zapatos nuevos.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    stimulus_ja: "今日の会議は何時ですか？",
    stimulus_zh: "今天会议几点？",
    stimulus_vi: "Hôm nay cuộc họp lúc mấy giờ?",
    stimulus_es: "¿A qué hora es la reunión hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 영화를 봐서 요리를 했어요.",
    example_en: "Yes, I watched a movie and cooked.",
    example_ja: "はい、私は映画を見て、料理をしました。",
    example_zh: "是的，我看了电影，所以做了饭。",
    example_vi: "Vâng, tôi đã xem phim rồi nấu ăn.",
    example_es: "Sí, vi una película y cociné.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "점심 같이 먹을래요?",
    stimulus_en: "Want to have lunch together?",
    stimulus_ja: "お昼、一緒に食べませんか？",
    stimulus_zh: "要一起吃午饭吗？",
    stimulus_vi: "Cùng ăn trưa không?",
    stimulus_es: "¿Quieres almorzar juntos?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 바다에 가서 요리를 했어요.",
    example_en: "Yes, I went to the beach and cooked.",
    example_ja: "はい、私は海に行って、料理をしました。",
    example_zh: "是的，我去了海边，所以做了饭。",
    example_vi: "Vâng, tôi đã đi biển rồi nấu ăn.",
    example_es: "Sí, fui a la playa y cociné.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    stimulus_ja: "今日忙しいですか？",
    stimulus_zh: "你今天忙吗？",
    stimulus_vi: "Hôm nay bạn bận không?",
    stimulus_es: "¿Estás ocupado hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 방을 정리해서 커피숍에 갔어요.",
    example_en: "Yes, I tidied my room and went to a coffee shop.",
    example_ja: "はい、私は部屋を片付けて、喫茶店に行きました。",
    example_zh: "是的，我整理了房间，所以去了咖啡厅。",
    example_vi: "Vâng, tôi đã dọn phòng rồi đến quán cà phê.",
    example_es: "Sí, ordené mi cuarto y fui a una cafetería.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    stimulus_ja: "今どこですか？",
    stimulus_zh: "你现在在哪里？",
    stimulus_vi: "Bây giờ bạn đang ở đâu?",
    stimulus_es: "¿Dónde estás ahora?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 책을 읽어서 드라마를 봤어요.",
    example_en: "Yes, I read a book and watched a drama.",
    example_ja: "はい、私は本を読んで、ドラマを見ました。",
    example_zh: "是的，我读了书，所以看了电视剧。",
    example_vi: "Vâng, tôi đã đọc sách rồi xem phim truyền hình.",
    example_es: "Sí, leí un libro y vi un drama.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    stimulus_ja: "今日の天気はどうですか？",
    stimulus_zh: "今天天气怎么样？",
    stimulus_vi: "Hôm nay thời tiết thế nào?",
    stimulus_es: "¿Cómo está el clima hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 도서관에 가서 친구를 만났어요.",
    example_en: "Yes, I went to the library and met a friend.",
    example_ja: "はい、私は図書館に行って、友達に会いました。",
    example_zh: "是的，我去了图书馆，所以见了朋友。",
    example_vi: "Vâng, tôi đã đến thư viện rồi gặp bạn.",
    example_es: "Sí, fui a la biblioteca y quedé con un amigo.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    stimulus_ja: "一緒に映画を見ませんか？",
    stimulus_zh: "要一起看电影吗？",
    stimulus_vi: "Cùng xem phim không?",
    stimulus_es: "¿Quieres ver una película juntos?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 고양이 밥을 줘서 김치찌개를 만들었어요.",
    example_en: "Yes, I fed the cat and made kimchi stew.",
    example_ja: "はい、私は猫にご飯をあげて、キムチチゲを作りました。",
    example_zh: "是的，我给猫喂了饭，所以做了泡菜汤。",
    example_vi: "Vâng, tôi đã cho mèo ăn rồi nấu canh kimchi.",
    example_es: "Sí, alimenté al gato e hice sopa de kimchi.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    stimulus_ja: "旅行はどうでしたか？",
    stimulus_zh: "旅行怎么样？",
    stimulus_vi: "Chuyến du lịch thế nào?",
    stimulus_es: "¿Qué tal el viaje?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 회의를 해서 쇼핑을 했어요.",
    example_en: "Yes, I had a meeting and went shopping.",
    example_ja: "はい、私は会議をして、買い物をしました。",
    example_zh: "是的，我开了会，所以购物了。",
    example_vi: "Vâng, tôi đã họp rồi đi mua sắm.",
    example_es: "Sí, tuve una reunión y fui de compras.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    stimulus_ja: "宿題は全部終わりましたか？",
    stimulus_zh: "作业都做完了吗？",
    stimulus_vi: "Bạn làm xong bài tập chưa?",
    stimulus_es: "¿Terminaste toda la tarea?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 운동을 해서 화분에 물을 줬어요.",
    example_en: "Yes, I exercised and watered the plants.",
    example_ja: "はい、私は運動をして、植木鉢に水をあげました。",
    example_zh: "是的，我运动了，所以给花盆浇了水。",
    example_vi: "Vâng, tôi đã tập thể dục rồi tưới cây.",
    example_es: "Sí, hice ejercicio y regué las plantas.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    stimulus_ja: "この本、読んでみましたか？",
    stimulus_zh: "你读过这本书吗？",
    stimulus_vi: "Bạn đã đọc cuốn sách này chưa?",
    stimulus_es: "¿Has leído este libro?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 책을 읽어서 회의를 했어요.",
    example_en: "Yes, I read a book and had a meeting.",
    example_ja: "はい、私は本を読んで、会議をしました。",
    example_zh: "是的，我读了书，所以开了会。",
    example_vi: "Vâng, tôi đã đọc sách rồi họp.",
    example_es: "Sí, leí un libro y tuve una reunión.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    stimulus_ja: "昨日どうして来なかったんですか？",
    stimulus_zh: "你昨天为什么没来？",
    stimulus_vi: "Sao hôm qua bạn không đến?",
    stimulus_es: "¿Por qué no viniste ayer?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 방을 정리해서 일찍 잤어요.",
    example_en: "Yes, I tidied my room and went to bed early.",
    example_ja: "はい、私は部屋を片付けて、早く寝ました。",
    example_zh: "是的，我整理了房间，所以早睡了。",
    example_vi: "Vâng, tôi đã dọn phòng rồi ngủ sớm.",
    example_es: "Sí, ordené mi cuarto y me acosté temprano.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    stimulus_ja: "今週末、何をするつもりですか？",
    stimulus_zh: "这周末你打算做什么？",
    stimulus_vi: "Cuối tuần này bạn định làm gì?",
    stimulus_es: "¿Qué vas a hacer este fin de semana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 숙제를 해서 늦게까지 일했어요.",
    example_en: "Yes, I did homework and worked late.",
    example_ja: "はい、私は宿題をして、遅くまで働きました。",
    example_zh: "是的，我做了作业，所以工作到很晚。",
    example_vi: "Vâng, tôi đã làm bài tập rồi làm việc đến khuya.",
    example_es: "Sí, hice la tarea y trabajé hasta tarde.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    stimulus_ja: "今日は何時に終わりますか？",
    stimulus_zh: "你今天几点结束？",
    stimulus_vi: "Hôm nay mấy giờ bạn xong việc?",
    stimulus_es: "¿A qué hora terminas hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 시장에 가서 텔레비전을 봤어요.",
    example_en: "Yes, I went to the market and watched TV.",
    example_ja: "はい、私は市場に行って、テレビを見ました。",
    example_zh: "是的，我去了市场，所以看了电视。",
    example_vi: "Vâng, tôi đã đi chợ rồi xem tivi.",
    example_es: "Sí, fui al mercado y vi televisión.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    stimulus_ja: "週末はよく過ごせましたか？",
    stimulus_zh: "周末过得好吗？",
    stimulus_vi: "Bạn đã có cuối tuần vui vẻ chứ?",
    stimulus_es: "¿Tuviste un buen fin de semana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 빵을 구워서 빵을 먹었어요.",
    example_en: "Yes, I baked bread and ate bread.",
    example_ja: "はい、私はパンを焼いて、パンを食べました。",
    example_zh: "是的，我烤了面包，所以吃了面包。",
    example_vi: "Vâng, tôi đã nướng bánh mì rồi ăn bánh.",
    example_es: "Sí, horneé pan y comí pan.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    stimulus_ja: "夕食は何が食べたいですか？",
    stimulus_zh: "晚饭想吃什么？",
    stimulus_vi: "Tối nay bạn muốn ăn gì?",
    stimulus_es: "¿Qué quieres comer de cena?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 빨래를 해서 새 신발을 샀어요.",
    example_en: "Yes, I did laundry and bought new shoes.",
    example_ja: "はい、私は洗濯をして、新しい靴を買いました。",
    example_zh: "是的，我洗了衣服，所以买了新鞋。",
    example_vi: "Vâng, tôi đã giặt đồ rồi mua giày mới.",
    example_es: "Sí, lavé la ropa y compré zapatos nuevos.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    stimulus_ja: "今日の夕方は何をしますか？",
    stimulus_zh: "今天晚上做什么？",
    stimulus_vi: "Tối nay bạn làm gì?",
    stimulus_es: "¿Qué haces esta noche?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 아이스크림을 먹어서 친구 집에 갔어요.",
    example_en: "Yes, I ate ice cream and went to a friend's house.",
    example_ja: "はい、私はアイスクリームを食べて、友達の家に行きました。",
    example_zh: "是的，我吃了冰淇淋，所以去了朋友家。",
    example_vi: "Vâng, tôi đã ăn kem rồi đến nhà bạn.",
    example_es: "Sí, comí helado y fui a la casa de un amigo.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    stimulus_ja: "コーヒー一杯どうですか？",
    stimulus_zh: "要喝杯咖啡吗？",
    stimulus_vi: "Đi uống cà phê không?",
    stimulus_es: "¿Quieres tomar un café?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 아이스크림을 먹어서 편지를 썼어요.",
    example_en: "Yes, I ate ice cream and wrote a letter.",
    example_ja: "はい、私はアイスクリームを食べて、手紙を書きました。",
    example_zh: "是的，我吃了冰淇淋，所以写了信。",
    example_vi: "Vâng, tôi đã ăn kem rồi viết thư.",
    example_es: "Sí, comí helado y escribí una carta.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    stimulus_ja: "誕生日おめでとう！",
    stimulus_zh: "生日快乐！",
    stimulus_vi: "Chúc mừng sinh nhật!",
    stimulus_es: "¡Feliz cumpleaños!",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 늦게까지 일해서 음악을 들었어요.",
    example_en: "Yes, I worked late and listened to music.",
    example_ja: "はい、私は遅くまで働いて、音楽を聴きました。",
    example_zh: "是的，我工作到很晚，所以听了音乐。",
    example_vi: "Vâng, tôi đã làm việc đến khuya rồi nghe nhạc.",
    example_es: "Sí, trabajé hasta tarde y escuché música.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    stimulus_ja: "週末、時間ありますか？",
    stimulus_zh: "周末有时间吗？",
    stimulus_vi: "Cuối tuần bạn có rảnh không?",
    stimulus_es: "¿Tienes tiempo el fin de semana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 친구 집에 가서 시장에 갔어요.",
    example_en: "Yes, I went to a friend's house and went to the market.",
    example_ja: "はい、私は友達の家に行って、市場に行きました。",
    example_zh: "是的，我去了朋友家，所以去了市场。",
    example_vi: "Vâng, tôi đã đến nhà bạn rồi đi chợ.",
    example_es: "Sí, fui a la casa de un amigo y fui al mercado.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    stimulus_ja: "昨日、よく眠れましたか？",
    stimulus_zh: "昨天睡得好吗？",
    stimulus_vi: "Hôm qua bạn ngủ ngon không?",
    stimulus_es: "¿Dormiste bien ayer?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 산에 가서 친구 집에 갔어요.",
    example_en: "Yes, I went to the mountain and went to a friend's house.",
    example_ja: "はい、私は山に行って、友達の家に行きました。",
    example_zh: "是的，我去了山里，所以去了朋友家。",
    example_vi: "Vâng, tôi đã đi núi rồi đến nhà bạn.",
    example_es: "Sí, fui a la montaña y fui a la casa de un amigo.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    stimulus_ja: "明日、時間は大丈夫ですか？",
    stimulus_zh: "明天有空吗？",
    stimulus_vi: "Ngày mai bạn rảnh không?",
    stimulus_es: "¿Tienes tiempo mañana?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 청소를 해서 이메일을 보냈어요.",
    example_en: "Yes, I cleaned and sent an email.",
    example_ja: "はい、私は掃除をして、メールを送りました。",
    example_zh: "是的，我打扫了卫生，所以发了邮件。",
    example_vi: "Vâng, tôi đã dọn dẹp rồi gửi email.",
    example_es: "Sí, limpié y envié un correo electrónico.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    stimulus_ja: "今日の会議は何時ですか？",
    stimulus_zh: "今天会议几点？",
    stimulus_vi: "Hôm nay cuộc họp lúc mấy giờ?",
    stimulus_es: "¿A qué hora es la reunión hoy?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    prompt_vi: "Hãy thử trả lời tin nhắn của bạn.",
    prompt_es: "Intenta responder al mensaje de tu amigo.",
    example_kr: "네, 저는 산에 가서 화분에 물을 줬어요.",
    example_en: "Yes, I went to the mountain and watered the plants.",
    example_ja: "はい、私は山に行って、植木鉢に水をあげました。",
    example_zh: "是的，我去了山里，所以给花盆浇了水。",
    example_vi: "Vâng, tôi đã đi núi rồi tưới cây.",
    example_es: "Sí, fui a la montaña y regué las plantas.",
  },
];
