import type { RawPrompt } from "./types";

export const WRITING_B1_REPLY: RawPrompt[] = [
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 드라마를 봐서 친구를 만났어요.",
    example_en: "Yes, I watched a drama and met a friend.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화를 봐서 빨래를 했어요.",
    example_en: "Yes, I watched a movie and did laundry.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 발표를 준비해서 요리를 했어요.",
    example_en: "Yes, I prepared a presentation and cooked.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화를 봐서 회의를 했어요.",
    example_en: "Yes, I watched a movie and had a meeting.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 한국어를 공부해서 음악을 들었어요.",
    example_en: "Yes, I studied Korean and listened to music.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 사진을 찍어서 요리를 했어요.",
    example_en: "Yes, I took photos and cooked.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 요리를 해서 과일을 샀어요.",
    example_en: "Yes, I cooked and bought fruit.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 산에 가서 과일을 샀어요.",
    example_en: "Yes, I went to the mountain and bought fruit.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 사진을 찍어서 회의를 했어요.",
    example_en: "Yes, I took photos and had a meeting.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 요리를 해서 일찍 일어났어요.",
    example_en: "Yes, I cooked and woke up early.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 시장에 가서 산에 갔어요.",
    example_en: "Yes, I went to the market and went to the mountain.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 쇼핑을 해서 화분에 물을 줬어요.",
    example_en: "Yes, I went shopping and watered the plants.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 커피를 마셔서 커피숍에 갔어요.",
    example_en: "Yes, I drank coffee and went to a coffee shop.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 일찍 자서 늦게까지 일했어요.",
    example_en: "Yes, I went to bed early and worked late.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 김치찌개를 만들어서 화분에 물을 줬어요.",
    example_en: "Yes, I made kimchi stew and watered the plants.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 도서관에 가서 드라마를 봤어요.",
    example_en: "Yes, I went to the library and watched a drama.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 일찍 자서 친구 집에 갔어요.",
    example_en: "Yes, I went to bed early and went to a friend's house.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 운동을 해서 새 신발을 샀어요.",
    example_en: "Yes, I exercised and bought new shoes.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화를 봐서 요리를 했어요.",
    example_en: "Yes, I watched a movie and cooked.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "점심 같이 먹을래요?",
    stimulus_en: "Want to have lunch together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 바다에 가서 요리를 했어요.",
    example_en: "Yes, I went to the beach and cooked.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 방을 정리해서 커피숍에 갔어요.",
    example_en: "Yes, I tidied my room and went to a coffee shop.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 책을 읽어서 드라마를 봤어요.",
    example_en: "Yes, I read a book and watched a drama.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 도서관에 가서 친구를 만났어요.",
    example_en: "Yes, I went to the library and met a friend.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 고양이 밥을 줘서 김치찌개를 만들었어요.",
    example_en: "Yes, I fed the cat and made kimchi stew.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 회의를 해서 쇼핑을 했어요.",
    example_en: "Yes, I had a meeting and went shopping.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 운동을 해서 화분에 물을 줬어요.",
    example_en: "Yes, I exercised and watered the plants.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 책을 읽어서 회의를 했어요.",
    example_en: "Yes, I read a book and had a meeting.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 방을 정리해서 일찍 잤어요.",
    example_en: "Yes, I tidied my room and went to bed early.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 숙제를 해서 늦게까지 일했어요.",
    example_en: "Yes, I did homework and worked late.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 시장에 가서 텔레비전을 봤어요.",
    example_en: "Yes, I went to the market and watched TV.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 빵을 구워서 빵을 먹었어요.",
    example_en: "Yes, I baked bread and ate bread.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 빨래를 해서 새 신발을 샀어요.",
    example_en: "Yes, I did laundry and bought new shoes.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 아이스크림을 먹어서 친구 집에 갔어요.",
    example_en: "Yes, I ate ice cream and went to a friend's house.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 아이스크림을 먹어서 편지를 썼어요.",
    example_en: "Yes, I ate ice cream and wrote a letter.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 늦게까지 일해서 음악을 들었어요.",
    example_en: "Yes, I worked late and listened to music.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 친구 집에 가서 시장에 갔어요.",
    example_en: "Yes, I went to a friend's house and went to the market.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 산에 가서 친구 집에 갔어요.",
    example_en: "Yes, I went to the mountain and went to a friend's house.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 청소를 해서 이메일을 보냈어요.",
    example_en: "Yes, I cleaned and sent an email.",
  },
  {
    level: "B1",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 산에 가서 화분에 물을 줬어요.",
    example_en: "Yes, I went to the mountain and watered the plants.",
  },
];
