import type { RawPrompt } from "./types";

export const WRITING_B2_A: RawPrompt[] = [
  {
    level: "B2",
    prompt_kr: "저출산 문제를 해결하기 위해 정부가 현금을 지원하는 정책에 대해 어떻게 생각하십니까? '-는 이상'과 '-기는 하지만'을 사용해서 여섯 문장 이상으로 찬성과 반대 의견을 모두 제시하며 여러분의 생각을 쓰세요.",
    prompt_en: "What do you think about the government policy of giving cash subsidies to solve the low birth rate problem? Write six or more sentences presenting both sides, using '-는 이상' and '-기는 하지만'.",
    example_kr: "저출산 문제가 심각한 이상 정부가 적극적으로 나서야 한다는 데에는 동의한다. 현금 지원은 즉각적인 효과가 있기는 하지만 근본적인 원인을 해결하지는 못한다. 예를 들어 육아휴직 제도나 보육 시설 확충 없이 돈만 준다면 부모들의 부담은 크게 줄지 않을 것이다. 반면 현금 지원은 시행이 간단하고 효과를 빨리 확인할 수 있다는 장점도 있다. 결국 현금 지원과 제도 개선을 함께 추진하는 것이 이상적이라고 생각한다. 단기적인 처방과 장기적인 대책을 동시에 마련해야 저출산 문제를 해결할 수 있을 것이다.",
  },
  {
    level: "B2",
    prompt_kr: "지방 소멸을 막기 위해 청년들에게 지방 이주를 장려하는 정책에 대해 어떻게 생각하십니까? '-는 만큼'과 '-을 뿐만 아니라'를 사용해서 여섯 문장 이상으로 양쪽 입장을 모두 다루며 쓰세요.",
    prompt_en: "What do you think about policies encouraging young people to move to rural areas to prevent regional decline? Write six or more sentences covering both perspectives, using '-는 만큼' and '-을 뿐만 아니라'.",
    example_kr: "지방 인구가 빠르게 줄어드는 만큼 청년 이주 정책이 필요하다는 주장에는 공감한다. 지방으로 이주하면 주거비 부담이 줄어들 뿐만 아니라 창업 지원금도 받을 수 있어 매력적이다. 하지만 일자리와 문화 시설이 부족한 지방에서 오래 정착하기는 쉽지 않다. 정책이 단순히 이주만 유도하고 정착 지원은 소홀히 한다면 청년들은 곧 도시로 돌아갈 것이다. 그러므로 이주 장려금뿐만 아니라 지속적인 일자리 창출과 교육 인프라 개선이 함께 이루어져야 한다. 결국 지방 소멸을 막으려면 단기 지원을 넘어선 종합적인 대책이 필요하다.",
  },
  {
    level: "B2",
    prompt_kr: "정년을 연장하여 고령 근로자가 더 오래 일할 수 있게 하는 것에 대해 어떻게 생각하십니까? '-는 반면'과 '-더라도'를 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about extending the retirement age so older workers can work longer? Write six or more sentences presenting both pros and cons, using '-는 반면' and '-더라도'.",
    example_kr: "정년 연장은 고령 근로자의 소득을 보장해 주는 반면 청년층의 취업 기회를 줄일 수 있다는 우려가 있다. 나이가 들더라도 체력과 경험이 뒷받침된다면 충분히 생산성을 유지할 수 있는 사람들이 많다. 그런데 기업 입장에서는 인건비 부담이 커지는 반면 신규 채용 여력은 줄어드는 문제가 발생한다. 정년이 연장되더라도 임금 체계를 함께 조정하지 않으면 세대 간 갈등이 심화될 수 있다. 따라서 임금피크제와 같은 보완책을 함께 도입하는 것이 바람직하다고 본다. 고령화 사회에서는 이러한 균형 잡힌 접근이 반드시 필요하다.",
  },
  {
    level: "B2",
    prompt_kr: "1인 가구가 증가하는 현상에 대해 어떻게 생각하십니까? '-는 셈이다'와 '-기 마련이다'를 사용해서 여섯 문장 이상으로 양쪽 시각을 모두 담아 쓰세요.",
    prompt_en: "What do you think about the rising trend of single-person households? Write six or more sentences covering both viewpoints, using '-는 셈이다' and '-기 마련이다'.",
    example_kr: "전체 가구의 삼분의 일이 1인 가구라면 이미 우리 사회의 표준 가구 형태가 바뀐 셈이다. 혼자 살다 보면 외로움을 느끼기 마련이지만 동시에 자유롭게 시간을 쓸 수 있다는 장점도 크다. 경제적인 면에서는 생활비를 혼자 부담해야 하니 씀씀이를 더 신중하게 관리하는 셈이 된다. 사람은 누구나 어려운 순간에 도움이 필요하기 마련인데 1인 가구는 응급 상황에서 도움받기가 어렵다는 문제도 있다. 그럼에도 최근에는 1인 가구를 위한 소형 주택과 서비스가 늘어나고 있어 불편함이 점차 줄어드는 셈이다. 결국 1인 가구 증가는 피할 수 없는 흐름이므로 이에 맞는 사회 시스템을 마련하는 것이 중요하다.",
  },
  {
    level: "B2",
    prompt_kr: "대형 마트의 의무 휴업일 제도에 대해 어떻게 생각하십니까? '-는 한'과 '-을 경우'를 사용해서 여섯 문장 이상으로 찬성과 반대 입장을 모두 설명하세요.",
    prompt_en: "What do you think about the mandatory closing days for large supermarkets? Write six or more sentences explaining both the pro and con positions, using '-는 한' and '-을 경우'.",
    example_kr: "전통 시장을 보호하려는 목적이 있는 한 의무 휴업일 제도는 나름의 의미가 있다고 생각한다. 소비자가 의무 휴업일에 장을 보지 못할 경우 오히려 온라인 쇼핑으로 소비를 옮기는 경우가 많다는 지적도 있다. 실제로 대형 마트가 문을 닫을 경우 전통 시장 매출이 크게 늘지 않았다는 조사 결과도 있다. 소비자의 선택권을 존중하는 한 강제적인 규제보다는 시장 스스로 경쟁력을 높이도록 유도하는 것이 낫다는 의견도 있다. 다만 전통 시장이 살아남지 못할 경우 지역 경제와 일자리에 미치는 영향이 크다는 점도 고려해야 한다. 따라서 규제와 지원을 함께 병행하는 방향으로 제도를 개선할 필요가 있다.",
  },
  {
    level: "B2",
    prompt_kr: "명품 소비가 젊은 세대 사이에서 확산되는 현상에 대해 어떻게 생각하십니까? '-에 비해'와 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 양쪽 관점을 모두 제시하세요.",
    prompt_en: "What do you think about the spread of luxury goods consumption among young people? Write six or more sentences presenting both perspectives, using '-에 비해' and '-는 데 그치다'.",
    example_kr: "예전 세대에 비해 요즘 젊은 세대는 명품 소비를 자기표현의 수단으로 여기는 경향이 강하다. 소득 수준에 비해 지나치게 비싼 제품을 구매하는 경우도 적지 않아 우려스럽다. 이런 소비가 단순히 유행을 따르는 데 그친다면 장기적으로 경제적 부담만 커질 수 있다. 반면 다른 취미 활동에 비해 명품은 되팔 때 가치가 어느 정도 유지된다는 실용적인 이유를 드는 사람도 있다. 하지만 과시적 소비가 만족감을 주는 데 그치고 진정한 자기 발전으로 이어지지 않는다면 문제가 될 수 있다. 결국 소비의 목적과 한도를 스스로 명확히 정하는 태도가 필요하다고 본다.",
  },
  {
    level: "B2",
    prompt_kr: "주 4일 근무제 도입에 대해 어떻게 생각하십니까? '-도록 하다'와 '-을수록'을 사용해서 여섯 문장 이상으로 찬반 양쪽 입장을 모두 다루세요.",
    prompt_en: "What do you think about introducing a four-day work week? Write six or more sentences covering both the pro and con positions, using '-도록 하다' and '-을수록'.",
    example_kr: "근로 시간이 줄어들수록 노동자의 삶의 질이 높아진다는 연구 결과는 주 4일제 도입에 힘을 실어 준다. 회사는 업무 효율을 높이도록 시스템을 개선해야 하는데 이는 결코 쉬운 일이 아니다. 생산성이 낮아질수록 기업의 경쟁력이 떨어질 수 있다는 반박도 만만치 않다. 그럼에도 직원들이 충분히 휴식을 취하도록 제도를 마련한 기업에서는 오히려 창의성과 만족도가 높아졌다는 사례도 있다. 업무 강도가 세질수록 짧은 근무일이 오히려 효율을 끌어올릴 수도 있다. 결국 산업별 특성을 고려해 단계적으로 도입하도록 하는 것이 현실적인 대안이라고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들의 공무원 시험 쏠림 현상에 대해 어떻게 생각하십니까? '-는 이상'과 '-는 반면'을 사용해서 여섯 문장 이상으로 원인과 문제점을 모두 다루세요.",
    prompt_en: "What do you think about the trend of young people flocking to civil service exams? Write six or more sentences covering both causes and problems, using '-는 이상' and '-는 반면'.",
    example_kr: "취업 시장이 불안정한 이상 안정적인 공무원 직업을 선호하는 청년들의 선택은 충분히 이해할 수 있다. 공무원은 정년이 보장되는 반면 민간 기업은 언제든 구조조정의 위험이 있다는 점이 큰 차이다. 하지만 수많은 청년이 몇 년씩 시험 준비에만 매달리는 이상 다른 산업 분야의 인재 손실도 커질 수밖에 없다. 창업이나 새로운 분야에 도전하는 청년은 줄어드는 반면 안정만을 추구하는 분위기는 점점 강해지고 있다. 이런 쏠림 현상이 계속되는 이상 국가 전체의 혁신 동력이 약해질 위험도 있다. 따라서 민간 부문의 고용 안정성을 높이는 정책적 노력이 함께 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "재건축, 재개발로 인한 원주민 이주 문제에 대해 어떻게 생각하십니까? '-기는 하지만'과 '-을 경우'를 사용해서 여섯 문장 이상으로 양쪽 입장을 모두 설명하세요.",
    prompt_en: "What do you think about the displacement of original residents due to redevelopment? Write six or more sentences explaining both sides, using '-기는 하지만' and '-을 경우'.",
    example_kr: "재개발이 노후 주거 환경을 개선하기는 하지만 그 과정에서 원주민들이 겪는 어려움을 간과해서는 안 된다. 보상금을 받을 경우 새로운 지역에서 살 집을 구하기 어려운 경우가 많다는 것이 현실적인 문제다. 개발이 지역 경제를 활성화하기는 하지만 오랫동안 살아온 공동체가 해체되는 손실도 무시할 수 없다. 세입자의 경우 보상 대상에서 제외될 경우 갑작스럽게 삶의 터전을 잃게 될 위험도 있다. 재건축이 자산 가치를 높이기는 하지만 그 혜택이 모두에게 골고루 돌아가지는 않는다는 지적도 타당하다. 따라서 개발 이익을 원주민과 함께 나누는 제도적 장치가 마련되어야 한다.",
  },
  {
    level: "B2",
    prompt_kr: "온라인 쇼핑이 오프라인 상점을 대체하는 현상에 대해 어떻게 생각하십니까? '-는 만큼'과 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 양쪽 시각을 모두 제시하세요.",
    prompt_en: "What do you think about online shopping replacing brick-and-mortar stores? Write six or more sentences presenting both viewpoints, using '-는 만큼' and '-는 데 그치다'.",
    example_kr: "온라인 쇼핑이 편리한 만큼 소비자들이 오프라인 매장을 찾는 횟수는 점점 줄어들고 있다. 하지만 옷이나 신발처럼 직접 착용해 봐야 하는 상품은 온라인으로 구매하는 데 그치지 않고 결국 매장을 방문하는 경우가 많다. 가격 비교가 쉬운 만큼 온라인 쇼핑은 합리적인 소비를 돕는다는 장점이 있다. 그런데 오프라인 매장이 단순히 상품을 진열하는 데 그친다면 온라인에 밀려 경쟁력을 잃을 수밖에 없다. 매장들이 체험형 공간으로 변화를 시도하는 만큼 오프라인만의 가치를 새롭게 만들어 갈 가능성도 충분하다. 결국 온라인과 오프라인이 서로 보완하는 방향으로 발전해야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 실업 문제 해결을 위해 대기업 신입 채용을 정부가 지원해야 한다는 주장에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-더라도'를 사용해서 여섯 문장 이상으로 찬반을 모두 다루세요.",
    prompt_en: "What do you think about the argument that the government should support large companies' hiring of new graduates to solve youth unemployment? Write six or more sentences covering both sides, using '-을 뿐만 아니라' and '-더라도'.",
    example_kr: "정부 지원은 기업의 채용 부담을 줄여 줄 뿐만 아니라 청년들에게 새로운 기회를 제공한다는 점에서 긍정적이다. 예산이 제한적이더라도 우선순위를 정해 효과적으로 집행한다면 충분히 의미 있는 성과를 낼 수 있다. 반면 대기업은 이미 충분한 자본을 갖추고 있을 뿐만 아니라 정부 지원 없이도 채용을 늘릴 여력이 있다는 비판도 있다. 지원이 있더라도 기업이 실제로 신규 채용을 늘리지 않는다면 세금만 낭비하는 셈이 된다. 오히려 중소기업에 지원을 집중하는 것이 고용 창출뿐만 아니라 산업 균형 발전에도 도움이 될 수 있다. 그러므로 지원 대상과 방식을 신중하게 설계할 필요가 있다.",
  },
  {
    level: "B2",
    prompt_kr: "노키즈존 확산에 대해 어떻게 생각하십니까? '-는 셈이다'와 '-는 반면'을 사용해서 여섯 문장 이상으로 양쪽 입장을 모두 제시하세요.",
    prompt_en: "What do you think about the spread of no-kids zones? Write six or more sentences presenting both sides, using '-는 셈이다' and '-는 반면'.",
    example_kr: "일부 매장에서 아이 동반 손님의 출입을 막는 것은 사실상 특정 손님을 차별하는 셈이다. 조용한 분위기를 원하는 손님에게는 편안한 공간이 되는 반면 아이를 키우는 부모에게는 갈 곳이 줄어드는 문제가 생긴다. 매장 입장에서는 소음이나 안전사고에 대한 부담을 줄이려는 것인 셈이지만 그 해결 방식이 지나치게 배타적이라는 비판을 받는다. 일부 손님의 불편한 경험 때문에 전체 아동을 배제하는 것은 문제의 원인을 잘못 짚은 셈이다. 반면 아이를 위한 공간을 따로 마련한 매장들은 오히려 가족 손님을 더 많이 유치하고 있다. 결국 무조건적인 출입 금지보다는 배려와 공존을 위한 대안을 찾는 것이 바람직하다.",
  },
  {
    level: "B2",
    prompt_kr: "구독 경제(정기 구독 서비스)의 확산에 대해 어떻게 생각하십니까? '-기 마련이다'와 '-에 비해'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about the spread of the subscription economy? Write six or more sentences covering both advantages and disadvantages, using '-기 마련이다' and '-에 비해'.",
    example_kr: "매달 일정 금액을 내는 방식이다 보니 처음에는 부담이 적다고 느끼기 마련이다. 한 번에 구매하는 것에 비해 구독 서비스는 초기 비용 부담이 적어 접근성이 높다는 장점이 있다. 하지만 여러 서비스를 동시에 구독하다 보면 지출이 눈덩이처럼 불어나기 마련이다. 실제 사용량에 비해 구독료가 아깝다고 느끼면서도 해지 절차가 번거로워 계속 유지하는 사람도 많다. 편리함을 추구하다 보면 불필요한 지출이 생기기 마련이므로 정기적으로 구독 목록을 점검하는 습관이 필요하다. 결국 구독 경제는 편리한 만큼 소비자의 신중한 관리가 뒷받침되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "재택근무가 회사 조직 문화에 미치는 영향에 대해 어떻게 생각하십니까? '-는 한'과 '-도록 하다'를 사용해서 여섯 문장 이상으로 양쪽 측면을 모두 다루세요.",
    prompt_en: "What do you think about the impact of remote work on company organizational culture? Write six or more sentences covering both aspects, using '-는 한' and '-도록 하다'.",
    example_kr: "직원들이 서로 대면하지 않는 한 자연스러운 소통과 유대감을 형성하기가 쉽지 않다는 것이 재택근무의 한계로 지적된다. 회사는 이런 문제를 보완하도록 정기적인 온라인 모임이나 오프라인 워크숍을 마련해야 한다. 명확한 업무 지침이 있는 한 재택근무도 사무실 근무 못지않은 효율을 낼 수 있다. 신입 직원이 조직 문화에 적응하도록 돕는 멘토링 제도가 없다면 소속감을 느끼기 어려울 수 있다. 성과 평가 기준이 공정한 한 재택근무자와 사무실 근무자 사이의 불만도 줄어들 것이다. 결국 회사가 소통과 평가 체계를 잘 갖추도록 노력한다면 재택근무의 단점을 충분히 보완할 수 있다고 본다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들이 결혼을 미루거나 하지 않는 현상에 대해 어떻게 생각하십니까? '-을수록'과 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 원인과 사회적 영향을 모두 다루세요.",
    prompt_en: "What do you think about the trend of young people delaying or avoiding marriage? Write six or more sentences covering both causes and social effects, using '-을수록' and '-는 데 그치다'.",
    example_kr: "주거비 부담이 클수록 결혼을 미루는 청년들이 늘어나는 것은 자연스러운 결과라고 할 수 있다. 정부의 신혼부부 지원 정책이 단순히 대출 조건 완화에 그친다면 근본적인 해결책이 되기 어렵다. 취업이 불안정할수록 결혼과 출산을 인생의 부담으로 여기는 경향도 강해진다. 결혼에 대한 인식이 단지 필수가 아닌 선택으로 바뀌는 데 그치는 것이 아니라 아예 부정적으로 변하고 있다는 점도 우려스럽다. 사회적 지원이 부족할수록 청년들은 결혼과 육아를 더욱 꺼리게 될 것이다. 따라서 주거, 고용, 보육을 아우르는 종합적인 대책이 마련되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "물가 상승 시기에 정부가 가격을 통제해야 한다는 주장에 대해 어떻게 생각하십니까? '-는 이상'과 '-을 경우'를 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about the argument that the government should control prices during times of inflation? Write six or more sentences presenting both sides, using '-는 이상' and '-을 경우'.",
    example_kr: "서민 경제가 힘든 이상 정부가 물가 안정을 위해 개입해야 한다는 주장에는 일리가 있다. 정부가 가격 상한선을 정할 경우 소비자는 당장 부담을 덜 수 있어 환영할 만하다. 그러나 시장 원리를 무시하는 이상 기업들이 생산을 줄이거나 품질을 낮출 위험도 커진다. 가격을 인위적으로 통제할 경우 오히려 공급 부족과 암시장 형성 같은 부작용이 나타날 수 있다. 물가 문제가 구조적인 이상 단기적인 가격 통제만으로는 근본적인 해결이 어렵다. 따라서 취약 계층에 대한 직접 지원과 함께 신중한 시장 개입이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "배달 앱 수수료 문제에 대해 어떻게 생각하십니까? '-기는 하지만'과 '-는 셈이다'를 사용해서 여섯 문장 이상으로 자영업자와 플랫폼의 입장을 모두 다루세요.",
    prompt_en: "What do you think about the delivery app commission fee issue? Write six or more sentences covering both the small business owners' and platforms' positions, using '-기는 하지만' and '-는 셈이다'.",
    example_kr: "배달 앱이 소상공인에게 새로운 판매 창구를 열어 주기는 하지만 높은 수수료는 큰 부담이 되고 있다. 매출의 상당 부분을 수수료로 지불하다 보면 결국 실제로 남는 이익은 얼마 되지 않는 셈이다. 플랫폼 입장에서는 서버 운영과 마케팅 비용이 들기는 하지만 그 비용을 자영업자에게만 전가한다는 비판을 피하기 어렵다. 소비자 가격에 배달비까지 더해지면 결국 소비자와 자영업자 모두가 부담을 나눠 지는 셈이 된다. 정부가 상생 방안을 논의하기는 했지만 실질적인 수수료 인하로 이어지지 않는다면 의미가 없다. 결국 플랫폼, 자영업자, 소비자가 함께 부담을 나누는 합리적인 구조가 필요하다고 본다.",
  },
  {
    level: "B2",
    prompt_kr: "지역 화폐(지역사랑상품권) 발행 정책에 대해 어떻게 생각하십니까? '-는 만큼'과 '-더라도'를 사용해서 여섯 문장 이상으로 효과와 한계를 모두 다루세요.",
    prompt_en: "What do you think about the policy of issuing local currency (regional gift certificates)? Write six or more sentences covering both effects and limitations, using '-는 만큼' and '-더라도'.",
    example_kr: "지역 화폐는 그 지역 안에서만 사용할 수 있는 만큼 지역 소상공인의 매출 증대에 도움이 된다는 평가를 받는다. 사용처가 제한적이더라도 할인 혜택이 크다면 소비자들은 기꺼이 지역 화폐를 이용한다. 하지만 발행과 운영에 상당한 예산이 들어가는 만큼 그 효과가 비용에 비해 크지 않다는 비판도 있다. 소비가 늘어나더라도 그것이 다른 지역에서 쓸 소비를 그대로 옮겨 온 것에 불과하다면 실질적인 경제 효과는 제한적이다. 지역 경제가 활성화되는 만큼 대형 프랜차이즈보다 개인 상점에 혜택이 집중되도록 설계하는 것이 중요하다. 결국 지역 화폐의 취지를 살리려면 지속적인 제도 개선이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 창업 지원 정책 확대에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 기대와 우려를 모두 다루세요.",
    prompt_en: "What do you think about expanding support policies for youth entrepreneurship? Write six or more sentences covering both expectations and concerns, using '-을 뿐만 아니라' and '-는 데 그치다'.",
    example_kr: "청년 창업 지원은 새로운 일자리를 만들 뿐만 아니라 경제 전반에 활력을 불어넣는 효과가 있다. 하지만 일부 지원이 단순히 초기 자금 제공에 그친다면 창업 이후 지속 가능성을 확보하기 어렵다. 창업 교육 프로그램은 이론 교육뿐만 아니라 실전 경험을 쌓을 기회도 함께 제공해야 효과적이다. 정부 지원이 서류 심사에서 끝나는 데 그치고 사후 관리가 부족하다면 실패 확률이 높아질 수밖에 없다. 성공적인 창업 사례는 자금 지원뿐만 아니라 멘토링과 네트워킹 지원이 함께 이루어졌을 때 나타난다. 따라서 지원이 일회성에 그치지 않도록 장기적인 관점에서 정책을 설계해야 한다.",
  },
  {
    level: "B2",
    prompt_kr: "고령 운전자 면허 자진 반납 제도에 대해 어떻게 생각하십니까? '-을 경우'와 '-는 이상'을 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about the voluntary license surrender program for elderly drivers? Write six or more sentences presenting both sides, using '-을 경우' and '-는 이상'.",
    example_kr: "교통사고 통계에서 고령 운전자 비율이 높게 나타나는 이상 이러한 제도의 도입 취지는 이해할 만하다. 면허를 반납할 경우 대중교통 이용료 할인이나 상품권 같은 혜택을 제공하는 것은 참여를 유도하는 좋은 방법이다. 그러나 대중교통이 부족한 지역에 사는 이상 면허를 반납하면 오히려 이동권이 크게 제한될 수 있다. 노인이 운전을 그만둘 경우 병원 방문이나 장보기 같은 일상생활 자체가 어려워질 위험도 있다. 자율적인 선택인 이상 강제적인 반납보다는 개인의 상황을 고려한 유연한 접근이 필요하다. 따라서 지역별 이동 지원 체계를 함께 마련하는 것이 우선되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "무인 매장(키오스크, 셀프 계산대) 확산에 대해 어떻게 생각하십니까? '-는 반면'과 '-기 마련이다'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about the spread of unmanned stores (kiosks, self-checkout)? Write six or more sentences covering both advantages and disadvantages, using '-는 반면' and '-기 마련이다'.",
    example_kr: "무인 매장은 인건비를 절감할 수 있는 반면 일자리가 줄어드는 부작용도 함께 나타난다. 새로운 기술이 도입되면 처음에는 낯설게 느껴지기 마련이라 고령층이나 디지털 기기에 익숙하지 않은 사람들은 불편을 겪는다. 무인 시스템은 대기 시간을 줄여 주는 반면 문제가 생겼을 때 즉각적인 도움을 받기 어렵다는 단점이 있다. 사람이 직접 응대하지 않다 보면 서비스의 온기가 사라지기 마련이라는 지적도 나온다. 매장 운영 비용이 줄어드는 반면 초기 설비 투자 비용은 오히려 커질 수 있다는 점도 고려해야 한다. 결국 효율성과 접근성을 함께 고려한 균형 잡힌 도입이 필요하다고 본다.",
  },
  {
    level: "B2",
    prompt_kr: "육아휴직을 남성도 의무적으로 사용하게 하는 제도에 대해 어떻게 생각하십니까? '-도록 하다'와 '-에 비해'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about making paternity leave mandatory for men as well? Write six or more sentences covering both pro and con positions, using '-도록 하다' and '-에 비해'.",
    example_kr: "남성도 의무적으로 육아휴직을 사용하도록 하는 제도는 육아 부담을 부부가 함께 나누도록 돕는다는 점에서 긍정적이다. 여성에 비해 남성의 육아휴직 사용률이 여전히 낮은 현실을 고려하면 이러한 의무화는 필요한 조치라고 볼 수 있다. 회사가 인력 공백을 감당하도록 미리 대비하지 않는다면 중소기업에는 큰 부담이 될 수 있다. 대기업에 비해 인력이 부족한 중소기업은 대체 인력을 구하기가 훨씬 어렵다는 현실적인 문제도 있다. 육아휴직 급여를 실질적인 소득에 가깝도록 인상하지 않으면 제도가 유명무실해질 위험도 있다. 따라서 의무화와 함께 기업 지원책을 병행하도록 제도를 설계해야 한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들의 '영끌'(영혼까지 끌어모아 대출받기) 주택 구매에 대해 어떻게 생각하십니까? '-는 셈이다'와 '-을수록'을 사용해서 여섯 문장 이상으로 위험과 이유를 모두 다루세요.",
    prompt_en: "What do you think about young people taking on maximum loans (yeonggeul) to buy homes? Write six or more sentences covering both the risks and reasons, using '-는 셈이다' and '-을수록'.",
    example_kr: "소득의 대부분을 대출 이자로 쓴다면 사실상 미래의 소득을 앞당겨 쓰는 셈이다. 집값이 계속 오를수록 지금 사지 않으면 영영 내 집을 마련할 수 없다는 불안감도 커진다. 금리가 오를수록 이자 부담이 눈덩이처럼 불어나 가계 경제 전체를 위협할 수 있다. 무리한 대출로 집을 산다는 것은 결국 미래의 위험을 현재로 끌어오는 셈이라는 비판도 타당하다. 전세 사기 우려가 커질수록 차라리 대출을 받아서라도 내 집을 마련하려는 사람들이 늘어나는 것도 이해할 만하다. 결국 무리한 영끌을 막으려면 안정적인 주거 대안을 함께 제시하는 정책이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "정부의 부동산 세금 강화 정책에 대해 어떻게 생각하십니까? '-는 데 그치다'와 '-더라도'를 사용해서 여섯 문장 이상으로 효과와 한계를 모두 다루세요.",
    prompt_en: "What do you think about the government's policy of strengthening real estate taxes? Write six or more sentences covering both effects and limitations, using '-는 데 그치다' and '-더라도'.",
    example_kr: "다주택자에 대한 세금을 강화하면 투기 수요를 억제하는 효과를 기대할 수 있다. 하지만 세금 정책이 단기적인 가격 안정에 그친다면 근본적인 공급 부족 문제는 해결되지 않는다. 세금이 늘어나더라도 자산 가치 상승분이 그보다 크다면 투자자들은 여전히 주택을 매입할 것이다. 정책이 단순한 규제에 그치지 않고 실수요자를 위한 공급 확대와 함께 추진되어야 실질적인 효과를 낼 수 있다. 세금 부담이 커지더라도 임대료를 올려 세입자에게 전가한다면 오히려 서민들이 피해를 볼 수 있다. 따라서 세금 정책은 공급 정책과 함께 신중하게 설계되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 인구의 수도권 집중 현상에 대해 어떻게 생각하십니까? '-는 이상'과 '-을 뿐만 아니라'를 사용해서 여섯 문장 이상으로 원인과 문제점을 모두 다루세요.",
    prompt_en: "What do you think about the concentration of the young population in the metropolitan area? Write six or more sentences covering both causes and problems, using '-는 이상' and '-을 뿐만 아니라'.",
    example_kr: "양질의 일자리가 수도권에 집중되어 있는 이상 청년들이 서울로 몰리는 현상은 자연스러운 결과라고 할 수 있다. 수도권은 일자리가 많을 뿐만 아니라 교육과 문화 인프라도 잘 갖춰져 있어 청년들에게 매력적이다. 이런 쏠림 현상이 계속되는 이상 지방은 인구 감소와 경제 위축이라는 악순환에서 벗어나기 어렵다. 수도권 집중은 지방의 활력을 떨어뜨릴 뿐만 아니라 수도권 내에서도 주거비 폭등 같은 부작용을 낳고 있다. 청년들이 지방에서도 좋은 일자리를 찾을 수 있는 이상 굳이 무리해서 수도권으로 이주할 필요는 없어질 것이다. 따라서 지방에 양질의 일자리를 만드는 균형 발전 정책이 시급하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "긱 이코노미(플랫폼 노동)의 확산에 대해 어떻게 생각하십니까? '-는 반면'과 '-을 경우'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about the spread of the gig economy (platform labor)? Write six or more sentences covering both pros and cons, using '-는 반면' and '-을 경우'.",
    example_kr: "플랫폼 노동은 원하는 시간에 자유롭게 일할 수 있다는 장점이 있는 반면 소득이 불안정하다는 단점도 뚜렷하다. 일이 몰릴 경우 예상보다 높은 수입을 올릴 수 있지만 그렇지 않을 경우 생계에 큰 어려움을 겪을 수 있다. 전통적인 고용 형태에 비해 자유로운 반면 4대 보험이나 퇴직금 같은 사회 안전망의 혜택을 받기 어렵다. 사고가 발생할 경우 산재 처리를 받지 못하는 경우가 많아 노동자 보호가 미흡하다는 비판도 크다. 기업 입장에서는 인건비 부담이 줄어드는 반면 노동자의 소속감과 충성도는 낮아질 수 있다. 따라서 플랫폼 노동자를 위한 최소한의 사회 보장 제도가 마련되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "지방 대학 정원 축소 정책에 대해 어떻게 생각하십니까? '-기는 하지만'과 '-는 만큼'을 사용해서 여섯 문장 이상으로 필요성과 우려를 모두 다루세요.",
    prompt_en: "What do you think about the policy of reducing enrollment quotas at regional universities? Write six or more sentences covering both necessity and concerns, using '-기는 하지만' and '-는 만큼'.",
    example_kr: "학령 인구가 줄어드는 만큼 대학 정원을 조정하는 것은 불가피한 측면이 있다. 정원 축소가 대학의 재정난을 어느 정도 완화하기는 하지만 지역 경제에는 부정적인 영향을 미칠 수 있다. 대학은 지역 사회에서 중요한 역할을 하는 만큼 대학이 사라지면 그 지역의 상권과 인구도 함께 위축된다. 정부가 구조조정을 지원하기는 하지만 지방 대학들이 자체적으로 경쟁력을 갖추지 못하면 근본적인 해결은 어렵다. 학생 수가 줄어드는 만큼 특성화된 학과나 산학 협력 프로그램으로 차별화를 꾀하는 것이 중요하다. 결국 단순한 정원 축소를 넘어 지방 대학의 경쟁력을 살릴 방안이 함께 고민되어야 한다.",
  },
  {
    level: "B2",
    prompt_kr: "임산부 배려석과 같은 사회적 배려석 제도에 대해 어떻게 생각하십니까? '-기 마련이다'와 '-도록 하다'를 사용해서 여섯 문장 이상으로 실효성과 한계를 모두 다루세요.",
    prompt_en: "What do you think about the system of social consideration seats, such as pregnant women's priority seats? Write six or more sentences covering both effectiveness and limitations, using '-기 마련이다' and '-도록 하다'.",
    example_kr: "배려석이 비어 있으면 다른 사람들이 자연스럽게 앉고 싶어지기 마련이라 정작 필요한 사람이 이용하지 못하는 경우가 생긴다. 대중교통 운영 기관은 배려석의 취지를 알리는 홍보를 강화하도록 노력해야 한다. 초기 임산부는 겉으로 티가 나지 않다 보니 오해를 받기 마련이어서 배지나 표시 제도가 함께 필요하다. 시민들이 자율적으로 배려석을 비워 두도록 교육하는 것이 강제 규정보다 더 효과적일 수 있다. 사람이 많은 시간대일수록 배려석을 지키기 어려워지기 마련이라 현실적인 어려움도 존재한다. 결국 제도와 시민 의식이 함께 성장하도록 지속적인 노력이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 세대의 조기 은퇴(파이어족) 열풍에 대해 어떻게 생각하십니까? '-을수록'과 '-는 셈이다'를 사용해서 여섯 문장 이상으로 매력과 위험을 모두 다루세요.",
    prompt_en: "What do you think about the FIRE (Financial Independence, Retire Early) movement among young people? Write six or more sentences covering both its appeal and risks, using '-을수록' and '-는 셈이다'.",
    example_kr: "일찍부터 저축하고 투자할수록 젊은 나이에 경제적 자유를 얻을 가능성이 커진다는 점에서 파이어족의 목표는 매력적이다. 소비를 극도로 줄이며 사는 것은 결국 현재의 행복을 미래를 위해 저당 잡히는 셈이라는 비판도 있다. 은퇴 시점이 빠를수록 남은 인생 동안 자산을 관리해야 하는 부담도 그만큼 커진다. 조기 은퇴를 준비하는 과정에서 오히려 재정 관리 능력을 키우게 되는 셈이니 완전히 부정적으로만 볼 수는 없다. 투자 성과가 기대에 미치지 못할수록 은퇴 이후의 삶이 불안정해질 위험도 크다. 결국 파이어족을 꿈꾸더라도 현실적인 계획과 균형 잡힌 삶의 태도가 필요하다고 본다.",
  },
  {
    level: "B2",
    prompt_kr: "학교 급식을 전면 무상으로 제공하는 정책에 대해 어떻게 생각하십니까? '-는 이상'과 '-에 비해'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about the policy of providing fully free school meals? Write six or more sentences covering both pro and con positions, using '-는 이상' and '-에 비해'.",
    example_kr: "교육이 국가의 책임인 이상 급식도 공교육의 일부로 보고 무상으로 제공해야 한다는 주장은 설득력이 있다. 선별적 지원에 비해 전면 무상 급식은 낙인 효과를 없애고 모든 학생이 평등하게 급식을 받을 수 있다는 장점이 있다. 하지만 예산이 한정된 이상 무상 급식에 지나치게 많은 재원을 쓰면 다른 교육 사업이 위축될 수 있다. 저소득층 지원에 비해 전면 무상 급식은 재정 효율성이 떨어진다는 지적도 타당하다. 아이들의 건강한 성장이 중요한 이상 급식의 질을 낮추지 않는 선에서 정책을 운영해야 한다. 따라서 재정 상황을 고려하면서도 형평성을 지키는 방향으로 정책을 설계할 필요가 있다.",
  },
  {
    level: "B2",
    prompt_kr: "가상화폐 투자 열풍에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 매력과 위험을 모두 다루세요.",
    prompt_en: "What do you think about the cryptocurrency investment craze? Write six or more sentences covering both its appeal and risks, using '-을 뿐만 아니라' and '-는 데 그치다'.",
    example_kr: "가상화폐는 높은 수익을 기대할 수 있을 뿐만 아니라 소액으로도 쉽게 투자를 시작할 수 있어 젊은 층에게 인기가 많다. 하지만 시세 변동이 너무 심해서 단기 투기에 그치는 경우가 대부분이라는 점이 문제로 지적된다. 전통적인 금융 자산에 비해 규제가 느슨할 뿐만 아니라 정보의 비대칭성도 커서 투자자 보호가 미흡하다. 많은 투자자들이 충분한 이해 없이 단순한 유행을 따르는 데 그친 채 투자에 뛰어들고 있다는 점도 우려스럽다. 반면 블록체인 기술은 금융을 넘어 다양한 산업에 응용될 뿐만 아니라 미래 성장 가능성도 크다는 긍정적인 평가도 있다. 따라서 투자자 스스로 충분한 학습과 신중한 판단이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "정규직과 비정규직의 임금 격차 문제에 대해 어떻게 생각하십니까? '-는 만큼'과 '-더라도'를 사용해서 여섯 문장 이상으로 원인과 해결 방안을 모두 다루세요.",
    prompt_en: "What do you think about the wage gap between regular and non-regular workers? Write six or more sentences covering both causes and solutions, using '-는 만큼' and '-더라도'.",
    example_kr: "고용이 불안정한 만큼 비정규직 노동자들에게는 더 많은 보상이 주어져야 한다는 주장은 설득력이 있다. 같은 업무를 하더라도 고용 형태가 다르다는 이유로 임금과 복지에서 큰 차별을 받는 것은 부당하다. 기업이 비용 절감을 위해 비정규직을 늘리는 만큼 정규직 전환에는 소극적일 수밖에 없는 구조적인 문제도 있다. 경력이 쌓이더라도 비정규직이라는 이유로 승진 기회조차 얻지 못하는 경우가 많다는 점도 심각하다. 동일노동 동일임금 원칙이 자리 잡는 만큼 격차는 점차 줄어들 것이라는 기대도 있다. 결국 제도적 보완과 함께 기업의 인식 변화가 함께 이루어져야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들의 해외 이민 증가 현상에 대해 어떻게 생각하십니까? '-는 반면'과 '-을 경우'를 사용해서 여섯 문장 이상으로 이유와 사회적 영향을 모두 다루세요.",
    prompt_en: "What do you think about the increasing trend of young people emigrating abroad? Write six or more sentences covering both reasons and social effects, using '-는 반면' and '-을 경우'.",
    example_kr: "해외에서는 워라밸을 지키며 일할 수 있는 반면 국내에서는 과도한 경쟁과 야근 문화가 여전히 남아 있다는 인식이 이민을 부추긴다. 청년들이 계속 해외로 떠날 경우 국내 노동 시장은 인재 유출이라는 심각한 문제에 직면할 수 있다. 해외에서는 능력만으로 평가받을 수 있는 반면 국내에서는 학벌이나 인맥이 여전히 중요한 요소로 작용한다는 불만도 크다. 우수한 인재들이 계속 빠져나갈 경우 국가 경쟁력 자체가 약화될 위험도 있다. 새로운 나라에서는 자유로운 삶을 살 수 있는 반면 언어와 문화 장벽이라는 현실적인 어려움도 감수해야 한다. 따라서 국내에서도 공정하고 유연한 근무 환경을 만들려는 노력이 시급하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "대학 등록금 동결 정책에 대해 어떻게 생각하십니까? '-기 마련이다'와 '-는 이상'을 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about the policy of freezing university tuition? Write six or more sentences presenting both sides, using '-기 마련이다' and '-는 이상'.",
    example_kr: "물가가 오르는 이상 등록금만 계속 동결되면 대학의 재정 부담은 갈수록 커질 수밖에 없다. 예산이 부족해지면 교육의 질도 함께 떨어지기 마련이라는 우려가 대학가에서 제기되고 있다. 학생과 학부모 입장에서는 가계 부담이 큰 이상 등록금 동결은 반가운 정책일 수밖에 없다. 지원이 충분하지 않은 상태에서 동결만 강요하면 대학은 시설 투자를 줄이기 마련이다. 교육의 공공성이 중요한 이상 정부가 등록금 동결에 상응하는 재정 지원을 함께 제공해야 한다. 결국 학생 부담 완화와 대학 재정 건전성을 동시에 고려한 정책이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "군 복무 기간 단축에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 찬반 의견을 모두 다루세요.",
    prompt_en: "What do you think about shortening the mandatory military service period? Write six or more sentences covering both sides, using '-을 뿐만 아니라' and '-는 데 그치다'.",
    example_kr: "복무 기간이 짧아지면 청년들이 학업과 취업 준비에 더 빨리 복귀할 수 있을 뿐만 아니라 인생 설계에도 유리하다. 하지만 훈련이 단순히 기간을 채우는 데 그친다면 실제 전투력 유지에는 오히려 부정적인 영향을 줄 수 있다. 병력 감소는 안보 공백을 초래할 뿐만 아니라 부족한 병력을 채우기 위한 대안 마련도 쉽지 않다. 복무 기간 단축이 처우 개선 없이 단순한 단축에 그친다면 장병들의 사기 진작 효과는 크지 않을 것이다. 첨단 무기 체계 도입은 병력 감소를 보완할 뿐만 아니라 군의 효율성도 높일 수 있는 대안이 될 수 있다. 결국 복무 기간 단축은 전력 유지 방안과 함께 신중하게 추진되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "노인 일자리 사업 확대에 대해 어떻게 생각하십니까? '-도록 하다'와 '-는 셈이다'를 사용해서 여섯 문장 이상으로 필요성과 한계를 모두 다루세요.",
    prompt_en: "What do you think about expanding job programs for the elderly? Write six or more sentences covering both necessity and limitations, using '-도록 하다' and '-는 셈이다'.",
    example_kr: "정부가 노인들도 사회 활동에 참여하도록 일자리를 마련하는 것은 고령화 사회에서 꼭 필요한 정책이다. 노인 일자리 대부분이 단순 노무에 그친다면 사실상 용돈벌이 수준의 일자리를 제공하는 셈이다. 지자체가 노인들의 경력과 역량을 살리도록 일자리를 설계한다면 훨씬 더 큰 효과를 거둘 수 있다. 낮은 임금이라도 규칙적으로 일하게 되면 노인들에게 심리적 안정감을 주는 셈이니 그 가치를 무시할 수 없다. 기업이 고령 인력을 적극적으로 채용하도록 인센티브를 제공하는 정책도 함께 고려해야 한다. 결국 단순한 일자리 수 늘리기를 넘어 노인들의 전문성을 살리는 방향으로 나아가야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "가족 형태의 다양화(비혼, 동거, 반려동물 가족 등)를 법적으로 인정해야 한다는 주장에 대해 어떻게 생각하십니까? '-는 한'과 '-에 비해'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about the argument that diverse family forms (unmarried, cohabiting, pet families, etc.) should be legally recognized? Write six or more sentences covering both pro and con positions, using '-는 한' and '-에 비해'.",
    example_kr: "사회 구성원들이 다양한 삶의 방식을 선택하는 한 법과 제도도 이러한 변화를 반영해야 한다는 주장은 설득력이 있다. 전통적인 혼인 가족에 비해 동거 가족은 법적 보호를 거의 받지 못해 의료 결정이나 상속에서 불이익을 겪는다. 사회적 합의가 충분히 이루어지지 않는 한 법 개정은 신중하게 접근해야 한다는 의견도 있다. 이성 부부 중심의 제도에 비해 새로운 형태의 가족은 세제 혜택이나 주거 지원에서도 소외되는 경우가 많다. 개인의 선택을 존중하는 한 그에 따른 법적 권리도 동등하게 보장되어야 한다고 생각한다. 결국 시대 변화에 맞춰 가족의 정의를 넓히는 논의가 필요하다고 본다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 대상 저금리 정책 대출(청년도약계좌 등)에 대해 어떻게 생각하십니까? '-기는 하지만'과 '-을수록'을 사용해서 여섯 문장 이상으로 효과와 한계를 모두 다루세요.",
    prompt_en: "What do you think about low-interest policy loans and savings programs targeted at young people? Write six or more sentences covering both effects and limitations, using '-기는 하지만' and '-을수록'.",
    example_kr: "정부의 청년 지원 금융 상품은 자산 형성에 도움을 주기는 하지만 가입 조건이 까다로워 정작 필요한 청년들이 소외되는 경우도 있다. 소득이 낮을수록 매달 일정 금액을 저축하기가 현실적으로 어려운 경우가 많다. 이런 정책이 청년들에게 저축 습관을 길러 주기는 하지만 근본적인 소득 문제를 해결해 주지는 못한다. 지원 규모가 클수록 재정 부담도 함께 커지기 때문에 정책의 지속 가능성을 고려해야 한다. 제도가 홍보되기는 하지만 복잡한 신청 절차 때문에 실제 이용률은 기대에 미치지 못하는 경우도 있다. 결국 접근성을 높이고 절차를 간소화하는 방향으로 제도를 개선할 필요가 있다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "대형 유통업체의 골목 상권 진출 규제에 대해 어떻게 생각하십니까? '-는 반면'과 '-는 이상'을 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about regulating large retailers from entering local neighborhood markets? Write six or more sentences presenting both sides, using '-는 반면' and '-는 이상'.",
    example_kr: "대형 유통업체는 저렴한 가격과 다양한 상품을 제공하는 반면 골목 상권의 소규모 상점들은 경쟁에서 밀려날 수밖에 없다. 소비자 선택의 자유가 중요한 이상 무조건적인 규제는 소비자에게 불이익을 줄 수 있다는 반론도 있다. 규제가 있는 지역에서는 전통 시장이 어느 정도 유지되는 반면 규제가 약한 지역에서는 골목 상권이 빠르게 무너지는 경향이 있다. 지역 경제의 근간이 소상공인인 이상 이들을 보호하려는 정책적 노력은 필요하다고 본다. 대형 업체의 진출이 지역 고용을 늘리는 반면 기존 소상공인들의 생계는 위협받는 이중적인 결과를 낳는다. 결국 소비자 편익과 소상공인 보호 사이에서 균형점을 찾는 것이 중요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들의 아르바이트 노동권 보호 강화에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-을 경우'를 사용해서 여섯 문장 이상으로 필요성과 우려를 모두 다루세요.",
    prompt_en: "What do you think about strengthening labor rights protection for young part-time workers? Write six or more sentences covering both necessity and concerns, using '-을 뿐만 아니라' and '-을 경우'.",
    example_kr: "아르바이트생은 근무 경험이 적을 뿐만 아니라 근로 계약에 대한 이해도 부족해서 부당한 대우를 받기 쉽다. 최저임금이 지켜지지 않을 경우 신고할 수 있는 창구를 적극적으로 알릴 필요가 있다. 노동권 보호를 강화하면 청년들의 근무 환경이 개선될 뿐만 아니라 사회 초년생으로서 좋은 경험을 쌓을 수 있다. 다만 규제가 지나치게 강화될 경우 소규모 자영업자들이 아예 채용을 꺼리게 될 위험도 있다. 부당 해고를 막는 제도는 노동자를 보호할 뿐만 아니라 건강한 노동 시장 문화를 만드는 데도 기여한다. 따라서 노동자 보호와 자영업자의 부담을 함께 고려한 세심한 제도 설계가 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "택배 노동자 처우 개선을 위한 사회적 합의에 대해 어떻게 생각하십니까? '-는 셈이다'와 '-더라도'를 사용해서 여섯 문장 이상으로 문제점과 해결 방안을 모두 다루세요.",
    prompt_en: "What do you think about the social agreement to improve conditions for delivery workers? Write six or more sentences covering both problems and solutions, using '-는 셈이다' and '-더라도'.",
    example_kr: "택배 노동자들이 하루에 수백 개의 물건을 나른다면 몸을 갈아 넣어 일하는 셈이라고 해도 과언이 아니다. 배송비가 저렴하더라도 그 비용 절감이 결국 노동자의 희생으로 메워지고 있다면 결코 바람직하지 않다. 소비자는 빠른 배송을 편리하게 누리는 반면 노동자는 그만큼 과로에 시달리는 셈이 된다. 배송 시스템이 개선되더라도 물량 자체가 줄지 않는다면 근본적인 문제 해결은 어렵다. 분류 작업 인력을 별도로 배치하는 것은 결국 노동 강도를 낮추는 실질적인 대안이 되는 셈이다. 따라서 소비자, 기업, 정부가 함께 책임을 나누는 사회적 합의가 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "출산 장려를 위해 다자녀 가구에 대한 세제 혜택을 확대해야 한다는 주장에 대해 어떻게 생각하십니까? '-는 만큼'과 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about expanding tax benefits for multi-child households to encourage childbirth? Write six or more sentences presenting both sides, using '-는 만큼' and '-는 데 그치다'.",
    example_kr: "자녀를 키우는 데 드는 비용 부담이 큰 만큼 세제 혜택 확대는 실질적인 도움이 될 수 있다. 하지만 혜택이 세금 감면에 그친다면 소득이 낮아 세금을 거의 내지 않는 가구는 아무 혜택도 받지 못한다. 자녀 수가 많을수록 생활비 부담도 커지는 만큼 형평성 있는 지원 방식을 고민할 필요가 있다. 정책이 단순한 세제 혜택에 그치지 않고 보육 시설 확충과 함께 이루어져야 실질적인 효과를 낼 수 있다. 출산율이 낮아지는 만큼 정부의 적극적인 지원은 시급한 과제라고 할 수 있다. 결국 세제 혜택과 함께 다양한 형태의 지원을 병행하는 것이 바람직하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "특성화고, 마이스터고 등 직업계고 확대 정책에 대해 어떻게 생각하십니까? '-는 이상'과 '-기 마련이다'를 사용해서 여섯 문장 이상으로 필요성과 한계를 모두 다루세요.",
    prompt_en: "What do you think about the policy of expanding vocational high schools like specialized and Meister schools? Write six or more sentences covering both necessity and limitations, using '-는 이상' and '-기 마련이다'.",
    example_kr: "산업 현장에서 실무 인재가 부족한 이상 직업계고 확대는 인력 수급 문제를 해결하는 좋은 대안이 될 수 있다. 새로운 진로가 열리면 학생들의 선택의 폭도 넓어지기 마련이라는 점에서 긍정적으로 평가할 만하다. 사회적으로 대학 진학을 중시하는 분위기가 남아 있는 이상 직업계고에 대한 편견을 없애기가 쉽지 않다. 특정 산업에 특화된 교육을 받다 보면 그 산업이 침체될 경우 취업에 어려움을 겪기 마련이다. 기업과의 연계가 활발한 이상 학생들은 졸업 후 곧바로 현장에 투입될 수 있다는 장점이 있다. 결국 다양한 산업 수요를 반영한 교육 과정 운영이 성공의 핵심이라고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 부채 탕감 정책에 대해 어떻게 생각하십니까? '-을수록'과 '-을 뿐만 아니라'를 사용해서 여섯 문장 이상으로 찬반 의견을 모두 제시하세요.",
    prompt_en: "What do you think about debt forgiveness policies for young people? Write six or more sentences presenting both sides, using '-을수록' and '-을 뿐만 아니라'.",
    example_kr: "학자금 대출 부담이 클수록 사회 초년생들이 경제 활동을 시작하기가 더욱 어려워진다는 점에서 부채 탕감의 필요성은 이해할 만하다. 부채가 줄어들면 소비 여력이 생길 뿐만 아니라 결혼이나 주택 마련 같은 인생 계획도 세우기 쉬워진다. 하지만 성실하게 빚을 갚아 온 사람들이 상대적으로 손해를 본다고 느낄수록 사회적 형평성 논란이 커질 수 있다. 탕감 대상이 넓어질 뿐만 아니라 조건이 느슨해질 경우 도덕적 해이를 부추길 위험도 있다. 부채 문제가 심각할수록 근본적인 원인인 등록금과 생활비 문제를 함께 다뤄야 한다. 결국 일회성 탕감보다는 지속 가능한 제도적 지원이 더 바람직하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "농촌 지역의 외국인 노동자 의존도 증가에 대해 어떻게 생각하십니까? '-는 반면'과 '-을 경우'를 사용해서 여섯 문장 이상으로 필요성과 문제점을 모두 다루세요.",
    prompt_en: "What do you think about the increasing dependence on foreign workers in rural areas? Write six or more sentences covering both necessity and problems, using '-는 반면' and '-을 경우'.",
    example_kr: "농촌은 일손 부족 문제가 심각한 반면 내국인 노동자를 구하기는 갈수록 어려워지고 있다. 외국인 노동자가 없을 경우 농사철에 필요한 인력을 제때 확보하지 못해 큰 손실을 볼 수 있다. 외국인 노동자들은 저임금 노동을 감당하는 반면 주거 환경이나 처우는 열악한 경우가 많다는 문제도 있다. 언어와 문화 차이로 소통에 어려움을 겪을 경우 작업 효율과 안전에도 영향을 미칠 수 있다. 이들이 지역 경제를 지탱하는 반면 제도적으로는 여전히 사각지대에 놓여 있는 경우가 많다. 따라서 외국인 노동자에 대한 처우 개선과 제도적 보호가 함께 이루어져야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "쇼핑몰, 백화점의 심야 영업시간 확대에 대해 어떻게 생각하십니까? '-도록 하다'와 '-는 셈이다'를 사용해서 여섯 문장 이상으로 찬반 의견을 모두 다루세요.",
    prompt_en: "What do you think about extending the late-night operating hours of shopping malls and department stores? Write six or more sentences covering both sides, using '-도록 하다' and '-는 셈이다'.",
    example_kr: "매장이 심야까지 영업하도록 시간을 늘리면 다양한 생활 패턴을 가진 소비자들의 편의를 높일 수 있다. 야간 근무가 늘어난다는 것은 결국 노동자들의 휴식 시간이 그만큼 줄어드는 셈이다. 기업은 매출 증대를 기대할 수 있지만 전기와 인건비 등 운영 비용도 함께 늘어나는 셈이 된다. 정부가 심야 노동자의 근무 환경을 보호하도록 최소한의 기준을 마련할 필요가 있다. 소비자 입장에서는 선택의 폭이 넓어지는 셈이니 심야 영업 확대를 반길 수 있다. 결국 소비자 편의와 노동자 권익을 동시에 고려한 신중한 접근이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "지역 균형 발전을 위해 공공기관을 지방으로 이전하는 정책에 대해 어떻게 생각하십니까? '-기는 하지만'과 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 효과와 한계를 모두 다루세요.",
    prompt_en: "What do you think about the policy of relocating public institutions to regional areas for balanced national development? Write six or more sentences covering both effects and limitations, using '-기는 하지만' and '-는 데 그치다'.",
    example_kr: "공공기관 지방 이전은 지역에 새로운 일자리를 만들어 주기는 하지만 정작 직원들이 가족과 떨어져 생활하는 불편을 감수해야 한다. 일부 지역에서는 기관 이전이 단순히 건물만 옮기는 데 그치고 실질적인 지역 경제 효과로는 이어지지 못했다는 평가도 있다. 지방 이전이 인구 유입 효과를 가져오기는 하지만 정주 여건이 개선되지 않으면 직원들은 가족 없이 홀로 생활하는 경우가 많다. 정책이 이전 목표 달성에 그치지 않고 지역 정착을 위한 주거와 교육 여건 개선까지 이어져야 한다. 이전 기관 주변에 관련 산업이 모여들기는 하지만 그 효과가 나타나기까지는 오랜 시간이 걸린다. 따라서 장기적인 안목을 가지고 정책을 지속적으로 보완해 나가야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들의 결혼 비용 부담을 줄이기 위한 스몰웨딩 확산에 대해 어떻게 생각하십니까? '-는 만큼'과 '-더라도'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about the spread of small weddings to reduce marriage cost burdens for young people? Write six or more sentences covering both advantages and disadvantages, using '-는 만큼' and '-더라도'.",
    example_kr: "결혼 비용 부담이 큰 만큼 스몰웨딩을 선택하는 청년들이 늘어나는 것은 합리적인 선택이라고 볼 수 있다. 하객 수가 적더라도 정말 소중한 사람들과 뜻깊은 시간을 보낼 수 있다면 그것으로 충분하다고 느끼는 사람도 많다. 전통적인 결혼식 문화가 강한 만큼 스몰웨딩을 선택하면 주변의 시선을 신경 써야 하는 경우도 있다. 규모가 작더라도 오히려 신랑 신부가 직접 준비하며 더 특별한 의미를 담을 수 있다는 장점도 있다. 축의금 문화가 남아 있는 만큼 하객이 줄어들면 경제적으로 손해를 본다고 느끼는 사람도 있다. 결국 형식보다 부부의 가치관에 맞는 결혼 방식을 선택하는 것이 중요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "온라인 중고 거래 플랫폼의 확산에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-을 경우'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about the spread of online secondhand trading platforms? Write six or more sentences covering both advantages and disadvantages, using '-을 뿐만 아니라' and '-을 경우'.",
    example_kr: "중고 거래 플랫폼은 자원을 재활용할 수 있을 뿐만 아니라 저렴한 가격으로 필요한 물건을 구할 수 있다는 장점이 있다. 직거래를 할 경우 사기나 안전사고의 위험이 있어 각별한 주의가 필요하다. 판매자와 구매자가 직접 소통할 뿐만 아니라 가격도 협상할 수 있어 합리적인 소비가 가능하다. 물건에 하자가 있을 경우 반품이나 환불이 쉽지 않다는 점은 큰 단점으로 꼽힌다. 중고 거래는 과소비를 줄일 뿐만 아니라 환경 보호에도 기여한다는 긍정적인 측면이 있다. 결국 안전한 거래 문화를 정착시키기 위한 플랫폼의 관리 책임이 더욱 중요해지고 있다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "정부가 반려동물 등록을 의무화하는 정책에 대해 어떻게 생각하십니까? '-는 이상'과 '-기 마련이다'를 사용해서 여섯 문장 이상으로 필요성과 한계를 모두 다루세요.",
    prompt_en: "What do you think about the government's policy of mandating pet registration? Write six or more sentences covering both necessity and limitations, using '-는 이상' and '-기 마련이다'.",
    example_kr: "유기 동물 문제가 심각한 이상 반려동물 등록 의무화는 반드시 필요한 제도라고 생각한다. 등록 절차가 번거로우면 사람들이 미루기 마련이라 제도를 간편하게 만드는 것이 중요하다. 반려동물을 키우는 인구가 늘어나는 이상 관리 체계도 그에 맞게 발전해야 한다. 처벌이 약하면 등록을 하지 않는 사람들이 생기기 마련이므로 실효성 있는 단속이 뒤따라야 한다. 생명을 책임지는 이상 소유자로서 최소한의 의무를 다하는 것은 당연하다고 본다. 결국 제도의 실효성을 높이기 위해서는 홍보와 단속이 함께 강화되어야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 취업난 속에서 스펙 쌓기 경쟁이 심화되는 현상에 대해 어떻게 생각하십니까? '-는 데 그치다'와 '-을수록'을 사용해서 여섯 문장 이상으로 원인과 문제점을 모두 다루세요.",
    prompt_en: "What do you think about the intensifying competition for résumé credentials amid youth unemployment? Write six or more sentences covering both causes and problems, using '-는 데 그치다' and '-을수록'.",
    example_kr: "취업 경쟁이 치열할수록 청년들은 자격증과 어학 점수 같은 스펙 쌓기에 더 많은 시간과 비용을 투자하게 된다. 스펙이 단순히 서류상의 숫자에 그친다면 실제 업무 능력과는 무관한 경우도 많다는 지적이 있다. 기업이 스펙만으로 지원자를 평가할수록 정작 필요한 실무 역량을 갖춘 인재를 놓칠 위험도 커진다. 자기소개서 작성이 형식적인 틀에 맞추는 데 그친다면 지원자의 진짜 강점을 보여 주기 어렵다. 경쟁이 심화될수록 청년들의 정신적 스트레스와 경제적 부담도 함께 늘어난다. 따라서 기업의 채용 기준을 실질적인 역량 중심으로 개선하는 노력이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "택시 대신 자율주행 차량 도입을 확대해야 한다는 주장에 대해 어떻게 생각하십니까? '-도록 하다'와 '-더라도'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about the argument for expanding autonomous vehicles instead of taxis? Write six or more sentences covering both pro and con positions, using '-도록 하다' and '-더라도'.",
    example_kr: "정부가 자율주행 기술을 안전하게 도입하도록 철저한 검증 절차를 마련하는 것이 무엇보다 중요하다. 기술이 아무리 발전하더라도 예기치 못한 돌발 상황에서는 여전히 사고 위험이 존재한다. 자율주행 차량이 상용화되도록 관련 법과 제도를 정비한다면 교통 체계 전반에 큰 변화를 가져올 수 있다. 요금이 저렴해지더라도 기존 택시 기사들의 일자리가 줄어드는 문제는 사회적으로 해결해야 할 과제다. 도입 초기에는 시범 지역을 지정하도록 하여 안전성을 충분히 검증한 뒤 확대하는 것이 바람직하다. 결국 기술 발전과 사회적 안전망을 함께 고려한 신중한 접근이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "대학 입시에서 지역 균형 선발 제도(지역 인재 전형)에 대해 어떻게 생각하십니까? '-는 셈이다'와 '-을 뿐만 아니라'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about regional balanced admission quotas (local talent programs) in university entrance? Write six or more sentences covering both pro and con positions, using '-는 셈이다' and '-을 뿐만 아니라'.",
    example_kr: "지역 인재 전형은 교육 환경이 열악한 지방 학생들에게 실질적인 기회를 넓혀 주는 셈이다. 이 제도는 지방 학생들의 대학 진학 기회를 늘려 줄 뿐만 아니라 지역 인재 유출을 막는 데도 도움이 된다. 반면 수도권 학생들은 같은 성적을 받고도 상대적으로 불리한 위치에 놓이는 셈이어서 형평성 논란이 있다. 지역 균형을 위한 제도가 오히려 다른 학생들에게 역차별이 될 뿐만 아니라 사회적 갈등을 낳을 수도 있다. 그럼에도 지역 간 교육 격차가 여전한 셈이니 최소한의 균형 장치는 필요하다는 의견이 우세하다. 결국 공정성과 형평성 사이에서 지속적인 사회적 논의가 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들 사이에서 프리랜서, 부업(N잡) 문화가 확산되는 것에 대해 어떻게 생각하십니까? '-는 반면'과 '-을 경우'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about the spread of freelancing and side-job (N-job) culture among young people? Write six or more sentences covering both advantages and disadvantages, using '-는 반면' and '-을 경우'.",
    example_kr: "부업을 통해 추가 수입을 얻을 수 있는 반면 본업에 소홀해질 위험도 함께 커진다. 여러 일을 동시에 진행할 경우 시간 관리에 실패하면 오히려 어느 것도 제대로 해내지 못할 수 있다. 다양한 경험을 쌓을 수 있는 반면 안정적인 하나의 경력을 쌓기는 상대적으로 어려워진다. 부업 소득이 예상보다 많아질 경우 세금 신고나 4대 보험 문제로 곤란을 겪는 사람도 있다. 자아실현의 기회가 되는 반면 지나친 부업은 결국 건강을 해치는 원인이 될 수도 있다. 따라서 자신의 역량과 시간을 충분히 고려한 균형 잡힌 선택이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "임대차 3법(전월세 상한제 등)에 대해 어떻게 생각하십니까? '-기는 하지만'과 '-는 이상'을 사용해서 여섯 문장 이상으로 효과와 부작용을 모두 다루세요.",
    prompt_en: "What do you think about the rental housing laws (rent increase caps, etc.)? Write six or more sentences covering both effects and side effects, using '-기는 하지만' and '-는 이상'.",
    example_kr: "임대차 3법은 세입자의 주거 안정을 보호하려는 취지를 가지고 있기는 하지만 시행 과정에서 여러 부작용도 나타났다. 임대료 인상을 제한하는 이상 집주인들은 전세를 월세로 전환하려는 경향을 보이게 된다. 세입자를 보호하려는 목적은 긍정적이기는 하지만 결과적으로 전세 매물이 줄어드는 역설적인 상황이 발생했다. 법적으로 계약 갱신을 보장하는 이상 집주인이 임대를 아예 꺼리는 부작용도 생길 수 있다. 제도가 세입자를 위한 것이기는 하지만 신규 세입자와 기존 세입자 사이의 형평성 문제도 제기되고 있다. 결국 시장 상황을 면밀히 살피며 제도를 지속적으로 보완해야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청소년의 아르바이트 노동시간 제한에 대해 어떻게 생각하십니까? '-을 뿐만 아니라'와 '-도록 하다'를 사용해서 여섯 문장 이상으로 필요성과 우려를 모두 다루세요.",
    prompt_en: "What do you think about limiting working hours for teenage part-time workers? Write six or more sentences covering both necessity and concerns, using '-을 뿐만 아니라' and '-도록 하다'.",
    example_kr: "청소년기는 학업과 성장에 중요한 시기일 뿐만 아니라 신체적으로도 무리한 노동을 감당하기 어려운 시기다. 정부가 청소년의 근무 시간을 엄격히 제한하도록 법을 마련한 것은 타당한 조치라고 생각한다. 노동시간 제한은 학업에 집중할 시간을 보장할 뿐만 아니라 안전사고 위험도 줄여 준다. 사업주가 이러한 규정을 철저히 지키도록 관리 감독을 강화해야 실효성을 높일 수 있다. 일부 저소득 가정의 청소년에게는 노동시간 제한이 오히려 경제적 어려움을 가중시킬 뿐만 아니라 필요한 소득 기회도 줄일 수 있다. 따라서 취약 계층 청소년을 위한 별도의 지원 방안도 함께 고려해야 한다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "온라인 플랫폼 기업에 대한 독과점 규제 강화에 대해 어떻게 생각하십니까? '-는 만큼'과 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about strengthening antitrust regulations on online platform companies? Write six or more sentences covering both pro and con positions, using '-는 만큼' and '-는 데 그치다'.",
    example_kr: "몇몇 플랫폼 기업의 시장 지배력이 커지는 만큼 이를 견제할 규제가 필요하다는 목소리가 커지고 있다. 그러나 규제가 단순히 기업 규모를 제한하는 데 그친다면 오히려 혁신을 저해할 수 있다는 우려도 있다. 소비자 편익을 해치는 만큼 불공정 거래 행위에 대해서는 엄격한 조치가 필요하다고 본다. 규제가 국내 기업 견제에 그치고 해외 기업에는 느슨하게 적용된다면 역차별 문제가 생길 수 있다. 시장 독점이 심화되는 만큼 중소 입점업체들의 협상력도 함께 보호해야 한다. 결국 혁신을 저해하지 않으면서도 공정한 경쟁 환경을 만드는 균형 잡힌 규제가 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "노후 소득 보장을 위한 국민연금 개혁에 대해 어떻게 생각하십니까? '-는 이상'과 '-더라도'를 사용해서 여섯 문장 이상으로 필요성과 부담을 모두 다루세요.",
    prompt_en: "What do you think about pension reform to guarantee retirement income? Write six or more sentences covering both necessity and burden, using '-는 이상' and '-더라도'.",
    example_kr: "고령화가 급속히 진행되는 이상 현재의 국민연금 제도로는 지속 가능성을 보장하기 어렵다는 지적이 많다. 보험료를 조금 올리더라도 미래 세대의 부담을 줄일 수 있다면 지금 개혁하는 것이 바람직하다고 본다. 연금 재정이 고갈 위기에 놓인 이상 개혁을 더 이상 미룰 수 없는 상황이다. 지급 시기를 늦추더라도 국민들이 충분히 이해하고 받아들일 수 있도록 사회적 합의 과정이 필요하다. 세대 간 형평성이 중요한 이상 젊은 세대의 부담만 늘리는 방식은 지양해야 한다. 결국 보험료, 지급액, 수급 연령을 종합적으로 조정하는 신중한 개혁이 필요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년 대상 주택 특별공급 제도에 대해 어떻게 생각하십니까? '-을 경우'와 '-기 마련이다'를 사용해서 여섯 문장 이상으로 찬반 입장을 모두 다루세요.",
    prompt_en: "What do you think about special housing supply programs for young people? Write six or more sentences covering both pro and con positions, using '-을 경우' and '-기 마련이다'.",
    example_kr: "청년들이 내 집 마련의 기회를 얻을 경우 결혼과 출산 등 다른 인생 계획도 세우기 쉬워진다는 점에서 긍정적이다. 특정 계층에게 혜택이 집중되면 다른 계층은 상대적 박탈감을 느끼기 마련이라는 지적도 있다. 청약 경쟁이 치열한 상황에서 특별공급 물량이 늘어날 경우 일반 공급 물량은 그만큼 줄어드는 문제가 생긴다. 새로운 제도가 도입되면 이를 악용하려는 부정 청약 시도도 함께 늘어나기 마련이다. 청년들이 안정적으로 정착할 경우 지역 사회에도 활력을 불어넣는 긍정적인 효과가 있다. 결국 제도의 실효성을 높이려면 부정 청약을 막는 철저한 검증 장치가 함께 마련되어야 한다.",
  },
  {
    level: "B2",
    prompt_kr: "재택근무와 사무실 출근을 병행하는 하이브리드 근무제에 대해 어떻게 생각하십니까? '-는 반면'과 '-을 뿐만 아니라'를 사용해서 여섯 문장 이상으로 장단점을 모두 다루세요.",
    prompt_en: "What do you think about hybrid work systems combining remote work and office attendance? Write six or more sentences covering both advantages and disadvantages, using '-는 반면' and '-을 뿐만 아니라'.",
    example_kr: "하이브리드 근무는 재택근무의 자유로움을 누릴 수 있는 반면 출근일 조율 때문에 팀원 간 일정을 맞추기 어려운 경우도 있다. 이 제도는 통근 시간을 줄여 줄 뿐만 아니라 직원들의 업무 만족도를 높이는 효과도 있다. 사무실 출근일에는 대면 협업이 활발한 반면 재택일에는 소통이 지연되어 업무 효율이 떨어질 수 있다. 회사는 사무 공간 운영 비용을 절감할 뿐만 아니라 직원들의 이직률도 낮출 수 있다는 장점이 있다. 유연한 근무가 가능한 반면 명확한 규칙이 없으면 오히려 혼란을 초래할 수 있다. 결국 명확한 가이드라인을 마련하면 하이브리드 근무의 장점을 최대한 살릴 수 있다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "층간소음 문제 해결을 위한 아파트 규제 강화에 대해 어떻게 생각하십니까? '-을수록'과 '-는 데 그치다'를 사용해서 여섯 문장 이상으로 필요성과 한계를 모두 다루세요.",
    prompt_en: "What do you think about strengthening apartment regulations to solve the floor-noise problem? Write six or more sentences covering both necessity and limitations, using '-을수록' and '-는 데 그치다'.",
    example_kr: "공동 주택에 거주하는 인구가 많아질수록 층간소음으로 인한 이웃 간 갈등도 그만큼 늘어나고 있다. 건설사에 대한 규제가 단순히 권고에 그친다면 실제 시공 현장에서는 지켜지지 않을 가능성이 크다. 소음 기준이 엄격해질수록 건설 비용이 늘어나 분양가 상승으로 이어질 수 있다는 우려도 있다. 문제를 신고하는 절차가 복잡한 데 그친다면 주민들은 스스로 갈등을 해결하려다 더 큰 다툼을 겪을 수 있다. 바닥 두께에 대한 기준이 강화될수록 신축 아파트의 소음 문제는 점차 줄어들 것으로 기대된다. 결국 법적 기준 강화와 함께 실질적인 감독 체계를 갖추는 것이 중요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들이 결혼 대신 반려동물을 키우며 살아가는 삶의 방식에 대해 어떻게 생각하십니까? '-는 셈이다'와 '-기는 하지만'을 사용해서 여섯 문장 이상으로 이유와 우려를 모두 다루세요.",
    prompt_en: "What do you think about young people choosing to raise pets instead of getting married? Write six or more sentences covering both reasons and concerns, using '-는 셈이다' and '-기는 하지만'.",
    example_kr: "결혼과 육아에 드는 부담을 고려하면 반려동물을 키우는 것은 상대적으로 부담이 적은 선택인 셈이다. 반려동물은 정서적인 위안을 주기는 하지만 사람과의 관계에서 얻는 만족감을 완전히 대체하기는 어렵다. 결혼을 미루는 대신 반려동물과 함께하는 삶을 선택하는 것은 개인의 행복을 우선시하는 셈이라고 볼 수 있다. 반려동물을 키우는 데도 상당한 시간과 비용이 들기는 하지만 자녀 양육에 비하면 부담이 훨씬 적다. 결혼에 대한 압박에서 벗어난다는 점에서 심리적으로 자유로워지는 셈이지만 노후에 외로움을 느낄 수 있다는 우려도 있다. 결국 어떤 삶을 선택하든 개인의 가치관을 존중하는 사회 분위기가 중요하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "지방 소도시의 빈집 문제 해결을 위한 정부 지원에 대해 어떻게 생각하십니까? '-도록 하다'와 '-는 만큼'을 사용해서 여섯 문장 이상으로 필요성과 한계를 모두 다루세요.",
    prompt_en: "What do you think about government support to solve the vacant house problem in small regional towns? Write six or more sentences covering both necessity and limitations, using '-도록 하다' and '-는 만큼'.",
    example_kr: "빈집이 늘어나는 만큼 지역 사회의 안전과 미관 문제도 함께 심각해지고 있다. 정부가 빈집을 리모델링하도록 지원하면 청년들이나 귀촌 희망자들에게 저렴한 주거 대안이 될 수 있다. 빈집 문제가 인구 감소와 직결되는 만큼 근본적으로는 지역에 사람이 머물 수 있는 환경을 만드는 것이 우선이다. 지자체가 빈집 정보를 체계적으로 관리하도록 데이터베이스를 구축한다면 활용도를 크게 높일 수 있다. 방치된 빈집이 늘어나는 만큼 범죄에 악용될 위험도 무시할 수 없다. 결국 빈집을 단순히 철거하기보다 새로운 용도로 활용하도록 정책을 설계하는 것이 바람직하다고 생각한다.",
  },
  {
    level: "B2",
    prompt_kr: "청년들이 대기업 취업보다 공공기관이나 대기업의 안정성만 좇는 경향에 대해 어떻게 생각하십니까? '-는 이상'과 '-을 뿐만 아니라'를 사용해서 여섯 문장 이상으로 원인과 사회적 영향을 모두 다루세요.",
    prompt_en: "What do you think about young people's tendency to chase only stability through public institutions or large companies? Write six or more sentences covering both causes and social effects, using '-는 이상' and '-을 뿐만 아니라'.",
    example_kr: "고용 불안이 사회 전반에 퍼져 있는 이상 청년들이 안정적인 직장을 선호하는 것은 자연스러운 현상이다. 대기업과 공공기관은 급여와 복지가 좋을 뿐만 아니라 사회적 인정을 받기도 쉬워 청년들에게 매력적이다. 중소기업의 근무 환경이 열악한 이상 청년들이 그곳으로 눈을 돌리기는 쉽지 않은 것이 현실이다. 이러한 쏠림 현상은 특정 기업의 경쟁만 심화시킬 뿐만 아니라 다른 산업 분야의 인재 부족 문제도 낳는다. 사회 안전망이 부족한 이상 청년들은 위험을 감수하기보다 안정을 택할 수밖에 없다. 따라서 중소기업의 처우 개선과 사회 안전망 확충이 함께 이루어져야 한다고 생각한다.",
  },
];
