import type { RawPrompt } from "./types";

export const WRITING_B2_DESCRIPTION: RawPrompt[] = [
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    example_kr: "우리 아빠는 따뜻하고 멋있어요, 그래서 항상 인기가 많아요.",
    example_en: "My dad is warm and cool, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    example_kr: "우리 학교는 시끄럽고 커요, 그래서 항상 인기가 많아요.",
    example_en: "My school is loud and big, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    example_kr: "우리 엄마는 유명하고 시끄러워요, 그래서 항상 인기가 많아요.",
    example_en: "My mom is famous and loud, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    example_kr: "이 카페는 귀엽고 깨끗해요, 그래서 항상 인기가 많아요.",
    example_en: "This cafe is cute and clean, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    example_kr: "제 가방은 예쁘고 깨끗해요, 그래서 항상 인기가 많아요.",
    example_en: "My bag is pretty and clean, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    example_kr: "이 노래는 편하고 복잡해요, 그래서 항상 인기가 많아요.",
    example_en: "This song is comfortable and crowded, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    example_kr: "이 케이크는 시끄럽고 예뻐요, 그래서 항상 인기가 많아요.",
    example_en: "This cake is loud and pretty, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    example_kr: "제 방은 작고 맛있어요, 그래서 항상 인기가 많아요.",
    example_en: "My room is small and delicious, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    example_kr: "서울은 크고 복잡해요, 그래서 항상 인기가 많아요.",
    example_en: "Seoul is big and crowded, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    example_kr: "우리 동네는 따뜻하고 유명해요, 그래서 항상 인기가 많아요.",
    example_en: "My neighborhood is warm and famous, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    example_kr: "이 영화는 시끄럽고 편해요, 그래서 항상 인기가 많아요.",
    example_en: "This movie is loud and comfortable, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 집 고양이를 자세히 묘사해 보세요.",
    prompt_en: "Describe our cat in some detail.",
    example_kr: "우리 집 고양이는 멋있고 편해요, 그래서 항상 인기가 많아요.",
    example_en: "Our cat is cool and comfortable, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    example_kr: "우리 선생님은 귀엽고 멋있어요, 그래서 항상 인기가 많아요.",
    example_en: "Our teacher is cute and cool, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    example_kr: "제 친구는 작고 유명해요, 그래서 항상 인기가 많아요.",
    example_en: "My friend is small and famous, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 집 강아지를 자세히 묘사해 보세요.",
    prompt_en: "Describe our dog in some detail.",
    example_kr: "우리 집 강아지는 작고 멋있어요, 그래서 항상 인기가 많아요.",
    example_en: "Our dog is small and cool, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    example_kr: "우리 아빠는 크고 유명해요, 그래서 항상 인기가 많아요.",
    example_en: "My dad is big and famous, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    example_kr: "우리 학교는 편하고 예뻐요, 그래서 항상 인기가 많아요.",
    example_en: "My school is comfortable and pretty, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    example_kr: "우리 엄마는 친절하고 멋있어요, 그래서 항상 인기가 많아요.",
    example_en: "My mom is kind and cool, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    example_kr: "이 카페는 편하고 친절해요, 그래서 항상 인기가 많아요.",
    example_en: "This cafe is comfortable and kind, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    example_kr: "제 가방은 유명하고 친절해요, 그래서 항상 인기가 많아요.",
    example_en: "My bag is famous and kind, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    example_kr: "이 노래는 복잡하고 멋있어요, 그래서 항상 인기가 많아요.",
    example_en: "This song is crowded and cool, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    example_kr: "이 케이크는 복잡하고 시끄러워요, 그래서 항상 인기가 많아요.",
    example_en: "This cake is crowded and loud, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    example_kr: "제 방은 시끄럽고 귀여워요, 그래서 항상 인기가 많아요.",
    example_en: "My room is loud and cute, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    example_kr: "서울은 편하고 깨끗해요, 그래서 항상 인기가 많아요.",
    example_en: "Seoul is comfortable and clean, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 동네를 자세히 묘사해 보세요.",
    prompt_en: "Describe my neighborhood in some detail.",
    example_kr: "우리 동네는 복잡하고 깨끗해요, 그래서 항상 인기가 많아요.",
    example_en: "My neighborhood is crowded and clean, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 영화를 자세히 묘사해 보세요.",
    prompt_en: "Describe this movie in some detail.",
    example_kr: "이 영화는 크고 따뜻해요, 그래서 항상 인기가 많아요.",
    example_en: "This movie is big and warm, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 집 고양이를 자세히 묘사해 보세요.",
    prompt_en: "Describe our cat in some detail.",
    example_kr: "우리 집 고양이는 아름답고 시끄러워요, 그래서 항상 인기가 많아요.",
    example_en: "Our cat is beautiful and loud, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 선생님을 자세히 묘사해 보세요.",
    prompt_en: "Describe our teacher in some detail.",
    example_kr: "우리 선생님은 작고 깨끗해요, 그래서 항상 인기가 많아요.",
    example_en: "Our teacher is small and clean, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 친구를 자세히 묘사해 보세요.",
    prompt_en: "Describe my friend in some detail.",
    example_kr: "제 친구는 멋있고 유명해요, 그래서 항상 인기가 많아요.",
    example_en: "My friend is cool and famous, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 집 강아지를 자세히 묘사해 보세요.",
    prompt_en: "Describe our dog in some detail.",
    example_kr: "우리 집 강아지는 시끄럽고 작아요, 그래서 항상 인기가 많아요.",
    example_en: "Our dog is loud and small, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 아빠를 자세히 묘사해 보세요.",
    prompt_en: "Describe my dad in some detail.",
    example_kr: "우리 아빠는 유명하고 예뻐요, 그래서 항상 인기가 많아요.",
    example_en: "My dad is famous and pretty, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 학교를 자세히 묘사해 보세요.",
    prompt_en: "Describe my school in some detail.",
    example_kr: "우리 학교는 예쁘고 조용해요, 그래서 항상 인기가 많아요.",
    example_en: "My school is pretty and quiet, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "우리 엄마를 자세히 묘사해 보세요.",
    prompt_en: "Describe my mom in some detail.",
    example_kr: "우리 엄마는 귀엽고 작아요, 그래서 항상 인기가 많아요.",
    example_en: "My mom is cute and small, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 카페를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cafe in some detail.",
    example_kr: "이 카페는 편하고 조용해요, 그래서 항상 인기가 많아요.",
    example_en: "This cafe is comfortable and quiet, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 가방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my bag in some detail.",
    example_kr: "제 가방은 예쁘고 맛있어요, 그래서 항상 인기가 많아요.",
    example_en: "My bag is pretty and delicious, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 노래를 자세히 묘사해 보세요.",
    prompt_en: "Describe this song in some detail.",
    example_kr: "이 노래는 귀엽고 맛있어요, 그래서 항상 인기가 많아요.",
    example_en: "This song is cute and delicious, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "이 케이크를 자세히 묘사해 보세요.",
    prompt_en: "Describe this cake in some detail.",
    example_kr: "이 케이크는 크고 작아요, 그래서 항상 인기가 많아요.",
    example_en: "This cake is big and small, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "제 방을 자세히 묘사해 보세요.",
    prompt_en: "Describe my room in some detail.",
    example_kr: "제 방은 조용하고 멋있어요, 그래서 항상 인기가 많아요.",
    example_en: "My room is quiet and cool, so it's always popular.",
  },
  {
    level: "B2",
    genre: "description",
    prompt_kr: "서울을 자세히 묘사해 보세요.",
    prompt_en: "Describe Seoul in some detail.",
    example_kr: "서울은 아름답고 조용해요, 그래서 항상 인기가 많아요.",
    example_en: "Seoul is beautiful and quiet, so it's always popular.",
  },
];
