import type { RawPrompt } from "./types";

export const WRITING_B2_OPINION: RawPrompt[] = [
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "단체 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on group trips.",
    prompt_ja: "団体旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 단체 여행을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like group trips, and the reason is that it makes me feel at ease.",
    example_ja: "私は団体旅行が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "등산에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hiking.",
    prompt_ja: "登山についての考えを詳しく書いてみましょう。",
    example_kr: "저는 등산을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like hiking, and the reason is that it makes me feel at ease.",
    example_ja: "私は登山が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "아침 운동에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on morning exercise.",
    prompt_ja: "朝の運動についての考えを詳しく書いてみましょう。",
    example_kr: "저는 아침 운동을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like morning exercise, and the reason is that it makes me feel at ease.",
    example_ja: "私は朝の運動が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "디저트에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dessert.",
    prompt_ja: "デザートについての考えを詳しく書いてみましょう。",
    example_kr: "저는 디저트를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like dessert, and the reason is that it makes me feel at ease.",
    example_ja: "私はデザートが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "일찍 자기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on going to bed early.",
    prompt_ja: "早く寝ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 일찍 자기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like going to bed early, and the reason is that it makes me feel at ease.",
    example_ja: "私は早く寝ることが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "자전거 타기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cycling.",
    prompt_ja: "自転車に乗ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 자전거 타기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like cycling, and the reason is that it makes me feel at ease.",
    example_ja: "私は自転車に乗ることが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling.",
    prompt_ja: "旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 여행을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like traveling, and the reason is that it makes me feel at ease.",
    example_ja: "私は旅行が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "채식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vegetarian food.",
    prompt_ja: "菜食についての考えを詳しく書いてみましょう。",
    example_kr: "저는 채식을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like vegetarian food, and the reason is that it makes me feel at ease.",
    example_ja: "私は菜食が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "카페에서 공부하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on studying at a cafe.",
    prompt_ja: "カフェで勉強することについての考えを詳しく書いてみましょう。",
    example_kr: "저는 카페에서 공부하기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like studying at a cafe, and the reason is that it makes me feel at ease.",
    example_ja: "私はカフェで勉強することが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "음악 듣기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on listening to music.",
    prompt_ja: "音楽を聴くことについての考えを詳しく書いてみましょう。",
    example_kr: "저는 음악 듣기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like listening to music, and the reason is that it makes me feel at ease.",
    example_ja: "私は音楽を聴くことが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "사진 찍기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on taking photos.",
    prompt_ja: "写真を撮ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 사진 찍기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like taking photos, and the reason is that it makes me feel at ease.",
    example_ja: "私は写真を撮ることが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "짧은 낮잠에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on short naps.",
    prompt_ja: "短い昼寝についての考えを詳しく書いてみましょう。",
    example_kr: "저는 짧은 낮잠을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like short naps, and the reason is that it makes me feel at ease.",
    example_ja: "私は短い昼寝が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "강아지에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dogs.",
    prompt_ja: "犬についての考えを詳しく書いてみましょう。",
    example_kr: "저는 강아지를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like dogs, and the reason is that it makes me feel at ease.",
    example_ja: "私は犬が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "계획 세우기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on making plans.",
    prompt_ja: "計画を立てることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 계획 세우기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like making plans, and the reason is that it makes me feel at ease.",
    example_ja: "私は計画を立てることが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "여름에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on summer.",
    prompt_ja: "夏についての考えを詳しく書いてみましょう。",
    example_kr: "저는 여름을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like summer, and the reason is that it makes me feel at ease.",
    example_ja: "私は夏が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "눈 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on snowy days.",
    prompt_ja: "雪が降る日についての考えを詳しく書いてみましょう。",
    example_kr: "저는 눈 오는 날을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like snowy days, and the reason is that it makes me feel at ease.",
    example_ja: "私は雪が降る日が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "비 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on rainy days.",
    prompt_ja: "雨が降る日についての考えを詳しく書いてみましょう。",
    example_kr: "저는 비 오는 날을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like rainy days, and the reason is that it makes me feel at ease.",
    example_ja: "私は雨が降る日が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "고양이에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cats.",
    prompt_ja: "猫についての考えを詳しく書いてみましょう。",
    example_kr: "저는 고양이를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like cats, and the reason is that it makes me feel at ease.",
    example_ja: "私は猫が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "아침형 인간에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on being a morning person.",
    prompt_ja: "朝型人間についての考えを詳しく書いてみましょう。",
    example_kr: "저는 아침형 인간을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like being a morning person, and the reason is that it makes me feel at ease.",
    example_ja: "私は朝型人間が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "혼밥에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on eating alone.",
    prompt_ja: "一人でご飯を食べることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 혼밥을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like eating alone, and the reason is that it makes me feel at ease.",
    example_ja: "私は一人でご飯を食べることが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "요리하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cooking.",
    prompt_ja: "料理することについての考えを詳しく書いてみましょう。",
    example_kr: "저는 요리하기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like cooking, and the reason is that it makes me feel at ease.",
    example_ja: "私は料理することが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "즉흥 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spontaneous trips.",
    prompt_ja: "思いつきの旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 즉흥 여행을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like spontaneous trips, and the reason is that it makes me feel at ease.",
    example_ja: "私は思いつきの旅行が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "봄에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spring.",
    prompt_ja: "春についての考えを詳しく書いてみましょう。",
    example_kr: "저는 봄을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like spring, and the reason is that it makes me feel at ease.",
    example_ja: "私は春が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "휴가에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vacations.",
    prompt_ja: "休暇についての考えを詳しく書いてみましょう。",
    example_kr: "저는 휴가를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like vacations, and the reason is that it makes me feel at ease.",
    example_ja: "私は休暇が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "가을에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on fall.",
    prompt_ja: "秋についての考えを詳しく書いてみましょう。",
    example_kr: "저는 가을을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like fall, and the reason is that it makes me feel at ease.",
    example_ja: "私は秋が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "혼자 여행하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling alone.",
    prompt_ja: "一人で旅行することについての考えを詳しく書いてみましょう。",
    example_kr: "저는 혼자 여행하기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like traveling alone, and the reason is that it makes me feel at ease.",
    example_ja: "私は一人で旅行することが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "더운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hot weather.",
    prompt_ja: "暑い天気についての考えを詳しく書いてみましょう。",
    example_kr: "저는 더운 날씨를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like hot weather, and the reason is that it makes me feel at ease.",
    example_ja: "私は暑い天気が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "영화 보기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on watching movies.",
    prompt_ja: "映画を見ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 영화 보기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like watching movies, and the reason is that it makes me feel at ease.",
    example_ja: "私は映画を見ることが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "독서에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on reading.",
    prompt_ja: "読書についての考えを詳しく書いてみましょう。",
    example_kr: "저는 독서를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like reading, and the reason is that it makes me feel at ease.",
    example_ja: "私は読書が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "추운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cold weather.",
    prompt_ja: "寒い天気についての考えを詳しく書いてみましょう。",
    example_kr: "저는 추운 날씨를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like cold weather, and the reason is that it makes me feel at ease.",
    example_ja: "私は寒い天気が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "겨울에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on winter.",
    prompt_ja: "冬についての考えを詳しく書いてみましょう。",
    example_kr: "저는 겨울을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like winter, and the reason is that it makes me feel at ease.",
    example_ja: "私は冬が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "야식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on late-night snacks.",
    prompt_ja: "夜食についての考えを詳しく書いてみましょう。",
    example_kr: "저는 야식을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like late-night snacks, and the reason is that it makes me feel at ease.",
    example_ja: "私は夜食が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "매운 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spicy food.",
    prompt_ja: "辛い食べ物についての考えを詳しく書いてみましょう。",
    example_kr: "저는 매운 음식을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like spicy food, and the reason is that it makes me feel at ease.",
    example_ja: "私は辛い食べ物が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "수영에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on swimming.",
    prompt_ja: "水泳についての考えを詳しく書いてみましょう。",
    example_kr: "저는 수영을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like swimming, and the reason is that it makes me feel at ease.",
    example_ja: "私は水泳が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "긴 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on long trips.",
    prompt_ja: "長い旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 긴 여행을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like long trips, and the reason is that it makes me feel at ease.",
    example_ja: "私は長い旅行が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "도시 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on city life.",
    prompt_ja: "都市生活についての考えを詳しく書いてみましょう。",
    example_kr: "저는 도시 생활을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like city life, and the reason is that it makes me feel at ease.",
    example_ja: "私は都市生活が好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "시골 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on countryside life.",
    prompt_ja: "田舎暮らしについての考えを詳しく書いてみましょう。",
    example_kr: "저는 시골 생활을 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like countryside life, and the reason is that it makes me feel at ease.",
    example_ja: "私は田舎暮らしが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "빵 굽기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on baking bread.",
    prompt_ja: "パンを焼くことについての考えを詳しく書いてみましょう。",
    example_kr: "저는 빵 굽기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like baking bread, and the reason is that it makes me feel at ease.",
    example_ja: "私はパンを焼くことが好きです。理由は心が落ち着くからです。",
  },
  {
    level: "B2",
    genre: "opinion",
    prompt_kr: "일찍 일어나기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on waking up early.",
    prompt_ja: "早起きすることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 일찍 일어나기를 좋아하는데 이유는 마음이 편해지기 때문이에요.",
    example_en: "I like waking up early, and the reason is that it makes me feel at ease.",
    example_ja: "私は早起きすることが好きです。理由は心が落ち着くからです。",
  },
];
