import type { RawPrompt } from "./types";

export const WRITING_B2_REPLY: RawPrompt[] = [
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 공원에서 산책해서 떡볶이를 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I walked in the park and ate tteokbokki, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 음악을 들어서 빵을 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I listened to music and ate bread, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 부모님과 통화해서 빵을 구웠어요, 정말 좋았어요.",
    example_en: "Yes, I talked with my parents on the phone and baked bread, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 늦게까지 일해서 일찍 잤어요, 정말 좋았어요.",
    example_en: "Yes, I worked late and went to bed early, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 음악을 들어서 책을 읽었어요, 정말 좋았어요.",
    example_en: "Yes, I listened to music and read a book, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 과일을 사서 커피를 내렸어요, 정말 좋았어요.",
    example_en: "Yes, I bought fruit and brewed coffee, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 커피를 내려서 친구 집에 갔어요, 정말 좋았어요.",
    example_en: "Yes, I brewed coffee and went to a friend's house, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 늦게까지 일해서 공원에서 산책했어요, 정말 좋았어요.",
    example_en: "Yes, I worked late and walked in the park, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화를 봐서 숙제를 했어요, 정말 좋았어요.",
    example_en: "Yes, I watched a movie and did homework, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 음악을 들어서 삼겹살을 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I listened to music and ate samgyeopsal, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 늦게까지 일해서 삼겹살을 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I worked late and ate samgyeopsal, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 일찍 일어나서 삼겹살을 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I woke up early and ate samgyeopsal, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화를 봐서 발표를 준비했어요, 정말 좋았어요.",
    example_en: "Yes, I watched a movie and prepared a presentation, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 빵을 먹어서 아이스크림을 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I ate bread and ate ice cream, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "점심 같이 먹을래요?",
    stimulus_en: "Want to have lunch together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 커피를 내려서 아이스크림을 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I brewed coffee and ate ice cream, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 일찍 일어나서 쇼핑을 했어요, 정말 좋았어요.",
    example_en: "Yes, I woke up early and went shopping, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 커피를 마셔서 숙제를 했어요, 정말 좋았어요.",
    example_en: "Yes, I drank coffee and did homework, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 드라마를 봐서 공원에서 산책했어요, 정말 좋았어요.",
    example_en: "Yes, I watched a drama and walked in the park, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화를 봐서 그림을 그렸어요, 정말 좋았어요.",
    example_en: "Yes, I watched a movie and drew a picture, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 삼겹살을 먹어서 텔레비전을 봤어요, 정말 좋았어요.",
    example_en: "Yes, I ate samgyeopsal and watched TV, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화관에 가서 한국어를 공부했어요, 정말 좋았어요.",
    example_en: "Yes, I went to the movie theater and studied Korean, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 발표를 준비해서 일찍 일어났어요, 정말 좋았어요.",
    example_en: "Yes, I prepared a presentation and woke up early, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 책을 읽어서 강아지를 산책시켰어요, 정말 좋았어요.",
    example_en: "Yes, I read a book and walked the dog, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 게임을 해서 동생을 도와줬어요, 정말 좋았어요.",
    example_en: "Yes, I played a game and helped my younger sibling, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 산에 가서 커피숍에 갔어요, 정말 좋았어요.",
    example_en: "Yes, I went to the mountain and went to a coffee shop, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 아이스크림을 먹어서 일찍 잤어요, 정말 좋았어요.",
    example_en: "Yes, I ate ice cream and went to bed early, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 드라마를 봐서 강아지를 산책시켰어요, 정말 좋았어요.",
    example_en: "Yes, I watched a drama and walked the dog, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 게임을 해서 부모님과 통화했어요, 정말 좋았어요.",
    example_en: "Yes, I played a game and talked with my parents on the phone, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 바다에 가서 게임을 했어요, 정말 좋았어요.",
    example_en: "Yes, I went to the beach and played a game, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 쇼핑을 해서 그림을 그렸어요, 정말 좋았어요.",
    example_en: "Yes, I went shopping and drew a picture, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 공원에서 산책해서 사진을 찍었어요, 정말 좋았어요.",
    example_en: "Yes, I walked in the park and took photos, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 과일을 사서 발표를 준비했어요, 정말 좋았어요.",
    example_en: "Yes, I bought fruit and prepared a presentation, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 방을 정리해서 자전거를 탔어요, 정말 좋았어요.",
    example_en: "Yes, I tidied my room and rode a bike, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 영화관에 가서 운동을 했어요, 정말 좋았어요.",
    example_en: "Yes, I went to the movie theater and exercised, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "점심 같이 먹을래요?",
    stimulus_en: "Want to have lunch together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 커피를 내려서 떡볶이를 먹었어요, 정말 좋았어요.",
    example_en: "Yes, I brewed coffee and ate tteokbokki, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 시장에 가서 부모님과 통화했어요, 정말 좋았어요.",
    example_en: "Yes, I went to the market and talked with my parents on the phone, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 화분에 물을 줘서 쇼핑을 했어요, 정말 좋았어요.",
    example_en: "Yes, I watered the plants and went shopping, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 공원에서 산책해서 발표를 준비했어요, 정말 좋았어요.",
    example_en: "Yes, I walked in the park and prepared a presentation, and it was really nice.",
  },
  {
    level: "B2",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    example_kr: "네, 저는 한국어를 공부해서 텔레비전을 봤어요, 정말 좋았어요.",
    example_en: "Yes, I studied Korean and watched TV, and it was really nice.",
  },
];
