import type { RawPrompt } from "./types";

export const WRITING_C1_REPLY: RawPrompt[] = [
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    stimulus_ja: "夕食は何が食べたいですか？",
    stimulus_zh: "晚饭想吃什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 영화를 봐서 숙제를 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watched a movie and did homework, and I felt good for the first time in a while.",
    example_ja: "はい、私は映画を見て、宿題をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我看了电影，做了作业，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    stimulus_ja: "宿題は全部終わりましたか？",
    stimulus_zh: "作业都做完了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 빨래를 해서 강아지를 산책시켰어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I did laundry and walked the dog, and I felt good for the first time in a while.",
    example_ja: "はい、私は洗濯をして、犬を散歩させました。久しぶりに気分がよかったです。",
    example_zh: "是的，我洗了衣服，带小狗散步了，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    stimulus_ja: "昨日はよく眠れましたか？",
    stimulus_zh: "昨天睡得好吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구랑 통화해서 바다에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I talked with a friend on the phone and went to the beach, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達と電話をして、海に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我和朋友通了电话，去了海边，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    stimulus_ja: "この本、読んでみましたか？",
    stimulus_zh: "你读过这本书吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구랑 통화해서 김치찌개를 만들었어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I talked with a friend on the phone and made kimchi stew, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達と電話をして、キムチチゲを作りました。久しぶりに気分がよかったです。",
    example_zh: "是的，我和朋友通了电话，做了泡菜汤，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    stimulus_ja: "週末はよく過ごせましたか？",
    stimulus_zh: "周末过得好吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 책을 읽어서 그림을 그렸어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I read a book and drew a picture, and I felt good for the first time in a while.",
    example_ja: "はい、私は本を読んで、絵を描きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我读了书，画了画，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    stimulus_ja: "お誕生日おめでとうございます！",
    stimulus_zh: "生日快乐！",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 쇼핑을 해서 김치찌개를 만들었어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went shopping and made kimchi stew, and I felt good for the first time in a while.",
    example_ja: "はい、私は買い物をして、キムチチゲを作りました。久しぶりに気分がよかったです。",
    example_zh: "是的，我购物了，做了泡菜汤，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    stimulus_ja: "今日の天気はどうですか？",
    stimulus_zh: "今天天气怎么样？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 도서관에 가서 노래를 불렀어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went to the library and sang a song, and I felt good for the first time in a while.",
    example_ja: "はい、私は図書館に行って、歌を歌いました。久しぶりに気分がよかったです。",
    example_zh: "是的，我去了图书馆，唱了歌，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    stimulus_ja: "明日、時間は大丈夫ですか？",
    stimulus_zh: "明天有空吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 한국어를 공부해서 산에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I studied Korean and went to the mountain, and I felt good for the first time in a while.",
    example_ja: "はい、私は韓国語を勉強して、山に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我学了韩语，去了山里，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    stimulus_ja: "今日、忙しいですか？",
    stimulus_zh: "你今天忙吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 과일을 사서 도서관에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I bought fruit and went to the library, and I felt good for the first time in a while.",
    example_ja: "はい、私は果物を買って、図書館に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我买了水果，去了图书馆，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    stimulus_ja: "今日の夕方、何をしますか？",
    stimulus_zh: "今天晚上做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 음악을 들어서 바다에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I listened to music and went to the beach, and I felt good for the first time in a while.",
    example_ja: "はい、私は音楽を聞いて、海に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我听了音乐，去了海边，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    stimulus_ja: "今日は何時に終わりますか？",
    stimulus_zh: "你今天几点结束？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 강아지를 산책시켜서 도서관에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I walked the dog and went to the library, and I felt good for the first time in a while.",
    example_ja: "はい、私は犬を散歩させて、図書館に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我带小狗散步了，去了图书馆，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    stimulus_ja: "昨日、どうして来なかったんですか？",
    stimulus_zh: "你昨天为什么没来？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구를 만나서 음악을 들었어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I met a friend and listened to music, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達に会って、音楽を聞きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我见了朋友，听了音乐，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    stimulus_ja: "旅行はどうでしたか？",
    stimulus_zh: "旅行怎么样？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 시장에 가서 새 신발을 샀어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went to the market and bought new shoes, and I felt good for the first time in a while.",
    example_ja: "はい、私は市場に行って、新しい靴を買いました。久しぶりに気分がよかったです。",
    example_zh: "是的，我去了市场，买了新鞋，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    stimulus_ja: "今日の会議は何時ですか？",
    stimulus_zh: "今天会议几点？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 노래를 불러서 일찍 잤어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I sang a song and went to bed early, and I felt good for the first time in a while.",
    example_ja: "はい、私は歌を歌って、早く寝ました。久しぶりに気分がよかったです。",
    example_zh: "是的，我唱了歌，早睡了，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    stimulus_ja: "週末、時間ありますか？",
    stimulus_zh: "周末有时间吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 삼겹살을 먹어서 방을 정리했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I ate samgyeopsal and tidied my room, and I felt good for the first time in a while.",
    example_ja: "はい、私はサムギョプサルを食べて、部屋を片付けました。久しぶりに気分がよかったです。",
    example_zh: "是的，我吃了五花肉，整理了房间，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    stimulus_ja: "一緒に映画見ませんか？",
    stimulus_zh: "要一起看电影吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 쇼핑을 해서 빵을 먹었어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went shopping and ate bread, and I felt good for the first time in a while.",
    example_ja: "はい、私は買い物をして、パンを食べました。久しぶりに気分がよかったです。",
    example_zh: "是的，我购物了，吃了面包，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    stimulus_ja: "今どこにいますか？",
    stimulus_zh: "你现在在哪里？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 청소를 해서 운동을 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I cleaned and exercised, and I felt good for the first time in a while.",
    example_ja: "はい、私は掃除をして、運動をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我打扫了卫生，做了运动，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    stimulus_ja: "今週末、何をするつもりですか？",
    stimulus_zh: "这周末你打算做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 영화를 봐서 사진을 찍었어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watched a movie and took photos, and I felt good for the first time in a while.",
    example_ja: "はい、私は映画を見て、写真を撮りました。久しぶりに気分がよかったです。",
    example_zh: "是的，我看了电影，拍了照片，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "점심 같이 먹을래요?",
    stimulus_en: "Want to have lunch together?",
    stimulus_ja: "お昼、一緒に食べませんか？",
    stimulus_zh: "要一起吃午饭吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구를 만나서 일찍 잤어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I met a friend and went to bed early, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達に会って、早く寝ました。久しぶりに気分がよかったです。",
    example_zh: "是的，我见了朋友，早睡了，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "커피 한잔 할래요?",
    stimulus_en: "Want to grab a coffee?",
    stimulus_ja: "コーヒー一杯飲みませんか？",
    stimulus_zh: "要喝杯咖啡吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 커피숍에 가서 늦게까지 일했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went to a coffee shop and worked late, and I felt good for the first time in a while.",
    example_ja: "はい、私はカフェに行って、遅くまで働きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我去了咖啡厅，工作到很晚，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "저녁에 뭐 먹고 싶어요?",
    stimulus_en: "What do you want to eat for dinner?",
    stimulus_ja: "夕食は何が食べたいですか？",
    stimulus_zh: "晚饭想吃什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 화분에 물을 줘서 사진을 찍었어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watered the plants and took photos, and I felt good for the first time in a while.",
    example_ja: "はい、私は植木に水をあげて、写真を撮りました。久しぶりに気分がよかったです。",
    example_zh: "是的，我给花盆浇了水，拍了照片，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "숙제 다 했어요?",
    stimulus_en: "Did you finish your homework?",
    stimulus_ja: "宿題は全部終わりましたか？",
    stimulus_zh: "作业都做完了吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 책을 읽어서 고양이 밥을 줬어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I read a book and fed the cat, and I felt good for the first time in a while.",
    example_ja: "はい、私は本を読んで、猫にご飯をあげました。久しぶりに気分がよかったです。",
    example_zh: "是的，我读了书，给猫喂了饭，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "어제 잘 잤어요?",
    stimulus_en: "Did you sleep well yesterday?",
    stimulus_ja: "昨日はよく眠れましたか？",
    stimulus_zh: "昨天睡得好吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 도서관에 가서 친구랑 통화했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went to the library and talked with a friend on the phone, and I felt good for the first time in a while.",
    example_ja: "はい、私は図書館に行って、友達と電話をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我去了图书馆，和朋友通了电话，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "이 책 읽어 봤어요?",
    stimulus_en: "Have you read this book?",
    stimulus_ja: "この本、読んでみましたか？",
    stimulus_zh: "你读过这本书吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 바다에 가서 도서관에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went to the beach and went to the library, and I felt good for the first time in a while.",
    example_ja: "はい、私は海に行って、図書館に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我去了海边，去了图书馆，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "주말 잘 보냈어요?",
    stimulus_en: "Did you have a good weekend?",
    stimulus_ja: "週末はよく過ごせましたか？",
    stimulus_zh: "周末过得好吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 떡볶이를 먹어서 회의를 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I ate tteokbokki and had a meeting, and I felt good for the first time in a while.",
    example_ja: "はい、私はトッポギを食べて、会議をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我吃了炒年糕，开了会，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "생일 축하해요!",
    stimulus_en: "Happy birthday!",
    stimulus_ja: "お誕生日おめでとうございます！",
    stimulus_zh: "生日快乐！",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 커피숍에 가서 요리를 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I went to a coffee shop and cooked, and I felt good for the first time in a while.",
    example_ja: "はい、私はカフェに行って、料理をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我去了咖啡厅，做了饭，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 날씨 어때요?",
    stimulus_en: "How's the weather today?",
    stimulus_ja: "今日の天気はどうですか？",
    stimulus_zh: "今天天气怎么样？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 텔레비전을 봐서 강아지를 산책시켰어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watched TV and walked the dog, and I felt good for the first time in a while.",
    example_ja: "はい、私はテレビを見て、犬を散歩させました。久しぶりに気分がよかったです。",
    example_zh: "是的，我看了电视，带小狗散步了，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "내일 시간 괜찮아요?",
    stimulus_en: "Are you free tomorrow?",
    stimulus_ja: "明日、時間は大丈夫ですか？",
    stimulus_zh: "明天有空吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 과일을 사서 방을 정리했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I bought fruit and tidied my room, and I felt good for the first time in a while.",
    example_ja: "はい、私は果物を買って、部屋を片付けました。久しぶりに気分がよかったです。",
    example_zh: "是的，我买了水果，整理了房间，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 바빠요?",
    stimulus_en: "Are you busy today?",
    stimulus_ja: "今日、忙しいですか？",
    stimulus_zh: "你今天忙吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 아이스크림을 먹어서 요리를 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I ate ice cream and cooked, and I felt good for the first time in a while.",
    example_ja: "はい、私はアイスクリームを食べて、料理をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我吃了冰淇淋，做了饭，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 저녁에 뭐 해요?",
    stimulus_en: "What are you doing this evening?",
    stimulus_ja: "今日の夕方、何をしますか？",
    stimulus_zh: "今天晚上做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구를 만나서 일찍 일어났어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I met a friend and woke up early, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達に会って、早く起きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我见了朋友，早起了，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 몇 시에 끝나요?",
    stimulus_en: "What time do you finish today?",
    stimulus_ja: "今日は何時に終わりますか？",
    stimulus_zh: "你今天几点结束？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 고양이 밥을 줘서 커피를 마셨어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I fed the cat and drank coffee, and I felt good for the first time in a while.",
    example_ja: "はい、私は猫にご飯をあげて、コーヒーを飲みました。久しぶりに気分がよかったです。",
    example_zh: "是的，我给猫喂了饭，喝了咖啡，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "어제 왜 안 왔어요?",
    stimulus_en: "Why didn't you come yesterday?",
    stimulus_ja: "昨日、どうして来なかったんですか？",
    stimulus_zh: "你昨天为什么没来？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 영화를 봐서 발표를 준비했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watched a movie and prepared a presentation, and I felt good for the first time in a while.",
    example_ja: "はい、私は映画を見て、発表を準備しました。久しぶりに気分がよかったです。",
    example_zh: "是的，我看了电影，准备了演讲，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "여행 어땠어요?",
    stimulus_en: "How was your trip?",
    stimulus_ja: "旅行はどうでしたか？",
    stimulus_zh: "旅行怎么样？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 편지를 써서 친구랑 통화했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I wrote a letter and talked with a friend on the phone, and I felt good for the first time in a while.",
    example_ja: "はい、私は手紙を書いて、友達と電話をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我写了信，和朋友通了电话，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "오늘 회의 몇 시예요?",
    stimulus_en: "What time is the meeting today?",
    stimulus_ja: "今日の会議は何時ですか？",
    stimulus_zh: "今天会议几点？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구를 만나서 영화를 봤어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I met a friend and watched a movie, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達に会って、映画を見ました。久しぶりに気分がよかったです。",
    example_zh: "是的，我见了朋友，看了电影，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "주말에 시간 있어요?",
    stimulus_en: "Do you have time this weekend?",
    stimulus_ja: "週末、時間ありますか？",
    stimulus_zh: "周末有时间吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 영화를 봐서 강아지를 산책시켰어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watched a movie and walked the dog, and I felt good for the first time in a while.",
    example_ja: "はい、私は映画を見て、犬を散歩させました。久しぶりに気分がよかったです。",
    example_zh: "是的，我看了电影，带小狗散步了，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "같이 영화 볼래요?",
    stimulus_en: "Want to watch a movie together?",
    stimulus_ja: "一緒に映画見ませんか？",
    stimulus_zh: "要一起看电影吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 새 신발을 사서 텔레비전을 봤어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I bought new shoes and watched TV, and I felt good for the first time in a while.",
    example_ja: "はい、私は新しい靴を買って、テレビを見ました。久しぶりに気分がよかったです。",
    example_zh: "是的，我买了新鞋，看了电视，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "지금 어디예요?",
    stimulus_en: "Where are you right now?",
    stimulus_ja: "今どこにいますか？",
    stimulus_zh: "你现在在哪里？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 텔레비전을 봐서 빨래를 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I watched TV and did laundry, and I felt good for the first time in a while.",
    example_ja: "はい、私はテレビを見て、洗濯をしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我看了电视，洗了衣服，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "이번 주말에 뭐 할 거예요?",
    stimulus_en: "What are you going to do this weekend?",
    stimulus_ja: "今週末、何をするつもりですか？",
    stimulus_zh: "这周末你打算做什么？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 친구를 만나서 게임을 했어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I met a friend and played a game, and I felt good for the first time in a while.",
    example_ja: "はい、私は友達に会って、ゲームをしました。久しぶりに気分がよかったです。",
    example_zh: "是的，我见了朋友，玩了游戏，好久没这样开心了。",
  },
  {
    level: "C1",
    genre: "reply",
    stimulus_kr: "점심 같이 먹을래요?",
    stimulus_en: "Want to have lunch together?",
    stimulus_ja: "お昼、一緒に食べませんか？",
    stimulus_zh: "要一起吃午饭吗？",
    prompt_kr: "친구의 메시지에 답장해 보세요.",
    prompt_en: "Try replying to your friend's message.",
    prompt_ja: "友達のメッセージに返信してみましょう。",
    prompt_zh: "试着回复朋友的消息。",
    example_kr: "네, 저는 요리를 해서 도서관에 갔어요, 오랜만에 기분이 좋았어요.",
    example_en: "Yes, I cooked and went to the library, and I felt good for the first time in a while.",
    example_ja: "はい、私は料理をして、図書館に行きました。久しぶりに気分がよかったです。",
    example_zh: "是的，我做了饭，去了图书馆，好久没这样开心了。",
  },
];
