import type { RawPrompt } from "./types";

export const WRITING_C2_JOURNAL: RawPrompt[] = [
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 커피를 내려서 발표를 준비했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I brewed coffee last week and prepared a presentation, spending the whole day at a relaxed pace.",
    example_ja: "私は先週コーヒーを淹れて、発表の準備をしました。一日中のんびりと過ごしました。",
    example_zh: "我上周煮了咖啡，准备了演讲，一整天都过得很悠闲。",
    example_vi: "Tôi pha cà phê rồi đã chuẩn bị bài thuyết trình, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 고양이 밥을 줘서 방을 정리했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I fed the cat a little while ago and tidied my room, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき猫にご飯をあげて、部屋を片付けました。一日中のんびりと過ごしました。",
    example_zh: "我刚才给猫喂了饭，整理了房间，一整天都过得很悠闲。",
    example_vi: "Tôi cho mèo ăn rồi đã dọn phòng, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 부모님과 통화해서 영화관에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I talked with my parents on the phone last month and went to the movie theater, spending the whole day at a relaxed pace.",
    example_ja: "私は先月両親と電話で話して、映画館に行きました。一日中のんびりと過ごしました。",
    example_zh: "我上个月和父母通了电话，去了电影院，一整天都过得很悠闲。",
    example_vi: "Tôi gọi điện với bố mẹ rồi đã đi xem phim, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 이메일을 보내서 사진을 찍었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I sent an email yesterday and took photos, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日メールを送って、写真を撮りました。一日中のんびりと過ごしました。",
    example_zh: "我昨天发了邮件，拍了照片，一整天都过得很悠闲。",
    example_vi: "Tôi gửi email rồi đã chụp ảnh, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 사진을 찍어서 운동을 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I took photos last year and exercised, spending the whole day at a relaxed pace.",
    example_ja: "私は去年写真を撮って、運動をしました。一日中のんびりと過ごしました。",
    example_zh: "我去年拍了照片，做了运动，一整天都过得很悠闲。",
    example_vi: "Tôi chụp ảnh rồi đã tập thể dục, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 이메일을 보내서 숙제를 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I sent an email last week and did homework, spending the whole day at a relaxed pace.",
    example_ja: "私は先週メールを送って、宿題をしました。一日中のんびりと過ごしました。",
    example_zh: "我上周发了邮件，做了作业，一整天都过得很悠闲。",
    example_vi: "Tôi gửi email rồi đã làm bài tập, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 시장에 가서 영화를 봤어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the market a little while ago and watched a movie, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき市場に行って、映画を見ました。一日中のんびりと過ごしました。",
    example_zh: "我刚才去了市场，看了电影，一整天都过得很悠闲。",
    example_vi: "Tôi đi chợ rồi đã xem phim, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 요리를 해서 영화를 봤어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I cooked last month and watched a movie, spending the whole day at a relaxed pace.",
    example_ja: "私は先月料理をして、映画を見ました。一日中のんびりと過ごしました。",
    example_zh: "我上个月做了饭，看了电影，一整天都过得很悠闲。",
    example_vi: "Tôi nấu ăn rồi đã xem phim, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 이메일을 보내서 커피를 내렸어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I sent an email yesterday and brewed coffee, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日メールを送って、コーヒーを淹れました。一日中のんびりと過ごしました。",
    example_zh: "我昨天发了邮件，煮了咖啡，一整天都过得很悠闲。",
    example_vi: "Tôi gửi email rồi đã pha cà phê, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 동생을 도와줘서 운동을 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I helped my younger sibling last year and exercised, spending the whole day at a relaxed pace.",
    example_ja: "私は去年弟や妹を手伝って、運動をしました。一日中のんびりと過ごしました。",
    example_zh: "我去年帮了弟弟，做了运动，一整天都过得很悠闲。",
    example_vi: "Tôi giúp em rồi đã tập thể dục, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 늦게까지 일해서 시장에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I worked late last week and went to the market, spending the whole day at a relaxed pace.",
    example_ja: "私は先週遅くまで仕事をして、市場に行きました。一日中のんびりと過ごしました。",
    example_zh: "我上周工作到很晚，去了市场，一整天都过得很悠闲。",
    example_vi: "Tôi làm việc đến khuya rồi đã đi chợ, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 도서관에 가서 요리를 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the library a little while ago and cooked, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき図書館に行って、料理をしました。一日中のんびりと過ごしました。",
    example_zh: "我刚才去了图书馆，做了饭，一整天都过得很悠闲。",
    example_vi: "Tôi đến thư viện rồi đã nấu ăn, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 공원에서 산책해서 이메일을 보냈어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I walked in the park last month and sent an email, spending the whole day at a relaxed pace.",
    example_ja: "私は先月公園を散歩して、メールを送りました。一日中のんびりと過ごしました。",
    example_zh: "我上个月在公园散步，发了邮件，一整天都过得很悠闲。",
    example_vi: "Tôi đi dạo ở công viên rồi đã gửi email, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 요리를 해서 빨래를 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I cooked yesterday and did laundry, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日料理をして、洗濯をしました。一日中のんびりと過ごしました。",
    example_zh: "我昨天做了饭，洗了衣服，一整天都过得很悠闲。",
    example_vi: "Tôi nấu ăn rồi đã giặt đồ, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 과일을 사서 발표를 준비했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I bought fruit last year and prepared a presentation, spending the whole day at a relaxed pace.",
    example_ja: "私は去年果物を買って、発表の準備をしました。一日中のんびりと過ごしました。",
    example_zh: "我去年买了水果，准备了演讲，一整天都过得很悠闲。",
    example_vi: "Tôi mua trái cây rồi đã chuẩn bị bài thuyết trình, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 사진을 찍어서 책을 읽었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I took photos last week and read a book, spending the whole day at a relaxed pace.",
    example_ja: "私は先週写真を撮って、本を読みました。一日中のんびりと過ごしました。",
    example_zh: "我上周拍了照片，读了书，一整天都过得很悠闲。",
    example_vi: "Tôi chụp ảnh rồi đã đọc sách, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 시장에 가서 사진을 찍었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the market a little while ago and took photos, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき市場に行って、写真を撮りました。一日中のんびりと過ごしました。",
    example_zh: "我刚才去了市场，拍了照片，一整天都过得很悠闲。",
    example_vi: "Tôi đi chợ rồi đã chụp ảnh, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 텔레비전을 봐서 영화관에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I watched TV last month and went to the movie theater, spending the whole day at a relaxed pace.",
    example_ja: "私は先月テレビを見て、映画館に行きました。一日中のんびりと過ごしました。",
    example_zh: "我上个月看了电视，去了电影院，一整天都过得很悠闲。",
    example_vi: "Tôi xem tivi rồi đã đi xem phim, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 부모님과 통화해서 삼겹살을 먹었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I talked with my parents on the phone yesterday and ate samgyeopsal, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日両親と電話で話して、サムギョプサルを食べました。一日中のんびりと過ごしました。",
    example_zh: "我昨天和父母通了电话，吃了五花肉，一整天都过得很悠闲。",
    example_vi: "Tôi gọi điện với bố mẹ rồi đã ăn thịt ba chỉ nướng, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 영화를 봐서 과일을 샀어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I watched a movie last year and bought fruit, spending the whole day at a relaxed pace.",
    example_ja: "私は去年映画を見て、果物を買いました。一日中のんびりと過ごしました。",
    example_zh: "我去年看了电影，买了水果，一整天都过得很悠闲。",
    example_vi: "Tôi xem phim rồi đã mua trái cây, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 강아지를 산책시켜서 쇼핑을 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I walked the dog last week and went shopping, spending the whole day at a relaxed pace.",
    example_ja: "私は先週犬を散歩させて、買い物をしました。一日中のんびりと過ごしました。",
    example_zh: "我上周带小狗散步了，购物了，一整天都过得很悠闲。",
    example_vi: "Tôi dắt chó đi dạo rồi đã đi mua sắm, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 커피숍에 가서 늦게까지 일했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to a coffee shop a little while ago and worked late, spending the whole day at a relaxed pace.",
    example_ja: "私はさっきカフェに行って、遅くまで仕事をしました。一日中のんびりと過ごしました。",
    example_zh: "我刚才去了咖啡厅，工作到很晚，一整天都过得很悠闲。",
    example_vi: "Tôi đến quán cà phê rồi đã làm việc đến khuya, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 영화관에 가서 도서관에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the movie theater last month and went to the library, spending the whole day at a relaxed pace.",
    example_ja: "私は先月映画館に行って、図書館に行きました。一日中のんびりと過ごしました。",
    example_zh: "我上个月去了电影院，去了图书馆，一整天都过得很悠闲。",
    example_vi: "Tôi đi xem phim rồi đã đến thư viện, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 한국어를 공부해서 화분에 물을 줬어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I studied Korean yesterday and watered the plants, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日韓国語を勉強して、植木に水をあげました。一日中のんびりと過ごしました。",
    example_zh: "我昨天学了韩语，给花盆浇了水，一整天都过得很悠闲。",
    example_vi: "Tôi học tiếng Hàn rồi đã tưới cây, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 화분에 물을 줘서 삼겹살을 먹었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I watered the plants last year and ate samgyeopsal, spending the whole day at a relaxed pace.",
    example_ja: "私は去年植木に水をあげて、サムギョプサルを食べました。一日中のんびりと過ごしました。",
    example_zh: "我去年给花盆浇了水，吃了五花肉，一整天都过得很悠闲。",
    example_vi: "Tôi tưới cây rồi đã ăn thịt ba chỉ nướng, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 영화를 봐서 텔레비전을 봤어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I watched a movie last week and watched TV, spending the whole day at a relaxed pace.",
    example_ja: "私は先週映画を見て、テレビを見ました。一日中のんびりと過ごしました。",
    example_zh: "我上周看了电影，看了电视，一整天都过得很悠闲。",
    example_vi: "Tôi xem phim rồi đã xem tivi, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 영화관에 가서 음악을 들었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the movie theater a little while ago and listened to music, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき映画館に行って、音楽を聴きました。一日中のんびりと過ごしました。",
    example_zh: "我刚才去了电影院，听了音乐，一整天都过得很悠闲。",
    example_vi: "Tôi đi xem phim rồi đã nghe nhạc, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 부모님과 통화해서 커피숍에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I talked with my parents on the phone last month and went to a coffee shop, spending the whole day at a relaxed pace.",
    example_ja: "私は先月両親と電話で話して、カフェに行きました。一日中のんびりと過ごしました。",
    example_zh: "我上个月和父母通了电话，去了咖啡厅，一整天都过得很悠闲。",
    example_vi: "Tôi gọi điện với bố mẹ rồi đã đến quán cà phê, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 일찍 자서 김치찌개를 만들었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to bed early yesterday and made kimchi stew, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日早く寝て、キムチチゲを作りました。一日中のんびりと過ごしました。",
    example_zh: "我昨天早睡了，做了泡菜汤，一整天都过得很悠闲。",
    example_vi: "Tôi ngủ sớm rồi đã nấu canh kimchi, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 동생을 도와줘서 회의를 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I helped my younger sibling last year and had a meeting, spending the whole day at a relaxed pace.",
    example_ja: "私は去年弟や妹を手伝って、会議をしました。一日中のんびりと過ごしました。",
    example_zh: "我去年帮了弟弟，开了会，一整天都过得很悠闲。",
    example_vi: "Tôi giúp em rồi đã họp, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 친구를 만나서 시장에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I met a friend last week and went to the market, spending the whole day at a relaxed pace.",
    example_ja: "私は先週友達に会って、市場に行きました。一日中のんびりと過ごしました。",
    example_zh: "我上周见了朋友，去了市场，一整天都过得很悠闲。",
    example_vi: "Tôi gặp bạn rồi đã đi chợ, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 도서관에 가서 쇼핑을 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the library a little while ago and went shopping, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき図書館に行って、買い物をしました。一日中のんびりと過ごしました。",
    example_zh: "我刚才去了图书馆，购物了，一整天都过得很悠闲。",
    example_vi: "Tôi đến thư viện rồi đã đi mua sắm, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 일찍 일어나서 고양이 밥을 줬어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I woke up early last month and fed the cat, spending the whole day at a relaxed pace.",
    example_ja: "私は先月早く起きて、猫にご飯をあげました。一日中のんびりと過ごしました。",
    example_zh: "我上个月早起了，给猫喂了饭，一整天都过得很悠闲。",
    example_vi: "Tôi dậy sớm rồi đã cho mèo ăn, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 동생을 도와줘서 쇼핑을 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I helped my younger sibling yesterday and went shopping, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日弟や妹を手伝って、買い物をしました。一日中のんびりと過ごしました。",
    example_zh: "我昨天帮了弟弟，购物了，一整天都过得很悠闲。",
    example_vi: "Tôi giúp em rồi đã đi mua sắm, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "작년에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last year? Write about it in some detail.",
    prompt_ja: "去年何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你去年做了什么？请详细写一写。",
    prompt_vi: "Năm ngoái bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 작년에 숙제를 해서 쇼핑을 했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I did homework last year and went shopping, spending the whole day at a relaxed pace.",
    example_ja: "私は去年宿題をして、買い物をしました。一日中のんびりと過ごしました。",
    example_zh: "我去年做了作业，购物了，一整天都过得很悠闲。",
    example_vi: "Tôi làm bài tập rồi đã đi mua sắm, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난주에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last week? Write about it in some detail.",
    prompt_ja: "先週何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上周做了什么？请详细写一写。",
    prompt_vi: "Tuần trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난주에 아이스크림을 먹어서 커피숍에 갔어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I ate ice cream last week and went to a coffee shop, spending the whole day at a relaxed pace.",
    example_ja: "私は先週アイスクリームを食べて、カフェに行きました。一日中のんびりと過ごしました。",
    example_zh: "我上周吃了冰淇淋，去了咖啡厅，一整天都过得很悠闲。",
    example_vi: "Tôi ăn kem rồi đã đến quán cà phê, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "아까 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do a little while ago? Write about it in some detail.",
    prompt_ja: "さっき何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你刚才做了什么？请详细写一写。",
    prompt_vi: "Lúc nãy bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 아까 과일을 사서 부모님과 통화했어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I bought fruit a little while ago and talked with my parents on the phone, spending the whole day at a relaxed pace.",
    example_ja: "私はさっき果物を買って、両親と電話で話しました。一日中のんびりと過ごしました。",
    example_zh: "我刚才买了水果，和父母通了电话，一整天都过得很悠闲。",
    example_vi: "Tôi mua trái cây rồi đã gọi điện với bố mẹ, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "지난달에 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do last month? Write about it in some detail.",
    prompt_ja: "先月何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你上个月做了什么？请详细写一写。",
    prompt_vi: "Tháng trước bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 지난달에 시장에 가서 음악을 들었어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I went to the market last month and listened to music, spending the whole day at a relaxed pace.",
    example_ja: "私は先月市場に行って、音楽を聴きました。一日中のんびりと過ごしました。",
    example_zh: "我上个月去了市场，听了音乐，一整天都过得很悠闲。",
    example_vi: "Tôi đi chợ rồi đã nghe nhạc, đã có cả một ngày thảnh thơi thoải mái.",
  },
  {
    level: "C2",
    genre: "journal",
    prompt_kr: "어제 무엇을 했어요? 자세히 써 보세요.",
    prompt_en: "What did you do yesterday? Write about it in some detail.",
    prompt_ja: "昨日何をしましたか？詳しく書いてみましょう。",
    prompt_zh: "你昨天做了什么？请详细写一写。",
    prompt_vi: "Hôm qua bạn đã làm gì? Hãy viết chi tiết.",
    example_kr: "저는 어제 게임을 해서 영화를 봤어요, 하루 종일 여유롭게 시간을 보냈어요.",
    example_en: "I played a game yesterday and watched a movie, spending the whole day at a relaxed pace.",
    example_ja: "私は昨日ゲームをして、映画を見ました。一日中のんびりと過ごしました。",
    example_zh: "我昨天玩了游戏，看了电影，一整天都过得很悠闲。",
    example_vi: "Tôi chơi game rồi đã xem phim, đã có cả một ngày thảnh thơi thoải mái.",
  },
];
