import type { RawPrompt } from "./types";

export const WRITING_C2_OPINION: RawPrompt[] = [
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "매운 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spicy food.",
    prompt_ja: "辛い食べ物についての考えを詳しく書いてみましょう。",
    example_kr: "저는 매운 음식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like spicy food, and the older I get, the more I seem to understand why.",
    example_ja: "私は辛い食べ物が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "영화 보기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on watching movies.",
    prompt_ja: "映画を見ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 영화 보기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like watching movies, and the older I get, the more I seem to understand why.",
    example_ja: "私は映画を見ることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "겨울에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on winter.",
    prompt_ja: "冬についての考えを詳しく書いてみましょう。",
    example_kr: "저는 겨울을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like winter, and the older I get, the more I seem to understand why.",
    example_ja: "私は冬が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "혼밥에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on eating alone.",
    prompt_ja: "一人でご飯を食べることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 혼밥을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like eating alone, and the older I get, the more I seem to understand why.",
    example_ja: "私は一人でご飯を食べることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "단체 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on group trips.",
    prompt_ja: "団体旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 단체 여행을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like group trips, and the older I get, the more I seem to understand why.",
    example_ja: "私は団体旅行が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "주말에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on weekends.",
    prompt_ja: "週末についての考えを詳しく書いてみましょう。",
    example_kr: "저는 주말을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like weekends, and the older I get, the more I seem to understand why.",
    example_ja: "私は週末が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "독서에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on reading.",
    prompt_ja: "読書についての考えを詳しく書いてみましょう。",
    example_kr: "저는 독서를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like reading, and the older I get, the more I seem to understand why.",
    example_ja: "私は読書が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "일찍 일어나기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on waking up early.",
    prompt_ja: "早起きについての考えを詳しく書いてみましょう。",
    example_kr: "저는 일찍 일어나기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like waking up early, and the older I get, the more I seem to understand why.",
    example_ja: "私は早起きが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "긴 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on long trips.",
    prompt_ja: "長い旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 긴 여행을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like long trips, and the older I get, the more I seem to understand why.",
    example_ja: "私は長い旅行が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "시골 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on countryside life.",
    prompt_ja: "田舎暮らしについての考えを詳しく書いてみましょう。",
    example_kr: "저는 시골 생활을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like countryside life, and the older I get, the more I seem to understand why.",
    example_ja: "私は田舎暮らしが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "짧은 낮잠에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on short naps.",
    prompt_ja: "短い昼寝についての考えを詳しく書いてみましょう。",
    example_kr: "저는 짧은 낮잠을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like short naps, and the older I get, the more I seem to understand why.",
    example_ja: "私は短い昼寝が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "여름에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on summer.",
    prompt_ja: "夏についての考えを詳しく書いてみましょう。",
    example_kr: "저는 여름을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like summer, and the older I get, the more I seem to understand why.",
    example_ja: "私は夏が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "야식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on late-night snacks.",
    prompt_ja: "夜食についての考えを詳しく書いてみましょう。",
    example_kr: "저는 야식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like late-night snacks, and the older I get, the more I seem to understand why.",
    example_ja: "私は夜食が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "한국 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on Korean food.",
    prompt_ja: "韓国料理についての考えを詳しく書いてみましょう。",
    example_kr: "저는 한국 음식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like Korean food, and the older I get, the more I seem to understand why.",
    example_ja: "私は韓国料理が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "휴가에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vacations.",
    prompt_ja: "休暇についての考えを詳しく書いてみましょう。",
    example_kr: "저는 휴가를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like vacations, and the older I get, the more I seem to understand why.",
    example_ja: "私は休暇が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "추운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cold weather.",
    prompt_ja: "寒い天気についての考えを詳しく書いてみましょう。",
    example_kr: "저는 추운 날씨를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cold weather, and the older I get, the more I seem to understand why.",
    example_ja: "私は寒い天気が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling.",
    prompt_ja: "旅行についての考えを詳しく書いてみましょう。",
    example_kr: "저는 여행을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like traveling, and the older I get, the more I seem to understand why.",
    example_ja: "私は旅行が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "도시 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on city life.",
    prompt_ja: "都市生活についての考えを詳しく書いてみましょう。",
    example_kr: "저는 도시 생활을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like city life, and the older I get, the more I seem to understand why.",
    example_ja: "私は都市生活が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "계획 세우기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on making plans.",
    prompt_ja: "計画を立てることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 계획 세우기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like making plans, and the older I get, the more I seem to understand why.",
    example_ja: "私は計画を立てることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "일찍 자기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on going to bed early.",
    prompt_ja: "早寝についての考えを詳しく書いてみましょう。",
    example_kr: "저는 일찍 자기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like going to bed early, and the older I get, the more I seem to understand why.",
    example_ja: "私は早寝が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "혼자 여행하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling alone.",
    prompt_ja: "一人旅についての考えを詳しく書いてみましょう。",
    example_kr: "저는 혼자 여행하기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like traveling alone, and the older I get, the more I seem to understand why.",
    example_ja: "私は一人旅が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "등산에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hiking.",
    prompt_ja: "登山についての考えを詳しく書いてみましょう。",
    example_kr: "저는 등산을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like hiking, and the older I get, the more I seem to understand why.",
    example_ja: "私は登山が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "빵 굽기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on baking bread.",
    prompt_ja: "パン作りについての考えを詳しく書いてみましょう。",
    example_kr: "저는 빵 굽기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like baking bread, and the older I get, the more I seem to understand why.",
    example_ja: "私はパン作りが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "디저트에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dessert.",
    prompt_ja: "デザートについての考えを詳しく書いてみましょう。",
    example_kr: "저는 디저트를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like dessert, and the older I get, the more I seem to understand why.",
    example_ja: "私はデザートが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "더운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hot weather.",
    prompt_ja: "暑い天気についての考えを詳しく書いてみましょう。",
    example_kr: "저는 더운 날씨를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like hot weather, and the older I get, the more I seem to understand why.",
    example_ja: "私は暑い天気が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "자전거 타기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cycling.",
    prompt_ja: "自転車に乗ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 자전거 타기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cycling, and the older I get, the more I seem to understand why.",
    example_ja: "私は自転車に乗ることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "봄에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spring.",
    prompt_ja: "春についての考えを詳しく書いてみましょう。",
    example_kr: "저는 봄을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like spring, and the older I get, the more I seem to understand why.",
    example_ja: "私は春が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "수영에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on swimming.",
    prompt_ja: "水泳についての考えを詳しく書いてみましょう。",
    example_kr: "저는 수영을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like swimming, and the older I get, the more I seem to understand why.",
    example_ja: "私は水泳が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "채식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vegetarian food.",
    prompt_ja: "菜食についての考えを詳しく書いてみましょう。",
    example_kr: "저는 채식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like vegetarian food, and the older I get, the more I seem to understand why.",
    example_ja: "私は菜食が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "아침 운동에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on morning exercise.",
    prompt_ja: "朝の運動についての考えを詳しく書いてみましょう。",
    example_kr: "저는 아침 운동을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like morning exercise, and the older I get, the more I seem to understand why.",
    example_ja: "私は朝の運動が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "아침형 인간에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on being a morning person.",
    prompt_ja: "朝型人間についての考えを詳しく書いてみましょう。",
    example_kr: "저는 아침형 인간을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like being a morning person, and the older I get, the more I seem to understand why.",
    example_ja: "私は朝型人間が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "사진 찍기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on taking photos.",
    prompt_ja: "写真を撮ることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 사진 찍기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like taking photos, and the older I get, the more I seem to understand why.",
    example_ja: "私は写真を撮ることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "강아지에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dogs.",
    prompt_ja: "犬についての考えを詳しく書いてみましょう。",
    example_kr: "저는 강아지를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like dogs, and the older I get, the more I seem to understand why.",
    example_ja: "私は犬が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "가을에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on fall.",
    prompt_ja: "秋についての考えを詳しく書いてみましょう。",
    example_kr: "저는 가을을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like fall, and the older I get, the more I seem to understand why.",
    example_ja: "私は秋が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "비 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on rainy days.",
    prompt_ja: "雨の日についての考えを詳しく書いてみましょう。",
    example_kr: "저는 비 오는 날을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like rainy days, and the older I get, the more I seem to understand why.",
    example_ja: "私は雨の日が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "고양이에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cats.",
    prompt_ja: "猫についての考えを詳しく書いてみましょう。",
    example_kr: "저는 고양이를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cats, and the older I get, the more I seem to understand why.",
    example_ja: "私は猫が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "요리하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cooking.",
    prompt_ja: "料理をすることについての考えを詳しく書いてみましょう。",
    example_kr: "저는 요리하기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cooking, and the older I get, the more I seem to understand why.",
    example_ja: "私は料理をすることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "눈 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on snowy days.",
    prompt_ja: "雪の日についての考えを詳しく書いてみましょう。",
    example_kr: "저는 눈 오는 날을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like snowy days, and the older I get, the more I seem to understand why.",
    example_ja: "私は雪の日が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "커피에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on coffee.",
    prompt_ja: "コーヒーについての考えを詳しく書いてみましょう。",
    example_kr: "저는 커피를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like coffee, and the older I get, the more I seem to understand why.",
    example_ja: "私はコーヒーが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
  },
];
