import type { RawPrompt } from "./types";

export const WRITING_C2_OPINION: RawPrompt[] = [
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "매운 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spicy food.",
    prompt_ja: "辛い食べ物についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对辛辣食物的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đồ cay.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la comida picante.",
    example_kr: "저는 매운 음식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like spicy food, and the older I get, the more I seem to understand why.",
    example_ja: "私は辛い食べ物が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢辛辣食物，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích đồ cay, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la comida picante, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "영화 보기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on watching movies.",
    prompt_ja: "映画を見ることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对看电影的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về xem phim.",
    prompt_es: "Escribe con detalle sobre lo que piensas de ver películas.",
    example_kr: "저는 영화 보기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like watching movies, and the older I get, the more I seem to understand why.",
    example_ja: "私は映画を見ることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢看电影，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích xem phim, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de ver películas, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "겨울에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on winter.",
    prompt_ja: "冬についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对冬天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa đông.",
    prompt_es: "Escribe con detalle sobre lo que piensas del invierno.",
    example_kr: "저는 겨울을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like winter, and the older I get, the more I seem to understand why.",
    example_ja: "私は冬が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢冬天，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích mùa đông, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el invierno, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "혼밥에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on eating alone.",
    prompt_ja: "一人でご飯を食べることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对一个人吃饭的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ăn một mình.",
    prompt_es: "Escribe con detalle sobre lo que piensas de comer solo.",
    example_kr: "저는 혼밥을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like eating alone, and the older I get, the more I seem to understand why.",
    example_ja: "私は一人でご飯を食べることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢一个人吃饭，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích ăn một mình, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de comer solo, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "단체 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on group trips.",
    prompt_ja: "団体旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对团体旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch theo nhóm.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los viajes en grupo.",
    example_kr: "저는 단체 여행을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like group trips, and the older I get, the more I seem to understand why.",
    example_ja: "私は団体旅行が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢团体旅行，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích du lịch theo nhóm, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los viajes en grupo, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "주말에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on weekends.",
    prompt_ja: "週末についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对周末的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cuối tuần.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los fines de semana.",
    example_kr: "저는 주말을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like weekends, and the older I get, the more I seem to understand why.",
    example_ja: "私は週末が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢周末，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích cuối tuần, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los fines de semana, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "독서에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on reading.",
    prompt_ja: "読書についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对阅读的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đọc sách.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la lectura.",
    example_kr: "저는 독서를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like reading, and the older I get, the more I seem to understand why.",
    example_ja: "私は読書が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢阅读，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích đọc sách, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la lectura, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "일찍 일어나기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on waking up early.",
    prompt_ja: "早起きについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对早起的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về dậy sớm.",
    prompt_es: "Escribe con detalle sobre lo que piensas de despertarse temprano.",
    example_kr: "저는 일찍 일어나기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like waking up early, and the older I get, the more I seem to understand why.",
    example_ja: "私は早起きが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢早起，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích dậy sớm, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de despertarse temprano, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "긴 여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on long trips.",
    prompt_ja: "長い旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对长途旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về chuyến du lịch dài ngày.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los viajes largos.",
    example_kr: "저는 긴 여행을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like long trips, and the older I get, the more I seem to understand why.",
    example_ja: "私は長い旅行が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢长途旅行，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích chuyến du lịch dài ngày, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los viajes largos, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "시골 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on countryside life.",
    prompt_ja: "田舎暮らしについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对乡村生活的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cuộc sống nông thôn.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la vida en el campo.",
    example_kr: "저는 시골 생활을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like countryside life, and the older I get, the more I seem to understand why.",
    example_ja: "私は田舎暮らしが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢乡村生活，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích cuộc sống nông thôn, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la vida en el campo, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "짧은 낮잠에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on short naps.",
    prompt_ja: "短い昼寝についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对小睡的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về giấc ngủ trưa ngắn.",
    prompt_es: "Escribe con detalle sobre lo que piensas de las siestas cortas.",
    example_kr: "저는 짧은 낮잠을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like short naps, and the older I get, the more I seem to understand why.",
    example_ja: "私は短い昼寝が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢小睡，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích giấc ngủ trưa ngắn, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de las siestas cortas, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "여름에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on summer.",
    prompt_ja: "夏についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对夏天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa hè.",
    prompt_es: "Escribe con detalle sobre lo que piensas del verano.",
    example_kr: "저는 여름을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like summer, and the older I get, the more I seem to understand why.",
    example_ja: "私は夏が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢夏天，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích mùa hè, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el verano, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "야식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on late-night snacks.",
    prompt_ja: "夜食についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对夜宵的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đồ ăn khuya.",
    prompt_es: "Escribe con detalle sobre lo que piensas de las meriendas de medianoche.",
    example_kr: "저는 야식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like late-night snacks, and the older I get, the more I seem to understand why.",
    example_ja: "私は夜食が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢夜宵，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích đồ ăn khuya, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de las meriendas de medianoche, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "한국 음식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on Korean food.",
    prompt_ja: "韓国料理についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对韩国料理的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về món ăn Hàn Quốc.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la comida coreana.",
    example_kr: "저는 한국 음식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like Korean food, and the older I get, the more I seem to understand why.",
    example_ja: "私は韓国料理が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢韩国料理，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích món ăn Hàn Quốc, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la comida coreana, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "휴가에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vacations.",
    prompt_ja: "休暇についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对假期的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về kỳ nghỉ.",
    prompt_es: "Escribe con detalle sobre lo que piensas de las vacaciones.",
    example_kr: "저는 휴가를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like vacations, and the older I get, the more I seem to understand why.",
    example_ja: "私は休暇が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢假期，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích kỳ nghỉ, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de las vacaciones, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "추운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cold weather.",
    prompt_ja: "寒い天気についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对寒冷天气的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về thời tiết lạnh.",
    prompt_es: "Escribe con detalle sobre lo que piensas del clima frío.",
    example_kr: "저는 추운 날씨를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cold weather, and the older I get, the more I seem to understand why.",
    example_ja: "私は寒い天気が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢寒冷天气，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích thời tiết lạnh, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el clima frío, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "여행에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling.",
    prompt_ja: "旅行についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch.",
    prompt_es: "Escribe con detalle sobre lo que piensas de viajar.",
    example_kr: "저는 여행을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like traveling, and the older I get, the more I seem to understand why.",
    example_ja: "私は旅行が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢旅行，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích du lịch, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de viajar, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "도시 생활에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on city life.",
    prompt_ja: "都市生活についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对城市生活的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cuộc sống thành phố.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la vida en la ciudad.",
    example_kr: "저는 도시 생활을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like city life, and the older I get, the more I seem to understand why.",
    example_ja: "私は都市生活が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢城市生活，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích cuộc sống thành phố, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la vida en la ciudad, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "계획 세우기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on making plans.",
    prompt_ja: "計画を立てることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对制定计划的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về lập kế hoạch.",
    prompt_es: "Escribe con detalle sobre lo que piensas de hacer planes.",
    example_kr: "저는 계획 세우기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like making plans, and the older I get, the more I seem to understand why.",
    example_ja: "私は計画を立てることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢制定计划，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích lập kế hoạch, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de hacer planes, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "일찍 자기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on going to bed early.",
    prompt_ja: "早寝についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对早睡的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ngủ sớm.",
    prompt_es: "Escribe con detalle sobre lo que piensas de acostarse temprano.",
    example_kr: "저는 일찍 자기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like going to bed early, and the older I get, the more I seem to understand why.",
    example_ja: "私は早寝が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢早睡，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích ngủ sớm, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de acostarse temprano, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "혼자 여행하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on traveling alone.",
    prompt_ja: "一人旅についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对独自旅行的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về du lịch một mình.",
    prompt_es: "Escribe con detalle sobre lo que piensas de viajar solo.",
    example_kr: "저는 혼자 여행하기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like traveling alone, and the older I get, the more I seem to understand why.",
    example_ja: "私は一人旅が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢独自旅行，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích du lịch một mình, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de viajar solo, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "등산에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hiking.",
    prompt_ja: "登山についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对爬山的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về leo núi.",
    prompt_es: "Escribe con detalle sobre lo que piensas del senderismo.",
    example_kr: "저는 등산을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like hiking, and the older I get, the more I seem to understand why.",
    example_ja: "私は登山が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢爬山，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích leo núi, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el senderismo, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "빵 굽기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on baking bread.",
    prompt_ja: "パン作りについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对烤面包的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về nướng bánh mì.",
    prompt_es: "Escribe con detalle sobre lo que piensas de hornear pan.",
    example_kr: "저는 빵 굽기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like baking bread, and the older I get, the more I seem to understand why.",
    example_ja: "私はパン作りが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢烤面包，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích nướng bánh mì, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de hornear pan, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "디저트에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dessert.",
    prompt_ja: "デザートについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对甜点的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đồ tráng miệng.",
    prompt_es: "Escribe con detalle sobre lo que piensas del postre.",
    example_kr: "저는 디저트를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like dessert, and the older I get, the more I seem to understand why.",
    example_ja: "私はデザートが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢甜点，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích đồ tráng miệng, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el postre, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "더운 날씨에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on hot weather.",
    prompt_ja: "暑い天気についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对炎热天气的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về thời tiết nóng.",
    prompt_es: "Escribe con detalle sobre lo que piensas del clima cálido.",
    example_kr: "저는 더운 날씨를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like hot weather, and the older I get, the more I seem to understand why.",
    example_ja: "私は暑い天気が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢炎热天气，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích thời tiết nóng, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el clima cálido, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "자전거 타기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cycling.",
    prompt_ja: "自転車に乗ることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对骑自行车的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về đi xe đạp.",
    prompt_es: "Escribe con detalle sobre lo que piensas de andar en bicicleta.",
    example_kr: "저는 자전거 타기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cycling, and the older I get, the more I seem to understand why.",
    example_ja: "私は自転車に乗ることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢骑自行车，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích đi xe đạp, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de andar en bicicleta, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "봄에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on spring.",
    prompt_ja: "春についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对春天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa xuân.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la primavera.",
    example_kr: "저는 봄을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like spring, and the older I get, the more I seem to understand why.",
    example_ja: "私は春が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢春天，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích mùa xuân, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la primavera, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "수영에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on swimming.",
    prompt_ja: "水泳についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对游泳的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về bơi lội.",
    prompt_es: "Escribe con detalle sobre lo que piensas de nadar.",
    example_kr: "저는 수영을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like swimming, and the older I get, the more I seem to understand why.",
    example_ja: "私は水泳が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢游泳，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích bơi lội, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de nadar, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "채식에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on vegetarian food.",
    prompt_ja: "菜食についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对素食的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ăn chay.",
    prompt_es: "Escribe con detalle sobre lo que piensas de la comida vegetariana.",
    example_kr: "저는 채식을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like vegetarian food, and the older I get, the more I seem to understand why.",
    example_ja: "私は菜食が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢素食，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích ăn chay, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de la comida vegetariana, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "아침 운동에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on morning exercise.",
    prompt_ja: "朝の運動についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对晨练的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về tập thể dục buổi sáng.",
    prompt_es: "Escribe con detalle sobre lo que piensas del ejercicio matutino.",
    example_kr: "저는 아침 운동을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like morning exercise, and the older I get, the more I seem to understand why.",
    example_ja: "私は朝の運動が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢晨练，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích tập thể dục buổi sáng, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el ejercicio matutino, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "아침형 인간에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on being a morning person.",
    prompt_ja: "朝型人間についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对晨型人的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về người dậy sớm.",
    prompt_es: "Escribe con detalle sobre lo que piensas de ser una persona madrugadora.",
    example_kr: "저는 아침형 인간을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like being a morning person, and the older I get, the more I seem to understand why.",
    example_ja: "私は朝型人間が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢做晨型人，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích người dậy sớm, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de ser una persona madrugadora, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "사진 찍기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on taking photos.",
    prompt_ja: "写真を撮ることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对拍照的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về chụp ảnh.",
    prompt_es: "Escribe con detalle sobre lo que piensas de tomar fotos.",
    example_kr: "저는 사진 찍기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like taking photos, and the older I get, the more I seem to understand why.",
    example_ja: "私は写真を撮ることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢拍照，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích chụp ảnh, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de tomar fotos, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "강아지에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on dogs.",
    prompt_ja: "犬についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对狗的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về chó con.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los perros.",
    example_kr: "저는 강아지를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like dogs, and the older I get, the more I seem to understand why.",
    example_ja: "私は犬が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢狗，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích chó con, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los perros, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "가을에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on fall.",
    prompt_ja: "秋についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对秋天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mùa thu.",
    prompt_es: "Escribe con detalle sobre lo que piensas del otoño.",
    example_kr: "저는 가을을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like fall, and the older I get, the more I seem to understand why.",
    example_ja: "私は秋が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢秋天，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích mùa thu, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el otoño, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "비 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on rainy days.",
    prompt_ja: "雨の日についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对下雨天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ngày mưa.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los días lluviosos.",
    example_kr: "저는 비 오는 날을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like rainy days, and the older I get, the more I seem to understand why.",
    example_ja: "私は雨の日が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢下雨天，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích ngày mưa, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los días lluviosos, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "고양이에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cats.",
    prompt_ja: "猫についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对猫的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về mèo.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los gatos.",
    example_kr: "저는 고양이를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cats, and the older I get, the more I seem to understand why.",
    example_ja: "私は猫が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢猫，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích mèo, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los gatos, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "요리하기에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on cooking.",
    prompt_ja: "料理をすることについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对做饭的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về nấu ăn.",
    prompt_es: "Escribe con detalle sobre lo que piensas de cocinar.",
    example_kr: "저는 요리하기를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like cooking, and the older I get, the more I seem to understand why.",
    example_ja: "私は料理をすることが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢做饭，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích nấu ăn, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de cocinar, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "눈 오는 날에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on snowy days.",
    prompt_ja: "雪の日についての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对下雪天的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về ngày tuyết rơi.",
    prompt_es: "Escribe con detalle sobre lo que piensas de los días de nieve.",
    example_kr: "저는 눈 오는 날을 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like snowy days, and the older I get, the more I seem to understand why.",
    example_ja: "私は雪の日が好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢下雪天，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích ngày tuyết rơi, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de los días de nieve, y cuanto más envejezco, más me parece entender el porqué.",
  },
  {
    level: "C2",
    genre: "opinion",
    prompt_kr: "커피에 대한 생각을 자세히 써 보세요.",
    prompt_en: "Write in some detail about your thoughts on coffee.",
    prompt_ja: "コーヒーについての考えを詳しく書いてみましょう。",
    prompt_zh: "请详细写一下你对咖啡的看法。",
    prompt_vi: "Hãy viết chi tiết suy nghĩ của bạn về cà phê.",
    prompt_es: "Escribe con detalle sobre lo que piensas del café.",
    example_kr: "저는 커피를 좋아하는 편인데 나이가 들수록 그 이유를 더 잘 알게 되는 것 같아요.",
    example_en: "I tend to like coffee, and the older I get, the more I seem to understand why.",
    example_ja: "私はコーヒーが好きな方で、歳を重ねるほどその理由がよく分かるようになる気がします。",
    example_zh: "我比较喜欢咖啡，好像年纪越大越明白其中的原因。",
    example_vi: "Tôi khá thích cà phê, dường như càng lớn tuổi tôi càng hiểu rõ hơn lý do vì sao.",
    example_es: "Suelo disfrutar de el café, y cuanto más envejezco, más me parece entender el porqué.",
  },
];
