import type { RawPassage } from "./types";

export const READING_A1_B: RawPassage[] = [
  {
    level: "A1",
    title_kr: "공원에서",
    title_en: "At the park",
    body_kr: "저는 오늘 공원에 가요. 날씨가 좋아요. 사람들이 자전거를 타요. 저는 벤치에 앉아요.",
    body_en: "Today I go to the park. The weather is nice. People ride bicycles. I sit on a bench.",
    questions: [
      { question_en: "Where does the person go today?", options: ["Park","Beach","Museum","School"], answerIndex: 0 },
      { question_en: "What do people do at the park?", options: ["Swim","Cook food","Ride bicycles","Read books"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "박물관 견학",
    title_en: "Museum field trip",
    body_kr: "오늘 우리 반은 박물관에 가요. 그림이 아주 많아요. 선생님이 설명해요. 저는 사진을 못 찍어요.",
    body_en: "Today our class goes to the museum. There are many paintings. The teacher explains. I cannot take photos.",
    questions: [
      { question_en: "Where does the class go?", options: ["Library","Park","Zoo","Museum"], answerIndex: 3 },
      { question_en: "What can the student not do?", options: ["Take photos","Sit down","Ask questions","Read"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "놀이터에서 놀아요",
    title_en: "Playing at the playground",
    body_kr: "동생이 놀이터에서 놀아요. 그네를 타요. 미끄럼틀도 타요. 저는 동생을 봐요.",
    body_en: "My younger sibling plays at the playground. They ride the swing. They also go down the slide. I watch my sibling.",
    questions: [
      { question_en: "Where is the younger sibling?", options: ["Store","Playground","Home","School"], answerIndex: 1 },
      { question_en: "What does the sibling ride besides the slide?", options: ["Car","Bicycle","Bus","Swing"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "바다에 가요",
    title_en: "Going to the beach",
    body_kr: "여름에 우리는 바다에 가요. 물이 시원해요. 저는 수영을 해요. 저녁에 집에 와요.",
    body_en: "In summer, we go to the beach. The water is cool. I swim. We come home in the evening.",
    questions: [
      { question_en: "When do they go to the beach?", options: ["Winter","Spring","Fall","Summer"], answerIndex: 3 },
      { question_en: "What does the person do at the beach?", options: ["Study","Sleep","Cook","Swim"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "교실 풍경",
    title_en: "The classroom scene",
    body_kr: "교실에 책상이 많아요. 학생들이 자리에 앉아요. 칠판에 글씨가 있어요. 선생님이 들어와요.",
    body_en: "There are many desks in the classroom. Students sit in their seats. There is writing on the blackboard. The teacher comes in.",
    questions: [
      { question_en: "What is on the blackboard?", options: ["A map","Nothing","Pictures","Writing"], answerIndex: 3 },
      { question_en: "Who comes into the classroom?", options: ["A parent","A student","The teacher","A doctor"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "체육 시간",
    title_en: "PE class",
    body_kr: "오늘은 체육 시간이 있어요. 우리는 운동장에서 뛰어요. 축구공을 차요. 조금 힘들어요.",
    body_en: "Today there is PE class. We run on the playground. We kick a soccer ball. It's a bit tiring.",
    questions: [
      { question_en: "Where do they run?", options: ["Classroom","Playground","Library","Gym"], answerIndex: 1 },
      { question_en: "What do they kick?", options: ["A can","A book","A soccer ball","A rock"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "새 학기",
    title_en: "New semester",
    body_kr: "오늘부터 새 학기예요. 새 친구를 만나요. 새 책도 받아요. 저는 조금 떨려요.",
    body_en: "The new semester starts today. I meet new friends. I also receive new books. I'm a little nervous.",
    questions: [
      { question_en: "What starts today?", options: ["A game","New semester","A trip","Vacation"], answerIndex: 1 },
      { question_en: "How does the person feel?", options: ["Very sleepy","Angry","Bored","A little nervous"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "시험 보는 날",
    title_en: "Test day",
    body_kr: "오늘은 시험 보는 날이에요. 저는 아침에 공부해요. 시험이 어려워요. 그래도 최선을 다해요.",
    body_en: "Today is test day. I study in the morning. The test is difficult. Still, I do my best.",
    questions: [
      { question_en: "When does the person study?", options: ["At lunch","At night","In the morning","After school"], answerIndex: 2 },
      { question_en: "How is the test?", options: ["Fun","Short","Easy","Difficult"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "머리가 아파요",
    title_en: "My head hurts",
    body_kr: "오늘 머리가 많이 아파요. 학교에 가고 싶지 않아요. 엄마가 약을 줘요. 저는 일찍 자요.",
    body_en: "My head hurts a lot today. I don't want to go to school. Mom gives me medicine. I go to bed early.",
    questions: [
      { question_en: "What hurts?", options: ["Leg","Head","Arm","Stomach"], answerIndex: 1 },
      { question_en: "Who gives medicine?", options: ["Friend","Teacher","Doctor","Mom"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "배가 아파요",
    title_en: "My stomach hurts",
    body_kr: "점심을 먹고 배가 아파요. 화장실에 자주 가요. 엄마가 걱정해요. 저는 물을 많이 마셔요.",
    body_en: "After lunch, my stomach hurts. I go to the bathroom often. Mom worries. I drink a lot of water.",
    questions: [
      { question_en: "When does the stomach start hurting?", options: ["At night","In the morning","Before breakfast","After lunch"], answerIndex: 3 },
      { question_en: "What does the person drink a lot of?", options: ["Juice","Water","Milk","Tea"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "병원에 가요",
    title_en: "Going to the hospital",
    body_kr: "동생이 다리를 다쳤어요. 우리는 병원에 가요. 의사 선생님이 봐 줘요. 다행히 많이 아프지 않아요.",
    body_en: "My younger sibling hurt their leg. We go to the hospital. The doctor examines them. Luckily, it doesn't hurt much.",
    questions: [
      { question_en: "What did the sibling hurt?", options: ["Arm","Hand","Head","Leg"], answerIndex: 3 },
      { question_en: "Who examines the sibling?", options: ["Doctor","Teacher","Nurse's friend","Parent"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "눈이 나빠요",
    title_en: "My eyesight is bad",
    body_kr: "저는 요즘 칠판이 잘 안 보여요. 눈이 나빠졌어요. 안경을 맞추러 가요. 새 안경이 마음에 들어요.",
    body_en: "Lately I can't see the blackboard well. My eyesight has gotten worse. I go to get glasses fitted. I like my new glasses.",
    questions: [
      { question_en: "What can't the person see well?", options: ["The book","The board","The TV","The sign"], answerIndex: 1 },
      { question_en: "What does the person get?", options: ["A book","A hat","Glasses","A phone"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "이가 아파요",
    title_en: "My tooth hurts",
    body_kr: "어제부터 이가 아파요. 단 음식을 못 먹어요. 오늘 치과에 가요. 치과 선생님이 이를 봐요.",
    body_en: "My tooth has hurt since yesterday. I can't eat sweet food. I go to the dentist today. The dentist checks my tooth.",
    questions: [
      { question_en: "Since when has the tooth hurt?", options: ["Last week","This morning","Today","Yesterday"], answerIndex: 3 },
      { question_en: "What can't the person eat?", options: ["Hot food","Sweet food","Spicy food","Cold food"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "운동 후 몸살",
    title_en: "Sore after exercise",
    body_kr: "어제 운동을 너무 많이 했어요. 오늘 온몸이 아파요. 다리가 특히 아파요. 저는 쉬고 싶어요.",
    body_en: "I exercised too much yesterday. My whole body aches today. My legs especially hurt. I want to rest.",
    questions: [
      { question_en: "When did the person exercise a lot?", options: ["Tomorrow","Yesterday","Today","Last month"], answerIndex: 1 },
      { question_en: "Which part especially hurts?", options: ["Neck","Legs","Back","Arms"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "봄이 왔어요",
    title_en: "Spring has come",
    body_kr: "이제 봄이에요. 꽃이 많이 펴요. 날씨가 따뜻해요. 사람들이 밖에 많이 나가요.",
    body_en: "It's spring now. Many flowers bloom. The weather is warm. People go outside a lot.",
    questions: [
      { question_en: "What season is it?", options: ["Winter","Summer","Fall","Spring"], answerIndex: 3 },
      { question_en: "How is the weather?", options: ["Warm","Hot","Rainy","Cold"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "가을 하늘",
    title_en: "Autumn sky",
    body_kr: "가을 하늘이 아주 파래요. 바람이 시원해요. 나뭇잎이 빨갛고 노래요. 저는 산책을 해요.",
    body_en: "The autumn sky is very blue. The wind is cool. The leaves are red and yellow. I take a walk.",
    questions: [
      { question_en: "What color is the sky?", options: ["Gray","White","Blue","Black"], answerIndex: 2 },
      { question_en: "What does the person do?", options: ["Swim","Study","Sleep","Take a walk"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "첫눈",
    title_en: "First snow",
    body_kr: "오늘 첫눈이 와요. 아이들이 밖으로 나가요. 눈사람을 만들어요. 손이 차갑지만 즐거워요.",
    body_en: "The first snow falls today. The children go outside. They make a snowman. Their hands are cold, but it's fun.",
    questions: [
      { question_en: "What falls today?", options: ["Nothing","The first snow","Rain","Hail"], answerIndex: 1 },
      { question_en: "What do the children make?", options: ["A snowman","A drawing","A sandcastle","A kite"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "더운 여름날",
    title_en: "A hot summer day",
    body_kr: "오늘은 정말 더워요. 에어컨을 켜요. 냉수를 자주 마셔요. 저녁에는 조금 시원해져요.",
    body_en: "Today is really hot. I turn on the air conditioner. I drink cold water often. It gets a bit cooler in the evening.",
    questions: [
      { question_en: "What does the person turn on?", options: ["Light","Heater","Air conditioner","TV"], answerIndex: 2 },
      { question_en: "When does it get cooler?", options: ["Morning","Evening","Never","Noon"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "겨울바람",
    title_en: "Winter wind",
    body_kr: "겨울바람이 아주 차가워요. 저는 두꺼운 옷을 입어요. 목도리도 해요. 그래도 손이 시려요.",
    body_en: "The winter wind is very cold. I wear thick clothes. I also wear a scarf. Still, my hands are cold.",
    questions: [
      { question_en: "What season is described?", options: ["Winter","Fall","Spring","Summer"], answerIndex: 0 },
      { question_en: "What does the person wear besides thick clothes?", options: ["Hat","Gloves","Boots","Scarf"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "장마철",
    title_en: "The rainy season",
    body_kr: "요즘 비가 매일 와요. 장마철이에요. 우산이 꼭 필요해요. 빨래가 잘 안 말라요.",
    body_en: "It rains every day these days. It's the rainy season. An umbrella is essential. Laundry doesn't dry well.",
    questions: [
      { question_en: "What season is it?", options: ["Snow season","Rainy season","Windy season","Dry season"], answerIndex: 1 },
      { question_en: "What is essential now?", options: ["Sunglasses","Umbrella","Boots","Fan"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "택시를 타요",
    title_en: "Taking a taxi",
    body_kr: "비가 많이 와서 택시를 타요. 기사님이 친절해요. 요금이 조금 비싸요. 그래도 편해요.",
    body_en: "It rains a lot, so I take a taxi. The driver is kind. The fare is a bit expensive. Still, it's convenient.",
    questions: [
      { question_en: "Why does the person take a taxi?", options: ["It's fast","It rains","It's cheap","No bus"], answerIndex: 1 },
      { question_en: "How is the fare?", options: ["A bit expensive","Free","Cheap","Unknown"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "기차 여행",
    title_en: "A train trip",
    body_kr: "우리는 기차를 타고 여행해요. 창밖 풍경이 예뻐요. 도시락도 먹어요. 세 시간 후에 도착해요.",
    body_en: "We travel by train. The scenery outside the window is pretty. We also eat a lunch box. We arrive in three hours.",
    questions: [
      { question_en: "How do they travel?", options: ["By boat","By plane","By car","By train"], answerIndex: 3 },
      { question_en: "How long until they arrive?", options: ["One hour","Two hours","Three hours","Five hours"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "공항 가는 길",
    title_en: "The way to the airport",
    body_kr: "내일 우리 가족은 공항에 가요. 캐리어가 아주 무거워요. 아빠가 운전해요. 저는 조금 설레요.",
    body_en: "Tomorrow my family goes to the airport. The suitcase is very heavy. Dad drives. I'm a little excited.",
    questions: [
      { question_en: "Where does the family go tomorrow?", options: ["Airport","Museum","School","Beach"], answerIndex: 0 },
      { question_en: "Who drives?", options: ["Grandpa","Dad","Mom","Sister"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "우체국에서",
    title_en: "At the post office",
    body_kr: "저는 편지를 부치러 우체국에 가요. 줄이 조금 길어요. 직원이 도와줘요. 편지가 잘 도착하면 좋겠어요.",
    body_en: "I go to the post office to send a letter. The line is a bit long. The staff helps me. I hope the letter arrives well.",
    questions: [
      { question_en: "Why does the person go to the post office?", options: ["To buy stamps only","To send a letter","To meet a friend","To eat lunch"], answerIndex: 1 },
      { question_en: "Who helps the person?", options: ["No one","A friend","The staff","The mailman"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "세탁소 심부름",
    title_en: "An errand to the laundry shop",
    body_kr: "엄마가 저에게 심부름을 시켜요. 세탁소에서 옷을 찾아요. 옷이 아주 깨끗해요. 저는 집으로 돌아가요.",
    body_en: "Mom gives me an errand. I pick up clothes at the laundry shop. The clothes are very clean. I go back home.",
    questions: [
      { question_en: "Who gives the errand?", options: ["Mom","Teacher","Dad","Friend"], answerIndex: 0 },
      { question_en: "Where does the person pick up clothes?", options: ["Market","Store","Laundry shop","School"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "미용실에 가요",
    title_en: "Going to the hair salon",
    body_kr: "오늘은 머리를 자르러 가요. 미용실 안이 조용해요. 머리가 짧아져요. 거울을 보니 마음에 들어요.",
    body_en: "Today I go to get my hair cut. It's quiet inside the salon. My hair becomes short. I like it when I look in the mirror.",
    questions: [
      { question_en: "Why does the person go there?", options: ["To cut hair","To see a doctor","To wash clothes","To buy shoes"], answerIndex: 0 },
      { question_en: "How does the person feel about the result?", options: ["Sad","Angry","They like it","Confused"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "우산을 잃어버렸어요",
    title_en: "I lost my umbrella",
    body_kr: "학교에서 집에 올 때 비가 와요. 그런데 우산이 없어요. 버스에 놓고 왔어요. 다음에는 조심해야겠어요.",
    body_en: "It rains when I come home from school. But I don't have an umbrella. I left it on the bus. I need to be more careful next time.",
    questions: [
      { question_en: "What is missing?", options: ["An umbrella","A bag","A book","A phone"], answerIndex: 0 },
      { question_en: "Where was it left?", options: ["Park","Store","Bus","Classroom"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "자전거를 타요",
    title_en: "Riding a bicycle",
    body_kr: "저는 주말마다 자전거를 타요. 강변에서 타면 시원해요. 속도가 조금 빨라요. 운동도 되고 재미있어요.",
    body_en: "I ride a bicycle every weekend. It's cool to ride along the riverside. The speed is a bit fast. It's exercise and fun too.",
    questions: [
      { question_en: "When does the person ride?", options: ["Every weekend","Never","Every day","Only in summer"], answerIndex: 0 },
      { question_en: "Where does the person ride?", options: ["School","Parking lot","Mountain","Riverside"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "동물원 나들이",
    title_en: "A zoo outing",
    body_kr: "우리 가족은 동물원에 가요. 코끼리가 아주 커요. 원숭이가 재미있게 놀아요. 하루 종일 즐거워요.",
    body_en: "My family goes to the zoo. The elephant is very big. The monkey plays in a fun way. It's fun all day.",
    questions: [
      { question_en: "Where does the family go?", options: ["Farm","Zoo","Beach","Museum"], answerIndex: 1 },
      { question_en: "Which animal is very big?", options: ["Lion","Elephant","Bird","Monkey"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "놀이공원",
    title_en: "The amusement park",
    body_kr: "오늘은 놀이공원에 가요. 롤러코스터가 무서워요. 그래도 한 번 더 타요. 팝콘도 사 먹어요.",
    body_en: "Today I go to the amusement park. The roller coaster is scary. Still, I ride it once more. I also buy and eat popcorn.",
    questions: [
      { question_en: "What is scary?", options: ["The clown","The maze","The roller coaster","The Ferris wheel"], answerIndex: 2 },
      { question_en: "What does the person eat?", options: ["Candy","Chips","Popcorn","Ice cream"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "산에 가요",
    title_en: "Going to the mountain",
    body_kr: "일요일에 아빠와 산에 가요. 계단이 많아서 힘들어요. 정상에서 경치가 아름다워요. 물을 많이 마셔요.",
    body_en: "On Sunday, I go to the mountain with Dad. There are many steps, so it's tiring. The view from the top is beautiful. I drink a lot of water.",
    questions: [
      { question_en: "Who does the person go with?", options: ["Friend","Mom","Dad","Teacher"], answerIndex: 2 },
      { question_en: "Why is it tiring?", options: ["It's raining","Many steps","It's far","It's hot"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "미술관 관람",
    title_en: "Visiting the art gallery",
    body_kr: "저는 미술관에서 그림을 봐요. 색깔이 아주 예뻐요. 조용히 걸어 다녀요. 마음이 편안해져요.",
    body_en: "I look at paintings at the art gallery. The colors are very pretty. I walk quietly. My mind becomes calm.",
    questions: [
      { question_en: "What does the person look at?", options: ["Photos","Sculptures","Paintings","Books"], answerIndex: 2 },
      { question_en: "How does the person walk?", options: ["Loudly","Slowly with music","Quietly","Quickly"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "수영장에서",
    title_en: "At the swimming pool",
    body_kr: "오늘 학교에서 수영장에 가요. 물이 조금 차가워요. 저는 수영을 열심히 배워요. 끝나고 배가 고파요.",
    body_en: "Today we go to the swimming pool from school. The water is a bit cold. I learn to swim hard. I'm hungry after it ends.",
    questions: [
      { question_en: "How is the water?", options: ["Warm","Dirty","A bit cold","Hot"], answerIndex: 2 },
      { question_en: "How does the person feel after?", options: ["Angry","Cold only","Hungry","Sleepy"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "학교 운동회",
    title_en: "School sports day",
    body_kr: "오늘은 학교 운동회예요. 우리 반은 파란 팀이에요. 달리기 경기를 해요. 우리 반이 일등을 해요.",
    body_en: "Today is school sports day. Our class is the blue team. We have a running race. Our class wins first place.",
    questions: [
      { question_en: "What color team is the class?", options: ["Blue","Red","Green","Yellow"], answerIndex: 0 },
      { question_en: "What place does the class win?", options: ["Last","First","Third","Second"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "발표 시간",
    title_en: "Presentation time",
    body_kr: "오늘 저는 발표를 해요. 조금 긴장돼요. 목소리가 떨려요. 발표가 끝나니 기분이 좋아요.",
    body_en: "Today I give a presentation. I'm a bit nervous. My voice trembles. I feel good after the presentation ends.",
    questions: [
      { question_en: "How does the person feel before presenting?", options: ["Nervous","Calm","Bored","Happy"], answerIndex: 0 },
      { question_en: "How does the person feel after?", options: ["Good","Angry","Tired only","Sad"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "짝꿍 이야기",
    title_en: "About my desk partner",
    body_kr: "제 짝꿍은 아주 친절해요. 저에게 연필을 빌려줘요. 우리는 같이 숙제를 해요. 짝꿍이 있어서 좋아요.",
    body_en: "My desk partner is very kind. They lend me a pencil. We do homework together. I'm glad to have a desk partner.",
    questions: [
      { question_en: "What does the desk partner lend?", options: ["A phone","Money","A book","A pencil"], answerIndex: 3 },
      { question_en: "What do they do together?", options: ["Cooking","Sports","Homework","Shopping"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "쉬는 시간",
    title_en: "Break time",
    body_kr: "수업이 끝나고 쉬는 시간이에요. 친구들이 복도에서 놀아요. 저는 물을 마셔요. 곧 다음 수업이 시작해요.",
    body_en: "Class ends and it's break time. Friends play in the hallway. I drink water. The next class starts soon.",
    questions: [
      { question_en: "Where do friends play?", options: ["Playground","Hallway","Classroom","Cafeteria"], answerIndex: 1 },
      { question_en: "What does the person drink?", options: ["Juice","Tea","Water","Milk"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "준비물을 잊었어요",
    title_en: "I forgot my school supplies",
    body_kr: "오늘 미술 준비물을 잊었어요. 마음이 급해요. 친구가 색연필을 빌려줘요. 정말 고마워요.",
    body_en: "I forgot my art supplies today. I feel anxious. A friend lends me colored pencils. I'm really thankful.",
    questions: [
      { question_en: "What subject's supplies did the person forget?", options: ["Music","Art","Math","Science"], answerIndex: 1 },
      { question_en: "Who lends colored pencils?", options: ["No one","Friend","Sister","Teacher"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "학교 급식",
    title_en: "School lunch service",
    body_kr: "오늘 급식에 불고기가 나와요. 저는 이 음식을 아주 좋아해요. 친구들과 줄을 서요. 다 먹고 나서 놀아요.",
    body_en: "Bulgogi is served in school lunch today. I like this food a lot. I stand in line with friends. We play after eating everything.",
    questions: [
      { question_en: "What is served today?", options: ["Bulgogi","Rice cake","Kimchi","Soup"], answerIndex: 0 },
      { question_en: "What do they do after eating?", options: ["Study","Play","Sleep","Go home"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "현장 체험 학습",
    title_en: "Field trip learning",
    body_kr: "오늘은 현장 체험 학습이에요. 우리는 버스를 타고 이동해요. 농장에서 동물을 봐요. 아주 신나는 하루예요.",
    body_en: "Today is a field trip. We travel by bus. We see animals at a farm. It's a very exciting day.",
    questions: [
      { question_en: "How do they travel?", options: ["Walking","Train","Bus","Bicycle"], answerIndex: 2 },
      { question_en: "Where do they see animals?", options: ["Farm","Museum","Zoo","Home"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "손을 다쳤어요",
    title_en: "I hurt my hand",
    body_kr: "체육 시간에 손을 다쳤어요. 조금 피가 나요. 양호실에서 치료를 받아요. 이제 괜찮아요.",
    body_en: "I hurt my hand during PE class. A little blood comes out. I get treated at the nurse's office. Now I'm okay.",
    questions: [
      { question_en: "When did the person get hurt?", options: ["Math class","Recess","Lunch","PE class"], answerIndex: 3 },
      { question_en: "Where does the person get treated?", options: ["Classroom","Nurse's office","Home","Hospital"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "콧물이 나요",
    title_en: "I have a runny nose",
    body_kr: "아침부터 콧물이 나요. 목도 조금 아파요. 마스크를 써요. 일찍 자면 나을 거예요.",
    body_en: "I've had a runny nose since morning. My throat also hurts a little. I wear a mask. I'll get better if I sleep early.",
    questions: [
      { question_en: "Since when has the nose been runny?", options: ["Yesterday","Last night","Lunch","Morning"], answerIndex: 3 },
      { question_en: "What does the person wear?", options: ["Glasses","Gloves","Mask","Scarf"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "예방 접종",
    title_en: "Vaccination",
    body_kr: "오늘 병원에서 예방 접종을 받아요. 주사가 조금 아파요. 저는 울지 않아요. 사탕을 받아서 기분이 좋아요.",
    body_en: "I get a vaccination at the hospital today. The shot hurts a little. I don't cry. I feel good because I get candy.",
    questions: [
      { question_en: "What does the person receive at the hospital?", options: ["A vaccination","A check-up only","Medicine","Glasses"], answerIndex: 0 },
      { question_en: "What does the person get afterward?", options: ["Money","Candy","A book","A toy"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "다리가 저려요",
    title_en: "My leg feels numb",
    body_kr: "오래 앉아 있어서 다리가 저려요. 일어나서 걸어요. 조금씩 괜찮아져요. 이제 다시 앉아요.",
    body_en: "My leg feels numb because I sat for a long time. I stand up and walk. It gets a bit better. Now I sit again.",
    questions: [
      { question_en: "Why does the leg feel numb?", options: ["Cold weather","Sitting too long","Jumping","Running"], answerIndex: 1 },
      { question_en: "What does the person do to feel better?", options: ["Walk","Drink water","Sleep","Eat"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "귀가 아파요",
    title_en: "My ear hurts",
    body_kr: "수영을 하고 나서 귀가 아파요. 물이 들어간 것 같아요. 엄마가 귀를 봐줘요. 병원에 가기로 해요.",
    body_en: "My ear hurts after swimming. It seems water got in. Mom checks my ear. We decide to go to the hospital.",
    questions: [
      { question_en: "When did the ear start hurting?", options: ["At school","Before swimming","In the morning","After swimming"], answerIndex: 3 },
      { question_en: "What do they decide to do?", options: ["Ignore it","Go to school","Go to the hospital","Sleep"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "지도를 봐요",
    title_en: "Looking at a map",
    body_kr: "우리는 처음 가는 동네예요. 지도 앱을 봐요. 길을 잘못 들었어요. 다시 찾아서 도착해요.",
    body_en: "We're going to a neighborhood for the first time. We look at a map app. We take the wrong path. We find it again and arrive.",
    questions: [
      { question_en: "What do they use?", options: ["A compass","A radio","A book","A map app"], answerIndex: 3 },
      { question_en: "What happens on the way?", options: ["They get hurt","They get lost","They wait long","It rains"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "은행 심부름",
    title_en: "An errand to the bank",
    body_kr: "엄마 대신 은행에 가요. 번호표를 뽑아요. 조금 기다려요. 순서가 되어서 일을 봐요.",
    body_en: "I go to the bank instead of Mom. I take a number ticket. I wait a bit. My turn comes and I handle the task.",
    questions: [
      { question_en: "What does the person take at the bank?", options: ["A number ticket","A pen","A book","A form"], answerIndex: 0 },
      { question_en: "Who does the person go instead of?", options: ["Mom","Teacher","Dad","Friend"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "택배를 보내요",
    title_en: "Sending a package",
    body_kr: "저는 택배를 보내러 나가요. 상자를 잘 포장해요. 편의점에서 부쳐요. 도착까지 이틀 걸려요.",
    body_en: "I go out to send a package. I wrap the box well. I send it from a convenience store. It takes two days to arrive.",
    questions: [
      { question_en: "Where does the person send the package from?", options: ["School","Post office","Home","Convenience store"], answerIndex: 3 },
      { question_en: "How long does it take to arrive?", options: ["A month","Two days","A week","One day"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "주차장에서",
    title_en: "At the parking lot",
    body_kr: "아빠 차를 주차장에서 찾아요. 자리가 잘 기억이 안 나요. 우리는 여기저기 찾아봐요. 드디어 차를 찾아요.",
    body_en: "We look for Dad's car in the parking lot. We don't remember the spot well. We search here and there. We finally find the car.",
    questions: [
      { question_en: "What are they looking for?", options: ["A key","A person","The car","A bag"], answerIndex: 2 },
      { question_en: "Do they find it in the end?", options: ["They give up","No","Not mentioned","Yes"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "버스를 놓쳤어요",
    title_en: "I missed the bus",
    body_kr: "아침에 버스를 놓쳤어요. 다음 버스를 기다려요. 십 분 후에 버스가 와요. 학교에 조금 늦게 도착해요.",
    body_en: "I missed the bus in the morning. I wait for the next bus. The bus comes ten minutes later. I arrive at school a bit late.",
    questions: [
      { question_en: "When did the person miss the bus?", options: ["Evening","Morning","Night","Afternoon"], answerIndex: 1 },
      { question_en: "How does the person arrive at school?", options: ["Early","A bit late","Very late","On time"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "횡단보도를 건너요",
    title_en: "Crossing the crosswalk",
    body_kr: "저는 횡단보도 앞에서 기다려요. 초록불이 켜져요. 좌우를 살피고 건너요. 안전하게 도착해요.",
    body_en: "I wait in front of the crosswalk. The green light turns on. I check both sides and cross. I arrive safely.",
    questions: [
      { question_en: "What does the person wait for?", options: ["Rain to stop","A friend","The green light","A bus"], answerIndex: 2 },
      { question_en: "What does the person do before crossing?", options: ["Close eyes","Check both sides","Run","Call someone"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "지하 주차장",
    title_en: "The underground parking lot",
    body_kr: "마트 지하 주차장은 조금 어두워요. 표지판을 잘 봐요. 차를 세우고 엘리베이터를 타요. 위층 마트로 가요.",
    body_en: "The mart's underground parking lot is a bit dark. I look carefully at the signs. I park the car and take the elevator. I go up to the mart.",
    questions: [
      { question_en: "How is the underground parking lot?", options: ["A bit dark","Empty","Small","Bright"], answerIndex: 0 },
      { question_en: "What do they take after parking?", options: ["Stairs","Escalator","Elevator","Nothing"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "동네 산책",
    title_en: "A walk around the neighborhood",
    body_kr: "저녁을 먹고 동네를 산책해요. 가로등이 하나둘 켜져요. 강아지들도 산책을 해요. 기분이 상쾌해져요.",
    body_en: "I walk around the neighborhood after dinner. Streetlights turn on one by one. Dogs are also walking. I feel refreshed.",
    questions: [
      { question_en: "When does the walk happen?", options: ["At noon","After dinner","Early morning","Before breakfast"], answerIndex: 1 },
      { question_en: "What else is walking?", options: ["Cats","Children only","Birds","Dogs"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "물놀이 준비",
    title_en: "Getting ready for water play",
    body_kr: "이번 주말에 계곡에 가요. 수영복과 튜브를 챙겨요. 선크림도 발라요. 정말 기대돼요.",
    body_en: "We go to a valley this weekend. I pack a swimsuit and a tube. I also apply sunscreen. I'm really looking forward to it.",
    questions: [
      { question_en: "Where are they going?", options: ["River","Beach","Valley","Pool"], answerIndex: 2 },
      { question_en: "What does the person apply?", options: ["Perfume","Lotion","Oil","Sunscreen"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "캠핑을 가요",
    title_en: "Going camping",
    body_kr: "가족과 함께 캠핑을 가요. 텐트를 같이 세워요. 밤에 별을 봐요. 아주 특별한 시간이에요.",
    body_en: "I go camping with my family. We set up the tent together. We look at stars at night. It's a very special time.",
    questions: [
      { question_en: "What do they set up together?", options: ["A tent","A table","A fire","A chair"], answerIndex: 0 },
      { question_en: "What do they look at night?", options: ["Birds","Fireworks","Stars","The moon only"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    title_kr: "가을 소풍",
    title_en: "An autumn picnic",
    body_kr: "학교에서 가을 소풍을 가요. 공원에서 도시락을 먹어요. 낙엽을 밟으며 걸어요. 즐거운 하루예요.",
    body_en: "We go on an autumn picnic from school. We eat a lunch box at the park. We walk stepping on fallen leaves. It's a fun day.",
    questions: [
      { question_en: "Where do they eat lunch?", options: ["Home","Park","Museum","Classroom"], answerIndex: 1 },
      { question_en: "What do they walk on?", options: ["Fallen leaves","Grass only","Sand","Ice"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "겨울 방학 계획",
    title_en: "Winter vacation plans",
    body_kr: "곧 겨울 방학이에요. 저는 스키를 배우고 싶어요. 책도 많이 읽고 싶어요. 계획이 아주 많아요.",
    body_en: "Winter vacation is coming soon. I want to learn to ski. I also want to read many books. I have a lot of plans.",
    questions: [
      { question_en: "What does the person want to learn?", options: ["Cooking","Swimming","Dancing","Skiing"], answerIndex: 3 },
      { question_en: "What else does the person want to do?", options: ["Travel abroad","Sleep all day","Watch TV","Read many books"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    title_kr: "안개 낀 아침",
    title_en: "A foggy morning",
    body_kr: "오늘 아침에 안개가 많아요. 앞이 잘 안 보여요. 차들이 천천히 가요. 조금 있으면 안개가 걷혀요.",
    body_en: "There is a lot of fog this morning. I can't see well ahead. The cars go slowly. The fog clears in a little while.",
    questions: [
      { question_en: "What is there a lot of this morning?", options: ["Fog","Snow","Rain","Wind"], answerIndex: 0 },
      { question_en: "How do the cars go?", options: ["Slowly","Not at all","Backward","Fast"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    title_kr: "태풍이 와요",
    title_en: "A typhoon is coming",
    body_kr: "내일 태풍이 온대요. 바람이 아주 세요. 우리는 창문을 잘 닫아요. 밖에 나가지 않기로 해요.",
    body_en: "They say a typhoon is coming tomorrow. The wind is very strong. We close the windows well. We decide not to go outside.",
    questions: [
      { question_en: "What is coming tomorrow?", options: ["A typhoon","A heat wave","Snow","Fog"], answerIndex: 0 },
      { question_en: "What do they decide?", options: ["Go outside","Not go outside","Go to school","Go camping"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    title_kr: "무지개를 봐요",
    title_en: "Seeing a rainbow",
    body_kr: "비가 그치고 무지개가 떠요. 색깔이 아주 예뻐요. 저는 사진을 찍어요. 잠깐 있다가 사라져요.",
    body_en: "The rain stops and a rainbow appears. The colors are very pretty. I take a picture. It disappears after a while.",
    questions: [
      { question_en: "When does the rainbow appear?", options: ["In winter","At night","Before rain","After rain stops"], answerIndex: 3 },
      { question_en: "What does the person do?", options: ["Take a picture","Run away","Draw it","Ignore it"], answerIndex: 0 },
    ],
  },
];
