import type { RawPassage } from "./types";

export const READING_A1_DIALOGUE: RawPassage[] = [
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "카페에서 주문하기",
    title_en: "Ordering at a cafe", title_ja: "カフェでの注文", title_zh: "在咖啡馆点单",
    body_kr: "직원: 어서 오세요. 뭐 드릴까요?\n손님: 아메리카노 한 잔 주세요.\n직원: 따뜻한 거요, 아니면 아이스요?\n손님: 아이스로 주세요.\n직원: 네, 사천 원입니다.\n손님: 여기 있어요.",
    body_en: "Clerk: Welcome. What can I get you?\nCustomer: One Americano, please.\nClerk: Hot or iced?\nCustomer: Iced, please.\nClerk: Okay, that's 4,000 won.\nCustomer: Here you go.", body_ja: "店員：いらっしゃいませ。何になさいますか。\n客：アメリカーノを一杯ください。\n店員：ホットになさいますか、それともアイスになさいますか。\n客：アイスでお願いします。\n店員：はい、4,000ウォンです。\n客：はい、どうぞ。", body_zh: "职员: 欢迎光临，您要点什么？\n顾客: 请给我一杯美式咖啡。\n职员: 热的还是冰的？\n顾客: 请给我冰的。\n职员: 好的，一共四千韩元。\n顾客: 给您。",
    questions: [
      { question_en: "What does the customer order?", question_ja: "お客さんは何を注文しましたか。", question_zh: "顾客点了什么？", options: ["Latte","Americano","Tea","Juice"], answerIndex: 1 },
      { question_en: "How much is the drink?", question_ja: "飲み物はいくらですか。", question_zh: "这杯饮品多少钱？", options: ["3,000 won","4,000 won","5,000 won","2,000 won"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "편의점 대화",
    title_en: "At the convenience store", title_ja: "コンビニでの会話", title_zh: "便利店对话",
    body_kr: "손님: 물 한 병 있어요?\n직원: 네, 저기 냉장고에 있어요.\n손님: 감사합니다. 이것도 계산해 주세요.\n직원: 봉투도 필요하세요?\n손님: 아니요, 괜찮아요.\n직원: 이천 원입니다.",
    body_en: "Customer: Do you have a bottle of water?\nClerk: Yes, it's in the fridge over there.\nCustomer: Thank you. Please ring this up too.\nClerk: Do you need a bag too?\nCustomer: No, that's okay.\nClerk: That's 2,000 won.", body_ja: "客：水が一本ありますか。\n店員：はい、あそこの冷蔵庫にあります。\n客：ありがとうございます。これも会計してください。\n店員：袋も必要ですか。\n客：いいえ、大丈夫です。\n店員：2,000ウォンです。", body_zh: "顾客: 有瓶装水吗？\n职员: 有的，在那边的冰箱里。\n顾客: 谢谢。这个也帮我结一下账。\n职员: 需要袋子吗？\n顾客: 不用，没关系。\n职员: 一共两千韩元。",
    questions: [
      { question_en: "What does the customer buy?", question_ja: "お客さんは何を買いますか。", question_zh: "顾客买了什么？", options: ["Coffee","Water","Snack","Juice"], answerIndex: 1 },
      { question_en: "Does the customer need a bag?", question_ja: "お客さんは袋が必要ですか。", question_zh: "顾客需要袋子吗？", options: ["Yes","No","Two bags","Doesn't say"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "버스에서",
    title_en: "On the bus", title_ja: "バスの中で", title_zh: "在公交车上",
    body_kr: "승객: 기사님, 시청역에 가요?\n기사님: 네, 다음다음 정류장이에요.\n승객: 알겠습니다. 감사합니다.\n기사님: 내릴 때 말씀하세요.\n승객: 저 여기서 내릴게요.\n기사님: 네, 조심히 가세요.",
    body_en: "Passenger: Excuse me, does this go to City Hall Station?\nDriver: Yes, it's two stops from here.\nPassenger: I see. Thank you.\nDriver: Let me know when you want to get off.\nPassenger: I'll get off here.\nDriver: Okay, take care.", body_ja: "乗客：運転手さん、市庁駅に行きますか。\n運転手：はい、次の次の停留所です。\n乗客：分かりました。ありがとうございます。\n運転手：降りるときに教えてください。\n乗客：ここで降ります。\n運転手：はい、気をつけて。", body_zh: "乘客: 师傅，去市厅站吗？\n司机: 是的，再过两站。\n乘客: 知道了，谢谢。\n司机: 要下车时请告诉我。\n乘客: 我在这里下车。\n司机: 好的，路上小心。",
    questions: [
      { question_en: "Where does the passenger want to go?", question_ja: "乗客はどこに行きたいですか。", question_zh: "乘客想去哪里？", options: ["Bus terminal","City Hall Station","Airport","Market"], answerIndex: 1 },
      { question_en: "How many stops away is it?", question_ja: "あと何個目の停留所ですか。", question_zh: "还有几站？", options: ["One","Two","Three","Four"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "택시 타기",
    title_en: "Taking a taxi", title_ja: "タクシーに乗る", title_zh: "打车",
    body_kr: "기사님: 어디로 가세요?\n승객: 강남역으로 가 주세요.\n기사님: 네, 알겠습니다.\n승객: 시간이 얼마나 걸려요?\n기사님: 이십 분쯤 걸려요.\n승객: 네, 감사합니다.",
    body_en: "Driver: Where would you like to go?\nPassenger: Please take me to Gangnam Station.\nDriver: Okay, sure.\nPassenger: How long will it take?\nDriver: About twenty minutes.\nPassenger: Okay, thank you.", body_ja: "運転手：どちらまで行かれますか。\n乗客：江南駅までお願いします。\n運転手：はい、承知しました。\n乗客：どのくらい時間がかかりますか。\n運転手：20分くらいかかります。\n乗客：はい、ありがとうございます。", body_zh: "司机: 您去哪里？\n乘客: 请去江南站。\n司机: 好的，知道了。\n乘客: 需要多长时间？\n司机: 大约二十分钟。\n乘客: 好的，谢谢。",
    questions: [
      { question_en: "Where does the passenger want to go?", question_ja: "乗客はどこに行きたいですか。", question_zh: "乘客想去哪里？", options: ["Gangnam Station","City Hall","Airport","Hospital"], answerIndex: 0 },
      { question_en: "How long will the ride take?", question_ja: "乗車時間はどのくらいですか。", question_zh: "车程需要多久？", options: ["Ten minutes","Twenty minutes","Thirty minutes","One hour"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "병원 진료",
    title_en: "A visit to the doctor", title_ja: "病院での診察", title_zh: "医院看病",
    body_kr: "의사: 어디가 아프세요?\n환자: 목이 아프고 기침이 나요.\n의사: 열도 있어요?\n환자: 네, 조금 있어요.\n의사: 약을 드릴게요. 푹 쉬세요.\n환자: 네, 감사합니다.",
    body_en: "Doctor: What's bothering you?\nPatient: My throat hurts and I have a cough.\nDoctor: Do you have a fever too?\nPatient: Yes, a little.\nDoctor: I'll give you some medicine. Please rest well.\nPatient: Okay, thank you.", body_ja: "医者：どこが痛いですか。\n患者：喉が痛くて、咳が出ます。\n医者：熱もありますか。\n患者：はい、少しあります。\n医者：お薬を出しますね。ゆっくり休んでください。\n患者：はい、ありがとうございます。", body_zh: "医生: 哪里不舒服？\n患者: 喉咙痛，还咳嗽。\n医生: 也发烧吗？\n患者: 是的，有一点。\n医生: 我给您开点药，请好好休息。\n患者: 好的，谢谢。",
    questions: [
      { question_en: "What symptoms does the patient have?", question_ja: "患者にはどんな症状がありますか。", question_zh: "患者有什么症状？", options: ["Headache and fever","Sore throat and cough","Stomachache","Toothache"], answerIndex: 1 },
      { question_en: "What does the doctor tell the patient to do?", question_ja: "医者は患者に何をするように言いましたか。", question_zh: "医生让患者做什么？", options: ["Exercise","Rest well","Drink coffee","Go to the hospital"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "약국에서",
    title_en: "At the pharmacy", title_ja: "薬局で", title_zh: "在药店",
    body_kr: "손님: 두통약 있어요?\n약사: 네, 여기 있어요.\n손님: 하루에 몇 번 먹어요?\n약사: 하루에 세 번 드세요.\n손님: 알겠습니다. 얼마예요?\n약사: 오천 원입니다.",
    body_en: "Customer: Do you have headache medicine?\nPharmacist: Yes, here it is.\nCustomer: How many times a day should I take it?\nPharmacist: Take it three times a day.\nCustomer: I see. How much is it?\nPharmacist: It's 5,000 won.", body_ja: "客：頭痛薬はありますか。\n薬剤師：はい、こちらです。\n客：一日に何回飲みますか。\n薬剤師：一日三回飲んでください。\n客：分かりました。いくらですか。\n薬剤師：5,000ウォンです。", body_zh: "顾客: 有头痛药吗？\n药剂师: 有，在这里。\n顾客: 一天吃几次？\n药剂师: 一天吃三次。\n顾客: 知道了。多少钱？\n药剂师: 五千韩元。",
    questions: [
      { question_en: "What medicine does the customer buy?", question_ja: "お客さんはどんな薬を買いますか。", question_zh: "顾客买了什么药？", options: ["Cough medicine","Headache medicine","Stomach medicine","Cold medicine"], answerIndex: 1 },
      { question_en: "How often should the customer take it?", question_ja: "どのくらいの頻度で飲みますか。", question_zh: "顾客应该多久吃一次？", options: ["Once a day","Twice a day","Three times a day","Four times a day"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "지민과 통화",
    title_en: "A phone call with Jimin", title_ja: "ジミンとの電話", title_zh: "和智敏通话",
    body_kr: "지민: 여보세요? 지금 통화 괜찮아?\n저: 응, 괜찮아. 무슨 일이야?\n지민: 이번 주말에 시간 있어?\n저: 응, 토요일에 시간 있어.\n지민: 그럼 같이 영화 볼까?\n저: 좋아! 몇 시에 만날까?",
    body_en: "Jimin: Hello? Is now a good time to talk?\nMe: Yes, it's fine. What's up?\nJimin: Are you free this weekend?\nMe: Yes, I'm free on Saturday.\nJimin: Then shall we watch a movie together?\nMe: Sounds good! What time should we meet?", body_ja: "ジミン：もしもし？今、電話大丈夫？\n私：うん、大丈夫だよ。どうしたの？\nジミン：今週末、時間ある？\n私：うん、土曜日は時間あるよ。\nジミン：じゃあ、一緒に映画を見ようか？\n私：いいね！何時に会おうか？", body_zh: "智敏: 喂？现在方便通话吗？\n我: 嗯，可以。有什么事？\n智敏: 这周末有时间吗？\n我: 有，星期六有时间。\n智敏: 那要不要一起看电影？\n我: 好啊！几点见面？",
    questions: [
      { question_en: "When is the narrator free?", question_ja: "私（語り手）はいつ時間がありますか。", question_zh: "叙述者什么时候有空？", options: ["Friday","Saturday","Sunday","Monday"], answerIndex: 1 },
      { question_en: "What does Jimin suggest doing?", question_ja: "ジミンは何をしようと提案しましたか。", question_zh: "智敏提议做什么？", options: ["Having dinner","Watching a movie","Going shopping","Studying together"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "길 물어보기",
    title_en: "Asking for directions", title_ja: "道を尋ねる", title_zh: "问路",
    body_kr: "저: 실례합니다. 이 근처에 은행이 있어요?\n행인: 네, 저기 사거리에서 오른쪽으로 가세요.\n저: 여기서 멀어요?\n행인: 아니요, 걸어서 오 분쯤 걸려요.\n저: 감사합니다.\n행인: 네, 조심히 가세요.",
    body_en: "Me: Excuse me. Is there a bank near here?\nPasserby: Yes, turn right at that intersection.\nMe: Is it far from here?\nPasserby: No, it takes about five minutes on foot.\nMe: Thank you.\nPasserby: You're welcome, take care.", body_ja: "私：すみません。この近くに銀行はありますか。\n通行人：はい、あそこの交差点で右に曲がってください。\n私：ここから遠いですか。\n通行人：いいえ、歩いて5分くらいです。\n私：ありがとうございます。\n通行人：はい、気をつけて。", body_zh: "我: 打扰一下，这附近有银行吗？\n路人: 有的，在那个十字路口往右走。\n我: 离这里远吗？\n路人: 不远，步行大约五分钟。\n我: 谢谢。\n路人: 不客气，路上小心。",
    questions: [
      { question_en: "What is the narrator looking for?", question_ja: "私は何を探していますか。", question_zh: "叙述者在找什么？", options: ["A hospital","A bank","A pharmacy","A station"], answerIndex: 1 },
      { question_en: "How far is it?", question_ja: "どのくらいの距離ですか。", question_zh: "有多远？", options: ["About five minutes","About ten minutes","About one hour","Very far"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "식당에서 주문하기",
    title_en: "Ordering at a restaurant", title_ja: "レストランでの注文", title_zh: "在餐厅点餐",
    body_kr: "직원: 몇 분이세요?\n손님: 두 명이에요.\n직원: 이쪽으로 앉으세요. 메뉴 여기 있습니다.\n손님: 김치찌개 두 개 주세요.\n직원: 네, 음료수도 필요하세요?\n손님: 물만 주세요.",
    body_en: "Clerk: How many people?\nCustomer: Two people.\nClerk: Please sit here. Here's the menu.\nCustomer: Two kimchi stews, please.\nClerk: Sure, do you need drinks too?\nCustomer: Just water, please.", body_ja: "店員：何名様ですか。\n客：二人です。\n店員：こちらにお座りください。メニューはこちらです。\n客：キムチチゲを二つください。\n店員：はい、お飲み物も必要ですか。\n客：お水だけください。", body_zh: "职员: 几位？\n顾客: 两位。\n职员: 请坐这边，这是菜单。\n顾客: 请给我们两份泡菜汤。\n职员: 好的，还需要饮料吗？\n顾客: 只要水就行。",
    questions: [
      { question_en: "How many people are dining?", question_ja: "何人で食事をしますか。", question_zh: "有几个人用餐？", options: ["One","Two","Three","Four"], answerIndex: 1 },
      { question_en: "What does the customer order to drink?", question_ja: "お客さんは飲み物に何を注文しましたか。", question_zh: "顾客点了什么饮料？", options: ["Soda","Juice","Water","Tea"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "헬스장 등록하기",
    title_en: "Signing up at the gym", title_ja: "ジムに入会する", title_zh: "健身房办会员",
    body_kr: "직원: 안녕하세요. 어떻게 오셨어요?\n회원: 헬스장 등록하고 싶어요.\n직원: 한 달 등록하시겠어요, 세 달 등록하시겠어요?\n회원: 세 달로 할게요.\n직원: 네, 여기에 이름과 전화번호를 써 주세요.\n회원: 네, 알겠습니다.",
    body_en: "Staff: Hello. How can I help you?\nMember: I'd like to sign up for the gym.\nStaff: Would you like a one-month or three-month membership?\nMember: I'll do three months.\nStaff: Okay, please write your name and phone number here.\nMember: Sure, got it.", body_ja: "スタッフ：こんにちは。どのようなご用件ですか。\n会員：ジムに入会したいです。\nスタッフ：1か月コースになさいますか、3か月コースになさいますか。\n会員：3か月にします。\nスタッフ：はい、こちらにお名前と電話番号を書いてください。\n会員：はい、分かりました。", body_zh: "职员: 您好，请问需要什么帮助？\n会员: 我想办健身房会员。\n职员: 您想办一个月的还是三个月的？\n会员: 我要三个月的。\n职员: 好的，请在这里写下姓名和电话号码。\n会员: 好的，知道了。",
    questions: [
      { question_en: "What does the person want to do?", question_ja: "この人は何をしたいですか。", question_zh: "这个人想做什么？", options: ["Cancel a membership","Sign up for the gym","Ask about a trainer","Return equipment"], answerIndex: 1 },
      { question_en: "How long a membership does the person choose?", question_ja: "どのくらいの期間の会員コースを選びましたか。", question_zh: "这个人选择了多长时间的会员？", options: ["One month","Two months","Three months","Six months"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "은행에서 계좌 만들기",
    title_en: "Opening a bank account", title_ja: "銀行で口座を作る", title_zh: "在银行开户",
    body_kr: "손님: 계좌를 만들고 싶어요.\n은행원: 신분증 있으세요?\n손님: 네, 여기 있어요.\n은행원: 이 서류를 작성해 주세요.\n손님: 네, 다 썼어요.\n은행원: 감사합니다. 카드는 다음 주에 나와요.",
    body_en: "Customer: I'd like to open an account.\nBank teller: Do you have an ID?\nCustomer: Yes, here it is.\nBank teller: Please fill out this form.\nCustomer: Okay, I'm done.\nBank teller: Thank you. Your card will be ready next week.", body_ja: "客：口座を作りたいです。\n銀行員：身分証明書はお持ちですか。\n客：はい、こちらです。\n銀行員：この書類にご記入ください。\n客：はい、書き終わりました。\n銀行員：ありがとうございます。カードは来週できあがります。", body_zh: "顾客: 我想开一个账户。\n银行职员: 您有身份证吗？\n顾客: 有，给您。\n银行职员: 请填写这份表格。\n顾客: 好，我填完了。\n银行职员: 谢谢。卡下周就能拿到。",
    questions: [
      { question_en: "What does the customer want to do?", question_ja: "お客さんは何をしたいですか。", question_zh: "顾客想做什么？", options: ["Withdraw money","Open an account","Exchange currency","Apply for a loan"], answerIndex: 1 },
      { question_en: "When will the card be ready?", question_ja: "カードはいつできますか。", question_zh: "卡什么时候能拿到？", options: ["Tomorrow","Next week","Next month","Today"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "미용실에서",
    title_en: "At the hair salon", title_ja: "美容室で", title_zh: "在美发店",
    body_kr: "미용사: 오늘 어떻게 해 드릴까요?\n손님: 머리를 좀 짧게 잘라 주세요.\n미용사: 얼마나 짧게요?\n손님: 어깨 정도로 해 주세요.\n미용사: 네, 파마도 하시겠어요?\n손님: 아니요, 자르기만 할게요.",
    body_en: "Hairdresser: What would you like today?\nCustomer: Please cut my hair a bit shorter.\nHairdresser: How short?\nCustomer: About shoulder length, please.\nHairdresser: Sure, would you like a perm too?\nCustomer: No, just a cut, please.", body_ja: "美容師：今日はどのようになさいますか。\n客：髪を少し短く切ってください。\n美容師：どのくらい短くしますか。\n客：肩くらいの長さにしてください。\n美容師：はい、パーマもかけますか。\n客：いいえ、カットだけにします。", body_zh: "美发师: 今天想怎么弄？\n顾客: 请把头发剪短一点。\n美发师: 要剪多短？\n顾客: 剪到肩膀左右就行。\n美发师: 好的，要烫发吗？\n顾客: 不用，只剪就行。",
    questions: [
      { question_en: "What does the customer want done?", question_ja: "お客さんは何をしてもらいたいですか。", question_zh: "顾客想做什么？", options: ["A perm","A haircut","Hair coloring","Hair washing only"], answerIndex: 1 },
      { question_en: "How short does the customer want their hair?", question_ja: "どのくらいの長さにしたいですか。", question_zh: "顾客想剪多短？", options: ["Very short","Shoulder length","Chin length","No change"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "이웃과의 대화",
    title_en: "A conversation with a neighbor", title_ja: "隣人との会話", title_zh: "和邻居的对话",
    body_kr: "이웃: 안녕하세요. 이사 오셨어요?\n저: 네, 지난주에 이사 왔어요.\n이웃: 반가워요. 저는 302호에 살아요.\n저: 저는 301호예요. 잘 부탁드려요.\n이웃: 혹시 필요한 거 있으면 말씀하세요.\n저: 감사합니다.",
    body_en: "Neighbor: Hello. Did you just move in?\nMe: Yes, I moved in last week.\nNeighbor: Nice to meet you. I live in unit 302.\nMe: I'm in unit 301. Nice to meet you too.\nNeighbor: If you need anything, just let me know.\nMe: Thank you.", body_ja: "隣人：こんにちは。引っ越してこられたんですか。\n私：はい、先週引っ越してきました。\n隣人：よろしくお願いします。私は302号室に住んでいます。\n私：私は301号室です。よろしくお願いします。\n隣人：何か必要なものがあれば言ってください。\n私：ありがとうございます。", body_zh: "邻居: 您好，您是搬来的吗？\n我: 是的，上周搬来的。\n邻居: 很高兴认识您。我住在302号。\n我: 我住在301号，请多关照。\n邻居: 如果需要什么，请跟我说。\n我: 谢谢。",
    questions: [
      { question_en: "When did the narrator move in?", question_ja: "私はいつ引っ越してきましたか。", question_zh: "叙述者什么时候搬来的？", options: ["Yesterday","Last week","Last month","Today"], answerIndex: 1 },
      { question_en: "What unit does the neighbor live in?", question_ja: "隣人は何号室に住んでいますか。", question_zh: "邻居住在几号房？", options: ["301","302","303","304"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "회사 동료와의 대화",
    title_en: "A conversation with a coworker", title_ja: "会社の同僚との会話", title_zh: "和公司同事的对话",
    body_kr: "김대리: 오늘 회의 몇 시예요?\n박대리: 두 시예요. 회의실 3층이에요.\n김대리: 자료는 다 준비했어요?\n박대리: 네, 이메일로 보냈어요.\n김대리: 확인해 볼게요. 고마워요.\n박대리: 네, 이따가 봐요.",
    body_en: "Kim: What time is the meeting today?\nPark: It's at 2 o'clock. The meeting room is on the third floor.\nKim: Did you prepare all the materials?\nPark: Yes, I sent them by email.\nKim: I'll check them. Thanks.\nPark: Sure, see you later.", body_ja: "キム主任：今日の会議は何時ですか。\nパク主任：2時です。会議室は3階です。\nキム主任：資料はもう準備しましたか。\nパク主任：はい、メールで送りました。\nキム主任：確認してみます。ありがとう。\nパク主任：はい、また後で。", body_zh: "金代理: 今天几点开会？\n朴代理: 两点，会议室在三楼。\n金代理: 资料都准备好了吗？\n朴代理: 是的，已经用邮件发过去了。\n金代理: 我确认一下，谢谢。\n朴代理: 好的，一会儿见。",
    questions: [
      { question_en: "What time is the meeting?", question_ja: "会議は何時ですか。", question_zh: "会议是几点？", options: ["1 o'clock","2 o'clock","3 o'clock","4 o'clock"], answerIndex: 1 },
      { question_en: "How did Park send the materials?", question_ja: "パクさんはどうやって資料を送りましたか。", question_zh: "朴代理怎么发送资料的？", options: ["By hand","By email","By phone","By mail"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "부동산에서 집 구하기",
    title_en: "Looking for an apartment", title_ja: "不動産屋で部屋を探す", title_zh: "在房产中介找房子",
    body_kr: "손님: 원룸을 구하고 있어요.\n중개인: 보증금과 월세는 어느 정도 생각하세요?\n손님: 보증금 오백에 월세 오십이요.\n중개인: 마침 좋은 집이 있어요. 지금 보러 갈까요?\n손님: 네, 좋아요.\n중개인: 그럼 차로 같이 가요.",
    body_en: "Customer: I'm looking for a studio apartment.\nAgent: What deposit and monthly rent were you thinking of?\nCustomer: A 5 million won deposit and 500,000 won rent.\nAgent: There happens to be a good place. Shall we go see it now?\nCustomer: Yes, sounds good.\nAgent: Then let's go together by car.", body_ja: "客：ワンルームを探しています。\n仲介人：保証金と家賃はどのくらいをお考えですか。\n客：保証金500万ウォンに家賃50万ウォンです。\n仲介人：ちょうど良い物件があります。今から見に行きましょうか。\n客：はい、いいですね。\n仲介人：それでは車で一緒に行きましょう。", body_zh: "顾客: 我在找一间单身公寓。\n中介: 押金和月租大概想要多少？\n顾客: 押金五百万韩元，月租五十万韩元。\n中介: 正好有一间不错的房子，现在要去看看吗？\n顾客: 好，可以。\n中介: 那我们坐车一起去吧。",
    questions: [
      { question_en: "What is the customer looking for?", question_ja: "お客さんは何を探していますか。", question_zh: "顾客在找什么？", options: ["A house","A studio apartment","An office","A store"], answerIndex: 1 },
      { question_en: "What does the agent suggest doing?", question_ja: "仲介人は何をしようと提案しましたか。", question_zh: "中介建议做什么？", options: ["Calling later","Going to see the place now","Sending photos","Waiting a week"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "세탁소에서",
    title_en: "At the dry cleaner", title_ja: "クリーニング店で", title_zh: "在洗衣店",
    body_kr: "손님: 이 재킷 좀 세탁해 주세요.\n직원: 네, 언제까지 필요하세요?\n손님: 금요일까지 필요해요.\n직원: 네, 목요일까지 해 드릴게요.\n손님: 가격은 얼마예요?\n직원: 만 원입니다.",
    body_en: "Customer: Please clean this jacket.\nClerk: Sure, when do you need it by?\nCustomer: I need it by Friday.\nClerk: Okay, I'll have it done by Thursday.\nCustomer: How much does it cost?\nClerk: It's 10,000 won.", body_ja: "客：このジャケットをクリーニングしてください。\n店員：はい、いつまでに必要ですか。\n客：金曜日までに必要です。\n店員：はい、木曜日までに仕上げます。\n客：値段はいくらですか。\n店員：1万ウォンです。", body_zh: "顾客: 请帮我洗一下这件外套。\n职员: 好的，您什么时候需要？\n顾客: 星期五之前需要。\n职员: 好的，星期四之前给您弄好。\n顾客: 多少钱？\n职员: 一万韩元。",
    questions: [
      { question_en: "What does the customer bring in?", question_ja: "お客さんは何を持ってきましたか。", question_zh: "顾客拿来了什么？", options: ["A coat","A jacket","A shirt","Pants"], answerIndex: 1 },
      { question_en: "When will the item be ready?", question_ja: "いつ仕上がりますか。", question_zh: "什么时候能取？", options: ["Wednesday","Thursday","Friday","Saturday"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "서점에서 책 찾기",
    title_en: "Finding a book at the bookstore", title_ja: "書店で本を探す", title_zh: "在书店找书",
    body_kr: "손님: 한국어 교재를 찾고 있어요.\n직원: 초급이세요, 중급이세요?\n손님: 초급이요.\n직원: 이쪽 코너에 있어요. 같이 가 드릴게요.\n손님: 감사합니다. 이 책으로 할게요.\n직원: 네, 계산 도와드릴게요.",
    body_en: "Customer: I'm looking for a Korean textbook.\nClerk: Beginner or intermediate level?\nCustomer: Beginner level.\nClerk: They're in this section. Let me show you.\nCustomer: Thank you. I'll take this book.\nClerk: Okay, let me ring that up for you.", body_ja: "客：韓国語の教材を探しています。\n店員：初級ですか、中級ですか。\n客：初級です。\n店員：こちらのコーナーにあります。ご案内します。\n客：ありがとうございます。この本にします。\n店員：はい、お会計いたします。", body_zh: "顾客: 我在找韩语教材。\n职员: 初级还是中级？\n顾客: 初级。\n职员: 在这边，我带您去。\n顾客: 谢谢，我就要这本。\n职员: 好的，我帮您结账。",
    questions: [
      { question_en: "What kind of book is the customer looking for?", question_ja: "お客さんはどんな本を探していますか。", question_zh: "顾客在找什么样的书？", options: ["A novel","A Korean textbook","A cookbook","A magazine"], answerIndex: 1 },
      { question_en: "What level does the customer want?", question_ja: "お客さんはどのレベルを望んでいますか。", question_zh: "顾客想要哪个级别？", options: ["Beginner","Intermediate","Advanced","Doesn't say"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "우체국에서 소포 보내기",
    title_en: "Sending a package at the post office", title_ja: "郵便局で小包を送る", title_zh: "在邮局寄包裹",
    body_kr: "손님: 이 소포를 미국으로 보내고 싶어요.\n직원: 무게를 재 볼게요. 이 킬로그램이네요.\n손님: 얼마나 빨리 도착해요?\n직원: 항공으로 보내면 일주일 정도 걸려요.\n손님: 그럼 항공으로 보내 주세요.\n직원: 네, 삼만 원입니다.",
    body_en: "Customer: I'd like to send this package to the US.\nClerk: Let me weigh it. It's two kilograms.\nCustomer: How fast will it arrive?\nClerk: If you send it by air, it takes about a week.\nCustomer: Then please send it by air.\nClerk: Okay, that's 30,000 won.", body_ja: "客：この小包をアメリカに送りたいです。\n職員：重さを量りますね。2キログラムですね。\n客：どのくらい早く届きますか。\n職員：航空便で送ると1週間くらいかかります。\n客：それでは航空便で送ってください。\n職員：はい、3万ウォンです。", body_zh: "顾客: 我想把这个包裹寄到美国。\n职员: 我称一下重量，两公斤。\n顾客: 多快能到？\n职员: 空运的话大约一周。\n顾客: 那就用空运寄吧。\n职员: 好的，三万韩元。",
    questions: [
      { question_en: "Where is the package going?", question_ja: "小包はどこに送りますか。", question_zh: "包裹要寄到哪里？", options: ["Canada","The US","Japan","France"], answerIndex: 1 },
      { question_en: "How is the package sent?", question_ja: "小包はどうやって送りますか。", question_zh: "包裹用什么方式寄？", options: ["By ship","By air","By truck","By train"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "지민과 약속 잡기",
    title_en: "Making plans with Jimin", title_ja: "ジミンと約束を決める", title_zh: "和智敏约定",
    body_kr: "지민: 이번 주 금요일 저녁에 뭐 해?\n저: 아직 특별한 계획 없어.\n지민: 그럼 새로 생긴 식당에 갈래?\n저: 좋아! 몇 시에 만날까?\n지민: 일곱 시에 역 앞에서 만나자.\n저: 알겠어, 그때 봐!",
    body_en: "Jimin: What are you doing this Friday evening?\nMe: I don't have any special plans yet.\nJimin: Then do you want to go to the new restaurant?\nMe: Sounds good! What time should we meet?\nJimin: Let's meet in front of the station at 7.\nMe: Okay, see you then!", body_ja: "ジミン：今週の金曜日の夜、何してる？\n私：まだ特別な予定はないよ。\nジミン：じゃあ、新しくできたレストランに行かない？\n私：いいね！何時に会おうか？\nジミン：7時に駅の前で会おう。\n私：分かった、その時にね！", body_zh: "智敏: 这周五晚上你做什么？\n我: 还没有特别的计划。\n智敏: 那要不要去新开的餐厅？\n我: 好啊！几点见面？\n智敏: 七点在车站前见吧。\n我: 好的，到时候见！",
    questions: [
      { question_en: "What does Jimin suggest?", question_ja: "ジミンは何を提案していますか。", question_zh: "智敏提议什么？", options: ["Watching a movie","Going to a new restaurant","Going shopping","Going hiking"], answerIndex: 1 },
      { question_en: "Where will they meet?", question_ja: "二人はどこで会いますか。", question_zh: "他们在哪里见面？", options: ["At Jimin's house","In front of the station","At the restaurant","At my house"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "호텔 체크인",
    title_en: "Checking in at a hotel", title_ja: "ホテルのチェックイン", title_zh: "酒店办理入住",
    body_kr: "직원: 어서 오세요. 예약하셨어요?\n손님: 네, 이지은으로 예약했어요.\n직원: 네, 확인했습니다. 여권 좀 보여 주세요.\n손님: 여기 있어요.\n직원: 방은 5층 502호입니다.\n손님: 감사합니다.",
    body_en: "Staff: Welcome. Do you have a reservation?\nGuest: Yes, it's under Lee Jieun.\nStaff: Yes, I found it. Could I see your passport?\nGuest: Here it is.\nStaff: Your room is on the 5th floor, room 502.\nGuest: Thank you.", body_ja: "スタッフ：いらっしゃいませ。ご予約はされていますか。\n客：はい、イ・ジウンの名前で予約しました。\nスタッフ：はい、確認しました。パスポートを見せてください。\n客：こちらです。\nスタッフ：お部屋は5階の502号室です。\n客：ありがとうございます。", body_zh: "职员: 欢迎光临，您有预订吗？\n客人: 有，预订人是李智恩。\n职员: 好的，已确认。请出示护照。\n客人: 给您。\n职员: 您的房间是五楼502号。\n客人: 谢谢。",
    questions: [
      { question_en: "What name is the reservation under?", question_ja: "予約は誰の名前になっていますか。", question_zh: "预订人姓名是什么？", options: ["Lee Jieun","Park Jimin","Lee Minho","Choi Yuna"], answerIndex: 0 },
      { question_en: "What room number is the guest given?", question_ja: "客に割り当てられた部屋番号は何ですか。", question_zh: "客人被安排到几号房？", options: ["402","502","503","302"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "옷가게에서",
    title_en: "At the clothing store", title_ja: "洋服店で", title_zh: "在服装店",
    body_kr: "손님: 이 셔츠 좀 입어 봐도 돼요?\n직원: 네, 탈의실은 저쪽이에요.\n손님: 사이즈가 좀 큰 것 같아요.\n직원: 작은 사이즈로 가져다 드릴게요.\n손님: 감사합니다. 이걸로 살게요.\n직원: 네, 계산해 드릴게요.",
    body_en: "Customer: Can I try on this shirt?\nClerk: Sure, the fitting room is over there.\nCustomer: The size seems a bit big.\nClerk: I'll bring you a smaller size.\nCustomer: Thank you. I'll buy this one.\nClerk: Okay, let me ring it up.", body_ja: "客：このシャツを試着してもいいですか。\n店員：はい、試着室はあちらです。\n客：サイズが少し大きいようです。\n店員：小さいサイズをお持ちします。\n客：ありがとうございます。これを買います。\n店員：はい、お会計いたします。", body_zh: "顾客: 我可以试穿这件衬衫吗？\n职员: 可以，试衣间在那边。\n顾客: 尺寸好像有点大。\n职员: 我给您拿小一号的。\n顾客: 谢谢，我买这件。\n职员: 好的，我帮您结账。",
    questions: [
      { question_en: "What does the customer try on?", question_ja: "お客さんは何を試着しますか。", question_zh: "顾客试穿了什么？", options: ["Pants","A shirt","A jacket","Shoes"], answerIndex: 1 },
      { question_en: "What was the problem with the first size?", question_ja: "最初のサイズは何が問題でしたか。", question_zh: "第一个尺码有什么问题？", options: ["Too small","Too big","Wrong color","Too expensive"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "안경점에서",
    title_en: "At the optical shop", title_ja: "眼鏡店で", title_zh: "在眼镜店",
    body_kr: "손님: 안경을 새로 맞추고 싶어요.\n직원: 시력 검사부터 해 드릴게요.\n손님: 네, 알겠습니다.\n직원: 시력이 조금 나빠지셨네요.\n손님: 안경테는 이걸로 할게요.\n직원: 네, 다음 주에 찾으러 오세요.",
    body_en: "Customer: I'd like to get new glasses made.\nStaff: Let's start with an eye exam.\nCustomer: Okay, sure.\nStaff: Your eyesight has gotten a little worse.\nCustomer: I'll go with this frame.\nStaff: Okay, please come pick them up next week.", body_ja: "客：新しく眼鏡を作りたいです。\n店員：まず視力検査をいたします。\n客：はい、分かりました。\n店員：視力が少し落ちていますね。\n客：フレームはこれにします。\n店員：はい、来週受け取りにいらしてください。", body_zh: "顾客: 我想重新配一副眼镜。\n职员: 先给您做视力检查。\n顾客: 好的，知道了。\n职员: 您的视力稍微变差了。\n顾客: 镜框就选这个吧。\n职员: 好的，请下周来取。",
    questions: [
      { question_en: "What does the customer want?", question_ja: "お客さんは何を求めていますか。", question_zh: "顾客想要什么？", options: ["Contact lenses","New glasses","Sunglasses","A repair"], answerIndex: 1 },
      { question_en: "When can the customer pick up the glasses?", question_ja: "いつ眼鏡を受け取れますか。", question_zh: "顾客什么时候能取眼镜？", options: ["Tomorrow","Next week","Next month","Today"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "주유소에서",
    title_en: "At the gas station", title_ja: "ガソリンスタンドで", title_zh: "在加油站",
    body_kr: "직원: 어서 오세요. 얼마나 넣어 드릴까요?\n손님: 오만 원어치 넣어 주세요.\n직원: 네, 카드로 계산하세요, 현금으로 계산하세요?\n손님: 카드로 할게요.\n직원: 네, 다 넣었습니다.\n손님: 감사합니다.",
    body_en: "Staff: Welcome. How much gas would you like?\nCustomer: Please put in 50,000 won worth.\nStaff: Sure, will you pay by card or cash?\nCustomer: I'll pay by card.\nStaff: Okay, it's all filled up.\nCustomer: Thank you.", body_ja: "スタッフ：いらっしゃいませ。どのくらい入れますか。\n客：5万ウォン分入れてください。\nスタッフ：はい、お支払いはカードですか、現金ですか。\n客：カードでお願いします。\nスタッフ：はい、給油完了しました。\n客：ありがとうございます。", body_zh: "职员: 欢迎光临，要加多少油？\n顾客: 请加五万韩元的。\n职员: 好的，刷卡还是付现金？\n顾客: 刷卡。\n职员: 好的，加满了。\n顾客: 谢谢。",
    questions: [
      { question_en: "How much gas does the customer buy?", question_ja: "お客さんはいくら分のガソリンを入れますか。", question_zh: "顾客加了多少油？", options: ["30,000 won worth","50,000 won worth","100,000 won worth","A full tank"], answerIndex: 1 },
      { question_en: "How does the customer pay?", question_ja: "お客さんはどうやって支払いますか。", question_zh: "顾客怎么付款？", options: ["Cash","Card","Mobile pay","Check"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "사진관에서 증명사진 찍기",
    title_en: "Taking an ID photo at the studio", title_ja: "写真館で証明写真を撮る", title_zh: "在照相馆拍证件照",
    body_kr: "손님: 여권 사진을 찍고 싶어요.\n사진사: 네, 이쪽 의자에 앉으세요.\n손님: 옷은 이대로 괜찮아요?\n사진사: 네, 괜찮아요. 정면을 보고 웃지 마세요.\n손님: 언제 찾으러 와요?\n사진사: 삼십 분 후에 오세요.",
    body_en: "Customer: I'd like to take a passport photo.\nPhotographer: Sure, please sit in this chair.\nCustomer: Is my outfit okay as it is?\nPhotographer: Yes, that's fine. Look straight ahead and don't smile.\nCustomer: When should I come pick it up?\nPhotographer: Please come back in thirty minutes.", body_ja: "客：パスポート写真を撮りたいです。\n写真家：はい、こちらの椅子にお座りください。\n客：服装はこのままで大丈夫ですか。\n写真家：はい、大丈夫です。正面を見て、笑わないでください。\n客：いつ受け取りに来ますか。\n写真家：30分後に来てください。", body_zh: "顾客: 我想拍护照照片。\n摄影师: 好的，请坐这边的椅子。\n顾客: 这身衣服可以吗？\n摄影师: 可以，没问题。请看正前方，不要笑。\n顾客: 什么时候来取？\n摄影师: 三十分钟后再来。",
    questions: [
      { question_en: "What kind of photo does the customer want?", question_ja: "お客さんはどんな写真を撮りたいですか。", question_zh: "顾客想拍什么样的照片？", options: ["A wedding photo","A passport photo","A family photo","A pet photo"], answerIndex: 1 },
      { question_en: "When should the customer return?", question_ja: "お客さんはいつ戻ってくればいいですか。", question_zh: "顾客应该什么时候回来？", options: ["In ten minutes","In thirty minutes","In one hour","Tomorrow"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "마트 계산대에서",
    title_en: "At the supermarket checkout", title_ja: "スーパーのレジで", title_zh: "在超市收银台",
    body_kr: "직원: 봉투 필요하세요?\n손님: 네, 하나 주세요.\n직원: 포인트 카드 있으세요?\n손님: 아니요, 없어요.\n직원: 그럼 카드로 계산하시겠어요?\n손님: 네, 카드로 할게요.",
    body_en: "Clerk: Do you need a bag?\nCustomer: Yes, one please.\nClerk: Do you have a points card?\nCustomer: No, I don't.\nClerk: Then will you pay by card?\nCustomer: Yes, I'll pay by card.", body_ja: "店員：袋は必要ですか。\n客：はい、一つください。\n店員：ポイントカードはお持ちですか。\n客：いいえ、持っていません。\n店員：それではカードでお支払いになりますか。\n客：はい、カードで払います。", body_zh: "职员: 需要袋子吗？\n顾客: 需要，给我一个。\n职员: 有积分卡吗？\n顾客: 没有。\n职员: 那么刷卡结账吗？\n顾客: 好，刷卡。",
    questions: [
      { question_en: "Does the customer need a bag?", question_ja: "お客さんは袋が必要ですか。", question_zh: "顾客需要袋子吗？", options: ["No","Yes, one","Yes, two","Doesn't say"], answerIndex: 1 },
      { question_en: "Does the customer have a points card?", question_ja: "お客さんはポイントカードを持っていますか。", question_zh: "顾客有积分卡吗？", options: ["Yes","No","Forgot it","Left it at home"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "치과 진료",
    title_en: "A visit to the dentist", title_ja: "歯科での診察", title_zh: "牙科看病",
    body_kr: "의사: 어디가 아프세요?\n환자: 어금니가 계속 아파요.\n의사: 언제부터 아팠어요?\n환자: 삼 일 전부터요.\n의사: 사진을 찍어 볼게요.\n환자: 네, 알겠습니다.",
    body_en: "Dentist: What's bothering you?\nPatient: My back tooth keeps hurting.\nDentist: Since when has it hurt?\nPatient: Since three days ago.\nDentist: I'll take an X-ray.\nPatient: Okay, sure.", body_ja: "医者：どこが痛いですか。\n患者：奥歯がずっと痛みます。\n医者：いつから痛みますか。\n患者：3日前からです。\n医者：レントゲンを撮ってみますね。\n患者：はい、分かりました。", body_zh: "医生: 哪里不舒服？\n患者: 臼齿一直疼。\n医生: 从什么时候开始疼的？\n患者: 从三天前开始。\n医生: 我给您拍张片子看看。\n患者: 好的，知道了。",
    questions: [
      { question_en: "What is hurting the patient?", question_ja: "患者はどこが痛いですか。", question_zh: "患者哪里疼？", options: ["A front tooth","A back tooth","The gums","The jaw"], answerIndex: 1 },
      { question_en: "Since when has it been hurting?", question_ja: "いつから痛んでいますか。", question_zh: "从什么时候开始疼的？", options: ["One day","Three days","One week","One month"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "면접 보기",
    title_en: "A job interview", title_ja: "面接を受ける", title_zh: "面试",
    body_kr: "면접관: 이 회사에 왜 지원하셨어요?\n지원자: 이 분야에 관심이 많아서 지원했습니다.\n면접관: 경력이 있으세요?\n지원자: 네, 삼 년 정도 있습니다.\n면접관: 언제부터 일할 수 있어요?\n지원자: 다음 달부터 가능합니다.",
    body_en: "Interviewer: Why did you apply to this company?\nApplicant: I applied because I'm very interested in this field.\nInterviewer: Do you have experience?\nApplicant: Yes, about three years.\nInterviewer: When can you start working?\nApplicant: I can start next month.", body_ja: "面接官：なぜこの会社に応募されたのですか。\n応募者：この分野にとても関心があり、応募しました。\n面接官：経歴はおありですか。\n応募者：はい、3年ほどあります。\n面接官：いつから働けますか。\n応募者：来月から可能です。", body_zh: "面试官: 您为什么应聘这家公司？\n应聘者: 因为我对这个领域很感兴趣，所以应聘了。\n面试官: 您有工作经验吗？\n应聘者: 有，大约三年。\n面试官: 您什么时候可以开始工作？\n应聘者: 下个月开始可以。",
    questions: [
      { question_en: "How much experience does the applicant have?", question_ja: "応募者はどのくらいの経験がありますか。", question_zh: "应聘者有多少工作经验？", options: ["One year","Two years","Three years","Five years"], answerIndex: 2 },
      { question_en: "When can the applicant start?", question_ja: "応募者はいつから働き始められますか。", question_zh: "应聘者什么时候可以开始工作？", options: ["This week","Next week","Next month","Next year"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "트레이너와 상담하기",
    title_en: "Consulting with a personal trainer", title_ja: "トレーナーとの相談", title_zh: "和教练咨询",
    body_kr: "트레이너: 운동 목표가 뭐예요?\n회원: 살을 좀 빼고 싶어요.\n트레이너: 일주일에 몇 번 운동할 수 있어요?\n회원: 세 번 정도 가능해요.\n트레이너: 그럼 월, 수, 금으로 계획을 짜요.\n회원: 네, 좋아요.",
    body_en: "Trainer: What's your fitness goal?\nMember: I'd like to lose some weight.\nTrainer: How many times a week can you work out?\nMember: About three times.\nTrainer: Then let's plan for Monday, Wednesday, and Friday.\nMember: Okay, sounds good.", body_ja: "トレーナー：運動の目標は何ですか。\n会員：少し痩せたいです。\nトレーナー：一週間に何回運動できますか。\n会員：3回くらいなら可能です。\nトレーナー：それでは月、水、金で計画を立てましょう。\n会員：はい、いいですね。", body_zh: "教练: 您的运动目标是什么？\n会员: 我想减一点肥。\n教练: 一周能运动几次？\n会员: 大概三次。\n教练: 那我们安排周一、周三、周五。\n会员: 好，可以。",
    questions: [
      { question_en: "What is the member's goal?", question_ja: "会員の目標は何ですか。", question_zh: "会员的目标是什么？", options: ["Gain muscle","Lose weight","Improve flexibility","Run faster"], answerIndex: 1 },
      { question_en: "How many days a week will the member work out?", question_ja: "会員は週に何日運動しますか。", question_zh: "会员一周运动几天？", options: ["Two","Three","Four","Five"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "카페에서 지민 만나기",
    title_en: "Meeting Jimin at a cafe", title_ja: "カフェでジミンに会う", title_zh: "在咖啡馆见智敏",
    body_kr: "저: 지민아, 여기야!\n지민: 오래 기다렸어? 미안해, 늦었지.\n저: 아니야, 나도 방금 왔어.\n지민: 뭐 마실래? 내가 살게.\n저: 그럼 카페라테 마실게.\n지민: 알겠어, 잠깐만 기다려.",
    body_en: "Me: Jimin, over here!\nJimin: Did you wait long? Sorry I'm late.\nMe: No, I just got here too.\nJimin: What do you want to drink? I'll buy.\nMe: Then I'll have a cafe latte.\nJimin: Okay, wait just a moment.", body_ja: "私：ジミン、こっちだよ！\nジミン：長く待った？ごめん、遅れちゃって。\n私：ううん、私も今来たところ。\nジミン：何飲む？私がおごるよ。\n私：じゃあ、カフェラテを飲むね。\nジミン：分かった、ちょっと待ってて。", body_zh: "我: 智敏，这里！\n智敏: 等很久了吗？对不起，我迟到了。\n我: 没有，我也刚到。\n智敏: 想喝什么？我请客。\n我: 那我喝拿铁吧。\n智敏: 好，稍等一下。",
    questions: [
      { question_en: "Who is buying the drinks?", question_ja: "誰が飲み物をおごりますか。", question_zh: "谁请客买饮料？", options: ["Me","Jimin","They split it","Neither"], answerIndex: 1 },
      { question_en: "What drink does the narrator choose?", question_ja: "私はどんな飲み物を選びましたか。", question_zh: "叙述者选了什么饮料？", options: ["Americano","Cafe latte","Tea","Juice"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "전화로 식당 예약하기",
    title_en: "Making a restaurant reservation by phone", title_ja: "電話でレストランを予約する", title_zh: "打电话预订餐厅",
    body_kr: "직원: 안녕하세요, 예약 도와드릴까요?\n손님: 네, 오늘 저녁 일곱 시에 두 명 예약하고 싶어요.\n직원: 죄송하지만 일곱 시는 자리가 없어요.\n손님: 그럼 여덟 시는 어때요?\n직원: 네, 여덟 시는 가능합니다.\n손님: 그럼 그 시간으로 예약할게요.",
    body_en: "Staff: Hello, may I help you with a reservation?\nCustomer: Yes, I'd like to book a table for two at 7 tonight.\nStaff: I'm sorry, but there's no table at 7.\nCustomer: Then how about 8?\nStaff: Yes, 8 is available.\nCustomer: Then I'll book for that time.", body_ja: "店員：こんにちは、ご予約のお手伝いをいたしましょうか。\n客：はい、今日の夜7時に二人で予約したいです。\n店員：申し訳ございませんが、7時は席がございません。\n客：それでは8時はどうですか。\n店員：はい、8時でしたら可能です。\n客：それではその時間で予約します。", body_zh: "职员: 您好，需要帮您预订吗？\n顾客: 是的，我想预订今晚七点两位。\n职员: 不好意思，七点没有空位了。\n顾客: 那八点怎么样？\n职员: 好的，八点可以。\n顾客: 那就预订那个时间吧。",
    questions: [
      { question_en: "How many people is the reservation for?", question_ja: "予約は何人分ですか。", question_zh: "预订是几位？", options: ["One","Two","Three","Four"], answerIndex: 1 },
      { question_en: "What time is the final reservation?", question_ja: "最終的な予約時間は何時ですか。", question_zh: "最终预订的时间是几点？", options: ["Six","Seven","Eight","Nine"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "빵집에서",
    title_en: "At the bakery", title_ja: "パン屋で", title_zh: "在面包店",
    body_kr: "손님: 이 크루아상 얼마예요?\n직원: 삼천 원이에요.\n손님: 두 개 주세요. 그리고 식빵도 하나 주세요.\n직원: 네, 다른 건 필요 없으세요?\n손님: 네, 그거면 돼요.\n직원: 다 합쳐서 만 원입니다.",
    body_en: "Customer: How much is this croissant?\nClerk: It's 3,000 won.\nCustomer: Two of them, please. And one loaf of bread too.\nClerk: Sure, do you need anything else?\nCustomer: No, that's all.\nClerk: That's 10,000 won in total.", body_ja: "客：このクロワッサンはいくらですか。\n店員：3,000ウォンです。\n客：二つください。それから食パンも一つください。\n店員：はい、他には必要ありませんか。\n客：はい、それで結構です。\n店員：全部で1万ウォンです。", body_zh: "顾客: 这个牛角包多少钱？\n职员: 三千韩元。\n顾客: 请给我两个，再给我一个吐司。\n职员: 好的，还需要别的吗？\n顾客: 不用，这样就够了。\n职员: 一共一万韩元。",
    questions: [
      { question_en: "How many croissants does the customer buy?", question_ja: "お客さんはクロワッサンを何個買いますか。", question_zh: "顾客买了几个牛角包？", options: ["One","Two","Three","Four"], answerIndex: 1 },
      { question_en: "What is the total price?", question_ja: "合計金額はいくらですか。", question_zh: "总共多少钱？", options: ["5,000 won","8,000 won","10,000 won","12,000 won"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "꽃집에서",
    title_en: "At the flower shop", title_ja: "花屋で", title_zh: "在花店",
    body_kr: "손님: 어머니 생신 선물로 꽃을 사고 싶어요.\n직원: 어떤 색을 좋아하세요?\n손님: 분홍색을 좋아하세요.\n직원: 그럼 이 장미 어때요?\n손님: 예쁘네요. 열 송이 주세요.\n직원: 네, 포장해 드릴게요.",
    body_en: "Customer: I'd like to buy flowers for my mother's birthday.\nClerk: What color does she like?\nCustomer: She likes pink.\nClerk: Then how about these roses?\nCustomer: They're pretty. Ten of them, please.\nClerk: Sure, I'll wrap them for you.", body_ja: "客：母の誕生日プレゼントに花を買いたいです。\n店員：どんな色がお好きですか。\n客：ピンク色が好きです。\n店員：それではこのバラはいかがですか。\n客：きれいですね。10本ください。\n店員：はい、包装いたします。", body_zh: "顾客: 我想买花作为妈妈生日礼物。\n职员: 她喜欢什么颜色？\n顾客: 她喜欢粉色。\n职员: 那这束玫瑰怎么样？\n顾客: 很漂亮，给我十枝。\n职员: 好的，我帮您包装。",
    questions: [
      { question_en: "Who are the flowers for?", question_ja: "花は誰のためのものですか。", question_zh: "花是给谁买的？", options: ["A friend","The customer's mother","A coworker","A neighbor"], answerIndex: 1 },
      { question_en: "What color flowers does the customer choose?", question_ja: "お客さんは何色の花を選びますか。", question_zh: "顾客选了什么颜色的花？", options: ["White","Pink","Red","Yellow"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "아파트 관리실에서",
    title_en: "At the apartment management office", title_ja: "マンションの管理事務所で", title_zh: "在公寓管理处",
    body_kr: "주민: 저희 집 수도에서 물이 새요.\n관리인: 언제부터 그랬어요?\n주민: 어제 저녁부터요.\n관리인: 오늘 오후에 사람을 보낼게요.\n주민: 몇 시쯤 올 수 있어요?\n관리인: 세 시쯤 갈 거예요.",
    body_en: "Resident: There's a water leak from my faucet.\nManager: Since when has it been like that?\nResident: Since last night.\nManager: I'll send someone this afternoon.\nResident: What time can they come?\nManager: They'll come around 3 o'clock.", body_ja: "住民：うちの水道から水が漏れています。\n管理人：いつからそうなりましたか。\n住民：昨日の夜からです。\n管理人：今日の午後に人を送ります。\n住民：何時ごろ来られますか。\n管理人：3時ごろ行きます。", body_zh: "住户: 我家水龙头在漏水。\n管理员: 从什么时候开始的？\n住户: 从昨天晚上开始。\n管理员: 今天下午我派人过去。\n住户: 大概几点能来？\n管理员: 大约三点会去。",
    questions: [
      { question_en: "What is the problem?", question_ja: "問題は何ですか。", question_zh: "问题是什么？", options: ["No hot water","A water leak","Broken heater","Noisy pipes"], answerIndex: 1 },
      { question_en: "When will someone come to fix it?", question_ja: "いつ修理に来ますか。", question_zh: "什么时候有人来修理？", options: ["This morning","This afternoon","Tomorrow","Next week"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "세차장에서",
    title_en: "At the car wash", title_ja: "洗車場で", title_zh: "在洗车场",
    body_kr: "직원: 어떤 세차를 원하세요?\n손님: 안팎으로 다 해 주세요.\n직원: 네, 시간이 삼십 분 정도 걸려요.\n손님: 여기서 기다려도 돼요?\n직원: 네, 저기 앉아서 기다리세요.\n손님: 감사합니다.",
    body_en: "Staff: What kind of wash would you like?\nCustomer: Please do both inside and outside.\nStaff: Okay, it'll take about thirty minutes.\nCustomer: Can I wait here?\nStaff: Yes, please have a seat over there and wait.\nCustomer: Thank you.", body_ja: "スタッフ：どんな洗車をご希望ですか。\n客：内外ともお願いします。\nスタッフ：はい、時間は30分ほどかかります。\n客：ここで待っていてもいいですか。\nスタッフ：はい、あちらに座ってお待ちください。\n客：ありがとうございます。", body_zh: "职员: 您想要哪种洗车？\n顾客: 请里外都洗一下。\n职员: 好的，大约需要三十分钟。\n顾客: 我可以在这里等吗？\n职员: 可以，请坐那边等。\n顾客: 谢谢。",
    questions: [
      { question_en: "What kind of car wash does the customer want?", question_ja: "お客さんはどんな洗車を希望していますか。", question_zh: "顾客想要哪种洗车？", options: ["Outside only","Inside only","Both inside and outside","Just a vacuum"], answerIndex: 2 },
      { question_en: "How long will it take?", question_ja: "どのくらい時間がかかりますか。", question_zh: "需要多长时间？", options: ["Ten minutes","Twenty minutes","Thirty minutes","One hour"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "도서관 대화",
    title_en: "At the library", title_ja: "図書館での会話", title_zh: "图书馆对话",
    body_kr: "이용자: 이 책을 빌리고 싶어요.\n사서: 회원 카드 있으세요?\n이용자: 네, 여기 있어요.\n사서: 이 책은 이 주일 동안 빌릴 수 있어요.\n이용자: 반납은 어디에 해요?\n사서: 정문 앞 반납함에 넣으세요.",
    body_en: "Patron: I'd like to borrow this book.\nLibrarian: Do you have a membership card?\nPatron: Yes, here it is.\nLibrarian: You can borrow this book for two weeks.\nPatron: Where do I return it?\nLibrarian: Put it in the return box in front of the main entrance.", body_ja: "利用者：この本を借りたいです。\n司書：会員カードはお持ちですか。\n利用者：はい、こちらです。\n司書：この本は2週間借りられます。\n利用者：返却はどこにすればいいですか。\n司書：正門前の返却ボックスに入れてください。", body_zh: "读者: 我想借这本书。\n馆员: 您有会员卡吗？\n读者: 有，给您。\n馆员: 这本书可以借两周。\n读者: 在哪里还书？\n馆员: 请放进正门前的还书箱。",
    questions: [
      { question_en: "How long can the patron borrow the book?", question_ja: "利用者はどのくらいの期間本を借りられますか。", question_zh: "读者可以借多久？", options: ["One week","Two weeks","One month","Three days"], answerIndex: 1 },
      { question_en: "Where should the book be returned?", question_ja: "本はどこに返却すればいいですか。", question_zh: "书应该还到哪里？", options: ["At the front desk","In the return box","By mail","To the librarian's office"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "공항 체크인",
    title_en: "Checking in at the airport", title_ja: "空港でのチェックイン", title_zh: "机场办理登机",
    body_kr: "직원: 여권과 항공권 보여 주세요.\n승객: 여기 있습니다.\n직원: 짐은 몇 개예요?\n승객: 캐리어 한 개 있어요.\n직원: 창가 자리와 통로 자리 중에 뭐가 좋으세요?\n승객: 창가 자리로 주세요.",
    body_en: "Staff: May I see your passport and ticket?\nPassenger: Here you go.\nStaff: How many bags do you have?\nPassenger: One suitcase.\nStaff: Would you prefer a window seat or an aisle seat?\nPassenger: I'll take the window seat, please.", body_ja: "職員：パスポートと航空券を見せてください。\n乗客：こちらです。\n職員：お荷物はいくつですか。\n乗客：スーツケースが一つあります。\n職員：窓側の席と通路側の席、どちらがよろしいですか。\n乗客：窓側の席をお願いします。", body_zh: "职员: 请出示护照和机票。\n乘客: 给您。\n职员: 您有几件行李？\n乘客: 一个行李箱。\n职员: 靠窗座位和靠走廊座位，您想要哪个？\n乘客: 请给我靠窗座位。",
    questions: [
      { question_en: "How many bags does the passenger have?", question_ja: "乗客は荷物をいくつ持っていますか。", question_zh: "乘客有几件行李？", options: ["None","One","Two","Three"], answerIndex: 1 },
      { question_en: "What seat does the passenger choose?", question_ja: "乗客はどの席を選びますか。", question_zh: "乘客选了哪个座位？", options: ["Aisle","Window","Middle","Doesn't matter"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "이삿짐센터와의 대화",
    title_en: "A conversation with the moving company", title_ja: "引っ越し業者との会話", title_zh: "和搬家公司的对话",
    body_kr: "고객: 이사 견적을 받고 싶어요.\n직원: 집이 몇 평이에요?\n고객: 스무 평 정도예요.\n직원: 짐이 많으세요?\n고객: 아니요, 많지 않아요.\n직원: 그럼 오십만 원 정도 나와요.",
    body_en: "Customer: I'd like to get a moving quote.\nStaff: How big is your home?\nCustomer: It's about 20 pyeong.\nStaff: Do you have a lot of belongings?\nCustomer: No, not a lot.\nStaff: Then it will cost around 500,000 won.", body_ja: "顧客：引っ越しの見積もりをお願いしたいです。\n職員：お住まいは何坪ですか。\n顧客：20坪くらいです。\n職員：荷物は多いですか。\n顧客：いいえ、多くありません。\n職員：それでは50万ウォンくらいになります。", body_zh: "客户: 我想要一份搬家报价。\n职员: 您家有多少坪？\n客户: 大约二十坪。\n职员: 行李多吗？\n客户: 不，不多。\n职员: 那大概是五十万韩元左右。",
    questions: [
      { question_en: "What is the customer asking for?", question_ja: "お客さんは何を求めていますか。", question_zh: "顾客在要求什么？", options: ["A repair","A moving quote","A cleaning service","A delivery"], answerIndex: 1 },
      { question_en: "How much will the move cost?", question_ja: "引っ越しの費用はどのくらいですか。", question_zh: "搬家费用大概多少？", options: ["300,000 won","500,000 won","700,000 won","1,000,000 won"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "저녁 메뉴 정하기",
    title_en: "Deciding on dinner", title_ja: "夕食のメニューを決める", title_zh: "决定晚餐菜单",
    body_kr: "남편: 오늘 저녁 뭐 먹을까?\n아내: 글쎄, 밖에서 먹을까?\n남편: 좋아. 어떤 음식 먹고 싶어?\n아내: 파스타 먹고 싶어.\n남편: 그럼 그 이탈리안 식당 갈까?\n아내: 응, 좋아. 예약할게.",
    body_en: "Husband: What should we eat for dinner tonight?\nWife: Hmm, shall we eat out?\nHusband: Sounds good. What kind of food do you want?\nWife: I want pasta.\nHusband: Then shall we go to that Italian restaurant?\nWife: Yes, sounds good. I'll make a reservation.", body_ja: "夫：今日の夕食、何食べようか。\n妻：そうね、外で食べようか。\n夫：いいね。どんな料理が食べたい？\n妻：パスタが食べたいな。\n夫：じゃあ、あのイタリアンレストランに行こうか。\n妻：うん、いいね。予約するね。", body_zh: "丈夫: 今天晚饭吃什么？\n妻子: 嗯，出去吃怎么样？\n丈夫: 好啊，你想吃什么？\n妻子: 我想吃意大利面。\n丈夫: 那要不要去那家意大利餐厅？\n妻子: 嗯，好啊，我来预订。",
    questions: [
      { question_en: "What does the wife want to eat?", question_ja: "妻は何を食べたいですか。", question_zh: "妻子想吃什么？", options: ["Pizza","Pasta","Sushi","Steak"], answerIndex: 1 },
      { question_en: "Who will make the reservation?", question_ja: "誰が予約をしますか。", question_zh: "谁来预订？", options: ["Husband","Wife","Both","Neither"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "회의 준비하기",
    title_en: "Preparing for a meeting", title_ja: "会議の準備をする", title_zh: "准备会议",
    body_kr: "이과장: 내일 회의 자료 다 준비됐어요?\n최대리: 거의 다 됐어요. 오늘 안에 끝낼게요.\n이과장: 발표는 몇 분 정도 할 거예요?\n최대리: 십 분 정도 생각하고 있어요.\n이과장: 좋아요. 자료 되면 저한테 보내 주세요.\n최대리: 네, 알겠습니다.",
    body_en: "Manager Lee: Are the materials for tomorrow's meeting all ready?\nAssistant Choi: Almost done. I'll finish today.\nManager Lee: How long will the presentation be?\nAssistant Choi: I'm thinking about ten minutes.\nManager Lee: Good. Send me the materials when they're ready.\nAssistant Choi: Okay, understood.", body_ja: "イ課長：明日の会議資料はもう準備できましたか。\nチェ主任：ほとんど終わりました。今日中に終わらせます。\nイ課長：発表は何分くらいの予定ですか。\nチェ主任：10分くらいを考えています。\nイ課長：いいですね。資料ができたら送ってください。\nチェ主任：はい、分かりました。", body_zh: "李科长: 明天开会的资料都准备好了吗？\n崔代理: 差不多了，今天之内会完成。\n李科长: 发表大概要多少分钟？\n崔代理: 我在想大概十分钟。\n李科长: 好，资料好了就发给我。\n崔代理: 好的，知道了。",
    questions: [
      { question_en: "When will the materials be finished?", question_ja: "資料はいつ完成しますか。", question_zh: "资料什么时候完成？", options: ["Tomorrow","Today","Next week","This weekend"], answerIndex: 1 },
      { question_en: "How long will the presentation be?", question_ja: "発表はどのくらいの長さですか。", question_zh: "发表大概多长时间？", options: ["Five minutes","Ten minutes","Twenty minutes","Thirty minutes"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "지민과의 약속 변경하기",
    title_en: "Changing plans with Jimin", title_ja: "ジミンとの約束を変更する", title_zh: "和智敏改约",
    body_kr: "지민: 미안한데, 오늘 저녁 약속 못 지킬 것 같아.\n저: 왜? 무슨 일 있어?\n지민: 회사에 일이 갑자기 생겼어.\n저: 괜찮아. 그럼 다음에 만나자.\n지민: 미안해. 내가 다음에 저녁 살게.\n저: 알겠어, 다음 주에 연락해.",
    body_en: "Jimin: Sorry, but I don't think I can make our dinner plan tonight.\nMe: Why? Did something happen?\nJimin: Something suddenly came up at work.\nMe: That's okay. Let's meet another time then.\nJimin: Sorry. I'll buy you dinner next time.\nMe: Okay, contact me next week.", body_ja: "ジミン：ごめん、今日の夜の約束、守れなさそう。\n私：どうして？何かあったの？\nジミン：会社で急に用事ができたんだ。\n私：大丈夫だよ。じゃあ、また今度会おう。\nジミン：ごめんね。今度、夕食おごるよ。\n私：分かった、来週連絡してね。", body_zh: "智敏: 对不起，今晚的约好像去不了了。\n我: 为什么？出什么事了？\n智敏: 公司突然有事。\n我: 没关系，那我们下次再见吧。\n智敏: 对不起，下次我请你吃晚饭。\n我: 好的，下周联系我。",
    questions: [
      { question_en: "Why can't Jimin make the plan?", question_ja: "なぜジミンは約束を守れませんか。", question_zh: "智敏为什么不能赴约？", options: ["She's sick","Something came up at work","She forgot","She's traveling"], answerIndex: 1 },
      { question_en: "What does Jimin promise?", question_ja: "ジミンは何を約束しましたか。", question_zh: "智敏承诺了什么？", options: ["To call tomorrow","To buy dinner next time","To meet at a different place","Nothing"], answerIndex: 1 },
    ],
  },
];
