import type { RawPassage } from "./types";

export const READING_A1_DIALOGUE: RawPassage[] = [
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "카페에서 주문하기",
    title_en: "Ordering at a cafe",
    body_kr: "직원: 어서 오세요. 뭐 드릴까요?\n손님: 아메리카노 한 잔 주세요.\n직원: 따뜻한 거요, 아니면 아이스요?\n손님: 아이스로 주세요.\n직원: 네, 사천 원입니다.\n손님: 여기 있어요.",
    body_en: "Clerk: Welcome. What can I get you?\nCustomer: One Americano, please.\nClerk: Hot or iced?\nCustomer: Iced, please.\nClerk: Okay, that's 4,000 won.\nCustomer: Here you go.",
    questions: [
      { question_en: "What does the customer order?", options: ["Latte","Americano","Tea","Juice"], answerIndex: 1 },
      { question_en: "How much is the drink?", options: ["3,000 won","4,000 won","5,000 won","2,000 won"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "편의점 대화",
    title_en: "At the convenience store",
    body_kr: "손님: 물 한 병 있어요?\n직원: 네, 저기 냉장고에 있어요.\n손님: 감사합니다. 이것도 계산해 주세요.\n직원: 봉투도 필요하세요?\n손님: 아니요, 괜찮아요.\n직원: 이천 원입니다.",
    body_en: "Customer: Do you have a bottle of water?\nClerk: Yes, it's in the fridge over there.\nCustomer: Thank you. Please ring this up too.\nClerk: Do you need a bag too?\nCustomer: No, that's okay.\nClerk: That's 2,000 won.",
    questions: [
      { question_en: "What does the customer buy?", options: ["Coffee","Water","Snack","Juice"], answerIndex: 1 },
      { question_en: "Does the customer need a bag?", options: ["Yes","No","Two bags","Doesn't say"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "버스에서",
    title_en: "On the bus",
    body_kr: "승객: 기사님, 시청역에 가요?\n기사님: 네, 다음다음 정류장이에요.\n승객: 알겠습니다. 감사합니다.\n기사님: 내릴 때 말씀하세요.\n승객: 저 여기서 내릴게요.\n기사님: 네, 조심히 가세요.",
    body_en: "Passenger: Excuse me, does this go to City Hall Station?\nDriver: Yes, it's two stops from here.\nPassenger: I see. Thank you.\nDriver: Let me know when you want to get off.\nPassenger: I'll get off here.\nDriver: Okay, take care.",
    questions: [
      { question_en: "Where does the passenger want to go?", options: ["Bus terminal","City Hall Station","Airport","Market"], answerIndex: 1 },
      { question_en: "How many stops away is it?", options: ["One","Two","Three","Four"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "택시 타기",
    title_en: "Taking a taxi",
    body_kr: "기사님: 어디로 가세요?\n승객: 강남역으로 가 주세요.\n기사님: 네, 알겠습니다.\n승객: 시간이 얼마나 걸려요?\n기사님: 이십 분쯤 걸려요.\n승객: 네, 감사합니다.",
    body_en: "Driver: Where would you like to go?\nPassenger: Please take me to Gangnam Station.\nDriver: Okay, sure.\nPassenger: How long will it take?\nDriver: About twenty minutes.\nPassenger: Okay, thank you.",
    questions: [
      { question_en: "Where does the passenger want to go?", options: ["Gangnam Station","City Hall","Airport","Hospital"], answerIndex: 0 },
      { question_en: "How long will the ride take?", options: ["Ten minutes","Twenty minutes","Thirty minutes","One hour"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "병원 진료",
    title_en: "A visit to the doctor",
    body_kr: "의사: 어디가 아프세요?\n환자: 목이 아프고 기침이 나요.\n의사: 열도 있어요?\n환자: 네, 조금 있어요.\n의사: 약을 드릴게요. 푹 쉬세요.\n환자: 네, 감사합니다.",
    body_en: "Doctor: What's bothering you?\nPatient: My throat hurts and I have a cough.\nDoctor: Do you have a fever too?\nPatient: Yes, a little.\nDoctor: I'll give you some medicine. Please rest well.\nPatient: Okay, thank you.",
    questions: [
      { question_en: "What symptoms does the patient have?", options: ["Headache and fever","Sore throat and cough","Stomachache","Toothache"], answerIndex: 1 },
      { question_en: "What does the doctor tell the patient to do?", options: ["Exercise","Rest well","Drink coffee","Go to the hospital"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "약국에서",
    title_en: "At the pharmacy",
    body_kr: "손님: 두통약 있어요?\n약사: 네, 여기 있어요.\n손님: 하루에 몇 번 먹어요?\n약사: 하루에 세 번 드세요.\n손님: 알겠습니다. 얼마예요?\n약사: 오천 원입니다.",
    body_en: "Customer: Do you have headache medicine?\nPharmacist: Yes, here it is.\nCustomer: How many times a day should I take it?\nPharmacist: Take it three times a day.\nCustomer: I see. How much is it?\nPharmacist: It's 5,000 won.",
    questions: [
      { question_en: "What medicine does the customer buy?", options: ["Cough medicine","Headache medicine","Stomach medicine","Cold medicine"], answerIndex: 1 },
      { question_en: "How often should the customer take it?", options: ["Once a day","Twice a day","Three times a day","Four times a day"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "지민과 통화",
    title_en: "A phone call with Jimin",
    body_kr: "지민: 여보세요? 지금 통화 괜찮아?\n저: 응, 괜찮아. 무슨 일이야?\n지민: 이번 주말에 시간 있어?\n저: 응, 토요일에 시간 있어.\n지민: 그럼 같이 영화 볼까?\n저: 좋아! 몇 시에 만날까?",
    body_en: "Jimin: Hello? Is now a good time to talk?\nMe: Yes, it's fine. What's up?\nJimin: Are you free this weekend?\nMe: Yes, I'm free on Saturday.\nJimin: Then shall we watch a movie together?\nMe: Sounds good! What time should we meet?",
    questions: [
      { question_en: "When is the narrator free?", options: ["Friday","Saturday","Sunday","Monday"], answerIndex: 1 },
      { question_en: "What does Jimin suggest doing?", options: ["Having dinner","Watching a movie","Going shopping","Studying together"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "길 물어보기",
    title_en: "Asking for directions",
    body_kr: "저: 실례합니다. 이 근처에 은행이 있어요?\n행인: 네, 저기 사거리에서 오른쪽으로 가세요.\n저: 여기서 멀어요?\n행인: 아니요, 걸어서 오 분쯤 걸려요.\n저: 감사합니다.\n행인: 네, 조심히 가세요.",
    body_en: "Me: Excuse me. Is there a bank near here?\nPasserby: Yes, turn right at that intersection.\nMe: Is it far from here?\nPasserby: No, it takes about five minutes on foot.\nMe: Thank you.\nPasserby: You're welcome, take care.",
    questions: [
      { question_en: "What is the narrator looking for?", options: ["A hospital","A bank","A pharmacy","A station"], answerIndex: 1 },
      { question_en: "How far is it?", options: ["About five minutes","About ten minutes","About one hour","Very far"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "식당에서 주문하기",
    title_en: "Ordering at a restaurant",
    body_kr: "직원: 몇 분이세요?\n손님: 두 명이에요.\n직원: 이쪽으로 앉으세요. 메뉴 여기 있습니다.\n손님: 김치찌개 두 개 주세요.\n직원: 네, 음료수도 필요하세요?\n손님: 물만 주세요.",
    body_en: "Clerk: How many people?\nCustomer: Two people.\nClerk: Please sit here. Here's the menu.\nCustomer: Two kimchi stews, please.\nClerk: Sure, do you need drinks too?\nCustomer: Just water, please.",
    questions: [
      { question_en: "How many people are dining?", options: ["One","Two","Three","Four"], answerIndex: 1 },
      { question_en: "What does the customer order to drink?", options: ["Soda","Juice","Water","Tea"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "헬스장 등록하기",
    title_en: "Signing up at the gym",
    body_kr: "직원: 안녕하세요. 어떻게 오셨어요?\n회원: 헬스장 등록하고 싶어요.\n직원: 한 달 등록하시겠어요, 세 달 등록하시겠어요?\n회원: 세 달로 할게요.\n직원: 네, 여기에 이름과 전화번호를 써 주세요.\n회원: 네, 알겠습니다.",
    body_en: "Staff: Hello. How can I help you?\nMember: I'd like to sign up for the gym.\nStaff: Would you like a one-month or three-month membership?\nMember: I'll do three months.\nStaff: Okay, please write your name and phone number here.\nMember: Sure, got it.",
    questions: [
      { question_en: "What does the person want to do?", options: ["Cancel a membership","Sign up for the gym","Ask about a trainer","Return equipment"], answerIndex: 1 },
      { question_en: "How long a membership does the person choose?", options: ["One month","Two months","Three months","Six months"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "은행에서 계좌 만들기",
    title_en: "Opening a bank account",
    body_kr: "손님: 계좌를 만들고 싶어요.\n은행원: 신분증 있으세요?\n손님: 네, 여기 있어요.\n은행원: 이 서류를 작성해 주세요.\n손님: 네, 다 썼어요.\n은행원: 감사합니다. 카드는 다음 주에 나와요.",
    body_en: "Customer: I'd like to open an account.\nBank teller: Do you have an ID?\nCustomer: Yes, here it is.\nBank teller: Please fill out this form.\nCustomer: Okay, I'm done.\nBank teller: Thank you. Your card will be ready next week.",
    questions: [
      { question_en: "What does the customer want to do?", options: ["Withdraw money","Open an account","Exchange currency","Apply for a loan"], answerIndex: 1 },
      { question_en: "When will the card be ready?", options: ["Tomorrow","Next week","Next month","Today"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "미용실에서",
    title_en: "At the hair salon",
    body_kr: "미용사: 오늘 어떻게 해 드릴까요?\n손님: 머리를 좀 짧게 잘라 주세요.\n미용사: 얼마나 짧게요?\n손님: 어깨 정도로 해 주세요.\n미용사: 네, 파마도 하시겠어요?\n손님: 아니요, 자르기만 할게요.",
    body_en: "Hairdresser: What would you like today?\nCustomer: Please cut my hair a bit shorter.\nHairdresser: How short?\nCustomer: About shoulder length, please.\nHairdresser: Sure, would you like a perm too?\nCustomer: No, just a cut, please.",
    questions: [
      { question_en: "What does the customer want done?", options: ["A perm","A haircut","Hair coloring","Hair washing only"], answerIndex: 1 },
      { question_en: "How short does the customer want their hair?", options: ["Very short","Shoulder length","Chin length","No change"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "이웃과의 대화",
    title_en: "A conversation with a neighbor",
    body_kr: "이웃: 안녕하세요. 이사 오셨어요?\n저: 네, 지난주에 이사 왔어요.\n이웃: 반가워요. 저는 302호에 살아요.\n저: 저는 301호예요. 잘 부탁드려요.\n이웃: 혹시 필요한 거 있으면 말씀하세요.\n저: 감사합니다.",
    body_en: "Neighbor: Hello. Did you just move in?\nMe: Yes, I moved in last week.\nNeighbor: Nice to meet you. I live in unit 302.\nMe: I'm in unit 301. Nice to meet you too.\nNeighbor: If you need anything, just let me know.\nMe: Thank you.",
    questions: [
      { question_en: "When did the narrator move in?", options: ["Yesterday","Last week","Last month","Today"], answerIndex: 1 },
      { question_en: "What unit does the neighbor live in?", options: ["301","302","303","304"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "회사 동료와의 대화",
    title_en: "A conversation with a coworker",
    body_kr: "김대리: 오늘 회의 몇 시예요?\n박대리: 두 시예요. 회의실 3층이에요.\n김대리: 자료는 다 준비했어요?\n박대리: 네, 이메일로 보냈어요.\n김대리: 확인해 볼게요. 고마워요.\n박대리: 네, 이따가 봐요.",
    body_en: "Kim: What time is the meeting today?\nPark: It's at 2 o'clock. The meeting room is on the third floor.\nKim: Did you prepare all the materials?\nPark: Yes, I sent them by email.\nKim: I'll check them. Thanks.\nPark: Sure, see you later.",
    questions: [
      { question_en: "What time is the meeting?", options: ["1 o'clock","2 o'clock","3 o'clock","4 o'clock"], answerIndex: 1 },
      { question_en: "How did Park send the materials?", options: ["By hand","By email","By phone","By mail"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "부동산에서 집 구하기",
    title_en: "Looking for an apartment",
    body_kr: "손님: 원룸을 구하고 있어요.\n중개인: 보증금과 월세는 어느 정도 생각하세요?\n손님: 보증금 오백에 월세 오십이요.\n중개인: 마침 좋은 집이 있어요. 지금 보러 갈까요?\n손님: 네, 좋아요.\n중개인: 그럼 차로 같이 가요.",
    body_en: "Customer: I'm looking for a studio apartment.\nAgent: What deposit and monthly rent were you thinking of?\nCustomer: A 5 million won deposit and 500,000 won rent.\nAgent: There happens to be a good place. Shall we go see it now?\nCustomer: Yes, sounds good.\nAgent: Then let's go together by car.",
    questions: [
      { question_en: "What is the customer looking for?", options: ["A house","A studio apartment","An office","A store"], answerIndex: 1 },
      { question_en: "What does the agent suggest doing?", options: ["Calling later","Going to see the place now","Sending photos","Waiting a week"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "세탁소에서",
    title_en: "At the dry cleaner",
    body_kr: "손님: 이 재킷 좀 세탁해 주세요.\n직원: 네, 언제까지 필요하세요?\n손님: 금요일까지 필요해요.\n직원: 네, 목요일까지 해 드릴게요.\n손님: 가격은 얼마예요?\n직원: 만 원입니다.",
    body_en: "Customer: Please clean this jacket.\nClerk: Sure, when do you need it by?\nCustomer: I need it by Friday.\nClerk: Okay, I'll have it done by Thursday.\nCustomer: How much does it cost?\nClerk: It's 10,000 won.",
    questions: [
      { question_en: "What does the customer bring in?", options: ["A coat","A jacket","A shirt","Pants"], answerIndex: 1 },
      { question_en: "When will the item be ready?", options: ["Wednesday","Thursday","Friday","Saturday"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "서점에서 책 찾기",
    title_en: "Finding a book at the bookstore",
    body_kr: "손님: 한국어 교재를 찾고 있어요.\n직원: 초급이세요, 중급이세요?\n손님: 초급이요.\n직원: 이쪽 코너에 있어요. 같이 가 드릴게요.\n손님: 감사합니다. 이 책으로 할게요.\n직원: 네, 계산 도와드릴게요.",
    body_en: "Customer: I'm looking for a Korean textbook.\nClerk: Beginner or intermediate level?\nCustomer: Beginner level.\nClerk: They're in this section. Let me show you.\nCustomer: Thank you. I'll take this book.\nClerk: Okay, let me ring that up for you.",
    questions: [
      { question_en: "What kind of book is the customer looking for?", options: ["A novel","A Korean textbook","A cookbook","A magazine"], answerIndex: 1 },
      { question_en: "What level does the customer want?", options: ["Beginner","Intermediate","Advanced","Doesn't say"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "우체국에서 소포 보내기",
    title_en: "Sending a package at the post office",
    body_kr: "손님: 이 소포를 미국으로 보내고 싶어요.\n직원: 무게를 재 볼게요. 이 킬로그램이네요.\n손님: 얼마나 빨리 도착해요?\n직원: 항공으로 보내면 일주일 정도 걸려요.\n손님: 그럼 항공으로 보내 주세요.\n직원: 네, 삼만 원입니다.",
    body_en: "Customer: I'd like to send this package to the US.\nClerk: Let me weigh it. It's two kilograms.\nCustomer: How fast will it arrive?\nClerk: If you send it by air, it takes about a week.\nCustomer: Then please send it by air.\nClerk: Okay, that's 30,000 won.",
    questions: [
      { question_en: "Where is the package going?", options: ["Canada","The US","Japan","France"], answerIndex: 1 },
      { question_en: "How is the package sent?", options: ["By ship","By air","By truck","By train"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "지민과 약속 잡기",
    title_en: "Making plans with Jimin",
    body_kr: "지민: 이번 주 금요일 저녁에 뭐 해?\n저: 아직 특별한 계획 없어.\n지민: 그럼 새로 생긴 식당에 갈래?\n저: 좋아! 몇 시에 만날까?\n지민: 일곱 시에 역 앞에서 만나자.\n저: 알겠어, 그때 봐!",
    body_en: "Jimin: What are you doing this Friday evening?\nMe: I don't have any special plans yet.\nJimin: Then do you want to go to the new restaurant?\nMe: Sounds good! What time should we meet?\nJimin: Let's meet in front of the station at 7.\nMe: Okay, see you then!",
    questions: [
      { question_en: "What does Jimin suggest?", options: ["Watching a movie","Going to a new restaurant","Going shopping","Going hiking"], answerIndex: 1 },
      { question_en: "Where will they meet?", options: ["At Jimin's house","In front of the station","At the restaurant","At my house"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "호텔 체크인",
    title_en: "Checking in at a hotel",
    body_kr: "직원: 어서 오세요. 예약하셨어요?\n손님: 네, 이지은으로 예약했어요.\n직원: 네, 확인했습니다. 여권 좀 보여 주세요.\n손님: 여기 있어요.\n직원: 방은 5층 502호입니다.\n손님: 감사합니다.",
    body_en: "Staff: Welcome. Do you have a reservation?\nGuest: Yes, it's under Lee Jieun.\nStaff: Yes, I found it. Could I see your passport?\nGuest: Here it is.\nStaff: Your room is on the 5th floor, room 502.\nGuest: Thank you.",
    questions: [
      { question_en: "What name is the reservation under?", options: ["Lee Jieun","Park Jimin","Lee Minho","Choi Yuna"], answerIndex: 0 },
      { question_en: "What room number is the guest given?", options: ["402","502","503","302"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "옷가게에서",
    title_en: "At the clothing store",
    body_kr: "손님: 이 셔츠 좀 입어 봐도 돼요?\n직원: 네, 탈의실은 저쪽이에요.\n손님: 사이즈가 좀 큰 것 같아요.\n직원: 작은 사이즈로 가져다 드릴게요.\n손님: 감사합니다. 이걸로 살게요.\n직원: 네, 계산해 드릴게요.",
    body_en: "Customer: Can I try on this shirt?\nClerk: Sure, the fitting room is over there.\nCustomer: The size seems a bit big.\nClerk: I'll bring you a smaller size.\nCustomer: Thank you. I'll buy this one.\nClerk: Okay, let me ring it up.",
    questions: [
      { question_en: "What does the customer try on?", options: ["Pants","A shirt","A jacket","Shoes"], answerIndex: 1 },
      { question_en: "What was the problem with the first size?", options: ["Too small","Too big","Wrong color","Too expensive"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "안경점에서",
    title_en: "At the optical shop",
    body_kr: "손님: 안경을 새로 맞추고 싶어요.\n직원: 시력 검사부터 해 드릴게요.\n손님: 네, 알겠습니다.\n직원: 시력이 조금 나빠지셨네요.\n손님: 안경테는 이걸로 할게요.\n직원: 네, 다음 주에 찾으러 오세요.",
    body_en: "Customer: I'd like to get new glasses made.\nStaff: Let's start with an eye exam.\nCustomer: Okay, sure.\nStaff: Your eyesight has gotten a little worse.\nCustomer: I'll go with this frame.\nStaff: Okay, please come pick them up next week.",
    questions: [
      { question_en: "What does the customer want?", options: ["Contact lenses","New glasses","Sunglasses","A repair"], answerIndex: 1 },
      { question_en: "When can the customer pick up the glasses?", options: ["Tomorrow","Next week","Next month","Today"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "주유소에서",
    title_en: "At the gas station",
    body_kr: "직원: 어서 오세요. 얼마나 넣어 드릴까요?\n손님: 오만 원어치 넣어 주세요.\n직원: 네, 카드로 계산하세요, 현금으로 계산하세요?\n손님: 카드로 할게요.\n직원: 네, 다 넣었습니다.\n손님: 감사합니다.",
    body_en: "Staff: Welcome. How much gas would you like?\nCustomer: Please put in 50,000 won worth.\nStaff: Sure, will you pay by card or cash?\nCustomer: I'll pay by card.\nStaff: Okay, it's all filled up.\nCustomer: Thank you.",
    questions: [
      { question_en: "How much gas does the customer buy?", options: ["30,000 won worth","50,000 won worth","100,000 won worth","A full tank"], answerIndex: 1 },
      { question_en: "How does the customer pay?", options: ["Cash","Card","Mobile pay","Check"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "사진관에서 증명사진 찍기",
    title_en: "Taking an ID photo at the studio",
    body_kr: "손님: 여권 사진을 찍고 싶어요.\n사진사: 네, 이쪽 의자에 앉으세요.\n손님: 옷은 이대로 괜찮아요?\n사진사: 네, 괜찮아요. 정면을 보고 웃지 마세요.\n손님: 언제 찾으러 와요?\n사진사: 삼십 분 후에 오세요.",
    body_en: "Customer: I'd like to take a passport photo.\nPhotographer: Sure, please sit in this chair.\nCustomer: Is my outfit okay as it is?\nPhotographer: Yes, that's fine. Look straight ahead and don't smile.\nCustomer: When should I come pick it up?\nPhotographer: Please come back in thirty minutes.",
    questions: [
      { question_en: "What kind of photo does the customer want?", options: ["A wedding photo","A passport photo","A family photo","A pet photo"], answerIndex: 1 },
      { question_en: "When should the customer return?", options: ["In ten minutes","In thirty minutes","In one hour","Tomorrow"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "마트 계산대에서",
    title_en: "At the supermarket checkout",
    body_kr: "직원: 봉투 필요하세요?\n손님: 네, 하나 주세요.\n직원: 포인트 카드 있으세요?\n손님: 아니요, 없어요.\n직원: 그럼 카드로 계산하시겠어요?\n손님: 네, 카드로 할게요.",
    body_en: "Clerk: Do you need a bag?\nCustomer: Yes, one please.\nClerk: Do you have a points card?\nCustomer: No, I don't.\nClerk: Then will you pay by card?\nCustomer: Yes, I'll pay by card.",
    questions: [
      { question_en: "Does the customer need a bag?", options: ["No","Yes, one","Yes, two","Doesn't say"], answerIndex: 1 },
      { question_en: "Does the customer have a points card?", options: ["Yes","No","Forgot it","Left it at home"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "치과 진료",
    title_en: "A visit to the dentist",
    body_kr: "의사: 어디가 아프세요?\n환자: 어금니가 계속 아파요.\n의사: 언제부터 아팠어요?\n환자: 삼 일 전부터요.\n의사: 사진을 찍어 볼게요.\n환자: 네, 알겠습니다.",
    body_en: "Dentist: What's bothering you?\nPatient: My back tooth keeps hurting.\nDentist: Since when has it hurt?\nPatient: Since three days ago.\nDentist: I'll take an X-ray.\nPatient: Okay, sure.",
    questions: [
      { question_en: "What is hurting the patient?", options: ["A front tooth","A back tooth","The gums","The jaw"], answerIndex: 1 },
      { question_en: "Since when has it been hurting?", options: ["One day","Three days","One week","One month"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "면접 보기",
    title_en: "A job interview",
    body_kr: "면접관: 이 회사에 왜 지원하셨어요?\n지원자: 이 분야에 관심이 많아서 지원했습니다.\n면접관: 경력이 있으세요?\n지원자: 네, 삼 년 정도 있습니다.\n면접관: 언제부터 일할 수 있어요?\n지원자: 다음 달부터 가능합니다.",
    body_en: "Interviewer: Why did you apply to this company?\nApplicant: I applied because I'm very interested in this field.\nInterviewer: Do you have experience?\nApplicant: Yes, about three years.\nInterviewer: When can you start working?\nApplicant: I can start next month.",
    questions: [
      { question_en: "How much experience does the applicant have?", options: ["One year","Two years","Three years","Five years"], answerIndex: 2 },
      { question_en: "When can the applicant start?", options: ["This week","Next week","Next month","Next year"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "트레이너와 상담하기",
    title_en: "Consulting with a personal trainer",
    body_kr: "트레이너: 운동 목표가 뭐예요?\n회원: 살을 좀 빼고 싶어요.\n트레이너: 일주일에 몇 번 운동할 수 있어요?\n회원: 세 번 정도 가능해요.\n트레이너: 그럼 월, 수, 금으로 계획을 짜요.\n회원: 네, 좋아요.",
    body_en: "Trainer: What's your fitness goal?\nMember: I'd like to lose some weight.\nTrainer: How many times a week can you work out?\nMember: About three times.\nTrainer: Then let's plan for Monday, Wednesday, and Friday.\nMember: Okay, sounds good.",
    questions: [
      { question_en: "What is the member's goal?", options: ["Gain muscle","Lose weight","Improve flexibility","Run faster"], answerIndex: 1 },
      { question_en: "How many days a week will the member work out?", options: ["Two","Three","Four","Five"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "카페에서 지민 만나기",
    title_en: "Meeting Jimin at a cafe",
    body_kr: "저: 지민아, 여기야!\n지민: 오래 기다렸어? 미안해, 늦었지.\n저: 아니야, 나도 방금 왔어.\n지민: 뭐 마실래? 내가 살게.\n저: 그럼 카페라테 마실게.\n지민: 알겠어, 잠깐만 기다려.",
    body_en: "Me: Jimin, over here!\nJimin: Did you wait long? Sorry I'm late.\nMe: No, I just got here too.\nJimin: What do you want to drink? I'll buy.\nMe: Then I'll have a cafe latte.\nJimin: Okay, wait just a moment.",
    questions: [
      { question_en: "Who is buying the drinks?", options: ["Me","Jimin","They split it","Neither"], answerIndex: 1 },
      { question_en: "What drink does the narrator choose?", options: ["Americano","Cafe latte","Tea","Juice"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "전화로 식당 예약하기",
    title_en: "Making a restaurant reservation by phone",
    body_kr: "직원: 안녕하세요, 예약 도와드릴까요?\n손님: 네, 오늘 저녁 일곱 시에 두 명 예약하고 싶어요.\n직원: 죄송하지만 일곱 시는 자리가 없어요.\n손님: 그럼 여덟 시는 어때요?\n직원: 네, 여덟 시는 가능합니다.\n손님: 그럼 그 시간으로 예약할게요.",
    body_en: "Staff: Hello, may I help you with a reservation?\nCustomer: Yes, I'd like to book a table for two at 7 tonight.\nStaff: I'm sorry, but there's no table at 7.\nCustomer: Then how about 8?\nStaff: Yes, 8 is available.\nCustomer: Then I'll book for that time.",
    questions: [
      { question_en: "How many people is the reservation for?", options: ["One","Two","Three","Four"], answerIndex: 1 },
      { question_en: "What time is the final reservation?", options: ["Six","Seven","Eight","Nine"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "빵집에서",
    title_en: "At the bakery",
    body_kr: "손님: 이 크루아상 얼마예요?\n직원: 삼천 원이에요.\n손님: 두 개 주세요. 그리고 식빵도 하나 주세요.\n직원: 네, 다른 건 필요 없으세요?\n손님: 네, 그거면 돼요.\n직원: 다 합쳐서 만 원입니다.",
    body_en: "Customer: How much is this croissant?\nClerk: It's 3,000 won.\nCustomer: Two of them, please. And one loaf of bread too.\nClerk: Sure, do you need anything else?\nCustomer: No, that's all.\nClerk: That's 10,000 won in total.",
    questions: [
      { question_en: "How many croissants does the customer buy?", options: ["One","Two","Three","Four"], answerIndex: 1 },
      { question_en: "What is the total price?", options: ["5,000 won","8,000 won","10,000 won","12,000 won"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "꽃집에서",
    title_en: "At the flower shop",
    body_kr: "손님: 어머니 생신 선물로 꽃을 사고 싶어요.\n직원: 어떤 색을 좋아하세요?\n손님: 분홍색을 좋아하세요.\n직원: 그럼 이 장미 어때요?\n손님: 예쁘네요. 열 송이 주세요.\n직원: 네, 포장해 드릴게요.",
    body_en: "Customer: I'd like to buy flowers for my mother's birthday.\nClerk: What color does she like?\nCustomer: She likes pink.\nClerk: Then how about these roses?\nCustomer: They're pretty. Ten of them, please.\nClerk: Sure, I'll wrap them for you.",
    questions: [
      { question_en: "Who are the flowers for?", options: ["A friend","The customer's mother","A coworker","A neighbor"], answerIndex: 1 },
      { question_en: "What color flowers does the customer choose?", options: ["White","Pink","Red","Yellow"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "아파트 관리실에서",
    title_en: "At the apartment management office",
    body_kr: "주민: 저희 집 수도에서 물이 새요.\n관리인: 언제부터 그랬어요?\n주민: 어제 저녁부터요.\n관리인: 오늘 오후에 사람을 보낼게요.\n주민: 몇 시쯤 올 수 있어요?\n관리인: 세 시쯤 갈 거예요.",
    body_en: "Resident: There's a water leak from my faucet.\nManager: Since when has it been like that?\nResident: Since last night.\nManager: I'll send someone this afternoon.\nResident: What time can they come?\nManager: They'll come around 3 o'clock.",
    questions: [
      { question_en: "What is the problem?", options: ["No hot water","A water leak","Broken heater","Noisy pipes"], answerIndex: 1 },
      { question_en: "When will someone come to fix it?", options: ["This morning","This afternoon","Tomorrow","Next week"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "세차장에서",
    title_en: "At the car wash",
    body_kr: "직원: 어떤 세차를 원하세요?\n손님: 안팎으로 다 해 주세요.\n직원: 네, 시간이 삼십 분 정도 걸려요.\n손님: 여기서 기다려도 돼요?\n직원: 네, 저기 앉아서 기다리세요.\n손님: 감사합니다.",
    body_en: "Staff: What kind of wash would you like?\nCustomer: Please do both inside and outside.\nStaff: Okay, it'll take about thirty minutes.\nCustomer: Can I wait here?\nStaff: Yes, please have a seat over there and wait.\nCustomer: Thank you.",
    questions: [
      { question_en: "What kind of car wash does the customer want?", options: ["Outside only","Inside only","Both inside and outside","Just a vacuum"], answerIndex: 2 },
      { question_en: "How long will it take?", options: ["Ten minutes","Twenty minutes","Thirty minutes","One hour"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "도서관 대화",
    title_en: "At the library",
    body_kr: "이용자: 이 책을 빌리고 싶어요.\n사서: 회원 카드 있으세요?\n이용자: 네, 여기 있어요.\n사서: 이 책은 이 주일 동안 빌릴 수 있어요.\n이용자: 반납은 어디에 해요?\n사서: 정문 앞 반납함에 넣으세요.",
    body_en: "Patron: I'd like to borrow this book.\nLibrarian: Do you have a membership card?\nPatron: Yes, here it is.\nLibrarian: You can borrow this book for two weeks.\nPatron: Where do I return it?\nLibrarian: Put it in the return box in front of the main entrance.",
    questions: [
      { question_en: "How long can the patron borrow the book?", options: ["One week","Two weeks","One month","Three days"], answerIndex: 1 },
      { question_en: "Where should the book be returned?", options: ["At the front desk","In the return box","By mail","To the librarian's office"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "공항 체크인",
    title_en: "Checking in at the airport",
    body_kr: "직원: 여권과 항공권 보여 주세요.\n승객: 여기 있습니다.\n직원: 짐은 몇 개예요?\n승객: 캐리어 한 개 있어요.\n직원: 창가 자리와 통로 자리 중에 뭐가 좋으세요?\n승객: 창가 자리로 주세요.",
    body_en: "Staff: May I see your passport and ticket?\nPassenger: Here you go.\nStaff: How many bags do you have?\nPassenger: One suitcase.\nStaff: Would you prefer a window seat or an aisle seat?\nPassenger: I'll take the window seat, please.",
    questions: [
      { question_en: "How many bags does the passenger have?", options: ["None","One","Two","Three"], answerIndex: 1 },
      { question_en: "What seat does the passenger choose?", options: ["Aisle","Window","Middle","Doesn't matter"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "이삿짐센터와의 대화",
    title_en: "A conversation with the moving company",
    body_kr: "고객: 이사 견적을 받고 싶어요.\n직원: 집이 몇 평이에요?\n고객: 스무 평 정도예요.\n직원: 짐이 많으세요?\n고객: 아니요, 많지 않아요.\n직원: 그럼 오십만 원 정도 나와요.",
    body_en: "Customer: I'd like to get a moving quote.\nStaff: How big is your home?\nCustomer: It's about 20 pyeong.\nStaff: Do you have a lot of belongings?\nCustomer: No, not a lot.\nStaff: Then it will cost around 500,000 won.",
    questions: [
      { question_en: "What is the customer asking for?", options: ["A repair","A moving quote","A cleaning service","A delivery"], answerIndex: 1 },
      { question_en: "How much will the move cost?", options: ["300,000 won","500,000 won","700,000 won","1,000,000 won"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "저녁 메뉴 정하기",
    title_en: "Deciding on dinner",
    body_kr: "남편: 오늘 저녁 뭐 먹을까?\n아내: 글쎄, 밖에서 먹을까?\n남편: 좋아. 어떤 음식 먹고 싶어?\n아내: 파스타 먹고 싶어.\n남편: 그럼 그 이탈리안 식당 갈까?\n아내: 응, 좋아. 예약할게.",
    body_en: "Husband: What should we eat for dinner tonight?\nWife: Hmm, shall we eat out?\nHusband: Sounds good. What kind of food do you want?\nWife: I want pasta.\nHusband: Then shall we go to that Italian restaurant?\nWife: Yes, sounds good. I'll make a reservation.",
    questions: [
      { question_en: "What does the wife want to eat?", options: ["Pizza","Pasta","Sushi","Steak"], answerIndex: 1 },
      { question_en: "Who will make the reservation?", options: ["Husband","Wife","Both","Neither"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "회의 준비하기",
    title_en: "Preparing for a meeting",
    body_kr: "이과장: 내일 회의 자료 다 준비됐어요?\n최대리: 거의 다 됐어요. 오늘 안에 끝낼게요.\n이과장: 발표는 몇 분 정도 할 거예요?\n최대리: 십 분 정도 생각하고 있어요.\n이과장: 좋아요. 자료 되면 저한테 보내 주세요.\n최대리: 네, 알겠습니다.",
    body_en: "Manager Lee: Are the materials for tomorrow's meeting all ready?\nAssistant Choi: Almost done. I'll finish today.\nManager Lee: How long will the presentation be?\nAssistant Choi: I'm thinking about ten minutes.\nManager Lee: Good. Send me the materials when they're ready.\nAssistant Choi: Okay, understood.",
    questions: [
      { question_en: "When will the materials be finished?", options: ["Tomorrow","Today","Next week","This weekend"], answerIndex: 1 },
      { question_en: "How long will the presentation be?", options: ["Five minutes","Ten minutes","Twenty minutes","Thirty minutes"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "dialogue",
    title_kr: "지민과의 약속 변경하기",
    title_en: "Changing plans with Jimin",
    body_kr: "지민: 미안한데, 오늘 저녁 약속 못 지킬 것 같아.\n저: 왜? 무슨 일 있어?\n지민: 회사에 일이 갑자기 생겼어.\n저: 괜찮아. 그럼 다음에 만나자.\n지민: 미안해. 내가 다음에 저녁 살게.\n저: 알겠어, 다음 주에 연락해.",
    body_en: "Jimin: Sorry, but I don't think I can make our dinner plan tonight.\nMe: Why? Did something happen?\nJimin: Something suddenly came up at work.\nMe: That's okay. Let's meet another time then.\nJimin: Sorry. I'll buy you dinner next time.\nMe: Okay, contact me next week.",
    questions: [
      { question_en: "Why can't Jimin make the plan?", options: ["She's sick","Something came up at work","She forgot","She's traveling"], answerIndex: 1 },
      { question_en: "What does Jimin promise?", options: ["To call tomorrow","To buy dinner next time","To meet at a different place","Nothing"], answerIndex: 1 },
    ],
  },
];
