import type { RawPassage } from "./types";

export const READING_A1_NOTICE: RawPassage[] = [
  {
    level: "A1",
    genre: "notice",
    title_kr: "카페 영업시간",
    title_en: "Cafe hours", title_ja: "カフェの営業時間", title_zh: "咖啡馆营业时间", title_vi: "Giờ mở cửa quán cà phê", title_es: "Horario del café",
    body_kr: "영업시간 안내\n평일 오전 8시부터 오후 9시까지\n주말 오전 10시부터 오후 6시까지\n월요일은 쉽니다.",
    body_en: "Business hours notice\nWeekdays from 8 AM to 9 PM\nWeekends from 10 AM to 6 PM\nClosed on Mondays.", body_ja: "営業時間のご案内\n平日 午前8時から午後9時まで\n週末 午前10時から午後6時まで\n月曜日は定休日です。", body_zh: "营业时间通知\n工作日上午8点至晚上9点\n周末上午10点至晚上6点\n周一休息。", body_vi: "Thông báo giờ mở cửa\nNgày thường từ 8 giờ sáng đến 9 giờ tối\nCuối tuần từ 10 giờ sáng đến 6 giờ tối\nNghỉ vào thứ Hai.", body_es: "Aviso de horario de atención\nDe lunes a viernes de 8 a.m. a 9 p.m.\nFines de semana de 10 a.m. a 6 p.m.\nCerrado los lunes.",
    questions: [
      { question_en: "What time does the cafe open on weekdays?", question_ja: "平日はカフェは何時に開店しますか。", question_zh: "咖啡馆工作日几点开门？", question_vi: "Quán cà phê mở cửa lúc mấy giờ vào ngày thường?", question_es: "¿A qué hora abre el café los días de semana?", options: ["7 AM", "8 AM", "9 AM", "10 AM"], answerIndex: 1 },
      { question_en: "Which day is the cafe closed?", question_ja: "カフェは何曜日が定休日ですか。", question_zh: "咖啡馆星期几休息？", question_vi: "Quán cà phê nghỉ vào ngày nào?", question_es: "¿Qué día cierra el café?", options: ["Sunday", "Saturday", "Monday", "Friday"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "정기 휴무 안내",
    title_en: "Regular closing day notice", title_ja: "定休日のお知らせ", title_zh: "定期休息日通知", title_vi: "Thông báo ngày nghỉ định kỳ", title_es: "Aviso de día de descanso regular",
    body_kr: "안내 말씀 드립니다.\n저희 가게는 매주 화요일에 쉽니다.\n다른 요일에는 정상 영업합니다.\n감사합니다.",
    body_en: "We would like to inform you.\nOur store is closed every Tuesday.\nOn other days, we are open as usual.\nThank you.", body_ja: "お知らせいたします。\n当店は毎週火曜日が定休日です。\nそれ以外の曜日は通常通り営業しております。\nありがとうございます。", body_zh: "通知如下。\n本店每周二休息。\n其他日子正常营业。\n谢谢。", body_vi: "Xin thông báo.\nCửa hàng chúng tôi nghỉ vào thứ Ba hàng tuần.\nCác ngày khác mở cửa bình thường.\nXin cảm ơn.", body_es: "Le informamos lo siguiente.\nNuestra tienda cierra todos los martes.\nLos demás días abrimos con normalidad.\nGracias.",
    questions: [
      { question_en: "Which day is the store closed every week?", question_ja: "このお店は毎週何曜日が休みですか。", question_zh: "这家店每周几休息？", question_vi: "Cửa hàng nghỉ ngày nào hàng tuần?", question_es: "¿Qué día cierra la tienda cada semana?", options: ["Monday", "Wednesday", "Tuesday", "Sunday"], answerIndex: 2 },
      { question_en: "What happens on other days?", question_ja: "他の曜日はどうなりますか。", question_zh: "其他日子怎么样？", question_vi: "Các ngày khác thì thế nào?", question_es: "¿Qué pasa los demás días?", options: ["The store is closed", "The store opens normally", "The store closes early", "The store is under construction"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "엘리베이터 점검 안내",
    title_en: "Elevator maintenance notice", title_ja: "エレベーター点検のお知らせ", title_zh: "电梯检修通知", title_vi: "Thông báo bảo trì thang máy", title_es: "Aviso de mantenimiento del ascensor",
    body_kr: "엘리베이터 점검 안내\n8월 27일 오전 9시부터 12시까지 점검합니다.\n이 시간에는 계단을 이용해 주세요.\n불편을 드려 죄송합니다.",
    body_en: "Elevator maintenance notice\nInspection will be done from 9 AM to 12 PM on August 27.\nPlease use the stairs during this time.\nWe are sorry for the inconvenience.", body_ja: "エレベーター点検のお知らせ\n8月27日午前9時から12時まで点検を行います。\nこの時間帯は階段をご利用ください。\nご不便をおかけして申し訳ございません。", body_zh: "电梯检修通知\n8月27日上午9点至12点进行检修。\n此时间段请使用楼梯。\n给您带来不便，敬请谅解。", body_vi: "Thông báo bảo trì thang máy\nSẽ tiến hành bảo trì từ 9 giờ đến 12 giờ trưa ngày 27 tháng 8.\nTrong thời gian này xin vui lòng sử dụng cầu thang bộ.\nXin lỗi vì sự bất tiện này.", body_es: "Aviso de mantenimiento del ascensor\nEl mantenimiento se realizará del 27 de agosto de 9 a.m. a 12 p.m.\nPor favor use las escaleras durante ese horario.\nDisculpe las molestias.",
    questions: [
      { question_en: "What is happening on August 27?", question_ja: "8月27日には何が行われますか。", question_zh: "8月27日会发生什么？", question_vi: "Chuyện gì xảy ra vào ngày 27 tháng 8?", question_es: "¿Qué sucede el 27 de agosto?", options: ["The elevator is being repaired", "The building is closing", "The stairs are being cleaned", "The water is being shut off"], answerIndex: 0 },
      { question_en: "What should residents use during the inspection?", question_ja: "点検中、住民は何を利用すべきですか。", question_zh: "检修期间居民应使用什么？", question_vi: "Trong lúc bảo trì cư dân nên dùng gì?", question_es: "¿Qué deben usar los residentes durante el mantenimiento?", options: ["The parking lot", "The stairs", "The back door", "The lobby"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "주차 안내",
    title_en: "Parking notice", title_ja: "駐車のご案内", title_zh: "停车通知", title_vi: "Thông báo đỗ xe", title_es: "Aviso de estacionamiento",
    body_kr: "주민 여러분께 안내드립니다.\n주차는 한 세대에 한 대만 가능합니다.\n다른 차는 주차하지 마세요.\n협조 부탁드립니다.",
    body_en: "A notice for all residents.\nOnly one car per household is allowed to park.\nPlease do not park other cars.\nThank you for your cooperation.", body_ja: "住民の皆様へご案内いたします。\n駐車は一世帯につき一台のみ可能です。\nそれ以外の車は駐車しないでください。\nご協力をお願いいたします。", body_zh: "致各位住户。\n每户只能停一辆车。\n请勿停放其他车辆。\n请予以配合。", body_vi: "Kính gửi quý cư dân.\nMỗi hộ chỉ được đỗ một xe.\nXin đừng đỗ thêm xe khác.\nMong quý vị hợp tác.", body_es: "Aviso para todos los residentes.\nSolo se permite un auto por hogar.\nPor favor no estacione otros autos.\nGracias por su cooperación.",
    questions: [
      { question_en: "How many cars can each household park?", question_ja: "各世帯は何台の車を駐車できますか。", question_zh: "每户能停几辆车？", question_vi: "Mỗi hộ được đỗ bao nhiêu xe?", question_es: "¿Cuántos autos puede estacionar cada hogar?", options: ["One", "Two", "Three", "As many as they want"], answerIndex: 0 },
      { question_en: "What are residents asked to do?", question_ja: "住民は何を求められていますか。", question_zh: "住户被要求做什么？", question_vi: "Cư dân được yêu cầu làm gì?", question_es: "¿Qué se les pide a los residentes?", options: ["Wash their car", "Cooperate with the parking rule", "Buy a parking pass", "Move to a new spot"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "쓰레기 배출 안내",
    title_en: "Trash collection notice", title_ja: "ゴミ出しのご案内", title_zh: "垃圾投放通知", title_vi: "Thông báo đổ rác", title_es: "Aviso de recolección de basura",
    body_kr: "쓰레기 배출 안내\n일반 쓰레기는 월요일과 목요일에 버립니다.\n재활용은 수요일에 버립니다.\n저녁 8시 이후에 버려 주세요.",
    body_en: "Trash collection notice\nGeneral trash is collected on Mondays and Thursdays.\nRecycling is collected on Wednesdays.\nPlease put out trash after 8 PM.", body_ja: "ゴミ出しのご案内\n一般ゴミは月曜日と木曜日に出してください。\nリサイクルは水曜日に出してください。\n夜8時以降に出してください。", body_zh: "垃圾投放通知\n普通垃圾请在周一和周四投放。\n可回收物请在周三投放。\n请在晚上8点以后投放。", body_vi: "Thông báo đổ rác\nRác thải thông thường đổ vào thứ Hai và thứ Năm.\nRác tái chế đổ vào thứ Tư.\nXin đổ rác sau 8 giờ tối.", body_es: "Aviso de recolección de basura\nLa basura general se recoge los lunes y jueves.\nEl reciclaje se recoge los miércoles.\nPor favor saque la basura después de las 8 p.m.",
    questions: [
      { question_en: "When is recycling collected?", question_ja: "リサイクルはいつ回収されますか。", question_zh: "可回收物什么时候回收？", question_vi: "Rác tái chế được thu vào khi nào?", question_es: "¿Cuándo se recoge el reciclaje?", options: ["Monday", "Tuesday", "Wednesday", "Thursday"], answerIndex: 2 },
      { question_en: "When should trash be put out?", question_ja: "ゴミはいつ出すべきですか。", question_zh: "垃圾应该什么时候投放？", question_vi: "Nên đổ rác vào lúc nào?", question_es: "¿Cuándo se debe sacar la basura?", options: ["Before 8 AM", "After 8 PM", "At noon", "Anytime"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "분실물 안내",
    title_en: "Lost and found notice", title_ja: "落とし物のお知らせ", title_zh: "失物招领通知", title_vi: "Thông báo đồ thất lạc", title_es: "Aviso de objetos perdidos",
    body_kr: "분실물을 찾습니다.\n검은색 지갑을 주웠습니다.\n주인은 카운터로 오세요.\n연락처: 010-1234-5678",
    body_en: "We found a lost item.\nWe found a black wallet.\nIf it is yours, please come to the counter.\nContact: 010-1234-5678", body_ja: "落とし物のお知らせ\n黒い財布を拾いました。\n持ち主の方はカウンターまでお越しください。\n連絡先: 010-1234-5678", body_zh: "寻找失主。\n捡到一个黑色钱包。\n失主请到柜台认领。\n联系方式：010-1234-5678", body_vi: "Tìm chủ đồ thất lạc.\nChúng tôi nhặt được một ví màu đen.\nChủ nhân xin vui lòng đến quầy.\nLiên hệ: 010-1234-5678", body_es: "Encontramos un objeto perdido.\nEncontramos una billetera negra.\nSi es suya, por favor venga al mostrador.\nContacto: 010-1234-5678",
    questions: [
      { question_en: "What item was found?", question_ja: "何が見つかりましたか。", question_zh: "捡到了什么物品？", question_vi: "Vật gì đã được tìm thấy?", question_es: "¿Qué objeto se encontró?", options: ["A phone", "A black wallet", "An umbrella", "A key"], answerIndex: 1 },
      { question_en: "Where should the owner go?", question_ja: "持ち主はどこへ行くべきですか。", question_zh: "失主应该去哪里？", question_vi: "Chủ nhân nên đến đâu?", question_es: "¿Adónde debe ir el dueño?", options: ["The police station", "The counter", "The manager's office", "The parking lot"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "임시 휴업 안내",
    title_en: "Temporary closure notice", title_ja: "臨時休業のお知らせ", title_zh: "临时停业通知", title_vi: "Thông báo tạm nghỉ", title_es: "Aviso de cierre temporal",
    body_kr: "임시 휴업 안내\n개인 사정으로 오늘 하루 쉽니다.\n내일부터 정상 영업합니다.\n죄송합니다.",
    body_en: "Temporary closure notice\nWe are closed today for personal reasons.\nWe will be open as usual starting tomorrow.\nWe apologize.", body_ja: "臨時休業のお知らせ\n個人的な事情により本日一日休業いたします。\n明日から通常通り営業いたします。\n申し訳ございません。", body_zh: "临时停业通知\n因个人原因今天停业一天。\n明天起正常营业。\n非常抱歉。", body_vi: "Thông báo tạm nghỉ\nDo lý do cá nhân, hôm nay chúng tôi tạm nghỉ.\nBắt đầu từ ngày mai sẽ mở cửa bình thường.\nXin lỗi quý khách.", body_es: "Aviso de cierre temporal\nHoy cerramos por motivos personales.\nMañana volveremos a abrir con normalidad.\nDisculpe las molestias.",
    questions: [
      { question_en: "Why is the store closed today?", question_ja: "今日お店が休みなのはなぜですか。", question_zh: "今天商店为什么休息？", question_vi: "Tại sao hôm nay cửa hàng đóng cửa?", question_es: "¿Por qué está cerrada la tienda hoy?", options: ["For a holiday", "For personal reasons", "For renovation", "For cleaning"], answerIndex: 1 },
      { question_en: "When will the store open again?", question_ja: "お店はいつ再開しますか。", question_zh: "商店什么时候重新营业？", question_vi: "Khi nào cửa hàng mở cửa lại?", question_es: "¿Cuándo volverá a abrir la tienda?", options: ["Tomorrow", "Next week", "Next month", "It is unknown"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "여름 세일 안내",
    title_en: "Summer sale notice", title_ja: "夏セールのお知らせ", title_zh: "夏季促销通知", title_vi: "Thông báo giảm giá mùa hè", title_es: "Aviso de rebajas de verano",
    body_kr: "여름 세일 안내\n8월 한 달 동안 모든 옷을 30% 할인합니다.\n신발도 20% 할인합니다.\n많이 오세요.",
    body_en: "Summer sale notice\nAll clothes are 30% off during August.\nShoes are also 20% off.\nPlease come and visit.", body_ja: "夏セールのお知らせ\n8月の一ヶ月間、全ての服を30%割引いたします。\n靴も20%割引です。\nぜひお越しください。", body_zh: "夏季促销通知\n8月一整月所有服装打七折。\n鞋子也打八折。\n欢迎光临。", body_vi: "Thông báo giảm giá mùa hè\nTrong suốt tháng 8, tất cả quần áo giảm giá 30%.\nGiày dép cũng giảm giá 20%.\nMời quý khách đến mua sắm.", body_es: "Aviso de rebajas de verano\nDurante todo agosto, toda la ropa tiene un 30% de descuento.\nLos zapatos también tienen un 20% de descuento.\nLos esperamos.",
    questions: [
      { question_en: "How much are clothes discounted?", question_ja: "服は何パーセント割引されますか。", question_zh: "服装打几折？", question_vi: "Quần áo được giảm giá bao nhiêu?", question_es: "¿Qué descuento tiene la ropa?", options: ["10%", "20%", "30%", "50%"], answerIndex: 2 },
      { question_en: "How long does the sale last?", question_ja: "セールはどのくらい続きますか。", question_zh: "促销持续多久？", question_vi: "Đợt giảm giá kéo dài bao lâu?", question_es: "¿Cuánto dura la rebaja?", options: ["One week", "One month", "One day", "One year"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "요가 수업 시간표",
    title_en: "Yoga class schedule", title_ja: "ヨガクラスの時間割", title_zh: "瑜伽课程时间表", title_vi: "Thời khóa biểu lớp yoga", title_es: "Horario de la clase de yoga",
    body_kr: "요가 수업 시간표\n월, 수, 금 오전 7시\n화, 목 저녁 7시\n수업 전에 등록해 주세요.",
    body_en: "Yoga class schedule\nMonday, Wednesday, Friday at 7 AM\nTuesday, Thursday at 7 PM\nPlease register before class.", body_ja: "ヨガクラスの時間割\n月・水・金 午前7時\n火・木 午後7時\n授業前に登録してください。", body_zh: "瑜伽课程时间表\n周一、三、五上午7点\n周二、四晚上7点\n上课前请报名。", body_vi: "Thời khóa biểu lớp yoga\nThứ Hai, Tư, Sáu lúc 7 giờ sáng\nThứ Ba, Năm lúc 7 giờ tối\nXin đăng ký trước khi vào lớp.", body_es: "Horario de la clase de yoga\nLunes, miércoles y viernes a las 7 a.m.\nMartes y jueves a las 7 p.m.\nPor favor inscríbase antes de la clase.",
    questions: [
      { question_en: "What time is the yoga class on Monday?", question_ja: "月曜日のヨガクラスは何時ですか。", question_zh: "周一的瑜伽课几点？", question_vi: "Lớp yoga thứ Hai diễn ra lúc mấy giờ?", question_es: "¿A qué hora es la clase de yoga los lunes?", options: ["7 AM", "7 PM", "9 AM", "9 PM"], answerIndex: 0 },
      { question_en: "What should people do before class?", question_ja: "授業前に何をすべきですか。", question_zh: "上课前应该做什么？", question_vi: "Mọi người nên làm gì trước khi vào lớp?", question_es: "¿Qué deben hacer las personas antes de la clase?", options: ["Bring water", "Register", "Pay cash only", "Arrive early"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "공사 중 안내",
    title_en: "Under construction notice", title_ja: "工事中のお知らせ", title_zh: "施工中通知", title_vi: "Thông báo đang thi công", title_es: "Aviso de obras en curso",
    body_kr: "공사 중입니다.\n9월 5일까지 공사가 계속됩니다.\n이 길로 다니지 마세요.\n다른 길을 이용해 주세요.",
    body_en: "Under construction.\nThe construction will continue until September 5.\nDo not walk this way.\nPlease use another path.", body_ja: "工事中です。\n9月5日まで工事が続きます。\nこの道は通らないでください。\n他の道をご利用ください。", body_zh: "施工中。\n施工将持续到9月5日。\n请勿从此路通行。\n请使用其他道路。", body_vi: "Đang thi công.\nViệc thi công sẽ tiếp tục đến ngày 5 tháng 9.\nXin đừng đi qua con đường này.\nXin sử dụng đường khác.", body_es: "Obras en curso.\nLas obras continuarán hasta el 5 de septiembre.\nNo pase por este camino.\nPor favor use otro camino.",
    questions: [
      { question_en: "When will the construction end?", question_ja: "工事はいつ終わりますか。", question_zh: "施工什么时候结束？", question_vi: "Khi nào việc thi công sẽ kết thúc?", question_es: "¿Cuándo terminarán las obras?", options: ["September 5", "August 5", "October 5", "It never ends"], answerIndex: 0 },
      { question_en: "What are people asked to do?", question_ja: "人々は何をするよう求められていますか。", question_zh: "大家被要求做什么？", question_vi: "Mọi người được yêu cầu làm gì?", question_es: "¿Qué se les pide a las personas?", options: ["Wait here", "Use another path", "Call the office", "Wear a helmet"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "택배 보관 안내",
    title_en: "Package storage notice", title_ja: "宅配便保管のご案内", title_zh: "快递保管通知", title_vi: "Thông báo lưu giữ bưu kiện", title_es: "Aviso de almacenamiento de paquetes",
    body_kr: "고객님께 안내드립니다.\n택배는 1층 관리실에 보관합니다.\n관리실은 오전 9시부터 오후 6시까지 엽니다.\n찾으러 오세요.",
    body_en: "A notice for customers.\nPackages are kept at the management office on the first floor.\nThe office is open from 9 AM to 6 PM.\nPlease come to pick it up.", body_ja: "お客様へご案内いたします。\n宅配便は1階の管理室で保管しております。\n管理室は午前9時から午後6時まで開いています。\nお受け取りにお越しください。", body_zh: "致各位顾客。\n快递保管在一楼管理室。\n管理室开放时间为上午9点至下午6点。\n请前来领取。", body_vi: "Kính gửi quý khách.\nBưu kiện được lưu giữ tại phòng quản lý ở tầng 1.\nPhòng quản lý mở cửa từ 9 giờ sáng đến 6 giờ tối.\nXin vui lòng đến nhận.", body_es: "Aviso para los clientes.\nLos paquetes se guardan en la oficina de administración del primer piso.\nLa oficina está abierta de 9 a.m. a 6 p.m.\nPor favor venga a recogerlo.",
    questions: [
      { question_en: "Where are packages kept?", question_ja: "宅配便はどこに保管されますか。", question_zh: "快递保管在哪里？", question_vi: "Bưu kiện được lưu giữ ở đâu?", question_es: "¿Dónde se guardan los paquetes?", options: ["At the front door", "At the management office", "At the mailbox", "At the parking lot"], answerIndex: 1 },
      { question_en: "What time does the office close?", question_ja: "管理室は何時に閉まりますか。", question_zh: "管理室几点关门？", question_vi: "Văn phòng đóng cửa lúc mấy giờ?", question_es: "¿A qué hora cierra la oficina?", options: ["6 PM", "9 PM", "9 AM", "12 PM"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "소음 자제 안내",
    title_en: "Noise reduction notice", title_ja: "騒音自制のお願い", title_zh: "请勿制造噪音通知", title_vi: "Thông báo hạn chế tiếng ồn", title_es: "Aviso de reducción de ruido",
    body_kr: "주민 여러분께 부탁드립니다.\n밤 10시부터 아침 7시까지는 조용히 해 주세요.\n특히 뛰거나 걷는 소리를 조심해 주세요.\n협조 감사합니다.",
    body_en: "A request to all residents.\nPlease be quiet from 10 PM to 7 AM.\nBe especially careful of running or walking sounds.\nThank you for your cooperation.", body_ja: "住民の皆様にお願いいたします。\n夜10時から朝7時までは静かにしてください。\n特に走ったり歩いたりする音にご注意ください。\nご協力ありがとうございます。", body_zh: "恳请各位住户配合。\n晚上10点到早上7点请保持安静。\n请特别注意跑动或走路的声音。\n感谢您的配合。", body_vi: "Kính mong quý cư dân lưu ý.\nXin giữ yên lặng từ 10 giờ tối đến 7 giờ sáng.\nĐặc biệt xin chú ý tiếng chạy hoặc đi lại.\nCảm ơn sự hợp tác của quý vị.", body_es: "Un pedido para todos los residentes.\nPor favor guarden silencio de 10 p.m. a 7 a.m.\nTengan especial cuidado con el ruido de correr o caminar.\nGracias por su cooperación.",
    questions: [
      { question_en: "During what hours should residents be quiet?", question_ja: "住民は何時から何時まで静かにするべきですか。", question_zh: "住户应在几点到几点之间保持安静？", question_vi: "Cư dân nên giữ yên lặng trong khoảng thời gian nào?", question_es: "¿En qué horario deben guardar silencio los residentes?", options: ["10 PM to 7 AM", "9 PM to 6 AM", "8 PM to 8 AM", "11 PM to 5 AM"], answerIndex: 0 },
      { question_en: "What sound should residents be careful about?", question_ja: "住民はどんな音に気をつけるべきですか。", question_zh: "住户应该注意什么声音？", question_vi: "Cư dân nên chú ý âm thanh gì?", question_es: "¿De qué sonido deben tener cuidado los residentes?", options: ["Music", "Talking", "Running or walking", "Cooking"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "동네 축제 안내",
    title_en: "Neighborhood festival notice", title_ja: "地域祭りのお知らせ", title_zh: "社区节日通知", title_vi: "Thông báo lễ hội khu phố", title_es: "Aviso de festival del barrio",
    body_kr: "동네 축제 안내\n9월 12일 토요일 공원에서 축제를 합니다.\n음식과 공연이 있습니다.\n누구나 참여할 수 있습니다.",
    body_en: "Neighborhood festival notice\nThe festival will be held at the park on Saturday, September 12.\nThere will be food and performances.\nAnyone can join.", body_ja: "地域祭りのお知らせ\n9月12日土曜日、公園でお祭りを開催します。\n食べ物と公演があります。\nどなたでも参加できます。", body_zh: "社区节日通知\n9月12日星期六将在公园举办节日活动。\n有美食和表演。\n任何人都可以参加。", body_vi: "Thông báo lễ hội khu phố\nLễ hội sẽ được tổ chức tại công viên vào thứ Bảy, ngày 12 tháng 9.\nSẽ có ẩm thực và biểu diễn.\nAi cũng có thể tham gia.", body_es: "Aviso de festival del barrio\nEl festival se realizará en el parque el sábado 12 de septiembre.\nHabrá comida y espectáculos.\nCualquiera puede participar.",
    questions: [
      { question_en: "Where is the festival held?", question_ja: "祭りはどこで開催されますか。", question_zh: "节日在哪里举办？", question_vi: "Lễ hội được tổ chức ở đâu?", question_es: "¿Dónde se realiza el festival?", options: ["At the park", "At the library", "At the school", "At the market"], answerIndex: 0 },
      { question_en: "What will there be at the festival?", question_ja: "祭りでは何がありますか。", question_zh: "节日上会有什么？", question_vi: "Ở lễ hội sẽ có gì?", question_es: "¿Qué habrá en el festival?", options: ["Only music", "Food and performances", "Only shopping", "A parade"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "벼룩시장 안내",
    title_en: "Flea market notice", title_ja: "フリーマーケットのお知らせ", title_zh: "跳蚤市场通知", title_vi: "Thông báo chợ trời", title_es: "Aviso de mercado de pulgas",
    body_kr: "벼룩시장 안내\n이번 주 일요일 오전 10시에 시작합니다.\n장소는 아파트 놀이터 앞입니다.\n안 쓰는 물건을 가져오세요.",
    body_en: "Flea market notice\nIt starts at 10 AM this Sunday.\nThe location is in front of the apartment playground.\nPlease bring items you don't use.", body_ja: "フリーマーケットのお知らせ\n今週日曜日午前10時に始まります。\n場所はマンションの遊び場前です。\n使わない物をお持ちください。", body_zh: "跳蚤市场通知\n本周日上午10点开始。\n地点在公寓游乐场前。\n请带上不用的物品。", body_vi: "Thông báo chợ trời\nSẽ bắt đầu lúc 10 giờ sáng Chủ nhật tuần này.\nĐịa điểm là trước sân chơi của chung cư.\nXin mang theo những món đồ không dùng đến.", body_es: "Aviso de mercado de pulgas\nComienza este domingo a las 10 a.m.\nEl lugar es frente al parque infantil del edificio.\nPor favor traiga artículos que ya no use.",
    questions: [
      { question_en: "What day is the flea market?", question_ja: "フリーマーケットは何曜日ですか。", question_zh: "跳蚤市场是星期几？", question_vi: "Chợ trời diễn ra vào ngày nào?", question_es: "¿Qué día es el mercado de pulgas?", options: ["Saturday", "Sunday", "Monday", "Friday"], answerIndex: 1 },
      { question_en: "Where is the flea market located?", question_ja: "フリーマーケットはどこで行われますか。", question_zh: "跳蚤市场在哪里举行？", question_vi: "Chợ trời ở đâu?", question_es: "¿Dónde queda el mercado de pulgas?", options: ["The park", "The parking lot", "In front of the playground", "The community center"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "도서관 이용 안내",
    title_en: "Library usage notice", title_ja: "図書館利用のご案内", title_zh: "图书馆使用须知", title_vi: "Hướng dẫn sử dụng thư viện", title_es: "Aviso de uso de la biblioteca",
    body_kr: "도서관 이용 안내\n책은 두 권까지 빌릴 수 있습니다.\n대출 기간은 2주입니다.\n도서관 안에서는 조용히 해 주세요.",
    body_en: "Library usage notice\nYou can borrow up to two books.\nThe loan period is two weeks.\nPlease be quiet inside the library.", body_ja: "図書館利用のご案内\n本は2冊まで借りることができます。\n貸出期間は2週間です。\n図書館内では静かにしてください。", body_zh: "图书馆使用须知\n每人最多可借两本书。\n借阅期限为两周。\n请在图书馆内保持安静。", body_vi: "Hướng dẫn sử dụng thư viện\nCó thể mượn tối đa hai quyển sách.\nThời hạn mượn là hai tuần.\nXin giữ yên lặng trong thư viện.", body_es: "Aviso de uso de la biblioteca\nPuede pedir prestados hasta dos libros.\nEl plazo de préstamo es de dos semanas.\nPor favor guarde silencio dentro de la biblioteca.",
    questions: [
      { question_en: "How many books can you borrow?", question_ja: "本は何冊まで借りられますか。", question_zh: "最多能借几本书？", question_vi: "Có thể mượn tối đa bao nhiêu quyển sách?", question_es: "¿Cuántos libros puede pedir prestados?", options: ["One", "Two", "Three", "Five"], answerIndex: 1 },
      { question_en: "How long is the loan period?", question_ja: "貸出期間はどのくらいですか。", question_zh: "借阅期限是多久？", question_vi: "Thời hạn mượn sách là bao lâu?", question_es: "¿Cuánto dura el plazo de préstamo?", options: ["One week", "Two weeks", "One month", "Three days"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "수영장 이용 규칙",
    title_en: "Swimming pool rules", title_ja: "プール利用規則", title_zh: "游泳池使用规则", title_vi: "Quy tắc sử dụng hồ bơi", title_es: "Reglas de la piscina",
    body_kr: "수영장 이용 규칙\n수영모를 꼭 써야 합니다.\n음식은 가져오지 마세요.\n어린이는 어른과 함께 오세요.",
    body_en: "Swimming pool rules\nYou must wear a swimming cap.\nDo not bring food.\nChildren must come with an adult.", body_ja: "プール利用規則\n水泳帽は必ず着用してください。\n食べ物は持ち込まないでください。\n子どもは大人と一緒にお越しください。", body_zh: "游泳池使用规则\n必须佩戴泳帽。\n请勿携带食物。\n儿童须由成人陪同。", body_vi: "Quy tắc sử dụng hồ bơi\nBắt buộc phải đội mũ bơi.\nXin không mang theo thức ăn.\nTrẻ em phải đi cùng người lớn.", body_es: "Reglas de la piscina\nEs obligatorio usar gorro de baño.\nNo traiga comida.\nLos niños deben venir acompañados de un adulto.",
    questions: [
      { question_en: "What must swimmers wear?", question_ja: "泳ぐ人は何を着用しなければなりませんか。", question_zh: "游泳的人必须戴什么？", question_vi: "Người bơi phải đeo gì?", question_es: "¿Qué deben usar los nadadores?", options: ["Goggles", "A swimming cap", "Sandals", "A jacket"], answerIndex: 1 },
      { question_en: "What is not allowed at the pool?", question_ja: "プールで許可されていないものは何ですか。", question_zh: "游泳池不允许什么？", question_vi: "Điều gì không được phép ở hồ bơi?", question_es: "¿Qué no está permitido en la piscina?", options: ["Swimming caps", "Towels", "Food", "Goggles"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "출입 금지",
    title_en: "No entry", title_ja: "立入禁止", title_zh: "禁止入内", title_vi: "Cấm vào", title_es: "Prohibido el paso",
    body_kr: "출입 금지\n이곳은 공사 중이라 위험합니다.\n들어가지 마세요.\n관리사무소: 02-123-4567",
    body_en: "No entry\nThis area is dangerous because of construction.\nDo not enter.\nManagement office: 02-123-4567", body_ja: "立入禁止\nここは工事中で危険です。\n入らないでください。\n管理事務所: 02-123-4567", body_zh: "禁止入内\n此处正在施工，很危险。\n请勿进入。\n管理办公室：02-123-4567", body_vi: "Cấm vào\nNơi này đang thi công nên nguy hiểm.\nXin đừng vào.\nVăn phòng quản lý: 02-123-4567", body_es: "Prohibido el paso\nEste lugar es peligroso porque está en obras.\nNo entre.\nOficina de administración: 02-123-4567",
    questions: [
      { question_en: "Why is the area off-limits?", question_ja: "なぜこの場所は立入禁止ですか。", question_zh: "为什么此区域禁止进入？", question_vi: "Tại sao khu vực này bị cấm vào?", question_es: "¿Por qué está prohibido el paso en esta zona?", options: ["It is being cleaned", "It is dangerous because of construction", "It is closed for a party", "It is a private garden"], answerIndex: 1 },
      { question_en: "Who should you contact for more information?", question_ja: "詳しい情報を得るには誰に連絡すべきですか。", question_zh: "如需更多信息应联系谁？", question_vi: "Nên liên hệ ai để biết thêm thông tin?", question_es: "¿Con quién debe contactar para más información?", options: ["The police", "The management office", "The neighbor", "The store owner"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "은행 영업시간 변경 안내",
    title_en: "Bank hours change notice", title_ja: "銀行営業時間変更のお知らせ", title_zh: "银行营业时间变更通知", title_vi: "Thông báo thay đổi giờ giao dịch ngân hàng", title_es: "Aviso de cambio de horario del banco",
    body_kr: "영업시간 변경 안내\n9월부터 영업시간이 오전 9시부터 오후 4시까지로 바뀝니다.\n토요일은 문을 닫습니다.\n참고해 주세요.",
    body_en: "Business hours change notice\nStarting in September, hours will change to 9 AM to 4 PM.\nThe bank will be closed on Saturdays.\nPlease take note.", body_ja: "営業時間変更のお知らせ\n9月から営業時間が午前9時から午後4時までに変わります。\n土曜日は休業いたします。\nご了承ください。", body_zh: "营业时间变更通知\n从9月起营业时间变更为上午9点至下午4点。\n星期六不营业。\n敬请留意。", body_vi: "Thông báo thay đổi giờ giao dịch\nTừ tháng 9, giờ giao dịch sẽ đổi thành từ 9 giờ sáng đến 4 giờ chiều.\nThứ Bảy sẽ đóng cửa.\nXin quý khách lưu ý.", body_es: "Aviso de cambio de horario\nA partir de septiembre, el horario cambiará de 9 a.m. a 4 p.m.\nEl banco cerrará los sábados.\nPor favor tome nota.",
    questions: [
      { question_en: "When does the new schedule start?", question_ja: "新しい営業時間はいつから始まりますか。", question_zh: "新的营业时间从什么时候开始？", question_vi: "Lịch giờ mới bắt đầu từ khi nào?", question_es: "¿Cuándo comienza el nuevo horario?", options: ["August", "September", "October", "January"], answerIndex: 1 },
      { question_en: "What day will the bank be closed?", question_ja: "銀行は何曜日に休業しますか。", question_zh: "银行星期几不营业？", question_vi: "Ngân hàng đóng cửa vào ngày nào?", question_es: "¿Qué día estará cerrado el banco?", options: ["Sunday", "Monday", "Friday", "Saturday"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "편의점 24시간 영업",
    title_en: "24-hour convenience store", title_ja: "コンビニの24時間営業", title_zh: "便利店24小时营业", title_vi: "Cửa hàng tiện lợi mở cửa 24 giờ", title_es: "Tienda de conveniencia abierta 24 horas",
    body_kr: "안내 말씀 드립니다.\n저희 편의점은 24시간 영업합니다.\n언제든지 오세요.\n항상 열려 있습니다.",
    body_en: "We would like to inform you.\nOur convenience store is open 24 hours.\nCome anytime.\nWe are always open.", body_ja: "お知らせいたします。\n当店は24時間営業しております。\nいつでもお越しください。\nいつも開いております。", body_zh: "通知如下。\n本便利店24小时营业。\n随时欢迎光临。\n我们全天开放。", body_vi: "Xin thông báo.\nCửa hàng tiện lợi chúng tôi mở cửa 24 giờ.\nMời quý khách ghé qua bất cứ lúc nào.\nChúng tôi luôn mở cửa.", body_es: "Le informamos lo siguiente.\nNuestra tienda de conveniencia está abierta las 24 horas.\nVenga cuando quiera.\nSiempre estamos abiertos.",
    questions: [
      { question_en: "How many hours a day is the store open?", question_ja: "このお店は一日に何時間開いていますか。", question_zh: "这家店一天开放几个小时？", question_vi: "Cửa hàng mở cửa bao nhiêu giờ một ngày?", question_es: "¿Cuántas horas al día está abierta la tienda?", options: ["12 hours", "18 hours", "24 hours", "8 hours"], answerIndex: 2 },
      { question_en: "According to the notice, when can customers come?", question_ja: "お知らせによると、お客様はいつ来ることができますか。", question_zh: "根据通知，顾客什么时候可以来？", question_vi: "Theo thông báo, khách có thể đến khi nào?", question_es: "Según el aviso, ¿cuándo pueden venir los clientes?", options: ["Only in the morning", "Only at night", "Anytime", "Only on weekends"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "단수 안내",
    title_en: "Water outage notice", title_ja: "断水のお知らせ", title_zh: "停水通知", title_vi: "Thông báo cắt nước", title_es: "Aviso de corte de agua",
    body_kr: "단수 안내\n8월 30일 오전 9시부터 오후 3시까지 물이 나오지 않습니다.\n미리 물을 받아 두세요.\n불편을 드려 죄송합니다.",
    body_en: "Water outage notice\nWater will not be available from 9 AM to 3 PM on August 30.\nPlease store water in advance.\nWe are sorry for the inconvenience.", body_ja: "断水のお知らせ\n8月30日午前9時から午後3時まで水が出ません。\nあらかじめ水をためておいてください。\nご不便をおかけして申し訳ございません。", body_zh: "停水通知\n8月30日上午9点至下午3点停水。\n请提前储备用水。\n给您带来不便，敬请谅解。", body_vi: "Thông báo cắt nước\nNước sẽ bị cắt từ 9 giờ sáng đến 3 giờ chiều ngày 30 tháng 8.\nXin trữ nước trước.\nXin lỗi vì sự bất tiện này.", body_es: "Aviso de corte de agua\nNo habrá agua del 30 de agosto de 9 a.m. a 3 p.m.\nPor favor guarde agua con anticipación.\nDisculpe las molestias.",
    questions: [
      { question_en: "What will happen on August 30?", question_ja: "8月30日には何が起こりますか。", question_zh: "8月30日会发生什么？", question_vi: "Điều gì sẽ xảy ra vào ngày 30 tháng 8?", question_es: "¿Qué sucederá el 30 de agosto?", options: ["Power will be cut", "Water will be cut", "The elevator will stop", "The road will close"], answerIndex: 1 },
      { question_en: "What are residents advised to do beforehand?", question_ja: "住民は事前に何をするよう勧められていますか。", question_zh: "住户应提前做什么？", question_vi: "Cư dân nên làm gì trước đó?", question_es: "¿Qué se recomienda hacer a los residentes de antemano?", options: ["Leave the building", "Store water", "Call the office", "Turn off the lights"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "정전 안내",
    title_en: "Power outage notice", title_ja: "停電のお知らせ", title_zh: "停电通知", title_vi: "Thông báo cắt điện", title_es: "Aviso de corte de electricidad",
    body_kr: "정전 안내\n전기 공사로 오늘 오후 1시부터 2시까지 전기가 끊깁니다.\n엘리베이터도 사용할 수 없습니다.\n양해 부탁드립니다.",
    body_en: "Power outage notice\nDue to electrical work, power will be cut from 1 PM to 2 PM today.\nThe elevator will also be unavailable.\nWe ask for your understanding.", body_ja: "停電のお知らせ\n電気工事のため、本日午後1時から2時まで停電いたします。\nエレベーターもご利用いただけません。\nご理解のほどよろしくお願いいたします。", body_zh: "停电通知\n因电力施工，今天下午1点至2点将停电。\n电梯也无法使用。\n敬请谅解。", body_vi: "Thông báo cắt điện\nDo thi công điện, hôm nay điện sẽ bị cắt từ 1 giờ đến 2 giờ chiều.\nThang máy cũng không thể sử dụng.\nMong quý vị thông cảm.", body_es: "Aviso de corte de electricidad\nPor trabajos eléctricos, hoy se cortará la luz de 1 p.m. a 2 p.m.\nEl ascensor tampoco estará disponible.\nAgradecemos su comprensión.",
    questions: [
      { question_en: "Why will the power be cut?", question_ja: "なぜ電気が止まりますか。", question_zh: "为什么会停电？", question_vi: "Tại sao điện sẽ bị cắt?", question_es: "¿Por qué se cortará la electricidad?", options: ["A storm", "Electrical work", "A fire", "Unpaid bills"], answerIndex: 1 },
      { question_en: "What else will not work during this time?", question_ja: "この間、他に何が使えなくなりますか。", question_zh: "这段时间还有什么不能用？", question_vi: "Trong thời gian này còn gì không hoạt động?", question_es: "¿Qué más no funcionará durante ese tiempo?", options: ["The elevator", "The water", "The internet", "The heating"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "소방 훈련 안내",
    title_en: "Fire drill notice", title_ja: "消防訓練のお知らせ", title_zh: "消防演习通知", title_vi: "Thông báo diễn tập cứu hỏa", title_es: "Aviso de simulacro de incendio",
    body_kr: "소방 훈련 안내\n9월 3일 오전 10시에 소방 훈련을 합니다.\n사이렌이 울리면 계단으로 나가세요.\n엘리베이터는 사용하지 마세요.",
    body_en: "Fire drill notice\nThere will be a fire drill at 10 AM on September 3.\nWhen the siren rings, exit through the stairs.\nDo not use the elevator.", body_ja: "消防訓練のお知らせ\n9月3日午前10時に消防訓練を行います。\nサイレンが鳴ったら階段で避難してください。\nエレベーターは使用しないでください。", body_zh: "消防演习通知\n9月3日上午10点进行消防演习。\n警报响起时请走楼梯疏散。\n请勿使用电梯。", body_vi: "Thông báo diễn tập cứu hỏa\nSẽ tiến hành diễn tập cứu hỏa lúc 10 giờ sáng ngày 3 tháng 9.\nKhi còi báo động vang lên, hãy đi ra bằng cầu thang bộ.\nXin đừng sử dụng thang máy.", body_es: "Aviso de simulacro de incendio\nHabrá un simulacro de incendio el 3 de septiembre a las 10 a.m.\nCuando suene la sirena, salga por las escaleras.\nNo use el ascensor.",
    questions: [
      { question_en: "What time is the fire drill?", question_ja: "消防訓練は何時ですか。", question_zh: "消防演习是几点？", question_vi: "Buổi diễn tập cứu hỏa diễn ra lúc mấy giờ?", question_es: "¿A qué hora es el simulacro de incendio?", options: ["9 AM", "10 AM", "1 PM", "6 PM"], answerIndex: 1 },
      { question_en: "What should people do when the siren rings?", question_ja: "サイレンが鳴ったら何をすべきですか。", question_zh: "警报响起时应该做什么？", question_vi: "Mọi người nên làm gì khi còi báo động vang lên?", question_es: "¿Qué deben hacer las personas cuando suene la sirena?", options: ["Stay inside", "Use the elevator", "Exit through the stairs", "Call the office"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "반려동물 안내",
    title_en: "Pet policy notice", title_ja: "ペットに関するご案内", title_zh: "宠物须知", title_vi: "Thông báo về thú cưng", title_es: "Aviso sobre mascotas",
    body_kr: "반려동물 안내\n복도에서는 목줄을 꼭 하세요.\n엘리베이터에서는 안아 주세요.\n협조해 주셔서 감사합니다.",
    body_en: "Pet policy notice\nPlease keep your pet on a leash in the hallway.\nPlease carry your pet in the elevator.\nThank you for your cooperation.", body_ja: "ペットに関するご案内\n廊下では必ずリードをつけてください。\nエレベーター内では抱っこしてください。\nご協力ありがとうございます。", body_zh: "宠物须知\n在走廊请务必系好牵引绳。\n在电梯内请抱着宠物。\n感谢您的配合。", body_vi: "Thông báo về thú cưng\nỞ hành lang xin luôn đeo dây dắt.\nỞ thang máy xin bế thú cưng lên.\nCảm ơn sự hợp tác của quý vị.", body_es: "Aviso sobre mascotas\nPor favor mantenga a su mascota con correa en el pasillo.\nPor favor cargue a su mascota en el ascensor.\nGracias por su cooperación.",
    questions: [
      { question_en: "What is required in the hallway?", question_ja: "廊下では何が必要ですか。", question_zh: "走廊里需要什么？", question_vi: "Ở hành lang cần có gì?", question_es: "¿Qué se requiere en el pasillo?", options: ["A muzzle", "A leash", "A cage", "A pet ID"], answerIndex: 1 },
      { question_en: "What should owners do in the elevator?", question_ja: "飼い主はエレベーターで何をすべきですか。", question_zh: "主人在电梯里应该做什么？", question_vi: "Chủ nuôi nên làm gì trong thang máy?", question_es: "¿Qué deben hacer los dueños en el ascensor?", options: ["Let the pet walk", "Carry the pet", "Leave the pet outside", "Use a cage"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "자전거 주차 안내",
    title_en: "Bicycle parking notice", title_ja: "自転車駐輪のご案内", title_zh: "自行车停放通知", title_vi: "Thông báo đỗ xe đạp", title_es: "Aviso de estacionamiento de bicicletas",
    body_kr: "자전거 주차 안내\n자전거는 지정된 곳에 세워 주세요.\n복도에 두면 치울 수 있습니다.\n협조 부탁드립니다.",
    body_en: "Bicycle parking notice\nPlease park bicycles in the designated area.\nBikes left in the hallway may be removed.\nThank you for your cooperation.", body_ja: "自転車駐輪のご案内\n自転車は指定の場所に停めてください。\n廊下に置くと撤去されることがあります。\nご協力をお願いいたします。", body_zh: "自行车停放通知\n请把自行车停在指定地点。\n放在走廊里的自行车可能会被清走。\n请予以配合。", body_vi: "Thông báo đỗ xe đạp\nXin để xe đạp ở nơi quy định.\nNếu để ở hành lang có thể sẽ bị dọn đi.\nMong quý vị hợp tác.", body_es: "Aviso de estacionamiento de bicicletas\nPor favor estacione las bicicletas en el área designada.\nLas bicicletas dejadas en el pasillo podrían ser retiradas.\nGracias por su cooperación.",
    questions: [
      { question_en: "Where should bicycles be parked?", question_ja: "自転車はどこに駐輪すべきですか。", question_zh: "自行车应该停在哪里？", question_vi: "Xe đạp nên đỗ ở đâu?", question_es: "¿Dónde deben estacionarse las bicicletas?", options: ["In the hallway", "In the designated area", "Near the elevator", "In the parking lot for cars"], answerIndex: 1 },
      { question_en: "What could happen to bikes left in the hallway?", question_ja: "廊下に置かれた自転車はどうなる可能性がありますか。", question_zh: "放在走廊里的自行车可能会怎样？", question_vi: "Xe đạp để ở hành lang có thể bị làm sao?", question_es: "¿Qué podría pasarles a las bicicletas dejadas en el pasillo?", options: ["Nothing", "They may be removed", "They will be painted", "They will be locked"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "금연 구역 안내",
    title_en: "No smoking area notice", title_ja: "禁煙区域のご案内", title_zh: "禁烟区通知", title_vi: "Thông báo khu vực cấm hút thuốc", title_es: "Aviso de zona para no fumadores",
    body_kr: "이곳은 금연 구역입니다.\n담배를 피우지 마세요.\n흡연은 흡연실에서만 가능합니다.\n협조 부탁드립니다.",
    body_en: "This is a no smoking area.\nDo not smoke here.\nSmoking is only allowed in the smoking room.\nThank you for your cooperation.", body_ja: "ここは禁煙区域です。\nタバコを吸わないでください。\n喫煙は喫煙室でのみ可能です。\nご協力をお願いいたします。", body_zh: "此处为禁烟区。\n请勿吸烟。\n吸烟仅限于吸烟室内。\n请予以配合。", body_vi: "Nơi đây là khu vực cấm hút thuốc.\nXin đừng hút thuốc.\nChỉ được hút thuốc trong phòng hút thuốc.\nMong quý vị hợp tác.", body_es: "Esta es una zona para no fumadores.\nNo fume aquí.\nSolo se permite fumar en la sala de fumadores.\nGracias por su cooperación.",
    questions: [
      { question_en: "What is not allowed in this area?", question_ja: "この区域では何が許可されていませんか。", question_zh: "此区域禁止什么？", question_vi: "Khu vực này cấm điều gì?", question_es: "¿Qué no está permitido en esta zona?", options: ["Eating", "Talking loudly", "Smoking", "Sitting"], answerIndex: 2 },
      { question_en: "Where can people smoke?", question_ja: "どこでタバコを吸うことができますか。", question_zh: "可以在哪里吸烟？", question_vi: "Mọi người có thể hút thuốc ở đâu?", question_es: "¿Dónde pueden fumar las personas?", options: ["Anywhere outside", "The smoking room", "The elevator", "The parking lot"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "분리수거 안내",
    title_en: "Recycling sorting notice", title_ja: "分別収集のご案内", title_zh: "垃圾分类通知", title_vi: "Thông báo phân loại rác", title_es: "Aviso de reciclaje separado",
    body_kr: "분리수거 안내\n플라스틱과 유리는 따로 버려 주세요.\n종이는 상자에 넣어 주세요.\n음식물 쓰레기는 전용 봉투를 사용하세요.",
    body_en: "Recycling sorting notice\nPlease throw away plastic and glass separately.\nPut paper in the box.\nUse a special bag for food waste.", body_ja: "分別収集のご案内\nプラスチックとガラスは分けて捨ててください。\n紙は箱に入れてください。\n生ゴミは専用の袋を使用してください。", body_zh: "垃圾分类通知\n塑料和玻璃请分开投放。\n纸张请放入纸箱。\n厨余垃圾请使用专用垃圾袋。", body_vi: "Thông báo phân loại rác\nXin đổ nhựa và thủy tinh riêng.\nGiấy xin bỏ vào thùng.\nRác thực phẩm xin dùng túi chuyên dụng.", body_es: "Aviso de reciclaje separado\nPor favor deseche el plástico y el vidrio por separado.\nPonga el papel en la caja.\nUse una bolsa especial para los residuos de comida.",
    questions: [
      { question_en: "What should be put in the box?", question_ja: "箱には何を入れるべきですか。", question_zh: "纸箱里应该放什么？", question_vi: "Nên bỏ gì vào thùng?", question_es: "¿Qué se debe poner en la caja?", options: ["Plastic", "Glass", "Paper", "Food waste"], answerIndex: 2 },
      { question_en: "What is needed for food waste?", question_ja: "生ゴミには何が必要ですか。", question_zh: "厨余垃圾需要什么？", question_vi: "Rác thực phẩm cần dùng gì?", question_es: "¿Qué se necesita para los residuos de comida?", options: ["A regular bag", "A special bag", "A box", "Nothing"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "주민센터 강좌 모집",
    title_en: "Community center class registration", title_ja: "住民センター講座の募集", title_zh: "社区中心课程招募", title_vi: "Tuyển sinh lớp học ở trung tâm cộng đồng", title_es: "Inscripción a curso del centro comunitario",
    body_kr: "주민센터 강좌 모집\n요리 교실을 새로 엽니다.\n매주 목요일 오후 2시입니다.\n신청은 1층 사무실에서 하세요.",
    body_en: "Community center class registration\nA new cooking class is opening.\nEvery Thursday at 2 PM.\nApply at the first-floor office.", body_ja: "住民センター講座の募集\n料理教室を新しく開講します。\n毎週木曜日午後2時です。\n申し込みは1階事務室でお願いします。", body_zh: "社区中心课程招募\n新开设烹饪课堂。\n每周四下午2点。\n请到一楼办公室报名。", body_vi: "Tuyển sinh lớp học ở trung tâm cộng đồng\nSẽ mở lớp học nấu ăn mới.\nVào 2 giờ chiều thứ Năm hàng tuần.\nXin đăng ký tại văn phòng tầng 1.", body_es: "Inscripción a curso del centro comunitario\nSe abre una nueva clase de cocina.\nTodos los jueves a las 2 p.m.\nInscríbase en la oficina del primer piso.",
    questions: [
      { question_en: "What kind of class is being offered?", question_ja: "どんな講座が開かれますか。", question_zh: "开设了什么样的课程？", question_vi: "Lớp học nào đang được mở?", question_es: "¿Qué tipo de clase se ofrece?", options: ["Yoga", "Cooking", "Painting", "Dancing"], answerIndex: 1 },
      { question_en: "Where should people apply?", question_ja: "どこで申し込むべきですか。", question_zh: "应该在哪里报名？", question_vi: "Nên đăng ký ở đâu?", question_es: "¿Dónde deben inscribirse las personas?", options: ["Online", "The first-floor office", "By phone", "By mail"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "도서 반납 안내",
    title_en: "Book return notice", title_ja: "図書返却のご案内", title_zh: "图书归还通知", title_vi: "Thông báo trả sách", title_es: "Aviso de devolución de libros",
    body_kr: "도서 반납 안내\n빌린 책은 8월 31일까지 반납해 주세요.\n늦으면 연체료가 있습니다.\n반납함은 정문 옆에 있습니다.",
    body_en: "Book return notice\nPlease return borrowed books by August 31.\nThere is a late fee if you are late.\nThe return box is next to the main entrance.", body_ja: "図書返却のご案内\n借りた本は8月31日までに返却してください。\n遅れると延滞料金が発生します。\n返却ボックスは正門の横にあります。", body_zh: "图书归还通知\n借阅的书请在8月31日前归还。\n逾期将收取滞纳金。\n还书箱在正门旁边。", body_vi: "Thông báo trả sách\nXin trả sách đã mượn trước ngày 31 tháng 8.\nNếu trễ sẽ có phí phạt.\nHộp trả sách ở bên cạnh cổng chính.", body_es: "Aviso de devolución de libros\nPor favor devuelva los libros prestados antes del 31 de agosto.\nSi se atrasa, habrá un recargo.\nEl buzón de devolución está junto a la entrada principal.",
    questions: [
      { question_en: "When is the return deadline?", question_ja: "返却期限はいつですか。", question_zh: "归还截止日期是什么时候？", question_vi: "Hạn trả sách là khi nào?", question_es: "¿Cuál es la fecha límite de devolución?", options: ["August 15", "August 31", "September 15", "September 30"], answerIndex: 1 },
      { question_en: "What happens if a book is returned late?", question_ja: "本の返却が遅れるとどうなりますか。", question_zh: "逾期归还会怎样？", question_vi: "Nếu trả sách trễ thì sao?", question_es: "¿Qué pasa si se devuelve un libro tarde?", options: ["Nothing", "A late fee", "The card is canceled", "The book is lost"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "무료 와이파이 안내",
    title_en: "Free wifi notice", title_ja: "無料Wi-Fiのご案内", title_zh: "免费无线网络通知", title_vi: "Thông báo wifi miễn phí", title_es: "Aviso de wifi gratis",
    body_kr: "무료 와이파이 안내\n비밀번호는 영수증에 있습니다.\n음료를 주문하신 분만 이용 가능합니다.\n즐거운 시간 보내세요.",
    body_en: "Free wifi notice\nThe password is on the receipt.\nOnly customers who ordered a drink can use it.\nHave a pleasant time.", body_ja: "無料Wi-Fiのご案内\nパスワードはレシートに記載されています。\nお飲み物をご注文いただいたお客様のみご利用いただけます。\n楽しい時間をお過ごしください。", body_zh: "免费无线网络通知\n密码在收据上。\n仅限点了饮品的顾客使用。\n祝您度过愉快的时光。", body_vi: "Thông báo wifi miễn phí\nMật khẩu có ghi trên hóa đơn.\nChỉ khách đã gọi đồ uống mới được sử dụng.\nChúc quý khách có thời gian vui vẻ.", body_es: "Aviso de wifi gratis\nLa contraseña está en el recibo.\nSolo pueden usarlo los clientes que pidieron una bebida.\nQue tenga un buen rato.",
    questions: [
      { question_en: "Where can customers find the wifi password?", question_ja: "お客様はWi-Fiのパスワードをどこで見つけられますか。", question_zh: "顾客在哪里能找到无线网络密码？", question_vi: "Khách có thể tìm mật khẩu wifi ở đâu?", question_es: "¿Dónde pueden encontrar los clientes la contraseña del wifi?", options: ["On the wall", "On the receipt", "On the menu", "On the door"], answerIndex: 1 },
      { question_en: "Who can use the wifi?", question_ja: "誰がWi-Fiを利用できますか。", question_zh: "谁可以使用无线网络？", question_vi: "Ai có thể dùng wifi?", question_es: "¿Quién puede usar el wifi?", options: ["Anyone", "Only staff", "Only customers who ordered a drink", "Only members"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "예약 없이 이용 가능",
    title_en: "Walk-ins welcome", title_ja: "予約不要のご案内", title_zh: "无需预约即可使用", title_vi: "Không cần đặt trước cũng có thể sử dụng", title_es: "Se atiende sin reserva",
    body_kr: "안내 말씀 드립니다.\n예약 없이도 이용하실 수 있습니다.\n자리가 없으면 잠시 기다려 주세요.\n감사합니다.",
    body_en: "We would like to inform you.\nYou can visit without a reservation.\nIf there are no seats, please wait a little.\nThank you.", body_ja: "お知らせいたします。\nご予約なしでもご利用いただけます。\n席がない場合は少々お待ちください。\nありがとうございます。", body_zh: "通知如下。\n无需预约也可使用。\n如没有座位请稍等片刻。\n谢谢。", body_vi: "Xin thông báo.\nQuý khách có thể sử dụng mà không cần đặt trước.\nNếu hết chỗ xin vui lòng đợi một chút.\nXin cảm ơn.", body_es: "Le informamos lo siguiente.\nPuede visitarnos sin reserva.\nSi no hay asientos disponibles, espere un momento por favor.\nGracias.",
    questions: [
      { question_en: "Is a reservation required?", question_ja: "予約は必要ですか。", question_zh: "需要预约吗？", question_vi: "Có cần đặt trước không?", question_es: "¿Se requiere reserva?", options: ["Yes, always", "No, walk-ins are welcome", "Only on weekends", "Only for groups"], answerIndex: 1 },
      { question_en: "What should customers do if there are no seats?", question_ja: "席がない場合、お客様は何をすべきですか。", question_zh: "没有座位时顾客应该怎么做？", question_vi: "Khách nên làm gì nếu hết chỗ?", question_es: "¿Qué deben hacer los clientes si no hay asientos?", options: ["Leave", "Call the manager", "Wait a little", "Come back tomorrow"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "씨씨티비 설치 안내",
    title_en: "CCTV installation notice", title_ja: "防犯カメラ設置のお知らせ", title_zh: "监控摄像头安装通知", title_vi: "Thông báo lắp đặt camera an ninh", title_es: "Aviso de instalación de cámaras de seguridad",
    body_kr: "안내 말씀 드립니다.\n건물 안전을 위해 씨씨티비를 설치했습니다.\n출입구와 복도를 촬영합니다.\n안전한 생활에 도움이 되길 바랍니다.",
    body_en: "We would like to inform you.\nCCTV has been installed for the building's safety.\nIt records the entrance and hallways.\nWe hope it helps everyone live safely.", body_ja: "お知らせいたします。\n建物の安全のため、防犯カメラを設置しました。\n出入口と廊下を撮影しています。\n安全な生活の一助となれば幸いです。", body_zh: "通知如下。\n为了大楼安全，已安装监控摄像头。\n拍摄范围为出入口和走廊。\n希望有助于大家安全生活。", body_vi: "Xin thông báo.\nĐể đảm bảo an toàn cho tòa nhà, chúng tôi đã lắp đặt camera an ninh.\nCamera quay khu vực cửa ra vào và hành lang.\nHy vọng sẽ giúp ích cho cuộc sống an toàn của quý vị.", body_es: "Le informamos lo siguiente.\nSe instalaron cámaras de seguridad para la seguridad del edificio.\nGraban la entrada y los pasillos.\nEsperamos que ayude a una vida más segura.",
    questions: [
      { question_en: "Why was the CCTV installed?", question_ja: "なぜ防犯カメラが設置されましたか。", question_zh: "为什么安装了监控摄像头？", question_vi: "Tại sao camera an ninh được lắp đặt?", question_es: "¿Por qué se instalaron las cámaras de seguridad?", options: ["For decoration", "For building safety", "For a school project", "For advertising"], answerIndex: 1 },
      { question_en: "What areas does the CCTV record?", question_ja: "防犯カメラはどの場所を撮影していますか。", question_zh: "监控摄像头拍摄哪些区域？", question_vi: "Camera an ninh quay khu vực nào?", question_es: "¿Qué áreas graban las cámaras de seguridad?", options: ["Only the roof", "The entrance and hallways", "Only the parking lot", "Only the elevator"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "우편함 이용 안내",
    title_en: "Mailroom notice", title_ja: "郵便受け利用のご案内", title_zh: "邮箱使用须知", title_vi: "Hướng dẫn sử dụng hộp thư", title_es: "Aviso de uso del buzón",
    body_kr: "우편함 이용 안내\n우편함은 1층 로비에 있습니다.\n열쇠는 관리실에서 받으세요.\n편지는 매일 확인해 주세요.",
    body_en: "Mailroom notice\nThe mailboxes are in the first-floor lobby.\nGet the key from the management office.\nPlease check your mail every day.", body_ja: "郵便受け利用のご案内\n郵便受けは1階ロビーにあります。\n鍵は管理室で受け取ってください。\n郵便物は毎日確認してください。", body_zh: "邮箱使用须知\n邮箱位于一楼大厅。\n钥匙请到管理室领取。\n请每天查看信件。", body_vi: "Hướng dẫn sử dụng hộp thư\nHộp thư nằm ở sảnh tầng 1.\nXin nhận chìa khóa tại phòng quản lý.\nXin kiểm tra thư mỗi ngày.", body_es: "Aviso de uso del buzón\nLos buzones están en el vestíbulo del primer piso.\nRecoja la llave en la oficina de administración.\nPor favor revise su correo todos los días.",
    questions: [
      { question_en: "Where are the mailboxes located?", question_ja: "郵便受けはどこにありますか。", question_zh: "邮箱在哪里？", question_vi: "Hộp thư ở đâu?", question_es: "¿Dónde están ubicados los buzones?", options: ["The basement", "The first-floor lobby", "The parking lot", "The second floor"], answerIndex: 1 },
      { question_en: "Where can residents get a mailbox key?", question_ja: "住民は郵便受けの鍵をどこで受け取れますか。", question_zh: "住户在哪里能领取邮箱钥匙？", question_vi: "Cư dân có thể nhận chìa khóa hộp thư ở đâu?", question_es: "¿Dónde pueden obtener los residentes la llave del buzón?", options: ["Online", "The management office", "The post office", "The security desk"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "설날 휴무 안내",
    title_en: "Lunar New Year closure notice", title_ja: "旧正月休業のお知らせ", title_zh: "春节休息通知", title_vi: "Thông báo nghỉ Tết Nguyên Đán", title_es: "Aviso de cierre por Año Nuevo Lunar",
    body_kr: "설날 휴무 안내\n2월 9일부터 11일까지 쉽니다.\n12일부터 정상 영업합니다.\n행복한 명절 보내세요.",
    body_en: "Lunar New Year closure notice\nWe are closed from February 9 to 11.\nWe reopen normally on the 12th.\nHave a happy holiday.", body_ja: "旧正月休業のお知らせ\n2月9日から11日まで休業いたします。\n12日から通常通り営業いたします。\n楽しい旧正月をお過ごしください。", body_zh: "春节休息通知\n2月9日至11日休息。\n12日起正常营业。\n祝您节日快乐。", body_vi: "Thông báo nghỉ Tết Nguyên Đán\nSẽ nghỉ từ ngày 9 đến 11 tháng 2.\nTừ ngày 12 sẽ mở cửa bình thường.\nChúc quý khách một kỳ nghỉ vui vẻ.", body_es: "Aviso de cierre por Año Nuevo Lunar\nCerramos del 9 al 11 de febrero.\nVolvemos a abrir con normalidad el día 12.\nQue tenga felices fiestas.",
    questions: [
      { question_en: "When does the store reopen?", question_ja: "お店はいつ再開しますか。", question_zh: "商店什么时候重新营业？", question_vi: "Khi nào cửa hàng mở cửa lại?", question_es: "¿Cuándo vuelve a abrir la tienda?", options: ["February 9", "February 10", "February 11", "February 12"], answerIndex: 3 },
      { question_en: "How many days is the store closed?", question_ja: "お店は何日間休業しますか。", question_zh: "商店休息几天？", question_vi: "Cửa hàng nghỉ mấy ngày?", question_es: "¿Cuántos días permanece cerrada la tienda?", options: ["Two", "Three", "Four", "One"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "추석 휴무 안내",
    title_en: "Chuseok closure notice", title_ja: "秋夕休業のお知らせ", title_zh: "中秋节休息通知", title_vi: "Thông báo nghỉ Chuseok", title_es: "Aviso de cierre por Chuseok",
    body_kr: "추석 휴무 안내\n9월 16일부터 18일까지 휴무입니다.\n택배는 19일부터 다시 받습니다.\n좋은 명절 보내세요.",
    body_en: "Chuseok closure notice\nWe are closed from September 16 to 18.\nWe will accept deliveries again starting on the 19th.\nHave a good holiday.", body_ja: "秋夕(チュソク)休業のお知らせ\n9月16日から18日まで休業いたします。\n宅配便は19日から再開いたします。\n良い秋夕をお過ごしください。", body_zh: "中秋节休息通知\n9月16日至18日休息。\n快递19日起恢复收发。\n祝您节日愉快。", body_vi: "Thông báo nghỉ Chuseok\nSẽ nghỉ từ ngày 16 đến 18 tháng 9.\nBưu kiện sẽ được nhận lại từ ngày 19.\nChúc quý khách một kỳ nghỉ tốt lành.", body_es: "Aviso de cierre por Chuseok\nCerramos del 16 al 18 de septiembre.\nVolveremos a recibir paquetes a partir del día 19.\nQue tenga buenas fiestas.",
    questions: [
      { question_en: "When will deliveries resume?", question_ja: "宅配便はいつ再開しますか。", question_zh: "快递什么时候恢复？", question_vi: "Khi nào bưu kiện được nhận lại?", question_es: "¿Cuándo se reanudarán las entregas?", options: ["September 16", "September 17", "September 18", "September 19"], answerIndex: 3 },
      { question_en: "What holiday is this notice about?", question_ja: "このお知らせはどの祝日についてですか。", question_zh: "这个通知是关于哪个节日的？", question_vi: "Thông báo này nói về ngày lễ nào?", question_es: "¿Sobre qué festividad trata este aviso?", options: ["New Year", "Chuseok", "Christmas", "Children's Day"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "헬스장 새 기구 안내",
    title_en: "New gym equipment notice", title_ja: "ジムの新しい器具のご案内", title_zh: "健身房新器材通知", title_vi: "Thông báo thiết bị mới của phòng gym", title_es: "Aviso de nuevo equipo del gimnasio",
    body_kr: "새 기구 안내\n러닝머신 세 대를 새로 들여왔습니다.\n사용 후에는 땀을 닦아 주세요.\n안전하게 운동하세요.",
    body_en: "New equipment notice\nThree new treadmills have been added.\nPlease wipe off sweat after use.\nExercise safely.", body_ja: "新しい器具のご案内\nランニングマシンを3台新しく導入しました。\n使用後は汗を拭き取ってください。\n安全に運動してください。", body_zh: "新器材通知\n新引进了三台跑步机。\n使用后请擦干汗水。\n请安全锻炼。", body_vi: "Thông báo thiết bị mới\nĐã nhập mới ba máy chạy bộ.\nXin lau mồ hôi sau khi sử dụng.\nHãy tập luyện an toàn.", body_es: "Aviso de nuevo equipo\nSe incorporaron tres cintas de correr nuevas.\nPor favor limpie el sudor después de usarlas.\nEjercítese con seguridad.",
    questions: [
      { question_en: "What new equipment was added?", question_ja: "どんな新しい器具が導入されましたか。", question_zh: "新增了什么器材？", question_vi: "Thiết bị mới nào đã được thêm vào?", question_es: "¿Qué equipo nuevo se agregó?", options: ["Weights", "Treadmills", "Bikes", "Yoga mats"], answerIndex: 1 },
      { question_en: "What should members do after using the equipment?", question_ja: "会員は器具を使用した後、何をすべきですか。", question_zh: "会员使用器材后应该做什么？", question_vi: "Hội viên nên làm gì sau khi dùng thiết bị?", question_es: "¿Qué deben hacer los miembros después de usar el equipo?", options: ["Turn it off", "Wipe off sweat", "Report to staff", "Take a photo"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "수영장 청소 안내",
    title_en: "Pool cleaning notice", title_ja: "プール清掃のお知らせ", title_zh: "游泳池清洁通知", title_vi: "Thông báo vệ sinh hồ bơi", title_es: "Aviso de limpieza de la piscina",
    body_kr: "수영장 청소 안내\n9월 1일은 청소로 수영장을 이용할 수 없습니다.\n2일부터 다시 이용 가능합니다.\n양해 부탁드립니다.",
    body_en: "Pool cleaning notice\nThe pool will be closed for cleaning on September 1.\nIt will be available again from the 2nd.\nWe ask for your understanding.", body_ja: "プール清掃のお知らせ\n9月1日は清掃のためプールをご利用いただけません。\n2日から再びご利用いただけます。\nご理解のほどよろしくお願いいたします。", body_zh: "游泳池清洁通知\n9月1日因清洁无法使用游泳池。\n2日起可再次使用。\n敬请谅解。", body_vi: "Thông báo vệ sinh hồ bơi\nNgày 1 tháng 9 hồ bơi sẽ đóng cửa để vệ sinh.\nTừ ngày 2 sẽ có thể sử dụng lại.\nMong quý vị thông cảm.", body_es: "Aviso de limpieza de la piscina\nEl 1 de septiembre la piscina no estará disponible por limpieza.\nEstará disponible de nuevo a partir del día 2.\nAgradecemos su comprensión.",
    questions: [
      { question_en: "Why is the pool closed on September 1?", question_ja: "なぜ9月1日にプールが閉鎖されますか。", question_zh: "9月1日游泳池为什么关闭？", question_vi: "Tại sao hồ bơi đóng cửa vào ngày 1 tháng 9?", question_es: "¿Por qué está cerrada la piscina el 1 de septiembre?", options: ["A competition", "Cleaning", "A holiday", "Repairs"], answerIndex: 1 },
      { question_en: "When does the pool reopen?", question_ja: "プールはいつ再開しますか。", question_zh: "游泳池什么时候重新开放？", question_vi: "Khi nào hồ bơi mở cửa lại?", question_es: "¿Cuándo vuelve a abrir la piscina?", options: ["September 1", "September 2", "September 3", "September 10"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "구인 안내",
    title_en: "Job posting notice", title_ja: "求人のお知らせ", title_zh: "招聘通知", title_vi: "Thông báo tuyển dụng", title_es: "Aviso de empleo",
    body_kr: "구인 안내\n주말 아르바이트생을 구합니다.\n오전 9시부터 오후 3시까지 일합니다.\n관심 있으면 카운터로 문의하세요.",
    body_en: "Job posting notice\nWe are looking for a weekend part-time worker.\nWork hours are 9 AM to 3 PM.\nIf interested, please ask at the counter.", body_ja: "求人のお知らせ\n週末アルバイトを募集しています。\n午前9時から午後3時まで勤務です。\nご興味のある方はカウンターまでお問い合わせください。", body_zh: "招聘通知\n招聘周末兼职人员。\n工作时间为上午9点至下午3点。\n有意者请到柜台咨询。", body_vi: "Thông báo tuyển dụng\nCần tuyển nhân viên làm thêm vào cuối tuần.\nLàm việc từ 9 giờ sáng đến 3 giờ chiều.\nNếu quan tâm xin hỏi tại quầy.", body_es: "Aviso de empleo\nBuscamos un empleado de medio tiempo para los fines de semana.\nEl horario de trabajo es de 9 a.m. a 3 p.m.\nSi está interesado, pregunte en el mostrador.",
    questions: [
      { question_en: "What kind of position is this?", question_ja: "どんな職種ですか。", question_zh: "这是什么样的职位？", question_vi: "Đây là vị trí công việc như thế nào?", question_es: "¿Qué tipo de puesto es este?", options: ["Full-time", "Weekend part-time", "Manager", "Delivery driver"], answerIndex: 1 },
      { question_en: "Where should interested people ask?", question_ja: "興味のある人はどこに問い合わせるべきですか。", question_zh: "有意者应该到哪里咨询？", question_vi: "Người quan tâm nên hỏi ở đâu?", question_es: "¿Dónde deben preguntar las personas interesadas?", options: ["Online", "By phone", "At the counter", "By mail"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "고양이를 찾습니다",
    title_en: "Looking for a cat", title_ja: "猫を探しています", title_zh: "寻找猫咪", title_vi: "Tìm mèo", title_es: "Buscamos un gato",
    body_kr: "고양이를 찾습니다.\n하얀색 고양이이고 이름은 나비입니다.\n8월 24일부터 안 보입니다.\n보시면 연락 주세요. 010-9876-5432",
    body_en: "Looking for a cat.\nIt is a white cat named Nabi.\nIt has been missing since August 24.\nPlease contact me if you see it. 010-9876-5432", body_ja: "猫を探しています。\n白い猫で、名前はナビです。\n8月24日からいなくなりました。\n見かけたらご連絡ください。010-9876-5432", body_zh: "寻找猫咪。\n是一只白色的猫，名字叫纳比。\n从8月24日起不见了。\n如果看到请联系。010-9876-5432", body_vi: "Tìm mèo.\nLà một con mèo màu trắng, tên là Nabi.\nKhông thấy nó từ ngày 24 tháng 8.\nNếu thấy xin hãy liên hệ. 010-9876-5432", body_es: "Buscamos un gato.\nEs un gato blanco llamado Nabi.\nHa estado perdido desde el 24 de agosto.\nSi lo ve, por favor contácteme. 010-9876-5432",
    questions: [
      { question_en: "What color is the missing cat?", question_ja: "いなくなった猫は何色ですか。", question_zh: "走失的猫是什么颜色？", question_vi: "Con mèo bị mất màu gì?", question_es: "¿De qué color es el gato perdido?", options: ["Black", "White", "Gray", "Orange"], answerIndex: 1 },
      { question_en: "Since when has the cat been missing?", question_ja: "いつから猫がいなくなりましたか。", question_zh: "猫是从什么时候开始不见的？", question_vi: "Con mèo mất tích từ khi nào?", question_es: "¿Desde cuándo está perdido el gato?", options: ["August 20", "August 22", "August 24", "August 30"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "도로 통제 안내",
    title_en: "Road closure notice", title_ja: "道路規制のお知らせ", title_zh: "道路管制通知", title_vi: "Thông báo cấm đường", title_es: "Aviso de cierre de calle",
    body_kr: "도로 통제 안내\n행사 때문에 오늘 오후 2시부터 5시까지 이 도로를 막습니다.\n다른 길로 가 주세요.\n불편을 드려 죄송합니다.",
    body_en: "Road closure notice\nThis road will be closed from 2 PM to 5 PM today because of an event.\nPlease take another route.\nWe are sorry for the inconvenience.", body_ja: "道路規制のお知らせ\nイベントのため、本日午後2時から5時までこの道路を封鎖します。\n他の道をご利用ください。\nご不便をおかけして申し訳ございません。", body_zh: "道路管制通知\n因活动，今天下午2点至5点将封闭此道路。\n请绕行其他道路。\n给您带来不便，敬请谅解。", body_vi: "Thông báo cấm đường\nDo có sự kiện, con đường này sẽ bị chặn từ 2 giờ đến 5 giờ chiều hôm nay.\nXin đi đường khác.\nXin lỗi vì sự bất tiện này.", body_es: "Aviso de cierre de calle\nEsta calle estará cerrada hoy de 2 p.m. a 5 p.m. por un evento.\nPor favor tome otra ruta.\nDisculpe las molestias.",
    questions: [
      { question_en: "Why is the road closed?", question_ja: "なぜ道路が封鎖されますか。", question_zh: "为什么封闭道路？", question_vi: "Tại sao con đường bị chặn?", question_es: "¿Por qué está cerrada la calle?", options: ["Construction", "An event", "An accident", "Snow"], answerIndex: 1 },
      { question_en: "What should drivers do?", question_ja: "運転手は何をすべきですか。", question_zh: "司机应该怎么做？", question_vi: "Người lái xe nên làm gì?", question_es: "¿Qué deben hacer los conductores?", options: ["Wait on the road", "Take another route", "Turn around and go home", "Park nearby"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "notice",
    title_kr: "고객 주차 안내",
    title_en: "Customer parking notice", title_ja: "お客様駐車のご案内", title_zh: "顾客停车通知", title_vi: "Thông báo đỗ xe cho khách", title_es: "Aviso de estacionamiento para clientes",
    body_kr: "고객 주차 안내\n매장 이용 고객은 두 시간 무료입니다.\n주차권은 카운터에서 받으세요.\n감사합니다.",
    body_en: "Customer parking notice\nCustomers get two hours of free parking.\nGet a parking ticket at the counter.\nThank you.", body_ja: "お客様駐車のご案内\n店舗をご利用のお客様は2時間無料です。\n駐車券はカウンターでお受け取りください。\nありがとうございます。", body_zh: "顾客停车通知\n光顾本店的顾客可享两小时免费停车。\n停车券请到柜台领取。\n谢谢。", body_vi: "Thông báo đỗ xe cho khách\nKhách hàng đến cửa hàng được miễn phí đỗ xe hai giờ.\nXin nhận vé đỗ xe tại quầy.\nXin cảm ơn.", body_es: "Aviso de estacionamiento para clientes\nLos clientes de la tienda tienen dos horas gratis.\nRecoja el boleto de estacionamiento en el mostrador.\nGracias.",
    questions: [
      { question_en: "How long is parking free for customers?", question_ja: "お客様の駐車は何時間無料ですか。", question_zh: "顾客免费停车多长时间？", question_vi: "Khách được miễn phí đỗ xe bao lâu?", question_es: "¿Cuánto tiempo es gratis el estacionamiento para los clientes?", options: ["One hour", "Two hours", "Three hours", "All day"], answerIndex: 1 },
      { question_en: "Where should customers get a parking ticket?", question_ja: "お客様はどこで駐車券を受け取るべきですか。", question_zh: "顾客应该在哪里领取停车券？", question_vi: "Khách nên nhận vé đỗ xe ở đâu?", question_es: "¿Dónde deben obtener los clientes el boleto de estacionamiento?", options: ["At the entrance", "At the counter", "Online", "From security"], answerIndex: 1 },
    ],
  },
];
