import type { RawPassage } from "./types";

export const READING_A1_STORY: RawPassage[] = [
  {
    level: "A1",
    genre: "story",
    title_kr: "새 컵",
    title_en: "A new cup",
    body_kr: "저는 새 컵을 샀어요. 컵은 파란색이에요. 아침마다 이 컵으로 물을 마셔요. 컵이 예뻐서 기분이 좋아요.",
    body_en: "I bought a new cup. The cup is blue. Every morning, I drink water with this cup. I feel good because the cup is pretty.",
    questions: [
      { question_en: "What color is the new cup?", options: ["Blue","White","Red","Yellow"], answerIndex: 0 },
      { question_en: "When does the narrator use the cup?", options: ["Every afternoon","Every morning","Every night","Every weekend"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "아기 동생",
    title_en: "My little sibling",
    body_kr: "우리 동생은 이제 자전거를 배워요. 처음에는 자주 넘어졌어요. 요즘은 혼자서도 잘 타요. 저는 동생이 정말 대단해요.",
    body_en: "My little sibling is learning to ride a bike now. At first, the sibling fell often. These days, the sibling rides well alone too. I think my sibling is really amazing.",
    questions: [
      { question_en: "What is the sibling learning to do?", options: ["Swim","Ride a bike","Draw","Sing"], answerIndex: 1 },
      { question_en: "What happened at first?", options: ["The sibling cried","The sibling fell often","The sibling ran away","The sibling slept"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "아기 옷",
    title_en: "New shoes for my sibling",
    body_kr: "저는 동생의 신발을 사요. 작은 신발들이 정말 귀여워요. 노란색과 하얀색 신발을 골라요. 동생이 새 신발을 신으면 좋아해요.",
    body_en: "I buy shoes for my sibling. The small shoes are really cute. I choose yellow and white shoes. My sibling is happy wearing the new shoes.",
    questions: [
      { question_en: "What colors does the narrator choose?", options: ["Yellow and white","Blue and green","Red and black","Pink and purple"], answerIndex: 0 },
      { question_en: "Who are the shoes for?", options: ["The mom","The sibling","The narrator","A friend"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "시골 할머니 댁",
    title_en: "Grandma's house in the country",
    body_kr: "우리 할머니는 시골에 사세요. 여름마다 시골 할머니 댁에 가요. 할머니 댁 마당에는 닭이 있어요. 공기가 맑고 조용해요.",
    body_en: "My grandmother lives in the countryside. Every summer, I go to grandma's house in the country. There are chickens in grandma's yard. The air is clean and quiet.",
    questions: [
      { question_en: "What is in grandma's yard?", options: ["Chickens","Cats","Dogs","Cows"], answerIndex: 0 },
      { question_en: "How is the air in the countryside?", options: ["Cold and wet","Dirty and loud","Clean and quiet","Hot and dusty"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "새 신발",
    title_en: "New shoes",
    body_kr: "오늘 새 신발을 신어요. 하얀색 운동화예요. 신발이 아주 편해요. 많이 걷고 싶어요.",
    body_en: "Today I wear my new shoes. They are white sneakers. The shoes are very comfortable. I want to walk a lot.",
    questions: [
      { question_en: "What kind of shoes are they?", options: ["Black boots", "White sneakers", "Red sandals", "Blue slippers"], answerIndex: 1 },
      { question_en: "How do the shoes feel?", options: ["Small", "Heavy", "Comfortable", "Expensive"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "아이스크림",
    title_en: "Ice cream",
    body_kr: "날씨가 더워요. 저는 아이스크림을 사요. 딸기 맛이에요. 아, 시원하고 달아요!",
    body_en: "The weather is hot. I buy ice cream. It's strawberry flavor. Ah, it's cool and sweet!",
    questions: [
      { question_en: "Why do they buy ice cream?", options: ["It's their birthday", "The weather is hot", "It's on sale", "A friend asked"], answerIndex: 1 },
      { question_en: "What flavor is it?", options: ["Chocolate", "Vanilla", "Strawberry", "Melon"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "사진을 찍어요",
    title_en: "Taking pictures",
    body_kr: "오늘 하늘이 예뻐요. 구름이 하얗어요. 저는 사진을 찍어요. 지민이한테 사진을 보내요.",
    body_en: "The sky is pretty today. The clouds are white. I take a picture. I send the picture to Jimin.",
    questions: [
      { question_en: "What do they take a picture of?", options: ["Food", "The sky", "A cat", "Themselves"], answerIndex: 1 },
      { question_en: "Who do they send it to?", options: ["Their mom", "Their teacher", "A friend", "Nobody"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "전화해요",
    title_en: "Making a call",
    body_kr: "저는 할머니한테 전화해요. 할머니는 부산에 살아요. 우리는 삼십 분 이야기해요. 할머니 목소리가 좋아요.",
    body_en: "I call my grandmother. She lives in Busan. We talk for thirty minutes. I love her voice.",
    questions: [
      { question_en: "Where does the grandmother live?", options: ["Seoul", "Busan", "Jeju", "Daegu"], answerIndex: 1 },
      { question_en: "How long do they talk?", options: ["Ten minutes", "Twenty minutes", "Thirty minutes", "An hour"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "꽃집",
    title_en: "The flower shop",
    body_kr: "내일은 엄마 생일이에요. 저는 꽃집에 가요. 노란 꽃을 사요. 엄마가 노란색을 좋아해요.",
    body_en: "Tomorrow is my mom's birthday. I go to the flower shop. I buy yellow flowers. My mom likes yellow.",
    questions: [
      { question_en: "Whose birthday is tomorrow?", options: ["The writer's", "Mom's", "Dad's", "A friend's"], answerIndex: 1 },
      { question_en: "Why yellow flowers?", options: ["They are cheap", "Mom likes yellow", "They smell good", "They last long"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "새 학기",
    title_en: "New semester",
    body_kr: "오늘부터 새 학기예요. 지민이라는 새 친구를 만나요. 새 책도 받아요. 저는 조금 떨려요.",
    body_en: "The new semester starts today. I meet a new friend named Jimin. I also receive new books. I'm a little nervous.",
    questions: [
      { question_en: "What starts today?", options: ["A game","New semester","A trip","Vacation"], answerIndex: 1 },
      { question_en: "How does the person feel?", options: ["Very sleepy","Angry","Bored","A little nervous"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "시험 보는 날",
    title_en: "Test day",
    body_kr: "오늘은 시험 보는 날이에요. 저는 아침에 공부해요. 시험이 어려워요. 그래도 최선을 다해요.",
    body_en: "Today is test day. I study in the morning. The test is difficult. Still, I do my best.",
    questions: [
      { question_en: "When does the person study?", options: ["At lunch","At night","In the morning","After school"], answerIndex: 2 },
      { question_en: "How is the test?", options: ["Fun","Short","Easy","Difficult"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "머리가 아파요",
    title_en: "My head hurts",
    body_kr: "오늘 머리가 많이 아파요. 학교에 가고 싶지 않아요. 엄마가 약을 줘요. 저는 일찍 자요.",
    body_en: "My head hurts a lot today. I don't want to go to school. Mom gives me medicine. I go to bed early.",
    questions: [
      { question_en: "What hurts?", options: ["Leg","Head","Arm","Stomach"], answerIndex: 1 },
      { question_en: "Who gives medicine?", options: ["Friend","Teacher","Doctor","Mom"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "배가 아파요",
    title_en: "My stomach hurts",
    body_kr: "점심을 먹고 배가 아파요. 화장실에 자주 가요. 엄마가 걱정해요. 저는 물을 많이 마셔요.",
    body_en: "After lunch, my stomach hurts. I go to the bathroom often. Mom worries. I drink a lot of water.",
    questions: [
      { question_en: "When does the stomach start hurting?", options: ["At night","In the morning","Before breakfast","After lunch"], answerIndex: 3 },
      { question_en: "What does the person drink a lot of?", options: ["Juice","Water","Milk","Tea"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "병원에 가요",
    title_en: "Going to the hospital",
    body_kr: "동생이 다리를 다쳤어요. 우리는 병원에 가요. 의사 선생님이 봐 줘요. 다행히 많이 아프지 않아요.",
    body_en: "My younger sibling hurt their leg. We go to the hospital. The doctor examines them. Luckily, it doesn't hurt much.",
    questions: [
      { question_en: "What did the sibling hurt?", options: ["Arm","Hand","Head","Leg"], answerIndex: 3 },
      { question_en: "Who examines the sibling?", options: ["Doctor","Teacher","Nurse's friend","Parent"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "눈이 나빠요",
    title_en: "My eyesight is bad",
    body_kr: "저는 요즘 칠판이 잘 안 보여요. 눈이 나빠졌어요. 안경을 맞추러 가요. 새 안경이 마음에 들어요.",
    body_en: "Lately I can't see the blackboard well. My eyesight has gotten worse. I go to get glasses fitted. I like my new glasses.",
    questions: [
      { question_en: "What can't the person see well?", options: ["The book","The board","The TV","The sign"], answerIndex: 1 },
      { question_en: "What does the person get?", options: ["A book","A hat","Glasses","A phone"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "이가 아파요",
    title_en: "My tooth hurts",
    body_kr: "어제부터 이가 아파요. 단 음식을 못 먹어요. 오늘 치과에 가요. 치과 선생님이 이를 봐요.",
    body_en: "My tooth has hurt since yesterday. I can't eat sweet food. I go to the dentist today. The dentist checks my tooth.",
    questions: [
      { question_en: "Since when has the tooth hurt?", options: ["Last week","This morning","Today","Yesterday"], answerIndex: 3 },
      { question_en: "What can't the person eat?", options: ["Hot food","Sweet food","Spicy food","Cold food"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "운동 후 몸살",
    title_en: "Sore after exercise",
    body_kr: "어제 운동을 너무 많이 했어요. 오늘 온몸이 아파요. 다리가 특히 아파요. 저는 쉬고 싶어요.",
    body_en: "I exercised too much yesterday. My whole body aches today. My legs especially hurt. I want to rest.",
    questions: [
      { question_en: "When did the person exercise a lot?", options: ["Tomorrow","Yesterday","Today","Last month"], answerIndex: 1 },
      { question_en: "Which part especially hurts?", options: ["Neck","Legs","Back","Arms"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "콧물이 나요",
    title_en: "I have a runny nose",
    body_kr: "아침부터 콧물이 나요. 목도 조금 아파요. 마스크를 써요. 일찍 자면 나을 거예요.",
    body_en: "I've had a runny nose since morning. My throat also hurts a little. I wear a mask. I'll get better if I sleep early.",
    questions: [
      { question_en: "Since when has the nose been runny?", options: ["Yesterday","Last night","Lunch","Morning"], answerIndex: 3 },
      { question_en: "What does the person wear?", options: ["Glasses","Gloves","Mask","Scarf"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "예방 접종",
    title_en: "Vaccination",
    body_kr: "오늘 병원에서 예방 접종을 받아요. 주사가 조금 아파요. 저는 울지 않아요. 사탕을 받아서 기분이 좋아요.",
    body_en: "I get a vaccination at the hospital today. The shot hurts a little. I don't cry. I feel good because I get candy.",
    questions: [
      { question_en: "What does the person receive at the hospital?", options: ["A vaccination","A check-up only","Medicine","Glasses"], answerIndex: 0 },
      { question_en: "What does the person get afterward?", options: ["Money","Candy","A book","A toy"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "다리가 저려요",
    title_en: "My leg feels numb",
    body_kr: "오래 앉아 있어서 다리가 저려요. 일어나서 걸어요. 조금씩 괜찮아져요. 이제 다시 앉아요.",
    body_en: "My leg feels numb because I sat for a long time. I stand up and walk. It gets a bit better. Now I sit again.",
    questions: [
      { question_en: "Why does the leg feel numb?", options: ["Cold weather","Sitting too long","Jumping","Running"], answerIndex: 1 },
      { question_en: "What does the person do to feel better?", options: ["Walk","Drink water","Sleep","Eat"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "귀가 아파요",
    title_en: "My ear hurts",
    body_kr: "수영을 하고 나서 귀가 아파요. 물이 들어간 것 같아요. 엄마가 귀를 봐줘요. 병원에 가기로 해요.",
    body_en: "My ear hurts after swimming. It seems water got in. Mom checks my ear. We decide to go to the hospital.",
    questions: [
      { question_en: "When did the ear start hurting?", options: ["At school","Before swimming","In the morning","After swimming"], answerIndex: 3 },
      { question_en: "What do they decide to do?", options: ["Ignore it","Go to school","Go to the hospital","Sleep"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "우산을 잃어버렸어요",
    title_en: "I lost my umbrella",
    body_kr: "학교에서 집에 올 때 비가 와요. 그런데 우산이 없어요. 버스에 놓고 왔어요. 다음에는 조심해야겠어요.",
    body_en: "It rains when I come home from school. But I don't have an umbrella. I left it on the bus. I need to be more careful next time.",
    questions: [
      { question_en: "What is missing?", options: ["An umbrella","A bag","A book","A phone"], answerIndex: 0 },
      { question_en: "Where was it left?", options: ["Park","Store","Bus","Classroom"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "손을 다쳤어요",
    title_en: "I hurt my hand",
    body_kr: "체육 시간에 손을 다쳤어요. 조금 피가 나요. 양호실에서 치료를 받아요. 이제 괜찮아요.",
    body_en: "I hurt my hand during PE class. A little blood comes out. I get treated at the nurse's office. Now I'm okay.",
    questions: [
      { question_en: "When did the person get hurt?", options: ["Math class","Recess","Lunch","PE class"], answerIndex: 3 },
      { question_en: "Where does the person get treated?", options: ["Classroom","Nurse's office","Home","Hospital"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "준비물을 잊었어요",
    title_en: "I forgot my school supplies",
    body_kr: "오늘 미술 준비물을 잊었어요. 마음이 급해요. 지민이가 색연필을 빌려줘요. 정말 고마워요.",
    body_en: "I forgot my art supplies today. I feel anxious. My friend Jimin lends me colored pencils. I'm really thankful.",
    questions: [
      { question_en: "What subject's supplies did the person forget?", options: ["Music","Art","Math","Science"], answerIndex: 1 },
      { question_en: "Who lends colored pencils?", options: ["No one","Friend","Sister","Teacher"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "버스를 놓쳤어요",
    title_en: "I missed the bus",
    body_kr: "아침에 버스를 놓쳤어요. 다음 버스를 기다려요. 십 분 후에 버스가 와요. 학교에 조금 늦게 도착해요.",
    body_en: "I missed the bus in the morning. I wait for the next bus. The bus comes ten minutes later. I arrive at school a bit late.",
    questions: [
      { question_en: "When did the person miss the bus?", options: ["Evening","Morning","Night","Afternoon"], answerIndex: 1 },
      { question_en: "How does the person arrive at school?", options: ["Early","A bit late","Very late","On time"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "버스 정류장",
    title_en: "The bus stop",
    body_kr: "버스 정류장에서 버스를 기다려요. 버스가 안 와요. 십 분을 기다려요. 드디어 버스가 와요!",
    body_en: "I wait for the bus at the bus stop. The bus doesn't come. I wait ten minutes. Finally the bus comes!",
    questions: [
      { question_en: "How long do they wait?", options: ["Five minutes", "Ten minutes", "Twenty minutes", "An hour"], answerIndex: 1 },
      { question_en: "What happens at the end?", options: ["They walk home", "The bus comes", "It rains", "They call a taxi"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "비 오는 날",
    title_en: "A rainy day",
    body_kr: "오늘은 비가 와요. 저는 우산이 없어요. 그래서 편의점에서 우산을 사요. 파란색 우산이에요.",
    body_en: "It's raining today. I don't have an umbrella. So I buy one at the convenience store. It's a blue umbrella.",
    questions: [
      { question_en: "What is the weather like?", options: ["Sunny", "Snowy", "Rainy", "Windy"], answerIndex: 2 },
      { question_en: "What color is the umbrella?", options: ["Red", "Blue", "Black", "Yellow"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "태풍이 와요",
    title_en: "A typhoon is coming",
    body_kr: "내일 태풍이 온대요. 바람이 아주 세요. 우리는 창문을 잘 닫아요. 밖에 나가지 않기로 해요.",
    body_en: "They say a typhoon is coming tomorrow. The wind is very strong. We close the windows well. We decide not to go outside.",
    questions: [
      { question_en: "What is coming tomorrow?", options: ["A typhoon","A heat wave","Snow","Fog"], answerIndex: 0 },
      { question_en: "What do they decide?", options: ["Go outside","Not go outside","Go to school","Go camping"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "무지개를 봐요",
    title_en: "Seeing a rainbow",
    body_kr: "비가 그치고 무지개가 떠요. 색깔이 아주 예뻐요. 저는 사진을 찍어요. 잠깐 있다가 사라져요.",
    body_en: "The rain stops and a rainbow appears. The colors are very pretty. I take a picture. It disappears after a while.",
    questions: [
      { question_en: "When does the rainbow appear?", options: ["In winter","At night","Before rain","After rain stops"], answerIndex: 3 },
      { question_en: "What does the person do?", options: ["Take a picture","Run away","Draw it","Ignore it"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "안개 낀 아침",
    title_en: "A foggy morning",
    body_kr: "오늘 아침에 안개가 많아요. 앞이 잘 안 보여요. 차들이 천천히 가요. 조금 있으면 안개가 걷혀요.",
    body_en: "There is a lot of fog this morning. I can't see well ahead. The cars go slowly. The fog clears in a little while.",
    questions: [
      { question_en: "What is there a lot of this morning?", options: ["Fog","Snow","Rain","Wind"], answerIndex: 0 },
      { question_en: "How do the cars go?", options: ["Slowly","Not at all","Backward","Fast"], answerIndex: 0 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "기차 여행",
    title_en: "A train trip",
    body_kr: "우리는 기차를 타고 여행해요. 창밖 풍경이 예뻐요. 도시락도 먹어요. 세 시간 후에 도착해요.",
    body_en: "We travel by train. The scenery outside the window is pretty. We also eat a lunch box. We arrive in three hours.",
    questions: [
      { question_en: "How do they travel?", options: ["By boat","By plane","By car","By train"], answerIndex: 3 },
      { question_en: "How long until they arrive?", options: ["One hour","Two hours","Three hours","Five hours"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "공항 가는 길",
    title_en: "The way to the airport",
    body_kr: "내일 우리 가족은 공항에 가요. 캐리어가 아주 무거워요. 아빠가 운전해요. 저는 조금 설레요.",
    body_en: "Tomorrow my family goes to the airport. The suitcase is very heavy. Dad drives. I'm a little excited.",
    questions: [
      { question_en: "Where does the family go tomorrow?", options: ["Airport","Museum","School","Beach"], answerIndex: 0 },
      { question_en: "Who drives?", options: ["Grandpa","Dad","Mom","Sister"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "동물원 나들이",
    title_en: "A zoo outing",
    body_kr: "우리 가족은 동물원에 가요. 코끼리가 아주 커요. 원숭이가 재미있게 놀아요. 하루 종일 즐거워요.",
    body_en: "My family goes to the zoo. The elephant is very big. The monkey plays in a fun way. It's fun all day.",
    questions: [
      { question_en: "Where does the family go?", options: ["Farm","Zoo","Beach","Museum"], answerIndex: 1 },
      { question_en: "Which animal is very big?", options: ["Lion","Elephant","Bird","Monkey"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "놀이공원",
    title_en: "The amusement park",
    body_kr: "오늘은 놀이공원에 가요. 롤러코스터가 무서워요. 그래도 한 번 더 타요. 팝콘도 사 먹어요.",
    body_en: "Today I go to the amusement park. The roller coaster is scary. Still, I ride it once more. I also buy and eat popcorn.",
    questions: [
      { question_en: "What is scary?", options: ["The clown","The maze","The roller coaster","The Ferris wheel"], answerIndex: 2 },
      { question_en: "What does the person eat?", options: ["Candy","Chips","Popcorn","Ice cream"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "산에 가요",
    title_en: "Going to the mountain",
    body_kr: "일요일에 아빠와 산에 가요. 계단이 많아서 힘들어요. 정상에서 경치가 아름다워요. 물을 많이 마셔요.",
    body_en: "On Sunday, I go to the mountain with Dad. There are many steps, so it's tiring. The view from the top is beautiful. I drink a lot of water.",
    questions: [
      { question_en: "Who does the person go with?", options: ["Friend","Mom","Dad","Teacher"], answerIndex: 2 },
      { question_en: "Why is it tiring?", options: ["It's raining","Many steps","It's far","It's hot"], answerIndex: 1 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "수영장에서",
    title_en: "At the swimming pool",
    body_kr: "오늘 학교에서 수영장에 가요. 물이 조금 차가워요. 저는 수영을 열심히 배워요. 끝나고 배가 고파요.",
    body_en: "Today we go to the swimming pool from school. The water is a bit cold. I learn to swim hard. I'm hungry after it ends.",
    questions: [
      { question_en: "How is the water?", options: ["Warm","Dirty","A bit cold","Hot"], answerIndex: 2 },
      { question_en: "How does the person feel after?", options: ["Angry","Cold only","Hungry","Sleepy"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "바다에 가요",
    title_en: "Going to the beach",
    body_kr: "여름에 우리는 바다에 가요. 물이 시원해요. 저는 수영을 해요. 저녁에 집에 와요.",
    body_en: "In summer, we go to the beach. The water is cool. I swim. We come home in the evening.",
    questions: [
      { question_en: "When do they go to the beach?", options: ["Winter","Spring","Fall","Summer"], answerIndex: 3 },
      { question_en: "What does the person do at the beach?", options: ["Study","Sleep","Cook","Swim"], answerIndex: 3 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "짝꿍 이야기",
    title_en: "About my desk partner",
    body_kr: "제 짝꿍 지민이는 아주 친절해요. 저에게 연필을 빌려줘요. 우리는 같이 숙제를 해요. 짝꿍이 있어서 좋아요.",
    body_en: "My desk partner Jimin is very kind. Jimin lends me a pencil. We do homework together. I'm glad to have a desk partner.",
    questions: [
      { question_en: "What does the desk partner lend?", options: ["A phone","Money","A book","A pencil"], answerIndex: 3 },
      { question_en: "What do they do together?", options: ["Cooking","Sports","Homework","Shopping"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "친구 집",
    title_en: "My friend's house",
    body_kr: "오늘 지민이 집에 가요. 지민이 집은 아파트예요. 우리는 게임을 해요. 정말 재미있어요.",
    body_en: "Today I go to Jimin's house. Jimin lives in an apartment. We play games. It's really fun.",
    questions: [
      { question_en: "Where does the friend live?", options: ["A house", "An apartment", "A dorm", "The countryside"], answerIndex: 1 },
      { question_en: "What do they do?", options: ["Study", "Cook", "Play games", "Watch a movie"], answerIndex: 2 },
    ],
  },
  {
    level: "A1",
    genre: "story",
    title_kr: "제 생일",
    title_en: "My birthday",
    body_kr: "제 생일은 오월 십일이에요. 생일에 지민이랑 친구들이 우리 집에 와요. 우리는 케이크를 먹어요. 저는 정말 행복해요.",
    body_en: "My birthday is May 10th. On my birthday Jimin and my other friends come to my house. We eat cake. I'm really happy.",
    questions: [
      { question_en: "When is their birthday?", options: ["May 1st", "May 10th", "October 5th", "June 10th"], answerIndex: 1 },
      { question_en: "What do they eat?", options: ["Cake", "Noodles", "Rice cake", "Pizza"], answerIndex: 0 },
    ],
  },
];
