import type { RawPassage } from "./types";

export const READING_A2_B: RawPassage[] = [
  {
    level: "A2",
    title_kr: "편의점 아르바이트",
    title_en: "A convenience store part-time job",
    body_kr: "저는 지난달부터 편의점에서 아르바이트를 해요. 밤 열 시부터 새벽 두 시까지 일해요. 처음에는 계산이 어려웠지만 지금은 익숙해요. 손님들이 친절해서 일이 재미있어요. 다음 주에는 시급이 오를 거예요.",
    body_en: "I have been working part-time at a convenience store since last month. I work from 10 PM to 2 AM. At first, using the register was hard, but now I'm used to it. The customers are kind, so the work is fun. Next week, my hourly wage will go up.",
    questions: [
      { question_en: "When does the narrator work?", options: ["2 AM to 10 AM","10 AM to 2 PM","2 PM to 10 PM","10 PM to 2 AM"], answerIndex: 3 },
      { question_en: "What will happen next week?", options: ["The store will close","They will change stores","Their wage will increase","They will quit"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "새로운 식당 발견",
    title_en: "Discovering a new restaurant",
    body_kr: "어제 회사 근처에서 새로운 식당을 발견했어요. 메뉴판에 김치찌개와 된장찌개가 있었어요. 저는 김치찌개를 주문했고 정말 맛있었어요. 다음에는 동료와 같이 다시 갈 거예요. 그 식당은 곧 유명해질 것 같아요.",
    body_en: "Yesterday I discovered a new restaurant near my office. The menu had kimchi stew and soybean paste stew. I ordered the kimchi stew and it was really delicious. Next time, I will go again with a coworker. I think that restaurant will become famous soon.",
    questions: [
      { question_en: "Where did the narrator find the restaurant?", options: ["Near their office","At the airport","Downtown","Near their home"], answerIndex: 0 },
      { question_en: "What did the narrator order?", options: ["Kimchi stew","Bibimbap","Bulgogi","Soybean paste stew"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "무선 이어폰을 샀어요",
    title_en: "I bought wireless earbuds",
    body_kr: "저는 오랫동안 무선 이어폰을 갖고 싶었어요. 지난 주말에 드디어 하나를 샀어요. 음질이 아주 좋고 배터리도 오래가요. 요즘은 출근할 때마다 음악을 들어요. 다음에는 케이스도 예쁜 걸로 바꿀 거예요.",
    body_en: "I had wanted wireless earbuds for a long time. Last weekend, I finally bought a pair. The sound quality is great and the battery lasts long. These days, I listen to music every time I commute. Next, I will change to a pretty case too.",
    questions: [
      { question_en: "When did the narrator buy the earbuds?", options: ["Last year","Yesterday","This morning","Last weekend"], answerIndex: 3 },
      { question_en: "What does the narrator plan to do next?", options: ["Change the case","Buy a new phone","Sell the earbuds","Return the earbuds"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "등산 동호회 가입",
    title_en: "Joining a hiking club",
    body_kr: "저는 작년에 등산 동호회에 가입했어요. 매달 한 번 회원들과 같이 산에 가요. 처음에는 힘들었지만 지금은 체력이 좋아졌어요. 지난주에는 북한산에 올라갔어요. 다음 달에는 더 높은 산에 도전할 거예요.",
    body_en: "I joined a hiking club last year. Once a month, I go to the mountains with the members. At first it was hard, but now my stamina has improved. Last week, we climbed Bukhansan. Next month, I will challenge a taller mountain.",
    questions: [
      { question_en: "How often do they hike together?", options: ["Twice a year","Once a month","Every day","Every week"], answerIndex: 1 },
      { question_en: "What mountain did they climb last week?", options: ["Bukhansan","Seoraksan","Hallasan","Jirisan"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "동료와의 점심 약속",
    title_en: "Lunch appointment with a coworker",
    body_kr: "오늘 저는 동료와 점심을 같이 먹기로 했어요. 우리는 회사 근처 국수집에 갔어요. 국수는 시원하고 맛있었어요. 동료는 다음 프로젝트 이야기를 해 줬어요. 내일도 같이 점심을 먹을 계획이에요.",
    body_en: "Today I decided to have lunch with a coworker. We went to a noodle shop near the office. The noodles were cool and delicious. My coworker told me about the next project. We plan to eat lunch together tomorrow too.",
    questions: [
      { question_en: "Where did they eat lunch?", options: ["A bakery","A pizza place","A noodle shop","A cafe"], answerIndex: 2 },
      { question_en: "What did the coworker talk about?", options: ["The next project","Their family","The weather","Their vacation"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "서점 아르바이트생",
    title_en: "The bookstore part-timer",
    body_kr: "저는 대학교 근처 서점에서 아르바이트를 하고 있어요. 책을 정리하고 손님에게 책을 추천해요. 어제는 인기 있는 소설책이 다 팔렸어요. 사장님은 다음 주에 더 주문할 거라고 했어요. 저는 이 일이 정말 즐거워요.",
    body_en: "I am working part-time at a bookstore near the university. I organize books and recommend them to customers. Yesterday, a popular novel completely sold out. The owner said they would order more next week. I really enjoy this job.",
    questions: [
      { question_en: "What sold out yesterday?", options: ["A magazine","A textbook","A comic book","A popular novel"], answerIndex: 3 },
      { question_en: "What will the owner do next week?", options: ["Close the store","Order more books","Lower prices","Hire more staff"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "스마트워치를 선물 받았어요",
    title_en: "I received a smartwatch as a gift",
    body_kr: "지난 생일에 남동생이 스마트워치를 선물해 줬어요. 처음에는 사용법을 잘 몰랐어요. 요즘은 매일 운동량을 확인해요. 오늘은 만 걸음을 걸었어요. 다음에는 수영할 때도 착용해 볼 거예요.",
    body_en: "On my last birthday, my younger brother gave me a smartwatch as a gift. At first, I didn't know how to use it well. These days, I check my exercise stats every day. Today, I walked ten thousand steps. Next, I will try wearing it while swimming too.",
    questions: [
      { question_en: "Who gave the smartwatch as a gift?", options: ["Their sister","Their mother","Their younger brother","Their friend"], answerIndex: 2 },
      { question_en: "How many steps did the narrator walk today?", options: ["Two thousand","Five thousand","Fifteen thousand","Ten thousand"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "사진 동호회 모임",
    title_en: "A photography club meetup",
    body_kr: "저는 사진 찍는 것을 좋아해서 사진 동호회에 가입했어요. 지난 토요일에 처음으로 모임에 나갔어요. 회원들과 공원에서 사진을 찍었어요. 다른 사람들의 사진 실력이 정말 좋았어요. 다음 모임에서는 야경 사진을 찍을 거예요.",
    body_en: "I love taking photos, so I joined a photography club. Last Saturday, I attended a meetup for the first time. I took photos in the park with the members. Other people's photography skills were really impressive. At the next meetup, we will take night scenery photos.",
    questions: [
      { question_en: "Where did they take photos?", options: ["At a park","At a market","At the beach","In a museum"], answerIndex: 0 },
      { question_en: "What will they photograph next time?", options: ["Night scenery","Portraits","Flowers","Food"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "레스토랑 예약 실수",
    title_en: "A restaurant reservation mistake",
    body_kr: "저는 친구 생일에 레스토랑을 예약했어요. 그런데 시간을 잘못 예약했어요. 우리가 도착했을 때 자리가 없었어요. 직원이 다른 자리를 빨리 준비해 줬어요. 다음에는 예약을 두 번 확인할 거예요.",
    body_en: "I made a restaurant reservation for my friend's birthday. But I booked the wrong time. When we arrived, there was no table. The staff quickly prepared another table for us. Next time, I will double-check my reservations.",
    questions: [
      { question_en: "What mistake did the narrator make?", options: ["Wrong time","Wrong date","Wrong restaurant","Wrong number of guests"], answerIndex: 0 },
      { question_en: "What did the staff do?", options: ["Refused them","Gave a discount","Prepared another table","Called a manager"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "커피숍 신메뉴",
    title_en: "The coffee shop's new menu",
    body_kr: "제가 자주 가는 커피숍에서 신메뉴가 나왔어요. 오늘 아침에 새로운 라떼를 마셔 봤어요. 맛이 달콤하고 향이 좋았어요. 바리스타는 이 메뉴가 곧 인기가 많아질 거라고 말했어요. 저는 내일 또 마시러 갈 거예요.",
    body_en: "The coffee shop I often visit released a new menu item. This morning I tried a new latte. It tasted sweet and had a nice aroma. The barista said this drink would soon become popular. I will go drink it again tomorrow.",
    questions: [
      { question_en: "What did the narrator try this morning?", options: ["A new sandwich","A new latte","A new cake","A new tea"], answerIndex: 1 },
      { question_en: "What did the barista predict?", options: ["It would be discontinued","It would be expensive","It would become popular","It would change taste"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "회사 회식",
    title_en: "A company dinner",
    body_kr: "지난 금요일에 회사 회식이 있었어요. 우리는 고깃집에서 삼겹살을 먹었어요. 부장님이 재미있는 이야기를 많이 해 줬어요. 저는 조금 늦게까지 있었어요. 다음 회식은 다음 달에 있을 거예요.",
    body_en: "Last Friday, there was a company dinner. We ate grilled pork belly at a BBQ restaurant. The department head told many funny stories. I stayed a little late. The next company dinner will be next month.",
    questions: [
      { question_en: "What did they eat?", options: ["Chicken","Beef ribs","Grilled pork belly","Fish"], answerIndex: 2 },
      { question_en: "When is the next company dinner?", options: ["Next week","Tomorrow","Next year","Next month"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "태블릿으로 그림 그리기",
    title_en: "Drawing with a tablet",
    body_kr: "저는 최근에 그림 그리는 태블릿을 샀어요. 처음에는 펜 사용법이 어색했어요. 유튜브 영상을 보면서 연습했어요. 이제는 간단한 그림을 그릴 수 있어요. 다음 달에는 온라인 그림 강좌를 들을 거예요.",
    body_en: "I recently bought a drawing tablet. At first, using the pen felt awkward. I practiced by watching YouTube videos. Now I can draw simple pictures. Next month, I will take an online drawing course.",
    questions: [
      { question_en: "How did the narrator practice?", options: ["Taking a class","Asking a friend","Reading a book","Watching YouTube videos"], answerIndex: 3 },
      { question_en: "What will the narrator do next month?", options: ["Buy a new pen","Sell the tablet","Stop drawing","Take an online course"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "편의점 야간 근무",
    title_en: "Working the night shift at a convenience store",
    body_kr: "저는 이번 학기부터 편의점 야간 근무를 시작했어요. 밤에는 손님이 별로 없어요. 그래서 공부할 시간이 조금 있어요. 어젯밤에는 취한 손님이 와서 조금 무서웠어요. 다음에는 더 조심할 거예요.",
    body_en: "I started working the night shift at a convenience store this semester. There aren't many customers at night. So I have a little time to study. Last night, a drunk customer came in and it was a bit scary. Next time, I will be more careful.",
    questions: [
      { question_en: "What does the narrator do during quiet night hours?", options: ["Studies","Cleans","Watches TV","Sleeps"], answerIndex: 0 },
      { question_en: "What happened last night?", options: ["A fire alarm went off","The store closed early","A friend visited","A drunk customer came"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "요가 클럽 첫 수업",
    title_en: "First class at a yoga club",
    body_kr: "저는 스트레스를 풀려고 요가 클럽에 등록했어요. 어제 첫 수업을 들었어요. 자세가 어려워서 몸이 아팠어요. 선생님은 천천히 연습하면 좋아질 거라고 했어요. 저는 다음 주에도 계속 다닐 거예요.",
    body_en: "I registered for a yoga club to relieve stress. Yesterday I took my first class. The poses were hard and my body felt sore. The teacher said it would improve if I practiced slowly. I will keep attending next week too.",
    questions: [
      { question_en: "Why did the narrator join yoga?", options: ["To get fit fast","To make friends","To lose weight","To relieve stress"], answerIndex: 3 },
      { question_en: "What did the teacher say?", options: ["To buy new equipment","To quit if it hurts","It would improve with practice","To join a harder class"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "새 노트북 구입",
    title_en: "Buying a new laptop",
    body_kr: "제 노트북이 너무 오래돼서 느려졌어요. 지난주에 전자제품 매장에 가서 새 노트북을 샀어요. 화면이 크고 속도도 아주 빨라요. 오늘부터 새 노트북으로 일을 시작했어요. 앞으로 일이 더 편해질 거예요.",
    body_en: "My laptop was so old that it became slow. Last week, I went to an electronics store and bought a new laptop. The screen is big and the speed is very fast. Starting today, I began working with the new laptop. Work will become more convenient from now on.",
    questions: [
      { question_en: "Why did the narrator buy a new laptop?", options: ["It was too slow","It was stolen","It was too small","It broke completely"], answerIndex: 0 },
      { question_en: "When did the narrator start using the new laptop?", options: ["Today","Yesterday","Last week","Next month"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "베이커리 아르바이트",
    title_en: "A bakery part-time job",
    body_kr: "저는 지난달부터 빵집에서 아르바이트를 해요. 아침 일찍 출근해서 빵을 진열해요. 갓 구운 빵 냄새가 정말 좋아요. 오늘은 손님이 많아서 아주 바빴어요. 다음 주에는 케이크 만드는 법도 배울 거예요.",
    body_en: "I have been working part-time at a bakery since last month. I go to work early in the morning and arrange the bread. The smell of freshly baked bread is really nice. Today there were many customers, so it was very busy. Next week, I will also learn how to make cakes.",
    questions: [
      { question_en: "What does the narrator do in the morning?", options: ["Arrange bread","Clean tables","Take orders","Bake bread"], answerIndex: 0 },
      { question_en: "What will the narrator learn next week?", options: ["How to manage staff","How to use the register","How to bake bread","How to make cakes"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "배드민턴 동호회",
    title_en: "A badminton club",
    body_kr: "저는 회사 동료들과 배드민턴 동호회를 만들었어요. 매주 수요일 저녁에 체육관에서 연습해요. 처음에는 실력이 부족했지만 지금은 많이 늘었어요. 다음 달에는 다른 회사와 경기를 할 거예요. 저는 그날을 기대하고 있어요.",
    body_en: "I started a badminton club with my coworkers. We practice at a gymnasium every Wednesday evening. At first my skills were lacking, but now I've improved a lot. Next month, we will play a match against another company. I'm looking forward to that day.",
    questions: [
      { question_en: "When do they practice?", options: ["Monday mornings","Sunday afternoons","Friday nights","Wednesday evenings"], answerIndex: 3 },
      { question_en: "What will happen next month?", options: ["A tournament ends","New members join","A match with another company","The club will close"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "친구와 브런치 카페",
    title_en: "Brunch cafe with a friend",
    body_kr: "지난 일요일에 친구와 브런치 카페에 갔어요. 저는 팬케이크를 시켰고 친구는 오믈렛을 시켰어요. 음식이 예쁘고 맛있어서 사진을 많이 찍었어요. 우리는 커피를 마시며 오랫동안 이야기했어요. 다음에는 다른 브런치 카페도 가 볼 거예요.",
    body_en: "Last Sunday, I went to a brunch cafe with a friend. I ordered pancakes and my friend ordered an omelet. The food was pretty and delicious, so we took many photos. We talked for a long time while drinking coffee. Next time, we will try another brunch cafe too.",
    questions: [
      { question_en: "What did the narrator order?", options: ["An omelet","Toast","A sandwich","Pancakes"], answerIndex: 3 },
      { question_en: "What did they do while drinking coffee?", options: ["Worked on laptops","Talked for a long time","Watched a movie","Read books"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "새로운 앱을 다운로드했어요",
    title_en: "I downloaded a new app",
    body_kr: "저는 요즘 시간 관리를 잘 못해서 고민이었어요. 친구가 좋은 앱을 추천해 줬어요. 어제 그 앱을 다운로드해서 사용해 봤어요. 할 일 목록을 정리하니까 훨씬 편해요. 앞으로 매일 이 앱을 사용할 거예요.",
    body_en: "Lately I've been worried because I'm not good at managing my time. My friend recommended a good app. Yesterday I downloaded and tried the app. Organizing my to-do list has made things much easier. I will use this app every day from now on.",
    questions: [
      { question_en: "Who recommended the app?", options: ["A coworker","A friend","A family member","An online review"], answerIndex: 1 },
      { question_en: "What does the app help with?", options: ["Exercise","Language learning","Cooking","Time management"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "독서 모임 참여",
    title_en: "Joining a book club",
    body_kr: "저는 책을 좋아해서 독서 모임에 참여하기 시작했어요. 이번 달 책은 짧은 소설이었어요. 지난주 모임에서 회원들과 책 내용을 이야기했어요. 다양한 생각을 들을 수 있어서 재미있었어요. 다음 달 책도 벌써 기대돼요.",
    body_en: "I love books, so I started participating in a book club. This month's book was a short novel. At last week's meeting, we discussed the book with the members. It was fun to hear various opinions. I'm already looking forward to next month's book.",
    questions: [
      { question_en: "What was this month's book?", options: ["A poetry collection","A history book","A short novel","A cookbook"], answerIndex: 2 },
      { question_en: "What did the narrator enjoy about the meeting?", options: ["Winning a prize","Hearing various opinions","The location","The food"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "피자 가게에서 일해요",
    title_en: "I work at a pizza place",
    body_kr: "저는 주말마다 피자 가게에서 아르바이트를 해요. 저는 배달을 담당하고 있어요. 지난 주말에는 주문이 아주 많아서 정신없이 바빴어요. 사장님이 저에게 시급을 올려 주겠다고 했어요. 저는 이 일을 계속하고 싶어요.",
    body_en: "I work part-time at a pizza place every weekend. I'm in charge of deliveries. Last weekend, there were so many orders that it was hectic. The owner told me they would raise my hourly wage. I want to keep doing this job.",
    questions: [
      { question_en: "What is the narrator's job at the pizza place?", options: ["Cooking","Cleaning","Deliveries","Cashier"], answerIndex: 2 },
      { question_en: "What did the owner promise?", options: ["A raise","New equipment","A promotion","A day off"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "게임 동호회 모임",
    title_en: "A gaming club meetup",
    body_kr: "저는 온라인 게임을 좋아해서 게임 동호회에 가입했어요. 지난주에 처음으로 오프라인 모임에 나갔어요. 회원들과 같이 새로운 게임을 했어요. 다들 친절하고 실력도 좋았어요. 다음 모임에는 대회에도 참가할 거예요.",
    body_en: "I love online games, so I joined a gaming club. Last week, I attended an offline meetup for the first time. I played a new game together with the members. Everyone was kind and skilled. At the next meetup, I will also join a tournament.",
    questions: [
      { question_en: "When did the narrator attend the first meetup?", options: ["Two days ago","Last month","Last week","Yesterday"], answerIndex: 2 },
      { question_en: "What will the narrator do at the next meetup?", options: ["Bring a friend","Quit the club","Watch only","Join a tournament"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "초밥집에서의 첫 경험",
    title_en: "My first experience at a sushi restaurant",
    body_kr: "저는 어제 처음으로 초밥집에 갔어요. 메뉴가 너무 많아서 무엇을 먹을지 고민했어요. 결국 연어 초밥 세트를 주문했어요. 생각보다 훨씬 신선하고 맛있었어요. 다음에는 다른 종류도 도전해 볼 거예요.",
    body_en: "Yesterday I went to a sushi restaurant for the first time. There were so many menu items that I struggled to decide. In the end, I ordered a salmon sushi set. It was much fresher and more delicious than I expected. Next time, I will try other kinds too.",
    questions: [
      { question_en: "What did the narrator order?", options: ["Shrimp tempura","Miso soup only","Tuna sushi set","Salmon sushi set"], answerIndex: 3 },
      { question_en: "How did the food taste compared to expectations?", options: ["Too salty","Worse than expected","Fresher and better","About the same"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "무선 청소기를 샀어요",
    title_en: "I bought a cordless vacuum",
    body_kr: "저는 청소를 편하게 하고 싶어서 무선 청소기를 샀어요. 지난 주말에 온라인으로 주문했어요. 오늘 물건이 도착해서 바로 사용해 봤어요. 가볍고 소음도 적어서 아주 만족스러워요. 앞으로 청소 시간이 훨씬 줄어들 것 같아요.",
    body_en: "I bought a cordless vacuum because I wanted to clean more easily. I ordered it online last weekend. The item arrived today and I tried it right away. It's light and quiet, so I'm very satisfied. Cleaning time will probably be much shorter from now on.",
    questions: [
      { question_en: "When did the narrator order the vacuum?", options: ["Last weekend","Last month","Yesterday","Today"], answerIndex: 0 },
      { question_en: "What does the narrator like about the vacuum?", options: ["It's cheap","It's colorful","It's light and quiet","It's very powerful"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "테니스를 배우기 시작했어요",
    title_en: "I started learning tennis",
    body_kr: "저는 새로운 운동을 배우고 싶어서 테니스 레슨을 등록했어요. 지난주에 첫 수업을 들었어요. 라켓 잡는 법부터 배웠어요. 생각보다 훨씬 어려웠지만 재미있었어요. 다음 달에는 동호회 사람들과 시합도 해 볼 거예요.",
    body_en: "I wanted to learn a new sport, so I signed up for tennis lessons. I took my first class last week. I learned how to hold the racket from the start. It was much harder than expected, but fun. Next month, I will also play a match with club members.",
    questions: [
      { question_en: "What did the narrator learn first?", options: ["How to keep score","How to serve","How to hold the racket","The rules of tennis"], answerIndex: 2 },
      { question_en: "What will the narrator do next month?", options: ["Quit lessons","Play a match","Watch a tournament","Buy new shoes"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "샐러드 가게에서 일해요",
    title_en: "I work at a salad shop",
    body_kr: "저는 건강한 음식에 관심이 많아서 샐러드 가게에서 아르바이트를 시작했어요. 매일 신선한 채소를 손질해요. 손님들에게 재료를 설명하는 것도 제 일이에요. 오늘은 새로운 소스를 추천했더니 손님이 아주 좋아했어요. 이 일을 하면서 저도 채소를 더 좋아하게 됐어요.",
    body_en: "I'm very interested in healthy food, so I started a part-time job at a salad shop. I prepare fresh vegetables every day. Explaining ingredients to customers is also part of my job. Today, I recommended a new sauce and the customer really liked it. While doing this job, I also came to like vegetables more.",
    questions: [
      { question_en: "What is one of the narrator's job duties?", options: ["Washing dishes","Cooking meat","Explaining ingredients","Delivering food"], answerIndex: 2 },
      { question_en: "What happened when the narrator recommended a sauce?", options: ["The sauce ran out","The customer complained","The customer liked it","The customer refused"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "새 스피커로 음악 감상",
    title_en: "Listening to music with a new speaker",
    body_kr: "저는 집에서 음악을 크게 듣고 싶어서 블루투스 스피커를 샀어요. 어제 처음으로 스피커를 연결해 봤어요. 소리가 정말 크고 깨끗했어요. 이웃에게 방해가 되지 않게 조심해야 해요. 주말에는 친구를 불러서 같이 음악을 들을 거예요.",
    body_en: "I wanted to listen to loud music at home, so I bought a Bluetooth speaker. Yesterday I connected the speaker for the first time. The sound was really loud and clear. I need to be careful not to disturb the neighbors. On the weekend, I will invite a friend over to listen to music together.",
    questions: [
      { question_en: "Why did the narrator buy the speaker?", options: ["To listen to loud music","For alarms","For work calls","As a gift"], answerIndex: 0 },
      { question_en: "What does the narrator need to be careful about?", options: ["Battery life","The price","Disturbing neighbors","Losing the speaker"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "베트남 쌀국수 식당",
    title_en: "A Vietnamese pho restaurant",
    body_kr: "저는 요즘 쌀국수에 빠져 있어요. 지난주에 새로 생긴 베트남 식당에 갔어요. 국물이 진하고 향이 좋았어요. 저는 다음에 친구들에게도 그 식당을 소개할 거예요. 오늘도 그 식당에서 점심을 먹었어요.",
    body_en: "Lately I've been obsessed with pho. Last week, I went to a newly opened Vietnamese restaurant. The broth was rich and had a nice aroma. I will introduce that restaurant to my friends next time. I also ate lunch at that restaurant today.",
    questions: [
      { question_en: "What is the narrator obsessed with lately?", options: ["Pho","Pizza","Ramen","Sushi"], answerIndex: 0 },
      { question_en: "What will the narrator do next?", options: ["Introduce the restaurant to friends","Cook pho at home","Stop eating pho","Move away"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "댄스 동호회 첫날",
    title_en: "First day at a dance club",
    body_kr: "저는 춤을 배우고 싶어서 댄스 동호회에 가입했어요. 오늘 첫 수업에 갔어요. 동작이 생각보다 복잡해서 계속 실수했어요. 그래도 선생님과 회원들이 많이 도와줬어요. 저는 다음 주에도 열심히 연습할 거예요.",
    body_en: "I wanted to learn to dance, so I joined a dance club. Today I went to my first class. The moves were more complex than expected, so I kept making mistakes. Still, the teacher and members helped me a lot. I will practice hard next week too.",
    questions: [
      { question_en: "How did the narrator find the dance moves?", options: ["More complex than expected","Too slow","Very easy","Boring"], answerIndex: 0 },
      { question_en: "Who helped the narrator?", options: ["A stranger","Family members","No one","The teacher and members"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "패스트푸드점 아르바이트",
    title_en: "A fast food restaurant part-time job",
    body_kr: "저는 방학 동안 패스트푸드점에서 아르바이트를 해요. 주문받는 일과 음식을 준비하는 일을 해요. 어제는 손님이 너무 많아서 실수를 했어요. 매니저는 괜찮다고 저를 격려해 줬어요. 다음에는 더 빠르고 정확하게 일할 거예요.",
    body_en: "I'm working part-time at a fast food restaurant during vacation. I take orders and prepare food. Yesterday there were so many customers that I made a mistake. The manager encouraged me, saying it was okay. Next time, I will work faster and more accurately.",
    questions: [
      { question_en: "What does the narrator do at work?", options: ["Taking orders and preparing food","Managing staff","Only cleaning","Only cashier duties"], answerIndex: 0 },
      { question_en: "How did the manager react to the mistake?", options: ["Fired the narrator","Ignored it","Encouraged the narrator","Got angry"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "새로운 태블릿 앱",
    title_en: "A new tablet app",
    body_kr: "저는 요리 레시피를 찾으려고 새로운 앱을 설치했어요. 이 앱에는 사진과 함께 자세한 설명이 있어요. 어제 그 앱을 보고 김밥을 만들어 봤어요. 결과가 아주 만족스러웠어요. 다음에는 다른 요리도 도전해 볼 거예요.",
    body_en: "I installed a new app to find cooking recipes. This app has detailed instructions along with photos. Yesterday, I made gimbap by looking at the app. The result was very satisfying. Next time, I will try other dishes too.",
    questions: [
      { question_en: "What did the narrator make using the app?", options: ["Kimchi","Gimbap","Bibimbap","Tteokbokki"], answerIndex: 1 },
      { question_en: "What feature does the app have?", options: ["Photos with detailed instructions","Video only","Only text","Just a shopping list"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "테이크아웃 커피 사업",
    title_en: "A takeout coffee stand job",
    body_kr: "저는 이번 여름에 작은 테이크아웃 커피 가게에서 일해요. 매일 아침 일찍 커피를 내려요. 손님들은 대부분 출근하는 직장인이에요. 오늘은 사장님이 새로운 원두를 소개해 줬어요. 저는 커피 맛을 구분하는 법을 배우고 있어요.",
    body_en: "This summer, I'm working at a small takeout coffee stand. I brew coffee early every morning. Most customers are office workers heading to work. Today, the owner introduced new coffee beans. I'm learning how to distinguish coffee flavors.",
    questions: [
      { question_en: "Who are most of the customers?", options: ["Students","Office workers","Elderly people","Tourists"], answerIndex: 1 },
      { question_en: "What is the narrator learning?", options: ["How to manage money","How to design menus","How to bake","How to distinguish coffee flavors"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "친구와 함께한 볼링",
    title_en: "Bowling with friends",
    body_kr: "지난 토요일에 친구들과 볼링장에 갔어요. 저는 볼링을 처음 쳐 봤어요. 처음에는 공이 계속 옆으로 갔어요. 시간이 지나면서 점점 나아졌어요. 다음에도 친구들과 같이 볼링을 치러 갈 거예요.",
    body_en: "Last Saturday, I went to a bowling alley with friends. It was my first time bowling. At first, the ball kept going sideways. It gradually improved as time passed. I will go bowling with my friends again next time.",
    questions: [
      { question_en: "Was this the narrator's first time bowling?", options: ["Not mentioned","Yes","No, second time","No, they go often"], answerIndex: 1 },
      { question_en: "What happened as time passed?", options: ["They left early","They gave up","They got worse","They gradually improved"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "고객센터 아르바이트",
    title_en: "A customer service center part-time job",
    body_kr: "저는 대학교 방학 동안 고객센터에서 아르바이트를 해요. 전화로 손님의 질문에 답해요. 처음에는 목소리가 떨렸지만 이제는 자신 있어요. 오늘은 어려운 손님을 잘 응대해서 칭찬을 받았어요. 저는 이 경험이 앞으로 큰 도움이 될 거라고 생각해요.",
    body_en: "I'm working part-time at a customer service center during university vacation. I answer customers' questions over the phone. At first my voice trembled, but now I'm confident. Today, I handled a difficult customer well and was praised. I think this experience will be a big help in the future.",
    questions: [
      { question_en: "What does the narrator do at work?", options: ["Answers questions by phone","Manages inventory","Delivers packages","Repairs products"], answerIndex: 0 },
      { question_en: "What happened today?", options: ["They got a raise","The narrator quit","They were praised","They made a mistake"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "떡집 사장님과의 인연",
    title_en: "A connection with the rice cake shop owner",
    body_kr: "저는 동네 떡집에서 오랫동안 떡을 사 왔어요. 사장님은 항상 저를 반갑게 맞아 주세요. 지난주에는 아르바이트 자리가 있다고 물어보셨어요. 저는 흔쾌히 승낙하고 이번 주부터 일을 시작했어요. 앞으로 사장님과 더 가까워질 것 같아요.",
    body_en: "I have been buying rice cakes from a neighborhood rice cake shop for a long time. The owner always greets me warmly. Last week, she asked if I wanted a part-time job. I gladly accepted and started working this week. I think I will grow closer to the owner from now on.",
    questions: [
      { question_en: "What did the owner ask the narrator last week?", options: ["If they wanted a part-time job","To leave a review","To recommend a friend","To buy more rice cakes"], answerIndex: 0 },
      { question_en: "When did the narrator start working?", options: ["This week","Last year","Next month","Last week"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "드론 조종을 배워요",
    title_en: "Learning to fly a drone",
    body_kr: "저는 새로운 취미로 드론 조종을 시작했어요. 지난달에 작은 드론을 하나 샀어요. 처음에는 조종이 서툴러서 나무에 부딪혔어요. 요즘은 공원에서 안전하게 날릴 수 있어요. 다음에는 사진을 찍을 수 있는 드론으로 바꿀 거예요.",
    body_en: "I started flying drones as a new hobby. Last month I bought a small drone. At first, my flying was clumsy and it hit a tree. These days, I can fly it safely in the park. Next, I will switch to a drone that can take photos.",
    questions: [
      { question_en: "What happened at first?", options: ["The drone was stolen","It hit a tree","It broke immediately","It flew away"], answerIndex: 1 },
      { question_en: "What does the narrator plan to do next?", options: ["Quit the hobby","Switch to a photo drone","Join a club","Sell the drone"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "동료의 퇴사 파티",
    title_en: "A coworker's farewell party",
    body_kr: "지난주에 친한 동료가 퇴사했어요. 우리는 회사 근처 술집에서 작은 파티를 열었어요. 다들 그동안의 추억을 이야기했어요. 저는 조금 슬펐지만 좋은 시간이었어요. 그 동료는 새로운 회사에서 다음 달부터 일을 시작할 거예요.",
    body_en: "Last week, a close coworker left the company. We held a small party at a bar near the office. Everyone talked about memories from their time together. I felt a bit sad, but it was a good time. That coworker will start working at a new company next month.",
    questions: [
      { question_en: "Where did they hold the party?", options: ["At the office","At a restaurant downtown","At a bar near the office","At home"], answerIndex: 2 },
      { question_en: "When will the coworker start the new job?", options: ["This week","Tomorrow","Next year","Next month"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "치킨집 배달 아르바이트",
    title_en: "A chicken restaurant delivery job",
    body_kr: "저는 오토바이 면허가 있어서 치킨집에서 배달 아르바이트를 해요. 주말 저녁에는 주문이 정말 많아요. 어제는 비가 와서 배달이 힘들었어요. 그래도 사장님이 따뜻한 커피를 주셨어요. 저는 이 일을 통해 책임감을 배우고 있어요.",
    body_en: "I have a motorcycle license, so I work part-time delivering for a chicken restaurant. There are really many orders on weekend evenings. Yesterday it rained, so delivery was hard. Still, the owner gave me a warm coffee. Through this job, I'm learning responsibility.",
    questions: [
      { question_en: "Why was delivery hard yesterday?", options: ["Traffic","Too many orders","It rained","The bike broke"], answerIndex: 2 },
      { question_en: "What did the owner do for the narrator?", options: ["Gave a day off","Bought a new bike","Gave warm coffee","Raised the pay"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "새로운 게임기를 샀어요",
    title_en: "I bought a new gaming console",
    body_kr: "저는 오랫동안 저축해서 새로운 게임기를 샀어요. 지난 주말에 드디어 물건을 받았어요. 밤새 게임을 하고 싶었지만 참았어요. 오늘은 친구를 초대해서 같이 게임을 했어요. 우리는 다음 주말에도 또 만나기로 했어요.",
    body_en: "I saved up for a long time and bought a new gaming console. Last weekend, I finally received the item. I wanted to play all night but held back. Today, I invited a friend and we played together. We agreed to meet again next weekend.",
    questions: [
      { question_en: "How did the narrator afford the console?", options: ["Borrowed money","Won a contest","Got it as a gift","Saved up for a long time"], answerIndex: 3 },
      { question_en: "What did the narrator do today?", options: ["Sold the console","Played alone all night","Returned the console","Invited a friend to play"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "고기 뷔페에 갔어요",
    title_en: "I went to a meat buffet",
    body_kr: "지난 금요일에 동료들과 고기 뷔페에 갔어요. 종류가 다양해서 무엇을 먹을지 고민했어요. 저는 너무 많이 먹어서 배가 아팠어요. 그래도 다들 즐거운 시간을 보냈어요. 다음에는 조금 천천히 먹을 거예요.",
    body_en: "Last Friday, I went to a meat buffet with coworkers. There were so many varieties that I struggled to decide what to eat. I ate too much and my stomach hurt. Still, everyone had a fun time. Next time, I will eat a bit more slowly.",
    questions: [
      { question_en: "What happened because the narrator ate too much?", options: ["Felt sleepy","Stomach hurt","Felt cold","Got a headache"], answerIndex: 1 },
      { question_en: "What will the narrator do next time?", options: ["Eat more slowly","Not go again","Skip dessert","Bring more friends"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "제빵 클래스 수강",
    title_en: "Taking a baking class",
    body_kr: "저는 빵을 직접 만들어 보고 싶어서 제빵 클래스에 등록했어요. 지난주에 첫 수업에서 식빵을 만들었어요. 반죽이 생각보다 힘들었어요. 그래도 완성된 빵은 정말 맛있었어요. 다음 수업에서는 크루아상을 만들 거예요.",
    body_en: "I wanted to try making bread myself, so I registered for a baking class. Last week, at the first class, I made white bread. Kneading the dough was harder than expected. Still, the finished bread was really delicious. At the next class, I will make croissants.",
    questions: [
      { question_en: "What did the narrator make in the first class?", options: ["Cake","White bread","Croissants","Cookies"], answerIndex: 1 },
      { question_en: "What will they make next?", options: ["Bagels","Cookies","Cake","Croissants"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "동네 마트 캐셔 일",
    title_en: "A neighborhood mart cashier job",
    body_kr: "저는 동네 마트에서 캐셔로 일하고 있어요. 매일 다양한 손님을 만나요. 오늘은 어르신이 무거운 짐을 들고 계셔서 도와드렸어요. 그분은 저에게 고맙다고 사탕을 주셨어요. 이런 작은 일들이 저를 행복하게 해요.",
    body_en: "I'm working as a cashier at a neighborhood mart. I meet various customers every day. Today, an elderly person was carrying heavy bags, so I helped them. They thanked me and gave me candy. Little things like this make me happy.",
    questions: [
      { question_en: "What did the narrator do for the elderly customer?", options: ["Gave a discount","Helped carry heavy bags","Called a taxi","Ordered for them"], answerIndex: 1 },
      { question_en: "What did the customer give the narrator?", options: ["Money","Flowers","A gift card","Candy"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "온라인 쇼핑 앱 문제",
    title_en: "A problem with a shopping app",
    body_kr: "저는 지난주에 온라인 쇼핑 앱으로 신발을 주문했어요. 그런데 도착한 신발의 사이즈가 잘못됐어요. 저는 고객센터에 채팅으로 문의했어요. 직원이 빠르게 교환을 도와줬어요. 다음에는 사이즈를 더 꼼꼼히 확인할 거예요.",
    body_en: "Last week, I ordered shoes through a shopping app. But the shoes that arrived were the wrong size. I contacted customer service via chat. The staff quickly helped me with an exchange. Next time, I will check the size more carefully.",
    questions: [
      { question_en: "What was wrong with the order?", options: ["Missing item","Wrong size","Wrong color","Damaged item"], answerIndex: 1 },
      { question_en: "How did the narrator contact customer service?", options: ["In person","By phone","By chat","By email"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "북카페 아르바이트",
    title_en: "A book cafe part-time job",
    body_kr: "저는 조용한 곳에서 일하고 싶어서 북카페 아르바이트를 시작했어요. 손님들이 책을 읽으며 커피를 마셔요. 저는 커피를 만들고 책을 정리해요. 오늘은 한가해서 저도 책을 조금 읽었어요. 이 일은 저에게 딱 맞는 것 같아요.",
    body_en: "I wanted to work in a quiet place, so I started a part-time job at a book cafe. Customers read books while drinking coffee. I make coffee and organize books. Today it was quiet, so I read a little too. This job seems perfect for me.",
    questions: [
      { question_en: "Why did the narrator choose this job?", options: ["High pay","Free books","Quiet environment","Close to home"], answerIndex: 2 },
      { question_en: "What did the narrator do today?", options: ["Cleaned all day","Read a little","Trained new staff","Left early"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "타코 트럭 발견",
    title_en: "Discovering a taco truck",
    body_kr: "저는 지난 주말에 길에서 타코 트럭을 발견했어요. 처음 보는 음식이라서 궁금했어요. 저는 새우 타코를 주문해서 먹어 봤어요. 매콤하고 아주 맛있었어요. 다음에도 그 트럭을 찾아서 다시 먹으러 갈 거예요.",
    body_en: "Last weekend, I discovered a taco truck on the street. It was food I hadn't seen before, so I was curious. I ordered and tried a shrimp taco. It was spicy and really delicious. I will find that truck again and go eat there next time.",
    questions: [
      { question_en: "What did the narrator order?", options: ["Beef taco","Shrimp taco","Vegetable taco","Chicken taco"], answerIndex: 1 },
      { question_en: "How did the taco taste?", options: ["Spicy and delicious","Too salty","Bland","Sweet"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "회사 동아리 사진전",
    title_en: "The company club's photo exhibition",
    body_kr: "저는 회사 사진 동아리 회원이에요. 지난달부터 작은 전시회를 준비했어요. 오늘 드디어 전시회가 열렸어요. 많은 동료들이 와서 사진을 구경했어요. 저는 다음 전시회를 위해 더 좋은 사진을 찍을 거예요.",
    body_en: "I'm a member of my company's photography club. We have been preparing a small exhibition since last month. Today the exhibition finally opened. Many coworkers came to look at the photos. I will take better photos for the next exhibition.",
    questions: [
      { question_en: "How long did they prepare for the exhibition?", options: ["One week","One year","Two days","Since last month"], answerIndex: 3 },
      { question_en: "Who came to the exhibition?", options: ["Only family","Many coworkers","Strangers only","No one"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "무인 카페 이용",
    title_en: "Using an unmanned cafe",
    body_kr: "저는 처음으로 무인 카페에 가 봤어요. 직원이 없어서 조금 어색했어요. 기계로 커피를 주문하고 결제했어요. 커피 맛은 괜찮았지만 조금 아쉬웠어요. 다음에는 다시 사람이 있는 카페에 갈 것 같아요.",
    body_en: "I went to an unmanned cafe for the first time. It felt a bit awkward with no staff. I ordered and paid for coffee using a machine. The coffee tasted fine but was a bit disappointing. Next time, I will probably go to a cafe with staff again.",
    questions: [
      { question_en: "How did the narrator feel about the unmanned cafe?", options: ["Bored","Angry","A bit awkward","Very excited"], answerIndex: 2 },
      { question_en: "How did the coffee taste?", options: ["Fine but disappointing","Terrible","Too sweet","Excellent"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "동료와 함께한 볼링 대회",
    title_en: "A bowling tournament with coworkers",
    body_kr: "저희 회사는 매년 볼링 대회를 열어요. 지난주에 저희 팀도 참가했어요. 저는 처음에 점수가 낮았지만 점점 좋아졌어요. 우리 팀은 아쉽게 2등을 했어요. 내년에는 꼭 1등을 하고 싶어요.",
    body_en: "My company holds a bowling tournament every year. Last week, our team participated too. My score was low at first, but it kept improving. Our team unfortunately came in second place. Next year, I really want to come in first.",
    questions: [
      { question_en: "What place did the team finish?", options: ["Last place","Second place","Third place","First place"], answerIndex: 1 },
      { question_en: "What is the narrator's goal for next year?", options: ["To come in first","To join another team","To watch only","To skip the event"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "새로운 헬스장 등록",
    title_en: "Registering at a new gym",
    body_kr: "저는 집 근처에 새로운 헬스장이 생겨서 등록했어요. 트레이너가 운동 계획을 짜 줬어요. 처음 며칠은 온몸이 아팠어요. 지금은 조금씩 익숙해지고 있어요. 다음 달에는 개인 레슨도 받아 볼 거예요.",
    body_en: "A new gym opened near my house, so I signed up. The trainer made an exercise plan for me. My whole body was sore for the first few days. Now I'm gradually getting used to it. Next month, I will also try personal training.",
    questions: [
      { question_en: "Who made the exercise plan?", options: ["The trainer","The narrator","A friend","A doctor"], answerIndex: 0 },
      { question_en: "What will the narrator try next month?", options: ["Swimming","A new gym","Group classes","Personal training"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "라멘집 웨이팅",
    title_en: "Waiting in line at a ramen shop",
    body_kr: "저는 유명한 라멘집에 가 봤어요. 사람이 너무 많아서 한 시간을 기다렸어요. 드디어 자리에 앉아서 라멘을 주문했어요. 국물이 진하고 면이 쫄깃했어요. 기다린 시간이 아깝지 않았어요.",
    body_en: "I went to a famous ramen shop. There were so many people that I waited an hour. Finally, I sat down and ordered ramen. The broth was rich and the noodles were chewy. The waiting time was not wasted.",
    questions: [
      { question_en: "How long did the narrator wait?", options: ["Fifteen minutes","Two hours","One hour","Thirty minutes"], answerIndex: 2 },
      { question_en: "How did the narrator feel about the wait afterward?", options: ["Disappointed","It was worth it","Regretted it","Angry"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "동아리 회비 관리",
    title_en: "Managing the club's membership fees",
    body_kr: "저는 등산 동호회의 총무를 맡고 있어요. 매달 회비를 걷고 관리해요. 지난달에는 회비로 새 장비를 샀어요. 회원들이 모두 만족스러워했어요. 다음 달에는 회식 비용으로 사용할 계획이에요.",
    body_en: "I'm in charge of managing the finances for my hiking club. I collect and manage membership fees every month. Last month, we used the fees to buy new equipment. All the members were satisfied. Next month, we plan to use it for a group dinner.",
    questions: [
      { question_en: "What is the narrator's role in the club?", options: ["Photographer","President","Guide","Treasurer/manager of fees"], answerIndex: 3 },
      { question_en: "What was the fee used for last month?", options: ["T-shirts","New equipment","A trip","A dinner"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "야외 바비큐 파티",
    title_en: "An outdoor barbecue party",
    body_kr: "지난 토요일에 친구들과 야외에서 바비큐 파티를 했어요. 저는 고기를 굽는 역할을 맡았어요. 처음에는 불 조절이 어려웠어요. 하지만 결국 고기를 맛있게 구웠어요. 다음에도 이런 모임을 자주 가질 거예요.",
    body_en: "Last Saturday, I had a barbecue party outdoors with friends. I was in charge of grilling the meat. At first, controlling the fire was hard. But in the end, I grilled the meat deliciously. We will have gatherings like this often in the future.",
    questions: [
      { question_en: "What was the narrator's role?", options: ["Grilling meat","Setting the table","Buying supplies","Cleaning up"], answerIndex: 0 },
      { question_en: "What was difficult at first?", options: ["Controlling the fire","Inviting friends","Choosing meat","Finding a location"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "중고 거래 앱 사용",
    title_en: "Using a secondhand trading app",
    body_kr: "저는 안 쓰는 물건을 팔려고 중고 거래 앱을 사용해 봤어요. 어제 오래된 카메라를 올렸어요. 몇 시간 만에 연락이 왔어요. 오늘 그 사람을 만나서 물건을 팔았어요. 앞으로도 이 앱을 자주 사용할 것 같아요.",
    body_en: "I tried using a secondhand trading app to sell things I don't use. Yesterday, I listed an old camera. Someone contacted me within a few hours. Today, I met that person and sold the item. I will probably use this app often from now on.",
    questions: [
      { question_en: "What did the narrator sell?", options: ["A bicycle","A phone","A laptop","A camera"], answerIndex: 3 },
      { question_en: "When did the narrator sell the item?", options: ["Last week","Today","Yesterday","Next week"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    title_kr: "디저트 카페 순례",
    title_en: "A dessert cafe tour",
    body_kr: "저는 디저트를 좋아해서 친구와 카페 순례를 했어요. 오늘 세 곳의 카페를 방문했어요. 각 카페마다 다른 케이크를 먹었어요. 저는 초콜릿 케이크가 가장 맛있었어요. 다음에는 더 많은 카페를 찾아볼 거예요.",
    body_en: "I love desserts, so I went on a cafe tour with a friend. Today we visited three cafes. We ate different cakes at each cafe. For me, the chocolate cake was the most delicious. Next time, I will look for even more cafes.",
    questions: [
      { question_en: "How many cafes did they visit today?", options: ["Five","Four","Three","Two"], answerIndex: 2 },
      { question_en: "Which cake did the narrator like best?", options: ["Chocolate cake","Cheese cake","Lemon cake","Strawberry cake"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "회사 인턴 첫날",
    title_en: "First day as a company intern",
    body_kr: "저는 오늘 회사에서 인턴으로 첫 출근을 했어요. 아침에 너무 긴장돼서 잠을 잘 못 잤어요. 다행히 팀장님과 동료들이 친절하게 대해 줬어요. 저는 간단한 업무부터 배우기 시작했어요. 앞으로 이 회사에서 많은 것을 배우고 싶어요.",
    body_en: "Today was my first day going to work as an intern at a company. I was so nervous in the morning that I couldn't sleep well. Fortunately, the team leader and coworkers treated me kindly. I started learning simple tasks first. I want to learn a lot at this company from now on.",
    questions: [
      { question_en: "How did the narrator feel in the morning?", options: ["Nervous","Calm","Angry","Bored"], answerIndex: 0 },
      { question_en: "How did the team treat the narrator?", options: ["They ignored them","Coldly","Strictly","Kindly"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "만화 카페에서 보낸 오후",
    title_en: "An afternoon spent at a manga cafe",
    body_kr: "저는 비 오는 날 만화 카페에 갔어요. 편안한 소파에서 만화책을 읽었어요. 간식도 팔아서 컵라면을 먹었어요. 시간 가는 줄 모르고 세 시간을 보냈어요. 다음 비 오는 날에도 다시 갈 거예요.",
    body_en: "I went to a manga cafe on a rainy day. I read manga in a comfortable sofa. They also sell snacks, so I ate cup noodles. I spent three hours without noticing the time. I will go again on the next rainy day.",
    questions: [
      { question_en: "What did the narrator do at the manga cafe?", options: ["Played games","Slept","Watched movies","Read manga"], answerIndex: 3 },
      { question_en: "How long did the narrator stay?", options: ["Thirty minutes","Five hours","Three hours","One hour"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "동료의 실수를 도와줬어요",
    title_en: "I helped a coworker with a mistake",
    body_kr: "오늘 동료가 중요한 파일을 실수로 지웠어요. 그는 매우 당황해했어요. 저는 예전에 백업해 둔 파일이 있어서 도와줬어요. 동료는 정말 고마워했어요. 다음부터는 항상 파일을 백업해 두기로 했어요.",
    body_en: "Today, a coworker accidentally deleted an important file. He was very flustered. I had a backup file from before, so I helped him. My coworker was really grateful. From now on, we decided to always back up files.",
    questions: [
      { question_en: "What did the coworker do by mistake?", options: ["Lost a report","Deleted an important file","Missed a meeting","Sent the wrong email"], answerIndex: 1 },
      { question_en: "How did the narrator help?", options: ["Asked the boss","Called IT support","Rewrote the file","Used a backup file"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    title_kr: "새로운 헤드폰 리뷰",
    title_en: "Reviewing new headphones",
    body_kr: "저는 유튜브를 보다가 헤드폰 리뷰 영상을 봤어요. 평이 좋아서 저도 하나 샀어요. 어제 물건이 도착해서 착용해 봤어요. 소리가 정말 선명했어요. 저도 리뷰를 남겨서 다른 사람들에게 도움을 주고 싶어요.",
    body_en: "While watching YouTube, I saw a headphone review video. The reviews were good, so I bought a pair too. The item arrived yesterday and I tried wearing them. The sound was really clear. I want to leave a review too, to help other people.",
    questions: [
      { question_en: "How did the narrator learn about the headphones?", options: ["A YouTube review","An advertisement","A store display","A friend told them"], answerIndex: 0 },
      { question_en: "What does the narrator want to do?", options: ["Leave a review","Buy another pair","Sell them","Return the headphones"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    title_kr: "베이킹 재료를 사러 갔어요",
    title_en: "I went to buy baking ingredients",
    body_kr: "저는 주말에 쿠키를 만들려고 재료를 사러 갔어요. 마트에서 밀가루와 버터를 샀어요. 계산할 때 직원이 친절하게 도와줬어요. 집에 와서 바로 쿠키를 만들기 시작했어요. 완성된 쿠키는 가족 모두가 좋아했어요.",
    body_en: "I went to buy ingredients to make cookies on the weekend. I bought flour and butter at the mart. When checking out, the staff helped me kindly. I came home and started making cookies right away. The whole family loved the finished cookies.",
    questions: [
      { question_en: "What did the narrator buy?", options: ["Sugar and eggs","Rice and salt","Milk and chocolate","Flour and butter"], answerIndex: 3 },
      { question_en: "Who liked the finished cookies?", options: ["Neighbors","Only the narrator","The whole family","No one"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    title_kr: "축구 동호회 첫 경기",
    title_en: "First match with a soccer club",
    body_kr: "저는 지난달에 동네 축구 동호회에 가입했어요. 오늘 처음으로 경기에 참가했어요. 너무 긴장돼서 실수를 몇 번 했어요. 그래도 팀원들이 격려해 줬어요. 다음 경기에서는 더 잘할 거예요.",
    body_en: "I joined a neighborhood soccer club last month. Today I participated in a match for the first time. I was so nervous that I made a few mistakes. Still, my teammates encouraged me. I will do better in the next match.",
    questions: [
      { question_en: "When did the narrator join the club?", options: ["This week","Today","Last month","Last year"], answerIndex: 2 },
      { question_en: "How did the teammates react to the mistakes?", options: ["Laughed at them","Ignored them","Got angry","Encouraged the narrator"], answerIndex: 3 },
    ],
  },
];
