import type { RawPassage } from "./types";

export const READING_A2_DIARY: RawPassage[] = [
  {
    level: "A2",
    genre: "diary",
    title_kr: "한국어 수업",
    title_en: "Korean class", title_ja: "韓国語の授業",
    body_kr: "저는 일주일에 두 번 한국어 수업을 들어요. 선생님이 친절해서 수업이 재미있어요. 숙제가 조금 많지만 실력이 늘고 있어요. 내년에는 시험을 볼 거예요.",
    body_en: "I take Korean class twice a week. The teacher is kind, so the class is fun. There is a bit of homework, but my skills are improving. Next year I'm going to take an exam.", body_ja: "私は週に2回、韓国語の授業を受けています。先生が親切なので授業が楽しいです。宿題が少し多いですが、実力が伸びています。来年は試験を受けるつもりです。",
    questions: [
      { question_en: "How often is the class?", question_ja: "授業はどのくらいの頻度でありますか。", options: ["Twice a week", "Once a week", "Every day", "Three times a week"], answerIndex: 0 },
      { question_en: "What does the person plan to do next year?", question_ja: "来年、何をする予定ですか。", options: ["Take an exam", "Move to Korea", "Teach a class", "Stop studying"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "카페 아르바이트",
    title_en: "A part-time job at a cafe", title_ja: "カフェのアルバイト",
    body_kr: "저는 카페에서 아르바이트를 해요. 일주일에 세 번 일해요. 손님이 많을 때는 조금 힘들어요. 하지만 사장님이 친절해서 괜찮아요. 커피 만드는 것도 배웠어요. 다음 달까지 일할 거예요.",
    body_en: "I work part-time at a cafe. I work three times a week. When there are a lot of customers it's a bit tough. But the owner is kind, so it's fine. I also learned how to make coffee. I'll work there until next month.", body_ja: "私はカフェでアルバイトをしています。週に3回働いています。お客さんが多いときは少し大変です。でも店長さんが親切なので大丈夫です。コーヒーの淹れ方も習いました。来月まで働くつもりです。",
    questions: [
      { question_en: "How often do they work?", question_ja: "どのくらいの頻度で働いていますか。", options: ["Every day", "Twice a week", "Three times a week", "Only weekends"], answerIndex: 2 },
      { question_en: "What did they learn?", question_ja: "何を習いましたか。", options: ["How to make coffee", "How to bake bread", "How to use a register", "How to speak English"], answerIndex: 0 },
      { question_en: "Why is the job okay despite busy days?", question_ja: "忙しい日でも仕事が大丈夫な理由は何ですか。", options: ["The pay is high", "The owner is kind", "The hours are short", "The cafe is near home"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "새 직장",
    title_en: "A new job", title_ja: "新しい職場",
    body_kr: "저는 지난달에 새 회사에 들어갔어요. 처음에는 사람들 이름을 몰라서 좀 어려웠어요. 지금은 동료들과 많이 친해졌어요. 일은 재미있지만 조금 바빠요. 앞으로 더 잘하고 싶어요.",
    body_en: "I started at a new company last month. At first it was hard because I didn't know people's names. Now I've become close with my coworkers. The work is interesting but a bit busy. I want to do better from now on.", body_ja: "私は先月、新しい会社に入りました。最初は人の名前がわからなくて少し大変でした。今は同僚たちととても仲良くなりました。仕事は面白いですが少し忙しいです。これからもっと頑張りたいです。",
    questions: [
      { question_en: "What was difficult at first?", question_ja: "最初、何が大変でしたか。", options: ["The commute", "Not knowing people's names", "The computer system", "The working hours"], answerIndex: 1 },
      { question_en: "How do they feel about the work?", question_ja: "仕事についてどう感じていますか。", options: ["Boring but easy", "Interesting but busy", "Too difficult", "Not what they expected"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "수영을 배워요",
    title_en: "Learning to swim", title_ja: "水泳を習っています",
    body_kr: "저는 지난달부터 수영을 배워요. 일주일에 두 번 수영장에 가요. 처음에는 물이 조금 무서웠어요. 지금은 많이 익숙해졌어요. 건강해진 것 같아서 기분이 좋아요.",
    body_en: "I've been learning to swim since last month. I go to the pool twice a week. At first the water was a little scary. Now I've gotten used to it. I feel good because I think I've gotten healthier.", body_ja: "私は先月から水泳を習っています。週に2回プールに行きます。最初は水が少し怖かったです。今はだいぶ慣れました。健康になった気がして気分がいいです。",
    questions: [
      { question_en: "How often do they go to the pool?", question_ja: "どのくらいの頻度でプールに行きますか。", options: ["Every day", "Twice a week", "Once a month", "Three times a week"], answerIndex: 1 },
      { question_en: "How did they feel at first?", question_ja: "最初、どう感じましたか。", options: ["Bored", "Confident", "A little scared of the water", "Angry"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "옆집 할머니",
    title_en: "The grandmother next door", title_ja: "隣のおばあさん",
    body_kr: "우리 옆집에 할머니가 사세요. 할머니는 만날 때마다 인사를 해 주세요. 가끔 반찬도 나눠 주세요. 그래서 저도 과일을 사서 드렸어요. 이웃이 좋아서 이 동네가 마음에 들어요.",
    body_en: "A grandmother lives next door to us. She greets me every time we meet. Sometimes she shares side dishes too. So I bought some fruit and gave it to her. I like this neighborhood because the neighbors are nice.", body_ja: "うちの隣におばあさんが住んでいます。会うたびに挨拶をしてくれます。時々おかずも分けてくれます。だから私も果物を買って差し上げました。ご近所さんが優しいので、この町が気に入っています。",
    questions: [
      { question_en: "What does the neighbor share?", question_ja: "隣の人は何を分けてくれますか。", options: ["Side dishes", "Money", "Books", "Flowers"], answerIndex: 0 },
      { question_en: "What did the writer give in return?", question_ja: "書き手はお返しに何をあげましたか。", options: ["A card", "Fruit", "Rice", "Nothing"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "카페에서 공부하기",
    title_en: "Studying at a cafe", title_ja: "カフェで勉強する",
    body_kr: "저는 주말마다 카페에서 공부해요. 집에서는 자꾸 눕고 싶어져요. 카페는 조금 시끄럽지만 집중이 더 잘 돼요. 보통 세 시간쯤 있다가 나와요. 가끔 커피값이 아까울 때도 있어요.",
    body_en: "Every weekend I study at a cafe. At home I keep wanting to lie down. The cafe is a bit noisy, but I concentrate better. I usually stay about three hours and then leave. Sometimes I feel the coffee is a waste of money.", body_ja: "私は週末ごとにカフェで勉強します。家ではつい横になりたくなります。カフェは少しうるさいですが、もっと集中できます。だいたい3時間くらいいてから出ます。時々コーヒー代がもったいないと感じることもあります。",
    questions: [
      { question_en: "Why don't they study at home?", question_ja: "なぜ家で勉強しないのですか。", options: ["It's too quiet", "They keep wanting to lie down", "Their family is loud", "There is no desk"], answerIndex: 1 },
      { question_en: "How long do they usually stay?", question_ja: "普段どのくらいの時間いますか。", options: ["One hour", "Two hours", "About three hours", "All day"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "자전거 타기",
    title_en: "Riding a bicycle", title_ja: "自転車に乗る",
    body_kr: "작년에 자전거를 한 대 샀어요. 주말에는 한강에 가서 자전거를 타요. 처음에는 다리가 많이 아팠어요. 이제는 두 시간도 탈 수 있어요. 자전거를 타면 스트레스가 풀려요.",
    body_en: "Last year I bought a bicycle. On weekends I go to the Han River and ride. At first my legs hurt a lot. Now I can ride for two hours. Riding relieves my stress.", body_ja: "去年、自転車を1台買いました。週末は漢江に行って自転車に乗ります。最初は足がとても痛かったです。今は2時間でも乗れます。自転車に乗るとストレスが解消されます。",
    questions: [
      { question_en: "Where do they ride on weekends?", question_ja: "週末はどこで自転車に乗りますか。", options: ["In a park near home", "At the Han River", "Around their neighborhood", "At a bicycle track"], answerIndex: 1 },
      { question_en: "How long can they ride now?", question_ja: "今はどのくらいの時間乗れますか。", options: ["Thirty minutes", "One hour", "Two hours", "All day"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "시험 공부",
    title_en: "Studying for a test", title_ja: "試験勉強",
    body_kr: "다음 주에 한국어 시험이 있어요. 그래서 요즘 매일 도서관에 가요. 단어를 외우고 듣기 연습을 해요. 좀 힘들지만 열심히 하고 있어요. 시험을 잘 보고 싶어요.",
    body_en: "I have a Korean test next week. So these days I go to the library every day. I memorize words and practice listening. It's a bit tiring, but I'm working hard. I want to do well on the test.", body_ja: "来週、韓国語の試験があります。だから最近は毎日図書館に行きます。単語を覚えてリスニング練習をします。少し大変ですが頑張っています。試験でいい結果を出したいです。",
    questions: [
      { question_en: "When is the test?", question_ja: "試験はいつですか。", options: ["Today", "Tomorrow", "Next week", "Next month"], answerIndex: 2 },
      { question_en: "Where do they study?", question_ja: "どこで勉強しますか。", options: ["At home", "At a cafe", "At the library", "At school"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "운동을 시작했어요",
    title_en: "I started exercising", title_ja: "運動を始めました",
    body_kr: "이번 달부터 아침 운동을 시작했어요. 매일 삼십 분씩 공원에서 뛰어요. 처음 일주일은 정말 힘들었어요. 그런데 지금은 몸이 가벼워요. 밤에 잠도 잘 자요. 내일도 뛸 거예요.",
    body_en: "I started morning exercise this month. I run in the park for thirty minutes every day. The first week was really hard. But now my body feels light. I sleep well at night too. I'll run again tomorrow.", body_ja: "今月から朝の運動を始めました。毎日30分ずつ公園で走ります。最初の1週間は本当に大変でした。でも今は体が軽いです。夜もよく眠れます。明日も走るつもりです。",
    questions: [
      { question_en: "How long do they run?", question_ja: "どのくらいの時間走りますか。", options: ["Ten minutes", "Thirty minutes", "An hour", "Two hours"], answerIndex: 1 },
      { question_en: "What improved?", question_ja: "何が良くなりましたか。", options: ["Their cooking", "Their Korean", "Their sleep", "Their grades"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "새 카메라",
    title_en: "A new camera", title_ja: "新しいカメラ",
    body_kr: "생일 선물로 카메라를 받았어요. 요즘 매일 사진을 찍어요. 하늘, 음식, 강아지를 찍어요. 사진을 SNS에 올려요. 사람들이 '좋아요'를 눌러 줘요. 사진 찍기가 제 새 취미예요.",
    body_en: "I got a camera as a birthday present. These days I take photos every day. I photograph the sky, food, and my dog. I post the photos on social media. People press 'like'. Photography is my new hobby.", body_ja: "誕生日プレゼントにカメラをもらいました。最近は毎日写真を撮っています。空や食べ物、犬の写真を撮ります。写真をSNSに載せます。みんなが「いいね」を押してくれます。写真を撮ることが私の新しい趣味です。",
    questions: [
      { question_en: "How did they get the camera?", question_ja: "どうやってカメラを手に入れましたか。", options: ["They bought it", "As a birthday present", "They borrowed it", "They won it"], answerIndex: 1 },
      { question_en: "What is their new hobby?", question_ja: "新しい趣味は何ですか。", options: ["Cooking", "Running", "Photography", "Painting"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "쓰레기 버리는 날",
    title_en: "Trash day", title_ja: "ゴミを出す日",
    body_kr: "한국에서는 쓰레기를 나눠서 버려야 해요. 음식물 쓰레기는 노란 봉투에 버려요. 플라스틱과 캔은 재활용해요. 처음에는 너무 복잡했어요. 그런데 지금은 익숙해졌어요. 환경에도 좋은 일이에요.",
    body_en: "In Korea you have to separate your trash. Food waste goes in the yellow bag. Plastic and cans get recycled. At first it was so complicated. But now I'm used to it. It's good for the environment too.", body_ja: "韓国ではゴミを分けて捨てなければいけません。生ゴミは黄色い袋に捨てます。プラスチックと缶はリサイクルします。最初はとても複雑でした。でも今は慣れました。環境にもいいことです。",
    questions: [
      { question_en: "Where does food waste go?", question_ja: "生ゴミはどこに捨てますか。", options: ["The blue bag", "The yellow bag", "The recycling bin", "Anywhere"], answerIndex: 1 },
      { question_en: "How do they feel about it now?", question_ja: "今はそれについてどう感じていますか。", options: ["Still confused", "Used to it", "Annoyed", "They gave up"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "아침 조깅",
    title_en: "Morning jogging", title_ja: "朝のジョギング",
    body_kr: "요즘 저는 매일 아침에 조깅을 해요. 오늘은 늦잠을 자서 조깅을 못 했어요. 대신 저녁에 공원에서 뛰었어요. 저녁 공기가 시원해서 기분이 좋았어요. 내일부터는 다시 아침에 뛸 거예요.",
    body_en: "These days I jog every morning. Today I overslept and couldn't jog. Instead, I ran in the park in the evening. The evening air was cool, so I felt good. From tomorrow, I will run in the mornings again.", body_ja: "最近、私は毎朝ジョギングをしています。今日は寝坊してジョギングができませんでした。代わりに夕方、公園で走りました。夕方の空気が涼しくて気分が良かったです。明日からはまた朝に走るつもりです。",
    questions: [
      { question_en: "Why couldn't the narrator jog in the morning?", question_ja: "なぜ主人公は朝ジョギングができませんでしたか。", options: ["Was sick","It was raining","Had no time","Overslept"], answerIndex: 3 },
      { question_en: "When did the narrator run instead?", question_ja: "主人公は代わりにいつ走りましたか。", options: ["Not at all","Night","Afternoon","Evening"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "텃밭을 가꿔요",
    title_en: "Tending a small garden", title_ja: "家庭菜園を育てています",
    body_kr: "저는 지난봄부터 작은 텃밭을 가꾸고 있어요. 상추와 토마토를 심었어요. 며칠 전에는 벌레 때문에 상추가 조금 상했어요. 그래도 토마토는 잘 자라고 있어요. 다음 달에는 첫 토마토를 수확할 거예요.",
    body_en: "I have been tending a small garden since last spring. I planted lettuce and tomatoes. A few days ago, the lettuce got a little damaged because of insects. Still, the tomatoes are growing well. Next month I will harvest the first tomatoes.", body_ja: "私は去年の春から小さな家庭菜園を育てています。レタスとトマトを植えました。数日前、虫のせいでレタスが少し傷みました。それでもトマトはよく育っています。来月には最初のトマトを収穫するつもりです。",
    questions: [
      { question_en: "What did the narrator plant?", question_ja: "主人公は何を植えましたか。", options: ["Carrots","Lettuce and tomatoes","Only tomatoes","Only lettuce"], answerIndex: 1 },
      { question_en: "What damaged the lettuce?", question_ja: "何がレタスを傷めましたか。", options: ["A dog","Sunlight","Insects","Rain"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "편의점 아르바이트",
    title_en: "A convenience store part-time job", title_ja: "コンビニのアルバイト",
    body_kr: "저는 지난달부터 편의점에서 아르바이트를 해요. 밤 열 시부터 새벽 두 시까지 일해요. 처음에는 계산이 어려웠지만 지금은 익숙해요. 손님들이 친절해서 일이 재미있어요. 다음 주에는 시급이 오를 거예요.",
    body_en: "I have been working part-time at a convenience store since last month. I work from 10 PM to 2 AM. At first, using the register was hard, but now I'm used to it. The customers are kind, so the work is fun. Next week, my hourly wage will go up.", body_ja: "私は先月からコンビニでアルバイトをしています。夜10時から明け方2時まで働きます。最初はレジが難しかったですが、今は慣れました。お客さんが親切なので仕事が楽しいです。来週、時給が上がるそうです。",
    questions: [
      { question_en: "When does the narrator work?", question_ja: "主人公はいつ働いていますか。", options: ["2 AM to 10 AM","10 AM to 2 PM","2 PM to 10 PM","10 PM to 2 AM"], answerIndex: 3 },
      { question_en: "What will happen next week?", question_ja: "来週、何が起こりますか。", options: ["The store will close","They will change stores","Their wage will increase","They will quit"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "등산 동호회 가입",
    title_en: "Joining a hiking club", title_ja: "登山サークルに入会",
    body_kr: "저는 작년에 등산 동호회에 가입했어요. 매달 한 번 회원들과 같이 산에 가요. 처음에는 힘들었지만 지금은 체력이 좋아졌어요. 지난주에는 북한산에 올라갔어요. 다음 달에는 더 높은 산에 도전할 거예요.",
    body_en: "I joined a hiking club last year. Once a month, I go to the mountains with the members. At first it was hard, but now my stamina has improved. Last week, we climbed Bukhansan. Next month, I will challenge a taller mountain.", body_ja: "私は去年、登山サークルに入会しました。月に1回、会員たちと一緒に山に行きます。最初は大変でしたが、今は体力がついてきました。先週は北漢山に登りました。来月はもっと高い山に挑戦するつもりです。",
    questions: [
      { question_en: "How often do they hike together?", question_ja: "どのくらいの頻度で一緒に登山しますか。", options: ["Twice a year","Once a month","Every day","Every week"], answerIndex: 1 },
      { question_en: "What mountain did they climb last week?", question_ja: "先週はどの山に登りましたか。", options: ["Bukhansan","Seoraksan","Hallasan","Jirisan"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "서점 아르바이트생",
    title_en: "The bookstore part-timer", title_ja: "書店のアルバイトスタッフ",
    body_kr: "저는 대학교 근처 서점에서 아르바이트를 하고 있어요. 책을 정리하고 손님에게 책을 추천해요. 어제는 인기 있는 소설책이 다 팔렸어요. 사장님은 다음 주에 더 주문할 거라고 했어요. 저는 이 일이 정말 즐거워요.",
    body_en: "I am working part-time at a bookstore near the university. I organize books and recommend them to customers. Yesterday, a popular novel completely sold out. The owner said they would order more next week. I really enjoy this job.", body_ja: "私は大学の近くの書店でアルバイトをしています。本を整理してお客さんに本を勧めます。昨日、人気の小説が全部売り切れました。店長は来週もっと注文すると言いました。私はこの仕事が本当に楽しいです。",
    questions: [
      { question_en: "What sold out yesterday?", question_ja: "昨日、何が売り切れましたか。", options: ["A magazine","A textbook","A comic book","A popular novel"], answerIndex: 3 },
      { question_en: "What will the owner do next week?", question_ja: "店長は来週何をしますか。", options: ["Close the store","Order more books","Lower prices","Hire more staff"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "태블릿으로 그림 그리기",
    title_en: "Drawing with a tablet", title_ja: "タブレットで絵を描く",
    body_kr: "저는 최근에 그림 그리는 태블릿을 샀어요. 처음에는 펜 사용법이 어색했어요. 유튜브 영상을 보면서 연습했어요. 이제는 간단한 그림을 그릴 수 있어요. 다음 달에는 온라인 그림 강좌를 들을 거예요.",
    body_en: "I recently bought a drawing tablet. At first, using the pen felt awkward. I practiced by watching YouTube videos. Now I can draw simple pictures. Next month, I will take an online drawing course.", body_ja: "私は最近、絵を描くタブレットを買いました。最初はペンの使い方がぎこちなかったです。ユーチューブの動画を見ながら練習しました。今は簡単な絵が描けます。来月はオンラインの絵の講座を受けるつもりです。",
    questions: [
      { question_en: "How did the narrator practice?", question_ja: "主人公はどうやって練習しましたか。", options: ["Taking a class","Asking a friend","Reading a book","Watching YouTube videos"], answerIndex: 3 },
      { question_en: "What will the narrator do next month?", question_ja: "主人公は来月何をしますか。", options: ["Buy a new pen","Sell the tablet","Stop drawing","Take an online course"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "편의점 야간 근무",
    title_en: "Working the night shift at a convenience store", title_ja: "コンビニの夜勤",
    body_kr: "저는 이번 학기부터 편의점 야간 근무를 시작했어요. 밤에는 손님이 별로 없어요. 그래서 공부할 시간이 조금 있어요. 어젯밤에는 취한 손님이 와서 조금 무서웠어요. 다음에는 더 조심할 거예요.",
    body_en: "I started working the night shift at a convenience store this semester. There aren't many customers at night. So I have a little time to study. Last night, a drunk customer came in and it was a bit scary. Next time, I will be more careful.", body_ja: "私は今学期からコンビニの夜勤を始めました。夜はあまりお客さんがいません。だから少し勉強する時間があります。昨夜は酔ったお客さんが来て少し怖かったです。次はもっと気をつけるつもりです。",
    questions: [
      { question_en: "What does the narrator do during quiet night hours?", question_ja: "主人公は夜の静かな時間に何をしますか。", options: ["Studies","Cleans","Watches TV","Sleeps"], answerIndex: 0 },
      { question_en: "What happened last night?", question_ja: "昨夜、何がありましたか。", options: ["A fire alarm went off","The store closed early","A friend visited","A drunk customer came"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "베이커리 아르바이트",
    title_en: "A bakery part-time job", title_ja: "パン屋のアルバイト",
    body_kr: "저는 지난달부터 빵집에서 아르바이트를 해요. 아침 일찍 출근해서 빵을 진열해요. 갓 구운 빵 냄새가 정말 좋아요. 오늘은 손님이 많아서 아주 바빴어요. 다음 주에는 케이크 만드는 법도 배울 거예요.",
    body_en: "I have been working part-time at a bakery since last month. I go to work early in the morning and arrange the bread. The smell of freshly baked bread is really nice. Today there were many customers, so it was very busy. Next week, I will also learn how to make cakes.", body_ja: "私は先月からパン屋でアルバイトをしています。朝早く出勤してパンを並べます。焼きたてのパンの匂いが本当にいいです。今日はお客さんが多くてとても忙しかったです。来週はケーキの作り方も習うつもりです。",
    questions: [
      { question_en: "What does the narrator do in the morning?", question_ja: "主人公は朝、何をしますか。", options: ["Arrange bread","Clean tables","Take orders","Bake bread"], answerIndex: 0 },
      { question_en: "What will the narrator learn next week?", question_ja: "主人公は来週、何を習いますか。", options: ["How to manage staff","How to use the register","How to bake bread","How to make cakes"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "배드민턴 동호회",
    title_en: "A badminton club", title_ja: "バドミントンサークル",
    body_kr: "저는 회사 동료들과 배드민턴 동호회를 만들었어요. 매주 수요일 저녁에 체육관에서 연습해요. 처음에는 실력이 부족했지만 지금은 많이 늘었어요. 다음 달에는 다른 회사와 경기를 할 거예요. 저는 그날을 기대하고 있어요.",
    body_en: "I started a badminton club with my coworkers. We practice at a gymnasium every Wednesday evening. At first my skills were lacking, but now I've improved a lot. Next month, we will play a match against another company. I'm looking forward to that day.", body_ja: "私は会社の同僚たちとバドミントンサークルを作りました。毎週水曜日の夜、体育館で練習します。最初は実力が足りませんでしたが、今はだいぶ上達しました。来月は他の会社と試合をします。私はその日を楽しみにしています。",
    questions: [
      { question_en: "When do they practice?", question_ja: "いつ練習しますか。", options: ["Monday mornings","Sunday afternoons","Friday nights","Wednesday evenings"], answerIndex: 3 },
      { question_en: "What will happen next month?", question_ja: "来月、何がありますか。", options: ["A tournament ends","New members join","A match with another company","The club will close"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "독서 모임 참여",
    title_en: "Joining a book club", title_ja: "読書会への参加",
    body_kr: "저는 책을 좋아해서 독서 모임에 참여하기 시작했어요. 이번 달 책은 짧은 소설이었어요. 지난주 모임에서 회원들과 책 내용을 이야기했어요. 다양한 생각을 들을 수 있어서 재미있었어요. 다음 달 책도 벌써 기대돼요.",
    body_en: "I love books, so I started participating in a book club. This month's book was a short novel. At last week's meeting, we discussed the book with the members. It was fun to hear various opinions. I'm already looking forward to next month's book.", body_ja: "私は本が好きなので読書会に参加し始めました。今月の本は短い小説でした。先週の集まりで会員たちと本の内容について話しました。いろいろな考えを聞けて面白かったです。来月の本ももう楽しみです。",
    questions: [
      { question_en: "What was this month's book?", question_ja: "今月の本は何でしたか。", options: ["A poetry collection","A history book","A short novel","A cookbook"], answerIndex: 2 },
      { question_en: "What did the narrator enjoy about the meeting?", question_ja: "主人公は集まりの何を楽しみましたか。", options: ["Winning a prize","Hearing various opinions","The location","The food"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "피자 가게에서 일해요",
    title_en: "I work at a pizza place", title_ja: "ピザ屋で働いています",
    body_kr: "저는 주말마다 피자 가게에서 아르바이트를 해요. 저는 배달을 담당하고 있어요. 지난 주말에는 주문이 아주 많아서 정신없이 바빴어요. 사장님이 저에게 시급을 올려 주겠다고 했어요. 저는 이 일을 계속하고 싶어요.",
    body_en: "I work part-time at a pizza place every weekend. I'm in charge of deliveries. Last weekend, there were so many orders that it was hectic. The owner told me they would raise my hourly wage. I want to keep doing this job.", body_ja: "私は週末ごとにピザ屋でアルバイトをしています。私は配達を担当しています。先週末は注文がとても多くて目が回るほど忙しかったです。店長は私の時給を上げてくれると言いました。私はこの仕事を続けたいです。",
    questions: [
      { question_en: "What is the narrator's job at the pizza place?", question_ja: "主人公のピザ屋での仕事は何ですか。", options: ["Cooking","Cleaning","Deliveries","Cashier"], answerIndex: 2 },
      { question_en: "What did the owner promise?", question_ja: "店長は何を約束しましたか。", options: ["A raise","New equipment","A promotion","A day off"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "테니스를 배우기 시작했어요",
    title_en: "I started learning tennis", title_ja: "テニスを習い始めました",
    body_kr: "저는 새로운 운동을 배우고 싶어서 테니스 레슨을 등록했어요. 지난주에 첫 수업을 들었어요. 라켓 잡는 법부터 배웠어요. 생각보다 훨씬 어려웠지만 재미있었어요. 다음 달에는 동호회 사람들과 시합도 해 볼 거예요.",
    body_en: "I wanted to learn a new sport, so I signed up for tennis lessons. I took my first class last week. I learned how to hold the racket from the start. It was much harder than expected, but fun. Next month, I will also play a match with club members.", body_ja: "私は新しい運動を習いたくてテニスのレッスンに申し込みました。先週、初めての授業を受けました。ラケットの持ち方から習いました。思ったよりずっと難しかったですが楽しかったです。来月はサークルの人たちと試合もしてみるつもりです。",
    questions: [
      { question_en: "What did the narrator learn first?", question_ja: "主人公は最初に何を習いましたか。", options: ["How to keep score","How to serve","How to hold the racket","The rules of tennis"], answerIndex: 2 },
      { question_en: "What will the narrator do next month?", question_ja: "主人公は来月、何をしますか。", options: ["Quit lessons","Play a match","Watch a tournament","Buy new shoes"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "샐러드 가게에서 일해요",
    title_en: "I work at a salad shop", title_ja: "サラダ店で働いています",
    body_kr: "저는 건강한 음식에 관심이 많아서 샐러드 가게에서 아르바이트를 시작했어요. 매일 신선한 채소를 손질해요. 손님들에게 재료를 설명하는 것도 제 일이에요. 오늘은 새로운 소스를 추천했더니 손님이 아주 좋아했어요. 이 일을 하면서 저도 채소를 더 좋아하게 됐어요.",
    body_en: "I'm very interested in healthy food, so I started a part-time job at a salad shop. I prepare fresh vegetables every day. Explaining ingredients to customers is also part of my job. Today, I recommended a new sauce and the customer really liked it. While doing this job, I also came to like vegetables more.", body_ja: "私は健康的な食べ物にとても興味があるので、サラダ店でアルバイトを始めました。毎日新鮮な野菜を下ごしらえします。お客さんに材料を説明するのも私の仕事です。今日は新しいソースを勧めたらお客さんがとても気に入ってくれました。この仕事をしながら私も野菜がもっと好きになりました。",
    questions: [
      { question_en: "What is one of the narrator's job duties?", question_ja: "主人公の仕事の一つは何ですか。", options: ["Washing dishes","Cooking meat","Explaining ingredients","Delivering food"], answerIndex: 2 },
      { question_en: "What happened when the narrator recommended a sauce?", question_ja: "主人公がソースを勧めたとき、何が起こりましたか。", options: ["The sauce ran out","The customer complained","The customer liked it","The customer refused"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "패스트푸드점 아르바이트",
    title_en: "A fast food restaurant part-time job", title_ja: "ファストフード店のアルバイト",
    body_kr: "저는 방학 동안 패스트푸드점에서 아르바이트를 해요. 주문받는 일과 음식을 준비하는 일을 해요. 어제는 손님이 너무 많아서 실수를 했어요. 매니저는 괜찮다고 저를 격려해 줬어요. 다음에는 더 빠르고 정확하게 일할 거예요.",
    body_en: "I'm working part-time at a fast food restaurant during vacation. I take orders and prepare food. Yesterday there were so many customers that I made a mistake. The manager encouraged me, saying it was okay. Next time, I will work faster and more accurately.", body_ja: "私は休みの間、ファストフード店でアルバイトをしています。注文を受ける仕事と食べ物を準備する仕事をします。昨日はお客さんが多すぎてミスをしました。マネージャーは大丈夫だと私を励ましてくれました。次はもっと速く、正確に仕事をするつもりです。",
    questions: [
      { question_en: "What does the narrator do at work?", question_ja: "主人公は仕事で何をしますか。", options: ["Taking orders and preparing food","Managing staff","Only cleaning","Only cashier duties"], answerIndex: 0 },
      { question_en: "How did the manager react to the mistake?", question_ja: "マネージャーはミスにどう反応しましたか。", options: ["Fired the narrator","Ignored it","Encouraged the narrator","Got angry"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "테이크아웃 커피 사업",
    title_en: "A takeout coffee stand job", title_ja: "テイクアウトコーヒー店の仕事",
    body_kr: "저는 이번 여름에 작은 테이크아웃 커피 가게에서 일해요. 매일 아침 일찍 커피를 내려요. 손님들은 대부분 출근하는 직장인이에요. 오늘은 사장님이 새로운 원두를 소개해 줬어요. 저는 커피 맛을 구분하는 법을 배우고 있어요.",
    body_en: "This summer, I'm working at a small takeout coffee stand. I brew coffee early every morning. Most customers are office workers heading to work. Today, the owner introduced new coffee beans. I'm learning how to distinguish coffee flavors.", body_ja: "私は今年の夏、小さなテイクアウトコーヒー店で働いています。毎朝早くコーヒーを淹れます。お客さんのほとんどは出勤する会社員です。今日は店長が新しいコーヒー豆を紹介してくれました。私はコーヒーの味を区別する方法を学んでいます。",
    questions: [
      { question_en: "Who are most of the customers?", question_ja: "お客さんのほとんどは誰ですか。", options: ["Students","Office workers","Elderly people","Tourists"], answerIndex: 1 },
      { question_en: "What is the narrator learning?", question_ja: "主人公は何を学んでいますか。", options: ["How to manage money","How to design menus","How to bake","How to distinguish coffee flavors"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "고객센터 아르바이트",
    title_en: "A customer service center part-time job", title_ja: "コールセンターのアルバイト",
    body_kr: "저는 대학교 방학 동안 고객센터에서 아르바이트를 해요. 전화로 손님의 질문에 답해요. 처음에는 목소리가 떨렸지만 이제는 자신 있어요. 오늘은 어려운 손님을 잘 응대해서 칭찬을 받았어요. 저는 이 경험이 앞으로 큰 도움이 될 거라고 생각해요.",
    body_en: "I'm working part-time at a customer service center during university vacation. I answer customers' questions over the phone. At first my voice trembled, but now I'm confident. Today, I handled a difficult customer well and was praised. I think this experience will be a big help in the future.", body_ja: "私は大学の休みの間、コールセンターでアルバイトをしています。電話でお客さんの質問に答えます。最初は声が震えましたが、今は自信があります。今日は難しいお客さんにうまく対応してほめられました。この経験は将来大きな助けになると思います。",
    questions: [
      { question_en: "What does the narrator do at work?", question_ja: "主人公は仕事で何をしますか。", options: ["Answers questions by phone","Manages inventory","Delivers packages","Repairs products"], answerIndex: 0 },
      { question_en: "What happened today?", question_ja: "今日、何がありましたか。", options: ["They got a raise","The narrator quit","They were praised","They made a mistake"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "드론 조종을 배워요",
    title_en: "Learning to fly a drone", title_ja: "ドローンの操縦を習っています",
    body_kr: "저는 새로운 취미로 드론 조종을 시작했어요. 지난달에 작은 드론을 하나 샀어요. 처음에는 조종이 서툴러서 나무에 부딪혔어요. 요즘은 공원에서 안전하게 날릴 수 있어요. 다음에는 사진을 찍을 수 있는 드론으로 바꿀 거예요.",
    body_en: "I started flying drones as a new hobby. Last month I bought a small drone. At first, my flying was clumsy and it hit a tree. These days, I can fly it safely in the park. Next, I will switch to a drone that can take photos.", body_ja: "私は新しい趣味としてドローンの操縦を始めました。先月、小さなドローンを一つ買いました。最初は操縦が下手で木にぶつかりました。最近は公園で安全に飛ばせます。次は写真が撮れるドローンに変えるつもりです。",
    questions: [
      { question_en: "What happened at first?", question_ja: "最初、何が起こりましたか。", options: ["The drone was stolen","It hit a tree","It broke immediately","It flew away"], answerIndex: 1 },
      { question_en: "What does the narrator plan to do next?", question_ja: "主人公は次に何をする予定ですか。", options: ["Quit the hobby","Switch to a photo drone","Join a club","Sell the drone"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "치킨집 배달 아르바이트",
    title_en: "A chicken restaurant delivery job", title_ja: "チキン屋の配達アルバイト",
    body_kr: "저는 오토바이 면허가 있어서 치킨집에서 배달 아르바이트를 해요. 주말 저녁에는 주문이 정말 많아요. 어제는 비가 와서 배달이 힘들었어요. 그래도 사장님이 따뜻한 커피를 주셨어요. 저는 이 일을 통해 책임감을 배우고 있어요.",
    body_en: "I have a motorcycle license, so I work part-time delivering for a chicken restaurant. There are really many orders on weekend evenings. Yesterday it rained, so delivery was hard. Still, the owner gave me a warm coffee. Through this job, I'm learning responsibility.", body_ja: "私はバイクの免許があるので、チキン屋で配達のアルバイトをしています。週末の夜は本当に注文が多いです。昨日は雨が降って配達が大変でした。それでも店長が温かいコーヒーをくれました。私はこの仕事を通して責任感を学んでいます。",
    questions: [
      { question_en: "Why was delivery hard yesterday?", question_ja: "昨日、なぜ配達が大変でしたか。", options: ["Traffic","Too many orders","It rained","The bike broke"], answerIndex: 2 },
      { question_en: "What did the owner do for the narrator?", question_ja: "店長は主人公に何をしてくれましたか。", options: ["Gave a day off","Bought a new bike","Gave warm coffee","Raised the pay"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "동네 마트 캐셔 일",
    title_en: "A neighborhood mart cashier job", title_ja: "近所のスーパーのレジの仕事",
    body_kr: "저는 동네 마트에서 캐셔로 일하고 있어요. 매일 다양한 손님을 만나요. 오늘은 어르신이 무거운 짐을 들고 계셔서 도와드렸어요. 그분은 저에게 고맙다고 사탕을 주셨어요. 이런 작은 일들이 저를 행복하게 해요.",
    body_en: "I'm working as a cashier at a neighborhood mart. I meet various customers every day. Today, an elderly person was carrying heavy bags, so I helped them. They thanked me and gave me candy. Little things like this make me happy.", body_ja: "私は近所のスーパーでレジ係として働いています。毎日いろいろなお客さんに会います。今日はお年寄りが重い荷物を持っていたので、お手伝いしました。その方はお礼にと私に飴をくれました。こんな小さなことが私を幸せにしてくれます。",
    questions: [
      { question_en: "What did the narrator do for the elderly customer?", question_ja: "主人公はお年寄りのお客さんに何をしましたか。", options: ["Gave a discount","Helped carry heavy bags","Called a taxi","Ordered for them"], answerIndex: 1 },
      { question_en: "What did the customer give the narrator?", question_ja: "お客さんは主人公に何をくれましたか。", options: ["Money","Flowers","A gift card","Candy"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "북카페 아르바이트",
    title_en: "A book cafe part-time job", title_ja: "ブックカフェのアルバイト",
    body_kr: "저는 조용한 곳에서 일하고 싶어서 북카페 아르바이트를 시작했어요. 손님들이 책을 읽으며 커피를 마셔요. 저는 커피를 만들고 책을 정리해요. 오늘은 한가해서 저도 책을 조금 읽었어요. 이 일은 저에게 딱 맞는 것 같아요.",
    body_en: "I wanted to work in a quiet place, so I started a part-time job at a book cafe. Customers read books while drinking coffee. I make coffee and organize books. Today it was quiet, so I read a little too. This job seems perfect for me.", body_ja: "私は静かな所で働きたくてブックカフェのアルバイトを始めました。お客さんは本を読みながらコーヒーを飲みます。私はコーヒーを作って本を整理します。今日は暇だったので私も少し本を読みました。この仕事は私にぴったりだと思います。",
    questions: [
      { question_en: "Why did the narrator choose this job?", question_ja: "主人公はなぜこの仕事を選びましたか。", options: ["High pay","Free books","Quiet environment","Close to home"], answerIndex: 2 },
      { question_en: "What did the narrator do today?", question_ja: "主人公は今日、何をしましたか。", options: ["Cleaned all day","Read a little","Trained new staff","Left early"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "새로운 헬스장 등록",
    title_en: "Registering at a new gym", title_ja: "新しいジムに登録",
    body_kr: "저는 집 근처에 새로운 헬스장이 생겨서 등록했어요. 트레이너가 운동 계획을 짜 줬어요. 처음 며칠은 온몸이 아팠어요. 지금은 조금씩 익숙해지고 있어요. 다음 달에는 개인 레슨도 받아 볼 거예요.",
    body_en: "A new gym opened near my house, so I signed up. The trainer made an exercise plan for me. My whole body was sore for the first few days. Now I'm gradually getting used to it. Next month, I will also try personal training.", body_ja: "家の近くに新しいジムができたので登録しました。トレーナーが運動計画を立ててくれました。最初の数日は全身が痛かったです。今は少しずつ慣れてきています。来月はパーソナルレッスンも受けてみるつもりです。",
    questions: [
      { question_en: "Who made the exercise plan?", question_ja: "誰が運動計画を立てましたか。", options: ["The trainer","The narrator","A friend","A doctor"], answerIndex: 0 },
      { question_en: "What will the narrator try next month?", question_ja: "主人公は来月、何を試しますか。", options: ["Swimming","A new gym","Group classes","Personal training"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "동아리 회비 관리",
    title_en: "Managing the club's membership fees", title_ja: "サークルの会費管理",
    body_kr: "저는 등산 동호회의 총무를 맡고 있어요. 매달 회비를 걷고 관리해요. 지난달에는 회비로 새 장비를 샀어요. 회원들이 모두 만족스러워했어요. 다음 달에는 회식 비용으로 사용할 계획이에요.",
    body_en: "I'm in charge of managing the finances for my hiking club. I collect and manage membership fees every month. Last month, we used the fees to buy new equipment. All the members were satisfied. Next month, we plan to use it for a group dinner.", body_ja: "私は登山サークルの会計を任されています。毎月会費を集めて管理します。先月は会費で新しい装備を買いました。会員たちはみんな満足していました。来月は会食の費用に使う予定です。",
    questions: [
      { question_en: "What is the narrator's role in the club?", question_ja: "主人公のサークルでの役割は何ですか。", options: ["Photographer","President","Guide","Treasurer/manager of fees"], answerIndex: 3 },
      { question_en: "What was the fee used for last month?", question_ja: "先月、会費は何に使われましたか。", options: ["T-shirts","New equipment","A trip","A dinner"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "베트남 쌀국수 식당",
    title_en: "A Vietnamese pho restaurant", title_ja: "ベトナムのフォー店",
    body_kr: "저는 요즘 쌀국수에 빠져 있어요. 지난주에 새로 생긴 베트남 식당에 갔어요. 국물이 진하고 향이 좋았어요. 저는 다음에 친구들에게도 그 식당을 소개할 거예요. 오늘도 그 식당에서 점심을 먹었어요.",
    body_en: "Lately I've been obsessed with pho. Last week, I went to a newly opened Vietnamese restaurant. The broth was rich and had a nice aroma. I will introduce that restaurant to my friends next time. I also ate lunch at that restaurant today.", body_ja: "私は最近フォーにはまっています。先週、新しくできたベトナム料理店に行きました。スープが濃厚で香りも良かったです。今度友達にもその店を紹介するつもりです。今日もその店でお昼を食べました。",
    questions: [
      { question_en: "What is the narrator obsessed with lately?", question_ja: "主人公は最近何にはまっていますか。", options: ["Pho","Pizza","Ramen","Sushi"], answerIndex: 0 },
      { question_en: "What will the narrator do next?", question_ja: "主人公は次に何をしますか。", options: ["Introduce the restaurant to friends","Cook pho at home","Stop eating pho","Move away"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "스마트워치를 선물 받았어요",
    title_en: "I received a smartwatch as a gift", title_ja: "スマートウォッチをプレゼントされました",
    body_kr: "지난 생일에 남동생이 스마트워치를 선물해 줬어요. 처음에는 사용법을 잘 몰랐어요. 요즘은 매일 운동량을 확인해요. 오늘은 만 걸음을 걸었어요. 다음에는 수영할 때도 착용해 볼 거예요.",
    body_en: "On my last birthday, my younger brother gave me a smartwatch as a gift. At first, I didn't know how to use it well. These days, I check my exercise stats every day. Today, I walked ten thousand steps. Next, I will try wearing it while swimming too.", body_ja: "この前の誕生日に弟がスマートウォッチをプレゼントしてくれました。最初は使い方がよくわかりませんでした。最近は毎日運動量を確認します。今日は1万歩歩きました。次は泳ぐときも着けてみるつもりです。",
    questions: [
      { question_en: "Who gave the smartwatch as a gift?", question_ja: "誰がスマートウォッチをプレゼントしましたか。", options: ["Their sister","Their mother","Their younger brother","Their friend"], answerIndex: 2 },
      { question_en: "How many steps did the narrator walk today?", question_ja: "主人公は今日、何歩歩きましたか。", options: ["Two thousand","Five thousand","Fifteen thousand","Ten thousand"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "무선 이어폰을 샀어요",
    title_en: "I bought wireless earbuds", title_ja: "ワイヤレスイヤホンを買いました",
    body_kr: "저는 오랫동안 무선 이어폰을 갖고 싶었어요. 지난 주말에 드디어 하나를 샀어요. 음질이 아주 좋고 배터리도 오래가요. 요즘은 출근할 때마다 음악을 들어요. 다음에는 케이스도 예쁜 걸로 바꿀 거예요.",
    body_en: "I had wanted wireless earbuds for a long time. Last weekend, I finally bought a pair. The sound quality is great and the battery lasts long. These days, I listen to music every time I commute. Next, I will change to a pretty case too.", body_ja: "私は長い間ワイヤレスイヤホンが欲しいと思っていました。先週末、とうとう一つ買いました。音質がとても良くてバッテリーも長持ちします。最近は通勤するたびに音楽を聞きます。次はケースもかわいいものに変えるつもりです。",
    questions: [
      { question_en: "When did the narrator buy the earbuds?", question_ja: "主人公はいつイヤホンを買いましたか。", options: ["Last year","Yesterday","This morning","Last weekend"], answerIndex: 3 },
      { question_en: "What does the narrator plan to do next?", question_ja: "主人公は次に何をするつもりですか。", options: ["Change the case","Buy a new phone","Sell the earbuds","Return the earbuds"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "새로운 앱을 다운로드했어요",
    title_en: "I downloaded a new app", title_ja: "新しいアプリをダウンロードしました",
    body_kr: "저는 요즘 시간 관리를 잘 못해서 고민이었어요. 친구가 좋은 앱을 추천해 줬어요. 어제 그 앱을 다운로드해서 사용해 봤어요. 할 일 목록을 정리하니까 훨씬 편해요. 앞으로 매일 이 앱을 사용할 거예요.",
    body_en: "Lately I've been worried because I'm not good at managing my time. My friend recommended a good app. Yesterday I downloaded and tried the app. Organizing my to-do list has made things much easier. I will use this app every day from now on.", body_ja: "私は最近、時間管理がうまくできなくて悩んでいました。友達がいいアプリを勧めてくれました。昨日そのアプリをダウンロードして使ってみました。やることリストを整理するとずっと楽になりました。これから毎日このアプリを使うつもりです。",
    questions: [
      { question_en: "Who recommended the app?", question_ja: "誰がそのアプリを勧めましたか。", options: ["A coworker","A friend","A family member","An online review"], answerIndex: 1 },
      { question_en: "What does the app help with?", question_ja: "そのアプリは何に役立ちますか。", options: ["Exercise","Language learning","Cooking","Time management"], answerIndex: 3 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "떡집 사장님과의 인연",
    title_en: "A connection with the rice cake shop owner", title_ja: "餅屋の店長さんとの縁",
    body_kr: "저는 동네 떡집에서 오랫동안 떡을 사 왔어요. 사장님은 항상 저를 반갑게 맞아 주세요. 지난주에는 아르바이트 자리가 있다고 물어보셨어요. 저는 흔쾌히 승낙하고 이번 주부터 일을 시작했어요. 앞으로 사장님과 더 가까워질 것 같아요.",
    body_en: "I have been buying rice cakes from a neighborhood rice cake shop for a long time. The owner always greets me warmly. Last week, she asked if I wanted a part-time job. I gladly accepted and started working this week. I think I will grow closer to the owner from now on.", body_ja: "私は近所の餅屋で長い間餅を買ってきました。店長さんはいつも私を温かく迎えてくれます。先週、アルバイトの席があると聞かれました。私は快く承諾して今週から働き始めました。これから店長さんともっと親しくなりそうです。",
    questions: [
      { question_en: "What did the owner ask the narrator last week?", question_ja: "先週、店長は主人公に何を尋ねましたか。", options: ["If they wanted a part-time job","To leave a review","To recommend a friend","To buy more rice cakes"], answerIndex: 0 },
      { question_en: "When did the narrator start working?", question_ja: "主人公はいつから働き始めましたか。", options: ["This week","Last year","Next month","Last week"], answerIndex: 0 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "커피숍 신메뉴",
    title_en: "The coffee shop's new menu", title_ja: "コーヒーショップの新メニュー",
    body_kr: "제가 자주 가는 커피숍에서 신메뉴가 나왔어요. 오늘 아침에 새로운 라떼를 마셔 봤어요. 맛이 달콤하고 향이 좋았어요. 바리스타는 이 메뉴가 곧 인기가 많아질 거라고 말했어요. 저는 내일 또 마시러 갈 거예요.",
    body_en: "The coffee shop I often visit released a new menu item. This morning I tried a new latte. It tasted sweet and had a nice aroma. The barista said this drink would soon become popular. I will go drink it again tomorrow.", body_ja: "私がよく行くコーヒーショップで新メニューが出ました。今朝、新しいラテを飲んでみました。味が甘くて香りも良かったです。バリスタはこのメニューがすぐ人気になると言いました。私は明日もまた飲みに行くつもりです。",
    questions: [
      { question_en: "What did the narrator try this morning?", question_ja: "主人公は今朝、何を試しましたか。", options: ["A new sandwich","A new latte","A new cake","A new tea"], answerIndex: 1 },
      { question_en: "What did the barista predict?", question_ja: "バリスタは何を予想しましたか。", options: ["It would be discontinued","It would be expensive","It would become popular","It would change taste"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "diary",
    title_kr: "회사 동아리 사진전",
    title_en: "The company club's photo exhibition", title_ja: "会社のサークルの写真展",
    body_kr: "저는 회사 사진 동아리 회원이에요. 지난달부터 작은 전시회를 준비했어요. 오늘 드디어 전시회가 열렸어요. 많은 동료들이 와서 사진을 구경했어요. 저는 다음 전시회를 위해 더 좋은 사진을 찍을 거예요.",
    body_en: "I'm a member of my company's photography club. We have been preparing a small exhibition since last month. Today the exhibition finally opened. Many coworkers came to look at the photos. I will take better photos for the next exhibition.", body_ja: "私は会社の写真サークルの会員です。先月から小さな展示会を準備してきました。今日、ついに展示会が開かれました。多くの同僚が来て写真を見てくれました。私は次の展示会のためにもっと良い写真を撮るつもりです。",
    questions: [
      { question_en: "How long did they prepare for the exhibition?", question_ja: "展示会の準備にどのくらいかかりましたか。", options: ["One week","One year","Two days","Since last month"], answerIndex: 3 },
      { question_en: "Who came to the exhibition?", question_ja: "誰が展示会に来ましたか。", options: ["Only family","Many coworkers","Strangers only","No one"], answerIndex: 1 },
    ],
  },
];
