import type { RawPassage } from "./types";

export const READING_A2_MESSAGE: RawPassage[] = [
  {
    level: "A2",
    genre: "message",
    title_kr: "커피 약속 잡기",
    title_en: "Setting up a coffee date", title_ja: "コーヒーの約束",
    body_kr: "유나: 오늘 시간 있어? 커피 마실래?\n나: 좋아! 몇 시에 만날까?\n유나: 3시 어때?\n나: 좋아. 그 카페 앞에서 만나자.\n유나: 응, 이따 봐!",
    body_en: "Yuna: Are you free today? Want to grab coffee?\nMe: Sounds good! What time should we meet?\nYuna: How about 3?\nMe: Good. Let's meet in front of that cafe.\nYuna: Okay, see you later!", body_ja: "ユナ: 今日時間ある?コーヒー飲まない?\n私: いいよ!何時に会う?\nユナ: 3時はどう?\n私: いいよ。あのカフェの前で会おう。\nユナ: うん、後でね!",
    questions: [
      { question_en: "What time do they agree to meet?", question_ja: "二人は何時に会うことにしましたか。", options: ["1 o'clock", "2 o'clock", "3 o'clock", "4 o'clock"], answerIndex: 2 },
      { question_en: "Where will they meet?", question_ja: "どこで会いますか。", options: ["At school", "In front of the cafe", "At the station", "At Sujin's house"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "보고서 확인 부탁",
    title_en: "Asking a coworker to check a report", title_ja: "報告書の確認をお願いする",
    body_kr: "박 대리님: 김 대리님, 보고서 다 쓰셨어요?\n나: 네, 방금 끝냈어요. 지금 보내 드릴게요.\n박 대리님: 감사합니다. 내일 회의 전에 확인할게요.\n나: 혹시 수정할 부분 있으면 알려 주세요.\n박 대리님: 네, 확인하고 연락드릴게요.",
    body_en: "Mr. Park: Ms. Kim, did you finish the report?\nMe: Yes, I just finished it. I'll send it now.\nMr. Park: Thanks. I'll check it before tomorrow's meeting.\nMe: Please let me know if anything needs fixing.\nMr. Park: Okay, I'll check and get back to you.", body_ja: "パク代理: キムさん、報告書はもう書き終わりましたか。\n私: はい、たった今終わりました。今すぐお送りします。\nパク代理: ありがとうございます。明日の会議の前に確認しますね。\n私: もし直す部分があれば教えてください。\nパク代理: はい、確認してご連絡します。",
    questions: [
      { question_en: "When will Mr. Park check the report?", question_ja: "パク代理はいつ報告書を確認しますか。", options: ["Right now", "Before tomorrow's meeting", "Next week", "After lunch"], answerIndex: 1 },
      { question_en: "What does the writer ask Mr. Park to do?", question_ja: "書き手はパク代理に何をお願いしていますか。", options: ["Write the report", "Send the report", "Point out anything to fix", "Cancel the meeting"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "보일러 고장",
    title_en: "The boiler is broken", title_ja: "ボイラーの故障",
    body_kr: "나: 안녕하세요, 집주인님. 보일러가 고장 났어요. 물이 안 따뜻해요.\n집주인: 아, 죄송해요. 언제부터 그랬어요?\n나: 오늘 아침부터요.\n집주인: 내일 오전에 수리 기사님을 보낼게요.\n나: 네, 감사합니다.",
    body_en: "Me: Hello, landlord. The boiler is broken. The water isn't warm.\nLandlord: Oh, I'm sorry. Since when?\nMe: Since this morning.\nLandlord: I'll send a repairman tomorrow morning.\nMe: Okay, thank you.", body_ja: "私: こんにちは、大家さん。ボイラーが故障しました。お湯が出ません。\n大家さん: あ、すみません。いつからそうなりましたか。\n私: 今朝からです。\n大家さん: 明日の午前中に修理の方を送りますね。\n私: はい、ありがとうございます。",
    questions: [
      { question_en: "What is the problem?", question_ja: "問題は何ですか。", options: ["The lights don't work", "The water isn't warm", "The door won't open", "The internet is down"], answerIndex: 1 },
      { question_en: "When will the repairman come?", question_ja: "修理の人はいつ来ますか。", options: ["Today", "Tomorrow morning", "Next week", "This evening"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "온라인몰 반품 문의",
    title_en: "Asking an online store about a return", title_ja: "オンラインショップへの返品の問い合わせ",
    body_kr: "고객: 안녕하세요. 어제 산 신발이 너무 작아요. 반품할 수 있어요?\n상담원: 네, 가능합니다. 언제 받으셨어요?\n고객: 이틀 전에 받았어요.\n상담원: 그럼 반품 신청서를 작성해 주세요.\n고객: 알겠습니다. 환불은 얼마나 걸려요?\n상담원: 보통 일주일 정도 걸려요.",
    body_en: "Customer: Hello. The shoes I bought yesterday are too small. Can I return them?\nAgent: Yes, that's possible. When did you receive them?\nCustomer: I received them two days ago.\nAgent: Then please fill out the return form.\nCustomer: Okay. How long does the refund take?\nAgent: It usually takes about a week.", body_ja: "お客様: こんにちは。昨日買った靴が小さすぎます。返品できますか。\n相談員: はい、可能です。いつお受け取りになりましたか。\nお客様: 二日前に受け取りました。\n相談員: それでは返品申請書を記入してください。\nお客様: 分かりました。返金にはどのくらいかかりますか。\n相談員: 通常一週間ほどかかります。",
    questions: [
      { question_en: "Why does the customer want to return the shoes?", question_ja: "お客様が靴を返品したい理由は何ですか。", options: ["Wrong color", "Too small", "Damaged", "Too expensive"], answerIndex: 1 },
      { question_en: "How long does the refund usually take?", question_ja: "返金には普通どのくらいかかりますか。", options: ["One day", "Three days", "About a week", "A month"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "차 좀 빌려줘",
    title_en: "Can I borrow the car?", title_ja: "車を貸してくれる?",
    body_kr: "동생: 오빠, 이번 주말에 차 좀 빌려줄 수 있어?\n나: 어디 가려고?\n동생: 친구 결혼식에 가야 해서.\n나: 몇 시에 필요해?\n동생: 토요일 아침 9시부터 저녁까지.\n나: 알겠어. 기름은 채워서 돌려줘.",
    body_en: "Younger sibling: Oppa, can I borrow the car this weekend?\nMe: Where are you going?\nYounger sibling: I have to go to a friend's wedding.\nMe: What time do you need it?\nYounger sibling: From 9am Saturday until evening.\nMe: Okay. Fill up the gas before you return it.", body_ja: "妹: お兄ちゃん、今週末に車をちょっと貸してくれる?\n私: どこに行くの?\n妹: 友達の結婚式に行かなきゃいけなくて。\n私: 何時から必要?\n妹: 土曜日の朝9時から夕方まで。\n私: 分かった。ガソリンを満タンにして返してね。",
    questions: [
      { question_en: "Why does the younger sibling need the car?", question_ja: "妹が車を必要としているのはなぜですか。", options: ["A job interview", "A friend's wedding", "A doctor's appointment", "A trip to the airport"], answerIndex: 1 },
      { question_en: "What condition does the narrator ask for?", question_ja: "語り手はどんな条件を求めましたか。", options: ["Wash the car", "Fill up the gas", "Return it early", "Pay for gas"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "조별 과제 회의 시간",
    title_en: "Setting a group project meeting time", title_ja: "グループ課題の打ち合わせ時間",
    body_kr: "민호: 우리 발표 자료 언제 같이 만들까요?\n나: 저는 수요일 오후가 괜찮아요.\n민호: 저는 그날 시간이 없어서 목요일이 나아요.\n나: 그럼 목요일 저녁 7시에 카페에서 만나요.\n민호: 좋아요. 자료 미리 준비해 올게요.",
    body_en: "Minho: When should we make the presentation materials together?\nMe: Wednesday afternoon works for me.\nMinho: I don't have time that day, so Thursday is better.\nMe: Then let's meet at 7pm Thursday at the cafe.\nMinho: Sounds good. I'll prepare the materials in advance.", body_ja: "ミンホ: 発表資料、いつ一緒に作りましょうか。\n私: 私は水曜日の午後が大丈夫です。\nミンホ: 私はその日時間がないので木曜日のほうがいいです。\n私: それじゃあ木曜日の夜7時にカフェで会いましょう。\nミンホ: いいですね。資料を前もって準備してきます。",
    questions: [
      { question_en: "Why does Minho suggest Thursday instead?", question_ja: "ミンホが木曜日を提案したのはなぜですか。", options: ["He is sick", "He has no time Wednesday", "The cafe is closed Wednesday", "He forgot the date"], answerIndex: 1 },
      { question_en: "Where will they meet?", question_ja: "どこで会いますか。", options: ["At school", "At the cafe", "At Minho's house", "At the library"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "택배 도착 확인",
    title_en: "Confirming a delivery arrival", title_ja: "宅配便の到着確認",
    body_kr: "기사님: 고객님, 택배 문 앞에 두었습니다.\n나: 네, 감사합니다. 혹시 언제쯤 왔어요?\n기사님: 방금 전에 두고 갔어요.\n나: 알겠습니다. 확인해 볼게요.\n(잠시 후)\n나: 물건 잘 받았어요. 감사합니다!",
    body_en: "Driver: I left your package in front of the door.\nMe: Okay, thank you. When did it arrive, by any chance?\nDriver: I just left it a moment ago.\nMe: Got it. I'll go check.\n(A little later)\nMe: I received the package safely. Thank you!", body_ja: "配達員: お客様、荷物はドアの前に置きました。\n私: はい、ありがとうございます。いつ頃来ましたか。\n配達員: たった今置いていきました。\n私: 分かりました。確認してみます。\n(しばらくして)\n私: 荷物、ちゃんと受け取りました。ありがとうございます!",
    questions: [
      { question_en: "Where did the driver leave the package?", question_ja: "配達員は荷物をどこに置きましたか。", options: ["At the front desk", "In front of the door", "With a neighbor", "At the post office"], answerIndex: 1 },
      { question_en: "What does the narrator do after checking?", question_ja: "確認した後、語り手は何をしますか。", options: ["Complains about it being late", "Asks for a refund", "Confirms receiving it", "Asks to redeliver it"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "저녁 약속 취소",
    title_en: "Canceling dinner plans", title_ja: "夕食の約束のキャンセル",
    body_kr: "지우: 오늘 저녁에 갑자기 회사에 일이 생겨서 못 갈 것 같아. 미안해.\n나: 괜찮아. 무슨 일이야?\n지우: 급한 보고서가 있어서 야근해야 해.\n나: 그럼 다음 주에 만나자.\n지우: 응, 이번 주말에 시간 맞춰 볼게.",
    body_en: "Jiwoo: Something suddenly came up at work this evening, so I don't think I can make it. Sorry.\nMe: That's okay. What happened?\nJiwoo: There's an urgent report, so I have to work late.\nMe: Then let's meet next week.\nJiwoo: Okay, I'll try to find time this weekend.", body_ja: "ジウ: 今日の夕方急に会社で用事ができて行けなさそう。ごめんね。\n私: 大丈夫だよ。何かあったの?\nジウ: 急ぎの報告書があって残業しなきゃいけないの。\n私: それじゃあ来週会おう。\nジウ: うん、今週末に時間を合わせてみるね。",
    questions: [
      { question_en: "Why does Jiwoo cancel dinner?", question_ja: "ジウが夕食をキャンセルしたのはなぜですか。", options: ["She is sick", "She has to work late", "She is traveling", "She forgot the plan"], answerIndex: 1 },
      { question_en: "What do they decide to do?", question_ja: "二人はどうすることにしましたか。", options: ["Cancel forever", "Meet next week instead", "Meet tomorrow", "Have dinner by phone"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "책 좀 빌려줄래?",
    title_en: "Can you lend me that book?", title_ja: "あの本、貸してくれる?",
    body_kr: "나: 저번에 말한 그 소설책 아직 가지고 있어?\n하은: 응, 있어. 빌려줄까?\n나: 응, 이번 주말에 읽고 싶어서.\n하은: 알겠어. 내일 학교 앞에서 줄게.\n나: 고마워! 다 읽으면 바로 돌려줄게.",
    body_en: "Me: Do you still have that novel you mentioned before?\nHaeun: Yes, I have it. Want me to lend it to you?\nMe: Yes, I want to read it this weekend.\nHaeun: Okay. I'll give it to you in front of school tomorrow.\nMe: Thanks! I'll return it right after I finish reading.", body_ja: "私: この前話してたあの小説、まだ持ってる?\nハウン: うん、あるよ。貸してあげようか?\n私: うん、今週末読みたくて。\nハウン: 分かった。明日学校の前で渡すね。\n私: ありがとう!読み終わったらすぐ返すね。",
    questions: [
      { question_en: "What does the narrator want to borrow?", question_ja: "語り手は何を借りたがっていますか。", options: ["A movie", "A novel", "A notebook", "A magazine"], answerIndex: 1 },
      { question_en: "Where will Haeun give the book?", question_ja: "ハウンはどこで本を渡しますか。", options: ["At her house", "In front of school", "At the library", "At the cafe"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "새 직장 소식",
    title_en: "News about a new job", title_ja: "新しい職場のニュース",
    body_kr: "나: 나 좋은 소식 있어! 새 회사에 합격했어.\n민지: 정말? 축하해! 언제부터 출근해?\n나: 다음 달 1일부터 시작이야.\n민지: 대박! 어떤 일을 하는 회사야?\n나: 마케팅 회사야. 진짜 기대돼.",
    body_en: "Me: I have good news! I got accepted at a new company.\nMinji: Really? Congratulations! When do you start?\nMe: I start on the 1st of next month.\nMinji: Awesome! What kind of company is it?\nMe: It's a marketing company. I'm really excited.", body_ja: "私: いいニュースがあるの!新しい会社に受かったよ。\nミンジ: 本当?おめでとう!いつから出勤するの?\n私: 来月の1日から始めるの。\nミンジ: すごい!どんな仕事をする会社なの?\n私: マーケティングの会社だよ。本当に楽しみ。",
    questions: [
      { question_en: "What is the good news?", question_ja: "いいニュースとは何ですか。", options: ["A promotion", "A new job", "A new apartment", "A vacation"], answerIndex: 1 },
      { question_en: "When does the narrator start working?", question_ja: "語り手はいつから働き始めますか。", options: ["Tomorrow", "Next week", "The 1st of next month", "In a year"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "콘서트 같이 갈 사람",
    title_en: "Coordinating a concert meetup", title_ja: "コンサートに一緒に行く人",
    body_kr: "재현: 다음 주 토요일에 콘서트 표 두 장 있는데 같이 갈래?\n나: 진짜? 몇 시 공연이야?\n재현: 저녁 7시야. 6시에 입구에서 만나자.\n나: 좋아! 표 값은 얼마야?\n재현: 오만 원이야. 만나서 줘.",
    body_en: "Jaehyun: I have two concert tickets for next Saturday, want to come with me?\nMe: Really? What time is the show?\nJaehyun: It's at 7pm. Let's meet at the entrance at 6.\nMe: Sounds good! How much is the ticket?\nJaehyun: It's 50,000 won. Give it to me when we meet.", body_ja: "ジェヒョン: 来週の土曜日にコンサートのチケットが二枚あるんだけど、一緒に行かない?\n私: 本当?何時の公演?\nジェヒョン: 夜7時だよ。6時に入り口で会おう。\n私: いいよ!チケット代はいくら?\nジェヒョン: 五万ウォンだよ。会ったときに渡して。",
    questions: [
      { question_en: "What time does the concert start?", question_ja: "コンサートは何時に始まりますか。", options: ["6pm", "7pm", "8pm", "9pm"], answerIndex: 1 },
      { question_en: "How much does the ticket cost?", question_ja: "チケットはいくらですか。", options: ["30,000 won", "40,000 won", "50,000 won", "60,000 won"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "룸메이트 청소 당번",
    title_en: "Roommate cleaning turns", title_ja: "ルームメイトの掃除当番",
    body_kr: "룸메이트: 이번 주 청소 당번이 누구지?\n나: 이번 주는 내 차례야. 미안, 회사 일이 바빠서 아직 못 했어.\n룸메이트: 괜찮아. 언제 할 수 있어?\n나: 오늘 저녁에 꼭 할게.\n룸메이트: 알겠어. 그럼 설거지는 내가 할게.",
    body_en: "Roommate: Whose turn is it to clean this week?\nMe: It's my turn this week. Sorry, I haven't done it yet because work has been busy.\nRoommate: That's okay. When can you do it?\nMe: I'll definitely do it this evening.\nRoommate: Okay. Then I'll do the dishes.", body_ja: "ルームメイト: 今週の掃除当番って誰だっけ?\n私: 今週は私の番だよ。ごめん、仕事が忙しくてまだできてないの。\nルームメイト: 大丈夫だよ。いつできそう?\n私: 今日の夜には必ずやるね。\nルームメイト: 分かった。じゃあ皿洗いは私がやるね。",
    questions: [
      { question_en: "Why hasn't the narrator cleaned yet?", question_ja: "語り手がまだ掃除をしていないのはなぜですか。", options: ["Forgot completely", "Was busy with work", "Was sick", "Was traveling"], answerIndex: 1 },
      { question_en: "What will the roommate do?", question_ja: "ルームメイトは何をしますか。", options: ["Clean instead", "Do the dishes", "Do nothing", "Move out"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "생일 파티 준비",
    title_en: "Planning a birthday party", title_ja: "誕生日パーティーの準備",
    body_kr: "수아: 다음 주 금요일이 지훈이 생일이야. 파티 준비할까?\n나: 좋아! 어디서 할까?\n수아: 우리 집에서 하자. 케이크는 내가 살게.\n나: 그럼 나는 음료수랑 과자를 준비할게.\n수아: 고마워. 지훈이한테는 비밀이야!",
    body_en: "Sua: Next Friday is Jihoon's birthday. Should we plan a party?\nMe: Sounds good! Where should we have it?\nSua: Let's have it at our house. I'll buy the cake.\nMe: Then I'll prepare drinks and snacks.\nSua: Thanks. It's a secret from Jihoon!", body_ja: "スア: 来週の金曜日がジフンの誕生日なの。パーティーの準備しようか?\n私: いいね!どこでやる?\nスア: うちでやろう。ケーキは私が買うね。\n私: それじゃあ私は飲み物とお菓子を用意するね。\nスア: ありがとう。ジフンには内緒だよ!",
    questions: [
      { question_en: "Whose birthday is it?", question_ja: "誰の誕生日ですか。", options: ["Sua's", "The narrator's", "Jihoon's", "A coworker's"], answerIndex: 2 },
      { question_en: "What will the narrator bring?", question_ja: "語り手は何を持ってきますか。", options: ["The cake", "A gift", "Drinks and snacks", "Flowers"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "예약 시간 변경",
    title_en: "Changing a restaurant reservation", title_ja: "予約時間の変更",
    body_kr: "고객: 안녕하세요. 오늘 저녁 7시 예약을 8시로 바꿀 수 있어요?\n식당: 네, 가능합니다. 몇 분이세요?\n고객: 네 명이에요.\n식당: 알겠습니다. 8시로 변경했습니다.\n고객: 감사합니다.",
    body_en: "Customer: Hello. Can I change my 7pm reservation tonight to 8pm?\nRestaurant: Yes, that's possible. How many people?\nCustomer: Four people.\nRestaurant: Okay, I've changed it to 8pm.\nCustomer: Thank you.", body_ja: "お客様: こんにちは。今日夜7時の予約を8時に変えられますか。\nお店: はい、可能です。何名様ですか。\nお客様: 四名です。\nお店: 分かりました。8時に変更しました。\nお客様: ありがとうございます。",
    questions: [
      { question_en: "What time is the new reservation?", question_ja: "新しい予約は何時ですか。", options: ["6pm", "7pm", "8pm", "9pm"], answerIndex: 2 },
      { question_en: "How many people are in the party?", question_ja: "何人のグループですか。", options: ["Two", "Three", "Four", "Five"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "몸이 아파서 결근",
    title_en: "Calling in sick to a coworker", title_ja: "体調不良で休むこと",
    body_kr: "나: 팀장님, 오늘 몸이 안 좋아서 병원에 가야 할 것 같아요.\n팀장님: 어디가 아프세요?\n나: 열이 나고 목이 아파요.\n팀장님: 그럼 오늘은 쉬고 푹 쉬세요.\n나: 감사합니다. 내일은 출근하겠습니다.",
    body_en: "Me: Team leader, I feel sick today so I think I need to go to the hospital.\nTeam leader: What's wrong?\nMe: I have a fever and my throat hurts.\nTeam leader: Then take today off and rest well.\nMe: Thank you. I'll come to work tomorrow.", body_ja: "私: チーム長、今日は体調が悪くて病院に行かないといけなさそうです。\nチーム長: どこが悪いんですか。\n私: 熱があって喉が痛いです。\nチーム長: それなら今日は休んでゆっくり休んでください。\n私: ありがとうございます。明日は出勤します。",
    questions: [
      { question_en: "What symptoms does the narrator have?", question_ja: "語り手にはどんな症状がありますか。", options: ["Headache and cough", "Fever and sore throat", "Stomachache", "Back pain"], answerIndex: 1 },
      { question_en: "What does the team leader tell the narrator to do?", question_ja: "チーム長は語り手に何をするよう言いましたか。", options: ["Come to work anyway", "Rest today", "See a specialist", "Take a week off"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "월세 입금 확인",
    title_en: "Confirming the rent payment", title_ja: "家賃の入金確認",
    body_kr: "집주인: 이번 달 월세가 아직 안 들어왔어요.\n나: 어, 죄송해요. 깜빡했어요. 지금 바로 보낼게요.\n집주인: 네, 확인되면 연락드릴게요.\n나: 방금 보냈어요. 확인해 주세요.\n집주인: 네, 잘 받았어요. 감사합니다.",
    body_en: "Landlord: This month's rent hasn't come in yet.\nMe: Oh, sorry. I forgot. I'll send it right now.\nLandlord: Okay, I'll let you know once I confirm it.\nMe: I just sent it. Please check.\nLandlord: Yes, I received it. Thank you.", body_ja: "大家さん: 今月の家賃がまだ入っていません。\n私: あ、すみません。忘れていました。今すぐ送ります。\n大家さん: はい、確認できたら連絡しますね。\n私: たった今送りました。確認してください。\n大家さん: はい、ちゃんと受け取りました。ありがとうございます。",
    questions: [
      { question_en: "Why hadn't the rent arrived?", question_ja: "家賃が届いていなかったのはなぜですか。", options: ["The bank was closed", "The tenant forgot", "The landlord changed accounts", "There was a system error"], answerIndex: 1 },
      { question_en: "What does the landlord do at the end?", question_ja: "最後に大家さんは何をしますか。", options: ["Asks for more money", "Confirms receiving the payment", "Cancels the lease", "Raises the rent"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "부모님 결혼기념일 선물",
    title_en: "A gift for our parents' anniversary", title_ja: "両親の結婚記念日のプレゼント",
    body_kr: "언니: 다음 주가 엄마 아빠 결혼기념일이야. 뭐 사 드릴까?\n나: 여행 상품권은 어때?\n언니: 좋은 생각이야! 얼마씩 낼까?\n나: 반반 나누자.\n언니: 알겠어. 내가 오늘 주문할게.",
    body_en: "Older sister: Next week is Mom and Dad's anniversary. What should we get them?\nMe: How about a travel voucher?\nOlder sister: Good idea! How much should we each pay?\nMe: Let's split it in half.\nOlder sister: Okay. I'll order it today.", body_ja: "姉: 来週がお母さんとお父さんの結婚記念日なの。何を買ってあげようか。\n私: 旅行券はどう?\n姉: いい考えね!いくらずつ出そうか。\n私: 半分ずつにしよう。\n姉: 分かった。今日私が注文するね。",
    questions: [
      { question_en: "What gift do they choose?", question_ja: "二人はどんなプレゼントを選びましたか。", options: ["Flowers", "A travel voucher", "A cake", "A photo album"], answerIndex: 1 },
      { question_en: "How will they split the cost?", question_ja: "費用はどう分けますか。", options: ["Older sister pays all", "Narrator pays all", "Half and half", "They ask their parents"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "이사 도와줄 수 있어?",
    title_en: "Can you help me move?", title_ja: "引っ越しを手伝ってくれる?",
    body_kr: "나: 이번 주 토요일에 이사하는데 좀 도와줄 수 있어?\n태윤: 응, 몇 시에 가면 돼?\n나: 오전 10시쯤 와 줘.\n태윤: 알겠어. 짐이 많아?\n나: 박스 몇 개랑 큰 가구 하나야.",
    body_en: "Me: I'm moving this Saturday, can you help me out?\nTaeyoon: Sure, what time should I come?\nMe: Come around 10am.\nTaeyoon: Got it. Is there a lot of stuff?\nMe: Just a few boxes and one big piece of furniture.", body_ja: "私: 今週の土曜日に引っ越すんだけど、ちょっと手伝ってくれる?\nテユン: うん、何時に行けばいい?\n私: 午前10時頃来て。\nテユン: 分かった。荷物は多い?\n私: 箱がいくつかと大きい家具が一つだよ。",
    questions: [
      { question_en: "What time should Taeyoon come?", question_ja: "テユンは何時に来ればいいですか。", options: ["9am", "10am", "11am", "Noon"], answerIndex: 1 },
      { question_en: "What does the narrator need to move?", question_ja: "語り手は何を運ぶ必要がありますか。", options: ["Only boxes", "A few boxes and one big furniture piece", "A car", "Nothing heavy"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "중고 물건 거래",
    title_en: "Buying a secondhand item", title_ja: "中古品の取引",
    body_kr: "구매자: 자전거 아직 팔아요?\n판매자: 네, 아직 있어요.\n구매자: 가격을 조금 깎아 줄 수 있어요?\n판매자: 오만 원까지는 가능해요.\n구매자: 좋아요. 내일 만나서 드릴게요.",
    body_en: "Buyer: Is the bicycle still for sale?\nSeller: Yes, it's still available.\nBuyer: Could you lower the price a bit?\nSeller: I can go as low as 50,000 won.\nBuyer: Okay. I'll meet you tomorrow to pay.", body_ja: "買い手: 自転車、まだ売ってますか。\n売り手: はい、まだあります。\n買い手: 値段を少し下げてもらえますか。\n売り手: 五万ウォンまでなら可能です。\n買い手: いいですね。明日会ってお渡しします。",
    questions: [
      { question_en: "What is being sold?", question_ja: "何が売られていますか。", options: ["A bicycle", "A car", "A phone", "A desk"], answerIndex: 0 },
      { question_en: "What price does the seller agree to?", question_ja: "売り手はいくらに同意しましたか。", options: ["30,000 won", "40,000 won", "50,000 won", "60,000 won"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "피티 수업 시간 변경",
    title_en: "Rescheduling a PT session", title_ja: "パーソナルトレーニングの時間変更",
    body_kr: "나: 트레이너님, 내일 오후 3시 수업을 바꿀 수 있을까요?\n트레이너: 네, 언제로 원하세요?\n나: 저녁 6시는 어때요?\n트레이너: 6시에 다른 회원이 있어서 7시는 어떠세요?\n나: 네, 7시로 할게요.",
    body_en: "Me: Trainer, could I change tomorrow's 3pm session?\nTrainer: Sure, when would you like?\nMe: How about 6pm?\nTrainer: There's another member at 6, how about 7pm?\nMe: Okay, I'll do 7pm.", body_ja: "私: トレーナーさん、明日の午後3時のレッスンを変更できますか。\nトレーナー: はい、いつがいいですか。\n私: 夜6時はどうですか。\nトレーナー: 6時は他の会員がいるので、7時はどうですか。\n私: はい、7時にします。",
    questions: [
      { question_en: "What time was the original session?", question_ja: "元のレッスンは何時でしたか。", options: ["1pm", "2pm", "3pm", "4pm"], answerIndex: 2 },
      { question_en: "What time do they finally agree on?", question_ja: "最終的に何時に決まりましたか。", options: ["5pm", "6pm", "7pm", "8pm"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "층간 소음 문제",
    title_en: "A noise problem between floors", title_ja: "階間騒音の問題",
    body_kr: "이웃: 안녕하세요. 밤에 소리가 좀 크게 들려서 연락드려요.\n나: 아, 죄송합니다. 몰랐어요. 어떤 소리였어요?\n이웃: 밤 11시쯤 발소리가 들렸어요.\n나: 앞으로 조심할게요. 불편하게 해서 죄송해요.\n이웃: 이해해 주셔서 감사해요.",
    body_en: "Neighbor: Hello. I'm reaching out because I hear some loud noise at night.\nMe: Oh, I'm sorry. I didn't know. What kind of sound was it?\nNeighbor: I heard footsteps around 11pm.\nMe: I'll be careful from now on. Sorry for the inconvenience.\nNeighbor: Thanks for understanding.", body_ja: "隣人: こんにちは。夜に音が少し大きく聞こえたのでご連絡しました。\n私: あ、すみません。知りませんでした。どんな音でしたか。\n隣人: 夜11時頃に足音が聞こえました。\n私: これから気をつけます。ご迷惑をおかけしてすみません。\n隣人: 分かっていただきありがとうございます。",
    questions: [
      { question_en: "What kind of noise did the neighbor hear?", question_ja: "隣人はどんな音を聞きましたか。", options: ["Music", "Footsteps", "A dog barking", "A TV"], answerIndex: 1 },
      { question_en: "What time did the noise happen?", question_ja: "その音はいつ聞こえましたか。", options: ["9pm", "10pm", "11pm", "Midnight"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "우산 돌려주기",
    title_en: "Returning a borrowed umbrella", title_ja: "傘を返すこと",
    body_kr: "나: 지난주에 빌려준 우산 고마웠어. 언제 돌려줄까?\n소라: 아, 괜찮아! 다음에 만날 때 줘도 돼.\n나: 그럼 이번 주말에 만날까?\n소라: 좋아, 토요일에 시간 있어.\n나: 그때 카페에서 만나서 줄게.",
    body_en: "Me: Thanks for lending me the umbrella last week. When should I return it?\nSora: Oh, it's fine! You can give it back next time we meet.\nMe: Then shall we meet this weekend?\nSora: Sure, I'm free on Saturday.\nMe: I'll meet you at the cafe then and give it back.", body_ja: "私: 先週貸してくれた傘、ありがとう。いつ返そうか。\nソラ: あ、大丈夫だよ!次会うときに返してくれればいいよ。\n私: それじゃあ今週末に会おうか。\nソラ: いいよ、土曜日に時間があるよ。\n私: その時カフェで会って返すね。",
    questions: [
      { question_en: "What is the narrator returning?", question_ja: "語り手は何を返しますか。", options: ["A book", "An umbrella", "Money", "A jacket"], answerIndex: 1 },
      { question_en: "When will they meet?", question_ja: "いつ会いますか。", options: ["Today", "Tomorrow", "Saturday", "Next month"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "점심 같이 먹을래요?",
    title_en: "Want to have lunch together?", title_ja: "一緒にお昼を食べませんか",
    body_kr: "동료: 오늘 점심 같이 먹을래요?\n나: 좋아요. 뭐 먹고 싶어요?\n동료: 회사 근처에 새로 생긴 국수집 가 볼까요?\n나: 좋아요. 12시에 로비에서 만나요.\n동료: 네, 이따 봐요!",
    body_en: "Colleague: Want to have lunch together today?\nMe: Sure. What do you feel like eating?\nColleague: Should we try the new noodle place near the office?\nMe: Sounds good. Let's meet in the lobby at 12.\nColleague: Okay, see you later!", body_ja: "同僚: 今日お昼一緒に食べませんか。\n私: いいですね。何が食べたいですか。\n同僚: 会社の近くに新しくできた麺屋、行ってみましょうか。\n私: いいですね。12時にロビーで会いましょう。\n同僚: はい、後で!",
    questions: [
      { question_en: "What kind of restaurant do they choose?", question_ja: "二人はどんなお店を選びましたか。", options: ["A noodle place", "A pizza place", "A cafe", "A bakery"], answerIndex: 0 },
      { question_en: "Where will they meet?", question_ja: "どこで会いますか。", options: ["At the restaurant", "In the lobby", "At the parking lot", "Outside the building"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "휴대폰 요금제 문의",
    title_en: "Asking about a phone plan", title_ja: "携帯電話の料金プランの問い合わせ",
    body_kr: "고객: 안녕하세요. 지금 요금제보다 싼 요금제가 있어요?\n상담원: 네, 데이터를 얼마나 쓰세요?\n고객: 한 달에 5기가 정도 써요.\n상담원: 그럼 이 요금제가 더 저렴할 거예요.\n고객: 좋아요, 그걸로 바꿔 주세요.",
    body_en: "Customer: Hello. Is there a cheaper plan than my current one?\nAgent: Sure, how much data do you use?\nCustomer: About 5GB a month.\nAgent: Then this plan would be cheaper for you.\nCustomer: Great, please switch me to that one.", body_ja: "お客様: こんにちは。今のプランより安いプランはありますか。\n相談員: はい、データはどのくらい使いますか。\nお客様: 一か月に5ギガくらい使います。\n相談員: それならこちらのプランのほうがお得です。\nお客様: いいですね、それに変えてください。",
    questions: [
      { question_en: "How much data does the customer use per month?", question_ja: "お客様は一か月にどのくらいデータを使いますか。", options: ["1GB", "3GB", "5GB", "10GB"], answerIndex: 2 },
      { question_en: "What does the customer decide?", question_ja: "お客様は何を決めましたか。", options: ["Keep the same plan", "Cancel the phone", "Switch to the cheaper plan", "Add more data"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "장 볼 목록 부탁",
    title_en: "Asking a roommate to buy groceries", title_ja: "買い物リストのお願い",
    body_kr: "룸메이트: 나 지금 마트 가는데 뭐 필요해?\n나: 오, 우유 좀 사다 줄 수 있어?\n룸메이트: 응, 또 필요한 거 있어?\n나: 계란도 부탁해.\n룸메이트: 알겠어. 다녀와서 영수증 보여줄게.",
    body_en: "Roommate: I'm going to the store now, do you need anything?\nMe: Oh, can you buy some milk?\nRoommate: Sure, anything else?\nMe: Eggs too, please.\nRoommate: Got it. I'll show you the receipt when I get back.", body_ja: "ルームメイト: 今からスーパーに行くんだけど、何か必要?\n私: あ、牛乳を買ってきてくれる?\nルームメイト: うん、他に必要なものある?\n私: 卵もお願い。\nルームメイト: 分かった。帰ってきたらレシート見せるね。",
    questions: [
      { question_en: "What does the narrator ask for besides milk?", question_ja: "語り手は牛乳のほかに何を頼みましたか。", options: ["Bread", "Eggs", "Rice", "Cheese"], answerIndex: 1 },
      { question_en: "What will the roommate show after shopping?", question_ja: "ルームメイトは買い物の後、何を見せますか。", options: ["A photo", "The receipt", "The change", "A gift"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "좋은 병원 추천",
    title_en: "Recommending a good doctor", title_ja: "いい病院の紹介",
    body_kr: "나: 요즘 허리가 계속 아파. 좋은 병원 알아?\n지훈: 응, 우리 동네 정형외과 괜찮아.\n나: 예약해야 해?\n지훈: 응, 전화로 예약하면 돼.\n나: 고마워, 오늘 전화해 볼게.",
    body_en: "Me: My back has been hurting lately. Do you know a good doctor?\nJihoon: Yes, the orthopedic clinic in our neighborhood is good.\nMe: Do I need a reservation?\nJihoon: Yes, you can just call to make one.\nMe: Thanks, I'll call today.", body_ja: "私: 最近ずっと腰が痛いの。いい病院知ってる?\nジフン: うん、うちの近くの整形外科がいいよ。\n私: 予約しないといけない?\nジフン: うん、電話で予約すればいいよ。\n私: ありがとう、今日電話してみるね。",
    questions: [
      { question_en: "What is bothering the narrator?", question_ja: "語り手を悩ませているのは何ですか。", options: ["Headache", "Back pain", "Toothache", "Stomachache"], answerIndex: 1 },
      { question_en: "What clinic does Jihoon recommend?", question_ja: "ジフンはどの病院を勧めましたか。", options: ["Dermatology", "Dentistry", "Orthopedics", "Ophthalmology"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "여행 동안 고양이 부탁",
    title_en: "Asking a sibling to watch the cat during a trip", title_ja: "旅行中の猫のお願い",
    body_kr: "나: 다음 주에 여행 가는데 고양이 좀 봐줄 수 있어?\n동생: 응, 며칠이나 가?\n나: 5일 정도. 사료랑 물만 챙겨 주면 돼.\n동생: 알겠어. 열쇠는 어디에 둘 거야?\n나: 가기 전에 직접 줄게.",
    body_en: "Me: I'm traveling next week, can you watch the cat?\nYounger sibling: Sure, how many days?\nMe: About 5 days. You just need to give food and water.\nYounger sibling: Got it. Where will you leave the key?\nMe: I'll give it to you in person before I go.", body_ja: "私: 来週旅行に行くんだけど、猫を見てくれる?\n弟: うん、何日行くの?\n私: 5日くらい。えさと水だけあげてくれればいいよ。\n弟: 分かった。鍵はどこに置いておく?\n私: 行く前に直接渡すね。",
    questions: [
      { question_en: "How long is the trip?", question_ja: "旅行はどのくらいの期間ですか。", options: ["3 days", "5 days", "A week", "Two weeks"], answerIndex: 1 },
      { question_en: "What does the sibling need to do?", question_ja: "弟は何をする必要がありますか。", options: ["Walk the cat", "Give food and water", "Take the cat to the vet", "Clean the house"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "프로젝트 마감일 확인",
    title_en: "Confirming a project deadline", title_ja: "プロジェクトの締め切り確認",
    body_kr: "팀장님: 이번 프로젝트 마감이 언제였죠?\n나: 다음 주 금요일까지예요.\n팀장님: 시간이 부족할 것 같은데, 도움이 필요해요?\n나: 네, 자료 정리를 도와주시면 좋을 것 같아요.\n팀장님: 알겠어요, 내일부터 같이 할게요.",
    body_en: "Team leader: When was the deadline for this project?\nMe: It's by next Friday.\nTeam leader: It seems like there isn't enough time, do you need help?\nMe: Yes, it would help if you could assist with organizing the data.\nTeam leader: Okay, let's work on it together starting tomorrow.", body_ja: "チーム長: 今回のプロジェクトの締め切りはいつでしたっけ。\n私: 来週の金曜日までです。\nチーム長: 時間が足りなさそうですが、手伝いが必要ですか。\n私: はい、資料の整理を手伝っていただけたらありがたいです。\nチーム長: 分かりました、明日から一緒にやりましょう。",
    questions: [
      { question_en: "When is the project due?", question_ja: "プロジェクトの締め切りはいつですか。", options: ["Tomorrow", "This Friday", "Next Friday", "Next month"], answerIndex: 2 },
      { question_en: "What help does the narrator ask for?", question_ja: "語り手はどんな手伝いを頼みましたか。", options: ["Writing the whole report", "Organizing the data", "Extending the deadline", "Finding a new team"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "집 보러 가는 시간",
    title_en: "Scheduling an apartment viewing", title_ja: "部屋の内見の時間",
    body_kr: "세입자: 안녕하세요, 집 좀 보고 싶은데 언제 가능해요?\n집주인: 내일 오후는 어떠세요?\n세입자: 몇 시가 좋으세요?\n집주인: 2시쯤 오세요.\n세입자: 네, 그때 뵐게요.",
    body_en: "Tenant: Hello, I'd like to view the apartment, when is possible?\nLandlord: How about tomorrow afternoon?\nTenant: What time is good?\nLandlord: Come around 2pm.\nTenant: Okay, I'll see you then.", body_ja: "入居希望者: こんにちは、部屋を見たいのですが、いつ可能ですか。\n大家さん: 明日の午後はどうですか。\n入居希望者: 何時がよろしいですか。\n大家さん: 2時頃来てください。\n入居希望者: はい、その時にお伺いします。",
    questions: [
      { question_en: "When is the viewing scheduled?", question_ja: "内見はいつの予定ですか。", options: ["Today", "Tomorrow afternoon", "Next week", "This weekend"], answerIndex: 1 },
      { question_en: "What time will they meet?", question_ja: "何時に会いますか。", options: ["1pm", "2pm", "3pm", "4pm"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "비 오는데 계획 변경",
    title_en: "Changing plans because of rain", title_ja: "雨で計画変更",
    body_kr: "나: 오늘 등산 가기로 했는데 비가 많이 와.\n지수: 그러네, 위험할 것 같아.\n나: 그럼 대신 영화 볼까?\n지수: 좋아! 몇 시 영화가 있어?\n나: 오후 4시 표를 예매할게.",
    body_en: "Me: We planned to go hiking today, but it's raining a lot.\nJisu: You're right, it seems dangerous.\nMe: Then shall we watch a movie instead?\nJisu: Sounds good! What time is there a showing?\nMe: I'll book tickets for the 4pm show.", body_ja: "私: 今日登山に行くことにしてたのに、雨がたくさん降ってる。\nジス: そうだね、危なそう。\n私: それじゃあ代わりに映画を見ようか。\nジス: いいね!何時の映画がある?\n私: 午後4時の回を予約するね。",
    questions: [
      { question_en: "Why do they change their plan?", question_ja: "二人が計画を変えたのはなぜですか。", options: ["It's too cold", "It's raining", "They are tired", "The trail is closed"], answerIndex: 1 },
      { question_en: "What do they decide to do instead?", question_ja: "代わりに何をすることにしましたか。", options: ["Stay home", "Go shopping", "Watch a movie", "Go to a cafe"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "근무 시간 바꿔 줄 수 있어?",
    title_en: "Can you cover my shift?", title_ja: "シフトを代わってくれる?",
    body_kr: "동료: 이번 주 토요일 근무 바꿔 줄 수 있어요?\n나: 무슨 일 있어요?\n동료: 가족 행사가 있어서요.\n나: 알겠어요. 대신 다음 주 일요일 근무 바꿔 줄 수 있어요?\n동료: 네, 그렇게 할게요.",
    body_en: "Colleague: Can you switch shifts with me for this Saturday?\nMe: Is something going on?\nColleague: There's a family event.\nMe: Okay. In return, can you swap with me for next Sunday's shift?\nColleague: Sure, I'll do that.", body_ja: "同僚: 今週の土曜日の勤務、代わってもらえますか。\n私: 何かあるんですか。\n同僚: 家族の行事があって。\n私: 分かりました。代わりに来週の日曜日の勤務を代わってもらえますか。\n同僚: はい、そうします。",
    questions: [
      { question_en: "Why does the colleague need to swap shifts?", question_ja: "同僚がシフトを代わってほしいのはなぜですか。", options: ["Illness", "A family event", "A vacation", "A doctor's appointment"], answerIndex: 1 },
      { question_en: "What does the narrator ask in return?", question_ja: "語り手はお返しに何を頼みましたか。", options: ["Money", "To swap next Sunday's shift", "To work an extra day", "Nothing"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "미용실 예약 문의",
    title_en: "Asking about a hair salon appointment", title_ja: "美容室の予約の問い合わせ",
    body_kr: "고객: 이번 주 금요일에 예약 가능해요?\n미용실: 네, 몇 시가 좋으세요?\n고객: 오후 3시쯤이요.\n미용실: 3시는 예약이 다 찼어요. 4시는 어떠세요?\n고객: 네, 4시로 할게요.",
    body_en: "Customer: Is there an available appointment this Friday?\nSalon: Yes, what time is good for you?\nCustomer: Around 3pm.\nSalon: 3pm is fully booked. How about 4pm?\nCustomer: Okay, I'll take 4pm.", body_ja: "お客様: 今週の金曜日に予約できますか。\n美容室: はい、何時がよろしいですか。\nお客様: 午後3時頃です。\n美容室: 3時は予約がいっぱいです。4時はどうですか。\nお客様: はい、4時にします。",
    questions: [
      { question_en: "Why can't the customer get the 3pm slot?", question_ja: "お客様が3時の予約を取れないのはなぜですか。", options: ["The salon is closed", "It's fully booked", "The stylist is on vacation", "It's a holiday"], answerIndex: 1 },
      { question_en: "What time does the customer finally book?", question_ja: "お客様は最終的に何時を予約しましたか。", options: ["2pm", "3pm", "4pm", "5pm"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "시험 합격 축하",
    title_en: "Congratulating on passing an exam", title_ja: "試験合格のお祝い",
    body_kr: "나: 나 오늘 시험 결과 나왔어. 합격했어!\n유나: 정말? 축하해! 진짜 열심히 했잖아.\n나: 고마워, 너무 기뻐.\n유나: 우리 오늘 저녁에 축하 파티 하자.\n나: 좋아! 내가 저녁 살게.",
    body_en: "Me: My exam results came out today. I passed!\nYuna: Really? Congratulations! You worked so hard.\nMe: Thanks, I'm so happy.\nYuna: Let's have a celebration dinner tonight.\nMe: Sounds good! I'll buy dinner.", body_ja: "私: 今日試験の結果が出たの。合格したよ!\nユナ: 本当?おめでとう!すごく頑張ってたもんね。\n私: ありがとう、本当にうれしい。\nユナ: 今日の夜お祝いパーティーしよう。\n私: いいね!夕食は私がおごるよ。",
    questions: [
      { question_en: "What good news does the narrator share?", question_ja: "語り手はどんないいニュースを伝えましたか。", options: ["A new job", "Passing an exam", "A promotion", "Winning a prize"], answerIndex: 1 },
      { question_en: "Who will pay for dinner?", question_ja: "誰が夕食代を払いますか。", options: ["Yuna", "The narrator", "They will split it", "Neither"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "택배 위치 문의",
    title_en: "Asking about a package's location", title_ja: "宅配便の場所についての問い合わせ",
    body_kr: "고객: 안녕하세요. 제 택배가 아직 안 왔어요.\n기사님: 죄송합니다, 확인해 볼게요.\n고객: 언제쯤 받을 수 있어요?\n기사님: 오늘 오후 5시까지는 도착할 거예요.\n고객: 알겠습니다, 기다릴게요.",
    body_en: "Customer: Hello. My package still hasn't arrived.\nDriver: Sorry, let me check.\nCustomer: When can I expect it?\nDriver: It should arrive by 5pm today.\nCustomer: Okay, I'll wait.", body_ja: "お客様: こんにちは。私の荷物がまだ届いていません。\n配達員: 申し訳ありません、確認してみます。\nお客様: いつ頃受け取れますか。\n配達員: 今日の午後5時までには届くと思います。\nお客様: 分かりました、待ちますね。",
    questions: [
      { question_en: "What is the customer's problem?", question_ja: "お客様の問題は何ですか。", options: ["Wrong item delivered", "The package hasn't arrived", "The package is damaged", "The address is wrong"], answerIndex: 1 },
      { question_en: "When will the package arrive?", question_ja: "荷物はいつ届きますか。", options: ["Tomorrow", "By 5pm today", "Next week", "Right now"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "인터넷 요금 나누기",
    title_en: "Splitting the internet bill", title_ja: "インターネット料金の分担",
    body_kr: "룸메이트: 이번 달 인터넷 요금 얼마 나왔어?\n나: 총 4만 원 나왔어. 반씩 내자.\n룸메이트: 알겠어, 지금 바로 보낼게.\n나: 고마워. 통장으로 보내면 돼.\n룸메이트: 네, 방금 보냈어.",
    body_en: "Roommate: How much did the internet bill come to this month?\nMe: It was 40,000 won total. Let's split it in half.\nRoommate: Got it, I'll send it right now.\nMe: Thanks. You can send it to my bank account.\nRoommate: Okay, I just sent it.", body_ja: "ルームメイト: 今月のインターネット料金いくらだった?\n私: 全部で4万ウォンだったよ。半分ずつ払おう。\nルームメイト: 分かった、今すぐ送るね。\n私: ありがとう。銀行口座に送ってくれればいいよ。\nルームメイト: うん、たった今送ったよ。",
    questions: [
      { question_en: "How much was the total internet bill?", question_ja: "インターネット料金は全部でいくらでしたか。", options: ["20,000 won", "30,000 won", "40,000 won", "50,000 won"], answerIndex: 2 },
      { question_en: "How do they split the cost?", question_ja: "費用はどう分けますか。", options: ["Narrator pays all", "Roommate pays all", "Half and half", "They cancel the internet"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "돈 좀 빌려줄 수 있어?",
    title_en: "Can you lend me some money?", title_ja: "お金を貸してくれる?",
    body_kr: "나: 미안한데 이번 달에 돈이 좀 부족해서. 십만 원만 빌려줄 수 있어?\n현우: 응, 괜찮아. 언제 필요해?\n나: 이번 주까지 필요해.\n현우: 알겠어, 오늘 저녁에 보내 줄게.\n나: 정말 고마워. 다음 달에 바로 갚을게.",
    body_en: "Me: Sorry, but I'm a bit short on money this month. Can you lend me 100,000 won?\nHyunwoo: Sure, that's fine. When do you need it?\nMe: I need it by this week.\nHyunwoo: Got it, I'll send it tonight.\nMe: Thank you so much. I'll pay you back right next month.", body_ja: "私: ごめんだけど、今月ちょっとお金が足りなくて。十万ウォンだけ貸してくれる?\nヒョヌ: うん、いいよ。いつ必要?\n私: 今週中に必要なの。\nヒョヌ: 分かった、今日の夜送るね。\n私: 本当にありがとう。来月すぐ返すね。",
    questions: [
      { question_en: "How much does the narrator ask to borrow?", question_ja: "語り手はいくら借りたいと頼みましたか。", options: ["50,000 won", "100,000 won", "150,000 won", "200,000 won"], answerIndex: 1 },
      { question_en: "When will the narrator pay it back?", question_ja: "語り手はいつ返しますか。", options: ["Tomorrow", "This week", "Next month", "Never"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "화상 회의 시간 변경",
    title_en: "Rescheduling a video conference call", title_ja: "ビデオ会議の時間変更",
    body_kr: "동료: 내일 오전 회의 시간을 오후로 바꿀 수 있을까요?\n나: 왜요? 무슨 일 있어요?\n동료: 오전에 다른 일정이 생겼어요.\n나: 알겠어요. 오후 2시는 어때요?\n동료: 좋아요, 2시로 하죠.",
    body_en: "Colleague: Could we move tomorrow morning's meeting to the afternoon?\nMe: Why? Is something wrong?\nColleague: I have another schedule conflict in the morning.\nMe: Okay. How about 2pm?\nColleague: Good, let's do 2pm.", body_ja: "同僚: 明日午前中の会議を午後に変えられますか。\n私: どうしてですか。何かありますか。\n同僚: 午前中に別の予定ができて。\n私: 分かりました。午後2時はどうですか。\n同僚: いいですね、2時にしましょう。",
    questions: [
      { question_en: "Why does the colleague want to reschedule?", question_ja: "同僚が会議の時間を変えたい理由は何ですか。", options: ["Being sick", "A schedule conflict", "The internet is down", "The office is closed"], answerIndex: 1 },
      { question_en: "What time is the new meeting?", question_ja: "新しい会議は何時ですか。", options: ["12pm", "1pm", "2pm", "3pm"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "부모님 뵈러 가기",
    title_en: "Visiting our parents", title_ja: "両親に会いに行くこと",
    body_kr: "형: 이번 주말에 부모님 뵈러 갈 거야?\n나: 응, 토요일에 가려고. 같이 갈래?\n형: 좋아, 몇 시에 출발해?\n나: 아침 9시에 출발하자.\n형: 알겠어, 그때 우리 집 앞으로 갈게.",
    body_en: "Older brother: Are you going to visit our parents this weekend?\nMe: Yes, I'm planning to go Saturday. Want to come?\nOlder brother: Sure, what time are we leaving?\nMe: Let's leave at 9am.\nOlder brother: Got it, I'll come to your place by then.", body_ja: "兄: 今週末、両親に会いに行くの?\n私: うん、土曜日に行くつもり。一緒に行く?\n兄: いいよ、何時に出発する?\n私: 朝9時に出発しよう。\n兄: 分かった、その時間にうちの前に行くね。",
    questions: [
      { question_en: "When are they visiting their parents?", question_ja: "いつ両親に会いに行きますか。", options: ["Friday", "Saturday", "Sunday", "Monday"], answerIndex: 1 },
      { question_en: "What time will they leave?", question_ja: "何時に出発しますか。", options: ["7am", "8am", "9am", "10am"], answerIndex: 2 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "옷 사이즈 교환 문의",
    title_en: "Asking to exchange a clothing size", title_ja: "服のサイズ交換の問い合わせ",
    body_kr: "고객: 안녕하세요, 지난주에 산 셔츠가 너무 커요. 사이즈 교환할 수 있어요?\n상담원: 네, 가능합니다. 영수증 있으세요?\n고객: 네, 사진 보내 드릴게요.\n상담원: 확인했습니다. 작은 사이즈로 보내 드릴게요.\n고객: 감사합니다.",
    body_en: "Customer: Hello, the shirt I bought last week is too big. Can I exchange the size?\nAgent: Yes, that's possible. Do you have the receipt?\nCustomer: Yes, I'll send a photo.\nAgent: Confirmed. I'll send you a smaller size.\nCustomer: Thank you.", body_ja: "お客様: こんにちは、先週買ったシャツが大きすぎます。サイズ交換できますか。\n相談員: はい、可能です。レシートはお持ちですか。\nお客様: はい、写真をお送りします。\n相談員: 確認しました。小さいサイズをお送りします。\nお客様: ありがとうございます。",
    questions: [
      { question_en: "What is the problem with the shirt?", question_ja: "シャツの何が問題ですか。", options: ["Wrong color", "Too big", "Torn", "Too expensive"], answerIndex: 1 },
      { question_en: "What does the customer send to prove the purchase?", question_ja: "お客様は購入の証明として何を送りますか。", options: ["A copy of the shirt", "A photo of the receipt", "Cash", "Nothing"], answerIndex: 1 },
    ],
  },
  {
    level: "A2",
    genre: "message",
    title_kr: "오랜만에 안부 인사",
    title_en: "Catching up after a long time", title_ja: "久しぶりの近況報告",
    body_kr: "나: 오랜만이야! 잘 지냈어?\n예진: 응, 잘 지냈어! 너는 요즘 어때?\n나: 나도 잘 지내. 새 회사에서 일하고 있어.\n예진: 진짜? 언제 한번 만나서 얘기하자.\n나: 좋아, 다음 주에 시간 맞춰 보자.",
    body_en: "Me: Long time no see! How have you been?\nYejin: I've been good! How about you lately?\nMe: I'm doing well too. I'm working at a new company now.\nYejin: Really? Let's meet up sometime to talk.\nMe: Sounds good, let's find time next week.", body_ja: "私: 久しぶり!元気だった?\nイェジン: うん、元気だったよ!最近どう?\n私: 私も元気だよ。新しい会社で働いてるの。\nイェジン: 本当?今度会って話そうよ。\n私: いいね、来週時間を合わせよう。",
    questions: [
      { question_en: "What is new with the narrator?", question_ja: "語り手に何か新しいことはありますか。", options: ["Moved abroad", "Working at a new company", "Got married", "Started school"], answerIndex: 1 },
      { question_en: "What do they plan to do?", question_ja: "二人は何をする予定ですか。", options: ["Call every day", "Meet up next week", "Never talk again", "Move in together"], answerIndex: 1 },
    ],
  },
];
