import type { RawPassage } from "./types";

export const READING_B1_EXPLAINER: RawPassage[] = [
  {
    level: "B1",
    genre: "explainer",
    title_kr: "온돌이란 무엇인가",
    title_en: "What is ondol?", title_ja: "オンドルとは何か",
    body_kr: "온돌은 바닥을 데워서 방 전체를 따뜻하게 만드는 한국의 전통 난방 방식이다. 아궁이에서 불을 때면 뜨거운 열기가 바닥 아래의 통로를 지나가면서 방바닥을 데운다고 한다. 위에서부터 데우는 서양의 난방과 달리 온돌은 아래에서부터 열을 전달하기 때문에 발이 먼저 따뜻해진다. 요즘 아파트에서는 아궁이 대신 보일러로 데운 물을 바닥에 흘려보내는 방식으로 온돌의 원리를 이어 가고 있다. 이런 이유로 한국 사람들은 지금도 바닥에 앉거나 눕는 것을 편안하게 느낀다.",
    body_en: "Ondol is Korea's traditional heating method, which warms an entire room by heating the floor. It is said that when a fire is lit in the furnace, the hot air passes through channels beneath the floor and warms it. Unlike Western heating, which warms from above, ondol delivers heat from below, so the feet get warm first. In modern apartments, instead of a furnace, boilers heat water that flows under the floor, continuing the same principle as ondol. For this reason, Korean people still feel comfortable sitting or lying on the floor today.", body_ja: "オンドルは床を温めて部屋全体を暖かくする韓国伝統の暖房方式である。かまどで火を焚くと、熱い空気が床下の通路を通って床を温めるという。上から温める西洋の暖房と違い、オンドルは下から熱を伝えるため足元から先に暖まる。最近のマンションではかまどの代わりにボイラーで温めた水を床に流す方式で、オンドルの原理を受け継いでいる。こうした理由から韓国人は今も床に座ったり横になったりすることを快適に感じる。",
    questions: [
      { question_en: "How does ondol heat differ from Western heating?", question_ja: "オンドルの暖房方式は西洋の暖房とどう違いますか。", options: ["It heats from below instead of above", "It only heats the ceiling", "It uses electric fans", "It cools the room first"], answerIndex: 0 },
      { question_en: "How do modern apartments continue the ondol principle?", question_ja: "現代のマンションはどのようにオンドルの原理を受け継いでいますか。", options: ["By burning wood indoors", "By using boilers to heat water under the floor", "By using space heaters", "By heating the walls only"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한복의 특징",
    title_en: "Features of hanbok", title_ja: "韓服の特徴",
    body_kr: "한복은 곡선이 강조된 디자인과 넉넉한 품이 특징인 한국의 전통 의복이다. 여성 한복은 짧은 저고리와 넓게 퍼지는 치마로 이루어져 있어서 움직일 때마다 부드러운 선이 드러난다. 남성 한복은 저고리와 바지로 구성되며 활동하기 편하도록 비교적 여유 있게 만들어졌다. 옷감의 색깔에도 의미가 담겨 있어서 결혼식처럼 중요한 행사에서는 화려한 색을 즐겨 사용한다고 한다. 요즘에는 명절이나 특별한 날에 주로 입지만 편하게 개량한 생활 한복도 인기를 얻고 있다.",
    body_en: "Hanbok is Korea's traditional clothing, characterized by curved designs and roomy fit. Women's hanbok consists of a short jacket and a wide, flowing skirt, so soft lines appear with every movement. Men's hanbok is made up of a jacket and pants, cut relatively loose for ease of movement. The colors of the fabric also carry meaning, and it is said that bright colors are favored for important occasions like weddings. These days, hanbok is mostly worn on holidays or special occasions, but comfortable modernized versions have also become popular.", body_ja: "韓服は曲線を強調したデザインとゆったりとした形が特徴の韓国の伝統衣装である。女性用の韓服は短いチョゴリと大きく広がるチマから成り、動くたびに柔らかな線が現れる。男性用の韓服はチョゴリとズボンで構成され、動きやすいように比較的ゆとりを持たせて作られている。生地の色にも意味が込められており、結婚式のような重要な行事では華やかな色がよく使われるという。最近では祝日や特別な日に主に着られるが、着やすく改良した生活韓服も人気を集めている。",
    questions: [
      { question_en: "What is a key feature of women's hanbok?", question_ja: "女性用韓服の主な特徴は何ですか。", options: ["A short jacket and a wide flowing skirt", "Tight-fitting pants", "A single long robe", "A hat and gloves"], answerIndex: 0 },
      { question_en: "When are bright colors especially favored in hanbok?", question_ja: "韓服で華やかな色が特に好まれるのはいつですか。", options: ["For everyday work clothes", "For sleeping", "For important occasions like weddings", "Only in winter"], answerIndex: 2 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "젓가락 사용 예절",
    title_en: "Chopstick etiquette", title_ja: "箸の使い方のマナー",
    body_kr: "한국에서 젓가락은 숟가락과 함께 식사할 때 꼭 필요한 도구이다. 밥그릇에 젓가락을 똑바로 꽂아 두는 행동은 제사 때의 모습을 떠올리게 하기 때문에 예의에 어긋난다고 여겨진다. 또한 음식을 집을 때 젓가락으로 이리저리 뒤적이는 것도 함께 식사하는 사람에게 불쾌감을 줄 수 있다. 국물이 있는 음식은 젓가락 대신 숟가락으로 먹는 것이 자연스럽고, 밥과 반찬은 젓가락으로 먹는 경우가 많다. 이런 예절을 지키면 어른들과 함께 식사할 때 더욱 정중한 인상을 줄 수 있다.",
    body_en: "In Korea, chopsticks are an essential tool for meals, used along with a spoon. Sticking chopsticks straight up in a bowl of rice is considered impolite because it recalls the way food is offered at ancestral rites. Also, stirring or poking through food with chopsticks while choosing what to eat can make others at the table uncomfortable. It is natural to eat soup with a spoon rather than chopsticks, while rice and side dishes are often eaten with chopsticks. Following these manners can leave a more respectful impression when eating with elders.", body_ja: "韓国では箸はスプーンとともに食事に欠かせない道具である。ご飯茶碗に箸をまっすぐ立てて置く行為は祭祀の様子を連想させるため、マナー違反とされている。また、食べ物を選ぶときに箸であちこちかき混ぜることも、一緒に食事をする人に不快感を与えることがある。スープのような汁物は箸ではなくスプーンで食べるのが自然で、ご飯やおかずは箸で食べることが多い。こうしたマナーを守ると、目上の人と食事をするときにより丁寧な印象を与えられる。",
    questions: [
      { question_en: "Why is sticking chopsticks upright in rice considered impolite?", question_ja: "ご飯に箸をまっすぐ立てることがマナー違反とされる理由は何ですか。", options: ["It wastes food", "It resembles ancestral rite offerings", "It breaks the chopsticks", "It is too slow"], answerIndex: 1 },
      { question_en: "What is typically used to eat soup?", question_ja: "スープを食べるときに一般的に使われるものは何ですか。", options: ["Fingers", "Chopsticks", "A spoon", "A fork"], answerIndex: 2 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "지하철 환승 시스템",
    title_en: "The subway transfer system", title_ja: "地下鉄の乗り換えシステム",
    body_kr: "서울의 지하철은 여러 노선이 서로 연결되어 있어서 한 번의 요금으로 다른 노선으로 갈아탈 수 있다. 승객은 교통카드를 태그하고 내렸다가 삼십 분 안에 다시 다른 노선의 열차를 타면 추가 요금 없이 환승할 수 있다고 한다. 노선마다 색깔이 다르게 표시되어 있어서 처음 이용하는 사람도 표지판만 보고 길을 찾기가 비교적 쉽다. 환승역에는 노선을 갈아탈 수 있는 통로가 있으며 표지판을 따라가면 헤매지 않고 이동할 수 있다. 이러한 환승 시스템 덕분에 서울에서는 자동차 없이도 도시 곳곳을 편리하게 다닐 수 있다.",
    body_en: "Seoul's subway lines are connected to one another, so passengers can transfer to a different line using a single fare. If a passenger taps their transit card and boards another line's train within thirty minutes, the transfer is made without an extra charge, it is said. Each line is marked with a different color, so even first-time users can find their way fairly easily just by following the signs. Transfer stations have passages connecting the lines, and following the signs lets riders move without getting lost. Thanks to this transfer system, people can conveniently get around Seoul without a car.", body_ja: "ソウルの地下鉄は複数の路線が互いに接続されており、一回の運賃で別の路線に乗り換えることができる。交通カードをタッチして降り、30分以内に別路線の列車に乗れば追加料金なしで乗り換えられるという。路線ごとに色分けされているため、初めて利用する人でも標識を見るだけで比較的簡単に道を見つけられる。乗換駅には路線を乗り継げる通路があり、標識に沿って進めば迷わずに移動できる。このような乗り換えシステムのおかげで、ソウルでは車がなくても市内各地を便利に移動できる。",
    questions: [
      { question_en: "What allows a passenger to transfer without an extra fare?", question_ja: "乗客が追加料金なしで乗り換えられるのはどんな条件のときですか。", options: ["Boarding within thirty minutes on another line", "Buying a second ticket", "Only traveling before noon", "Using a paper ticket"], answerIndex: 0 },
      { question_en: "How are subway lines distinguished for easy navigation?", question_ja: "路線を分かりやすくするために何が使われていますか。", options: ["By different colors", "By different sounds", "By different station sizes", "By different train speeds"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "분리수거 규칙",
    title_en: "Recycling separation rules", title_ja: "ゴミ分別のルール",
    body_kr: "한국에서는 쓰레기를 종류별로 나누어 버리는 분리수거 제도가 엄격하게 지켜지고 있다. 종이, 플라스틱, 유리, 캔은 각각 정해진 통에 따로 담아야 하며, 음식물 쓰레기는 반드시 별도의 봉투에 담아 버려야 한다. 일반 쓰레기는 지역마다 지정된 종량제 봉투에 넣어야 하기 때문에 봉투를 사지 않으면 쓰레기를 버릴 수 없다. 플라스틱을 버릴 때는 라벨을 떼고 안을 깨끗이 헹구는 것이 좋다고 알려져 있다. 이러한 규칙을 지키지 않으면 벌금을 내야 할 수도 있어서 대부분의 주민들이 분리수거를 습관처럼 실천한다.",
    body_en: "In Korea, a strict system requires waste to be separated by type before disposal. Paper, plastic, glass, and cans must each go into their designated bins, and food waste must be thrown away in a separate bag. General waste must be placed in region-specific pay-as-you-throw bags, so without buying such a bag, one cannot dispose of trash. It is recommended to remove labels and rinse containers clean before recycling plastic. Failing to follow these rules can result in a fine, so most residents practice recycling as a habit.", body_ja: "韓国ではゴミを種類別に分けて捨てる分別収集の制度が厳しく守られている。紙、プラスチック、ガラス、缶はそれぞれ決められた容器に分けて入れなければならず、生ゴミは必ず別の袋に入れて捨てなければならない。一般ゴミは地域ごとに指定された従量制の袋に入れる必要があるため、その袋を買わなければゴミを捨てることができない。プラスチックを捨てるときはラベルを剥がし、中をきれいにすすぐとよいとされている。こうしたルールを守らないと罰金を払わなければならないこともあるため、ほとんどの住民が分別収集を習慣として実践している。",
    questions: [
      { question_en: "What must food waste be placed in?", question_ja: "生ゴミは何に入れなければなりませんか。", options: ["The same bag as plastic", "A separate bag", "Any general bin", "A glass container only"], answerIndex: 1 },
      { question_en: "What happens if someone doesn't follow the recycling rules?", question_ja: "分別のルールを守らないとどうなる可能性がありますか。", options: ["Nothing at all", "They may receive a fine", "They get a reward", "Their trash is collected first"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "대중교통 환승 할인 제도",
    title_en: "The public transit transfer discount system", title_ja: "大衆交通の乗り換え割引制度",
    body_kr: "한국의 대중교통 요금제는 버스와 지하철을 갈아타도 요금이 크게 늘지 않도록 설계되어 있다. 같은 교통카드로 버스에서 지하철로, 혹은 지하철에서 버스로 갈아탈 때 기본요금이 한 번만 부과된다고 한다. 이동 거리가 늘어나면 추가 요금이 붙지만 처음부터 새로 요금을 내는 것보다 훨씬 저렴하다. 이 제도 덕분에 먼 거리를 이동할 때도 여러 번 갈아타는 것에 대한 부담이 줄어든다. 이러한 환승 할인은 대중교통 이용을 늘리고 자가용 이용을 줄이려는 목적에서 만들어졌다고 한다.",
    body_en: "Korea's public transit fare system is designed so that fares don't rise sharply when passengers transfer between buses and subways. Using the same transit card, when transferring from bus to subway or subway to bus, the base fare is said to be charged only once. As the distance traveled increases, an extra charge is added, but it is still much cheaper than paying a fresh new fare each time. Thanks to this system, the burden of transferring multiple times is reduced even for long trips. This transfer discount is said to have been created to encourage public transit use and reduce car use.", body_ja: "韓国の大衆交通の料金制度は、バスと地下鉄を乗り換えても料金が大きく増えないように設計されている。同じ交通カードでバスから地下鉄へ、または地下鉄からバスへ乗り換えるとき、基本料金は一度しか課金されないという。移動距離が伸びると追加料金がつくが、最初から新たに料金を払うよりずっと安くなる。この制度のおかげで、遠くまで移動する際に何度も乗り換える負担が軽減される。この乗り換え割引は大衆交通の利用を増やし、自家用車の利用を減らす目的で作られたと言われている。",
    questions: [
      { question_en: "What happens to the base fare when transferring between bus and subway?", question_ja: "バスと地下鉄を乗り換えるとき、基本料金はどうなりますか。", options: ["It is charged twice", "It is charged only once", "It doubles", "It is refunded"], answerIndex: 1 },
      { question_en: "What was the purpose of creating this discount system?", question_ja: "この割引制度が作られた目的は何ですか。", options: ["To make buses faster", "To encourage public transit use and reduce car use", "To fund new subway lines", "To limit late-night travel"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "국민건강보험 제도",
    title_en: "The national health insurance system", title_ja: "国民健康保険制度",
    body_kr: "한국의 국민건강보험은 모든 국민이 의무적으로 가입해야 하는 공공 의료 보험 제도이다. 매달 소득에 따라 보험료를 내면 병원에서 진료를 받을 때 비용의 상당 부분을 보험이 대신 부담해 준다. 이 제도 덕분에 큰 수술이나 장기 치료가 필요한 경우에도 개인이 부담하는 비용이 크게 줄어든다고 한다. 회사에 다니는 사람은 회사와 보험료를 나누어 내지만 자영업자나 소득이 없는 사람도 가입해야 한다. 이러한 보편적인 보험 제도는 외국인들 사이에서도 한국 의료 체계의 큰 장점으로 자주 언급된다.",
    body_en: "Korea's National Health Insurance is a public medical insurance system that all citizens are required to join. By paying premiums each month based on income, a large portion of medical costs is covered by insurance when receiving treatment at a hospital. Thanks to this system, even in cases requiring major surgery or long-term treatment, the amount an individual has to pay is said to be greatly reduced. Employees split the premium with their company, but self-employed people and those without income must also enroll. This universal insurance system is often mentioned among foreigners as a major strength of Korea's medical system.", body_ja: "韓国の国民健康保険は、すべての国民が加入を義務づけられている公的医療保険制度である。毎月所得に応じて保険料を納めると、病院で診療を受ける際に費用の大部分を保険が代わりに負担してくれる。この制度のおかげで、大きな手術や長期治療が必要な場合でも個人が負担する費用が大幅に減るという。会社員は会社と保険料を折半するが、自営業者や所得のない人も加入しなければならない。このような普遍的な保険制度は、外国人の間でも韓国の医療制度の大きな長所としてよく言及される。",
    questions: [
      { question_en: "Who is required to join the national health insurance?", question_ja: "国民健康保険への加入が義務づけられているのは誰ですか。", options: ["Only employees", "Only self-employed people", "All citizens", "Only the elderly"], answerIndex: 2 },
      { question_en: "How do employees typically pay their premiums?", question_ja: "会社員はどのように保険料を支払いますか。", options: ["The government pays entirely", "They split it with their company", "They pay nothing", "They pay double the rate"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "장마철이란 무엇인가",
    title_en: "What is jangma season?", title_ja: "梅雨とは何か",
    body_kr: "장마는 초여름에 한반도 전역에 걸쳐 비가 계속 내리는 시기를 말한다. 보통 6월 하순부터 7월 중순까지 이어지며 이 시기에는 습도가 매우 높아진다고 한다. 따뜻한 공기와 차가운 공기가 만나 정체 전선을 이루기 때문에 며칠씩 비가 그치지 않는 경우도 흔하다. 장마철에는 갑자기 폭우가 쏟아지는 일이 많아서 홍수나 산사태 같은 피해에 대비해야 한다. 장마가 끝나면 곧이어 무더운 여름이 본격적으로 시작되기 때문에 장마는 여름의 시작을 알리는 신호로도 여겨진다.",
    body_en: "Jangma refers to the period in early summer when rain falls continuously across the Korean peninsula. It usually lasts from late June to mid-July, and humidity is said to become very high during this period. Because warm air and cold air meet to form a stationary front, it is common for rain not to stop for several days in a row. During jangma, sudden heavy downpours often occur, so people must prepare for damage like floods or landslides. Since scorching summer weather begins in earnest right after jangma ends, it is also regarded as a signal marking the start of summer.", body_ja: "梅雨とは初夏に朝鮮半島全域で雨が降り続く時期のことを指す。通常6月下旬から7月中旬まで続き、この時期は湿度が非常に高くなるという。暖かい空気と冷たい空気がぶつかって停滞前線を作るため、何日も雨が止まないことも珍しくない。梅雨の時期には突然大雨が降ることが多いため、洪水や土砂崩れなどの被害に備える必要がある。梅雨が終わるとすぐに本格的な猛暑が始まるため、梅雨は夏の始まりを知らせる合図としても考えられている。",
    questions: [
      { question_en: "When does jangma usually occur?", question_ja: "梅雨は通常いつ起こりますか。", options: ["Late June to mid-July", "December to January", "Early spring", "Late autumn"], answerIndex: 0 },
      { question_en: "What can happen suddenly during jangma?", question_ja: "梅雨の時期に突然起こりうることは何ですか。", options: ["Snowstorms", "Heavy downpours", "Sandstorms", "Heat waves only"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "황사란 무엇인가",
    title_en: "What is hwangsa (yellow dust)?", title_ja: "黄砂とは何か",
    body_kr: "황사는 중국이나 몽골의 사막 지역에서 바람에 날려 온 미세한 모래와 흙먼지가 한국까지 이동하는 현상이다. 주로 봄철에 자주 발생하며 하늘이 뿌옇게 흐려지고 시야가 나빠진다고 한다. 황사에는 먼지뿐 아니라 여러 오염 물질이 섞여 있을 수 있어서 호흡기가 약한 사람에게는 특히 해롭다. 황사가 심한 날에는 마스크를 착용하고 창문을 닫는 것이 좋다고 전문가들은 조언한다. 최근에는 사막화가 심해지면서 황사가 발생하는 빈도와 강도가 예전보다 높아졌다는 연구도 있다.",
    body_en: "Hwangsa is a phenomenon in which fine sand and dust, blown from desert regions in China or Mongolia, travels all the way to Korea. It occurs mainly in spring, and it is said that the sky turns hazy and visibility worsens. Hwangsa can contain not only dust but also various pollutants mixed in, making it especially harmful to people with weak respiratory systems. Experts advise wearing a mask and closing windows on days when hwangsa is severe. Some recent research also suggests that as desertification worsens, the frequency and intensity of hwangsa have increased compared to before.", body_ja: "黄砂とは中国やモンゴルの砂漠地帯から風で運ばれた細かい砂や土ぼこりが韓国まで移動してくる現象である。主に春によく発生し、空がかすんで見通しが悪くなるという。黄砂には粉じんだけでなく様々な汚染物質が混ざっていることがあり、呼吸器が弱い人には特に有害である。黄砂がひどい日にはマスクを着用し、窓を閉めるとよいと専門家は助言する。最近では砂漠化が進み、黄砂が発生する頻度と強さが以前より高くなったという研究もある。",
    questions: [
      { question_en: "Where does hwangsa originate?", question_ja: "黄砂はどこから来ますか。", options: ["Ocean currents near Korea", "Desert regions in China or Mongolia", "Volcanic eruptions in Japan", "Forest fires"], answerIndex: 1 },
      { question_en: "What do experts advise on days with severe hwangsa?", question_ja: "黄砂がひどい日に専門家は何を勧めていますか。", options: ["Open all windows", "Go outside more often", "Wear a mask and close windows", "Ignore it completely"], answerIndex: 2 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국의 사계절",
    title_en: "Korea's four seasons", title_ja: "韓国の四季",
    body_kr: "한국은 봄, 여름, 가을, 겨울이 뚜렷하게 구분되는 사계절을 가진 나라이다. 봄에는 벚꽃과 진달래 같은 꽃이 피어나면서 날씨가 점점 따뜻해진다. 여름은 덥고 습한 편이며 장마철이 지나면 본격적인 무더위가 이어진다고 한다. 가을에는 선선한 바람이 불고 단풍이 물들어서 많은 사람들이 산이나 공원으로 나들이를 간다. 겨울은 대체로 춥고 건조하며 지역에 따라 눈이 많이 내리기도 해서 계절마다 옷차림과 생활 방식이 크게 달라진다.",
    body_en: "Korea is a country with four clearly distinguished seasons: spring, summer, autumn, and winter. In spring, flowers like cherry blossoms and azaleas bloom as the weather gradually warms. Summer tends to be hot and humid, and it is said that intense heat continues once jangma season ends. In autumn, cool winds blow and leaves change color, so many people go on outings to mountains or parks. Winter is generally cold and dry, and in some regions heavy snow falls, so clothing and lifestyle change greatly from season to season.", body_ja: "韓国は春、夏、秋、冬がはっきりと分かれた四季を持つ国である。春には桜やツツジのような花が咲き、天気が徐々に暖かくなる。夏は暑くて湿度が高く、梅雨が終わると本格的な猛暑が続くという。秋には涼しい風が吹き紅葉が色づき、多くの人が山や公園へ出かける。冬はおおむね寒くて乾燥しており、地域によっては雪がたくさん降ることもあるため、季節ごとに服装や生活様式が大きく変わる。",
    questions: [
      { question_en: "What happens in Korea right after jangma season?", question_ja: "韓国では梅雨が終わった直後に何が起こりますか。", options: ["Snow begins", "Intense heat continues", "Leaves change color", "Flowers bloom"], answerIndex: 1 },
      { question_en: "What do many people do in autumn?", question_ja: "秋に多くの人がすることは何ですか。", options: ["Stay indoors all day", "Go on outings to see the changing leaves", "Plant crops", "Avoid parks"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "배달 문화",
    title_en: "Delivery culture", title_ja: "デリバリー文化",
    body_kr: "한국은 배달 음식 문화가 매우 발달한 나라로 잘 알려져 있다. 스마트폰 애플리케이션 하나로 다양한 음식점의 메뉴를 확인하고 몇 분 안에 주문할 수 있다. 대부분의 지역에서는 주문한 지 삼십 분에서 한 시간 안에 음식이 집 앞까지 배달된다고 한다. 심지어 늦은 밤이나 궂은 날씨에도 배달이 가능해서 많은 사람들이 이 서비스를 자주 이용한다. 이러한 빠른 배달 문화는 배달원들의 오토바이 이동과 위치 추적 기술 덕분에 가능해졌다고 알려져 있다.",
    body_en: "Korea is well known as a country with a highly developed food delivery culture. With a single smartphone app, people can check menus from various restaurants and place an order within minutes. In most areas, food is said to arrive at the doorstep within thirty minutes to an hour after ordering. Delivery is even possible late at night or in bad weather, so many people use this service frequently. This fast delivery culture is known to be made possible by delivery riders' motorcycles and location-tracking technology.", body_ja: "韓国は出前・デリバリーの食文化が非常に発達した国としてよく知られている。スマートフォンのアプリ一つで様々な飲食店のメニューを確認し、数分で注文できる。ほとんどの地域では注文してから30分から1時間以内に自宅前まで食べ物が届けられるという。夜遅くや悪天候の日でも配達が可能なため、多くの人がこのサービスを頻繁に利用している。このような速い配達文化は、配達員のバイク移動と位置追跡技術のおかげで可能になったと言われている。",
    questions: [
      { question_en: "How is food delivery typically ordered in Korea?", question_ja: "韓国ではどのように出前を注文しますか。", options: ["By calling a landline only", "Through a smartphone app", "By visiting the restaurant first", "Through the mail"], answerIndex: 1 },
      { question_en: "What makes fast delivery possible according to the passage?", question_ja: "この文章によると、速い配達を可能にしているものは何ですか。", options: ["Only walking couriers", "Motorcycles and location-tracking technology", "Trains", "Drones exclusively"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "편의점 문화",
    title_en: "Convenience store culture", title_ja: "コンビニ文化",
    body_kr: "한국의 편의점은 단순히 물건을 파는 가게를 넘어 생활의 다양한 필요를 채워 주는 공간으로 자리 잡았다. 대부분의 편의점은 하루 종일, 심지어 명절에도 문을 열기 때문에 언제든 필요한 물건을 살 수 있다. 도시락이나 삼각김밥 같은 간편식이 다양하게 준비되어 있어서 바쁜 직장인이나 학생들이 자주 이용한다. 또한 공과금을 내거나 택배를 보내고 받는 일도 편의점에서 처리할 수 있다고 한다. 이런 편리함 덕분에 편의점은 한국인의 일상에서 없어서는 안 될 장소가 되었다.",
    body_en: "Korean convenience stores have become spaces that fulfill various daily needs, going beyond simply selling goods. Most convenience stores are open all day, even on holidays, so people can buy what they need at any time. A variety of ready-to-eat foods, like lunch boxes and triangle kimbap, are available, so busy workers and students use them often. It is also said that paying utility bills and sending or receiving parcels can be handled at convenience stores. Thanks to this convenience, convenience stores have become an indispensable part of daily life in Korea.", body_ja: "韓国のコンビニは、単に物を売る店を超えて、生活のさまざまな必要を満たす場所として定着している。ほとんどのコンビニは一日中、祝日でさえも営業しているため、いつでも必要な物を買うことができる。弁当や三角キンパのような手軽な食品が豊富にそろっており、忙しい会社員や学生がよく利用する。また、公共料金の支払いや宅配便の発送・受け取りもコンビニで処理できるという。こうした便利さのおかげで、コンビニは韓国人の日常に欠かせない場所となった。",
    questions: [
      { question_en: "When are most Korean convenience stores open?", question_ja: "ほとんどの韓国のコンビニはいつ営業していますか。", options: ["Only on weekdays", "All day, even on holidays", "Only in the morning", "Only at night"], answerIndex: 1 },
      { question_en: "What besides shopping can be done at a convenience store?", question_ja: "買い物以外にコンビニでできることは何ですか。", options: ["Getting a haircut", "Paying utility bills and sending parcels", "Renting a car", "Filing taxes"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "카페 문화",
    title_en: "Cafe culture", title_ja: "カフェ文化",
    body_kr: "한국에서 카페는 단순히 커피를 마시는 곳이 아니라 공부하거나 일하는 공간으로도 널리 쓰인다. 콘센트와 무료 와이파이를 갖춘 카페가 많아서 노트북을 들고 와 오랜 시간 머무는 손님도 흔히 볼 수 있다. 이런 사람들을 가리켜 카페와 사무실을 합친 말로 '카공족'이라고 부르기도 한다고 한다. 도시 곳곳에는 개성 있는 인테리어로 꾸며진 카페가 많아서 사진을 찍으러 방문하는 사람들도 적지 않다. 이렇게 다양한 이유로 카페를 찾는 사람들이 늘면서 카페는 한국인의 일상과 여가에 깊이 자리 잡았다.",
    body_en: "In Korea, cafes are not just places to drink coffee but are also widely used as spaces to study or work. Many cafes have outlets and free Wi-Fi, so it is common to see customers bring laptops and stay for long hours. Such people are said to sometimes be called 'kagongjok,' a term combining cafe and studying. Many cafes around cities are decorated with distinctive interiors, so quite a few people visit just to take photos. As more people visit cafes for these various reasons, cafes have become deeply embedded in Koreans' daily life and leisure.", body_ja: "韓国でカフェは単にコーヒーを飲む場所ではなく、勉強や仕事をする空間としても広く使われている。コンセントと無料Wi-Fiを備えたカフェが多く、ノートパソコンを持ち込んで長時間滞在する客もよく見られる。こうした人々はカフェと勉強を合わせて「カゴンジョク」と呼ばれることもあるという。街中には個性的な内装で飾られたカフェが多く、写真を撮りに訪れる人も少なくない。こうした様々な理由でカフェを訪れる人が増え、カフェは韓国人の日常と余暇に深く根付いている。",
    questions: [
      { question_en: "Why do many people stay long hours at cafes?", question_ja: "多くの人がカフェで長時間過ごすのはなぜですか。", options: ["To sleep", "To study or work using outlets and Wi-Fi", "To avoid the rain", "To meet strangers"], answerIndex: 1 },
      { question_en: "Why do some people visit distinctively decorated cafes?", question_ja: "個性的な内装のカフェを訪れる人がいるのはなぜですか。", options: ["To buy furniture", "To take photos", "To attend classes", "To exercise"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "찜질방이란 무엇인가",
    title_en: "What is a jjimjilbang?", title_ja: "チムジルバンとは何か",
    body_kr: "찜질방은 목욕탕과 사우나, 휴게 공간이 함께 있는 한국의 대중 목욕 시설이다. 방문객은 몸을 씻은 후 편안한 옷으로 갈아입고 뜨거운 찜질방 안에서 땀을 흘리며 휴식을 취한다고 한다. 찜질방 안에는 온도가 다른 여러 개의 방이 있어서 사람들은 취향에 따라 방을 옮겨 다니며 즐긴다. 식혜나 삶은 계란 같은 간단한 간식을 파는 곳도 있어서 가족 단위로 시간을 보내기에 좋다. 일부 찜질방은 이십사 시간 운영되기 때문에 저렴한 숙소 대신 하룻밤을 보내는 사람들도 있다.",
    body_en: "A jjimjilbang is a public bathing facility in Korea that combines a bathhouse, sauna, and resting areas. It is said that visitors wash themselves, change into comfortable clothes, and relax while sweating inside the hot sauna rooms. Inside a jjimjilbang there are several rooms with different temperatures, so people move between rooms to enjoy the one they prefer. Some also sell simple snacks like sikhye or boiled eggs, making it a good place for families to spend time together. Since some jjimjilbangs operate twenty-four hours, some people spend the night there instead of paying for cheap lodging.", body_ja: "チムジルバンは、浴場とサウナ、休憩スペースが一緒になった韓国の公衆浴場施設である。訪問客は体を洗った後、楽な服に着替え、熱いサウナ室で汗を流しながら休息を取るという。チムジルバンの中には温度の異なる複数の部屋があり、人々は好みに応じて部屋を移動しながら楽しむ。シッケや茹で卵のような簡単なおやつを売る店もあり、家族連れで時間を過ごすのにも良い。一部のチムジルバンは24時間営業しているため、安い宿の代わりに一晩を過ごす人もいる。",
    questions: [
      { question_en: "What does a jjimjilbang combine?", question_ja: "チムジルバンには何が組み合わさっていますか。", options: ["A gym and a library", "A bathhouse, sauna, and resting areas", "A restaurant and a cinema", "A hospital and a hotel"], answerIndex: 1 },
      { question_en: "Why do some people spend the night at a jjimjilbang?", question_ja: "一部の人がチムジルバンで一晩過ごすのはなぜですか。", options: ["It's required by law", "Some operate 24 hours as a cheap lodging option", "They get lost there", "It is free only at night"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "커피의 카페인 함량",
    title_en: "The caffeine content of coffee", title_ja: "コーヒーのカフェイン含有量",
    body_kr: "커피에 들어 있는 카페인의 양은 원두의 종류와 추출 방법에 따라 크게 달라진다고 한다. 일반적으로 에스프레소 한 잔보다 아메리카노처럼 물로 희석한 커피가 오히려 카페인 총량이 더 많은 경우도 있다. 이는 아메리카노에 사용되는 원액의 양이 에스프레소보다 많기 때문이라고 알려져 있다. 카페인은 각성 효과가 있어서 졸음을 줄여 주지만 지나치게 많이 섭취하면 심장이 빨리 뛰거나 잠을 이루기 어려워질 수 있다. 이런 이유로 전문가들은 하루에 마시는 커피의 양을 적절히 조절할 것을 권한다.",
    body_en: "The amount of caffeine in coffee is said to vary greatly depending on the type of bean and the brewing method. Generally, a diluted coffee like an Americano can actually contain more total caffeine than a single shot of espresso. This is because the amount of coffee extract used in an Americano is greater than that in espresso, it is known. Caffeine has a stimulating effect that reduces sleepiness, but consuming too much can cause a racing heart or trouble falling asleep. For this reason, experts recommend properly controlling how much coffee one drinks per day.", body_ja: "コーヒーに含まれるカフェインの量は、豆の種類や抽出方法によって大きく異なるという。一般的にエスプレッソ1杯よりも、アメリカーノのように水で薄めたコーヒーの方が、カフェインの総量が多い場合もある。これはアメリカーノに使われる原液の量がエスプレッソより多いためだと言われている。カフェインには覚醒効果があり眠気を減らしてくれるが、摂りすぎると心臓がドキドキしたり、なかなか寝つけなくなったりすることがある。こうした理由から、専門家は一日に飲むコーヒーの量を適度に調整することを勧めている。",
    questions: [
      { question_en: "Why might an Americano contain more caffeine than an espresso shot?", question_ja: "アメリカーノがエスプレッソショットよりカフェインが多い場合があるのはなぜですか。", options: ["It uses more coffee extract", "It is brewed longer", "It uses a different bean entirely", "It has added caffeine powder"], answerIndex: 0 },
      { question_en: "What can too much caffeine cause?", question_ja: "カフェインの摂りすぎは何を引き起こす可能性がありますか。", options: ["Better sleep", "A racing heart and trouble sleeping", "Improved digestion", "Lower blood pressure"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "김치가 발효식품인 이유",
    title_en: "Why kimchi is a fermented food", title_ja: "キムチが発酵食品である理由",
    body_kr: "김치는 배추나 무 같은 채소를 소금에 절인 뒤 양념과 함께 숙성시켜 만드는 발효식품이다. 채소를 소금에 절이면 수분이 빠지면서 유산균이 자라기 좋은 환경이 만들어진다고 한다. 시간이 지나면서 이 유산균이 채소 속의 당을 분해해 신맛과 특유의 감칠맛을 만들어 낸다. 발효가 진행될수록 맛이 점점 시어지기 때문에 김치는 담근 지 얼마나 됐는지에 따라 맛이 달라진다. 이런 발효 과정 덕분에 김치에는 유산균이 풍부해서 건강에 좋은 음식으로도 널리 알려져 있다.",
    body_en: "Kimchi is a fermented food made by salting vegetables like napa cabbage or radish and then aging them with seasoning. When vegetables are salted, moisture is drawn out, creating an environment where lactic acid bacteria can thrive, it is said. Over time, these bacteria break down the sugars in the vegetables, producing a sour taste and a distinctive savory flavor. As fermentation progresses, the flavor becomes increasingly sour, so kimchi tastes different depending on how long it has been fermenting. Thanks to this fermentation process, kimchi is rich in lactic acid bacteria and is also widely known as a healthy food.", body_ja: "キムチは白菜や大根のような野菜を塩に漬けたあと、薬味と一緒に熟成させて作る発酵食品である。野菜を塩に漬けると水分が抜け、乳酸菌が育ちやすい環境ができるという。時間が経つにつれてこの乳酸菌が野菜の中の糖を分解し、酸味と独特のうま味を生み出す。発酵が進むほど味がだんだん酸っぱくなるため、キムチは漬けてからどのくらい経ったかによって味が変わる。この発酵の過程のおかげでキムチには乳酸菌が豊富に含まれており、健康に良い食品としても広く知られている。",
    questions: [
      { question_en: "What happens when vegetables are salted for kimchi?", question_ja: "キムチを作る際に野菜を塩漬けするとどうなりますか。", options: ["They become sweeter immediately", "Moisture is drawn out, helping bacteria grow", "They lose all flavor", "They stop fermenting"], answerIndex: 1 },
      { question_en: "Why does kimchi's taste change over time?", question_ja: "キムチの味が時間とともに変わるのはなぜですか。", options: ["It is reheated repeatedly", "New vegetables are added daily", "Fermentation makes it progressively more sour", "Salt is removed over time"], answerIndex: 2 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "태권도의 유래",
    title_en: "The origins of taekwondo", title_ja: "テコンドーの起源",
    body_kr: "태권도는 손과 발을 사용하는 한국의 전통 무술로 오랜 역사를 지니고 있다고 알려져 있다. 고대 한반도의 여러 무예에서 그 뿌리를 찾을 수 있으며 시간이 흐르며 여러 형태로 발전해 왔다. 현대적인 태권도는 20세기 중반에 여러 무술 유파가 통합되면서 체계를 갖추게 되었다고 한다. 발차기를 중심으로 한 화려한 동작이 특징이며 힘뿐만 아니라 정신 수양도 중요하게 여겨진다. 오늘날 태권도는 올림픽 정식 종목으로 채택될 만큼 세계적으로 널리 알려진 스포츠가 되었다.",
    body_en: "Taekwondo is a traditional Korean martial art using the hands and feet, and it is said to have a long history. Its roots can be found in various ancient martial arts of the Korean peninsula, and it developed into different forms over time. Modern taekwondo is said to have taken its systematic shape in the mid-20th century when several martial art schools were unified. It is characterized by dynamic movements centered on kicks, and mental discipline is considered just as important as physical strength. Today, taekwondo has become a sport widely known around the world, having been adopted as an official Olympic event.", body_ja: "テコンドーは手と足を使う韓国の伝統武術で、長い歴史を持つと言われている。古代朝鮮半島のさまざまな武芸にそのルーツを見出すことができ、時代を経て様々な形に発展してきた。現代のテコンドーは20世紀半ばに複数の武術の流派が統合されて体系化されたという。蹴りを中心とした華麗な動作が特徴で、力だけでなく精神修養も重要視される。今日、テコンドーはオリンピックの正式種目に採用されるほど世界的に広く知られたスポーツとなった。",
    questions: [
      { question_en: "When did modern taekwondo take its systematic shape?", question_ja: "現代のテコンドーはいつ体系化されましたか。", options: ["In ancient times only", "In the mid-20th century", "In the 21st century", "During the Joseon dynasty"], answerIndex: 1 },
      { question_en: "What is taekwondo especially characterized by?", question_ja: "テコンドーは特に何によって特徴づけられますか。", options: ["Swimming techniques", "Dynamic kicking movements", "Weapon fighting", "Wrestling holds"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한글의 원리",
    title_en: "The principles of Hangeul", title_ja: "ハングルの原理",
    body_kr: "한글은 조선의 세종대왕이 백성들이 쉽게 글을 배울 수 있도록 만든 문자라고 알려져 있다. 자음은 발음할 때의 입 모양과 혀의 위치를 본떠서 만들어졌다고 한다. 모음은 하늘, 땅, 사람을 상징하는 세 가지 기본 요소를 조합해서 만들어졌다. 이러한 원리 덕분에 한글은 배우기 쉬우면서도 소리를 매우 정확하게 표현할 수 있는 문자로 평가받는다. 이런 과학적인 원리 때문에 한글은 세계 여러 언어학자들 사이에서도 독창적인 문자 체계로 자주 언급된다.",
    body_en: "Hangeul is said to have been created by King Sejong of the Joseon dynasty so that ordinary people could easily learn to read and write. The consonants are said to have been designed based on the shape of the mouth and tongue position when pronouncing each sound. The vowels were created by combining three basic elements symbolizing sky, earth, and person. Thanks to these principles, Hangeul is regarded as a writing system that is easy to learn yet capable of representing sounds very precisely. Because of this scientific design, Hangeul is often mentioned among linguists around the world as a highly original writing system.", body_ja: "ハングルは朝鮮の世宗大王が民が文字を簡単に学べるようにと作った文字だと言われている。子音は発音するときの口の形と舌の位置をかたどって作られたという。母音は天、地、人を象徴する三つの基本要素を組み合わせて作られた。こうした原理のおかげで、ハングルは学びやすいうえに音を非常に正確に表現できる文字として評価されている。この科学的な原理のため、ハングルは世界中の言語学者の間でも独創的な文字体系としてよく取り上げられる。",
    questions: [
      { question_en: "What were Hangeul's consonants designed based on?", question_ja: "ハングルの子音は何をもとに作られましたか。", options: ["Animal shapes", "The mouth and tongue shape during pronunciation", "Numbers", "Chinese characters"], answerIndex: 1 },
      { question_en: "What three elements do Hangeul vowels symbolize?", question_ja: "ハングルの母音が象徴する三つの要素は何ですか。", options: ["Fire, water, wind", "Sky, earth, and person", "Sun, moon, star", "Mountain, river, sea"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "설날 풍습",
    title_en: "Seollal customs", title_ja: "ソルラルの風習",
    body_kr: "설날은 음력 새해 첫날을 기념하는 한국의 대표적인 명절이다. 이날 아침에는 가족들이 모여 조상에게 차례를 지내고 떡국을 함께 먹는다고 한다. 떡국을 먹으면 나이를 한 살 더 먹는다는 말이 있을 정도로 떡국은 설날에 빠질 수 없는 음식이다. 차례가 끝나면 아이들은 어른들께 세배를 하고 그 대가로 세뱃돈을 받는 풍습이 있다. 이 외에도 윷놀이 같은 전통 놀이를 즐기며 온 가족이 함께 시간을 보내는 것이 설날의 중요한 전통이다.",
    body_en: "Seollal is one of Korea's major holidays, celebrating the first day of the lunar new year. On this morning, families are said to gather to hold an ancestral rite and eat tteokguk (rice cake soup) together. There is even a saying that eating tteokguk makes you a year older, showing how essential the dish is to Seollal. After the ancestral rite, there is a custom in which children bow deeply to their elders and receive New Year's money in return. Beyond that, enjoying traditional games like yutnori together as a whole family is an important Seollal tradition.", body_ja: "ソルラルは陰暦の元日を祝う韓国の代表的な名節である。この日の朝、家族が集まって祖先に茶礼を行い、トックを一緒に食べるという。トックを食べると年を一つ取るという言葉があるほど、トックはソルラルに欠かせない食べ物である。茶礼が終わると子どもたちは目上の人にセベ(お辞儀)をし、その代わりにお年玉をもらう風習がある。このほかにもユンノリのような伝統遊びを楽しみながら家族全員で時間を過ごすことがソルラルの大切な伝統である。",
    questions: [
      { question_en: "What food is essential to Seollal morning?", question_ja: "ソルラルの朝に欠かせない食べ物は何ですか。", options: ["Songpyeon", "Tteokguk (rice cake soup)", "Bibimbap", "Samgyetang"], answerIndex: 1 },
      { question_en: "What do children receive after bowing to elders?", question_ja: "子どもたちは目上の人にお辞儀をした後、何を受け取りますか。", options: ["A new toy", "New Year's money", "New clothes", "Candy"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "추석 풍습",
    title_en: "Chuseok customs", title_ja: "チュソクの風習",
    body_kr: "추석은 음력 팔월 보름에 지내는 한국의 대표적인 가을 명절로 한 해의 수확에 감사하는 날이라고 한다. 이날 가족들은 함께 모여 조상에게 차례를 지내고 성묘를 다녀오는 경우가 많다. 대표적인 음식으로는 송편이 있는데, 반달 모양으로 빚은 떡 속에 깨나 콩 같은 소를 넣어 만든다. 추석 전날 저녁에는 가족이 모여 함께 송편을 빚으며 이야기를 나누는 것이 오랜 전통이다. 명절 연휴 동안에는 많은 사람들이 고향을 방문하기 때문에 도로와 기차역이 크게 붐빈다.",
    body_en: "Chuseok is one of Korea's major autumn holidays, held on the fifteenth day of the eighth lunar month, and it is said to be a day of giving thanks for the year's harvest. On this day, families often gather to hold an ancestral rite and visit family graves. A representative food is songpyeon, a half-moon-shaped rice cake filled with sesame seeds or beans. On the evening before Chuseok, it is a long tradition for families to gather and make songpyeon together while talking. Since many people travel to their hometowns during the holiday, roads and train stations become extremely crowded.", body_ja: "チュソクは陰暦8月15日に行われる韓国の代表的な秋の名節で、一年の収穫に感謝する日だという。この日、家族が一緒に集まって祖先に茶礼を行い、お墓参りをすることが多い。代表的な食べ物にソンピョンがあり、半月の形に作った餅の中にごまや豆などの餡を入れて作る。チュソクの前日の夕方には家族が集まって一緒にソンピョンを作りながら話をするのが古くからの伝統である。連休の間は多くの人が故郷を訪れるため、道路や駅が大変混雑する。",
    questions: [
      { question_en: "What does Chuseok celebrate?", question_ja: "チュソクは何を祝う日ですか。", options: ["The start of winter", "Thanks for the year's harvest", "A royal birthday", "The founding of Korea"], answerIndex: 1 },
      { question_en: "What is songpyeon?", question_ja: "ソンピョンとは何ですか。", options: ["A soup", "A half-moon-shaped rice cake with filling", "A grilled meat dish", "A type of tea"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "폐백이란 무엇인가",
    title_en: "What is pyebaek?", title_ja: "ペベクとは何か",
    body_kr: "폐백은 한국의 전통 결혼식에서 신랑과 신부가 양가 어른들께 처음으로 인사를 드리는 의식이다. 신부는 보통 한복을 곱게 차려입고 대추와 밤이 담긴 접시 앞에서 큰절을 올린다고 한다. 어른들은 절을 받은 후 신랑과 신부에게 덕담을 건네고 대추와 밤을 던져 주는 풍습이 있다. 이때 신부가 치마로 대추와 밤을 많이 받을수록 자식을 많이 낳는다는 이야기가 전해진다. 요즘은 결혼식 형태가 다양해지면서 폐백을 간소하게 하거나 생략하는 부부도 늘고 있다고 한다.",
    body_en: "Pyebaek is a ceremony in traditional Korean weddings in which the bride and groom formally greet their parents from both families for the first time. The bride typically wears an elegant hanbok and performs a deep bow in front of a plate of jujubes and chestnuts. After receiving the bow, the elders are said to offer words of blessing to the couple and toss jujubes and chestnuts toward the bride. There is a saying that the more jujubes and chestnuts the bride catches in her skirt, the more children she will have. These days, as wedding formats have diversified, more couples are simplifying or skipping pyebaek altogether.", body_ja: "ペベクは韓国の伝統的な結婚式で、新郎新婦が両家の目上の人に初めて挨拶をする儀式である。新婦は普通、韓服を美しく着こなし、なつめと栗が盛られた皿の前で深いお辞儀をするという。目上の人はお辞儀を受けた後、新郎新婦に祝いの言葉をかけ、なつめと栗を投げて渡す風習がある。このとき新婦がチマでなつめと栗をたくさん受け止めるほど、子どもをたくさん産むという言い伝えがある。最近では結婚式の形が多様化し、ペベクを簡単に行ったり省略したりする夫婦も増えているという。",
    questions: [
      { question_en: "What does the bride do during pyebaek?", question_ja: "ペベクのとき新婦は何をしますか。", options: ["Sing a song", "Perform a deep bow in front of jujubes and chestnuts", "Give a speech", "Dance with the groom"], answerIndex: 1 },
      { question_en: "What does the traditional saying claim about catching jujubes and chestnuts?", question_ja: "なつめと栗をたくさん受け止めることについて、伝統的な言い伝えは何と言っていますか。", options: ["It brings good luck for travel", "It means having many children", "It predicts wealth", "It ensures a long marriage"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국식 나이 계산법",
    title_en: "The Korean age counting system", title_ja: "韓国式の年齢の数え方",
    body_kr: "예전에 한국에서는 태어나자마자 한 살로 계산하고 새해가 되면 모두 한 살씩 나이를 더하는 독특한 나이 계산법을 사용했다. 이 방식으로는 12월에 태어난 아기도 다음 해 1월이 되면 두 살이 된다고 한다. 이런 계산법 때문에 외국인들은 한국 사람의 실제 나이를 헷갈려 하는 경우가 많았다. 이러한 혼란을 줄이기 위해 2023년부터 법적으로는 태어난 날을 기준으로 나이를 세는 만 나이 방식이 공식적으로 자리 잡았다. 다만 일상 대화에서는 여전히 예전 방식으로 나이를 말하는 사람들도 남아 있다고 한다.",
    body_en: "In the past, Korea used a unique age-counting method in which a person was considered one year old at birth, and everyone added a year on New Year's Day. Under this method, even a baby born in December would turn two years old the following January. Because of this counting method, foreigners often found it confusing to figure out a Korean person's real age. To reduce this confusion, since 2023 the 'man nai' system, which counts age based on one's actual birth date, has officially become the legal standard. Still, some people are said to continue using the old method when speaking casually.", body_ja: "以前、韓国では生まれた瞬間を1歳とし、新年になると全員が一斉に1歳年を取るという独特な年齢の数え方が使われていた。この方式では12月に生まれた赤ちゃんも翌年1月になると2歳になるという。こうした数え方のため、外国人は韓国人の本当の年齢を混乱することが多かった。この混乱を減らすため、2023年から実際の誕生日を基準に年齢を数える「満年齢」方式が法律上正式に定着した。ただし、日常会話では今も昔の方式で年齢を言う人が残っているという。",
    questions: [
      { question_en: "Under the old system, when did a person's age increase?", question_ja: "昔の数え方では、いつ年齢が一つ増えましたか。", options: ["On their birthday", "On New Year's Day", "Every month", "Never"], answerIndex: 1 },
      { question_en: "What changed officially since 2023?", question_ja: "2023年から公式に何が変わりましたか。", options: ["Age is no longer tracked", "Age is legally counted from actual birth date", "Everyone must be the same age", "The New Year's counting became mandatory"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국의 명함 문화",
    title_en: "Business card culture in Korea", title_ja: "韓国の名刺文化",
    body_kr: "한국의 비즈니스 자리에서는 처음 만난 사람과 명함을 주고받는 것이 일반적인 인사 방식이다. 명함은 보통 두 손으로 건네야 하며 받을 때도 두 손으로 정중하게 받는 것이 예의라고 한다. 명함을 받은 후에는 곧바로 주머니에 넣지 않고 잠시 살펴보는 모습을 보이는 것이 예의로 여겨진다. 회의 중에는 상대방의 명함을 테이블 위에 올려 두고 참고하는 경우도 흔하다. 이러한 명함 예절은 상대방에 대한 존중을 표현하는 방법으로 여겨지기 때문에 비즈니스 관계에서 중요하게 다뤄진다.",
    body_en: "In Korean business settings, exchanging business cards with someone you're meeting for the first time is a common greeting custom. A business card should usually be handed over with both hands, and it is considered polite to receive it with both hands as well. After receiving a card, it is considered polite to look at it for a moment rather than putting it away immediately. During meetings, it is also common to leave the other person's card on the table for reference. Because this card etiquette is seen as a way of showing respect, it is treated as important in business relationships.", body_ja: "韓国のビジネスの場では、初めて会う人と名刺を交換するのが一般的な挨拶の方法である。名刺は普通両手で渡さなければならず、受け取るときも両手で丁重に受け取るのがマナーだという。名刺を受け取った後はすぐにポケットにしまわず、しばらく眺める姿を見せるのが礼儀とされている。会議中は相手の名刺をテーブルの上に置いて参考にすることもよくある。こうした名刺のマナーは相手への敬意を表す方法とみなされるため、ビジネス関係において重要に扱われる。",
    questions: [
      { question_en: "How should a business card typically be exchanged?", question_ja: "名刺は一般的にどのように交換すべきですか。", options: ["Thrown across the table", "With both hands", "Only verbally introduced", "Mailed later"], answerIndex: 1 },
      { question_en: "What is considered polite after receiving a card?", question_ja: "名刺を受け取った後、礼儀とされていることは何ですか。", options: ["Immediately putting it away", "Looking at it for a moment first", "Signing it", "Returning it right away"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "PC방이란 무엇인가",
    title_en: "What is a PC bang?", title_ja: "PC房とは何か",
    body_kr: "PC방은 시간당 요금을 내고 성능 좋은 컴퓨터로 게임이나 인터넷을 이용할 수 있는 한국의 대중적인 공간이다. 집에 있는 컴퓨터보다 사양이 뛰어난 경우가 많아서 온라인 게임을 즐기는 사람들이 자주 찾는다고 한다. 대부분의 PC방에서는 라면이나 음료 같은 간단한 음식도 함께 판매하고 있어서 오래 머물기에 편리하다. 친구들과 함께 방문해서 같은 게임을 나란히 즐기는 모습도 흔하게 볼 수 있다. 이러한 특징 덕분에 PC방은 젊은 세대에게 여가와 사교를 동시에 즐길 수 있는 공간으로 자리 잡았다.",
    body_en: "A PC bang is a popular Korean space where people pay an hourly fee to use high-performance computers for gaming or browsing the internet. Since the computers often have better specs than those at home, it is said that people who enjoy online games visit frequently. Most PC bangs also sell simple food and drinks like ramen or beverages, making it convenient to stay for a long time. It's also common to see friends visiting together and playing the same game side by side. Thanks to these features, PC bangs have become a place where the younger generation can enjoy leisure and socializing at the same time.", body_ja: "PC房は時間単位の料金を払って高性能のコンピューターでゲームやインターネットを利用できる韓国の大衆的な空間である。家のコンピューターより性能が優れていることが多いため、オンラインゲームを楽しむ人がよく訪れるという。ほとんどのPC房ではラーメンや飲み物のような簡単な食べ物も一緒に販売しており、長く滞在するのに便利である。友達と一緒に訪れて同じゲームを並んで楽しむ姿もよく見られる。こうした特徴のおかげで、PC房は若い世代にとって余暇と交流を同時に楽しめる空間として定着した。",
    questions: [
      { question_en: "Why do many people prefer PC bang computers over home computers?", question_ja: "多くの人が家のコンピューターよりPC房のコンピューターを好むのはなぜですか。", options: ["They are cheaper to own", "They often have better specs", "They are quieter", "They require no payment"], answerIndex: 1 },
      { question_en: "What else can be purchased at most PC bangs?", question_ja: "ほとんどのPC房で他に購入できるものは何ですか。", options: ["Clothing", "Simple food and drinks", "Furniture", "Movie tickets"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "노래방 문화",
    title_en: "Noraebang culture", title_ja: "カラオケ文化",
    body_kr: "노래방은 작은 방을 빌려서 마이크와 화면을 이용해 노래를 부르며 즐기는 한국의 대표적인 여가 공간이다. 친구들이나 회사 동료들이 모임 후 이차 장소로 노래방을 찾는 경우가 아주 흔하다고 한다. 방마다 노래 목록이 담긴 리모컨이 있어서 원하는 곡의 번호를 눌러 손쉽게 예약할 수 있다. 점수 기능이 있는 기계도 많아서 노래가 끝나면 점수를 두고 서로 웃으며 경쟁하기도 한다. 이렇게 편하게 스트레스를 풀 수 있는 공간이기 때문에 노래방은 세대와 상관없이 널리 사랑받고 있다.",
    body_en: "Noraebang is a popular Korean leisure space where people rent a small room and sing songs using a microphone and screen. It is said that friends or coworkers very commonly head to a noraebang as a second stop after a gathering. Each room has a remote control with a song list, so guests can easily queue a song by entering its number. Many machines also have a scoring feature, so after a song finishes, people often laugh and compete over the score. Because it's such a comfortable place to relieve stress, noraebang is widely loved across generations.", body_ja: "ノレバン(カラオケ)は小さな部屋を借りてマイクと画面を使い、歌を歌って楽しむ韓国の代表的な余暇空間である。友達や会社の同僚が集まりの後の二次会としてノレバンを訪れることがとても多いという。部屋ごとに曲のリストが入ったリモコンがあり、聴きたい曲の番号を押すだけで簡単に予約できる。採点機能付きの機械も多く、歌が終わると点数をめぐって笑いながら競い合うこともある。こうして気軽にストレスを発散できる空間であるため、ノレバンは世代を問わず広く愛されている。",
    questions: [
      { question_en: "How do guests queue a song at a noraebang?", question_ja: "ノレバンで曲を予約するにはどうしますか。", options: ["By writing it on paper", "By entering its number on a remote", "By calling staff", "By singing it out loud first"], answerIndex: 1 },
      { question_en: "What do people sometimes compete over after singing?", question_ja: "歌った後に人々が競い合うことがあるものは何ですか。", options: ["Who orders food first", "The score shown by the machine", "Who leaves first", "The room's decoration"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "재난 문자 시스템",
    title_en: "The disaster alert text system", title_ja: "災害文字システム",
    body_kr: "한국에서는 지진이나 폭우 같은 재난이 발생하면 정부가 재난 문자를 통해 국민에게 위험을 알린다고 한다. 이 문자는 해당 지역에 있는 모든 휴대폰으로 자동으로 전송되기 때문에 특별히 신청하지 않아도 받을 수 있다. 문자에는 재난의 종류와 발생 위치, 그리고 대피 방법 같은 정보가 간단하게 담겨 있다. 최근에는 폭염이나 미세먼지 농도가 높을 때도 주의를 당부하는 문자가 발송되고 있다고 한다. 이러한 시스템은 신속하게 정보를 전달해서 피해를 줄이는 데 큰 역할을 하고 있다고 평가받는다.",
    body_en: "In Korea, when a disaster such as an earthquake or heavy rain occurs, the government is said to alert citizens to the danger through disaster text messages. These texts are automatically sent to every phone in the affected area, so people receive them without needing to sign up specially. The texts briefly contain information such as the type of disaster, its location, and evacuation instructions. Recently, alerts have also been sent to warn of extreme heat or high levels of fine dust. This system is regarded as playing a major role in reducing damage by delivering information quickly.", body_ja: "韓国では地震や豪雨のような災害が発生すると、政府が災害文字を通じて国民に危険を知らせるという。この文字は該当地域にあるすべての携帯電話に自動的に送信されるため、特別に申し込まなくても受け取ることができる。文字には災害の種類、発生場所、そして避難方法のような情報が簡潔に含まれている。最近では猛暑や微細粉じんの濃度が高いときにも注意を呼びかける文字が送信されているという。このシステムは情報を迅速に伝えることで被害を減らすのに大きな役割を果たしていると評価されている。",
    questions: [
      { question_en: "Who receives disaster alert texts?", question_ja: "災害文字は誰が受け取りますか。", options: ["Only people who sign up in advance", "Everyone with a phone in the affected area", "Only government officials", "Only foreign residents"], answerIndex: 1 },
      { question_en: "What kind of information is included in the texts?", question_ja: "文字にはどのような情報が含まれていますか。", options: ["Stock market updates", "Disaster type, location, and evacuation instructions", "Sports scores", "Restaurant recommendations"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "전세 제도란 무엇인가",
    title_en: "What is the jeonse system?", title_ja: "チョンセ制度とは何か",
    body_kr: "전세는 한국에서 흔히 볼 수 있는 독특한 주택 임대 방식으로, 매달 월세를 내는 대신 계약 초기에 큰 보증금을 한 번에 낸다. 세입자는 계약 기간 동안 별도의 월세 없이 지내다가 계약이 끝나면 낸 보증금을 그대로 돌려받는다고 한다. 집주인은 이 보증금을 은행에 넣거나 다른 곳에 투자해서 이익을 얻는 경우가 많다. 큰 목돈이 필요하기 때문에 세입자는 대출을 받아 보증금을 마련하는 경우도 적지 않다. 이러한 전세 제도는 세계적으로 드문 임대 방식이라서 한국을 처음 방문하는 외국인들이 신기하게 여기곤 한다.",
    body_en: "Jeonse is a unique rental system commonly seen in Korea, in which a tenant pays a large deposit all at once at the start of the lease instead of paying monthly rent. It is said that tenants live without paying separate monthly rent during the contract period, and when the contract ends, they get the deposit back in full. Landlords often earn profit by putting this deposit in a bank or investing it elsewhere. Because a large lump sum is required, it is not uncommon for tenants to take out a loan to prepare the deposit. Since this jeonse system is rare worldwide, foreigners visiting Korea for the first time often find it surprising.", body_ja: "チョンセは韓国でよく見られる独特な住宅賃貸方式で、毎月家賃を払う代わりに契約の初めにまとまった保証金を一度に支払う。入居者は契約期間中、別途の家賃なしで暮らし、契約が終わると支払った保証金をそのまま返してもらうという。家主はこの保証金を銀行に預けたり他に投資したりして利益を得ることが多い。大きなまとまった金額が必要なため、入居者がローンを組んで保証金を用意することも少なくない。このチョンセ制度は世界的に珍しい賃貸方式であるため、韓国を初めて訪れる外国人は不思議に感じることが多い。",
    questions: [
      { question_en: "What does a jeonse tenant pay instead of monthly rent?", question_ja: "チョンセの入居者は毎月の家賃の代わりに何を払いますか。", options: ["Nothing at all", "A large deposit at the start of the lease", "Weekly fees", "Utility bills only"], answerIndex: 1 },
      { question_en: "What happens to the deposit when the lease ends?", question_ja: "契約が終わると保証金はどうなりますか。", options: ["It is kept by the landlord permanently", "It is returned in full to the tenant", "It is donated", "It is split in half"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국의 군복무 제도",
    title_en: "Korea's military service system", title_ja: "韓国の兵役制度",
    body_kr: "한국에서는 성인 남성이라면 대부분 일정 기간 군대에서 복무해야 하는 병역 의무 제도가 있다. 복무 기간은 군의 종류에 따라 다르지만 보통 십팔 개월에서 이십일 개월 사이라고 알려져 있다. 신체검사를 통해 건강 상태에 따라 복무 형태가 결정되며 일부는 사회복무요원처럼 대체 복무를 하기도 한다. 대학생들은 학업을 마친 후나 휴학 기간 중에 입대하는 경우가 많아서 입대 시기를 스스로 조정하기도 한다. 이 제도는 남북이 분단된 특수한 상황에서 국가 안보를 위해 마련된 것이라고 설명된다.",
    body_en: "In Korea, there is a mandatory military service system requiring most adult men to serve in the military for a set period. The length of service varies by branch but is generally known to be between eighteen and twenty-one months. Physical exams determine the type of service based on health condition, and some serve in alternative roles such as social service positions. Many university students enlist after finishing their studies or during a leave of absence, so they can adjust the timing of enlistment themselves to some degree. This system is explained as having been established for national security, given the unique situation of the divided Korean peninsula.", body_ja: "韓国では成人男性のほとんどが一定期間軍隊で服務しなければならない兵役義務の制度がある。服務期間は軍の種類によって異なるが、通常18か月から21か月の間だと言われている。身体検査を通じて健康状態に応じて服務の形態が決まり、一部は社会服務要員のような代替服務をすることもある。大学生は学業を終えた後や休学期間中に入隊することが多く、自分で入隊時期を調整することもある。この制度は南北が分断された特殊な状況のもと、国家安全保障のために作られたと説明される。",
    questions: [
      { question_en: "How long is military service generally known to last?", question_ja: "兵役期間は一般的にどのくらいと言われていますか。", options: ["Six months", "Between eighteen and twenty-one months", "Five years", "One week"], answerIndex: 1 },
      { question_en: "Why is this system explained as necessary?", question_ja: "この制度が必要とされる理由として説明されているのは何ですか。", options: ["For sports competitions", "For national security given the divided peninsula", "To reduce unemployment", "For international trade"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "대학수학능력시험이란",
    title_en: "What is the CSAT (Suneung)?", title_ja: "大学修学能力試験とは",
    body_kr: "대학수학능력시험, 흔히 수능이라고 불리는 이 시험은 한국 고등학생들이 대학 입학을 위해 치르는 전국 단위 시험이다. 매년 11월에 하루 동안 국어, 수학, 영어를 비롯한 여러 과목을 순서대로 치르게 된다. 시험 당일에는 지각한 수험생을 돕기 위해 경찰차가 태워 주기도 하고 회사 출근 시간이 조정되기도 한다고 한다. 시험 시간 동안에는 항공기 이착륙까지 제한될 만큼 사회 전체가 수험생을 배려하는 분위기가 형성된다. 이러한 사회적 관심 때문에 수능은 단순한 시험을 넘어 한국 사회의 중요한 연례행사로 여겨진다.",
    body_en: "The College Scholastic Ability Test, commonly known as Suneung, is a nationwide exam Korean high school students take for university admission. Every November, it is held over a single day, with subjects including Korean, math, and English taken in sequence. On exam day, it is said that police cars sometimes give rides to students running late, and even company work start times are adjusted. During the exam periods, even aircraft takeoffs and landings are restricted, showing how the whole of society accommodates the test-takers. Because of this level of social attention, Suneung is regarded as more than just an exam — it is an important annual event in Korean society.", body_ja: "大学修学能力試験、通称スヌンと呼ばれるこの試験は、韓国の高校生が大学入学のために受ける全国規模の試験である。毎年11月に一日かけて国語、数学、英語をはじめとする複数の科目を順番に受ける。試験当日には遅刻しそうな受験生を助けるためにパトカーが乗せてあげたり、会社の出勤時間が調整されたりすることもあるという。試験時間中は飛行機の離着陸まで制限されるほど、社会全体が受験生に配慮する雰囲気が作られる。こうした社会的な関心のため、スヌンは単なる試験を超えて韓国社会の重要な年中行事とみなされている。",
    questions: [
      { question_en: "When is Suneung typically held?", question_ja: "スヌンは通常いつ行われますか。", options: ["Every November", "Every summer", "Twice a year", "In January"], answerIndex: 0 },
      { question_en: "What is restricted during the exam periods?", question_ja: "試験時間中に制限されるものは何ですか。", options: ["Bus routes", "Aircraft takeoffs and landings", "Grocery store hours", "Internet access"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국의 회식 문화",
    title_en: "Korean workplace dinner culture", title_ja: "韓国の会食文化",
    body_kr: "회식은 직장 동료들이 업무 시간 이후에 함께 식사하며 친목을 다지는 한국 특유의 직장 문화이다. 보통 팀 전체가 참여하며 고기나 술을 함께 나누는 자리로 이어지는 경우가 많다고 한다. 예전에는 회식이 늦게까지 이어지고 여러 장소를 옮겨 다니는 이차, 삼차 문화가 흔했다. 최근에는 일과 삶의 균형을 중시하는 분위기가 퍼지면서 회식 시간이 짧아지고 참석을 강요하지 않는 회사도 늘고 있다. 이런 변화 덕분에 회식은 예전보다 부담이 적은 자율적인 자리로 서서히 바뀌고 있다고 한다.",
    body_en: "Hoesik is a distinctly Korean workplace culture in which coworkers eat and bond together after work hours. Usually the whole team participates, and it is said the gathering often involves sharing meat or alcohol together. In the past, it was common for hoesik to continue late into the night, moving to a second or even third venue. Recently, as a culture valuing work-life balance has spread, more companies are shortening hoesik and no longer forcing employees to attend. Thanks to these changes, hoesik is said to be gradually shifting into a less burdensome, more voluntary gathering than before.", body_ja: "フェシクは職場の同僚が業務時間の後に一緒に食事をして親睦を深める韓国特有の職場文化である。通常はチーム全体が参加し、肉や酒を一緒に楽しむ場になることが多いという。以前は会食が遅くまで続き、二次会、三次会と場所を移す文化がよく見られた。最近ではワークライフバランスを重視する雰囲気が広まり、会食の時間を短くしたり参加を強要しない会社も増えている。こうした変化のおかげで、会食は以前より負担の少ない自律的な集まりへと徐々に変わりつつあるという。",
    questions: [
      { question_en: "What did hoesik traditionally often involve?", question_ja: "フェシクは伝統的にどのようなものを伴うことが多かったですか。", options: ["A quiet solo dinner", "Moving to a second or third venue late into the night", "Only breakfast meetings", "Online video calls"], answerIndex: 1 },
      { question_en: "How is hoesik culture changing recently?", question_ja: "最近フェシク文化はどのように変化していますか。", options: ["It is becoming mandatory for everyone", "It is becoming shorter and less forced", "It has completely disappeared", "It now lasts even longer"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "온천 문화",
    title_en: "Hot spring culture", title_ja: "温泉文化",
    body_kr: "한국에는 화산 활동이 활발하지는 않지만 지열로 데워진 물이 솟아나는 온천 지역이 여러 곳에 있다. 사람들은 온천물에 몸을 담그면 피로가 풀리고 혈액 순환에도 도움이 된다고 믿는다. 온천 지역에는 대개 숙박 시설과 함께 대형 목욕 시설이 있어서 하루를 온전히 쉬면서 보낼 수 있다. 물의 성분에 따라 유황천이나 라돈천처럼 다양한 종류의 온천이 있으며 각각 다른 효능이 있다고 알려져 있다. 이런 이유로 온천 여행은 가족이나 연인이 함께 휴식을 취하기 위해 즐겨 찾는 여행 방식 중 하나가 되었다.",
    body_en: "Although Korea doesn't have very active volcanic activity, there are several regions where geothermally heated water rises to the surface as hot springs. People believe that soaking in hot spring water relieves fatigue and helps blood circulation. Hot spring areas usually have large bathing facilities along with lodging, allowing visitors to spend a whole day resting. Depending on the mineral content, there are various types of springs, such as sulfur springs or radon springs, each said to have different benefits. For these reasons, hot spring trips have become one of the popular travel styles families or couples enjoy to relax together.", body_ja: "韓国では火山活動はあまり活発ではないが、地熱で温められた水が湧き出る温泉地帯がいくつかある。人々は温泉水に浸かると疲れが取れ、血行にも良いと信じている。温泉地帯にはたいてい宿泊施設と大型の入浴施設があり、一日をまるごと休んで過ごすことができる。水の成分によって硫黄泉やラドン泉のような様々な種類の温泉があり、それぞれ異なる効能があると言われている。こうした理由から、温泉旅行は家族や恋人と一緒に休息を取るために好まれる旅行の一つとなった。",
    questions: [
      { question_en: "What do people believe hot spring water helps with?", question_ja: "人々は温泉水が何に役立つと信じていますか。", options: ["Improving eyesight", "Relieving fatigue and helping blood circulation", "Curing colds instantly", "Growing hair"], answerIndex: 1 },
      { question_en: "What varies depending on mineral content?", question_ja: "水の成分によって変わるものは何ですか。", options: ["The price of admission", "The type of hot spring and its benefits", "The size of the pool only", "The opening hours"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한옥의 구조",
    title_en: "The structure of hanok", title_ja: "韓屋の構造",
    body_kr: "한옥은 나무와 흙, 돌 같은 자연 재료로 지어진 한국의 전통 가옥이다. 지붕은 대개 기와나 짚으로 덮여 있으며 처마가 길게 뻗어 있어서 여름에는 햇빛을 막고 겨울에는 낮게 뜬 해를 집 안으로 들인다고 한다. 마당을 가운데 두고 여러 채의 건물이 둘러싸는 형태가 흔해서 자연스럽게 바람이 통하는 구조를 갖추고 있다. 방바닥에는 온돌이 설치되어 있어서 겨울에도 따뜻하게 지낼 수 있다. 이러한 구조는 계절의 변화가 뚜렷한 한국의 기후에 맞춰 오랜 시간에 걸쳐 발전해 온 결과라고 설명된다.",
    body_en: "Hanok is a traditional Korean house built from natural materials such as wood, earth, and stone. The roof is usually covered with tiles or straw, and the eaves extend far out, so it is said they block sunlight in summer while letting in the low winter sun. It is common for several buildings to surround a central courtyard, creating a structure through which air naturally flows. Ondol is installed under the floor, allowing the house to stay warm even in winter. This structure is explained as the result of long development suited to Korea's climate, which has clearly distinct seasons.", body_ja: "韓屋は木や土、石のような自然の材料で建てられた韓国の伝統家屋である。屋根はたいてい瓦や藁で覆われており、軒が長く伸びているため、夏には日差しを遮り、冬には低く昇る太陽の光を家の中に取り入れるという。中庭を囲むように複数の建物が並ぶ形が一般的で、自然に風が通る構造になっている。床にはオンドルが設置されているため、冬でも暖かく過ごすことができる。この構造は季節の変化がはっきりした韓国の気候に合わせて長い時間をかけて発展してきた結果だと説明される。",
    questions: [
      { question_en: "What do the long eaves of a hanok do?", question_ja: "韓屋の長い軒は何をしますか。", options: ["Collect rainwater only", "Block summer sun and let in winter sun", "Keep out insects", "Support the chimney"], answerIndex: 1 },
      { question_en: "What keeps a hanok warm in winter?", question_ja: "韓屋を冬でも暖かく保つものは何ですか。", options: ["Electric heaters", "Ondol installed under the floor", "Thick curtains only", "A fireplace in every room"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "전통 시장의 특징",
    title_en: "Features of traditional markets", title_ja: "伝統市場の特徴",
    body_kr: "전통 시장은 다양한 상점들이 좁은 골목을 따라 늘어서 있는 한국의 오래된 상업 공간이다. 채소나 생선, 옷 같은 물건을 파는 상인들이 저마다 목소리를 높이며 손님을 부르는 모습을 흔히 볼 수 있다. 큰 마트와 달리 정해진 가격표가 없는 경우가 많아서 흥정을 통해 가격을 정하기도 한다고 한다. 시장 안에는 국수나 떡볶이 같은 길거리 음식을 파는 노점도 많아서 구경하며 먹는 재미도 크다. 최근에는 전통 시장이 온누리 상품권 같은 제도를 통해 다시 활기를 되찾고 있다는 이야기도 자주 들린다.",
    body_en: "Traditional markets are old commercial spaces in Korea where a variety of shops line narrow alleys. It is common to see merchants selling vegetables, fish, or clothes calling out loudly to attract customers. Unlike large supermarkets, there are often no fixed price tags, and it is said that prices are sometimes decided through bargaining. Inside the market there are also many street food stalls selling things like noodles or tteokbokki, making browsing and eating part of the fun. Recently, it is also often heard that traditional markets are regaining vitality through systems like Onnuri gift certificates.", body_ja: "伝統市場は様々な店が狭い路地に並んでいる韓国の古くからの商業空間である。野菜や魚、服のような品物を売る商人たちが、それぞれ大きな声でお客を呼ぶ姿がよく見られる。大型スーパーと違って決まった値札がない場合が多く、値段交渉によって価格が決まることもあるという。市場の中にはうどんやトッポッキのような屋台料理を売る露店も多く、見て回りながら食べる楽しみも大きい。最近では伝統市場がオンヌリ商品券のような制度を通じて再び活気を取り戻しているという話もよく聞かれる。",
    questions: [
      { question_en: "How are prices sometimes determined at traditional markets?", question_ja: "伝統市場では価格がどのように決まることがありますか。", options: ["Fixed by the government", "Through bargaining", "Set by an app", "Always the same as supermarkets"], answerIndex: 1 },
      { question_en: "What has recently helped traditional markets regain vitality?", question_ja: "最近、伝統市場が活気を取り戻すのに役立っているものは何ですか。", options: ["Closing early", "Systems like Onnuri gift certificates", "Banning street food", "Removing all stalls"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "태극기의 의미",
    title_en: "The meaning of the Taegukgi", title_ja: "太極旗の意味",
    body_kr: "태극기는 한국의 국기로 흰색 바탕에 태극 문양과 네 개의 괘가 그려져 있다. 흰색 바탕은 밝음과 평화를 사랑하는 민족성을 상징한다고 알려져 있다. 가운데의 태극 문양은 파란색과 빨간색이 서로 어우러져 있으며 이는 우주의 조화와 균형을 나타낸다고 한다. 네 모서리에 있는 건, 곤, 감, 리라는 네 개의 괘는 각각 하늘과 땅, 물과 불을 의미한다고 설명된다. 이러한 상징들은 동양 철학의 음양 사상에 바탕을 두고 있어서 태극기는 단순한 깃발을 넘어 깊은 철학적 의미를 담고 있다.",
    body_en: "The Taegukgi is Korea's national flag, featuring the taeguk symbol and four trigrams on a white background. The white background is said to symbolize a national character that loves brightness and peace. The taeguk symbol in the center blends blue and red together, and this is said to represent the harmony and balance of the universe. The four trigrams at the corners, called geon, gon, gam, and ri, are explained as representing sky and earth, water and fire, respectively. Because these symbols are rooted in the East Asian philosophy of yin and yang, the Taegukgi carries deep philosophical meaning beyond being a simple flag.", body_ja: "太極旗は韓国の国旗で、白い地に太極文様と四つの卦が描かれている。白い地は明るさと平和を愛する民族性を象徴すると言われている。中央の太極文様は青と赤が互いに調和しており、これは宇宙の調和と均衡を表すという。四つの角にある乾、坤、坎、離という四つの卦は、それぞれ天と地、水と火を意味すると説明される。これらの象徴は東洋哲学の陰陽思想に基づいているため、太極旗は単なる旗を超えて深い哲学的意味を持っている。",
    questions: [
      { question_en: "What does the white background of the Taegukgi symbolize?", question_ja: "太極旗の白い地は何を象徴していますか。", options: ["Wealth and power", "Brightness and peace", "War and conflict", "Speed and technology"], answerIndex: 1 },
      { question_en: "What philosophy are the flag's symbols rooted in?", question_ja: "旗の象徴は何の思想に基づいていますか。", options: ["Buddhism only", "Yin and yang philosophy", "Western astrology", "Confucian ritual only"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국어 존댓말 체계",
    title_en: "The Korean honorific system", title_ja: "韓国語の敬語体系",
    body_kr: "한국어에는 상대방과의 관계나 나이에 따라 말투를 다르게 사용하는 존댓말 체계가 발달해 있다. 처음 만난 사람이나 나이가 많은 사람에게는 문장 끝에 '-습니다'나 '-요' 같은 표현을 붙여 정중하게 말한다고 한다. 반대로 친구나 나이가 어린 사람에게는 이런 표현 없이 반말을 사용하는 경우가 많다. 동사나 명사 자체가 높임의 뜻을 가진 단어로 바뀌기도 해서 '밥'이 '진지'로, '먹다'가 '드시다'로 바뀌는 예도 있다. 이러한 존댓말 체계는 한국 사회의 서열 문화와 예의를 중시하는 태도를 잘 보여 준다고 설명된다.",
    body_en: "Korean has a developed honorific system in which speech style changes depending on one's relationship with the listener or their age. It is said that with someone met for the first time or someone older, people speak politely by attaching expressions like '-seumnida' or '-yo' to the end of sentences. Conversely, with friends or younger people, informal speech is often used without such expressions. Even verbs or nouns themselves can change into honorific words, such as 'bap' (meal) becoming 'jinji,' or 'meokda' (to eat) becoming 'deusida.' This honorific system is explained as clearly reflecting Korean society's hierarchical culture and its emphasis on courtesy.", body_ja: "韓国語には相手との関係や年齢に応じて話し方を変える敬語体系が発達している。初めて会う人や年上の人には文末に「-습니다」や「-요」のような表現をつけて丁寧に話すという。反対に友達や年下の人には、こうした表現を使わずにパンマル(タメ口)を使うことが多い。動詞や名詞自体が敬意を表す言葉に変わることもあり、「밥(ご飯)」が「진지」に、「먹다(食べる)」が「드시다」に変わる例もある。こうした敬語体系は、韓国社会の序列文化と礼儀を重んじる態度をよく表していると説明される。",
    questions: [
      { question_en: "What is added to sentences for polite speech?", question_ja: "丁寧な話し方のために文に何が加えられますか。", options: ["Numbers", "Expressions like '-seumnida' or '-yo'", "Extra vowels", "Loud tone only"], answerIndex: 1 },
      { question_en: "What does the honorific system reflect about Korean society?", question_ja: "敬語体系は韓国社会について何を反映していますか。", options: ["A lack of structure", "Hierarchical culture and emphasis on courtesy", "Disregard for age", "A preference for informality"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "빨리빨리 문화",
    title_en: "Ppalli-ppalli (hurry-hurry) culture", title_ja: "パルリパルリ文化",
    body_kr: "빨리빨리 문화는 무엇이든 신속하게 처리하는 것을 중요하게 여기는 한국 사회의 특징을 가리키는 말이다. 음식점에서 주문한 음식이 몇 분 안에 나오고 택배가 하루 만에 도착하는 것도 이러한 문화의 영향이라고 한다. 이런 속도 중심의 문화는 짧은 시간에 빠른 경제 성장을 이루는 데 큰 역할을 했다고 평가받는다. 하지만 지나치게 서두르다 보면 실수가 생기거나 안전이 소홀해지는 부작용도 있다고 지적된다. 최근에는 속도와 함께 신중함의 가치도 균형 있게 강조해야 한다는 목소리가 커지고 있다.",
    body_en: "Ppalli-ppalli culture refers to a feature of Korean society that places great importance on handling everything quickly. It is said that food arriving within minutes at restaurants and parcels being delivered within a day are also influenced by this culture. This speed-focused culture is credited with playing a major role in achieving rapid economic growth in a short period. However, it is also pointed out that excessive haste can lead to mistakes or neglect of safety as a side effect. Recently, more voices have called for balancing speed with the value of carefulness.", body_ja: "パルリパルリ文化とは、何事も素早く処理することを大切にする韓国社会の特徴を指す言葉である。飲食店で注文した料理が数分で出てきたり、宅配便が一日で届いたりするのもこの文化の影響だという。このような速度重視の文化は、短期間で急速な経済成長を成し遂げるうえで大きな役割を果たしたと評価されている。しかし、あまりに急ぎすぎるとミスが起きたり安全がおろそかになったりする副作用もあると指摘されている。最近では速さとともに慎重さの価値もバランスよく重視すべきだという声が大きくなっている。",
    questions: [
      { question_en: "What is ppalli-ppalli culture credited with?", question_ja: "パルリパルリ文化は何に貢献したと評価されていますか。", options: ["Slowing down the economy", "Playing a role in rapid economic growth", "Increasing unemployment", "Reducing delivery speed"], answerIndex: 1 },
      { question_en: "What side effect is pointed out about this culture?", question_ja: "この文化について指摘されている副作用は何ですか。", options: ["Too much relaxation", "Mistakes and neglect of safety from excessive haste", "Lower productivity", "Less delivery demand"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "택배 시스템",
    title_en: "The parcel delivery system", title_ja: "宅配システム",
    body_kr: "한국의 택배 시스템은 물건을 주문한 다음 날이면 도착할 정도로 매우 빠르고 효율적으로 운영된다고 알려져 있다. 대부분의 아파트에는 택배함이나 경비실이 있어서 사람이 집에 없어도 물건을 안전하게 맡길 수 있다. 최근에는 문 앞에 물건을 두고 사진을 찍어 보내 주는 방식이 일반화되면서 직접 대면하지 않고도 배송이 완료된다. 물류 센터에서는 자동화된 분류 시스템을 활용해 방대한 양의 물건을 빠르게 처리한다고 한다. 이러한 빠르고 편리한 시스템 덕분에 한국인들은 온라인 쇼핑을 일상적으로 이용하게 되었다.",
    body_en: "Korea's parcel delivery system is known to operate so quickly and efficiently that items ordered one day often arrive the next. Most apartment buildings have parcel lockers or a security office, so packages can be safely left even when no one is home. Recently, it has become common for delivery workers to leave the package at the door and send a photo, completing delivery without any face-to-face contact. Distribution centers are said to use automated sorting systems to quickly process huge volumes of packages. Thanks to this fast and convenient system, Koreans have come to use online shopping as part of their daily lives.", body_ja: "韓国の宅配システムは、注文した翌日には届くほど非常に速く効率的に運営されていると言われている。ほとんどのマンションには宅配ボックスや警備室があるため、家に人がいなくても荷物を安全に預けることができる。最近ではドアの前に荷物を置き、写真を撮って送る方式が一般化し、直接顔を合わせなくても配達が完了する。物流センターでは自動化された仕分けシステムを活用して膨大な量の荷物を素早く処理するという。こうした速くて便利なシステムのおかげで、韓国人はオンラインショッピングを日常的に利用するようになった。",
    questions: [
      { question_en: "How fast do many parcels arrive after ordering?", question_ja: "多くの荷物は注文からどのくらいで届きますか。", options: ["Within an hour", "The next day", "Within a month", "Same year"], answerIndex: 1 },
      { question_en: "What common delivery method avoids face-to-face contact?", question_ja: "対面せずに配達を完了する一般的な方法は何ですか。", options: ["Calling before delivery", "Leaving the package and sending a photo", "Requiring a signature in person", "Delivering only to offices"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "김장이란 무엇인가",
    title_en: "What is gimjang?", title_ja: "キムジャンとは何か",
    body_kr: "김장은 겨울이 오기 전에 가족이나 이웃이 모여 한 해 동안 먹을 김치를 대량으로 담그는 한국의 전통 풍습이다. 예전에는 냉장 기술이 없었기 때문에 겨울에 채소를 구하기 어려운 시기를 대비해 미리 김치를 만들어 두었다고 한다. 배추를 소금에 절이고 여러 사람이 함께 양념을 버무리는 작업은 시간이 오래 걸려서 협동이 필요하다. 이런 이유로 김장은 단순히 음식을 만드는 일을 넘어 공동체가 서로 돕고 나누는 문화로 자리 잡았다. 오늘날에도 많은 가정에서 늦가을이 되면 김장을 하며 가족의 전통을 이어 가고 있다.",
    body_en: "Gimjang is a traditional Korean custom in which family or neighbors gather before winter to make a large batch of kimchi to last through the year. It is said that in the past, without refrigeration technology, people prepared kimchi in advance for the winter months when vegetables were hard to find. Salting cabbage and mixing seasonings together with several people takes a long time and requires cooperation. For this reason, gimjang has become more than just a food-making task — it has become a culture of a community helping and sharing with one another. Even today, many families continue this tradition by making gimjang when late autumn arrives.", body_ja: "キムジャンは冬が来る前に家族や近所の人が集まり、一年間食べるキムチをまとめて漬ける韓国の伝統的な風習である。以前は冷蔵技術がなかったため、冬に野菜を手に入れにくい時期に備えてあらかじめキムチを作っておいたという。白菜を塩に漬け、大勢で薬味を混ぜる作業は時間がかかるため協力が必要である。こうした理由から、キムジャンは単に食べ物を作る作業を超えて、共同体が互いに助け合い分かち合う文化として定着した。今日でも多くの家庭が晩秋になるとキムジャンを行い、家族の伝統を受け継いでいる。",
    questions: [
      { question_en: "Why did people traditionally prepare kimchi in large batches before winter?", question_ja: "人々が冬を迎える前にまとめてキムチを準備した理由は何ですか。", options: ["To sell it at market", "Because vegetables were hard to find in winter without refrigeration", "For religious ceremonies", "To trade with neighbors"], answerIndex: 1 },
      { question_en: "What does gimjang represent beyond food preparation?", question_ja: "キムジャンは食べ物の準備を超えて何を表していますか。", options: ["A competition", "A culture of community cooperation and sharing", "A solitary activity", "A government requirement"], answerIndex: 1 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "한국의 지역 축제",
    title_en: "Korea's regional festivals", title_ja: "韓国の地域祭り",
    body_kr: "한국의 여러 지역에서는 계절이나 특산물을 주제로 한 다양한 지역 축제가 열린다. 봄에는 벚꽃 축제나 딸기 축제처럼 그 계절의 풍경과 먹거리를 즐기는 행사가 많다고 한다. 여름에는 물놀이를 즐길 수 있는 머드 축제 같은 시원한 축제가 관광객들에게 인기를 끈다. 가을에는 각 지역의 특산물을 홍보하는 농산물 축제가 열려서 신선한 먹거리를 저렴하게 살 수 있다. 이러한 지역 축제는 지역 경제를 살리고 그 지역만의 매력을 널리 알리는 데 중요한 역할을 한다고 평가받는다.",
    body_en: "Various regions across Korea hold diverse local festivals themed around the season or a regional specialty. In spring, there are said to be many events, such as cherry blossom festivals or strawberry festivals, that let people enjoy the season's scenery and food. In summer, refreshing festivals like the mud festival, where visitors can play in water, attract many tourists. In autumn, agricultural product festivals are held to promote each region's specialties, letting people buy fresh food at low prices. These regional festivals are regarded as playing an important role in reviving local economies and widely promoting each region's unique charm.", body_ja: "韓国のさまざまな地域では、季節や特産物をテーマにした多様な地域祭りが開かれる。春には桜祭りやいちご祭りのように、その季節の風景や食べ物を楽しむ行事が多いという。夏には水遊びを楽しめるマッド祭りのような涼しい祭りが観光客に人気を集める。秋には各地域の特産物を宣伝する農産物祭りが開かれ、新鮮な食べ物を安く買うことができる。こうした地域祭りは地域経済を活性化させ、その地域ならではの魅力を広く知らせるうえで重要な役割を果たしていると評価されている。",
    questions: [
      { question_en: "What kind of festival is popular in summer according to the passage?", question_ja: "この文章によると、夏に人気のある祭りはどんな種類ですか。", options: ["A snow festival", "A mud festival", "A tea ceremony festival", "A book festival"], answerIndex: 1 },
      { question_en: "What role are regional festivals said to play?", question_ja: "地域祭りはどのような役割を果たすと言われていますか。", options: ["Reviving local economies and promoting regional charm", "Increasing traffic congestion only", "Reducing tourism", "Replacing national holidays"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "explainer",
    title_kr: "야식 문화",
    title_en: "Late-night snack culture", title_ja: "夜食文化",
    body_kr: "야식은 저녁 식사 이후 늦은 밤에 먹는 간식이나 식사를 가리키는 말로 한국에서 특히 발달한 문화이다. 치킨이나 라면, 떡볶이처럼 간단하면서도 자극적인 맛의 음식이 야식으로 인기가 많다고 한다. 배달 서비스가 발달하면서 늦은 시간에도 손쉽게 음식을 주문해서 먹을 수 있게 됐다. 시험공부를 하거나 야근을 하는 사람들에게 야식은 지친 하루를 견디는 작은 위로가 되기도 한다. 다만 늦은 시간에 자주 먹으면 체중이나 소화에 부담을 줄 수 있어서 적당히 즐기는 것이 좋다고 전문가들은 조언한다.",
    body_en: "Yasik refers to snacks or meals eaten late at night after dinner, and it is a culture especially developed in Korea. Simple yet intensely flavored foods like fried chicken, ramen, or tteokbokki are said to be popular choices for yasik. As delivery services developed, it became easy to order and eat food even late at night. For people studying for exams or working overtime, yasik can be a small comfort that helps them get through an exhausting day. However, experts advise enjoying it in moderation, since eating late frequently can put a strain on weight and digestion.", body_ja: "夜食とは夕食後の遅い時間に食べるおやつや食事を指す言葉で、韓国で特に発達した文化である。チキンやラーメン、トッポッキのような簡単で刺激的な味の食べ物が夜食として人気だという。配達サービスが発達したことで、遅い時間でも簡単に食べ物を注文して食べられるようになった。試験勉強をしたり残業をしたりする人にとって、夜食は疲れた一日を乗り切る小さな慰めにもなる。ただし、遅い時間に頻繁に食べると体重や消化に負担をかける可能性があるため、適度に楽しむのがよいと専門家は助言する。",
    questions: [
      { question_en: "What foods are commonly popular as yasik?", question_ja: "夜食としてよく人気があるのはどんな食べ物ですか。", options: ["Salads and fruit", "Fried chicken, ramen, and tteokbokki", "Soup only", "Bread and cereal"], answerIndex: 1 },
      { question_en: "What do experts advise about eating yasik often?", question_ja: "夜食を頻繁に食べることについて専門家は何を助言していますか。", options: ["Eat it every night", "Enjoy it in moderation", "Avoid delivery services", "Only eat it for breakfast instead"], answerIndex: 1 },
    ],
  },
];
