import type { RawPassage } from "./types";

export const READING_B1_REVIEW: RawPassage[] = [
  {
    level: "B1",
    genre: "review",
    title_kr: "새로 생긴 카페 후기",
    title_en: "A review of a newly opened cafe", title_ja: "新しくできたカフェのレビュー", title_zh: "新开咖啡馆的体验", title_vi: "Đánh giá quán cà phê mới mở",
    body_kr: "회사 근처에 새로 생긴 카페에 가 봤어요. 인테리어가 예쁘고 커피 맛도 진한 편이었어요. 하지만 자리가 별로 없어서 앉을 곳을 찾기가 힘들었어요. 그래도 커피 맛이 좋아서 다시 갈 만한 곳이에요.",
    body_en: "I went to a newly opened cafe near my office. The interior was pretty and the coffee had a fairly rich flavor. However, there weren't many seats, so it was hard to find a place to sit. Still, the coffee is good enough that it's worth visiting again.", body_ja: "会社の近くに新しくできたカフェに行ってみました。インテリアがきれいで、コーヒーの味も濃厚な方でした。ただ、席があまりなくて座る場所を見つけるのが大変でした。それでもコーヒーの味が良いので、また行く価値のある場所です。", body_zh: "我去了公司附近新开的咖啡馆。装修很漂亮，咖啡味道也比较浓郁。不过座位不多，很难找到位子坐。尽管如此，咖啡味道不错，值得再去。", body_vi: "Tôi đã đến một quán cà phê mới mở gần công ty. Nội thất đẹp và cà phê cũng khá đậm đà. Tuy nhiên, chỗ ngồi không nhiều nên khó tìm được chỗ. Dù vậy, cà phê ngon nên đây là nơi đáng để quay lại.",
    questions: [
      { question_en: "What was the drawback of the cafe?", question_ja: "カフェの欠点は何でしたか。", question_zh: "咖啡馆的缺点是什么？", question_vi: "Nhược điểm của quán cà phê là gì?", options: ["Not enough seats", "Bad coffee", "Rude staff", "Too expensive"], answerIndex: 0 },
      { question_en: "What is the writer's overall opinion?", question_ja: "書き手の全体的な感想はどうですか。", question_zh: "作者的整体评价是什么？", question_vi: "Nhận xét chung của người viết là gì?", options: ["Worth going back", "Never going again", "Only good for takeout", "Too far away"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "헬스장 등록 후기",
    title_en: "A review of signing up at a gym", title_ja: "ジム入会のレビュー", title_zh: "健身房办卡体验", title_vi: "Đánh giá đăng ký phòng gym",
    body_kr: "집 근처 헬스장에 3개월 등록했어요. 기구가 다양하고 트레이너도 친절한 편이었어요. 다만 주말에는 사람이 너무 많아서 기구를 기다려야 했어요. 평일에 다닌다면 추천할 만한 곳이에요.",
    body_en: "I signed up for three months at a gym near my house. The equipment is varied and the trainers were fairly kind. However, on weekends it was so crowded that I had to wait for machines. If you go on weekdays, it's a place worth recommending.", body_ja: "家の近くのジムに3か月間入会しました。器具の種類が多く、トレーナーも親切な方でした。ただ、週末は人が多すぎて器具を待たなければなりませんでした。平日に通うなら勧められる場所です。", body_zh: "我在家附近的健身房办了三个月的卡。器材种类多，教练也比较亲切。不过周末人太多，要等器材。如果平日去的话是值得推荐的地方。", body_vi: "Tôi đã đăng ký tập ba tháng ở phòng gym gần nhà. Thiết bị đa dạng và huấn luyện viên khá thân thiện. Tuy nhiên, cuối tuần đông người nên phải chờ máy tập. Nếu đi vào ngày thường thì đây là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was the problem on weekends?", question_ja: "週末の問題は何でしたか。", question_zh: "周末的问题是什么？", question_vi: "Vấn đề vào cuối tuần là gì?", options: ["Having to wait for machines", "The gym was closed", "The trainers were rude", "The equipment was broken"], answerIndex: 0 },
      { question_en: "When does the writer suggest going?", question_ja: "書き手はいつ通うことを勧めていますか。", question_zh: "作者建议什么时候去？", question_vi: "Người viết gợi ý nên đi khi nào?", options: ["On weekdays", "Only on weekends", "Late at night", "Early morning only"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "미용실 이용 후기",
    title_en: "A review of a hair salon visit", title_ja: "美容室利用のレビュー", title_zh: "美发店体验", title_vi: "Đánh giá tiệm làm tóc",
    body_kr: "동네 미용실에서 처음으로 파마를 했어요. 디자이너가 제 얼굴형에 맞게 스타일을 잘 골라 주셨어요. 그런데 가격이 다른 곳보다 조금 비싼 편이었어요. 결과가 만족스러워서 가격을 생각하면 추천할 만해요.",
    body_en: "I got a perm for the first time at a neighborhood hair salon. The designer picked a style that suited my face shape well. However, the price was a bit higher than other places. Since I'm satisfied with the result, considering the price, it's worth recommending.", body_ja: "近所の美容室で初めてパーマをかけました。デザイナーが私の顔の形に合わせてスタイルをうまく選んでくれました。ただ、料金が他の店より少し高い方でした。仕上がりに満足しているので、料金を考えれば勧められます。", body_zh: "我第一次在附近的美发店烫了头发。设计师很好地根据我的脸型选择了发型。不过价格比其他地方稍贵一些。结果让我很满意，考虑到价格也值得推荐。", body_vi: "Tôi đã uốn tóc lần đầu tiên ở tiệm làm tóc trong khu phố. Nhà tạo mẫu đã chọn kiểu tóc rất hợp với khuôn mặt tôi. Tuy nhiên, giá cả hơi cao hơn so với những nơi khác. Vì kết quả khiến tôi hài lòng nên xét về giá cả thì vẫn đáng giới thiệu.",
    questions: [
      { question_en: "What was the caveat about the salon?", question_ja: "美容室について気になった点は何でしたか。", question_zh: "关于美发店的注意事项是什么？", question_vi: "Điều lưu ý về tiệm làm tóc là gì?", options: ["It was a bit expensive", "The staff were late", "The style didn't suit her", "It was hard to book"], answerIndex: 0 },
      { question_en: "What did the writer like?", question_ja: "書き手は何が気に入りましたか。", question_zh: "作者喜欢什么？", question_vi: "Người viết thích điều gì?", options: ["The designer chose a style that suited her", "The waiting area", "The free coffee", "The parking lot"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "배달 앱 서비스 후기",
    title_en: "A review of a food delivery app", title_ja: "配達アプリサービスのレビュー", title_zh: "外卖应用体验", title_vi: "Đánh giá dịch vụ ứng dụng giao đồ ăn",
    body_kr: "요즘 자주 쓰는 배달 앱이 있어요. 주문하기가 간단하고 배달도 빠른 편이에요. 그렇지만 배달비가 조금씩 오르고 있어서 부담스러워요. 그래도 편리함 때문에 계속 쓸 만한 앱이에요.",
    body_en: "There's a delivery app I use often these days. Ordering is simple and delivery is fairly fast. However, delivery fees keep rising a little, which feels burdensome. Still, because of the convenience, it's an app worth continuing to use.", body_ja: "最近よく使う配達アプリがあります。注文が簡単で配達も速い方です。ただ、配達料が少しずつ上がっていて負担に感じます。それでも便利さのおかげで使い続けたいアプリです。", body_zh: "我最近经常用一个外卖应用。下单很简单，配送也比较快。不过配送费一点点在上涨，让人有负担。尽管如此，因为方便，还是值得继续使用的应用。", body_vi: "Gần đây tôi hay dùng một ứng dụng giao đồ ăn. Đặt hàng đơn giản và giao hàng cũng khá nhanh. Tuy nhiên, phí giao hàng cứ tăng dần khiến tôi thấy hơi nặng nề. Dù vậy, vì tiện lợi nên đây là ứng dụng đáng để tiếp tục sử dụng.",
    questions: [
      { question_en: "What is the writer's complaint?", question_ja: "書き手の不満は何ですか。", question_zh: "作者的不满是什么？", question_vi: "Điều người viết phàn nàn là gì?", options: ["Delivery fees keep rising", "The app crashes often", "Delivery is too slow", "The menu is limited"], answerIndex: 0 },
      { question_en: "Does the writer recommend continuing to use it?", question_ja: "書き手はこのアプリを使い続けることを勧めていますか。", question_zh: "作者建议继续使用吗？", question_vi: "Người viết có khuyên tiếp tục sử dụng không?", options: ["Yes, because it's convenient", "No, they will stop using it", "Only for certain restaurants", "Only on weekends"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "요즘 본 영화 후기",
    title_en: "A review of a movie I recently watched", title_ja: "最近見た映画のレビュー", title_zh: "最近看的电影感想", title_vi: "Đánh giá bộ phim gần đây đã xem",
    body_kr: "주말에 친구와 함께 새로 나온 영화를 봤어요. 이야기 전개가 흥미롭고 배우들의 연기도 훌륭한 편이었어요. 다만 상영 시간이 너무 길어서 중간에 조금 지루했어요. 그래도 볼 만한 영화라서 추천하고 싶어요.",
    body_en: "I watched a newly released movie with a friend over the weekend. The story development was interesting and the actors' performances were pretty excellent. However, the running time was so long that it got a bit boring in the middle. Still, it's a movie worth watching, so I'd like to recommend it.", body_ja: "週末に友達と一緒に新しく公開された映画を見ました。話の展開が面白く、俳優たちの演技もかなり良かったです。ただ、上映時間が長すぎて途中で少し退屈でした。それでも見る価値のある映画なので勧めたいです。", body_zh: "周末我和朋友一起看了一部新上映的电影。剧情发展有趣，演员们的演技也相当出色。不过片长太长，中间有点无聊。尽管如此，还是一部值得看的电影，我想推荐。", body_vi: "Cuối tuần tôi đã xem một bộ phim mới ra mắt cùng bạn. Diễn biến câu chuyện thú vị và diễn xuất của các diễn viên cũng khá xuất sắc. Tuy nhiên, thời lượng phim quá dài nên có đoạn giữa hơi buồn chán. Dù vậy, đây vẫn là bộ phim đáng xem nên tôi muốn giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the movie?", question_ja: "映画の欠点は何でしたか。", question_zh: "电影的缺点是什么？", question_vi: "Nhược điểm của bộ phim là gì?", options: ["It was too long", "The acting was bad", "The story was confusing", "The sound was bad"], answerIndex: 0 },
      { question_en: "Does the writer recommend the movie?", question_ja: "書き手はこの映画を勧めていますか。", question_zh: "作者推荐这部电影吗？", question_vi: "Người viết có giới thiệu bộ phim này không?", options: ["Yes", "No", "Only for children", "Only in theaters"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "최근 읽은 책 후기",
    title_en: "A review of a book I recently read", title_ja: "最近読んだ本のレビュー", title_zh: "最近读的书感想", title_vi: "Đánh giá cuốn sách gần đây đã đọc",
    body_kr: "친구가 추천해 준 소설을 한 권 읽었어요. 문장이 쉽게 읽히고 이야기도 감동적인 편이었어요. 하지만 결말이 조금 급하게 끝나는 느낌이 들었어요. 전체적으로는 읽을 만한 책이라서 추천하고 싶어요.",
    body_en: "I read a novel that a friend recommended to me. The sentences were easy to read and the story was fairly moving. However, the ending felt like it wrapped up a bit too quickly. Overall, it's a book worth reading, so I'd like to recommend it.", body_ja: "友達が勧めてくれた小説を一冊読みました。文章が読みやすく、話も感動的な方でした。ただ、結末が少し急に終わる感じがしました。全体的には読む価値のある本なので勧めたいです。", body_zh: "我读了一本朋友推荐的小说。文字很容易读，故事也比较感人。不过结局感觉有点仓促。总体来说是一本值得读的书，我想推荐。", body_vi: "Tôi đã đọc một cuốn tiểu thuyết được bạn giới thiệu. Câu văn dễ đọc và câu chuyện cũng khá cảm động. Tuy nhiên, tôi cảm thấy đoạn kết có phần hơi vội vàng. Nhìn chung đây là cuốn sách đáng đọc nên tôi muốn giới thiệu.",
    questions: [
      { question_en: "What was the writer's complaint about the book?", question_ja: "書き手が本について不満だった点は何ですか。", question_zh: "作者对这本书不满的地方是什么？", question_vi: "Điều người viết không hài lòng về cuốn sách là gì?", options: ["The ending felt rushed", "The writing was too difficult", "The story was boring", "It was too short"], answerIndex: 0 },
      { question_en: "What is the overall verdict?", question_ja: "全体的な評価はどうですか。", question_zh: "总体评价是什么？", question_vi: "Đánh giá chung là gì?", options: ["Worth reading", "Not worth reading", "Only for children", "Too expensive"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "제주도 호텔 숙박 후기",
    title_en: "A review of staying at a hotel in Jeju", title_ja: "済州島ホテル宿泊のレビュー", title_zh: "济州岛酒店住宿体验", title_vi: "Đánh giá lưu trú khách sạn ở Jeju",
    body_kr: "제주도 여행 때 바다가 보이는 호텔에 묵었어요. 전망이 정말 아름답고 방도 깨끗한 편이었어요. 다만 조식 메뉴가 단조로워서 조금 아쉬웠어요. 전망을 중요하게 생각한다면 추천할 만한 곳이에요.",
    body_en: "During my trip to Jeju, I stayed at a hotel with an ocean view. The view was truly beautiful and the room was fairly clean. However, the breakfast menu was monotonous, which was a bit disappointing. If you value the view, it's a place worth recommending.", body_ja: "済州島旅行のとき、海が見えるホテルに泊まりました。眺めが本当に美しく、部屋も清潔な方でした。ただ、朝食のメニューが単調で少し残念でした。眺めを重視するなら勧められる場所です。", body_zh: "济州岛旅行时我住在能看到大海的酒店。景色真的很美，房间也比较干净。不过早餐菜单比较单调，有点可惜。如果重视景色的话是值得推荐的地方。", body_vi: "Trong chuyến du lịch Jeju, tôi đã ở một khách sạn có view biển. Tầm nhìn thực sự đẹp và phòng cũng khá sạch sẽ. Tuy nhiên, thực đơn bữa sáng hơi đơn điệu nên tôi thấy tiếc. Nếu coi trọng tầm nhìn thì đây là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was disappointing about the hotel?", question_ja: "ホテルについて残念だった点は何ですか。", question_zh: "关于酒店让人失望的地方是什么？", question_vi: "Điều gì khiến người viết thất vọng về khách sạn?", options: ["The breakfast menu was monotonous", "The room was dirty", "The staff were rude", "It was too noisy"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["The ocean view", "The gym", "The price", "The parking"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "경주 여행지 후기",
    title_en: "A review of a tourist spot in Gyeongju", title_ja: "慶州旅行のレビュー", title_zh: "庆州旅游感想", title_vi: "Đánh giá điểm du lịch Gyeongju",
    body_kr: "역사 유적지로 유명한 경주에 다녀왔어요. 유적들이 잘 보존되어 있고 설명판도 자세한 편이었어요. 그런데 여름이라 그런지 그늘이 부족해서 너무 더웠어요. 봄이나 가을에 간다면 강력히 추천할 만한 곳이에요.",
    body_en: "I visited Gyeongju, famous for its historical sites. The relics are well preserved and the information boards were fairly detailed. However, maybe because it was summer, there wasn't enough shade, so it was very hot. If you go in spring or fall, it's a place I'd strongly recommend.", body_ja: "歴史遺跡で有名な慶州に行ってきました。遺跡がよく保存されていて、説明板も詳しい方でした。ただ、夏だったからか日陰が足りなくてとても暑かったです。春や秋に行くなら強くお勧めできる場所です。", body_zh: "我去了以历史遗迹闻名的庆州。遗迹保存得很好，说明牌也比较详细。不过可能因为是夏天，阴凉处不足，非常热。如果春天或秋天去的话是强烈推荐的地方。", body_vi: "Tôi đã đến thăm Gyeongju, nổi tiếng với các di tích lịch sử. Các di tích được bảo tồn tốt và bảng thuyết minh cũng khá chi tiết. Tuy nhiên, có lẽ vì là mùa hè nên thiếu bóng râm khiến trời rất nóng. Nếu đi vào mùa xuân hoặc mùa thu thì đây là nơi tôi mạnh mẽ giới thiệu.",
    questions: [
      { question_en: "What was the problem with visiting in summer?", question_ja: "夏に訪れることの問題点は何でしたか。", question_zh: "夏天去的问题是什么？", question_vi: "Vấn đề khi đến thăm vào mùa hè là gì?", options: ["Not enough shade and too hot", "The site was closed", "It was too crowded", "There was no parking"], answerIndex: 0 },
      { question_en: "When does the writer suggest visiting?", question_ja: "書き手はいつ訪れることを勧めていますか。", question_zh: "作者建议什么时候去？", question_vi: "Người viết gợi ý nên đến thăm khi nào?", options: ["Spring or fall", "Only winter", "Only summer", "Any season is fine"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "온라인 코딩 강의 후기",
    title_en: "A review of an online coding course", title_ja: "オンラインコーディング講座のレビュー", title_zh: "在线编程课体验", title_vi: "Đánh giá khóa học lập trình trực tuyến",
    body_kr: "요즘 인기 있는 온라인 코딩 강의를 들었어요. 설명이 차근차근 되어 있어서 초보자도 따라가기 쉬운 편이었어요. 하지만 질문에 대한 답변이 오는 데 시간이 꽤 걸렸어요. 그래도 내용이 알차서 추천할 만한 강의예요.",
    body_en: "I took a popular online coding course these days. The explanations were step by step, so it was fairly easy for beginners to follow. However, it took quite a while to get answers to questions. Still, the content is substantial, so it's a course worth recommending.", body_ja: "最近人気のオンラインコーディング講座を受けました。説明が段階的にされていて初心者でもついていきやすい方でした。ただ、質問への回答が来るまでかなり時間がかかりました。それでも内容が充実しているので勧められる講座です。", body_zh: "我上了一门最近很受欢迎的在线编程课。讲解循序渐进，初学者也比较容易跟上。不过对问题的回复要花不少时间。尽管如此，内容很充实，是值得推荐的课程。", body_vi: "Tôi đã học một khóa học lập trình trực tuyến đang được ưa chuộng gần đây. Phần giải thích được trình bày từng bước nên người mới bắt đầu cũng khá dễ theo kịp. Tuy nhiên, việc nhận được câu trả lời cho câu hỏi mất khá nhiều thời gian. Dù vậy, nội dung phong phú nên đây là khóa học đáng giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the course?", question_ja: "この講座の欠点は何でしたか。", question_zh: "这门课的缺点是什么？", question_vi: "Nhược điểm của khóa học là gì?", options: ["Slow responses to questions", "Too advanced for beginners", "No video lessons", "Too expensive"], answerIndex: 0 },
      { question_en: "What did the writer like about the course?", question_ja: "書き手はこの講座の何を気に入りましたか。", question_zh: "作者喜欢这门课的哪一点？", question_vi: "Người viết thích điều gì ở khóa học?", options: ["Step-by-step explanations", "The free trial", "The certificate", "The live chat"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "요가 수업 후기",
    title_en: "A review of a yoga class", title_ja: "ヨガクラスのレビュー", title_zh: "瑜伽课体验", title_vi: "Đánh giá lớp học yoga",
    body_kr: "회사 근처 요가원에서 저녁 수업을 듣기 시작했어요. 강사님이 자세를 하나하나 꼼꼼히 봐 주는 편이라서 좋았어요. 다만 수업 인원이 많아서 조금 붐비는 느낌이 들었어요. 그래도 스트레스가 많이 풀려서 추천하고 싶어요.",
    body_en: "I started taking evening yoga classes near my office. It was good because the instructor carefully checks each pose. However, the class had a lot of people, so it felt a bit crowded. Still, my stress has eased a lot, so I'd like to recommend it.", body_ja: "会社の近くのヨガスタジオで夜のクラスを受け始めました。講師が一つ一つの姿勢を丁寧に見てくれる方で良かったです。ただ、受講人数が多くて少し混雑している感じがしました。それでもストレスがかなり解消されたので勧めたいです。", body_zh: "我开始在公司附近的瑜伽馆上晚间课程。老师会仔细地一个个纠正姿势，这点很好。不过上课人数多，感觉有点拥挤。尽管如此，压力得到了很大缓解，我想推荐。", body_vi: "Tôi bắt đầu học lớp yoga buổi tối gần công ty. Tôi thấy hài lòng vì giáo viên kiểm tra từng tư thế một cách tỉ mỉ. Tuy nhiên, lớp học đông người nên tôi cảm thấy hơi chật chội. Dù vậy, căng thẳng đã giảm đi nhiều nên tôi muốn giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the class?", question_ja: "このクラスの欠点は何でしたか。", question_zh: "这堂课的缺点是什么？", question_vi: "Nhược điểm của lớp học là gì?", options: ["It felt crowded", "The instructor was late", "It was too expensive", "It was too far away"], answerIndex: 0 },
      { question_en: "How does the writer feel now?", question_ja: "書き手は今どう感じていますか。", question_zh: "作者现在感觉如何？", question_vi: "Hiện tại người viết cảm thấy thế nào?", options: ["Much less stressed", "More stressed", "Bored", "Injured"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "휴대폰 케이스 구매 후기",
    title_en: "A review of buying a phone case", title_ja: "携帯ケース購入のレビュー", title_zh: "手机壳购买体验", title_vi: "Đánh giá mua ốp lưng điện thoại",
    body_kr: "인터넷에서 인기 있는 휴대폰 케이스를 하나 샀어요. 디자인이 예쁘고 그립감도 좋은 편이었어요. 하지만 몇 주 쓰니까 모서리 부분이 조금씩 벗겨지기 시작했어요. 디자인은 마음에 들지만 내구성 때문에 재구매는 고민이 돼요.",
    body_en: "I bought a popular phone case online. The design was pretty and the grip was fairly good. However, after a few weeks of use, the corners started to peel little by little. I like the design, but because of the durability, I'm hesitant about buying it again.", body_ja: "ネットで人気の携帯ケースを一つ買いました。デザインがきれいで握りやすさも良い方でした。ただ、数週間使うと角の部分が少しずつはがれ始めました。デザインは気に入っていますが、耐久性のせいで再購入は悩みます。", body_zh: "我在网上买了一个很受欢迎的手机壳。设计好看，手感也比较好。不过用了几周后，边角处开始一点点脱皮。虽然设计我很喜欢，但因为耐用性的问题，是否再购买让我犹豫。", body_vi: "Tôi đã mua một chiếc ốp lưng điện thoại đang được ưa chuộng trên mạng. Thiết kế đẹp và cảm giác cầm nắm cũng khá tốt. Tuy nhiên, sau vài tuần sử dụng, phần góc bắt đầu bong tróc dần. Tôi thích thiết kế nhưng vì độ bền nên còn phân vân về việc mua lại.",
    questions: [
      { question_en: "What problem appeared after a few weeks?", question_ja: "数週間後にどんな問題が現れましたか。", question_zh: "几周后出现了什么问题？", question_vi: "Vấn đề gì xuất hiện sau vài tuần?", options: ["The corners started peeling", "The color faded", "It cracked immediately", "It didn't fit the phone"], answerIndex: 0 },
      { question_en: "Does the writer plan to buy it again?", question_ja: "書き手はまた購入するつもりですか。", question_zh: "作者打算再买吗？", question_vi: "Người viết có định mua lại không?", options: ["They are hesitant", "Yes, definitely", "They already bought three more", "They gave it away"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "무선 이어폰 사용 후기",
    title_en: "A review of using wireless earbuds", title_ja: "ワイヤレスイヤホン使用のレビュー", title_zh: "无线耳机使用体验", title_vi: "Đánh giá sử dụng tai nghe không dây",
    body_kr: "새로 나온 무선 이어폰을 구입해서 한 달째 쓰고 있어요. 음질이 선명하고 착용감도 편안한 편이에요. 그런데 배터리가 생각보다 빨리 닳는 게 아쉬워요. 음질만 본다면 추천할 만한 제품이에요.",
    body_en: "I bought newly released wireless earbuds and have been using them for a month. The sound quality is clear and they're fairly comfortable to wear. However, it's disappointing that the battery drains faster than expected. If you're focused on sound quality, it's a product worth recommending.", body_ja: "新しく出たワイヤレスイヤホンを購入して1か月使っています。音質が澄んでいて、着け心地も快適な方です。ただ、バッテリーが思ったより早く減るのが残念です。音質だけを見れば勧められる製品です。", body_zh: "我买了新出的无线耳机，用了一个月了。音质清晰，佩戴感也比较舒适。不过电池比想象中耗得快，有点可惜。如果只看音质的话是值得推荐的产品。", body_vi: "Tôi đã mua tai nghe không dây mới ra mắt và dùng được một tháng. Âm thanh rõ ràng và đeo cũng khá thoải mái. Tuy nhiên, tôi thấy tiếc vì pin hết nhanh hơn tôi nghĩ. Nếu chỉ xét về chất lượng âm thanh thì đây là sản phẩm đáng giới thiệu.",
    questions: [
      { question_en: "What is the drawback of the earbuds?", question_ja: "このイヤホンの欠点は何ですか。", question_zh: "这款耳机的缺点是什么？", question_vi: "Nhược điểm của tai nghe này là gì?", options: ["The battery drains quickly", "The sound is unclear", "They fall out easily", "They are too heavy"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["The sound quality", "The price", "The box design", "The warranty"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "공기청정기 사용 후기",
    title_en: "A review of using an air purifier", title_ja: "空気清浄機使用のレビュー", title_zh: "空气净化器使用体验", title_vi: "Đánh giá sử dụng máy lọc không khí",
    body_kr: "미세먼지가 심해서 공기청정기를 하나 샀어요. 필터 교체가 간단하고 소음도 조용한 편이에요. 다만 필터 가격이 생각보다 비싸서 유지비가 부담돼요. 성능은 만족스러워서 전체적으로 추천할 만해요.",
    body_en: "Since fine dust got bad, I bought an air purifier. Filter replacement is simple and the noise is fairly quiet. However, the filter price is more expensive than expected, so the maintenance cost is a burden. The performance is satisfying, so overall it's worth recommending.", body_ja: "微細粉じんがひどくて空気清浄機を一つ買いました。フィルター交換が簡単で、音も静かな方です。ただ、フィルターの価格が思ったより高くて維持費が負担になります。性能には満足しているので全体的に勧められます。", body_zh: "因为细颗粒物严重，我买了一台空气净化器。滤芯更换简单，噪音也比较小。不过滤芯价格比想象中贵，维护费用有负担。性能让人满意，总体来说值得推荐。", body_vi: "Vì bụi mịn nghiêm trọng nên tôi đã mua một máy lọc không khí. Thay bộ lọc đơn giản và tiếng ồn cũng khá nhỏ. Tuy nhiên, giá bộ lọc đắt hơn tôi nghĩ nên chi phí duy trì là gánh nặng. Hiệu suất khiến tôi hài lòng nên nhìn chung đáng giới thiệu.",
    questions: [
      { question_en: "What is the writer's concern?", question_ja: "書き手の懸念は何ですか。", question_zh: "作者的顾虑是什么？", question_vi: "Mối lo ngại của người viết là gì?", options: ["The filter is expensive", "It is too loud", "It doesn't clean the air well", "It is too big"], answerIndex: 0 },
      { question_en: "What is the overall verdict?", question_ja: "全体的な評価はどうですか。", question_zh: "总体评价是什么？", question_vi: "Đánh giá chung là gì?", options: ["Worth recommending", "Not worth buying", "Only for large rooms", "Too complicated to use"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "동네 세탁소 후기",
    title_en: "A review of a neighborhood dry cleaner", title_ja: "近所のクリーニング店のレビュー", title_zh: "社区洗衣店体验", title_vi: "Đánh giá tiệm giặt là trong khu phố",
    body_kr: "집 앞에 있는 세탁소를 몇 달째 이용하고 있어요. 옷을 맡기면 깨끗하게 세탁해 주는 편이고 사장님도 친절해요. 그런데 가끔 완성되는 날짜가 예상보다 늦어질 때가 있어요. 그래도 품질이 좋아서 계속 이용할 만한 곳이에요.",
    body_en: "I've been using the dry cleaner in front of my house for a few months. When I drop off clothes, they clean them fairly well and the owner is kind. However, sometimes the pickup date is later than expected. Still, the quality is good, so it's a place worth continuing to use.", body_ja: "家の前にあるクリーニング店を数か月利用しています。服を預けるときれいに洗ってくれる方で、店主も親切です。ただ、時々仕上がりの日にちが予想より遅れることがあります。それでも品質が良いので利用し続ける価値のある店です。", body_zh: "我在家门口的洗衣店用了好几个月。送洗衣物洗得比较干净，老板也很亲切。不过有时候完工日期会比预计的晚。尽管如此，因为质量好，是值得继续光顾的地方。", body_vi: "Tôi đã dùng dịch vụ tiệm giặt là trước nhà mấy tháng nay. Khi gửi quần áo, họ giặt khá sạch sẽ và chủ tiệm cũng thân thiện. Tuy nhiên, đôi khi ngày lấy đồ trễ hơn dự kiến. Dù vậy, vì chất lượng tốt nên đây là nơi đáng tiếp tục sử dụng.",
    questions: [
      { question_en: "What is the occasional problem?", question_ja: "時々起こる問題は何ですか。", question_zh: "偶尔发生的问题是什么？", question_vi: "Vấn đề thỉnh thoảng xảy ra là gì?", options: ["Pickup is sometimes delayed", "Clothes come back dirty", "The prices are too high", "The shop is often closed"], answerIndex: 0 },
      { question_en: "What does the writer say about the owner?", question_ja: "書き手は店主について何と言っていますか。", question_zh: "作者对老板的评价是什么？", question_vi: "Người viết nói gì về chủ tiệm?", options: ["Kind", "Rude", "Always busy", "Hard to reach"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "동네 빵집 후기",
    title_en: "A review of a neighborhood bakery", title_ja: "近所のパン屋のレビュー", title_zh: "社区面包店体验", title_vi: "Đánh giá tiệm bánh trong khu phố",
    body_kr: "새로 생긴 빵집에 가서 빵을 몇 개 사 봤어요. 빵이 정말 부드럽고 종류도 다양한 편이었어요. 하지만 인기가 많아서 오후에는 원하는 빵이 다 팔리고 없었어요. 오전에 일찍 간다면 추천할 만한 빵집이에요.",
    body_en: "I went to a newly opened bakery and bought a few breads. The bread was really soft and the variety was fairly wide. However, it's so popular that by the afternoon, the bread I wanted was already sold out. If you go early in the morning, it's a bakery worth recommending.", body_ja: "新しくできたパン屋に行ってパンをいくつか買ってみました。パンが本当に柔らかく、種類も豊富な方でした。ただ、人気があるため午後には欲しいパンが売り切れていました。午前中早めに行くなら勧められるパン屋です。", body_zh: "我去了新开的面包店买了几个面包。面包真的很松软，种类也比较丰富。不过因为很受欢迎，下午想要的面包常常卖完了。如果早上早点去的话是值得推荐的面包店。", body_vi: "Tôi đã đến tiệm bánh mới mở và mua vài loại bánh. Bánh thực sự mềm và chủng loại cũng khá đa dạng. Tuy nhiên, vì đông khách nên đến chiều là loại bánh tôi muốn đã bán hết. Nếu đi sớm vào buổi sáng thì đây là tiệm bánh đáng giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the bakery?", question_ja: "このパン屋の欠点は何でしたか。", question_zh: "这家面包店的缺点是什么？", question_vi: "Nhược điểm của tiệm bánh là gì?", options: ["Bread sells out by the afternoon", "The bread is too hard", "The staff are unfriendly", "It is too expensive"], answerIndex: 0 },
      { question_en: "When does the writer suggest visiting?", question_ja: "書き手はいつ訪れることを勧めていますか。", question_zh: "作者建议什么时候去？", question_vi: "Người viết gợi ý nên đến khi nào?", options: ["Early in the morning", "Late at night", "Only on weekends", "Right before closing"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "분식집 후기",
    title_en: "A review of a Korean snack restaurant", title_ja: "粉食店のレビュー", title_zh: "小吃店体验", title_vi: "Đánh giá quán ăn vặt (bunsik)",
    body_kr: "학교 근처 분식집에서 떡볶이와 김밥을 먹었어요. 떡볶이 소스가 맛있고 양도 푸짐한 편이었어요. 그런데 가게가 좁아서 사람이 많을 때는 앉을 자리가 없었어요. 맛은 확실히 좋아서 포장해서 먹는 것도 추천해요.",
    body_en: "I ate tteokbokki and kimbap at a snack restaurant near the school. The tteokbokki sauce was tasty and the portions were fairly generous. However, the shop was small, so when it was busy there was nowhere to sit. The taste is definitely good, so I'd also recommend getting it to go.", body_ja: "学校の近くの粉食店でトッポッキとキンパを食べました。トッポッキのソースがおいしく、量も多めな方でした。ただ、店が狭いので人が多いときは座る席がありませんでした。味は確かに良いので、持ち帰りで食べるのもお勧めです。", body_zh: "我在学校附近的小吃店吃了炒年糕和紫菜包饭。炒年糕酱汁好吃，分量也比较足。不过店面很小，人多的时候没有座位。味道确实很好，我也推荐打包带走吃。", body_vi: "Tôi đã ăn tteokbokki và kimbap ở một quán ăn vặt gần trường. Nước sốt tteokbokki ngon và khẩu phần cũng khá đầy đặn. Tuy nhiên, quán nhỏ nên khi đông khách không có chỗ ngồi. Vì hương vị chắc chắn ngon nên tôi cũng khuyên nên mua mang về.",
    questions: [
      { question_en: "What was the problem with the restaurant?", question_ja: "このレストランの問題点は何でしたか。", question_zh: "这家店的问题是什么？", question_vi: "Vấn đề của quán ăn này là gì?", options: ["Not enough seating", "Bad taste", "Slow service", "High prices"], answerIndex: 0 },
      { question_en: "What alternative does the writer suggest?", question_ja: "書き手が提案する代わりの方法は何ですか。", question_zh: "作者提出了什么替代方案？", question_vi: "Người viết đề xuất giải pháp thay thế nào?", options: ["Getting food to go", "Going somewhere else", "Calling ahead", "Avoiding weekends"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "디저트 카페 후기",
    title_en: "A review of a dessert cafe", title_ja: "デザートカフェのレビュー", title_zh: "甜品咖啡馆体验", title_vi: "Đánh giá quán cà phê tráng miệng",
    body_kr: "인스타그램에서 유명한 디저트 카페에 가 봤어요. 케이크 모양이 예쁘고 맛도 달콤한 편이었어요. 하지만 가격이 다른 카페보다 꽤 비싼 편이라서 부담스러웠어요. 특별한 날에 한 번쯤 가 볼 만한 곳이에요.",
    body_en: "I went to a dessert cafe that's famous on Instagram. The cakes looked pretty and were fairly sweet. However, the prices were quite a bit higher than other cafes, which felt burdensome. It's a place worth visiting once for a special occasion.", body_ja: "インスタグラムで有名なデザートカフェに行ってみました。ケーキの形がかわいく、味も甘い方でした。ただ、価格が他のカフェよりかなり高めで負担に感じました。特別な日に一度は行ってみる価値のある場所です。", body_zh: "我去了Instagram上很有名的甜品咖啡馆。蛋糕造型漂亮，味道也比较甜。不过价格比其他咖啡馆贵不少，有点负担。是值得在特别的日子去一次的地方。", body_vi: "Tôi đã đến một quán cà phê tráng miệng nổi tiếng trên Instagram. Bánh có hình dáng đẹp và vị cũng khá ngọt. Tuy nhiên, giá cả khá cao hơn so với các quán khác nên tôi cảm thấy hơi nặng nề. Đây là nơi đáng thử một lần vào ngày đặc biệt.",
    questions: [
      { question_en: "What is the drawback of the cafe?", question_ja: "このカフェの欠点は何ですか。", question_zh: "这家咖啡馆的缺点是什么？", question_vi: "Nhược điểm của quán cà phê là gì?", options: ["The prices are high", "The cakes taste bad", "The location is far", "The service is slow"], answerIndex: 0 },
      { question_en: "When does the writer suggest going?", question_ja: "書き手はいつ行くことを勧めていますか。", question_zh: "作者建议什么时候去？", question_vi: "Người viết gợi ý nên đi khi nào?", options: ["For a special occasion", "Every day", "Only in winter", "Never"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "헤어드라이어 구매 후기",
    title_en: "A review of buying a hair dryer", title_ja: "ヘアドライヤー購入のレビュー", title_zh: "吹风机购买体验", title_vi: "Đánh giá mua máy sấy tóc",
    body_kr: "새로 나온 고속 헤어드라이어를 구입했어요. 머리가 빨리 마르고 손잡이도 가벼운 편이에요. 그런데 사용할 때 소음이 생각보다 큰 편이라서 조금 신경 쓰여요. 빠르게 말리는 게 중요하다면 추천할 만한 제품이에요.",
    body_en: "I bought a newly released fast hair dryer. My hair dries quickly and the handle is fairly light. However, the noise while using it is louder than expected, so it's a bit bothersome. If drying quickly matters to you, it's a product worth recommending.", body_ja: "新しく出た高速ヘアドライヤーを購入しました。髪が早く乾き、持ち手も軽い方です。ただ、使うときの音が思ったより大きくて少し気になります。速く乾かすことが重要なら勧められる製品です。", body_zh: "我买了新出的高速吹风机。头发干得快，把手也比较轻。不过使用时噪音比想象中大，有点在意。如果重视快速吹干的话是值得推荐的产品。", body_vi: "Tôi đã mua một máy sấy tóc tốc độ cao mới ra mắt. Tóc khô nhanh và tay cầm cũng khá nhẹ. Tuy nhiên, tiếng ồn khi sử dụng lớn hơn tôi nghĩ nên hơi khó chịu. Nếu việc sấy khô nhanh là quan trọng thì đây là sản phẩm đáng giới thiệu.",
    questions: [
      { question_en: "What is the drawback of the hair dryer?", question_ja: "このヘアドライヤーの欠点は何ですか。", question_zh: "这款吹风机的缺点是什么？", question_vi: "Nhược điểm của máy sấy tóc là gì?", options: ["It is loud", "It is too heavy", "It dries hair slowly", "It overheats"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["Fast drying", "The price", "The color options", "The warranty"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "요가 매트 구매 후기",
    title_en: "A review of buying a yoga mat", title_ja: "ヨガマット購入のレビュー", title_zh: "瑜伽垫购买体验", title_vi: "Đánh giá mua thảm tập yoga",
    body_kr: "온라인으로 두꺼운 요가 매트를 하나 주문했어요. 쿠션감이 좋고 미끄럼 방지도 잘되는 편이에요. 다만 부피가 커서 보관하기가 조금 불편해요. 편안함을 중요하게 생각한다면 추천할 만한 제품이에요.",
    body_en: "I ordered a thick yoga mat online. The cushioning is good and the non-slip feature works fairly well. However, it's bulky, so storing it is a bit inconvenient. If comfort matters to you, it's a product worth recommending.", body_ja: "オンラインで厚めのヨガマットを一つ注文しました。クッション性が良く、滑り止めもよく効く方です。ただ、かさばるので保管が少し不便です。快適さを重視するなら勧められる製品です。", body_zh: "我在网上订购了一张厚瑜伽垫。缓冲感好，防滑效果也比较好。不过体积大，收纳起来有点不方便。如果重视舒适度的话是值得推荐的产品。", body_vi: "Tôi đã đặt mua một tấm thảm yoga dày qua mạng. Độ êm tốt và khả năng chống trượt cũng khá tốt. Tuy nhiên, vì cồng kềnh nên việc cất giữ hơi bất tiện. Nếu coi trọng sự thoải mái thì đây là sản phẩm đáng giới thiệu.",
    questions: [
      { question_en: "What is inconvenient about the mat?", question_ja: "このマットについて不便な点は何ですか。", question_zh: "关于这款垫子的不便之处是什么？", question_vi: "Điều bất tiện về tấm thảm này là gì?", options: ["It is bulky to store", "It is too thin", "It slips easily", "It smells bad"], answerIndex: 0 },
      { question_en: "What does the writer like about it?", question_ja: "書き手はこのマットの何が気に入っていますか。", question_zh: "作者喜欢它的哪一点？", question_vi: "Người viết thích điều gì ở nó?", options: ["The cushioning", "The price", "The color", "The weight"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "언어 교환 앱 후기",
    title_en: "A review of a language exchange app", title_ja: "言語交換アプリのレビュー", title_zh: "语言交换应用体验", title_vi: "Đánh giá ứng dụng trao đổi ngôn ngữ",
    body_kr: "한국어를 배우려고 언어 교환 앱을 써 봤어요. 다양한 나라 사람들과 대화할 수 있어서 재미있는 편이에요. 하지만 대화가 안 맞는 상대를 만나면 시간이 아깝게 느껴지기도 해요. 꾸준히 쓴다면 실력 향상에 도움이 될 만한 앱이에요.",
    body_en: "I tried a language exchange app to learn Korean. It's fairly fun because I can talk with people from various countries. However, when I meet a partner I don't click with, it can feel like a waste of time. If used consistently, it's an app that can help improve your skills.", body_ja: "韓国語を学ぼうと言語交換アプリを使ってみました。様々な国の人と話せるので楽しい方です。ただ、話が合わない相手に出会うと時間がもったいなく感じることもあります。継続して使えば実力向上に役立つアプリです。", body_zh: "为了学韩语，我试用了一款语言交换应用。可以和各国的人聊天，比较有趣。不过遇到聊不来的对象时会觉得浪费时间。如果坚持使用的话，是有助于提高实力的应用。", body_vi: "Tôi đã thử dùng ứng dụng trao đổi ngôn ngữ để học tiếng Hàn. Có thể trò chuyện với người từ nhiều quốc gia khác nhau nên khá thú vị. Tuy nhiên, khi gặp người không hợp để trò chuyện, tôi cũng cảm thấy tốn thời gian. Nếu sử dụng đều đặn thì đây là ứng dụng có thể giúp nâng cao trình độ.",
    questions: [
      { question_en: "What is the downside of the app?", question_ja: "このアプリの欠点は何ですか。", question_zh: "这款应用的缺点是什么？", question_vi: "Nhược điểm của ứng dụng này là gì?", options: ["Mismatched conversation partners waste time", "It costs too much", "It has too few users", "It crashes often"], answerIndex: 0 },
      { question_en: "What is the overall verdict?", question_ja: "全体的な評価はどうですか。", question_zh: "总体评价是什么？", question_vi: "Đánh giá chung là gì?", options: ["Helpful if used consistently", "Not useful at all", "Only for advanced speakers", "Better than a tutor"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "치킨집 배달 후기",
    title_en: "A review of ordering from a fried chicken place", title_ja: "チキン店の配達レビュー", title_zh: "炸鸡店外送体验", title_vi: "Đánh giá giao hàng từ quán gà rán",
    body_kr: "새로 생긴 치킨집에서 배달을 시켜 봤어요. 치킨이 바삭하고 소스도 맛있는 편이었어요. 그런데 배달 시간이 예상보다 훨씬 오래 걸려서 조금 짜증이 났어요. 맛만큼은 확실해서 여유 있게 주문한다면 추천할 만해요.",
    body_en: "I ordered delivery from a newly opened fried chicken place. The chicken was crispy and the sauce was fairly tasty. However, delivery took much longer than expected, which was a bit annoying. The taste is definitely good, so if you order with plenty of time to spare, it's worth recommending.", body_ja: "新しくできたチキン店で配達を頼んでみました。チキンがサクサクで、ソースもおいしい方でした。ただ、配達時間が予想よりずっと長くかかって少しいらいらしました。味だけは確かなので、余裕を持って注文するなら勧められます。", body_zh: "我在新开的炸鸡店点了外送。炸鸡酥脆，酱汁也比较好吃。不过配送时间比预计的长很多，有点烦躁。味道确实很好，如果留出充裕的时间点餐是值得推荐的。", body_vi: "Tôi đã đặt giao hàng từ một quán gà rán mới mở. Gà giòn và nước sốt cũng khá ngon. Tuy nhiên, thời gian giao hàng lâu hơn nhiều so với dự kiến nên tôi hơi bực mình. Vì hương vị chắc chắn ngon nên nếu đặt hàng khi có thời gian rảnh rỗi thì đáng giới thiệu.",
    questions: [
      { question_en: "What was the problem with the order?", question_ja: "注文の問題点は何でしたか。", question_zh: "这次订单的问题是什么？", question_vi: "Vấn đề của đơn hàng này là gì?", options: ["Delivery took too long", "The chicken was cold", "The order was wrong", "The chicken was too spicy"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["The taste", "The packaging", "The price", "The driver"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "게스트하우스 숙박 후기",
    title_en: "A review of staying at a guesthouse", title_ja: "ゲストハウス宿泊のレビュー", title_zh: "民宿住宿体验", title_vi: "Đánh giá lưu trú tại nhà nghỉ (guesthouse)",
    body_kr: "부산 여행 때 저렴한 게스트하우스에 묵었어요. 위치가 좋고 다른 여행객들과 이야기할 수 있어서 즐거운 편이었어요. 다만 방음이 잘 안 돼서 밤에 조금 시끄러웠어요. 가격 대비 만족스러워서 추천할 만한 곳이에요.",
    body_en: "During my trip to Busan, I stayed at a cheap guesthouse. The location was good and it was fairly fun to talk with other travelers. However, the soundproofing wasn't great, so it was a bit noisy at night. It's satisfying for the price, so it's a place worth recommending.", body_ja: "釜山旅行のとき、安いゲストハウスに泊まりました。立地が良く、他の旅行者と話せて楽しい方でした。ただ、防音があまりよくなくて夜少しうるさかったです。価格の割に満足できるので勧められる場所です。", body_zh: "釜山旅行时我住在一家便宜的民宿。位置好，能和其他旅行者聊天，比较愉快。不过隔音不太好，晚上有点吵。以这个价格来说很令人满意，是值得推荐的地方。", body_vi: "Trong chuyến du lịch Busan, tôi đã ở một nhà nghỉ giá rẻ. Vị trí tốt và có thể trò chuyện với những du khách khác nên khá vui. Tuy nhiên, cách âm không tốt nên ban đêm hơi ồn. Vì hài lòng so với giá cả nên đây là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the guesthouse?", question_ja: "このゲストハウスの欠点は何でしたか。", question_zh: "这家民宿的缺点是什么？", question_vi: "Nhược điểm của nhà nghỉ này là gì?", options: ["Poor soundproofing at night", "Bad location", "Rude staff", "Dirty rooms"], answerIndex: 0 },
      { question_en: "What does the writer say about the value?", question_ja: "書き手はコストパフォーマンスについて何と言っていますか。", question_zh: "作者对性价比是怎么评价的？", question_vi: "Người viết nói gì về giá trị đồng tiền?", options: ["Satisfying for the price", "Overpriced", "Not worth it at all", "Too cheap to be good"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "놀이공원 방문 후기",
    title_en: "A review of visiting an amusement park", title_ja: "遊園地訪問のレビュー", title_zh: "游乐园游玩体验", title_vi: "Đánh giá tham quan công viên giải trí",
    body_kr: "오랜만에 가족과 놀이공원에 다녀왔어요. 놀이기구 종류가 많고 직원들도 친절한 편이었어요. 그런데 주말이라 그런지 줄이 너무 길어서 많이 기다려야 했어요. 평일에 간다면 훨씬 더 즐겁게 즐길 만한 곳이에요.",
    body_en: "I went to an amusement park with my family after a long time. There were many types of rides and the staff were fairly kind. However, maybe because it was a weekend, the lines were so long that we had to wait a lot. If you go on a weekday, it's a place you could enjoy much more.", body_ja: "久しぶりに家族と遊園地に行ってきました。アトラクションの種類が多く、スタッフも親切な方でした。ただ、週末だったからか列がとても長くてかなり待たなければなりませんでした。平日に行けばもっと楽しめる場所です。", body_zh: "我久违地和家人去了游乐园。游乐设施种类多，员工也比较亲切。不过可能因为是周末，排队太长，要等很久。如果平日去的话能玩得更开心。", body_vi: "Đã lâu rồi tôi mới cùng gia đình đến công viên giải trí. Có nhiều loại trò chơi và nhân viên cũng khá thân thiện. Tuy nhiên, có lẽ vì là cuối tuần nên hàng chờ rất dài và phải đợi nhiều. Nếu đi vào ngày thường thì có thể tận hưởng vui vẻ hơn nhiều.",
    questions: [
      { question_en: "What was the problem at the park?", question_ja: "遊園地での問題点は何でしたか。", question_zh: "在游乐园遇到的问题是什么？", question_vi: "Vấn đề gặp phải ở công viên là gì?", options: ["Long lines on the weekend", "The rides were broken", "Tickets were too expensive", "The staff were rude"], answerIndex: 0 },
      { question_en: "When does the writer suggest going?", question_ja: "書き手はいつ行くことを勧めていますか。", question_zh: "作者建议什么时候去？", question_vi: "Người viết gợi ý nên đi khi nào?", options: ["On a weekday", "Only in winter", "Right at closing time", "During a holiday"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "박물관 관람 후기",
    title_en: "A review of visiting a museum", title_ja: "博物館見学のレビュー", title_zh: "博物馆参观体验", title_vi: "Đánh giá tham quan bảo tàng",
    body_kr: "역사 박물관에 처음으로 가 봤어요. 전시물이 다양하고 설명도 이해하기 쉬운 편이었어요. 다만 오디오 가이드를 빌리려면 추가 요금을 내야 해서 조금 아쉬웠어요. 역사에 관심이 있다면 꼭 가 볼 만한 곳이에요.",
    body_en: "I visited a history museum for the first time. The exhibits were varied and the explanations were fairly easy to understand. However, it was a bit disappointing that you have to pay extra to rent an audio guide. If you're interested in history, it's definitely a place worth visiting.", body_ja: "歴史博物館に初めて行ってみました。展示物が多様で、説明も理解しやすい方でした。ただ、音声ガイドを借りるには追加料金が必要で少し残念でした。歴史に興味があればぜひ行ってみる価値のある場所です。", body_zh: "我第一次去了历史博物馆。展品丰富，说明也比较容易理解。不过想租语音导览需要额外付费，有点可惜。如果对历史感兴趣，绝对值得一去。", body_vi: "Tôi đã đến bảo tàng lịch sử lần đầu tiên. Hiện vật trưng bày đa dạng và phần giải thích cũng khá dễ hiểu. Tuy nhiên, tôi hơi tiếc vì phải trả thêm phí để thuê máy hướng dẫn âm thanh. Nếu quan tâm đến lịch sử thì đây chắc chắn là nơi đáng đến.",
    questions: [
      { question_en: "What was disappointing about the museum?", question_ja: "博物館について残念だった点は何ですか。", question_zh: "关于博物馆让人失望的地方是什么？", question_vi: "Điều gì khiến người viết thất vọng về bảo tàng?", options: ["Extra fee for the audio guide", "No English signs", "Too crowded", "Closed early"], answerIndex: 0 },
      { question_en: "Who does the writer recommend the museum to?", question_ja: "書き手は誰にこの博物館を勧めていますか。", question_zh: "作者推荐给谁？", question_vi: "Người viết giới thiệu bảo tàng cho ai?", options: ["People interested in history", "Only children", "Only tourists", "No one"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "온라인 쇼핑몰 구매 후기",
    title_en: "A review of shopping at an online store", title_ja: "オンラインショップ購入のレビュー", title_zh: "网店购物体验", title_vi: "Đánh giá mua sắm tại trang thương mại điện tử",
    body_kr: "요즘 자주 이용하는 온라인 쇼핑몰이 있어요. 배송이 빠르고 상품 사진도 실제와 비슷한 편이에요. 그런데 반품 절차가 복잡해서 한 번 불편했던 적이 있어요. 배송 속도만큼은 확실해서 계속 이용할 만한 곳이에요.",
    body_en: "There's an online store I use often these days. Delivery is fast and the product photos are fairly similar to the actual items. However, the return process is complicated, and I had an inconvenient experience once. The delivery speed is definitely reliable, so it's a place worth continuing to use.", body_ja: "最近よく利用するオンラインショップがあります。配送が速く、商品写真も実物に近い方です。ただ、返品手続きが複雑で一度不便に感じたことがあります。配送スピードだけは確かなので利用し続ける価値のある店です。", body_zh: "我最近经常用一个网店。配送快，商品照片也和实物比较相似。不过退货流程复杂，有一次让我觉得不方便。至少配送速度确实可靠，是值得继续使用的地方。", body_vi: "Gần đây tôi hay dùng một trang thương mại điện tử. Giao hàng nhanh và ảnh sản phẩm cũng khá giống thực tế. Tuy nhiên, quy trình đổi trả phức tạp nên có một lần tôi thấy bất tiện. Vì tốc độ giao hàng chắc chắn tốt nên đây là nơi đáng tiếp tục sử dụng.",
    questions: [
      { question_en: "What was the writer's inconvenience?", question_ja: "書き手が不便に感じたことは何ですか。", question_zh: "作者感到不便的是什么？", question_vi: "Điều bất tiện của người viết là gì?", options: ["The return process was complicated", "Products arrived damaged", "Prices were too high", "Customer service was rude"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["Fast delivery", "Cheap prices", "Free returns", "Wide selection"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "세차장 이용 후기",
    title_en: "A review of using a car wash", title_ja: "洗車場利用のレビュー", title_zh: "洗车场使用体验", title_vi: "Đánh giá sử dụng tiệm rửa xe",
    body_kr: "자동 세차장을 처음으로 이용해 봤어요. 세차 속도가 빠르고 가격도 저렴한 편이었어요. 다만 세차 후에도 차 안쪽까지는 깨끗해지지 않았어요. 겉면만 빠르게 닦고 싶다면 추천할 만한 곳이에요.",
    body_en: "I used an automatic car wash for the first time. The washing speed is fast and the price was fairly cheap. However, even after washing, the inside of the car wasn't cleaned. If you just want a quick exterior wash, it's a place worth recommending.", body_ja: "自動洗車場を初めて利用してみました。洗車のスピードが速く、価格も安い方でした。ただ、洗車後も車の内側まではきれいになりませんでした。外側だけ手早くきれいにしたいなら勧められる場所です。", body_zh: "我第一次使用了自动洗车场。洗车速度快，价格也比较便宜。不过洗完后车内还是没有变干净。如果只想快速清洁车外表的话是值得推荐的地方。", body_vi: "Tôi đã lần đầu tiên sử dụng tiệm rửa xe tự động. Tốc độ rửa xe nhanh và giá cũng khá rẻ. Tuy nhiên, sau khi rửa xe, bên trong xe vẫn chưa sạch. Nếu chỉ muốn lau nhanh bên ngoài thì đây là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was the limitation of the car wash?", question_ja: "この洗車場の限界は何でしたか。", question_zh: "这家洗车场的局限是什么？", question_vi: "Hạn chế của tiệm rửa xe này là gì?", options: ["The interior wasn't cleaned", "It was too slow", "It was too expensive", "It damaged the car"], answerIndex: 0 },
      { question_en: "Who would this car wash suit?", question_ja: "この洗車場はどんな人に合っていますか。", question_zh: "这家洗车场适合什么人？", question_vi: "Tiệm rửa xe này phù hợp với ai?", options: ["People who only want the exterior washed", "People who need deep cleaning", "People with motorcycles", "People with no time at all"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "공유 자전거 서비스 후기",
    title_en: "A review of a bike-sharing service", title_ja: "シェアサイクルサービスのレビュー", title_zh: "共享单车服务体验", title_vi: "Đánh giá dịch vụ xe đạp công cộng",
    body_kr: "출퇴근할 때 공유 자전거를 이용하기 시작했어요. 요금이 저렴하고 앱으로 대여하기도 간편한 편이에요. 그런데 자전거 상태가 가끔 좋지 않아서 타기 불편할 때가 있어요. 짧은 거리를 이동할 때는 추천할 만한 서비스예요.",
    body_en: "I started using a bike-sharing service for my commute. The fee is cheap and renting through the app is fairly simple. However, sometimes the bike condition isn't great, making it uncomfortable to ride. For short distances, it's a service worth recommending.", body_ja: "通勤のときシェアサイクルを利用し始めました。料金が安く、アプリでのレンタルも簡単な方です。ただ、自転車の状態が時々良くなくて乗りにくいことがあります。短い距離を移動するときは勧められるサービスです。", body_zh: "我开始在上下班时使用共享单车。费用便宜，用应用租借也比较简便。不过有时车况不太好，骑起来不舒服。短距离出行时是值得推荐的服务。", body_vi: "Tôi bắt đầu dùng xe đạp công cộng khi đi làm. Phí rẻ và thuê xe qua ứng dụng cũng khá đơn giản. Tuy nhiên, đôi khi tình trạng xe không tốt nên cưỡi hơi bất tiện. Khi di chuyển quãng đường ngắn thì đây là dịch vụ đáng giới thiệu.",
    questions: [
      { question_en: "What is the occasional problem?", question_ja: "時々起こる問題は何ですか。", question_zh: "偶尔发生的问题是什么？", question_vi: "Vấn đề thỉnh thoảng xảy ra là gì?", options: ["Bikes are sometimes in poor condition", "The app doesn't work", "The fee is too high", "Bikes are never available"], answerIndex: 0 },
      { question_en: "When does the writer recommend the service?", question_ja: "書き手はいつこのサービスを勧めていますか。", question_zh: "作者建议什么时候使用这项服务？", question_vi: "Người viết gợi ý dùng dịch vụ này khi nào?", options: ["For short distances", "For long trips", "Only at night", "Only on rainy days"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "필라테스 스튜디오 후기",
    title_en: "A review of a Pilates studio", title_ja: "ピラティススタジオのレビュー", title_zh: "普拉提工作室体验", title_vi: "Đánh giá studio Pilates",
    body_kr: "소규모 필라테스 스튜디오에 다니기 시작했어요. 개인 맞춤 지도가 가능해서 효과가 좋은 편이었어요. 다만 인원이 적어서 그런지 수업료가 꽤 비싼 편이에요. 자세 교정이 필요하다면 투자할 만한 곳이에요.",
    body_en: "I started attending a small Pilates studio. Personalized instruction is available, so it's fairly effective. However, maybe because class sizes are small, the tuition is quite expensive. If you need posture correction, it's a place worth investing in.", body_ja: "小規模なピラティススタジオに通い始めました。個人に合わせた指導が受けられて効果が良い方でした。ただ、人数が少ないからか授業料がかなり高い方です。姿勢矯正が必要なら投資する価値のある場所です。", body_zh: "我开始去一家小型普拉提工作室。可以进行个性化指导，效果比较好。不过可能因为人数少，课程费用相当贵。如果需要纠正体态，是值得投资的地方。", body_vi: "Tôi bắt đầu đến một studio Pilates quy mô nhỏ. Có thể được hướng dẫn riêng theo cá nhân nên hiệu quả khá tốt. Tuy nhiên, có lẽ vì số lượng học viên ít nên học phí khá đắt. Nếu cần chỉnh sửa tư thế thì đây là nơi đáng đầu tư.",
    questions: [
      { question_en: "What is the drawback of the studio?", question_ja: "このスタジオの欠点は何ですか。", question_zh: "这家工作室的缺点是什么？", question_vi: "Nhược điểm của studio này là gì?", options: ["The tuition is expensive", "The instructors are unqualified", "Classes are too crowded", "It is far from home"], answerIndex: 0 },
      { question_en: "Who is this studio recommended for?", question_ja: "このスタジオは誰に勧められますか。", question_zh: "这家工作室推荐给谁？", question_vi: "Studio này được giới thiệu cho ai?", options: ["People who need posture correction", "Beginners only", "People on a tight budget", "People who dislike small groups"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "이사업체 이용 후기",
    title_en: "A review of using a moving company", title_ja: "引っ越し業者利用のレビュー", title_zh: "搬家公司使用体验", title_vi: "Đánh giá sử dụng công ty chuyển nhà",
    body_kr: "이번 이사 때 처음으로 포장 이사 업체를 불렀어요. 짐을 빠르게 옮겨 주고 포장도 꼼꼼한 편이었어요. 그런데 견적보다 최종 비용이 조금 더 나와서 당황스러웠어요. 시간을 아끼고 싶다면 추천할 만한 서비스예요.",
    body_en: "For this move, I called a full-service moving company for the first time. They moved things quickly and the packing was fairly thorough. However, I was flustered because the final cost was a bit higher than the quote. If you want to save time, it's a service worth recommending.", body_ja: "今回の引っ越しで初めてパック引っ越し業者を呼びました。荷物を素早く運んでくれて、梱包も丁寧な方でした。ただ、見積もりより最終費用が少し高くなって戸惑いました。時間を節約したいなら勧められるサービスです。", body_zh: "这次搬家我第一次叫了打包搬家公司。搬东西快，打包也比较细致。不过最终费用比报价多了一点，让我有点惊讶。如果想节省时间，是值得推荐的服务。", body_vi: "Lần chuyển nhà này, lần đầu tiên tôi gọi dịch vụ chuyển nhà trọn gói. Họ chuyển đồ nhanh và đóng gói cũng khá tỉ mỉ. Tuy nhiên, tôi hơi bối rối vì chi phí cuối cùng cao hơn báo giá một chút. Nếu muốn tiết kiệm thời gian thì đây là dịch vụ đáng giới thiệu.",
    questions: [
      { question_en: "What surprised the writer?", question_ja: "書き手を戸惑わせたことは何ですか。", question_zh: "让作者感到惊讶的是什么？", question_vi: "Điều gì khiến người viết ngạc nhiên?", options: ["The final cost was higher than the quote", "The movers were late", "Items were damaged", "The movers were rude"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["Fast, thorough packing", "The low price", "The friendly manager", "The free boxes"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "가정용 프린터 구매 후기",
    title_en: "A review of buying a home printer", title_ja: "家庭用プリンター購入のレビュー", title_zh: "家用打印机购买体验", title_vi: "Đánh giá mua máy in gia đình",
    body_kr: "재택근무 때문에 가정용 프린터를 하나 샀어요. 설치가 간단하고 인쇄 속도도 빠른 편이에요. 다만 잉크값이 생각보다 비싸서 유지비가 부담스러워요. 가끔씩만 인쇄한다면 추천할 만한 제품이에요.",
    body_en: "Because of working from home, I bought a home printer. The setup is simple and the print speed is fairly fast. However, the ink is more expensive than expected, so the maintenance cost is burdensome. If you only print occasionally, it's a product worth recommending.", body_ja: "在宅勤務のため家庭用プリンターを一つ買いました。設置が簡単で、印刷速度も速い方です。ただ、インク代が思ったより高くて維持費が負担になります。たまにしか印刷しないなら勧められる製品です。", body_zh: "因为在家办公，我买了一台家用打印机。安装简单，打印速度也比较快。不过墨水价格比想象中贵，维护费用有负担。如果只是偶尔打印，是值得推荐的产品。", body_vi: "Vì làm việc tại nhà nên tôi đã mua một máy in gia đình. Lắp đặt đơn giản và tốc độ in cũng khá nhanh. Tuy nhiên, giá mực đắt hơn tôi nghĩ nên chi phí duy trì là gánh nặng. Nếu chỉ thỉnh thoảng in thì đây là sản phẩm đáng giới thiệu.",
    questions: [
      { question_en: "What is the writer's concern?", question_ja: "書き手の懸念は何ですか。", question_zh: "作者的顾虑是什么？", question_vi: "Mối lo ngại của người viết là gì?", options: ["Ink is expensive", "It prints slowly", "It is hard to set up", "It is too large"], answerIndex: 0 },
      { question_en: "Who does the writer recommend it for?", question_ja: "書き手はどんな人にこれを勧めていますか。", question_zh: "作者推荐给什么人？", question_vi: "Người viết giới thiệu sản phẩm này cho ai?", options: ["People who print only occasionally", "People who print daily for work", "Businesses", "Students only"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "노트북 가방 구매 후기",
    title_en: "A review of buying a laptop bag", title_ja: "ノートパソコンバッグ購入のレビュー", title_zh: "笔记本电脑包购买体验", title_vi: "Đánh giá mua túi đựng laptop",
    body_kr: "출근용으로 노트북 가방을 하나 새로 샀어요. 수납공간이 넉넉하고 디자인도 깔끔한 편이에요. 그런데 어깨끈이 조금 얇아서 짐이 많을 때는 어깨가 아팠어요. 짐이 적은 편이라면 충분히 추천할 만한 가방이에요.",
    body_en: "I bought a new laptop bag for commuting to work. The storage space is ample and the design is fairly clean. However, the shoulder strap is a bit thin, so my shoulder hurt when I carried a lot. If you usually carry light loads, it's a bag worth recommending.", body_ja: "通勤用にノートパソコンバッグを新しく買いました。収納スペースが十分で、デザインもすっきりしている方です。ただ、肩ひもが少し薄くて荷物が多いときは肩が痛かったです。荷物が少ない方なら十分勧められるバッグです。", body_zh: "为了上班我新买了一个笔记本电脑包。收纳空间充足，设计也比较简洁。不过肩带有点薄，东西多的时候肩膀会疼。如果平时携带东西不多，是完全值得推荐的包。", body_vi: "Tôi đã mua mới một túi đựng laptop để đi làm. Không gian chứa đồ rộng rãi và thiết kế cũng khá gọn gàng. Tuy nhiên, dây đeo vai hơi mỏng nên khi mang nhiều đồ thì vai bị đau. Nếu thường mang ít đồ thì đây là túi hoàn toàn đáng giới thiệu.",
    questions: [
      { question_en: "What was uncomfortable about the bag?", question_ja: "このバッグの何が不快でしたか。", question_zh: "这个包让人不舒服的地方是什么？", question_vi: "Điều gì khiến chiếc túi này khó chịu?", options: ["The thin shoulder strap", "The small storage", "The bad design", "The heavy material"], answerIndex: 0 },
      { question_en: "Who is the bag recommended for?", question_ja: "このバッグは誰に勧められますか。", question_zh: "这个包推荐给什么人？", question_vi: "Túi này được giới thiệu cho ai?", options: ["People who carry light loads", "People who carry very heavy items", "Students only", "People who never travel"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "커피 머신 구매 후기",
    title_en: "A review of buying a coffee machine", title_ja: "コーヒーマシン購入のレビュー", title_zh: "咖啡机购买体验", title_vi: "Đánh giá mua máy pha cà phê",
    body_kr: "집에서 커피를 자주 마셔서 캡슐 커피 머신을 샀어요. 사용법이 간단하고 커피 맛도 진한 편이에요. 다만 캡슐 가격이 계속 들어서 카페보다 저렴하다고 말하기는 어려워요. 편리함을 우선한다면 추천할 만한 제품이에요.",
    body_en: "Since I drink coffee often at home, I bought a capsule coffee machine. The usage is simple and the coffee is fairly rich. However, since I keep spending on capsules, it's hard to say it's cheaper than a cafe. If convenience is your priority, it's a product worth recommending.", body_ja: "家でコーヒーをよく飲むのでカプセルコーヒーマシンを買いました。使い方が簡単で、コーヒーの味も濃厚な方です。ただ、カプセル代がかかり続けるのでカフェより安いとは言いにくいです。便利さを優先するなら勧められる製品です。", body_zh: "因为在家经常喝咖啡，我买了一台胶囊咖啡机。使用方法简单，咖啡味道也比较浓郁。不过胶囊费用不断产生，很难说比咖啡馆便宜。如果优先考虑便利性，是值得推荐的产品。", body_vi: "Vì thường uống cà phê ở nhà nên tôi đã mua một máy pha cà phê viên nén. Cách sử dụng đơn giản và cà phê cũng khá đậm đà. Tuy nhiên, vì tiền viên nén cứ tiếp tục phát sinh nên khó nói là rẻ hơn quán cà phê. Nếu ưu tiên sự tiện lợi thì đây là sản phẩm đáng giới thiệu.",
    questions: [
      { question_en: "What is the drawback the writer mentions?", question_ja: "書き手が言及する欠点は何ですか。", question_zh: "作者提到的缺点是什么？", question_vi: "Nhược điểm mà người viết đề cập là gì?", options: ["Capsules keep costing money", "The machine is complicated", "The coffee tastes weak", "It takes too long to brew"], answerIndex: 0 },
      { question_en: "What does the writer emphasize as the strength?", question_ja: "書き手が強みとして強調しているものは何ですか。", question_zh: "作者强调的优点是什么？", question_vi: "Người viết nhấn mạnh điểm mạnh nào?", options: ["Convenience", "Low cost", "Design", "Portability"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "애완동물 미용실 후기",
    title_en: "A review of a pet grooming salon", title_ja: "ペット美容室のレビュー", title_zh: "宠物美容院体验", title_vi: "Đánh giá tiệm chăm sóc thú cưng",
    body_kr: "강아지를 데리고 새로 생긴 애완동물 미용실에 다녀왔어요. 직원들이 강아지를 다루는 솜씨가 좋고 친절한 편이었어요. 그런데 예약이 밀려서 생각보다 오래 기다려야 했어요. 미리 예약만 잘 한다면 추천할 만한 곳이에요.",
    body_en: "I took my dog to a newly opened pet grooming salon. The staff were fairly skilled and kind in handling the dog. However, appointments were backed up, so I had to wait longer than expected. If you make a reservation in advance properly, it's a place worth recommending.", body_ja: "犬を連れて新しくできたペット美容室に行ってきました。スタッフが犬を扱う腕が良く、親切な方でした。ただ、予約が詰まっていて思ったより長く待たなければなりませんでした。事前にしっかり予約すれば勧められる場所です。", body_zh: "我带小狗去了新开的宠物美容院。员工处理小狗的手法好，也比较亲切。不过预约排得很满，比想象中等了更久。只要提前预约好，是值得推荐的地方。", body_vi: "Tôi đã đưa cún cưng đến tiệm chăm sóc thú cưng mới mở. Nhân viên có tay nghề xử lý chó tốt và cũng khá thân thiện. Tuy nhiên, vì lịch hẹn bị dồn nên tôi phải chờ lâu hơn dự kiến. Nếu đặt hẹn trước cẩn thận thì đây là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the salon?", question_ja: "この美容室の欠点は何でしたか。", question_zh: "这家美容院的缺点是什么？", question_vi: "Nhược điểm của tiệm này là gì?", options: ["Long wait due to backed-up appointments", "Rough handling of pets", "High prices", "Poor grooming quality"], answerIndex: 0 },
      { question_en: "What advice does the writer give?", question_ja: "書き手はどんなアドバイスをしていますか。", question_zh: "作者给出了什么建议？", question_vi: "Người viết đưa ra lời khuyên gì?", options: ["Make a reservation in advance", "Avoid weekdays", "Bring your own shampoo", "Go only in winter"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "도서관 스터디룸 후기",
    title_en: "A review of a library study room", title_ja: "図書館スタディルームのレビュー", title_zh: "图书馆自习室体验", title_vi: "Đánh giá phòng tự học thư viện",
    body_kr: "시험공부를 위해 도서관 스터디룸을 예약해서 이용했어요. 조용하고 책상도 넓은 편이라서 집중이 잘됐어요. 다만 예약이 인기가 많아서 원하는 시간대를 잡기가 어려웠어요. 미리미리 예약한다면 정말 추천할 만한 곳이에요.",
    body_en: "I reserved and used a library study room for exam preparation. It was quiet and the desks were fairly spacious, so I could focus well. However, reservations are popular, so it was hard to get the time slot I wanted. If you book well in advance, it's a place I'd really recommend.", body_ja: "試験勉強のために図書館のスタディルームを予約して利用しました。静かで机も広めな方だったので集中できました。ただ、予約が人気で希望の時間帯を取るのが難しかったです。早めに予約すれば本当にお勧めできる場所です。", body_zh: "为了准备考试我预约使用了图书馆自习室。很安静，桌子也比较宽敞，容易集中注意力。不过预约很受欢迎，很难抢到想要的时间段。如果提前预约的话真的很值得推荐。", body_vi: "Tôi đã đặt và sử dụng phòng tự học thư viện để ôn thi. Yên tĩnh và bàn cũng khá rộng nên tôi tập trung tốt. Tuy nhiên, vì đặt chỗ rất được ưa chuộng nên khó lấy được khung giờ mong muốn. Nếu đặt trước sớm thì đây thực sự là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was the difficulty with the study room?", question_ja: "スタディルームの難点は何でしたか。", question_zh: "自习室的难点是什么？", question_vi: "Khó khăn của phòng tự học này là gì?", options: ["Hard to get a preferred time slot", "It was too noisy", "The desks were too small", "It was too expensive"], answerIndex: 0 },
      { question_en: "What advice does the writer give?", question_ja: "書き手はどんなアドバイスをしていますか。", question_zh: "作者给出了什么建议？", question_vi: "Người viết đưa ra lời khuyên gì?", options: ["Book well in advance", "Avoid weekends", "Bring your own chair", "Study at night only"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "캠핑장 후기",
    title_en: "A review of a campsite", title_ja: "キャンプ場のレビュー", title_zh: "露营地体验", title_vi: "Đánh giá khu cắm trại",
    body_kr: "가족과 함께 산속에 있는 캠핑장에 다녀왔어요. 경치가 아름답고 사이트도 넓은 편이었어요. 그런데 화장실과 샤워실이 조금 낡아서 불편했어요. 자연을 즐기고 싶다면 충분히 추천할 만한 곳이에요.",
    body_en: "I went to a campsite in the mountains with my family. The scenery was beautiful and the sites were fairly spacious. However, the bathroom and shower facilities were a bit old, which was inconvenient. If you want to enjoy nature, it's a place well worth recommending.", body_ja: "家族と一緒に山の中にあるキャンプ場に行ってきました。景色が美しく、サイトも広めな方でした。ただ、トイレとシャワー室が少し古くて不便でした。自然を楽しみたいなら十分勧められる場所です。", body_zh: "我和家人一起去了山里的露营地。风景优美，营地也比较宽敞。不过厕所和淋浴室有点老旧，不太方便。如果想享受大自然，是完全值得推荐的地方。", body_vi: "Tôi đã cùng gia đình đến một khu cắm trại trong núi. Phong cảnh đẹp và khu cắm trại cũng khá rộng rãi. Tuy nhiên, nhà vệ sinh và phòng tắm hơi cũ nên bất tiện. Nếu muốn tận hưởng thiên nhiên thì đây hoàn toàn là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was inconvenient at the campsite?", question_ja: "キャンプ場で不便だった点は何ですか。", question_zh: "在露营地不方便的地方是什么？", question_vi: "Điều bất tiện tại khu cắm trại là gì?", options: ["Old bathroom and shower facilities", "No parking", "Too much noise", "No cell signal"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["The beautiful scenery", "The cheap price", "The restaurant on site", "The pool"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "스마트워치 구매 후기",
    title_en: "A review of buying a smartwatch", title_ja: "スマートウォッチ購入のレビュー", title_zh: "智能手表购买体验", title_vi: "Đánh giá mua đồng hồ thông minh",
    body_kr: "건강 관리를 위해 스마트워치를 하나 샀어요. 운동량과 수면을 기록해 줘서 유용한 편이에요. 다만 배터리가 하루 만에 다 닳아서 매일 충전해야 해요. 건강 관리에 관심이 많다면 추천할 만한 제품이에요.",
    body_en: "I bought a smartwatch for managing my health. It's fairly useful because it tracks exercise and sleep. However, the battery drains within a day, so I have to charge it every day. If you're very interested in health management, it's a product worth recommending.", body_ja: "健康管理のためにスマートウォッチを一つ買いました。運動量と睡眠を記録してくれて便利な方です。ただ、バッテリーが一日で全部減るので毎日充電しなければなりません。健康管理に関心が高いなら勧められる製品です。", body_zh: "为了健康管理我买了一块智能手表。能记录运动量和睡眠，比较有用。不过电池一天就用完了，得每天充电。如果对健康管理很感兴趣，是值得推荐的产品。", body_vi: "Tôi đã mua một chiếc đồng hồ thông minh để chăm sóc sức khỏe. Nó ghi lại lượng vận động và giấc ngủ nên khá hữu ích. Tuy nhiên, pin hết sạch trong một ngày nên phải sạc mỗi ngày. Nếu quan tâm nhiều đến chăm sóc sức khỏe thì đây là sản phẩm đáng giới thiệu.",
    questions: [
      { question_en: "What is the drawback of the smartwatch?", question_ja: "このスマートウォッチの欠点は何ですか。", question_zh: "这款智能手表的缺点是什么？", question_vi: "Nhược điểm của đồng hồ thông minh này là gì?", options: ["The battery drains in a day", "It doesn't track sleep", "It is too heavy", "It breaks easily"], answerIndex: 0 },
      { question_en: "What does the writer say it is useful for?", question_ja: "書き手はこれが何に役立つと言っていますか。", question_zh: "作者说它对什么有用？", question_vi: "Người viết nói nó hữu ích cho việc gì?", options: ["Tracking exercise and sleep", "Making phone calls", "Playing games", "Taking photos"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "온라인 요리 강좌 후기",
    title_en: "A review of an online cooking course", title_ja: "オンライン料理講座のレビュー", title_zh: "在线烹饪课体验", title_vi: "Đánh giá khóa học nấu ăn trực tuyến",
    body_kr: "집에서 배울 수 있는 온라인 요리 강좌를 신청했어요. 영상 설명이 자세하고 레시피도 따라 하기 쉬운 편이었어요. 그런데 재료 준비 목록이 미리 안내되지 않아서 조금 불편했어요. 요리 초보자에게 충분히 추천할 만한 강좌예요.",
    body_en: "I signed up for an online cooking course I could take at home. The video explanations were detailed and the recipes were fairly easy to follow. However, the ingredient list wasn't provided in advance, which was a bit inconvenient. It's a course well worth recommending for cooking beginners.", body_ja: "家で学べるオンライン料理講座に申し込みました。動画の説明が詳しく、レシピも真似しやすい方でした。ただ、材料の準備リストが事前に案内されなくて少し不便でした。料理初心者に十分勧められる講座です。", body_zh: "我报名了一门可以在家学习的在线烹饪课。视频讲解详细，食谱也比较容易跟着做。不过食材准备清单没有提前告知，有点不方便。对烹饪初学者来说是完全值得推荐的课程。", body_vi: "Tôi đã đăng ký một khóa học nấu ăn trực tuyến có thể học tại nhà. Video giải thích chi tiết và công thức cũng khá dễ làm theo. Tuy nhiên, danh sách nguyên liệu cần chuẩn bị không được thông báo trước nên hơi bất tiện. Đây là khóa học hoàn toàn đáng giới thiệu cho người mới học nấu ăn.",
    questions: [
      { question_en: "What was inconvenient about the course?", question_ja: "この講座で不便だった点は何ですか。", question_zh: "这门课不方便的地方是什么？", question_vi: "Điều bất tiện về khóa học này là gì?", options: ["The ingredient list wasn't given in advance", "The videos had no sound", "The recipes were too hard", "There was no support"], answerIndex: 0 },
      { question_en: "Who does the writer recommend the course for?", question_ja: "書き手は誰にこの講座を勧めていますか。", question_zh: "作者推荐给什么人？", question_vi: "Người viết giới thiệu khóa học này cho ai?", options: ["Cooking beginners", "Professional chefs", "People who dislike cooking", "Restaurant owners"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "자동차 정비소 후기",
    title_en: "A review of a car repair shop", title_ja: "自動車整備工場のレビュー", title_zh: "汽车修理厂体验", title_vi: "Đánh giá xưởng sửa xe ô tô",
    body_kr: "자동차 소음이 심해서 동네 정비소에 맡겼어요. 문제를 빠르게 찾아 주고 설명도 이해하기 쉬운 편이었어요. 다만 부품 가격이 다른 곳보다 조금 비싸게 느껴졌어요. 실력만큼은 확실해서 다시 갈 만한 곳이에요.",
    body_en: "Since my car was making a lot of noise, I took it to a neighborhood repair shop. They found the problem quickly and the explanation was fairly easy to understand. However, the parts price felt a bit higher than other places. Their skill is definitely reliable, so it's a place worth going back to.", body_ja: "車の異音がひどくて近所の整備工場に預けました。問題を素早く見つけてくれて、説明も理解しやすい方でした。ただ、部品の価格が他の店より少し高く感じました。腕は確かなのでまた行く価値のある場所です。", body_zh: "因为车噪音很大，我送去了附近的修理厂。他们很快找到了问题，说明也比较容易理解。不过零件价格感觉比别处贵一些。技术确实可靠，是值得再去的地方。", body_vi: "Vì xe có tiếng ồn nghiêm trọng nên tôi đã mang đến xưởng sửa xe trong khu phố. Họ tìm ra vấn đề nhanh chóng và giải thích cũng khá dễ hiểu. Tuy nhiên, giá phụ tùng có cảm giác hơi đắt hơn nơi khác. Vì tay nghề chắc chắn tốt nên đây là nơi đáng quay lại.",
    questions: [
      { question_en: "What was the drawback of the shop?", question_ja: "この工場の欠点は何でしたか。", question_zh: "这家修理厂的缺点是什么？", question_vi: "Nhược điểm của xưởng này là gì?", options: ["Parts felt a bit expensive", "They couldn't find the problem", "The explanation was confusing", "They were closed often"], answerIndex: 0 },
      { question_en: "What does the writer praise?", question_ja: "書き手が褒めているものは何ですか。", question_zh: "作者称赞了什么？", question_vi: "Người viết khen điều gì?", options: ["Their skill in finding problems", "The cheap prices", "The free coffee", "The waiting room"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "사진관 촬영 후기",
    title_en: "A review of a photo studio session", title_ja: "写真館撮影のレビュー", title_zh: "照相馆拍摄体验", title_vi: "Đánh giá chụp ảnh tại tiệm ảnh",
    body_kr: "가족 사진을 찍으려고 동네 사진관을 예약했어요. 사진작가님이 편안한 분위기를 잘 만들어 주는 편이었어요. 그런데 사진 보정본을 받는 데 시간이 예상보다 오래 걸렸어요. 결과물은 만족스러워서 추천할 만한 곳이에요.",
    body_en: "I booked a neighborhood photo studio to take family photos. The photographer was fairly good at creating a comfortable atmosphere. However, receiving the edited photos took longer than expected. The results were satisfying, so it's a place worth recommending.", body_ja: "家族写真を撮ろうと近所の写真館を予約しました。写真家が居心地の良い雰囲気をうまく作ってくれる方でした。ただ、補正済みの写真を受け取るのに予想より時間がかかりました。仕上がりには満足しているので勧められる場所です。", body_zh: "为了拍全家福我预约了附近的照相馆。摄影师比较擅长营造轻松的氛围。不过拿到修图成片花的时间比预期的长。结果让人满意，是值得推荐的地方。", body_vi: "Tôi đã đặt lịch tại một tiệm ảnh trong khu phố để chụp ảnh gia đình. Nhiếp ảnh gia khá giỏi trong việc tạo không khí thoải mái. Tuy nhiên, việc nhận ảnh đã chỉnh sửa mất nhiều thời gian hơn dự kiến. Kết quả khiến tôi hài lòng nên đây là nơi đáng giới thiệu.",
    questions: [
      { question_en: "What was the drawback of the studio?", question_ja: "この写真館の欠点は何でしたか。", question_zh: "这家照相馆的缺点是什么？", question_vi: "Nhược điểm của tiệm ảnh này là gì?", options: ["Editing took longer than expected", "The photographer was rude", "The studio was messy", "The photos were poor quality"], answerIndex: 0 },
      { question_en: "How does the writer feel about the results?", question_ja: "書き手は結果についてどう感じていますか。", question_zh: "作者对结果感觉如何？", question_vi: "Người viết cảm thấy thế nào về kết quả?", options: ["Satisfied", "Disappointed", "Indifferent", "Angry"], answerIndex: 0 },
    ],
  },
  {
    level: "B1",
    genre: "review",
    title_kr: "명상 앱 사용 후기",
    title_en: "A review of using a meditation app", title_ja: "瞑想アプリ使用のレビュー", title_zh: "冥想应用使用体验", title_vi: "Đánh giá sử dụng ứng dụng thiền",
    body_kr: "스트레스를 줄이려고 명상 앱을 한 달 동안 써 봤어요. 다양한 프로그램이 있고 목소리도 편안한 편이었어요. 하지만 무료로 이용할 수 있는 콘텐츠가 생각보다 적었어요. 꾸준히 명상하고 싶다면 유료 버전도 고려할 만해요.",
    body_en: "I used a meditation app for a month to reduce stress. There are various programs and the voice is fairly soothing. However, the free content was less than expected. If you want to meditate consistently, the paid version is also worth considering.", body_ja: "ストレスを減らそうと瞑想アプリを一か月使ってみました。様々なプログラムがあり、声も心地よい方でした。ただ、無料で使えるコンテンツが思ったより少なかったです。継続して瞑想したいなら有料版も検討する価値があります。", body_zh: "为了减压我用了一个月的冥想应用。有各种各样的课程，声音也比较舒缓。不过免费能用的内容比想象中少。如果想坚持冥想，也值得考虑付费版。", body_vi: "Để giảm căng thẳng, tôi đã dùng thử một ứng dụng thiền trong một tháng. Có nhiều chương trình đa dạng và giọng đọc cũng khá dễ chịu. Tuy nhiên, nội dung có thể dùng miễn phí ít hơn tôi nghĩ. Nếu muốn thiền đều đặn thì cũng nên cân nhắc phiên bản trả phí.",
    questions: [
      { question_en: "What is the limitation of the free version?", question_ja: "無料版の制限は何ですか。", question_zh: "免费版的限制是什么？", question_vi: "Hạn chế của phiên bản miễn phí là gì?", options: ["Limited free content", "It doesn't work offline", "The voice is annoying", "It has ads every minute"], answerIndex: 0 },
      { question_en: "What does the writer suggest?", question_ja: "書き手は何を提案していますか。", question_zh: "作者提出了什么建议？", question_vi: "Người viết đề xuất điều gì?", options: ["Considering the paid version", "Deleting the app", "Using a different app entirely", "Only using it once a week"], answerIndex: 0 },
    ],
  },
];
