import type { RawPassage } from "./types";

export const READING_B2_EXPLAINER: RawPassage[] = [
  {
    level: "B2",
    genre: "explainer",
    title_kr: "미루는 습관의 심리학",
    title_en: "The psychology of procrastination",
    body_kr: "많은 사람들이 해야 할 일을 뒤로 미루면서도 그 이유를 게으름 때문이라고 오해한다. 그러나 심리학자들은 미루는 행동이 대개 감정 조절의 문제라고 설명한다. 어려운 과제를 마주할 때 느끼는 불안이나 부담감을 피하려고 뇌가 즉각적인 회피를 선택한다는 것이다. 문제는 이 회피가 순간의 안도감만 줄 뿐 나중에 더 큰 스트레스로 돌아온다는 점이다. 전문가들은 미루는 습관을 고치려면 의지력보다 환경을 바꾸는 것이 효과적이라고 말한다. 예를 들어 일을 작은 단위로 쪼개면 시작에 대한 부담이 줄어든다. 또한 시작하는 행동 자체에 집중하고 완성도는 나중에 신경 쓰는 방법도 도움이 된다. 결국 미루는 습관을 이해하는 첫걸음은 자신을 탓하지 않는 것에서 시작된다.",
    body_en: "Many people put off tasks and mistakenly blame it on laziness. But psychologists explain that procrastination is usually a problem of emotional regulation. When facing a difficult task, the brain chooses immediate avoidance to escape the anxiety or pressure it triggers. The problem is that this avoidance only brings momentary relief and returns as greater stress later. Experts say that changing the environment is more effective than relying on willpower to break the habit. For instance, breaking work into small units reduces the burden of starting. Focusing on the act of starting itself, rather than perfection, also helps. Ultimately, the first step to understanding procrastination is not blaming oneself.",
    questions: [
      { question_en: "According to the passage, what do psychologists say procrastination is mainly about?", options: ["Laziness", "Lack of intelligence", "Poor time management skills", "Emotional regulation"], answerIndex: 3 },
      { question_en: "What method is suggested to reduce the burden of starting a task?", options: ["Working only at night", "Breaking work into small units", "Ignoring the task completely", "Waiting for motivation to appear"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "결정 피로란 무엇인가",
    title_en: "What is decision fatigue?",
    body_kr: "하루 종일 크고 작은 선택을 반복하다 보면 저녁 무렵에는 판단력이 눈에 띄게 흐려지는 경험을 하게 된다. 심리학에서는 이를 결정 피로라고 부른다. 뇌가 하나의 근육처럼 작동하여 선택을 거듭할수록 에너지가 소모된다는 이론이다. 실제로 판사들이 오전보다 오후에 더 엄격한 판결을 내리는 경향이 있다는 연구 결과도 있다. 이는 판단이 지칠수록 사람들이 더 쉽고 안전한 선택지를 고르는 경향과 관련이 있다. 결정 피로를 줄이기 위해 일부 성공한 사람들은 옷차림이나 식사 메뉴처럼 사소한 선택을 미리 정해 둔다. 이렇게 하면 정말 중요한 결정에 쓸 에너지를 아낄 수 있다. 결국 좋은 판단을 유지하려면 무엇을 선택하느냐보다 언제 선택하느냐가 중요할 수 있다.",
    body_en: "After making countless big and small choices throughout the day, people often notice their judgment becoming noticeably foggy by evening. Psychology calls this decision fatigue. The theory holds that the brain works like a muscle, and repeated choices drain its energy. Research has even found that judges tend to hand down harsher rulings in the afternoon than in the morning. This is linked to a tendency to choose easier, safer options as judgment grows tired. To reduce decision fatigue, some highly successful people pre-decide trivial choices like clothing or meals. This saves energy for decisions that truly matter. Ultimately, maintaining good judgment may depend less on what you choose and more on when you choose it.",
    questions: [
      { question_en: "What research finding is mentioned to support the idea of decision fatigue?", options: ["Doctors work faster in the morning", "Athletes perform better after lunch", "Teachers grade more fairly at night", "Judges rule more harshly in the afternoon"], answerIndex: 3 },
      { question_en: "What strategy do some successful people use to fight decision fatigue?", options: ["Pre-deciding trivial choices in advance", "Avoiding all decisions", "Making every decision quickly without thought", "Sleeping more hours"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "완벽주의라는 함정",
    title_en: "The trap of perfectionism",
    body_kr: "완벽주의는 흔히 성실함이나 높은 기준의 상징으로 여겨진다. 하지만 심리학자들은 완벽주의가 오히려 성과를 떨어뜨리고 정신 건강을 해칠 수 있다고 지적한다. 완벽주의자들은 실수를 두려워한 나머지 일을 아예 시작하지 못하거나 끝없이 미루는 경향을 보인다. 또한 결과물이 기준에 미치지 못한다고 느끼면 성취 자체를 즐기지 못하고 자책에 빠지기 쉽다. 연구에 따르면 이러한 성향은 번아웃과 불안 장애의 위험을 높이는 요인으로 작용한다. 전문가들은 완벽주의와 높은 기준을 구분해야 한다고 조언한다. 높은 기준을 가진 사람은 실수를 배움의 과정으로 받아들이지만 완벽주의자는 실수를 실패로 규정한다는 차이가 있다. 결국 건강한 성취는 완벽함이 아니라 꾸준한 개선을 목표로 삼을 때 가능해진다.",
    body_en: "Perfectionism is often seen as a sign of diligence or high standards. But psychologists point out that it can actually lower performance and harm mental health. Perfectionists tend to fail to start tasks at all, or endlessly postpone them, out of fear of mistakes. They also find it hard to enjoy achievement itself, falling into self-blame whenever a result falls short of their standard. Research shows this tendency raises the risk of burnout and anxiety disorders. Experts advise distinguishing perfectionism from high standards. Someone with high standards accepts mistakes as part of learning, while a perfectionist defines mistakes as failure — that is the difference. Ultimately, healthy achievement becomes possible when the goal is steady improvement rather than perfection.",
    questions: [
      { question_en: "What risk does research link to perfectionism?", options: ["Higher risk of burnout and anxiety disorders", "Improved memory", "Better sleep quality", "Increased creativity"], answerIndex: 0 },
      { question_en: "How do people with high standards differ from perfectionists, according to the passage?", options: ["They avoid setting goals", "They work only alone", "They accept mistakes as part of learning", "They never make mistakes"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "감정을 이름 붙이는 힘",
    title_en: "The power of naming emotions",
    body_kr: "화가 나거나 불안할 때 그 감정에 정확한 이름을 붙이는 것만으로도 마음이 진정되는 효과가 있다고 한다. 이를 감정 라벨링이라고 부른다. 뇌 영상 연구에 따르면 감정을 언어로 표현하는 순간 감정을 담당하는 편도체의 활동이 줄어드는 것으로 나타났다. 반면 이성적 판단을 담당하는 전두엽의 활동은 활발해진다. 즉 감정에 이름을 붙이는 행위 자체가 뇌를 진정시키는 스위치 역할을 하는 셈이다. 그러나 많은 사람들은 감정을 그저 좋다 나쁘다로 단순하게 구분하는 데 그친다. 전문가들은 화남과 실망, 불안과 두려움처럼 비슷하지만 다른 감정을 세밀하게 구분하는 연습이 필요하다고 말한다. 감정 어휘가 풍부할수록 스트레스 상황에서 더 유연하게 대처할 수 있다는 연구 결과도 이를 뒷받침한다.",
    body_en: "Simply naming an emotion accurately when feeling angry or anxious is said to have a calming effect. This is called emotional labeling. Brain imaging studies show that the moment an emotion is put into words, activity in the amygdala, which handles emotion, decreases. Meanwhile, activity in the prefrontal cortex, responsible for rational judgment, increases. In other words, naming an emotion itself acts as a switch that calms the brain. However, many people simply categorize emotions as good or bad. Experts say practice is needed to distinguish similar but different emotions in detail, such as anger versus disappointment, or anxiety versus fear. Research supporting this shows that a richer emotional vocabulary allows people to cope more flexibly with stressful situations.",
    questions: [
      { question_en: "What happens in the brain when an emotion is put into words, according to the passage?", options: ["Amygdala activity increases and prefrontal activity decreases", "Nothing measurable changes", "Amygdala activity decreases and prefrontal activity increases", "Both regions become inactive"], answerIndex: 2 },
      { question_en: "What do experts recommend for better emotional coping?", options: ["Suppressing emotions in public", "Ignoring emotions completely", "Labeling everything as simply good or bad", "Distinguishing similar emotions in detail"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "타인의 시선을 의식하는 뇌",
    title_en: "A brain wired to notice others' gaze",
    body_kr: "낯선 사람들 앞에서 발표할 때 유난히 긴장되는 이유는 단순한 소심함 때문만은 아니다. 진화심리학자들은 인간이 사회적 동물로 진화하면서 타인의 평가에 예민하게 반응하도록 뇌가 설계되었다고 설명한다. 과거에는 집단에서 배제되는 것이 생존을 위협하는 일이었기 때문에 이런 반응이 유용했다. 그러나 현대 사회에서는 이 반응이 과도하게 작동하며 불필요한 불안을 낳는 경우가 많다. 흥미롭게도 실험 참가자들이 실제로는 아무도 자신을 주목하지 않는데도 모두가 자신을 보고 있다고 느끼는 현상이 관찰되었다. 이를 스포트라이트 효과라고 부른다. 이 효과를 인식하는 것만으로도 사회적 불안이 줄어든다는 연구 결과가 있다. 결국 남들이 나를 그렇게까지 신경 쓰지 않는다는 사실을 아는 것이 마음의 짐을 덜어 준다.",
    body_en: "Feeling unusually nervous when presenting in front of strangers is not simply due to shyness. Evolutionary psychologists explain that as humans evolved as social animals, the brain became wired to react sensitively to others' judgment. In the past, being excluded from the group threatened survival, so this reaction was useful. But in modern society, this reaction often overreacts and creates unnecessary anxiety. Interestingly, experiments have observed that participants feel everyone is watching them even when, in reality, no one is paying attention. This is called the spotlight effect. Studies show that simply becoming aware of this effect reduces social anxiety. Ultimately, knowing that others don't care as much as we think lightens the mental burden.",
    questions: [
      { question_en: "What is the spotlight effect, as described in the passage?", options: ["A method to reduce stage fright physically", "A stage lighting technique", "The tendency to avoid crowds", "Feeling watched by everyone when no one is actually looking"], answerIndex: 3 },
      { question_en: "What did research find about awareness of the spotlight effect?", options: ["It only works for extroverts", "It increases social anxiety", "It reduces social anxiety", "It has no measurable impact"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "왜 나쁜 기억이 더 오래 남을까",
    title_en: "Why bad memories stick around longer",
    body_kr: "즐거웠던 여행보다 실수했던 순간이 더 선명하게 기억에 남는 경험은 누구에게나 있다. 심리학자들은 이를 부정 편향이라고 부른다. 인간의 뇌는 위험을 피하고 생존 확률을 높이기 위해 부정적인 정보에 더 강하게 반응하도록 진화했다. 좋은 일보다 나쁜 일에서 배울 것이 많다고 뇌가 판단하기 때문이다. 문제는 이 편향이 지나치면 자기 평가를 왜곡시킨다는 점이다. 실제로는 잘한 일이 훨씬 많음에도 몇 번의 실수만 곱씹으며 스스로를 부족한 사람으로 여기게 되는 것이다. 심리학자들은 이를 극복하기 위해 하루를 마무리하며 잘한 일 세 가지를 의식적으로 떠올리는 연습을 권한다. 이런 작은 훈련이 반복되면 부정 편향의 영향력을 서서히 줄일 수 있다고 한다.",
    body_en: "Everyone has experienced remembering a moment of failure more vividly than a pleasant trip. Psychologists call this negativity bias. The human brain evolved to react more strongly to negative information in order to avoid danger and improve chances of survival. The brain judges that there is more to learn from bad events than good ones. The problem is that when this bias goes too far, it distorts self-evaluation. Even when someone has done far more things well, dwelling on a few mistakes can make them see themselves as inadequate. To overcome this, psychologists recommend consciously recalling three things done well at the end of each day. Repeating this small exercise can gradually reduce the influence of negativity bias.",
    questions: [
      { question_en: "What is negativity bias, as explained in the passage?", options: ["A tendency to forget bad events quickly", "An inability to remember anything", "A preference for negative people", "A stronger reaction to negative information than positive"], answerIndex: 3 },
      { question_en: "What exercise do psychologists recommend to counter negativity bias?", options: ["Writing down only mistakes", "Avoiding all reflection", "Recalling three things done well each day", "Comparing yourself to others daily"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "몰입은 어떻게 만들어지는가",
    title_en: "How flow is created",
    body_kr: "시간 가는 줄 모르고 어떤 일에 완전히 빠져든 경험을 심리학에서는 몰입이라고 부른다. 이 개념을 처음 제시한 학자는 몰입이 특별한 재능이 아니라 조건이 맞으면 누구에게나 일어날 수 있는 상태라고 설명했다. 몰입이 발생하려면 과제의 난이도와 개인의 실력이 적절히 균형을 이루어야 한다. 과제가 너무 쉬우면 지루함을 느끼고 너무 어려우면 불안을 느끼기 때문이다. 또한 즉각적인 피드백이 주어지는 활동일수록 몰입이 잘 일어난다. 게임이 대표적인 예로, 점수나 진행 상황이 바로바로 표시되기 때문에 사람들이 쉽게 빠져든다. 흥미로운 점은 몰입 상태에서는 자의식이 옅어지고 오히려 만족감이 커진다는 것이다. 전문가들은 일상 업무에도 명확한 목표와 즉각적인 피드백을 도입하면 몰입을 유도할 수 있다고 조언한다.",
    body_en: "Psychology calls the experience of being so absorbed in something that time seems to disappear \"flow.\" The scholar who first proposed this concept explained that flow is not a special talent but a state that can happen to anyone under the right conditions. For flow to occur, the difficulty of a task and a person's skill level must be properly balanced. A task that is too easy causes boredom, while one that is too hard causes anxiety. Flow also occurs more readily in activities that give immediate feedback. Games are a prime example, since scores or progress are displayed instantly, drawing people in easily. Interestingly, self-consciousness fades and satisfaction grows in a state of flow. Experts advise that introducing clear goals and immediate feedback into everyday work can induce flow as well.",
    questions: [
      { question_en: "What condition is necessary for flow to occur, according to the passage?", options: ["Difficulty and skill must be balanced", "The person must work alone", "The task must be extremely easy", "The task must have no feedback"], answerIndex: 0 },
      { question_en: "What happens to self-consciousness during flow?", options: ["It fades while satisfaction grows", "It increases sharply", "It has no relation to flow", "It disappears entirely and permanently"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "손실을 더 두려워하는 마음",
    title_en: "A mind that fears loss more than it values gain",
    body_kr: "만 원을 얻었을 때의 기쁨보다 만 원을 잃었을 때의 아픔이 훨씬 크게 느껴진다는 사실을 실험으로 증명한 학자들이 있다. 이를 손실 회피라고 부른다. 연구에 따르면 사람들은 이익보다 손실에 약 두 배 더 민감하게 반응한다. 이 성향은 투자 결정에서 특히 두드러진다. 손실을 확정 짓기 싫어서 가치가 떨어지는 주식을 계속 보유하는 경우가 대표적이다. 손실 회피는 소비 습관에도 영향을 미친다. 무료 체험 후 해지하지 않으면 자동으로 결제되는 구독 서비스가 인기를 끄는 이유도 여기에 있다. 이미 시작한 것을 그만두는 결정이 손실처럼 느껴지기 때문이다. 이러한 심리를 이해하면 비합리적인 소비나 투자 결정을 줄이는 데 도움이 될 수 있다.",
    body_en: "Researchers have proven through experiments that the pain of losing ten thousand won feels much greater than the joy of gaining the same amount. This is called loss aversion. Studies show people are roughly twice as sensitive to losses as to equivalent gains. This tendency is especially prominent in investment decisions. A classic example is holding onto a declining stock because one is unwilling to lock in the loss. Loss aversion also affects consumption habits. It explains why subscription services that auto-renew after a free trial unless canceled are so popular — stopping something already started feels like a loss. Understanding this psychology can help reduce irrational spending and investment decisions.",
    questions: [
      { question_en: "According to the passage, how much more sensitive are people to losses than gains?", options: ["Ten times as sensitive", "Equally sensitive", "About half as sensitive", "About twice as sensitive"], answerIndex: 3 },
      { question_en: "Why do auto-renewing subscription services succeed, according to the passage?", options: ["Because they are always the cheapest option", "Because people forget they exist", "Because canceling feels like a loss", "Because they require no internet access"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "기억은 왜 왜곡될까",
    title_en: "Why memory gets distorted",
    body_kr: "우리는 흔히 기억을 과거를 그대로 저장한 녹화 영상처럼 여기지만 심리학 연구는 이러한 믿음이 사실과 다르다는 것을 보여 준다. 기억은 매번 떠올릴 때마다 조금씩 재구성되며 그 과정에서 세부 내용이 바뀌기도 한다. 실제로 실험 참가자들에게 없었던 사건에 대한 암시를 반복적으로 주었더니 시간이 지나면서 그 일이 실제로 있었다고 확신하는 경우가 나타났다. 이러한 현상은 목격자 증언의 신뢰성 문제와도 깊은 관련이 있다. 확신에 찬 목격자의 증언이라 하더라도 시간이 지나면서 왜곡되었을 가능성을 배제할 수 없다는 것이다. 연구자들은 감정이 강하게 개입된 기억일수록 오히려 왜곡될 위험이 크다고 지적한다. 강렬한 감정이 세부 사항보다 전체적인 인상을 우선적으로 남기기 때문이다. 이러한 연구 결과는 법정에서의 증언 채택 방식에도 실질적인 영향을 미치고 있다.",
    body_en: "We often think of memory as a recording that preserves the past exactly as it happened, but psychological research shows this belief is not accurate. Memory is reconstructed slightly each time it is recalled, and details can change in the process. In fact, when experiment participants were repeatedly given suggestions about an event that never happened, some came to firmly believe over time that it actually occurred. This phenomenon is deeply related to the reliability problem of eyewitness testimony. Even a confident eyewitness's testimony, researchers say, cannot rule out the possibility of distortion over time. Researchers point out that memories with strong emotional involvement are actually at greater risk of distortion. This is because intense emotion tends to leave behind an overall impression rather than precise details. These research findings are having a practical impact on how testimony is treated in courts.",
    questions: [
      { question_en: "What did the experiment involving false suggestions reveal about memory?", options: ["Participants came to believe events that never happened", "Memory cannot be influenced by suggestion", "Suggestions have no lasting effect", "Memory is always perfectly accurate"], answerIndex: 0 },
      { question_en: "According to researchers, what type of memory is at greater risk of distortion?", options: ["Memories from early childhood only", "Memories written down immediately", "Memories with no emotional content", "Memories with strong emotional involvement"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "번아웃 이후 다시 일어서는 법",
    title_en: "How to rebuild after burnout",
    body_kr: "열정적으로 일하던 사람이 어느 순간 극심한 피로와 무기력을 느끼며 아무것도 할 수 없는 상태에 빠지는 경우가 있다. 이를 번아웃이라고 부르며, 세계보건기구는 이를 만성적인 직장 스트레스로 인한 증후군으로 규정한 바 있다. 번아웃을 겪는 사람들은 흔히 일을 더 열심히 하지 못하는 자신을 탓하지만, 전문가들은 이것이 능력의 문제가 아니라 오랜 시간 축적된 스트레스의 결과라고 강조한다. 회복을 위해서는 먼저 충분한 휴식을 통해 몸과 마음의 에너지를 회복하는 것이 우선이다. 그러나 단순히 쉬는 것만으로는 부족하며, 자신을 소진시킨 근본적인 원인을 점검하는 과정이 함께 필요하다는 지적도 있다. 일부 전문가들은 지나치게 많은 책임을 홀로 떠안는 습관이나 완벽주의적 성향이 번아웃의 주요 원인이라고 분석한다. 회복 과정에서 주변에 도움을 요청하는 것을 부끄러워하지 않는 태도도 중요하게 꼽힌다. 결국 번아웃에서 벗어나는 길은 예전으로 완전히 돌아가는 것이 아니라 일과 삶의 새로운 균형을 찾는 데 있다.",
    body_en: "There are cases where someone who once worked passionately suddenly falls into a state of extreme fatigue and helplessness, unable to do anything. This is called burnout, and the World Health Organization has defined it as a syndrome resulting from chronic workplace stress. People experiencing burnout often blame themselves for not being able to work harder, but experts stress this is not a matter of ability but the result of stress accumulated over a long period. Recovery requires, first, restoring the body's and mind's energy through sufficient rest. But simply resting is not enough, some note, and a process of examining the root cause that led to exhaustion is also needed. Some experts analyze that a habit of shouldering too much responsibility alone, or a perfectionist tendency, is a major cause of burnout. Not feeling ashamed to ask those around you for help during recovery is also cited as important. Ultimately, the path out of burnout lies not in returning completely to how things were before, but in finding a new balance between work and life.",
    questions: [
      { question_en: "How does the World Health Organization define burnout?", options: ["A personal character flaw", "A syndrome from chronic workplace stress", "A temporary mood swing", "A physical illness unrelated to work"], answerIndex: 1 },
      { question_en: "What do some experts identify as a major cause of burnout?", options: ["Shouldering too much responsibility alone or perfectionism", "Avoiding all responsibility", "Taking too many vacations", "Working too few hours"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "왜 우리는 뒷담화를 할까",
    title_en: "Why do people gossip?",
    body_kr: "뒷담화는 흔히 부정적이고 소모적인 행동으로 여겨지지만 진화심리학자들은 이것이 인간 사회에서 나름의 기능을 수행해 왔다고 설명한다. 초기 인류 사회에서 집단의 규모가 커지면서 모든 구성원의 행동을 직접 관찰하기 어려워지자 정보를 공유하는 수단으로 뒷담화가 발달했다는 것이다. 누가 신뢰할 수 있고 누가 그렇지 않은지에 대한 정보를 공유하는 것은 집단 생존에 실질적인 도움이 되었다. 실제로 연구에 따르면 대화의 상당 부분이 타인에 대한 이야기로 채워지며 이는 시대와 문화를 막론하고 공통적으로 나타나는 현상이다. 물론 근거 없는 비방으로 흐르는 뒷담화는 관계를 해치고 신뢰를 무너뜨리는 부작용을 낳는다. 심리학자들은 뒷담화 자체를 무조건 나쁘게 볼 것이 아니라 그것이 사실에 기반하는지, 그리고 어떤 목적으로 이루어지는지를 살펴야 한다고 조언한다. 결국 중요한 것은 뒷담화의 존재 여부가 아니라 그것이 관계를 해치는 방향으로 흐르지 않도록 하는 절제다.",
    body_en: "Gossip is often seen as a negative, unproductive behavior, but evolutionary psychologists explain it has served a function of its own in human society. As group size grew in early human societies, making it hard to directly observe every member's behavior, gossip developed as a means of sharing information. Sharing information about who could and could not be trusted provided real benefit to group survival. Research indeed shows that a considerable portion of conversation is filled with talk about other people, a phenomenon common across eras and cultures. Of course, gossip that drifts into baseless slander causes side effects such as damaging relationships and eroding trust. Psychologists advise not viewing gossip itself as unconditionally bad but examining whether it is based on fact and what purpose it serves. In the end, what matters is not whether gossip exists but exercising restraint so it does not drift in a direction that damages relationships.",
    questions: [
      { question_en: "What function did gossip serve in early human societies, according to evolutionary psychologists?", options: ["It only harmed group survival", "It served as a means of sharing information about trustworthiness", "It had no function at all", "It replaced all other forms of communication"], answerIndex: 1 },
      { question_en: "What do psychologists advise about evaluating gossip?", options: ["Always view it as unconditionally bad", "Examine whether it is fact-based and its purpose", "Ban all conversation about others", "Ignore its effects on relationships"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "왜 우리는 후회를 반복할까",
    title_en: "Why do we keep repeating regret?",
    body_kr: "지나간 선택을 곱씹으며 후회하는 것은 인간의 흔한 심리적 습관이다. 흥미롭게도 심리학 연구에 따르면 사람들은 저지른 행동보다 하지 않은 행동을 더 오래, 더 강하게 후회하는 경향이 있다. 시도했다가 실패한 일은 시간이 지나면서 배움의 경험으로 받아들여지는 반면 시도조차 하지 않은 일은 계속해서 마음에 남기 때문이다. 이를 행동 후회와 무행동 후회의 차이라고 부른다. 특히 인생의 중요한 갈림길에서 도전을 포기했던 순간일수록 오랫동안 후회로 남는 경향이 강하다. 전문가들은 이러한 심리를 이해하면 앞으로의 결정에서 참고할 지침을 얻을 수 있다고 말한다. 실패에 대한 두려움 때문에 시도 자체를 회피하고 있다면 그 선택이 나중에 더 큰 후회로 돌아올 가능성이 크다는 것이다. 결국 후회를 줄이는 가장 좋은 방법은 완벽한 결과를 보장받는 것이 아니라 일단 시도해 보는 용기에 있다는 조언이 뒤따른다.",
    body_en: "Dwelling on and regretting past choices is a common human psychological habit. Interestingly, psychological research shows that people tend to regret things they did not do longer and more intensely than things they did. This is because attempts that failed tend to be accepted over time as learning experiences, whereas things never even attempted keep lingering in the mind. This is called the difference between action regret and inaction regret. Regret tends to be especially long-lasting for moments at major turning points in life when someone gave up on a challenge. Experts say understanding this psychology can offer useful guidance for future decisions. If fear of failure is causing someone to avoid even attempting something, that choice is likely to return as even greater regret later. Ultimately, advice follows that the best way to reduce regret lies not in guaranteeing a perfect outcome but in having the courage to simply try.",
    questions: [
      { question_en: "According to the research mentioned, which type of regret tends to last longer?", options: ["Regret over things done and failed", "Regret over other people's choices", "Regret over things never attempted", "Regret has no duration difference"], answerIndex: 2 },
      { question_en: "What advice follows from understanding this psychology, according to the passage?", options: ["Never reflect on past choices", "Only attempt guaranteed successes", "Have the courage to simply try", "Avoid all risk permanently"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "텀블러는 정말 환경에 도움이 될까",
    title_en: "Do reusable cups really help the environment?",
    body_kr: "일회용 컵 대신 텀블러를 사용하는 사람들이 눈에 띄게 늘었다. 그러나 최근 일부 연구는 이러한 실천이 생각만큼 단순하지 않다고 지적한다. 텀블러를 생산하는 과정에서도 상당한 자원과 에너지가 소모되기 때문에 몇 번 쓰다 버리면 오히려 일회용 컵보다 환경에 부담을 줄 수 있다는 것이다. 연구자들은 텀블러 한 개가 일회용 컵을 대체하는 효과를 내려면 최소 수십 번 이상 반복해서 사용해야 한다고 분석했다. 문제는 다양한 디자인의 텀블러가 유행처럼 소비되면서 정작 오래 쓰이지 못하는 경우가 많다는 점이다. 전문가들은 새 텀블러를 사는 것보다 이미 가진 것을 최대한 오래 쓰는 태도가 더 중요하다고 강조한다. 결국 친환경 소비의 핵심은 무엇을 사느냐가 아니라 얼마나 오래 쓰느냐에 있다.",
    body_en: "The number of people using reusable cups instead of disposable ones has noticeably grown. But recent studies point out that this practice is not as simple as it seems. Producing a reusable cup also consumes considerable resources and energy, so discarding it after only a few uses can actually place a greater burden on the environment than a disposable cup. Researchers found that a single reusable cup must be used dozens of times or more to offset the disposable cups it replaces. The problem is that as trendy reusable cup designs are consumed like fashion items, many end up rarely used for long. Experts stress that using what one already owns for as long as possible matters more than buying a new reusable cup. Ultimately, the core of eco-friendly consumption lies not in what you buy but in how long you use it.",
    questions: [
      { question_en: "What did researchers find about the environmental benefit of reusable cups?", options: ["They should be replaced every week", "They must be used dozens of times or more to offset disposables", "They have no environmental cost at all", "They are always better after just one use"], answerIndex: 1 },
      { question_en: "What do experts say matters most for eco-friendly consumption?", options: ["Buying multiple reusable cups", "Buying the newest design", "Avoiding cups entirely", "Using what you already own for as long as possible"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "친환경이라는 이름의 함정",
    title_en: "The trap behind the word 'eco-friendly'",
    body_kr: "제품 포장에 초록색 나뭇잎 그림과 함께 친환경이라는 문구가 붙은 상품을 흔히 볼 수 있다. 그러나 이런 표시가 실제 환경 보호 효과를 보장하지는 않는다는 지적이 늘고 있다. 이른바 그린워싱이라 불리는 이 현상은 기업이 실질적인 노력 없이 이미지만으로 친환경 소비자를 끌어들이려는 마케팅 전략을 뜻한다. 예를 들어 포장재 극히 일부만 재활용 소재로 바꾸고도 전체 제품이 친환경적인 것처럼 홍보하는 경우가 대표적이다. 소비자들이 이런 표시에 익숙해지면서 오히려 진짜 친환경 제품을 가려내기가 더 어려워졌다는 역설도 발생한다. 이에 일부 국가에서는 친환경 문구 사용에 대한 기준을 강화하는 법안을 마련하고 있다. 전문가들은 소비자 스스로도 인증 마크나 성분표를 꼼꼼히 확인하는 습관을 들여야 한다고 조언한다. 결국 그린워싱을 막는 힘은 규제와 함께 소비자의 비판적인 시각에서 나온다.",
    body_en: "It is common to see products with a green leaf image and the label \"eco-friendly\" on their packaging. But a growing number of critics point out that such labels do not guarantee actual environmental benefit. This phenomenon, called greenwashing, refers to a marketing strategy in which companies try to attract eco-conscious consumers through image alone, without substantive effort. A common example is promoting an entire product as eco-friendly after changing only a tiny portion of its packaging to recycled material. As consumers grow accustomed to such labels, a paradox emerges in which it becomes even harder to identify genuinely eco-friendly products. In response, some countries are drafting legislation to tighten standards for using eco-friendly claims. Experts advise that consumers themselves should form the habit of carefully checking certification marks and ingredient lists. Ultimately, the power to stop greenwashing comes from both regulation and consumers' critical perspective.",
    questions: [
      { question_en: "What does greenwashing refer to, according to the passage?", options: ["A government recycling program", "Genuine environmental certification", "Marketing eco-friendly image without substantive effort", "A type of biodegradable plastic"], answerIndex: 2 },
      { question_en: "What do experts advise consumers to do to counter greenwashing?", options: ["Carefully check certification marks and ingredients", "Trust all green labels automatically", "Rely only on advertisements", "Stop buying any products"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "플라스틱 없는 하루는 가능할까",
    title_en: "Is a plastic-free day even possible?",
    body_kr: "아침에 눈을 떠서 밤에 잠들 때까지 플라스틱을 전혀 만지지 않고 하루를 보내는 것이 가능할지 실험해 본 사람들이 있다. 결과는 예상보다 훨씬 어려웠다는 것이다. 칫솔부터 샴푸 용기, 식품 포장재까지 일상 곳곳에 플라스틱이 스며들어 있기 때문이다. 이 실험은 플라스틱이 우리 삶에 얼마나 깊숙이 자리 잡았는지를 새삼 일깨워 준다. 완전히 플라스틱을 없애는 것이 현실적으로 불가능하다면 대안은 무엇일까. 전문가들은 완벽한 제로를 목표로 하기보다 대체 가능한 부분부터 하나씩 바꿔 나가는 태도를 제안한다. 예를 들어 플라스틱 칫솔을 대나무 칫솔로, 비닐봉지를 장바구니로 바꾸는 식이다. 작은 실천들이 모이면 개인의 소비 습관뿐 아니라 기업의 생산 방식에도 변화를 이끌어낼 수 있다는 것이 이들의 설명이다.",
    body_en: "Some people have tried the experiment of going an entire day, from waking up to falling asleep, without touching plastic at all. The result was that it was far harder than expected. Plastic is woven into everyday life, from toothbrushes to shampoo bottles to food packaging. This experiment serves as a fresh reminder of just how deeply plastic is embedded in our lives. If eliminating plastic entirely is realistically impossible, what is the alternative? Experts suggest aiming not for a perfect zero but for gradually replacing what can be replaced, one item at a time. For example, swapping a plastic toothbrush for a bamboo one, or a plastic bag for a reusable tote. Their explanation is that small practices, added together, can drive change not only in personal consumption habits but also in how companies produce goods.",
    questions: [
      { question_en: "What did the plastic-free day experiment reveal?", options: ["Plastic no longer exists in most products", "It was easier than expected", "Plastic is easy to avoid entirely", "Plastic is deeply embedded in everyday life"], answerIndex: 3 },
      { question_en: "What approach do experts suggest instead of aiming for zero plastic?", options: ["Buying only imported goods", "Waiting for government bans", "Giving up on any change", "Gradually replacing items one at a time"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "패스트 패션의 그림자",
    title_en: "The shadow of fast fashion",
    body_kr: "저렴한 가격에 최신 유행을 반영한 옷을 빠르게 선보이는 패스트 패션은 소비자들에게 큰 인기를 끌어 왔다. 그러나 그 이면에는 환경에 큰 부담을 주는 생산 방식이 자리하고 있다. 옷 한 벌을 만드는 데 상당한 물과 에너지가 소비되며, 유행이 빠르게 바뀌는 만큼 버려지는 옷의 양도 급증하고 있다. 특히 합성 섬유로 만든 옷은 세탁할 때마다 미세 플라스틱을 배출해 바다 오염의 원인이 되기도 한다. 이러한 문제가 알려지면서 옷을 오래 입고 수선해서 다시 쓰는 문화가 조금씩 확산되고 있다. 몇몇 브랜드는 헌 옷을 수거해 재활용하는 프로그램을 운영하며 이미지를 개선하려 하지만 실질적인 효과는 크지 않다는 비판도 있다. 전문가들은 근본적인 해법은 결국 소비자가 옷을 사는 속도를 늦추는 것이라고 말한다. 유행을 좇기보다 오래 입을 수 있는 옷을 신중하게 고르는 태도가 필요한 시점이다.",
    body_en: "Fast fashion, which quickly delivers trendy clothes at low prices, has been hugely popular with consumers. But behind it lies a production method that places a heavy burden on the environment. Making a single garment consumes significant water and energy, and as trends change rapidly, the volume of discarded clothing is surging. Clothes made of synthetic fiber, in particular, release microplastics with every wash, contributing to ocean pollution. As this problem has become known, a culture of wearing clothes longer and mending them for reuse is slowly spreading. Some brands run programs collecting old clothes for recycling to improve their image, but critics say the actual impact is limited. Experts say the fundamental solution is for consumers to slow the pace at which they buy clothes. Rather than chasing trends, it is time to choose clothes carefully with long-term wear in mind.",
    questions: [
      { question_en: "What environmental problem is linked to synthetic fiber clothing in the passage?", options: ["It releases microplastics when washed", "It never wears out", "It cannot be dyed", "It uses no water to produce"], answerIndex: 0 },
      { question_en: "What do experts say is the fundamental solution to fast fashion's problems?", options: ["Banning all clothing production", "Slowing the pace at which consumers buy clothes", "Making all clothes synthetic", "Increasing advertising for new trends"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "도시 양봉이 늘어나는 이유",
    title_en: "Why urban beekeeping is on the rise",
    body_kr: "최근 도시 옥상이나 공원에서 벌통을 발견하는 일이 낯설지 않게 되었다. 도시 양봉이라 불리는 이 활동은 꿀을 얻기 위한 목적을 넘어 생태계 보호라는 의미를 지닌다. 전 세계적으로 꿀벌 개체 수가 급격히 줄어들고 있는데, 이는 농작물 수분에 큰 차질을 빚을 수 있는 심각한 문제다. 흥미롭게도 일부 연구는 오히려 도시가 살충제 사용이 적고 다양한 꽃이 자라는 환경 덕분에 벌들에게 더 안전한 서식지가 될 수 있다고 밝혔다. 이에 여러 지자체와 기업들이 옥상에 벌통을 설치하는 프로젝트를 지원하고 나섰다. 다만 도심 양봉이 늘면서 이웃 주민들과의 갈등이나 안전 문제도 함께 제기되고 있다. 전문가들은 적절한 거리 유지와 교육을 통해 이런 우려를 충분히 해소할 수 있다고 말한다. 도시 양봉은 사람과 자연이 공존하는 새로운 방식으로 주목받고 있다.",
    body_en: "Finding beehives on city rooftops or in parks has become a familiar sight. Urban beekeeping, as this activity is called, carries meaning beyond simply harvesting honey — it is tied to ecosystem protection. Bee populations are declining sharply worldwide, a serious problem that could severely disrupt crop pollination. Interestingly, some studies show that cities, with less pesticide use and diverse flowering plants, can actually be safer habitats for bees. In response, several municipalities and companies have begun supporting projects to install beehives on rooftops. However, as urban beekeeping increases, conflicts with neighbors and safety concerns have also been raised. Experts say maintaining proper distance and providing education can sufficiently address such concerns. Urban beekeeping is drawing attention as a new way for people and nature to coexist.",
    questions: [
      { question_en: "According to some studies, why might cities be safer habitats for bees?", options: ["Cities are colder than rural areas", "Cities have no flowers at all", "Cities have more pesticide use", "Cities have less pesticide use and diverse flowers"], answerIndex: 3 },
      { question_en: "What concerns have arisen alongside the rise of urban beekeeping?", options: ["Conflicts with neighbors and safety concerns", "A shortage of rooftops", "Falling honey prices", "Declining interest from companies"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "빗물을 모으는 도시 설계",
    title_en: "Urban design that collects rainwater",
    body_kr: "갑작스러운 폭우로 도로가 잠기는 일이 잦아지면서 도시의 빗물 관리 방식에 대한 관심이 높아지고 있다. 전통적인 배수 시설만으로는 늘어난 강우량을 감당하기 어렵다는 지적이 이어지면서 대안으로 주목받는 것이 이른바 스펀지 도시 개념이다. 이는 도로와 건물 사이에 식물과 흙으로 이루어진 공간을 마련해 빗물이 땅속으로 자연스럽게 스며들도록 하는 설계 방식이다. 빗물 정원이나 투수성 포장재도 같은 원리로 활용된다. 이런 방식은 홍수 위험을 줄일 뿐 아니라 모인 빗물을 저장했다가 가뭄철에 재사용할 수 있다는 장점도 있다. 여러 도시가 이 개념을 도입해 공원과 도로를 새롭게 설계하고 있다. 다만 기존 도시 구조를 바꾸는 데는 막대한 예산과 시간이 필요하다는 현실적인 어려움도 존재한다. 전문가들은 장기적인 관점에서 단계적으로 접근하는 것이 현실적인 해법이라고 조언한다.",
    body_en: "As sudden downpours increasingly flood roads, interest in how cities manage rainwater is growing. With traditional drainage systems struggling to handle heavier rainfall, the so-called sponge city concept has drawn attention as an alternative. It is a design approach that creates plant- and soil-filled spaces between roads and buildings, letting rainwater naturally seep into the ground. Rain gardens and permeable pavement work on the same principle. This approach not only reduces flood risk but also allows collected rainwater to be stored and reused during droughts. Several cities have adopted this concept in redesigning parks and roads. However, practical difficulties remain, since transforming existing urban structures requires enormous budgets and time. Experts advise that a phased, long-term approach is the realistic solution.",
    questions: [
      { question_en: "What is the sponge city concept designed to do?", options: ["Eliminate all green spaces", "Speed up drainage into rivers only", "Increase paved surfaces citywide", "Let rainwater naturally seep into the ground"], answerIndex: 3 },
      { question_en: "What difficulty do experts note about adopting the sponge city concept?", options: ["It works only in small towns", "It has already been fully adopted everywhere", "It requires no funding", "It requires enormous budgets and time"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "탄소 라벨을 붙이는 식품들",
    title_en: "Food products getting carbon labels",
    body_kr: "슈퍼마켓 진열대에서 제품의 탄소 배출량을 숫자로 표시한 라벨을 발견하는 일이 점점 늘고 있다. 이러한 탄소 라벨은 제품이 생산되고 유통되는 전 과정에서 발생한 온실가스 양을 소비자에게 알려 주는 역할을 한다. 도입 취지는 소비자가 정보를 바탕으로 더 친환경적인 선택을 하도록 돕는 데 있다. 실제로 라벨을 도입한 이후 상대적으로 탄소 배출량이 적은 제품의 판매량이 늘었다는 조사 결과도 나왔다. 다만 모든 제품의 탄소 배출량을 정확하게 측정하고 비교하는 일이 쉽지 않다는 현실적인 어려움도 존재한다. 원재료의 산지나 가공 방식에 따라 배출량 차이가 크기 때문에 기준을 통일하는 작업 자체가 복잡하다는 것이다. 일부 기업은 이런 복잡함을 이용해 자사에 유리한 방식으로만 배출량을 계산한다는 비판도 받는다. 전문가들은 신뢰할 수 있는 국제 기준을 마련하는 것이 탄소 라벨 제도가 자리 잡기 위한 선결 과제라고 지적한다.",
    body_en: "It is increasingly common to find labels displaying a product's carbon emissions as a number on supermarket shelves. Such carbon labels are meant to inform consumers of the amount of greenhouse gas generated throughout a product's production and distribution. The intent behind introducing them is to help consumers make more eco-friendly choices based on information. Indeed, surveys show that sales of relatively lower-carbon products rose after such labels were introduced. However, practical difficulties exist, since accurately measuring and comparing carbon emissions across all products is not easy. Because emissions vary greatly depending on the origin of raw materials or processing methods, unifying standards is itself a complex task. Some companies are also criticized for exploiting this complexity to calculate emissions in ways that favor themselves. Experts point out that establishing trustworthy international standards is a prerequisite for the carbon labeling system to take root.",
    questions: [
      { question_en: "What is the purpose of carbon labels, according to the passage?", options: ["To hide emissions information", "To promote only imported goods", "To help consumers make more eco-friendly choices", "To raise product prices"], answerIndex: 2 },
      { question_en: "What difficulty is mentioned regarding carbon labels?", options: ["All products have identical emissions", "No company wants to use them", "Consumers ignore them completely", "Measuring and comparing emissions accurately is not easy"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "리페어 카페의 등장",
    title_en: "The rise of repair cafes",
    body_kr: "고장 난 물건을 고치기보다 새로 사는 것이 익숙해진 시대에 물건을 함께 고쳐 주는 리페어 카페라는 공간이 조금씩 늘어나고 있다. 자원봉사자들이 전자제품이나 가구, 의류를 무료로 수리해 주는 이 공간은 유럽에서 처음 시작되어 여러 나라로 확산되었다. 참가자들은 단순히 물건을 고치는 것을 넘어 수리 과정을 직접 배우고 물건을 오래 쓰는 태도를 익히게 된다. 이는 대량 생산과 소비가 낳은 자원 낭비 문제에 대한 작은 대안으로 주목받고 있다. 리페어 카페를 운영하는 이들은 물건에 대한 애착이 소비를 줄이는 가장 효과적인 방법이라고 설명한다. 정든 물건을 고쳐서 계속 쓰는 경험이 새것을 사는 것과는 다른 만족감을 준다는 것이다. 일부 지자체는 이러한 활동을 지원하기 위해 공간과 예산을 제공하기도 한다. 리페어 카페는 작은 실천이지만 소비 중심 사회에 던지는 질문이라는 점에서 의미가 크다는 평가를 받는다.",
    body_en: "In an era when buying something new has become more common than repairing what is broken, spaces called repair cafes, where people fix items together, are slowly increasing. Started in Europe and spreading to other countries, these spaces have volunteers repair electronics, furniture, and clothing for free. Participants go beyond simply having something fixed, learning the repair process themselves and developing a habit of using items for longer. This is drawing attention as a small alternative to the resource waste problem caused by mass production and consumption. Those who run repair cafes explain that attachment to one's belongings is the most effective way to reduce consumption. The experience of repairing a cherished item and continuing to use it, they say, brings a different kind of satisfaction than buying something new. Some local governments provide space and budget to support such activities. Repair cafes are seen as significant, small as the practice may be, for posing a question to a consumption-centered society.",
    questions: [
      { question_en: "Where did repair cafes originally start, according to the passage?", options: ["Europe", "Africa", "South America", "Asia"], answerIndex: 0 },
      { question_en: "What do repair cafe organizers say is the most effective way to reduce consumption?", options: ["Increasing advertising", "Lowering prices on new goods", "Attachment to one's belongings", "Banning repairs entirely"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "케이팝은 어떻게 세계를 사로잡았나",
    title_en: "How K-pop captured the world",
    body_kr: "몇 년 전만 해도 케이팝은 아시아 일부 지역의 하위문화로 여겨졌지만 지금은 전 세계 음악 차트를 장악하는 주류 문화가 되었다. 이러한 성공의 배경에는 철저하게 계산된 제작 시스템이 자리하고 있다는 분석이 많다. 기획사들은 수년에 걸친 연습생 훈련을 통해 노래와 춤, 외국어 실력까지 갖춘 완성형 아이돌을 길러 낸다. 여기에 소셜 미디어를 활용한 팬덤과의 실시간 소통이 더해지면서 국경을 넘는 강력한 팬 문화가 형성되었다. 팬들은 단순한 소비자를 넘어 콘텐츠를 함께 만들고 퍼뜨리는 적극적인 참여자 역할을 한다. 일부 비평가들은 이런 시스템이 지나치게 상업적이며 아티스트 개인의 개성을 억누른다고 비판하기도 한다. 그럼에도 불구하고 케이팝이 보여 준 글로벌 성공 방식은 다른 나라 엔터테인먼트 산업에도 큰 영향을 미치고 있다.",
    body_en: "Just a few years ago, K-pop was considered a subculture confined to parts of Asia, but it has now become a mainstream force dominating music charts worldwide. Many analysts trace this success to a thoroughly calculated production system. Entertainment agencies train trainees for years to produce fully formed idols skilled in singing, dancing, and even foreign languages. Combined with real-time communication with fandoms through social media, this has formed a powerful fan culture that crosses borders. Fans act not merely as consumers but as active participants who help create and spread content. Some critics argue this system is overly commercial and suppresses individual artists' personalities. Nevertheless, the global success formula K-pop has demonstrated is having a significant influence on entertainment industries in other countries.",
    questions: [
      { question_en: "What is cited as a key factor behind K-pop's global success?", options: ["Reliance on foreign producers only", "Avoiding social media entirely", "A lack of any training system", "A calculated, years-long trainee production system"], answerIndex: 3 },
      { question_en: "What criticism do some critics raise about the K-pop system?", options: ["It suppresses individual artists' personalities", "It has no international reach", "It ignores fans completely", "It is not commercial enough"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "웹툰이 바꾼 만화 산업의 지형",
    title_en: "How webtoons reshaped the comics industry",
    body_kr: "스마트폰 화면에 맞춰 세로로 넘기며 보는 웹툰은 이제 한국을 넘어 전 세계 독자들에게 익숙한 콘텐츠가 되었다. 전통적인 만화가 종이책이나 잡지 형태로 유통되었던 것과 달리 웹툰은 처음부터 디지털 환경에 맞게 설계되었다. 이런 형식적 차이는 단순한 매체 전환을 넘어 이야기를 전달하는 방식 자체를 바꾸어 놓았다. 한 화면에서 다음 화면으로 넘어가는 순간의 긴장감을 이용한 연출이 대표적인 예다. 또한 무료로 먼저 공개하고 이후 회차부터 유료로 전환하는 방식은 독자층을 빠르게 넓히는 데 크게 기여했다. 인기를 얻은 웹툰은 드라마나 영화로 제작되며 원작의 흥행을 다른 매체로 확장하는 경우도 흔해졌다. 다만 빠른 연재 속도로 인한 작가들의 노동 강도가 지나치다는 지적도 꾸준히 제기되고 있다. 웹툰 산업이 계속 성장하려면 창작자의 처우 개선이라는 과제도 함께 풀어야 한다는 목소리가 커지고 있다.",
    body_en: "Webtoons, read by scrolling vertically on a smartphone screen, have become familiar content to readers worldwide, not just in Korea. Unlike traditional comics distributed as paper books or magazines, webtoons were designed from the start for the digital environment. This formal difference has changed not just the medium but the very way stories are told. A prime example is directing that uses the tension of the moment one screen transitions to the next. The practice of releasing early chapters free and switching to paid access later also greatly contributed to rapidly expanding the reader base. Popular webtoons are often adapted into dramas or films, extending the original's success into other media. However, criticism has persistently been raised that the fast serialization pace places excessive strain on creators. There is a growing call that for the webtoon industry to keep growing, improving creators' working conditions must also be addressed.",
    questions: [
      { question_en: "How did webtoons change storytelling, according to the passage?", options: ["By using the tension of screen-to-screen transitions", "By requiring print publication", "By eliminating dialogue", "By removing all images"], answerIndex: 0 },
      { question_en: "What ongoing concern is raised about the webtoon industry?", options: ["A lack of adaptations into other media", "Declining smartphone use", "Too few readers worldwide", "Excessive strain on creators from fast serialization"], answerIndex: 3 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "숏폼 콘텐츠에 익숙해진 뇌",
    title_en: "A brain accustomed to short-form content",
    body_kr: "몇 초 만에 다음 영상으로 넘어가는 숏폼 콘텐츠가 일상의 큰 부분을 차지하게 되었다. 짧고 자극적인 영상에 익숙해질수록 긴 글이나 영화처럼 느린 호흡의 콘텐츠에 집중하기가 점점 어려워진다는 우려가 나온다. 전문가들은 이런 현상을 주의력 지속 시간의 감소와 연관 지어 설명한다. 뇌가 빠른 보상에 익숙해지면 상대적으로 느린 즐거움에는 반응이 둔해진다는 것이다. 실제로 영화관에서 두 시간 동안 집중하기 힘들어졌다고 말하는 사람들이 늘고 있다는 조사도 있다. 이런 흐름에 발맞춰 콘텐츠 제작자들도 점점 더 짧고 자극적인 구성을 선호하게 되면서 악순환이 생긴다는 지적도 있다. 다만 모든 전문가가 부정적으로만 보는 것은 아니다. 짧은 형식이 오히려 정보 습득을 효율적으로 만든다는 반론도 존재하며, 결국 중요한 것은 형식 자체보다 균형 있게 소비하는 태도라는 데 의견이 모인다.",
    body_en: "Short-form content, which shifts to the next video within seconds, now occupies a large part of daily life. Concerns are growing that as people grow accustomed to short, stimulating videos, it becomes increasingly hard to focus on slower-paced content like long articles or films. Experts link this phenomenon to a decline in attention span. Once the brain grows used to fast rewards, it becomes relatively dull to slower forms of enjoyment, they explain. Surveys indeed show a growing number of people saying they find it hard to stay focused for two hours in a movie theater. Some point out that a vicious cycle forms as content creators, following this trend, increasingly favor shorter, more stimulating formats. Not all experts view this negatively, however. There is a counterargument that short formats actually make absorbing information more efficient, and opinion converges that what matters, in the end, is not the format itself but a balanced way of consuming it.",
    questions: [
      { question_en: "What do experts link the rise of short-form content to?", options: ["A decline in attention span", "Better focus in movie theaters", "An increase in attention span", "Higher literacy rates"], answerIndex: 0 },
      { question_en: "What do experts ultimately agree matters most?", options: ["A balanced approach to consuming content", "Only watching long-form content", "Ignoring the issue completely", "Banning short-form content entirely"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "팬덤 문화의 양면성",
    title_en: "The two sides of fandom culture",
    body_kr: "좋아하는 연예인이나 작품을 향한 애정을 넘어 하나의 문화 현상으로 자리 잡은 팬덤은 오늘날 대중문화 산업에서 무시할 수 없는 영향력을 지닌다. 팬들은 음반과 공연 티켓을 구매하는 것을 넘어 관련 콘텐츠를 직접 제작하고 확산시키며 산업의 성장을 견인한다. 기획사와 제작사들도 이런 팬덤의 힘을 인식하고 팬과의 소통을 마케팅 전략의 핵심으로 삼는다. 그러나 팬덤 문화에는 그늘도 존재한다. 특정 팬덤 사이의 과도한 경쟁이 온라인상의 갈등으로 번지는 경우가 잦고, 좋아하는 대상에 대한 비판을 전혀 용납하지 않는 배타적인 태도가 문제로 지적되기도 한다. 일부 전문가들은 이러한 현상이 소속감을 향한 인간의 본능적 욕구와 맞닿아 있다고 분석한다. 결국 팬덤 문화가 건강하게 유지되려면 애정과 비판이 공존할 수 있는 여지를 남겨 두는 태도가 필요하다는 지적이 나온다.",
    body_en: "Fandom, which has grown beyond simple affection for a favorite celebrity or work into a cultural phenomenon in its own right, now wields influence in the popular culture industry that cannot be ignored. Fans go beyond buying albums and concert tickets to directly creating and spreading related content, driving the industry's growth. Agencies and production companies, recognizing the power of fandom, make communication with fans a core marketing strategy. But fandom culture has a darker side too. Excessive competition between certain fandoms often spills into online conflict, and an exclusionary attitude that tolerates no criticism of the object of affection is also pointed out as a problem. Some experts analyze this phenomenon as tied to a basic human desire for belonging. Ultimately, there is a call that for fandom culture to remain healthy, it needs to leave room for affection and criticism to coexist.",
    questions: [
      { question_en: "How do fans contribute to industry growth, according to the passage?", options: ["By only buying tickets and never doing anything else", "By discouraging others from joining", "By avoiding all social media", "By creating and spreading related content themselves"], answerIndex: 3 },
      { question_en: "What darker side of fandom culture is mentioned?", options: ["Too much tolerance for criticism", "A complete lack of communication with agencies", "Excessive competition leading to online conflict", "Declining ticket sales"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "역주행이라는 신기한 현상",
    title_en: "The curious phenomenon of chart comebacks",
    body_kr: "발매 당시에는 큰 주목을 받지 못했던 노래가 몇 년이 지난 뒤 갑자기 인기 차트 상위권에 오르는 현상을 역주행이라고 부른다. 과거에는 상상하기 어려웠던 이런 현상은 온라인 플랫폼과 소셜 미디어의 발달로 가능해졌다. 짧은 영상 속 배경 음악으로 우연히 쓰인 곡이 입소문을 타면서 재조명되는 경우가 대표적이다. 이는 음악을 소비하는 방식이 방송이나 음반 발매 시점 중심에서 벗어나 훨씬 유동적으로 변했다는 것을 보여 준다. 기획사들도 이런 흐름을 인식하고 오래된 곡의 저작권을 관리하거나 재발매를 시도하는 등 새로운 전략을 세우고 있다. 흥미로운 점은 역주행한 곡의 성공이 반드시 원곡 가수에게만 이익을 주는 것은 아니라는 사실이다. 곡을 활용한 콘텐츠 제작자와 플랫폼 역시 함께 수혜를 입는 구조가 형성된다. 역주행 현상은 대중음악 산업에서 시간의 개념이 예전과는 완전히 달라졌음을 보여 주는 상징적인 사례로 평가받는다.",
    body_en: "The phenomenon in which a song that drew little attention upon release suddenly climbs the charts years later is called a \"chart comeback\" or reverse rise. Once unimaginable, this phenomenon has become possible thanks to online platforms and social media. A common example is a song used by chance as background music in a short video, gaining renewed attention as it goes viral. This shows that how people consume music has become far more fluid, moving away from being centered on broadcasts or release dates. Agencies, recognizing this trend, are devising new strategies such as managing the rights to old songs or attempting rereleases. Interestingly, the success of a chart comeback does not necessarily benefit only the original artist. A structure forms in which content creators and platforms that used the song also share in the benefit. The phenomenon is regarded as a symbolic case showing that the concept of time in the pop music industry has completely changed from before.",
    questions: [
      { question_en: "What has enabled the 'chart comeback' phenomenon, according to the passage?", options: ["Radio broadcasts only", "Online platforms and social media", "Government music policy", "Vinyl record sales"], answerIndex: 1 },
      { question_en: "Who benefits from a song's chart comeback, according to the passage?", options: ["Only the platform, never the artist", "No one benefits financially", "The original artist as well as content creators and platforms", "Only the original artist"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "정서 노동을 하는 콘텐츠 크리에이터",
    title_en: "Content creators performing emotional labor",
    body_kr: "밝고 긍정적인 모습으로 시청자들을 만나는 인터넷 방송인이나 유튜버의 일상은 화면 밖에서 보이는 것과 크게 다를 수 있다. 전문가들은 이들이 겪는 심리적 부담을 정서 노동이라는 개념으로 설명한다. 실제 감정과 무관하게 시청자가 기대하는 밝은 이미지를 지속적으로 연기해야 하기 때문이다. 특히 실시간 방송이라는 특성상 이런 감정 관리는 쉬는 시간 없이 이어지는 경우가 많다. 여기에 더해 조회수와 구독자 수라는 수치로 성과가 끊임없이 평가되는 환경은 이들의 스트레스를 가중시킨다. 악성 댓글에 지속적으로 노출되는 것도 큰 부담으로 작용한다. 최근 몇몇 크리에이터들이 번아웃을 이유로 활동을 중단하며 이 문제가 새삼 주목받았다. 업계에서는 창작자의 정신 건강을 지원하는 제도적 장치가 필요하다는 목소리가 커지고 있다.",
    body_en: "The daily lives of internet broadcasters or YouTubers who appear bright and positive on screen can differ greatly from what viewers see. Experts explain the psychological burden they experience through the concept of emotional labor. This is because they must continuously perform the upbeat image viewers expect, regardless of their actual feelings. Given the nature of live broadcasting in particular, such emotional management often continues without breaks. On top of that, an environment where performance is constantly evaluated through numbers like view counts and subscriber counts adds to their stress. Continuous exposure to hateful comments is also a major burden. The issue drew renewed attention recently when several creators paused their activities, citing burnout. Voices in the industry are growing louder calling for institutional support systems for creators' mental health.",
    questions: [
      { question_en: "How do experts describe the psychological burden faced by content creators?", options: ["Manual labor", "Physical labor", "Emotional labor", "No burden at all"], answerIndex: 2 },
      { question_en: "What recent event drew renewed attention to this issue?", options: ["Several creators pausing activities due to burnout", "A rise in subscriber counts", "New broadcasting equipment being released", "Creators receiving awards"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "밈이 되는 순간",
    title_en: "The moment something becomes a meme",
    body_kr: "예능 프로그램의 우연한 한 장면이나 평범한 사람의 짧은 영상이 어느 순간 폭발적으로 퍼지며 밈이 되는 경우를 흔히 볼 수 있다. 흥미로운 점은 정작 제작진이나 출연자가 의도하지 않은 순간이 밈이 되는 경우가 훨씬 많다는 것이다. 전문가들은 예측 불가능성과 공감 가능성이 결합될 때 밈이 탄생할 확률이 높아진다고 분석한다. 지나치게 완벽하게 계산된 장면보다 어딘가 어색하거나 과장된 순간이 오히려 사람들의 흥미를 끈다는 것이다. 밈이 확산되는 과정에서 원래의 맥락은 사라지고 전혀 다른 의미로 재해석되는 경우도 많다. 이 때문에 밈의 대상이 된 인물이 예상치 못한 관심에 부담을 느끼는 부작용도 발생한다. 최근에는 기업들도 이런 밈 문화를 마케팅에 적극적으로 활용하며 대중과 소통하려는 시도를 이어가고 있다. 다만 억지로 밈을 만들려는 시도는 대개 성공하지 못한다는 것이 업계의 공통된 경험이다.",
    body_en: "It is common to see an accidental scene from an entertainment show or a short clip of an ordinary person suddenly spread explosively and become a meme. Interestingly, moments that become memes are far more often ones the production crew or performers never intended. Experts analyze that a meme is more likely to be born when unpredictability combines with relatability. An awkward or exaggerated moment, rather than a perfectly calculated scene, tends to draw people's interest instead. As a meme spreads, its original context often disappears and gets reinterpreted with an entirely different meaning. This causes a side effect in which the person who becomes the subject of a meme feels burdened by unexpected attention. Recently, companies too have been actively using this meme culture in marketing, continuing attempts to communicate with the public. However, it is a common experience across the industry that forced attempts to manufacture a meme usually fail.",
    questions: [
      { question_en: "What combination increases the likelihood of something becoming a meme, according to experts?", options: ["Celebrity status and wealth", "Unpredictability and relatability", "Long duration and formal tone", "Perfect planning and high budget"], answerIndex: 1 },
      { question_en: "What is the industry's common experience regarding forced attempts to create memes?", options: ["They usually fail", "They require government approval", "They usually succeed easily", "They always go viral instantly"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "왜 우리는 무서운 영화를 찾아볼까",
    title_en: "Why do we seek out scary movies?",
    body_kr: "심장이 뛰고 손에 땀이 나는 공포 영화를 굳이 찾아보는 사람들의 심리는 얼핏 이해하기 어려워 보인다. 심리학자들은 이러한 행동을 안전한 두려움을 즐기려는 욕구로 설명한다. 실제 위험은 없지만 몸은 진짜 위기 상황처럼 반응하면서 아드레날린이 분비되고, 영화가 끝나면 안도감과 함께 쾌감을 느끼게 된다는 것이다. 이 과정은 롤러코스터를 타는 즐거움과 비슷한 원리로 설명되기도 한다. 흥미로운 점은 이런 자극을 선호하는 정도가 사람마다 크게 다르다는 것이다. 새로운 자극을 추구하는 성향이 강한 사람일수록 공포 영화에서 더 큰 즐거움을 느낀다는 연구 결과도 있다. 또한 여럿이 함께 무서운 장면을 견디는 경험이 사회적 유대감을 강화한다는 분석도 흥미롭다. 결국 공포 영화가 꾸준히 사랑받는 이유는 안전하게 짜릿함을 경험하고 싶어 하는 인간의 본능적 욕구에 있다고 할 수 있다.",
    body_en: "The psychology of people who deliberately seek out horror movies, which make hearts race and palms sweat, seems hard to understand at first glance. Psychologists explain this behavior as a desire to enjoy safe fear. Although there is no real danger, the body reacts as if facing a genuine crisis, releasing adrenaline, and once the movie ends, people feel relief along with a sense of pleasure. This process is sometimes explained by a principle similar to the thrill of riding a roller coaster. Interestingly, the degree to which people prefer such stimulation varies greatly from person to person. Research shows that people with a stronger tendency to seek novel stimulation feel greater enjoyment from horror movies. It is also interesting to note that the shared experience of enduring scary scenes together strengthens social bonds. Ultimately, the enduring appeal of horror movies can be attributed to the human instinct to want to experience thrills safely.",
    questions: [
      { question_en: "How do psychologists explain the appeal of horror movies?", options: ["A dislike of all other genres", "A need to avoid social contact", "A wish to experience real danger", "A desire to enjoy safe fear"], answerIndex: 3 },
      { question_en: "What social effect of watching horror movies together is mentioned?", options: ["It strengthens social bonds", "It has no social effect", "It weakens friendships", "It causes permanent fear"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "알고리즘이 골라 주는 취향",
    title_en: "Taste curated by algorithms",
    body_kr: "요즘 사람들은 무엇을 볼지 스스로 고민하기보다 플랫폼이 추천하는 콘텐츠를 그대로 소비하는 경우가 많아졌다. 알고리즘은 사용자의 시청 기록을 분석해 다음에 좋아할 만한 콘텐츠를 정교하게 예측한다. 이런 편리함 덕분에 사람들은 원하는 콘텐츠를 더 쉽게 찾을 수 있게 되었다. 그러나 전문가들은 이러한 시스템이 오히려 취향의 폭을 좁힐 위험이 있다고 지적한다. 이미 좋아하는 것과 비슷한 콘텐츠만 계속 추천받다 보면 낯설고 새로운 장르를 접할 기회가 줄어든다는 것이다. 이러한 현상을 필터 버블이라고 부르며, 이는 콘텐츠 소비뿐 아니라 정보와 의견의 다양성에도 영향을 미칠 수 있다고 우려하는 목소리도 있다. 일부 플랫폼은 이런 문제를 인식하고 의도적으로 다양한 장르를 섞어서 추천하는 기능을 도입하기도 했다. 전문가들은 편리한 추천에만 의존하지 말고 가끔은 스스로 새로운 콘텐츠를 찾아보는 의식적인 노력이 필요하다고 조언한다.",
    body_en: "These days, people increasingly consume whatever content platforms recommend rather than deciding for themselves what to watch. Algorithms analyze a user's viewing history to precisely predict content they are likely to enjoy next. Thanks to this convenience, people can find the content they want more easily. Experts point out, however, that such systems risk actually narrowing the breadth of one's taste. Continuously being recommended content similar to what one already likes reduces opportunities to encounter unfamiliar, new genres. This phenomenon is called a filter bubble, and some voice concern that it can affect not just content consumption but also diversity in information and opinion. Some platforms, recognizing this problem, have introduced features that deliberately mix in diverse genres among recommendations. Experts advise not relying solely on convenient recommendations but making a conscious effort to occasionally seek out new content oneself.",
    questions: [
      { question_en: "What risk do experts associate with recommendation algorithms?", options: ["They risk narrowing the breadth of one's taste", "They increase exposure to new genres", "They make platforms too slow", "They eliminate all viewing history"], answerIndex: 0 },
      { question_en: "What is the phenomenon of being shown only similar content called?", options: ["A content bubble burst", "A genre lock", "A filter bubble", "An algorithm crash"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "귀여움이 지배하는 시장",
    title_en: "A market ruled by cuteness",
    body_kr: "캐릭터 인형이나 굿즈를 향한 사람들의 관심이 나이와 관계없이 확산되고 있다. 예전에는 어린이의 전유물로 여겨지던 귀여운 캐릭터 상품이 이제는 성인 소비자들 사이에서도 큰 인기를 끌고 있다. 전문가들은 이러한 현상을 팍팍한 현실에서 오는 위안의 욕구와 연결 지어 설명한다. 복잡하고 경쟁적인 일상 속에서 단순하고 사랑스러운 존재를 곁에 두는 것이 정서적인 안정감을 준다는 것이다. 기업들도 이러한 흐름을 읽고 성인을 겨냥한 캐릭터 컬래버레이션 상품을 앞다투어 출시하고 있다. 흥미로운 점은 이런 소비가 단순한 소장 욕구를 넘어 자신을 표현하는 수단으로 여겨진다는 것이다. 가방에 매다는 인형이나 소품을 통해 개인의 취향을 드러내는 문화가 자리 잡은 셈이다. 전문가들은 귀여움을 향한 소비가 앞으로도 다양한 산업과 결합하며 계속 성장할 것으로 내다본다.",
    body_en: "Interest in character dolls and merchandise is spreading regardless of age. Cute character products, once considered exclusive to children, are now hugely popular among adult consumers as well. Experts link this phenomenon to a desire for comfort amid a harsh reality. Keeping something simple and lovable close by provides emotional stability amid a complex, competitive daily life, they explain. Companies, reading this trend, are racing to launch character collaboration products aimed at adults. Interestingly, this kind of consumption is seen as going beyond a simple desire to collect, becoming a means of self-expression. A culture has taken root in which people reveal personal taste through dolls or accessories hung on bags. Experts predict that consumption driven by cuteness will keep growing, combining with various industries going forward.",
    questions: [
      { question_en: "How do experts explain the popularity of cute character products among adults?", options: ["As unrelated to emotions", "As a sign of declining incomes", "As purely a children's trend", "As a desire for comfort amid harsh reality"], answerIndex: 3 },
      { question_en: "What does this kind of consumption represent beyond collecting, according to the passage?", options: ["A government policy", "A form of investment", "A means of self-expression", "A required school activity"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "예측 불가능한 결말이 사랑받는 이유",
    title_en: "Why unpredictable endings are so loved",
    body_kr: "예상을 완전히 뒤엎는 결말을 가진 작품들이 오랫동안 대중의 화제로 남는 경우가 많다. 심리학자들은 이러한 현상을 인지 부조화와 관련지어 설명한다. 예상과 다른 결과를 마주했을 때 우리 뇌는 그 간극을 이해하려고 더 깊이 몰입하게 된다는 것이다. 이 과정에서 뇌는 강렬한 각성 상태를 경험하며 이것이 오래도록 기억에 남는 인상적인 경험으로 자리 잡는다. 반면 예측 가능한 결말은 편안함을 주지만 강렬한 인상을 남기기는 어렵다. 흥미로운 점은 좋은 반전이 단순히 놀라움만 주는 것이 아니라 이전 내용을 돌아보게 만든다는 것이다. 처음에는 이해되지 않았던 장면들이 결말을 알고 나서야 비로소 의미를 갖게 되는 경우가 대표적이다. 이러한 재해석의 과정 자체가 관객에게 지적인 즐거움을 준다는 것이 전문가들의 설명이다. 결국 훌륭한 반전은 단순한 충격이 아니라 이야기 전체를 다시 생각하게 만드는 힘에서 나온다.",
    body_en: "Works with endings that completely overturn expectations often remain the subject of public conversation for a long time. Psychologists explain this phenomenon in relation to cognitive dissonance. When faced with a result different from what was expected, our brain becomes more deeply engaged trying to understand the gap. In this process, the brain experiences an intense state of arousal, which becomes an impressive experience that stays in memory for a long time. A predictable ending, by contrast, offers comfort but rarely leaves a strong impression. Interestingly, a good twist does not merely surprise but also makes viewers look back on earlier content. A classic example is scenes that made no sense at first only gaining meaning once the ending is known. This process of reinterpretation itself gives the audience intellectual pleasure, experts explain. Ultimately, a great twist derives its power not from mere shock but from prompting a rethinking of the entire story.",
    questions: [
      { question_en: "How do psychologists explain the appeal of unpredictable endings?", options: ["Through a dislike of surprises", "Through the concept of cognitive dissonance", "Through random chance alone", "Through simple boredom"], answerIndex: 1 },
      { question_en: "What does a good twist do besides surprising the audience, according to the passage?", options: ["It has no lasting effect", "It ends the story abruptly with no meaning", "It makes viewers reinterpret earlier content", "It removes all earlier scenes from memory"], answerIndex: 2 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "조용한 퇴사",
    title_en: "Quiet quitting",
    body_kr: "'조용한 퇴사'라는 말이 유행하고 있다. 실제로 회사를 그만두는 것이 아니라, 맡은 일만 딱 하고 그 이상은 하지 않는 태도를 가리킨다. 이를 두고 세대 간 시각이 엇갈린다. 기성세대는 책임감의 상실로 읽는 반면, 젊은 세대는 계약한 만큼 일하는 당연한 권리라고 말한다. 흥미로운 점은 이 현상이 열심히 일해도 보상이 따라오지 않는다는 경험에서 나왔다는 것이다. 승진과 연봉이 노력과 무관하게 느껴질 때, 초과 노동을 줄이는 것은 개인에게 합리적인 선택이 된다. 결국 조용한 퇴사는 개인의 게으름이 아니라 보상 구조에 대한 신호로 읽어야 한다는 분석이 설득력을 얻고 있다.",
    body_en: "The phrase 'quiet quitting' is in fashion. It doesn't mean actually leaving a company, but doing exactly what your job requires and nothing more. Views split along generational lines: the older generation reads it as a loss of responsibility, while younger workers call it the natural right to work as much as they're contracted for. Interestingly, the phenomenon grew out of the experience that hard work doesn't bring rewards. When promotions and pay feel unrelated to effort, cutting back on extra labor becomes a rational choice for the individual. The persuasive analysis, then, is that quiet quitting should be read not as personal laziness but as a signal about the reward structure.",
    questions: [
      { question_en: "What does 'quiet quitting' actually mean?", options: ["Resigning without notice", "Doing only what the job requires", "Working from home", "Changing careers secretly"], answerIndex: 1 },
      { question_en: "What does the passage say it signals?", options: ["Personal laziness", "A problem in the reward structure", "Poor hiring", "Generational conflict only"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "카공족 논쟁",
    title_en: "The cafe-studier debate",
    body_kr: "카페에서 오랜 시간 공부하는 사람들, 이른바 '카공족'을 둘러싼 논쟁이 뜨겁다. 커피 한 잔으로 네다섯 시간씩 자리를 차지하면 회전율이 떨어져 매출에 타격을 준다는 것이 사장님들의 입장이다. 실제로 시간제한을 두거나 콘센트를 막는 카페가 늘고 있다. 반면 이용자들은 카페가 공부하기 좋은 공간으로 스스로를 홍보해 놓고 이제 와서 손님을 가려 받는 것은 모순이라고 반박한다. 도서관 좌석이 부족한 현실도 카공족을 만든 배경이다. 일부 카페는 아예 시간당 요금을 받는 '스터디 카페'로 전환해 갈등을 비즈니스 기회로 바꾸었다. 공간의 가격을 어떻게 매길 것인가라는 새로운 질문이 등장한 셈이다.",
    body_en: "The debate over 'cafe studiers' — people who study in cafes for hours — is heated. Owners argue that occupying a seat for four or five hours over a single coffee hurts turnover and revenue. Indeed, more cafes are imposing time limits or blocking outlets. Users counter that cafes marketed themselves as good places to study, so picking and choosing customers now is contradictory. The shortage of library seats is also part of what created cafe studiers. Some cafes have converted into hourly-rate 'study cafes,' turning the conflict into a business opportunity. A new question has emerged: how do you price space itself?",
    questions: [
      { question_en: "Why do owners object to cafe studiers?", options: ["They are noisy", "Low turnover hurts revenue", "They break furniture", "They order too much"], answerIndex: 1 },
      { question_en: "How did some cafes turn the conflict into opportunity?", options: ["Banning laptops", "Becoming hourly-rate study cafes", "Raising coffee prices", "Closing earlier"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "구독의 함정",
    title_en: "The subscription trap",
    body_kr: "음악, 영화, 배송, 심지어 면도날까지 구독하는 시대다. 구독 경제는 소유보다 접근을 판다. 한 달에 만 원이라는 가격은 가볍게 느껴지지만, 서비스가 쌓이면 이야기가 달라진다. 한 조사에 따르면 사람들은 자신의 구독료 총액을 실제보다 삼십 퍼센트 이상 적게 추정한다고 한다. 해지를 어렵게 만드는 설계도 문제다. 가입은 클릭 한 번이지만 해지는 전화 상담을 거쳐야 하는 서비스가 여전히 많다. 전문가들은 분기마다 구독 목록을 점검하고, 마지막으로 사용한 날짜를 기준으로 정리하라고 조언한다. 편리함에는 값이 있고, 그 값은 무관심 속에서 계속 청구된다.",
    body_en: "We now subscribe to music, movies, deliveries, even razor blades. The subscription economy sells access rather than ownership. Ten thousand won a month feels light, but the story changes as services pile up. According to one survey, people underestimate their total subscription spending by more than thirty percent. Designs that make cancelling hard are another problem: signing up takes one click, but many services still require a phone call to quit. Experts advise reviewing your subscription list every quarter and cutting based on when you last used each service. Convenience has a price, and that price keeps getting charged amid our inattention.",
    questions: [
      { question_en: "By how much do people underestimate their subscription spending?", options: ["About 10%", "More than 30%", "About 50%", "They overestimate it"], answerIndex: 1 },
      { question_en: "What do experts advise?", options: ["Cancel everything", "Review the list quarterly by last-used date", "Use only free services", "Share accounts"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "왜 한국어에는 호칭이 많을까",
    title_en: "Why Korean has so many terms of address",
    body_kr: "한국어를 배우는 외국인이 가장 놀라는 것 중 하나는 호칭의 다양함이다. 언니, 누나, 오빠, 형은 성별과 화자에 따라 갈리고, 직장에서는 이름 대신 '과장님', '팀장님' 같은 직함이 이름을 대신한다. 심지어 식당에서 모르는 사람을 '이모님'이라고 부르기도 한다. 이런 호칭 체계는 관계와 서열을 중시해 온 문화가 언어에 새겨진 결과다. 호칭을 정해야 대화를 시작할 수 있기 때문에, 처음 만난 사이에 나이를 묻는 관습도 여기서 나왔다. 최근에는 수평적인 문화를 위해 직급 호칭을 없애고 '님'이나 영어 이름을 쓰는 회사도 늘고 있다. 언어가 문화를 담는다면, 호칭의 변화는 한국 사회의 변화를 보여 주는 창이라고 할 수 있다.",
    body_en: "One of the things that most surprises foreign learners of Korean is the variety of terms of address. Eonni, nuna, oppa, and hyeong split by gender of both speaker and addressee, and at work, titles like 'Manager Kim' replace names entirely. People even call restaurant staff they've never met 'imo' (aunt). This system of address is culture — one that prized relationships and hierarchy — inscribed into language. Because you must settle on a term of address before conversation can begin, the custom of asking someone's age on first meeting grew from this too. Recently, more companies are dropping rank-based titles in favor of a plain 'nim' or English names to build flatter cultures. If language carries culture, the changing address system is a window into a changing Korean society.",
    questions: [
      { question_en: "Why do Koreans often ask someone's age on first meeting?", options: ["Simple curiosity", "To settle on the right term of address", "It's required by law", "To plan birthdays"], answerIndex: 1 },
      { question_en: "What are some companies doing recently?", options: ["Adding more titles", "Dropping rank titles for 'nim' or English names", "Banning small talk", "Requiring formal speech"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "냉장고를 부탁해",
    title_en: "Trusting the fridge",
    body_kr: "일주일에 한 번 장을 보는데도 냉장고에서 버리는 음식이 자꾸 나온다면, 문제는 장보기가 아니라 냉장고 관리에 있을 가능성이 크다. 전문가들은 냉장고를 '보관함'이 아니라 '순환하는 공간'으로 봐야 한다고 말한다. 실천법은 의외로 단순하다. 첫째, 새로 산 것은 뒤에 넣고 오래된 것을 앞으로 당긴다. 둘째, 일주일에 한 번 '냉장고 파먹기' 날을 정해 장을 보지 않고 남은 재료로만 요리한다. 셋째, 냉동실의 음식에는 반드시 날짜를 적는다. 냉동실은 시간이 멈추는 곳이 아니라 천천히 흐르는 곳이기 때문이다. 이 세 가지만 지켜도 음식물 쓰레기가 눈에 띄게 줄어든다. 가계부와 환경, 둘 다에 이로운 습관이다.",
    body_en: "If you shop once a week yet keep throwing food out of the fridge, the problem is likely fridge management, not shopping. Experts say we should treat the refrigerator not as a storage box but as a space of circulation. The practices are surprisingly simple. First, put new purchases at the back and pull older items forward. Second, set one 'fridge-emptying' day a week: skip shopping and cook only with what's left. Third, always date what goes into the freezer — the freezer isn't where time stops, only where it flows slowly. Just these three habits visibly cut food waste. It's a habit that benefits both your budget and the environment.",
    questions: [
      { question_en: "How should the fridge be viewed?", options: ["As a storage box", "As a space of circulation", "As a freezer", "As a pantry"], answerIndex: 1 },
      { question_en: "What is a 'fridge-emptying' day?", options: ["Deep-cleaning the fridge", "Cooking only with what's left, no shopping", "Defrosting day", "Grocery delivery day"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "운동을 계속하게 만드는 것",
    title_en: "What keeps people exercising",
    body_kr: "새해마다 헬스장은 붐비지만 삼 월이 되면 절반이 사라진다. 무엇이 운동을 계속하게 만들까. 연구들은 의지력보다 환경 설계가 중요하다고 입을 모은다. 목표를 '살 빼기'처럼 결과로 잡으면 성과가 보이지 않는 순간 포기하기 쉽다. 반면 '화요일과 목요일 저녁 일곱 시'처럼 시간과 장소로 잡으면 지속률이 크게 올라간다. 함께 운동하는 동료의 존재도 강력하다. 약속이 생기면 빠지기 어렵기 때문이다. 흥미롭게도 운동 강도는 지속과 큰 관련이 없었다. 힘든 운동보다 '내일 또 하고 싶은 정도'의 운동이 습관을 만든다. 결국 운동을 계속하는 사람들은 의지가 강한 사람이 아니라, 포기하기 어려운 구조를 만든 사람들이다.",
    body_en: "Gyms are packed every new year, but by March half the crowd is gone. What keeps people exercising? Studies agree that environment design matters more than willpower. Frame your goal as an outcome, like 'losing weight,' and you'll quit the moment results stall. Frame it as a time and place — 'Tuesday and Thursday at 7 p.m.' — and persistence jumps. A workout partner is powerful too: it's hard to skip an appointment. Interestingly, intensity had little to do with persistence. Habits are built not by grueling workouts but by exercise you'd 'want to do again tomorrow.' In the end, the people who keep exercising aren't the strong-willed — they're the ones who built a structure that's hard to quit.",
    questions: [
      { question_en: "Which goal framing works better?", options: ["Outcome goals like losing weight", "Time-and-place goals", "Intensity goals", "Money-based goals"], answerIndex: 1 },
      { question_en: "What relation did intensity have to persistence?", options: ["Harder is better", "Little relation", "Only easy workouts last", "It matters most"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "칭찬의 기술",
    title_en: "The art of praise",
    body_kr: "칭찬은 고래도 춤추게 한다지만, 어떤 칭찬은 오히려 독이 된다. 심리학 연구에 따르면 '넌 머리가 좋구나'처럼 재능을 칭찬받은 아이들은 이후 어려운 과제를 피하는 경향을 보였다. 실패하면 재능이 없다는 증거가 될까 봐 두려운 것이다. 반면 '끝까지 고민한 방법이 좋았어'처럼 과정을 칭찬받은 아이들은 더 어려운 과제에 도전했다. 이 원리는 어른에게도 적용된다. 동료의 발표를 칭찬할 때 '역시 발표를 잘해'보다 '자료 구성을 바꾼 게 효과적이었어'가 더 힘이 된다. 좋은 칭찬은 상대를 평가하는 것이 아니라, 상대가 한 선택을 알아봐 주는 것이다.",
    body_en: "They say praise makes even whales dance, but some praise is poison. Psychology research found that children praised for talent — 'you're so smart' — later tended to avoid difficult tasks, fearing that failure would prove they lacked talent. Children praised for process — 'I liked how you kept working through it' — took on harder challenges. The principle applies to adults too. When praising a colleague's presentation, 'the way you restructured the material was effective' lands better than 'you're always good at presenting.' Good praise doesn't evaluate the person; it recognizes the choices they made.",
    questions: [
      { question_en: "What happened to children praised for talent?", options: ["They tried harder tasks", "They avoided difficult tasks", "They ignored praise", "They praised others"], answerIndex: 1 },
      { question_en: "What does good praise do?", options: ["Evaluates the person", "Recognizes the person's choices", "Compares with others", "Sets higher goals"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "만 원의 행복 실험",
    title_en: "The 10,000-won happiness experiment",
    body_kr: "돈으로 행복을 살 수 있을까. 한 연구팀이 흥미로운 실험을 했다. 참가자들에게 만 원씩 주고 절반에게는 자신을 위해, 나머지 절반에게는 남을 위해 쓰게 했다. 저녁에 행복도를 측정하자 남을 위해 쓴 집단이 뚜렷하게 높았다. 액수를 키워도 결과는 비슷했다. 자신을 위한 소비의 만족은 금방 사라졌지만, 선물이나 기부의 기억은 오래 남았다. 연구진은 이를 '관계가 남기 때문'이라고 설명한다. 커피 한 잔을 사 줬을 때 남는 것은 커피가 아니라 상대의 표정과 대화다. 돈으로 행복을 사는 가장 확실한 방법은, 역설적이게도 그 돈을 남에게 쓰는 것이다.",
    body_en: "Can money buy happiness? A research team ran an interesting experiment. They gave participants 10,000 won each: half were told to spend it on themselves, half on someone else. When happiness was measured that evening, the group that spent on others scored clearly higher. Raising the amount didn't change the result. Satisfaction from spending on oneself faded fast, while memories of gifts and giving lingered. The researchers' explanation: 'what remains is the relationship.' When you buy someone a coffee, what stays isn't the coffee — it's their expression and the conversation. The surest way to buy happiness with money, paradoxically, is to spend it on someone else.",
    questions: [
      { question_en: "Which group was happier that evening?", options: ["Those who spent on themselves", "Those who spent on others", "Those who saved it", "No difference"], answerIndex: 1 },
      { question_en: "Why does spending on others last longer?", options: ["It's tax-deductible", "The relationship remains", "It costs less", "It earns interest"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "explainer",
    title_kr: "아날로그의 반격",
    title_en: "The analog comeback",
    body_kr: "음원 스트리밍의 시대에 LP 판매량이 십 년 연속 늘고 있다. 필름 카메라는 중고 가격이 새 제품보다 비싸졌고, 종이 다이어리는 연말마다 품절된다. 디지털이 모든 것을 대체할 것이라던 예측은 왜 빗나갔을까. 첫 번째 답은 '소유의 감각'이다. 스트리밍은 접근을 팔지만 LP는 물건으로 남는다. 두 번째는 '제한이 주는 집중'이다. 필름은 서른여섯 장뿐이라 한 장을 신중하게 찍게 된다. 세 번째는 '느림의 가치'다. 손으로 쓰는 일기는 타이핑보다 느리기에 오히려 생각이 정리된다. 아날로그의 반격은 과거로의 회귀가 아니다. 무한한 디지털 속에서 유한한 것이 주는 만족을 재발견하는 일이다.",
    body_en: "In the streaming era, LP sales have grown for ten straight years. Used film cameras now cost more than they did new, and paper planners sell out every December. Why did the prediction that digital would replace everything miss? The first answer is the sense of ownership: streaming sells access, but an LP remains an object. The second is the focus that limits create: film gives you only thirty-six frames, so each shot becomes deliberate. The third is the value of slowness: writing a diary by hand is slower than typing, and precisely because of that, it organizes your thoughts. The analog comeback is not a return to the past — it is rediscovering the satisfaction of the finite within the infinity of digital.",
    questions: [
      { question_en: "Why does film's 36-frame limit matter?", options: ["It's cheaper", "It makes each shot deliberate", "It develops faster", "It's easier to carry"], answerIndex: 1 },
      { question_en: "What is the analog comeback, according to the passage?", options: ["Nostalgia for the past", "Rediscovering the satisfaction of finite things", "A marketing trick", "A rejection of technology"], answerIndex: 1 },
    ],
  },
];
