import type { RawPassage } from "./types";

export const READING_B2_OPINION: RawPassage[] = [
  {
    level: "B2",
    genre: "opinion",
    title_kr: "한국에도 팁 문화가 필요할까",
    title_en: "Does Korea need tipping culture?",
    body_kr: "최근 몇몇 카페와 레스토랑에서 팁을 권유하는 모습을 보게 되면서 나는 이 흐름에 반대하는 입장이다. 물론 서비스가 좋았을 때 마음을 표현하고 싶다는 의견도 이해는 간다. 하지만 팁 문화는 결국 종업원의 기본급을 낮추는 핑계가 되고 손님에게는 불필요한 부담을 지운다. 미국처럼 팁이 필수가 되어 버린 사회를 보면 오히려 계산이 복잡해지고 불쾌한 경험도 늘어난다. 나는 서비스 비용을 가격에 투명하게 포함시키는 지금의 방식이 더 합리적이라고 생각한다. 결국 팁을 도입하기보다 정당한 임금을 보장하는 쪽이 모두에게 이익이다.",
    body_en: "Having recently seen some cafes and restaurants suggesting tips, I am against this trend. Of course, I understand the view that people want to express gratitude when service was good. But tipping culture ends up becoming an excuse to lower workers' base pay and places an unnecessary burden on customers. Looking at a society like the US where tipping has become mandatory, calculations actually get more complicated and unpleasant experiences increase. I think the current way of transparently including service cost in the price is more reasonable. In the end, guaranteeing fair wages benefits everyone more than introducing tipping.",
    questions: [
      { question_en: "What is the writer's stance on tipping culture coming to Korea?", options: ["Strongly in favor", "Against it", "Completely neutral", "Undecided but leaning positive"], answerIndex: 1 },
      { question_en: "What counterargument does the writer acknowledge?", options: ["Tipping is required by law elsewhere", "Wanting to express gratitude for good service", "Restaurants need more profit", "Customers prefer cashless payment"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "재택근무가 정말 더 생산적인가",
    title_en: "Is remote work really more productive?",
    body_kr: "재택근무를 둘러싼 논쟁이 여전히 뜨거운데 나는 재택근무가 실제로 생산성을 높인다고 생각한다. 출퇴근 시간이 사라지면서 그 시간을 업무나 휴식에 쓸 수 있고 불필요한 회의도 줄어드는 경우가 많다. 물론 협업이 필요한 업무나 신입 직원 교육에는 대면 근무가 더 효과적이라는 지적도 타당하다. 그러나 이런 문제는 완전한 재택보다 필요할 때만 사무실에 모이는 하이브리드 방식으로 충분히 해결할 수 있다. 나는 관리자가 근무 시간을 감시하는 대신 결과물로 평가하는 문화가 자리 잡는다면 재택근무의 장점이 더욱 커질 것이라고 본다. 결국 문제는 재택근무 자체가 아니라 그것을 뒷받침하는 조직 문화에 있다.",
    body_en: "The debate over remote work is still heated, but I think remote work actually increases productivity. With commute time eliminated, that time can go toward work or rest, and unnecessary meetings often decrease. Of course, the point that in-person work is more effective for collaborative tasks or training new employees is valid. But this problem can be sufficiently solved through a hybrid approach where people gather at the office only when needed, rather than full remote work. I believe that if a culture of evaluating results instead of monitoring hours takes hold, the advantages of remote work will grow even more. In the end, the issue isn't remote work itself but the organizational culture supporting it.",
    questions: [
      { question_en: "What is the writer's stance on remote work?", options: ["It lowers productivity", "It increases productivity", "It should be banned", "It has no effect either way"], answerIndex: 1 },
      { question_en: "What counterpoint does the writer acknowledge about remote work?", options: ["It costs companies more money", "In-person work is better for collaboration and training", "Employees dislike working from home", "It reduces employee salaries"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "카페에서 노트북 사용을 막아야 할까",
    title_en: "Should laptops be banned in cafes?",
    body_kr: "요즘 카페에 가면 공부나 업무를 하는 사람들이 자리를 오래 차지하는 모습을 자주 본다. 나는 그럼에도 불구하고 노트북 사용을 완전히 금지하는 것에는 반대한다. 물론 회전율이 떨어져 매출에 영향을 준다는 카페 사장님들의 불만은 충분히 이해할 만하다. 그러나 시간제 좌석 요금이나 이용 시간 제한 같은 유연한 방법으로도 같은 효과를 거둘 수 있다. 무조건 금지해 버리면 조용히 공부할 공간이 필요한 학생들이 갈 곳을 잃게 된다. 나는 규제보다는 서로를 배려하는 문화와 합리적인 정책이 함께 가야 한다고 생각한다.",
    body_en: "These days when I go to cafes, I often see people studying or working occupying seats for a long time. Nevertheless, I oppose completely banning laptop use. Of course, cafe owners' complaints that turnover drops and affects revenue are quite understandable. But the same effect can be achieved through flexible methods like hourly seating fees or time limits. If laptops are simply banned outright, students who need a quiet place to study lose somewhere to go. I think regulation should go hand in hand with a culture of mutual consideration and reasonable policy, rather than outright bans.",
    questions: [
      { question_en: "What is the writer's position on banning laptops in cafes?", options: ["Fully supports a total ban", "Opposes a total ban", "Wants laptops banned only on weekends", "Has no opinion"], answerIndex: 1 },
      { question_en: "What complaint from cafe owners does the writer acknowledge?", options: ["Customers are too noisy", "Laptop users lower table turnover and revenue", "Wifi costs too much", "Laptops damage the furniture"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "미니멀리즘은 과대평가되었다",
    title_en: "Minimalism is overrated",
    body_kr: "몇 년 전부터 미니멀 라이프가 유행하면서 물건을 적게 소유하는 것이 곧 행복이라는 인식이 퍼졌다. 하지만 나는 미니멀리즘이 다소 과대평가되었다고 생각한다. 불필요한 소비를 줄이고 공간을 정리한다는 취지 자체는 분명 긍정적이다. 그렇지만 지나치게 물건을 비우는 것에 집착하다 보면 오히려 추억이 담긴 물건이나 실용적인 도구까지 버리게 되는 경우가 많다. 또한 미니멀리즘이 하나의 트렌드로 소비되면서 값비싼 미니멀 디자인 제품을 사들이는 모순적인 상황도 벌어진다. 나는 물건의 개수보다 그 물건이 자신에게 의미가 있는지가 더 중요한 기준이라고 본다.",
    body_en: "Since minimalist living became a trend a few years ago, the idea that owning fewer things equals happiness has spread. But I think minimalism is somewhat overrated. The original intent of reducing unnecessary consumption and organizing space is certainly positive. However, obsessing over decluttering too much often leads people to throw away sentimental items or practical tools as well. There's also the contradictory situation where minimalism itself becomes a consumed trend, with people buying expensive minimalist-design products. I believe whether an item is meaningful to a person is a more important standard than how many items they own.",
    questions: [
      { question_en: "What is the writer's overall view of minimalism?", options: ["It is completely without merit", "It is somewhat overrated", "It should be mandatory for everyone", "It has no drawbacks at all"], answerIndex: 1 },
      { question_en: "What positive aspect of minimalism does the writer acknowledge?", options: ["It makes people wealthier", "Reducing unnecessary consumption and organizing space", "It guarantees more free time", "It improves relationships automatically"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "알고리즘이 취향을 결정하게 둬도 될까",
    title_en: "Should we let algorithms decide our taste?",
    body_kr: "요즘은 넷플릭스나 유튜브의 추천 알고리즘이 우리가 무엇을 볼지 대신 결정해 주는 경우가 많다. 나는 이런 흐름이 편리하기는 하지만 장기적으로는 위험하다고 생각한다. 물론 방대한 콘텐츠 속에서 원하는 것을 빠르게 찾아 준다는 장점은 부정할 수 없다. 하지만 알고리즘은 이미 좋아하는 것과 비슷한 것만 계속 추천하기 때문에 시야가 점점 좁아지는 결과를 낳는다. 새로운 장르나 낯선 관점을 접할 기회가 줄어들면 취향뿐 아니라 사고방식도 편협해질 수 있다. 나는 가끔 알고리즘을 벗어나 스스로 검색하고 탐색하는 습관이 반드시 필요하다고 믿는다.",
    body_en: "These days, recommendation algorithms on Netflix or YouTube often decide what we watch for us. I think this trend is convenient but risky in the long run. Of course, the advantage of quickly finding what you want amid vast amounts of content can't be denied. But since algorithms keep recommending things similar to what you already like, the result is a narrowing field of view. When opportunities to encounter new genres or unfamiliar perspectives decrease, not only taste but also ways of thinking can become narrow-minded. I believe it is essential to occasionally step outside the algorithm and search and explore on your own.",
    questions: [
      { question_en: "What is the writer's main concern about algorithmic curation?", options: ["It costs too much money", "It narrows people's perspectives over time", "It is too slow", "It only works on weekends"], answerIndex: 1 },
      { question_en: "What benefit of algorithms does the writer admit?", options: ["It quickly helps find what you want in vast content", "It improves eyesight", "It replaces the need for friends", "It guarantees better sleep"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "즉시 배송이 동네 가게를 위협한다",
    title_en: "Instant delivery threatens local shops",
    body_kr: "새벽 배송이나 즉시 배송 서비스가 확산되면서 소비자에게는 분명 편리한 세상이 되었다. 그러나 나는 이런 서비스가 동네 상점에 미치는 영향을 가볍게 볼 수 없다고 생각한다. 대형 플랫폼이 가격 경쟁력과 속도를 무기로 시장을 장악하면서 골목의 작은 마트와 청과물 가게는 손님을 잃어 가고 있다. 물론 소비자 입장에서는 더 싸고 빠른 선택지를 택하는 것이 당연하다는 반론도 일리가 있다. 하지만 지역 상권이 무너지면 결국 일자리와 동네 공동체까지 흔들릴 수 있다는 점을 간과해서는 안 된다. 나는 소비자 개개인도 가끔은 동네 가게를 이용하려는 의식적인 선택이 필요하다고 생각한다.",
    body_en: "As dawn delivery and instant delivery services spread, life has clearly become more convenient for consumers. But I don't think we can take lightly the impact these services have on local shops. As large platforms dominate the market with price competitiveness and speed as weapons, small neighborhood marts and produce stores are losing customers. Of course, the counterargument that consumers naturally choose the cheaper, faster option makes sense. But we shouldn't overlook the fact that if local commerce collapses, jobs and neighborhood communities can be shaken as well. I think individual consumers also need to make a conscious choice to use local shops sometimes.",
    questions: [
      { question_en: "What is the writer's stance on instant delivery services?", options: ["Fully positive with no concerns", "Concerned about their effect on local shops", "In favor of banning them immediately", "Indifferent to the issue"], answerIndex: 1 },
      { question_en: "What counterargument does the writer acknowledge?", options: ["Consumers naturally prefer cheaper, faster options", "Delivery drivers earn too much", "Local shops always have better prices", "Platforms are illegal"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "코딩 교육은 더 일찍 시작되어야 한다",
    title_en: "Coding education should start earlier",
    body_kr: "인공지능과 자동화가 빠르게 확산되는 시대에 나는 코딩 교육이 초등학교 저학년부터 시작되어야 한다고 생각한다. 물론 너무 이른 나이에 컴퓨터 앞에 앉히는 것이 창의력이나 신체 발달에 좋지 않다는 우려도 무시할 수는 없다. 하지만 코딩은 단순히 프로그래밍 언어를 배우는 것이 아니라 문제를 논리적으로 쪼개고 해결하는 사고방식을 키우는 과정이다. 이런 사고력은 어릴 때부터 훈련할수록 자연스럽게 몸에 밴다. 또한 놀이처럼 접근하는 블록 코딩 도구들이 이미 많아서 아이들의 부담도 크지 않다. 나는 적절한 방식으로만 도입한다면 이른 코딩 교육이 아이들의 미래에 큰 자산이 될 것이라고 확신한다.",
    body_en: "In an era where AI and automation are spreading rapidly, I think coding education should start from the early years of elementary school. Of course, the concern that sitting children in front of computers too early is bad for creativity or physical development cannot be ignored. But coding isn't simply learning a programming language — it's a process of building a way of thinking that logically breaks down and solves problems. This kind of thinking becomes natural the earlier it is trained. Also, there are already many play-like block coding tools, so the burden on children isn't great. I'm convinced that if introduced in the right way, early coding education will be a great asset to children's future.",
    questions: [
      { question_en: "What is the writer's position on early coding education?", options: ["It should be delayed until high school", "It should start in early elementary school", "It should never be taught", "It should only be optional for adults"], answerIndex: 1 },
      { question_en: "What concern about early coding education does the writer acknowledge?", options: ["It is too expensive for schools", "It might hurt creativity or physical development", "It requires expensive equipment", "Teachers refuse to teach it"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "주 4일제는 아직 현실적이지 않다",
    title_en: "The four-day workweek isn't realistic yet",
    body_kr: "몇몇 기업이 주 4일제를 시범 도입했다는 소식이 들려오면서 기대감이 커지고 있지만 나는 아직 시기상조라고 생각한다. 노동 시간을 줄이면서도 생산성과 임금을 유지할 수 있다는 실험 결과들이 흥미로운 것은 사실이다. 그러나 이런 실험은 대부분 자율성이 높은 사무직이나 창의적인 업무 중심의 기업에서 이루어졌다는 한계가 있다. 제조업이나 서비스업처럼 인력이 곧 생산량과 직결되는 분야에서는 같은 방식이 그대로 적용되기 어렵다. 무리하게 도입했다가 오히려 남은 하루치 업무가 다른 요일에 몰려 노동 강도만 높아질 위험도 있다. 나는 산업별 특성을 충분히 반영한 단계적 접근이 먼저 필요하다고 본다.",
    body_en: "As news spreads that some companies have piloted a four-day workweek, expectations are growing, but I think it's still premature. It's true that some experimental results showing productivity and wages can be maintained while reducing work hours are intriguing. However, these experiments have mostly been limited to office jobs with high autonomy or companies centered on creative work. In fields like manufacturing or services, where workforce size is directly tied to output, the same approach is hard to apply as is. Forcing the introduction risks the leftover day's work simply piling onto other days, increasing labor intensity instead. I think a gradual approach that fully reflects industry-specific characteristics is needed first.",
    questions: [
      { question_en: "What is the writer's stance on the four-day workweek?", options: ["It should be adopted everywhere immediately", "It is premature for widespread adoption now", "It has already failed completely", "It only applies to manufacturing"], answerIndex: 1 },
      { question_en: "What positive finding does the writer acknowledge about four-day workweek trials?", options: ["Workers quit less often", "Some show productivity and wages can be maintained", "All industries benefit equally", "It reduces company costs immediately"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "소셜 미디어 연령 제한이 필요하다",
    title_en: "Social media needs an age limit",
    body_kr: "청소년들의 정신 건강 문제가 소셜 미디어 사용과 관련이 있다는 연구가 늘어나면서 나는 연령 제한 도입에 찬성하는 쪽으로 마음이 기울었다. 청소년 스스로 온라인에서의 비교와 압박을 조절하기 어렵다는 점에서 어른들의 개입이 필요하다고 생각한다. 물론 나이만으로 접근을 막는 것이 실효성이 없고 아이들이 우회로를 쉽게 찾을 것이라는 반박도 설득력이 있다. 그렇다고 해서 아무 조치도 취하지 않는 것이 정답은 아니다. 나는 완벽한 제한보다는 부모와 학교가 함께 디지털 사용 습관을 교육하는 것과 병행하는 제한이 현실적이라고 생각한다. 결국 규제와 교육이 함께 갈 때만 실질적인 효과를 기대할 수 있다.",
    body_en: "As research increasingly links teenagers' mental health issues to social media use, I've leaned toward supporting the introduction of age limits. I think adult intervention is needed because teenagers themselves find it hard to manage the comparison and pressure they face online. Of course, the counterargument that restricting access by age alone is ineffective and that kids will easily find workarounds is persuasive. But that doesn't mean doing nothing is the right answer either. I think a realistic approach combines limits with parents and schools jointly teaching healthy digital habits, rather than expecting a perfect restriction. In the end, real effect can only be expected when regulation and education go hand in hand.",
    questions: [
      { question_en: "What is the writer's overall stance on age limits for social media?", options: ["Opposed to any limits", "In favor, combined with education", "Indifferent to the issue", "Wants social media banned entirely"], answerIndex: 1 },
      { question_en: "What counterargument does the writer acknowledge?", options: ["Age limits are unenforceable and kids find workarounds", "Social media has no health effects", "Parents don't care about the issue", "Schools already solved the problem"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "빨리빨리 문화는 강점이다",
    title_en: "\"Ppalli-ppalli\" culture is a strength",
    body_kr: "외국인들이 흔히 지적하는 한국의 빨리빨리 문화에 대해 나는 오히려 이것이 강점이라고 생각한다. 물론 서두르는 과정에서 실수가 생기고 안전이 소홀해질 수 있다는 비판은 타당하다. 실제로 일부 사고 사례를 보면 속도를 지나치게 강조한 결과라는 점을 부정하기 어렵다. 그러나 빠른 의사 결정과 실행력 덕분에 한국이 짧은 시간 안에 경제 성장과 기술 혁신을 이뤄 낸 것도 사실이다. 배달 서비스나 온라인 행정 처리 같은 분야에서 세계적으로 앞서 나갈 수 있었던 배경에도 이 문화가 있다. 나는 속도와 안전을 동시에 챙기는 시스템만 갖춘다면 빨리빨리 문화는 여전히 소중한 자산이라고 믿는다.",
    body_en: "Regarding the \"ppalli-ppalli\" (hurry-hurry) culture that foreigners commonly point out about Korea, I actually think it's a strength. Of course, the criticism that mistakes happen and safety gets neglected in the rush is valid. Looking at some accident cases, it's hard to deny they resulted from overemphasizing speed. However, it's also true that fast decision-making and execution allowed Korea to achieve economic growth and technological innovation in a short time. This culture is also behind Korea's ability to lead the world in fields like delivery services and online administrative processing. I believe that as long as systems are put in place to manage both speed and safety together, ppalli-ppalli culture remains a valuable asset.",
    questions: [
      { question_en: "What is the writer's stance on \"ppalli-ppalli\" culture?", options: ["It should be eliminated entirely", "It is a valuable strength overall", "It has no relation to economic growth", "It only causes harm"], answerIndex: 1 },
      { question_en: "What criticism does the writer acknowledge as valid?", options: ["It makes food taste worse", "It can lead to mistakes and neglected safety", "It slows down economic growth", "Foreigners dislike Korean food because of it"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "인기 관광지에는 인원 제한이 필요하다",
    title_en: "Popular tourist spots need visitor limits",
    body_kr: "최근 유명 관광지들이 관광객 수를 제한하기 시작했다는 뉴스를 보고 나는 이러한 정책에 찬성하게 되었다. 관광 산업이 지역 경제에 기여한다는 점은 분명하지만 과도한 관광객 유입은 환경 훼손과 주민들의 삶의 질 저하로 이어진다. 물론 관광 수입에 의존하는 지역에서는 인원 제한이 곧 매출 감소를 의미한다는 우려도 이해할 만하다. 하지만 지금처럼 무분별하게 인원이 몰리면 정작 그 장소의 매력 자체가 훼손되어 장기적으로는 관광객마저 줄어들 위험이 있다. 나는 예약제나 요금 차등제 같은 방식으로 관광객 수를 조절하면서도 수입은 유지할 수 있는 대안이 충분히 가능하다고 본다. 결국 지속 가능한 관광을 위해서는 단기적인 손해를 감수할 필요가 있다.",
    body_en: "After seeing news that famous tourist spots have started limiting visitor numbers, I've come to support this kind of policy. It's clear tourism contributes to the local economy, but an excessive influx of tourists leads to environmental damage and a decline in residents' quality of life. Of course, the concern in regions dependent on tourism revenue that visitor limits mean reduced income is understandable. But if crowds keep pouring in indiscriminately as now, the very appeal of the place gets damaged, risking a long-term decline in tourists as well. I think alternatives like reservation systems or tiered pricing can adjust visitor numbers while still maintaining income. In the end, sustainable tourism requires accepting some short-term loss.",
    questions: [
      { question_en: "What is the writer's stance on limiting tourists at popular spots?", options: ["Opposed to any limits", "In favor of visitor limits", "Wants tourism banned entirely", "No opinion on the matter"], answerIndex: 1 },
      { question_en: "What concern does the writer acknowledge about limiting visitors?", options: ["Tourists will get lost", "Tourism-dependent regions fear reduced income", "Airlines will lose customers", "Hotels will close permanently"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "AI가 만든 예술도 예술이다",
    title_en: "AI-generated art is still art",
    body_kr: "인공지능이 그린 그림이나 작곡한 음악을 두고 진짜 예술이 아니라는 논쟁이 뜨겁지만 나는 AI 창작물도 예술의 범주에 포함될 수 있다고 생각한다. 물론 인간의 감정과 경험 없이 만들어진 결과물이 예술이라 불릴 자격이 있는지 의문을 제기하는 입장도 충분히 이해가 간다. 그러나 예술의 역사를 돌아보면 새로운 도구가 등장할 때마다 비슷한 논쟁이 있었다. 사진기가 처음 등장했을 때도 그림을 대체할 것이라는 우려와 함께 예술이 아니라는 비판을 받았지만 지금은 하나의 독립된 예술 장르로 인정받는다. 결국 중요한 것은 도구가 아니라 그 결과물이 사람들에게 감동이나 사유를 이끌어 내는가이다. 나는 AI를 도구로 활용하는 창작자의 역할이 여전히 예술 행위의 핵심이라고 믿는다.",
    body_en: "There's a heated debate over whether paintings drawn or music composed by AI count as real art, but I think AI creations can be included in the category of art. Of course, I fully understand the position questioning whether results made without human emotion and experience deserve to be called art. But looking back at art history, similar debates arose whenever a new tool appeared. When cameras first appeared, they were criticized as not being art, along with fears they would replace painting, but photography is now recognized as its own independent art genre. In the end, what matters is not the tool but whether the result draws emotion or reflection from people. I believe the role of the creator who uses AI as a tool remains the core of the artistic act.",
    questions: [
      { question_en: "What is the writer's stance on AI-generated art?", options: ["It can be considered real art", "It should never be called art", "Only photography counts as art", "AI cannot create anything at all"], answerIndex: 0 },
      { question_en: "What historical parallel does the writer use to support their view?", options: ["The invention of the printing press", "The camera being initially dismissed as not art", "The invention of the radio", "The rise of television"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "아이 사진을 온라인에 올리는 것을 신중히 생각해야 한다",
    title_en: "Sharing kids' photos online deserves more caution",
    body_kr: "많은 부모들이 아이의 성장 과정을 소셜 미디어에 기록하지만 나는 이런 행동에 좀 더 신중해야 한다는 입장이다. 물론 가족과 지인들에게 아이의 소식을 쉽게 전할 수 있고 소중한 순간을 기록으로 남길 수 있다는 장점은 인정한다. 그러나 아이는 아직 자신의 사진이 공개되는 것에 동의할 능력이 없으며 그 정보는 인터넷에 영구적으로 남는다. 실제로 온라인에 퍼진 아이 사진이 악용되는 사례도 보고되고 있어 걱정이 커진다. 나는 완전히 올리지 말라는 것이 아니라 공개 범위를 제한하고 아이가 자라서 스스로 판단할 수 있을 때까지는 신중하게 접근해야 한다고 생각한다. 아이의 프라이버시도 부모가 지켜 줘야 할 권리라는 점을 기억해야 한다.",
    body_en: "Many parents record their child's growth on social media, but I believe this deserves more caution. Of course, I acknowledge the advantage of easily sharing news about the child with family and acquaintances and keeping a record of precious moments. However, the child doesn't yet have the ability to consent to their photo being made public, and that information stays on the internet permanently. There are indeed reported cases of children's photos spreading online being misused, which raises concern. I'm not saying never post at all, but that people should limit the audience and take a cautious approach until the child grows old enough to judge for themselves. We should remember that a child's privacy is also a right parents must protect.",
    questions: [
      { question_en: "What is the writer's stance on sharing children's photos online?", options: ["It should be done freely with no limits", "It requires caution and limited audiences", "Children's photos should never exist", "It has no risks at all"], answerIndex: 1 },
      { question_en: "What benefit does the writer acknowledge about sharing kids' photos?", options: ["It earns money for parents", "It lets family easily see the child's news and keeps memories", "It guarantees the child's safety", "It improves the child's grades"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "현금 없는 사회, 아직은 이르다",
    title_en: "A cashless society is still premature",
    body_kr: "카드와 모바일 결제가 보편화되면서 현금 없는 사회를 지지하는 목소리가 커지고 있지만 나는 아직 시기상조라고 생각한다. 결제가 빠르고 위생적이며 기록 관리가 편하다는 장점은 분명하다. 그러나 디지털 기기 사용이 서툰 고령층이나 신용 정보가 부족한 사람들은 현금 없는 환경에서 오히려 소외될 수 있다. 또한 정전이나 시스템 오류처럼 예상치 못한 상황에서 현금이 유일한 대안이 되는 경우도 여전히 존재한다. 나는 완전한 현금 폐지보다 현금과 디지털 결제가 공존하는 구조가 당분간 더 안전하다고 본다. 기술의 편리함이 누군가를 배제하는 방식으로 작동해서는 안 된다.",
    body_en: "As card and mobile payments become common, voices supporting a cashless society are growing, but I think it's still premature. The advantages of fast, hygienic payment and easy record-keeping are clear. However, elderly people unfamiliar with digital devices or those lacking credit information could actually be left out in a cashless environment. There are also still cases where cash remains the only option in unexpected situations like power outages or system errors. I think a structure where cash and digital payment coexist is safer for now, rather than fully abolishing cash. The convenience of technology should not work in a way that excludes someone.",
    questions: [
      { question_en: "What is the writer's stance on a fully cashless society?", options: ["Fully supports it immediately", "Thinks it's premature", "Wants cash banned entirely", "Has no concerns about it"], answerIndex: 1 },
      { question_en: "What advantage of cashless payment does the writer acknowledge?", options: ["It is fast, hygienic, and easy to track", "It eliminates all crime", "It guarantees equal access for everyone", "It works even during power outages"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "직장에 반려동물을 데려와도 될까",
    title_en: "Should pets be allowed at work?",
    body_kr: "몇몇 스타트업들이 반려동물 동반 출근을 허용하면서 나는 이런 문화가 더 확산되어야 한다고 생각한다. 반려동물과 함께 있으면 스트레스가 줄고 직원들 사이의 대화도 자연스럽게 늘어난다는 연구 결과가 있다. 물론 동물 알레르기가 있는 동료나 동물을 무서워하는 사람들을 배려해야 한다는 반론도 충분히 타당하다. 모든 직원에게 강요할 수 없는 문제라는 점도 인정한다. 그러나 지정된 공간이나 요일을 정해 운영한다면 이런 우려를 상당 부분 해소할 수 있다. 나는 반려동물 동반 근무가 직원 만족도를 높이는 좋은 복지 제도가 될 수 있다고 믿는다.",
    body_en: "As some startups allow employees to bring pets to work, I think this culture should spread further. There is research showing that being with a pet reduces stress and naturally increases conversation among coworkers. Of course, the counterargument that colleagues with animal allergies or people afraid of animals need consideration is quite valid. I also acknowledge this isn't something that can be forced on every employee. But operating it through designated spaces or specific days can resolve much of this concern. I believe pet-friendly workplaces can become a great benefit that raises employee satisfaction.",
    questions: [
      { question_en: "What is the writer's stance on allowing pets at work?", options: ["Opposed to it entirely", "Supports it, ideally with limits like designated spaces", "Wants it mandatory for all companies", "Has no opinion"], answerIndex: 1 },
      { question_en: "What concern does the writer acknowledge?", options: ["Pets cost too much to maintain", "Colleagues with allergies or fear of animals need consideration", "Pets reduce company profits", "Pets are illegal in offices"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "패스트 패션의 편리함은 대가를 치른다",
    title_en: "Fast fashion's convenience comes at a cost",
    body_kr: "저렴한 가격에 최신 유행을 빠르게 살 수 있는 패스트 패션은 분명 매력적이지만 나는 그 편리함이 너무 큰 대가를 치르게 한다고 생각한다. 물론 경제적으로 여유가 없는 사람들에게 저렴한 옷은 실질적인 도움이 된다는 점을 부정할 수는 없다. 그러나 패스트 패션 산업은 막대한 물 소비와 화학 염료 오염, 그리고 저임금 노동 착취 문제로 계속 비판받고 있다. 유행이 빠르게 바뀌면서 옷이 금방 버려지고 그 대부분이 재활용되지 못한 채 매립되거나 소각된다는 사실도 심각하다. 나는 무조건 소비를 멈추라는 것이 아니라 조금 더 오래 입을 수 있는 옷을 선택하는 습관이 필요하다고 본다. 결국 지금의 소비 방식은 지구가 감당하기 어려운 속도로 가고 있다.",
    body_en: "Fast fashion, which lets you quickly buy the latest trends at low prices, is certainly appealing, but I think its convenience comes at too great a cost. Of course, one can't deny that cheap clothing offers real help to people without much financial room. But the fast fashion industry keeps facing criticism for massive water consumption, chemical dye pollution, and low-wage labor exploitation. It's also serious that as trends change quickly, clothes get discarded quickly, with most ending up in landfills or incinerated without being recycled. I'm not saying to stop consuming altogether, but that we need a habit of choosing clothes that can be worn longer. In the end, the current pace of consumption is moving faster than the planet can handle.",
    questions: [
      { question_en: "What is the writer's stance on fast fashion?", options: ["Fully supports it with no concerns", "Believes its convenience comes at too great an environmental and labor cost", "Wants all clothing production banned", "Thinks it has no effect on the environment"], answerIndex: 1 },
      { question_en: "What benefit of fast fashion does the writer acknowledge?", options: ["It creates high-paying jobs", "It offers real help to people with limited money", "It uses less water than other industries", "It never goes out of style"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "대중교통 무료화, 해 볼 만하다",
    title_en: "Free public transit is worth trying",
    body_kr: "일부 유럽 도시들이 대중교통을 무료로 운영한다는 소식을 접하면서 나는 한국에서도 시도해 볼 가치가 있다고 생각하게 되었다. 무료 대중교통은 자가용 이용을 줄여 교통 혼잡과 대기 오염을 완화하는 효과가 있다고 알려져 있다. 물론 운영 비용을 세금으로 충당해야 한다는 점에서 재정 부담을 우려하는 목소리도 이해할 만하다. 실제로 일부 도시에서는 재정난으로 무료 정책을 되돌린 사례도 있다. 그러나 자동차 유지비와 도로 건설 비용, 환경 오염 처리 비용까지 고려하면 장기적으로는 오히려 사회적 비용을 줄일 수 있다는 분석도 있다. 나는 전면 무료화가 부담스럽다면 노약자나 저소득층부터 단계적으로 확대하는 방안도 충분히 현실적이라고 본다.",
    body_en: "Hearing news that some European cities operate free public transit, I've come to think it's worth trying in Korea too. Free public transit is known to ease traffic congestion and air pollution by reducing private car use. Of course, the concern about the financial burden, since operating costs must be covered by taxes, is understandable. In fact, some cities have reversed the free policy due to financial difficulty. But considering car maintenance costs, road construction costs, and pollution cleanup costs, some analyses show it could actually reduce social costs in the long run. I think if full free transit feels burdensome, gradually expanding it starting with the elderly or low-income groups is also a realistic option.",
    questions: [
      { question_en: "What is the writer's stance on free public transit?", options: ["Opposed to it under any circumstances", "Thinks it's worth trying, even if gradually", "Wants it removed where it already exists", "Has no interest in the topic"], answerIndex: 1 },
      { question_en: "What concern does the writer acknowledge about free transit?", options: ["It causes more traffic accidents", "The financial burden of covering costs through taxes", "It makes buses too crowded to use", "It only works in small towns"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "끊임없는 자기계발 강박에서 벗어나야 한다",
    title_en: "We need to escape the pressure of constant self-improvement",
    body_kr: "새벽 기상, 독서, 운동, 부업까지 자기계발을 강조하는 콘텐츠가 넘쳐나지만 나는 이런 문화가 오히려 사람들을 지치게 만든다고 생각한다. 물론 꾸준한 노력과 성장을 추구하는 태도 자체는 긍정적이며 실제로 삶의 만족도를 높이는 경우도 많다. 그러나 문제는 잠시라도 쉬면 뒤처진다는 불안감을 조성하는 방식으로 자기계발이 소비되고 있다는 점이다. 휴식을 게으름으로, 여유를 나태함으로 여기게 만드는 분위기 속에서 사람들은 진정한 회복의 시간을 갖지 못한다. 나는 성장이 목표가 되는 것은 좋지만 그것이 강박이 되어서는 안 된다고 본다. 결국 아무것도 하지 않는 시간도 삶에서 반드시 필요한 부분이다.",
    body_en: "Content emphasizing self-improvement — early rising, reading, exercise, even side hustles — is overflowing, but I think this culture actually exhausts people. Of course, the attitude of pursuing steady effort and growth is itself positive and often does raise life satisfaction. But the problem is that self-improvement is being consumed in a way that creates anxiety about falling behind if you rest even briefly. In an atmosphere that treats rest as laziness and leisure as idleness, people can't get genuine recovery time. I think it's good for growth to be a goal, but it shouldn't become an obsession. In the end, time spent doing nothing is also a necessary part of life.",
    questions: [
      { question_en: "What is the writer's stance on constant self-improvement culture?", options: ["It is entirely beneficial with no downsides", "It can become an unhealthy obsession", "It should be banned by law", "It has no connection to anxiety"], answerIndex: 1 },
      { question_en: "What positive aspect of self-improvement does the writer acknowledge?", options: ["It guarantees wealth", "Steady effort and growth can raise life satisfaction", "It replaces the need for sleep", "It is required for all jobs"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "봉사료 폐지가 정답은 아니다",
    title_en: "Abolishing service charges isn't the answer",
    body_kr: "일부 레스토랑에서 봉사료를 없애야 한다는 목소리가 커지고 있지만 나는 무조건적인 폐지에는 신중해야 한다고 생각한다. 소비자 입장에서는 최종 가격이 명확하지 않고 팁처럼 느껴져 불편하다는 불만이 이해가 간다. 그러나 봉사료가 실제로 직원들의 처우 개선에 쓰이는 경우도 많으며 이를 없애면 그 비용이 서비스 질 저하로 이어질 위험이 있다. 나는 봉사료를 없애기보다 처음부터 총액 가격을 투명하게 표시하는 방식이 더 나은 대안이라고 본다. 소비자는 명확한 가격을 알 수 있고 업장은 안정적인 재원을 유지할 수 있기 때문이다. 결국 핵심은 봉사료의 존재 여부가 아니라 가격 표시의 투명성이다.",
    body_en: "Voices calling for the abolition of service charges at some restaurants are growing, but I think unconditional abolition requires caution. From the consumer's perspective, the complaint that the final price is unclear and feels like an unwanted tip is understandable. But service charges are often actually used to improve staff treatment, and removing them risks a decline in service quality as that cost disappears. I think a better alternative than eliminating service charges is transparently displaying the total price from the start. That way consumers can know the clear price and businesses can maintain stable funding. In the end, the key issue isn't whether service charges exist but the transparency of price display.",
    questions: [
      { question_en: "What is the writer's stance on abolishing service charges?", options: ["Fully supports immediate abolition", "Urges caution and suggests transparent pricing instead", "Wants service charges doubled", "Has no opinion on pricing"], answerIndex: 1 },
      { question_en: "What consumer complaint does the writer acknowledge?", options: ["Restaurants are too expensive overall", "The final price feels unclear and tip-like", "Food quality has declined", "Service charges are illegal"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "노스탤지어 마케팅은 게으른 전략이다",
    title_en: "Nostalgia marketing is a lazy strategy",
    body_kr: "옛날 캐릭터나 예전 광고를 다시 활용하는 노스탤지어 마케팅이 곳곳에서 유행하고 있지만 나는 이것이 창의성 부족을 감추는 게으른 전략이라고 생각한다. 물론 익숙한 추억을 자극해 소비자에게 친근감을 주고 안정적인 반응을 이끌어 낼 수 있다는 효과는 인정한다. 실제로 단기적인 매출 상승 효과도 여러 사례에서 확인된다. 그러나 새로운 아이디어에 투자하기보다 과거의 인기에 기대는 방식이 반복되면 브랜드의 장기적인 경쟁력은 오히려 약화될 수 있다. 소비자들도 결국 비슷한 향수 자극에 무뎌지기 마련이다. 나는 과거를 활용하더라도 새로운 해석이나 가치를 더하지 않는다면 그것은 진정한 창작이라 부르기 어렵다고 본다.",
    body_en: "Nostalgia marketing, which reuses old characters or old ads, is trending everywhere, but I think it's a lazy strategy that hides a lack of creativity. Of course, I acknowledge the effect of stimulating familiar memories, giving consumers a sense of closeness, and drawing a stable response. Indeed, short-term sales boosts have been confirmed in various cases. But if brands repeatedly rely on past popularity rather than investing in new ideas, their long-term competitiveness can actually weaken. Consumers eventually become numb to similar nostalgic stimulation too. I think that even when using the past, if no new interpretation or value is added, it's hard to call it genuine creation.",
    questions: [
      { question_en: "What is the writer's stance on nostalgia marketing?", options: ["It is the best marketing strategy available", "It is a lazy strategy that can weaken long-term competitiveness", "It should be used exclusively by all brands", "It has no effect on sales at all"], answerIndex: 1 },
      { question_en: "What effect of nostalgia marketing does the writer acknowledge?", options: ["It permanently increases brand loyalty", "It can create familiarity and boost short-term sales", "It eliminates the need for advertising budgets", "It only works for food brands"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "명품 소비, 개인의 자유일 뿐이다",
    title_en: "Luxury spending is simply personal freedom",
    body_kr: "명품을 사는 사람들을 두고 허영심이 많다고 비판하는 시선이 여전히 존재하지만 나는 이것이 지나친 참견이라고 생각한다. 물론 무리하게 빚을 내면서까지 명품을 구매하는 행동은 문제가 될 수 있다는 점은 인정한다. 하지만 자신이 번 돈을 어디에 쓸지는 전적으로 개인의 선택이며 다른 사람이 도덕적으로 판단할 문제가 아니다. 누군가는 여행에 돈을 쓰고 누군가는 취미에 돈을 쓰듯이 명품도 그 사람에게 만족감을 주는 소비의 한 형태일 뿐이다. 나는 소비의 옳고 그름을 판단하기보다 각자의 가치관을 존중하는 태도가 더 필요하다고 본다. 결국 중요한 것은 자신의 경제 상황에 맞게 소비하는지 여부다.",
    body_en: "There's still a view that criticizes people who buy luxury goods as being overly vain, but I think this is excessive meddling. Of course, I acknowledge that buying luxury goods by taking on excessive debt can be a problem. But how one spends money they've earned is entirely a personal choice, not something others should morally judge. Just as someone spends money on travel and another on hobbies, luxury goods are simply one form of spending that brings satisfaction to that person. I think respecting each person's values matters more than judging right or wrong in spending. In the end, what matters is whether one spends according to their own financial situation.",
    questions: [
      { question_en: "What is the writer's stance on criticizing luxury spending?", options: ["Fully agrees luxury buyers are vain", "Thinks it's excessive meddling into personal choice", "Wants luxury goods banned", "Believes only the wealthy should spend freely"], answerIndex: 1 },
      { question_en: "What problem does the writer acknowledge about luxury spending?", options: ["It always ruins friendships", "Going into excessive debt to buy luxury goods", "It is illegal in most countries", "It never brings satisfaction"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "온라인 강의가 대학 교육을 대체할 수 있을까",
    title_en: "Can online courses replace university education?",
    body_kr: "저렴하고 유명한 온라인 강의가 늘어나면서 대학 교육이 필요 없다는 주장도 종종 들리지만 나는 아직은 완전한 대체가 어렵다고 생각한다. 온라인 강의는 시간과 장소의 제약 없이 원하는 지식을 저렴하게 얻을 수 있다는 강력한 장점이 있다. 그러나 대학은 단순히 지식 전달만이 아니라 동료들과의 토론, 인맥 형성, 그리고 스스로 문제를 해결하는 경험을 함께 제공한다. 특히 실습이 중요한 전공에서는 온라인 학습만으로 채울 수 없는 부분이 분명히 존재한다. 나는 온라인 강의가 대학 교육을 대체하기보다 보완하는 도구로서 훨씬 더 큰 가치를 지닌다고 본다. 두 가지를 병행할 때 학습 효과가 가장 크다고 믿는다.",
    body_en: "As cheap, well-known online courses increase, claims that university education is unnecessary are sometimes heard, but I think full replacement is still difficult. Online courses have the strong advantage of letting people gain desired knowledge cheaply without constraints of time or place. However, universities offer not just knowledge transfer but also discussion with peers, networking, and the experience of solving problems on one's own. Especially in majors where hands-on practice matters, there's clearly a part that online learning alone can't fill. I think online courses have far greater value as a tool that complements university education rather than replacing it. I believe learning is most effective when the two are combined.",
    questions: [
      { question_en: "What is the writer's stance on online courses replacing university?", options: ["Online courses should fully replace universities", "Full replacement is still difficult; they should complement each other", "Universities are entirely useless", "Online courses have no value at all"], answerIndex: 1 },
      { question_en: "What advantage of online courses does the writer acknowledge?", options: ["They provide networking opportunities like universities", "They offer affordable knowledge without time or place constraints", "They guarantee a job afterward", "They replace hands-on practice entirely"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "일회용품 규제는 더 강화되어야 한다",
    title_en: "Regulation on disposable items should be strengthened",
    body_kr: "카페에서 일회용 컵 사용을 줄이려는 정책이 시행되었지만 여전히 미흡하다고 느끼며 나는 규제가 더 강화되어야 한다고 생각한다. 물론 소상공인들에게 다회용기 세척 등 추가적인 부담을 준다는 반발도 이해할 만하다. 코로나19 이후 위생에 대한 우려로 오히려 일회용품 사용이 늘어난 측면도 있다는 점을 인정한다. 그러나 플라스틱 쓰레기가 바다와 토양을 오염시키는 속도를 생각하면 지금의 미온적인 대응으로는 부족하다. 나는 정부가 다회용기 시스템을 지원하고 소상공인의 부담을 세제 혜택 등으로 완화해 준다면 규제 강화가 충분히 가능하다고 본다. 환경 문제는 더 이상 미룰 수 있는 사안이 아니다.",
    body_en: "Policies to reduce disposable cup use in cafes have been implemented, but I feel they're still insufficient, so I think regulation should be strengthened further. Of course, the backlash that this places additional burdens on small business owners, like washing reusable containers, is understandable. I also acknowledge that disposable item use has actually increased somewhat due to hygiene concerns since COVID-19. But considering the speed at which plastic waste pollutes oceans and soil, the current lukewarm response is insufficient. I think stronger regulation is entirely possible if the government supports reusable container systems and eases the burden on small businesses through tax benefits. Environmental issues are no longer something we can put off.",
    questions: [
      { question_en: "What is the writer's stance on disposable item regulation?", options: ["It should be loosened", "It should be strengthened further", "It should be abolished entirely", "It has no effect on the environment"], answerIndex: 1 },
      { question_en: "What concern does the writer acknowledge about stronger regulation?", options: ["It burdens small business owners with extra costs", "It will destroy the environment faster", "It is already too strict", "Consumers refuse to comply"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "익명 온라인 댓글은 제한되어야 한다",
    title_en: "Anonymous online comments should be limited",
    body_kr: "표현의 자유를 이유로 익명 댓글 제도를 옹호하는 사람들이 많지만 나는 일정 부분 제한이 필요하다고 생각한다. 물론 익명성이 권력자를 비판하거나 부당함을 고발할 때 보호막이 되어 준다는 점은 분명한 장점이다. 그러나 그 익명성 뒤에 숨어 근거 없는 비방과 혐오 표현을 쏟아내는 사람들도 상당수 존재한다. 실제로 악성 댓글로 인해 고통받는 사람들의 사례가 끊이지 않고 있다는 사실을 외면해서는 안 된다. 나는 완전한 실명제보다 최소한의 본인 확인을 거치는 준익명제 정도가 표현의 자유와 책임을 동시에 지킬 수 있는 균형점이라고 본다. 자유에는 언제나 책임이 따라야 한다.",
    body_en: "Many people defend the anonymous comment system in the name of freedom of expression, but I think some degree of restriction is necessary. Of course, anonymity clearly has the advantage of serving as a shield when criticizing those in power or reporting injustice. But there are also a considerable number of people who hide behind that anonymity to pour out baseless slander and hate speech. We shouldn't ignore the fact that cases of people suffering from malicious comments continue without end. I think a semi-anonymous system with minimal identity verification, rather than full real-name policy, is the balance point that can protect both freedom of expression and responsibility. Freedom must always come with responsibility.",
    questions: [
      { question_en: "What is the writer's stance on anonymous online comments?", options: ["They should remain completely unrestricted", "Some restriction, like minimal identity verification, is necessary", "They should be fully replaced by real names", "They have no negative effects"], answerIndex: 1 },
      { question_en: "What benefit of anonymity does the writer acknowledge?", options: ["It increases advertising revenue", "It protects people criticizing power or reporting injustice", "It eliminates all internet crime", "It guarantees polite discussion"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "회식 문화는 사라져야 한다",
    title_en: "Company dinner culture should disappear",
    body_kr: "퇴근 후 이어지는 회식 문화에 대해 나는 이제 이런 관행이 사라져야 한다고 생각한다. 물론 회식을 통해 평소 나누지 못한 이야기를 하고 팀워크를 다질 수 있다는 긍정적인 측면도 있다는 점은 인정한다. 그러나 개인의 저녁 시간과 자유를 회사가 당연하다는 듯 침범하는 것은 더 이상 정당화되기 어렵다. 특히 술을 강요하는 분위기나 상사의 눈치를 봐야 하는 자리는 오히려 스트레스를 가중시킨다. 나는 팀워크를 다지고 싶다면 근무 시간 내에 짧은 점심 식사나 활동으로도 충분히 대체할 수 있다고 본다. 결국 강제성이 사라진 자율적인 만남만이 진짜 의미 있는 시간이 될 수 있다.",
    body_en: "Regarding the company dinner culture that continues after work, I now think this practice should disappear. Of course, I acknowledge the positive side that dinners let people talk about things they usually can't and build teamwork. But it's increasingly hard to justify a company invading an individual's evening time and freedom as if it were natural. Especially an atmosphere that forces drinking or requires watching a boss's mood only adds to stress. I think if the goal is building teamwork, a short lunch or activity during work hours can sufficiently replace it. In the end, only voluntary gatherings free of compulsion can become truly meaningful time.",
    questions: [
      { question_en: "What is the writer's stance on mandatory after-work company dinners?", options: ["They should continue as they are", "They should disappear", "They should happen more often", "They have no downsides"], answerIndex: 1 },
      { question_en: "What positive aspect of company dinners does the writer acknowledge?", options: ["They guarantee promotions", "They can build teamwork and allow conversation", "They save the company money", "They replace the need for vacations"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "반려동물 등록제는 더 엄격해져야 한다",
    title_en: "Pet registration should become stricter",
    body_kr: "유기 동물 문제가 심각해지는 가운데 나는 반려동물 등록제가 지금보다 훨씬 엄격해져야 한다고 생각한다. 현재의 등록 제도는 사실상 강제성이 약해서 등록하지 않아도 큰 불이익이 없다는 점이 문제다. 물론 등록 절차가 번거롭고 비용이 든다는 반발도 이해할 수 있다. 그러나 책임감 없이 동물을 키우다가 쉽게 버리는 문제를 해결하려면 명확한 법적 책임을 부여하는 것이 필수적이다. 등록을 의무화하고 위반 시 강한 처벌을 적용하는 나라들에서 유기 동물 수가 실제로 줄어든 사례도 있다. 나는 동물을 키우는 것이 권리인 만큼 책임도 함께 따라야 한다고 믿는다.",
    body_en: "Amid the worsening problem of abandoned animals, I think pet registration should become far stricter than it is now. The problem is that the current registration system is effectively weak in enforcement, so there's little real penalty for not registering. Of course, I understand the backlash that the registration process is cumbersome and costly. But to solve the problem of people irresponsibly raising and then easily abandoning animals, imposing clear legal responsibility is essential. There are cases in countries that mandate registration and apply strong penalties for violations where the number of abandoned animals has actually decreased. I believe that just as raising a pet is a right, responsibility must come with it.",
    questions: [
      { question_en: "What is the writer's stance on pet registration laws?", options: ["They should be loosened", "They should become much stricter", "They should be abolished", "They have no relation to animal abandonment"], answerIndex: 1 },
      { question_en: "What complaint does the writer acknowledge about registration?", options: ["It is too easy and quick", "The process is cumbersome and costs money", "It doesn't apply to dogs", "It requires no paperwork at all"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "재난 문자, 너무 잦은 것 아닌가",
    title_en: "Are emergency alerts too frequent?",
    body_kr: "휴대폰으로 오는 재난 문자가 하루에도 여러 번 울리는 것을 보며 나는 이 제도에 개선이 필요하다고 생각한다. 물론 실제 위험 상황에서 신속하게 정보를 전달받아 대피할 수 있다는 점에서 이 제도의 가치는 부정할 수 없다. 그러나 지역과 무관하거나 이미 지난 정보, 혹은 경미한 사안까지 반복적으로 발송되면서 정작 중요한 경보에 둔감해지는 부작용이 생기고 있다. 실제로 많은 사람들이 재난 문자 알림을 꺼 버리는 현상이 늘어나고 있다는 점은 심각하게 받아들여야 한다. 나는 문자의 발송 기준을 더 정교하게 나누고 지역과 위험도에 맞게 선별적으로 보내는 시스템이 필요하다고 본다. 경보는 잦을수록 좋은 것이 아니라 정확할수록 좋은 것이다.",
    body_en: "Seeing emergency alert texts on my phone go off several times a day, I think this system needs improvement. Of course, the value of this system in allowing people to quickly receive information and evacuate during real danger can't be denied. But as alerts unrelated to one's area, already-past information, or even minor matters get sent repeatedly, a side effect emerges where people become desensitized to genuinely important warnings. The fact that many people are increasingly turning off emergency alert notifications should be taken seriously. I think a system is needed that more precisely refines the criteria for sending alerts and selectively sends them based on region and risk level. Alerts aren't better the more frequent they are — they're better the more accurate they are.",
    questions: [
      { question_en: "What is the writer's stance on the current emergency alert system?", options: ["It should be sent even more frequently", "It needs improvement to reduce unnecessary alerts", "It should be abolished entirely", "It has no problems at all"], answerIndex: 1 },
      { question_en: "What value of the alert system does the writer acknowledge?", options: ["It guarantees no natural disasters occur", "It allows quick evacuation during real danger", "It saves phone battery", "It replaces the need for news broadcasts"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "구독 서비스 범람, 이대로 괜찮은가",
    title_en: "Is the flood of subscription services really fine?",
    body_kr: "영상, 음악, 배달까지 거의 모든 서비스가 구독 방식으로 바뀌고 있지만 나는 이 흐름이 소비자에게 반드시 유리하지만은 않다고 생각한다. 물론 초기 비용 없이 원하는 서비스를 필요한 만큼만 이용할 수 있다는 장점은 분명하다. 그러나 여러 구독 서비스가 늘어나면서 매달 빠져나가는 총 비용을 제대로 인식하지 못하는 사람들이 많다. 하나하나는 적은 금액이라도 합치면 상당한 지출이 되는데도 자동 결제 때문에 그 사실을 잊고 지내는 경우가 흔하다. 나는 구독을 무조건 줄이라는 것이 아니라 정기적으로 자신의 구독 목록을 점검하는 습관이 필요하다고 본다. 편리함에 익숙해질수록 소비에 대한 감각은 오히려 무뎌질 수 있다.",
    body_en: "Nearly every service, from video and music to delivery, is shifting to a subscription model, but I don't think this trend is necessarily favorable for consumers. Of course, the advantage of using desired services only as much as needed without upfront cost is clear. But as multiple subscription services increase, many people fail to properly recognize the total amount leaving their account each month. Even if each one is a small amount, combined they add up to considerable spending, yet automatic payments often make people forget this fact. I'm not saying to unconditionally cut subscriptions, but that a habit of regularly reviewing one's subscription list is needed. The more accustomed we get to convenience, the duller our sense of spending can become.",
    questions: [
      { question_en: "What is the writer's stance on the rise of subscription services?", options: ["Entirely beneficial with no drawbacks", "Not necessarily favorable, since costs add up unnoticed", "Should be banned by the government", "Has no effect on personal finances"], answerIndex: 1 },
      { question_en: "What advantage of subscriptions does the writer acknowledge?", options: ["They guarantee lower prices than one-time purchases", "They let people use services as needed without upfront cost", "They eliminate all monthly bills", "They require no internet connection"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "SNS 없는 삶이 더 행복할 수 있다",
    title_en: "Life without SNS can be happier",
    body_kr: "많은 사람들이 소셜 미디어 없이는 소통이 불가능하다고 말하지만 나는 오히려 SNS를 끊은 뒤 삶의 만족도가 높아질 수 있다고 생각한다. 물론 멀리 사는 친구나 가족과 소식을 주고받고 다양한 정보를 얻을 수 있다는 점은 SNS의 분명한 장점이다. 그러나 끊임없이 타인의 삶과 자신을 비교하게 만들고 알림에 시달리게 하는 부작용은 그 장점을 상쇄하고도 남는다. 실제로 SNS 사용을 줄인 사람들의 불안 수준이 낮아졌다는 연구 결과도 여러 차례 발표된 바 있다. 나는 완전히 끊는 것이 어렵다면 사용 시간을 제한하거나 알림을 꺼 두는 것만으로도 큰 변화를 경험할 수 있다고 본다. 결국 연결되어 있다는 느낌과 실제 행복은 다른 문제다.",
    body_en: "Many people say communication is impossible without social media, but I think life satisfaction can actually rise after quitting SNS. Of course, keeping in touch with friends and family who live far away and gaining diverse information are clear advantages of SNS. But the side effects of constantly comparing oneself to others' lives and being bombarded with notifications more than offset those advantages. Studies have repeatedly shown that people who reduced SNS use had lower anxiety levels. I think even if fully quitting is hard, limiting usage time or turning off notifications alone can bring a big change. In the end, feeling connected and actual happiness are different matters.",
    questions: [
      { question_en: "What is the writer's stance on quitting or reducing SNS use?", options: ["It always makes people lonelier", "It can raise life satisfaction and lower anxiety", "It should be legally required", "It has no measurable effect"], answerIndex: 1 },
      { question_en: "What advantage of SNS does the writer acknowledge?", options: ["It guarantees financial success", "It helps keep in touch with distant friends and family", "It eliminates all forms of loneliness", "It replaces the need for phone calls entirely"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "학교 시험 위주 평가는 바뀌어야 한다",
    title_en: "School evaluation based on exams should change",
    body_kr: "여전히 시험 점수 하나로 학생을 평가하는 방식이 지배적이지만 나는 이러한 평가 체계가 근본적으로 바뀌어야 한다고 생각한다. 물론 시험은 객관적이고 공정한 기준을 제공한다는 점에서 오랫동안 신뢰받아 온 방식이다. 그러나 창의력이나 협업 능력, 문제 해결 능력처럼 시험만으로는 측정할 수 없는 역량이 점점 더 중요해지고 있는 시대다. 암기 위주의 평가는 학생들에게 정답을 빨리 찾는 훈련만 시킬 뿐 스스로 질문을 던지는 힘을 키워 주지 못한다. 나는 프로젝트 기반 평가나 포트폴리오처럼 다양한 방식을 병행한다면 학생 개개인의 강점을 더 정확히 파악할 수 있다고 본다. 교육의 목표가 달라졌다면 평가 방식도 함께 달라져야 한다.",
    body_en: "The practice of evaluating students based on a single exam score is still dominant, but I think this evaluation system needs to fundamentally change. Of course, exams have long been trusted for providing an objective, fair standard. But we're in an era where abilities like creativity, collaboration, and problem-solving, which exams alone can't measure, are becoming more and more important. Memorization-focused evaluation only trains students to quickly find correct answers and fails to build the ability to ask their own questions. I think combining various methods like project-based evaluation or portfolios can more accurately capture each student's individual strengths. If the goals of education have changed, the way we evaluate should change along with them.",
    questions: [
      { question_en: "What is the writer's stance on exam-based evaluation in schools?", options: ["It should remain the only method", "It should fundamentally change to include other methods", "It should be replaced solely by grades from parents", "It has no relation to creativity"], answerIndex: 1 },
      { question_en: "What strength of exams does the writer acknowledge?", options: ["They measure creativity best", "They provide an objective, fair standard", "They eliminate the need for teachers", "They guarantee future job success"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "일부 관광객의 소란, 규제만이 답은 아니다",
    title_en: "Tourist misbehavior isn't solved by regulation alone",
    body_kr: "관광객들의 소음이나 무례한 행동으로 인한 주민 불만이 늘어나면서 강력한 규제를 요구하는 목소리가 커지고 있지만 나는 규제만으로는 근본적인 해결이 어렵다고 생각한다. 물론 벌금이나 출입 제한 같은 즉각적인 조치가 문제를 일부 줄일 수 있다는 점은 인정한다. 그러나 대부분의 문제는 관광객이 현지 문화나 규범을 제대로 알지 못한 채 방문하는 데서 비롯된다. 규제만 강화하면 관광객들은 오히려 반감을 갖게 되고 지역에 대한 인상만 나빠질 위험이 있다. 나는 공항이나 숙소에서 현지 예절을 안내하는 교육적 접근을 병행해야 진짜 효과가 있다고 본다. 처벌보다 이해를 통한 예방이 더 지속 가능한 해법이다.",
    body_en: "As resident complaints about noise and rude behavior from tourists grow, calls for strong regulation are increasing, but I think regulation alone can't fundamentally solve the problem. Of course, I acknowledge that immediate measures like fines or entry restrictions can reduce the problem somewhat. But most problems arise from tourists visiting without properly knowing the local culture or norms. If only regulation is strengthened, tourists may instead develop resentment, risking only a worsened impression of the region. I think a real effect comes only when combined with an educational approach that guides local etiquette at airports or accommodations. Prevention through understanding is a more sustainable solution than punishment.",
    questions: [
      { question_en: "What is the writer's stance on solving tourist misbehavior through regulation?", options: ["Regulation alone is sufficient", "Regulation alone is insufficient without education", "No action should be taken at all", "Tourists should be banned entirely"], answerIndex: 1 },
      { question_en: "What benefit of regulation does the writer acknowledge?", options: ["It permanently changes tourist culture", "It can reduce the problem somewhat through immediate measures", "It increases tourism revenue", "It replaces the need for local laws"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "일과 삶의 경계는 분명해야 한다",
    title_en: "The line between work and life should stay clear",
    body_kr: "스마트폰 덕분에 언제 어디서나 업무 연락을 받을 수 있게 되었지만 나는 이런 상시 연결 상태가 오히려 삶의 질을 떨어뜨린다고 생각한다. 물론 긴급한 상황에서 빠르게 대응할 수 있다는 점은 회사 입장에서 효율적으로 보일 수 있다. 그러나 퇴근 후에도 메시지를 확인해야 한다는 압박감은 진정한 휴식을 방해하고 장기적으로 번아웃을 초래한다. 실제로 퇴근 후 업무 연락을 법으로 제한한 나라들에서 직원들의 정신 건강 지표가 개선되었다는 보고도 있다. 나는 정말 긴급한 사안이 아니라면 업무 시간 외 연락은 자제하는 문화가 자리 잡아야 한다고 본다. 쉼이 보장되지 않는 효율은 결국 오래가지 못한다.",
    body_en: "Thanks to smartphones, we can now receive work contact anytime, anywhere, but I think this constant connectivity actually lowers quality of life. Of course, being able to respond quickly in urgent situations may look efficient from the company's perspective. But the pressure to check messages even after work hours interferes with genuine rest and leads to burnout in the long run. There are indeed reports that in countries that legally restrict work contact after hours, employees' mental health indicators improved. I think a culture should take hold where contact outside work hours is avoided unless truly urgent. Efficiency that doesn't guarantee rest ultimately doesn't last.",
    questions: [
      { question_en: "What is the writer's stance on after-hours work contact?", options: ["It should be encouraged more", "It should be limited to protect rest and mental health", "It has no effect on burnout", "It should replace all daytime work"], answerIndex: 1 },
      { question_en: "What advantage of constant connectivity does the writer acknowledge?", options: ["It guarantees higher salaries", "It allows quick response in urgent situations", "It eliminates the need for meetings", "It improves employee creativity"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "1인 가구 증가, 사회가 준비되어야 한다",
    title_en: "As single-person households rise, society must prepare",
    body_kr: "1인 가구가 빠르게 늘어나고 있지만 여전히 많은 정책과 상품이 다인 가구를 기준으로 설계되어 있다. 나는 이제 사회 전반의 기준이 바뀌어야 한다고 생각한다. 물론 오랫동안 가족 단위가 사회의 기본 구성으로 여겨져 온 만큼 급격한 변화가 혼란을 줄 수 있다는 우려도 이해한다. 그러나 주거, 식품, 의료 서비스까지 1인 가구를 고려하지 않은 설계는 이미 많은 사람들에게 실질적인 불편을 주고 있다. 소형 주택 공급 부족이나 대용량 위주의 식품 포장이 대표적인 예다. 나는 1인 가구를 특별한 예외가 아니라 사회의 주요 구성원으로 받아들이는 정책 전환이 시급하다고 본다.",
    body_en: "Single-person households are rapidly increasing, but many policies and products are still designed around multi-person households. I think the overall standards of society need to change now. Of course, I understand the concern that rapid change could cause confusion, given that the family unit has long been considered the basic building block of society. But designs that fail to consider single-person households, from housing to food to medical services, are already causing real inconvenience to many people. The shortage of small housing units or food packaging geared toward large quantities are prime examples. I think a policy shift is urgently needed to treat single-person households not as a special exception but as major members of society.",
    questions: [
      { question_en: "What is the writer's stance on adapting society for single-person households?", options: ["Society should continue ignoring them", "Policies and products should adapt to include them", "Single-person households should be discouraged", "There is no real inconvenience for them"], answerIndex: 1 },
      { question_en: "What concern does the writer acknowledge about this change?", options: ["It would raise taxes significantly", "Rapid change could cause confusion given long-held norms", "It would eliminate family households entirely", "It has no relation to housing policy"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "패널티 없는 결석 제도는 필요하다",
    title_en: "Penalty-free absence policies are necessary",
    body_kr: "회사나 학교에서 결석이나 결근에 무조건 불이익을 주는 관행에 대해 나는 이제 바뀔 필요가 있다고 생각한다. 물론 무단으로 자주 빠지는 사람들에게 최소한의 규율이 필요하다는 반론은 일리가 있다. 그러나 몸이 아프거나 심리적으로 힘든 상황에서도 눈치를 보며 출근이나 등교를 강행하게 만드는 지금의 분위기는 오히려 전체의 생산성과 건강을 해친다. 아파도 나와야 한다는 압박 속에서 병을 더 키우거나 주변에 전염시키는 경우도 드물지 않다. 나는 일정 횟수의 자유로운 결석을 허용하되 남용을 막을 명확한 기준을 함께 마련한다면 충분히 합리적인 제도가 될 수 있다고 본다. 결국 억지로 나오는 것보다 제대로 쉬고 돌아오는 것이 모두에게 이득이다.",
    body_en: "Regarding the practice at companies or schools of unconditionally penalizing absences, I think it now needs to change. Of course, the counterargument that some minimal discipline is needed for people who frequently skip without notice makes sense. But the current atmosphere, which pressures people to force themselves to come to work or school even while sick or emotionally struggling, actually harms overall productivity and health. Under pressure to show up even while sick, it's not rare for illness to worsen or spread to others. I think allowing a certain number of free absences, while setting clear standards to prevent abuse, could become a reasonably sound system. In the end, properly resting and returning benefits everyone more than forcing oneself to show up.",
    questions: [
      { question_en: "What is the writer's stance on penalty-free absence policies?", options: ["All absences should be penalized without exception", "A reasonable number of free absences should be allowed", "Attendance rules should be eliminated entirely", "Sick employees should always come to work"], answerIndex: 1 },
      { question_en: "What counterargument does the writer acknowledge?", options: ["Absences never affect productivity", "Some discipline is needed for frequent unnotified absences", "Everyone should be allowed unlimited absences", "Illness never spreads at work"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "인플루언서 뒷광고, 처벌만으로 부족하다",
    title_en: "Undisclosed influencer ads: punishment alone isn't enough",
    body_kr: "협찬 사실을 숨기고 광고를 진행하는 인플루언서들의 뒷광고 문제가 반복해서 불거지지만 나는 강한 처벌만으로는 이 문제가 해결되지 않는다고 생각한다. 물론 소비자를 기만하는 행위에 대해 엄격한 법적 제재가 필요하다는 주장에는 동의한다. 그러나 처벌만 강화하면 적발되지 않는 교묘한 방식으로 회피하는 사례가 늘어날 뿐이라는 우려도 무시할 수 없다. 근본적인 문제는 협찬 표시가 소비자 눈에 잘 띄지 않게 만들어지는 플랫폼의 구조에도 있다. 나는 플랫폼 차원에서 협찬 여부를 명확하게 표시하도록 기술적으로 강제하는 시스템을 함께 도입해야 실효성이 생긴다고 본다. 처벌과 시스템 개선이 동시에 이루어져야 진짜 변화가 가능하다.",
    body_en: "The problem of influencers running undisclosed sponsored ads keeps resurfacing, but I don't think strong punishment alone will solve this. Of course, I agree that strict legal sanctions are needed for deceiving consumers. But the concern that strengthening punishment alone will only increase cases of clever evasion that avoid detection can't be ignored. The root problem also lies in the platform structure that makes sponsorship disclosures hard for consumers to notice. I think real effectiveness comes only when a system that technically forces clear sponsorship labeling at the platform level is introduced together with punishment. Real change is only possible when punishment and system improvement happen simultaneously.",
    questions: [
      { question_en: "What is the writer's stance on solving undisclosed influencer ads?", options: ["Punishment alone is sufficient", "Punishment alone is insufficient without platform-level system changes", "No action is needed at all", "Influencers should be banned from advertising entirely"], answerIndex: 1 },
      { question_en: "What point does the writer agree with regarding punishment?", options: ["Punishment should be eliminated entirely", "Strict legal sanctions for deceiving consumers are needed", "Fines should never exceed a small amount", "Punishment always solves deception completely"], answerIndex: 1 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "재활용 분리배출, 더 단순해져야 한다",
    title_en: "Recycling sorting should become simpler",
    body_kr: "복잡한 분리배출 기준 때문에 재활용률이 오히려 떨어진다는 지적이 있는데 나는 이 문제를 심각하게 받아들여야 한다고 생각한다. 물론 세밀한 분류가 재활용의 질을 높인다는 원칙 자체는 타당하다. 그러나 기준이 지나치게 복잡하고 지역마다 다르기 때문에 많은 사람들이 혼란스러워하다가 결국 대충 버리게 되는 역효과가 발생한다. 실제로 분리배출 기준을 간소화한 지역에서 오히려 재활용률이 높아졌다는 사례도 있다. 나는 정확성을 조금 포기하더라도 누구나 쉽게 이해할 수 있는 단순한 기준을 마련하는 것이 현실적으로 더 효과적이라고 본다. 아무리 좋은 제도라도 사람들이 따르지 못하면 의미가 없다.",
    body_en: "There's criticism that complicated sorting standards actually lower the recycling rate, and I think this problem should be taken seriously. Of course, the principle that detailed sorting improves recycling quality is itself valid. But because the standards are excessively complex and differ by region, many people get confused and end up just throwing things away carelessly, producing a counterproductive effect. There are indeed cases where regions that simplified their sorting standards saw recycling rates actually rise. I think establishing simple standards that anyone can easily understand, even at some cost to precision, is more realistically effective. No matter how good a system is, it's meaningless if people can't follow it.",
    questions: [
      { question_en: "What is the writer's stance on current recycling sorting standards?", options: ["They should become even more detailed", "They should be simplified to improve compliance", "They should be abolished entirely", "They have no effect on recycling rates"], answerIndex: 1 },
      { question_en: "What principle does the writer acknowledge as valid?", options: ["Detailed sorting improves recycling quality", "Simple sorting always fails", "Recycling doesn't matter environmentally", "Regional differences don't affect confusion"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "육아휴직, 아빠도 당연히 써야 한다",
    title_en: "Fathers should absolutely take parental leave too",
    body_kr: "육아휴직이 여전히 여성의 몫으로 여겨지는 분위기 속에서 나는 남성의 육아휴직 사용이 훨씬 더 당연해져야 한다고 생각한다. 물론 회사 내에서 남성 직원의 장기 공백이 업무에 지장을 줄 수 있다는 현실적인 우려는 이해할 만하다. 그러나 육아는 부모 모두의 책임이며 초기 몇 개월의 돌봄 경험은 이후 가족 관계 전체에 큰 영향을 미친다. 남성의 육아휴직 사용률이 높은 나라일수록 출산율과 여성의 경력 유지율이 동시에 개선되었다는 연구 결과도 있다. 나는 기업 문화와 인사 평가 방식이 함께 바뀌어야 실질적인 변화가 가능하다고 본다. 육아휴직을 쓰는 것이 특별한 배려가 아니라 당연한 권리로 자리 잡아야 한다.",
    body_en: "In an atmosphere where parental leave is still seen as something for women, I think men taking parental leave should become far more normalized. Of course, the practical concern that a male employee's long absence could disrupt work within a company is understandable. But childcare is the responsibility of both parents, and the caregiving experience of the first few months greatly affects the entire family relationship afterward. There is research showing that countries with higher rates of men taking parental leave saw improvements in both birth rates and women's career retention. I think real change is only possible when corporate culture and performance evaluation methods change together. Taking parental leave should become an ordinary right, not a special favor.",
    questions: [
      { question_en: "What is the writer's stance on fathers taking parental leave?", options: ["It should remain rare and discouraged", "It should become far more normalized", "It should be legally banned", "It has no effect on families"], answerIndex: 1 },
      { question_en: "What concern does the writer acknowledge about men taking leave?", options: ["It could disrupt work due to long absence", "It always lowers the birth rate", "Men are incapable of childcare", "It has no connection to company culture"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "스포츠 스타의 사생활, 어디까지 알아야 할까",
    title_en: "How much of an athlete's private life should we know?",
    body_kr: "유명 운동선수의 사생활이 언론과 대중의 관심 대상이 되는 것을 보며 나는 이런 관심이 지나치다고 생각한다. 물론 대중의 지지와 관심이 선수들에게 막대한 수입과 명예를 안겨 준다는 점에서 어느 정도의 관심은 불가피하다는 의견도 이해한다. 그러나 경기력이나 실력과 무관한 개인적인 영역까지 파헤치고 소비하는 것은 선수를 한 인간이 아니라 콘텐츠로 취급하는 태도다. 실제로 지나친 관심과 악플로 인해 정신적으로 고통받는 선수들의 사례가 계속 보도되고 있다. 나는 선수의 실력과 경기에 집중하는 것이 팬으로서 더 건강한 태도라고 본다. 존경은 사생활을 침해하지 않고도 충분히 표현할 수 있다.",
    body_en: "Watching famous athletes' private lives become the focus of media and public attention, I think this attention has gone too far. Of course, I understand the view that some degree of attention is unavoidable, given that public support and interest bring athletes enormous income and fame. But digging into and consuming personal areas unrelated to performance or skill is treating the athlete as content rather than as a human being. There continue to be reported cases of athletes suffering mentally due to excessive attention and malicious comments. I think focusing on an athlete's skill and games is a healthier attitude as a fan. Respect can be fully expressed without invading privacy.",
    questions: [
      { question_en: "What is the writer's stance on public attention to athletes' private lives?", options: ["It should increase even more", "It has gone too far and should focus on performance instead", "Athletes deserve no privacy at all", "It has no effect on athletes' mental health"], answerIndex: 1 },
      { question_en: "What point does the writer acknowledge about public interest?", options: ["It brings athletes income and fame", "It always improves athletes' performance", "It has no connection to media coverage", "It guarantees athletes' safety"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "결혼식 축의금 문화, 다시 생각해야 한다",
    title_en: "Rethinking wedding gift-money culture",
    body_kr: "정해진 금액의 축의금을 주고받는 결혼식 문화에 대해 나는 이제 조금 더 유연해질 필요가 있다고 생각한다. 물론 축의금이 결혼식 비용 부담을 나누고 서로의 관계를 확인하는 오랜 전통이라는 점은 인정한다. 그러나 친분의 정도와 무관하게 정해진 금액을 관행적으로 지불해야 한다는 부담감은 오히려 진심 어린 축하의 의미를 퇴색시킨다. 특히 형편이 어려운 사람들에게는 여러 번 겹치는 결혼식 초대가 상당한 경제적 압박이 되기도 한다. 나는 금액보다 참석 자체나 진심이 담긴 축하의 형태를 더 존중하는 문화가 자리 잡아야 한다고 본다. 전통은 시대에 맞게 유연하게 바뀔 수 있어야 한다.",
    body_en: "Regarding wedding culture where people give and receive a fixed amount of gift money, I think it now needs to become a bit more flexible. Of course, I acknowledge that gift money is a long tradition that shares the burden of wedding costs and affirms relationships. But the pressure to conventionally pay a fixed amount regardless of the closeness of the relationship actually fades the meaning of sincere congratulation. Especially for people in difficult financial circumstances, multiple overlapping wedding invitations can become significant financial pressure. I think a culture should take hold that respects attendance itself or sincere forms of congratulation more than the amount. Tradition should be able to flexibly change with the times.",
    questions: [
      { question_en: "What is the writer's stance on wedding gift-money culture?", options: ["It should remain exactly as it is", "It should become more flexible than a fixed amount", "Gift money should be abolished by law", "It has no financial impact on anyone"], answerIndex: 1 },
      { question_en: "What tradition does the writer acknowledge as valuable?", options: ["Gift money shares wedding costs and affirms relationships", "Weddings should never involve money", "Guests should always overpay", "Gift money guarantees a happy marriage"], answerIndex: 0 },
    ],
  },
  {
    level: "B2",
    genre: "opinion",
    title_kr: "온라인 중고 거래, 신뢰가 우선이다",
    title_en: "Online secondhand trading: trust comes first",
    body_kr: "중고 거래 플랫폼 이용이 급증하면서 편리함을 누리는 사람이 많지만 나는 신뢰를 지키기 위한 장치가 더 필요하다고 생각한다. 물론 저렴한 가격으로 필요한 물건을 구하고 안 쓰는 물건을 처분할 수 있다는 점에서 이 서비스의 유용함은 부정할 수 없다. 그러나 사진과 실제 물건이 다르거나 거래 후 연락이 끊기는 사기 사례가 끊임없이 발생하고 있다. 이런 문제는 결국 플랫폼 전체에 대한 불신으로 이어져 정직한 이용자들에게도 피해를 준다. 나는 거래 후기나 신원 확인 절차를 더욱 강화하는 것이 장기적으로 플랫폼의 신뢰도와 이용자 수 모두를 지키는 길이라고 본다. 편리함은 안전이 뒷받침될 때 비로소 지속 가능하다.",
    body_en: "As the use of secondhand trading platforms surges, many people enjoy the convenience, but I think more safeguards are needed to protect trust. Of course, the usefulness of this service in letting people find needed items cheaply and dispose of unused items can't be denied. But fraud cases where the photo differs from the actual item, or contact is cut off after a deal, keep occurring endlessly. These problems eventually lead to distrust of the entire platform, harming even honest users. I think strengthening transaction reviews or identity verification procedures further is, in the long run, the way to protect both the platform's credibility and its number of users. Convenience is only sustainable when backed by safety.",
    questions: [
      { question_en: "What is the writer's stance on secondhand trading platforms?", options: ["They need stronger trust safeguards despite their usefulness", "They should be shut down entirely", "They have no problems worth addressing", "Convenience matters more than safety"], answerIndex: 0 },
      { question_en: "What usefulness of the platforms does the writer acknowledge?", options: ["They guarantee no fraud ever occurs", "They let people find cheap items and sell unused ones", "They replace the need for stores entirely", "They are only used by young people"], answerIndex: 1 },
    ],
  },
];
