import type { RawPassage } from "./types";

export const READING_C2_ESSAY: RawPassage[] = [
  {
    level: "C2",
    genre: "essay",
    title_kr: "사소한 거짓말의 윤리",
    title_en: "The ethics of small lies",
    body_kr: "누군가의 안부를 물을 때 우리는 대개 진심을 다 말하지 않습니다. 괜찮지 않아도 괜찮다고 답하는 것은 거짓말이라기보다 사회적 윤활유에 가깝습니다. 문제는 이 관행이 어디까지 확장될 수 있는가입니다. 상대를 배려하려는 의도가 있다고 해서 모든 왜곡이 정당화되지는 않습니다. 특히 정보의 불균형이 클 때, 사소한 거짓은 상대의 판단을 조용히 왜곡합니다. 의료 현장에서 예후를 완곡하게 전달하는 관행이 대표적인 예입니다. 환자를 배려한다는 명분 아래 정작 환자의 자기결정권이 침해될 수 있습니다. 반대로 모든 진실을 가감 없이 전달하는 것도 능사는 아닙니다. 진실은 전달 방식과 시점에 따라 전혀 다른 효과를 냅니다. 결국 중요한 것은 거짓과 진실의 이분법이 아니라 누구를 위한 배려인가라는 질문입니다. 상대의 이익을 가장한 자기 편의는 정당화되기 어렵습니다.",
    body_en: "When we ask after someone's wellbeing, we usually do not say the whole truth. Answering that we are fine when we are not is less a lie than social lubricant. The question is how far this practice can be stretched. Having a caring intention does not justify every distortion. Especially when there is a large information gap, a small lie quietly distorts the other person's judgment. Softening a prognosis in medical settings is a representative example. Under the name of caring for the patient, the patient's right to self-determination can in fact be violated. Conversely, delivering the whole truth without any tact is not always the answer either. Truth produces entirely different effects depending on how and when it is delivered. In the end, what matters is not the binary of lie versus truth but the question of whose interest the tact serves. Convenience disguised as concern for the other is hard to justify.",
    questions: [
      { question_en: "What is given as a representative example of tactful untruth?", options: ["Softening a medical prognosis","Advertising slogans","Job interview answers","Political campaign promises"], answerIndex: 0 },
      { question_en: "What question does the writer say ultimately matters?", options: ["Whether lying is illegal","How often people lie","Whose interest the tact serves","Whether the statement is technically false"], answerIndex: 2 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "익명성과 책임",
    title_en: "Anonymity and responsibility",
    body_kr: "온라인 공간에서 익명성은 오랫동안 표현의 자유를 지키는 방패로 여겨져 왔습니다. 신원을 밝히기 어려운 이들이 부당한 권력을 고발할 수 있었던 것도 이 덕분입니다. 그러나 같은 익명성이 책임을 지우지 않는 발언의 온상이 되기도 합니다. 얼굴이 드러나지 않을 때 사람들은 평소라면 삼갔을 말을 훨씬 쉽게 내뱉습니다. 심리학에서는 이를 탈개인화라는 개념으로 설명해 왔습니다. 자신을 집단의 일부로 인식할수록 개별 행위에 대한 책임감은 옅어진다는 것입니다. 실명제를 도입하면 문제가 해결될 것이라는 기대는 여러 나라에서 시험되었지만 효과는 제한적이었습니다. 표현의 위축이라는 부작용만 남긴 사례도 적지 않습니다. 결국 핵심은 신원 공개 여부가 아니라 행위와 결과를 연결하는 구조에 있습니다. 플랫폼이 발언의 이력과 맥락을 추적 가능하게 설계할 때 책임은 비로소 실질화됩니다. 익명성 자체를 없애기보다 익명성이 남용되는 조건을 줄이는 편이 더 현실적인 접근입니다.",
    body_en: "In online spaces, anonymity has long been regarded as a shield protecting freedom of expression. It is thanks to anonymity that those unable to reveal their identity could expose unjust power. Yet the same anonymity also becomes a hotbed for speech that carries no accountability. When faces are not shown, people say things far more easily than they would normally hold back. Psychology has explained this through the concept of deindividuation. The more a person perceives themselves as part of a group, the thinner their sense of responsibility for individual acts becomes. The expectation that a real-name system would solve the problem was tested in several countries, but its effect proved limited. Not a few cases left behind only the side effect of chilled expression. In the end, the key lies not in whether identity is disclosed but in the structure that links act to consequence. Accountability becomes substantive only when a platform is designed to make the history and context of speech traceable. Reducing the conditions under which anonymity is abused is a more realistic approach than eliminating anonymity itself.",
    questions: [
      { question_en: "What concept explains reduced responsibility in anonymous groups?", options: ["Confirmation bias","Deindividuation","Groupthink","Cognitive dissonance"], answerIndex: 1 },
      { question_en: "What does the writer conclude is the more realistic approach?", options: ["Banning anonymous accounts entirely","Reducing the conditions under which anonymity is abused","Requiring government ID for all speech","Ignoring the problem"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "관용의 한계",
    title_en: "The limits of tolerance",
    body_kr: "관용은 다른 신념과 생활 방식을 존중하는 태도로 오랫동안 자유주의 사회의 미덕이었습니다. 그러나 관용이 무제한으로 확장될 수 있는지는 별개의 문제입니다. 관용 자체를 파괴하려는 세력에게도 관용을 베풀어야 하는가라는 질문이 그 지점에서 등장합니다. 철학자들은 이를 관용의 역설이라 불러왔습니다. 모든 견해를 동등하게 존중한다면 관용을 부정하는 견해까지 보호받게 되고, 그 결과 관용의 토대 자체가 무너질 수 있습니다. 그렇다고 관용의 경계를 아무나 임의로 정할 수 있다면 그것대로 위험합니다. 소수자를 억압하는 명분으로 관용의 이름이 악용된 사례는 역사에 드물지 않습니다. 결국 경계는 신념의 내용이 아니라 그 신념이 타인의 자유를 실질적으로 침해하는가라는 기준으로 그어져야 합니다. 말로 그치는 불쾌한 주장과 폭력을 선동하는 발언은 같은 잣대로 다룰 수 없습니다. 관용은 무제한의 수용이 아니라 갈등을 규율하는 조건부 원칙으로 이해될 때 비로소 지속 가능해집니다.",
    body_en: "Tolerance, as an attitude of respecting different beliefs and ways of life, has long been a virtue of liberal societies. But whether tolerance can be extended without limit is a separate question. The question of whether tolerance should even be granted to forces seeking to destroy tolerance itself arises at that point. Philosophers have called this the paradox of tolerance. If every view is respected equally, then even views that deny tolerance come to be protected, and the very foundation of tolerance can collapse as a result. Yet it is equally dangerous if anyone can arbitrarily set the boundary of tolerance. Cases in which the name of tolerance was abused as a pretext for oppressing minorities are not rare in history. In the end, the boundary must be drawn not by the content of a belief but by the standard of whether that belief actually infringes on others' freedom. An unpleasant claim that remains mere speech and speech that incites violence cannot be treated by the same measure. Tolerance becomes sustainable only when it is understood not as unlimited acceptance but as a conditional principle that regulates conflict.",
    questions: [
      { question_en: "What do philosophers call the problem of unlimited tolerance?", options: ["The consent dilemma","The freedom fallacy","The paradox of tolerance","The liberty trap"], answerIndex: 2 },
      { question_en: "By what standard does the writer say boundaries should be drawn?", options: ["Whether a belief is old","Whether a belief is religious","Whether a belief actually infringes on others' freedom","Whether a belief is popular"], answerIndex: 2 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "소유와 정체성",
    title_en: "Ownership and identity",
    body_kr: "우리는 종종 소유물을 통해 자신을 설명합니다. 어떤 차를 몰고 어떤 동네에 사는지가 정체성의 일부처럼 여겨지곤 합니다. 이러한 경향은 소비 사회에서 새롭게 만들어진 것이 아니라 오래된 심리적 기제에 뿌리를 두고 있습니다. 심리학자들은 사람과 소유물 사이의 이러한 결합을 확장된 자아라는 개념으로 설명해 왔습니다. 물건을 잃어버릴 때 단순한 손실 이상의 상실감을 느끼는 이유도 여기에 있습니다. 문제는 이 결합이 자본에 의해 손쉽게 동원된다는 점입니다. 광고 산업은 물건이 곧 자아를 완성한다는 메시지를 정교하게 반복해 왔습니다. 그 결과 소비는 필요를 채우는 행위에서 정체성을 증명하는 행위로 변질됩니다. 흥미로운 점은 경험에 대한 지출이 물건에 대한 지출보다 만족감을 더 오래 지속시킨다는 연구 결과입니다. 경험은 소유물처럼 비교당하지 않고 기억으로 재구성되기 때문입니다. 소유가 정체성을 대신할 수 없다는 사실을 자각하는 것이야말로 소비주의에서 벗어나는 첫걸음입니다.",
    body_en: "We often explain ourselves through our possessions. What car we drive and what neighborhood we live in are often treated as part of our identity. This tendency was not newly created by consumer society but is rooted in an old psychological mechanism. Psychologists have explained this bond between a person and their possessions through the concept of the extended self. This is also why losing an object makes us feel a loss greater than the mere material one. The problem is that this bond is easily mobilized by capital. The advertising industry has elaborately repeated the message that objects complete the self. As a result, consumption is transformed from an act that fills a need into an act that proves identity. An interesting finding is that spending on experiences sustains satisfaction longer than spending on objects. That is because experiences, unlike possessions, are not compared but reconstructed as memory. Recognizing that ownership cannot substitute for identity is the first step toward escaping consumerism.",
    questions: [
      { question_en: "What concept explains the bond between people and possessions?", options: ["Social proof","The endowment effect","Cognitive dissonance","The extended self"], answerIndex: 3 },
      { question_en: "Why does spending on experiences sustain satisfaction longer?", options: ["Experiences are cheaper","Experiences do not fade","Experiences are shared more often","Experiences are reconstructed as memory rather than compared"], answerIndex: 3 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "약속의 구속력",
    title_en: "The binding force of a promise",
    body_kr: "약속은 법적 강제력이 없어도 사람을 움직이는 힘을 지닙니다. 왜 우리는 지키지 않아도 처벌받지 않을 말에 스스로를 묶는 것일까요. 철학자들은 약속의 구속력이 미래의 자신을 현재의 자신이 통제하려는 시도라고 설명해 왔습니다. 불확실한 세계에서 상대가 예측 가능하게 행동하리라는 믿음은 관계를 지탱하는 최소한의 기반입니다. 그 기반이 없다면 매번 계약과 담보를 동원해야 하고, 그 비용은 감당하기 어려울 만큼 커집니다. 약속을 지키는 관행이 사회 전체의 거래 비용을 낮추는 셈입니다. 그렇다고 모든 약속이 절대적으로 지켜져야 하는 것은 아닙니다. 상황이 근본적으로 변했을 때조차 약속을 고집하는 것은 오히려 관계를 해칠 수 있습니다. 중요한 것은 약속을 어길 때 그 이유를 투명하게 밝히고 상대의 손실을 인정하는 태도입니다. 침묵 속의 파기가 신뢰를 무너뜨리는 반면, 설명이 동반된 파기는 신뢰를 완전히 파괴하지 않습니다. 약속의 진정한 가치는 지키는 행위 자체보다 그것을 대하는 정직함에 있는지도 모릅니다.",
    body_en: "A promise has the power to move people even without legal force behind it. Why do we bind ourselves to words we will not be punished for breaking? Philosophers have explained that the binding force of a promise is an attempt by the present self to control the future self. In an uncertain world, the belief that the other party will act predictably is the minimal foundation that sustains a relationship. Without that foundation, contracts and collateral would have to be mobilized every time, and the cost would grow unbearably large. The practice of keeping promises, in effect, lowers the transaction costs of society as a whole. That does not mean every promise must be kept absolutely. Insisting on a promise even when circumstances have fundamentally changed can in fact harm the relationship. What matters is the attitude of transparently disclosing the reason when breaking a promise and acknowledging the other party's loss. While a silent breach destroys trust, a breach accompanied by an explanation does not destroy it completely. The true value of a promise may lie not in the act of keeping it itself but in the honesty with which it is treated.",
    questions: [
      { question_en: "What does keeping promises do for society, according to the passage?", options: ["Eliminates the need for trust","Increases legal disputes","Lowers overall transaction costs","Reduces the need for communication"], answerIndex: 2 },
      { question_en: "What matters most when a promise must be broken?", options: ["Breaking it silently to avoid conflict","Transparently explaining the reason and acknowledging loss","Never breaking it under any circumstance","Offering monetary compensation only"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "죄책감과 수치심",
    title_en: "Guilt and shame",
    body_kr: "죄책감과 수치심은 흔히 같은 감정으로 혼동되지만 심리학은 둘을 명확히 구분합니다. 죄책감은 특정한 행위에 대한 후회이고, 수치심은 존재 전체에 대한 부정적 평가입니다. 잘못을 저질렀을 때 죄책감을 느끼는 사람은 그 행위를 바로잡으려 노력합니다. 반면 수치심을 느끼는 사람은 자신을 숨기거나 방어하는 데 에너지를 씁니다. 이 차이는 사소해 보이지만 행동의 결과에서 극명하게 갈립니다. 죄책감은 관계를 회복시키는 방향으로 작동하는 반면, 수치심은 오히려 고립을 심화시킵니다. 그럼에도 많은 교육과 훈육이 수치심을 지렛대로 삼아 왔습니다. 아이를 나무랄 때 행동이 아니라 인격을 지적하는 말이 대표적인 예입니다. 그런 말은 단기적으로 순응을 이끌어 낼 수 있지만 장기적으로는 자존감을 갉아먹습니다. 건강한 도덕적 발달은 행위와 자아를 분리하는 언어에서 시작됩니다. 잘못을 지적하되 존재를 부정하지 않는 화법이 그래서 중요합니다.",
    body_en: "Guilt and shame are often confused as the same emotion, but psychology draws a clear distinction between the two. Guilt is regret over a specific act, while shame is a negative evaluation of one's entire being. A person who feels guilt after doing something wrong tends to work to correct that act. A person who feels shame, by contrast, spends energy hiding or defending themselves. This difference looks trivial but diverges sharply in its behavioral consequences. Guilt tends to operate in a direction that restores relationships, while shame instead deepens isolation. Even so, much education and discipline have used shame as a lever. A representative example is criticizing a child's character rather than their behavior when scolding them. Such words can produce compliance in the short term but erode self-esteem in the long run. Healthy moral development begins with language that separates the act from the self. That is why it matters to point out a wrong without denying the person's worth.",
    questions: [
      { question_en: "How does guilt differ from shame according to the passage?", options: ["Guilt targets a specific act; shame targets the whole self","Guilt lasts longer than shame","Guilt is rare; shame is common","Guilt is public; shame is private"], answerIndex: 0 },
      { question_en: "What is a representative example of shame-based discipline?", options: ["Criticizing a child's character rather than their behavior","Offering rewards for good behavior","Ignoring misbehavior","Explaining consequences calmly"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "선의의 거짓말과 신뢰",
    title_en: "White lies and trust",
    body_kr: "선의의 거짓말은 관계를 부드럽게 만든다는 통념이 널리 퍼져 있습니다. 그러나 최근 연구들은 이 통념에 의문을 제기합니다. 작은 거짓말이 발각되었을 때 상대가 느끼는 배신감은 거짓말의 크기와 비례하지 않는다는 것입니다. 오히려 사소한 거짓일수록 왜 굳이 그랬는지에 대한 의문이 신뢰 전반으로 번지는 경우가 많습니다. 이는 사람들이 거짓말의 내용보다 거짓말을 하는 성향 자체를 판단의 근거로 삼기 때문입니다. 한 번의 작은 거짓이 발견되면 상대는 다른 발언들도 소급하여 의심하기 시작합니다. 그렇다고 모든 진실을 여과 없이 전달하는 것이 대안이 되지는 못합니다. 연구자들이 제안하는 절충안은 침묵할 자유를 넓히는 것입니다. 굳이 답하지 않아도 되는 질문에는 답을 피할 수 있어야 한다는 것입니다. 거짓을 말하지 않으면서도 모든 것을 말하지 않을 권리를 인정할 때, 관계는 오히려 더 정직해질 수 있습니다. 정직은 침묵을 배제하지 않습니다.",
    body_en: "The common belief that white lies smooth over relationships is widespread. Recent research, however, questions this belief. The betrayal a person feels upon discovering a small lie is not proportional to the size of the lie. In fact, the smaller the lie, the more often the question of why it was necessary at all spreads into doubt about trust as a whole. This is because people use the tendency to lie itself, rather than the content of the lie, as the basis for judgment. Once a single small lie is discovered, the other party begins to retroactively doubt other statements as well. That does not mean delivering the unfiltered truth in every instance becomes the alternative. The compromise researchers propose is to widen the freedom to remain silent. Questions one need not answer should be allowed to go unanswered. When the right not to say everything is recognized without ever lying, relationships can actually become more honest. Honesty does not exclude silence.",
    questions: [
      { question_en: "What do people use as the basis for judging a small lie, per the research?", options: ["The tendency to lie itself, not the content","The size of the lie only","The relationship's length","The listener's mood"], answerIndex: 0 },
      { question_en: "What compromise do researchers propose?", options: ["Widening the freedom to remain silent","Requiring full disclosure at all times","Banning small talk","Legal penalties for white lies"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "공정함이라는 감각",
    title_en: "The sense of fairness",
    body_kr: "공정함에 대한 감각은 이성적 계산 이전에 직관적으로 작동합니다. 원숭이에게 같은 과제를 시키고 서로 다른 보상을 주는 실험은 이를 잘 보여줍니다. 더 적은 보상을 받은 개체는 과제 자체를 거부하며 분노에 가까운 반응을 보였습니다. 이는 공정함이 인간만의 학습된 규범이 아니라 오래된 진화적 유산일 가능성을 시사합니다. 문제는 이 직관이 절대적 기준에 대한 것이 아니라 상대적 비교에 대한 것이라는 점입니다. 사람들은 자신의 처지가 개선되었더라도 남과 비교해 뒤처졌다고 느끼면 불공정하다고 판단합니다. 이러한 경향은 정책 설계자에게 까다로운 과제를 안깁니다. 총량이 늘어도 배분의 격차가 눈에 띄면 정책은 지지를 얻기 어렵습니다. 반대로 절차가 투명하게 공개될 때 사람들은 결과의 불평등을 더 쉽게 받아들입니다. 결과의 공정함 못지않게 과정의 공정함이 수용 여부를 좌우하는 셈입니다. 정책이 성공하려면 무엇을 나눌지보다 어떻게 나누는지를 설명하는 데 더 많은 공을 들여야 합니다.",
    body_en: "The sense of fairness operates intuitively before any rational calculation. An experiment giving monkeys the same task but different rewards demonstrates this well. The individual receiving the smaller reward rejected the task itself, showing a response close to anger. This suggests that fairness may not be a norm learned uniquely by humans but an old evolutionary inheritance. The problem is that this intuition concerns not an absolute standard but a relative comparison. People judge a situation as unfair when they feel they have fallen behind others, even if their own condition has improved. This tendency poses a tricky challenge for policy designers. Even when the total pie grows, a policy struggles to gain support if the gap in distribution is visible. Conversely, when the process is transparently disclosed, people accept inequality of outcome more readily. The fairness of the process, no less than the fairness of the outcome, determines whether it is accepted. For a policy to succeed, more effort must go into explaining how the pie is divided than into explaining what is divided.",
    questions: [
      { question_en: "What did the monkey experiment suggest about fairness?", options: ["It disappears with training","It may be an old evolutionary inheritance","It is purely a human cultural invention","It only applies to monetary rewards"], answerIndex: 1 },
      { question_en: "What helps people accept an unequal outcome, per the passage?", options: ["A transparently disclosed process","Government mandates","Anonymity of recipients","A larger total pie only"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "용서의 조건",
    title_en: "The conditions for forgiveness",
    body_kr: "용서는 종종 관계를 회복하는 미덕으로 칭송받지만 그 조건을 따져 보면 훨씬 복잡한 문제입니다. 가해자가 진심으로 반성하지 않은 상태에서 이루어지는 용서는 피해자에게 또 다른 짐을 지웁니다. 화해를 강요받는 분위기 속에서 피해자는 감정을 억누르고 관계를 이어가야 한다는 압박을 느낍니다. 이는 용서를 사회적 규범으로 만들 때 특히 두드러지는 부작용입니다. 반면 진정한 용서는 강요가 아니라 시간과 자율성 속에서 자연스럽게 형성됩니다. 심리학 연구는 용서가 가해자를 위한 것이 아니라 피해자 자신을 위한 것일 때 지속 가능하다고 말합니다. 분노를 계속 품는 것이 정신 건강에 미치는 부담을 줄이려는 선택으로서의 용서입니다. 그렇다고 모든 잘못을 반드시 용서해야 하는 것은 아닙니다. 용서하지 않을 권리 또한 존중받아야 할 선택지입니다. 사과와 반성이 결여된 상태에서 성급하게 이루어지는 화해는 오히려 같은 잘못을 반복시킬 위험이 있습니다. 결국 용서는 결과가 아니라 피해자가 스스로 선택할 수 있는 과정으로 이해되어야 합니다.",
    body_en: "Forgiveness is often praised as a virtue that restores relationships, but examining its conditions reveals a far more complex issue. Forgiveness granted while the offender has not truly reflected places yet another burden on the victim. Under pressure to reconcile, the victim feels compelled to suppress their feelings and continue the relationship. This is a side effect that becomes especially pronounced when forgiveness is turned into a social norm. Genuine forgiveness, by contrast, forms naturally through time and autonomy rather than compulsion. Psychological research says forgiveness is sustainable when it is for the victim's own sake rather than for the offender's. It is forgiveness chosen as a way to reduce the burden that continued anger places on mental health. That does not mean every wrong must necessarily be forgiven. The right not to forgive is also an option that deserves respect. Reconciliation rushed in the absence of apology and reflection risks repeating the same wrong. In the end, forgiveness should be understood not as an outcome but as a process the victim can choose for themselves.",
    questions: [
      { question_en: "When is forgiveness described as sustainable?", options: ["When it is demanded by society","When it happens immediately","When the offender requests it","When it is for the victim's own sake"], answerIndex: 3 },
      { question_en: "What risk does rushed reconciliation carry?", options: ["It eliminates anger permanently","It guarantees an apology","It risks repeating the same wrong","It always heals relationships"], answerIndex: 2 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "게으름에 대한 오해",
    title_en: "Misunderstanding laziness",
    body_kr: "게으름은 흔히 의지박약의 문제로 취급됩니다. 그러나 행동을 미루는 현상을 자세히 들여다보면 단순한 나태와는 거리가 멉니다. 많은 경우 미루기는 과제 자체보다 실패에 대한 두려움에서 비롯됩니다. 시도했다가 못하는 것보다 아예 시도하지 않는 편이 자존감을 덜 다치게 한다는 방어적 계산이 작동하는 것입니다. 완벽하게 해내야 한다는 압박이 클수록 이러한 회피는 더 심해지는 경향이 있습니다. 이는 게으름이 능력의 문제가 아니라 감정 조절의 문제에 가깝다는 것을 보여줍니다. 실제로 미루는 사람에게 의지력을 더 발휘하라고 다그치는 접근은 대체로 효과가 없습니다. 오히려 과제를 작게 쪼개고 실패의 기준을 낮추는 전략이 더 큰 효과를 낸다는 연구 결과가 축적되어 왔습니다. 자신을 탓하는 것이 습관이 되면 다음 시도는 더욱 미뤄집니다. 자기 비난의 악순환을 끊는 것이야말로 생산성을 회복하는 첫걸음입니다. 게으름을 도덕적 결함으로 낙인찍기 전에 그 이면의 두려움을 먼저 살펴야 하는 이유입니다.",
    body_en: "Laziness is commonly treated as a problem of weak will. But looking closely at the phenomenon of procrastination reveals something far from simple idleness. In many cases, procrastination stems not from the task itself but from fear of failure. A defensive calculation operates in which not trying at all hurts self-esteem less than trying and failing. The greater the pressure to perform perfectly, the more this avoidance tends to intensify. This shows that laziness is closer to a problem of emotional regulation than of ability. In fact, pushing a procrastinator to exert more willpower is generally ineffective. Research has instead accumulated showing that breaking a task into small pieces and lowering the bar for failure produces a greater effect. When self-blame becomes a habit, the next attempt is delayed even further. Breaking the vicious cycle of self-criticism is the first step toward restoring productivity. This is why the fear behind laziness must be examined before it is stigmatized as a moral flaw.",
    questions: [
      { question_en: "What does procrastination often stem from, per the passage?", options: ["Lack of deadlines","Poor time management tools","Low intelligence","Fear of failure"], answerIndex: 3 },
      { question_en: "What strategy is shown to be more effective than demanding willpower?", options: ["Monetary punishment","Public shaming","Stricter deadlines","Breaking tasks into small pieces and lowering the bar for failure"], answerIndex: 3 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "완벽주의의 대가",
    title_en: "The cost of perfectionism",
    body_kr: "완벽주의는 흔히 높은 성취와 동일시되지만 그 이면에는 상당한 대가가 숨어 있습니다. 완벽주의자는 결과가 아무리 좋아도 부족한 부분에만 시선을 고정합니다. 이러한 성향은 단기적으로 성과를 끌어올리는 것처럼 보이지만 장기적으로는 만성적인 불안과 소진으로 이어집니다. 연구자들은 완벽주의를 자기 지향형과 타인 지향형, 사회 부과형으로 구분해 왔습니다. 특히 타인의 기준에 맞추려는 사회 부과형 완벽주의가 정신 건강에 가장 해롭다는 것이 여러 연구에서 확인되었습니다. 실패를 용납하지 않는 환경에서 자란 사람일수록 이러한 성향을 내면화하기 쉽습니다. 문제는 완벽을 추구하는 태도와 탁월함을 추구하는 태도가 겉으로는 비슷해 보인다는 점입니다. 탁월함을 추구하는 사람은 실수에서 배우지만, 완벽을 추구하는 사람은 실수를 존재 자체의 결함으로 받아들입니다. 이 차이는 회복 탄력성에서 극명하게 드러납니다. 완벽주의에서 벗어나는 첫걸음은 충분히 좋다는 기준을 스스로 정의하는 데 있습니다. 성취의 크기보다 그 과정을 견디는 마음의 여유가 결국 지속 가능성을 좌우합니다.",
    body_en: "Perfectionism is commonly equated with high achievement, but a considerable cost hides behind it. A perfectionist fixates on what is lacking no matter how good the result is. This tendency seems to boost performance in the short term but leads to chronic anxiety and burnout in the long run. Researchers have divided perfectionism into self-oriented, other-oriented, and socially prescribed types. Multiple studies have confirmed that socially prescribed perfectionism, the drive to meet others' standards, is the most harmful to mental health. People raised in environments that do not tolerate failure are more likely to internalize this tendency. The problem is that the attitude of pursuing perfection and the attitude of pursuing excellence look similar on the surface. A person pursuing excellence learns from mistakes, while a person pursuing perfection takes mistakes as a flaw in their very being. This difference shows up sharply in resilience. The first step out of perfectionism lies in defining for oneself a standard of good enough. In the end, it is not the size of the achievement but the ease of mind to endure the process that determines sustainability.",
    questions: [
      { question_en: "Which type of perfectionism is most harmful to mental health?", options: ["Task-oriented perfectionism","Socially prescribed perfectionism","Time-oriented perfectionism","Self-oriented perfectionism"], answerIndex: 1 },
      { question_en: "How does a person pursuing excellence differ from one pursuing perfection?", options: ["They avoid all risk","They learn from mistakes rather than seeing them as personal flaws","They ignore feedback","They achieve less overall"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "침묵의 무게",
    title_en: "The weight of silence",
    body_kr: "회의 자리에서 아무도 반대하지 않았다는 사실이 곧 모두가 동의했다는 증거는 아닙니다. 침묵은 종종 동의보다 두려움이나 체념의 표현일 때가 많습니다. 조직 심리학에서는 이러한 현상을 조직적 침묵이라 부릅니다. 발언이 자신에게 불이익으로 돌아올 것이라는 학습된 믿음이 반복되면 구성원들은 점차 입을 닫습니다. 문제는 이 침묵이 조용히 조직 전체의 위험을 키운다는 점입니다. 재난이나 대형 사고의 사후 조사에서 반복적으로 발견되는 패턴이 바로 이것입니다. 위험 신호를 감지한 누군가가 있었지만 발언하지 못했다는 사실이 뒤늦게 드러나는 경우가 많습니다. 침묵을 깨는 문화를 만들기 위해서는 발언 자체를 장려하는 것만으로는 부족합니다. 발언한 사람이 실제로 불이익을 받지 않는다는 경험이 축적되어야 신뢰가 형성됩니다. 권한을 가진 사람이 먼저 자신의 실수를 인정하는 태도도 이러한 신뢰 형성에 중요한 역할을 합니다. 침묵이 안전을 의미하지 않는다는 사실을 조직이 받아들일 때 비로소 진짜 위험이 드러날 수 있습니다.",
    body_en: "The fact that no one objected in a meeting is not proof that everyone agreed. Silence is often an expression of fear or resignation rather than consent. Organizational psychology calls this phenomenon organizational silence. When the learned belief that speaking up will bring personal disadvantage repeats itself, members gradually stop speaking. The problem is that this silence quietly grows the risk to the whole organization. This is exactly the pattern repeatedly found in post-mortem investigations of disasters and major accidents. It is often revealed too late that someone had detected a warning sign but could not speak up. To build a culture that breaks silence, merely encouraging people to speak is not enough. Trust forms only once the experience accumulates that those who speak up do not actually suffer disadvantage. The attitude of those in power admitting their own mistakes first also plays an important role in building this trust. Only when an organization accepts that silence does not mean safety can the real danger come to light.",
    questions: [
      { question_en: "What is organizational silence often an expression of?", options: ["Fear or resignation rather than consent","Boredom","Genuine agreement","Efficiency"], answerIndex: 0 },
      { question_en: "What pattern is repeatedly found in disaster investigations?", options: ["Someone detected a risk but could not speak up","Too many people spoke at once","No one noticed any risk","Warnings were ignored intentionally by leadership"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "후회와 결정",
    title_en: "Regret and decision",
    body_kr: "후회는 흔히 피해야 할 감정으로 여겨지지만 그 기능을 들여다보면 이야기가 달라집니다. 심리학 연구에 따르면 사람들이 가장 오래 후회하는 것은 저지른 행동이 아니라 하지 않은 행동입니다. 시간이 지날수록 실패한 시도에 대한 후회는 옅어지는 반면 시도조차 하지 않은 일에 대한 후회는 오히려 짙어집니다. 이는 인간의 마음이 완결된 사건보다 미완의 가능성을 더 오래 붙들기 때문입니다. 이러한 비대칭은 의사 결정의 순간에 유용한 지침이 될 수 있습니다. 선택의 갈림길에서 두려움이 앞설 때, 몇 년 후 어느 쪽을 더 후회할지 자문해 보는 방법이 그것입니다. 다만 후회를 두려워한 나머지 무모한 결정을 정당화하는 함정도 경계해야 합니다. 모든 시도가 옳은 것은 아니며, 신중한 판단 없이 감행한 선택은 그 자체로 새로운 후회를 낳습니다. 결국 후회는 회피할 감정이 아니라 다음 선택을 위한 정보로 활용될 때 가치를 갖습니다. 지나간 선택을 곱씹는 데 머무르지 않고 그로부터 기준을 추출하는 태도가 중요합니다.",
    body_en: "Regret is commonly seen as an emotion to avoid, but looking at its function tells a different story. Psychological research shows that what people regret longest is not the actions they took but the actions they did not take. Regret over failed attempts fades over time, while regret over things not even attempted grows deeper instead. This is because the human mind holds onto unfinished possibilities longer than completed events. This asymmetry can become a useful guide at the moment of decision. At a fork in the road where fear takes the lead, one method is to ask which side one would regret more a few years from now. Still, one must also guard against the trap of justifying reckless decisions out of fear of regret. Not every attempt is right, and a choice ventured without careful judgment produces new regret of its own. In the end, regret has value not when avoided but when used as information for the next choice. What matters is not dwelling on a past choice but extracting a standard from it.",
    questions: [
      { question_en: "What do people regret longest, according to the research?", options: ["Nothing, over time","Actions they did not take","Actions they took and failed at","Decisions made by others"], answerIndex: 1 },
      { question_en: "What trap should be guarded against?", options: ["Never making decisions","Regretting too little","Avoiding all risk","Justifying reckless decisions out of fear of regret"], answerIndex: 3 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "동정과 연민의 차이",
    title_en: "The difference between pity and compassion",
    body_kr: "동정과 연민은 흔히 같은 뜻으로 쓰이지만 그 구조는 사뭇 다릅니다. 동정은 상대를 자신보다 낮은 위치에 두고 내려다보는 시선을 전제합니다. 반면 연민은 상대의 고통을 자신도 겪을 수 있는 일로 받아들이는 동등한 시선에서 출발합니다. 이 차이는 상대가 받아들이는 태도에서도 극명하게 드러납니다. 동정을 받은 사람은 종종 수치심을 느끼며 관계에서 위축됩니다. 반면 연민을 받은 사람은 존중받는다는 느낌 속에서 위로를 얻습니다. 문제는 두 감정이 표면적으로 비슷한 표정과 언어로 표현된다는 점입니다. 위로의 말을 건네는 사람조차 자신이 동정하는지 연민하는지 명확히 구분하지 못하는 경우가 많습니다. 연민을 실천하기 위해서는 상대의 처지를 상상하는 데서 그치지 않고 자신의 취약함을 함께 인정해야 합니다. 이는 자신도 언제든 같은 처지에 놓일 수 있다는 겸허함을 요구합니다. 결국 연민은 우월한 위치에서 베푸는 시혜가 아니라 같은 인간으로서의 연대에서 비롯됩니다.",
    body_en: "Pity and compassion are often used interchangeably, but their structures are quite different. Pity presupposes a gaze that looks down on the other from a position above them. Compassion, by contrast, starts from an equal gaze that accepts the other's suffering as something one could experience oneself. This difference is also starkly revealed in how the recipient responds. A person who receives pity often feels shame and withdraws from the relationship. A person who receives compassion, by contrast, finds comfort in feeling respected. The problem is that the two emotions are expressed through similar expressions and words on the surface. Even the person offering words of comfort often cannot clearly tell whether they are pitying or feeling compassion. To practice compassion, one must not stop at imagining the other's situation but also acknowledge one's own vulnerability together with it. This requires the humility of recognizing that one could be in the same situation at any time. In the end, compassion springs not from charity granted from a superior position but from solidarity as a fellow human being.",
    questions: [
      { question_en: "What does pity presuppose, according to the passage?", options: ["Complete equality","A gaze that looks down on the other","Shared suffering only","Financial superiority"], answerIndex: 1 },
      { question_en: "What does practicing compassion require, beyond imagining the other's situation?", options: ["Acknowledging one's own vulnerability","Public recognition","Avoiding eye contact","Offering money"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "자율성과 개입",
    title_en: "Autonomy and intervention",
    body_kr: "타인의 선택이 어리석어 보일 때 개입해야 하는가라는 질문은 오래된 윤리적 딜레마입니다. 자율성을 존중하는 전통은 성인이 자신의 삶을 스스로 결정할 권리를 최우선으로 둡니다. 그러나 그 결정이 명백히 해로운 결과로 이어질 것이 예견될 때조차 침묵해야 하는가라는 반문이 뒤따릅니다. 흡연이나 위험한 스포츠처럼 본인에게만 해가 미치는 행위와 타인에게 피해를 주는 행위를 구분하는 것이 전통적인 접근이었습니다. 그러나 현실에서는 이 구분이 생각만큼 깔끔하지 않습니다. 개인의 건강 악화는 결국 가족과 의료 체계에 부담을 전가하기 때문입니다. 자유주의 철학은 이러한 간접적 영향까지 개입의 근거로 삼을 경우 개입의 범위가 무한히 확장될 위험을 경고해 왔습니다. 그래서 등장한 절충안이 온정적 간섭주의를 최소화하되 정보 제공은 극대화하자는 원칙입니다. 선택을 대신해 주는 대신 선택의 결과를 명료하게 보여 주는 방식입니다. 넛지라 불리는 정책 설계가 이러한 절충의 대표적인 시도입니다. 결국 자율성 존중과 보호 사이의 균형점은 고정된 답이 아니라 매 사안마다 다시 그어야 하는 선입니다.",
    body_en: "The question of whether to intervene when another person's choice seems foolish is an old ethical dilemma. The tradition of respecting autonomy places the right of an adult to determine their own life above all else. But a counter-question follows: should one stay silent even when a decision is foreseen to lead to clearly harmful consequences? The traditional approach distinguished between acts that harm only oneself, such as smoking or dangerous sports, and acts that harm others. In reality, however, this distinction is not as clean as it seems. Deteriorating personal health ultimately shifts a burden onto family and the healthcare system. Liberal philosophy has warned that if such indirect effects are also taken as grounds for intervention, the scope of intervention risks expanding without limit. The compromise that emerged is the principle of minimizing paternalistic interference while maximizing the provision of information. It is a method of clearly showing the consequences of a choice rather than making the choice on someone's behalf. Policy design known as the nudge is a representative attempt at this kind of compromise. In the end, the balance between respecting autonomy and protection is not a fixed answer but a line that must be redrawn for each case.",
    questions: [
      { question_en: "What compromise principle emerged in the passage?", options: ["Ignoring indirect societal effects entirely","Minimizing paternalism while maximizing information provision","Legal punishment for poor choices","Banning all risky personal behavior"], answerIndex: 1 },
      { question_en: "What is given as a representative attempt at this compromise?", options: ["Mandatory health insurance","Nudge-based policy design","Public shaming campaigns","Total deregulation"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "습관의 도덕성",
    title_en: "The morality of habit",
    body_kr: "도덕적 행위를 논할 때 우리는 흔히 의식적인 선택을 전제합니다. 그러나 실제 행동의 상당수는 숙고 없이 습관에 의해 자동으로 실행됩니다. 아리스토텔레스는 이미 오래전에 덕이란 반복된 행위를 통해 형성되는 성품이라고 보았습니다. 옳은 일을 매번 의지로 선택하는 사람보다 옳은 일이 몸에 밴 사람이 더 안정적으로 덕을 실천한다는 것입니다. 이 관점은 도덕 교육의 방향에 중요한 시사점을 던집니다. 규칙을 암기시키는 것만으로는 충분하지 않으며, 반복된 경험을 통해 좋은 습관을 형성하도록 돕는 것이 더 근본적인 접근이라는 것입니다. 문제는 나쁜 습관 역시 같은 방식으로 형성된다는 점입니다. 차별적인 언행이나 무심한 태도가 반복을 통해 성찰 없이 굳어지는 경우가 대표적입니다. 이러한 습관은 당사자조차 자신이 잘못하고 있다는 인식 없이 지속됩니다. 습관을 교정하려면 그 행위가 일어나는 맥락 자체를 바꾸는 개입이 필요합니다. 결국 도덕성은 순간의 결단이 아니라 오랜 시간에 걸쳐 축적된 반복의 총합으로 완성됩니다.",
    body_en: "When we discuss moral action, we usually presuppose a conscious choice. In reality, however, a considerable portion of our behavior is executed automatically by habit, without deliberation. Aristotle already held long ago that virtue is a character formed through repeated action. A person for whom doing the right thing has become second nature practices virtue more stably than one who chooses it by will each time. This view offers an important implication for the direction of moral education. Merely having rules memorized is not enough; helping good habits form through repeated experience is the more fundamental approach. The problem is that bad habits are formed the same way. Discriminatory speech or an indifferent attitude hardening through repetition without reflection is a representative case. Such habits persist even without the person themselves recognizing that they are doing wrong. Correcting a habit requires intervention that changes the very context in which the behavior occurs. In the end, morality is completed not by a moment's decision but by the sum of repetition accumulated over a long time.",
    questions: [
      { question_en: "What did Aristotle consider virtue to be?", options: ["An innate trait","A character formed through repeated action","A single moral decision","A legal obligation"], answerIndex: 1 },
      { question_en: "What is needed to correct a bad habit, per the passage?", options: ["Memorizing more rules","Punishing the person publicly","Intervention that changes the context in which it occurs","Ignoring the behavior"], answerIndex: 2 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "비교의 함정",
    title_en: "The trap of comparison",
    body_kr: "인간은 절대적인 기준보다 상대적인 위치로 자신의 처지를 가늠하는 경향이 있습니다. 소득이 늘어도 주변 사람의 소득이 더 빨리 늘면 만족감은 오히려 줄어듭니다. 경제학자들은 이를 상대 소득 가설이라는 개념으로 설명해 왔습니다. 이러한 성향은 진화적으로 뿌리 깊은 것이어서 의지만으로 극복하기 어렵습니다. 문제는 이 비교의 대상이 디지털 환경에서 극적으로 확장되었다는 점입니다. 과거에는 이웃이나 동료가 비교의 준거였다면, 지금은 전 세계에서 가장 화려한 삶을 사는 소수가 그 자리를 차지합니다. 소셜 미디어에 노출되는 시간이 늘수록 삶의 만족도가 하락한다는 연구 결과는 이와 무관하지 않습니다. 사람들이 접하는 것은 타인의 편집된 순간일 뿐 전체 삶이 아니라는 사실을 알면서도 비교는 멈추지 않습니다. 이 함정에서 벗어나는 방법으로 제안되는 것이 비교의 방향을 바꾸는 것입니다. 타인과 비교하는 대신 과거의 자신과 비교하는 습관이 그 대안입니다. 비교 자체를 없앨 수 없다면 그 기준을 스스로 선택하는 것이 남은 유일한 통제력입니다.",
    body_en: "Humans tend to gauge their situation by relative position rather than an absolute standard. Even if one's income rises, satisfaction can actually fall if the incomes of those around them rise faster. Economists have explained this through the concept of the relative income hypothesis. This tendency is evolutionarily deep-rooted and hard to overcome by willpower alone. The problem is that the object of this comparison has expanded dramatically in the digital environment. While neighbors or colleagues once served as the reference point for comparison, that place is now occupied by a small number of people living the most glamorous lives worldwide. The research finding that life satisfaction declines as time spent on social media increases is not unrelated to this. Even knowing that what people encounter is only others' edited moments rather than their whole lives, the comparison does not stop. What is proposed as a way out of this trap is changing the direction of comparison. Comparing oneself to one's past self instead of to others is the alternative offered. If comparison itself cannot be eliminated, choosing its standard for oneself is the only control that remains.",
    questions: [
      { question_en: "What concept explains why satisfaction can fall despite rising income?", options: ["Diminishing marginal utility","The endowment effect","Loss aversion","The relative income hypothesis"], answerIndex: 3 },
      { question_en: "What alternative is proposed to escape the comparison trap?", options: ["Increasing income further","Ignoring statistics","Comparing oneself to one's past self","Avoiding all social contact"], answerIndex: 2 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "겸손이라는 미덕",
    title_en: "Humility as a virtue",
    body_kr: "겸손은 흔히 자신을 낮추는 태도로 오해되지만 철학적으로는 훨씬 정교한 개념입니다. 진정한 겸손은 자신을 과소평가하는 것이 아니라 자신의 능력과 한계를 정확하게 인식하는 태도입니다. 자신을 지나치게 낮추는 것도, 지나치게 높이는 것도 모두 현실을 왜곡하는 방식이라는 점에서 겸손의 반대편에 있습니다. 지적 겸손이라는 개념은 이러한 정의를 더 구체화합니다. 자신의 신념이 틀릴 수 있다는 가능성을 항상 열어 두는 태도가 그것입니다. 흥미로운 점은 지적 겸손이 자신감의 결여가 아니라는 것입니다. 오히려 자신의 판단에 근거가 있다는 것을 알면서도 새로운 증거 앞에서 기존 입장을 수정할 수 있는 유연함이 지적 겸손의 핵심입니다. 이러한 태도가 부족한 사람일수록 반대 의견을 위협으로 받아들이고 방어적으로 반응하는 경향을 보입니다. 조직에서 지적 겸손을 갖춘 리더가 이끄는 팀은 실수를 더 빨리 인정하고 학습 속도도 빠르다는 연구 결과가 있습니다. 결국 겸손은 자신을 축소하는 기술이 아니라 진실 앞에서 자신을 열어 두는 훈련입니다.",
    body_en: "Humility is often misunderstood as an attitude of lowering oneself, but philosophically it is a far more refined concept. True humility is not underestimating oneself but accurately recognizing one's own abilities and limits. Both excessively lowering and excessively elevating oneself distort reality, placing them on the opposite side of humility. The concept of intellectual humility further specifies this definition. It is the attitude of always keeping open the possibility that one's own belief could be wrong. Interestingly, intellectual humility is not a lack of confidence. Rather, the core of intellectual humility is the flexibility to revise one's existing position in the face of new evidence, even while knowing one's judgment has grounds. People who lack this attitude tend to take opposing opinions as threats and respond defensively. Research has found that teams led by leaders with intellectual humility admit mistakes faster and learn faster. In the end, humility is not a technique for shrinking oneself but a training in staying open to the truth.",
    questions: [
      { question_en: "What is intellectual humility, per the passage?", options: ["Always agreeing with others","Lacking confidence in one's judgment","Keeping open the possibility that one's belief could be wrong","Avoiding decisions"], answerIndex: 2 },
      { question_en: "What did research find about teams led by intellectually humble leaders?", options: ["They make fewer decisions","They avoid conflict entirely","They have lower morale","They admit mistakes and learn faster"], answerIndex: 3 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "익숙함과 무관심",
    title_en: "Familiarity and indifference",
    body_kr: "우리는 처음 마주하는 부조리에는 분노하지만 그 부조리가 반복되면 점차 무감각해집니다. 이러한 현상은 도덕적 나태가 아니라 인지적 적응이라는 보편적 기제에서 비롯됩니다. 뇌는 반복되는 자극에 대한 반응을 효율화하기 위해 감각의 강도를 낮추도록 설계되어 있습니다. 문제는 이 기제가 신체적 자극뿐 아니라 도덕적 판단에도 똑같이 적용된다는 점입니다. 매일 접하는 빈곤이나 불평등의 이미지는 처음의 충격을 점차 잃어 갑니다. 언론이 같은 문제를 반복해서 보도할수록 대중의 관심이 오히려 줄어드는 역설이 여기서 발생합니다. 활동가들은 이 무관심을 깨기 위해 익숙한 문제를 낯설게 보여 주는 전략을 고민해 왔습니다. 통계 대신 한 사람의 구체적인 이야기를 전면에 내세우는 방식이 대표적입니다. 추상적인 숫자보다 얼굴을 가진 개인의 서사가 감정적 반응을 더 강하게 불러일으키기 때문입니다. 그러나 이러한 전략도 반복되면 같은 무뎌짐을 겪습니다. 결국 무관심을 완전히 없앨 수는 없으며, 관심을 지속적으로 갱신하려는 의식적인 노력만이 그 간격을 메울 수 있습니다.",
    body_en: "We are outraged by an injustice the first time we encounter it, but as that injustice repeats, we gradually grow numb. This phenomenon springs not from moral laziness but from the universal mechanism of cognitive adaptation. The brain is designed to lower the intensity of sensation in order to make its response to repeated stimuli more efficient. The problem is that this mechanism applies equally to moral judgment, not just physical stimuli. Images of poverty or inequality encountered daily gradually lose their initial shock. The paradox arises here that the more the media repeatedly reports the same problem, the more public interest actually declines. Activists have pondered strategies to make familiar problems look unfamiliar again in order to break through this indifference. Foregrounding one person's concrete story instead of statistics is a representative example. This is because a narrative with a face evokes a stronger emotional response than an abstract number. But even this strategy suffers the same dulling once repeated. In the end, indifference cannot be eliminated entirely, and only a conscious effort to continually renew attention can fill the gap.",
    questions: [
      { question_en: "What mechanism causes moral numbness to repeated injustice?", options: ["Cognitive adaptation","Economic scarcity","Deliberate moral laziness","Legal desensitization"], answerIndex: 0 },
      { question_en: "What strategy do activists use to break through indifference?", options: ["Repeating the same statistics more often","Using louder advertising","Increasing news frequency","Foregrounding one person's concrete story"], answerIndex: 3 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "선택의 피로",
    title_en: "Decision fatigue",
    body_kr: "하루 동안 내려야 하는 선택의 수는 상상보다 훨씬 많습니다. 아침에 무엇을 입을지부터 저녁에 무엇을 먹을지까지, 의식하지 못하는 사이에도 의사 결정은 끊임없이 소모됩니다. 심리학자들은 이러한 소모를 결정 피로라는 개념으로 설명해 왔습니다. 의지력이 유한한 자원처럼 소진된다는 이 관점에 따르면 하루가 저물수록 판단의 질은 떨어질 수밖에 없습니다. 실제로 판사들이 오전에 내리는 가석방 결정이 오후보다 관대하다는 연구는 이 개념을 뒷받침하는 대표적인 사례로 인용되어 왔습니다. 물론 이 연구의 해석을 둘러싸고 학계에서는 여전히 논쟁이 있습니다. 그럼에도 불구하고 사소한 선택을 줄이는 것이 중요한 판단의 질을 지키는 전략이 될 수 있다는 함의는 널리 받아들여지고 있습니다. 일부 기업가들이 매일 같은 옷을 입는 관행을 택하는 이유도 여기에 있습니다. 사소한 결정을 자동화함으로써 중요한 결정에 쓸 에너지를 아끼려는 것입니다. 그러나 모든 선택을 없애는 것이 능사는 아니며, 어떤 선택은 그 자체로 삶의 활력을 제공하기도 합니다. 핵심은 선택을 완전히 제거하는 것이 아니라 무엇에 에너지를 쓸지 의식적으로 배분하는 데 있습니다.",
    body_en: "The number of decisions we must make in a day is far greater than we imagine. From what to wear in the morning to what to eat in the evening, decision-making is constantly consumed even without our awareness. Psychologists have explained this consumption through the concept of decision fatigue. According to this view, which treats willpower as a finite resource that depletes, the quality of judgment inevitably declines as the day wears on. In fact, the finding that judges' parole decisions are more lenient in the morning than in the afternoon has been cited as a representative case supporting this concept. Of course, debate over how to interpret this study still continues in academia. Nevertheless, the implication that reducing trivial choices can be a strategy for protecting the quality of important judgments is widely accepted. This is also why some entrepreneurs adopt the practice of wearing the same clothes every day. By automating trivial decisions, they aim to save energy for important ones. But eliminating all choice is not the answer either, since some choices themselves provide vitality to life. The key lies not in removing choice entirely but in consciously allocating where energy is spent.",
    questions: [
      { question_en: "What does the parole-decision study suggest?", options: ["Judges are inherently unfair","Judgment quality can decline as the day wears on","Willpower is unlimited","Morning decisions are always wrong"], answerIndex: 1 },
      { question_en: "Why do some entrepreneurs wear the same clothes daily?", options: ["To save money","To save decision energy for important choices","To follow a company policy","To appear humble"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "감사의 계산법",
    title_en: "The arithmetic of gratitude",
    body_kr: "감사는 순수한 감정처럼 보이지만 그 이면에는 은밀한 계산이 작동할 때가 많습니다. 선물이나 호의를 받았을 때 느끼는 감사가 순수한 기쁨인지, 아니면 갚아야 한다는 부담의 다른 이름인지는 생각만큼 명확하지 않습니다. 인류학자들은 오래전부터 선물 교환이 대가 없는 행위처럼 보여도 실제로는 정교한 호혜의 규범 위에서 작동한다고 지적해 왔습니다. 지나치게 큰 선물을 받았을 때 사람들이 오히려 불편함을 느끼는 이유도 여기에 있습니다. 갚을 수 없는 크기의 호의는 감사보다 부채감을 남기기 때문입니다. 이러한 계산은 관계의 권력 구조와도 무관하지 않습니다. 대가를 바라지 않는다고 말하는 호의조차 은연중에 상대의 복종이나 충성을 기대하는 경우가 있습니다. 그렇다고 모든 감사를 계산으로 환원하는 것은 지나친 냉소입니다. 진정한 감사는 갚음을 전제하지 않고도 존재할 수 있으며, 이는 대개 권력 차이가 크지 않은 관계에서 더 순수하게 나타납니다. 결국 감사의 질을 가늠하는 기준은 감정의 크기가 아니라 그 감정이 부담 없이 표현될 수 있는 관계의 조건입니다.",
    body_en: "Gratitude looks like a pure emotion, but a covert calculation often operates beneath it. Whether the gratitude felt upon receiving a gift or favor is pure joy or another name for the burden of having to repay is not as clear as it seems. Anthropologists have long pointed out that gift exchange, even when it looks like an act with no expectation of return, actually operates on an elaborate norm of reciprocity. This is also why people feel uncomfortable upon receiving an excessively large gift. A favor too large to repay leaves behind a sense of debt rather than gratitude. This calculation is not unrelated to the power structure of a relationship either. Even a favor said to expect nothing in return sometimes implicitly expects the other's submission or loyalty. That said, reducing all gratitude to calculation is excessive cynicism. Genuine gratitude can exist without presupposing repayment, and this tends to appear more purely in relationships where the power gap is not large. In the end, the standard for gauging the quality of gratitude is not the size of the emotion but the condition of the relationship that allows it to be expressed without burden.",
    questions: [
      { question_en: "Why do people feel uncomfortable receiving an excessively large gift?", options: ["It is illegal in most places","It is against etiquette","It leaves a sense of debt rather than gratitude","It always signals romantic interest"], answerIndex: 2 },
      { question_en: "Where does genuine, unburdened gratitude tend to appear more purely?", options: ["In anonymous transactions","In relationships where the power gap is not large","In relationships with strict hierarchy","In business contracts"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "이기심의 재평가",
    title_en: "Reassessing selfishness",
    body_kr: "이기심은 오랫동안 도덕적으로 경계해야 할 대상으로 취급되어 왔습니다. 그러나 경제학과 진화 생물학은 이기심에 대해 훨씬 복잡한 그림을 제시합니다. 애덤 스미스는 개인이 자신의 이익을 추구하는 과정이 의도치 않게 사회 전체의 이익으로 이어질 수 있음을 지적했습니다. 이는 이기심을 옹호한 것이 아니라 이기심이 작동하는 구조적 조건을 설명한 것입니다. 시장이 투명하고 경쟁이 공정할 때 개인의 이익 추구는 자원의 효율적 배분으로 이어질 수 있습니다. 그러나 그 조건이 무너지면 같은 이기심은 독점과 착취로 귀결됩니다. 진화 생물학 역시 순수한 이타심이란 존재하지 않으며 모든 협력은 결국 유전자의 생존 전략이라는 관점을 제시해 왔습니다. 이 관점은 냉소적으로 들리지만 협력의 진화적 기원을 설명하는 데는 유용합니다. 중요한 것은 동기의 순수성을 따지는 것보다 이기심이 사회에 이로운 방향으로 작동하도록 제도를 설계하는 일입니다. 이기심을 도덕적으로 비난하는 데 그친다면 그 힘을 건설적으로 활용할 기회를 놓치게 됩니다. 결국 이기심은 억압할 대상이 아니라 방향을 설계해야 할 힘입니다.",
    body_en: "Selfishness has long been treated as something to be morally guarded against. Economics and evolutionary biology, however, offer a far more complex picture of it. Adam Smith pointed out that the process of individuals pursuing their own interest can unintentionally lead to the benefit of society as a whole. This was not an endorsement of selfishness but an explanation of the structural conditions under which selfishness operates. When markets are transparent and competition is fair, the pursuit of individual interest can lead to efficient allocation of resources. But when those conditions collapse, the same selfishness results in monopoly and exploitation. Evolutionary biology has likewise offered the view that pure altruism does not exist and that all cooperation is ultimately a gene's survival strategy. This view sounds cynical but is useful for explaining the evolutionary origin of cooperation. What matters more than questioning the purity of motive is designing institutions so that selfishness operates in a direction beneficial to society. Stopping at moral condemnation of selfishness forfeits the chance to put that force to constructive use. In the end, selfishness is not something to suppress but a force whose direction must be designed.",
    questions: [
      { question_en: "What did Adam Smith point out about self-interest?", options: ["It is unrelated to markets","It should be morally condemned","It can unintentionally benefit society under the right conditions","It always leads to monopoly"], answerIndex: 2 },
      { question_en: "What does the writer say matters more than judging motive purity?", options: ["Praising altruism publicly","Banning self-interest","Designing institutions to direct selfishness beneficially","Ignoring economic theory"], answerIndex: 2 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "사생활의 경계",
    title_en: "The boundaries of privacy",
    body_kr: "사생활은 오랫동안 물리적 공간의 문제로 이해되어 왔습니다. 문을 닫으면 그 안의 일은 타인의 시선에서 벗어난다는 전제가 그것입니다. 그러나 데이터가 삶의 모든 흔적을 기록하는 시대에 이 전제는 더 이상 유효하지 않습니다. 우리가 어디를 가고 무엇을 검색하고 누구와 연락하는지는 물리적 문과 무관하게 축적됩니다. 문제는 이러한 정보가 개별적으로는 사소해 보여도 결합되었을 때 매우 구체적인 초상을 만들어 낸다는 점입니다. 위치 정보와 검색 기록만으로도 건강 상태나 인간관계를 상당히 정확하게 추정할 수 있습니다. 이 때문에 현대적 사생활 논의는 감출 것이 있는지 없는지의 문제에서 벗어나야 합니다. 감출 것이 없다는 이유로 감시를 감수해야 한다는 논리는 사생활을 개인의 결백을 증명하는 도구로 축소시킵니다. 사생활은 결백의 문제가 아니라 정보에 대한 통제권의 문제입니다. 누가 나에 대한 정보를 언제 어떤 목적으로 사용하는지 스스로 결정할 수 있는 권한이 핵심입니다. 결국 사생활 보호는 무언가를 숨기는 기술이 아니라 자기 정보에 대한 주권을 지키는 문제로 재정의되어야 합니다.",
    body_en: "Privacy has long been understood as a matter of physical space. The premise was that what happens behind a closed door escapes others' view. But in an age when data records every trace of life, this premise no longer holds. Where we go, what we search for, and whom we contact accumulate regardless of any physical door. The problem is that such information, however trivial it looks individually, produces a highly specific portrait when combined. Location data and search history alone can quite accurately estimate a person's health status or relationships. For this reason, contemporary discussions of privacy must move beyond the question of whether one has something to hide. The logic that surveillance must be accepted because one has nothing to hide reduces privacy to a tool for proving personal innocence. Privacy is not a matter of innocence but a matter of control over information. What matters most is the authority to decide for oneself who uses information about oneself, when, and for what purpose. In the end, privacy protection must be redefined not as the technique of hiding something but as the matter of defending sovereignty over one's own information.",
    questions: [
      { question_en: "What does combining seemingly trivial data points produce?", options: ["Legal immunity","Only marketing noise","Nothing significant","A highly specific portrait of a person"], answerIndex: 3 },
      { question_en: "How does the writer redefine privacy?", options: ["As physical isolation","As the ability to hide wrongdoing","As a purely legal category","As sovereignty over one's own information"], answerIndex: 3 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "도덕적 운",
    title_en: "Moral luck",
    body_kr: "같은 부주의로 운전을 했더라도 한 사람은 무사히 귀가하고 다른 사람은 보행자를 치어 사망에 이르게 할 수 있습니다. 두 사람의 행위는 동일했지만 결과는 하늘과 땅 차이입니다. 철학에서는 이러한 현상을 도덕적 운이라는 개념으로 다루어 왔습니다. 우리의 도덕적 평가가 순전히 행위자의 의도와 노력만이 아니라 통제할 수 없는 우연의 결과에도 좌우된다는 역설을 가리키는 말입니다. 전통적인 윤리 이론은 도덕적 책임이 오직 행위자가 통제할 수 있는 것에만 근거해야 한다고 주장해 왔습니다. 그러나 실제 법과 여론은 결과의 차이에 따라 명백히 다른 책임을 묻습니다. 사망 사고를 낸 운전자는 아무 일도 없었던 운전자보다 훨씬 무거운 처벌을 받습니다. 이러한 불일치는 우리의 직관과 원칙 사이의 간극을 드러냅니다. 일부 철학자는 이 간극이 도덕적 판단의 결함이 아니라 인간이 결과에 대해 느끼는 책임의 본질적인 부분이라고 주장합니다. 결과를 완전히 배제한 도덕 평가는 오히려 비현실적이라는 것입니다. 도덕적 운의 문제는 명쾌한 해결책보다 우리가 내리는 판단의 한계를 겸허하게 인정하도록 요구합니다.",
    body_en: "Two people can drive with the same degree of carelessness, yet one arrives home safely while the other strikes and kills a pedestrian. Their actions were identical, but the outcomes are worlds apart. Philosophy has treated this phenomenon through the concept of moral luck. The term points to the paradox that our moral evaluation is shaped not purely by an agent's intention and effort but also by the outcome of chance beyond their control. Traditional ethical theory has argued that moral responsibility should rest only on what the agent can control. In reality, however, law and public opinion clearly assign different responsibility depending on the difference in outcome. A driver who causes a fatal accident receives a far heavier punishment than a driver to whom nothing happened. This inconsistency reveals a gap between our intuitions and our principles. Some philosophers argue that this gap is not a flaw in moral judgment but an essential part of the responsibility humans feel toward outcomes. A moral evaluation that entirely excludes outcomes would be unrealistic. The problem of moral luck demands, rather than a neat solution, humble recognition of the limits of the judgments we make.",
    questions: [
      { question_en: "What paradox does moral luck describe?", options: ["All moral judgments are equally valid","Moral evaluation is shaped by outcomes beyond an agent's control","Intentions never matter","Luck determines legal guilt entirely"], answerIndex: 1 },
      { question_en: "What does traditional ethical theory argue responsibility should rest on?", options: ["What the agent can control","Legal precedent","The final outcome only","Public opinion"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "기억의 재구성",
    title_en: "The reconstruction of memory",
    body_kr: "기억은 과거를 그대로 보관하는 저장고가 아니라 회상할 때마다 새로 조립되는 구성물에 가깝습니다. 인지심리학의 여러 실험은 사후에 제공된 정보가 원래의 기억에 스며들어 진술을 바꾼다는 사실을 보여 주었습니다. 이는 목격자 증언의 신뢰성에 관한 법적 논의로 이어졌습니다. 기억의 생생함이 곧 정확성을 보장하지는 않는다는 점은 이제 상식에 가깝습니다.",
    body_en: "Memory is not a warehouse that preserves the past intact but is closer to a construct reassembled each time it is recalled. Numerous experiments in cognitive psychology have shown that information supplied afterward seeps into the original memory and alters testimony. This has led to legal debate about the reliability of eyewitness testimony. That the vividness of a memory does not guarantee its accuracy is now close to common sense.",
    questions: [
      { question_en: "How is memory characterized in the passage?", options: ["As a construct reassembled at each recall", "As a permanent archive of events", "As a purely emotional response", "As an unconscious reflex"], answerIndex: 0 },
      { question_en: "What legal debate did the findings prompt?", options: ["The reliability of eyewitness testimony", "The length of criminal sentences", "The use of forensic DNA", "The right to remain silent"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "번역의 불가능성",
    title_en: "The impossibility of translation",
    body_kr: "번역은 두 언어 사이의 단순한 치환이 아니라 서로 다른 세계관을 조율하는 작업입니다. 어떤 낱말은 그것을 낳은 문화적 맥락을 벗어나는 순간 의미의 일부를 잃어버립니다. 그럼에도 번역이 무의미하다고 말할 수는 없습니다. 완전한 등가가 불가능하다는 자각이야말로 더 정교한 번역을 가능하게 하는 출발점이기 때문입니다.",
    body_en: "Translation is not a simple substitution between two languages but the work of reconciling different worldviews. Certain words lose part of their meaning the moment they leave the cultural context that produced them. Even so, one cannot say translation is meaningless. The very awareness that perfect equivalence is impossible is the starting point that makes more refined translation possible.",
    questions: [
      { question_en: "What does the passage say translation really involves?", options: ["Reconciling different worldviews", "Matching grammar rules precisely", "Preserving sentence length", "Simplifying difficult words"], answerIndex: 0 },
      { question_en: "What makes more refined translation possible?", options: ["Awareness that perfect equivalence is impossible", "Access to larger dictionaries", "Translating only modern texts", "Working in teams of two"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "역사 서술의 관점",
    title_en: "Perspective in historical writing",
    body_kr: "역사는 지나간 사실의 목록이 아니라 무엇을 기록하고 무엇을 생략할지 선택하는 과정의 산물입니다. 사료 자체가 이미 특정 계층의 시선으로 남겨진 것이기에 완전한 객관성은 애초에 성립하기 어렵습니다. 그렇다고 모든 서술이 동등하게 타당하다는 상대주의로 흐르는 것은 위험합니다. 사료의 검증과 해석의 투명성이 역사학을 지탱하는 최소한의 규율입니다.",
    body_en: "History is not a list of past facts but the product of a process of choosing what to record and what to omit. Because historical sources themselves were left behind through the gaze of particular classes, complete objectivity is difficult to establish from the outset. That said, drifting into a relativism where all accounts are equally valid is dangerous. Verification of sources and transparency of interpretation are the minimum discipline sustaining historical study.",
    questions: [
      { question_en: "Why is complete objectivity hard to achieve?", options: ["Sources reflect the gaze of particular classes", "Historians rarely agree on dates", "Most records have been destroyed", "Languages change over time"], answerIndex: 0 },
      { question_en: "What does the writer call dangerous?", options: ["Relativism treating all accounts as equally valid", "Verifying sources too strictly", "Studying unpopular periods", "Relying on written records"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "상관과 인과 사이",
    title_en: "Between correlation and causation",
    body_kr: "두 변수가 함께 움직인다는 관찰은 그 자체로 인과를 입증하지 못합니다. 그럼에도 언론과 일상의 논쟁에서는 상관관계가 곧 원인으로 번역되는 일이 빈번합니다. 여기에는 제3의 변수가 두 현상을 동시에 끌어올리는 구조가 숨어 있을 수 있습니다. 표본의 선택 자체가 결과를 결정해 버리는 경우도 흔합니다. 생존한 사례만 관찰하고 규칙을 도출하면 결론은 필연적으로 왜곡됩니다. 이러한 오류를 통제하기 위해 고안된 것이 무작위 배정 실험입니다. 다만 사회 현상의 상당수는 윤리적 이유로 실험 설계가 불가능합니다. 따라서 연구자는 자연 실험이나 도구 변수를 통해 인과의 근사치를 추정합니다. 통계를 읽는 능력이란 결국 숫자를 믿는 것이 아니라 그 숫자가 만들어진 과정을 따져 묻는 태도입니다.",
    body_en: "The observation that two variables move together does not by itself establish causation. Even so, in journalism and everyday argument, correlation is frequently translated into cause. A structure may be hidden here in which a third variable raises both phenomena at once. It is also common for the selection of the sample itself to determine the result. If we observe only the cases that survived and derive a rule, the conclusion is inevitably distorted. The randomized controlled trial was devised to control for such errors. However, for a great many social phenomena, experimental design is impossible for ethical reasons. Researchers therefore estimate an approximation of causality through natural experiments or instrumental variables. The ability to read statistics is ultimately not a matter of trusting numbers but an attitude of interrogating the process by which those numbers were produced.",
    questions: [
      { question_en: "What may hide behind a correlation?", options: ["A third variable raising both", "A measurement error", "A translation mistake", "An outdated sample"], answerIndex: 0 },
      { question_en: "Why is experimental design often impossible?", options: ["For ethical reasons", "Because of cost", "Because samples are too large", "Because data is private"], answerIndex: 0 },
      { question_en: "How does the writer define statistical literacy?", options: ["Interrogating how the numbers were produced", "Memorizing formulas", "Trusting peer-reviewed data", "Preferring large samples"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "전문가에 대한 불신",
    title_en: "Distrust of expertise",
    body_kr: "전문가의 판단이 예전만큼 무조건적인 권위를 갖지 못한다는 진단은 이제 익숙합니다. 이러한 변화를 무지의 확산으로만 설명하는 것은 지나치게 단순한 접근입니다. 실제로 전문가 집단이 예측에 실패하거나 이해관계에 얽힌 사례가 축적되어 왔기 때문입니다. 불확실성을 솔직하게 드러내지 않은 소통 방식도 신뢰를 갉아먹었습니다. 확신에 찬 발언이 나중에 번복될 때 대중은 전문성 자체를 의심하게 됩니다. 반면 어떤 영역에서는 축적된 지식을 대체할 수 있는 것이 존재하지 않습니다. 문제는 권위를 되돌리는 것이 아니라 검증 가능한 신뢰를 다시 구축하는 데 있습니다. 근거와 한계를 함께 제시하는 태도가 그 출발점이 됩니다. 확실성을 약속하지 않는 전문가가 오히려 더 신뢰받는 역설이 여기서 성립합니다.",
    body_en: "The diagnosis that expert judgment no longer carries the unconditional authority it once did is by now familiar. Explaining this change solely as the spread of ignorance is far too simple an approach. That is because cases in which expert communities failed to predict or were entangled in interests have accumulated. Ways of communicating that did not honestly disclose uncertainty have also eaten away at trust. When confident statements are later reversed, the public comes to doubt expertise itself. In some domains, on the other hand, nothing exists that can replace accumulated knowledge. The problem lies not in restoring authority but in rebuilding verifiable trust. An attitude of presenting evidence together with its limits becomes the starting point. Here the paradox holds that an expert who promises no certainty is trusted more.",
    questions: [
      { question_en: "Why does the writer reject the 'spread of ignorance' explanation?", options: ["Experts have failed or been entangled in interests", "The public is better educated", "Media coverage improved", "Experts are more numerous"], answerIndex: 0 },
      { question_en: "What paradox is described?", options: ["An expert who promises no certainty is trusted more", "Ignorance increases with information", "Authority grows when questioned", "Uncertainty reduces error"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "표준어와 방언",
    title_en: "Standard language and dialect",
    body_kr: "표준어는 언어적 우월성에 근거한 개념이 아니라 행정적 필요에서 선택된 규범입니다. 그럼에도 표준어를 쓰지 않는 화자는 종종 교육 수준이나 세련됨과 연결되어 평가받습니다. 언어에 대한 판단이 실은 화자 집단에 대한 판단으로 작동하는 셈입니다. 방언은 결핍된 형태가 아니라 자체의 문법과 음운 체계를 갖춘 완결된 언어 변이입니다. 언어학이 오래전부터 강조해 온 이 사실은 대중적 인식에 잘 반영되지 않습니다. 미디어에서 방언이 유머나 향토성의 기호로만 소비되는 관행도 여기에 기여합니다. 표준어 교육의 필요성 자체를 부정할 이유는 없습니다. 다만 표준을 익히는 일이 자신의 말을 부끄러워하는 과정이 되어서는 안 됩니다. 다중 언어 능력으로 이해할 때 방언 화자는 결핍이 아니라 자산을 지닌 사람입니다.",
    body_en: "A standard language is not a concept grounded in linguistic superiority but a norm chosen out of administrative necessity. Even so, speakers who do not use the standard are often judged in connection with education level or sophistication. In effect, judgments about language operate as judgments about groups of speakers. A dialect is not a deficient form but a complete linguistic variety with its own grammar and phonological system. This fact, long emphasized by linguistics, is poorly reflected in popular perception. The practice of consuming dialect in the media only as a marker of humor or rustic color contributes to this. There is no reason to deny the need for standard language education itself. Still, learning the standard must not become a process of being ashamed of one's own speech. Understood as multilingual competence, a dialect speaker is someone with an asset rather than a deficiency.",
    questions: [
      { question_en: "What is a standard language, per the passage?", options: ["A norm chosen from administrative necessity", "The most logical variety", "The oldest form of a language", "A literary invention"], answerIndex: 0 },
      { question_en: "How does the media contribute to the problem?", options: ["It consumes dialect as humor or rustic color", "It bans dialect entirely", "It over-represents dialects", "It mistranslates dialect"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "건축과 집단 기억",
    title_en: "Architecture and collective memory",
    body_kr: "도시의 건물은 기능적 구조물인 동시에 공동체의 기억이 축적되는 매체입니다. 어떤 건축물을 남기고 어떤 것을 철거할지는 언제나 해석의 문제를 동반합니다. 특히 식민지 시기나 권위주의 시대의 유산은 격렬한 논쟁의 대상이 됩니다. 보존을 주장하는 쪽은 불편한 과거일수록 기록으로 남겨야 한다고 말합니다. 철거를 요구하는 쪽은 그 공간이 여전히 상징 권력을 행사한다고 반박합니다. 두 입장 모두 기억을 통제하려 한다는 점에서는 다르지 않습니다. 최근에는 원형을 남기되 해설을 덧붙여 맥락을 재구성하는 방식이 선호되고 있습니다. 건물이 스스로 의미를 말하지 않는다는 사실을 전제로 삼는 접근입니다. 기억의 문제는 무엇을 남기느냐만큼 어떻게 읽게 할 것이냐의 문제이기 때문입니다.",
    body_en: "A city's buildings are functional structures and at the same time media in which a community's memory accumulates. Which structures to keep and which to demolish always brings with it a problem of interpretation. Legacies of the colonial period or of authoritarian eras in particular become objects of fierce debate. Those who argue for preservation say that the more uncomfortable the past, the more it must be kept as a record. Those demanding demolition counter that such spaces still exercise symbolic power. Both positions are alike in that each seeks to control memory. Recently, an approach of keeping the original while adding interpretive commentary to reconstruct the context has been preferred. It is an approach premised on the fact that a building does not state its own meaning. That is because the question of memory is as much about how we make it read as about what we keep.",
    questions: [
      { question_en: "What do both sides of the debate share?", options: ["Each seeks to control memory", "Each favors demolition", "Each rejects commentary", "Each ignores architecture"], answerIndex: 0 },
      { question_en: "What premise underlies the preferred approach?", options: ["A building does not state its own meaning", "Old buildings are unsafe", "Records are more reliable", "Context is unknowable"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "음모론이 자라는 자리",
    title_en: "Where conspiracy theories grow",
    body_kr: "음모론을 단순히 비합리적인 사고의 산물로 규정하면 그 지속성을 설명하기 어렵습니다. 실제로 음모론은 대개 설명되지 않은 사건의 공백에서 자라납니다. 공식 발표가 불투명하거나 뒤늦게 번복될 때 대안적 서사의 수요가 발생합니다. 여기에 과거에 실제로 은폐가 있었다는 경험이 더해지면 의심은 합리적인 태도처럼 보이게 됩니다. 음모론의 구조적 특징은 반증을 흡수한다는 데 있습니다. 반박 증거가 제시되면 그 증거를 은폐의 일부로 편입시키기 때문입니다. 따라서 사실 확인만 반복하는 대응은 효과가 제한적입니다. 더 중요한 것은 신뢰할 만한 정보를 적시에 투명하게 제공하는 제도적 역량입니다. 공백을 남기지 않는 설명이 최선의 예방책인 셈입니다.",
    body_en: "If we define conspiracy theories simply as products of irrational thought, their persistence becomes hard to explain. In reality, conspiracy theories mostly grow in the gaps left by unexplained events. When official announcements are opaque or are belatedly reversed, demand for an alternative narrative arises. Add to that the experience that cover-ups genuinely occurred in the past, and suspicion comes to look like a reasonable attitude. The structural feature of a conspiracy theory is that it absorbs disconfirmation. When contrary evidence is presented, that evidence is incorporated as part of the cover-up. Responses that merely repeat fact-checking therefore have limited effect. What matters more is the institutional capacity to provide trustworthy information transparently and in good time. An explanation that leaves no gap is, in effect, the best prevention.",
    questions: [
      { question_en: "Where do conspiracy theories mostly grow?", options: ["In gaps left by unexplained events", "In closed communities", "Among the poorly educated", "In wartime only"], answerIndex: 0 },
      { question_en: "What is their structural feature?", options: ["They absorb disconfirming evidence", "They rely on single sources", "They avoid specifics", "They fade quickly"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "예술 시장의 가격",
    title_en: "Prices in the art market",
    body_kr: "예술 작품의 가격은 제작 원가나 노동 시간과 거의 상관없이 형성됩니다. 대체 불가능한 단일 재화라는 성격이 일반적인 수요 공급 곡선을 왜곡하기 때문입니다. 여기에 소수의 평론가와 갤러리, 경매사가 평가의 권위를 나누어 가집니다. 어떤 작가가 어느 기관에 전시되었는가 하는 이력이 가격의 핵심 근거가 됩니다. 즉 가치는 발견되는 것이 아니라 상당 부분 제도적으로 구성됩니다. 투자 자산으로서의 성격이 강해지면서 이런 경향은 더욱 뚜렷해졌습니다. 가격의 상승 자체가 작품의 중요성을 입증하는 순환 논리가 작동하기도 합니다. 그렇다고 시장의 판단을 전부 허구로 치부할 수는 없습니다. 다만 가격표를 미학적 평가로 착각하지 않는 분별은 반드시 필요합니다.",
    body_en: "The price of an artwork is formed almost independently of production cost or labor time. That is because its character as a non-substitutable, singular good distorts the ordinary supply and demand curve. On top of this, a small number of critics, galleries, and auction houses share the authority of evaluation. Which institution has exhibited a given artist becomes a central basis for price. In other words, value is not discovered so much as institutionally constructed. As the character of art as an investment asset has strengthened, this tendency has become more pronounced. A circular logic sometimes operates in which the rise in price itself proves the work's importance. That said, we cannot dismiss the market's judgment as entirely fictitious. Still, the discernment not to mistake a price tag for an aesthetic evaluation is indispensable.",
    questions: [
      { question_en: "Why is the ordinary supply curve distorted?", options: ["Artworks are non-substitutable singular goods", "Buyers are anonymous", "Supply is unlimited", "Costs are hidden"], answerIndex: 0 },
      { question_en: "What circular logic is described?", options: ["Rising price itself proves importance", "Critics follow auction results", "Artists price their own work", "Museums buy what they exhibit"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "의미와 즐거움의 차이",
    title_en: "The difference between meaning and pleasure",
    body_kr: "어떤 순간은 즐거웠지만 시간이 지나면 별다른 흔적을 남기지 않습니다. 반면 어떤 순간은 힘들었음에도 오래도록 마음에 남아 삶의 좌표가 됩니다. 심리학자들은 이 차이를 쾌락과 의미의 구분으로 설명해 왔습니다. 쾌락은 즉각적인 만족을 주지만 소비되는 즉시 사라지는 경향이 있습니다. 반면 의미는 당장의 감정과 무관하게 자신이 더 큰 이야기의 일부라는 감각에서 비롯됩니다. 아이를 키우는 일이나 낯선 이를 돕는 일이 흔히 즐겁지 않으면서도 의미 있게 느껴지는 이유가 여기에 있습니다. 흥미로운 점은 의미를 좇는 삶이 반드시 더 행복한 것은 아니라는 연구 결과입니다. 오히려 의미를 추구하는 과정에는 불안과 부담이 동반되는 경우가 많습니다. 그럼에도 사람들은 쾌락만 있는 삶보다 의미가 있는 삶을 선택하는 경향을 보입니다. 이는 인간이 순간의 감정 상태만이 아니라 자신의 서사 전체를 평가하는 존재이기 때문일 것입니다. 결국 좋은 삶이란 즐거움의 총합이 아니라 자신이 이해할 수 있는 이야기를 얼마나 갖고 있는가의 문제인지도 모릅니다.",
    body_en: "Some moments are pleasant but leave hardly any trace once time has passed. Other moments, though difficult, stay with us for a long time and become a coordinate for our lives. Psychologists have explained this difference through the distinction between pleasure and meaning. Pleasure brings immediate satisfaction but tends to vanish the instant it is consumed. Meaning, by contrast, arises from a sense of being part of a larger story, regardless of one's immediate feelings. This is why raising a child or helping a stranger often feels meaningful even when it is not enjoyable. An interesting finding is that a life devoted to pursuing meaning is not necessarily a happier one. In fact, the process of pursuing meaning is often accompanied by anxiety and burden. Even so, people tend to choose a life with meaning over a life with pleasure alone. This is likely because humans evaluate not just their momentary emotional state but their narrative as a whole. In the end, a good life may be a matter not of the sum of pleasures but of how much of a story one can understand about oneself.",
    questions: [
      { question_en: "How is pleasure characterized in contrast to meaning?", options: ["It tends to vanish as soon as it is consumed", "It always produces anxiety", "It lasts longer than meaning", "It cannot be measured"], answerIndex: 0 },
      { question_en: "What did research find about a life devoted to pursuing meaning?", options: ["It is always more enjoyable", "It is not necessarily happier and often carries anxiety and burden", "It guarantees success", "It requires no effort"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "잊혀짐에 대한 두려움",
    title_en: "The fear of being forgotten",
    body_kr: "죽음보다 잊혀짐을 더 두려워하는 사람들이 있습니다. 자신이 사라진다는 사실보다 자신의 흔적조차 남지 않는다는 상상이 더 견디기 힘든 것입니다. 이러한 두려움은 인류가 기념비와 기록을 남기려는 오래된 충동과 무관하지 않습니다. 비석에 이름을 새기고 자서전을 쓰고 유산을 남기려는 시도들은 모두 기억되고자 하는 욕구의 다른 얼굴입니다. 그러나 기억은 본질적으로 유한한 자원입니다. 아무리 위대한 인물이라도 몇 세대가 지나면 이름만 남고 구체적인 삶은 흐려집니다. 결국 모든 인간은 언젠가 완전히 잊히는 운명을 피할 수 없습니다. 이 사실을 직시하면 두려움은 오히려 다른 질문으로 바뀝니다. 기억되는 기간의 길이가 아니라 지금 이 순간 누군가에게 실질적인 영향을 미쳤는가가 중요해지는 것입니다. 한 사람의 친절이 다른 사람의 태도로 이어지고 그것이 또 다른 사람에게 전해질 때, 이름은 사라져도 그 영향은 형체를 바꾸며 이어집니다. 결국 잊히지 않으려는 싸움보다 지금 여기서 남길 수 있는 흔적에 집중하는 태도가 두려움을 다스리는 더 현실적인 방법입니다.",
    body_en: "There are people who fear being forgotten more than they fear death. The fantasy that not even a trace of oneself will remain is harder to bear than the fact that one will disappear. This fear is not unrelated to humanity's old impulse to leave monuments and records behind. Carving one's name into a headstone, writing a memoir, and trying to leave a legacy are all different faces of the same desire to be remembered. But memory is, by its nature, a finite resource. No matter how great a figure, after a few generations only the name remains while the concrete details of the life blur. In the end, every human is unable to escape the fate of one day being completely forgotten. Facing this fact turns the fear into a different question instead. What matters is not the length of time one is remembered but whether one had a real effect on someone in this very moment. When one person's kindness carries over into another's attitude and is passed on again to someone else, the influence continues in a changed form even after the name is gone. In the end, focusing on the trace one can leave here and now is a more realistic way of managing the fear than fighting not to be forgotten.",
    questions: [
      { question_en: "What do monuments, memoirs, and legacies represent, per the passage?", options: ["Different faces of the desire to be remembered", "Legal obligations", "Signs of vanity only", "A rejection of mortality"], answerIndex: 0 },
      { question_en: "What does the writer say matters more than the length of being remembered?", options: ["Whether one had a real effect on someone in the present moment", "How many monuments exist", "How famous one becomes", "How long one lives"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "아름다움은 발견되는가 구성되는가",
    title_en: "Is beauty discovered or constructed",
    body_kr: "노을이나 얼굴, 선율 앞에서 우리는 아름다움이 대상 안에 원래 있었고 자신은 그것을 발견했을 뿐이라고 느낍니다. 그러나 미학의 오랜 논쟁은 이 직관에 의문을 던져 왔습니다. 같은 대상이 문화와 시대에 따라 전혀 다르게 평가된다는 사실은 아름다움이 대상의 고유한 속성만은 아닐 가능성을 시사합니다. 한 시대에 이상적으로 여겨졌던 신체 비율이 다른 시대에는 평범하거나 낯설게 여겨지는 사례가 대표적입니다. 이는 아름다움이 감상자의 훈련된 지각과 기대를 통해 상당 부분 구성된다는 관점을 뒷받침합니다. 그렇다고 아름다움이 순전히 자의적인 합의에 불과하다고 결론짓는 것도 성급합니다. 대칭이나 비례처럼 문화를 넘어 반복적으로 선호되는 특징들이 분명 존재하기 때문입니다. 아마도 진실은 그 중간 어디쯤에 있을 것입니다. 지각의 하드웨어는 진화가 물려준 것이지만 그 하드웨어가 무엇에 반응하도록 조율되는가는 문화와 경험이 채워 넣습니다. 아름다움을 느끼는 순간은 그래서 순수한 발견도 순수한 발명도 아닌, 타고난 감각과 길들여진 시선이 만나는 지점입니다. 결국 무엇이 아름다운가를 묻는 일은 대상이 아니라 우리 자신의 형성 과정을 되묻는 일이기도 합니다.",
    body_en: "Standing before a sunset, a face, or a melody, we feel that beauty was already there in the object and that we merely discovered it. But a long-running debate in aesthetics has questioned this intuition. The fact that the same object is evaluated in entirely different ways across cultures and eras suggests that beauty may not be solely an inherent property of the object. A representative example is a body proportion once considered ideal in one era being seen as ordinary or unfamiliar in another. This supports the view that beauty is constructed to a considerable degree through the viewer's trained perception and expectation. That said, it would also be hasty to conclude that beauty is nothing but purely arbitrary consensus. This is because features such as symmetry and proportion are clearly preferred repeatedly across cultures. The truth is probably somewhere in between. The hardware of perception is inherited from evolution, but what that hardware is tuned to respond to is filled in by culture and experience. The moment of feeling beauty is therefore neither pure discovery nor pure invention, but the point where an innate sense meets a cultivated way of seeing. In the end, asking what is beautiful is also a way of asking about our own process of formation rather than about the object.",
    questions: [
      { question_en: "What does the varying evaluation of the same object across cultures suggest?", options: ["Beauty may not be solely an inherent property of the object", "Beauty is a fixed universal constant", "Only trained critics can perceive beauty", "Beauty has no biological basis at all"], answerIndex: 0 },
      { question_en: "What does the writer conclude beauty is?", options: ["The point where an innate sense meets a cultivated way of seeing", "A purely arbitrary social agreement", "An entirely fixed biological reflex", "A concept with no cultural component"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "확신의 윤리",
    title_en: "The ethics of certainty",
    body_kr: "자신의 판단에 확신을 갖는 것은 유능함의 표시로 여겨지곤 합니다. 그러나 확신의 크기가 근거의 크기와 항상 비례하지는 않습니다. 오히려 아는 것이 적을수록 확신은 커지는 역설적인 경향이 여러 연구에서 확인되어 왔습니다. 이러한 현상은 자신의 무지를 가늠할 능력조차 지식에 의존한다는 사실에서 비롯됩니다. 문제는 확신에 찬 태도가 사회적으로 더 신뢰받는 경향이 있다는 점입니다. 청중은 망설이는 전문가보다 단호한 비전문가를 더 믿는 경우가 많습니다. 이는 지적으로 정직한 사람일수록 불리한 처지에 놓이는 역설적인 구조를 만듭니다. 그렇다고 모든 것에 회의적인 태도를 취하는 것이 대안이 되지는 못합니다. 근거가 충분한 사안까지 불필요하게 유보하는 태도는 또 다른 형태의 왜곡입니다. 결국 지적으로 정직하다는 것은 확신의 정도를 근거의 정도에 최대한 맞추려는 부단한 조정의 노력을 의미합니다. 확신은 성격의 문제가 아니라 자신이 알고 있는 것과 모르고 있는 것의 경계를 정직하게 그리는 훈련의 문제입니다.",
    body_en: "Having confidence in one's own judgment is often taken as a sign of competence. But the size of one's confidence is not always proportional to the size of one's evidence. In fact, several studies have confirmed the paradoxical tendency that the less one knows, the greater one's confidence tends to be. This phenomenon arises from the fact that even the ability to gauge one's own ignorance depends on knowledge. The problem is that a confident attitude tends to be trusted more socially. Audiences often believe a decisive non-expert more than a hesitant expert. This creates the paradoxical structure in which the more intellectually honest a person is, the more disadvantaged their position becomes. That does not mean adopting a skeptical attitude toward everything is the alternative. Withholding judgment unnecessarily even on matters with sufficient evidence is a distortion of another kind. In the end, being intellectually honest means the constant effort of adjusting the degree of one's confidence to match the degree of one's evidence as closely as possible. Certainty is not a matter of personality but a matter of training oneself to honestly draw the line between what one knows and what one does not know.",
    questions: [
      { question_en: "What paradoxical tendency have studies confirmed?", options: ["The less one knows, the greater one's confidence tends to be", "Confidence always matches evidence", "Experts are always more confident than non-experts", "Confidence decreases with age"], answerIndex: 0 },
      { question_en: "What does intellectual honesty mean, per the passage?", options: ["Being skeptical of everything at all times", "Continually adjusting one's confidence to match the evidence", "Always deferring to experts", "Never expressing an opinion"], answerIndex: 1 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "관심과 사랑",
    title_en: "Attention and love",
    body_kr: "사랑을 감정의 강도로 측정하려는 시도는 흔하지만 정작 사랑을 가장 선명하게 드러내는 것은 강렬한 순간이 아니라 지속적인 관심일 때가 많습니다. 누군가를 사랑한다는 것은 그 사람의 사소한 변화를 알아차리는 능력과 밀접하게 연결되어 있습니다. 표정의 미묘한 차이나 평소와 다른 말투는 세심하게 주의를 기울이는 사람에게만 보입니다. 철학자 시몬 베유는 관심을 기울이는 행위 자체가 가장 희귀하고 순수한 형태의 관대함이라고 말한 바 있습니다. 이는 관심이 상대에게 무언가를 주는 행위가 아니라 자신을 잠시 비우고 상대를 있는 그대로 받아들이는 행위이기 때문입니다. 반대로 무관심은 반드시 냉담한 얼굴을 하고 나타나지 않습니다. 함께 있으면서도 다른 곳에 정신이 팔려 있는 상태, 상대의 말을 들으면서 다음 할 말을 준비하는 상태가 훨씬 흔한 무관심의 형태입니다. 사랑이 식었다고 느끼는 많은 순간은 사실 감정이 사라진 것이 아니라 관심이 다른 곳으로 옮겨 간 것일 수 있습니다. 관계를 회복하는 일은 그래서 거창한 다짐보다 다시 상대를 주의 깊게 바라보는 훈련에서 시작됩니다. 결국 사랑은 느끼는 것이라기보다 지속적으로 기울이는 관심의 다른 이름인지도 모릅니다.",
    body_en: "Attempts to measure love by the intensity of feeling are common, but what most clearly reveals love is often not an intense moment but sustained attention. Loving someone is closely tied to the ability to notice their small changes. A subtle difference in expression or a tone of voice unlike usual is visible only to someone paying careful attention. The philosopher Simone Weil once said that the act of paying attention itself is the rarest and purest form of generosity. This is because attention is not an act of giving the other person something but an act of briefly emptying oneself and accepting the other as they are. Indifference, by contrast, does not necessarily wear a cold face. Being physically present while one's mind is elsewhere, or listening to the other while preparing what to say next, is a far more common form of indifference. Many moments when love feels like it has cooled may not actually be the disappearance of feeling but the shifting of attention elsewhere. Restoring a relationship therefore begins not with a grand resolution but with the practice of once again looking carefully at the other person. In the end, love may be less something one feels than another name for the attention one continues to pay.",
    questions: [
      { question_en: "What did philosopher Simone Weil say about attention?", options: ["It is the rarest and purest form of generosity", "It is a burden to be avoided", "It is unrelated to love", "It requires formal training"], answerIndex: 0 },
      { question_en: "What is described as a common form of inattentiveness?", options: ["Being present but preparing what to say next instead of listening", "Speaking too loudly", "Avoiding conversation entirely", "Only communicating in writing"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "언어로 다 담을 수 없는 진실",
    title_en: "Truths that resist being fully articulated",
    body_kr: "슬픔이나 경외감처럼 강렬한 경험을 언어로 옮기려 할 때 우리는 종종 무력감을 느낍니다. 아무리 정교한 문장을 골라도 경험의 어떤 부분은 항상 빠져나가는 것 같습니다. 이는 표현력의 부족이라기보다 언어라는 도구의 근본적인 한계일 수 있습니다. 언어는 연속적이고 통합된 경험을 개별 낱말이라는 이산적인 단위로 쪼개어 전달하는 체계입니다. 그 과정에서 경험을 이루던 미묘한 결들은 필연적으로 다듬어지고 손실됩니다. 시와 음악, 회화 같은 예술 형식이 존재하는 이유도 여기에 있는지 모릅니다. 산문적 언어가 놓치는 것을 리듬과 이미지, 침묵의 배치로 대신 전달하려는 시도인 셈입니다. 흥미로운 점은 이러한 한계를 인정하는 것이 소통을 포기하는 일이 아니라는 것입니다. 오히려 다 말할 수 없다는 사실을 함께 아는 두 사람 사이에서 더 깊은 이해가 오갈 때가 있습니다. 말해지지 않은 여백을 상대가 스스로 채우도록 남겨 두는 것도 소통의 한 방식이기 때문입니다. 결국 가장 깊은 진실 앞에서 언어가 할 수 있는 최선은 완전히 담아내는 것이 아니라 그 너머를 가리키는 것인지도 모릅니다.",
    body_en: "When we try to render an intense experience such as sorrow or awe into language, we often feel powerless. No matter how refined the sentence we choose, some part of the experience always seems to slip away. This may be not a lack of expressive skill but a fundamental limit of language as a tool. Language is a system that conveys a continuous, integrated experience by breaking it into discrete units called words. In that process, the subtle textures that made up the experience are inevitably smoothed over and lost. This may be the very reason art forms such as poetry, music, and painting exist. They are attempts to convey, through rhythm, image, and the arrangement of silence, what prosaic language misses. What is interesting is that acknowledging this limit is not giving up on communication. Rather, deeper understanding can pass between two people who both know that not everything can be said. Leaving an unspoken gap for the other person to fill in on their own is also a way of communicating. In the end, faced with the deepest truths, the best language can do may not be to fully capture them but to point beyond them.",
    questions: [
      { question_en: "Why do experiences like sorrow or awe resist full articulation, per the passage?", options: ["Language breaks continuous experience into discrete word-units, losing subtle textures", "People lack sufficient vocabulary", "Emotions cannot be discussed in any culture", "Writers are generally untrained"], answerIndex: 0 },
      { question_en: "What is suggested as a reason art forms like poetry and music exist?", options: ["To convey through rhythm, image, and silence what prose misses", "To replace ordinary conversation entirely", "To simplify complex emotions for children", "To document historical events accurately"], answerIndex: 0 },
    ],
  },
  {
    level: "C2",
    genre: "essay",
    title_kr: "무너질 것을 알면서 짓는 일",
    title_en: "Building something you know will be undone",
    body_kr: "모래성을 쌓는 아이는 파도가 그것을 무너뜨릴 것을 이미 알고 있습니다. 그럼에도 아이는 조금의 망설임도 없이 정성껏 성을 쌓습니다. 어른의 눈에는 이 행위가 비합리적으로 보일 수 있습니다. 결과가 남지 않을 일에 시간과 노력을 들이는 것은 낭비처럼 여겨지기 때문입니다. 그러나 정원을 가꾸거나 하루치의 요리를 준비하는 어른의 행위 역시 본질적으로 다르지 않습니다. 정원은 계절이 바뀌면 다시 손봐야 하고 음식은 먹히는 순간 사라집니다. 이러한 일들의 가치는 결과물의 영속성이 아니라 그것을 만드는 과정 자체에 있습니다. 무너질 것을 알면서도 정성을 다하는 태도는 결과에 대한 집착에서 벗어난 행위이기도 합니다. 오히려 영원히 남을 것이라는 기대가 있을 때 우리는 과정을 소홀히 하기 쉽습니다. 언젠가 사라진다는 사실을 받아들이면 지금 이 순간의 완성도에 더 집중하게 됩니다. 결국 무상함은 행위를 무의미하게 만드는 조건이 아니라 지금 여기에 온전히 머무르게 하는 조건일 수 있습니다.",
    body_en: "A child building a sandcastle already knows that the waves will knock it down. Even so, the child builds it with full care and without the slightest hesitation. To an adult's eyes, this behavior can look irrational, since spending time and effort on something that will leave no lasting result seems like a waste. But an adult tending a garden or preparing a day's meal is not fundamentally different. A garden must be tended again once the season changes, and food disappears the moment it is eaten. The value of such activities lies not in the permanence of the result but in the process of making itself. Putting in full care while knowing something will collapse is also an act freed from attachment to the outcome. In fact, when we expect something to last forever, we tend to neglect the process. Accepting that something will one day disappear leads us to focus more on the completeness of this present moment. In the end, impermanence may not be a condition that makes an act meaningless but a condition that lets us stay fully present here and now.",
    questions: [
      { question_en: "What does the passage say makes gardening or cooking essentially similar to building a sandcastle?", options: ["Both are impermanent, and their value lies in the process rather than the result's permanence", "Both require professional training", "Both are done purely out of obligation", "Both are considered wasteful by most adults"], answerIndex: 0 },
      { question_en: "What does accepting impermanence lead to, per the passage?", options: ["Neglecting the process entirely", "Greater focus on the completeness of the present moment", "A loss of motivation", "Avoiding creative activities altogether"], answerIndex: 1 },
    ],
  },
];
